### PR TITLE
ARROW-14778: [C++] Round mean of decimal types after division

### PR DESCRIPTION
**Pull request by lidavidm**
With this, the mean and hash_mean aggregate kernels will accumulate sums and perform the final division with decimal values, but the final division will be rounded (half towards infinity) based on the remainder after division instead of rounding towards zero (truncating).

### CODE REVIEW

**Comment by jonkeane** [comment]
You mention this in the Jira, but could we add in the cast back to decimal proactively? What I'm seeing in postgres (haven't tried others yet) is it "just" blows up the precision on the decimal but does still return a decimal with `AVG`.

If someone has a decimal already it seems odd that it would return a double when a decimal result is possible (it's not quite like division of integers where you have to return something with more precision than an integer there). Even of (for now? until someone complains?) we cast back to the same decimal precision as the input, I think that would be more natural for what operations on decimals like this behave like elsewhere.

```
postgres=# create table df (dec decimal(3, 2));
                insert into df (dec) values (0.01);
                insert into df (dec) values (0.02);
                insert into df (dec) values (0.02);
                insert into df (dec) values (0.02);
CREATE TABLE
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
postgres=# alter table df add column flt float;
                insert into df (flt) values (0.01);
                insert into df (flt) values (0.02);
                insert into df (flt) values (0.02);
                insert into df (flt) values (0.02);
ALTER TABLE
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
postgres=# select pg_typeof(dec), pg_typeof(flt) from df;
 pg_typeof |    pg_typeof     
-----------+------------------
 numeric   | double precision
 numeric   | double precision
 numeric   | double precision
 numeric   | double precision
 numeric   | double precision
 numeric   | double precision
 numeric   | double precision
 numeric   | double precision
(8 rows)

postgres=# select AVG(dec), pg_typeof(AVG(dec)), AVG(flt), pg_typeof(AVG(flt)) from df;
          avg           | pg_typeof |  avg   |    pg_typeof     
------------------------+-----------+--------+------------------
 0.01750000000000000000 | numeric   | 0.0175 | double precision
```

**Comment by lidavidm** [comment]
Just for reference it seems DuckDB actually outputs a double:

```
D create table df (dec decimal(3, 2), flt float);
D insert info df (dec, flt) values (0.01, 0.01);
Error: Parser Error: syntax error at or near "info"
LINE 1: insert info df (dec, flt) values (0.01, 0.01);
               ^
D insert into df (dec, flt) values (0.01, 0.01);
D insert into df (dec, flt) values (0.02, 0.02);
D insert into df (dec, flt) values (0.02, 0.02);
D insert into df (dec, flt) values (0.02, 0.02);
D select typeof(dec), typeof(flt) from df;
┌──────────────┬─────────────┐
│ typeof(dec)  │ typeof(flt) │
├──────────────┼─────────────┤
│ DECIMAL(3,2) │ FLOAT       │
│ DECIMAL(3,2) │ FLOAT       │
│ DECIMAL(3,2) │ FLOAT       │
│ DECIMAL(3,2) │ FLOAT       │
└──────────────┴─────────────┘
D select avg(dec), avg(flt), typeof(avg(dec)), typeof(avg(flt)) from df;
┌──────────┬─────────────────────┬──────────────────┬──────────────────┐
│ avg(dec) │      avg(flt)       │ typeof(avg(dec)) │ typeof(avg(flt)) │
├──────────┼─────────────────────┼──────────────────┼──────────────────┤
│ 0.0175   │ 0.01749999960884452 │ DOUBLE           │ DOUBLE           │
└──────────┴─────────────────────┴──────────────────┴──────────────────┘
```

We can cast back to Decimal, but how should we round/truncate the result?

**Comment by jonkeane** [comment]
_nods_ yeah. We can ask them what their philosophy is there. I'm not sure I know the history. 

As for round/trunc I would vote for rounding to whatever the precision is (if we truncate we'll get the same result we have now IIRC). Or if it's easier to do the postgres blow up precision to max, that would be ok by me

**Comment by pitrou** [comment]
I would say that if the summation is done as decimal, then the result should probably be decimal as well. People use decimals when floats are not adequate, AFAIK.

**Comment by lidavidm** [comment]
Reverted the original change and instead added a rounding step directly on the decimal result.

**Comment by jonkeane** [comment]
This looks good to me. Someone with more C++ should probably look at the code in more detail, though

**Review by cyb70289 — APPROVED** [review]
+1. PR title and message should be updated.

**Comment by lidavidm** [comment]
Thanks for the reminder, I've updated the title/description.

**Comment by cyb70289** [comment]
> Thanks for the reminder, I've updated the title/description.

`round half toward infinity`?

**Comment by lidavidm** [comment]
> > Thanks for the reminder, I've updated the title/description.
> 
> `round half toward infinity`?

Ah yup, that's right, thanks.

**Pull request closed without merging**
