### PR TITLE
[Release] Verify 5.0.0-RC0 [WIP]

### PR DESCRIPTION
**Pull request by kszucs**

### CODE REVIEW

**Comment by kszucs** [comment]
@github-actions crossbow submit --group verify-rc-source --param release=5.0.0 --param rc=0

**Comment by kszucs** [comment]
@github-actions crossbow submit --group verify-rc-source --param release=5.0.0 --param rc=0

**Comment by kszucs** [comment]
I assume the integration verification tasks fail due to an environmental issue, similarly to the ruby one (need to properly set `PKG_CONFIG_PATH`).

Integration tests pass for both in case of conda-integration build and local verification on macOS.

**Comment by kou** [comment]
For the Ruby one: Arrow Flight is built with system OpenSSL but Arrow Flight GLib tried to link against conda's OpenSSL and it's failed. I don't know why this was caused...

**Comment by kou** [comment]
> For the Ruby one: Arrow Flight is built with system OpenSSL but Arrow Flight GLib tried to link against conda's OpenSSL and it's failed. I don't know why this was occurred...

Wrong. This verification scripts build Arrow C++ with bundled gRPC. The bundled gRPC uses system shared OpenSSL but `libarrow_flight.so` doesn't link system shared OpenSSL.

The following patch will solve this:

```diff
diff --git a/cpp/cmake_modules/ThirdpartyToolchain.cmake b/cpp/cmake_modules/ThirdpartyToolchain.cmake
index a79d4fd7b..56c37000b 100644
--- a/cpp/cmake_modules/ThirdpartyToolchain.cmake
+++ b/cpp/cmake_modules/ThirdpartyToolchain.cmake
@@ -2543,6 +2543,9 @@ macro(build_grpc)
       c-ares::cares
       ZLIB::ZLIB
       Threads::Threads)
+  if(ARROW_OPENSSL_USE_SHARED)
+    list(APPEND GRPC_LINK_LIBRARIES OpenSSL::SSL)
+  endif()
   set_target_properties(gRPC::grpc
                         PROPERTIES IMPORTED_LOCATION "${GRPC_STATIC_LIBRARY_GRPC}"
                                    INTERFACE_INCLUDE_DIRECTORIES "${GRPC_INCLUDE_DIR}"
```

I confirmed this on my local Ubuntu 20.04 Docker container.

**Comment by kou** [comment]
#10773

**Comment by kszucs** [comment]
Closing in favor of RC1

**Pull request closed without merging**
