### PR TITLE
ARROW-2810: [Plasma] Remove flatbuffers from public API

### PR DESCRIPTION
**Pull request by pcmoritz**

### CODE REVIEW

**Comment by pitrou** [comment]
Can you create a JIRA for this? Thanks.

**Comment by wesm** [comment]
I'd already created one, just added

**Comment by wesm** [comment]
@pcmoritz there's another usage of the wire protocol in plasma.h; I removed the include in https://github.com/apache/arrow/pull/2282/commits/d6c149784514f6d8d920df5b4c5db1f9902ff1e4. I'll let you decide how to handle it

**Comment by pcmoritz** [comment]
appveyor passed on my fork: https://ci.appveyor.com/project/pcmoritz/arrow/build/1.0.826, so feel free to merge

**Review by wesm — APPROVED** [review]
+1. Thanks @pcmoritz!

**Pull request closed without merging**
