### PR TITLE
ARROW-4302: [C++] Add OpenSSL to C++ build toolchain

### PR DESCRIPTION
**Pull request by majetideepak**

### CODE REVIEW

**Review by xhochy — COMMENTED** [review]
+1, LGTM

The failures were unrelated so I retriggered them.

**Comment by kszucs** [comment]
There are multiple places this change should have been incorporated in: 
- explicit conda dependencies in CI (rather than depending on openssl as a transitive dependency)
- packaging tasks: wheels, conda, linux (most of them are failing now)
- integration / docker-compose tests

Sadly We don't have instant feedback from these builds, so We should be a bit more careful with introducing new (default) dependencies.

**Comment by majetideepak** [comment]
@kszucs Apologies for breaking those. Can you help with making the changes needed there? Alternatively, we can disable the support by setting `PARQUET_BUILD_ENCRYPTION` to `OFF` by default.

**Comment by kszucs** [comment]
@majetideepak it is not anyone's fault, currently We only get notified after merging to master, which is the root cause - the tooling still needs a lot of development to provide quick and more visible feedback.

Certainly your proposal would be the best and incrementally opt-in for `PARQUET_BUILD_ENCRYPTION` in the packaging builds.

**Comment by wesm** [comment]
@kszucs what's our timeline for having our build cluster operational to assist with these issues? I'm hoping that we'll be able to kick off a packaging validation run when future toolchain changes come through

cc @nealrichardson

**Comment by kszucs** [comment]
@wesm that depends on how We want to run the packaging tasks:
- via ursabot, but We doesn't have windows or mac workers yet - requires to reimplement the packaging tasks
- via crossbow (triggered by ursabot) which requires additional scheduling logic to notify ursabot about the finished crossbow tasks (additionally crossbow must be installable to host alongside ursabot's buildmaster)

**Comment by wesm** [comment]
Well, either way, the bottom line is that the project's productivity is suffering because these tasks are not automated. It is not important to me how it is accomplished as long as it is clear and easy

**Comment by kszucs** [comment]
@wesm currently I'm implementing the second approach without the notification, so We'll be able to submit crossbow tasks and get a link for the branches.

**Pull request merged**
