### PR TITLE
[CI] Testing ursabot status push

### PR DESCRIPTION
**Pull request by kszucs**

### CODE REVIEW

**Comment by kszucs** [comment]
@ursabot --help

**Comment by xhochy** [comment]
@ursabot build

**Comment by kszucs** [comment]
@ursabot build

**Comment by wesm** [comment]
Seems like it's working! =)

**Comment by kszucs** [comment]
@ursabot build

**Comment by kszucs** [comment]
Ehh, just testing that :)

**Comment by kszucs** [comment]
@ursabot build

**Comment by kszucs** [comment]
The requests are recorded:

image

**Comment by kszucs** [comment]
And the statuses are updated.

**Pull request closed without merging**
