### PR TITLE
GH-38024: [Java][FlightRPC] Expose appMetadata through JDBC ResultSet

### LINKED ISSUE #38024: [Java][flight-sql-jdbc] Expose app_metadata for FlightInfo through JDBC interfaces
### Describe the enhancement requested

As a follow up to #38022, we'll want to add a way to expose the metadata through the JDBC interface implementations. The FlightInfo metadata could be exposed in the following classes:
- PreparedStatement
- ResultSet
- ResultSetMetaData

### Component(s)

Java

### PR DESCRIPTION
**Pull request by aiguofer**
FlightInfo can now contain appMetadata. This PR exposes that metadata through the JDBC interface through `ArrowFlightJdbcFlightStreamResultSet.getAppMetadata`.
* Closes: #38024

### CODE REVIEW

**Comment by lidavidm** [comment]
CC @jduo 

One question: we distribute shaded driver JARs, so people will have to reference a shaded name. It may be better to define a non-shaded interface that people can cast to?

**Comment by jduo** [comment]
> CC @jduo
> 
> One question: we distribute shaded driver JARs, so people will have to reference a shaded name. It may be better to define a non-shaded interface that people can cast to?

I agree. Also, it would be good to have a non-shaded build target to reduce the binary size for users that aren't concerned about dependency collisions (for example, embedding the driver into a stack that they have full control of the dependencies).

**Comment by lidavidm** [comment]
> it would be good to have a non-shaded build target to reduce the binary size for users that aren't concerned about dependency collisions

[flight-sql-jdbc-core](https://github.com/apache/arrow/tree/main/java/flight/flight-sql-jdbc-core) should do that and is distributed: https://central.sonatype.com/artifact/org.apache.arrow/flight-sql-jdbc-core/overview

**Comment by aiguofer** [comment]
Interesting. I seem to be able to cast it just fine when using the shaded jar. That being said, I agree having some sort of `ArrowFlightSqlResultSet` or some more relatable name would be better.

**Comment by lidavidm** [comment]
Ah, yes, the shaded JAR should work fine - but you have to 'peek' into the shaded JAR and use the shaded name, right? It would be best to provide a 'normal' name for people to reference instead of some odd shaded thing

**Comment by lidavidm** [comment]
That said if you want to defer that we can just focus on this change here

**Review by lidavidm — APPROVED** [review]

**Comment by lidavidm** [comment]
Alright, we can add the interface if someone complains about having to use the mangled name.

**Comment by aiguofer** [comment]
@lidavidm hey! sorry just got back from a long vacation last night. I think this is fine for now.

I was thinking at some point we might want to expose a way to get the Arrow batches directly as well, and at that point we can reconsider the interface/class name.

**Comment by lidavidm** [comment]
Ah, sounds good.

And yes, some way to convert a ResultSet to an Arrow or ADBC interface would be a perfect way to slowly introduce Arrow to a JDBC-based application.

**Pull request merged**
