### PR TITLE
GH-34629: [Go] Fix transpose_ints to work on riscv64-freebsd

### LINKED ISSUE #34629: [Go] Doesn't build on riscv64-freebsd
### Describe the bug, including details regarding any error messages, version, and platform.

While building a project (`github.com/brimdata/zed/cmd/zed`) on riscv64-freebsd, we encountered a build failure in this project:

```
# github.com/apache/arrow/go/v11/internal/utils
vendor/github.com/apache/arrow/go/v11/internal/utils/transpose_ints_def.go:76:4: undefined: TransposeInt8Int8
vendor/github.com/apache/arrow/go/v11/internal/utils/transpose_ints_def.go:78:4: undefined: TransposeInt8Int16
vendor/github.com/apache/arrow/go/v11/internal/utils/transpose_ints_def.go:80:4: undefined: TransposeInt8Int32
vendor/github.com/apache/arrow/go/v11/internal/utils/transpose_ints_def.go:82:4: undefined: TransposeInt8Int64
vendor/github.com/apache/arrow/go/v11/internal/utils/transpose_ints_def.go:84:4: undefined: TransposeInt8Uint8
vendor/github.com/apache/arrow/go/v11/internal/utils/transpose_ints_def.go:86:4: undefined: TransposeInt8Uint16
vendor/github.com/apache/arrow/go/v11/internal/utils/transpose_ints_def.go:88:4: undefined: TransposeInt8Uint32
vendor/github.com/apache/arrow/go/v11/internal/utils/transpose_ints_def.go:90:4: undefined: TransposeInt8Uint64
vendor/github.com/apache/arrow/go/v11/internal/utils/transpose_ints_def.go:95:4: undefined: TransposeInt16Int8
vendor/github.com/apache/arrow/go/v11/internal/utils/transpose_ints_def.go:97:4: undefined: TransposeInt16Int16
vendor/github.com/apache/arrow/go/v11/internal/utils/transpose_ints_def.go:97:4: too many errors
```

It appears that support code for riscv64 is missing.  Please add such code.

### Component(s)

Go

### PR DESCRIPTION
**Pull request by zeroshade**
### Rationale for this change
Protecting the Go arrow packages from failing on new architectures by ensuring the pure go implementation gets loaded for any architecture that isn't one of the explicit ones we have assembly for.

### What changes are included in this PR?
changing the go build constraint

* Closes: #34629

### CODE REVIEW

**Comment by zeroshade** [comment]
@clausecker Please try building this branch. I've only tested using go1.20 and `GOOS=freebsd GOARCH=riscv64 go build` as I don't have access to a riscv64 system. But with that I was able to reproduce the failing build you showed in the issue, and then use this fix to make it build successfully.

**Comment by clausecker** [comment]
Thanks, will check.  Is there are test suite or something I can run?

**Comment by zeroshade** [comment]
there are unit tests you can run via `go test`. You could also try running `ci/scripts/go_test.sh` if you like.

**Comment by clausecker** [comment]
Package `internal` now builds.  Others do not, largely because you depend on `modernc.org/sqlite` which is not available for this architecture.  A `go test ./internal/...` yielded:

```
# github.com/apache/arrow/go/v12/internal/utils
internal/utils/transpose_ints_noasm.go:20:1: invalid non-alphanumeric build constraint: ||
internal/utils/transpose_ints_noasm.go:20:1: invalid non-alphanumeric build constraint: (!amd64
internal/utils/transpose_ints_noasm.go:20:1: invalid non-alphanumeric build constraint: &&
internal/utils/transpose_ints_noasm.go:20:1: invalid non-alphanumeric build constraint: &&
internal/utils/transpose_ints_noasm.go:20:1: invalid non-alphanumeric build constraint: &&
internal/utils/transpose_ints_noasm.go:20:1: invalid non-alphanumeric build constraint: !ppc64le)
```

which is something you might want to look into, too.

Thank you for the fixes!

**Comment by zeroshade** [comment]
Thankfully `modernc.org/sqlite` is only used for the flight sql example package, so likely shouldn't affect most consumers.

For the issue with `non-alphanumeric build constraints` what version of Go were you using there? Since we intend for building against older versions of Go too, i'm guessing I need to modify the `+build` constraint since the syntax using `||` and `&&` in the build constraints was added in go 1.16 i think....

**Comment by zeroshade** [comment]
@clausecker I ran `go fix` on the whole directory there, can you try again and confirm you don't get that `invalid build constraint` error anymore?

**Comment by clausecker** [comment]
I can confirm.

**Pull request merged**
