### PR TITLE
ARROW-15382: [Java] fix SplitAndTransfer throws for (0,0) if vector empty

### PR DESCRIPTION
**Pull request by wzx140**

### CODE REVIEW

**Comment by wzx140** [comment]
@lidavidm Could you please review it? Really thanks!

**Comment by lidavidm** [comment]
@davisusanibar would you like to take a look here first?

**Review by lidavidm — APPROVED** [review]
Thanks. I think it would be good to have a test with a non-empty vector but transferring 0 length as well (also, trying a non-zero startIndex but with 0 length).

**Comment by pitrou** [comment]
@wzx140 Would you like to add another unit test as suggested by @lidavidm ?

**Comment by lidavidm** [comment]
@davisusanibar or @lwhite1 would you like to perhaps carry this over the finish line?

**Comment by lwhite1** [comment]
> Thanks. I think it would be good to have a test with (1) a non-empty vector but transferring 0 length as well (also, (2) trying a non-zero startIndex but with 0 length).

I created a test with a non-empty vector and transferring length 0, but it throws an exception when the allocator is closed `java.lang.IllegalStateException: Allocator[ROOT] closed with outstanding buffers allocated (1).`

The same test transferring length 1 passes.

**Review by lwhite1 — CHANGES_REQUESTED** [review]
As mentioned in earlier comment, this PR does not address situations where the source vector is non-empty, and the transfer length is 0.

**Comment by amol-** [comment]
Closing because it has been untouched for a while, in case it's still relevant feel free to reopen and move it forward 👍

**Comment by FiV0** [comment]
Hey, could this be reopened. This is still an issue in Arrow 15.0.2 and I run into it multiple times. Also happy to look into it if further work needs to be done.

**Pull request closed without merging**
