### PR TITLE
ARROW-3891: [Java] Remove Long.bitCount with simple bitmap operations

### PR DESCRIPTION
**Pull request by animeshtrivedi**
to check if a bit is set or not, there is no need to count
number of bits set in a long. A simple shift and bitwise AND
is sufficient (and faster!).

Signed-off-by: Animesh Trivedi <atrivedi@apache.org>

### CODE REVIEW

**Review by wesm — COMMENTED** [review]
LGTM. @siddharthteotia @jacques-n?

**Comment by fsaintjacques** [comment]
LGTM.

**Comment by jacques-n** [comment]
+1 lgtm

**Review by xhochy — APPROVED** [review]
+1, LGTM

**Pull request closed without merging**
