### PR TITLE
ARROW-18128: [Java][CI] Update timestamp of Java Nightlies X.Y.Z-SNAPSHOT folder

### PR DESCRIPTION
**Pull request by raulcd**

### CODE REVIEW

**Comment by kou** [comment]
I tried this locally but I noticed that there are no 2022-09-XX directories in https://nightlies.apache.org/arrow/java/org/apache/arrow/arrow-vector/ now.

It seems that https://github.com/apache/arrow/actions/runs/3298113920/jobs/5439805962 removes 2022-09-21 and https://github.com/apache/arrow/actions/runs/3303520952/jobs/5451532542 removes 2022-09-22.

It seems that the current prune implementation works well.
It seems that the current build repository implementation has a problem.

For example, 2022-10-01 https://github.com/apache/arrow/actions/runs/3164856433/jobs/5153450720 failed to build repository https://github.com/apache/arrow/actions/runs/3164856433/jobs/5153450720#step:11:28 (`ls: cannot access 'binaries/nightly-packaging-20***-10-01-0/java-jars': No such file or directory`) because java-jars nightly job failed https://lists.apache.org/thread/z8h8bbhjrzpxdlp5ko6sp1tv7bjnmosh .

**Comment by kou** [comment]
Ah, how about updating timestamp of the `X.Y.Z-SNAPSHOT` directory when we update artifacts under the `X.Y.Z-SNAPSHOT` directory?

```diff
diff --git a/.github/workflows/java_nightly.yml b/.github/workflows/java_nightly.yml
index b47306eec8..c9b9ba1d71 100644
--- a/.github/workflows/java_nightly.yml
+++ b/.github/workflows/java_nightly.yml
@@ -110,6 +110,7 @@ jobs:
           for LIBRARY in $(ls binaries/$PREFIX/java-jars | grep -E '.jar|.pom' | grep SNAPSHOT); do
             [[ $LIBRARY =~ $PATTERN_TO_GET_LIB_AND_VERSION ]]
             mkdir -p repo/org/apache/arrow/${BASH_REMATCH[1]}/${BASH_REMATCH[2]}
+            touch repo/org/apache/arrow/${BASH_REMATCH[1]}/${BASH_REMATCH[2]}
             mkdir -p repo/org/apache/arrow/${BASH_REMATCH[1]}/${DATE}
             # Copy twice to maintain a latest snapshot and some earlier versions
             cp binaries/$PREFIX/java-jars/$LIBRARY repo/org/apache/arrow/${BASH_REMATCH[1]}/${BASH_REMATCH[2]}
```

**Comment by raulcd** [comment]
Thanks @kou that makes sense. I've reverted the previous change and have applied the `touch` command to update the timestamp on those folders.

**Review by kou — APPROVED** [review]
+1

**Pull request merged**
