### PR TITLE
ARROW-3209: [C++] Rename libarrow_gpu to libarrow_cuda

### PR DESCRIPTION
**Pull request by pitrou**
Also rename the arrow::gpu namespace to arrow::cuda.

### CODE REVIEW

**Comment by pitrou** [comment]
I think the C glib side needs to be fixed, but I'm not sure how. @kou would you like to push something to this PR?

**Comment by wesm** [comment]
Ah, I forgot about the disruption that this would cause to the glib side, where there are also Linux packages. I think it's a good idea to leave open the possibility of GPU computing outside of CUDA

**Comment by kou** [comment]
I'll add some commits for C GLib, Ruby and Linux packages to this PR.

**Comment by kou** [comment]
It seems that `Cuda` in `arrow::cuda::Cuda*` is redundant.
Should we keep `Cuda` or remove `Cuda`?

**Comment by pitrou** [comment]
> It seems that Cuda in `arrow::cuda::Cuda*` is redundant. Should we keep Cuda or remove Cuda?

I'd keep it.

**Review by kou — APPROVED** [review]
OK.
+1 from me.

We can merge this when Linux packages are built on Travis CI:
https://github.com/kou/crossbow/branches/all?utf8=%E2%9C%93&query=build-53

**Comment by wesm** [comment]
Some of the Linux packages failed

**Comment by wesm** [comment]
Great, thanks @kou!

**Pull request closed without merging**
