### PR TITLE
ARROW-8757: [C++][Plasma] Write Plasma header in little-endian format

### PR DESCRIPTION
**Pull request by kiszk**
This PR writes and reads Plasma header (version, type, and length) in the big-endian format. It allows us to make it easy to interpret a header of Plasma data among different endian machines.

The current issue is to write Plasma header in native endian at [here](https://github.com/apache/arrow/blob/master/cpp/src/plasma/io.cc#L65-L71). It is not possible to know version, type, and length of a given Plasma file among different platforms. Feather V2 also uses little-endian for the header based on [the discussion](https://github.com/apache/arrow/pull/6777#discussion_r400770040). This PR uses little-endian by following this discussion.

### CODE REVIEW

**Review by kou — APPROVED** [review]
+1
The title should be "... in little-endian format" instead of "... in big-endian format"?

**Comment by kiszk** [comment]
Good catch. updated the title.

**Comment by nealrichardson** [comment]
@github-actions rebase

**Comment by nealrichardson** [comment]
Sorry, auto-rebase didn't work because there are changes to .github/workflows in master. IDK if the "C GLib & Ruby / AMD64 Windows MinGW 64 GLib & Ruby" failure is real or not, or if rebase would fix it, but that's what I was trying.

**Comment by kou** [comment]
Rerunning fixed the test failure.
I've merged this.
Sorry. I forgot to merge this.

**Pull request closed without merging**
