### PR TITLE
ARROW-8684: [Python] Workaround Cython type initialization bug

### PR DESCRIPTION
**Pull request by pitrou**
This should fix a crash on some macOS builds.

### CODE REVIEW

**Comment by pitrou** [comment]
@crossbow ursabot submit -g wheel

**Comment by pitrou** [comment]
@github-actions crossbow submit -g wheel

**Comment by pitrou** [comment]
@github-actions crossbow submit wheel

**Comment by kszucs** [comment]
@ursabot crossbow submit -g wheel

**Review by kszucs — APPROVED** [review]
I guess we need to merge it without tests :)
Thanks for fixing it!

**Pull request closed without merging**
