### PR TITLE
ARROW-251: Expose APIs for getting code and message of the status

### PR DESCRIPTION
**Pull request by jihoonson**

### CODE REVIEW

**Comment by jihoonson** [comment]
It looks like a test tries to allocate too large native memory. I'm investigating it.

**Comment by julienledem** [comment]
TLGTM. @wesm ?

**Comment by wesm** [comment]
@jihoonson can you add unit tests for these? See 

https://github.com/apache/kudu/blob/master/src/kudu/util/status-test.cc

as a possible starting point (this Status class originally came from the Kudu codebase)

**Comment by jihoonson** [comment]
I added some tests. I think it would be better to add remaining tests in a separate ticket.

**Comment by wesm** [comment]
Sounds good, thank you. +1

**Pull request closed without merging**
