### PR TITLE
ARROW-9043: [Go][FOLLOWUP] Move license file copy to correct location

### PR DESCRIPTION
**Pull request by wesm**
See https://github.com/apache/arrow/pull/7355#issuecomment-640584322

### CODE REVIEW

**Comment by wesm** [comment]
@jba can you please confirm this is correct. In the future a PR would be welcome

**Comment by jba** [comment]
Sorry, I could have easily made a PR, just didn't think of it.

This PR is not wrong, but it's unnecessary to rename the file (and I wouldn't do it, because it's confusing). What we need is, _either_ a `LICENSE.txt` in `go/arrow`, _or_ a `LICENSE` at top level. I think the former is the smaller change for you.

**Comment by kszucs** [comment]
To prevent any misunderstandings please confirm that renaming https://github.com/apache/arrow/blob/master/LICENSE.txt to `LICENSE` would resolve the issue. How can we test it?

**Comment by jba** [comment]
I believe it would resolve the issue, but it's not easy to test. 
I'll fork the repo, make the change, and get it onto `pkg.go.dev` to verify. I'll report back here.

**Comment by kszucs** [comment]
Thanks @jba!

**Comment by jba** [comment]
DO NOT SUBMIT.

Renaming the top-level LICENSE.txt to LICENSE will work as far as making the LICENSE file visible, but it won't matter because we don't yet recognize the OpenSSL license as granting us the permissions we need. I'm in discussions about that now and will reply here.

**Comment by wesm** [comment]
@kszucs can you take this over?

**Comment by kszucs** [comment]
Yes. We can go on either route, but it is still unclear to me whether we can test it automatically (I'm unfamiliar with go packaging). 

Based on the information @jba provided I'm happy to merge it, but if there is a way to maintain the packaging requirements of go we should have jiras for it - like creating nightly packages perhaps?

cc @sbinet

**Comment by jba** [comment]
There's no feasible way to test this, unfortunately. I verified both my suggested changes by forking the repo, making the edits, and running an internal tool to verify that they worked. The external alternative would be to `go get` the package at the latest release to inform the Go module proxy, wait a few minutes, then check for it on pkg.go.dev. That would be a complicated test to automate, and would almost certainly be flaky, with little benefit.

**Comment by kszucs** [comment]
Thanks @jba for the update. Merging it then.

**Review by kszucs — APPROVED** [review]

**Pull request closed without merging**
