### PR TITLE
[Rust] Fix unused variable in code example

### PR DESCRIPTION
**Pull request by Joey9801**

### CODE REVIEW

**Comment by Joey9801** [comment]
I'm not sure this fix is substantial enough that it really needs a JIRA ticket. Happy to make one and link it to this PR if I'm wrong about that though!

**Comment by alamb** [comment]
Thanks @Joey9801 ! This is great. I am not sure what happened (the force push of master for the 3.0 release perhaps made a mess). Can you please rebase it against master?

A JIRA ticket is part of the process for each thing merged however small. However, I can make one for tracking prior to merge if you don't get to it

https://github.com/apache/arrow/pull/9308/commits/3a380a4c4193c6683a71ba72dc31f8456bc661d5 looks great.

**Review by jorgecarleitao — APPROVED** [review]
@Joey9801 , thanks a lot for this PR. LGTM

Could you rebase against master to cleanup all the commits? (We had to rebase master, it is not your fault).

**Comment by alamb** [comment]
I have created a new PR with this change https://github.com/apache/arrow/pull/9459 rebased against master

**Comment by nevi-me** [comment]
Fixed in #9459

**Pull request closed without merging**
