### PR TITLE
ARROW-8036: [C++] Avoid gtest 1.10 deprecation warnings

### PR DESCRIPTION
**Pull request by pitrou**

### CODE REVIEW

**Comment by pitrou** [comment]
Looks like there's a problem with the gtest 1.10 conda-forge package on Windows (as usual?).
https://ci.appveyor.com/project/pitrou/arrow/builds/31348643

**Comment by pitrou** [comment]
Issue reported upstream: https://github.com/conda-forge/gtest-feedstock/issues/43

**Comment by pitrou** [comment]
+1, will merge if green

**Comment by pitrou** [comment]
AppVeyor: https://ci.appveyor.com/project/pitrou/arrow/builds/31426111

**Comment by wesm** [comment]
@pitrou is there a reference about the API change that made this work (TYPED_TEST_CASE -> TYPED_TEST_SUITE)?

**Comment by pitrou** [comment]
There's https://github.com/google/googletest/releases/tag/release-1.10.0

**Comment by wesm** [comment]
Aha well there we go, thanks =)

**Pull request closed without merging**
