### PR TITLE
ARROW-11321: [Rust][DataFusion] Fix DataFusion compilation error

### PR DESCRIPTION
**Pull request by Dandandan**
FYI @jorgecarleitao I think some change on master and maybe some parquet related changes caused a compilation error on master. This fixes the compilation error.

### CODE REVIEW

**Comment by jorgecarleitao** [comment]
This has an unrelated change on a submodule?

**Comment by Dandandan** [comment]
Yeah those submodules seems to cause some issues lately :/. Should be fixed now @jorgecarleitao

**Comment by jorgecarleitao** [comment]
cc @alamb

**Review by alamb — APPROVED** [review]
I think #9076 changed the API. Thanks @Dandandan

**Comment by alamb** [comment]
I ran this locally and it fixes the build for me. I plan to merge this in prior to CI finishing to get master back to green

**Comment by alamb** [comment]
For anyone else following along, the error this PR fixes looks like the following (from https://github.com/apache/arrow/runs/1729540155):

```
  Compiling arrow-flight v3.0.0-SNAPSHOT (/__w/arrow/arrow/rust/arrow-flight)
   Compiling tonic v0.3.1
   Compiling datafusion v3.0.0-SNAPSHOT (/__w/arrow/arrow/rust/datafusion)
error[E0061]: this function takes 2 arguments but 1 argument was supplied
   --> datafusion/src/physical_plan/parquet.rs:712:25
    |
712 |             data_buffer.resize(data_buffer.len() + data_size);
    |                         ^^^^^^ ----------------------------- supplied 1 argument
    |                         |
    |                         expected 2 arguments

error: aborting due to previous error
```

**Comment by alamb** [comment]
🚀

**Comment by jorgecarleitao** [comment]
Thanks a lot, @Dandandan and @alamb , and sorry for the mess 😞

**Comment by alamb** [comment]
No worries @jorgecarleitao  -- I think this was likely to happen given the backup of PRs waiting to go on to master :)

**Comment by Dandandan** [comment]
I am really excited for the changes w.r.t. performance in the merged PRs!

This will allow us to further improve some kernels :+1:

**Pull request closed without merging**
