### PR TITLE
ARROW-16732: [C++] Bump vendored version of nlohmann_json

### PR DESCRIPTION
**Pull request by raulcd**

### CODE REVIEW

**Comment by raulcd** [comment]
@github-actions crossbow submit -g cpp

**Comment by raulcd** [comment]
@github-actions crossbow submit -g cpp

**Comment by raulcd** [comment]
I've rebased master to test with the new version for RE2 too:
https://github.com/apache/arrow/pull/13570

**Review by pitrou — APPROVED** [review]
+1, thank you @raulcd

**Pull request merged**
