### PR TITLE
ARROW-10915: [Rust] README.md: set the Env vars as absolute dirs; several minor fixes.

### PR DESCRIPTION
**Pull request by mqy**
In rust/README.md,  both ARROW_TEST_DATA and PARQUET_TEST_DATA are set as relative path. The problem is: we MAY have to reset them back-and-forth across top and subdirectories – that's annoying. So, the obvious solution is: set the Env vars as absolute dirs.

This PR also contains several minor fixes to spelling and format!

### CODE REVIEW

**Comment by jorgecarleitao** [comment]
Doesn't this assume the existence of `realpath`? I can't find that on mac os, and I am not sure it exists on windows also.

**Comment by mqy** [comment]
> Doesn't this assume the existence of `realpath`? I can't find that on mac os, and I am not sure it exists on windows also.

Thanks, that's make sense. The bash on my macOS must have been replace by GNU bash 4. 
I'll fix them with $(cd ...; pwd)

**Comment by mqy** [comment]
Sorry, due to some strange problem (VsCode cache when do branch switch), I did some forced push.

**Review by jorgecarleitao — APPROVED** [review]
LGTM. Neat solution to the relative path issue.

**Review by andygrove — APPROVED** [review]

**Pull request closed without merging**
