### PR TITLE
ARROW-7254: [Java] BaseVariableWidthVector#setSafe appears to make value offsets inconsistent

### PR DESCRIPTION
**Pull request by liyafan82**
See the discussion in ARROW-7254

### CODE REVIEW

**Review by emkornfield — COMMENTED** [review]
It setvaluecount happens after set(abcd) is this fix still needed

**Comment by emkornfield** [comment]
OK, see comment on JIRA, I'm a little bit mixed on if we should patch this change as the pattern goes against what the documented usage should be.  That being said, since this is non-obvious it might be better to fix to avoid others getting mixed up with this as well.

**Comment by liyafan82** [comment]
> OK, see comment on JIRA, I'm a little bit mixed on if we should patch this change as the pattern goes against what the documented usage should be. That being said, since this is non-obvious it might be better to fix to avoid others getting mixed up with this as well.

There is no problem if we call setValueCount after manipulating the vector, as the setValueCount will call fillHoles, which brings the vector to a consistent state.

Strictly speaking, this is not consistent with the patten of the life cycle of a vector. This problem only exists for VariableWidthVectors.

**Review by lidavidm — APPROVED** [review]

**Comment by lidavidm** [comment]
Thank you @liyafan82 for investigating this!

**Pull request closed without merging**
