### PR TITLE
ARROW-8703: [R] schema$metadata should be properly typed

### PR DESCRIPTION
**Pull request by nealrichardson**

### CODE REVIEW

**Comment by nealrichardson** [comment]
@jorisvandenbossche could you give this a quick glance? https://github.com/apache/arrow/pull/7236/files#diff-4f1c8c5db1e5e55eab54a6f88138bfe1R322-R333 is the most concise view of the interface this adds.

**Comment by jorisvandenbossche** [comment]
That looks good to me. 
In Python, we don't allow editing the metadata in-place (there are methods to add or update it, but those return a new table / new schema), so in that sense we follow more how it is done on the C++ side, but I don't think it is a problem to update the pointer in place.

One question: if you do like `tab$metadata <- list(test = TRUE)`, I understand in the code how this change is propagated to the actual table, but if you do `tab$metadata$foo <- 42` (which updates the named list), how is that propagated to the metadata on the C++ level?

**Review by fsaintjacques — APPROVED** [review]
LGTM

**Comment by nealrichardson** [comment]
@jorisvandenbossche that part is a little magical. `tab$metadata$foo <- 42` essentially gets the list from `tab$metadata` anonymously, does `that$foo <- 42`, and then assigns `tab$metadata <- that`. So there's only one path to updating at the C++ level, replacing the whole metadata object.

**Pull request closed without merging**
