### PR TITLE
ARROW-9397: [R] Pass CC/CXX et al. to cmake when building libarrow in Linux build

### PR DESCRIPTION
**Pull request by nealrichardson**

### CODE REVIEW

**Comment by nealrichardson** [comment]
@github-actions crossbow submit *as-cran*

**Comment by nealrichardson** [comment]
FYI @jeroen

**Comment by jeroen** [comment]
You have a bug here because your version of `R_CMD_config` takes R from the PATH but that may not be the correct R. Some machines have many versions of R.

It may be safer to use e.g. `tools::Rcmd(c('config', 'CXX'), stdout=T)`

**Comment by nealrichardson** [comment]
Is there a way to get that config without shelling out at all?

**Comment by jeroen** [comment]
Not from the configure step I think.

These are all `make` variables so the native way to build embedded libs is to pass these down when invoking a sub-make, like so: https://github.com/rstudio/httpuv/blob/master/src/Makevars#L65-L70

**Comment by nealrichardson** [comment]
@github-actions crossbow submit *as-cran*

**Comment by nealrichardson** [comment]
@github-actions crossbow submit as-cran

**Comment by nealrichardson** [comment]
@github-actions crossbow submit *as-cran*

**Pull request closed without merging**
