### PR TITLE
[Website] Update Committer List

### PR DESCRIPTION
**Pull request by paddyhoran**

### CODE REVIEW

**Review by andygrove — APPROVED** [review]

**Review by kou — APPROVED** [review]
+1
Welcome!

**Comment by wesm** [comment]
This went in without an informative commit message, but the patch is pretty self-explanatory

https://github.com/apache/arrow/commit/d945e7f1115eb8c690ddcb3720197b4506ec112a

**Comment by paddyhoran** [comment]
Apologies @wesm. I was not considering the commit history on master.

**Comment by wesm** [comment]
Not a problem! When using the GitHub UI to merge one can enter a more informative commit message

**Pull request merged**
