### PR TITLE
ARROW-1219: [C++] Use Google C++ code formatting

### PR DESCRIPTION
**Pull request by wesm**
Our coding style guide has a ton of rules. I put up this patch to discuss since we don't have too many patches outstanding right now. This uses the exact Google style used in TensorFlow and other projects, but relaxes the column limit to 90 characters.

The main change is horizontal alignment in function signatures:

```diff
 void ValidateBasicStructArray(const StructArray* result,
-    const vector<uint8_t>& struct_is_valid, const vector<char>& list_values,
-    const vector<uint8_t>& list_is_valid, const vector<int>& list_lengths,
-    const vector<int>& list_offsets, const vector<int32_t>& int_values) {
+                              const vector<uint8_t>& struct_is_valid,
+                              const vector<char>& list_values,
+                              const vector<uint8_t>& list_is_valid,
+                              const vector<int>& list_lengths,
+                              const vector<int>& list_offsets,
+                              const vector<int32_t>& int_values) {
```

I find the paren-aligned version a bit more readable, but it's a matter of taste

### CODE REVIEW

**Comment by wesm** [comment]
@pcmoritz @robertnishihara @cpcloud @xhochy do you have any feelings on this? I think the Google style is more similar to what the Plasma codebase was prior to importing into Arrow.

**Comment by robertnishihara** [comment]
I like the change aesthetically, the simpler `clang-format`, and the consistency with other projects. However, I don't feel strongly about this.

**Comment by pcmoritz** [comment]
+1 for the change

**Comment by xhochy** [comment]
I'm open for everything as long as `ninja format` works. Another thing that bothers me more: Could we pin the clang-format version? I have different versions on different systems and everywhere I would be able to install 3.8 , 3.9 and 4.0 but am unsure which one we currently use and thus often have reformatting changes in unrelated code.

Also I would merge the other open C++ PRs first before doing any reformatting to avoid huge merge conflicts, esp https://github.com/apache/arrow/pull/797.

**Comment by wesm** [comment]
`ninja format` and `make format` work definitely. According to http://apt.llvm.org/ LLVM 3.9 is the "stable" version, but maybe this is a typo. I've been using that. I am happy to pin 4.0 as long as that is easy to obtain on both Linux and macOS. I just opened https://issues.apache.org/jira/browse/ARROW-1221 about this

It's not necessary to merge this right away. I can wait until https://github.com/apache/arrow/pull/797 and other PRs are merged and then do the reformat

**Comment by wesm** [comment]
Bombs away

**Pull request closed without merging**
