### PR TITLE
ARROW-10269: [Rust] Update to 2020-11-14 nightly

### PR DESCRIPTION
**Pull request by nevi-me**
This takes us from 2020-04-22 to 2020-11-14.
There have been a lot of clippy lints introduced since April, and an incompleteness feature warning about specialization (which causes CI to fail).

I have allowed almost all clippy lints in datafusion, as we have >150 warnings there.
I have made changes to fix arrow and parquet lints where I perceive them not to affect open PRs.

### CODE REVIEW

**Comment by nevi-me** [comment]
FYI @vertexclique

**Comment by jorgecarleitao** [comment]
Segfault on the coverage, outch :/

**Comment by nevi-me** [comment]
> Segfault on the coverage, outch :/

I want to look at whether we can use the new llvm-based coverage instead of tarpaulin

**Comment by nevi-me** [comment]
> Segfault on the coverage, outch :/

Found and fixed the problem. We were using an older cached version of `cargo-tarpaulin`, but the latest version has a bug; so I've forced us into using an older version, and left a reference to the GH issue.

We should be good to go @jorgecarleitao

**Review by jorgecarleitao — APPROVED** [review]
LGTM. Thanks a lot @nevi-me , cool fixes to the code also.

**Review by vertexclique — APPROVED** [review]
Thanks for this Neville!

**Comment by jorgecarleitao** [comment]
Do we wait for some of the PRs to be flushed, or do we merge this?

**Comment by nevi-me** [comment]
I don't see this being a big risk to open PRs (as some already have merge conflicts). We run 36 CI jobs for this, vs the normal 8; so maybe there's an efficiency argument in merging this sooner, instead of having to rebase later (which I don't mind doing).

**Review by alamb — COMMENTED** [review]
🎉  -- thank you @nevi-me 

FYI I filed https://issues.apache.org/jira/browse/ARROW-10597 to track enablign clippy lints in datafusion

**Comment by nevi-me** [comment]
@alamb thanks. A quick solution for many of the lints, is to run clippy-fix with -Z unstable-options, so that one doesn't manually fix them.

**Comment by alamb** [comment]
@nevi-me  check it out: https://github.com/apache/arrow/pull/8687 -- which I think enables clippy lint in all parts of the project

**Pull request closed without merging**
