### PR TITLE
ARROW-8799: [C++][Parquet] NestedListReader needs to handle empty item batches

### PR DESCRIPTION
**Pull request by bkietz**

### CODE REVIEW

**Comment by bkietz** [comment]
CI failure is a minio flake https://github.com/apache/arrow/pull/7181/checks?check_run_id=675715164#step:8:3095

**Comment by emkornfield** [comment]
@bkietz could you add a unit test?

**Comment by bkietz** [comment]
@emkornfield @wesm In adding a unit test I've become uncertain of the `ColumnReader` contract and whether my solution upholds it

- [ColumnReader::NextBatch's doccomment](https://github.com/apache/arrow/blob/6716bbd/cpp/src/parquet/arrow/reader.h#L254-L255) states that when no data remains null should be yielded (which I read as: a null ChunkedArray).
- Instead the tests [assert that the chunked array contain a single null chunk](https://github.com/apache/arrow/blob/6716bbd25ead03ad4774c8d1caa612a8f66e853c/cpp/src/parquet/arrow/arrow_reader_writer_test.cc#L502-L504)
- When reading into a dictionary `LeafReader` does neither of these and instead yields an empty `ChunkedArray` (for which `NestedListReader` on master is unprepared, causing ARROW-8799).

If modifying `NestedListReader` as I have here is unsatisfactory, I could change `TransferDictionary` to ensure `LeafReader` yields `ChunkedArray{nullptr}` when its out of data. What do you think?

**Review by wesm — APPROVED** [review]
+1 -- I think this is a band-aid solution until all these code can be deleted in favor of a complete nested data reading implementation. Just to confirm this fixes ARROW-8799 and so this is OK to merge?

**Comment by bkietz** [comment]
Confirmed, this resolves the issue

**Pull request closed without merging**
