### PR TITLE
ARROW-8520: [Developer] Use .asf.yaml to direct GitHub notifications to JIRA and mailing lists

### PR DESCRIPTION
**Pull request by wesm**
Context: INFRA-20149

Following instructions per https://s.apache.org/asfyaml-notify

### CODE REVIEW

**Comment by wesm** [comment]
I just requested the creation of github@

**Comment by wesm** [comment]
+1. This can only be "tested in production" so I'm merging this

**Comment by pitrou** [comment]
Wow, thank you for solving this.

**Comment by wesm** [comment]
Think I've fixed it now. There was a typo in the Confluence docs so the first iteration didn't work

**Pull request closed without merging**
