### PR TITLE
GH-35641: [CI][C++] Disable precompiled headers

### LINKED ISSUE #35641: [CI][C++] Bad compile/link times despite ccache
### Describe the bug, including details regarding any error messages, version, and platform.

Example here on the AMD64 Conda C++ build:
https://github.com/apache/arrow/actions/runs/5005430904/jobs/8969381538?pr=33634

```
=== ccache statistics before build
===
Cacheable calls:   284 / 894 (31.77%)
  Hits:             14 / 284 ( 4.93%)
    Direct:         14 /  14 (100.0%)
    Preprocessed:    0 /  14 ( 0.00%)
  Misses:          270 / 284 (95.07%)
Uncacheable calls: 610 / 894 (68.23%)
Local storage:
  Cache size (GB): 0.1 / 1.0 (11.35%)
  Hits:             14 / 284 ( 4.93%)
  Misses:          270 / 284 (95.07%)

[ ... CMake runs ... ]

real	27m46.563s
user	49m43.936s
sys	4m28.705s

===
=== ccache statistics after build
===
Cacheable calls:    568 / 1788 (31.77%)
  Hits:             298 /  568 (52.46%)
    Direct:         233 /  298 (78.19%)
    Preprocessed:    65 /  298 (21.81%)
  Misses:           270 /  568 (47.54%)
Uncacheable calls: 1220 / 1788 (68.23%)
Local storage:
  Cache size (GB):  0.1 /  1.0 (11.35%)
  Hits:             298 /  568 (52.46%)
  Misses:           270 /  568 (47.54%)
```

So ccache was completely successful in this build (0 misses during the entire CMake configure / build), yet CMake took 27 minutes.

We should investigate:
* disabling building static libraries (`ARROW_BUILD_STATIC`) to save on linking times
* why there are more than 600 uncacheable calls and only 280 cacheable calls, which is the majority of the ~860 compilation calls (the "Building CXX" lines in the logs)

Note that the "AMD64 Conda C++" build can be reproduced using [Archery](https://arrow.apache.org/docs/dev/developers/continuous_integration/docker.html) with the `conda-cpp` image:
```console
$ archery docker run conda-cpp
```

### Component(s)

C++

### PR DESCRIPTION
**Pull request by pitrou**
### Rationale for this change

ccache does not like precompiled headers and does not cache anything in that case, which pessimizes build times.

### What changes are included in this PR?

Disable precompiled headers, and enable unity builds to make up for it.

### Are these changes tested?

Yes, by construction.

### Are there any user-facing changes?

No.

* Closes: #35641

### CODE REVIEW

**Comment by pitrou** [comment]
@github-actions crossbow submit test-conda*

**Comment by pitrou** [comment]
cc @kou

**Comment by pitrou** [comment]
@github-actions crossbow submit test-conda*

**Comment by pitrou** [comment]
@github-actions crossbow submit test-conda* example*

**Comment by pitrou** [comment]
Hmm, CMAKE_UNITY_BUILD might actually make things worse if there's not enough RAM. Let's disable it again.

**Comment by kou** [comment]
Before ("Uncacheable calls" are increased):

https://github.com/apache/arrow/actions/runs/6044793011/job/16403882283#step:6:996

```text
Uncacheable calls:                  6314 / 9460 (66.74%)
  Could not use precompiled header: 6314 / 6314 (100.0%)
```
↓

https://github.com/apache/arrow/actions/runs/6044793011/job/16403882283#step:6:3341

```text
Uncacheable calls:                  6888 / 10320 (66.74%)
  Could not use precompiled header: 6888 /  6888 (100.0%)
```

After ("Uncacheable calls" aren't increased):

https://github.com/apache/arrow/actions/runs/6042717769/job/16398390958?pr=37502#step:6:1180

```text
 Uncacheable calls:                  6314 / 9460 (66.74%)
  Could not use precompiled header: 6314 / 6314 (100.0%)
```

↓

https://github.com/apache/arrow/actions/runs/6042717769/job/16398390958?pr=37502#step:6:3501

```text
 Uncacheable calls:                  6314 / 10311 (61.24%)
  Could not use precompiled header: 6314 /  6314 (100.0%)
```

**Comment by kou** [comment]
Can we merge this?
Do you want to do more tries on this PR?

**Comment by pitrou** [comment]
Yes, we can merge.

**Pull request merged**
