### PR TITLE
ARROW-460: [C++] JSON read/write for dictionaries

### PR DESCRIPTION
**Pull request by wesm**
cc @BryanCutler; this ended up being rather tedious.

As one uncertainty: I wasn't sure what to write for the `typeLayout` field for dictionary fields. We don't use this at all in C++, so let me know what you need in Java (if anything)

### CODE REVIEW

**Comment by BryanCutler** [comment]
Since `typeLayout` is optional in Java, you don't need to write anything and it will default to a 32bit Int.  I believe this field is for specifying an Int of a different bitwidth - so does C++ just use a 32bit index?

**Comment by wesm** [comment]
We don't use the typeLayout at all on read; we use the `indexType` from the dictionary metadata

**Comment by wesm** [comment]
OK, dictionaries are now in the top level. here's an example json:

https://gist.github.com/wesm/5100e41173a3b5e53437b7a887e4383a#file-gistfile1-json

**Comment by wesm** [comment]
As you can see in the JSON, the typeLayout I am writing is the index type

**Comment by wesm** [comment]
+1. Merging this and we can reconcile JSON format discrepancies when the Java version is complete and we add the integration tests themselves

**Comment by BryanCutler** [comment]
Sorry @wesm , I got mixed up between `indexType` and `typeLayout` in my response.  Java expects the encoded Field to have a `typeLayout` to describe the dictionary type so it can then proceed to read the dictionary data.  How do you  C++ if that metadata isn't there?

**Comment by BryanCutler** [comment]
I'll post my PR soon, there is still a couple things that need to be worked out, but it can read/write JSON so we can start testing.

**Comment by wesm** [comment]
The typeLayout right now is deterministic based on the other type metadata, so we don't need it. I can change the typeLayout to be the dictionary type layout if it causes a problem

**Pull request closed without merging**
