### PR TITLE
ARROW-795: [C++] Consolidate arrow/arrow_io/arrow_ipc into a single shared and static library

### PR DESCRIPTION
**Pull request by wesm**
This leaves c_glib in a broken state, since I'd rather let @kou fix up things the way he prefers (I started refactoring the automake files and realized I would probably just make a mess). 

I'm going to submit a patch to make parquet-cpp work on top of this.

### CODE REVIEW

**Comment by wesm** [comment]
@kou if you base changes for arrow-glib on top of this branch, can you post a git commit here for me to cherry pick into this PR, so that we can get a passing build? I can try my hand at cleaning things up if you like, too, but I wasn't sure about some of the generated code in arrow-glib/Makefile.am. Thanks!

**Comment by kou** [comment]
I've attached a patch: [0001-GLib-Consolidate-arrow-glib-arrow-io-glib-arrow-ipc-.txt](https://github.com/apache/arrow/files/908698/0001-GLib-Consolidate-arrow-glib-arrow-io-glib-arrow-ipc-.txt)

**Comment by wesm** [comment]
Thank you! I just applied the patch

**Comment by wesm** [comment]
The test suite passed except for Parquet failures / S3 timeouts

**Comment by wesm** [comment]
@pcmoritz @robertnishihara -- does this seem OK? The idea was to make Arrow simpler to develop against for thirdparties (and easier for us to package / develop internally). The public APIs still have the `io::` and `ipc::` C++ namespaces

**Comment by wesm** [comment]
+1, @xhochy is on vacation and we spoke briefly about this offline, so I'm going to merge. If there's any unforeseen consequences I'll be responsive to make quick fixes

**Comment by robertnishihara** [comment]
This makes sense! I don't anticipate any problems here.

**Pull request closed without merging**
