### PR TITLE
ARROW-4243: [Python] Fix test failures with pandas 0.24.0rc1

### PR DESCRIPTION
**Pull request by kou**

### CODE REVIEW

**Comment by kou** [comment]
Test failure log: https://travis-ci.org/kszucs/crossbow/builds/478558634#L2723

**Review by kszucs — APPROVED** [review]
LGTM

**Comment by wesm** [comment]
I'm trying to diagnose https://issues.apache.org/jira/browse/ARROW-4260 which is causing failures in many places. I can't tell if this patch is a cause or not -- I haven't been able to reproduce locally as of yet

**Comment by pcmoritz** [comment]
this has been failing for us as well: https://github.com/ray-project/ray/issues/3775

I can submit a patch to make it pandas 0.22 compatible again

**Pull request closed without merging**
