### PR TITLE
ARROW-12974: [R] test-r-without-arrow build fails because of example requiring Arrow

### PR DESCRIPTION
**Pull request by thisisnic**

### CODE REVIEW

**Comment by thisisnic** [comment]
@github-actions crossbow submit test-r-without-arrow

**Comment by thisisnic** [comment]
@github-actions crossbow submit test-r-without-arrow

**Comment by thisisnic** [comment]
@github-actions crossbow submit test-r-without-arrow

**Comment by thisisnic** [comment]
@github-actions crossbow submit test-r-without-arrow

**Review by nealrichardson — APPROVED** [review]

**Pull request closed without merging**
