### PR TITLE
ARROW-4399: [C++] Do not use extern template class with NumericArray<T> and NumericTensor<T>

### PR DESCRIPTION
**Pull request by wesm**
Using this has little benefit with this class, and can cause tricky symbol linkage issues with some environments

### CODE REVIEW

**Comment by wesm** [comment]
LLVM apt is down

```
+sudo apt-add-repository -y 'deb http://llvm.org/apt/xenial/ llvm-toolchain-xenial-6.0 main'
+sudo apt-get update -qq
W: The repository 'http://llvm.org/apt/xenial llvm-toolchain-xenial-6.0 Release' does not have a Release file.
E: Failed to fetch https://llvm.org/apt/xenial/dists/llvm-toolchain-xenial-6.0/main/binary-amd64/Packages  Protocol "http" not supported or disabled in libcurl
E: Some index files failed to download. They have been ignored, or old ones used instead.
The command "$TRAVIS_BUILD_DIR/ci/travis_install_clang_tools.sh" failed and exited with 100 during .
```

**Comment by kou** [comment]
Or we can handle tensor as another issue.

**Comment by wesm** [comment]
I'm trying to remove those now

**Comment by wesm** [comment]
Looks like we can't completely remove ARROW_TEMPLATE_EXPORT yet since it's used in sparse_tensor.cc. I'm removing from `NumericTensor<T>` so we can look into SparseTensorImpl in a different patch

**Review by pitrou — APPROVED** [review]
LGTM.

**Pull request closed without merging**
