### PR TITLE
ARROW-17075: [C++] Enforce no trailing slashes on filenames in HDFS

### PR DESCRIPTION
**Pull request by wjones127**
Follow up to #13577 / ARROW-17045.

### CODE REVIEW

**Comment by wjones127** [comment]
@github-actions crossbow submit -g conda-python-hdfs

**Comment by wjones127** [comment]
@github-actions crossbow submit -g conda-python-hdfs

**Comment by wjones127** [comment]
@github-actions crossbow submit conda-python-hdfs

**Comment by wjones127** [comment]
@github-actions crossbow submit _hdfs_

**Comment by wjones127** [comment]
@github-actions crossbow submit *_hdfs_*

**Comment by jorisvandenbossche** [comment]
@github-actions crossbow submit *hdfs*

**Comment by jorisvandenbossche** [comment]
@wjones127 the syntax and how it gets displayed by github is a bit confusing, I used `*hdfs*` (as a glob search pattern), although this "looks" the same as what you typed

**Comment by wjones127** [comment]
> @wjones127 the syntax and how it gets displayed by github is a bit confusing, I used *hdfs* (as a glob search pattern), although this "looks" the same as what you typed

Thanks! I couldn't remember how it works, and GitHub's "quote reply" feature was misleading me to think it was underscores.

**Comment by wjones127** [comment]
The tests failures are unrelated. The scanner failure test looks to be: https://issues.apache.org/jira/browse/ARROW-17087

**Review by pitrou — APPROVED** [review]
+1, thanks. Will wait for AppVeyor build.

**Pull request merged**
