### PR TITLE
[Release] Verify 9.0.0 RC1 

### PR DESCRIPTION
**Pull request by kszucs**

### CODE REVIEW

**Comment by kszucs** [comment]
@github-actions crossbow submit verify-rc-source-* --param release=9.0.0 --param rc=1

**Comment by raulcd** [comment]
Revision: 6b59b2f498cd03e50c88d400a83cfc360fb3d1f1

Submitted crossbow builds: [ursacomputing/crossbow @ release-9.0.0-rc1-0](https://github.com/ursacomputing/crossbow/branches/all?query=release-9.0.0-rc1-0)

|Task|Status|
|----|------|
|almalinux-8-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:release-9.0.0-rc1-0-github-almalinux-8-amd64)|
|almalinux-8-arm64|[TravisCI](https://app.travis-ci.com/github/ursacomputing/crossbow/branches)|
|almalinux-9-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:release-9.0.0-rc1-0-github-almalinux-9-amd64)|
|almalinux-9-arm64|[TravisCI](https://app.travis-ci.com/github/ursacomputing/crossbow/branches)|
|amazon-linux-2-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:release-9.0.0-rc1-0-github-amazon-linux-2-amd64)|
|amazon-linux-2-arm64|[TravisCI](https://app.travis-ci.com/github/ursacomputing/crossbow/branches)|
|centos-7-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:release-9.0.0-rc1-0-github-centos-7-amd64)|
|centos-8-stream-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:release-9.0.0-rc1-0-github-centos-8-stream-amd64)|
|centos-8-stream-arm64|[TravisCI](https://app.travis-ci.com/github/ursacomputing/crossbow/branches)|
|centos-9-stream-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:release-9.0.0-rc1-0-github-centos-9-stream-amd64)|
|centos-9-stream-arm64|[TravisCI](https://app.travis-ci.com/github/ursacomputing/crossbow/branches)|
|conan-maximum|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:release-9.0.0-rc1-0-github-conan-maximum)|
|conan-minimum|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:release-9.0.0-rc1-0-github-conan-minimum)|
|debian-bookworm-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:release-9.0.0-rc1-0-github-debian-bookworm-amd64)|
|debian-bookworm-arm64|[TravisCI](https://app.travis-ci.com/github/ursacomputing/crossbow/branches)|
|debian-bullseye-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:release-9.0.0-rc1-0-github-debian-bullseye-amd64)|
|debian-bullseye-arm64|[TravisCI](https://app.travis-ci.com/github/ursacomputing/crossbow/branches)|
|java-jars|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:release-9.0.0-rc1-0-github-java-jars)|
|nuget|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:release-9.0.0-rc1-0-github-nuget)|
|python-sdist|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:release-9.0.0-rc1-0-github-python-sdist)|
|test-ubuntu-default-docs|[Azure](https://dev.azure.com/ursacomputing/crossbow/_build/latest?definitionId=1&branchName=release-9.0.0-rc1-0-azure-test-ubuntu-default-docs)|
|ubuntu-bionic-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:release-9.0.0-rc1-0-github-ubuntu-bionic-amd64)|
|ubuntu-bionic-arm64|[TravisCI](https://app.travis-ci.com/github/ursacomputing/crossbow/branches)|
|ubuntu-focal-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:release-9.0.0-rc1-0-github-ubuntu-focal-amd64)|
|ubuntu-focal-arm64|[TravisCI](https://app.travis-ci.com/github/ursacomputing/crossbow/branches)|
|ubuntu-jammy-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:release-9.0.0-rc1-0-github-ubuntu-jammy-amd64)|
|ubuntu-jammy-arm64|[TravisCI](https://app.travis-ci.com/github/ursacomputing/crossbow/branches)|
|wheel-macos-big-sur-cp310-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:release-9.0.0-rc1-0-github-wheel-macos-big-sur-cp310-arm64)|
|wheel-macos-big-sur-cp310-universal2|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:release-9.0.0-rc1-0-github-wheel-macos-big-sur-cp310-universal2)|
|wheel-macos-big-sur-cp38-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:release-9.0.0-rc1-0-github-wheel-macos-big-sur-cp38-arm64)|
|wheel-macos-big-sur-cp39-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:release-9.0.0-rc1-0-github-wheel-macos-big-sur-cp39-arm64)|
|wheel-macos-big-sur-cp39-universal2|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:release-9.0.0-rc1-0-github-wheel-macos-big-sur-cp39-universal2)|
|wheel-macos-high-sierra-cp310-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:release-9.0.0-rc1-0-github-wheel-macos-high-sierra-cp310-amd64)|
|wheel-macos-high-sierra-cp37-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:release-9.0.0-rc1-0-github-wheel-macos-high-sierra-cp37-amd64)|
|wheel-macos-high-sierra-cp38-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:release-9.0.0-rc1-0-github-wheel-macos-high-sierra-cp38-amd64)|
|wheel-macos-high-sierra-cp39-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:release-9.0.0-rc1-0-github-wheel-macos-high-sierra-cp39-amd64)|
|wheel-macos-mavericks-cp310-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:release-9.0.0-rc1-0-github-wheel-macos-mavericks-cp310-amd64)|
|wheel-macos-mavericks-cp37-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:release-9.0.0-rc1-0-github-wheel-macos-mavericks-cp37-amd64)|
|wheel-macos-mavericks-cp38-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:release-9.0.0-rc1-0-github-wheel-macos-mavericks-cp38-amd64)|
|wheel-macos-mavericks-cp39-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:release-9.0.0-rc1-0-github-wheel-macos-mavericks-cp39-amd64)|
|wheel-manylinux2014-cp310-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:release-9.0.0-rc1-0-github-wheel-manylinux2014-cp310-amd64)|
|wheel-manylinux2014-cp310-arm64|[TravisCI](https://app.travis-ci.com/github/ursacomputing/crossbow/branches)|
|wheel-manylinux2014-cp37-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:release-9.0.0-rc1-0-github-wheel-manylinux2014-cp37-amd64)|
|wheel-manylinux2014-cp37-arm64|[TravisCI](https://app.travis-ci.com/github/ursacomputing/crossbow/branches)|
|wheel-manylinux2014-cp38-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:release-9.0.0-rc1-0-github-wheel-manylinux2014-cp38-amd64)|
|wheel-manylinux2014-cp38-arm64|[TravisCI](https://app.travis-ci.com/github/ursacomputing/crossbow/branches)|
|wheel-manylinux2014-cp39-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:release-9.0.0-rc1-0-github-wheel-manylinux2014-cp39-amd64)|
|wheel-manylinux2014-cp39-arm64|[TravisCI](https://app.travis-ci.com/github/ursacomputing/crossbow/branches)|
|wheel-windows-cp310-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:release-9.0.0-rc1-0-github-wheel-windows-cp310-amd64)|
|wheel-windows-cp37-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:release-9.0.0-rc1-0-github-wheel-windows-cp37-amd64)|
|wheel-windows-cp38-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:release-9.0.0-rc1-0-github-wheel-windows-cp38-amd64)|
|wheel-windows-cp39-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:release-9.0.0-rc1-0-github-wheel-windows-cp39-amd64)|

**Comment by raulcd** [comment]
@github-actions crossbow submit verify-rc-binaries-* --param release=9.0.0 --param rc=1

**Comment by kszucs** [comment]
@github-actions crossbow submit verify-rc-binaries-* --param release=9.0.0 --param rc=1

**Comment by kszucs** [comment]
@github-actions crossbow submit verify-rc-binaries-* --param release=9.0.0 --param rc=1

**Comment by kszucs** [comment]
@github-actions crossbow submit verify-rc-binaries-* --param release=9.0.0 --param rc=1

**Comment by kszucs** [comment]
@github-actions crossbow submit verify-rc-binaries-* --param release=9.0.0 --param rc=1

**Comment by kszucs** [comment]
Closing in favor of RC2

**Pull request closed without merging**
