### PR TITLE
ARROW-9092: [C++][TRIAGE] Do not enable TestRoundFunctions when using LLVM 9 until gandiva-decimal-test is fixed

### PR DESCRIPTION
**Pull request by wesm**
This unblocks LLVM 9 users from running the test suite. Whoever merges this, please leave the JIRA issue open.

### CODE REVIEW

**Review by projjal — APPROVED** [review]

**Review by kou — APPROVED** [review]
+1

**Comment by projjal** [comment]
@wesm I was trying to look into this but the TestRoundFunctions is passing for me with llvm 9 in both mac and ubuntu 18.04. Does it occur intermittently?

**Comment by wesm** [comment]
It occurs for me every time. My toolchain environment is somewhat complex (because I'm using some conda packages) so I'll see if I can provide a reproduction for you (it could take me a while to get back to you). FWIW I believe @kou encountered this problem also, probably in a more vanilla toolchain environment

**Comment by kou** [comment]
Sorry. I couldn't reproduce this on my local environment including `docker-compose run conda-cpp` on my local machine: https://github.com/apache/arrow/pull/7280#issuecomment-635634955

But it's reproduced on GitHub Actions with conda https://github.com/apache/arrow/runs/721758545 and without conda https://github.com/apache/arrow/runs/721758560 .

I looked into this a bit on GitHub Actions with https://github.com/mxschmitt/action-tmate . But I couldn't find what is the problem.

**Comment by wesm** [comment]
I used perf to record some data about the hung function

```
+   83.37%     0.00%  gandiva-decimal  [unknown]                      [.] 0xffffffffffffffff
+   65.62%     5.27%  gandiva-decimal  libgandiva.so.100.0.0          [.] llvm::SelectionDAG::Combine
+   62.50%     0.00%  gandiva-decimal  libgandiva.so.100.0.0          [.] llvm::SelectionDAGISel::CodeGenAndEmitDAG
+   57.88%     0.04%  gandiva-decimal  libgandiva.so.100.0.0          [.] llvm::SelectionDAGISel::SelectAllBasicBlocks
+   55.57%     0.00%  gandiva-decimal  libgandiva.so.100.0.0          [.] llvm::SelectionDAGISel::runOnMachineFunction
+   54.60%     0.00%  gandiva-decimal  libgandiva.so.100.0.0          [.] llvm::MachineFunctionPass::runOnFunction
+   53.48%     0.00%  gandiva-decimal  libgandiva.so.100.0.0          [.] (anonymous namespace)::X86DAGToDAGISel::runOnMachineFunction
+   46.62%     0.07%  gandiva-decimal  libgandiva.so.100.0.0          [.] llvm::FPPassManager::runOnFunction
+   45.75%     0.00%  gandiva-decimal  libgandiva.so.100.0.0          [.] llvm::legacy::PassManagerImpl::run
+   41.41%     0.00%  gandiva-decimal  libgandiva.so.100.0.0          [.] llvm::FPPassManager::runOnModule
+   39.79%     0.00%  gandiva-decimal  libgandiva.so.100.0.0          [.] llvm::MCJIT::emitObject
+   39.75%     2.28%  gandiva-decimal  libgandiva.so.100.0.0          [.] (anonymous namespace)::DAGCombiner::combine
+   30.20%     3.51%  gandiva-decimal  libgandiva.so.100.0.0          [.] (anonymous namespace)::DAGCombiner::visit
+   16.76%     6.80%  gandiva-decimal  libgandiva.so.100.0.0          [.] llvm::TargetLowering::SimplifyDemandedVectorElts
+   16.22%     0.54%  gandiva-decimal  libgandiva.so.100.0.0          [.] (anonymous namespace)::DAGCombiner::SimplifyDemandedVectorElts
+   15.57%     0.11%  gandiva-decimal  libgandiva.so.100.0.0          [.] (anonymous namespace)::DAGCombiner::SimplifyDemandedVectorElts
+   10.84%     1.95%  gandiva-decimal  libgandiva.so.100.0.0          [.] (anonymous namespace)::SelectionDAGLegalize::LegalizeOp
+   10.23%     4.51%  gandiva-decimal  libgandiva.so.100.0.0          [.] llvm::X86TargetLowering::SimplifyDemandedVectorEltsForTargetNode
+    8.64%     1.48%  gandiva-decimal  libgandiva.so.100.0.0          [.] (anonymous namespace)::DAGCombiner::recursivelyDeleteUnusedNodes
+    8.23%     0.25%  gandiva-decimal  libgandiva.so.100.0.0          [.] llvm::X86TargetLowering::LowerOperation
+    8.17%     1.55%  gandiva-decimal  libgandiva.so.100.0.0          [.] llvm::X86TargetLowering::PerformDAGCombine
+    7.59%     6.43%  gandiva-decimal  libgandiva.so.100.0.0          [.] (anonymous namespace)::DAGCombiner::AddToWorklist
+    7.10%     0.00%  gandiva-decimal  libgandiva.so.100.0.0          [.] gandiva::Projector::Make
+    6.93%     1.23%  gandiva-decimal  libgandiva.so.100.0.0          [.] LowerVSETCC
+    6.90%     0.14%  gandiva-decimal  libgandiva.so.100.0.0          [.] llvm::X86TargetLowering::LowerSETCC
+    6.68%     1.30%  gandiva-decimal  libgandiva.so.100.0.0          [.] llvm::SelectionDAG::getNode
+    6.27%     0.00%  gandiva-decimal  libgandiva.so.100.0.0          [.] gandiva::Engine::FinalizeModule
+    6.13%     0.58%  gandiva-decimal  libgandiva.so.100.0.0          [.] llvm::TargetLowering::SimplifySetCC
+    6.02%     0.00%  gandiva-decimal  libgandiva.so.100.0.0          [.] gandiva::LLVMGenerator::Build
+    5.81%     0.00%  gandiva-decimal  libgandiva.so.100.0.0          [.] gandiva::Projector::Make
+    5.45%     0.90%  gandiva-decimal  libgandiva.so.100.0.0          [.] llvm::SelectionDAG::LegalizeOp
```

It looks like an LLVM bug based on Googling for "llvm::SelectionDAG::Combine hang"

**Pull request closed without merging**
