### PR TITLE
ARROW-1150: Silence AdaptiveIntBuilder compiler warning on MSVC

### PR DESCRIPTION
**Pull request by xhochy**
We need to explicitly mark those sections as safe.

### CODE REVIEW

**Comment by xhochy** [comment]
@MaxRis Appveyor builds are failing on ZSTD thirdparty builds: https://ci.appveyor.com/project/ApacheSoftwareFoundation/arrow/build/1.0.2322/job/d6e5i4dwsjs5jxsm Can you have a short look at this?

**Comment by MaxRis** [comment]
@xhochy , investigating this, thanks

**Comment by MaxRis** [comment]
@xhochy , have create [PR](https://github.com/apache/arrow/pull/835) to remove temporary zstd from Toolchain build job. It looks like zstd enables [-GL optimization](https://msdn.microsoft.com/en-us/library/0zza0de8.aspx), which makes the binaries incompatible with default msvc build settings.

**Review by wesm — APPROVED** [review]
+1

**Pull request closed without merging**
