### PR TITLE
ARROW-2780: [Go] Run code coverage analysis

### PR DESCRIPTION
**Pull request by sbinet**
needs #2193

### CODE REVIEW

**Comment by sbinet** [comment]
again, travis failure unrelated to this CL.

**Comment by wesm** [comment]
Sorry about that, the tracking JIRA is https://issues.apache.org/jira/browse/ARROW-2782

**Comment by pitrou** [comment]
@sbinet could you rebase now that #2193 is merged?

**Comment by sbinet** [comment]
I'll rebase in a couple of hours.

**Comment by sbinet** [comment]
done.

**Review by wesm — APPROVED** [review]
+1. Will merge once build completes. Thanks @sbinet!

**Pull request closed without merging**
