### PR TITLE
ARROW-5432: [Python] Add NativeFile.read_at()

### PR DESCRIPTION
**Pull request by Ivan-Dimitrov**
Adding a read_at function for pyarrow.NativeFile that allows you to specify a length and offset. The read_at function doesn't do any reading ahead. 

https://issues.apache.org/jira/browse/ARROW-5432

### CODE REVIEW

**Comment by Ivan-Dimitrov** [comment]
HdfsPread (documented here: https://mapr.com/docs/archive/mapr50/28872231.html) doesn't change the offset of the file, but it seems ReadAt call in the arrow library does. This doesn't really matter for functionality, but it's good to know.

**Comment by pitrou** [comment]
> it seems ReadAt call in the arrow library does

It should be platform-dependent. Did you test on Windows?

**Review by pitrou — APPROVED** [review]
LGTM

**Comment by pitrou** [comment]
Travis-CI compile error is due to https://github.com/cython/cython/issues/2974

**Comment by pitrou** [comment]
I tried to push changes to your branch but apparently that confused Github. I'll open a new PR, sorry.

**Pull request closed without merging**
