### PR TITLE
ARROW-4825: [WIP][C++][Python] Transition from MemoryPool* to shared_ptr<MemoryPool>&

### PR DESCRIPTION
**Pull request by pearu**
This PR implements MemoryPool storage using shared_ptr to ensure that MemoryPool will be kept alive until all its Buffers are deallocated.

Fixes [ARROW-4825](https://issues.apache.org/jira/browse/ARROW-4825).

### CODE REVIEW

**Comment by fsaintjacques** [comment]
I'm -1 on this one. This is a very invasive change. I will continue the discussion in JIRA.

**Comment by wesm** [comment]
We'll need to spend some time discussing this given the scope and invasiveness of it. I would like to see if there are other ways to address the root problem which is a _new_ memory pool being created in Python and then being garbage collected as a result of user code. I think this issue can be addressed with changes that are less invasive and do not require changing any APIs

**Comment by wesm** [comment]
For example, `MemoryPool` may internally create a private `shared_ptr<MemoryBank>` object which is shared between the `MemoryPool` and `PoolBuffer` instances. This can be done in a fully transparent way

This is BTW the way that we extend the lifetime of memory maps beyond the lifetime of a `MemoryMappedFile` instance

**Comment by pearu** [comment]
I admit, modifying ca 200 files per PR is invasive.
However, my pleas are:
1. using `shared_ptr<MemoryPool>` instead of `MemoryPool*` seems the right thing to do because it guarantees the proper destruction order of objects that hold the `MemoryPool` pointer without any workarounds (such as MemoryBank, if I understand it correctly).
2. the change from `MemoryPool*` to `shared_ptr<MemoryPool>` turned out to be trivial: there are only few coding patterns that required changes and all the updated unittests pass successfully.

**Comment by wesm** [comment]
What I like least about this is that semantics from bindings layers are influencing the C++ API. That doesn't seem right to me. In many data processing applications, the memory manager is a component that is central to runtime state management. It is the application's responsibility to ensure that the `MemoryPool` stays alive longer than the memory allocated from it. 

The other big problem with this application is that we do have quite a lot of C++ API users. I can see breaking / deprecating an API here or there but not breaking dozens of APIs all at once. I think we should investigate our options, staying focused on the goals at hand (making sure that code written in Python does not segfault), and avoid unnecessary refactoring creep.

**Comment by wesm** [comment]
For example, one way to fix the original problem is to retain references to all created memory pools from the Python API and never garbage collect them

**Comment by pearu** [comment]
OK, I'll look into resolving the ARROW-4825 for Python-only: attach a Python MemoryPool instance to Buffers that are created using the given MemoryPool instance.

**Comment by fsaintjacques** [comment]
Or have a wrapping allocator that stacks the allocated buffers and explicitly delete them, this could be simplified with context guard:

```
with allocator() as pool:
  #  push buf to pool._buffers
  buf = pool.allocate(...)

# allocator goes out of scope, pool.__exit__ calls `map(lambda x: del x, pool._buffers)` ensure they're deleted before pool.

**Comment by pearu** [comment]
I agree, there are many ways to workaround the current issue without changing Arrow at all. However, the use-case giving the segfault is something that would be very natural to use for most users, IMHO.

**Comment by wesm** [comment]
It depends. Many applications will never touch the MemoryPool API and simply use `arrow::default_memory_pool()`. I would regard using custom memory pools as fairly advanced usage and should require an awareness of runtime state management. In database systems, such runtime state is often managed by some kind of singleton object, and memory is managed very carefully in different components of the project. Since pyarrow is a developer-centric library rather than a user-centric one I would expect a higher level of sophistication from its user than something like pandas

**Comment by pearu** [comment]
See alternative fix in PR #3888.

**Comment by pitrou** [comment]
I'm a bit surprised by the choice to fix this on the Python side while the defect is obviously on the C++ side.

I see two possible downsides with changing the C++ side:
* API breakage: this is the main problem with the change
* Potential performance issues: those sound a bit more unlikely

One can indeed decide to store a middleman `shared_ptr<MemoryPoolImpl>` instead of `shared_ptr<MemoryPool>`. It has the same potential performance issues, doesn't break the API (AFAICT), but makes life harder for memory pool implementors.

**Comment by wesm** [comment]
@pitrou it would probably be best to discuss this further on the mailing list. IMHO the `MemoryPool` is a key property of the runtime environment. Having a huge number of objects "sharing ownership" of the MemoryPool does not seem useful to me. That it is possible to:

* Create a MemoryPool
* Allocate a Buffer with it
* Destruct the MemoryPool
* subsequently Segfault on deallocation of the Buffer

is not a defect, instead that is how the project was explicitly designed. I don't even think this behavior is even bad, since this case indicates that an application has improperly looked after the lifetime of the MemoryPool.

**Comment by wesm** [comment]
Closing this PR for now. My view is that it is the application's responsibility to steward the lifetime of a MemoryPool. We can discuss further on the mailing list

**Pull request closed without merging**
