### PR TITLE
ARROW-952: fix regex include from C++ standard library

### PR DESCRIPTION
**Pull request by pcmoritz**

### CODE REVIEW

**Comment by wesm** [comment]
We removed `std::regex` altogether, is this needed?

**Comment by pcmoritz** [comment]
It was still included here, that's what caused the problem:
https://github.com/apache/arrow/blob/master/cpp/src/arrow/util/decimal.h#L24

You are right, it is not actually used. I'll fix the PR.

**Comment by cpcloud** [comment]
Thanks! Sorry I missed this.

**Comment by pcmoritz** [comment]
No worries and thanks for getting rid of <regex> and boost::regex :)

**Review by wesm — APPROVED** [review]
+1

**Pull request closed without merging**
