### PR TITLE
PARQUET-1707 [C++]: parquet-arrow-test fails with UBSAN

### PR DESCRIPTION
**Pull request by gawain-bolton**

### CODE REVIEW

**Comment by wesm** [comment]
@kszucs @emkornfield is there a nightly ubsan build, and if not can we set one up?

**Comment by pitrou** [comment]
Hmm, I think we had UBSAN set up together with ASAN on Travis...

**Comment by pitrou** [comment]
Created https://issues.apache.org/jira/browse/ARROW-7292

**Review by wesm — APPROVED** [review]
+1

**Pull request closed without merging**
