### PR TITLE
MINOR: [Archery] Update comment

### PR DESCRIPTION
**Pull request by pitrou**
Followup to ARROW-14851; I forgot to do it before merging.

### CODE REVIEW

**Comment by pitrou** [comment]
cc @dianaclarke

**Comment by fsaintjacques** [comment]
Now I remember :)

**Review by fsaintjacques — APPROVED** [review]

**Comment by pitrou** [comment]
@fsaintjacques Do you remember why it was done like this?

**Comment by fsaintjacques** [comment]
Lack of time to implement, the proper solution is to add a Run() method to the base BenchmarkRunner and memoize the result.

**Pull request closed without merging**
