### PR TITLE
ARROW-18151: [CI] Avoid unnecessary redirect for some conda URLs 

### PR DESCRIPTION
**Pull request by raulcd**
Fixes the unnecessary redirects:
```
--2022-10-25 08:44:33--  https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
Resolving repo.continuum.io (repo.continuum.io)... 104.18.200.79, 104.18.201.79, 2606:4700::6812:c84f, ...
Connecting to repo.continuum.io (repo.continuum.io)|104.18.200.79|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh [following]
--2022-10-25 08:44:34--  https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
Resolving repo.anaconda.com (repo.anaconda.com)... 104.16.131.3, 104.16.130.3, 2606:4700::6810:8303, ...
Connecting to repo.anaconda.com (repo.anaconda.com)|104.16.131.3|:443... connected.
HTTP request sent, awaiting response... 200 OK
 ```

### CODE REVIEW

**Review by assignUser — APPROVED** [review]
Tested locally :+1:

**Review by jorisvandenbossche — APPROVED** [review]
Those links are from a long time ago ;)

**Comment by raulcd** [comment]
I just rebased master to get rid of the CI failures

**Comment by raulcd** [comment]
@jorisvandenbossche I think the CI failures have nothing to do with it.

**Comment by pitrou** [comment]
By the way, do we want to move to mambaforge at some point?

**Comment by jorisvandenbossche** [comment]
> By the way, do we want to move to mambaforge at some point?

Or micromamba? (https://mamba.readthedocs.io/en/latest/user_guide/micromamba.html)

**Pull request merged**
