### PR TITLE
GH-41173: [Java] Add spotless configuration for Maven pom.xml files

### PR DESCRIPTION
**Pull request by laurentgo**
### What changes are included in this PR?

To make sure that all pom.xml files follow the same convention regarding indentation and organization, add spotless plugin with sortPom module to  check and format the files automatically.
    
Update Java developer documentation to provide the link to the  convention and instructions on how to use spotless
    
Finally apply the convention to all `pom.xml` files

### Are these changes tested?

No new test as no code change (just formatting)

### Are there any user-facing changes?

None
* GitHub Issue: #41173

### CODE REVIEW

**Comment by vibhatha** [comment]
@laurentgo there is already and effort to add this module by module: https://github.com/apache/arrow/issues/40757

**Comment by laurentgo** [comment]
I saw the spotless change but I assumed it was for Java files, not `pom.xml`. I would argue that `pom.xml` are style on their own, and that there's only a few of them (compared to the numerous java files).

At the same time, as someone who's offering/trying to clean up those files, it's kind of hard to have to match each file own style...

**Comment by lidavidm** [comment]
I think we can do this first. @vibhatha would it conflict?

**Comment by vibhatha** [comment]
This is formatting all poms. I thought we wanted a smaller diff as a previous PR was closed for the length of it. 

If this solves the problem, let's close the issues created per module. 

Also I would recommend to check existing issues before creating new ones.

**Comment by vibhatha** [comment]
> I saw the spotless change but I assumed (wrongly) it was for Java files, not `pom.xml`. My bad.
> 
> 
> 
>  I would argue that `pom.xml` have a style on their own, and that there's only a few of them (compared to the numerous java files).
> 
> 
> 
> At the same time, as someone who's offering/trying to clean up those files, it's kind of hard to have to match each file own style...

It's fine. Let's try to wrap up this PR. 
But let's close the other tickets if it closes the expected via this PR. 

Objective is to format code and xml both. 

If this PR is only doing xml format we can declare that and make code changes in the other list. 

Also please feel free to work on those issues if it's in the scope.

**Comment by lidavidm** [comment]
The previous PR formatted nearly everything.

**Review by vibhatha — COMMENTED** [review]
Looks fine to me. Let's verify the CIs.

**Comment by vibhatha** [comment]
> The previous PR formatted nearly everything.

Yes, except the Java. I looked into the changes. I am not an expert with spotless, but this only formats the pom. 

It would be very hard to be sure about all formatting. I will run the crossbows and validate. That should be one validator. 

I think we decided to go module by module since it's hard to eye-check everything in a single PR.

**Comment by vibhatha** [comment]
But this PR is manageable. We can use the other spotless tickets to format code and licenses.

**Comment by vibhatha** [comment]
@github-actions crossbow submit -g java

**Review by lidavidm — APPROVED** [review]

**Pull request merged**
