### PR TITLE
ARROW-4281: [CI] Use Ubuntu Xenial VMs on Travis-CI

### PR DESCRIPTION
**Pull request by pitrou**
The R build job still uses Trusty, though, as the community-supported R images don't work with Xenial.

### CODE REVIEW

**Comment by pravindra** [comment]
I’ll look into this tomorrow (my time).

**Comment by pravindra** [comment]
@pitrou - i'm able to get the java tests to run with this fix.

`
diff --git a/cpp/src/gandiva/jni/symbols.map b/cpp/src/gandiva/jni/symbols.map
index a387ae1f..e0f5def4 100644
--- a/cpp/src/gandiva/jni/symbols.map
+++ b/cpp/src/gandiva/jni/symbols.map
@@ -15,6 +15,6 @@
 # specific language governing permissions and limitations
 # under the License.
 {
-  global: extern "C++" { gandiva*; Java*; JNI*; };
+  global: extern "C++" { gandiva*; }; Java*; JNI*;
   local: *;
 };
`

**Comment by pitrou** [comment]
Thanks @pravindra ! I'll apply the fix in the PR.

**Comment by wesm** [comment]
rebased

**Comment by kszucs** [comment]
We should be able to set conda-forge globally: `conda config --add channels conda-forge`

**Comment by pitrou** [comment]
> I think We can remove all occurrences of -c conda-forge

Ok, i'm trying this now.

**Comment by wesm** [comment]
@pitrou anything more you want to do here? Otherwise IMHO this should be merged (and we can deal with any further issues that arise)

**Review by kszucs — APPROVED** [review]
LGTM

**Comment by kszucs** [comment]
Created issue for the channel removal: https://issues.apache.org/jira/browse/ARROW-4334

**Pull request closed without merging**
