### PR TITLE
GH-40536: [CI]: Migrate remaining jobs away from self-hosted mac runners.

### PR DESCRIPTION
**Pull request by assignUser**
### Rationale for this change
CRAN no longer builds on 10.13 and gh provides M1 runners now.

### What changes are included in this PR?

use m1 for  verify-rc-binaries-wheels-macos-14-arm64:
and macos-11 for r-binary-packages

### Are these changes tested?
crossbow
* GitHub Issue: #40536

### CODE REVIEW

**Comment by assignUser** [comment]
@github-actions crossbow submit  verify-rc-binaries-wheels-macos-14-arm64 r-binary-packages

**Comment by kou** [comment]
@github-actions crossbow submit verify-rc-binaries-wheels-macos-14-arm64 --param release=15.0.2 --param rc=3

**Comment by assignUser** [comment]
ugh, brew doesn't support macos 11 anymore so it tries to build sccache from source... 
```
Warning: You are using macOS 11.
We (and Apple) do not provide support for this old version.
It is expected behaviour that some formulae will fail to build in this old version.
It is expected behaviour that Homebrew will be buggy and slow.
Do not create any issues about this on Homebrew's GitHub repositories.
Do not create any issues even if you think this message is unrelated.
```
Lets just bump to 12, 11 will be removed in Q2 anyway: https://github.com/actions/runner-images/issues/9255

**Comment by assignUser** [comment]
@github-actions crossbow submit  r-binary-packages

**Comment by kou** [comment]
verify-rc-binaries-wheels-macos-14-arm64 worked. I'll unify `verify-rc/github.macos.{arm,amd}64.yml`.

**Comment by kou** [comment]
@github-actions crossbow submit verify-rc-*-macos-* --param release=15.0.2 --param rc=3

**Comment by kou** [comment]
@github-actions crossbow submit verify-rc--macos- --param release=15.0.2 --param rc=3

**Comment by kou** [comment]
verify-rc-source-cpp-macos-arm64 and verify-rc-source-cpp-macos-conda-amd64 failures will be passed on main because main has https://github.com/apache/arrow/commit/5127ef0369e37cda05cbcfb545319ff52191668d#diff-aa8c7db0f10c202b555dd103c54828afa0e8cbd781e87694b5ac4705beba2cdeR1068 .

**Review by kou — APPROVED** [review]
+1

**Review by raulcd — APPROVED** [review]

**Comment by raulcd** [comment]
Thanks both @kou and @assignUser for the effort!

**Pull request merged**
