### PR TITLE
ARROW-10: Fix mismatch of javadoc names and method parameters

### PR DESCRIPTION
**Pull request by lw-lin**

### CODE REVIEW

**Comment by proflin** [comment]
@jacques-n Would mind taking a look please? Thanks.

**Comment by jacques-n** [comment]
Looks reasonable. Can you rebase and make sure that commit message is of format "ARROW-10: ..." like other commits?

**Comment by proflin** [comment]
Rebased and re-committed with message of format "ARROW-10: ..."; sorry for the inconvenience caused earlier. Would you take a another look please? Thanks.

**Comment by HyukjinKwon** [comment]
@jacques-n @proflin Would this be better if [org.apache.arrow.memory.BufferManager.java#L45](https://github.com/apache/arrow/blob/master/java/memory/src/main/java/org/apache/arrow/memory/BufferManager.java#L45) and [org.apache.arrow.memory.AllocationManager.java#L330-L331](https://github.com/apache/arrow/blob/master/java/memory/src/main/java/org/apache/arrow/memory/AllocationManager.java#L330-L331) are filled up?

I don't want to make a PR for them if the documentation stuff can be dealt with here.

**Comment by proflin** [comment]
@HyukjinKwon comments addressed. Thanks!

**Comment by akhld** [comment]
Sorry for cross commenting, but can we add a getting started doc?

**Comment by wesm** [comment]
+1

**Pull request closed without merging**
