### PR TITLE
ARROW-8743: [CI][C++] Add a test job for s390x

### PR DESCRIPTION
**Pull request by kou**

### CODE REVIEW

**Comment by kou** [comment]
@kiszk Do you want to work on fixing test failures step-by-step as follow-up tasks?

**Comment by kiszk** [comment]
@kou Thank you. I am happy to fix them.

**Comment by kiszk** [comment]
One question. Can we enable options step-by-step, too? For example, can we customize `ENV ...` at https://github.com/apache/arrow/pull/7131/commits/5d6617c4a26be2983336e1baba1a16effe412e9c#diff-cb07f7d49b556d3668355e47df3ad348R85 for each platform?

It can reduce the number of errors in a log file when we submit a PR to fix failures step-by-step.

**Comment by kou** [comment]
Sure. I'll reduce enabled options.

**Comment by kiszk** [comment]
Thank you very much!
Other candidates look `ARROW_PYTHON` and `ARROW_S3`. Does it make sense?

**Comment by kou** [comment]
Done: https://travis-ci.org/github/apache/arrow/builds/684931696

There are many failure outputs from `cpp/src/arrow/util/rle_encoding_test.cc`. It's a core component. We can't disable it.

Do you think that the current job is a good starting point?

**Comment by kou** [comment]
> Other candidates look `ARROW_PYTHON` and `ARROW_S3`. Does it make sense?

They are already disabled by default: https://travis-ci.org/github/apache/arrow/builds/684931696#L1496

**Comment by kiszk** [comment]
Yes, I think that it is a good starting point. 

I have a patch to fix failures at `rle_encoding_test.cc` in my environment. In my local environment, I used the option `cmake -DCMAKE_BUILD_TYPE=Debug -DARROW_BUILD_TESTS=ON`.

After merging this, I will submit a PR.

**Comment by kou** [comment]
OK. I'll merge this once remaining GitHub Actions jobs are passed.

**Pull request closed without merging**
