### PR TITLE
ARROW-13480: [C++] Fix possible deadlock when dataset produces an error

### PR DESCRIPTION
**Pull request by pitrou**

### CODE REVIEW

**Comment by pitrou** [comment]
@westonpace Feel free to add any C++ tests to this.

**Comment by westonpace** [comment]
Thanks!  Will do.

**Comment by westonpace** [comment]
Added a C++ change as a PR to your repo.

**Comment by pitrou** [comment]
@westonpace Are you ok with the fix?

**Review by westonpace — APPROVED** [review]

**Pull request closed without merging**
