### PR TITLE
MINOR: [CI][Python] Use Docker CLI for HDFS test jobs as well

### PR DESCRIPTION
**Pull request by pitrou**

### CODE REVIEW

**Comment by pitrou** [comment]
@github-actions crossbow submit *hdfs*

**Comment by pitrou** [comment]
Hmm, apparently, the newer `docker compose` command does not work exactly like the old `docker-compose`. It seems the hostname `impala` is not available to connect to from the main Docker container:
https://github.com/ursacomputing/crossbow/actions/runs/10263540816/job/28395608131#step:7:5727
```

hdfsBuilderConnect(forceNewInstance=1, nn=impala, port=8020, kerbTicketCachePath=(NULL), userName=hdfs) error:
java.lang.IllegalArgumentException: java.net.UnknownHostException: impala
	at org.apache.hadoop.security.SecurityUtil.buildTokenService(SecurityUtil.java:443)
/arrow/cpp/src/arrow/io/hdfs_test.cc:122: Failure
	at org.apache.hadoop.hdfs.NameNodeProxiesClient.createProxyWithClientProtocol(NameNodeProxiesClient.java:132)
	at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:351)
	at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:285)
	at org.apache.hadoop.hdfs.DistributedFileSystem.initialize(DistributedFileSystem.java:164)
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:3242)
	at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:121)
	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:3291)
	at org.apache.hadoop.fs.FileSystem$Cache.getUnique(FileSystem.java:3265)
	at org.apache.hadoop.fs.FileSystem.newInstance(FileSystem.java:523)
	at org.apache.hadoop.fs.FileSystem$2.run(FileSystem.java:493)
	at org.apache.hadoop.fs.FileSystem$2.run(FileSystem.java:490)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/javax.security.auth.Subject.doAs(Subject.java:423)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1893)
	at org.apache.hadoop.fs.FileSystem.newInstance(FileSystem.java:490)
Caused by: java.net.UnknownHostException: impala
```

@kou @assignUser Any idea how we could fix this?

**Comment by pitrou** [comment]
Looking at the logs, it seems that Archery simply is not able to spawn dependent services when not using `docker-compose`.

**Comment by pitrou** [comment]
This diff seems to fix things locally for me (assuming `ARCHERY_USE_DOCKER_CLI=0`), but it might have unforeseen consequences?
```diff
diff --git a/dev/archery/archery/docker/cli.py b/dev/archery/archery/docker/cli.py
index 7053db2afc..a2e699d666 100644
--- a/dev/archery/archery/docker/cli.py
+++ b/dev/archery/archery/docker/cli.py
@@ -78,8 +78,7 @@ def docker(ctx, src, dry_run, using_docker_cli, using_docker_buildx):
                             using_docker=using_docker_cli,
                             using_buildx=using_docker_buildx,
                             debug=ctx.obj.get('debug', False),
-                            compose_bin=("docker compose" if using_docker_cli
-                                         else "docker-compose"))
+                            compose_bin="docker compose")
     if dry_run:
         _mock_compose_calls(compose)
     ctx.obj['compose'] = compose
```

**Comment by assignUser** [comment]
Well it should be the same as using `ARCHERY_USE_DOCKER_CLI=1` but apparently it isn't seeing the failure in the run above. 

I think we should remove `docker-compose` as it is no longer receiving updates. This will of course need testing and potentially some images will need updates.

**Comment by kou** [comment]
How about using `docker compose` (or `docker-compose`) when the service has `links:`? 

```diff
diff --git a/dev/archery/archery/docker/core.py b/dev/archery/archery/docker/core.py
index 5be4887ea4..9ba603626e 100644
--- a/dev/archery/archery/docker/core.py
+++ b/dev/archery/archery/docker/core.py
@@ -341,7 +341,7 @@ class DockerCompose(Command):
 
         args = []
 
-        use_docker = self.config.using_docker or service['need_gpu'] or resource_limit
+        use_docker = (not service.get('links')) and (self.config.using_docker or service['need_gpu'] or resource_limit)
         if use_docker:
             # use gpus, requires docker>=19.03
             if service['need_gpu']:
```

**Comment by pitrou** [comment]
This PR is superseded by #43586, closing

**Pull request closed without merging**
