### PR TITLE
ARROW-4972: [Go] implement ArrayEquals

### PR DESCRIPTION
**Pull request by sbinet**

### CODE REVIEW

**Comment by sbinet** [comment]
PTAL @alexandreyc @stuartcarnie

**Comment by alexandreyc** [comment]
LGTM

I was thinking of generating code for numeric (and derived) arrays, where the comparison function is always the same except for parameters types. What's your opinion?

**Comment by sbinet** [comment]
I considered this as well but I followed your lead.
I could whip up a generator if you prefer.

**Comment by sbinet** [comment]
(or, better, integrate it into the `numeric` template)

**Comment by alexandreyc** [comment]
Yes I think it would be better!

**Comment by sbinet** [comment]
done. :)

**Pull request closed without merging**
