### PR TITLE
Serialize tensors in PyTorch 0.4

### PR DESCRIPTION
**Pull request by alok**
As of PyTorch 0.4.0, `type(t)` where `t` is a tensor will always equal `torch.Tensor`. To get the original types, you need to call `t.type()`. This change fixes serialization for torch tensors. Otherwise, they're truncated (at least upon deserialization in Ray).

### CODE REVIEW

**Comment by pitrou** [comment]
The change looks basically good to me. Unfortunately, I don't think our CI setup currently tests with PyTorch anymore (there were problems with the binary packages available), and the failures look unrelated.

**Review by pitrou — APPROVED** [review]

**Comment by alok** [comment]
@robertnishihara [See here](https://github.com/pytorch/pytorch/releases) and search for `The type() of a Tensor has changed`. Basically, `type(t)` *for any tensor type* will always be `torch.Tensor`. To do a proper comparison, you need to use `isinstance` or run `t.type()`

**Comment by robertnishihara** [comment]
Thanks @alok, can you try rebasing on the master and see if the test failures go away?

**Comment by pcmoritz** [comment]
LGTM, the test failure was fixed in https://github.com/apache/arrow/commit/4b8511f92d24dc9d5ace150218a2902c8e32dc76

**Pull request merged**
