### PR TITLE
ARROW-7192: [Rust] Implement Flight crate

### PR DESCRIPTION
**Pull request by andygrove**
This PR adds a new `flight` crate which generates code from the `Flight.proto` file for use by other projects and includes an example which runs a Tonic gRPC server that implements the Flight protocol but all the methods return an `Err` saying that the methods are not implemented.

Note that is was necessary to upgrade to a more recent Rust nightly to be able to use Tonic and I had to remove some `#[inline]` declarations on empty trait methods in order to fix compilation errors.

### CODE REVIEW

**Comment by andygrove** [comment]
Made some progress. Now the main method fails to compile with:

```
31  |       let svc: FlightService = FlightServiceServer::new(service);
    |                ^^^^^^^^^^^^^
    |                |
    |                associated type `HandshakeStream` must be specified
    |                associated type `ListFlightsStream` must be specified
    |                associated type `DoGetStream` must be specified
    |                associated type `DoPutStream` must be specified
    |                associated type `DoActionStream` must be specified
    |                associated type `ListActionsStream` must be specified
```

**Comment by nevi-me** [comment]
> Made some progress. Now the main method fails to compile with:
> 
> ```
> 31  |       let svc: FlightService = FlightServiceServer::new(service);
>     |                ^^^^^^^^^^^^^
>     |                |
>     |                associated type `HandshakeStream` must be specified
>     |                associated type `ListFlightsStream` must be specified
>     |                associated type `DoGetStream` must be specified
>     |                associated type `DoPutStream` must be specified
>     |                associated type `DoActionStream` must be specified
>     |                associated type `ListActionsStream` must be specified
> ```

Hi Andy, I fixed the code and pushed to your branch. 

You shouldn't specify the `FlightService` type there because `FlightServiceServer::new(service)` returns `FlightServiceServer<FlightServiceImpl>`.

The main cause of the compilation error was however the import of the compiled protos. I don't know why, but it's a bit frustrating at first that `prost` doesn't consider the same proto import as equal when imported in 2 projects (in this case the bin and lib).

If there isn't a solution to this, it might end up causing frustration to users (unless they don't need to compile their own protobufs).
What I normally do is convert `crate_a::proto::MyMessage` to `bytes::BytesMut` then encode `crate_b::proto::MyMessage` from the bytes. I'm probably doing something wrong; ping @LucioFranco

**Comment by LucioFranco** [comment]
@nevi-me I'm not directly following the problem? Prost/Tonic just generate rust code. Under the hood `include_proto` just use `include!` which will bring the rust code as if it were defined directly in that module. So just like any other rust code if you define something in one crate it belongs to that crate.

Usually, what you probably want to do is to have an intermediary crate that is just the compiled protos so that libs/bins can just reference that one. Let me know if that makes sense! Happy to help more! (I am currently on the train in the middle of france so I might be slow to respond)

**Comment by andygrove** [comment]
Thanks @nevi-me  and @LucioFranco for the help :-)

I have split this into two crates now. One for the generated code and one for the demo.

I guess I'll quickly run into a dependency on IPC now and can start helping with that.

**Comment by andygrove** [comment]
@kszucs I'm not sure how to fix the Ursabot build. Isn't this using docker-compose now?

**Comment by kszucs** [comment]
@andygrove this will fix the ursabot build https://github.com/ursa-labs/ursabot/pull/185

**Comment by kszucs** [comment]
@ursabot build

**Comment by kszucs** [comment]
@andygrove deployed the new builder and it passes, "Ursabot / AMD64 Debian 9 Rust 1.35" is no longer running.

**Comment by andygrove** [comment]
Thanks @kszucs it looks good!

**Review by sunchao — APPROVED** [review]
LGTM. It will be great if there is a `README.md` for this crate.

**Comment by LucioFranco** [comment]
This looks like a great start, feel free to ping me for more reviews on things :)

I am hoping to get a the first non alpha release of tonic out by end of this up coming week with tokio/hyper/tower.

**Comment by andygrove** [comment]
I added a README and renamed the crate from `flight` to `arrow-flight` because there is already a `flight` crate published to crates.io (unrelated to Arrow).

**Review by nevi-me — APPROVED** [review]
LGTM

**Comment by sunchao** [comment]
> I added a README and renamed the crate from `flight` to `arrow-flight` because there is already a `flight` crate published to crates.io (unrelated to Arrow).

Maybe we can still keep the directory name as `flight`? even though the crate name has to be `arrow-flight`.

**Pull request closed without merging**
