### PR TITLE
ARROW-18259: [C++][CMake] Add support for system Thrift CMake package

### PR DESCRIPTION
**Pull request by kou**

### CODE REVIEW

**Review by pitrou — APPROVED** [review]

**Comment by pitrou** [comment]
Hmm, it looks like this break some CI builds.

**Comment by kou** [comment]
* https://github.com/apache/thrift/pull/2725
* https://github.com/apache/thrift/pull/2726

**Comment by kou** [comment]
https://github.com/conda-forge/thrift-cpp-feedstock/issues/68

**Comment by kou** [comment]
+1

**Pull request merged**
