### PR TITLE
MINOR: [Dev] Add zanmato1984 and ZhangHuiGui in collaborators list 

### PR DESCRIPTION
**Pull request by mapleFU**
### Rationale for this change

Recently zanmato1984 and ZhangHuiGui is active on arrow-compute and arrow-acero module, which lacks maintainer. The contributions can be seem below:
* https://github.com/apache/arrow/commits?author=zanmato1984
* https://github.com/apache/arrow/commits?author=ZhangHuiGui

I promote them as collaborators

### What changes are included in this PR?

Changes `.asf.yaml`

### Are these changes tested?

No

### Are there any user-facing changes?

No

### CODE REVIEW

**Comment by jbonofre** [comment]
As reminder the collaborators list is limited to 10 entries.

**Comment by mapleFU** [comment]
> As reminder the collaborators list is limited to 10 entries.

Aha it already has 7 coolaborators now...I'll let the community decide whether we should add them

**Review by raulcd — APPROVED** [review]
Thanks @mapleFU 
As far as I know we could ask ASF infra to increase the number of collaborators but we could also take a look to the list and check when collaborators stop contributing to the project.
I am +1 with the new additions!

**Review by assignUser — APPROVED** [review]

**Review by kou — APPROVED** [review]
+1

In general, we'll invite active collaborators to committers eventually. And we can remove committers from collaborators. So collaborators seat will not be full.
See also: https://arrow.apache.org/committers/#becoming-a-committer

**Pull request merged**
