### PR TITLE
ARROW-10490: [C++][GLib] Fix range-loop-analysis warnings

### PR DESCRIPTION
**Pull request by kou**
They are detected by Xcode 12.

### CODE REVIEW

**Review by terencehonles — APPROVED** [review]
Looks good to me! Definitely better than pinning Xcode, and now I was going to look into the JNI status check failures.

I've bisected it to https://github.com/apache/arrow/pull/8533, and I'm testing reverting the `DCHECK_NE` change to see what that does. I **just** finished bisecting so I was going to run the tests and then ask about if the change should be there and how the test should probably be fixed if it should be there.

**Comment by kou** [comment]
OK.
I'll merge this.

It seems that #8533 isn't related to the JNI failure because #8533 is R related change and the JNI failure is Java related code.
We may need to discuss it at the https://lists.apache.org/thread.html/rdd900f5359fb57f32e3eb686f6584535e81e3b2f7440cbc74f945b67%40%3Cdev.arrow.apache.org%3E thread.

**Comment by terencehonles** [comment]
> OK.
> I'll merge this.
> 
> It seems that #8533 isn't related to the JNI failure because #8533 is R related change and the JNI failure is Java related code.
> We may need to discuss it at the https://lists.apache.org/thread.html/rdd900f5359fb57f32e3eb686f6584535e81e3b2f7440cbc74f945b67%40%3Cdev.arrow.apache.org%3E thread.

It's an R related change, but it touches a C file which breaks the java/adapter/orc/src/test/java/org/apache/arrow/adapter/orc/OrcReaderTest.java test (it seems like it's a segfault, but I don't know how to get better logging to confirm that, the process is dead though). Removing the `DCHECK_NE` change in `memory.cc` "fixes" the issue, but it looks like there is also a memory leak coming from java/flight/flight-core/src/test/java/org/apache/arrow/flight/TestDoExchange.java (testClientCancel) which was also causing issues. I'll try to follow up on the mailing list tomorrow (thanks for the heads up about it, I just figured I'd share my findings here)

**Comment by kou** [comment]
Ah, I see.

> I'll try to follow up on the mailing list tomorrow

Thanks!

**Pull request closed without merging**
