### PR TITLE
ARROW-16016: [C++] Fix recursive ccache invocation error

### PR DESCRIPTION
**Pull request by pitrou**
Do not force using ccache if the user already added a compiler launcher for the same reason.

### CODE REVIEW

**Comment by pitrou** [comment]
Not sure this is the correct fix or workaround...

**Comment by kou** [comment]
How about overwriting `CMAKE_X_COMPILER_LAUNCHER`?

```diff
diff --git a/cpp/CMakeLists.txt b/cpp/CMakeLists.txt
index ff70619440..528302de69 100644
--- a/cpp/CMakeLists.txt
+++ b/cpp/CMakeLists.txt
@@ -195,8 +195,8 @@ if(ARROW_USE_CCACHE)
   find_program(CCACHE_FOUND ccache)
   if(CCACHE_FOUND)
     message(STATUS "Using ccache: ${CCACHE_FOUND}")
-    set_property(GLOBAL PROPERTY RULE_LAUNCH_COMPILE ${CCACHE_FOUND})
-    set_property(GLOBAL PROPERTY RULE_LAUNCH_LINK ${CCACHE_FOUND})
+    set(CMAKE_C_COMPILER_LAUNCHER ${CCACHE_FOUND})
+    set(CMAKE_CXX_COMPILER_LAUNCHER ${CCACHE_FOUND})
     # ARROW-3985: let ccache preserve C++ comments, because some of them may be
     # meaningful to the compiler
     set(ENV{CCACHE_COMMENTS} "1")
```

**Comment by pitrou** [comment]
That would be fine with me, I just don't know why we didn't just do that initially.

**Comment by pitrou** [comment]
@github-actions crossbow submit -g cpp

**Comment by pitrou** [comment]
@kou Does this look ok now?

**Review by kou — APPROVED** [review]
+1

> Edit: perhaps because that property appeared in CMake 3.4?

Yes.

**Pull request closed without merging**
