### PR TITLE
ARROW-17040: [Go] Add a new StructBuilder constructor to support some specific use cases

### PR DESCRIPTION
**Pull request by lquerel**
Currently, the `NewStructBuilder` constructor takes a struct data type and creates the constructor hierarchy itself. While interesting in most cases, this approach is not easy to integrate with some libraries.

This PR introduces a new constructor `UnsafeNewStructBuilderFromFields`. `UnsafeNewStructBuilderFromFields` returns a builder, using the provided memory allocator, the corresponding initialized fields and constructors. This method is unsafe because the caller must ensure that the fields and constructors are compatible and that the builders have the same length. 

Use case: Can be used by libraries that implement their own Arrow builders tree and ensure the validation of fields and builders by themselves.

Jira issue: https://issues.apache.org/jira/browse/ARROW-17040

### CODE REVIEW

**Comment by zeroshade** [comment]
@lquerel Thanks for the contribution! What is the use case for a user to create their own Arrow Builders tree rather than using the provided builders for the specific types?

**Comment by lquerel** [comment]
@zeroshade For example, for conversion libraries that follow a visitor pattern and walk through a columnar data tree generating builders for each column as they go. The output of this visitor will be a list of builders and field definitions. Starting from a builders tree (provided by NewStructBuilder) is not easy to integrate with this type of pattern.

**Comment by zeroshade** [comment]
@lquerel In that situation, couldn't the user just construct the individual columns and then build the final struct column without needing the explicit struct builder? something like:

```go
children := make([]arrow.ArrayData, len(builders))
for i, b := range builders {
    arr := b.NewArray()
    defer arr.Release()
    children[i] = arr.Data()
}

data := array.NewData(arrow.StructOf(fields...), children[0].Len(), []*memory.Buffers{nil, nil}, children, 0, 0)
defer data.Release()
final := array.NewStructData(data)
```

the `StructBuilder` is really just a convenience wrapper around a slice of builders and building the top level null-bitmap. So, if you have the slice of builders to use your this new Unsafe function then you have one of two situations:

1. you have the type information already (from however you constructed the builders) and can create the struct type
2. you have already populated the builders, which means you can just grab the final arrays and construct the struct column easily

Worst case, you could turn the above code snippet into a helper function. Does this make sense?

**Comment by lquerel** [comment]
@zeroshade Sorry for the delay. I'm closing this PR as your suggestion worked well in my context.

**Pull request closed without merging**
