### PR TITLE
ARROW-16636: [Rust] Activate several IPC integration tests for rust

### PR DESCRIPTION
**Pull request by viirya**
arrow-rs has fixed severals integration test failures (https://github.com/apache/arrow-rs/issues/1404):

generate_decimal128_case
generate_interval_case
generate_map_case
generate_non_canonical_map_case
generate_nested_large_offsets_case
generate_nested_dictionary_case
generate_unions_case

And this one passes test without any fix:
generate_extension_case

We should activate these IPC integration tests for rust.

### CODE REVIEW

**Comment by viirya** [comment]
cc @alamb

**Comment by viirya** [comment]
Hmm, I ran `archery integration --with-cpp=true --with-rust=true` locally without any issue. I'll look into the difference.

**Comment by viirya** [comment]
I'm in business trip this week. I will have more time to look into this in next week.

**Comment by viirya** [comment]
Regarding the failure `FAILED TEST: decimal Rust producing,  Rust consuming`, it is because Rust performs a decimal check that C++ doesn't. And in the golden file `0.14.1_decimal.gold.json`, there are some values failing this check. I can conform that the test can be passed if removing the check in Rust side.

I propose a quick fix at Rust side to remove it, just following C++ Arrow decimal builder.

**Comment by viirya** [comment]
Yea, `FAILED TEST: decimal Rust producing,  Rust consuming` was fixed now. Continuing looking into remaining two failed cases.

**Comment by viirya** [comment]
For `FAILED TEST: union Rust producing,  Rust consuming`, proposed the fix at https://github.com/apache/arrow-rs/pull/1789

**Comment by viirya** [comment]
@alamb All tests are passed now. Please take a look. Thanks.

**Review by alamb — APPROVED** [review]

**Comment by alamb** [comment]
The arrow repo used to have a different way of merging PRs (using a script) -- let me know if you would like to give it a try or if you would like me to. 🎖️

**Comment by viirya** [comment]
@alamb Thank you. I think you can just merge this.

**Comment by alamb** [comment]
Looking into it

**Comment by alamb** [comment]
Following the process in https://github.com/apache/arrow/tree/master/dev

**Comment by alamb** [comment]
Thanks again @viirya  -- this is a major step forward

**Comment by viirya** [comment]
Thank you @alamb

**Pull request merged**
