### PR TITLE
ARROW-12772: [CI] Merge script test fails due to missing dependency

### PR DESCRIPTION
**Pull request by kszucs**

### CODE REVIEW

**Review by kszucs — COMMENTED** [review]
+1, merging on green

**Comment by lidavidm** [comment]
Oh, sorry, I didn't search hard enough for this -.-

**Comment by kszucs** [comment]
> Oh, sorry, I didn't search hard enough for this -.-

I was unsure whether we should remove six altogether instead, but there could be committers still using python 2.7 in certain platforms (though it should be unlikely).

**Review by kszucs — COMMENTED** [review]
+1, travis failures are unrelated.

**Pull request closed without merging**
