### PR TITLE
ARROW-12281: [JS] Remove shx, trash, and rimraf and update learna for yarn

### PR DESCRIPTION
**Pull request by domoritz**

### CODE REVIEW

**Comment by kou** [comment]
Could you rebase on master?

**Comment by domoritz** [comment]
I merged master.

**Comment by domoritz** [comment]
I also noticed we don't use the `trash` dependency.

**Comment by domoritz** [comment]
We also use shx in https://github.com/apache/arrow/blob/8e43f23dcc6a9e630516228f110c48b64d13cec6/js/gulp/test-task.js.

**Comment by domoritz** [comment]
Fixed https://github.com/apache/arrow/pull/9938#issuecomment-817248164

**Review by trxcllnt — APPROVED** [review]

**Pull request closed without merging**
