### PR TITLE
ARROW-13743: [CI] OSX job fails due to incompatible git and libcurl

### PR DESCRIPTION
**Pull request by kszucs**

### CODE REVIEW

**Comment by kszucs** [comment]
@github-actions crossbow submit -g conda

**Comment by kszucs** [comment]
Though this resolves the immediate build issue, it would be time for another "recipe sync" again. We should start thinking on alternative ways to have nightly conda builds, since it's pretty hard to maintain the vendored feedstock setup (not the recipes themselves). 

@xhochy we could clone the arrow-cpp-feedstock then use the azure templates including the matrices defined therein, though:
- I'm not sure whether we could override matrix parameters like [UPLOAD_PACKAGES](https://github.com/conda-forge/arrow-cpp-feedstock/blob/master/.azure-pipelines/azure-pipelines-linux.yml#L13)
- How future-proof would it be, since the feedstocks keep evolving
- How could we incorporate the arrow-cpp packages to similarly configured r-arrow builds

I'd also consider to just remove the conda package builds altogether, and turn the conda-forge build validation to a release task where we would try to build the RC directly in the feedstock. 

cc @nealrichardson

**Review by pitrou — APPROVED** [review]

**Comment by xhochy** [comment]
> I'd also consider to just remove the conda package builds altogether, and turn the conda-forge build validation to a release task where we would try to build the RC directly in the feedstock.

Please don't do that :( We use the conda packages in several places for testing, this would break a lot of testing of upstream packages against arrow nightlies.

Cloning the feedstock could be an option, one thing we wanted to do then would be to change some values in `conda-forge.yml` to upload to different channels and rerender using `conda-smithy`.

**Comment by kszucs** [comment]
> Please don't do that :( We use the conda packages in several places for testing, this would break a lot of testing of upstream packages against arrow nightlies.

Good to know that :)

> 
> Cloning the feedstock could be an option, one thing we wanted to do then would be to change some values in `conda-forge.yml` to upload to different channels and rerender using `conda-smithy`.

Perhaps we could create an apache artifactory repository for the nightlies?

**Pull request closed without merging**
