### PR TITLE
GH-43467: [C++] Add support for the official LZ4 CMake package

### PR DESCRIPTION
**Pull request by kou**
### Rationale for this change

LZ4 1.10.0 provides `LZ4::lz4` but LZ4 1.9.4 provides only `LZ4::lz4_shared` and `LZ4::lz4_static`. So we need to prepare `LZ4::lz4` in our side.

### What changes are included in this PR?

Define `LZ4::lz4` by `LZ4::lz4_shared` or `LZ4::lz4_static` if `LZ4::lz4` doesn't exist.

### Are these changes tested?

Yes.

### Are there any user-facing changes?

Yes.
* GitHub Issue: #43467

### CODE REVIEW

**Comment by kou** [comment]
@github-actions crossbow submit -g linux

**Comment by assignUser** [comment]
@github-action crossbow submit r-binary-packages

**Comment by kou** [comment]
@github-actions crossbow submit debian-* ubuntu-*

**Comment by kou** [comment]
+1

**Review by assignUser — APPROVED** [review]

**Comment by jonkeane** [comment]
Thanks for this! I've been attempting to replicate the CRAN issue locally and this look like it will work (though I haven't yet gotten a full success yet due to other unrelated AWS dependency issues. I'll cherry pick it to our maintenance branch there and test again tomorrow morning

**Pull request merged**
