### PR TITLE
ARROW-742: [C++] std::wstring_convert exceptions handling

### PR DESCRIPTION
**Pull request by maxhora**

### CODE REVIEW

**Comment by wesm** [comment]
Can you rebase this (I rebased master after 0.4.1 vote passed)?

**Comment by MaxRis** [comment]
@wesm , rebased

**Review by wesm — COMMENTED** [review]
Can you add a unit test that hit this code path?

**Comment by MaxRis** [comment]
good idea, will add

**Comment by MaxRis** [comment]
@wesm , have added unit tests to throw range exception on using `FileOutputStream` and `ReadableFile` file classes to test `FileOpenReadable` and `FileOpenWritable` inner method

**Comment by MaxRis** [comment]
@wesm , this time ci builds should pass, could you please take a look, thanks!

**Review by wesm — APPROVED** [review]
+1, thanks @MaxRis!

**Pull request closed without merging**
