### PR TITLE
ARROW-5369: [C++] Add support for glog on Windows

### PR DESCRIPTION
**Pull request by kou**
Windows doesn't have sigaction() but has signal().

glog also uses signal():
https://github.com/google/glog/blob/master/src/signalhandler.cc#L390

### CODE REVIEW

**Comment by kou** [comment]
Umm. This is buildable but test is failed. Why?

https://ci.appveyor.com/project/ApacheSoftwareFoundation/arrow/builds/24639044/job/munbig5qtkfxuqqc#L1553

```text
64/80 Test #65: parquet-column_reader-test .........***Failed    0.04 sec
Running main() from C:/repo/mingw-w64-gtest/src/googletest-release-1.8.1/googletest/src/gtest_main.cc
[==========] Running 6 tests from 2 test cases.
[----------] Global test environment set-up.
[----------] 5 tests from TestPrimitiveReader
[ RUN      ] TestPrimitiveReader.TestInt32FlatRequired
[       OK ] TestPrimitiveReader.TestInt32FlatRequired (0 ms)
[ RUN      ] TestPrimitiveReader.TestInt32FlatOptional
[       OK ] TestPrimitiveReader.TestInt32FlatOptional (0 ms)
[ RUN      ] TestPrimitiveReader.TestInt32FlatRepeated
[       OK ] TestPrimitiveReader.TestInt32FlatRepeated (0 ms)
[ RUN      ] TestPrimitiveReader.TestInt32FlatRequiredSkip
[       OK ] TestPrimitiveReader.TestInt32FlatRequiredSkip (0 ms)
[ RUN      ] TestPrimitiveReader.TestDictionaryEncodedPages
libunwind: _Unwind_Resume C:/repo/mingw-w64-clang/src/llvm-7.0.1.src/projects/libunwind/src/UnwindLevel1.c:391 - _Unwind_Resume() can't return
This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
```

I'll disable glog on AppVeyor for now.

**Comment by wesm** [comment]
That's strange, I'm not sure what could be happening

**Review by wesm — APPROVED** [review]
+1. I'll open an issue on the glog-feedstock to see if anyone knows what is wrong

**Comment by wesm** [comment]
Oh hmm it's not related to the conda-forge build. Any ideas about where to seek help with this?

**Comment by kou** [comment]
I'll try running these failed Parquet tests on `gdb` on MSYS2.

I've opened a issue for this: https://issues.apache.org/jira/browse/PARQUET-1584

**Pull request closed without merging**
