### PR TITLE
ARROW-5198: [JAVA] add hasNull flag to Vectors

### PR DESCRIPTION
**Pull request by yuruiz**
- Add hasNull flag to BaseFixedWidthVector, BaseVariableWidthVector, FixedSizeListVector and ListVector to indicate if current vector has null or not.
- Skip null checking if hasNull flag is false
- When vector transfer occurs, transfer hasNull flag as well
- Move setNull method from the subclass of BaseFixedWidthVector to BaseFixedWidthVector

### CODE REVIEW

**Comment by fsaintjacques** [comment]
If vectors are immutable, why don't you memoize the null count like in the C++ side? That'll make the getNullCount faster while providing the same functionality.

**Comment by jacques-n** [comment]
Can you please start on this list to discussion changes on the hot code path before you start working on them? Thanks

**Comment by yuruiz** [comment]
> If vectors are immutable, why don't you memoize the null count like in the C++ side? That'll make the getNullCount faster while providing the same functionality.

@fsaintjacques For what I understand, in C++ the Arrow Arrays represent immutable data and do not provide update accessors. However, in Java the Arrow ValueVector is not the case, it indeed provides the update accessor that allow external consumer to update values. So it makes no sense to memorize the null count since the value can be invalid after user updates.

**Comment by yuruiz** [comment]
> Can you please start on this list to discussion changes on the hot code path before you start working on them? Thanks

Hi @jacques-n , not sure I understand what mean here. The purpose of this PR is to remove unnecessary null check when there is no null in current vector.  In vectorized data processing, accessing data via get accessor is a high frequency operation and we want to make sure to remove all the redundant operation from the code path. Is that answer your question?

**Comment by fsaintjacques** [comment]
Then if vectors are not immutable, your implementation of hasNull memoization is also prone to invalidation, i.e. hasNull has to be recomputed every time a value is set (since it can flip the last null to non-null)?

**Comment by jacques-n** [comment]
> > Can you please start on this list to discussion changes on the hot code path before you start working on them? Thanks
> 
> Hi @jacques-n , not sure I understand you question here. The purpose of this PR is to remove unnecessary null check when there is no null in current vector. In vectorized data processing, accessing data via get accessor is a high frequency operation and we want to make sure to remove all the redundant operation from the code path. Is that answer your question?

You're assuming a certain usage of the API and changing the hot path of the code. As @fsaintjacques points out, given the the vectors are mutable, the behavior of this patch can also lead to returning wrong result. 

Earlier versions of the vector classes had specialized classes specifically for this purpose however we decided that the extra complexity was not something that was worth maintaining as specific memory algorithms that can take advantage of this will likely interact with memory directly as opposed always through the vector interface, such as the [pivot algorithm we implemented|https://github.com/dremio/dremio-oss/blob/master/sabot/kernel/src/main/java/com/dremio/sabot/op/common/ht2/Pivots.java].

So my comment was really about the idea that for fundamental hot-path changes like this, you should discuss the requirements you're trying to resolve and your idea around possible changes on the mailing list before coding something up. It will likely save you some time.

-1 on this in general

**Pull request closed without merging**
