### PR TITLE
ARROW-6096: [C++] conditionally use boost regex for gcc < 4.9

### PR DESCRIPTION
**Pull request by hatemhelal**
I did a quick test of this on mac and verified that the parquet shared library no longer depends on the boost regex lib.

### CODE REVIEW

**Comment by hatemhelal** [comment]
I don't think this is quite right since the arrow library depends on boost regex:

```
otool -L debug/libarrow.100.0.0.dylib
debug/libarrow.100.0.0.dylib:
	@rpath/libarrow.100.dylib (compatibility version 100.0.0, current version 100.0.0)
	/usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/opt/openssl/lib/libssl.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/opt/glog/lib/libglog.0.dylib (compatibility version 0.0.0, current version 0.4.0)
	/usr/local/opt/lz4/lib/liblz4.1.dylib (compatibility version 1.0.0, current version 1.9.1)
	/usr/local/opt/snappy/lib/libsnappy.1.dylib (compatibility version 1.0.0, current version 1.1.7)
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.11)
	/usr/local/opt/zstd/lib/libzstd.1.dylib (compatibility version 1.0.0, current version 1.4.1)
	/usr/local/opt/boost/lib/libboost_system-mt.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/local/opt/boost/lib/libboost_filesystem-mt.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/local/opt/boost/lib/libboost_regex-mt.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 400.9.4)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.200.5)
```

**Comment by hatemhelal** [comment]
Latest commit is a bit speculative but it seems ok to remove the runtime dependency on boost regex from libarrow since the only usage of the boost regex library was in [cpp/src/parquet/metadata.cc](https://github.com/apache/arrow/blob/eb73b962e42b5ae6983bf026ebf825f1f707e245/cpp/src/parquet/metadata.cc#L32)

**Comment by fsaintjacques** [comment]
Since we might have version conflicts (gcc-4.8?), is the effort justified to just write a string parsing function? The pattern is regular and can be done in a single pass.

**Review by wesm — APPROVED** [review]
+1

Travis build: https://travis-ci.org/mathworks/arrow/builds/566572411

I can live with this but I agree w/ @fsaintjacques it would probably be better to remove the regex dependency altogether. I wouldn't go out of anyone's way to deal with this right now though

**Comment by hatemhelal** [comment]
Created this task to remove the regex dependency:

https://issues.apache.org/jira/browse/PARQUET-1639

**Pull request closed without merging**
