### PR TITLE
ARROW-10786: [Packaging][RPM] Drop support for CentOS 6

### PR DESCRIPTION
**Pull request by kou**
Because CentOS 6 reached EOL at 2020-11-30.

### CODE REVIEW

**Comment by kou** [comment]
@github-actions crossbow submit centos-*

**Comment by kou** [comment]
+1

**Comment by nealrichardson** [comment]
Thanks @kou! At some point (I guess for the next release) https://github.com/apache/arrow-site/blob/master/install.md should get updated too.

**Comment by kou** [comment]
I'll do in the next release process.
I'll also drop support for Debian GNU/Linux Stretch.

**Pull request closed without merging**
