### PR TITLE
GH-35922: [C++] Drop support for Debian GNU/Linux buster (10)

### LINKED ISSUE #35922: [C++] Drop support for Debian GNU/Linux buster (10)
### Describe the enhancement requested

Debian GNU/Linux buster reached EOL on 2022-09-10:

https://wiki.debian.org/DebianReleases

> Version | Code name | Release date | End of life date | EOL LTS | EOL ELTS
> -- | -- | -- | -- | -- | --
> 10 | Buster | 2019-07-06 | 2022-09-10 | 2024-06-30

### Component(s)

C++, Packaging

### PR DESCRIPTION
**Pull request by kou**
### Rationale for this change

Because Debian GNU/Linux buster reached EOL on 2022-09-10.

### What changes are included in this PR?

Removed Debian GNU/Linux buster related codes.

### Are these changes tested?

Yes.

### Are there any user-facing changes?

Yes.
* Closes: #35922

### CODE REVIEW

**Comment by kou** [comment]
@github-actions crossbow submit -g nightly-tests -g nightly-packaging -g nightly-release

**Review by assignUser — APPROVED** [review]
Nice!

**Comment by assignUser** [comment]
Actually there seem to be some rake fails when running docker for integration tests IIUC https://github.com/ursacomputing/crossbow/actions/runs/5183462378/jobs/9341385916#step:9:5900

Maybe it's using the debian 10 dockerfile?

**Comment by kou** [comment]
It doesn't use Debian GNU/Linux 10: https://github.com/ursacomputing/crossbow/actions/runs/5183462378/jobs/9341385916#step:9:150

```text
#8 0.554 Get:1 http://deb.debian.org/debian bookworm InRelease [193 kB]
``` 

"bookworm" is 12.

I think that it's failed because storage is full...

**Comment by kou** [comment]
I'll merge this in this week if nobody objects this.

**Comment by kou** [comment]
I merge this.

**Pull request merged**
