### PR TITLE
ARROW-11190: [C++] Clean up compiler warnings

### PR DESCRIPTION
**Pull request by bkietz**
Some unused variables:
- https://github.com/apache/arrow/runs/1669466544#step:8:1434

Some maybe uninitialized:
- https://github.com/apache/arrow/runs/1669466544#step:8:1498

### CODE REVIEW

**Comment by bkietz** [comment]
non-apache CI: https://github.com/bkietz/arrow/runs/1670186905

**Comment by nealrichardson** [comment]
https://github.com/bkietz/arrow/runs/1670186993 shows a couple of other warnings still, though they're not related to the recent dataset work

**Comment by bkietz** [comment]
@nealrichardson not sure how to resolve those warnings

**Comment by nealrichardson** [comment]
Ok

**Pull request closed without merging**
