### PR TITLE
ARROW-7999: [C++] Fix crash on corrupt List / Map array input

### PR DESCRIPTION
**Pull request by pitrou**
Found by OSS-Fuzz. Should fix the following issues:
* https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=20284
* https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=21039

### CODE REVIEW

**Comment by pitrou** [comment]
AppVeyor build: https://ci.appveyor.com/project/pitrou/arrow/builds/31236073

**Comment by pitrou** [comment]
cc @wesm @emkornfield

**Comment by pitrou** [comment]
Will merge if no-one comments on this. @xhochy

**Comment by xhochy** [comment]
@pitrou To review this it would be interesting for me where this did crash.

**Comment by pitrou** [comment]
Ok, I sent them privately. Also, if you want to be able to view the issues on OSS-Fuzz, you can tell me a Google account to add to https://github.com/google/oss-fuzz/blob/master/projects/arrow/project.yaml

**Review by xhochy — APPROVED** [review]
+1, LGTM. Thanks for the reports

**Pull request closed without merging**
