### PR TITLE
ARROW-7620: [Rust] Remove call to flatc

### PR DESCRIPTION
**Pull request by andygrove**
The Rust build was calling `rustc` to generate code from the flatbuffers files, and this recently stopped working on Windows (about a week ago) and I'm not sure why.

This was a work-in-progress anyway that was never completed. To generate working code we would have to follow the steps in https://github.com/apache/arrow/blob/master/rust/arrow/regen.sh to add the necessary imports to the generated code.

I suggest we just remove this for now since the generated code doesn't have any impact on the project (the files had the `_generated` suffix and were not referenced in any `mod.rs`).

### CODE REVIEW

**Comment by nevi-me** [comment]
I was taking the approach of creating a `build.rs` file, but I think removing the call is fine.

Do we need to install flatc in CI though? Given that the fbs files don't change frequently, I think we could regenerate them when necessary, and not install flatc in CI.

**Comment by andygrove** [comment]
I think the best approach would be to use `build.rs` even though that would require devs to have flatbuffers installed to be able to build the project. I can create a new JIRA for that.

**Comment by nevi-me** [comment]
I think so too, but at the same time I think it's done added overhead to keep regenerating files that rarely change. Please have a look at my WIP PR, where I had started with the approach.

The regen.sh script uses `sed`, which I found out last night to take different arguments depending on which platform it runs under.
We'd also need to add a flatc installation to the Ursabot build script.

There might already be a JIRA about automatically building files, I'll look for it first.

**Review by nevi-me — APPROVED** [review]

**Comment by paddyhoran** [comment]
I was going to start looking into this also.  Maybe we should add the `build.rs` and only have it re-generate based on a feature flag (and leave this off by default and in CI)?

Having it on all the time seem to have it's issues:
 - installing flatc in CI
 - building the project for new contributors

**Pull request closed without merging**
