### PR TITLE
ARROW-3942: [R] Feather api fixes

### PR DESCRIPTION
**Pull request by romainfrancois**
Some fixes  to follow up open #3043, and added the columns argument to `read_feather` that can be: 

 - character vector
 - integer vector : 1-based in R
 - NULL: to get all columns (the default)

Also adds `as_tibble` argument to read_feather to switch between data.frame and arrow::Table return value

### CODE REVIEW

**Comment by wesm** [comment]
I had suggested having an `as_tibble = TRUE` (or `as_arrow = FALSE`) argument in `read_feather` to preserve the default behavior of `feather::read_feather`. Thoughts?

**Comment by romainfrancois** [comment]
Then I suppose it would also need use_threads. This only apply to the conversion right ?

**Comment by wesm** [comment]
Reading to an Arrow table is zero-copy when the input is a memory map -- the use_threads is only for parallelizing conversions to pandas. Have you looked at parallelizing the equivalent conversions in R? https://issues.apache.org/jira/browse/ARROW-3315 (there is a companion issue for parallelizing the other direction)

**Comment by romainfrancois** [comment]
Not yet. at the moment focusing on the vignette and fixing things independent pr as needed

**Review by wesm — APPROVED** [review]
+1. Thanks @romainfrancois!

**Comment by wesm** [comment]
Build fails due to

```
0.78schecking Rd cross-references ... WARNING
Missing link or links in documentation object 'read_feather.Rd':
  ‘feather_table_reader’
See section 'Cross-references' in the 'Writing R Extensions' manual.
checking installed package size ... NOTE
  installed size is 11.9Mb
  sub-directories of 1Mb or more:
    libs  10.0Mb
    R      1.7Mbchecking S3 generic/method consistency ... NOTE
Found the following apparent S3 methods exported but not registered:
  print.integer64 str.integer64
See section ‘Registering S3 methods’ in the ‘Writing R Extensions’
manual.
```

merge after fixing this

**Comment by wesm** [comment]
Thank you. merging

**Pull request closed without merging**
