### PR TITLE
ARROW-11766: [R] Better handling for missing compression codecs on Linux

### PR DESCRIPTION
**Pull request by pachadotdev**

### CODE REVIEW

**Comment by jonkeane** [comment]
I suspect the CI failures are related to what was resolved in #9868, so you could try to rebase to get rid of those.

I also see a number of comments from the now closed #9743 that haven't yet been addressed in this branch/PR would you mind looking at those, addressing them and letting us know when this is ready for re-review?

**Comment by pachamaltese** [comment]
> I suspect the CI failures are related to what was resolved in #9868, so you could try to rebase to get rid of those.
> 
> I also see a number of comments from the now closed #9743 that haven't yet been addressed in this branch/PR would you mind looking at those, addressing them and letting us know when this is ready for re-review?

thanks, I shall write a list here

**Comment by pachamaltese** [comment]
List of TODOs:

- [ ] rebase with #9868
- [ ] check that pets.parquet is not used in  r/tests/testthat/test-parquet.R (https://github.com/apache/arrow/pull/9743#discussion_r597270252)
- [ ] check skip_on_cran() in r/tests/testthat/test-feather.R (https://github.com/apache/arrow/pull/9743#discussion_r598966595)
- [ ] check skip_if() in  r/tests/testthat/test-parquet.R (https://github.com/apache/arrow/pull/9743#discussion_r606390457)

**Comment by pachamaltese** [comment]
gonna need new PR :S

**Pull request closed without merging**
