### PR TITLE
WIP: [R] Verify CRAN release-18.0.0-rc0

### PR DESCRIPTION
**Pull request by amoeba**
Only using this to trigger crossbow jobs for the CRAN release. Do not merge.

### CODE REVIEW

**Comment by amoeba** [comment]
@github-actions crossbow submit -g r

**Comment by amoeba** [comment]
@github-actions crossbow submit r-recheck-*

**Comment by amoeba** [comment]
The couple of job failures I see so far look fine for the moment. And revdepcheck looks clean. I'll let the others run and go from there.

**Comment by amoeba** [comment]
@github-actions crossbow submit -g r

**Comment by amoeba** [comment]
Crossbow jobs are looking good now but `test-r-linux-as-cran` is failing on what appears to be downloading Thrift. I took a look at the logs and it looks like it's trying a few mirrors, failing on each, and not trying the rest? According to the cmake docs, all of them should get tried. @assignUser do you have any ideas?

**Comment by amoeba** [comment]
@github-actions crossbow submit r-recheck-*

**Comment by jonkeane** [comment]
On the thrift timeout, I just tried each of the URLs that are listed in the logs and while the first one did work for me right now, all the rest 404ed. Which makes me think that something might be wrong with those URLs and we should update them so that we have backups again:

```
-- Downloading...
   dst='/tmp/RtmpAwPrlt/working_dir/RtmpBltHq0/file743780f417a/thrift_ep-prefix/src/thrift-0.16.0.tar.gz'
   timeout='none'
   inactivity timeout='none'
-- Using src='https://www.apache.org/dyn/closer.cgi?action=download&filename=/thrift/0.16.0/thrift-0.16.0.tar.gz'
-- Using src='https://downloads.apache.org/thrift/0.16.0/thrift-0.16.0.tar.gz'
-- Using src='https://apache.claz.org/thrift/0.16.0/thrift-0.16.0.tar.gz'
-- Using src='https://apache.cs.utah.edu/thrift/0.16.0/thrift-0.16.0.tar.gz'
-- Using src='https://apache.mirrors.lucidnetworks.net/thrift/0.16.0/thrift-0.16.0.tar.gz'
-- Using src='https://apache.osuosl.org/thrift/0.16.0/thrift-0.16.0.tar.gz'
-- [download 0% complete]
-- Using src='https://apache.cs.utah.edu/thrift/0.16.0/thrift-0.16.0.tar.gz'
-- Using src='https://apache.mirrors.lucidnetworks.net/thrift/0.16.0/thrift-0.16.0.tar.gz'
-- Using src='https://ftp.wayne.edu/apache/thrift/0.16.0/thrift-0.16.0.tar.gz'
-- [download 0% complete]
-- Using src='https://apache.cs.utah.edu/thrift/0.16.0/thrift-0.16.0.tar.gz'
-- Using src='https://apache.mirrors.lucidnetworks.net/thrift/0.16.0/thrift-0.16.0.tar.gz'
-- Using src='https://mirror.olnevhost.net/pub/apache/thrift/0.16.0/thrift-0.16.0.tar.gz'
-- [download 0% complete]
```

**Comment by amoeba** [comment]
Oh, you're right. I think only the closer.cgi one works for me. I'll look into that.

**Comment by amoeba** [comment]
Some observations:

- downloads.apache.org only has archives of Thrift 0.20.0 and 0.21.0 (current latest stable is 0.21.0)
- Apache appears to now (since 2021?) [have a CDN](https://apache.org/history/mirror-history.html): https://dlcdn.apache.org/thrift/. That also only has archives of 0.20.0 and 0.21.0.

https://apache.org/history/mirror-history.html gives more context and this sentence may explain why this list of URLs degraded over time:

> Any organization that has been hosting an Apache download mirror site, and that finds it useful for its own purposes, may continue to host the mirror site. 

So I think by continuing to use these mirror URLs we were living on borrowed time. The CDN is now the recommended way for users to download content from ASF projects.

So I think we actually need to do two things here:

- Change the URL to just use the ASF CDN
- Update our Thrift version in cpp/thirdparty/versions.txt to 0.20.0 or greater. Arrow C++ builds cleanly on my system when using Brew-provided Thrift 0.21.0 so it seems like this may be doable.

**Comment by amoeba** [comment]
We also use https://archive.apache.org/dist/thrift/ which has older versions (including 0.16.0), though I'm not sure if using it is appropriate.

**Comment by assignUser** [comment]
@amoeba yes we can use archive.a.o if we need an older version but imo if a newer version works we should update, I will create a blocker issue for 18.0.1

**Comment by amoeba** [comment]
Thanks @assignUser!

**Comment by amoeba** [comment]
Closing as we're done with this PR now. See https://github.com/apache/arrow/issues/44496 for context.

**Pull request closed without merging**
