### PR TITLE
ARROW-6186: [Packaging][deb] Add missing headers to libplasma-dev for Ubuntu 16.04

### PR DESCRIPTION
**Pull request by kou**

### CODE REVIEW

**Comment by kou** [comment]
@ursabot crossbow package ubuntu-xenial

**Comment by kou** [comment]
@kszucs The Travis CI status link in https://github.com/apache/arrow/pull/5050#issuecomment-520100084 is broken.

Wrong link: https://travis-ci.org/https://github.com/ursa-labs/crossbow/branches

**Comment by kou** [comment]
https://github.com/ursa-labs/crossbow/releases/download/ursabot-132-travis-ubuntu-xenial/libplasma-dev_0.14.0.dev246-1_amd64.deb includes `/usr/include/plasma/`.

**Review by kszucs — APPROVED** [review]

**Comment by kszucs** [comment]
@kou thanks for letting me know, created an ursabot issue https://github.com/ursa-labs/ursabot/issues/155

**Comment by kou** [comment]
Oh, sorry...
https://issues.apache.org/jira/browse/ARROW-6186 is right.

**Pull request closed without merging**
