### PR TITLE
GH-33934: [Packaging][Linux] Enable Flight for arm64

### LINKED ISSUE #33934: [Packaging] Installation of "libarrow-flight-dev" package fails on Debian/Ubuntu arm64 platform
### Describe the bug, including details regarding any error messages, version, and platform.

When attempting to install package: libarrow-flight-dev in a container running Docker image: ubuntu:latest on the **linux/arm64** platform - it fails with error:

```
The following packages have unmet dependencies:
 libarrow-flight-dev : Depends: libarrow-dev (= 9.0.0-1) but 11.0.0-1 is to be installed
E: Unable to correct problems, you have held broken packages.
```

To reproduce the issue - I run these commands on my M1 (arm64) MacBook Pro from a terminal:
```
docker run -it --entrypoint /bin/bash --platform linux/arm64 ubuntu:latest

# Then in the container - run:
apt update && \
apt install -y -V ca-certificates sudo wget lsb-release && \
wget https://apache.jfrog.io/artifactory/arrow/$(lsb_release --id --short | tr 'A-Z' 'a-z')/apache-arrow-apt-source-latest-$(lsb_release --codename --short).deb && \
apt install -y -V ./apache-arrow-apt-source-latest-$(lsb_release --codename --short).deb && \
apt update && \
apt install -y -V libarrow-flight-dev
```

If I run with the **linux/amd64** platform - however - the script above works just fine.

I hit this issue when attempting to build an arm64 Docker container (trying to follow instructions here: https://arrow.apache.org/install/)

Thank you!

### Component(s)

Packaging

### PR DESCRIPTION
**Pull request by kou**
### Rationale for this change

We can't enable Flight for arm64 packages because Travis CI doesn't have enough resource.

If we use self-hosted arm64 GitHub Runner, we can enable Flight.

### What changes are included in this PR?

These changes use self-hosted arm64 GitHub Runner and enable Flight.
 
### Are these changes tested?

Yes.

### Are there any user-facing changes?

Yes.
* Closes: #33934

### CODE REVIEW

**Comment by kou** [comment]
@github-actions crossbow submit -g linux

**Comment by kou** [comment]
@github-actions crossbow submit almalinux-8-*

**Comment by kou** [comment]
@github-actions crossbow submit almalinux-8-*

**Comment by kou** [comment]
@github-actions crossbow submit almalinux-8-*

**Comment by kou** [comment]
@github-actions crossbow submit debian-bullseye-*

**Comment by kou** [comment]
@github-actions crossbow submit debian-bullseye-*

**Comment by kou** [comment]
@raulcd It seems that self-hosted arm64 GitHub Actions Runner doesn't work:  https://github.com/ursacomputing/crossbow/actions/runs/4527627095/jobs/7973655317
Could you check this?

It worked 3 days ago: https://github.com/ursacomputing/crossbow/actions/runs/4511211696/jobs/7943091712

**Comment by amaldonadomat** [comment]
hello @kou 
It should be working now, sorry for the inconvenience!

**Comment by kou** [comment]
@github-actions crossbow submit debian-bullseye-*

**Comment by kou** [comment]
@github-actions crossbow submit debian-bullseye-*

**Comment by kou** [comment]
@github-actions crossbow submit debian-bullseye-*

**Comment by kou** [comment]
@github-actions crossbow submit debian-bullseye-arm64

**Comment by kou** [comment]
@github-actions crossbow submit debian-bullseye-*

**Comment by kou** [comment]
@github-actions crossbow submit -g linux

**Comment by kou** [comment]
@amaldonadomat Can we use Ubuntu 22.04 instead of Ubuntu 20.04 for self-hosted arm64 runner? If we can use Ubuntu 22.04, our CI script can be simplified because Ubuntu 22.04 or later provides the `createrepo-c` package: https://packages.ubuntu.com/search?keywords=createrepo-c

(We can use Ubuntu 20.04 for this case because we can build createrepo-c manually. So this is not a blocker.)

**Comment by amaldonadomat** [comment]
@kou For sure, I've updated the runner image used and now it's using 22.04 on Crossbow. I ran this [job](https://github.com/ursacomputing/crossbow/actions/runs/4552249334/jobs/8027347062) on a testing branch and it seems to be working fine

**Comment by kou** [comment]
@amaldonadomat Thanks!!!

**Comment by kou** [comment]
@github-actions crossbow submit debian-bullseye-*

**Comment by kou** [comment]
@github-actions crossbow submit debian-bullseye-arm64

**Comment by kou** [comment]
@github-actions crossbow submit debian-bullseye-arm64

**Comment by kou** [comment]
@github-actions crossbow submit debian-bullseye-arm64

**Comment by kou** [comment]
@github-actions crossbow submit -g linux

**Comment by amaldonadomat** [comment]
hello @kou 
I've been doing a better adjustment of the pods to the resources in the nodes, so that we can have more jobs in parallel given the resources. Let me know if you find something not working as expected or slow, I hope this helps speeding up the runs

**Comment by kou** [comment]
@amaldonadomat Wow! Thanks!!!

**Comment by kou** [comment]
+1

**Pull request merged**
