### PR TITLE
ARROW-11222: [Rust] Catch up with flatbuffers 0.8.1 which had some UB problems fixed

### PR DESCRIPTION
**Pull request by mqy**
The major change of [flatbuffers 0.8.1](https://docs.rs/flatbuffers/0.8.1/flatbuffers/index.html) since 0.8.0 is https://github.com/google/flatbuffers/pull/6393, which fixed some possible memory alignment issues.

In this PR, the ipc/gen/*.rs files are generated by `regen.sh` as before, without any manual change.

### CODE REVIEW

**Comment by mqy** [comment]
The crate `flatbuffers` is not pinned to `0.8.1`, so let's  run `cargo update` to pull it locally.

**Review by andygrove — APPROVED** [review]
LGTM. Thanks @mqy

**Comment by alamb** [comment]
I suggest we hold off merging this PR until the Arrow 3.0 release is completed (happening in the next day or two) to minimize the chance we break something right before the release

**Comment by mqy** [comment]
> I suggest we hold off merging this PR until the Arrow 3.0 release is completed (happening in the next day or two) to minimize the chance we break something right before the release

@alamb thanks for the review! Since there are no direct evidence that this PR can fix something in arrow, it's OK to me to hold off merging this PR.

BTW, I've exploring the cause of `test_struct` test failure for several days, filed several issues, but can't figure out the exact reason. The latest issue is filed and commented at https://issues.apache.org/jira/projects/ARROW/issues/ARROW-11239. It looks like `ArrayRef::slice()` is not bug-free. I suggest you evaluate this problem seriously before the 3.0 release. 

CC @jorgecarleitao I'm glad if you can take time for this possible problem at this weekend, as you said :)

**Comment by alamb** [comment]
I apologize for the delay in merging Rust PRs -- the 3.0 release is being finalized now and are planning to minimize entropy by postponing merging  changes not critical for the release until the process was complete. I hope the process is complete in the next few days. There is more [discussion](https://lists.apache.org/list.html?dev@arrow.apache.org) in the mailing list

**Comment by mqy** [comment]
> I apologize for the delay in merging Rust PRs 

@alamb I understand the common releasing process that freezes pushing/merging unless for those fully tested or fatal bug fix, this is really important. You are welcome, no need to apologize at all 👍

**Comment by alamb** [comment]
I merged this branch (locally) to master and re-ran the tests to verify things still work. Everything still looks good, so merging it in.

**Pull request closed without merging**
