### PR TITLE
GH-38823: Fix TestArrowReaderAdHoc.ReadFloat16Files to use new uncompressed files

### LINKED ISSUE #38823: [C++][Parquet] Skip TestArrowReaderAdHoc.ReadFloat16Files when snappy is not built
### Describe the bug, including details regarding any error messages, version, and platform.

https://github.com/ursacomputing/crossbow/actions/runs/6943255937/job/18887922572 failed with following error:
```
[ RUN      ] TestArrowReaderAdHoc.ReadFloat16Files
/arrow/cpp/src/parquet/arrow/arrow_reader_writer_test.cc:4129: Failure
Failed
'reader->ReadTable(&table)' failed with NotImplemented: Support for codec 'snappy' not built
Google Test trace:
/arrow/cpp/src/parquet/arrow/arrow_reader_writer_test.cc:4123: path = /arrow/cpp/submodules/parquet-testing/data/float16_nonzeros_and_nans.parquet
[  FAILED  ] TestArrowReaderAdHoc.ReadFloat16Files (1 ms)
[----------] 6 tests from TestArrowReaderAdHoc (11 ms total)
```

### Component(s)

C++, Parquet

### PR DESCRIPTION
**Pull request by wgtmac**
### Rationale for this change

[ RUN      ] TestArrowReaderAdHoc.ReadFloat16Files
/arrow/cpp/src/parquet/arrow/arrow_reader_writer_test.cc:4129: Failure
Failed
'reader->ReadTable(&table)' failed with NotImplemented: Support for codec 'snappy' not built
Google Test trace:
/arrow/cpp/src/parquet/arrow/arrow_reader_writer_test.cc:4123: path = /arrow/cpp/submodules/parquet-testing/data/float16_nonzeros_and_nans.parquet
[  FAILED  ] TestArrowReaderAdHoc.ReadFloat16Files (1 ms)
[----------] 6 tests from TestArrowReaderAdHoc (11 ms total)

### What changes are included in this PR?

Use uncompressed files from parquet-testing.

### Are these changes tested?

Make sure the test does not fail.

### Are there any user-facing changes?

No
* Closes: #38823

### CODE REVIEW

**Comment by pitrou** [comment]
Could we instead regenerate the data files to not use any compression?

**Comment by mapleFU** [comment]
Does it has any rules for these codec in parquet-testing? Seems brotli, lz4/lz4_raw, zstd, snappy are all used there...

**Comment by wgtmac** [comment]
@benibus Do you still have the code to generate the file?

**Comment by pitrou** [comment]
@wgtmac Look at https://github.com/apache/parquet-testing/blob/master/data/README.md

**Comment by wgtmac** [comment]
Thanks for the guidance! @pitrou 

Sorry that I'm not that familiar with python. May I request @benibus to re-generate the two float16 parquet files with everything unchanged except setting the codec to none?

**Comment by benibus** [comment]
@wgtmac I've just opened a PR: https://github.com/apache/parquet-testing/pull/42

**Review by mapleFU — APPROVED** [review]

**Comment by wgtmac** [comment]
The CI failure is unrelated. I'll merge it. Thanks @pitrou @benibus @mapleFU!

**Pull request merged**
