### PR TITLE
ARROW-17628: [CI][Packaging][Java] Publish latest nightly with SNAPSHOT version

### PR DESCRIPTION
**Pull request by raulcd**
In order to help automate nightly distribution upload latest nightly with a fix SNAPSHOT version.
The new artifact names will be like:
```
    - flight-integration-tests-10.0.0-SNAPSHOT-tests.jar
    - flight-integration-tests-10.0.0-SNAPSHOT.jar
    - flight-integration-tests-10.0.0-SNAPSHOT.pom
    - flight-sql-10.0.0-SNAPSHOT-javadoc.jar
    - flight-sql-10.0.0-SNAPSHOT-sources.jar
    - flight-sql-10.0.0-SNAPSHOT-tests.jar
    - flight-sql-10.0.0-SNAPSHOT.jar
    - flight-sql-10.0.0-SNAPSHOT.pom
```

### CODE REVIEW

**Comment by raulcd** [comment]
@github-actions crossbow submit java-jars

**Comment by raulcd** [comment]
The comment bot can't handle the changes on this branch as it is uses the archery version from master. I've triggered the job from my own fork, here:
Revision: 4507760544ad74c475018618732ca51972c9e720

Submitted crossbow builds: [ursacomputing/crossbow @ actions-06d7f5e5a1](https://github.com/ursacomputing/crossbow/branches/all?query=actions-06d7f5e5a1)

|Task|Status|
|----|------|
|java-jars|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:actions-06d7f5e5a1-github-java-jars)|

We can see the new artifacts published here with the new naming:
https://github.com/ursacomputing/crossbow/releases?q=actions-06d7f5e5a1-github-java-jars

**Comment by raulcd** [comment]
@kou @assignUser this should be ready for review

**Review by assignUser — APPROVED** [review]
Looks good! Should create a much smoother DX for staying on the bleeding edge of arrow java 👍

**Review by kou — APPROVED** [review]
+1

**Pull request merged**
