### PR TITLE
ARROW-16073: [R] clean-up date time unit testing once tzdb is available on Windows

### PR DESCRIPTION
**Pull request by dragosmg**

### CODE REVIEW

**Comment by jonkeane** [comment]
Would you mind rebasing this and looking into the windows CI failures? We might be too late already, but we really should make sure this is done + more importantly there are no issues before we release

**Comment by dragosmg** [comment]
All window jobs seem to be tripping up in the same spot (involving formats), with the following error message:
```
Invalid: Cannot find locale 'English_United States.1252': locale::facet::_S_create_c_locale name not valid
```

As far as I can tell it has to do with the `format`, in general, and `"%b"` + `"%B"`, in particular, as they rely on the locale in order to figure out the abbreviated / full month names.

**Comment by dragosmg** [comment]
We could link to [ARROW-13133](https://issues.apache.org/jira/browse/ARROW-13133) to solve the remaining locale-related issues. Not sure a new Jira is needed.

**Comment by wjones127** [comment]
> All window jobs seem to be tripping up in the same spot (involving formats)

@dragosmg This is expected. We don't support locales other than the "C" locale, so you can't format timestamps in different locales. From my earlier research, this seems to be an issue with MINGW itself. R gets around this by vendoring the strftime implementation:

> However, not all OSes (notably Windows) provided strptime and many issues were found for those which did, so since 2000 R has used a fork of code from glibc. The forked code uses the system's strftime to find the locale-specific day and month names and any AM/PM indicator.
>
>On some platforms (including Windows and by default on macOS) the system's strftime is replaced (along with most of the rest of the C-level datetime code) by code modified from IANA's tzcode distribution (https://www.iana.org/time-zones).

**Comment by dragosmg** [comment]
Thanks @wjones127 The absence of locale support is showing up in a number of different places (for example, some of the datetime parsing). Do you think it's worth having a separate Jira to discuss locale support? [ARROW-13133](https://issues.apache.org/jira/browse/ARROW-13133) touches on locale, but doesn't go far enough.

**Comment by dragosmg** [comment]
@jonkeane I believe I addressed all comments/suggestions. Would you have time for another look?

**Pull request closed without merging**
