### PR TITLE
ARROW-2434: [Rust] Add windows support

### PR DESCRIPTION
**Pull request by paddyhoran**
I'm not that familiar with JIRA but I believe that I do not have the permission to self-assign this issue.  @andygrove maybe you can assign to me on JIRA please (or let me know if I should be able to self-assign).

I had to expose `_aligned_malloc` and `_aligned_free` but I'm thinking that this should be in _libc_.  This is just to get windows support building.  I'll submit a PR to libc and open another JIRA to clean things up.

### CODE REVIEW

**Comment by andygrove** [comment]
Hi @paddyhoran I tried to assign to you in JIRA but couldn't find your username on there. I think you need to create yourself a JIRA account first and then you should be able to self-assign.

**Review by xhochy — APPROVED** [review]
+1, LGTM

**Comment by paddyhoran** [comment]
@xhochy do you know why I am not listed on the [contributors](https://github.com/apache/arrow/graphs/contributors) page after this getting merged?

**Comment by paddyhoran** [comment]
Ah I see.  Thanks @xhochy, sorry for the silly question...

**Pull request closed without merging**
