### PR TITLE
ARROW-4538: [Python] Remove index column from subschema in write_to_dataframe

### PR DESCRIPTION
**Pull request by c-thiel**
I noticed that `parquet.write_to_dataset` failes if the index name is not None. This is due to `write_to_dataframe` only removing the old `__index_level` prefixed column names.

In this PR I determined the dataframe index names from the metadata just like in `pyarrow.pandas_compat.table_to_blockmanager`. I believe that this is a good thing to do, as the extra trip via pandas in `write_to_dataframe` will hopefully be superfluous in the future.

This is my first contribution to arrow (appart from some issues), so please let me know if this is what you're looking for.

### CODE REVIEW

**Comment by c-thiel** [comment]
Just for documentation purposes, here is some copy and paste code that fails:
```python
import pyarrow as pa
import pyarrow.parquet as pq
import os
import shutil
import pandas as pd
import numpy as np

PATH_PYARROW_MANUAL = '/tmp/pyarrow_manual.pa/'

if os.path.exists(PATH_PYARROW_MANUAL):
    shutil.rmtree(PATH_PYARROW_MANUAL)
os.mkdir(PATH_PYARROW_MANUAL)

arrays = np.array([np.array([0, 1, 2]), np.array([3, 4]), np.nan, np.nan])
df = pd.DataFrame([0, 0, 1, 1], columns=['partition_column'])
df['arrays'] = pd.Series(arrays)

df.index.name='ID'

table = pa.Table.from_pandas(df, preserve_index=True)
print(table.schema.names)

pq.write_to_dataset(table, root_path=PATH_PYARROW_MANUAL, 
                    partition_cols=['partition_column'],
                    preserve_index=True
                   )
```

**Comment by c-thiel** [comment]
I believe the failed test is not due to my change. Please let me know if I can do anything else to fix this.

**Comment by xhochy** [comment]
@c-thiel The code looks good. Thank you for your contribution. Can you rebase on master to get the tests passing? They should be all fine now.

**Comment by c-thiel** [comment]
> 
> 
> @c-thiel The code looks good. Thank you for your contribution. Can you rebase on master to get the tests passing? They should be all fine now.

Looking good now :)

**Review by xhochy — APPROVED** [review]
+1, LGTM

**Pull request closed without merging**
