### PR TITLE
ARROW-1134: [C++] Support for C++/CLI compilation, add NULLPTR define to avoid using nullptr in public headers

### PR DESCRIPTION
**Pull request by wesm**
cc @tobyshaw. Can you test this?

Close #1098

### CODE REVIEW

**Comment by wesm** [comment]
We should probably have some kind of linting script to check that nullptr or `<mutex>` does not creep into a public header. I could write some kind of Python script for this if

**Comment by wesm** [comment]
@xhochy @cpcloud I would suggest we should merge this and wait for more feedback from C++/CLI users

**Comment by wesm** [comment]
In the meantime we'll need to add a linting script so that this work does not get undone by a future patch

**Comment by cpcloud** [comment]
+1 LGTM

**Pull request closed without merging**
