### PR TITLE
ARROW-12094: [C++][R] Fix re2 building on clang/libc++

### PR DESCRIPTION
**Pull request by nealrichardson**
Also includes a followup to ARROW-11736 to add the utf8proc/re2 features to arrow_info() and use that in skip_if_not_available().

### CODE REVIEW

**Comment by nealrichardson** [comment]
@github-actions crossbow submit test-r-linux-as-cran

**Comment by nealrichardson** [comment]
@github-actions crossbow submit test-r-linux-as-cran

**Comment by xhochy** [comment]
@nealrichardson Do you have the error message / build log available?

**Comment by nealrichardson** [comment]
https://github.com/ursacomputing/crossbow/runs/2197449739?check_suite_focus=true#step:7:210 is the failure

**Comment by xhochy** [comment]
The R arrow package is built using `std=gnu11`, if you can try and compile it with `gnu17`, chances are high that you get rid of the error. Where is the C++ part of Arrow built? I cannot find that in the logs.

**Comment by nealrichardson** [comment]
Unfortunately because this is the `as-cran` test job, the C++ build output is suppressed (otherwise CRAN checks fail spuriously). It could be reproduced locally with docker-compose, if it were worthwhile. But we don't require C++ 17 for Arrow, [only C++ 11](https://github.com/apache/arrow/blob/master/r/DESCRIPTION#L24), and we have to use the same compiler settings that R uses in order to avoid compiler mismatch: https://github.com/apache/arrow/blob/master/r/tools/nixlibs.R#L318. So I don't understand how we could compile re2 with gnu17.

**Comment by kou** [comment]
It's caused by ignoring `-stdlib=c++` specified by `CXX` environment variable that is provided by `R CMD config CXX`.
We use `CMAKE_CXX_COMPILER` to tell `CXX` environment variable information to bundled libraries. But it only has compiler path such as `/usr/bin/clang++` in `CXX=/usr/bin/clang++ -std=gnu++14 -stdlib=libc++`. It doesn't have other options such as `-std=gnu++14 -stdlib=libc++`. `CMAKE_CXX_COMPILER_ARG1` has them.

How about passing `CMAKE_CXX_COMPILER_ARG1` information to bundled libraries?

```diff
diff --git a/cpp/cmake_modules/ThirdpartyToolchain.cmake b/cpp/cmake_modules/ThirdpartyToolchain.cmake
index e19544182..ef2ccfd0a 100644
--- a/cpp/cmake_modules/ThirdpartyToolchain.cmake
+++ b/cpp/cmake_modules/ThirdpartyToolchain.cmake
@@ -620,8 +620,8 @@ endif()
 # ----------------------------------------------------------------------
 # ExternalProject options
 
-set(EP_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${CMAKE_CXX_FLAGS_${UPPERCASE_BUILD_TYPE}}")
-set(EP_C_FLAGS "${CMAKE_C_FLAGS} ${CMAKE_C_FLAGS_${UPPERCASE_BUILD_TYPE}}")
+set(EP_CXX_FLAGS "${CMAKE_CXX_COMPILER_ARG1} ${CMAKE_CXX_FLAGS} ${CMAKE_CXX_FLAGS_${UPPERCASE_BUILD_TYPE}}")
+set(EP_C_FLAGS "${CMAKE_C_COMPILER_ARG1} ${CMAKE_C_FLAGS} ${CMAKE_C_FLAGS_${UPPERCASE_BUILD_TYPE}}")
 
 if(NOT MSVC_TOOLCHAIN)
   # Set -fPIC on all external projects
```

**Comment by nealrichardson** [comment]
@github-actions crossbow submit test-r-linux-as-cran

**Comment by nealrichardson** [comment]
@github-actions autotune

**Comment by nealrichardson** [comment]
Thanks @kou! That seems to work.

**Comment by kou** [comment]
@github-actions crossbow submit -g nightly

**Comment by nealrichardson** [comment]
@github-actions crossbow submit test-r-versions

**Comment by nealrichardson** [comment]
@kou other than the test-r-versions nightly (for which I've pushed a fix), everything else looks no worse than master. I'll merge once CI confirms the fix.

**Review by kou — APPROVED** [review]
+1

Could you update the pull request description before we merge this?

**Pull request closed without merging**
