### PR TITLE
[EXP] ARROW-3253: [CI] Set up CI with Azure Pipelines [skip travis]

### PR DESCRIPTION
**Pull request by pitrou**
The main perk of using Azure Pipelines currently is that it gives 10 parallel jobs for open source projects, which is much higher than what AppVeyor offers.

### CODE REVIEW

**Comment by pitrou** [comment]
Example build with my Azure Pipelines account at: https://dev.azure.com/pitrou/arrow/_build/results?buildId=64&view=logs

**Comment by pitrou** [comment]
By the way, I wasn't able to make a C++ debug build successful on Azure because of problems downloading and building Boost. There may be an issue with our ExternalProject setup for Boost.

**Comment by kaylangan** [comment]
I'm a Program Manager on Azure Pipelines. Let me know if you have any questions or suggestions. I'm happy to help!

**Comment by vtbassmatt** [comment]
Hey folks, like @kaylangan I'm a PM on Azure Pipelines. I know woefully little about C++, having not touched it since undergrad, so bear with some dumb questions. Will you see speedups from clcache within a single build job, or does it only help if you can cache across runs? We don't offer any persistent storage between runs in the hosted pools.

We can definitely investigate having precompiled Boost available. I've opened a feature request to have a C++ expert investigate: https://github.com/Microsoft/azure-pipelines-image-generation/issues/263

Performance characteristics of C: vs D: using Azure VMs the way we do is... complicated :) If you're finding that for your workloads, the D: drive is faster, then you should use it. (That's likewise why we run the agent itself off the D: drive.) We don't make D: the default for a lot of things due to space constraints.

**Comment by pitrou** [comment]
> Will you see speedups from clcache within a single build job, or does it only help if you can cache across runs? We don't offer any persistent storage between runs in the hosted pools.

It would only help accross runs. We do this on AppVeyor, and it helps mildly (depending on which parts of the source code have changed).

**Comment by vtbassmatt** [comment]
Glad to hear you're having a good experience!

With our current architecture (we throw away the VM after every run), adding caching is pretty challenging. But it's definitely a common request, and we have a few ideas to run down.

**Comment by pitrou** [comment]
@vtbassmatt @kaylangan The Apache Foundation can't allow Azure Pipelines to be enabled on the Apache Arrow repository, as the AP app requires to give write access to the repository. Is there anything you could do to remove that requirement?

**Comment by vtbassmatt** [comment]
Write access is required to set up the web hooks and GitHub Checks. It also sets things up in an application identity instead of someone's personal GitHub identity.

If you're interested in trying things out without web hooks, you'll have to manually queue builds - no PR or CI integration. Also, GitHub Checks won't be set up. Mostly pointing that out so that when others come along, they'll understand why those features aren't lit up. Here are the steps:
1. Go to your Azure Pipelines organization
2. Choose "New pipeline"
3. Choose the option to "use the visual designer" instead of choosing GitHub at the top
4. Go through our older, wizard-based experience, using an OAuth connection under your own GitHub credentials
5. Before you save the pipeline, make sure to go to the Triggers tab and turn off CI/PR builds -- if those are "on" and you don't have the right to create webhooks, we will fail to save the build.
6. Save the pipeline and manually queue.

**Comment by vtbassmatt** [comment]
Curious: what would it take to get the right permissions? I noticed after I posted that AppVeyor's rich integration _is_ installed, so there must be a path to getting write access.

**Comment by pitrou** [comment]
Unfortunately, I have no idea. If you could ask by commenting [on this issue](https://issues.apache.org/jira/browse/INFRA-17030), it would be great :-)

**Comment by janpio** [comment]
@vtbassmatt This is what Appveyor asks for:

image
https://github.com/settings/connections/applications/01881570529737c25f97

image
https://github.com/settings/connections/applications/3fe1696ae02990ae1249

So seems they are doing things without write access. (Note that theses are OAuth apps in Github, not GitHub/Marketplace apps. Their GitHub app is pretty new: https://www.appveyor.com/blog/2018/10/02/github-apps-integration/)

**Comment by janpio** [comment]
I tried to follow your steps @vtbassmatt to get it working via your old flow with OAuth. 

1. I could only select an apache repo when I used the "personal access token" method, not the "OAuth" or "Grant authorization" as the apache org did not allow this I think. Did I mess up or was this information missing from your list above?

2. I created a pipeline for one of "my" repos: https://dev.azure.com/apache-cordova/cordova-lib/_build But I couldn't figure out how to configure it to use the configuration file from the PR: https://github.com/apache/cordova-lib/pull/696 What do I have to do so it uses the `azure-pipelines.yml`?

3. Also, did I get the limitations of this method right?

- No automatic builds on PRs and commits - each and every build has to be manually triggered via the web UI.
- No check integration into PRs that could report the build state back to GitHub - all feedback is in the Azure Pipelines UI only.

**Comment by janpio** [comment]
Any one last reply to @vtbassmatt :

> Curious: what would it take to get the right permissions?

From my understanding only committers with the correct paperwork submitted to Apache may have write access to the _code_. So any GitHub app (or app in general) that can change code but does so in its own name, will not work. Does Azure Pipelines _really_ have to be able to modify the _code_? Could there be other ways to achieve the necessary configuration? 

I am always confused about the permissions of apps, but afaik this is mostly because the permissions are not granular enough. Does this apply here? Could GitHub change something to fix this?

**Comment by vtbassmatt** [comment]
Hi, sorry for my delay in responding!

We're investigating whether we can still give the rich experience we want to give without forcing write access. (Ideally, GitHub would give us a way to *request* write access but gracefully degrade if the user declines. That doesn't exist yet.) Things look promising here but I don't have an ETA.

On the PAT vs OAuth question -- I may be missing a nuance of our system there. @DavidStaheli can you weigh in?

And on the limitations -- when I wrote that, I forgot that we could fall back to service hooks. You'll get the automatic builds of PRs and so on, but you won't get the GitHub Checks integration. When you create a pipeline using OAuth (and I would think PAT as well), we should set those webhooks up automatically. I'll shoot you a mail so we can troubleshoot why that's not working for you.

**Comment by emkornfield** [comment]
Any status updates on this?

**Comment by pitrou** [comment]
@emkornfield This is still waiting for the Apache Infrastructure team to eventually allow an Azure CI hook in Apache repos. Unfortunately we can't act ourselves. See https://issues.apache.org/jira/browse/INFRA-17030.

**Comment by janpio** [comment]
I am also in communication with Azure Pipelines (Matt C. and David S.) with the goal of finding alternative solutions that could enable us to use Azure Pipelines with the current INFRA and Legal environment. Not that easy :(

**Comment by pitrou** [comment]
@vtbassmatt Slightly off-topic, but I don't manage to log in into the "pitrou" Azure DevOps user anymore (on https://dev.azure.com/pitrou/ , I get 401 Unauthorized). Azure DevOps support doesn't seem willing to help me, they keep saying that I should _"contact the “pitrou” organization owner"_ (that's me!). Is there any way to get this unstuck?

**Comment by janpio** [comment]
No progress on a way to use Azure Pipelines for Apache projects yet :(

**Comment by pitrou** [comment]
So, I refreshed this PR and the Azure build is ok. There is an error at the end but it should be an Arrow problem (not 100% sure).

**Comment by pitrou** [comment]
@janpio Right, the Apache governance isn't helping us here...

**Comment by janpio** [comment]
I created https://issues.apache.org/jira/browse/INFRA-18115 to maybe start a conversation on the current limitations here. Maybe this can be changed.

**Comment by wesm** [comment]
Maybe we can make use of it on our forks at least for now?

**Comment by wesm** [comment]
(we could also implement some kind of bot-triggered build, but that won't help us migrate away from Appveyor)

**Comment by pitrou** [comment]
> Maybe we can make use of it on our forks at least for now?

Certainly :-)

**Comment by wesm** [comment]
Closing this regrettably for the time being -- it might be more worth our time to set up Windows buildbot agents

**Pull request closed without merging**
