### PR TITLE
MINOR: [Java] Bump Netty to 4.1.108.Final

### PR DESCRIPTION
**Pull request by sullis**
### Rationale for this change

[Java] bump to latest version of Netty

https://netty.io/news/2024/02/13/4-1-107-Final.html

https://netty.io/news/2024/03/21/4-1-108-Final.html

### What changes are included in this PR?

modified Java pom.xml

### Are these changes tested?

GitHub Actions CI build

### Are there any user-facing changes?

No

### CODE REVIEW

**Comment by lidavidm** [comment]
Is there a particular fix we should be aware of, and should we bump the gRPC requirement at the same time?

**Comment by vibhatha** [comment]
@github-actions crossbow submit *java*

**Comment by vibhatha** [comment]
@github-actions crossbow submit -g java

**Comment by vibhatha** [comment]
@sullis could we rebase this and check the CIs once again. There were some changes to CIs recently.

**Review by lidavidm — APPROVED** [review]

**Pull request merged**
