### PR TITLE
GH-40544: [Dev] Add cmake-format configuration to pre-commit

### PR DESCRIPTION
**Pull request by kou**
### Rationale for this change

We can maintain cmake-format related configuration by just listing target files and excluded files in YAML instead of writing not only listing paths but also extra codes in Python by using pre-commit.

### What changes are included in this PR?

Add cmake-format related pre-commit configuration.

We don't remove cmake-format related code from Archery for now. We'll do it when pre-commit can replace `archery lint` entirely.

### Are these changes tested?

Yes.

### Are there any user-facing changes?

No.
* GitHub Issue: #40544

### CODE REVIEW

**Comment by pitrou** [comment]
Hmm, does this mean I have to install and run an additional tool to properly format CMake changes? The selling point of `archery lint` is that it handles everything by itself.

**Comment by kou** [comment]
> does this mean I have to install and run an additional tool to properly format CMake changes?

Yes. You need to install `pre-commit` by `conda install -c conda-forge pre-commit`/`pip install pre-commit`/`sudo apt install -y pre-commit` (Ubuntu 22.04+) and run `pre-commit run -a` instead of `archery lint`. Note that you don't need to install `cmake_format` separately like `pip install -e 'dev/archery[lint]'`.

> The selling point of `archery lint` is that it handles everything by itself.

This means that `archery lint` runs all lints (`cmake_format`, `clang-format` and so on), right?

`pre-commit run -a` also does it eventually. I'll open PRs for it. For example, I'll add configurations of `clang-format` for `cpp/` and `python/` to `.pre-commit-config.yaml` like existing configuration of `c_glib/`: https://github.com/apache/arrow/blob/eecd7797f1d789551fbb000a93504182c47b6baa/.pre-commit-config.yaml#L55-L61 

If you don't like removing `cmake_format` related codes from Archery before `pre-commit run -a` can replace `archery lint` entirely, I'll remove Archery related changes from this PR.

**Comment by pitrou** [comment]
> If you don't like removing `cmake_format` related codes from Archery before `pre-commit run -a` can replace `archery lint` entirely, I'll remove Archery related changes from this PR.

Please do. It would be annoying to have to use two different commands for linting.

**Comment by kou** [comment]
OK. I've reverted Archery changes.

**Comment by kou** [comment]
+1

It's executed:

https://github.com/apache/arrow/actions/runs/8306057631/job/22733676937?pr=40545#step:6:17

```text
CMake Format.............................................................Passed
```

**Pull request merged**
