### PR TITLE
GH-15172: [Python] Docstring test failure

### LINKED ISSUE #15172: [Python] Docstring test failure
### Describe the bug, including details regarding any error messages, version, and platform.

This seems to be failing on a more or less regular basis:
```

______________________ [doctest] pyarrow._fs.PyFileSystem ______________________
EXAMPLE LOCATION UNKNOWN, not showing all tests of that example
??? >>> gfs = github.GithubFileSystem('apache', 'arrow', sha='ec51aec4d15035f4d9d6a1c4346d0a2b9a37fb75')
UNEXPECTED EXCEPTION: HTTPError('403 Client Error: rate limit exceeded for url: https://api.github.com/repos/apache/arrow/git/trees/ec51aec4d15035f4d9d6a1c4346d0a2b9a37fb75')
Traceback (most recent call last):
  File "/opt/conda/envs/arrow/lib/python3.9/doctest.py", line 1334, in __run
    exec(compile(example.source, filename, "single",
  File "<doctest pyarrow._fs.PyFileSystem[1]>", line 1, in <module>
  File "/opt/conda/envs/arrow/lib/python3.9/site-packages/fsspec/spec.py", line 76, in __call__
    obj = super().__call__(*args, **kwargs)
  File "/opt/conda/envs/arrow/lib/python3.9/site-packages/fsspec/implementations/github.py", line 56, in __init__
    self.ls("")
  File "/opt/conda/envs/arrow/lib/python3.9/site-packages/fsspec/implementations/github.py", line 158, in ls
    r.raise_for_status()
  File "/opt/conda/envs/arrow/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: rate limit exceeded for url: https://api.github.com/repos/apache/arrow/git/trees/ec51aec4d15035f4d9d6a1c4346d0a2b9a37fb75
/opt/conda/envs/arrow/lib/python3.9/site-packages/pyarrow/_fs.cpython-39-x86_64-linux-gnu.so:None: UnexpectedException
```

Example at https://github.com/apache/arrow/actions/runs/3831162396/jobs/6519941475#step:6:6215

### Component(s)

Python

### PR DESCRIPTION
**Pull request by AlenkaF**
* Closes: #15172

### CODE REVIEW

**Comment by AlenkaF** [comment]
@pitrou I am not sure if this will fix the flakey docstring but it would be my first go at it.

**Comment by pitrou** [comment]
I'm a bit skeptical because I wouldn't expect the API rate limits to depend on the changeset. @assignUser Thoughts?

**Comment by assignUser** [comment]
Hmm... the sha is probably not the issue. Not sure if the default `GITHUB_TOKEN` is picked up or not? If not that is probably the issue as unauthenticated api access has a strict 50 calls/h limit  **per IP** so if some other api calls are made from the same IP that limit is reached quickly. Explicit authentication via `GITHUB_TOKEN` should avoid this. (or usign the web based url vs the api but that would porbably defeat the purpose here :D)

**Comment by AlenkaF** [comment]
Ah, in that case it would be better just to add an ignore mark for doctest to skip this docstring example.

**Review by pitrou — APPROVED** [review]
LGTM, thanks @AlenkaF !

**Pull request merged**
