### PR TITLE
ARROW-7693: [CI] Fix test name for Spark integration, add new tests

### PR DESCRIPTION
**Pull request by BryanCutler**
Spark master renamed some Pandas/Arrow tests, this updates the tests names and adds some new tests to nightly CI.

### CODE REVIEW

**Comment by BryanCutler** [comment]
@ursabot crossbow submit test-conda-python-3.7-spark-master

**Comment by kszucs** [comment]
[AMD64 Conda Crossbow Submit (#88527)](https://ci.ursalabs.org/#builders/98/builds/477) builder has been succeeded.

Revision: c1cf839dcae64e65fb4dc017acce945aa89e128b

Submitted crossbow builds: [ursa-labs/crossbow @ ursabot-464](https://github.com/ursa-labs/crossbow/branches/all?query=ursabot-464)

|Task|Status|
|----|------|
|test-conda-python-3.7-spark-master|[CircleCI](https://circleci.com/gh/ursa-labs/crossbow/tree/ursabot-464-circle-test-conda-python-3.7-spark-master)|

**Comment by jorisvandenbossche** [comment]
Now there are actually some tests failing. 

```
======================================================================
ERROR: test_grouped_over_window (pyspark.sql.tests.test_pandas_grouped_map.GroupedMapInPandasTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/spark/python/pyspark/sql/tests/test_pandas_grouped_map.py", line 542, in test_grouped_over_window
    .select('id', 'result').collect()
  File "/spark/python/pyspark/sql/dataframe.py", line 563, in collect
    sock_info = self._jdf.collectToPython()
  File "/spark/python/lib/py4j-0.10.8.1-src.zip/py4j/java_gateway.py", line 1286, in __call__
    answer, self.gateway_client, self.target_id, self.name)
  File "/spark/python/pyspark/sql/utils.py", line 98, in deco
    return f(*a, **kw)
  File "/spark/python/lib/py4j-0.10.8.1-src.zip/py4j/protocol.py", line 328, in get_return_value
    format(target_id, ".", name), value)
py4j.protocol.Py4JJavaError: An error occurred while calling o741.collectToPython.
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 99 in stage 41.0 failed 1 times, most recent failure: Lost task 99.0 in stage 41.0 (TID 949, 2449b060635e, executor driver): org.apache.spark.api.python.PythonException: Traceback (most recent call last):
  File "/opt/conda/envs/arrow/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 2897, in get_loc
    return self._engine.get_loc(key)
  File "pandas/_libs/index.pyx", line 107, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 131, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1607, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1614, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'ts'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/spark/python/lib/pyspark.zip/pyspark/worker.py", line 599, in main
    process()
  File "/spark/python/lib/pyspark.zip/pyspark/worker.py", line 591, in process
    serializer.dump_stream(out_iter, outfile)
  File "/spark/python/lib/pyspark.zip/pyspark/sql/pandas/serializers.py", line 255, in dump_stream
    return ArrowStreamSerializer.dump_stream(self, init_stream_yield_batches(), stream)
  File "/spark/python/lib/pyspark.zip/pyspark/sql/pandas/serializers.py", line 88, in dump_stream
    for batch in iterator:
  File "/spark/python/lib/pyspark.zip/pyspark/sql/pandas/serializers.py", line 249, in init_stream_yield_batches
    batch = self._create_batch(series)
  File "/spark/python/lib/pyspark.zip/pyspark/sql/pandas/serializers.py", line 182, in _create_batch
    for field in t]
  File "/spark/python/lib/pyspark.zip/pyspark/sql/pandas/serializers.py", line 182, in <listcomp>
    for field in t]
  File "/opt/conda/envs/arrow/lib/python3.7/site-packages/pandas/core/frame.py", line 2995, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/opt/conda/envs/arrow/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 2899, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 107, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 131, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1607, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1614, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'ts'
```

but I don't directly see how this is related to pyarrow. There seems to be going something wrong in the serialization

**Comment by BryanCutler** [comment]
>but I don't directly see how this is related to potential recent changes in pyarrow. There seems to be going something wrong in the serialization (with struct arrays)

Yeah, it's kind of a strange failure and I'm not sure what's causing it either. I'll try to reproduce locally and debug.

**Comment by BryanCutler** [comment]
Ok, so the problem seems to be that a Timestamp Column from a Table loses it's name when converted to Pandas. It only seems to be if its a timestamp type, and I'm not sure what the correct behavior is since the "Column" is actually a `ChunkedArray` and doesn't really have a name anymore.  Here is a simple repro:
```python
In [23]: a1 = pa.array([pd.Timestamp.now()])                                                                                 

In [24]: a2 = pa.array([1])                                                                                                  

In [25]: t = pa.Table.from_arrays([a1, a2], ['ts', 'a'])                                                                     

In [26]: for c in t: 
    ...:     print(c.to_pandas()) 
    ...:                                                                                                                     
0   2020-01-28 13:17:26.738708
dtype: datetime64[ns]
0    1
Name: a, dtype: int64
```
What are your thoughts on if this is a bug or not @wesm @jorisvandenbossche ?

**Comment by jorisvandenbossche** [comment]
Ah, yes, that's a bug. 
And it seems to depend on the resolution:

```
In [52]: table = pa.table({'a': pd.date_range("2012", periods=3), 'b': [1, 2, 3]})  

In [53]: table.column('a').to_pandas()  # ns resolution
Out[53]: 
0   2012-01-01
1   2012-01-02
2   2012-01-03
Name: a, dtype: datetime64[ns]

In [54]: table = pa.table({'a': pa.array([1, 2, 3], pa.timestamp('us')), 'b': [1, 2, 3]}) 

In [55]: table.column('a').to_pandas()
Out[55]: 
0   1970-01-01 00:00:00.000001
1   1970-01-01 00:00:00.000002
2   1970-01-01 00:00:00.000003
dtype: datetime64[ns]
```

**Comment by jorisvandenbossche** [comment]
It is a regression due to the change I did here (https://github.com/apache/arrow/commit/af6fa24be0dbbc021e0844c63d1c0b89fb23a95c): 

https://github.com/apache/arrow/blob/2205caa39f6dbd74fbceb3f8cd8ddaa9067f064d/python/pyarrow/array.pxi#L1124-L1126

The `cast` probably looses the stored name.

(I can do a fix tomorrow, I don't know what the status is of the release process)

**Comment by BryanCutler** [comment]
Ok, thanks @jorisvandenbossche !  I made https://issues.apache.org/jira/browse/ARROW-7709 to track that one. I'll go ahead and merge this PR.

**Pull request closed without merging**
