### PR TITLE
GH-37129: [CI][Docs] Free up disk space

### LINKED ISSUE #37129: [CI][Docs] Complete docs job is failed by "No space left on device" error
### Describe the bug, including details regarding any error messages, version, and platform.

https://github.com/apache/arrow/actions/runs/5830590560/job/15812275941#step:6:8651

```text
  FAILED: CMakeFiles/_flight.dir/_flight.cpp.o
  /usr/bin/ccache /usr/lib/ccache/c++  -DARROW_HAVE_RUNTIME_AVX2 -DARROW_HAVE_RUNTIME_AVX512 -DARROW_HAVE_RUNTIME_BMI2 -DARROW_HAVE_RUNTIME_SSE4_2 -DARROW_HAVE_SSE4_2 -D_flight_EXPORTS -I../../pyarrow/src -Ipyarrow/src -isystem /usr/include/python3.8 -isystem /usr/local/lib/python3.8/dist-packages/numpy/core/include -Wno-noexcept-type  -Wall -fno-semantic-interposition -msse4.2  -fdiagnostics-color=always  -fno-omit-frame-pointer -Wno-unused-variable -Wno-maybe-uninitialized -g -O0  -fPIC   -std=c++17 -Wno-unused-function -Winvalid-pch -include /arrow/python/build/temp.linux-x86_64-cpython-38/CMakeFiles/_flight.dir/cmake_pch.hxx -MD -MT CMakeFiles/_flight.dir/_flight.cpp.o -MF CMakeFiles/_flight.dir/_flight.cpp.o.d -o CMakeFiles/_flight.dir/_flight.cpp.o -c _flight.cpp
  _flight.cpp:75452:1: fatal error: error writing to /tmp/ccBobgrt.s: No space left on device
  75452 | }
        | ^
  compilation terminated.
```

### Component(s)

Continuous Integration, Documentation

### PR DESCRIPTION
**Pull request by kou**
### Rationale for this change

We need many disk space for building docs.

### What changes are included in this PR?

Reuse existing free code.

### Are these changes tested?

Yes.

### Are there any user-facing changes?

No.
* Closes: #37129

### CODE REVIEW

**Comment by kou** [comment]
@github-actions crossbow submit debian-bookworm-amd64

**Comment by kou** [comment]
Passed: https://github.com/kou/arrow/actions/runs/5837171484/job/15832197984

**Review by assignUser — APPROVED** [review]
Nice, a bit ridiculous that they install so much stuff that diskspace becomes bottle neck ^^

**Comment by kou** [comment]
We have 23G disk space by default... It should be enough for most cases. We should reduce required disk space...

**Pull request merged**
