### PR TITLE
ARROW-9195: [Java] Fixed UNSAFE.get from bytearray usage

### PR DESCRIPTION
**Pull request by projjal**

### CODE REVIEW

**Comment by kiszk** [comment]
How about adding test cases to cause a failure by the original code?

**Comment by projjal** [comment]
> How about adding test cases to cause a failure by the original code?

done

**Comment by kiszk** [comment]
Looks good

**Review by liyafan82 — APPROVED** [review]
LGTM, thank you for fixing the problem.

**Pull request closed without merging**
