### PR TITLE
GH-39996: [Archery] Fix Crossbow build on a PR from a fork's main branch

### LINKED ISSUE #39996: [Archery] Crossbow refuses to run on the main branch of a fork
### Describe the bug, including details regarding any error messages, version, and platform.

When invoking `@github-actions crossbow submit ...` on a PR made from a fork's `main` branch, Archery fails triggering the builds. Example:
https://github.com/apache/arrow/pull/39878#issuecomment-1933766758

Result:
https://github.com/apache/arrow/actions/runs/7828116460/job/21357317509#step:5:18
```
Run archery trigger-bot \
  archery trigger-bot \
    --event-name issue_comment \
    --event-payload /home/runner/work/_temp/_github_workflow/event.json
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.8.18/x64
    PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.8.18/x64/lib/pkgconfig
    Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.8.18/x64
    Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.8.18/x64
    Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.8.18/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.8.18/x64/lib
    ARROW_GITHUB_TOKEN: ***
    CROSSBOW_GITHUB_TOKEN: ***
fatal: not a git repository (or any of the parent directories): .git
Cloning into '/tmp/tmpze7d9_8y/arrow'...
fatal: refusing to fetch into branch 'refs/heads/main' checked out at '/tmp/tmpze7d9_8y/arrow'
ERROR:archery:Command '['git', '-C', '/tmp/tmpze7d9_8y/arrow', 'fetch', 'origin', 'pull/39878/head:main']' returned non-zero exit status 128.
```

### Component(s)

Archery, Continuous Integration

### PR DESCRIPTION
**Pull request by pitrou**
### Are there any user-facing changes?

* Closes: #39996

### CODE REVIEW

**Comment by pitrou** [comment]
I've checked that `_clone_arrow_and_crossbow` works locally but I'm not sure how to exercise this PR for real. @kou Any thoughts?

**Comment by kou** [comment]
How about adding the following to this PR only for testing?

```diff
diff --git a/.github/workflows/dev.yml b/.github/workflows/dev.yml
index 4892767324..c8d3bdd1ec 100644
--- a/.github/workflows/dev.yml
+++ b/.github/workflows/dev.yml
@@ -113,3 +113,25 @@ jobs:
       - name: Run Merge Script Test
         shell: bash
         run: pytest -v dev/test_merge_arrow_pr.py
+
+  crossbow:
+    name: Crossbow
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout Arrow
+        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
+        with:
+          path: arrow
+          # fetch the tags for version number generation
+          fetch-depth: 0
+      - name: Set up Python
+        uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c # v5.0.0
+        with:
+          python-version: 3.8
+      - name: Install Archery and Crossbow dependencies
+        run: pip install -e arrow/dev/archery[bot]
+      - name: Handle GitHub comment event
+        env:
+          ARROW_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          archery crossbow submit ...
```

Or I think that we can merge this to main and try because you've already checked this on your local.

**Comment by pitrou** [comment]
Ah, thanks, I will add your suggestion.

**Comment by pitrou** [comment]
Your suggestion didn't work. We would need to call `archery trigger-bot`, but that in turn requires an actual Github event...

**Comment by kou** [comment]
Ah, the changed code is for `trigger-bot`. Sorry.

How about merging this?

**Comment by pitrou** [comment]
> How about merging this?

Fair enough, let's do it.

**Comment by pitrou** [comment]
@github-actions crossbow submit conda-clean

**Comment by pitrou** [comment]
Ok, so this didn't work on the original PR:
```
Cloning into bare repository '/tmp/tmp10_wjydg/arrow_bare'...
From https://github.com/apache/arrow
 ! [rejected]            refs/pull/39878/head -> main  (non-fast-forward)
ERROR:archery:Command '['git', '-C', '/tmp/tmp10_wjydg/arrow_bare', 'fetch', 'origin', 'pull/39878/head:main']' returned non-zero exit status 1.
```

**Pull request merged**
