### PR TITLE
ARROW-7932: [Rust] implement array_reader for temporal types

### PR DESCRIPTION
**Pull request by mcassels**
Add date/time/timestamp/interval/duration LogicalType support to array_reader

### CODE REVIEW

**Comment by maxburke** [comment]
Thoughts @andygrove / @nevi-me ?

**Comment by maxburke** [comment]
Any objections to merging tihs?

**Comment by paddyhoran** [comment]
@mcassels thank you for this and sorry it is taking so long to get reviewed :)

I looked at this yesterday and it looks fine to me but I'm no expert on parquet (hence why I didn't approve/merge it).

@sunchao @sadikovi you're the parquet experts, what do you think?

**Review by andygrove — APPROVED** [review]
This seems consistent with how the other types are implemented so LGTM!

**Comment by andygrove** [comment]
I'm traveling right now and have a new laptop so I'm not set up to be able to merge this right now but hopefully, another committer will be able to take care of the merge.

**Comment by nealrichardson** [comment]
I'll merge since y'all are good with it.

**Pull request closed without merging**
