### PR TITLE
ARROW-10846: [C++] Add async filesystem operations

### PR DESCRIPTION
**Pull request by pitrou**

### CODE REVIEW

**Comment by pitrou** [comment]
@westonpace Would you like to review this?

**Comment by pitrou** [comment]
I tested HDFS here: https://github.com/ursacomputing/crossbow/runs/2033412067

**Comment by westonpace** [comment]
@pitrou Looks good to me.  I wonder if we will even need to use AWS' async mode?  It seems that calling into S3 this way is pretty much equivalent to overriding their executor with our own.

Callers will have to take care to know that these futures will complete on the IOContext and transfer them off quickly but looking at it now I agree that the transfer doesn't belong in here. Looks great.

**Comment by pitrou** [comment]
We do use AWS async APIs at a couple places, but you're right this is not mandatory.
OTOH, if we don't use them then we may have a double indirection (first our own executor, then AWS would use its own executor? or are the sync AWS APIs really sync?).

**Pull request closed without merging**
