### PR TITLE
ARROW-1590: [JS] Flow TS Table method generics

### PR DESCRIPTION
**Pull request by trxcllnt**
This PR fixes the Table generics to infer the types from the call site:

kapture 2017-09-21 at 4 03 34

@wesm this PR also includes the fixes to the prepublish script I mentioned yesterday.

### CODE REVIEW

**Comment by wesm** [comment]
@trxcllnt can you rebase on master?

**Comment by trxcllnt** [comment]
@wesm done

**Comment by wesm** [comment]
There are still some extra commits that should rebase out if you base against the current apache/master. I rebased some commits on the release branch and force-pushed master after 0.7.0 which is why there's an issue

**Comment by trxcllnt** [comment]
@wesm ok, I rebased and dropped the extra commits.

**Comment by wesm** [comment]
Sweet, thanks!

**Review by wesm — APPROVED** [review]
+1

**Pull request closed without merging**
