### PR TITLE
ARROW-11251: [CI] Make sure that devtoolset-8 is really installed + being used

### PR DESCRIPTION
**Pull request by jonkeane**

### CODE REVIEW

**Comment by jonkeane** [comment]
@github-actions crossbow submit test-r-rstudio-r-base-3.6-centos*

**Comment by jonkeane** [comment]
@github-actions crossbow submit test-r-rstudio-r-base-3.6-centos*

**Comment by jonkeane** [comment]
@github-actions crossbow submit wheel-win-cp38

**Comment by jonkeane** [comment]
Confirmation that centos7 + devtools 8 is getting the correct gcc: 

https://dev.azure.com/ursa-labs/crossbow/_build/results?buildId=23111&view=logs&j=0da5d1d9-276d-5173-c4c4-9d4d4ed14fdb&t=6c939d89-0d1a-51f2-8b30-091a7a82e98c&l=47

**Review by nealrichardson — APPROVED** [review]
Can you please rebase in order to trigger builds?

**Pull request closed without merging**
