### PR TITLE
ARROW-3022: [Go] add support for Struct arrays

### PR DESCRIPTION
**Pull request by sbinet**

### CODE REVIEW

**Comment by sbinet** [comment]
@stuartcarnie PTAL.

**Comment by wesm** [comment]
Restarted

**Review by stuartcarnie — APPROVED** [review]
Great work Sebastien!

**Comment by sbinet** [comment]
rebased on top of latest `master`.
(nice side-effect: travis is having a better day, and the CI tests are green :P)

**Comment by wesm** [comment]
@pitrou or @cpcloud can you help merge the Go PRs that have been approved? I am away from internet until tomorrow

**Comment by pitrou** [comment]
@wesm Will do.

**Comment by pitrou** [comment]
Thanks @sbinet for doing this :-)

**Pull request closed without merging**
