### PR TITLE
GH-43382: [C++][Parquet] min-max Statistics doesn't work well when one of min-max is truncated

### PR DESCRIPTION
**Pull request by mapleFU**
### Rationale for this change

See https://github.com/apache/arrow/issues/43382

### What changes are included in this PR?

Change stats has min-max from min || max to &&

### Are these changes tested?

* [x] TODO

### Are there any user-facing changes?

Might affect interface using HasMinMax

**This PR includes breaking changes to public APIs.**

* GitHub Issue: #43382

### CODE REVIEW

**Comment by mapleFU** [comment]
This is just a try, I can also extract has-min and has-max

**Comment by mapleFU** [comment]
@pitrou @wgtmac would you mind take a look whether this fixing is ok or there is better api? I'll draft testing once api is stable

**Comment by wgtmac** [comment]
I'm fine to be conservative. So this change looks good. However, the encoded_min and encoded_max are still set. I'd propose to deprecate `virtual bool HasMinMax() const = 0;` and add `virtual bool HasMin() const = 0;` and `virtual bool HasMax() const = 0;`

**Comment by mapleFU** [comment]
Updated: I'll separate the implemetation into two separate patch:

* The first one is test and remove the || in HasMinMax, changing the syntax to both has-min and has-max
* The second one is add HasMin and HasMax.

Anyway this is a bug rather than feature so we should fix it first

**Comment by mapleFU** [comment]
@kou @emkornfield @wgtmac would you mind take a look? This patch only change `||` -> `&&`

**Review by kou — APPROVED** [review]
+1

Could you uncomment `<!-- **This PR includes breaking changes to public APIs.** -->` in the PR description?

**Review by wgtmac — APPROVED** [review]
+1

**Pull request merged**
