### PR TITLE
ARROW-1609: [Plasma] Xcode 9 compilation workaround

### PR DESCRIPTION
**Pull request by pcmoritz**
see https://github.com/apache/arrow/pull/1139

### CODE REVIEW

**Review by xhochy — APPROVED** [review]
+1, LGTM

**Comment by xhochy** [comment]
I'm seeing this error now also pop up in the unittests of plasma on macOS.

**Comment by xhochy** [comment]
@pcmoritz Do you also see these problems or is there something non-standard in my setup?

**Comment by pcmoritz** [comment]
I was still using XCode 8 but installing version 9 now and looking into this.

**Comment by robertnishihara** [comment]
I can reproduce the problem.

**Comment by robertnishihara** [comment]
Should be fixed by #1261.

**Pull request closed without merging**
