### PR TITLE
ARROW-3226: [Plasma] Fix small memory crash

### PR DESCRIPTION
**Pull request by guoyuhong**
Plasma Store will do the eviction when the memory allocation fails. When specified a smaller store limit, the memory allocation will succeed but Plasma Store will crash when limit memory reached.
Call stack:
```
F0912 23:55:49.693681 2961466240 eviction_policy.cc:73]  Check failed: memory_used_ <= store_info_->memory_capacity
*** Check failure stack trace: ***
    @        0x1087d0aca  google::LogMessage::Fail()
    @        0x1087ce8ee  google::LogMessage::SendToLog()
    @        0x1087cf76f  google::LogMessage::Flush()
    @        0x1087cf5a9  google::LogMessage::~LogMessage()
    @        0x1087cf865  google::LogMessage::~LogMessage()
    @        0x1087e8ef5  arrow::ArrowLog::~ArrowLog()
    @        0x1087aef8e  plasma::EvictionPolicy::ObjectCreated()
    @        0x1087a21e8  plasma::PlasmaStore::CreateObject()
    @        0x1087a6e8c  plasma::PlasmaStore::ProcessMessage()
    @        0x1087abc1c  std::__1::__function::__func<>::operator()()
    @        0x1087af81e  plasma::EventLoop::FileEventCallback()
    @        0x1087c8eb1  aeProcessEvents
    @        0x1087c919b  aeMain
    @        0x1087a8508  plasma::PlasmaStoreRunner::Start()
    @        0x1087a81fa  plasma::StartServer()
    @        0x1087a8d9c  main
```

### CODE REVIEW

**Comment by pcmoritz** [comment]
@guoyuhong Thanks a lot for the patch! Do you currently understand why the crash is happening? How can dlmalloc promise more memory than it has room in the memory mapped file?

Also if you have a small script to reproduce it that would be helpful to see if that's the right fix or if something else is going wrong here (it seems to me that this fix should not be needed).

**Comment by guoyuhong** [comment]
@pcmoritz You can use the test case in client_test of this PR to repro it or use the following script:
```python
ray.init(object_store_memory=10000)
message = "This is a message"
for i in range(10000):
    ray.put(message)

```

**Comment by guoyuhong** [comment]
@pcmoritz Have you tried the script or the test case?

**Comment by guoyuhong** [comment]
@pcmoritz Maybe here is the problem. In [`dlmalloc_set_footprint_limit`](https://github.com/apache/arrow/blob/master/cpp/src/plasma/thirdparty/dlmalloc.c#L5367), the input memory is changed by `granularity_align(bytes)` and save to `gm->footprint_limit`. In this case, 1000 bytes will be changed 131072 and 1000000000 will be changed to 1000079360. Therefore, when we try to allocate an object which makes `footprint` between the input limit and the aligned limit, `dlmemalign` may return a normal pointer but [the eviction policy check](https://github.com/apache/arrow/blob/master/cpp/src/plasma/eviction_policy.cc#L73) fails and Plasma crashes.

**Comment by guoyuhong** [comment]
@pcmoritz

**Comment by pcmoritz** [comment]
@guoyuhong I'm currently working on replacing dlmalloc with jemalloc to fix this issue and a bunch of others (memory fragmentation, file descriptor sending problems), let's wait until I have the patch ready which should be in the next couple of days and then we can see which solution is better. How do you feel about that?

**Comment by guoyuhong** [comment]
@pcmoritz Thanks for the information. Yes, let's wait for the new allocation function and then see whether there is still this bug.

**Comment by pcmoritz** [comment]
I put my current progress up here: https://github.com/apache/arrow/pull/2593

It is currently blocked on https://github.com/jemalloc/jemalloc/issues/1329, let me know if you have any ideas here :)

**Comment by wesm** [comment]
In https://github.com/apache/arrow/pull/4189 it is proposed to update to jemalloc 5.2.0. Does that resolve the issue?

**Comment by wesm** [comment]
@guoyuhong do you know if jemalloc 5.2.0 resolves this issue?

**Comment by guoyuhong** [comment]
@wesm Sorry for the late response. I use the `SmallMemoryTest` in this PR to take a test. Currently, Size `1000` is not allowed. I changed to 3000, it passed. Therefore, I will close this PR.

**Pull request closed without merging**
