### PR TITLE
ARROW-2137: [Python] Don't print paths that are ignored when reading Parquet files

### PR DESCRIPTION
**Pull request by kisankansagra**
_should_silently_exclude should silently exclude, not print stuff

### CODE REVIEW

**Comment by cpcloud** [comment]
This seems reasonable, since we're ignoring `_SUCCESS` and `.crc` files. `_SUCCESS` files are empty and `.crc` files are a data integrity implementation detail that a user would probably almost never want to read in directly.

**Comment by cpcloud** [comment]
Looks like a spurious travis failure

**Comment by cpcloud** [comment]
Opened a JIRA for this: https://issues.apache.org/jira/browse/ARROW-2137

**Comment by wesm** [comment]
@kisankansagra could you let us know your JIRA id on issues.apache.org (or create an account if necessary) so we can assign this issue to you?

**Review by wesm — APPROVED** [review]
+1

**Pull request closed without merging**
