### PR TITLE
GH-40268: [Archery] Bump the version of pygit2, adapt to API changes

### PR DESCRIPTION
**Pull request by jonkeane**
### Rationale for this change

`archery crossbow submit ...` fails with newer versions of pygit2

### What changes are included in this PR?

Adapt away from deprecated [sic] APIs in pygit2 to ones that work with current versions, bump the pin

### Are these changes tested?

Manually, yes, I can use `archery crossbow submit ...` again. CI will run using archery in a bunch of places on this PR too.

### Are there any user-facing changes?

No
* GitHub Issue: #40268

### CODE REVIEW

**Comment by kou** [comment]
It seems that pygit 1.14 requires Python 3.9 or later.
How about using recent Python (Python 3.12?) for Archery?

**Comment by jonkeane** [comment]
> How about using recent Python (Python 3.12?) for Archery?

Unless I'm missing something obvious, it looks like this actually would mean bumping python versions in a bunch of places. I wonder if we should instead either not require 3.9 except for `archery[crossbow]` or maybe pin to a lower version of pygit2 instead. What do folks think?

**Comment by kou** [comment]
It's not a strong opinion but it may be a good time to update Python version for Archery.
Python 3.8 will reach EOL on 2024-10: https://devguide.python.org/versions/

**Comment by pitrou** [comment]
I agree with requiring Python 3.9 on Archery-related CI jobs.

**Review by pitrou — APPROVED** [review]

**Comment by pitrou** [comment]
3 of the 4 failing PR checks are due to missing Python version bumps, can you take a look @jonkeane ?

**Comment by pitrou** [comment]
@github-actions crossbow submit -g python -g wheel

**Comment by jonkeane** [comment]
> 3 of the 4 failing PR checks are due to missing Python version bumps, can you take a look @jonkeane ?

Yup, I can keep bumping versions if we're all good with doing that here. I'll also change the title to be more "bump python, and also the tiny archery fix too"

**Comment by jonkeane** [comment]
For the C++ / ARM64 Ubuntu 20.04 C++, ARM64 Debian 11 Go 1.19/1.20 jobs, IIUC those run on the self-hosted runners managed by Voltron Data, yeah?

I see:

```
https://github.com/apache/arrow/blob/d6b9051fa05b230ce288eb0b7ab6b596200c45b1/.github/workflows/cpp.yml#L137-L140
``` 

Which is pulling from apt (rather than using the setup-python action). Would it be preferred to switch to the setup-python action or add a ppa that we can fetch a newer python from? 

The other C++ / AMD64 macOS 12 C++ is a timeout that [I'm seeing on main on main too](https://github.com/apache/arrow/actions/runs/8081138119/job/22078996952)

**Comment by kou** [comment]
> ARM64 Ubuntu 20.04 C++

Let's use Ubuntu 22.04:

```diff
diff --git a/.github/workflows/cpp.yml b/.github/workflows/cpp.yml
index e9409f1cd6..b5461e2f56 100644
--- a/.github/workflows/cpp.yml
+++ b/.github/workflows/cpp.yml
@@ -94,12 +94,12 @@ jobs:
             cat <<JSON >> "$GITHUB_OUTPUT"
           {
             "arch": "arm64v8",
-            "clang-tools": "10",
+            "clang-tools": "14",
             "image": "ubuntu-cpp",
-            "llvm": "10",
+            "llvm": "14",
             "runs-on": ["self-hosted", "arm", "linux"],
-            "title": "ARM64 Ubuntu 20.04 C++",
-            "ubuntu": "20.04"
+            "title": "ARM64 Ubuntu 22.04 C++",
+            "ubuntu": "22.04"
           }
           JSON
           fi
```

> ARM64 Debian 11 Go 1.19/1.20

Let's use Debian 12:

```diff
diff --git a/.github/workflows/go.yml b/.github/workflows/go.yml
index bbffab6704..5d6918aa60 100644
--- a/.github/workflows/go.yml
+++ b/.github/workflows/go.yml
@@ -90,7 +90,7 @@ jobs:
           echo "JSON" >> "$GITHUB_OUTPUT"
 
   docker:
-    name: ${{ matrix.arch-label }} Debian 11 Go ${{ matrix.go }}
+    name: ${{ matrix.arch-label }} Debian 12 Go ${{ matrix.go }}
     needs: docker-targets
     runs-on: ${{ matrix.runs-on }}
     if: ${{ !contains(github.event.pull_request.title, 'WIP') }}
@@ -101,6 +101,7 @@ jobs:
         include: ${{ fromJson(needs.docker-targets.outputs.targets) }}
     env:
       ARCH: ${{ matrix.arch }}
+      DEBIAN: "12"
       GO: ${{ matrix.go }}
     steps:
       - name: Checkout Arrow
``

**Comment by jonkeane** [comment]
Bumping to 22.04 still resulted in python 3.8 for C++ / ARM64 Ubuntu 22.04 C++: https://github.com/apache/arrow/actions/runs/8088510588/job/22102700260?pr=40269#step:5:55

But in looking at the extended builds, there are a number of old OSes that we won't have 3.8 by default (and some we even want 3.8 in order to build on). (e.g. wheel-macos-big-sur-cp38-arm64, test-fedora-39-python-3, test-ubuntu-20.04-python-3). 

IMO, we should not bundle all of these changes up because of this one archery issue. We should:

1. pin pygit2 to one version older (with a note to update it when 3.8 is fully gone), 
2. accept that archery[crossbow] requires 3.9, but others do not. Document that and then we can bump python to 3.12 for the places that call `archery crossbow` and leave many of these (especially the older ones which generally are using only archery[docker] on older python versions).

I think I would prefer the second of those, but am also happy to do the first.

**Comment by pitrou** [comment]
I'm ok with option 2 as well.

**Comment by jonkeane** [comment]
@github-actions crossbow submit -g python -g wheel

**Review by raulcd — APPROVED** [review]
Current CI failures are unrelated

**Pull request merged**
