### PR TITLE
ARROW-3860: [WIP][Gandiva][C++] Link std c++ statically.

### PR DESCRIPTION
**Pull request by praveenbingo**
Restores linking statically to std c++, so that it can be safely packaged for other
similar environments.

### CODE REVIEW

**Comment by pitrou** [comment]
I'm not sure we want to do that by default. @wesm

**Comment by wesm** [comment]
I hear you -- this issue is a bit distressing as the hard-coding of linker flags specific to Dremio builds was causing problems for other Arrow developers. I asked multiple times and waited over a month before fixing the problem myself

* October 4: https://github.com/apache/arrow/pull/2695#issuecomment-426957629
* October 6: https://github.com/apache/arrow/pull/2705#discussion_r223183596
* October 11: https://github.com/apache/arrow/pull/2744#issuecomment-428934053
* November 10, raising ARROW-3437 to blocker: https://issues.apache.org/jira/browse/ARROW-3437?focusedCommentId=16682681&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-16682681

Here is the fix on November 19: https://github.com/apache/arrow/commit/ba2b2ea2301f067cc95306e11546ddb6d402a55c#diff-55d595f15416efb8fd2b661f37cb55b7

We have a problem of process right now in that people like me are not able to verify changes that are affecting Dremio builds -- had I been able to, I would have been glad to sort out a remediation. Short of that, I am not sure how else I would have been able to force action on this issue. As you can see in the discussion on https://issues.apache.org/jira/browse/ARROW-3860, there is a lack of transparency into your process that makes it difficult for me to help.

**Comment by wesm** [comment]
If you want to revert https://github.com/apache/arrow/commit/ba2b2ea2301f067cc95306e11546ddb6d402a55c temporarily until you figure out the packaging stuff, it's fine with me, but let's please not let it linger much longer since I would like to get the project into release-ready shape in the next 2-3 weeks

**Comment by wesm** [comment]
I think https://github.com/apache/arrow/pull/3035 will address the issue

**Comment by jacques-n** [comment]
Hey @wesm , I appreciate your attention and detailed response. I've opened up https://issues.apache.org/jira/browse/ARROW-3887 and will have our team work on adding that. There is no desire to be opaque. Will work with the team on becoming more transparent as well.

**Comment by praveenbingo** [comment]
Thanks a ton Wes and Jacques for taking this to closure.

**Pull request closed without merging**
