### PR TITLE
ARROW-9704: [Java] TestEndianness.testLittleEndian supports little- and big-endian platforms

### PR DESCRIPTION
**Pull request by kiszk**
This PR aims to take care of data layout on little- and big-endian platforms in `TestEndianness.testLittleEndian`

### CODE REVIEW

**Comment by nealrichardson** [comment]
Is this mergeable now? According to the mailing list discussion:

> It does not seem too invasive to support native endianness in
implementation libraries.  As long as there is appropriate performance
testing and CI infrastructure to demonstrate the changes work.

If I read this PR correctly, it's just changing the test to follow native endianness.

**Comment by kiszk** [comment]
Thank you for your comment.

According to Micah 's [comment](https://github.com/apache/arrow/pull/7938#issuecomment-703381572), we may wait until he will update the document soon.
@emkornfield WDYT?

Since Java CI was merged, I rebased to run Java CI.

**Comment by emkornfield** [comment]
Opened https://github.com/apache/arrow/pull/8374 to make sure we are all on the same page, once that goes in, I think we can submit this.

**Comment by kiszk** [comment]
@nealrichardson @emkornfield Is it ok to merge this?  I think that this failure is not related to the change of this PR.

**Comment by nealrichardson** [comment]
Sounds like it. I'll merge.

**Pull request closed without merging**
