### PR TITLE
ARROW-2182: [Python] Build C++ libraries in benchmarks build step 

### PR DESCRIPTION
**Pull request by pitrou**
Also add a Travis-CI step to check the benchmarking setup (in one matrix configuration).

### CODE REVIEW

**Comment by pitrou** [comment]
@wesm it would be nice if you could give this a try. It seems to work here (i.e. `asv run` rebuilds the arrow C++ libraries on the given changeset) but perhaps it doesn't on other setups.

**Comment by pitrou** [comment]
Note this doesn't handle parquet-cpp. Currently the benchmarks don't exercise Parquet at all.

**Comment by wesm** [comment]
I'll take this for a spin when I can, tomorrow or Friday most likely

**Comment by pitrou** [comment]
Example benchmark running step here:
https://travis-ci.org/apache/arrow/jobs/365152266#L7580

The numbers are not very important but it shows `asv run` succeeding on a given changeset.

**Review by xhochy — APPROVED** [review]
+1, LGTM

**Pull request closed without merging**
