### PR TITLE
WIP: [Release] Verify release-13.0.0-rc3

### PR DESCRIPTION
**Pull request by kou**
PR to verify Release Candidate

### CODE REVIEW

**Comment by kou** [comment]
@github-actions crossbow submit  --group verify-rc-source --param release=13.0.0 --param rc=3

**Comment by raulcd** [comment]
@github-actions crossbow submit  --group verify-rc-binaries --group verify-rc-wheels --param release=13.0.0 --param rc=3

**Comment by raulcd** [comment]
Revision: b7d2f7ffca66c868bd2fce5b3749c6caa002a7f0

Submitted crossbow builds: [ursacomputing/crossbow @ release-13.0.0-rc3-0](https://github.com/ursacomputing/crossbow/branches/all?query=release-13.0.0-rc3-0)

|Task|Status|
|----|------|
|almalinux-8-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc3-0-github-almalinux-8-amd64)|
|almalinux-8-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc3-0-github-almalinux-8-arm64)|
|almalinux-9-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc3-0-github-almalinux-9-amd64)|
|almalinux-9-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc3-0-github-almalinux-9-arm64)|
|amazon-linux-2023-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc3-0-github-amazon-linux-2023-amd64)|
|amazon-linux-2023-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc3-0-github-amazon-linux-2023-arm64)|
|centos-7-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc3-0-github-centos-7-amd64)|
|centos-8-stream-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc3-0-github-centos-8-stream-amd64)|
|centos-8-stream-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc3-0-github-centos-8-stream-arm64)|
|centos-9-stream-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc3-0-github-centos-9-stream-amd64)|
|centos-9-stream-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc3-0-github-centos-9-stream-arm64)|
|conan-maximum|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc3-0-github-conan-maximum)|
|conan-minimum|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/5888548871/job/15969956761)|
|debian-bookworm-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc3-0-github-debian-bookworm-amd64)|
|debian-bookworm-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc3-0-github-debian-bookworm-arm64)|
|debian-bullseye-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc3-0-github-debian-bullseye-amd64)|
|debian-bullseye-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc3-0-github-debian-bullseye-arm64)|
|debian-trixie-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc3-0-github-debian-trixie-amd64)|
|debian-trixie-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc3-0-github-debian-trixie-arm64)|
|java-jars|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc3-0-github-java-jars)|
|nuget|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc3-0-github-nuget)|
|python-sdist|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/5888548455/job/15969955159)|
|r-binary-packages|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc3-0-github-r-binary-packages)|
|test-ubuntu-default-docs|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc3-0-github-test-ubuntu-default-docs)|
|ubuntu-focal-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc3-0-github-ubuntu-focal-amd64)|
|ubuntu-focal-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc3-0-github-ubuntu-focal-arm64)|
|ubuntu-jammy-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/5888552088/job/15969966665)|
|ubuntu-jammy-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc3-0-github-ubuntu-jammy-arm64)|
|ubuntu-lunar-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc3-0-github-ubuntu-lunar-amd64)|
|ubuntu-lunar-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/5888552831/job/15969968285)|
|wheel-clean|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc3-0-github-wheel-clean)|
|wheel-macos-big-sur-cp310-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc3-0-github-wheel-macos-big-sur-cp310-arm64)|
|wheel-macos-big-sur-cp311-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc3-0-github-wheel-macos-big-sur-cp311-arm64)|
|wheel-macos-big-sur-cp38-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/5888547831/job/15969953071)|
|wheel-macos-big-sur-cp39-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/5888553535/job/15969970022)|
|wheel-macos-mojave-cp310-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc3-0-github-wheel-macos-mojave-cp310-amd64)|
|wheel-macos-mojave-cp311-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc3-0-github-wheel-macos-mojave-cp311-amd64)|
|wheel-macos-mojave-cp38-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc3-0-github-wheel-macos-mojave-cp38-amd64)|
|wheel-macos-mojave-cp39-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc3-0-github-wheel-macos-mojave-cp39-amd64)|
|wheel-manylinux-2-28-cp310-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc3-0-github-wheel-manylinux-2-28-cp310-amd64)|
|wheel-manylinux-2-28-cp310-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc3-0-github-wheel-manylinux-2-28-cp310-arm64)|
|wheel-manylinux-2-28-cp311-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/5888549754/job/15969959388)|
|wheel-manylinux-2-28-cp311-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/5888547634/job/15969952569)|
|wheel-manylinux-2-28-cp38-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc3-0-github-wheel-manylinux-2-28-cp38-amd64)|
|wheel-manylinux-2-28-cp38-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/5888551331/job/15969964514)|
|wheel-manylinux-2-28-cp39-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc3-0-github-wheel-manylinux-2-28-cp39-amd64)|
|wheel-manylinux-2-28-cp39-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc3-0-github-wheel-manylinux-2-28-cp39-arm64)|
|wheel-manylinux-2014-cp310-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc3-0-github-wheel-manylinux-2014-cp310-amd64)|
|wheel-manylinux-2014-cp310-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc3-0-github-wheel-manylinux-2014-cp310-arm64)|
|wheel-manylinux-2014-cp311-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc3-0-github-wheel-manylinux-2014-cp311-amd64)|
|wheel-manylinux-2014-cp311-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc3-0-github-wheel-manylinux-2014-cp311-arm64)|
|wheel-manylinux-2014-cp38-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc3-0-github-wheel-manylinux-2014-cp38-amd64)|
|wheel-manylinux-2014-cp38-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc3-0-github-wheel-manylinux-2014-cp38-arm64)|
|wheel-manylinux-2014-cp39-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/5888549235/job/15969958102)|
|wheel-manylinux-2014-cp39-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc3-0-github-wheel-manylinux-2014-cp39-arm64)|
|wheel-windows-cp310-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc3-0-github-wheel-windows-cp310-amd64)|
|wheel-windows-cp311-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/5888556648/job/15969978734)|
|wheel-windows-cp38-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc3-0-github-wheel-windows-cp38-amd64)|
|wheel-windows-cp39-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/5888550295/job/15969961286)|

**Comment by raulcd** [comment]
@ursabot please benchmark

**Comment by raulcd** [comment]
@github-actions crossbow submit  --group verify-rc-binaries --group verify-rc-wheels --param release=13.0.0 --param rc=3

**Pull request merged**
