### PR TITLE
ARROW-4323: [Packaging] Fix failing OSX clang conda forge builds

### PR DESCRIPTION
**Pull request by kszucs**
@xhochy I've managed to fix the xcode errors, now it's failing with the `mach_port_t` compile error.

Does your [patch](https://github.com/conda-forge/arrow-cpp-feedstock/pull/72/commits/81ef94ad9041e28e417c03cc6bab1bd0a0ee9a21) work?

### CODE REVIEW

**Comment by xhochy** [comment]
@kszucs my patch does not work. I have a different one now in the queue.

Huge thanks for finding the root cause. I would like to merge this and then continue with the `mach_port_t` again.

**Comment by kszucs** [comment]
@xhochy Would You like to merge it now? The travis error is unrelated.

**Review by xhochy — APPROVED** [review]
+1, LGTM

I will have a look to get rid of `Wno-conversion` in a separate PR.

**Comment by kszucs** [comment]
Crossbow build: https://travis-ci.org/kszucs/crossbow/builds/483303370
It has already passed, but restarted the builds because travis failed to upload the artifact (which happens occasionally)

**Comment by kszucs** [comment]
+1

The crossbow build is still failing, but because of some travis-ruby deployment error, which is unrelated.

**Pull request closed without merging**
