### PR TITLE
ARROW-1771: [C++] ARROW-1749 Breaks Public API test in parquet-cpp

### PR DESCRIPTION
**Pull request by cpcloud**

### CODE REVIEW

**Comment by wesm** [comment]
Good catch, time to add a public API test suite in Arrow, too.

**Comment by cpcloud** [comment]
I'll add a `public-ap-test` in this PR that test that `DCHECK` isn't defined and we can keep adding to it as needed.

**Comment by cpcloud** [comment]
@wesm Actually, is there any reason we shouldn't just prevent compilation if `DCHECK` is defined when including `arrow/api.h`? This would of course only fail to compile if someone is compiling tests.

**Comment by cpcloud** [comment]
so instead of a full blown test executable we have somethign like this:

```c++
#ifdef DCHECK
#error "helpful message"
#endif
```

**Comment by wesm** [comment]
Well, somewhere we need a test executable that is using the public API headers. I think the risk is that unit tests may include non-public headers (including gtest and other things) and so it may be hard to isolate the exact things we want to test

**Comment by cpcloud** [comment]
@wesm The most recent commit includes an example of what I'm talking about.

**Review by wesm — APPROVED** [review]
+1

**Comment by wesm** [comment]
You might like my bash function for pre-checkin

```
function arrow_preflight {
    ARROW_PREFLIGHT_DIR=$HOME/code/arrow/cpp/preflight
    mkdir -p $ARROW_PREFLIGHT_DIR
    pushd $ARROW_PREFLIGHT_DIR
    arrow_cmake
    ninja format
    ninja lint
    popd
    pushd $HOME/code/arrow/python
    flake8 --count pyarrow
    flake8 --count --config=.flake8.cython pyarrow
    popd
}
```

**Pull request closed without merging**
