### PR TITLE
ARROW-5916: [C++] Allow RecordBatch.length to be less than array lengths

### PR DESCRIPTION
**Pull request by jgm-ktg**

### CODE REVIEW

**Comment by wesm** [comment]
I'm still having a hard time with this, I'm concerned about the implications for other implementations. 

We have `custom_metadata` in `Message` here

https://github.com/apache/arrow/blob/master/format/Message.fbs#L98

This isn't properly exposed yet in C++, but it seems like this would be the place to serialize instructions for your application to slice the record batches that are coming out. We might need to return to this discussion on the mailing list now that we have a concrete implementation proposal to look at (which was absent in the past).

**Comment by xhochy** [comment]
I cannot find the correct mail thread but I remember there was one. Can someone point me to it? I currently would object to this PR as this seems to is a huge complication I don't really understand the need for. The RecordBatch is actually quite a good structure as you will not have to deal with chunking and can make the simple assumption that all its arrays are of the same length.

**Comment by jgm-ktg** [comment]
> I cannot find the correct mail thread but I remember there was one. Can someone point me to it? I currently would object to this PR as this seems to is a huge complication I don't really understand the need for. The RecordBatch is actually quite a good structure as you will not have to deal with chunking and can make the simple assumption that all its arrays are of the same length.

@xhochy 

https://lists.apache.org/thread.html/2692dd8fe09c92aa313bded2f4c2d4240b9ef75a8604ec214eb02571@%3Cdev.arrow.apache.org%3E
with special reference to https://www.dropbox.com/sh/6ycfuivrx70q2jx/AAAt-RDaZWmQ2VqlM-0s6TqWa?dl=0

I'll take another shot at it; there are two motives:

(1) We want to pre-allocate an entire batch, perhaps by popping it from a pool of pre-built batches, and populate it by overwriting row data.  In the case of variable-length fields it may be that we cannot completely fill the batch.  (See the Dropbox link above for illustrations.)  By writing a batch length that is less than the array lengths we can "close" the batch without the inefficiencies of retooling our allocations.  Think of this in a shared memory context or a mapped file context.  "Vanilla" IPC readers would not stumble over this if the proposal were adopted... e.g. a pyarrow reader of a batch in a file would read only the relevant slice without the need for side-car data.

(I believe that this strategy of pre-allocating and wasting space will be the fastest way to compose a batch, but I have not yet had time to write a comparison with current batch-building algos to prove the point.)

(2) With appropriate consistency locking in place, we may want to analyze the results of a batch before it is completely constructed using the method in #1.  Again it seems helpful to communicate in the metadata how much of the batch is populated.

These considerations only have considerable strength in my mind because of the desire for readers of such batches to be unaware that they are "special."  A researcher using pyarrow to surf a file that was created from such batches should not have to jump through hoops to know what to ignore, IMHO.

I realize that consideration #2 breaks the immutability doctrine surrounding batches... a doctrine that will be broken on a regular basis by applications that cannot afford to choose between latency and columnar layout.  This being the case, I really think it is worth the effort to make it official and put some guidance around it.  But even without this consideration, I believe that universal compatibility (on the reader side) with batches built using the space/time tradeoff (in favor of time) in #1 justifies this simple change that does not seem to be injurious to anything else.

**Comment by emkornfield** [comment]
Per mailing list thread and discussion here by PMC members I think this is a specialized enough use-case that we shouldn't be altering this check in the code base.

**Pull request closed without merging**
