### PR TITLE
ARROW-5967: [Java] DateUtility#timeZoneList is not correct

### PR DESCRIPTION
**Pull request by tianchen92**
Related to [ARROW-5967](https://issues.apache.org/jira/browse/ARROW-5967).
Now timeZoneList in DateUtility belongs to Joda time.
Since we have replace Joda time with Java time in ARROW-2015, this should also be changed.

TimeStampXXTZVectors have a timezone member which seems not used now and its getObject returns Long(different with that in TimeStampXXVectors which returns LocalDateTime), should it return LocalDateTime with its timezone?

Is it reasonable if we do as follows:
1. remove Joda timezoneList in DateUtility
2. add method like getLocalDateTimeFromEpochMilli(long epochMillis, String timezone) in DateUtility
3. Not sure make TimeStampXXTZVectors return LocalDateTime？

### CODE REVIEW

**Comment by emkornfield** [comment]
My vote would be to either leave as is or would be to have TimeStampXXTZVectors return ZonedDateTime or something similar.  CC @BryanCutler who I think did the initial migration to get his thoughts.

**Comment by BryanCutler** [comment]
Yeah, a lot of from `DateUtility` I was not sure of the usage, so I left most as is. It would be nice to clean it up and (1) and (2) sound reasonable to me. I think changing the vector API in (3) might be better brought up as a separate issue. Could someone from Dremio verify what is being used in this utility and what could be cleaned up? cc @pravindra

**Comment by tianchen92** [comment]
@praveenbingo @pravindra Mind take a look and give some comments about TimeStampXXTZVectors API change? thanks

**Comment by pravindra** [comment]
sorry for the delay, @tianchen92 - will get back to you on this by tomorrow.

**Comment by pravindra** [comment]
This patch requires only a minor change in dremio, and I agree this list doesn't belong here. So, I'm fine with 1 and 2. 

For 3 - dremio doesn't support the TZ variants yet. If there is no immediate use case, I'd prefer to leave it as it is.

**Review by pravindra — APPROVED** [review]
I'll wait for day to see if there are any objections and then, merge.

**Comment by tianchen92** [comment]
Thanks a lot for your efforts

**Comment by pravindra** [comment]
thanks @tianchen92 for fixing this.

**Pull request closed without merging**
