### PR TITLE
ARROW-11931: [Go] bump to go1.15

### PR DESCRIPTION
**Pull request by zeroshade**
@emkornfield 

spun off from #9671

### CODE REVIEW

**Comment by zeroshade** [comment]
Once someone merges this in, I'll update the linked PR

**Comment by emkornfield** [comment]
@sbinet does this seem OK.  It looks like 1.15 got released relatively recently (Aug 2020?).

**Review by sbinet — APPROVED** [review]
it's fine.

the usual dev-cycle of Go-based projects is to follow the Go-stdlib rules (that explicitly support `N` and `N-1` releases, and best effort for earlier releases).
Go-1.16 was released a couple of weeks ago so we're golden.

besides, IIUC, that's just requiring Go-1.15 for testing, right?
I don't suppose we do use >=Go-1.15 constructs or packages.

**Comment by sbinet** [comment]
ah, that's for the Gonum (Go-1.14) and for go-parquet (Go-1.15, for the signed int shifts):
```
# github.com/apache/arrow/go/parquet/internal/bmi
internal/bmi/bmi_noasm.go:239:28: invalid operation: value << bitLen (shift count type int, must be unsigned integer)
internal/bmi/bmi_noasm.go:251:22: invalid operation: uint64(1) << idx (shift count type int, must be unsigned integer)652
internal/bmi/bmi_noasm.go:253:22: invalid operation: uint64(0) << idx (shift count type int, must be unsigned integer)
note: module requires Go 1.15
```

**Comment by zeroshade** [comment]
I'm explicitly not changing the go1.12 declaration in the arrow go.mod, so anyone currently using it shouldn't be affected.

At a worst case scenario, I can modify the go-parquet to introduce a new build and test pipeline with go1.15 rather than piggy backing off the existing go-arrow pipeline and adding the go-parquet directory. I just figured that was excessive since the other languages didn't seem to separate the arrow and parquet build and tests.

**Comment by sbinet** [comment]
I think that's fine.

**Comment by kou** [comment]
Can we merge this?

**Pull request closed without merging**
