### PR TITLE
ARROW-11138: [Rust] [DataFusion] Add ltrim, rtrim to built-in functions

### PR DESCRIPTION
**Pull request by ovr**
Hello!

Thanks

### CODE REVIEW

**Comment by seddonm1** [comment]
These were not added previously as technically they are not in the ANSI SQL standards. Hopefully this can drive a decision on what dialect to support.

**Review by jorgecarleitao — APPROVED** [review]
Thanks a lot, @ovr ! LGTM.

Could you

1. add the corresponding functions to the `prelude`, so that the DataFrame API can also use them?
2. fix the formatting so that the CI passes?

**Comment by ovr** [comment]
@seddonm1 

> Hopefully this can drive a decision on what dialect to support.

Should I create an issue to discuss it or mailing list? Is there any channel for communications like slack?

@jorgecarleitao 

Thanks. Done ✅

**Comment by jorgecarleitao** [comment]
@andygrove @alamb , opinions?

My (weak) opinion is that as long as we do not conflict with ANSI SQL (in that we offer a conflicting or incomplete spec), I do not see any problem.

**Comment by seddonm1** [comment]
Thanks @jorgecarleitao and @ovr 

My view would be to elect an initial dialect (my preference being Postgres - https://www.postgresql.org/docs/13/functions-string.html which supports ANSI + what appear to be sensible additions), document that in the readme and assess any function PRs against that. The secondary benefit is that we can point to the Postgres (or other) docs for usage instructions. 

The risk of not making the decision early risks what happened with Spark SQL where [functions](https://spark.apache.org/docs/latest/api/sql/index.html) were added seemingly ad-hoc making their usage very difficult and no clear feature matrix available.

I am happy to volunteer to update documentation if we can reach the consensus on dialect.

**Comment by alamb** [comment]
I agree with @seddonm1  that ideally we would follow Postgres when possible so we can just re-use all their documentation and semantics and so we don't end up inadvertently creating yet another SQL dialect like spark. 

Specifically in this case, it looks like the relevant postgres function is called `TRIM`. A screen shot from https://www.postgresql.org/docs/9.1/functions-string.html

Screen Shot 2021-01-06 at 6 29 19 PM

**Comment by andygrove** [comment]
I am also +1 for choosing Postgres dialect as the default.

**Comment by seddonm1** [comment]
> I agree with @seddonm1 that ideally we would follow Postgres when possible so we can just re-use all their documentation and semantics and so we don't end up inadvertently creating yet another SQL dialect like spark.
> 
> Specifically in this case, it looks like the relevant postgres function is called `TRIM`. A screen shot from https://www.postgresql.org/docs/9.1/functions-string.html

FYI (because I had to work this out) the way to read the Postgres documentation the first table (Table 9-6. SQL String Functions and Operators) is the ANSI SQL and the second table (Table 9-7. Other String Functions) are Postgres dialect specific implementations. This pattern is standardised for other Postgres documentation.

You can see that `ltrim` comes from the Table 9-7. Other String Functions section.

**Review by alamb — APPROVED** [review]
Thanks for the pointer @seddonm1  

Thus is looks to me like this PR implements (a subset) of the postgres functions LTRIM and RTRIM. My suggestion is that we merge this PR and file a JIRA to add the second optional arguments (what character to trim) - it would probably be a good introductory item for new contributors. 

Screen Shot 2021-01-07 at 7 14 19 AM

If no one objects (or beats me to it) I'll merge this one and file the follow on ticket

**Comment by alamb** [comment]
Filed https://issues.apache.org/jira/browse/ARROW-11164 for the optional second argument

Filed https://issues.apache.org/jira/browse/ARROW-11165 to document the desired dialect -- I'll try and create a proposal and send a note to the mailing list

**Review by alamb — COMMENTED** [review]
Thanks @ovr !

**Pull request closed without merging**
