### PR TITLE
GH-37560 [Python][Documentation] Replacing confusing batch size from 128Ki to 128_000

### LINKED ISSUE #37560: [Python][Docs] PyArrow Documentation bug dataset.to_batches()
### Describe the bug, including details regarding any error messages, version, and platform.

https://github.com/apache/arrow/blob/main/python/pyarrow/_dataset.pyx#L3439

Default value is misleading and it suggests that user should define chunk size (128 Ki) rather than number of rows

I would use `2**17` or `128_000` rather than `128 Ki`

### Component(s)

Documentation, Python

### PR DESCRIPTION
**Pull request by aru-trackunit**
### Rationale for this change

https://github.com/apache/arrow/issues/37560

### Are there any user-facing changes? -> Documentation
* Closes: #37560

### CODE REVIEW

**Comment by aru-trackunit** [comment]
Mmm correct I went for a suggestion included in the issue but I think you are right 131072 is a precise number though

**Comment by AlenkaF** [comment]
Thanks for the correction @mapleFU! Would `2**17` be prefered in this case?

**Comment by aru-trackunit** [comment]
Is this PR good enough? Should I do something more about it?

**Comment by danepitkin** [comment]
IMO it is not exactly clear that 131072 is supposed to be 128KB. I would prefer only making the change `128 Ki` -> `128 KB`. In the parameter description, we can then add `The default value is (128 * 1024) bytes.`

**Comment by AlenkaF** [comment]
I do agree with Dane on this.
Sorry to steer you into a wrong direction at the start!

**Comment by mapleFU** [comment]
> IMO it is not exactly clear that 131072 is supposed to be 128KB. 

batch size doesn't means KB (kilobytes)

> Would 2**17 be prefered in this case?

All is look good to me(though I think previous 128Ki is also ok)

**Review by mapleFU — APPROVED** [review]

**Comment by AlenkaF** [comment]
OK, great to see this being opened up as it is not clear to us also =)
I will merge this as is, with `131_072`.

**Comment by danepitkin** [comment]
> > IMO it is not exactly clear that 131072 is supposed to be 128KB.
> 
> batch size doesn't means KB (kilobytes)

You're right, I didn't realize this was talking about rows instead of bytes!

**Pull request merged**
