### PR TITLE
ARROW-8246: [C++] Add -Wa,-mbig-obj to CXXFLAGS on MinGW if it is supported

### PR DESCRIPTION
**Pull request by wesm**
Hopefully this will resolve issues with debug builds on MinGW

### CODE REVIEW

**Comment by wesm** [comment]
cc @kou @nealrichardson

**Review by kou — APPROVED** [review]
+1

**Comment by kou** [comment]
AppVeyor: https://ci.appveyor.com/project/wesm/arrow/builds/31775468

**Comment by kou** [comment]
Should we try debug build in this pull request?

**Comment by kou** [comment]
I tried debug build on local but `ld` still takes long time...

**Comment by kou** [comment]
Oh, `ld` finished.
It seems that this fixes debug build problem on MinGW.

**Comment by wesm** [comment]
Ah great, thanks @kou for checking. Merging this

**Pull request closed without merging**
