### PR TITLE
GH-41463: [C++] Skip TestConcurrentFillFromScalar for platforms without threading support

### PR DESCRIPTION
**Pull request by zanmato1984**
### Rationale for this change

See #41463 and https://github.com/apache/arrow/pull/40237#issuecomment-2084577090

### What changes are included in this PR?

Skip test for platforms that have no threading support.

### Are these changes tested?

Change is test.

### Are there any user-facing changes?

None.

* GitHub Issue: #41463

### CODE REVIEW

**Comment by zanmato1984** [comment]
cc @jorisvandenbossche

**Comment by raulcd** [comment]
Can we create an issue for this? This is not MINOR and it is currently failing on the 16.1.0 maintenance branch. It should be cherry-picked and for it to be cherry-picked and milestoned correctly we require an issue.

**Comment by jorisvandenbossche** [comment]
This should not be on 16.1.0, though?

**Comment by jorisvandenbossche** [comment]
Or was it added explicitly to 16.1 because of fixing a data race?

**Comment by zanmato1984** [comment]
> Can we create an issue for this? This is not MINOR and it is currently failing on the 16.1.0 maintenance branch. It should be cherry-picked and for it to be cherry-picked and milestoned correctly we require an issue.

Thanks for reminding. I've filed #41463 and updated the PR description. Sorry for the trouble.

**Review by mapleFU — APPROVED** [review]

**Comment by jorisvandenbossche** [comment]
@github-actions crossbow submit test-ubuntu-22.04-cpp-emscripten

**Review by jorisvandenbossche — APPROVED** [review]

**Comment by jorisvandenbossche** [comment]
Thanks @zanmato1984 for the quick follow-up

**Pull request merged**
