### PR TITLE
GH-40448: [CI][Dev] Run pre-commit

### PR DESCRIPTION
**Pull request by kou**
### Rationale for this change

We have pre-commit configuration but it's not used in CI.

### What changes are included in this PR?

Run pre-commit in CI.

### Are these changes tested?

Yes.

### Are there any user-facing changes?

No.
* GitHub Issue: #40448

### CODE REVIEW

**Review by raulcd — COMMENTED** [review]
LGTM, is your idea that we remove archery lint in the future on this issue? https://github.com/apache/arrow/issues/40417

**Comment by kou** [comment]
Yes. I want to do it if nobody objects it.

**Comment by pitrou** [comment]
The pre-commit step is now taking hours on most CI runs. Can you take a look @raulcd @kou ?
Example: https://github.com/apache/arrow/actions/runs/8412061637

**Comment by kou** [comment]
I've opened #40791 for it.

**Pull request merged**
