### PR TITLE
ARROW-3382: [Gandiva][C++] Run tests in travis

### PR DESCRIPTION
**Pull request by pravindra**

### CODE REVIEW

**Comment by wesm** [comment]
re2 needs to be added to the conda toolchain. I'm working on this in https://github.com/conda-forge/re2-feedstock/pull/15, I will update this PR once I get that merged

**Comment by pravindra** [comment]
> re2 needs to be added to the conda toolchain. 

Thanks Wes. I'll test out the rest of the travis script by then.

**Comment by wesm** [comment]
I added the option to link dynamically to re2 while libre2.a is not yet available in the conda toolchain. This is https://issues.apache.org/jira/browse/ARROW-3435

**Comment by wesm** [comment]
OK, now we're down to compiler warnings:

```
/home/travis/build/apache/arrow/cpp/src/gandiva/precompiled/bitmap.cc: In function ‘void bitMapSetBit(unsigned char*, int, bool)’:
/home/travis/build/apache/arrow/cpp/src/gandiva/precompiled/bitmap.cc:41:17: error: conversion to ‘unsigned char’ from ‘long unsigned int’ may alter its value [-Werror=conversion]
   bmap[byteIdx] ^= (-value ^ bmap[byteIdx]) & (1UL << bitIdx);
                 ^
/home/travis/build/apache/arrow/cpp/src/gandiva/precompiled/bitmap.cc: In function ‘void bitMapClearBitIfFalse(unsigned char*, int, bool)’:
/home/travis/build/apache/arrow/cpp/src/gandiva/precompiled/bitmap.cc:50:19: error: conversion to ‘unsigned char’ from ‘int’ may alter its value [-Werror=conversion]
     bmap[byteIdx] &= ~(1 << bitIdx);
```

**Comment by pravindra** [comment]
@wesm - I've added a new CI entry for gandiva cpp build and cpp tests. Will add java build and tests in the next PR.

The travis build  failed for a java entry (some flight tests), that are not related to my changes.

**Comment by wesm** [comment]
OK, yes that's ARROW-3343. I'll look later today and merge if no one gets to it first

**Review by wesm — APPROVED** [review]
+1

**Pull request closed without merging**
