### PR TITLE
ARROW-5564: [C++] Use uriparser from conda-forge

### PR DESCRIPTION
**Pull request by pitrou**

### CODE REVIEW

**Comment by kszucs** [comment]
@pitrou please add it to the crossbow conda build too https://github.com/apache/arrow/blob/master/dev/tasks/conda-recipes/arrow-cpp/meta.yaml

**Comment by pitrou** [comment]
@kszucs Done.

**Comment by pitrou** [comment]
AppVeyor after the uriparser package was actually available on conda-forge: https://ci.appveyor.com/project/pitrou/arrow/builds/25664179

**Comment by kszucs** [comment]
Also run `ursabot crossbow package -g conda` after uriparser gets available.

**Comment by pitrou** [comment]
@ursabot crossbow package -g conda

**Comment by pitrou** [comment]
Hmm, one of the AppVeyor builds took too long (more than 1 hour)!

**Comment by kszucs** [comment]
Yep, we should move the the windows builds to azure as well, but CF still has issues with it.

**Review by wesm — APPROVED** [review]
+1

**Pull request closed without merging**
