### PR TITLE
PARQUET-1581: [C++] Fix undefined behavior in encoding.cc 

### PR DESCRIPTION
**Pull request by emkornfield**

### CODE REVIEW

**Comment by wesm** [comment]
Do you know how this UB could occur?

**Comment by emkornfield** [comment]
Hmm, this came up after cleaning up unaligned access UBSan errors, but I think had a small bug in that cleanup and reverted.  I'll see if I can reproduce without it but will close this for now until I can (I also need to open a thread about UBSan issues on the mailing list).

**Comment by emkornfield** [comment]
I haven't following the code paths fully but n DictEncoding/0.CheckDecodeArrowUsingDenseBuilder
when I log:
```
  541     ARROW_LOG(INFO) << "encoder num entries: " << dict_encoder->num_entries();
  542     plain_decoder_->SetData(dict_encoder->num_entries(), dict_buffer_->data(),
  543                             static_cast<int>(dict_buffer_->size()));
```
I see 
```
I0517 12:58:39.690502 14292 encoding-test.cc:541] encoder num entries: 99
I0517 12:58:39.692281 14292 encoding-test.cc:541] encoder num entries: 99
I0517 12:58:39.693528 14292 encoding-test.cc:541] encoder num entries: 0
```
I believe the last entry exercises this code path.

**Comment by emkornfield** [comment]
If the above doesn't sound right I can dig further.

**Comment by wesm** [comment]
OK. I'm interested in the UBSAN report to see what the UB is actually occurring, could we set up a docker-compose build for this?

**Comment by emkornfield** [comment]
sorry should have clarified this was a null reference error.  ive updated the PR with a more specific fix.

**Comment by emkornfield** [comment]
I'll open up  follow-up JIRAs per discussion on the ML to get UBsan integrated with the build

**Comment by emkornfield** [comment]
I opened up https://issues.apache.org/jira/browse/ARROW-5365 to track adding in UBSan and ASAN to CI (I thought we were already doing ASAN though?)

**Review by pitrou — APPROVED** [review]
LGTM.

**Comment by pitrou** [comment]
> I thought we were already doing ASAN though?

No we are not. We had Valgrind runs but we disabled them because of regressions when refactoring the CMake build system AFAICT.

**Comment by pitrou** [comment]
Note: null pointers are generally a PITA with C++ undefined behaviour rules. You often need to special-case the null case, even when it seems things should be alright as the size is zero. @bkietz

**Pull request closed without merging**
