### PR TITLE
ARROW-2709: [Python] Write a dataset without converting arrow table to pandas

### PR DESCRIPTION
**Pull request by na11an**
Hello,
I would like to ask you to have a look on the careful suggestion for the issue.
I think that It would be temporary alternative for large data set before preparing group-by operation although it seems to be not efficient in terms of performance.

### CODE REVIEW

**Comment by kou** [comment]
There are many conflicts.
Can you create a branch instead of using the "master" branch and try again?

**Comment by wesm** [comment]
@na11an I am -1 on this approach to solving the problem as it is going to be too slow. The preferred solution is to implement filtering and selection in C++, then make this available in Python

**Comment by na11an** [comment]
@wesm I also agree with your opinion. 
However, it would be ok to implement the functions in C++ with this JIRA item. May I try contributing it continuously? The purpose of this change is to share the idea. I would like to close this change and create the other pull request https://github.com/apache/arrow/pull/3344 for the issue.

**Comment by wesm** [comment]
You are welcome to create a C++ implementation. There are many details involved to do this because the partition keys have to be hashed to categorize the rows of the table. Before you begin to work on the project I recommend that you propose your implementation plan in one or more JIRA issues to make sure the rest of us agree.

**Pull request closed without merging**
