### PR TITLE
ARROW-11570: [Rust] ScalarValue - support Date64

### PR DESCRIPTION
**Pull request by ovr**
Introduce support for ScalarValue::Date64.

### CODE REVIEW

**Review by alamb — APPROVED** [review]
Looks good to me. Thanks @ovr

**Comment by alamb** [comment]
Any thoughts @Dandandan  or @andygrove ?

**Review by Dandandan — APPROVED** [review]
LGTM 👍

**Comment by alamb** [comment]
Thanks @Dandandan  and @ovr !

**Pull request closed without merging**
