### PR TITLE
ARROW-15781: [Python] Release GIL in ensure_complete_metadata

### LINKED ISSUE #12501: [python] Parallel parquet metadata resolution?
Hi all,

We're trying to improve the metadata resolution performance of pyarrow's ParquetDataset in Ray (https://github.com/ray-project/ray/issues/21274). Metadata resolution is a bottleneck when directories have 1000s of files in cloud storage.

Trying multiple threads or processes, both approaches seem to have issues:
- With threads: there is a mutex preventing concurrent metadata resolution of arrow::dataset::ParquetFileFragments.
- With processes: Serializing a ParquetFileFragment to send to another process triggers metadata resolution (again hitting the lock issue).

Is there a recommended way of achieving parallelism here?

### PR DESCRIPTION
**Pull request by lidavidm**
Closes #12501.

### CODE REVIEW

**Comment by lidavidm** [comment]
@ericl would you be able to build this and ensure it fixes your case too?

I tested with the following:

```diff
diff --git a/cpp/src/arrow/dataset/file_parquet.cc b/cpp/src/arrow/dataset/file_parquet.cc
index cdee1f006..52de0ea11 100644
--- a/cpp/src/arrow/dataset/file_parquet.cc
+++ b/cpp/src/arrow/dataset/file_parquet.cc
@@ -17,6 +17,8 @@
 
 #include "arrow/dataset/file_parquet.h"
 
+#include <chrono>
+#include <thread>
 #include <memory>
 #include <mutex>
 #include <unordered_map>
@@ -561,6 +563,7 @@ Status ParquetFileFragment::EnsureCompleteMetadata(parquet::arrow::FileReader* r
     return EnsureCompleteMetadata(reader.get());
   }
 
+  std::this_thread::sleep_for(std::chrono::seconds(1));
   std::shared_ptr<Schema> schema;
   RETURN_NOT_OK(reader->GetSchema(&schema));
   if (physical_schema_ && !physical_schema_->Equals(*schema)) {
```

and 

```
from concurrent.futures import ThreadPoolExecutor
import time

import pyarrow as pa
import pyarrow.parquet as pq

dataset = pq.ParquetDataset([
    "/home/lidavidm/Documents/ursa-labs-taxi-data/2009/03/data.parquet",
    "/home/lidavidm/Documents/ursa-labs-taxi-data/2009/04/data.parquet",
], use_legacy_dataset=False)

print(dataset.fragments)

pool = ThreadPoolExecutor()

start = time.monotonic()
for x in pool.map(lambda x: x.metadata, dataset.fragments):
    print(x)
end = time.monotonic()
print(end - start)
```

**Comment by ericl** [comment]
I ran into some trouble building pyarrow, but the above test case looks great :+1:  Looking forwards to trying it out in the next release.

**Comment by lidavidm** [comment]
Got it. We do have [nightly packages](https://arrow.apache.org/docs/dev/python/install.html#installing-nightly-packages) for conda/pip so you can test a little sooner than that.

**Review by jorisvandenbossche — COMMENTED** [review]
Looks good, thanks!

**Review by jorisvandenbossche — APPROVED** [review]

**Pull request closed without merging**
