### PR TITLE
WIP: [R] Verify CRAN release-15.0.1

### PR DESCRIPTION
**Pull request by thisisnic**
Do not merge - for release testing purposes only

### CODE REVIEW

**Comment by thisisnic** [comment]
@github-actions crossbow submit --group r

**Comment by assignUser** [comment]
@github-actions crossbow submit --group r

**Comment by assignUser** [comment]
I don't know what to make from this one: https://github.com/ursacomputing/crossbow/actions/runs/8198491573/job/22422094029#step:9:39
It might just be that the devdocs build isn't current with our recent changes but :shrug:

**Comment by assignUser** [comment]
I think many of these are related to https://github.com/apache/arrow/issues/40323

**Comment by thisisnic** [comment]
> I think many of these are related to #40323

Agreed. I don't see anything here which blocks the release. Not sure about the reason for devdocs failing though it seems to happen every release for some reason or another, but given other builds pass it's a non-issue.

**Comment by thisisnic** [comment]
All looks good and package on CRAN now

**Pull request closed without merging**
