### PR TITLE
ARROW-8785: [Python][Packaging] Build the windows wheels with MIMALLOC enabled

### PR DESCRIPTION
**Pull request by kszucs**

### CODE REVIEW

**Comment by kszucs** [comment]
@github-actions crossbow submit wheel-win-cp36m

**Comment by kszucs** [comment]
@github-actions crossbow submit wheel-win-cp36m

**Review by pitrou — APPROVED** [review]
Need to fix git conflicts, otherwise +1 to me.

**Comment by pitrou** [comment]
@github-actions crossbow submit wheel-win-cp36m

**Comment by pitrou** [comment]
@github-actions crossbow submit wheel-win-cp36m

**Comment by pitrou** [comment]
@github-actions crossbow submit wheel-win-cp36m

**Pull request closed without merging**
