### PR TITLE
ARROW-5201: [Python] handle collections.abc deprecation warnings

### PR DESCRIPTION
**Pull request by jorisvandenbossche**
https://issues.apache.org/jira/browse/ARROW-5201

### CODE REVIEW

**Comment by xhochy** [comment]
@jorisvandenbossche Can you rebase on master? Then the appveyor failure is hopefully fixed.

**Comment by jorisvandenbossche** [comment]
In the meaning of: pushing a new commit to trigger AppVeyor again? Or to actually add a commit on master that fixed AppVeyor? As it is already up to date with master.

**Comment by fsaintjacques** [comment]
Rebase with master and push as hopefully this is fixed in master (and will also trigger appveyor again).

**Review by pitrou — APPROVED** [review]
+1 from me.

**Comment by jorisvandenbossche** [comment]
Appveyor is passing now

**Comment by pitrou** [comment]
Thanks @jorisvandenbossche !

**Pull request closed without merging**
