### PR TITLE
MINOR: [CI][C++] Bump aws-sdk-version on conda jobs

### PR DESCRIPTION
**Pull request by pitrou**

### CODE REVIEW

**Comment by pitrou** [comment]
@github-actions crossbow submit *conda*

**Comment by pitrou** [comment]
@h-vetinari @xhochy

**Comment by h-vetinari** [comment]
FWIW, 1.9.379 seems to be doing OK in https://github.com/conda-forge/arrow-cpp-feedstock/pull/875, though the impact of https://github.com/aws/aws-sdk-cpp/issues/2181 isn't clear to me

**Comment by pitrou** [comment]
I'm gonna merge this one.

**Comment by raulcd** [comment]
Could this failure for [AMD64 Windows MinGW MINGW32 C++](https://github.com/apache/arrow/actions/runs/3524800995/jobs/5910691317#logs)
on this PR: https://github.com/apache/arrow/pull/14700
be related to the aws-sdk-version bump?

**Comment by pitrou** [comment]
@raulcd Those builds don't use conda-forge.

**Comment by raulcd** [comment]
oh! of course 🤦‍♂️! I just saw the spurious trace there and got confused:
```
[FATAL] 2022-11-22 16:35:18.683 WinHttpSyncHttpClient [1] Failed setting secure crypto protocols with error code: 87
[FATAL] 2022-11-22 16:35:18.731 WinHttpSyncHttpClient [1] Failed setting secure crypto protocols with error code: 87
```

**Pull request merged**
