### PR TITLE
ARROW-10230: [JS][Doc] JavaScript documentation fails to build

### PR DESCRIPTION
**Pull request by kszucs**

### CODE REVIEW

**Comment by kszucs** [comment]
@github-actions crossbow submit test-ubuntu-18.04-docs

**Comment by kszucs** [comment]
@github-actions crossbow submit test-ubuntu-18.04-docs

**Comment by kszucs** [comment]
@github-actions crossbow submit test-ubuntu-18.04-docs

**Review by trxcllnt — APPROVED** [review]

**Comment by kszucs** [comment]
The build failure is irrelevant.

**Pull request closed without merging**
