### PR TITLE
ARROW-16736: [C++] Bump vendored version of RE2

### PR DESCRIPTION
**Pull request by raulcd**

### CODE REVIEW

**Comment by raulcd** [comment]
@github-actions crossbow submit -g cpp

**Review by pitrou — APPROVED** [review]
LGTM, let's just wait for CI

**Comment by raulcd** [comment]
The test-conda-cpp-valgrind has been failing on the nightlies for the last days. I have created a new JIRA ticket to track it:
https://issues.apache.org/jira/browse/ARROW-17041

**Comment by pitrou** [comment]
Thanks @raulcd !

**Pull request merged**
