### PR TITLE
ARROW-5669: [Python][Packaging] Add ARROW_TEST_DATA env variable to Crossbow Linux Wheel build

### PR DESCRIPTION
**Pull request by wesm**

### CODE REVIEW

**Comment by wesm** [comment]
@ursabot crossbow test package wheel

**Comment by wesm** [comment]
@ursabot crossbow package -g wheel

**Comment by wesm** [comment]
Phew OK https://travis-ci.org/wesm/crossbow/builds/548464496

**Comment by wesm** [comment]
+1, will wait for the Travis linter to run

**Comment by pcmoritz** [comment]
+1 Awesome :)

**Comment by wesm** [comment]
Here's a passing lint https://travis-ci.org/wesm/arrow/jobs/548464278. Merging this so I can rebase the other wheel patch

**Pull request closed without merging**
