### PR TITLE
ARROW-3613: [Go] fix builder resize

### PR DESCRIPTION
**Pull request by alexandreyc**
Hello,

Following the discussion on JIRA here is a patch that fixes the issue with resizing builders.

I think that I would be good that someone who knows the codebase better than I do review this PR.

Alexandre

### CODE REVIEW

**Comment by alexandreyc** [comment]
Oops, still an issue... Working on it.

**Comment by alexandreyc** [comment]
The Ruby build seems to be broken.

**Comment by wesm** [comment]
Probably a transient thing; I just restarted that build. As long as the Go build passes, once someone reviews the patch and it's approved, it can be merged

**Review by wesm — APPROVED** [review]
+1; I was able to read this well enough to see that this behavior is consistent with the docstring. I looked at the C++ implementation and I think that resizing to an absolute size less than the current number of elements in the builder will leave the builders in a bad state. I opened https://issues.apache.org/jira/browse/ARROW-3740 to investigate

**Pull request closed without merging**
