### PR TITLE
ARROW-4076: [Python] Validate ParquetDataset schema after filtering

### PR DESCRIPTION
**Pull request by gsakkis**
Fixes https://issues.apache.org/jira/browse/ARROW-4076

### CODE REVIEW

**Review by emkornfield — CHANGES_REQUESTED** [review]
Hi @gsakkis Would it be possible to add a unit-test to prevent a regression?

**Comment by xhochy** [comment]
Rebased

**Comment by jorisvandenbossche** [comment]
Hi @gsakkis, do you have time to update this PR? (adding a test)

Otherwise I can also take a look into updating it.

**Comment by jorisvandenbossche** [comment]
This PR can be closed now, since it was merged (+test) as https://github.com/apache/arrow/pull/4600

**Pull request closed without merging**
