### PR TITLE
ARROW-6563: [Rust] [DataFusion] MergeExec

### PR DESCRIPTION
**Pull request by andygrove**
Implement the MergeExec execution plan for executing partitions in parallel and merging into a single partition.

### CODE REVIEW

**Comment by andygrove** [comment]
@paddyhoran @sunchao @nevi-me Here's another relatively small PR that would be good to get reviewed soon if possible. Thanks!

**Review by paddyhoran — CHANGES_REQUESTED** [review]
Can we add a simple test or two, other than that LGTM

**Comment by andygrove** [comment]
@paddyhoran I added a test and this is ready for re-review. Thanks!

**Review by paddyhoran — APPROVED** [review]
LGTM

**Pull request closed without merging**
