### PR TITLE
ARROW-13134: [C++][CI] Pin aws-sdk-cpp to < 1.9

### PR DESCRIPTION
**Pull request by pitrou**

### CODE REVIEW

**Comment by pitrou** [comment]
@github-actions crossbow submit -g conda

**Comment by pitrou** [comment]
Successful AppVeyor build here: https://ci.appveyor.com/project/pitrou/arrow/builds/39798005

**Comment by pitrou** [comment]
@xhochy Should I also update the conda recipe?

**Comment by xhochy** [comment]
> @xhochy Should I also update the conda recipe?

No, there we pin it already via the files in ci_support.

**Comment by xhochy** [comment]
@github-actions crossbow submit test-conda-*

**Comment by xhochy** [comment]
The conda group in crossbow is not relevant for this PR. I triggered the right one 😉

**Comment by pitrou** [comment]
Ahah, thank you :-D

**Review by xhochy — APPROVED** [review]
+1, LGTM

Merge on green.

**Pull request closed without merging**
