### PR TITLE
ARROW-9579: [C++] Provide the plugin API to support customized compression codec for parquet

### PR DESCRIPTION
**Pull request by xieqi**
This PR provide plugin framework for parquet to support customized compression codec , please see proposal 
https://docs.google.com/document/d/1W_TxVRN7WV1wBVOTdbxngzBek1nTolMlJWy6aqC6WG8/edit

### CODE REVIEW

**Comment by emkornfield** [comment]
Thank you for the PR this will likely need a great deal of review from both code and design perspective.  Before it is reviewed it should have thorough unit tests.  And since it deals with Parquet interop it should also likely have some method of verifying compatibility with the Java implementation of possible (also a link to the corresponding Java pr would be useful)

**Comment by pitrou** [comment]
Hmm, reading the mailing-list discussion again, I don't think we had agreed on a design. The first question for me is what the end-user API should be.
* should the user calling the Parquet reader ask explicitly for a compression override (e.g. "instead of using standard GZip, use HW-accelerated GZip")
* should instead the compression override be configured using a global setting?
* or should the override even be transparent? (how?)

From a first look, I see this PR proposes a plugin API, which does not seem necessary to solve the problem at hand. Arrow is a library and I'm not sure it's our duty to implement a specific extension-loading mechanism (though I could be convinced otherwise :-)).

**Comment by winningsix** [comment]
@pitrou  @emkornfield  FYI. This is Java side PR. https://github.com/apache/parquet-mr/pull/803/files

**Comment by xieqi** [comment]
@pitrou 
For Parquet write, the end-user still use the standard GZip as the compression codec, we add a compression_plugin API in parquet WriterProperties Builder, the end-user can use the following code snippet to enable plugin:
`parquet::WriterProperties::Builder builder;`
`builder.compression(parquet::Compression::GZIP);`
`builder.compression_plugin("libGzipPlugin.so");`
It will use the plugin to compress and write some plugin hint in ColumnMetaData's key_value_metadata.

For parquet read, it will first check if parquet ColumnMetaData's key_value_metadata has plugin information. It will call plugin to decompress the data if has such metadata, otherwise it will call the standard GZip to decompress data. So it is transparent for end-user in parquet read side.

**Comment by winningsix** [comment]
@xieqi How about the on-disk path? How does user determine whether to use a customized codec for a given compression codec?

**Comment by pitrou** [comment]
I'm going to close this PR as stale, and because the approach here is too heavy-weight as already discussed.

**Comment by pitrou** [comment]
Link to ML discussion: https://lists.apache.org/thread.html/r88c56e47cdd69eda23477c67c8e4ad5e66a3ccb144087082d427ffbf%40%3Cdev.arrow.apache.org%3E

**Pull request closed without merging**
