### PR TITLE
ARROW-8689: [C++] Fix linking S3FS benchmarks

### PR DESCRIPTION
**Pull request by pitrou**

### CODE REVIEW

**Comment by pitrou** [comment]
Java issues on CI look unrelated. @kszucs can you confirm?

**Comment by fsaintjacques** [comment]
Java compilation errors were fixed in #7093

**Comment by pitrou** [comment]
Ok, rebasing.

**Comment by pitrou** [comment]
AppVeyor build: https://ci.appveyor.com/project/pitrou/arrow/builds/32634981

**Pull request closed without merging**
