### PR TITLE
ARROW-16176: [Release][C#] Use .NET 6.0 on Ubuntu 22.04

### PR DESCRIPTION
**Pull request by kou**
Ubuntu 22.04 ships OpenSSL 3 and .NET 5.0 or earlier doesn't support
OpenSSL 3 yet.

### CODE REVIEW

**Comment by kou** [comment]
@github-actions crossbow submit viery-rc-source-csharp-*

**Comment by kou** [comment]
@github-actions crossbow submit verify-rc-source-csharp-*

**Comment by kou** [comment]
@github-actions crossbow submit verify-rc-source-csharp-*

**Comment by kou** [comment]
@eerhardt It seems that our tests can't be ran with .NET 6.0:

https://github.com/ursacomputing/crossbow/runs/5999340698?check_suite_focus=true

```text
Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
Testhost process exited with error: It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '3.1.0' (x64) was not found.
  - The following frameworks were found:
      6.0.4 at [/tmp/arrow-HEAD.6doHP/csharp/bin/shared/Microsoft.NETCore.App]
You can resolve the problem by installing the specified framework and/or SDK.
The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=3.1.0&arch=x64&rid=ubuntu.22.04-x64
. Please check the diagnostic logs for more information.

Test Run Aborted.
  Apache.Arrow.Flight -> /arrow/csharp/artifacts/Apache.Arrow.Flight/Debug/netstandard2.1/Apache.Arrow.Flight.dll
  Apache.Arrow.Flight -> /arrow/csharp/artifacts/Apache.Arrow.Flight/Debug/netstandard2.0/Apache.Arrow.Flight.dll
  Apache.Arrow.Flight.AspNetCore -> /arrow/csharp/artifacts/Apache.Arrow.Flight.AspNetCore/Debug/netcoreapp3.1/Apache.Arrow.Flight.AspNetCore.dll
  Apache.Arrow.Flight.TestWeb -> /arrow/csharp/artifacts/Apache.Arrow.Flight.TestWeb/Debug/netcoreapp3.1/Apache.Arrow.Flight.TestWeb.dll
  Apache.Arrow.Flight.Tests -> /arrow/csharp/artifacts/Apache.Arrow.Flight.Tests/Debug/netcoreapp3.1/Apache.Arrow.Flight.Tests.dll
Test run for /arrow/csharp/artifacts/Apache.Arrow.Flight.Tests/Debug/netcoreapp3.1/Apache.Arrow.Flight.Tests.dll (.NETCoreApp,Version=v3.1)
Microsoft (R) Test Execution Command Line Tool Version 17.0.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
Testhost process exited with error: It was not possible to find any compatible framework version
The framework 'Microsoft.AspNetCore.App', version '3.1.0' (x64) was not found.
  - The following frameworks were found:
      6.0.4 at [/tmp/arrow-HEAD.6doHP/csharp/bin/shared/Microsoft.AspNetCore.App]
You can resolve the problem by installing the specified framework and/or SDK.
The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.AspNetCore.App&framework_version=3.1.0&arch=x64&rid=ubuntu.22.04-x64
. Please check the diagnostic logs for more information.
```

Should we support .NET 6.0? Or should we disable verification with .NET 6.0?

**Comment by eerhardt** [comment]
Sorry for the delay. 

Since 2.1 is EOL, I think it makes sense to update our projects to supported versions.

Do you want me to push changes to this PR to fix this? Or do you want me to send a separate PR?

**Comment by kou** [comment]
> Do you want me to push changes to this PR to fix this? Or do you want me to send a separate PR?

The former is better but you can choose the latter if you have a trouble.

**Comment by eerhardt** [comment]
@github-actions crossbow submit verify-rc-source-csharp-*

**Comment by kszucs** [comment]
@github-actions crossbow submit verify-rc-source-csharp-*

**Comment by kszucs** [comment]
@github-actions crossbow submit verify-rc-source-csharp-*

**Review by kszucs — APPROVED** [review]
Thanks @eerhardt and @kou!

**Comment by kou** [comment]
Thanks @eerhardt !

**Pull request closed without merging**
