### PR TITLE
ARROW-5344: [C++] Use ArrayDataVisitor in dict-to-anything cast

### PR DESCRIPTION
**Pull request by pitrou**
Also fix uninitialized data for null entries.

### CODE REVIEW

**Review by bkietz — APPROVED** [review]
LGTM
Is it a *fix* to initialize values under a null? I think they *could* be left uninitialized

**Comment by pitrou** [comment]
The problem is that the uninitialized memory area could contain remnants of private data, then if you serialize the array the buffers will be copied as-is.

**Comment by wesm** [comment]
This is a new one

```
~/build/pitrou/arrow/cpp/apidoc ~/build/pitrou/arrow/python ~/build/pitrou/arrow
warning: Tag 'PERL_PATH' at line 2150 of file 'Doxyfile' has become obsolete.
         To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
warning: Tag 'MSCGEN_PATH' at line 2172 of file 'Doxyfile' has become obsolete.
         To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
~/build/pitrou/arrow/python ~/build/pitrou/arrow
/home/travis/build/pitrou/arrow/ci/travis_script_python.sh: line 230: 28489 Segmentation fault      (core dumped) sphinx-build -q -b html -d _build/doctrees -W source _build/html
The command "$TRAVIS_BUILD_DIR/ci/travis_script_python.sh 3.6" exited with 139.
```

from https://travis-ci.org/pitrou/arrow/jobs/586179104

**Comment by pitrou** [comment]
I'm restarting the Travis-CI job.

**Comment by pitrou** [comment]
Looks like the Sphinx crash is deterministic and may be caused by the datetime issue fixed in #5416:
https://travis-ci.org/pitrou/arrow/jobs/586179104#L5761

**Comment by pitrou** [comment]
Rebased.

**Pull request closed without merging**
