### PR TITLE
[Java] bump maven.plugins:maven-shade-plugin to 3.4.2

### PR DESCRIPTION
**Pull request by kiszk**
### Rationale for this change

Bumps [org.apache.maven.plugins:maven-shade-plugin](https://github.com/apache/maven-shade-plugin) from 3.2.4 to newer version, but not to 3.5.2

### What changes are included in this PR?

bump org.apache.maven.plugins:maven-shade-plugin

### Are these changes tested?

via CI

### Are there any user-facing changes?

Should not. Run additional CI for spark integration by using `@github-actions crossbow submit test-spark`

### CODE REVIEW

**Comment by lidavidm** [comment]
@github-actions crossbow submit -g java

**Comment by kiszk** [comment]
3.4.2 causes the following error
```
[INFO] -------------------< org.apache.arrow:arrow-vector >--------------------
[INFO] Building Arrow Vectors 17.0.0-SNAPSHOT                           [12/23]
[INFO]   from vector/pom.xml
[INFO] --------------------------------[ jar ]---------------------------------
Warning:  The POM for org.apache.maven.plugins:maven-shade-plugin:jar:3.4.2 is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Apache Arrow Java Root POM 17.0.0-SNAPSHOT:
[INFO] 
[INFO] Arrow Maven Plugins ................................ SUCCESS [  5.937 s]
[INFO] Module Info Compiler Maven Plugin .................. SUCCESS [  5.198 s]
[INFO] Arrow Bill of Materials ............................ SUCCESS [  4.479 s]
[INFO] Apache Arrow Java Root POM ......................... SUCCESS [  3.896 s]
[INFO] Arrow Format ....................................... SUCCESS [  9.879 s]
[INFO] Arrow Memory ....................................... SUCCESS [  1.650 s]
[INFO] Arrow Memory - Core ................................ SUCCESS [ 14.715 s]
[INFO] Arrow Memory - Unsafe .............................. SUCCESS [  6.950 s]
[INFO] Arrow Memory - Netty Buffer ........................ SUCCESS [  8.400 s]
[INFO] Arrow Memory - Netty ............................... SUCCESS [  4.745 s]
[INFO] Arrow Vectors ...................................... FAILURE [  0.144 s]
[INFO] Arrow Compression .................................. SKIPPED
[INFO] Arrow Tools ........................................ SKIPPED
[INFO] Arrow JDBC Adapter ................................. SKIPPED
[INFO] Arrow Flight ....................................... SUCCESS [  1.654 s]
[INFO] Arrow Flight Core .................................. SKIPPED
[INFO] Arrow Flight SQL ................................... SKIPPED
[INFO] Arrow Flight SQL JDBC Driver Core .................. SKIPPED
[INFO] Arrow Flight SQL JDBC Driver ....................... SKIPPED
[INFO] Arrow Flight Integration Tests ..................... SKIPPED
[INFO] Arrow AVRO Adapter ................................. SKIPPED
[INFO] Arrow Algorithms ................................... SKIPPED
[INFO] Arrow Performance Benchmarks ....................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  46.125 s (Wall Clock)
[INFO] Finished at: 2024-05-26T08:04:08Z
[INFO] ------------------------------------------------------------------------
Error:  Plugin org.apache.maven.plugins:maven-shade-plugin:3.4.2 or one of its dependencies could not be resolved: The following artifacts could not be resolved: org.apache.maven.plugins:maven-shade-plugin:jar:3.4.2 (absent): Could not find artifact org.apache.maven.plugins:maven-shade-plugin:jar:3.4.2 in apache (https://repo.maven.apache.org/maven2/) -> [Help 1]
Error:  
Error:  To see the full stack trace of the errors, re-run Maven with the -e switch.
Error:  Re-run Maven using the -X switch to enable full debug logging.
Error:  
Error:  For more information about the errors and possible solutions, please read the following articles:
Error:  [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException
```

**Comment by kiszk** [comment]
@github-actions crossbow submit test-spark

**Comment by kiszk** [comment]
@github-actions crossbow submit -g java

**Comment by kiszk** [comment]
@github-actions crossbow submit -g java

**Comment by lidavidm** [comment]
Interesting, it looks like anything beyond 3.2 does not work

**Comment by kiszk** [comment]
Yeah, interesting. While I close this, I will include a link to this PR in related issues.

**Pull request closed without merging**
