### PR TITLE
ARROW-4038: [Rust] Implement boolean AND, OR, NOT array ops

### PR DESCRIPTION
**Pull request by andygrove**
- Implements boolean AND, OR, NOT operations in `array_ops`
- Removes all uses of `unwrap()` in array_ops and replaces with `?`
- Improve error messages

### CODE REVIEW

**Comment by andygrove** [comment]
@paddyhoran @sunchao Could I get a review please. Rust tests are passing but Python tests failed with a timeout.

**Comment by nevi-me** [comment]
An unrelated question @andygrove , do you know if Rust vectorises array ops automatically?

**Review by sunchao — COMMENTED** [review]
Thanks @andygrove . It seems there is no well-established rules to define what's the result should be when one of the operand is null. Maybe we should add document for each public methods and clearly describe the behavior. This can be in a different PR of course.

Another minor thing is, in operators such as `gt_eq`, we define:
```rust
    bool_op(left, right, |a, b| match (a, b) {
        (None, _) => false,
        (_, None) => true,
        (Some(aa), Some(bb)) => aa >= bb,
    })
```

However this means `None` and `None` is also mapped to `false`, is that right? This perhaps is unexpected.

**Comment by andygrove** [comment]
Thanks @sunchao I addressed your feedback. Good points.

**Review by sunchao — APPROVED** [review]
LGTM. Thanks @andygrove .

**Pull request closed without merging**
