### PR TITLE
ARROW-5174: [Go] implement Stringer for DataTypes

### PR DESCRIPTION
**Pull request by sbinet**

### CODE REVIEW

**Comment by sbinet** [comment]
needs #4160

**Comment by sbinet** [comment]
PTAL @stuartcarnie @alexandreyc @nickpoorman

**Comment by sbinet** [comment]
(the Travis-CI error is unrelated (JDK-9 is acting up?))

**Comment by alexandreyc** [comment]
LGTM

(except for arrow-cat and arrow-main that I did not fully review since I need read the whole thing first :))

**Comment by sbinet** [comment]
thanks.

feel free to comment on the PR(s) that I might have already collected and I'll retrofit those comments.

**Review by stuartcarnie — APPROVED** [review]
💯

**Pull request closed without merging**
