### PR TITLE
ARROW-3600: [CI/Packaging] Add Ubuntu 18.10

### PR DESCRIPTION
**Pull request by yahonda**
This pull request provides Ubuntu 18.10 support. Originally opened at https://github.com/apache/arrow-dist/pull/30 then transferred to this repository.

### CODE REVIEW

**Comment by kou** [comment]
Thanks.
But we need more works.

We've created a tool for building packages that is called "crossbow". We can find document for crossbow at  https://github.com/apache/arrow/blob/master/dev/tasks/README.md

It's better that you confirm this change by crossbow. But I can do it later.

**Comment by kou** [comment]
We need to add entry to `dev/tasks.yml` and `dev/tasks/linux-packages/package-task.rb` for Ubuntu 18.10.

**Comment by yahonda** [comment]
Thanks for the review. Added two Ubuntu 18.10 entries. I am working on building my crossbow repository.

**Comment by kou** [comment]
Thanks.
I don't try yet but we also need to add `ubuntu-bionic:` entry for artifact list to `dev/tasks.yml`.

**Comment by yahonda** [comment]
Thanks again. Added artifacts entry for ubuntu-cosmic. I hope I understand your comment correctly.

**Comment by kou** [comment]
Thanks.
I'll merge this when we confirm that this change works well with crossbow.

**Comment by kszucs** [comment]
Submitted [build-353](https://github.com/kszucs/crossbow/branches/all?utf8=%E2%9C%93&query=build-353)

**Comment by kszucs** [comment]
I confirm it works as expected. Thanks @yahonda !

**Comment by kou** [comment]
@kszucs Thanks!

I've confirmed that we can upload all artifacts: https://github.com/kou/crossbow/releases/tag/build-44-ubuntu-cosmic

I'll merge this.

**Comment by kou** [comment]
Oh. I stopped. :-)

**Pull request closed without merging**
