### PR TITLE
GH-32110: [R] printing data in Table/RecordBatch print method

### PR DESCRIPTION
**Pull request by thisisnic**
### Rationale for this change

Add output preview for printing of Tables

### What changes are included in this PR?

Methods to add output preview to printed Tables

### Are these changes tested?

Not yet, will be

### Are there any user-facing changes?

Yes

* GitHub Issue: #32110

### CODE REVIEW

**Comment by thisisnic** [comment]
Very rough draft.  Current unresolved questions:
* do we want to display the Arrow type or the R type?
* what objects do we want this to work on?

**Comment by thisisnic** [comment]
I'm not entirely sure this makes sense to add; since the original issue was opened, we've mostly satisfied the original use case as we implemented `glimpse()`, and calling `head()` then `collect()` makes a lot of sense as a workflow for previewing results, as we are explicitly pulling the data into R with those.

For this to make sense, we'd need to swap out the R types for the Arrow types, and document this as something that could be useful after calling `compute()` or working intentionally with Arrow Tables to preserve the type etc.

We still have the schema printing with Datasets, unless we want to extend this to those too, but then are we going to only do it for local Datasets?

**Comment by jonkeane** [comment]
Would you mind adding examples of what this looks like? That might help the discussion too.

> I'm not entirely sure this makes sense to add; since the original issue was opened, we've mostly satisfied the original use case as we implemented glimpse(), and calling head() then collect() makes a lot of sense as a workflow for previewing results, as we are explicitly pulling the data into R with those.
Agreed that `glimpse()` does a lot of what we need, though I suspect that there's a strong contingent of folks who don't know about / use `glimpse()` and it is a second command needed in these circumstances. `glimpse()` is also transposed which folks might not care for (either aesthetically or on principle)  There is value add in there being a "real" `print()` method that acts like a data.frame IMO.

> For this to make sense, we'd need to swap out the R types for the Arrow types, 
Agreed


> We still have the schema printing with Datasets, unless we want to extend this to those too, but then are we going to only do it for local Datasets?
Yeah, thought this might be a step towards under-the-hood (possibly with some opt in or opt out), we run the query with head and return that.

With `dbplyr` we get the head by default:

```
> db <- memdb_frame(a = rep(c(3, 4, 1, 2), 100000), b = rep(c(5, 1, 2, NA), 100000))
> db |> filter(!is.na(b))
# Source:   SQL [?? x 2]
# Database: sqlite 3.45.2 [:memory:]
       a     b
   <dbl> <dbl>
 1     3     5
 2     4     1
 3     1     2
 4     3     5
 5     4     1
 6     1     2
 7     3     5
 8     4     1
 9     1     2
10     3     5
# ℹ more rows
# ℹ Use `print(n = ...)` to see more rows
```

With arrow queries that might not be possible to do in a lightweight way, but I bet there is a way where we could cover most of these in a relatively lightweight way (and again possibly only as an opt in if we're really worried about long running commands...)

**Comment by thisisnic** [comment]
This has turned about to be hairier than it looks and I may have to abandon this PR as I don't have time to finish it.  I'll leave more information here though in case anyone else wants to pick it up or I come back to it at some point.

The issues I had lay in the fact that initially I thought we'd need to define a ton of S3 methods for different functions which needed subtly changing from the ones which run on a tibble.  I tried, on another branch to implement the minimal set of changes, and just edit the displayed table which was created for a tibble, but this led to more problems as the types didn't line up with the column widths and we'd either have to truncate them or dive into the calculation of the column widths which is where I don't have time to go deeper.

To illustrate, here's the `dplyr::starwars` data with Arrow types but the types not aligned with the column names:
```
> arrow_table(dplyr::starwars)
# An Arrow Table: 87 x 14
   name   height  mass hair_color skin_color eye_color birth_year sex   gender homeworld species films
  <string><int32><double><string><string><string><double><string><string><string><string><list<...>><list<...>><list<...>>
 1 Luke …    172    77 blond      fair       blue            19   male  mascu… Tatooine  Human     [5]
 2 C-3PO     167    75 NA         gold       yellow         112   none  mascu… Tatooine  Droid     [6]
 3 R2-D2      96    32 NA         white, bl… red             33   none  mascu… Naboo     Droid     [7]
 4 Darth…    202   136 none       white      yellow          41.9 male  mascu… Tatooine  Human     [4]
 5 Leia …    150    49 brown      light      brown           19   fema… femin… Alderaan  Human     [5]
 6 Owen …    178   120 brown, gr… light      blue            52   male  mascu… Tatooine  Human     [3]
 7 Beru …    165    75 brown      light      blue            47   fema… femin… Tatooine  Human     [3]
 8 R5-D4      97    32 NA         white, red red             NA   none  mascu… Tatooine  Droid     [1]
 9 Biggs…    183    84 black      light      brown           24   male  mascu… Tatooine  Human     [1]
10 Obi-W…    182    77 auburn, w… fair       blue-gray       57   male  mascu… Stewjon   Human     [6]
# ℹ 77 more rows
# ℹ 2 more variables: vehicles <list<character>>, starships <list<character>>
# ℹ Use `print(n = ...)` to see more rows
```

Here's the branch containing the simpler implementation that's a bit nicer than where I got to with this one: https://github.com/apache/arrow/compare/main...thisisnic:arrow:print2

**Pull request closed without merging**
