### PR TITLE
ARROW-3621: [Go] implement Table, Record, RecordReader and TableReader

### PR DESCRIPTION
**Pull request by sbinet**
This CL implements a few things:
- Table, Schema and Column (needs #2838 to go in and then a rebase)
- RecordBatch and RecordBatchReader
- TableReader

### CODE REVIEW

**Comment by sbinet** [comment]
@stuartcarnie PTAL

**Comment by wesm** [comment]
Just rebased this

**Comment by wesm** [comment]
@stuartcarnie can you review this?

**Comment by stuartcarnie** [comment]
@wesm / @sbinet I plan to look at these PRs as soon as I finish up some other items at the top of my list

**Review by stuartcarnie — APPROVED** [review]
All looks great, @sbinet – thank you for all your contributions!

@wesm LGTM 👍

**Pull request closed without merging**
