### PR TITLE
ARROW-11346: [C++][Compute] Implement quantile kernel benchmark

### PR DESCRIPTION
**Pull request by cyb70289**

### CODE REVIEW

**Comment by cyb70289** [comment]
On Xeon(R) Gold 5218, compiled with clang-9.
```
---------------------------------------------------------------------------------------------
Benchmark                                   Time             CPU   Iterations UserCounters...
---------------------------------------------------------------------------------------------
QuantileKernelInt32/1048576/10000        2317 us         2317 us          303 bytes_per_second=431.623M/s null_percent=0.01 size=1048.58k
QuantileKernelInt32/1048576/100          1445 us         1445 us          484 bytes_per_second=691.86M/s null_percent=1 size=1048.58k
QuantileKernelInt32/1048576/10           1930 us         1930 us          363 bytes_per_second=518.236M/s null_percent=10 size=1048.58k
QuantileKernelInt32/1048576/2            1814 us         1814 us          386 bytes_per_second=551.129M/s null_percent=50 size=1048.58k
QuantileKernelInt32/1048576/1           0.640 us        0.640 us      1094700 bytes_per_second=1.49004T/s null_percent=100 size=1048.58k
QuantileKernelInt32/1048576/0            2155 us         2155 us          325 bytes_per_second=463.971M/s null_percent=0 size=1048.58k
QuantileKernelInt64/1048576/10000         936 us          936 us          749 bytes_per_second=1068.56M/s null_percent=0.01 size=1048.58k
QuantileKernelInt64/1048576/100          1180 us         1180 us          592 bytes_per_second=847.643M/s null_percent=1 size=1048.58k
QuantileKernelInt64/1048576/10            896 us          896 us          786 bytes_per_second=1116.39M/s null_percent=10 size=1048.58k
QuantileKernelInt64/1048576/2             813 us          813 us          862 bytes_per_second=1.20162G/s null_percent=50 size=1048.58k
QuantileKernelInt64/1048576/1           0.642 us        0.642 us      1091460 bytes_per_second=1.48548T/s null_percent=100 size=1048.58k
QuantileKernelInt64/1048576/0             937 us          937 us          748 bytes_per_second=1067.5M/s null_percent=0 size=1048.58k
QuantileKernelDouble/1048576/10000       1217 us         1217 us          575 bytes_per_second=821.591M/s null_percent=0.01 size=1048.58k
QuantileKernelDouble/1048576/100         1340 us         1340 us          522 bytes_per_second=746.154M/s null_percent=1 size=1048.58k
QuantileKernelDouble/1048576/10           972 us          972 us          721 bytes_per_second=1029.08M/s null_percent=10 size=1048.58k
QuantileKernelDouble/1048576/2            937 us          937 us          747 bytes_per_second=1067.54M/s null_percent=50 size=1048.58k
QuantileKernelDouble/1048576/1          0.654 us        0.654 us      1071271 bytes_per_second=1.4589T/s null_percent=100 size=1048.58k
QuantileKernelDouble/1048576/0           1330 us         1330 us          526 bytes_per_second=751.827M/s null_percent=0 size=1048.58k
```

**Comment by cyb70289** [comment]
travis ci error not related

**Comment by cyb70289** [comment]
mingw32 ci failure is not relevant

**Review by pitrou — APPROVED** [review]
+1, thank you @cyb70289

**Pull request closed without merging**
