### PR TITLE
ARROW-9888: [Rust][DataFusion] Allow ExecutionContext to be shared between threads (again)

### PR DESCRIPTION
**Pull request by alamb**
The idea here is to share the ExecutionContext between threads (which was previously added in https://issues.apache.org/jira/browse/ARROW-9425 / https://github.com/apache/arrow/pull/7723 but has since regressed. 

This PR fixes the issue and adds a test to ensure the behavior does not revert again

(Note this is based on https://github.com/apache/arrow/pull/8079 -- I will convert it to a real PR once that is merged)

### CODE REVIEW

**Comment by alamb** [comment]
fyi @jorgecarleitao

**Review by jorgecarleitao — APPROVED** [review]
LGTM.

Thanks a lot for this. You have been unstoppable today! 🚄

**Comment by alamb** [comment]
This week I think I get to spend most of my work time on DataFusion -- I need to make it count 🔨 !

**Review by andygrove — APPROVED** [review]
LGTM

**Pull request closed without merging**
