### PR TITLE
ARROW-3358: [Gandiva][C++] Deprecate Gandiva Status.

### PR DESCRIPTION
**Pull request by praveenbingo**
Removing all references to gandiva status and using arrow
status instead.

### CODE REVIEW

**Comment by wesm** [comment]
Thank you. @kou or @shiro615 can you update the GLib bindings to follow this change? we can cherry-pick into this PR

**Review by wesm — APPROVED** [review]
+1 pending passing build and GLib fixes

**Comment by praveenbingo** [comment]
> Thank you. @kou or @shiro615 can you update the GLib bindings to follow this change? we can cherry-pick into this PR

Let me take a look, if its simple i will fix it as part of this PR..

**Comment by wesm** [comment]
Hm, weird Plasma error in the tests, probably transient:

```
=================================== FAILURES ===================================
_______________________________ test_plasma_list _______________________________

    @pytest.mark.plasma
    def test_plasma_list():
        import pyarrow.plasma as plasma
    
        with plasma.start_plasma_store(
                plasma_store_memory=DEFAULT_PLASMA_STORE_MEMORY) \
                as (plasma_store_name, p):
            plasma_client = plasma.connect(plasma_store_name, "", 0)
    
            # Test sizes
            u, _, _ = create_object(plasma_client, 11, metadata_size=7, seal=False)
            l1 = plasma_client.list()
            assert l1[u]["data_size"] == 11
            assert l1[u]["metadata_size"] == 7
    
            # Test ref_count
            v = plasma_client.put(np.zeros(3))
            l2 = plasma_client.list()
            # Ref count has already been released
            assert l2[v]["ref_count"] == 0
            a = plasma_client.get(v)
            l3 = plasma_client.list()
            assert l3[v]["ref_count"] == 1
            del a
    
            # Test state
            w, _, _ = create_object(plasma_client, 3, metadata_size=0, seal=False)
            l4 = plasma_client.list()
            assert l4[w]["state"] == "created"
            plasma_client.seal(w)
            l5 = plasma_client.list()
            assert l5[w]["state"] == "sealed"
    
            # Test timestamps
            t1 = time.time()
            x, _, _ = create_object(plasma_client, 3, metadata_size=0, seal=False)
            t2 = time.time()
            l6 = plasma_client.list()
>           assert math.floor(t1) <= l6[x]["create_time"] <= math.ceil(t2)
E           assert 1540842334 <= 1540842333
E            +  where 1540842334 = <built-in function floor>(1540842334.001501)
E            +    where <built-in function floor> = math.floor
```

**Comment by wesm** [comment]
I missed this in my review:

```
  // Gandiva range of errors
  CodeGenError = 40,
  ArrowError = 41,
  ExpressionValidationError = 42,
  ExecutionError = 43
```

Out of these errors, how many do you actually need?

**Comment by praveenbingo** [comment]
> I missed this in my review:
> 
> ```
>   // Gandiva range of errors
>   CodeGenError = 40,
>   ArrowError = 41,
>   ExpressionValidationError = 42,
>   ExecutionError = 43
> ```
> 
> Out of these errors, how many do you actually need?

Currently we use all four of them.

**Comment by shiro615** [comment]
@praveenbingo Thank you for updating the GLib bindings!

**Comment by wesm** [comment]
@praveenbingo I didn't see usage of ArrowError

https://github.com/apache/arrow/search?l=C%2B%2B&q=ArrowError

I was thinking you would want to use the Status valid that's returned by the failing part of the rest of the library.

For `ExpressionValidationError`, you could return `Status::Invalid` instead

**Comment by kou** [comment]
I want to rename `GARROW_ERROR_CODEGEN` to `GARROW_ERROR_CODE_GEN` or `GARROW_ERROR_CODE_GENERATION`.
I'll work on it later.

**Comment by wesm** [comment]
It depends on what your objective with the error codes is, i.e. if a new error code has a specific use in an application. Each new error code introduces complexity into bindings

**Pull request closed without merging**
