### PR TITLE
ARROW-10155: [Rust] [DataFusion] Improved lib.rs docs

### PR DESCRIPTION
**Pull request by jorgecarleitao**
Extended lib documentation, migrating some of it from the README.

### CODE REVIEW

**Comment by jorgecarleitao** [comment]
FYI: in vs code, I have placed

```json
[
    {
        "command": "rust-analyzer.onEnter",
        "key": "enter",
        "when": "editorTextFocus && !suggestWidgetVisible && editorLangId == rust && !vim.active || vim.mode == 'Insert' && editorTextFocus && !suggestWidgetVisible && editorLangId == rust"
    }
]
```

in `keybindings.json`, which auto inserts `//!` when enter is pressed inside a `//!`, which is useful to write documentation.

**Comment by jorgecarleitao** [comment]
@andygrove , I am merging this PR to see whether I can.

**Comment by jorgecarleitao** [comment]
nvmd, I still can't:

> ERROR: Permission to apache/arrow.git denied to jorgecarleitao.

**Review by andygrove — APPROVED** [review]

**Comment by andygrove** [comment]
> nvmd, I still can't:
> 
> > ERROR: Permission to apache/arrow.git denied to jorgecarleitao.

This is when you are running `./dev/merge_pr.py` from your own cloned repo?

**Comment by jorgecarleitao** [comment]
@andygrove, yes.

```bash
(venv) Jorges-MacBook-Pro-2:arrow jorgecarleitao$ dev/merge_arrow_pr.py
ARROW_HOME = /Users/jorgecarleitao/projects/arrow/dev
PROJECT_NAME = arrow
Which pull request would you like to merge? (e.g. 34): 8323
Env APACHE_JIRA_USERNAME not set, please enter your JIRA username:jorgecarleitao
Env APACHE_JIRA_PASSWORD not set, please enter your JIRA password:

=== Pull Request #8323 ===
title   ARROW-10155: [Rust] [DataFusion] Improved lib.rs docs
source  jorgecarleitao/readme
target  master
url     https://api.github.com/repos/apache/arrow/pulls/8323
=== JIRA ARROW-10155 ===
Summary         [Rust] [DataFusion] Add documentation to lib.rs
Assignee        Jorge Leitão
Components      Rust - DataFusion
Status          Open
URL             https://issues.apache.org/jira/browse/ARROW-10155

Proceed with merging pull request #8323? (y/n): y
From github.com:apache/arrow
 * [new ref]             refs/pull/8323/head -> PR_TOOL_MERGE_PR_8323
From github.com:apache/arrow
 * [new branch]          master     -> PR_TOOL_MERGE_PR_8323_MASTER
   334e33ef4..b73731bac  master     -> apache/master
Switched to branch 'PR_TOOL_MERGE_PR_8323_MASTER'
Author 1: Jorge C. Leitao <jorgecarleitao@gmail.com>
```

```bash
Merge complete (local ref PR_TOOL_MERGE_PR_8323_MASTER). Push to apache? (y/n): y
ERROR: Permission to apache/arrow.git denied to jorgecarleitao.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Command failed: ['git', 'push', 'apache', 'PR_TOOL_MERGE_PR_8323_MASTER:master']
With output:
--------------
b''
--------------
Restoring head pointer to 4cb2d528
Note: checking out '4cb2d528'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 4cb2d5289 Improved DataFusion lib.rs docs and added examples to Cargo.
Deleting local branch PR_TOOL_MERGE_PR_8323
Deleting local branch PR_TOOL_MERGE_PR_8323_MASTER
Restoring head pointer to 4cb2d528
HEAD is now at 4cb2d5289 Improved DataFusion lib.rs docs and added examples to Cargo.
Traceback (most recent call last):
  File "dev/merge_arrow_pr.py", line 436, in merge
    run_cmd(push_cmd)
  File "dev/merge_arrow_pr.py", line 91, in run_cmd
    raise e
  File "dev/merge_arrow_pr.py", line 83, in run_cmd
    output = subprocess.check_output(cmd)
  File "/usr/local/Cellar/python@3.7/3.7.9/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/usr/local/Cellar/python@3.7/3.7.9/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['git', 'push', 'apache', 'PR_TOOL_MERGE_PR_8323_MASTER:master']' returned non-zero exit status 128.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "dev/merge_arrow_pr.py", line 597, in <module>
    cli()
  File "dev/merge_arrow_pr.py", line 582, in cli
    pr.merge()
  File "dev/merge_arrow_pr.py", line 439, in merge
    self.cmd.fail("Exception while pushing: %s" % e)
  File "dev/merge_arrow_pr.py", line 270, in fail
    raise Exception(msg)
Exception: Exception while pushing: Command '['git', 'push', 'apache', 'PR_TOOL_MERGE_PR_8323_MASTER:master']' returned non-zero exit status 128.
```

I think that I may not have push permissions on the repo yet.

**Comment by andygrove** [comment]
Ok, probably best to ask for help on the mailing list.

**Pull request closed without merging**
