### PR TITLE
ARROW-4820: [Python] hadoop class path derived not correct

### PR DESCRIPTION
**Pull request by chenfj068**
> hdfs.py method _derive_hadoop_classpath add hadoop config dir to hadoop classpath

Fix for  https://issues.apache.org/jira/browse/ARROW-4820

### CODE REVIEW

**Comment by wesm** [comment]
This looks OK to me. The HDFS integration tests need to be run

**Comment by kszucs** [comment]
Working on it. I'll probably turn off libhdfs3, because it's still problematic.

**Comment by kszucs** [comment]
test: [kszucs/crossbow/build-449](https://github.com/kszucs/crossbow/branches/all?utf8=%E2%9C%93&query=build-449)

**Review by kszucs — APPROVED** [review]
Integration test is green. Thanks @chenfj068!

**Pull request closed without merging**
