### PR TITLE
GH-36604: [Java][CI] Set up Arrow Java support for JDK8 and JDK11+ maven packaging

### LINKED ISSUE #36604: [Java][CI] Set up Arrow Java support for JDK8 and JDK11+
### Describe the enhancement requested

Currently, Arrow Java is using JDK11 to compile the code, and it offers JDK8 support with [source/target 8](https://github.com/apache/arrow/blob/ea4f03ac166e3961b59f29f60dcd160fbed29894/java/pom.xml#L203-L207).

We will eventually need to compile with JDK11 and use source/target 11. The main challenge will be excluding clients that need to continue using JDK8.

The following are the options for moving to JDK11:

1. In order to continue offering support for JDK 8, cross-compile with JDK 11+ and package with release=8:
If we compile with --release=8, we will have trouble accessing sun.misc.Unsafe, which is not as exposed/public/documented (https://openjdk.org/jeps/247).

2. Discontinue support for JDK8.

3. **Set up Arrow Java flavors for JDK8 and JDK11+.**

-------

This enhancement consider the changes needed to implement the 3rd option mention above: **Set up Arrow Java flavors for JDK8 and JDK11+.**

1. New Arrow Java library should be offering support for JDK8 and JDK11+ throughout different maven artifacts (adding classifier support).

```
arrow-memory-core-15.0.0-SNAPSHOT.pom
arrow-memory-core-15.0.0-SNAPSHOT-tests.jar
arrow-memory-core-15.0.0-SNAPSHOT.jar
arrow-memory-core-15.0.0-SNAPSHOT-javadoc.jar
arrow-memory-core-15.0.0-SNAPSHOT-sources.jar
arrow-memory-core-15.0.0-SNAPSHOT-cyclonedx.json
arrow-memory-core-15.0.0-SNAPSHOT-cyclonedx.xml
arrow-memory-core-15.0.0-SNAPSHOT-jdk8tests.jar
arrow-memory-core-15.0.0-SNAPSHOT-jdk8.jar
```

2. New Arrow Java library should be offering default support for JDK11 (major version: 55) 

Java libraries by default will offer JDK11 support (major version: 55):
```
  <dependency>
    <groupId>org.apache.arrow</groupId>
    <artifactId>arrow-memory-core</artifactId>
    <version>15.0.0-SNAPSHOT</version>
  </dependency>
```
3. If the user need to use JDK8 as a mandatory, then they need to change from-to:

From:
```
  <dependency>
    <groupId>org.apache.arrow</groupId>
    <artifactId>arrow-memory-core</artifactId>
    <version>15.0.0-SNAPSHOT</version>
  </dependency>
```
To JDK8 (major version: 52):
```
<dependency>
  <groupId>org.apache.arrow</groupId>
  <artifactId>arrow-memory-core</artifactId>
  <version>15.0.0-SNAPSHOT</version>
  <classifier>jdk8</classifier>
</dependency>
```

### Component(s)

Continuous Integration, Developer Tools, Documentation, Java

### PR DESCRIPTION
**Pull request by davisusanibar**
### Rationale for this change

To close https://github.com/apache/arrow/issues/36604

### What changes are included in this PR?

Set up Arrow Java support for JDK8 and JDK11+

### Are these changes tested?

Yes, it is testing by github actions java jars

### Are there any user-facing changes?

Yes
* Closes: #36604

### CODE REVIEW

**Comment by davisusanibar** [comment]
@github-actions crossbow submit java-jars

**Comment by davisusanibar** [comment]
@github-actions crossbow submit java-jars

**Comment by lidavidm** [comment]
I thought the point is that we *wouldn't* support Java 8 after some date? Why are we building separate JARs for Java 8 when there's no point anyways? (We can't use any new language features, so we might as well stick with the current toolchain, if we are going to support Java 8.)

**Comment by davisusanibar** [comment]
> I thought the point is that we _wouldn't_ support Java 8 after some date? Why are we building separate JARs for Java 8 when there's no point anyways? (We can't use any new language features, so we might as well stick with the current toolchain, if we are going to support Java 8.)

Hi @lidavidm, this draft PR shows how we can build Arrow Java using JDK8 & JDK11 and offer both versions independently. We will need to mark one version arrow in the future that will be the last to support JDK8, so we propose to tag them (ie: classifier jdk8).  

Alternatively, we could defer this discussion until we have an agreement to deprecate JDK8 and only support JDK11.  

Let me maintain this PR as a draft to I could continue when we have an agreement as a community to deprecate JDK8.

**Comment by lidavidm** [comment]
What is the point of building a separate JDK11 version from the same source code? We can't use Java 11 features anyways, so we may as well continue targeting Java 8.

**Comment by davisusanibar** [comment]
> 



> What is the point of building a separate JDK11 version from the same source code? We can't use Java 11 features anyways, so we may as well continue targeting Java 8.

The significance of this only applies if we deprecate JDK8, in which case source/target should start with Java 11.

**Comment by lidavidm** [comment]
You can't target Java 8 when using Java 9+ features, so this is still pointless.

**Pull request closed without merging**
