### PR TITLE
ARROW-2989: [C++/Python] Remove API deprecations in 0.10

### PR DESCRIPTION
**Pull request by wesm**
I didn't remove the `nthreads` deprecations in Python yet. @pitrou do you support removing them in 0.11?

### CODE REVIEW

**Comment by pitrou** [comment]
Removing the `nthreads` arguments is fine with me.

**Comment by wesm** [comment]
Done. I noticed that the default for `use_threads` is `False`. I think that a `True` default would result in a better average experience for library users. What do you think?

**Comment by pitrou** [comment]
I think there are arguments both ways. The advantage of leaving it to False is to force people to think about it, IMHO. If it's True by default and someone uses their own parallelism, they may get suboptimal results without knowing why (because of oversubscription). Perhaps @mrocklin wants to share thoughts about it (topic: making some operations parallel by default in library code).

**Comment by wesm** [comment]
Agree that there are arguments both ways. I would argue that if users are using parallelism separately that they should also be aware of Arrow's default parallelism and set the thread pool parameters accordingly

**Review by pitrou — COMMENTED** [review]
LGTM. Just one question: do some tests or benchmarks need modifying to exercise the single-thread case now that using threads is the default?

**Comment by mrocklin** [comment]
Other libraries, like BLAS, enable parallelism by default.  As someone who parallelizes around these libraries I'm pretty comfortable setting environment variables on my system to control it.  If Arrow wanted to look for `OMP_NUM_THREADS` and follow that I suspect that that would capture the intent of many users.

**Comment by wesm** [comment]
@pitrou they probably do. Let me have a look about that

**Comment by xhochy** [comment]
+1 for `OMP_NUM_THREADS` that's also what we set in our environments mostly to control parallelism of many libraries.

**Comment by wesm** [comment]
`OMP_NUM_THREADS` is already the default. I'll have a look at tests where we may need to disable threading

**Comment by wesm** [comment]
The tests in `test_convert_pandas.py` pass `use_threads=False` in most cases, and there are separate threading tests. I'm flipping the argument to `True` and changing the threaded test to be non-threaded

**Comment by wesm** [comment]
+1 from me. Feel free to merge once the build is green

**Pull request closed without merging**
