### PR TITLE
GH-41702: [C++][Parquet] Thrift: generate template method to accelerate reading thrift

### PR DESCRIPTION
**Pull request by mapleFU**
### Rationale for this change

By default, the Thrift serializer and deserializer call many virtual functions. However, the Thrift C++ compiler has an option to generate template methods that does away with the cost of calling virtual functions. It seems to make the metadata read/write benchmarks around 10% faster.

### What changes are included in this PR?

1. `cpp/build-support/update-thrift.sh`: enable `templates` option to Thirft C++ compilerargument
2. `cpp/src/parquet/thrift_internal.h`: use generated code
3. `cpp/src/generated`: update generated files.

### Are these changes tested?

Covered by existing tests.

### Are there any user-facing changes?

No.

* GitHub Issue: #41702

### CODE REVIEW

**Comment by mapleFU** [comment]
@emkornfield @pitrou I've update a patching here. This generated call less virtual functions during deserializing. Would you mind take a look?

I'm not so familiar with thrift compiler, maybe more useful tools can help deserializing

**Comment by pitrou** [comment]
@mapleFU I didn't know this was possible. This looks neat in the principle. Did you try to run some benchmark?

**Comment by mapleFU** [comment]
Run in page index: https://github.com/apache/arrow/issues/41702#issuecomment-2116873657

For dense footer it's more useful since readVirt is called for more times

**Comment by wgtmac** [comment]
I remember there was about 3% speedup reading a sample parquet file.

**Comment by pitrou** [comment]
Perhaps you can try with the additional benchmarks in https://github.com/apache/arrow/pull/41761

**Comment by mapleFU** [comment]
On my M1 Pro with Release(O2):

After:

```
Run on (10 X 24.0711 MHz CPU s)
CPU Caches:
  L1 Data 64 KiB
  L1 Instruction 128 KiB
  L2 Unified 4096 KiB (x10)
Load Average: 7.98, 10.79, 8.83
-------------------------------------------------------------------------------------------------------------
Benchmark                                                   Time             CPU   Iterations UserCounters...
-------------------------------------------------------------------------------------------------------------
WriteMetadata/num_columns:1/num_row_groups:1            10248 ns        10198 ns        65596 file_size=459 items_per_second=98.0618k/s
WriteMetadata/num_columns:1/num_row_groups:100         708873 ns       701642 ns         1003 file_size=37.383k items_per_second=1.42523k/s
WriteMetadata/num_columns:1/num_row_groups:1000       7027939 ns      7022677 ns           99 file_size=374.885k items_per_second=142.396/s
WriteMetadata/num_columns:10/num_row_groups:1           78750 ns        78709 ns         8900 file_size=3.762k items_per_second=12.705k/s
WriteMetadata/num_columns:10/num_row_groups:100       6751510 ns      6644838 ns          105 file_size=358.835k items_per_second=150.493/s
WriteMetadata/num_columns:10/num_row_groups:1000     67659713 ns     67142800 ns           10 file_size=3.614M items_per_second=14.8936/s
WriteMetadata/num_columns:100/num_row_groups:1         787280 ns       771871 ns          910 file_size=37.352k items_per_second=1.29555k/s
WriteMetadata/num_columns:100/num_row_groups:100     66632500 ns     66540000 ns           10 file_size=3.61693M items_per_second=15.0286/s
WriteMetadata/num_columns:100/num_row_groups:1000   703455917 ns    699385000 ns            1 file_size=36.2887M items_per_second=1.42983/s
WriteMetadata/num_columns:1000/num_row_groups:1       8089713 ns      8087153 ns           85 file_size=376.655k items_per_second=123.653/s
WriteMetadata/num_columns:1000/num_row_groups:100   705972459 ns    702311000 ns            1 file_size=36.4815M items_per_second=1.42387/s
WriteMetadata/num_columns:10000/num_row_groups:1     82793505 ns     82773750 ns            8 file_size=3.82213M items_per_second=12.0811/s
WriteMetadata/num_columns:10000/num_row_groups:100 7789295000 ns   7492551000 ns            1 file_size=369.089M items_per_second=0.133466/s
ReadMetadata/num_columns:1/num_row_groups:1              3022 ns         3021 ns       229889 file_size=459 items_per_second=330.982k/s
ReadMetadata/num_columns:1/num_row_groups:100           59165 ns        59139 ns        11742 file_size=37.383k items_per_second=16.9092k/s
ReadMetadata/num_columns:1/num_row_groups:1000         587111 ns       586972 ns         1189 file_size=374.885k items_per_second=1.70366k/s
ReadMetadata/num_columns:10/num_row_groups:1            13977 ns        13973 ns        50402 file_size=3.762k items_per_second=71.569k/s
ReadMetadata/num_columns:10/num_row_groups:100         475674 ns       475562 ns         1469 file_size=358.835k items_per_second=2.10278k/s
ReadMetadata/num_columns:10/num_row_groups:1000       4743075 ns      4742237 ns          139 file_size=3.614M items_per_second=210.871/s
ReadMetadata/num_columns:100/num_row_groups:1          119355 ns       119308 ns         5747 file_size=37.352k items_per_second=8.38169k/s
ReadMetadata/num_columns:100/num_row_groups:100       5379931 ns      5378835 ns          133 file_size=3.61693M items_per_second=185.914/s
ReadMetadata/num_columns:100/num_row_groups:1000     58173311 ns     58151000 ns           13 file_size=36.2887M items_per_second=17.1966/s
ReadMetadata/num_columns:1000/num_row_groups:1        1285306 ns      1284195 ns          514 file_size=376.655k items_per_second=778.698/s
ReadMetadata/num_columns:1000/num_row_groups:100     59154014 ns     59110667 ns           12 file_size=36.4815M items_per_second=16.9174/s
ReadMetadata/num_columns:10000/num_row_groups:1      15298734 ns     15288065 ns           46 file_size=3.82213M items_per_second=65.4105/s
ReadMetadata/num_columns:10000/num_row_groups:100   597222875 ns    594531000 ns            1 file_size=369.089M items_per_second=1.682/s
```

Before:

```
WriteMetadata/num_columns:1/num_row_groups:1            13997 ns        10952 ns        64411 file_size=459 items_per_second=91.3074k/s
WriteMetadata/num_columns:1/num_row_groups:100        1161928 ns       781421 ns          915 file_size=37.383k items_per_second=1.27972k/s
WriteMetadata/num_columns:1/num_row_groups:1000       9028193 ns      7580868 ns           91 file_size=374.885k items_per_second=131.911/s
WriteMetadata/num_columns:10/num_row_groups:1           87804 ns        81408 ns         8680 file_size=3.762k items_per_second=12.2838k/s
WriteMetadata/num_columns:10/num_row_groups:100       7922727 ns      7032396 ns           96 file_size=358.835k items_per_second=142.199/s
WriteMetadata/num_columns:10/num_row_groups:1000     83557727 ns     72335889 ns            9 file_size=3.614M items_per_second=13.8244/s
WriteMetadata/num_columns:100/num_row_groups:1        1046771 ns       866386 ns          813 file_size=37.352k items_per_second=1.15422k/s
WriteMetadata/num_columns:100/num_row_groups:100     97720995 ns     74290111 ns            9 file_size=3.61693M items_per_second=13.4607/s
WriteMetadata/num_columns:100/num_row_groups:1000  1042585917 ns    773579000 ns            1 file_size=36.2887M items_per_second=1.29269/s
WriteMetadata/num_columns:1000/num_row_groups:1       9320268 ns      8396910 ns           78 file_size=376.655k items_per_second=119.091/s
WriteMetadata/num_columns:1000/num_row_groups:100   789198500 ns    726929000 ns            1 file_size=36.4815M items_per_second=1.37565/s
WriteMetadata/num_columns:10000/num_row_groups:1    105553526 ns     89228125 ns            8 file_size=3.82213M items_per_second=11.2072/s
WriteMetadata/num_columns:10000/num_row_groups:100 9705208125 ns   7941607000 ns            1 file_size=369.089M items_per_second=0.125919/s
ReadMetadata/num_columns:1/num_row_groups:1              3341 ns         3262 ns       215501 file_size=459 items_per_second=306.531k/s
ReadMetadata/num_columns:1/num_row_groups:100           70801 ns        67469 ns        10226 file_size=37.383k items_per_second=14.8215k/s
ReadMetadata/num_columns:1/num_row_groups:1000         697046 ns       661042 ns         1033 file_size=374.885k items_per_second=1.51276k/s
ReadMetadata/num_columns:10/num_row_groups:1            19616 ns        15182 ns        46741 file_size=3.762k items_per_second=65.866k/s
ReadMetadata/num_columns:10/num_row_groups:100         631976 ns       538377 ns         1240 file_size=358.835k items_per_second=1.85743k/s
ReadMetadata/num_columns:10/num_row_groups:1000       5701558 ns      5375484 ns          122 file_size=3.614M items_per_second=186.03/s
ReadMetadata/num_columns:100/num_row_groups:1          137789 ns       128750 ns         5466 file_size=37.352k items_per_second=7.76702k/s
ReadMetadata/num_columns:100/num_row_groups:100       6475114 ns      6090483 ns          118 file_size=3.61693M items_per_second=164.191/s
ReadMetadata/num_columns:100/num_row_groups:1000     64411345 ns     62630000 ns           11 file_size=36.2887M items_per_second=15.9668/s
ReadMetadata/num_columns:1000/num_row_groups:1        1473490 ns      1402757 ns          453 file_size=376.655k items_per_second=712.882/s
ReadMetadata/num_columns:1000/num_row_groups:100     66037220 ns     64025909 ns           11 file_size=36.4815M items_per_second=15.6187/s
ReadMetadata/num_columns:10000/num_row_groups:1      18425749 ns     16564045 ns           44 file_size=3.82213M items_per_second=60.3717/s
ReadMetadata/num_columns:10000/num_row_groups:100   650862958 ns    636789000 ns            1 file_size=369.089M items_per_second=1.57038/s
```

**Comment by mapleFU** [comment]
On my AMD 3800X:

Before:

```
WriteMetadata/num_columns:1/num_row_groups:1            14816 ns        14816 ns        48309 file_size=459 items_per_second=67.4938k/s
WriteMetadata/num_columns:1/num_row_groups:100        1087488 ns      1087494 ns          699 file_size=37.383k items_per_second=919.545/s
WriteMetadata/num_columns:1/num_row_groups:1000       9939072 ns      9937325 ns           59 file_size=374.885k items_per_second=100.631/s
WriteMetadata/num_columns:10/num_row_groups:1          118413 ns       118412 ns         5646 file_size=3.762k items_per_second=8.44508k/s
WriteMetadata/num_columns:10/num_row_groups:100       9458300 ns      9458325 ns           69 file_size=358.835k items_per_second=105.727/s
WriteMetadata/num_columns:10/num_row_groups:1000     99919203 ns     99917686 ns            7 file_size=3.614M items_per_second=10.0082/s
WriteMetadata/num_columns:100/num_row_groups:1        1145205 ns      1145207 ns          624 file_size=37.352k items_per_second=873.204/s
WriteMetadata/num_columns:100/num_row_groups:100    101083527 ns    101079183 ns            6 file_size=3.61693M items_per_second=9.89323/s
WriteMetadata/num_columns:100/num_row_groups:1000  1027574292 ns   1027570500 ns            1 file_size=36.2887M items_per_second=0.973169/s
WriteMetadata/num_columns:1000/num_row_groups:1      10933400 ns     10933348 ns           66 file_size=376.655k items_per_second=91.4633/s
WriteMetadata/num_columns:1000/num_row_groups:100   997383234 ns    989469900 ns            1 file_size=36.4815M items_per_second=1.01064/s
WriteMetadata/num_columns:10000/num_row_groups:1    113278188 ns    113278583 ns            6 file_size=3.82213M items_per_second=8.82779/s
WriteMetadata/num_columns:10000/num_row_groups:100 1.0258e+10 ns   1.0257e+10 ns            1 file_size=369.089M items_per_second=0.0974916/s
ReadMetadata/num_columns:1/num_row_groups:1              4286 ns         4286 ns       156757 file_size=459 items_per_second=233.3k/s
ReadMetadata/num_columns:1/num_row_groups:100           92293 ns        92293 ns         7323 file_size=37.383k items_per_second=10.8351k/s
ReadMetadata/num_columns:1/num_row_groups:1000         874417 ns       874410 ns          838 file_size=374.885k items_per_second=1.14363k/s
ReadMetadata/num_columns:10/num_row_groups:1            20860 ns        20860 ns        33415 file_size=3.762k items_per_second=47.9385k/s
ReadMetadata/num_columns:10/num_row_groups:100         730042 ns       730043 ns          997 file_size=358.835k items_per_second=1.36978k/s
ReadMetadata/num_columns:10/num_row_groups:1000       7307342 ns      7307324 ns           83 file_size=3.614M items_per_second=136.849/s
ReadMetadata/num_columns:100/num_row_groups:1          186400 ns       186401 ns         3787 file_size=37.352k items_per_second=5.36479k/s
ReadMetadata/num_columns:100/num_row_groups:100       7121296 ns      7121319 ns           85 file_size=3.61693M items_per_second=140.423/s
ReadMetadata/num_columns:100/num_row_groups:1000     81473986 ns     81458278 ns            9 file_size=36.2887M items_per_second=12.2762/s
ReadMetadata/num_columns:1000/num_row_groups:1        1814784 ns      1814759 ns          400 file_size=376.655k items_per_second=551.037/s
ReadMetadata/num_columns:1000/num_row_groups:100     79376073 ns     79376022 ns            9 file_size=36.4815M items_per_second=12.5983/s
ReadMetadata/num_columns:10000/num_row_groups:1      20298949 ns     20236894 ns           36 file_size=3.82213M items_per_second=49.4147/s
ReadMetadata/num_columns:10000/num_row_groups:100   797135144 ns    797041100 ns            1 file_size=369.089M items_per_second=1.25464/s
```

After:
```
WriteMetadata/num_columns:1/num_row_groups:1            14042 ns        14026 ns        48265 file_size=459 items_per_second=71.2951k/s
WriteMetadata/num_columns:1/num_row_groups:100         982543 ns       982545 ns          693 file_size=37.383k items_per_second=1.01776k/s
WriteMetadata/num_columns:1/num_row_groups:1000       9236559 ns      9234951 ns           75 file_size=374.885k items_per_second=108.284/s
WriteMetadata/num_columns:10/num_row_groups:1          115867 ns       115865 ns         6050 file_size=3.762k items_per_second=8.63075k/s
WriteMetadata/num_columns:10/num_row_groups:100       9106303 ns      9106322 ns           77 file_size=358.835k items_per_second=109.814/s
WriteMetadata/num_columns:10/num_row_groups:1000     95039480 ns     95039886 ns            7 file_size=3.614M items_per_second=10.5219/s
WriteMetadata/num_columns:100/num_row_groups:1        1066471 ns      1066474 ns          648 file_size=37.352k items_per_second=937.67/s
WriteMetadata/num_columns:100/num_row_groups:100     92350381 ns     92350900 ns            8 file_size=3.61693M items_per_second=10.8283/s
WriteMetadata/num_columns:100/num_row_groups:1000   972198408 ns    971689600 ns            1 file_size=36.2887M items_per_second=1.02914/s
WriteMetadata/num_columns:1000/num_row_groups:1      10303438 ns     10302799 ns           68 file_size=376.655k items_per_second=97.061/s
WriteMetadata/num_columns:1000/num_row_groups:100   926151272 ns    926026200 ns            1 file_size=36.4815M items_per_second=1.07988/s
WriteMetadata/num_columns:10000/num_row_groups:1    109520337 ns    109283500 ns            6 file_size=3.82213M items_per_second=9.15051/s
WriteMetadata/num_columns:10000/num_row_groups:100 9607536338 ns   9603598900 ns            1 file_size=369.089M items_per_second=0.104128/s
ReadMetadata/num_columns:1/num_row_groups:1              3776 ns         3737 ns       190309 file_size=459 items_per_second=267.588k/s
ReadMetadata/num_columns:1/num_row_groups:100           76296 ns        76114 ns         9217 file_size=37.383k items_per_second=13.1382k/s
ReadMetadata/num_columns:1/num_row_groups:1000         706469 ns       706463 ns          993 file_size=374.885k items_per_second=1.4155k/s
ReadMetadata/num_columns:10/num_row_groups:1            18738 ns        18738 ns        35672 file_size=3.762k items_per_second=53.3679k/s
ReadMetadata/num_columns:10/num_row_groups:100         590179 ns       590180 ns         1202 file_size=358.835k items_per_second=1.6944k/s
ReadMetadata/num_columns:10/num_row_groups:1000       5821858 ns      5821727 ns          123 file_size=3.614M items_per_second=171.77/s
ReadMetadata/num_columns:100/num_row_groups:1          168284 ns       168284 ns         4074 file_size=37.352k items_per_second=5.94234k/s
ReadMetadata/num_columns:100/num_row_groups:100       5752814 ns      5752800 ns          118 file_size=3.61693M items_per_second=173.828/s
ReadMetadata/num_columns:100/num_row_groups:1000     65674677 ns     65672427 ns           11 file_size=36.2887M items_per_second=15.2271/s
ReadMetadata/num_columns:1000/num_row_groups:1        1574680 ns      1574646 ns          444 file_size=376.655k items_per_second=635.063/s
ReadMetadata/num_columns:1000/num_row_groups:100     65989678 ns     65988873 ns           11 file_size=36.4815M items_per_second=15.1541/s
ReadMetadata/num_columns:10000/num_row_groups:1      16967274 ns     16966876 ns           41 file_size=3.82213M items_per_second=58.9384/s
ReadMetadata/num_columns:10000/num_row_groups:100   652885946 ns    652766800 ns            1 file_size=369.089M items_per_second=1.53194/s
```

**Comment by pitrou** [comment]
@github-actions crossbow submit -g cpp -g wheel

**Review by pitrou — APPROVED** [review]
+1, thank you @mapleFU

**Pull request merged**
