### PR TITLE
ARROW-7799: [R][CI] Remove flatbuffers from homebrew formulae

### PR DESCRIPTION
**Pull request by nealrichardson**

### CODE REVIEW

**Comment by nealrichardson** [comment]
@ursabot crossbow submit homebrew-cpp macos-r-autobrew

**Comment by kszucs** [comment]
[AMD64 Conda Crossbow Submit (#89942)](https://ci.ursalabs.org/#builders/98/builds/514) builder has been succeeded.

Revision: 05d35a4716788162ca8007d70ccca32d4df0c76d

Submitted crossbow builds: [ursa-labs/crossbow @ ursabot-490](https://github.com/ursa-labs/crossbow/branches/all?query=ursabot-490)

|Task|Status|
|----|------|
|homebrew-cpp|[TravisCI](https://travis-ci.org/ursa-labs/crossbow/branches)|
|macos-r-autobrew|[TravisCI](https://travis-ci.org/ursa-labs/crossbow/branches)|

**Comment by nealrichardson** [comment]
@ursabot crossbow submit macos-r-autobrew

**Comment by kszucs** [comment]
[AMD64 Conda Crossbow Submit (#89948)](https://ci.ursalabs.org/#builders/98/builds/515) builder has been succeeded.

Revision: 2df3a9e75a3425edf3417f207a48e813735836bc

Submitted crossbow builds: [ursa-labs/crossbow @ ursabot-491](https://github.com/ursa-labs/crossbow/branches/all?query=ursabot-491)

|Task|Status|
|----|------|
|macos-r-autobrew|[TravisCI](https://travis-ci.org/ursa-labs/crossbow/branches)|

**Comment by nealrichardson** [comment]
@ursabot crossbow submit macos-r-autobrew

**Comment by kszucs** [comment]
[AMD64 Conda Crossbow Submit (#89949)](https://ci.ursalabs.org/#builders/98/builds/516) builder has been succeeded.

Revision: dd2e3a38ff3466fb913e4a6beb20611fbbb6a1f2

Submitted crossbow builds: [ursa-labs/crossbow @ ursabot-492](https://github.com/ursa-labs/crossbow/branches/all?query=ursabot-492)

|Task|Status|
|----|------|
|macos-r-autobrew|[TravisCI](https://travis-ci.org/ursa-labs/crossbow/branches)|

**Pull request closed without merging**
