### PR TITLE
ARROW-3173: [Rust] dynamic_types example does not run

### PR DESCRIPTION
**Pull request by paddyhoran**

### CODE REVIEW

**Comment by paddyhoran** [comment]
Can't while at the office but will do this weekend, thanks @kszucs.

**Comment by wesm** [comment]
@kszucs since you're a committer now you should be able to rebase and force push this branch yourself

**Comment by wesm** [comment]
@sbinet is this a new issue?

**Comment by sbinet** [comment]
Sorry, where is Go failing?
The Travis CI is green :)

**Comment by paddyhoran** [comment]
That's bizarre, yesterday there were Go failures.  It was the `go get -t -v ./..` that was failing I believe, it mentioned something about a path issue with `/math`.  Sorry if that's vague I can't quite remember and I'm unfamiliar with Go.  @wesm did you see the failure also?

In any case, I guess it's all good now.

**Comment by wesm** [comment]
I restarted the build, so I guess the failure was transient

**Comment by paddyhoran** [comment]
Ah, makes sense then, thanks @wesm

**Review by kszucs — APPROVED** [review]
LGTM, Thanks!

**Pull request closed without merging**
