### PR TITLE
ARROW-2333: [Python] Fix bundling boost with default namespace

### PR DESCRIPTION
**Pull request by pitrou**

### CODE REVIEW

**Review by wesm — APPROVED** [review]
+1. This came up with `--bundle-boost` but not setting a different namespace, right?

**Comment by pitrou** [comment]
No, I think it's simply `PYARROW_BUNDLE_ARROW_CPP=1`.

**Comment by wesm** [comment]
I see. @cpcloud does this impact the packaging builds?

**Comment by wesm** [comment]
Probably goes without saying that finding out about packaging problems post-release shows that something is wrong with our development process

**Comment by cpcloud** [comment]
@wesm Not sure, I'll look.

**Review by xhochy — APPROVED** [review]
+1, LGTM

**Comment by xhochy** [comment]
We currently test the Linux packaging in CI and should be able to remove this from the `arrow-dist` repo and simply use the Dockerfiles contained in the main repository. In contrast for OSX, we only do conda-based builds and don't check if they work with the non-conda packages. This is definitely a missing component in our matrix. I was yet reluctant to add it as OSX was always very slow in Travis.

**Pull request closed without merging**
