### PR TITLE
GH-35987: [C++] Unpin brew protobuf version

### LINKED ISSUE #35987: [C++] Add support for Protobuf 23.2 on non-Windows
### Describe the enhancement requested

We can't resolve `google::protobuf::internal::ThreadSafeArena::thread_cache_` with Protobuf 23.2 on non-Windows:

```text
 /Applications/Xcode_14.2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: ../../release/libarrow.a(util_avx2.cc.o) has no symbols
ld: illegal thread local variable reference to regular symbol __ZN6google8protobuf8internal15ThreadSafeArena13thread_cache_E for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I think that https://github.com/protocolbuffers/protobuf/pull/12983 solves this but it's not released yet.

Workarounds:
1. Specify `PROTOBUF_USE_DLLS` explicitly on non-Windows too.
2. Use bundled (old) Protobuf

### Component(s)

C++

### PR DESCRIPTION
**Pull request by js8544**
Unpin brew protobuf version because of an upstream patch.
* Closes: #35987

### CODE REVIEW

**Comment by raulcd** [comment]
@github-actions crossbow submit verify-rc-source-*-macos-*

**Comment by kou** [comment]
@js8544 #36013 has been merged. Could you rebase on main?

**Comment by js8544** [comment]
@kou It seems to work, but the log of https://github.com/apache/arrow/actions/runs/5286487434/jobs/9565966246?pr=36087 is a bit weird.
```
==> Homebrew is run entirely by unpaid volunteers. Please consider donating:
  https://github.com/Homebrew/brew#donations

==> Auto-updated Homebrew!
Updated 7 taps (azure/bicep, homebrew/core, homebrew/cask, homebrew/bundle, homebrew/services, mongodb/brew and aws/tap).
==> New Formulae
ansible@7
apko
argparse
ast-grep
aws-amplify
aws/tap/eks-node-viewer
bashate
boolector
charls
clive
conda-lock
core-lightning
ddns-go
fastgron
git-credential-oauth
git-tools
grpc@1.54
grype
joshuto
jsign
judy
libabigail
libecpint
libfastjson
libint
libmediainfo
libomemo-c
libpaho-mqtt
libzen
lowdown
ls-lint
mariadb@10.11
melange
mods
nexttrace
openfga
procps@3
protobuf@21
roblox-ts
rojo
rye
shodan
slsa-verifier
spotify_player
swift-outdated
tailwindcss-language-server
tern
votca
wzprof
xbyak
yamlfmt
==> New Casks
apple-hewlett-packard-printer-drivers
chatbox
copilot
craft
devpod
dintch
engine-dj
eu
eusamanager
filemonitor
firefly-shimmer
grs-bluewallet
lasso
loupedeck
motu-m-series
mumu-x
processmonitor
rode-connect
skiff
smooze-pro
tea
yealink-meeting

You have [50](https://github.com/apache/arrow/actions/runs/5286487434/jobs/9565966246?pr=36087#step:3:51) outdated formulae and 4 outdated casks installed.

Installing aws-sdk-cpp
Installing bash
Installing boost
Using brotli
Upgrading c-ares
Installing ccache
Upgrading cmake
Installing flatbuffers
Upgrading git
Installing glog
Installing googletest
Installing grpc
Installing llvm@14
Using lz4
Installing ninja
Upgrading openssl@1.1
Installing protobuf
Upgrading python
Installing rapidjson
Using snappy
Installing thrift
Using wget
Installing xsimd
Using zstd
Homebrew Bundle complete! 24 Brewfile dependencies now installed.
```

It says `protobuf@21` in `New Formulae` but it does end up install `protobuf`, and its version is 23.2 in the build log.

**Comment by kou** [comment]
It's not a problem. It just says that `protobuf@21` was added since the GitHub Actions image was created.

**Review by kou — APPROVED** [review]
+1

**Comment by kou** [comment]
@github-actions crossbow submit verify-rc-source-*-macos-*

**Pull request merged**
