### PR TITLE
ARROW-17773: [CI][C++] Fix sccache error on Travis-CI Arm64 build

### PR DESCRIPTION
**Pull request by cyb70289**

### CODE REVIEW

**Comment by pitrou** [comment]
@assignUser Does this look ok?

**Comment by cyb70289** [comment]
Arm job is okay. But s390x CI fails as there's no `sccache` binary available for s390x.
https://app.travis-ci.com/github/apache/arrow/jobs/583544355#L1933
https://github.com/mozilla/sccache/releases/

**Comment by pitrou** [comment]
We need a way to disable sccache on some CI jobs then.

**Comment by assignUser** [comment]
Thanks for taking this on @cyb70289! I did not know that ubuntu-cpp was a multiplatform image used for arm and s390x too. Otherwise I would have added additional checks to the build script for priunting the sccache stats. We could check if one of the relevant envvars is set e.g. `SCCACHE_BUCKET`

**Comment by cyb70289** [comment]
The sccache installation is skipped on s390x.
https://app.travis-ci.com/github/apache/arrow/jobs/583665459#L1932

Unfortunately we cannot verify the full build due to another issue.
https://issues.apache.org/jira/browse/ARROW-17715

**Comment by cyb70289** [comment]
@github-actions crossbow submit -g nightly

**Comment by cyb70289** [comment]
@assignUser Is this PR okay to merge? The nightly job failures are not related.

**Comment by assignUser** [comment]
@github-actions crossbow submit r-binary-packages  test-ubuntu-*-cpp

**Review by assignUser — APPROVED** [review]
Thanks @cyb70289 !

**Pull request merged**
