### PR TITLE
ARROW-13984: [Go][Parquet] file handling for go parquet, just the readers

### PR DESCRIPTION
**Pull request by zeroshade**
This implements the file/column and page readers for Parquet files. In order to keep this smaller, I've only included what was necessary for the readers and will make a separate PR for the file and column writers after this.

### CODE REVIEW

**Comment by zeroshade** [comment]
For visibility: @emkornfield @nickpoorman @fsaintjacques @sbinet

**Comment by zeroshade** [comment]
Looking into the MacOS failure

**Comment by zeroshade** [comment]
issue was in the `extractBitsGo` function in the `bmi` package, looks like the MacOS tests are the only ones being run on a machine that isn't supporting BMI2 and thus uses the noasm implementation which caught the issue. All fixed now and ready for review.

**Comment by zeroshade** [comment]
@emkornfield any chance for a review or someone else I could tag to ask for a review here?

**Comment by emkornfield** [comment]
Sorry, will try to get to it over the weekend of next week.

**Comment by emkornfield** [comment]
@zeroshade sorry still reviewing (there is a lot here) will try to do some more tomorrow.  Sorry for the delay.

**Pull request closed without merging**
