### PR TITLE
WIP: [Release] Verify release-12.0.0-rc0

### PR DESCRIPTION
**Pull request by kou**
PR to verify Release Candidate

### CODE REVIEW

**Comment by kou** [comment]
@github-actions crossbow submit  --group verify-rc-source --param release=12.0.0 --param rc=0

**Comment by raulcd** [comment]
Revision: 9736dde84bb2e6996d1d12f6a044c33398e3c3a3

Submitted crossbow builds: [ursacomputing/crossbow @ release-12.0.0-rc0-0](https://github.com/ursacomputing/crossbow/branches/all?query=release-12.0.0-rc0-0)

|Task|Status|
|----|------|
|almalinux-8-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-12.0.0-rc0-0-github-almalinux-8-amd64)|
|almalinux-8-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-12.0.0-rc0-0-github-almalinux-8-arm64)|
|almalinux-9-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-12.0.0-rc0-0-github-almalinux-9-amd64)|
|almalinux-9-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-12.0.0-rc0-0-github-almalinux-9-arm64)|
|amazon-linux-2-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-12.0.0-rc0-0-github-amazon-linux-2-amd64)|
|amazon-linux-2-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-12.0.0-rc0-0-github-amazon-linux-2-arm64)|
|centos-7-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-12.0.0-rc0-0-github-centos-7-amd64)|
|centos-8-stream-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-12.0.0-rc0-0-github-centos-8-stream-amd64)|
|centos-8-stream-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-12.0.0-rc0-0-github-centos-8-stream-arm64)|
|centos-9-stream-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-12.0.0-rc0-0-github-centos-9-stream-amd64)|
|centos-9-stream-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-12.0.0-rc0-0-github-centos-9-stream-arm64)|
|conan-maximum|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-12.0.0-rc0-0-github-conan-maximum)|
|conan-minimum|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-12.0.0-rc0-0-github-conan-minimum)|
|debian-bookworm-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-12.0.0-rc0-0-github-debian-bookworm-amd64)|
|debian-bookworm-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-12.0.0-rc0-0-github-debian-bookworm-arm64)|
|debian-bullseye-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-12.0.0-rc0-0-github-debian-bullseye-amd64)|
|debian-bullseye-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-12.0.0-rc0-0-github-debian-bullseye-arm64)|
|java-jars|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-12.0.0-rc0-0-github-java-jars)|
|nuget|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-12.0.0-rc0-0-github-nuget)|
|python-sdist|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-12.0.0-rc0-0-github-python-sdist)|
|r-binary-packages|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-12.0.0-rc0-0-github-r-binary-packages)|
|test-ubuntu-default-docs|[Azure](https://github.com/ursacomputing/crossbow/tree/release-12.0.0-rc0-0-azure-test-ubuntu-default-docs)|
|ubuntu-focal-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-12.0.0-rc0-0-github-ubuntu-focal-amd64)|
|ubuntu-focal-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-12.0.0-rc0-0-github-ubuntu-focal-arm64)|
|ubuntu-jammy-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-12.0.0-rc0-0-github-ubuntu-jammy-amd64)|
|ubuntu-jammy-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-12.0.0-rc0-0-github-ubuntu-jammy-arm64)|
|ubuntu-kinetic-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-12.0.0-rc0-0-github-ubuntu-kinetic-amd64)|
|ubuntu-kinetic-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-12.0.0-rc0-0-github-ubuntu-kinetic-arm64)|
|wheel-clean|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-12.0.0-rc0-0-github-wheel-clean)|
|wheel-macos-big-sur-cp310-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-12.0.0-rc0-0-github-wheel-macos-big-sur-cp310-arm64)|
|wheel-macos-big-sur-cp311-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-12.0.0-rc0-0-github-wheel-macos-big-sur-cp311-arm64)|
|wheel-macos-big-sur-cp38-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-12.0.0-rc0-0-github-wheel-macos-big-sur-cp38-arm64)|
|wheel-macos-big-sur-cp39-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-12.0.0-rc0-0-github-wheel-macos-big-sur-cp39-arm64)|
|wheel-macos-mojave-cp310-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-12.0.0-rc0-0-github-wheel-macos-mojave-cp310-amd64)|
|wheel-macos-mojave-cp311-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-12.0.0-rc0-0-github-wheel-macos-mojave-cp311-amd64)|
|wheel-macos-mojave-cp37-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-12.0.0-rc0-0-github-wheel-macos-mojave-cp37-amd64)|
|wheel-macos-mojave-cp38-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-12.0.0-rc0-0-github-wheel-macos-mojave-cp38-amd64)|
|wheel-macos-mojave-cp39-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-12.0.0-rc0-0-github-wheel-macos-mojave-cp39-amd64)|
|wheel-manylinux2014-cp310-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-12.0.0-rc0-0-github-wheel-manylinux2014-cp310-amd64)|
|wheel-manylinux2014-cp310-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-12.0.0-rc0-0-github-wheel-manylinux2014-cp310-arm64)|
|wheel-manylinux2014-cp311-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-12.0.0-rc0-0-github-wheel-manylinux2014-cp311-amd64)|
|wheel-manylinux2014-cp311-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-12.0.0-rc0-0-github-wheel-manylinux2014-cp311-arm64)|
|wheel-manylinux2014-cp37-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-12.0.0-rc0-0-github-wheel-manylinux2014-cp37-amd64)|
|wheel-manylinux2014-cp37-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-12.0.0-rc0-0-github-wheel-manylinux2014-cp37-arm64)|
|wheel-manylinux2014-cp38-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-12.0.0-rc0-0-github-wheel-manylinux2014-cp38-amd64)|
|wheel-manylinux2014-cp38-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-12.0.0-rc0-0-github-wheel-manylinux2014-cp38-arm64)|
|wheel-manylinux2014-cp39-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-12.0.0-rc0-0-github-wheel-manylinux2014-cp39-amd64)|
|wheel-manylinux2014-cp39-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-12.0.0-rc0-0-github-wheel-manylinux2014-cp39-arm64)|
|wheel-windows-cp310-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-12.0.0-rc0-0-github-wheel-windows-cp310-amd64)|
|wheel-windows-cp311-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-12.0.0-rc0-0-github-wheel-windows-cp311-amd64)|
|wheel-windows-cp37-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-12.0.0-rc0-0-github-wheel-windows-cp37-amd64)|
|wheel-windows-cp38-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-12.0.0-rc0-0-github-wheel-windows-cp38-amd64)|
|wheel-windows-cp39-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-12.0.0-rc0-0-github-wheel-windows-cp39-amd64)|

**Comment by raulcd** [comment]
@github-actions crossbow submit  --group verify-rc-binaries --group verify-rc-wheels --param release=12.0.0 --param rc=0

**Comment by raulcd** [comment]
@ursabot please benchmark

**Pull request merged**
