### PR TITLE
ARROW-16668: [CI] Add Substrait support to python wheels

### PR DESCRIPTION
**Pull request by raulcd**

### CODE REVIEW

**Comment by raulcd** [comment]
@github-actions crossbow submit wheel-*

**Comment by raulcd** [comment]
@github-actions crossbow submit wheel-windows-*

**Comment by raulcd** [comment]
@kou @kszucs if you have some time, let me know what do you think of this PR. We were not adding substrait, neither testing it, to our Python wheels previously.

**Review by kszucs — APPROVED** [review]
Thanks @raulcd!

**Review by kou — APPROVED** [review]
+1

**Comment by kou** [comment]
@raulcd This broke our doctest. Could you confirm this?

https://github.com/apache/arrow/runs/6615749316?check_suite_focus=true#step:6:5590

```text
_______________________ [doctest] pyarrow.lib.Table.join _______________________
4663         ...                     'year': [2020, 2022, 2019]})
4664         >>> df2 = pd.DataFrame({'id': [3, 4],
4665         ...                     'n_legs': [5, 100],
4666         ...                     'animal': ["Brittle stars", "Centipede"]})
4667         >>> t1 = pa.Table.from_pandas(df1)
4668         >>> t2 = pa.Table.from_pandas(df2)
4669 
4670         Left outer join:
4671 
4672         >>> t1.join(t2, 'id')
Differences (unified diff with -expected +actual):
    @@ -2,9 +2,9 @@
     id: int64
     year: int64
    +animal: string
     n_legs: int64
    -animal: string
     ----
     id: [[3,1,2]]
     year: [[2019,2020,2022]]
    +animal: [["Brittle stars",null,null]]
     n_legs: [[5,null,null]]
    -animal: [["Brittle stars",null,null]]
```

**Comment by raulcd** [comment]
@AlenkaF @jorisvandenbossche Do you know if the output order for these doctests should be deterministic? I can see the errors on master started when we merged this PR as @kou is pointing out but that PR is supposed to only add substrait to our wheels when they are being built but has nothing to do on the job that builds documentation and runs doctests.

**Comment by AlenkaF** [comment]
Oh, this test gave me trouble locally also. If I ran it twice in case of error, the error disappeared.
I am sure this is not connected to this PR but to this one: https://github.com/apache/arrow/pull/13204.

Will research and fix the issue. Thanks Raul for the ping!

**Pull request merged**
