### PR TITLE
GH-14969: [R][Docs] Enable pkgdown built-in search

### LINKED ISSUE #14969: [R] pkgdown built-in search doesn't work
### Describe the bug, including details regarding any error messages, version, and platform.

Built-in search does not seem working.

image

### Component(s)

R, Website

### PR DESCRIPTION
**Pull request by eitsupi**
### Rationale for this change

Enable local search of pkgdown site.

### What changes are included in this PR?

Remove some files that are not currently in use.

### Are these changes tested?

There is no test, but the following functions can be run to verify that the site is working properly.

```r
pkgdown::init_site("r")
pkgdown::build_search("r")
pkgdown::build_home("r")
```

### Are there any user-facing changes?

No. Document changes only.
* Closes: #14969

### CODE REVIEW

**Comment by eitsupi** [comment]
@github-actions crossbow submit preview-docs

**Comment by eitsupi** [comment]
I am wondering if `r/pkgdown/templates/navbar.html` is also not currently in use and could be removed. (which seems to have nothing to do with fixing this issue)

**Comment by kou** [comment]
Preview: http://crossbow.voltrondata.com/pr_docs/36374/r/

It seems that search box works. Is this expected behavior?

**Comment by eitsupi** [comment]
> It seems that search box works. Is this expected behavior?

Yes, I think it is working well.

**Comment by kou** [comment]
@thisisnic @paleolimbot Can we merge this?

**Comment by thisisnic** [comment]
Sorry for the delay on this, have been on holiday.

> I am wondering if r/pkgdown/templates/navbar.html is also not currently in use and could be removed. (which seems to have nothing to do with fixing this issue)

Unsure without looking into this if it's a custom template or not, but open to removing it if it's not used - let's discuss in another issue.

Not a criticism but an FYI - I would have approved this sooner with a bit more information confirming that we no longer use the tabset functionality that is implemented in `extra.js`, but I had a scan through the code and it appears we no longer use this, so it looks good to remove it.  

Thanks for investigating and fixing this @eitsupi, it'll be helpful to have the search functionality working now!

Before I merge this, would you mind removing `{.tabset}` on line 90 in `vignettes/developers/setup.Rmd`?  If you don't get to it before I get back, I'll push the change to the branch.

**Review by thisisnic — APPROVED** [review]

**Comment by eitsupi** [comment]
@github-actions crossbow submit preview-docs

**Comment by eitsupi** [comment]
> Preview: [http://crossbow.voltrondata.com/pr_docs/36374/r](http://crossbow.voltrondata.com/pr_docs/36374/r/)

Where can I look to find out this URL? (I recall it being listed in the GitHub Actions log, but I just looked and couldn't find it)

**Comment by kou** [comment]
See the summary view: https://github.com/ursacomputing/crossbow/actions/runs/5465384142#summary-14796723867

**Comment by eitsupi** [comment]
> See the summary view: [ursacomputing/crossbow/actions/runs/5465384142#summary-14796723867](https://github.com/ursacomputing/crossbow/actions/runs/5465384142#summary-14796723867)

Oh, I get it. Thanks.

**Pull request merged**
