### PR TITLE
ARROW-1047: [Java] [FollowUp] Change ArrowMagic to be non-public class

### PR DESCRIPTION
**Pull request by icexelloss**
Move ArrowMagic from vector.ipc to vector.ipc.message package.

### CODE REVIEW

**Comment by icexelloss** [comment]
cc @BryanCutler

**Review by wesm — APPROVED** [review]
+1, though `ArrowMagic` is only used in the file reader/writer

**Comment by BryanCutler** [comment]
I was thinking of `ArrowMagic` more being part of the file protocol than a message, but it's fine with me if you prefer to move it there.

**Comment by wesm** [comment]
I suggest we do not merge this because the magic number is only used in the file implementation, if that's OK

**Comment by icexelloss** [comment]
Yes that's good point. I will change the PR to make it ArrowMagic non public class.

**Comment by wesm** [comment]
+1

**Pull request closed without merging**
