### PR TITLE
ARROW-13493  [C++] Anonymous structs in an anonymous union are a GNU extension

### PR DESCRIPTION
**Pull request by nirandaperera**

### CODE REVIEW

**Comment by nealrichardson** [comment]
I've reproduced the error on https://github.com/apache/arrow/pull/10839, so I'll merge that (assuming I haven't broken other things) and then you can rebase this, run the as-cran crossbow job, and we should see the build pass.

**Comment by nealrichardson** [comment]
ok @nirandaperera, merged, please rebase and then do `@github-actions crossbow submit test-r-linux-as-cran`

**Comment by nirandaperera** [comment]
@github-actions crossbow submit test-r-linux-as-cran

**Comment by nealrichardson** [comment]
Looks like you fixed one warning but there's still another: https://github.com/ursacomputing/crossbow/runs/3203443397?check_suite_focus=true#step:7:192

**Comment by nirandaperera** [comment]
@github-actions crossbow submit test-r-linux-as-cran

**Comment by nirandaperera** [comment]
@nealrichardson I think this is fine now! :-)

**Review by nealrichardson — APPROVED** [review]
+1, thank you! 🙏

**Pull request closed without merging**
