### PR TITLE
ARROW-1557 [Python] Validate names length in Table.from_arrays

### PR DESCRIPTION
**Pull request by TomAugspurger**
We now raise a ValueError when the length of the names doesn't match
the length of the arrays.

```python
In [1]: import pyarrow as pa

In [2]: pa.Table.from_arrays([pa.array([1, 2]), pa.array([3, 4])], names=['a', 'b', 'c'])
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-2-cda803f3f774> in <module>()
----> 1 pa.Table.from_arrays([pa.array([1, 2]), pa.array([3, 4])], names=['a', 'b', 'c'])

table.pxi in pyarrow.lib.Table.from_arrays()

table.pxi in pyarrow.lib._schema_from_arrays()

ValueError: Length of names (3) does not match length of arrays (2)
```

This affected `RecordBatch.from_arrays` and `Table.from_arrays`.

### CODE REVIEW

**Review by wesm — APPROVED** [review]
+1, thanks @TomAugspurger!

**Comment by wesm** [comment]
Appears there is a test failure that was exposed by this patch, can you fix?

**Comment by wesm** [comment]
here's a fix to cherry pick https://github.com/wesm/arrow/commit/965a560867f45025dcbfe50c572593faa7d7cb33

**Comment by TomAugspurger** [comment]
Sure thing. While we have the chance, on https://github.com/apache/arrow/pull/1117/files#diff-434b799d30eaec7287bee5603a9c45beR318, should that be changed to `if not K`, since that's already `len(arrays)`? My intuition is that `len` is going to be pretty quick anyway, but thought I'd check.

**Comment by wesm** [comment]
`if not K` is probably better, feel free to make that change too

**Comment by wesm** [comment]
In case it's useful we have nightly dev builds

**Pull request closed without merging**
