### PR TITLE
[MINOR] Add Flight SQL Example Link

### PR DESCRIPTION
**Pull request by thatstatsguy**
Add Go example to documentation for Flight SQL

### CODE REVIEW

**Comment by lidavidm** [comment]
Thanks!

This is meant as a specification document. Perhaps the right place to put this is in the Go docs themselves?

**Comment by thatstatsguy** [comment]
Thanks for the feedback David! 

I guess the underlying issue here is I really struggled to find an example for implementing Apache Arrow SQL. 

I think others may have struggled too and would appreciate a central view of examples available (even if it's still experimental)

No objection to moving it elsewhere given it's a spec doc - just wanted to flag the issue I had :)

**Comment by lidavidm** [comment]
The [Cookbook](https://arrow.apache.org/cookbook/) is what we use for examples. That said Flight SQL examples would probably be too long to fit that well.

I also don't think the examples in the source tree are really meant as examples - at least the C++/Java ones are really harnesses for unit testing.

That said, the example is already in the [Go docs](https://pkg.go.dev/github.com/apache/arrow/go/v10@v10.0.0/arrow/flight/flightsql/example). I would be ok with adding C++/Go/Java links to 'external resources' with a disclaimer.

**Comment by amol-** [comment]
Closing because it has been untouched for a while, in case it's still relevant feel free to reopen and move it forward 👍

**Pull request closed without merging**
