### PR TITLE
ARROW-3169: [C++] Break up array-test into multiple compilation units

### PR DESCRIPTION
**Pull request by pitrou**
This makes the code easier to read and also eases up recompilation times on multicore setups.

### CODE REVIEW

**Comment by wesm** [comment]
What do you think about creating an "array" or "columnar" subdirectory where this code (and also possibly array.cc) can be organized?

**Comment by pitrou** [comment]
I don't know. The Array class is pretty central so it feels a bit weird to put it in a subdirectory. Perhaps we need to think about it some more or ask other people.

**Comment by wesm** [comment]
Right. The public API "arrow/array.h" wouldn't need to change. We can solicit some more opinions; not really necessary to do anything here

**Comment by pitrou** [comment]
cc @xhochy for opinions.

**Comment by fsaintjacques** [comment]
My opinion: I'd like having a `core` where the very important stuff is, notably type.h, buffer.h, array.h, table.h (possibly move ChunkedArray out of table.h in it's own header), record_batch ...

This would help new comers, you point them to the directory. The other possibility is to clean up the root directory by hidding the not "critical" stuff, e.g. allocator, builder, compare, memory pool, pretty print, status, table builder, visitor...

**Comment by pitrou** [comment]
I don't know. Personally I'd rather keep the important stuff in the base directory, where it's immediately reachable :-)

**Comment by wesm** [comment]
We used to have things split up, a long time ago

https://github.com/apache/arrow/tree/apache-arrow-0.1.0/cpp/src/arrow/types

I do like having the "most important stuff" in the base directory, at least the public headers.

**Review by wesm — APPROVED** [review]
+1, except from a directory listing point of view should we use "array-binary-test.cc" instead of "binary-array-test.cc"?

**Comment by wesm** [comment]
Not sure why the Windows toolchain build is complaining about double-conversion

```
Make Error at cmake_modules/ThirdpartyToolchain.cmake:503 (find_package):
  Could not find a package configuration file provided by "double-conversion"
  with any of the following names:
    double-conversionConfig.cmake
    double-conversion-config.cmake
  Add the installation prefix of "double-conversion" to CMAKE_PREFIX_PATH or
  set "double-conversion_DIR" to a directory containing one of the above
  files.  If "double-conversion" provides a separate development package or
  SDK, be sure it has been installed.
```

**Comment by pitrou** [comment]
It failed downloading it from conda-forge:
https://ci.appveyor.com/project/ApacheSoftwareFoundation/arrow/builds/20621397/job/ktkt3i9iqfjrckl9#L393

**Comment by pitrou** [comment]
> +1, except from a directory listing point of view should we use "array-binary-test.cc" instead of "binary-array-test.cc"?

That was my intuition as well, but I thought it might sound weird for english speakers?

**Comment by wesm** [comment]
Using `array-X-test.cc` sounds good to me. The "array-" bit is more of a "namespace" than anything, and helps keep the files organized to the eye

**Pull request closed without merging**
