### PR TITLE
GH-31621: [JS] Fix Union null bitmaps

### LINKED ISSUE #17168: [Integration][JS] Fix map type to allow non-standard field names
Javascript should support the integration test added in ARROW-7173.

**Reporter**: [Antoine Pitrou](https://issues.apache.org/jira/browse/ARROW-8716) / @pitrou

<sub>**Note**: *This issue was originally created as [ARROW-8716](https://issues.apache.org/jira/browse/ARROW-8716). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

### LINKED ISSUE #37063: [JavaScript] Vector includes will return false for first element
### Describe the bug, including details regarding any error messages, version, and platform.

The [implementation](https://github.com/apache/arrow/blob/main/js/src/vector.ts#L198) for `includes` in the `Vector` class seems to have a minor bug: the comparison will return false if argument is the first element (element at index 0).

Example code:
```javascript
import {vectorFromArray} from 'apache-arrow';
const arr = [1, 2, 3];
const v = vectorFromArray(arr);
console.log(v.includes(1)); // false 
console.log(v.indexOf(1)); // 0
```

### Component(s)

JavaScript

### PR DESCRIPTION
**Pull request by trxcllnt**
This PR fixes `Union` null handling, and re-enables the disabled `SparseUnion` test.

The format doc [says](https://arrow.apache.org/docs/format/Columnar.html#union-layout):
> Unlike other data types, unions do not have their own validity bitmap.

Therefore we need to remove null masks from union types and allow them to delegate validity to their children.

Also fixes https://github.com/apache/arrow/issues/37063 for good measure.

* Closes: #31621
* Closes: #37063
* Closes #24123
* Closes #17168

### CODE REVIEW

**Review by domoritz — APPROVED** [review]

**Comment by trxcllnt** [comment]
@pitrou yes, it should. I'll enable the integration tests now.

**Review by domoritz — APPROVED** [review]

**Comment by trxcllnt** [comment]
The integration test is failing because the unions test has duplicate field names. I have a fix for it locally, but it involves renaming the duplicated `sparse` and `dense` fields to `sparse_{1,2}` and `dense_{1,2}`.

**Comment by kou** [comment]
@eerhardt Could you take a look at this?

**Comment by eerhardt** [comment]
@trxcllnt - can you run the integration tests locally? The arrow file should be written to the location that `--arrow-file` specifies when the test runs.

**Comment by trxcllnt** [comment]
@eerhardt I've only ever compiled and run the JS, C++, and Java. Don't really wanna install mono, is there a way to do it via docker?

**Comment by eerhardt** [comment]
> Don't really wanna install mono

You don't need to install mono. .NET runs on Linux and Mac. https://dot.net/download

> is there a way to do it via docker?

Yes, this is how the integration tests run in CI. You can execute the same commands as what CI does:

https://github.com/apache/arrow/blob/29819425f428d703ad5c80cc0afaf7902dbbb224/.github/workflows/integration.yml#L85-L95

You should be able to speed it up by commenting out the languages you don't need to build here:

https://github.com/apache/arrow/blob/29819425f428d703ad5c80cc0afaf7902dbbb224/docker-compose.yml#L1709-L1715

and here:

https://github.com/apache/arrow/blob/29819425f428d703ad5c80cc0afaf7902dbbb224/ci/scripts/integration_arrow.sh#L28-L40

**Review by domoritz — APPROVED** [review]

**Pull request merged**
