### PR TITLE
ARROW-11280: [Release][APT] Fix minimal build example check

### PR DESCRIPTION
**Pull request by kou**

### CODE REVIEW

**Comment by kou** [comment]
C++ bug: #9224

**Comment by kou** [comment]
Packaging bug: #9225

**Comment by kszucs** [comment]
If I understand correctly this patch is required to verify the current RC0 packages. Shall we cut a new RC to produce new packages?

**Comment by kszucs** [comment]
I'll wait for the yum fixes meanwhile.

**Comment by kou** [comment]
OK. I'll remove the workaround.
The fix for the "minimal_build" example check is still needed for RC1.

**Comment by kou** [comment]
Yum fix: #9229

**Comment by kou** [comment]
+1

**Pull request closed without merging**
