### PR TITLE
ARROW-2520: [Rust] CI should also build against nightly Rust

### PR DESCRIPTION
**Pull request by kszucs**

### CODE REVIEW

**Comment by wesm** [comment]
Since these builds are both pretty fast can you run them in the same CI entry?

**Comment by kszucs** [comment]
Sure, I was considering that alternative too. Hopefully both toolchains are going to be cached properly.

**Comment by kszucs** [comment]
@xhochy could You take a look at this one too?

**Review by xhochy — APPROVED** [review]
+1, LGTM

**Comment by kszucs** [comment]
Thanks!

**Pull request closed without merging**
