### PR TITLE
ARROW-1577: [JS] add ASF release scripts

### PR DESCRIPTION
**Pull request by trxcllnt**
@wesm does [this](https://github.com/apache/arrow/commit/b270dbad4f4fd70e19613b93148ec2ae3596e1fd#diff-fc8acbd4f42fb5e6b0cad14928b68115R59) look good?

### CODE REVIEW

**Comment by trxcllnt** [comment]
@wesm ok, I added `dev/release/js-source-release.sh` and `js/npm-release.sh` scripts:

```sh
cd $ARROW_HOME
# create a release branch (assuming patch release 0.1.2 -> 0.1.3)
git co -b release-js-0_1_3
# create a new v0.1.3 tag
git tag -a apache-arrow-js-0.1.3 -m "v0.1.3"
./dev/release/js-source-release.sh
# > Usage: ./dev/release/js-source-release.sh <js-version> <arrow-version> <rc-num>

# - runs `npm version 0.1.3 --no-git-tag-version`
# - git-commits the new package.json@0.1.3
# - creates a tarball at dev/release/js-tmp/apache-arrow-js-0.1.3.tar.gz
# - copies signed tarballs to dev/release/js-tmp/js-rc-tmp/apache-arrow-js-0.1.3-rc0
# - svn commits the dev/release/js-tmp/js-rc-tmp/apache-arrow-js-0.1.3-rc0 directory

# js-version 0.1.3, arrow-version 0.8.0, rc 0
./dev/release/js-source-release.sh 0.1.3 0.8.0 0
```

And when we're ready to publish the modules to npm, we can run:
```sh
cd apache-arrow-js-0.1.3-rc0
tar -xzf *.tar.gz
cd apache-arrow-js-0.1.3
# provide the same arrow-version so we can add an npm dist-tag to indicate which versions of Arrow the JS lib is compatible with
npm run release -- 0.8.0
# available at either
npm install apache-arrow@0.1.3
# or 
npm install apache-arrow@v0.8.0
```

At the moment the `npm-release.sh` script [executes the integration tests](https://github.com/apache/arrow/pull/1346/commits/c9cb2e04ec4a85fe1e49d1c023b15fceb3598952#diff-a8aff12ce8d320cec92901f4a8129ed3R27) before publishing.

If the `npm run release` step is run with the [integration test envars](https://github.com/trxcllnt/arrow/blob/js-asf-release-scripts/js/gulp/test-task.js#L66) available (or at the same directory level as the `arrow/js`), it should work fine. If thats's too much of a hassle, feel free to comment them out:
```sh
# validate the targets pass all tests before publishing
npm install
# npx run-s clean:all lint create:testdata build
# npm run test -- -t ts -u --integration
# npm run test -- --integration
npx run-s clean:all lint build
npm run test
# ...
```

**Comment by wesm** [comment]
In
 
```
# available at either
npm install apache-arrow@0.1.3
# or 
npm install apache-arrow@v0.8.0
```

I am concerned this might confuse more than help. As long as two implementations are using the same metadata version (e.g. V4), then the older metadata is supposed to be forward compatible. So an older JS version that uses V4 would be compatible with versions of the other Arrow libraries other than 0.8.0. Is there somewhere else where we can document the version cross-compatibility?

**Comment by wesm** [comment]
There are some missing steps in running the source release, can you let me know what I need to do?

* Installed node with nvm `nvm install node`
* Tried running dev/release/js-source-release.sh, failed due to missing gulp
* Ran `npm install --global gulp`, then tried the script again, failed with:

```
Preparing source for tag apache-arrow-js-0.2.0
Using commit 6beed6abf3d288511a0766bf51a255842290032f

> apache-arrow@0.2.0 clean:testdata /home/wesm/code/arrow/js
> gulp clean:testdata

module.js:544
    throw err;
    ^

Error: Cannot find module 'del'
    at Function.Module._resolveFilename (module.js:542:15)
    at Function.Module._load (module.js:472:25)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/wesm/code/arrow/js/gulpfile.js:18:13)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! apache-arrow@0.2.0 clean:testdata: `gulp clean:testdata`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the apache-arrow@0.2.0 clean:testdata script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/wesm/.npm/_logs/2017-11-22T15_10_58_135Z-debug.log
```

**Comment by trxcllnt** [comment]
@wesm ah right, I forgot you need the dependencies installed. I've updated the release script run `npm install` before doing things.

You shouldn't need to hand edit the version in package.json, because the [`npm version`](https://docs.npmjs.com/cli/version) command will do that for you [here](https://github.com/apache/arrow/pull/1346/commits/567c570e3568a97e90349e6911fa342b6c08274b#diff-2ca055280723a1db988255852328f368R54). If the version is already set in package.json to the value you pass to `js-source-release.sh`, the command will fail with a "same-version" error.

`npm version` typically also automatically creates git tags. I had this disabled, but found a config variable that lets us specify the [tag version prefix](https://docs.npmjs.com/misc/config#tag-version-prefix)

So now [this command](https://github.com/apache/arrow/pull/1346/commits/6692e1797a355e7351be16cced42511ff2bb006c#diff-2ca055280723a1db988255852328f368R44) will:
1. increment the package.json version to the `$js_version` you pass to `js-source-release.sh`
2. `git commit -m "[Release] apache-arrow-js-X.Y.Z"`
3. `git tag -a apache-arrow-js-X.Y.Z` ([specified here]((https://github.com/apache/arrow/pull/1346/commits/6692e1797a355e7351be16cced42511ff2bb006c#diff-3564d26fe29cca7ef63a785b2ed23ed0R3)))

so now you shouldn't have to explicitly create a new git tag before running `js-source-release.sh`, as npm will do that automatically.

**Comment by wesm** [comment]
Cool, I will give it another go!

**Comment by wesm** [comment]
```
$ dev/release/js-source-release.sh 0.2.0 0
Preparing source for tag apache-arrow-js-0.2.0

> uglifyjs-webpack-plugin@0.4.6 postinstall /home/wesm/code/arrow/js/node_modules/webpack/node_modules/uglifyjs-webpack-plugin
> node lib/post_install.js

npm WARN apache-arrow@0.1.2 requires a peer of command-line-usage@4.0.1 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 1269 packages in 22.642s
v0.2.0

> apache-arrow@0.2.0 version /home/wesm/code/arrow/js
> npm install && npm run clean:all

npm WARN apache-arrow@0.2.0 requires a peer of command-line-usage@4.0.1 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 116 packages in 4.871s

> apache-arrow@0.2.0 clean:all /home/wesm/code/arrow/js
> run-p clean clean:testdata


> apache-arrow@0.2.0 clean /home/wesm/code/arrow/js
> gulp clean


> apache-arrow@0.2.0 clean:testdata /home/wesm/code/arrow/js
> gulp clean:testdata

[15:59:12] Using gulpfile ~/code/arrow/js/gulpfile.js
[15:59:12] Using gulpfile ~/code/arrow/js/gulpfile.js
[15:59:12] Starting 'clean:testdata'...
[15:59:12] Starting 'clean'...
[15:59:12] Starting 'clean:ts'...
[15:59:12] Starting 'clean:apache-arrow'...
[15:59:12] Starting 'clean:es5:cjs'...
[15:59:12] Starting 'clean:es2015:cjs'...
[15:59:12] Starting 'clean:esnext:cjs'...
[15:59:12] Starting 'clean:es5:esm'...
[15:59:12] Starting 'clean:es2015:esm'...
[15:59:12] Starting 'clean:esnext:esm'...
[15:59:12] Starting 'clean:es5:cls'...
[15:59:12] Starting 'clean:es2015:cls'...
[15:59:12] Starting 'clean:esnext:cls'...
[15:59:12] Starting 'clean:es5:umd'...
[15:59:12] Starting 'clean:es2015:umd'...
[15:59:12] Starting 'clean:esnext:umd'...
[15:59:12] Finished 'clean:testdata' after 5.41 ms
[15:59:12] Finished 'clean:ts' after 10 ms
[15:59:12] Finished 'clean:apache-arrow' after 11 ms
[15:59:12] Finished 'clean:es5:cjs' after 11 ms
[15:59:12] Finished 'clean:es2015:cjs' after 11 ms
[15:59:12] Finished 'clean:esnext:cjs' after 11 ms
[15:59:12] Finished 'clean:es5:esm' after 14 ms
[15:59:12] Finished 'clean:es2015:esm' after 14 ms
[15:59:12] Finished 'clean:esnext:esm' after 14 ms
[15:59:12] Finished 'clean:es5:cls' after 14 ms
[15:59:12] Finished 'clean:es2015:cls' after 14 ms
[15:59:12] Finished 'clean:esnext:cls' after 14 ms
[15:59:12] Finished 'clean:es5:umd' after 14 ms
[15:59:12] Finished 'clean:es2015:umd' after 14 ms
[15:59:12] Finished 'clean:esnext:umd' after 14 ms
[15:59:12] Finished 'clean' after 17 ms
Cannot continue: unknown git tag: apache-arrow-js-0.2.0
```

**Comment by wesm** [comment]
Rebased. +1, will merge once the builds run

**Comment by wesm** [comment]
Thanks @trxcllnt!

**Pull request closed without merging**
