### PR TITLE
Fix typo in plasma protocol.

### PR DESCRIPTION
**Pull request by Yeolar**

### CODE REVIEW

**Comment by pcmoritz** [comment]
+1 for the change

**Comment by wesm** [comment]
Could this error have caused any problems? Any way to test for it (e.g. a DCHECK someplace?)?

**Comment by pcmoritz** [comment]
Good question! The method is tested here:
https://github.com/apache/arrow/blob/master/cpp/src/plasma/test/serialization_tests.cc#L176

What we could do is injecting flatbuffer verifier calls in all the methods in plasma_protocol (only in debug mode); I don't think flatbuffers::GetRoot has a way of detecting that the wrong message was read. What do you think?

**Comment by Yeolar** [comment]
PlasmaSealRequest covers PlasmaReleaseRequest, in plasma.fbs. (For "object_id: string;" is also the first field in PlasmaSealRequest.) I think that's why no error occured, flatbuffers is just casting types from void*.  Agree with @pcmoritz, maybe can use the Verify method for checking in test.

**Comment by pcmoritz** [comment]
Ok, I created a JIRA here: https://issues.apache.org/jira/browse/ARROW-1255

@Yeolar: Do you want to tackle it as part of this PR? We can probably do this with minimal code duplication (and effort) by making a new method that replaces flatbuffers::GetRoot and checks with the verifyer. Maybe such a method already exists in flatbuffers.

**Comment by Yeolar** [comment]
@pcmoritz , I've submitted a new PR https://github.com/apache/arrow/issues/887, please have a look if it's apposite. By the way, when compiling arrow, it seems plasma not compiled, how to include?

**Comment by pcmoritz** [comment]
Thanks, I'll have a look! Here is a draft of the documentation on how to make Plasma work: https://github.com/pcmoritz/arrow/blob/724fd2f4dbd2655bcd33d8e672198fd1b704c75a/python/doc/source/plasma.rst

The gist of it is that you need to pass -DARROW_PLASMA=on into CMake when compiling the C++ part of arrow and then set the environment variable PYARROW_WITH_PLASMA=1 when running setup.py.

The documentation is work in progress (see https://github.com/apache/arrow/pull/881), let us know if you have ideas on how to improve it. The Python documentation should already work, the C++ one I need to fix first, I'll do that in the next couple of days.

**Pull request closed without merging**
