### PR TITLE
ARROW-7829: [R] Test R bindings on clang 

### PR DESCRIPTION
**Pull request by nealrichardson**

### CODE REVIEW

**Comment by nealrichardson** [comment]
@ursabot crossbow submit macos-r-autobrew

**Comment by kszucs** [comment]
[AMD64 Conda Crossbow Submit (#90275)](https://ci.ursalabs.org/#builders/98/builds/529) builder has been succeeded.

Revision: f0711ff66b84f6dd56f7dfafe16117ca1a8dc8f3

Submitted crossbow builds: [ursa-labs/crossbow @ ursabot-502](https://github.com/ursa-labs/crossbow/branches/all?query=ursabot-502)

|Task|Status|
|----|------|
|macos-r-autobrew|[TravisCI](https://travis-ci.org/ursa-labs/crossbow/branches)|

**Comment by nealrichardson** [comment]
@ursabot crossbow submit macos-r-autobrew

**Comment by kszucs** [comment]
[AMD64 Conda Crossbow Submit (#90276)](https://ci.ursalabs.org/#builders/98/builds/530) builder has been succeeded.

Revision: 05169013d5bd28e100a8d9cd4850cafd9d6aa0e3

Submitted crossbow builds: [ursa-labs/crossbow @ ursabot-503](https://github.com/ursa-labs/crossbow/branches/all?query=ursabot-503)

|Task|Status|
|----|------|
|macos-r-autobrew|[TravisCI](https://travis-ci.org/ursa-labs/crossbow/branches)|

**Comment by nealrichardson** [comment]
@ursabot crossbow submit macos-r-autobrew

**Comment by kszucs** [comment]
[AMD64 Conda Crossbow Submit (#90277)](https://ci.ursalabs.org/#builders/98/builds/531) builder has been succeeded.

Revision: 58b911fa0afde6c09eeb90143198deb22437f24f

Submitted crossbow builds: [ursa-labs/crossbow @ ursabot-504](https://github.com/ursa-labs/crossbow/branches/all?query=ursabot-504)

|Task|Status|
|----|------|
|macos-r-autobrew|[TravisCI](https://travis-ci.org/ursa-labs/crossbow/branches)|

**Pull request closed without merging**
