### PR TITLE
ARROW-5721: [Rust] Move array related code into a separate module

### PR DESCRIPTION
**Pull request by sunchao**
This moves all array related code into a separate module `array`, and re-export public interfaces.
This allows us to:
1. Split array related implementations into multiple files (e.g., equality, display, etc).
2. Via re-exporting, we can keep the common structs/traits under the `arrow::array` namespace. So,
instead of saying:
```rust
import arrow::builder::Int32Builder;
```
We can say:
```rust
import arrow::array::Int32Builder;
```
which is more accurate.

### CODE REVIEW

**Review by nevi-me — APPROVED** [review]
LGTM

**Comment by kszucs** [comment]
@sunchao how about renaming `array_data.rs` to `data.rs`?

**Comment by sunchao** [comment]
@kszucs Good idea. Will do.

**Comment by sunchao** [comment]
@kszucs can you take another look? thanks.

**Review by kszucs — APPROVED** [review]
LGTM, thanks @sunchao!

**Pull request closed without merging**
