### PR TITLE
ARROW-12952: [C++] Add count_substring_regex

### PR DESCRIPTION
**Pull request by lidavidm**
This also adds the regular case-insensitive count_substring.

### CODE REVIEW

**Comment by pitrou** [comment]
Can you rebase this @lidavidm ?

**Comment by lidavidm** [comment]
Rebased, thanks for the reminder.

**Review by pitrou — APPROVED** [review]
LGTM, just a nit

**Comment by pitrou** [comment]
Hmm, there are conflicts now...

**Comment by lidavidm** [comment]
It's because the tests overlap/I forgot to rename & move the test case for ascii_replace_slice (now done).

**Comment by lidavidm** [comment]
Thanks for the review!

CI green other than the usual culprits, merging.

**Pull request closed without merging**
