### PR TITLE
ARROW-4744: [C++][CI] Change mingw builds back to debug.  Cleanup up some version warnings

### PR DESCRIPTION
**Pull request by emkornfield**

### CODE REVIEW

**Comment by kou** [comment]
Thanks!
Should we do the same thing for Zstd?

https://ci.appveyor.com/project/ApacheSoftwareFoundation/arrow/builds/22762420/job/4xuv4mpnwvmq5byf#L391

```text
C:/projects/arrow/cpp/src/arrow/util/compression_zstd.cc: In member function 'virtual int64_t arrow::util::ZSTDCodec::MaxCompressedLen(int64_t, const uint8_t*)':
C:/projects/arrow/cpp/src/arrow/util/compression_zstd.cc:232:38: error: conversion to 'size_t {aka unsigned int}' from 'int64_t {aka long long int}' may alter its value [-Werror=conversion]
   return ZSTD_compressBound(input_len);
                                      ^
cc1plus.exe: all warnings being treated as errors
```

**Comment by emkornfield** [comment]
Yes on it.

**Comment by emkornfield** [comment]
Also, should/can these checks be turned on for linux builds?

**Comment by emkornfield** [comment]
or turned off for ming in the short term?  I don't understand why the breakage just started occurring now.

**Comment by kou** [comment]
It's caused by combination of #3693 and #3750. It's my fault. Sorry.
We can disable `-Werror` by the following change:

```diff
diff --git a/ci/appveyor-cpp-build-mingw.bat b/ci/appveyor-cpp-build-mingw.bat
index 249ea1ab..bdd3b144 100644
--- a/ci/appveyor-cpp-build-mingw.bat
+++ b/ci/appveyor-cpp-build-mingw.bat
@@ -17,8 +17,8 @@
 
 @echo on
 
-set CMAKE_BUILD_TYPE=debug
-set MESON_BUILD_TYPE=debug
+set CMAKE_BUILD_TYPE=release
+set MESON_BUILD_TYPE=release
 
 set INSTALL_DIR=%HOMEDRIVE%%HOMEPATH%\install
 set PATH=%INSTALL_DIR%\bin;%PATH%
```

**Comment by emkornfield** [comment]
@kou I made the change, lets hope that fixes CI (I think the other changes aren't bad so I'll leave them in if that is OK).  I sent a follow-up e-mail to the mailing to see how we want to proceed with some of these ignored warnings.

**Comment by emkornfield** [comment]
Build failure is plasma (looks like it might be flaky? because its based on timestamps):
    
            # Test timestamps
            t1 = time.time()
            x, _, _ = create_object(plasma_client, 3, metadata_size=0, seal=False)
            t2 = time.time()
            l6 = plasma_client.list()
>           assert math.floor(t1) <= l6[x]["create_time"] <= math.ceil(t2)
E           assert 1551585976 <= 1551585975
E            +  where 1551585976 = <built-in function floor>(1551585976.0053494)
E            +    where <built-in function floor> = math.floor

**Comment by kou** [comment]
+1
`arrow-array-test` is stuck with MinGW 32bit but it's not related in this change.
https://ci.appveyor.com/project/ApacheSoftwareFoundation/arrow/builds/22779178/job/787pa80bsth5rb4d#L727

**Comment by xhochy** [comment]
@kou @emkornfield The 64bit builds now get stuck from time to time too on master: https://ci.appveyor.com/project/ApacheSoftwareFoundation/arrow/builds/22779601/job/d1h0bfv5oyecs414

**Comment by emkornfield** [comment]
@kou do you have thoughts on what might be causing that?  Could we maybe disable ming64 until we can figure it out?

**Comment by kou** [comment]
I don't know why... It's not reproduced on my local machine.
We can disable only `arrow-array-test` instead of disabling all MinGW 64bit build. I want to keep Apache Arrow 0.13.0 buildable with MinGW.

**Comment by emkornfield** [comment]
@kou is disabling something you can do?  I'm currently working on another flaky test and probably won't be able to get to it tonight.

**Comment by kou** [comment]
OK. I'll do later.

**Comment by kou** [comment]
Done: #3809

**Pull request closed without merging**
