### PR TITLE
ARROW-6504: [Python][Packaging] Add mimalloc to conda packages for better performance

### PR DESCRIPTION
**Pull request by kszucs**

### CODE REVIEW

**Comment by kszucs** [comment]
@ursabot crossbow submit -g conda

**Review by pitrou — APPROVED** [review]
+1 from me

**Comment by kszucs** [comment]
@pitrou mimalloc doesn't seem to compile in the windows builds

**Comment by pitrou** [comment]
@kszucs Try to add `os: Visual Studio 2015` at the beginning of your appveyor.yml?

**Comment by kszucs** [comment]
I'll try to move the windows builds to azure as well following the recent feedstock changes.

**Comment by kszucs** [comment]
@ursabot crossbow submit conda-win-vs2015-py36 conda-win-vs2015-py37

**Comment by kszucs** [comment]
@ursabot crossbow submit conda-win-vs2015-py36 conda-win-vs2015-py37

**Comment by kszucs** [comment]
@ursabot crossbow submit conda-win-vs2015-py36 conda-win-vs2015-py37

**Comment by kszucs** [comment]
@ursabot crossbow submit -g conda

**Review by kszucs — COMMENTED** [review]
+1

**Pull request closed without merging**
