### PR TITLE
ARROW-7328: [CI] GitHub Actions should trigger on changes to GitHub Actions configuration

### PR DESCRIPTION
**Pull request by kszucs**

### CODE REVIEW

**Review by pitrou — APPROVED** [review]
+1

**Comment by fsaintjacques** [comment]
dumb idea, can we move this into `ci/github-workflow` and symlink `.github` there? That would fall under the `ci/**` rule.

**Comment by pitrou** [comment]
@fsaintjacques The nice thing with the current approach is that changes to a YAML file doesn't trigger unrelated builds, only the builds backed by that YAML file.

**Review by kou — APPROVED** [review]
+1

Rust failures are unrelated. We should fix them separately.

Python's pandas master failure is also unrelated. https://issues.apache.org/jira/browse/ARROW-7497 tracks this.

**Pull request closed without merging**
