### PR TITLE
ARROW-11231: [Python][Packaging] Enable mimalloc in wheels

### PR DESCRIPTION
**Pull request by pitrou**

### CODE REVIEW

**Comment by pitrou** [comment]
@github-actions crossbow -c ursacomputing/crossbow submit -g wheel

**Review by xhochy — APPROVED** [review]
+1 LGTM

**Comment by kszucs** [comment]
I applied this change in #9096 since I'm going to submit the wheel builds again to verify the changes there.

**Comment by pitrou** [comment]
Wheel builds triggered here:
https://github.com/ursacomputing/crossbow/branches/all?query=build-10

(note that we can't enable mimalloc on manylinux1 because it fails to compile)

**Comment by pitrou** [comment]
All passed on https://github.com/ursacomputing/crossbow/branches/all?query=build-10

**Comment by kszucs** [comment]
> Wheel builds triggered here:
> https://github.com/ursacomputing/crossbow/branches/all?query=build-10
> 
> (note that we can't enable mimalloc on manylinux1 because it fails to compile)

I removed manylinux1 altogether.

**Comment by pitrou** [comment]
Closing in favour of #9096.

**Pull request closed without merging**
