### PR TITLE
ARROW-7786: [R] Wire up check_metadata in Table.Equals method

### PR DESCRIPTION
**Pull request by nealrichardson**
In tests, use `expect_equal()` to test that Tables and Schemas are the same, including metadata. Use `expect_equivalent()` to skip the metadata check.

This patch also adds the `Schema$WithMetadata()` method to set key-value metadata. It also fixes a bunch of invalid Equals methods that either errored or segfaulted when you passed a non-Arrow object to them. 

I created https://issues.apache.org/jira/browse/ARROW-7891 as a followup for adding a check_metadata argument to RecordBatch->Equals in C++, since it seems like it should exist.

### CODE REVIEW

**Comment by nealrichardson** [comment]
Merging since build is green (other than that flaky failure) and Wes needs this over in #6408

**Comment by wesm** [comment]
For my own understanding, how does `expect_equivalent` (respectively `expect_identical`) toggle the `check_metadata` flag?

**Comment by nealrichardson** [comment]
Internally `expect_equal` and `expect_equivalent` call the base R `all.equal` function, just with different values for `check.attributes`. I extended the `all.equal` method for arrow objects to pass that to `check_metadata`: https://github.com/apache/arrow/pull/6459/files#diff-cace654e27e925d238b03d553da440bdR99

**Comment by wesm** [comment]
I see, thank you =) I guess R's attributes is similar to Arrow's metadata fields, so that makes sense

**Pull request closed without merging**
