### PR TITLE
ARROW-11256: [Packaging][Linux] Don't buffer packaging output

### PR DESCRIPTION
**Pull request by kou**
It avoids timeout error on Travis CI.

### CODE REVIEW

**Comment by kou** [comment]
@github-actions crossbow submit centos-7-aarch64

**Comment by kou** [comment]
@github-actions crossbow submit -g linux-arm64

**Comment by kou** [comment]
@github-actions crossbow submit debian-buster-arm64

**Comment by kou** [comment]
@github-actions crossbow submit centos-8-aarch64

**Comment by kou** [comment]
@github-actions crossbow submit -g linux-arm64

**Review by kszucs — APPROVED** [review]
Thanks Kou! The travis build is unrelated, so merging.

**Pull request closed without merging**
