### PR TITLE
ARROW-1217: [GLib] Add GInputStream based arrow::io::RandomAccessFile

### PR DESCRIPTION
**Pull request by kou**
`GInputStream` provides many input types such as local file, in memory data, socket including TLS support. It's useful to read data from many data sources.

### CODE REVIEW

**Review by wesm — APPROVED** [review]
+1, this looks very useful. I will await merging pending a fixed build

**Comment by kou** [comment]
Oops. I needed to update dependencies in Go example.
I've pushed a commit. It will fix the build failure.

**Comment by kou** [comment]
Umm... I need more works...

**Comment by wesm** [comment]
Thanks @kou, merging

**Comment by kou** [comment]
Thanks.
I realized that we should use `XXX_get_raw()` name for function that returns wrapped object for consistency. I'll fix it.

**Pull request closed without merging**
