### PR TITLE
WIP: [Release] Verify release-13.0.0-rc1

### PR DESCRIPTION
**Pull request by kou**
PR to verify Release Candidate

### CODE REVIEW

**Comment by kou** [comment]
@github-actions crossbow submit  --group verify-rc-source --param release=13.0.0 --param rc=1

**Comment by raulcd** [comment]
Revision: cbf8e418212de9a40e35375fa7b97afd2b0b2cf0

Submitted crossbow builds: [ursacomputing/crossbow @ release-13.0.0-rc1-0](https://github.com/ursacomputing/crossbow/branches/all?query=release-13.0.0-rc1-0)

|Task|Status|
|----|------|
|almalinux-8-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc1-0-github-almalinux-8-amd64)|
|almalinux-8-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc1-0-github-almalinux-8-arm64)|
|almalinux-9-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc1-0-github-almalinux-9-amd64)|
|almalinux-9-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc1-0-github-almalinux-9-arm64)|
|amazon-linux-2023-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc1-0-github-amazon-linux-2023-amd64)|
|amazon-linux-2023-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc1-0-github-amazon-linux-2023-arm64)|
|centos-7-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc1-0-github-centos-7-amd64)|
|centos-8-stream-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc1-0-github-centos-8-stream-amd64)|
|centos-8-stream-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc1-0-github-centos-8-stream-arm64)|
|centos-9-stream-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc1-0-github-centos-9-stream-amd64)|
|centos-9-stream-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc1-0-github-centos-9-stream-arm64)|
|conan-maximum|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc1-0-github-conan-maximum)|
|conan-minimum|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc1-0-github-conan-minimum)|
|debian-bookworm-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/5668052402/job/15357986056)|
|debian-bookworm-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/5668053646/job/15357989311)|
|debian-bullseye-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc1-0-github-debian-bullseye-amd64)|
|debian-bullseye-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc1-0-github-debian-bullseye-arm64)|
|debian-trixie-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc1-0-github-debian-trixie-amd64)|
|debian-trixie-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc1-0-github-debian-trixie-arm64)|
|java-jars|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc1-0-github-java-jars)|
|nuget|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc1-0-github-nuget)|
|python-sdist|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc1-0-github-python-sdist)|
|r-binary-packages|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/5668055811/job/15357995234)|
|test-ubuntu-default-docs|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/5668056025/job/15357995936)|
|ubuntu-focal-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc1-0-github-ubuntu-focal-amd64)|
|ubuntu-focal-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/5668056766/job/15357998482)|
|ubuntu-jammy-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc1-0-github-ubuntu-jammy-amd64)|
|ubuntu-jammy-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/5668052055/job/15357985287)|
|ubuntu-lunar-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc1-0-github-ubuntu-lunar-amd64)|
|ubuntu-lunar-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc1-0-github-ubuntu-lunar-arm64)|
|wheel-clean|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc1-0-github-wheel-clean)|
|wheel-macos-big-sur-cp310-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/5668055191/job/15357993494)|
|wheel-macos-big-sur-cp311-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/5668051713/job/15357984660)|
|wheel-macos-big-sur-cp38-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/5668055489/job/15357994375)|
|wheel-macos-big-sur-cp39-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc1-0-github-wheel-macos-big-sur-cp39-arm64)|
|wheel-macos-mojave-cp310-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc1-0-github-wheel-macos-mojave-cp310-amd64)|
|wheel-macos-mojave-cp311-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc1-0-github-wheel-macos-mojave-cp311-amd64)|
|wheel-macos-mojave-cp38-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/5668053965/job/15357990284)|
|wheel-macos-mojave-cp39-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/5668053120/job/15357988074)|
|wheel-manylinux-2-28-cp310-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc1-0-github-wheel-manylinux-2-28-cp310-amd64)|
|wheel-manylinux-2-28-cp310-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/5668057738/job/15358001401)|
|wheel-manylinux-2-28-cp311-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/5668059167/job/15358005573)|
|wheel-manylinux-2-28-cp311-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/5668057223/job/15357999857)|
|wheel-manylinux-2-28-cp38-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc1-0-github-wheel-manylinux-2-28-cp38-amd64)|
|wheel-manylinux-2-28-cp38-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc1-0-github-wheel-manylinux-2-28-cp38-arm64)|
|wheel-manylinux-2-28-cp39-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc1-0-github-wheel-manylinux-2-28-cp39-amd64)|
|wheel-manylinux-2-28-cp39-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc1-0-github-wheel-manylinux-2-28-cp39-arm64)|
|wheel-manylinux-2014-cp310-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc1-0-github-wheel-manylinux-2014-cp310-amd64)|
|wheel-manylinux-2014-cp310-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/5668058515/job/15358003803)|
|wheel-manylinux-2014-cp311-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc1-0-github-wheel-manylinux-2014-cp311-amd64)|
|wheel-manylinux-2014-cp311-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc1-0-github-wheel-manylinux-2014-cp311-arm64)|
|wheel-manylinux-2014-cp38-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/5668058838/job/15358004662)|
|wheel-manylinux-2014-cp38-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc1-0-github-wheel-manylinux-2014-cp38-arm64)|
|wheel-manylinux-2014-cp39-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/5668052796/job/15357987113)|
|wheel-manylinux-2014-cp39-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/5668061846/job/15358012415)|
|wheel-windows-cp310-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/5668060522/job/15358008893)|
|wheel-windows-cp311-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/5668054649/job/15357991925)|
|wheel-windows-cp38-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/5668054357/job/15357991185)|
|wheel-windows-cp39-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/5668056977/job/15357999097)|

**Comment by raulcd** [comment]
Revision: cbf8e418212de9a40e35375fa7b97afd2b0b2cf0

Submitted crossbow builds: [ursacomputing/crossbow @ release-13.0.0-rc1-1](https://github.com/ursacomputing/crossbow/branches/all?query=release-13.0.0-rc1-1)

|Task|Status|
|----|------|
|test-ubuntu-default-docs|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc1-1-github-test-ubuntu-default-docs)|

**Comment by raulcd** [comment]
Revision: cbf8e418212de9a40e35375fa7b97afd2b0b2cf0

Submitted crossbow builds: [ursacomputing/crossbow @ release-13.0.0-rc1-2](https://github.com/ursacomputing/crossbow/branches/all?query=release-13.0.0-rc1-2)

|Task|Status|
|----|------|
|test-ubuntu-default-docs|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/5670240770/job/15364691346)|

**Comment by raulcd** [comment]
Closing this because we will be creating a new RC

**Comment by h-vetinari** [comment]
> Closing this because we will be creating a new RC

Any timeline for this? :)

(no pressure, just so that I know when I need to allocate a bit of time; talking about 13.0.0 GA)

**Comment by thisisnic** [comment]
> > Closing this because we will be creating a new RC
> 
> Any timeline for this? :)
> 
> (no pressure, just so that I know when I need to allocate a bit of time; talking about 13.0.0 GA)

I believe that the blocker for the creation of the next RC (and discussion about it) can be be found here: https://github.com/apache/arrow/issues/36892#issuecomment-1655445724

**Comment by raulcd** [comment]
Thanks @thisisnic !

@h-vetinari, as shared by @thisisnic I am waiting for some feedback on the issue above. I plan to start creating the RC tomorrow if I don't get any more info. Once the RC is created running all the verification tasks and creating binaries take a couple days + the vote itself which takes 2-3 more days, etc.

**Pull request closed without merging**
