### PR TITLE
ARROW-16585: [C++] Add support for absolute CMAKE_INSTALL_*DIR

### PR DESCRIPTION
**Pull request by kou**

### CODE REVIEW

**Comment by kou** [comment]
@github-actions crossbow submit -g nightly-packaging -g nightly-release -g nighlty-tests

**Comment by kou** [comment]
@github-actions crossbow submit -g nightly-packaging -g nightly-release -g nightly-tests

**Comment by kou** [comment]
+1

**Comment by alexshpilkin** [comment]
@kou Thank you for the quick fix!

**Comment by veprbl** [comment]
Why not just substitute `CMAKE_INSTALL_*DIR` -> `CMAKE_INSTALL_FULL_*DIR`?

**Comment by kou** [comment]
See the ARROW-16585's description:

> See “[Concatenating paths when building pkg-config files](https://github.com/jtojnar/cmake-snips#concatenating-paths-when-building-pkg-config-files)” for a thorough discussion of the problem and a suggested fix, or [KDE’s extra-cmake-modules](https://invent.kde.org/frameworks/extra-cmake-modules/-/blob/master/modules/ECMGeneratePkgConfigFile.cmake#L166) for a simpler approach.

**Comment by veprbl** [comment]
@kou Thanks. I've never came across this pkg-config feature.

**Pull request closed without merging**
