### PR TITLE
ARROW-10757: [Rust] [CI] Fix CI failures

### PR DESCRIPTION
**Pull request by nevi-me**
Fixes Ci failures by separating running tests, and discarding artefacts after testing
Also adds a separate test for `arrow` on stable.

Changes made:
* Reorder the Rust tests to test other modules without `arrow`, reducing test duplication
* Add stable toolchain test for the `arrow` crate, test it next to `feature "simd"`
* Clear the test artefacts before testing `arrow`, to reclaim some disk space
* Update nightly to `2020-11-24` so that the tests would get triggered

### CODE REVIEW

**Comment by nevi-me** [comment]
🤡 so the Rust CI won't run because no files have been changed. I'm going to bump the nightly to force things to move

**Comment by nevi-me** [comment]
The Python 3.5 failure is expected, Python 3.5 is being removed in another PR

**Review by paddyhoran — APPROVED** [review]
LGTM

**Review by jorgecarleitao — APPROVED** [review]
LGTM. Thanks!

**Pull request closed without merging**
