### PR TITLE
ARROW-12140: [C++][CI] Fix Valgrind failures in Grouper tests

### PR DESCRIPTION
**Pull request by pitrou**
Make sure no uninitialized bits remain in generated null bitmap.

### CODE REVIEW

**Comment by pitrou** [comment]
@bkietz Could take a quick look here?

**Comment by cyb70289** [comment]
Noticed this error in valgrind cpp CI. Just curious why I cannot reproduce it locally.

**Comment by pitrou** [comment]
It may depend on the Valgrind or compiler version. To reproduce CI results, it is advisable to use [archery](https://arrow.apache.org/docs/developers/archery.html) to trigger Docker-based builds (e.g. `archery buid conda-cpp-valgrind`).

**Review by westonpace — COMMENTED** [review]
LGTM.  I think I understand now the valgrind error, I'll repeat it here to check my understanding.  Since `validity` wasn't initialized then `BitUtil::SetBitTo` was applying operations like `x & 0x1` where `x` was undefined.  This would be OK if `SetBitTo` was applied to every bit in the byte.

It could be solved by initializing `validity` to 0 but this version is more efficient because it builds up a byte of data at a time (which can likely happen in registers / L1 / L2) and then writes over `validity` with the whole byte when finished.

As for the other changes, I will try and be more attentive and use `ARROW_VALGRIND` when writing future stress tests.

**Comment by westonpace** [comment]
@cyb70289 I had the same question.  I noticed a couple of differences in `conda-cpp-valgrind` and my build (it uses `-Og` instead of `-O0`) but even when I tried replicating these I didn't get the same output.

I did run Antoine's changes with `archery docker run conda-cpp-valgrind`.  This generates errors reliably on master for me but not on this branch.

**Comment by pitrou** [comment]
@westonpace Your understanding is right. Thanks!

**Comment by westonpace** [comment]
@cyb70289 Ah, figured it out.  The valgrind tests have jemalloc turned off and use the system allocator.  By turning off jemalloc I can reproduce the valgrind errors.

**Comment by pitrou** [comment]
Yes, some allocators can trip Valgrind.

**Pull request closed without merging**
