### PR TITLE
ARROW-13338: [C++][Dataset][R][Python] Default to async scanning

### PR DESCRIPTION
**Pull request by bkietz**

### CODE REVIEW

**Comment by bkietz** [comment]
Looks like this is dependent on ARROW-11782/ARROW-12288

**Comment by bkietz** [comment]
Also relevant: https://issues.apache.org/jira/browse/ARROW-12803

**Comment by pitrou** [comment]
I see that PR seems a bit stale. Was it forgotten somehow?

**Comment by westonpace** [comment]
> I see this PR seems a bit stale. Was it forgotten somehow?

@pitrou 

It's blocked at the moment.  I'll comment on the JIRA.

**Pull request closed without merging**
