### PR TITLE
ARROW-4774: [C++] Fix FileWriter::WriteTable segfault

### PR DESCRIPTION
**Pull request by fsaintjacques**
FileWriter expects a well-formed Table where all columns are of equal
lengths.

- WriteTable checks if the table is valid
- Python ensure that a table is valid before wrapping it

### CODE REVIEW

**Comment by fsaintjacques** [comment]
I'm not sure if the ruby failure is related, at first sight, it doesn't seem so. @kou?

**Review by wesm — APPROVED** [review]
+1. The `Validate` call is not too expensive but it does check the schema types match the column types which isn't free, so we should keep in mind

**Comment by wesm** [comment]
The Ruby failure is not related; I think I saw that in a different build elsewhere

**Comment by kou** [comment]
It was reported at https://github.com/apache/arrow/pull/3810#issuecomment-470608578 .
I could reproduce this with the latest GLib. It was released at 2019-03-04.
It seems that we can resolve this by releasing a new version of Ruby bindings of GLib. I'll do it soon.

**Comment by kou** [comment]
I've fixed.

**Comment by sgalla1** [comment]
If I understand correctly, this fix will provide better checking to make sure the tables are equal length. So this means it will not accept a table that has nested arrays? See https://stackoverflow.com/questions/54985512/pyarrow-write-nested-array-to-parquet

**Comment by xhochy** [comment]
@sgalla1 Nested arrays are support as long as on the most upper nesting level the length of the array is equal to all other arrays in the table.

**Pull request closed without merging**
