### PR TITLE
ARROW-2238: [C++] Detect and use clcache in cmake configuration

### PR DESCRIPTION
**Pull request by pitrou**

### CODE REVIEW

**Comment by pitrou** [comment]
Example AppVeyor build at https://ci.appveyor.com/project/pitrou/arrow/build/1.0.155

**Comment by pitrou** [comment]
The failure at https://ci.appveyor.com/project/pitrou/arrow/build/1.0.155/job/q31movster4v84d9 shows this can lead to inconsistencies or errors: cmake first tries to detect the compller from user-supplied information (generator, environment variables), then the clcache setting overrides that detection.

Either we add logic to try and avoid such errors, or we simply let people override CC/CXX if they want to use clcache (statu quo).

**Comment by pitrou** [comment]
Also I'm not sure whether we have a Windows developer on board; I'm merely launching a VM from time to time but otherwise work on Ubuntu :-)

**Comment by wesm** [comment]
@MaxRis can take a look. How does the error you linked to arise?

**Comment by pitrou** [comment]
I think that's because `CMAKE_CXX_COMPILER` forcefully overrides the compiler command. When using the Visual Studio generators, you traditionally don't need to run `vcvarsall.bat` (presumably because cmake would hardcode the full compiler path), but then `clcache` fails finding the compiler.

So it's possible that calling `vcvarsall.bat` is all that's needed here. But that would also change the workflow may be accustomed to.

**Comment by MaxRis** [comment]
@pitrou I will check, thanks

**Comment by MaxRis** [comment]
@pitrou it seems that we already try to use `ccache` [there](https://github.com/apache/arrow/blob/master/cpp/CMakeLists.txt#L68) if it's presented. I'm wondering if it will make more sense to refactor referenced lines and optionally use `clcache` for MSVC?
Also, probably, usage of RULE_LAUNCH_COMPILE and RULE_LAUNCH_LINK should solve issue with selected compiler overwrite. 
And it seems that starting from Cmake 3.4.0 [CXX_COMPILER_LAUNCHER](https://cmake.org/cmake/help/v3.4/prop_tgt/LANG_COMPILER_LAUNCHER.html#prop_tgt:%3CLANG%3E_COMPILER_LAUNCHER) variable is available, but we stick to CMake of min ver 3.2

**Comment by pitrou** [comment]
> Also, probably, usage of RULE_LAUNCH_COMPILE and RULE_LAUNCH_LINK should solve issue with selected compiler overwrite.

Last I tried it seemed it didn't work. I might give it a try again...

**Comment by MaxRis** [comment]
I will try on my end as well

**Comment by MaxRis** [comment]
@pitrou, do you have an idea how to verify that clcache.exe was really used during compilation? I've tried with it and without, but I can't find any difference in output/produced results.

**Comment by pitrou** [comment]
@MaxRis running `clcache -s` gives you aggregate statistics for the cache, so you can see (by the number of hits and misses) if clcache was used at all.

**Comment by MaxRis** [comment]
@pitrou thanks!

**Comment by MaxRis** [comment]
update: it seems that current solution `set(CMAKE_CXX_COMPILER ${CLCACHE_FOUND})` works only with `NMake Makefiles` generator, but clcache doesn't get called if `Visual Studio 14 2015 Win64` or similar is used.

**Comment by pitrou** [comment]
clcache works best with Ninja or NMake (*). My suggestion here would be to recommend Ninja + clcache for best build performance. The other concern, though, is to avoid breaking existing builds for those who prefer other generators (e.g. Visual Studio).

(*) See the following links:
- https://github.com/frerich/clcache/issues/273#issuecomment-354623452
- https://github.com/frerich/clcache/wiki/Integration#integration-for-visual-studio

**Comment by MaxRis** [comment]
@pitrou it should be fine to set `set(CMAKE_CXX_COMPILER ${CLCACHE_FOUND})` only if Generator defined as `Ninja` or `NMake Makefiles`. This possibly also will resolve current Appveyor failure. What do you think?

**Comment by pitrou** [comment]
@MaxRis that sounds ok to me.

**Comment by MaxRis** [comment]
@pitrou I will check if that resolves Appveyor build failure and let you know, thanks

**Comment by MaxRis** [comment]
@pitrou [here ](https://github.com/apache/arrow/commit/17ee3121ff6843dd5749aa9d461abbad953cf5ef)it's changes to solve Jenkins failure as discussed
[Passed Appveyor build](https://ci.appveyor.com/project/MaxRisuhin/arrow/build/job/8lnl668fbpadl84s)

**Comment by pitrou** [comment]
@MaxRis thanks! I'll integrate it in my PR.

**Comment by pitrou** [comment]
Actually, it doesn't look right. Here you see that the cache wasn't looked up at all:
https://ci.appveyor.com/project/MaxRisuhin/arrow/build/1.0.253/job/puv48c73yknmel34#L3175

**Comment by MaxRis** [comment]
@pitrou sorry, haven't checked in such manner. I have checked only that `clcache` was applied as compiler replacement with additional output https://ci.appveyor.com/project/MaxRisuhin/arrow/build/1.0.253/job/e8v49o78ku8cltur#L418 ... and also have seen that with NMake Makefiles generator `clcache` is used in local builds. Will try to figure out why it doesn't work in Appveyor env.

**Comment by MaxRis** [comment]
Hey @pitrou , could you please check logs of last passed build ( https://ci.appveyor.com/project/ApacheSoftwareFoundation/arrow/build/1.0.5601 ). For some reasons `clcache` statistics shows that it was used, by my opinion, fine. Could you please verify? Thanks

**Comment by pitrou** [comment]
@MaxRis, yes, it looks fine... And the build times are ok too (without cache, the total duration would probably be much more than 45 minutes).

**Comment by MaxRis** [comment]
Great! Should be fine to go with these changes, thanks!

**Comment by xhochy** [comment]
@MaxRis @pitrou This also looks fine from my side but as you both are more qualified on that matter: Is this ready to be merged?

**Comment by pitrou** [comment]
@xhochy, yes, it's ready for merging.

**Review by wesm — APPROVED** [review]
+1

**Pull request closed without merging**
