### PR TITLE
ARROW-5253: [C++] Fix snappy external build

### PR DESCRIPTION
**Pull request by fsaintjacques**
CMAKE_INSTALL_LIBDIR is not propagated thus fails on systems that uses
`lib64` (alpine and possibly redhat derivatives).

### CODE REVIEW

**Review by xhochy — APPROVED** [review]
+1, LGTM

**Comment by kszucs** [comment]
@xhochy You can check out the tests at http://nashville.ursalabs.org:4100/#/builders/1

**Comment by wesm** [comment]
@kszucs how do I read the build outputs, is the most recent build 85 the one to look at?

**Comment by fsaintjacques** [comment]
Bad link:

http://nashville.ursalabs.org:4100/#/builders/1/builds/80

**Review by wesm — APPROVED** [review]
Cool. +1

**Pull request closed without merging**
