### PR TITLE
ARROW-14220: [C++] Missing ending quote in thirdpartyversions

### PR DESCRIPTION
**Pull request by jonkeane**

### CODE REVIEW

**Comment by jonkeane** [comment]
@github-actions crossbow submit test-r-offline-maximal

**Review by nealrichardson — APPROVED** [review]
CI failures on mac seem unrelated; @jonkeane can you write up a jira for those if there isn't already one?

**Comment by jonkeane** [comment]
Here's the issue for that one: https://issues.apache.org/jira/browse/ARROW-14225

I'll merge this now since it's no worse than what's going on in the main branch.

**Comment by kou** [comment]
Oh... Thanks!

**Pull request closed without merging**
