### PR TITLE
[CI][Python] Try Travis-CI fix for missing setuptools

### PR DESCRIPTION
**Pull request by pitrou**

### CODE REVIEW

**Comment by pitrou** [comment]
Seems to fix the "missing setuptools" issue, but builds fail later. @kou

**Comment by kiszk** [comment]
According to [this](https://stackoverflow.com/questions/55786898/standard-init-linux-go190-exec-user-process-caused-exec-format-error-when-ru), shebang may be missing.

**Comment by pitrou** [comment]
Is this a new issue? It worked before. Also, in which file would the shebang be missing?

**Comment by kiszk** [comment]
Good point. you are right. When I visited travis-ci forum, I found the interesting [post](https://travis-ci.community/t/arm64-builds-are-not-being-provisioned-with-the-correct-bash-version/9978).

The same situation occurs in our environment...
[good](https://travis-ci.org/github/apache/arrow/jobs/728153988#L51)
[not good](https://travis-ci.org/github/apache/arrow/jobs/729889055#L38)

**Comment by pitrou** [comment]
It looks like this isn't necessary anymore.

**Pull request closed without merging**
