### PR TITLE
ARROW-16881: [Gandiva][C++] Fix castINTERVALYEAR implementation

### PR DESCRIPTION
**Pull request by Johnnathanalmeida**
Fix error in LLVM where didn't find these two functions.

Fix regex to allow negative digits for Interval Year.

### CODE REVIEW

**Comment by Johnnathanalmeida** [comment]
@github-actions crossbow submit java-jars

**Comment by Johnnathanalmeida** [comment]
@github-actions crossbow submit java-jars

**Comment by Johnnathanalmeida** [comment]
@github-actions crossbow submit java-jars

**Comment by Johnnathanalmeida** [comment]
@github-actions crossbow submit java-jars

**Comment by Johnnathanalmeida** [comment]
@github-actions crossbow submit java-jars

**Comment by Johnnathanalmeida** [comment]
@github-actions crossbow submit java-jars

**Comment by Johnnathanalmeida** [comment]
@github-actions crossbow submit java-jars

**Review by siddhantrao23 — APPROVED** [review]
+1, looks good to me

**Pull request merged**
