### PR TITLE
ARROW-6050: [Java] Update out-of-date java/flight/README.md

### PR DESCRIPTION
**Pull request by tianchen92**
Related to [ARROW-6050](https://issues.apache.org/jira/browse/ARROW-6050).

### CODE REVIEW

**Comment by pitrou** [comment]
@lihalite Would you like to take a look?

**Review by ghost — APPROVED** [review]
This is fine, but now that we do have Python bindings, we should either recommend those, or explicitly state that these are instructions to generate raw gRPC bindings for development use.

**Comment by tianchen92** [comment]
@lihalite Thanks for your review, not familiar with this. Could we get this merged first or should add more information?

**Comment by lihalite** [comment]
@tianchen92 let's get this merged first.

**Pull request closed without merging**
