### PR TITLE
ARROW-8952: [C++] WIP Support for textual, JSON schema representation

### PR DESCRIPTION
**Pull request by chrish42**
Draft pull request for discussion of possible text schema for Arrow, using Flatbuffers' existing serialization to JSON feature (via `flatbuffers::GenerateText()`, etc.) on the Arrow schema. Not intented to necessarily hint at what the final code would look like, but to allow people to discuss the general approach and see examples of the format.

This approach has the advantages of not introducing any new dependencies, and reusing existing Flatbuffers for much of the feature.

Once there is agreement on this approach, I can then polish this into a mergeable state. In the meantime, the (temporary) `arrow-schema` program takes a hard-coded schema, and outputs the (proposed) corresponding JSON, so people can see what the text schemas would look like with this proposal.

As an example, the following Arrow schema definition:
```
  std::vector<std::shared_ptr<arrow::Field>> schema_vector = {
    arrow::field("id", arrow::int64()),
    arrow::field("cost", arrow::float64()),
    arrow::field("cost_components", arrow::list(arrow::float64()))};
  auto schema = arrow::Schema(schema_vector);
```
translates to:
```
{
  fields: [
    {
      name: "id",
      nullable: true,
      type_type: "Int",
      type: {
        bitWidth: 64,
        is_signed: true
      },
      children: [

      ]
    },
    {
      name: "cost",
      nullable: true,
      type_type: "FloatingPoint",
      type: {
        precision: "DOUBLE"
      },
      children: [

      ]
    },
    {
      name: "cost_components",
      nullable: true,
      type_type: "List",
      type: {
      },
      children: [
        {
          name: "item",
          nullable: true,
          type_type: "FloatingPoint",
          type: {
            precision: "DOUBLE"
          },
          children: [

          ]
        }
      ]
    }
  ]
}
```

Seems pretty straightforward to read for anyone who knows about Arrow's data representation to me. A bit verbose for the simpler cases, however. Maybe we would need to add a couple extra keys at the top level... Versioning for the text schema? Something that says this is an Arrow schema? Or maybe that's not necessary.

### CODE REVIEW

**Comment by emkornfield** [comment]
> Seems pretty straightforward to read for anyone who knows about Arrow's data representation to me. A bit verbose for the simpler cases, however. Maybe we would need to add a couple extra keys at the top level... Versioning for the text schema? Something that says this is an Arrow schema? Or maybe that's not necessary.

I would be prefer not to add anything that the flatbuffer parser can't parse.  Feature versioning is something I've been meaning to make a proposal for but I think that might be different then what you are thinking of.  I'd be OK with having this as a non-official function (probably move out of IPC namespace) to clarify this is only an convenience in the C++ (and binding code base).  I think @wesm had some concerns in general about exposing this.

**Comment by chrish42** [comment]
I'd also prefer not to add anything to the JSON, but I was raising that option because there were concerns about maintaining compatibility in the past when I initially raised this, so that would be a way to mitigate that. One way to add extra fields while still leaving all the parsing to the Flatbuffers library would be to create a new Flatbuffers schema with said additional fields. But the first choice would be to make sure that Flatbuffers won't be changing that format under Arrow's feet, and so not need those extra fields.

Also, agreed about this not belonging in the ipc namespace. It should probably live closer to the Schema C++ Arrow class. But we can discuss all that more once there's agreement on the approach and I rework the pull request to be mergeable. I'm not sure what you mean by non-official function, though. Could you expand on that? For me, the goal is to have a (user-readable, non-code) way of expressing an Arrow schema that's supported across versions. I get that we'll get there progressively, however.

**Comment by emkornfield** [comment]
>  I'm not sure what you mean by non-official function, though. Could you expand on that?
Sorry, I meant not something that is supported officially in the IPC format specification (i.e. other languages need to support reading the JSON).

**Comment by chrish42** [comment]
@wesm @emkornfield What would be the next step to move this forward? For me the next steps would be:
1. Get agreement from key Arrow folks (anyone else than you two?) that this is a reasonable way forward.
2. Create tracking issue on Arrow's JIRA
3. Decide on where this would live API-wise (not in `arrow::ipc`, I agree... somewhere close to the Schema class?)
4. Polish current pull request to be able to read and write Schema object from its JSON representation.

Are these the right things in the right order? Thanks!

**Comment by emkornfield** [comment]
@chish42 that seems like the right order.

For #1 given that you discussed it on the mailing list and people have been CCed here, since no one has objected I think we can move forward.  (lazy consensus).

Yes, please create a JIRA for tracking purposes (and it will give one more bump to the thread of anybody monitoring JIRA has any hard disagreements/input).

For #3 I would have to think about it a bit, but maybe additional methods on Schema or functions defined in type.h 

4. yes, please maybe mark the header title here as WIP until you feel comfortable for a review.

**Comment by chrish42** [comment]
Cool. Thank you! I've created [https://issues.apache.org/jira/browse/ARROW-8952](ARROW-8952).

New methods on the Schema class seem a natural place where to put this, so I'll add the load/save JSON schema functionality there. (It'll be easy to relocate elsewhere later anyways if desired.)

**Comment by chrish42** [comment]
What would be a good testing strategy for this, actually? This is mostly calling `CreateFlatBuffersFromSchema()` and then `SaveFlatBuffersToJson()` (not the actual function names :-) ) and those are already tested, so I don't think I need to add a ton of tests on top of those. Would the following sound good enough:

1. Some tests that Schemas round-trip through load&save intact
2. Loading some pre-defined schemas from JSON, and comparing them to a Schema object constructed via code

Thoughts? If there are relevant pieces of the code for testing schemas that I should be looking at, pointers to that would be appreciated.

**Comment by emkornfield** [comment]
Both of those sound like good strategies to me.

**Comment by chrish42** [comment]
Okay, even more work-in-progress than the usual, but pushing here to ask for some CMake advice. Basically, I've moved things to a member function of the Schema class (that works). Then I tried to get rid of the hack to load the Flatbuffer Schema.fbs definition, by embedding a copy in a string at compile time, via a flatbuffer_schema.cc.in file, and then linking that in.

Unfortunately, I clearly don't know enough about CMake. The corresponding flatbuffer_schema.cc does get created, with the right content. However, it never gets compiled into an object file, or included in the list of files to link in libarrow.a, etc. It seems like the build system has just chosen to silently ignore that file. Because I only get an error about a missing symbol at link time (instead of "cannot file this object file", say). Anyone who's better at CMake than me?

Otherwise, we can also discuss the name and signature of the member functions: `ToJson` and `FromJson` good? How do they report errors? For the rest, however, please ignore until that "use a schema string" piece is working. Thanks.

**Comment by emkornfield** [comment]
@chish42 I don't have a lot of expertise in CMake.  Not sure if it helps but we've already checked in generated flatbuffers header files checked in https://github.com/apache/arrow/blob/master/cpp/src/generated/Schema_generated.h

**Comment by chrish42** [comment]
@emkornfield I had checked earlier, and those generated files didn't have the actual Flatbuffers schema for the `Schema` class in them, which is what is needed to generate a `flatbuffers::Parser` instance. But I had another look, and I found some support to serialize a binary version of that definition with `flatc` which can then be loaded in a `Parser` class instance. I assume that's also faster than parsing the .fbs text file, so better all around.

Next step is the error handling. And then the opposite direction, with `FromJson()`. (I put that as a static class method instead of a constructor to be able to report errors more easily. Let me know if you feel that's not the right call.)

**Comment by chrish42** [comment]
Work in progress on `Schema:FromJson()`. Doesn't work currently. The FlatBuffer structure generated has 0 fields, even though the JSON data has some. Probably passing the wrong pointer somewhere... If you see my mistake, please comment here. Otherwise, I'll come back to this after having slept on it. :-D

**Comment by emkornfield** [comment]
@chrish42 are you still working on this?  Maybe close and then reopen the PR once you have the bandwidth to get something working?

**Comment by chrish42** [comment]
Hiya folks. I am still working on this somewhat regularly. I have code for ToJson too... except I get a crash there, and most of the work is understanding Flatbuffers and why that code is crashing. I'll at least push a new version of the code next week with that (thought I had already done so), after I've merged with the latest changes. Basically, the `GetSchema()` function in `metadata_internal.cc` doesn't seem to be an exact inverse of the `SchemaToFlatbuffer()` function in that same file. But there were some improvements in that area (seeing a `FieldToFlatbufferVisitor` class there, for one), and I understsand Flatbuffers and the Arrow code a bit better now, so maybe I'll be able to figure out it. Either way, I'll push my latest next week, and you folks can have a look. But nothing's been happening on the pull request because almost all the work has been debugging.

**Comment by chrish42** [comment]
@emkornfield Here's the latest version, rebased on the latest Arrow code (been some changes with DictMemo -> DictFeidlMapper, etc.).  There are `Schema::FromJson()` and `Schema::ToJson()` member functions. If you compile things, you'll also get a temporary `arrow-schema` executable, that you can run to exercise those two member functions.

The problem I'm struggling with is in the `Schema::FromJson()` member function (`ToJson()` works fine). I'm initializing a FlatBuffers parser with the schema for Arrow's `Schema`, then using it to parse the Json representation of an Arrow Schema. However, the Flatbuffers binary buffer produced by that isn't what `arrow::ipc::internal::GetSchema()` expects, because I get a crash there. So that's where I'm at currently, debugging and trying to figoure out Flatbuffers, to understand what's happening. Hence the not much happening on the "adding / changing lines of code" side, and the slow progress.

If it was possible to `@`-summon someone who knows this part of the Arrow code well, I'm guessing the problem will be obvious to them. That would be really lovely, and probably save me a bunch of time. Otherwise, I'll continue working on it, but progress will be slow, because I can only work on this occasionally, and I don't know Flatbuffers or this part of the code well. (And Flatbuffers problems are kindof a pain to debug, as I'm figuring out.)

**Comment by emkornfield** [comment]
I'll try to take a look later this week (please ping me if I forget).

**Comment by chrish42** [comment]
@emkornfield Ping, as requested. 😀 Thanks! It's really not a lot of code. too. (Since Flatbuffers is doing the JSON <-> Flatbuffer part.)

**Comment by emkornfield** [comment]
thanks for the reminder I should be able to look tonight/over the weekend.

**Comment by emkornfield** [comment]
sorry for delay, will try to look tomorrow.

**Comment by emkornfield** [comment]
sorry, will try to look at this soon.

**Comment by emkornfield** [comment]
Sorry for the delay hope to have some time this week.

**Comment by emkornfield** [comment]
ugh, sorry I never got to this.  will try to look this week hopefully.

**Pull request closed without merging**
