### PR TITLE
GH-44846: [CI][C++] Revert change for maybe uninitialized variable to fix thread sanitizer failure

### PR DESCRIPTION
**Pull request by raulcd**
### Rationale for this change

The thread sanitizer build was failing since the original was merged: https://github.com/apache/arrow/commit/2e1ddf5069731d2b908b18d851b2389973cc988c

### What changes are included in this PR?

Revert change

### Are these changes tested?

Via CI

### Are there any user-facing changes?

No

* GitHub Issue: #44846

### CODE REVIEW

**Comment by raulcd** [comment]
@github-actions crossbow submit test-ubuntu-24.04-cpp-thread-sanitizer

**Comment by raulcd** [comment]
I can't reproduce locally, I am just trying to understand if a previous commit is the culprit of the issue.

**Comment by raulcd** [comment]
@pitrou @kou this seems to be the culprit for the thread sanitizer failures. Should I revert the change?

**Comment by pitrou** [comment]
I don't know, I don't understand how those TSan failures could be related to the change being reverted.

**Comment by pitrou** [comment]
Also, I don't know why CI was mostly skipped on this PR, did you put "WIP" in the PR title at some point?

**Comment by raulcd** [comment]
yes, I was initially trying to understand if this was the issue or not, that's why I used WIP. I've just rebased with a new commit message to trigger CI again.

**Comment by pitrou** [comment]
Ok, I think the original commit just surfaces a lingering bug in `ConcurrentQueue`. `UnsyncFront` is simply not safe, as it calls `deque::front()` which can be implemented in terms of `deque::begin()`, but a concurrent call to `deque::push_back()` is specificed as invalidating all iterators.

**Comment by raulcd** [comment]
Thanks @pitrou then let me close this PR as the change is good and it surfaced the bug. I will add your comment to the thread sanitizer issue

**Pull request closed without merging**
