### PR TITLE
ARROW-3930: [C++] Avoid using Mersenne Twister for random test data

### PR DESCRIPTION
**Pull request by pitrou**
Mersenne Twister is much slower than the default C++ random engine (at least on GNU libstdc++), and we're not looking for very good statistical properties either.

### CODE REVIEW

**Comment by pitrou** [comment]
Here the user CPU time for the entire test suite goes down from 45 seconds to 30 seconds. Unfortunately there is also a regression in `parquet-arrow-reader-writer-test` (in `TestArrowReadWrite.ListLargeRecords`, which already has shown data-dependent fragility in the past).

**Comment by wesm** [comment]
I can look into the broken test

**Comment by wesm** [comment]
I can repro the failure on Ubuntu 14.04. It's times like these that https://issues.apache.org/jira/browse/ARROW-517 would be a debugging lifesaver

**Comment by fsaintjacques** [comment]
LGTM

**Comment by wesm** [comment]
Sigh, there's problems with the last record in the row group again. I thought I had got the proper fix in PARQUET-1308 but I guess not. I'm working on it in

https://github.com/wesm/arrow/tree/ARROW-3930-debugging

I'll try to push a fix here before end of day

**Comment by wesm** [comment]
OK, I believe I've tracked the problem down to an issue converting the definition levels into a validity bitmap. The values become different at the 998th record

```
998
[
  [
    6,
    72,
    94,
    null,
    31,
    39,
    64,
    29,
    null,
    null,
    null,
    null,
    null
  ]
][
  [
    6,
    72,
    94,
    null,
    31,
    39,
    64,
    29,
    11,
    10,
    18,
    92,
    72
  ]
]
```

The latter is the correct record

The record reader has the following data buffered:

```
(gdb) p reader->DebugPrintState()
def levels: 3 3 3 2 3 3 3 3 3 3 3 3 3 
rep levels: 0 1 1 1 1 1 1 1 1 1 1 1 1 
values: 6 72 94 26 31 39 64 29 11 10 18 92 72 
``

The validity bitmap, which is computed in https://github.com/apache/arrow/blob/master/cpp/src/parquet/arrow/record_reader.cc#L419, is wrong. 

BTW the state of nested data in Parquet is reaching a crisis state. Once we get the 0.12 release is done I'm going to stop working on anything else until we can read and write nested data to satisfaction, and we can make this code a lot cleaner. Right now it's a bit of a pile of hacks (at least the parts I've worked on) so very difficult to work on

**Comment by wesm** [comment]
OK, I found the bug. Will push fix + test shortly and then merge this if all looks good

**Comment by wesm** [comment]
Fixed. I'll split my change into a new PR

**Comment by pitrou** [comment]
It seems there are Valgrind issues with Parquet now:
https://travis-ci.org/apache/arrow/jobs/463103392#L3549

Also I'm not sure why the Brotli tests have started failing:
https://travis-ci.org/apache/arrow/jobs/463103394#L1202

**Comment by wesm** [comment]
Awesome. I can look into the valgrind issue

**Comment by wesm** [comment]
Working on this valgrind issue. Haven't figured it out yet

**Comment by wesm** [comment]
@xhochy there seems to be a mishandling of values vs. definition/repetition levels on the statistics update path. 

https://github.com/apache/arrow/blob/master/cpp/src/parquet/column_writer.cc#L720

What is being passed in here is actually the number of definition levels, which is not necessarily equal to the number of spaced values, depending on the realization of the data. In fact, here are the 14 definition levels that caused this error here:

```
(gdb) p def_levels[0]
$74 = 1
(gdb) p def_levels[1]
$75 = 3
(gdb) p def_levels[2]
$76 = 3
(gdb) p def_levels[3]
$77 = 3
(gdb) p def_levels[4]
$78 = 3
(gdb) p def_levels[5]
$79 = 3
(gdb) p def_levels[6]
$80 = 3
(gdb) p def_levels[7]
$81 = 2
(gdb) p def_levels[8]
$82 = 3
(gdb) p def_levels[9]
$83 = 2
(gdb) p def_levels[10]
$84 = 2
(gdb) p def_levels[11]
$85 = 3
(gdb) p def_levels[12]
$86 = 3
(gdb) p def_levels[13]
$87 = 3
```

So the first definition level indicates (I think!) that we have a null list. 

```
def level 0: outer list null
def level 1: outer list value slot null
def level 2: inner list value null
def level 3: inner list value not null
```

This supports the thesis why we didn't see this issue before, because the data is random, so we just didn't hit this case...

I think I am able to fix this. All of this code is going to need a significant reworking when get to reading and writing arbitrary nested data sets

**Comment by wesm** [comment]
BTW I had to look this up but you can attach gdb to a valgrind session to be able to inspect stack frames when there is a valgrind error. the incantation in this case is

```
valgrind --vgdb=yes --vgdb-error=0 --tool=memcheck debug/parquet-arrow-reader-writer-test --gtest_filter=*TableWithChunkedColumns*
```

it will print instructions for attaching gdb to the process

**Comment by wesm** [comment]
I'm scratching my head a bit about what a useful unit test for this would look like. If you'd like a deterministic unit test that reproduces the issue I can try to create something now that I understand the underlying cause

**Comment by fsaintjacques** [comment]
Can you generate a parquet file with the schema and some rows, then add it to parquet-data? Won't be a unit test, but an integration test is better than nothing.

**Comment by wesm** [comment]
I will add a unit test -- the definition levels that triggered the bug are above

**Comment by wesm** [comment]
A bit annoying to reproduce but that did it. I'm going to split the Parquet changes into a separate patch so it will show up in the changelog

**Comment by wesm** [comment]
OK so merge https://github.com/apache/arrow/pull/3114 once that looks good, then rebase and merge this branch. I'm headed to bed but if the builds look good go right ahead

**Review by wesm — APPROVED** [review]
+1. The build failure is the Homebrew timeout in the Ruby builds we've been seeing a lot lately

**Pull request closed without merging**
