### PR TITLE
ARROW-11452: [Rust] Fix issue with Parquet Arrow reader not following type path

### PR DESCRIPTION
**Pull request by maxburke**
Not sure where the test data file should go, but I've attached it.

[structs.parquet.zip](https://github.com/apache/arrow/files/5906689/structs.parquet.zip)

### CODE REVIEW

**Comment by kou** [comment]
We use https://github.com/apache/parquet-testing for test data.
Cc: @pitrou

**Comment by maxburke** [comment]
What's the best way to sequence changes into these two repositories? Should I open a PR against arrow-testing with the new file as well, and wait for it to be accepted before seeing the CI results here?

**Comment by pitrou** [comment]
@maxburke Yes, you should open a PR to [arrow-testing](https://github.com/apache/arrow-testing/tree/master/data/parquet) and update this one when the arrow-testing PR is merged.

**Comment by nevi-me** [comment]
hey @maxburke, I'll review and help out with this PR on the weekend. I currently don't have enough time during the evenings.

**Comment by nevi-me** [comment]
Hi @maxburke, I'm currently reviewing this; the failing tests are because the logic in this PR accounts for 1-level structs correctly (as per the schema of the attached file), but if a field is at the root of the Arrow schema, it doesn't work correctly.

For example, in the schema `<schema<a: date32>>`, we don't get `a: date32` from the Arrow schema.

I've opened ARROW-11618 and ARROW-11619 to make this ergonomic, as there are other issues with how we project into schemas on both Parquet and Arrow (respective to the JIRA issues).

This issue is likely blocking me on other nested-read work :(

**Comment by maxburke** [comment]
@nevi-me apologies for not looking at this sooner but I've merged in your changes!

**Comment by alamb** [comment]
@maxburke  / @sunchao  does this PR need any more work or review? I am not quite sure what was merged (or what remains to merge)

**Review by nevi-me — APPROVED** [review]
LGTM

**Pull request closed without merging**
