### PR TITLE
ARROW-11602: [Rust] Clippy lints

### PR DESCRIPTION
**Pull request by nevi-me**
There's some clippy lints that are returning errors, where they haven't before. Not sure what's happening, as we've pinned versions.

### CODE REVIEW

**Comment by alamb** [comment]
Thank you @nevi-me  -- looks like there are still a few more lints being hit

**Review by alamb — APPROVED** [review]

**Comment by alamb** [comment]
Looks to me like Rust 1.50 was released today: https://forge.rust-lang.org/

Screen Shot 2021-02-11 at 2 42 24 PM

So clippy got pickier

**Comment by nevi-me** [comment]
darn it, I was hoping it isn't a new stable release, because we have a lot of unnecessary `Result<()>`. This will take me longer

**Comment by alamb** [comment]
@nevi-me  -- I am working on a fix for the other lint errors based on this PR. My plan is to just disable the lints that are still failing -- because as you say changing `Result<..>` signatures is a much larger change

**Comment by nevi-me** [comment]
Thanks @alamb, it's inefficient use of time to try pursue all the lints now. Thanks, I'm closing this.

**Comment by alamb** [comment]
https://github.com/apache/arrow/pull/9476

**Pull request closed without merging**
