### PR TITLE
ARROW-3910: [Python] Set date_as_objects=True as default in to_pandas methods

### PR DESCRIPTION
**Pull request by wesm**
This does not add a deprecation warning primarily because it's a bit difficult to do (we would need to check the data types whether it's a date -- or in the case of a table, if any field is a date--, and then warn if so). `True` is the correct option though in order to accurately roundtrip data to and from pandas. Some users might have some workarounds floating around, but this is sufficiently advanced stuff already.

With this patch, date data round trips with no special options

```
In [2]: import pyarrow as pa                                   
                                                               
In [3]: import datetime                                        
                                                               
In [4]: arr = pa.array([datetime.date(2000, 1, 1), None])      
                                                               
In [5]: arr                                                    
Out[5]:                                                        
<pyarrow.lib.Date32Array object at 0x0000022CCDB1BBD8>         
[                                                              
  10957,                                                       
  null                                                         
]                                                              
                                                               
In [6]: arr.to_pandas()                                        
Out[6]: array([datetime.date(2000, 1, 1), None], dtype=object) 
                                                               
In [7]: pa.array(arr.to_pandas())                              
Out[7]:                                                        
<pyarrow.lib.Date32Array object at 0x0000022CCDC7FE58>         
[                                                              
  10957,                                                       
  null                                                         
]                                                              
```

If others strongly feel it's worth going to the effort of raising a deprecation warning, please chime in.

### CODE REVIEW

**Comment by wesm** [comment]
Spurious-looking test failure

```
Warning, treated as error:
/home/travis/build/apache/arrow/docs/source/python/benchmarks.rst:53:Unknown directive type "asv".
```

**Comment by xhochy** [comment]
Shouldn't we first have a DeprecationWarning in 0.12 and then switch in 0.13? Or was `date_as_object` already present in 0.11?

**Comment by wesm** [comment]
+1. The docs failure was the only thing that failed

**Comment by wesm** [comment]
Hm, I'm first going to rebase and add a section to the Sphinx docs about this topic

**Pull request closed without merging**
