### PR TITLE
ARROW-10104: [Python] Separate tests into its own conda package

### PR DESCRIPTION
**Pull request by xhochy**

### CODE REVIEW

**Comment by xhochy** [comment]
@github-actions crossbow submit -g conda

**Comment by xhochy** [comment]
@github-actions crossbow submit -g conda

**Comment by xhochy** [comment]
@github-actions crossbow submit conda-linux-gcc-py36-cpu

**Comment by xhochy** [comment]
@github-actions crossbow submit -g conda

**Comment by xhochy** [comment]
@github-actions crossbow submit conda-win-vs2017-py37

**Comment by xhochy** [comment]
@github-actions crossbow submit conda-win-vs2017-py37

**Comment by xhochy** [comment]
@github-actions crossbow submit conda-win-vs2017-py37

**Comment by xhochy** [comment]
@github-actions crossbow submit conda-win-vs2017-py37

**Comment by xhochy** [comment]
@github-actions crossbow submit -g conda

**Comment by xhochy** [comment]
@github-actions crossbow submit conda-*aarch64

**Review by kszucs — APPROVED** [review]
LGTM, I assume the aarch builds depend on upstream CF changes.

**Comment by xhochy** [comment]
They should pass, they are picking an older `orc` build that doesn't have a `run_exports`, newer ones have it and thus a rerun  should make it work.

**Comment by xhochy** [comment]
🎉

**Comment by wesm** [comment]
I have brought this up before in the context of the wheels -- do we know how much .whl footprint `pyarrow/tests` takes up?

**Comment by xhochy** [comment]
It's 2 MiB on-disk-space, so not as drastic as other things. I'm happy to pay the space-saved-vs-maintenance cost in the conda package but I'm unsure whether it's worth the hassle with wheels.

```
df.query("package == 'pyarrow' and name.str.startswith('lib/python3.8/site-packages/pyarrow/tests/')")['size'].sum() // 1024 / 1024
# -> 2.1767578125
``

**Pull request closed without merging**
