### PR TITLE
PARQUET-1824: [C++] Fix crashes and undefined behaviour on invalid input

### PR DESCRIPTION
**Pull request by pitrou**
Should fix the following issues:
- https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=20940
- https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=21334

(found by OSS-Fuzz)

### CODE REVIEW

**Comment by pitrou** [comment]
Based on PR #6685.

**Comment by pitrou** [comment]
AppVeyor build: https://ci.appveyor.com/project/pitrou/arrow/builds/31663420

**Comment by pitrou** [comment]
@wesm Do you want to check the `LevelDecoder` changes?

**Review by fsaintjacques — APPROVED** [review]
More unbounded buffers, let 'em comming.

**Review by wesm — COMMENTED** [review]
+1. Thanks for fixing these issues

**Pull request closed without merging**
