### PR TITLE
ARROW-15533: [C++] Check ARROW_WITH_OPENTELEMETRY in CI

### PR DESCRIPTION
**Pull request by mbrobbel**
- Set `ARROW_WITH_OPENTELEMETRY: ON` in C++ GitHub Actions workflow
- Add default value for ExecNode::ToStringExtra argument indent argument

### CODE REVIEW

**Comment by wjones127** [comment]
Is the option making it though to the build? I see the env variable but this line suggests it's not actually turned on in the CMake Configure:

https://github.com/apache/arrow/runs/5040342323?check_suite_focus=true#step:7:460

Also, maybe we should also add this to a Linux build, like the `AMD64 Conda C++` one?

**Comment by mbrobbel** [comment]
> Is the option making it though to the build? I see the env variable but this line suggests it's not actually turned on in the CMake Configure:
> 
> https://github.com/apache/arrow/runs/5040342323?check_suite_focus=true#step:7:460
> 

Thanks for spotting that! I forgot to update the build script.

> Also, maybe we should also add this to a Linux build, like the `AMD64 Conda C++` one?

This is blocked on https://github.com/apache/arrow/pull/11963. I'll add a reminder to that PR to enable OpenTelemetry in CI once that gets merged.

**Comment by mbrobbel** [comment]
Disabling OT in Windows builds in this PR. The fix from #11963 should also fix those builds: https://github.com/apache/arrow/blob/8573ba86990968ab95ac8e53d05071f917da93d4/cpp/cmake_modules/ThirdpartyToolchain.cmake#L4126-L4128

**Comment by pitrou** [comment]
@github-actions crossbow submit -g cpp

**Comment by pitrou** [comment]
@github-actions crossbow submit test-ubuntu-18.04-*

**Review by pitrou — APPROVED** [review]
+1, let's wait for CI

**Comment by jorisvandenbossche** [comment]
The "python-sdist" nightly build started failing (see https://github.com/ursacomputing/crossbow/runs/5062761297?check_suite_focus=true), with a message that seems related to OpenTelemetry:

```
 -- stderr output is:
CMake Error at /usr/share/cmake-3.16/Modules/ExternalProject.cmake:2421 (message):
  error: could not find git for clone of opentelemetry-proto
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/ExternalProject.cmake:3236 (_ep_add_download_command)
  cmake/opentelemetry-proto.cmake:9 (ExternalProject_Add)
  CMakeLists.txt:363 (include)



CMake Error at /build/cpp/opentelemetry_ep-prefix/src/opentelemetry_ep-stamp/opentelemetry_ep-configure-DEBUG.cmake:47 (message):
  Stopping after outputting logs.
```

So potentially related to this PR (note, I didn't actually look into it, just looked at commits in the last day that could be related to the new failure, and pinging here in case you could take a look).

**Comment by mbrobbel** [comment]
> The "python-sdist" nightly build started failing (see https://github.com/ursacomputing/crossbow/runs/5062761297?check_suite_focus=true), with a message that seems related to OpenTelemetry:
> 
> ```
>  -- stderr output is:
> CMake Error at /usr/share/cmake-3.16/Modules/ExternalProject.cmake:2421 (message):
>   error: could not find git for clone of opentelemetry-proto
> Call Stack (most recent call first):
>   /usr/share/cmake-3.16/Modules/ExternalProject.cmake:3236 (_ep_add_download_command)
>   cmake/opentelemetry-proto.cmake:9 (ExternalProject_Add)
>   CMakeLists.txt:363 (include)
> 
> 
> 
> CMake Error at /build/cpp/opentelemetry_ep-prefix/src/opentelemetry_ep-stamp/opentelemetry_ep-configure-DEBUG.cmake:47 (message):
>   Stopping after outputting logs.
> ```
> 
> So potentially related to this PR (note, I didn't actually look into it, just looked at commits in the last day that could be related to the new failure, and pinging here in case you could take a look).

It looks like `git` is removed before the build starts: https://github.com/ursacomputing/crossbow/runs/5062761297?check_suite_focus=true#step:6:501.
Should we change that or disable OpenTelemetry for these builds?

**Comment by jorisvandenbossche** [comment]
This removal of git was added in https://github.com/apache/arrow/pull/10342, cc @kszucs

**Comment by pitrou** [comment]
I opened https://github.com/apache/arrow/pull/12356 for the python-sdist failure.

**Comment by jorisvandenbossche** [comment]
> This removal of git was added in #10342, cc @kszucs

@kszucs do you remember the reason for it? 
We now have a similar failure of the `python-sdist` build, this time the new substrait option requiring git:

```
 CMake Error at /usr/share/cmake-3.16/Modules/ExternalProject.cmake:2421 (message):
  error: could not find git for clone of substrait_ep
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/ExternalProject.cmake:3236 (_ep_add_download_command)
  src/arrow/engine/CMakeLists.txt:50 (externalproject_add)
```

**Comment by kszucs** [comment]
> > This removal of git was added in #10342, cc @kszucs
> 
> @kszucs do you remember the reason for it?

Git was used to generate a version number even for a python sdist release with explicit version and already available source code. 

> We now have a similar failure of the `python-sdist` build, this time the new substrait option requiring git:
> 
> ```
>  CMake Error at /usr/share/cmake-3.16/Modules/ExternalProject.cmake:2421 (message):
>   error: could not find git for clone of substrait_ep
> Call Stack (most recent call first):
>   /usr/share/cmake-3.16/Modules/ExternalProject.cmake:3236 (_ep_add_download_command)
>   src/arrow/engine/CMakeLists.txt:50 (externalproject_add)
> ```

I think we should avoid hard dependency on git and prefer downloading tarballs from github.

**Comment by jorisvandenbossche** [comment]
> I think we should avoid hard dependency on git and prefer downloading tarballs from github.

Opened a JIRA for this: https://issues.apache.org/jira/browse/ARROW-15760

**Comment by kszucs** [comment]
We should pass

```cmake
    URL "https://github.com/${ARROW_SUBSTRAIT_REPO}/archive/${ARROW_SUBSTRAIT_TAG}.tar.gz"
```

instead of 

https://github.com/apache/arrow/blob/bee67c5f2ff84a1759d02b45d7a0cea9b494175b/cpp/src/arrow/engine/CMakeLists.txt#L51-L52

**Pull request closed without merging**
