### PR TITLE
ARROW-6106: [Java] Add Scala Specs2 test for Arrow Stream

### PR DESCRIPTION
**Pull request by tampler**

### CODE REVIEW

**Comment by wesm** [comment]
This patch is lacking in context -- we don't have any Scala code in the project yet. Can you open a JIRA issue and describe what you're proposing?

**Comment by tampler** [comment]
You can run my tests from another project: 
```
git clone https://github.com/Neurodyne/apache-arrow-parquet
cd apache-arrow-parquet
sbt testOnly arrowtest.ArrowSpec
```
To run Scala code, you need to setup a project and build.sbt
I can contribute that too

**Comment by tampler** [comment]
@wesm I can't open an issue in your Jira, since I'm not a member and have read only access. Pls open an issue for this PR.

Thanks

**Comment by tampler** [comment]
@wesm I just ported a vector/ips/TestArrowStream.java to Scala to showcase integration with Scala for other developers.

I'm using Parquet and Arrow in my Scala project

**Comment by wesm** [comment]
> I can't open an issue in your Jira, since I'm not a member and have read only access.

http://issues.apache.org/jira is free for all. You can register and create an account

**Comment by elahrvivaz** [comment]
I'm not sure what the benefit of a scala unit test is, since there is no arrow scala API. You'd have to bring in scala dependencies in order to build the unit test, which seems not great. And calling java classes from scala does not require any special syntax. If you really want a scala example, it might be better to add it to the documentation, instead of the source tree.

**Comment by tampler** [comment]
@elahrvivaz 
Look, I'm not playing with your tests for the sake of fun. I have a business issue and need to integrate Kafka with Arrow. Tell me better how do I restore Arrow object from Array[Byte] ?

That port may be a good starting point for Scala devs, who are struggling with your Arrow Java API.
Apache team offers a zero tech support for now, zero docs and zero presentations.

My contribution may be a good starting point for adoption Arrow in Scala and I"m willing to grow and support it

**Comment by elahrvivaz** [comment]
We use arrow extensively in my scala project, there are lots of examples [here](https://github.com/locationtech/geomesa/tree/master/geomesa-arrow) if you want to check it out.
My point is that there isn't any special scala syntax needed to interop with java libraries. You should be able to easily adopt the java unit tests to scala syntax. But adding an scala unit test that can't be compiled doesn't seem like a good idea - it is going to drift when changes are made. And adding scala to the arrow build just to run a unit test also doesn't seem worthwhile. That's why I suggested adding it as documentation, which as you mentioned is currently lacking.

**Comment by wesm** [comment]
I agree with @elahrvivaz -- unless there is an effort to develop some kind of Scala "syntactic sugar" front-end for some of the Java components I think this is better treated a documentation issue. There is no major commercial entity behind Apache Arrow who can take responsibility for writing professional documentation, so we are dependent on volunteers to help out. In the meantime, we direct users to various Scala projects (like Apache Spark or Geomesa or others) that make use of the Java API

**Comment by kszucs** [comment]
BTW I'd really like to see a Scala wrapper around the java implementation, perhaps we should bring it up the mailing list.

**Comment by tampler** [comment]
Ok guys, let's have a deal. 

I'll make Scala docs for Arrow in Markdown and Mermoid and you'll help me to solve my business problem and implement Serdes for both Parquet and Arrow.

1. My business problem: How to deserialize the following code in Scala/Java: 
```python
import pyarrow as pa
def record_batch_to_bytes(df):
    batch = pa.RecordBatch.from_pandas(df)
    ser_ = pa.serialize(batch)
    return bytes(ser_.to_buffer())
```
I then read this in my Scala code from Kafka, but can't reconstruct an object, see [here](https://github.com/Clover-Group/zio-tsp/blob/15aef1c7678ee00743e623dcc911b7678be179b5/src/test/scala/Arrow.scala#L103)

2. Need to implement an Arrow and Parquet Serdes for [ZIO](https://zio.dev). See my current implementation [here](https://github.com/Neurodyne/zio-serdes/blob/dfff853c4739ec43a0d97f9d6ecf62245c1fc197/src/test/scala/Base.scala#L82)

If you help me with those 2 issues, both related to non-existent support and documentation, I'll happily put my effort to help other devs with your Arrow and Parquet projects.

**Comment by emkornfield** [comment]
@tampler it looks like @wesm answered the immediate problem on the JIRA (python might be using the wrong API).  If that didn't solve your problem it might pay to discuss further on the mailing list, to see if you can get support there.

Also, per above, adding some level of Scala support would probably be welcome but should be discussed on the mailing list.  Also, additional documentation PRs are always welcome.  

As it stands now would you mind if we closed this PR?

**Comment by tampler** [comment]
Yes, thank you for your help. Will proceed in mailing lists

Thanks everybody

**Pull request closed without merging**
