### PR TITLE
GH-43969: [CI][Dev] Prune .dockerignore

### PR DESCRIPTION
**Pull request by pitrou**
### Rationale for this change

The smaller the better, according to https://docs.docker.com/build/cache/optimize/

### What changes are included in this PR?

Prune obsolete or unnecessary inclusions from `.dockerignore`.

### Are these changes tested?

Yes, by CI.

### Are there any user-facing changes?

No.

* GitHub Issue: #43969

### CODE REVIEW

**Comment by pitrou** [comment]
@github-actions crossbow submit -g nightly-tests

**Comment by pitrou** [comment]
@kou @assignUser Could one of you take a look at this?

**Comment by pitrou** [comment]
@github-actions crossbow submit -g nightly-packaging

**Review by kou — APPROVED** [review]
+1

**Comment by pitrou** [comment]
@github-actions crossbow submit -g nightly-release

**Comment by pitrou** [comment]
CI failures look unrelated

**Pull request merged**
