### PR TITLE
ARROW-10290: [C++] List POP_BACK is not available in older CMake versions

### PR DESCRIPTION
**Pull request by kszucs**

### CODE REVIEW

**Comment by kszucs** [comment]
@github-actions crossbow submit centos-7-amd64 debian-stretch-amd64

**Review by kszucs — COMMENTED** [review]
+1, merging on green.

**Comment by lidavidm** [comment]
My bad, thank you for fixing this!

**Comment by kszucs** [comment]
No worries, it's more of a continuous integration issue to cover most of the CMake configurations.

**Pull request closed without merging**
