### PR TITLE
MINOR: WIP [Python][CI] Enable -W error on all Python tests

### PR DESCRIPTION
**Pull request by raulcd**
This is just a testing PR related to: https://github.com/apache/arrow/pull/38238

### CODE REVIEW

**Comment by raulcd** [comment]
@github-actions crossbow submit test-conda-python-3.11

**Comment by jorisvandenbossche** [comment]
I thought about that yesterday as well, but this won't work without adding some more ignore filters. For example on the nightly builds with numpy/pandas we still have some deprecation warnings. 

The annoying part with this way is that we can't tweak it per build like with the env var, but of course we can then just add enough filters to cover all builds, and don't care that they are too broad for some other builds. And in any case, this solves the whole issue of not being able to pass it through an env var if the filter has spaces as we have in https://github.com/apache/arrow/pull/38238. And another benefit is that this then also is used when running the tests locally, making it more consistent with CI.

**Comment by raulcd** [comment]
Yes, I was pretty sure we would have to add more tweaking for other jobs but to be honest at the moment I am not entirely sure how to fix it the other way, unless we want to add a much broader ignore (without spaces).

There also some builds where we might just want to add `-W ignore` and we basically don't get any error like the nightly builds with numpy/pandas. So probably is worth exploring how much effort this is going to take.

**Comment by raulcd** [comment]
@github-actions crossbow submit test-conda-python-3.11

**Comment by jorisvandenbossche** [comment]
> There also some builds where we might just want to add `-W ignore`

Ah, indeed, we could override those settings on certain builds like that (although we don't want to ignore them, but always show them, so `-W always`?)

**Comment by raulcd** [comment]
I was expecting the last one to fail 🤔
My expectation was the CLI `-W` was taking precedence but if no input on CLI the `setup.cfg` config should have kicked in, so I was expecting if we don't add the ignore the build to fail 🤔

**Comment by jorisvandenbossche** [comment]
Hmm, yeah, that's also my expectation ..

**Comment by jorisvandenbossche** [comment]
I assume it doesn't see the setup.cfg, because we run the installed tests, not in-place (using `--pyargs pyarrow`)

**Comment by jorisvandenbossche** [comment]
Short term, while we figure this out, maybe we can just remove the "-W error" for now in https://github.com/apache/arrow/pull/38238 so that the nightly CI is green again. And then we can do a follow-up PR like this one to figure it out in a more robust way?

**Pull request closed without merging**
