### PR TITLE
GH-40108: [JS] Remove SWC dependency and move types to dev deps

### PR DESCRIPTION
**Pull request by domoritz**
* GitHub Issue: apache/arrow-js#65
* GitHub Issue: #65

### CODE REVIEW

**Review by trxcllnt — CHANGES_REQUESTED** [review]
Per the [ts-node docs](https://www.npmjs.com/package/ts-node#swc-1):
> SWC uses `@swc/helpers` instead of `tslib`. If you have enabled `importHelpers`, you must also install `@swc/helpers`.

**Comment by trxcllnt** [comment]
IIRC the reason we're using swc was that the regular ts-node compilation speed is so slow, it was timing out the integration tests.

**Comment by trxcllnt** [comment]
Specifically this commit: https://github.com/apache/arrow/pull/37668/commits/bae5c1f6d8c94ee6afa1c337ee834bb4466bad55

**Comment by domoritz** [comment]
Yeah, looks like we need 45 minutes rather than 25 compared to https://github.com/apache/arrow/pull/41260. So yeah, not a change we should make.

**Comment by domoritz** [comment]
Closing this for now as it seems like we need to make more major cleanup.

**Pull request closed without merging**
