### PR TITLE
ARROW-5493: [Go][Integration] add Go support for IPC integration tests

### PR DESCRIPTION
**Pull request by sbinet**

### CODE REVIEW

**Comment by wesm** [comment]
This is a big project, I'm glad to see you working on it!

**Comment by sbinet** [comment]
PTAL @stuartcarnie @alexandreyc @wesm 

I am reasonnably happy with this PR now.
it stills leaves `Map`, `Dictionary`, `Union`, `Decimal` and `Extension` arrays to be tested and validated, but this can be done in a following PR.
(also, I'd like to push this one before I run out of steam and time for Arrow)

**Comment by sbinet** [comment]
travis error (linting build) seems unrelated.

**Review by wesm — APPROVED** [review]
Gave this a skim and aside from the Go-specific design/implementation details it looks reasonable to me. Would be great to get a thumbs up from another Go developer

**Review by stuartcarnie — APPROVED** [review]
It's a big PR, so I mostly skimmed it. Seeing lots of new tests makes me feel 💯

**Pull request closed without merging**
