### PR TITLE
ARROW-11273: [Release][deb] Remove unsupported Debian GNU/Linux stretch

### PR DESCRIPTION
**Pull request by kou**

### CODE REVIEW

**Comment by kou** [comment]
@kszucs Sorry for missing this change.
We need to remove the https://bintray.com/apache/arrow/debian-rc/3.0.0-rc0 version and re-upload Debian GNU/Linux related packages by `UPLOAD_DEFAULT=0 UPLOAD_DEBIAN_APT=1 UPLOAD_DEBIAN_DEB=1 dev/release/03-binary.sh 3.0.0 0 ...`.

**Review by kszucs — APPROVED** [review]

**Comment by kszucs** [comment]
No worries. I managed to remove the version with:

```
curl --verbose --fail --basic --user ${BINTRAY_USER}:${BINTRAY_PASSWORD} --header 'Content-Type: application/json' --request DELETE https://bintray.com/api/v1/packages/apache/arrow/debian-rc/versions/3.0.0-rc0
```

Now I'm uploading with with this change.

**Comment by kszucs** [comment]
Re-uploaded the debian packages.

**Comment by kou** [comment]
Thanks!
It seems that there are some more problems around Linux packaging... I'm looking in to them...

**Pull request closed without merging**
