### PR TITLE
ARROW-8500: [C++] Add benchmark for using Filter on RecordBatch

### PR DESCRIPTION
**Pull request by wesm**
Since I changed Filter on RecordBatch to transform the filter to indices and use Take, I wanted to have a benchmark to compare the before/after performance so this can also be monitored over time. These benchmarks could use some refactoring but this is at least a starting point.

### CODE REVIEW

**Comment by wesm** [comment]
@ursabot benchmark --benchmark-filter=FilterRecordBatch 22f374102

**Comment by wesm** [comment]
@ursabot benchmark --benchmark-filter=FilterRecordBatch 22f3741

**Comment by wesm** [comment]
@fsaintjacques @kszucs any idea what went wrong with buildbot?

**Comment by kszucs** [comment]
Buildbot parses a specific stdio format from the archery command which was a bit different for this invocation, my guess is passing a specific commit makes the output format different.

**Comment by kszucs** [comment]
@ursabot benchmark --benchmark-filter=FilterRecordBatch

**Comment by kszucs** [comment]
@ursabot benchmark --benchmark-filter=Filter 22f3741

**Comment by kszucs** [comment]
Another guess is `FilterRecordBatch` doesn't exist in the contender.

**Comment by wesm** [comment]
@kszucs oh right, that would do it

**Comment by wesm** [comment]
Note: those Filter benchmarks are garbage because they don't include the RandomArrayGenerator::Boolean bugfix

**Comment by wesm** [comment]
I created https://github.com/wesm/arrow/tree/ARROW-8500-comparison for running apples-to-apples benchmark comparisons

For filtering record batches, the new selection vector approach is 5-40x faster. The performance improvement goes up drastically for low selectivity filters.

* performance now: https://gist.github.com/wesm/b76e6928b7b18815cb5b33d730f8563d
* performance before: https://gist.github.com/wesm/2f4b5339e968f55e9b08c2de5d8393cd

**Comment by wesm** [comment]
+1, awaiting CI

**Comment by fsaintjacques** [comment]
I confirm locally with taxi dataset, runtime for a low selectivity (total_amount > 200$, 120k / 1.5b rows) goes from 9s to 3s. Niice improvement.

**Comment by wesm** [comment]
Good stuff.

**Pull request closed without merging**
