### PR TITLE
ARROW-9331: [C++] Improve the performance of Tensor-to-SparseTensor conversion

### PR DESCRIPTION
**Pull request by mrkn**
In this pull-request, the slowing down of the conversion introduced in #7539 is canceled, and the conversion speed is improved than before #7539 in some cases.

### CODE REVIEW

**Comment by wesm** [comment]
@mrkn would you like someone to look at this?

**Comment by mrkn** [comment]
@wesm Yes, currently I’ve almost done for SparseCOOTensor. I think merging this before finishing for all the sparse format is better than nothing to be merged before 1.0.

**Comment by mrkn** [comment]
@wesm I'm working on fixing the problems on VC++.  Please wait a moment.

**Review by wesm — APPROVED** [review]
+1, benchmarks look good 

https://gist.github.com/wesm/31425511bc6b787d9acc44b82127397f

I also checked that this doesn't affect binary size much

**Pull request closed without merging**
