### PR TITLE
ARROW-4440 [C++] Fix flatbuffers build using msvc

### PR DESCRIPTION
**Pull request by rip-nsk**

### CODE REVIEW

**Comment by wesm** [comment]
```
[29/371] Performing install_flatc step for 'flatbuffers_ep'
FAILED: flatbuffers_ep-prefix/src/flatbuffers_ep-stamp/flatbuffers_ep-install_flatc 
cmd.exe /C "cd /D C:\projects\arrow\cpp\build && "C:\Program Files (x86)\CMake\bin\cmake.exe" -E copy C:/projects/arrow/cpp/build/flatbuffers_ep-prefix/src/flatbuffers_ep-build/RELEASE/flatc.exe C:/projects/arrow/cpp/build/arrow_thirdparty/bin/flatc.exe && "C:\Program Files (x86)\CMake\bin\cmake.exe" -E touch C:/projects/arrow/cpp/build/flatbuffers_ep-prefix/src/flatbuffers_ep-stamp/flatbuffers_ep-install_flatc"
Error copying file "C:/projects/arrow/cpp/build/flatbuffers_ep-prefix/src/flatbuffers_ep-build/RELEASE/flatc.exe" to "C:/projects/arrow/cpp/build/arrow_thirdparty/bin/flatc.exe".
```

**Comment by wesm** [comment]
This problem appears to be non-deterministic. I don't know what is causing it

**Comment by wesm** [comment]
I'm reverting these changes since 0.12.0 which are likely to blame for the flakiness

https://github.com/apache/arrow/pull/3295/commits/1e0fdbc85530412f2982cd15519b360bf8c40414

**Comment by wesm** [comment]
I reverted recent changes to the Flatbuffers EP in https://github.com/apache/arrow/pull/3295. So closing this

**Comment by rip-nsk** [comment]
In my case flatc is persistently not found and proposed fix resolves this issue.
I'll take a look deeper..

**Pull request closed without merging**
