### PR TITLE
ARROW-11717: [Integration] report debug logs for failing Flight case

### PR DESCRIPTION
**Pull request by lidavidm**
This doesn't fix the flaky case, just gets us extra debug info in the case that it does.

### CODE REVIEW

**Comment by alamb** [comment]
👍  thank you @lidavidm

**Comment by lidavidm** [comment]
The test stops failing once I add debug logging on the Rust side :/ But the C++ debug logs report that when it connects to the Rust server, the server resets the connection.

**Comment by lidavidm** [comment]
Actually, I think I see the issue now. The Rust service starts listening on the port in listen_on in flight_server_scenarios.rs, but the Flight server isn't set up until _after_ that - so if the client connects in between, it'll get an error. Do you have to await the future from `serve()` in order for the gRPC server to actually start listening? That way, the printing could be delayed until the server is actually ready.

**Comment by alamb** [comment]
Thanks @lidavidm  -- that sounds very plausible. I'll get a PR up with a proposed fix

**Comment by alamb** [comment]
Proposed PR here: https://github.com/apache/arrow/pull/9593

**Pull request closed without merging**
