### PR TITLE
ARROW-17015: [CI] Enable flight and flight sql on Ubuntu 20.04

### PR DESCRIPTION
**Pull request by raulcd**

### CODE REVIEW

**Comment by raulcd** [comment]
@github-actions crossbow submit test-ubuntu-20.04-cpp

**Comment by raulcd** [comment]
This is currently reproducing https://github.com/apache/arrow/pull/13547:
```
 -- Found SQLite3Alt: /usr/lib/x86_64-linux-gnu/libsqlite3.so  
CMake Error at src/arrow/flight/sql/CMakeLists.txt:122 (target_compile_definitions):
  Cannot specify compile definitions for target "flight_sql_test" which is
  not built by this project.
  ```
Once this one is merged I'll rebase and run the crossbow job again.

**Comment by kou** [comment]
@raulcd Could you rebase on master?

**Comment by raulcd** [comment]
@github-actions crossbow submit test-ubuntu-20.04-cpp

**Comment by raulcd** [comment]
@lidavidm should the arrow-flight-sql-test work with ASAN UBSAN? I don't think this was being tested previously, should I open a ticket for it? I am asking because I am not sure whether this is supposed to be a bug or an improvement.
```
 [ RUN      ] TestFlightSqlClient.TestGetDbSchemas
unknown file: Failure
Unexpected mock function call - taking default action specified at:
/arrow/cpp/src/arrow/flight/sql/client_test.cc:151:
    Function call: GetFlightInfo(@0x61500007d948 184-byte object <00-00 00-00 00-00 F0-BF 40-00 00-00 00-00 00-00 80-4C 06-49 CF-7F 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 01-01 00-00 00-00 00-00 00-20 00-00 00-00 00-00 ... 01-00 00-04 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00>, @0x7fff35794e80 64-byte object <02-00 00-00 00-00 00-00 C0-45 08-00 B0-60 00-00 65-00 00-00 00-00 00-00 65-00 00-00 00-00 00-00 C4-A9 AE-66 00-10 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00>)
          Returns: (nullptr)
Google Mock tried the following 1 expectation, but it didn't match:
/arrow/cpp/src/arrow/flight/sql/client_test.cc:152: EXPECT_CALL(sql_client_, GetFlightInfo(Ref(call_options_), descriptor))...
  Expected arg #1: is equal to 64-byte object <02-00 00-00 BE-BE BE-BE C0-6B 05-00 C0-60 00-00 73-00 00-00 00-00 00-00 73-00 00-00 00-00 00-00 BE-BE BE-BE BE-BE BE-BE 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00>
           Actual: 64-byte object <02-00 00-00 00-00 00-00 C0-45 08-00 B0-60 00-00 65-00 00-00 00-00 00-00 65-00 00-00 00-00 00-00 C4-A9 AE-66 00-10 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00>
         Expected: to be called once
           Actual: never called - unsatisfied and active
/arrow/cpp/src/arrow/flight/sql/client_test.cc:152: Failure
Actual function call count doesn't match EXPECT_CALL(sql_client_, GetFlightInfo(Ref(call_options_), descriptor))...
         Expected: to be called once
           Actual: never called - unsatisfied and active
[  FAILED  ] TestFlightSqlClient.TestGetDbSchemas (1 ms)
```

**Comment by lidavidm** [comment]
I see ARROW-17051 was filed, I'll see if I can spare time to look

**Comment by lidavidm** [comment]
Does incorporating #13599 fix the issue here?

**Comment by raulcd** [comment]
> Does incorporating #13599 fix the issue here?

I've tested locally with these changes and it fixes the issue.

**Comment by raulcd** [comment]
@github-actions crossbow submit test-ubuntu-20.04-cpp

**Comment by kou** [comment]
Could you remove `ARROW_BUILD_STATIC=OFF` for the Travis CI failure https://app.travis-ci.com/github/apache/arrow/jobs/577761548 :

```diff
diff --git a/.travis.yml b/.travis.yml
index 5038f66181..fadb18b508 100644
--- a/.travis.yml
+++ b/.travis.yml
@@ -59,7 +59,6 @@ jobs:
         # glog and CMAKE_UNITY_BUILD=ON.
         DOCKER_RUN_ARGS: >-
           "
-          -e ARROW_BUILD_STATIC=OFF
           -e ARROW_ORC=OFF
           -e ARROW_USE_GLOG=OFF
           -e CMAKE_UNITY_BUILD=ON
```

**Comment by raulcd** [comment]
I am quite confused about the travis error here. From my understanding on travis we were overriding the default Dockerfile on `ubuntu-20.04-cpp.dockerfile` from: `ARROW_FLIGHT=OFF \` with `-e ARROW_FLIGHT=ON` on `.travis.yml`.
This change updates the default on the `ubuntu-20.04-cpp.dockerfile` from: `ARROW_FLIGHT=OFF \` to:
```
    ARROW_FLIGHT=ON \
    ARROW_FLIGHT_SQL=ON \
```
but having specified on travis:
`-e ARROW_FLIGHT_SQL=OFF`
should be exactly the same scenario as initially:
Flight ON, Flight SQL OFF but I am getting the following error:
```
FAILED: debug/arrow-flight-sql-test 

: && /usr/bin/c++  -Wno-noexcept-type -Wno-subobject-linkage  -fdiagnostics-color=always -ggdb -O0  -Wall -Wno-conversion -Wno-sign-conversion -Wunused-result -Werror -fno-semantic-interposition -march=armv8-a  -g   src/arrow/flight/sql/CMakeFiles/arrow-flight-sql-test.dir/Unity/unity_0_cxx.cxx.o  -o debug/arrow-flight-sql-test  -Wl,-rpath,/build/cpp/googletest_ep-prefix/lib:/build/cpp/debug  debug/libarrow_flight_sql.a  debug/libarrow_flight.a  debug/libarrow_flight_testing.a  debug/libarrow_testing.a  debug/libarrow.a  /usr/lib/aarch64-linux-gnu/libcrypto.so  /usr/lib/aarch64-linux-gnu/libssl.so  /usr/lib/aarch64-linux-gnu/libbrotlienc.so  /usr/lib/aarch64-linux-gnu/libbrotlidec.so  /usr/lib/aarch64-linux-gnu/libbrotlicommon.so  google_cloud_cpp_ep-install/lib/libgoogle_cloud_cpp_storage.a  awssdk_ep-install/lib/libaws-cpp-sdk-identity-management.a  awssdk_ep-install/lib/libaws-cpp-sdk-sts.a  awssdk_ep-install/lib/libaws-cpp-sdk-cognito-identity.a  awssdk_ep-install/lib/libaws-cpp-sdk-s3.a  awssdk_ep-install/lib/libaws-cpp-sdk-core.a  awssdk_ep-install/lib/libaws-c-event-stream.a  awssdk_ep-install/lib/libaws-checksums.a  awssdk_ep-install/lib/libaws-c-common.a  opentelemetry_ep-install/lib/libopentelemetry_trace.a  opentelemetry_ep-install/lib/libopentelemetry_exporter_ostream_span.a  opentelemetry_ep-install/lib/libopentelemetry_exporter_otlp_http.a  /usr/lib/aarch64-linux-gnu/libutf8proc.so  /usr/lib/aarch64-linux-gnu/libre2.so  -ldl  googletest_ep-prefix/lib/libgtest_maind.so  googletest_ep-prefix/lib/libgmockd.so  grpc_ep-install/lib/libgrpc++.a  /usr/lib/aarch64-linux-gnu/libsqlite3.so  debug/libarrow_flight.a  grpc_ep-install/lib/libgrpc++.a  grpc_ep-install/lib/libgrpc.a  grpc_ep-install/lib/libgpr.a  absl_ep-install/lib/libabsl_raw_hash_set.a  absl_ep-install/lib/libabsl_hashtablez_sampler.a  absl_ep-install/lib/libabsl_hash.a  absl_ep-install/lib/libabsl_city.a  absl_ep-install/lib/libabsl_low_level_hash.a  absl_ep-install/lib/libabsl_random_distributions.a  absl_ep-install/lib/libabsl_random_seed_sequences.a  absl_ep-install/lib/libabsl_random_internal_pool_urbg.a  absl_ep-install/lib/libabsl_random_internal_randen.a  absl_ep-install/lib/libabsl_random_internal_randen_hwaes.a  absl_ep-install/lib/libabsl_random_internal_randen_hwaes_impl.a  absl_ep-install/lib/libabsl_random_internal_randen_slow.a  absl_ep-install/lib/libabsl_random_internal_platform.a  absl_ep-install/lib/libabsl_random_internal_seed_material.a  absl_ep-install/lib/libabsl_random_seed_gen_exception.a  absl_ep-install/lib/libabsl_statusor.a  absl_ep-install/lib/libabsl_status.a  absl_ep-install/lib/libabsl_cord.a  absl_ep-install/lib/libabsl_cordz_info.a  absl_ep-install/lib/libabsl_cord_internal.a  absl_ep-install/lib/libabsl_cordz_functions.a  absl_ep-install/lib/libabsl_exponential_biased.a  absl_ep-install/lib/libabsl_cordz_handle.a  absl_ep-install/lib/libabsl_synchronization.a  absl_ep-install/lib/libabsl_graphcycles_internal.a  absl_ep-install/lib/libabsl_stacktrace.a  absl_ep-install/lib/libabsl_symbolize.a  absl_ep-install/lib/libabsl_debugging_internal.a  absl_ep-install/lib/libabsl_demangle_internal.a  absl_ep-install/lib/libabsl_malloc_internal.a  grpc_ep-install/lib/libupb.a  grpc_ep-install/lib/libaddress_sorting.a  /usr/lib/aarch64-linux-gnu/libcares.so  debug/libarrow_testing.so.900.0.0  debug/libarrow.so.900.0.0  /usr/lib/aarch64-linux-gnu/libboost_filesystem.so.1.71.0  /usr/lib/aarch64-linux-gnu/libboost_system.so.1.71.0  debug/libarrow.a  /usr/lib/aarch64-linux-gnu/libbrotlienc.so  /usr/lib/aarch64-linux-gnu/libbrotlidec.so  /usr/lib/aarch64-linux-gnu/libbrotlicommon.so  google_cloud_cpp_ep-install/lib/libgoogle_cloud_cpp_storage.a  google_cloud_cpp_ep-install/lib/libgoogle_cloud_cpp_rest_internal.a  google_cloud_cpp_ep-install/lib/libgoogle_cloud_cpp_common.a  absl_ep-install/lib/libabsl_bad_optional_access.a  absl_ep-install/lib/libabsl_str_format_internal.a  absl_ep-install/lib/libabsl_time.a  absl_ep-install/lib/libabsl_strings.a  absl_ep-install/lib/libabsl_strings_internal.a  absl_ep-install/lib/libabsl_throw_delegate.a  absl_ep-install/lib/libabsl_base.a  absl_ep-install/lib/libabsl_spinlock_wait.a  absl_ep-install/lib/libabsl_int128.a  absl_ep-install/lib/libabsl_civil_time.a  absl_ep-install/lib/libabsl_time_zone.a  absl_ep-install/lib/libabsl_bad_variant_access.a  absl_ep-install/lib/libabsl_raw_logging_internal.a  absl_ep-install/lib/libabsl_log_severity.a  crc32c_ep-install/lib/libcrc32c.a  awssdk_ep-install/lib/libaws-cpp-sdk-identity-management.a  awssdk_ep-install/lib/libaws-cpp-sdk-sts.a  awssdk_ep-install/lib/libaws-cpp-sdk-cognito-identity.a  awssdk_ep-install/lib/libaws-cpp-sdk-s3.a  awssdk_ep-install/lib/libaws-cpp-sdk-core.a  awssdk_ep-install/lib/libaws-c-event-stream.a  awssdk_ep-install/lib/libaws-checksums.a  awssdk_ep-install/lib/libaws-c-common.a  opentelemetry_ep-install/lib/libopentelemetry_exporter_ostream_span.a  opentelemetry_ep-install/lib/libopentelemetry_exporter_otlp_http.a  opentelemetry_ep-install/lib/libopentelemetry_otlp_recordable.a  opentelemetry_ep-install/lib/libopentelemetry_trace.a  opentelemetry_ep-install/lib/libopentelemetry_resources.a  opentelemetry_ep-install/lib/libopentelemetry_common.a  opentelemetry_ep-install/lib/libopentelemetry_exporter_otlp_http_client.a  opentelemetry_ep-install/lib/libopentelemetry_proto.a  protobuf_ep-install/lib/libprotobuf.a  opentelemetry_ep-install/lib/libopentelemetry_http_client_curl.a  /usr/lib/aarch64-linux-gnu/libcurl.so  /usr/lib/aarch64-linux-gnu/libssl.so  /usr/lib/aarch64-linux-gnu/libcrypto.so  /usr/lib/aarch64-linux-gnu/libutf8proc.so  /usr/lib/aarch64-linux-gnu/libre2.so  -ldl  /usr/lib/aarch64-linux-gnu/libbz2.so  /usr/lib/aarch64-linux-gnu/liblz4.so  /usr/lib/aarch64-linux-gnu/libsnappy.so.1.1.8  /usr/lib/aarch64-linux-gnu/libz.so  /usr/lib/aarch64-linux-gnu/libzstd.so  jemalloc_ep-prefix/src/jemalloc_ep/dist//lib/libjemalloc_pic.a  mimalloc_ep/src/mimalloc_ep/lib/mimalloc-2.0/libmimalloc-debug.a  -pthread  -lrt  googletest_ep-prefix/lib/libgtestd.so && :

collect2: fatal error: ld terminated with signal 9 [Killed]

compilation terminated.
```
which feels like an OOM. @lidavidm @kou any idea on the issue here?

**Comment by raulcd** [comment]
ok, it clearly is using `ARROW_FLIGHT_SQL=ON`:
```
--   ARROW_FLIGHT_SQL=ON [default=OFF]
--       Build the Arrow Flight SQL extension
```
I'll try to investigate why archery is not passing the environment variable defined on travis.

**Comment by raulcd** [comment]
@github-actions crossbow submit test-ubuntu-20.04-cpp

**Comment by raulcd** [comment]
@github-actions crossbow submit test-ubuntu-20.04-cpp

**Comment by amol-** [comment]
Closing because it has been untouched for a while, in case it's still relevant feel free to reopen and move it forward 👍

**Pull request closed without merging**
