### PR TITLE
ARROW-5633: [Python] Enable bz2 in Linux wheels

### PR DESCRIPTION
**Pull request by pitrou**

### CODE REVIEW

**Comment by pitrou** [comment]
@ursabot help

**Comment by pitrou** [comment]
@ursabot crossbow build wheel

**Comment by kszucs** [comment]
`@ursabot package --help`

**Comment by pitrou** [comment]
@ursabot crossbow wheel

**Comment by pitrou** [comment]
@ursabot build wheel

**Comment by pitrou** [comment]
EEk!

**Comment by kszucs** [comment]
@ursabot crossbow --help

**Comment by kszucs** [comment]
@ursabot crossbow package --help

**Comment by pitrou** [comment]
@ursabot crossbow package wheel

**Comment by kszucs** [comment]
@pitrou You want to run `@ursabot crossbow package --group wheel`

**Comment by kszucs** [comment]
@pitrou For testing the linux wheels you need to rebuild the image, add `docker-compose build python-manylinux1` after https://github.com/apache/arrow/blob/master/dev/tasks/python-wheels/travis.linux.yml#L49 then submit the linux task.

**Comment by pitrou** [comment]
@kszucs I've already rebuilt and uploaded the image from my machine.

**Comment by pitrou** [comment]
@kszucs What does this task do? How is it different from the manylinux task on travis-CI?

**Comment by kszucs** [comment]
Basically the same, but uploads the artifact and the wheel tasks build wheels for multiple python versions.

**Comment by pitrou** [comment]
@ursabot crossbow package wheel-win-cp36m

**Comment by pitrou** [comment]
I give up on Windows. @kou @xhochy feel free to take a look.

**Comment by wesm** [comment]
The Windows wheel build is currently broken? Is there a JIRA for this?

**Comment by pitrou** [comment]
@wesm Why broken?

**Comment by wesm** [comment]
You said "I give up on Windows." I wondered what you meant

**Review by wesm — APPROVED** [review]
+1

**Comment by pitrou** [comment]
Ah, no, it's simply that I gave up on enabling bz2 in Windows wheels.

**Comment by wesm** [comment]
OK, I opened https://issues.apache.org/jira/browse/ARROW-5667

**Pull request closed without merging**
