### PR TITLE
ARROW-3400: [Packaging] Add support for Parquet GLib deb/rpm

### PR DESCRIPTION
**Pull request by kou**

### CODE REVIEW

**Comment by kou** [comment]
https://github.com/kou/crossbow/branches/all?utf8=%E2%9C%93&query=build-22

**Comment by xhochy** [comment]
@kou Some of the builds fail due to missing references like `undefined reference to `garrow_schema_get_raw(_GArrowSchema*)'`

**Comment by kou** [comment]
Yes. I'm trying to fix it...

**Comment by kou** [comment]
https://github.com/kou/crossbow/branches/all?utf8=%E2%9C%93&query=build-27
All packages are built.

**Comment by kou** [comment]
I'll merge this.

**Pull request closed without merging**
