### PR TITLE
ARROW-2750: Add MATLAB support for reading numeric types from Feather files

### PR DESCRIPTION
**Pull request by kevingurney**
Add MATLAB support for reading numeric types (i.e. [u]int[x][y], float, double) from Feather files. This is the first in a series of future feature submissions for Feather read/write support and other Arrow IPC integration with MATLAB.

The associated pull request creates a top-level "matlab" directory in the Apache Arrow project. It also introduces a MATLAB function "featherread", which takes a Feather filename as input and returns a MATLAB table. featherread maps Feather datatypes to corresponding MATLAB datatypes.

This initial pull request does not support null values.

featherread.m calls the Arrow C+ APIs using MEX, MATLAB's facility for calling C/C+ code.

See the README.md in the "matlab" directory for instructions on how to build the MEX interface. Currently, building on Windows using CMake is not fully functional, but the MEX interface can be compiled manually using the MATLAB "mex" command.

A MATLAB install is required to be present on your machine to build the MEX interface.

### CODE REVIEW

**Comment by kevingurney** [comment]
Added Apache License Version 2.0 to notAFeatherFile.feather to address Apache Rat failures reported by Travis CI.

**Comment by xhochy** [comment]
This looks really good. 

@kevingurney Any chances that we can test this code in our CI?

**Comment by xhochy** [comment]
Also I wonder a bit on the legal implications on depending on Matlab in the Apache Software Foundation. It probably counts as a runtime such as the JVM but I'm not an expert in this matter.

**Comment by kevingurney** [comment]
@xhochy, it is nice to meet you, and thank you for reviewing my changes!

Regarding running MATLAB tests in Travis CI - this is definitely something we would love to be able to do, and we are currently investigating approaches to accomplish this.

All of the source code included in this pull request has been checked in under the Apache Version 2.0 License, but a MATLAB license and installation is needed to build the C/C++ MEX code. I will follow up with my colleagues at MathWorks regarding the legal side of things.

**Comment by wesm** [comment]
I'd be surprised if MATLAB in Travis CI were possible. They might be able to provide licenses to Arrow developers to be able to test and validate the extension.

**Comment by tkelman** [comment]
Would the Matlab Compiler Runtime include enough of the mex runtime libraries to be able to link against and test?

**Comment by kevingurney** [comment]
@wesm We are exploring providing a way to call a MathWorks cloud service to run MATLAB tests from a Travis build. While this is still under investigation, we were hoping that perhaps this project would be interested in piloting this technology.

@tkelman The MATLAB Compiler Runtime is meant for running MATLAB compiled applications and not for running arbitrary MATLAB code, so that wouldn't be suitable for this particular use case.

**Comment by wesm** [comment]
@kevingurney sounds good. One thing you could do would be to set up a bot (using https://probot.github.io/docs/ or something like that) that watches PRs for a particular code phrase or comment to kick off a MATLAB build (in case you are using Jenkins or something else).

**Comment by kevingurney** [comment]
@wesm Thanks for the suggestion! We can certainly explore this approach as we move forward.

**Comment by kevingurney** [comment]
We are actively investigating CI solutions and hope to have something usable soon. While we continue to work on this, is it possible to merge these changes into the project?

**Comment by wesm** [comment]
As you can see with 57 open pull requests and many issues we're scrambling to fix in advance of the 0.10.0 release, it may take a little while. I'll take a look through now and see if I see any issues. 

Can you or anyone from the MathWorks lend any assistance in some maintenance time for Apache Arrow?

**Comment by wesm** [comment]
Sorry I made a git mistake (since your branch is called "master", it resulted in some counterintuitive git behavior when I did `git checkout -b mathworks-master mathworks/master`) and it's not letting me reopen the PR. I'm opening a new PR now, sorry about that. Could you avoid making PRs out of the master branch in the future?

**Comment by kevingurney** [comment]
@wesm I read your posts on the Apache Arrow development mailing list regarding the difficulties of open source project maintenance. We recognize that this is a painful, ongoing issue. I've shared your thoughts with colleagues at MathWorks for further consideration regarding how we might be able to offer greater assistance with project maintenance efforts.

In the future, I'll be sure to make pull requests from separate feature branches, rather than the master branch. Thank you for reopening my pull request.

**Pull request closed without merging**
