### PR TITLE
ARROW-4918: [C++] Add cmake-format to pre-commit

### PR DESCRIPTION
**Pull request by xhochy**
Also extended the pattern to cover all the CMake code I've written in the last weeks.

### CODE REVIEW

**Comment by fsaintjacques** [comment]
LGTM

**Comment by wesm** [comment]
Hm, do we want to reformat all the cmake_modules/* files? Some of these have code reused from other projects and so it could just cause unnecessary divergence. Definitely we should keep ThirdpartyToolchain.cmake clean

**Comment by xhochy** [comment]
> Hm, do we want to reformat all the cmake_modules/* files? Some of these have code reused from other projects and so it could just cause unnecessary divergence. Definitely we should keep ThirdpartyToolchain.cmake clean

Changed this to an explicit list and reverted the changes to the files that were imported.

**Review by wesm — APPROVED** [review]
+1

**Pull request closed without merging**
