### PR TITLE
ARROW-17207: [C++][CI] Occasional timeout failures on arrow-compute-scalar-test

### PR DESCRIPTION
**Pull request by westonpace**

### CODE REVIEW

**Comment by westonpace** [comment]
No single test dominates the execution time.  There are just a lot of tests.  None of the tests appear to use threads.  When run with TSAN the tests are slower but the additional load appears evenly distributed across tests.

Splitting into two tests seems like the simplest approach for now.

**Comment by pitrou** [comment]
While the approach here is sane, perhaps we can try profiling this with TSAN enabled to see if there obvious optimizations to do in our test routines?

(another possibility might be to enable some compiler optimizations when building with TSAN, I don't think how safe/reasonable that is)

**Comment by pitrou** [comment]
Now that https://github.com/apache/arrow/pull/14502 is merged, I think we can close this.

**Comment by pitrou** [comment]
Note I also profiled as I suggested above (albeit without TSAN), and unfortunately no particular contributor stood out.

**Pull request closed without merging**
