### PR TITLE
ARROW-2538: [Java] Introduce BaseWriter.writeNull method

### PR DESCRIPTION
**Pull request by pudidic**
When a data set has null values in complex data type, it's hard to call proper writeNull method. Because writeNull is declared in AbstractFieldWriter, which is package local, not public. Moreover, UnionListWriter has no implementation of writeNull method, so it falls into AbstractFieldWriter.writeNull, which throws an IllegalArgumentException by default. So BaseWriter.writeNull is required to write null values inside of complex data types.

### CODE REVIEW

**Comment by siddharthteotia** [comment]
Why do we need to specifically write NULLs. All vectors by default are nullable and have a validity bitmap to indicate which column values are NULL. So I am wondering when do we specifically call writeNull().

**Comment by siddharthteotia** [comment]
ping

**Comment by emkornfield** [comment]
@pudidic Given the questions above is this still desired functionality?

**Comment by emkornfield** [comment]
Closing, as no response from author.

**Pull request closed without merging**
