### PR TITLE
[WIP] ARROW-4648: [C++] Reorganize file names

### PR DESCRIPTION
**Pull request by pitrou**
Replace underscores with hyphens.

### CODE REVIEW

**Comment by wesm** [comment]
Hm. Can we use underscores instead of hyphens? FWIW underscores is what Google uses

https://github.com/tensorflow/tensorflow/tree/master/tensorflow/core/platform

**Comment by wesm** [comment]
(I hope this PR was tool-assisted)

**Comment by xhochy** [comment]
> Yes, it's tool assisted.
> 
> As for underscores: I don't really care what Google is doing. What do others think? @xhochy @fsaintjacques @emkornfield

I don't care, go ahead.

**Comment by wesm** [comment]
I agree that we should not make a decision based on cargo cult. It was more to say that there might be some reason why underscores were chosen

**Comment by wesm** [comment]
Here's what @emkornfield said

"I prefer "_" for file names (which the style guide recommends as a default if there isn't a consistent pattern): https://google.github.io/styleguide/cppguide.html#File_Names"

**Comment by emkornfield** [comment]
> "I prefer "_" for file names (which the style guide recommends as a default if there isn't a consistent pattern): 

I'm also biased since I've grown accustomed to this in my day job :) 

I don't think it is the case, but are there any contexts where the dashes can   be misinterpreted as flags in scripts (I don't think so, but that is the only objective  reason I can see for choosing one or the other)

**Comment by pitrou** [comment]
Concurrent PR (using underscores rather than hyphens) in #5069.

**Comment by emkornfield** [comment]
Closing as #5069 was merged.

**Pull request closed without merging**
