### PR TITLE
GH-36815: [C#]: Enable net472 tests under Windows

### LINKED ISSUE #36815: [C#] CI should run for .NET 4.7.2 under Windows
### Describe the enhancement requested

CI currently runs only for net70. If we try to enable net472 it fails -- probably because net472 is only supported under Windows.

### Component(s)

C#

### PR DESCRIPTION
**Pull request by CurtHagenlocher**
### What changes are included in this PR?

The primary C# test project is updated to run for .NET 4.7.2 only on Windows platforms.

### Are these changes tested?

Yes.
* Closes: #36815

### CODE REVIEW

**Comment by CurtHagenlocher** [comment]
Okay, this seems to work.

**Comment by kou** [comment]
@github-actions crossbow submit verify-rc-source-csharp-*

**Comment by kou** [comment]
@github-actions crossbow submit verify-rc-source-windows

**Comment by kou** [comment]
Ah, our RC verification script https://github.com/apache/arrow/blob/main/dev/release/verify-release-candidate.bat doesn't test the C# part...
We need to add it. Could you open an issue for it?

Does the following log show that this case was tested?

 https://github.com/apache/arrow/actions/runs/5626539222/job/15247546402?pr=36818#step:6:68

 ```text
Test run for D:\a\arrow\arrow\csharp\artifacts\Apache.Arrow.Tests\Debug\net472\Apache.Arrow.Tests.dll (.NETFramework,Version=v4.7.2)
Microsoft (R) Test Execution Command Line Tool Version 17.6.3 (x64)
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.

Passed!  - Failed:     0, Passed:  1110, Skipped:     0, Total:  1110, Duration: 5 s - Apache.Arrow.Tests.dll (net472)
 ```

**Comment by CurtHagenlocher** [comment]
I clearly should have come back to this before checking in the Duration change (which has now broken the .NET 4.7.2 build).

Opened #38298.

**Comment by CurtHagenlocher** [comment]
@github-actions crossbow submit verify-rc-source-windows

**Pull request merged**
