### PR TITLE
ARROW-6905: [Packaging][OSX] Nightly builds on MacOS are failing because of brew compile timeouts

### PR DESCRIPTION
**Pull request by nealrichardson**

### CODE REVIEW

**Comment by nealrichardson** [comment]
@ursabot crossbow submit homebrew-cpp homebrew-cpp-autobrew macos-r-autobrew gandiva-jar-osx wheel-osx-cp27m wheel-osx-cp35m wheel-osx-cp36m wheel-osx-cp37m wheel-win-cp36m wheel-win-cp37m

**Comment by nealrichardson** [comment]
@ursabot crossbow submit homebrew-cpp

**Comment by kszucs** [comment]
@ursabot crossbow submit wheel-osx-cp37m

**Comment by kszucs** [comment]
Gandiva is resolved by #5681, the latest home-brew nightly tasks were passing, and I'm incorporating the wheel related changes to #5647. So closing in favor of the other PRs.

**Pull request closed without merging**
