### PR TITLE
ARROW-14041: [C++] Replace uses of BitmapReader in Parquet decoders

### PR DESCRIPTION
**Pull request by pitrou**
Use potentially more performant alternatives, though micro-benchmarks don't seem to show any significant improvement.

### CODE REVIEW

**Comment by cyb70289** [comment]
Looks we should increase MacOS CI job time limit.
It's currently set to 45min [1]. A recent successful test finishes in 43min [2].

[1] https://github.com/apache/arrow/blob/master/.github/workflows/cpp.yml#L120
[2] https://github.com/apache/arrow/runs/4315087429?check_suite_focus=true

**Comment by pitrou** [comment]
I've rebased for the macOS CI timeout change.

**Comment by pitrou** [comment]
@ursabot please benchmark

**Comment by cyb70289** [comment]
There is regression from some parquet column io benchmarks. Is it real or just noise?

**Comment by pitrou** [comment]
Let's try it again just to see.

**Comment by pitrou** [comment]
@ursabot please benchmark

**Comment by pitrou** [comment]
@ursabot please benchmark

**Comment by cyb70289** [comment]
Looks the regression of parquet-column-io-benchmark (RleEncoding/Decoding) is not real. They are not related to this change. It does happens in microbenchmark.

**Review by cyb70289 — APPROVED** [review]

**Pull request closed without merging**
