### PR TITLE
WIP

### PR DESCRIPTION
**Pull request by pitrou**

### CODE REVIEW

**Comment by pitrou** [comment]
@github-actions crossbow submit wheel-windows-cp312-amd64

**Comment by zooba** [comment]
I don't see where it would go, but you'll need to move the `/nodefaultlib:libucrt.lib /nodefaultlib:libvcruntime.lib` to linker options and add `ucrt.lib vcruntime.lib` there as well.

You _might_ be able to keep them in `CXXFLAGS` and add `-link` before the linker args start, but I suspect that won't work through CMake. There's probably a separate variable that you just aren't using yet.

**Comment by raulcd** [comment]
The current logs show:
```
cl : command line warning D9002: ignoring unknown option '/nodefaultlib:libucrt.lib'
```

**Comment by pitrou** [comment]
> I don't see where it would go, but you'll need to move the `/nodefaultlib:libucrt.lib /nodefaultlib:libvcruntime.lib` to linker options and add `ucrt.lib vcruntime.lib` there as well.
> 
> You _might_ be able to keep them in `CXXFLAGS` and add `-link` before the linker args start, but I suspect that won't work through CMake. There's probably a separate variable that you just aren't using yet.

Hmm, ok. Well, as I said on the issue, then, the simplest is probably to keep the current build options and simply not bundle the DLL anymore.

**Pull request closed without merging**
