### PR TITLE
ARROW-11973 [Rust][DataFusion] Boolean kleene kernels

### PR DESCRIPTION
**Pull request by ch-sc**
This PR adds two boolean kernels `kleene_or` and `kleene_and`.

As described in the corresponding [JIRA ticket](https://issues.apache.org/jira/browse/ARROW-11973), the kleene operator handels null values differently compared to plain OR and AND operators. 

| Operator | Left       | Right  | Result   |
| -----------: | ----------:| --------:| ---------: |
| AND        | TRUE   | NULL | NULL    |
| AND        | FALSE  | NULL | FALSE |
| OR          | TRUE   | NULL | TRUE   |
| OR          | FALSE  | NULL | NULL   |

### CODE REVIEW

**Comment by Dandandan** [comment]
@ch-sc thanks for your PR

In the JIRA ticket it is mentioned that these semantics are default for SQL - however - these return `NULL` in PostgreSQL (the dialect we want to target for DataFusion.

```
SELECT TRUE AND NULL;
SELECT TRUE OR NULL;
```

**Comment by ch-sc** [comment]
Hi @Dandandan, I actaully checked on Postgres (11) beforehand and it did return exactly the values I provided in the table.

```
SELECT TRUE AND NULL; --> NULL
SELECT FALSE AND NULL; --> FALSE
SELECT TRUE OR NULL; --> TRUE
SELECT FALSE OR NULL; --> NULL
```

Which Postgres version are you using?

**Comment by jorgecarleitao** [comment]
I tried on mysql, postgres and big query and was happy with the table you provided on JIRA. I am also curious how I got a different result than @Dandandan  xD

**Comment by Dandandan** [comment]
Haha @ch-sc  @javierluraschi I tried it on this website which I used before https://rextester.com/l/postgresql_online_compiler
but it shows `null` on every input now 🤣

So forget what I said, it is very useful to do this both for Arrow & DataFusion :+1:

**Comment by ch-sc** [comment]
@Dandandan @jorgecarleitao the integration tests fail because of scarce disk space:
```
+ npm install
##[warning]You are running out of disk space. The runner will stop working when the machine runs out of disk space. Free space left: 57 MB
npm WARN tar ENOSPC: no space left on device, write
```

Any ideas what we can do about this?

**Review by alamb — COMMENTED** [review]
@ch-sc  I'll plan to review this carefully tomorrow -- sorry I missed it with all the other things going on.

**Review by alamb — APPROVED** [review]
This is really nicely done @ch-sc  -- I went over the implementation and reviewed the tests carefully. 💯 

Thank you for the contribution

**Comment by alamb** [comment]
For the record the issue of the integration test running out of space is known and not related to this PR

**Pull request closed without merging**
