### PR TITLE
WIP: [Release] Verify release-11.0.0-rc0

### PR DESCRIPTION
**Pull request by kou**
PR to verify Release Candidate

### CODE REVIEW

**Comment by kou** [comment]
@github-actions crossbow submit  --group verify-rc-source --param release=11.0.0 --param rc=0

**Comment by raulcd** [comment]
Revision: f10f5cfd1376fb0e602334588b3f3624d41dee7d

Submitted crossbow builds: [ursacomputing/crossbow @ release-11.0.0-rc0-0](https://github.com/ursacomputing/crossbow/branches/all?query=release-11.0.0-rc0-0)

|Task|Status|
|----|------|
|almalinux-8-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-11.0.0-rc0-0-github-almalinux-8-amd64)|
|almalinux-8-arm64|[Travis CI](https://github.com/ursacomputing/crossbow/tree/release-11.0.0-rc0-0-travis-almalinux-8-arm64)|
|almalinux-9-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-11.0.0-rc0-0-github-almalinux-9-amd64)|
|almalinux-9-arm64|[Travis CI](https://github.com/ursacomputing/crossbow/tree/release-11.0.0-rc0-0-travis-almalinux-9-arm64)|
|amazon-linux-2-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-11.0.0-rc0-0-github-amazon-linux-2-amd64)|
|amazon-linux-2-arm64|[Travis CI](https://github.com/ursacomputing/crossbow/tree/release-11.0.0-rc0-0-travis-amazon-linux-2-arm64)|
|centos-7-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-11.0.0-rc0-0-github-centos-7-amd64)|
|centos-8-stream-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-11.0.0-rc0-0-github-centos-8-stream-amd64)|
|centos-8-stream-arm64|[Travis CI](https://github.com/ursacomputing/crossbow/tree/release-11.0.0-rc0-0-travis-centos-8-stream-arm64)|
|centos-9-stream-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-11.0.0-rc0-0-github-centos-9-stream-amd64)|
|centos-9-stream-arm64|[Travis CI](https://github.com/ursacomputing/crossbow/tree/release-11.0.0-rc0-0-travis-centos-9-stream-arm64)|
|conan-maximum|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/3949367968/jobs/6760483261)|
|conan-minimum|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-11.0.0-rc0-0-github-conan-minimum)|
|debian-bookworm-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-11.0.0-rc0-0-github-debian-bookworm-amd64)|
|debian-bookworm-arm64|[Travis CI](https://github.com/ursacomputing/crossbow/runs/10726099251)|
|debian-bullseye-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-11.0.0-rc0-0-github-debian-bullseye-amd64)|
|debian-bullseye-arm64|[Travis CI](https://github.com/ursacomputing/crossbow/tree/release-11.0.0-rc0-0-travis-debian-bullseye-arm64)|
|java-jars|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-11.0.0-rc0-0-github-java-jars)|
|nuget|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-11.0.0-rc0-0-github-nuget)|
|python-sdist|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-11.0.0-rc0-0-github-python-sdist)|
|r-binary-packages|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-11.0.0-rc0-0-github-r-binary-packages)|
|test-ubuntu-default-docs|[Azure](https://github.com/ursacomputing/crossbow/tree/release-11.0.0-rc0-0-azure-test-ubuntu-default-docs)|
|ubuntu-bionic-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-11.0.0-rc0-0-github-ubuntu-bionic-amd64)|
|ubuntu-bionic-arm64|[Travis CI](https://github.com/ursacomputing/crossbow/tree/release-11.0.0-rc0-0-travis-ubuntu-bionic-arm64)|
|ubuntu-focal-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-11.0.0-rc0-0-github-ubuntu-focal-amd64)|
|ubuntu-focal-arm64|[Travis CI](https://github.com/ursacomputing/crossbow/tree/release-11.0.0-rc0-0-travis-ubuntu-focal-arm64)|
|ubuntu-jammy-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/3949368490/jobs/6760484337)|
|ubuntu-jammy-arm64|[Travis CI](https://github.com/ursacomputing/crossbow/tree/release-11.0.0-rc0-0-travis-ubuntu-jammy-arm64)|
|ubuntu-kinetic-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-11.0.0-rc0-0-github-ubuntu-kinetic-amd64)|
|ubuntu-kinetic-arm64|[Travis CI](https://github.com/ursacomputing/crossbow/tree/release-11.0.0-rc0-0-travis-ubuntu-kinetic-arm64)|
|wheel-macos-big-sur-cp310-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/3949368873/jobs/6760485267)|
|wheel-macos-big-sur-cp311-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-11.0.0-rc0-0-github-wheel-macos-big-sur-cp311-arm64)|
|wheel-macos-big-sur-cp38-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/3949372997/jobs/6760494555)|
|wheel-macos-big-sur-cp39-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-11.0.0-rc0-0-github-wheel-macos-big-sur-cp39-arm64)|
|wheel-macos-mojave-cp310-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-11.0.0-rc0-0-github-wheel-macos-mojave-cp310-amd64)|
|wheel-macos-mojave-cp311-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-11.0.0-rc0-0-github-wheel-macos-mojave-cp311-amd64)|
|wheel-macos-mojave-cp37-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-11.0.0-rc0-0-github-wheel-macos-mojave-cp37-amd64)|
|wheel-macos-mojave-cp38-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-11.0.0-rc0-0-github-wheel-macos-mojave-cp38-amd64)|
|wheel-macos-mojave-cp39-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-11.0.0-rc0-0-github-wheel-macos-mojave-cp39-amd64)|
|wheel-manylinux2014-cp310-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-11.0.0-rc0-0-github-wheel-manylinux2014-cp310-amd64)|
|wheel-manylinux2014-cp310-arm64|[Travis CI](https://github.com/ursacomputing/crossbow/tree/release-11.0.0-rc0-0-travis-wheel-manylinux2014-cp310-arm64)|
|wheel-manylinux2014-cp311-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-11.0.0-rc0-0-github-wheel-manylinux2014-cp311-amd64)|
|wheel-manylinux2014-cp311-arm64|[Travis CI](https://github.com/ursacomputing/crossbow/runs/10726101943)|
|wheel-manylinux2014-cp37-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/3949371267/jobs/6760491048)|
|wheel-manylinux2014-cp37-arm64|[Travis CI](https://github.com/ursacomputing/crossbow/tree/release-11.0.0-rc0-0-travis-wheel-manylinux2014-cp37-arm64)|
|wheel-manylinux2014-cp38-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/3949370109/jobs/6760488126)|
|wheel-manylinux2014-cp38-arm64|[Travis CI](https://github.com/ursacomputing/crossbow/tree/release-11.0.0-rc0-0-travis-wheel-manylinux2014-cp38-arm64)|
|wheel-manylinux2014-cp39-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/3949372445/jobs/6760493478)|
|wheel-manylinux2014-cp39-arm64|[Travis CI](https://github.com/ursacomputing/crossbow/tree/release-11.0.0-rc0-0-travis-wheel-manylinux2014-cp39-arm64)|
|wheel-windows-cp310-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-11.0.0-rc0-0-github-wheel-windows-cp310-amd64)|
|wheel-windows-cp311-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/3949369344/jobs/6760486405)|
|wheel-windows-cp37-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/3949371824/jobs/6760492196)|
|wheel-windows-cp38-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/3949374724/jobs/6760498529)|
|wheel-windows-cp39-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-11.0.0-rc0-0-github-wheel-windows-cp39-amd64)|

**Comment by kou** [comment]
I re-ran the failed source verification jobs on macOS arm64.

**Comment by kou** [comment]
Passed.

**Comment by kou** [comment]
@github-actions crossbow submit  --group verify-rc-binaries --group verify-rc-wheels --param release=11.0.0 --param rc=0

**Comment by assignUser** [comment]
The pytest seg fault is also happening in verification https://github.com/ursacomputing/crossbow/actions/runs/3954649758/jobs/6772203240#step:5:2810

**Comment by kou** [comment]
@raulcd In general, we merge a RC branch to `maint-*` branch as a post release task: https://arrow.apache.org/docs/dev/developers/release.html#post-release-tasks

Because a RC may be rejected when a blocker is found.

**Comment by raulcd** [comment]
Hi @kou thanks for the clarification. I also found it strange but that's what appears on the release management guide in the instructions for sending the vote. https://arrow.apache.org/docs/dev/developers/release.html#verify-the-release

I'll update the notes to remove the merge instructions before sending the vote.

**Pull request merged**
