### PR TITLE
GH-43879: [Go] Remove go related code

### PR DESCRIPTION
**Pull request by raulcd**
### Rationale for this change

Go code has been mode to its own repository at https://github.com/apache/arrow-go

### What changes are included in this PR?

Removing the folder `go/` from the https://github.com/apache/arrow repository

### Are these changes tested?

I'll validate on CI there's no failures

### Are there any user-facing changes?

The Go code is no longer present on the Arrow repository.
* GitHub Issue: #43879

### CODE REVIEW

**Comment by raulcd** [comment]
@github-actions crossbow submit verify-rc-source-*

**Comment by raulcd** [comment]
The CI failures are unrelated and I've triggered the swift jobs to validate they still work even if we remove the `go/` subfolder.
@zeroshade @kou I think this is ok to be merged
I'll revert https://github.com/apache/arrow/pull/44293/commits/9ee7be2cc35efbbd2837252c1dc6da5873803a1e before merging

**Review by kou — APPROVED** [review]
+1

**Review by raulcd — COMMENTED** [review]
I am merging this in preparation for the release.
:+1:

**Pull request merged**
