### PR TITLE
ARROW-9051: [GLib] Refer Array related objects from Array

### PR DESCRIPTION
**Pull request by kou**
It's for preventing from freeing needed data.

### CODE REVIEW

**Comment by kou** [comment]
Sorry. This will be big to for review.
This fixes recent test failure like https://github.com/apache/arrow/runs/737152388 : 

```text
2020-06-04T04:42:11.7272962Z Failure: test_new(TestStructArray)
2020-06-04T04:42:11.7278250Z /arrow/c_glib/test/test-struct-array.rb:45:in `test_new'
2020-06-04T04:42:11.7280011Z      42:       Arrow::Int8Array.new(2, Arrow::Buffer.new([-29, 2].pack("C*")), nulls, 0),
2020-06-04T04:42:11.7280698Z      43:       Arrow::BooleanArray.new(2, Arrow::Buffer.new([0b01].pack("C*")), nulls, 0),
2020-06-04T04:42:11.7281159Z      44:     ]
2020-06-04T04:42:11.7281643Z   => 45:     assert_equal(struct_array1,
2020-06-04T04:42:11.7282232Z      46:                  Arrow::StructArray.new(data_type,
2020-06-04T04:42:11.7290723Z      47:                                         3,
2020-06-04T04:42:11.7291310Z      48:                                         children,
2020-06-04T04:42:11.7292404Z <#<Arrow::StructArray:0x2b94c20 ptr=0x247d820 -- is_valid:
2020-06-04T04:42:11.7292879Z   [
2020-06-04T04:42:11.7293137Z     true,
2020-06-04T04:42:11.7293502Z     true,
2020-06-04T04:42:11.7293785Z     false
2020-06-04T04:42:11.7294015Z   ]
2020-06-04T04:42:11.7294639Z -- child 0 type: int8
2020-06-04T04:42:11.7295527Z   [
2020-06-04T04:42:11.7296462Z     -29,
2020-06-04T04:42:11.7297060Z     2
2020-06-04T04:42:11.7298316Z   ]
2020-06-04T04:42:11.7298708Z -- child 1 type: bool
2020-06-04T04:42:11.7299354Z   [
2020-06-04T04:42:11.7299501Z     true,
2020-06-04T04:42:11.7299764Z     false
2020-06-04T04:42:11.7299872Z   ]>> expected but was
2020-06-04T04:42:11.7300715Z <#<Arrow::StructArray:0x291fd78 ptr=0x246d040 -- is_valid:
2020-06-04T04:42:11.7300848Z   [
2020-06-04T04:42:11.7300948Z     true,
2020-06-04T04:42:11.7301047Z     true,
2020-06-04T04:42:11.7301135Z     false
2020-06-04T04:42:11.7301234Z   ]
2020-06-04T04:42:11.7301472Z -- child 0 type: int8
2020-06-04T04:42:11.7301557Z   [
2020-06-04T04:42:11.7302241Z     -72,
2020-06-04T04:42:11.7302558Z     -8
2020-06-04T04:42:11.7302664Z   ]
2020-06-04T04:42:11.7302888Z -- child 1 type: bool
2020-06-04T04:42:11.7302997Z   [
2020-06-04T04:42:11.7303101Z     true,
2020-06-04T04:42:11.7303205Z     true
2020-06-04T04:42:11.7309639Z   ]>>
```

**Comment by pitrou** [comment]
Don't you use a Buffer subclass that owns a GLib buffer?

**Comment by kou** [comment]
It's interesting. I didn't think about the idea.
But we can't use this approach because we also need to refer not only GLib's buffers but also Ruby's buffers.

`Arrow::Buffer.new("...")` uses a Ruby's string for buffer data. It means that the Ruby's string needs to live while the GLib's buffer lives. A Ruby's buffer refers the Ruby's string for the buffer data. To prevent Ruby's buffers from Ruby's GC, we need to refer related GLib objects from living GLib objects. Ruby's GC can refer corresponding Ruby's objects with the situation.
If we refer GLib's buffers only from C++'s buffers, Ruby's GC can't refer Ruby's buffers for these GLib's buffers. It means that Ruby's strings  for buffer data may be freed while GLib's buffers live.

**Comment by kou** [comment]
+1

**Pull request closed without merging**
