### PR TITLE
ARROW-11054: [Rust] [DataFusion] Move to sqlparser 0.7.0

### PR DESCRIPTION
**Pull request by ovr**
Hello!

Thanks

### CODE REVIEW

**Review by andygrove — APPROVED** [review]
LGTM. Thanks @ovr

**Comment by ovr** [comment]
@andygrove I am still working on it, planning to finish today/tomorrow. I will mark this PR to ready for merge after it.

**Comment by ovr** [comment]
I finished, CI passed, I think PR is now ready for review.

Thanks

cC @andygrove

**Review by Dandandan — APPROVED** [review]
Awesome 😎 looks great @ovr !

**Comment by alamb** [comment]
The full set of Rust CI tests did not run on this PR :(

Can you please rebase this PR against [apache/master](https://github.com/apache/arrow) to pick up the changes in https://github.com/apache/arrow/pull/9056 so that they do? 

I apologize for the inconvenience.

**Review by alamb — APPROVED** [review]
Nice. Thanks @ovr

**Comment by alamb** [comment]
Thanks again @ovr

**Pull request closed without merging**
