### PR TITLE
ARROW-5672: [Java] Refactor redundant method modifier

### PR DESCRIPTION
**Pull request by tianchen92**
Related to [ARROW-5672](https://issues.apache.org/jira/browse/ARROW-5672).

### CODE REVIEW

**Comment by praveenbingo** [comment]
@tianchen92 Thanks for this. It looks like gandiva interfaces need fixing (CI is failing).

Please run with Gandiva profile locally to see the affected interfaces

**Comment by tianchen92** [comment]
@praveenbingo Thanks for your reminder, fixed now.

**Review by praveenbingo — APPROVED** [review]
+1 LGTM.

**Review by liyafan82 — APPROVED** [review]

**Comment by emkornfield** [comment]
+1, LGTM

**Pull request closed without merging**
