### PR TITLE
ARROW-7411: [C++][Flight] Improve the output of Arrow Flight benchmark

### PR DESCRIPTION
**Pull request by MaChengxin**

### CODE REVIEW

**Comment by pitrou** [comment]
@lidavidm

**Review by lidavidm — APPROVED** [review]

**Review by pitrou — APPROVED** [review]
Made some improvements, +1

**Comment by lidavidm** [comment]
The test failure looks unrelated, but I restarted it.

**Comment by lidavidm** [comment]
Tests pass, thank you both!

**Pull request closed without merging**
