### PR TITLE
ARROW-13129: [C#] Fix TableFromRecordBatches

### PR DESCRIPTION
**Pull request by 0x0L**

### CODE REVIEW

**Comment by eerhardt** [comment]
I'm not sure I understand the benefits here. Can you explain what was broken?

Also, can you add a unit test?

**Comment by 0x0L** [comment]
https://github.com/apache/arrow/blob/e9fa30406215b76ed6c885302fbfe6075c47badf/csharp/src/Apache.Arrow/Table.cs#L45-L46

The column array actually gets cleared in the new column as well since it's not a copy.

**Comment by eerhardt** [comment]
Alternatively, we could change `TableFromRecordBatches` to be:

```C#
         public static Table TableFromRecordBatches(Schema schema, IList<RecordBatch> recordBatches)
        {
            int nBatches = recordBatches.Count;
            int nColumns = schema.Fields.Count;

            List<Column> columns = new List<Column>(nColumns);
            for (int icol = 0; icol < nColumns; icol++)
            {
                List<Array> columnArrays = new List<Array>(nBatches);
                for (int jj = 0; jj < nBatches; jj++)
                {
                    columnArrays.Add(recordBatches[jj].Column(icol) as Array);
                }
                columns.Add(new Arrow.Column(schema.GetFieldByIndex(icol), columnArrays));
            }
```

And undo the `ToList()` changes here.

The reason I'd prefer that approach is because we have a bunch of other APIs that assume they take ownership of the array/list that is passed to them. The reason for that is to limit the amount of allocations. If someone builds up a single list, passes it into the `Table` constructor, and then moves on, it is a waste for the Table constructor to make a copy of the list as well. It is confusing for some APIs to make a defensive copy, but others not to.

Thoughts?

**Comment by 0x0L** [comment]
Honestly I find the semantics quite misleading, like the author of TableFromRecordBatches :) IMO these copies are harmless in terms of performance. It also enforces more coherence with the default constructor.

**Comment by eerhardt** [comment]
> IMO these copies are harmless in terms of performance

Unfortunately, this isn't true. Allocating unnecessary objects puts pressure on the garbage collector. Check out [this article](https://devblogs.microsoft.com/dotnet/performance-improvements-in-net-5/#gc) about some of the performance improvements that were made by reducing allocations.

**Comment by 0x0L** [comment]
!! the example with GC called every 15ms looked more like a bug than something else... Note though that in that benchmark there are probably as many allocations in pure clr as is in the old managed version.

If I there's no way to tell the user what's going on through the type system which leads to bugs just like this one. 
We may use `ref` parameters and null the ref we were given but that's still quite unsatisfactory.

I still value API "unsurpriseness" more than performance.

It's up to you. I can - reluctantly :) - edit the code in TableFromBatches

**Comment by 0x0L** [comment]
As a benchmark, I just ran a slightly modified version of their benchmark using ToList, also tried ToArray and no op. This certainly does not reveal any pathological issue in netcoreapp3.1 

```c#
using System;
using System.Linq;
using System.Diagnostics;
using System.Threading;

class Program
{
    public static void Main()
    {
        new Thread(() =>
        {
            var a = new int[20].ToList();
            while (true) a = a.ToList();
        }) { IsBackground = true }.Start();

        var sw = new Stopwatch();
        while (true)
        {
            sw.Restart();
            for (int i = 0; i < 10; i++)
            {
                GC.Collect();
                Thread.Sleep(15);
            }
            Console.WriteLine(sw.Elapsed.TotalSeconds);
        }
    }
}
```

**Comment by eerhardt** [comment]
Take a look at all the changes we've been making in the dotnet/runtime libraries that reduce allocations: https://github.com/dotnet/runtime/pulls?q=is%3Apr+is%3Aclosed+allocation+. Even the article I linked says:

> Lots of effort goes into reducing allocation, not because the act of allocating is itself particularly expensive, but because of the follow-on costs in cleaning up after those allocations via the garbage collector (GC).

If you allocate less objects, the GC has less work to do.

> I still value API "unsurpriseness"

I agree. Looking at the rest of the APIs that copy, they all take `IEnumerable<T>` for the parameter, and then call `ToList` or `ToArray`. Here are some examples:

https://github.com/apache/arrow/blob/8e43f23dcc6a9e630516228f110c48b64d13cec6/csharp/src/Apache.Arrow/Arrays/ArrayData.cs#L34-L44

https://github.com/apache/arrow/blob/8e43f23dcc6a9e630516228f110c48b64d13cec6/csharp/src/Apache.Arrow/RecordBatch.cs#L63-L70

https://github.com/apache/arrow/blob/8e43f23dcc6a9e630516228f110c48b64d13cec6/csharp/src/Apache.Arrow/Schema.cs#L39-L48

But then we also have `internal` APIs that take `List<T>` and the code takes ownership of that list without copying. This reduces allocations internally, while keeping the public API "unsurprising".

So how about following that same pattern here?

* Change these APIs to take `IEnumerable` instead of `IList`
* Internally when we create a Table, Column, ChunkedArray, we call the internal API that takes ownership of the list.

thoughts?

**Comment by 0x0L** [comment]
I agree. I think the `internal` access modifier should be used. I guess Flight assembly will probably have to be declared as friend.

Is that ok ?

**Comment by eerhardt** [comment]
I guess I don't see how the Flight assembly is relevant here. It doesn't use Table, Column, or ChunkedArray. But it is already IVT:

https://github.com/apache/arrow/blob/6c8d30ea82222fd2750b999840872d3f6cbdc8f8/csharp/src/Apache.Arrow/Properties/AssembyInfo.cs#L18

**Comment by pitrou** [comment]
@eerhardt @0x0L What is the status on this PR? Does either of you want to move it forward?
(also cc @wjones127 in case he's interested)

**Comment by 0x0L** [comment]
Sorry, not really involved with C# anymore. I'll try to push the changes we discussed shortly

**Comment by 0x0L** [comment]
In the end, I only fixed the behavior.
I'm not too sure where to stop with this ownership issue and it probably deserves more time to think about

**Review by eerhardt — APPROVED** [review]
LGTM. Thanks for the contribution.

**Pull request merged**
