### PR TITLE
WIP: [R] Verify CRAN release-12.0.1-rc1

### PR DESCRIPTION
**Pull request by thisisnic**

### CODE REVIEW

**Comment by thisisnic** [comment]
@github-actions crossbow submit --group r

**Comment by thisisnic** [comment]
valgrind timed out, devdocs often fails, conda isn't necessary for the release, and I have no idea why the homebrew build failed (it seems to be building from source instead of relying on the binary, so the binary not being there shouldn't be it), but have resubmitted the job to check.

**Comment by thisisnic** [comment]
> The homebrew failure is the known failure when installing the latest protobuf version with brew: #35987

Thanks Raul.

**Comment by assignUser** [comment]
12.0.1 is on CRAN :tada:

**Pull request closed without merging**
