### PR TITLE
ARROW-5485: [C++] Install libraries from googletest_ep into build output directory on non-Windows platforms

### PR DESCRIPTION
**Pull request by wesm**
I missed this when working on the googletest shared library migration as it only is a problem on macOS. Linux uses the library path from the link step without any extra fiddling, but on macOS it cannot resolve the library as described on the ARROW-5485 ticket.

This change results in the shared libraries being installed adjacent to the build outputs, e.g.

```
$ ll release/
total 20180
-rwxr-xr-x 1 wesm wesm  4492248 Jun  6 16:59 arrow-array-test*
lrwxrwxrwx 1 wesm wesm       14 Jun  6 16:58 libarrow.so -> libarrow.so.14*
lrwxrwxrwx 1 wesm wesm       18 Jun  6 16:58 libarrow.so.14 -> libarrow.so.14.0.0*
-rwxr-xr-x 1 wesm wesm 14900504 Jun  6 16:58 libarrow.so.14.0.0*
lrwxrwxrwx 1 wesm wesm       22 Jun  6 16:58 libarrow_testing.so -> libarrow_testing.so.14*
lrwxrwxrwx 1 wesm wesm       26 Jun  6 16:58 libarrow_testing.so.14 -> libarrow_testing.so.14.0.0*
-rwxr-xr-x 1 wesm wesm   583048 Jun  6 16:58 libarrow_testing.so.14.0.0*
-rwxr-xr-x 1 wesm wesm    16552 Jun  6 16:58 libgmock_main.so*
-rwxr-xr-x 1 wesm wesm   174824 Jun  6 16:58 libgmock.so*
-rwxr-xr-x 1 wesm wesm    16456 Jun  6 16:58 libgtest_main.so*
-rwxr-xr-x 1 wesm wesm   464352 Jun  6 16:58 libgtest.so*
```

### CODE REVIEW

**Comment by praveenbingo** [comment]
@wesm - It fails in my desktop post this change. I think its because the linked through rpath

otool -L on any test gives the following output

	@rpath/libarrow_testing.14.dylib (compatibility version 14.0.0, current version 14.0.0)
	@rpath/libarrow.14.dylib (compatibility version 14.0.0, current version 14.0.0)
	libgtest_main.dylib (compatibility version 0.0.0, current version 0.0.0)
	libgtest.dylib (compatibility version 0.0.0, current version 0.0.0)
	libgmock.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 400.9.4)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.250.1)

running the test from build folder still gives 

dyld: Library not loaded: libgtest_main.dylib
  Referenced from: /Users/praveenkumar/Desktop/dremio/code/arrow-for/arrow/cpp/build/./release/arrow-array-test
  Reason: image not found

however, cd into release folder and running the test works.

**Comment by wesm** [comment]
OK, since you have a mac, can you try to fix?

**Comment by praveenbingo** [comment]
> OK, since you have a mac, can you try to fix?

Sure will do, was planning to get this post something i am working on.

**Comment by praveenbingo** [comment]
@wesm I am closing it and opening a new PR https://travis-ci.org/apache/arrow/builds/543159861 for the same.

**Comment by wesm** [comment]
superseded by #4499

**Pull request closed without merging**
