### PR TITLE
ARROW-1287: [Python] Implement whence argument for pyarrow.NativeFile.seek

### PR DESCRIPTION
**Pull request by wesm**
I still need to validate this against the use case in https://github.com/dask/fastparquet/issues/188

### CODE REVIEW

**Comment by wesm** [comment]
Build failure seems unrelated

**Review by xhochy — APPROVED** [review]

**Comment by wesm** [comment]
@MaxRis one of the entries in the Appveyor build matrix randomly stopped working. Here is the build on master where it stopped working, with no Windows-related code changes https://ci.appveyor.com/project/ApacheSoftwareFoundation/arrow/build/1.0.2593. Any ideas?

Merging this PR since that is unrelated

**Comment by wesm** [comment]
I created https://issues.apache.org/jira/browse/ARROW-1294 to track this

**Comment by MaxRis** [comment]
@wesm , thank you, investigating...

**Comment by wesm** [comment]
seems to be a cmake 3.9.0 problem, but not sure why

**Pull request closed without merging**
