### PR TITLE
ARROW-12421: [Rust] [DataFusion] Fix topkexec failure

### PR DESCRIPTION
**Pull request by Dandandan**
This reproduces the test failure for the `TopKExec` test that @andygrove was seeing in combination with a 24-core machine.

Also FYI @alamb

(Marked as ready for review to trigger CI)

### CODE REVIEW

**Review by alamb — COMMENTED** [review]
Nice

**Comment by Dandandan** [comment]
@alamb @andygrove I pushed a version with a fix (I believe) for the `TopKExec` example. Not sure if the original version with `try_fold` could also be fixed to work, but this works at least. It now has a `.clone` on the map which is not a big deal for small `k` but probably would be better to avoid that.

**Comment by andygrove** [comment]
Thanks @Dandandan :rocket: 

So if the issue was just in the test, I should change my vote on the release to a +1?

**Comment by Dandandan** [comment]
@andygrove as far as I can see the issue was in the test and faulty TopKExec implementation only, not really in repartion or the optimization of the repartion node.

**Comment by andygrove** [comment]
ok, we probably need to get the flatbuffer dependency change in anyway, so
we should re-introduce the repartition optimization. Do you want to create
a PR for that? If not, I can get to it later today.

**Comment by Dandandan** [comment]
I probably won't get to that anymore today. Thanks, would be great

**Review by andygrove — APPROVED** [review]

**Comment by alamb** [comment]
Thanks @Dandandan 

> @andygrove as far as I can see the issue was in the test and faulty TopKExec implementation only, not really in repartion or the optimization of the repartion node.

For the record, the `TopKExec` is an example (not part of the DataFusion codebase)

**Comment by Dandandan** [comment]
Thanks @alamb @andygrove .

It would still be valuable to see if we can improve the example, or even add it to DataFusion once we have a good implementation (without the extension stuff of course)!

**Pull request closed without merging**
