### PR TITLE
ARROW-576: [C++] Complete file/stream implementation for union types

### PR DESCRIPTION
**Pull request by wesm**

### CODE REVIEW

**Comment by wesm** [comment]
Triggered build since things were fouled up yesterday by the S3 outage

**Comment by wesm** [comment]
Looks like our OS X miniconda download link disappeared. fun

**Comment by wesm** [comment]
green build https://travis-ci.org/wesm/arrow/builds/207006486

**Comment by wesm** [comment]
+1, merging as quite minor change

**Comment by wesm** [comment]
Seems the git mirror is lagging...

**Review by xhochy — APPROVED** [review]
+1, LGTM

**Pull request closed without merging**
