### PR TITLE
GH-34148: [C++][Thirdparty] make zstd require CMake 3.18

### LINKED ISSUE #34148: [C++] Minimal build failed in crossbow because of zstd v1.5.4 requires CMake v3.18
### Describe the bug, including details regarding any error messages, version, and platform.

After patch https://github.com/apache/arrow/pull/34114 is merged, crossbow CI was broken: https://github.com/ursacomputing/crossbow/actions/runs/4153851721/jobs/7185765610#step:3:1131

This is because zstd v1.5.4 introduce [CheckLinkerFlag](https://cmake.org/cmake/help/latest/module/CheckLinkerFlag.html), which is introduced in https://github.com/facebook/zstd/pull/3392 . And our crossbow CI install cmake 3.16, which didn't support it.

### Component(s)

C++, Developer Tools

### PR DESCRIPTION
**Pull request by mapleFU**
### Rationale for this change

See https://github.com/apache/arrow/issues/34148 . Zstd v1.5.4 require CMake 3.18 

### What changes are included in this PR?

CMake version check changed

### Are these changes tested?

No

### Are there any user-facing changes?

Yes, lower version cmake user cannot use zstd now

* Closes: #34148

### CODE REVIEW

**Comment by kou** [comment]
@github-actions crossbow submit example-cpp-minimal-build-static

**Comment by mapleFU** [comment]
```
CMake Error at cmake_modules/ThirdpartyToolchain.cmake:2509 (message):
  Building Zstandard using ExternalProject requires at least CMake 3.18
Call Stack (most recent call first):
  cmake_modules/ThirdpartyToolchain.cmake:205 (build_zstd)
  cmake_modules/ThirdpartyToolchain.cmake:278 (build_dependency)
  cmake_modules/ThirdpartyToolchain.cmake:2558 (resolve_dependency)
  CMakeLists.txt:504 (include)
```

lol...

**Review by assignUser — CHANGES_REQUESTED** [review]
I am -1 on this. Can we not rather than stopping the build in case the cmake version is to low drop to the previous working zstd version (1.52.x or what it was)

**Comment by kou** [comment]
@assignUser OK. How about sending a patch like the following to upstream then?

```diff
diff --git a/build/cmake/CMakeModules/AddZstdCompilationFlags.cmake b/build/cmake/CMakeModules/AddZstdCompilationFlags.cmake
index 0265349f..c4be65ce 100644
--- a/build/cmake/CMakeModules/AddZstdCompilationFlags.cmake
+++ b/build/cmake/CMakeModules/AddZstdCompilationFlags.cmake
@@ -1,6 +1,15 @@
 include(CheckCXXCompilerFlag)
 include(CheckCCompilerFlag)
-include(CheckLinkerFlag)
+# VERSION_GREATER_EQUAL requires CMake 3.7 or later.
+# https://cmake.org/cmake/help/latest/command/if.html#version-greater-equal
+if (CMAKE_VERSION VERSION_LESS 3.18)
+    set(ZSTD_HAVE_CHECK_LINKER_FLAG false)
+else ()
+    set(ZSTD_HAVE_CHECK_LINKER_FLAG true)
+endif ()
+if (ZSTD_HAVE_CHECK_LINKER_FLAG)
+    include(CheckLinkerFlag)
+endif()
 
 function(EnableCompilerFlag _flag _C _CXX _LD)
     string(REGEX REPLACE "\\+" "PLUS" varname "${_flag}")
@@ -20,7 +29,11 @@ function(EnableCompilerFlag _flag _C _CXX _LD)
         endif ()
     endif ()
     if (_LD)
-        CHECK_LINKER_FLAG(C ${_flag} LD_FLAG_${varname})
+        if (ZSTD_HAVE_CHECK_LINKER_FLAG)
+            CHECK_LINKER_FLAG(C ${_flag} LD_FLAG_${varname})
+        else ()
+            set(LD_FLAG_${varname} false)
+        endif ()
         if (LD_FLAG_${varname})
             set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} ${_flag}" PARENT_SCOPE)
             set(CMAKE_SHARED_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS} ${_flag}" PARENT_SCOPE)

```

**Comment by mapleFU** [comment]
All is ok for me, personally I use CMake 3.22, so this doesn't bother me...
Can we include some interface in CMake 3.16 rather than include in upstream?

**Comment by assignUser** [comment]
I will have time to add a patch at the end of the week

**Comment by kou** [comment]
Thanks!
But I opened a pull request https://github.com/facebook/zstd/pull/3510 because some discussions were proceeded in https://github.com/facebook/zstd/issues/3500 .

**Comment by assignUser** [comment]
That is good for the next release but we should fix this in arrow now. How about we just roll back to the previous version until your fix is released?

**Comment by assignUser** [comment]
Anyone that wants to use the 1.5.4 can use `zstd_URL` to override it.

**Comment by kou** [comment]
OK.
@mapleFU Could you revert #34114 ? We will bump zstd to1.5.5 that includes a fix for https://github.com/facebook/zstd/issues/3500 later.

**Comment by mapleFU** [comment]
> OK. @mapleFU Could you revert #34114 ? We will bump zstd to1.5.5 that includes a fix for [facebook/zstd#3500](https://github.com/facebook/zstd/issues/3500) later.

Glad to do it

**Comment by kou** [comment]
Let's ask zstd maintainers when the next release be after https://github.com/facebook/zstd/issues/3500 is fixed.

If the next release is unknown, we may implement conditional bundled zstd build. We use zstd 1.5.4 with newer CMake and use zstd 1.5.2 with older CMake.

**Comment by mapleFU** [comment]
I've revert it yet https://github.com/apache/arrow/pull/34190#issuecomment-1430757816 . And if you want me to pickup zstd in newer cmake, you can just tell me or edit it directly on my patch

**Comment by mapleFU** [comment]
Currently convert it to draft, maybe close it or change it introduce later zstd when upstream is ok

**Comment by kou** [comment]
OK. I close this.

**Pull request closed without merging**
