### PR TITLE
ARROW-4137: [Rust] Move parquet code into a separate crate

### PR DESCRIPTION
**Pull request by sunchao**
This moves the parquet related code into a separate sub-crate that
depends on arrow.

### CODE REVIEW

**Comment by kou** [comment]
I've added a commit to update version on release process.

**Review by andygrove — APPROVED** [review]
LGTM

**Review by paddyhoran — APPROVED** [review]

**Comment by sunchao** [comment]
Thanks @kou ! Regarding the release, I'm wondering whether every crate (e.g., arrow, parquet) has to use the same version number, and be released at the same time. Could we do separate releases for the crates with different version numbers?

**Comment by kou** [comment]
> whether every crate (e.g., arrow, parquet) has to use the same version number

We use different versions in C++. Parquet C++ uses https://github.com/apache/arrow/blob/master/cpp/src/parquet/.parquetcppversion and other C++ modules (Arrow, Plasma and Gandiva) use the same version.

We use the same versions in C and Ruby.

I think that we can use the different versions in Rust too but we may need to discuss it on mailing list.

> Could we do separate releases for the crates with different version numbers?

I'm not sure separate release is good for us.

We use different versions in C++ but we don't use separate release for C++.

We use separate release for JavaScript.

Separate release will be possible but we may need to discuss it on mailing list.
Our release cycle will be shorter in 2019. So we may not need separate release.

**Comment by kou** [comment]
BTW, we use subdirectories both for Arrow and Parquet in C++, C and Ruby:

* https://github.com/apache/arrow/tree/master/cpp/src `{arrow/,parquet/}`
* https://github.com/apache/arrow/tree/master/c_glib `{arrow-glib/,parquet-glib/}`
* https://github.com/apache/arrow/tree/master/ruby `{red-arrow/,red-parquet/}`

We may like the structure in Rust. (I think that this is out of scope of this pull request.)

**Comment by sunchao** [comment]
Thanks @kou ! good suggestion on the sub-directory - will look into that after this PR. I'll also send an email to the dev mailing list.

**Comment by kou** [comment]
Thanks!

**Comment by kszucs** [comment]
Agree with @kou on the dub-directories.

**Comment by kszucs** [comment]
Thanks @sunchao for the PR and thanks @andygrove @paddyhoran for the reviews!

**Pull request closed without merging**
