### PR TITLE
ARROW-3529: [Ruby] Import Red Parquet

### PR DESCRIPTION
**Pull request by kou**
It's Ruby bindings of Apache Parquet GLib.

It's based on https://github.com/red-data-tools/red-parquet/ at
cfb8fbfcaa5cb9c835058c2e612d202f6cad2edf .

See also https://github.com/red-data-tools/red-parquet/commit/cfb8fbfcaa5cb9c835058c2e612d202f6cad2edf

### CODE REVIEW

**Comment by kou** [comment]
I want to donate Ruby bindings for Apache Parquet GLib. It's developed by me.

**Comment by xhochy** [comment]
+1, looking forward to this. It's surprisingly simple, I like what GLib provides here as infrastructure. I wonder whether we need the code donation process here.

**Comment by wesm** [comment]
The code donation process isn't so bad. I'm not sure what the guidelines are on this

**Comment by xhochy** [comment]
Then let's start it now, then it's done even sooner.

**Comment by wesm** [comment]
I have started a vote on the mailing list. When 72 hours have elapsed, I will start the incubator IP clearance vote

**Comment by wesm** [comment]
Haven't started the incubator vote yet, sorry. Working on that now

**Comment by wesm** [comment]
Here is the incubator vote https://lists.apache.org/thread.html/924ef2bff8b61222da886806db9669a62f792f2857cf1a7b0c6d6ae4@%3Cgeneral.incubator.apache.org%3E. This can be merged in 72 hours

**Comment by wesm** [comment]
The IP clearance vote has passed. Merging this

**Pull request closed without merging**
