### PR TITLE
ARROW-16267: [Java] Adding support to compile Java code with JDK 18

### PR DESCRIPTION
**Pull request by davisusanibar**

### CODE REVIEW

**Comment by davisusanibar** [comment]
Please @raulcd / @assignUser your support with this review, thank you in advance.

**Review by assignUser — APPROVED** [review]
The [job works](https://github.com/apache/arrow/runs/6578520318?check_suite_focus=true) I had a look at the log and it looks fine to my non-java eyes :) 👍

**Comment by lidavidm** [comment]
Does GitHub offer a way to just specify "latest" so that we can automatically get 19, 20, ..., etc when they release?

**Comment by assignUser** [comment]
@lidavidm This is a docker issue, as we use some of [these](https://hub.docker.com/_/maven) for the jobs and they don't have a `3.8.5-openjdk-latest` tag. So there is no easy way to keep this up to date automatically. openjdk 20 is slated for release in 9/2022 so maybe we just open a jira with fix-version 10.0.0?

**Pull request closed without merging**
