### PR TITLE
ARROW-4831: [C++] CMAKE_AR is not passed to ZSTD thirdparty dependency 

### PR DESCRIPTION
**Pull request by kszucs**
Test it via docker.

1. Start an interactive shell in the conda container:

```bash
docker run -it --rm -v /local/path/to/arrow:/arrow ursalab/amd64-ubuntu-18.04-conda-python-3.6:worker bash
```

2. Execute the following build from `/arrow` withing the container:

```bash
export ARROW_BUILD_TYPE=debug
export ARROW_BUILD_TOOLCHAIN=$CONDA_PREFIX
export ARROW_HOME=$CONDA_PREFIX
export PARQUET_HOME=$CONDA_PREFIX
export PYARROW_CMAKE_GENERATOR=Ninja

mkdir -p cpp/build
pushd cpp/build

cmake -GNinja \
      -DCMAKE_BUILD_TYPE=$ARROW_BUILD_TYPE \
      -DCMAKE_INSTALL_PREFIX=$ARROW_HOME \
      -DARROW_PYTHON=ON \
      -DCMAKE_AR=${AR} \
      -DCMAKE_RANLIB=${RANLIB} \
      ..
ninja
ninja install

popd

pushd python

python setup.py build_ext --inplace --build-type=$ARROW_BUILD_TYPE
py.test -sv pyarrow

popd
```

### CODE REVIEW

**Comment by kszucs** [comment]
@wesm please review, I'd need it to fix the conda buildbot builds https://github.com/ursa-labs/ursabot/issues/13

**Review by xhochy — APPROVED** [review]
+1, LGTM

**Review by wesm — APPROVED** [review]
+1. I guess this might cause a rebase artifact

**Comment by xhochy** [comment]
@kszucs @wesm  This broke master on Windows: https://ci.appveyor.com/project/ApacheSoftwareFoundation/arrow/builds/23063072/job/bd0gom16atlkddtx

**Comment by xhochy** [comment]
Opened https://issues.apache.org/jira/browse/ARROW-4866

**Pull request closed without merging**
