### PR TITLE
ARROW-1860: [C++] Introduce ipc::PreparedMessage data structure to avoid making multiple passes over record batches

### PR DESCRIPTION
**Pull request by wesm**
The purpose of this is to decompose a record batch into its serialized Flatbuffer metadata and sequence of buffers that form its body so that the total output size can be computed, e.g. for writing to a shared memory segment. Prior to this, one would have to call `GetRecordBatchSize`, allocate memory, then `WriteRecordBatch` which duplicates work. 

This also introduces a change to how padding is handled in unaligned streams to make the message contents deterministic. This makes record batches consistent with the way that tensors were already being written, with alignment bytes being written first to move the stream position to a multiple of 8, then beginning to write the metadata and message body.

### CODE REVIEW

**Review by xhochy — APPROVED** [review]
+1, LGTM

**Comment by wesm** [comment]
Handled alignment on the read side, also. One question this brings up is whether the Java stream writer writes padded / aligned messages. I believe it does (this is checked for in C++: https://github.com/apache/arrow/blob/master/cpp/src/arrow/ipc/writer.cc#L854). But we should make sure. This is a case where having the Spark integration tests would be really helpful (cc @BryanCutler @icexelloss)

**Review by xhochy — CHANGES_REQUESTED** [review]
Failure is due to a segmentation fault.

**Comment by wesm** [comment]
Picking this up again

**Comment by wesm** [comment]
So it seems that not all Python file objects support the `tell` operation, for example the `_io.BufferedReader` that you get calling `makefile` on a socket. That's the last issue here -- I think probably the best way to deal with this is to implement a `PyInputStream` in https://github.com/apache/arrow/blob/master/cpp/src/arrow/python/io.h and handle the stream position bookkeeping internally, if that sounds good to folks

**Comment by pitrou** [comment]
> So it seems that not all Python file objects support the tell operation, for example the _io.BufferedReader that you get calling makefile on a socket.

Yes, non-seekable files generally don't support tell() either.
I'm a bit surprised that you need this: if writing to a generic output stream, why do you want to pad data? Padding only sounds useful when writing to a true random access file that may be e.g. memory-mapped.

**Comment by wesm** [comment]
> why do you want to pad data? 

I'll need to revisit this patch from a few months ago and remember why I thought this. The basic idea is for messages to be relocatable and deterministic (e.g. if you were to hash the metadata, you would always get the same hash). By always aligning the stream before writing a message, you guarantee that the message metadata and body have the exact same contents.

Given the time that has passed, it'll probably make sense to start this patch over. There's a unit test here that can be taken over, but the rest of the refactoring should probably be started from from the codebase as it is now.

**Comment by wesm** [comment]
Abandoning this PR for now. I would like to start again on this later in the year

**Pull request closed without merging**
