### PR TITLE
ARROW-14493: [Release][Go] Add update of import path for major versions to script

### PR DESCRIPTION
**Pull request by zeroshade**
When a major version update goes out, the Go import path and module name should update accordingly with a `/v<majorversion>` suffix.

### CODE REVIEW

**Comment by zeroshade** [comment]
@kou @kszucs I've fixed the outstanding issue here and bumped the files up to v7. This should get everything into a good state for the eventual next release above and beyond the upcoming v6.0.1 release.

**Comment by zeroshade** [comment]
bump @kou can you just take a sanity check here please?

**Comment by kou** [comment]
I'll update test code written in Ruby after I 6.0.1 RC1. Please wait for a while...

**Comment by zeroshade** [comment]
Sounds good, Thanks

**Review by kou — APPROVED** [review]
+1

I'll merge this once CI is finished with green.

**Pull request closed without merging**
