### PR TITLE
ARROW-2891: [Python] Preserve schema in write_to_dataset

### PR DESCRIPTION
**Pull request by jkulzick**

### CODE REVIEW

**Review by xhochy — CHANGES_REQUESTED** [review]
This looks good, just remove the copy and then this can be merged.

**Review by xhochy — APPROVED** [review]
+1, LGTM

**Comment by xhochy** [comment]
@jkulzick Thank you for having the patience to fix this!

**Comment by jkulzick** [comment]
@xhochy Happy to contribute. Thanks for this great package!

**Comment by wesm** [comment]
Thanks @jkulzick!

**Comment by ScubaDrew** [comment]
Thank you @jkulzick -- running into this issue right now!

**Comment by ScubaDrew** [comment]
I've looked everywhere I could think of. Is there any place which provides an estimation of when the next release including this fix might be made? -- Thanks!

**Pull request closed without merging**
