### PR TITLE
ARROW-600: ZSTD compression lib support

### PR DESCRIPTION
**Pull request by maxhora**

### CODE REVIEW

**Review by xhochy — APPROVED** [review]
+1, nice!

**Comment by MaxRis** [comment]
@xhochy , travis job is [failing](https://travis-ci.org/apache/arrow/jobs/249763425) for these changes. I guess, that `quay.io/xhochy/arrow_manylinux1_x86_64_base:latest` should be updated with changes in this changelist to avoid failure of this job. Does it make sense? Thanks

**Comment by xhochy** [comment]
@MaxRis, yes, I need to push to my master to fix that. I'll verify locally that this works and then we can merge and I push it.

**Comment by xhochy** [comment]
Verified successfully that this works. Will merge and push to apache and my master so that the builds get fixed.

**Comment by MaxRis** [comment]
@xhochy , thank you!

**Pull request closed without merging**
