### PR TITLE
ARROW-16796: [C++] Fix bad defaulting of ExecContext argument

### PR DESCRIPTION
**Pull request by rtpsw**
See https://issues.apache.org/jira/browse/ARROW-16796

### CODE REVIEW

**Comment by rtpsw** [comment]
@westonpace, could you review or refer to someone?

**Comment by westonpace** [comment]
Good catch.  I wonder if we should remove the default argument to bind entirely (it would look something like https://github.com/westonpace/arrow/commit/c9ae1dd6a0857af69e48a95ec76480f4c466791e ).  Looks like there are only a few other non-test spots we call bind.

 * In the parquet reader we convert statistics into expressions and bind them to the schema.  These expressions will only use min/max and it's only really for simplification and not execution so we're probably ok.
 * The scanner has a number of methods that create exec plans (this is the "lightweight producer" half of the scanner).  We could arguably add an ExecContext to scan options but I think it would better to start phasing out this half of the scanner in favor of direct use of exec plans instead.

CC @bkietz for second opinion

**Comment by rtpsw** [comment]
> Good catch. I wonder if we should remove the default argument to bind entirely (it would look something like [westonpace@c9ae1dd](https://github.com/westonpace/arrow/commit/c9ae1dd6a0857af69e48a95ec76480f4c466791e) ). Looks like there are only a few other non-test spots we call bind.

This discussion has wider scope than this PR, so I moved it to the jira issue

**Review by westonpace — APPROVED** [review]
> This discussion has wider scope than this PR, so I moved it to the jira issue

Fair enough.  This fix is fine on its own and if that helps you move forward then I don't see any harm in doing this first while we deliberate the larger question.

**Pull request merged**
