### PR TITLE
ARROW-7561: [Doc][Python] Add missing conda_env_gandiva.yml in python.rst

### PR DESCRIPTION
**Pull request by maartenb**
In the python/development.html page add the missing "--file conda_env_gandiva.yml" argument to the conda setup command.

### CODE REVIEW

**Review by jorisvandenbossche — APPROVED** [review]
Thanks! You wanted to add some more fixes? (otherwise I'll merge)

**Comment by maartenb** [comment]
Added directions for setting up the test data and added pushd/popd around the pytest command for consistency with the rest of the page.

**Comment by maartenb** [comment]
All set now, thanks. Let me know if you like me to update something.

Is there a documentation snap-shot that is based on master rather then the latest release?

**Review by wesm — APPROVED** [review]
+1

**Pull request closed without merging**
