### PR TITLE
ARROW-8450: [Integration][C++] Implement large offsets types

### PR DESCRIPTION
**Pull request by pitrou**
Implement integration tests for LargeList, LargeBinary and LargeString types.
Enable them for C++ (only).

Also add tests for recursive nested types.

### CODE REVIEW

**Comment by pitrou** [comment]
AppVeyor build: https://ci.appveyor.com/project/pitrou/arrow/builds/32175567

**Comment by pitrou** [comment]
Hmm, I notice the 64-bit offsets are serialized as JSON integers. @nealrichardson should they be serialized as strings instead?

**Comment by bkietz** [comment]
@pitrou I believe they should, looking for the relevant JIRA

**Comment by pitrou** [comment]
Hmm, it seems that even the "DATA" of int64 columns is output as JSON integers currently...

**Comment by bkietz** [comment]
Hmmm, that should have been changed in #5267

**Comment by pitrou** [comment]
That seems to have been lost when it was migrated to Archery.

**Review by bkietz — APPROVED** [review]
It was surprising to me that GetIntArray and WriteIntField were not being used to handle the data buffers of integer arrays (which would have fixed https://issues.apache.org/jira/browse/ARROW-8471 ). Some deduplication should be possible in a follow up

**Comment by pitrou** [comment]
Yes, it seems so.

**Comment by bkietz** [comment]
merging

**Pull request closed without merging**
