### PR TITLE
GH-34113: [C++][Thirdparty] Bump zstd to v1.5.4

### LINKED ISSUE #34113: [C++] Upgrade zstd to v1.5.4
### Describe the enhancement requested

Zstd has release it's latest version, v1.5.4, which containing a lots of performance improvement under x86 and aarch64. The release note can be seen here: https://github.com/facebook/zstd/releases/tag/v1.5.4

Notice that arrow is using zstd v1.5.2, can we upgrade it to v1.5.4?

### Component(s)

C++

### PR DESCRIPTION
**Pull request by mapleFU**
### Rationale for this change

Zstd has release it's latest version, v1.5.4, which containing a lots of performance improvement under x86 and aarch64. The release note can be seen here: https://github.com/facebook/zstd/releases/tag/v1.5.4

### What changes are included in this PR?

update zstd tag in thirdparty

### Are these changes tested?

no more tests added

### Are there any user-facing changes?

no

* Closes: #34113

### CODE REVIEW

**Comment by mapleFU** [comment]
Interesting, why `C++ / AMD64 Windows 2019 C++17 (pull_request)` failed... Let me find out the reason

**Comment by mapleFU** [comment]
Seems it downloads: https://github.com/facebook/zstd/archive/v1.5.4.tar.gz
the actual is: [zstd-1.5.4.tar.gz](https://github.com/facebook/zstd/releases/download/v1.5.4/zstd-1.5.4.tar.gz)

**Comment by mapleFU** [comment]
@kou Hi kou, sorry for disturbing you. I find a naive problem:

Currently we download from "github.com/facebook/zstd/archive/", and it hash tags differ from hashtag in release note. Currently we use "https://github.com/facebook/zstd/archive/${ARROW_ZSTD_BUILD_VERSION}.tar.gz", and can have `ARROW_ZSTD_BUILD_VERSION` like `v1.5.2` or `v1.5.4`.

The release notes have link like `https://github.com/facebook/zstd/releases/download/v{ARROW_ZSTD_BUILD_VERSION}/zstd-{ARROW_ZSTD_BUILD_VERSION}.tar.gz`. Note that `{ARROW_ZSTD_BUILD_VERSION}` is like `1.5.2` or `1.5.4` without `v`.

Here I have 2 solving ways:
1. Just use  "github.com/facebook/zstd/archive/", and recount a sha256sum
2. Use "https://github.com/facebook/zstd/releases/download/", and use `https://github.com/facebook/zstd/releases/download/{ARROW_ZSTD_BUILD_VERSION}/zstd-{remove_prefix(ARROW_ZSTD_BUILD_VERSION)}.tar.gz`

**Comment by kou** [comment]
Let's use the official one ( `https://github.com/facebook/zstd/releases/download/v{ARROW_ZSTD_BUILD_VERSION}/zstd-{ARROW_ZSTD_BUILD_VERSION}.tar.gz` )!

**Comment by mapleFU** [comment]
@kou All tests passed, would you mind check it?

**Review by kou — APPROVED** [review]
+1

Thanks!

**Comment by assignUser** [comment]
> Let's use the official one ( `https://github.com/facebook/zstd/releases/download/v{ARROW_ZSTD_BUILD_VERSION}/zstd-{ARROW_ZSTD_BUILD_VERSION}.tar.gz` )!

that has the advantage of being hash stable unlike the archive links :D

**Comment by kou** [comment]
Oh, this broke `example-cpp-minimal-build-static`...:

https://github.com/ursacomputing/crossbow/actions/runs/4153851721/jobs/7185765610#step:3:1131

```text
[ 25%] Performing configure step for 'zstd_ep'
CMake Error at /build/arrow/zstd_ep-prefix/src/zstd_ep-stamp/zstd_ep-configure-RELEASE.cmake:37 (message):
-- stdout output is:
  Command failed: 1
-- The C compiler identification is GNU 9.4.0
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/cc
-- The CXX compiler identification is GNU 9.4.0
-- Check for working C compiler: /usr/bin/cc

-- Check for working C compiler: /usr/bin/cc -- works
   '/usr/bin/cmake' '-DCMAKE_C_COMPILER=/usr/bin/cc' '-DCMAKE_CXX_COMPILER=/usr/bin/c++' '-DCMAKE_AR=/usr/bin/ar' '-DCMAKE_RANLIB=/usr/bin/ranlib' '-DBUILD_SHARED_LIBS=OFF' '-DBUILD_STATIC_LIBS=ON' '-DBUILD_TESTING=OFF' '-DCMAKE_BUILD_TYPE=RELEASE' '-DCMAKE_CXX_FLAGS= -fdiagnostics-color=always -fPIC' '-DCMAKE_CXX_FLAGS_DEBUG=-g -O0 -ggdb -Wno-error' '-DCMAKE_CXX_FLAGS_MISIZEREL=-Os -DNDEBUG' '-DCMAKE_CXX_FLAGS_RELEASE=-O3 -DNDEBUG -O2 -ftree-vectorize' '-DCMAKE_CXX_FLAGS_RELWITHDEBINFO=-O2 -g -DNDEBUG -O2 -ftree-vectorize  -O0 -ggdb' '-DCMAKE_CXX_STANDARD=17' '-DCMAKE_C_FLAGS= -fPIC' '-DCMAKE_C_FLAGS_DEBUG=-g -O0 -ggdb -Wno-error' '-DCMAKE_C_FLAGS_MISIZEREL=-Os -DNDEBUG' '-DCMAKE_C_FLAGS_RELEASE=-O3 -DNDEBUG -O2 -ftree-vectorize' '-DCMAKE_C_FLAGS_RELWITHDEBINFO=-O2 -g -DNDEBUG -O2 -ftree-vectorize  -O0 -ggdb' '-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=' '-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=' '-DCMAKE_INSTALL_LIBDIR=lib' '-DCMAKE_VERBOSE_MAKEFILE=FALSE' '-DCMAKE_INSTALL_PREFIX=/build/arrow/zstd_ep-install' '-DZSTD_BUILD_PROGRAMS=OFF' '-DZSTD_BUILD_SHARED=OFF' '-DZSTD_BUILD_STATIC=ON' '-DZSTD_MULTITHREAD_SUPPORT=OFF' '-GUnix Makefiles' '/build/arrow/zstd_ep-prefix/src/zstd_ep/build/cmake'
-- Detecting C compiler ABI info

-- Detecting C compiler ABI info - done
  See also
-- Detecting C compile features

-- Detecting C compile features - done
    /build/arrow/zstd_ep-prefix/src/zstd_ep-stamp/zstd_ep-configure-*.log
-- Check for working CXX compiler: /usr/bin/c++

-- Check for working CXX compiler: /usr/bin/c++ -- works

-- Detecting CXX compiler ABI info
CMake Error at /build/arrow/zstd_ep-prefix/src/zstd_ep-stamp/zstd_ep-configure-RELEASE.cmake:47 (message):
-- Detecting CXX compiler ABI info - done
  Stopping after outputting logs.
-- Detecting CXX compile features

-- Detecting CXX compile features - done

-- ZSTD VERSION: 1.5.4
make[2]: *** [CMakeFiles/zstd_ep.dir/build.make:108: zstd_ep-prefix/src/zstd_ep-stamp/zstd_ep-configure] Error 1
-- Performing Test C_FLAG_WALL
make[1]: *** [CMakeFiles/Makefile2:1450: CMakeFiles/zstd_ep.dir/all] Error 2
-- Performing Test C_FLAG_WALL - Success
make[1]: *** Waiting for unfinished jobs....
-- Performing Test CXX_FLAG_WALL
-- Performing Test CXX_FLAG_WALL - Success
-- Performing Test C_FLAG_WEXTRA
-- Performing Test C_FLAG_WEXTRA - Success
-- Performing Test CXX_FLAG_WEXTRA
-- Performing Test CXX_FLAG_WEXTRA - Success
-- Performing Test C_FLAG_WUNDEF
-- Performing Test C_FLAG_WUNDEF - Success
-- Performing Test CXX_FLAG_WUNDEF
-- Performing Test CXX_FLAG_WUNDEF - Success
-- Performing Test C_FLAG_WSHADOW
-- Performing Test C_FLAG_WSHADOW - Success
-- Performing Test CXX_FLAG_WSHADOW
-- Performing Test CXX_FLAG_WSHADOW - Success
-- Performing Test C_FLAG_WCAST_ALIGN
-- Performing Test C_FLAG_WCAST_ALIGN - Success
-- Performing Test CXX_FLAG_WCAST_ALIGN
-- Performing Test CXX_FLAG_WCAST_ALIGN - Success
-- Performing Test C_FLAG_WCAST_QUAL
-- Performing Test C_FLAG_WCAST_QUAL - Success
-- Performing Test CXX_FLAG_WCAST_QUAL
-- Performing Test CXX_FLAG_WCAST_QUAL - Success
-- Performing Test C_FLAG_WSTRICT_PROTOTYPES
-- Performing Test C_FLAG_WSTRICT_PROTOTYPES - Success
-- Configuring incomplete, errors occurred!
See also "/build/arrow/zstd_ep-prefix/src/zstd_ep-build/CMakeFiles/CMakeOutput.log".

-- stderr output is:
CMake Error at CMakeModules/AddZstdCompilationFlags.cmake:3 (include):
  include could not find load file:

    CheckLinkerFlag
Call Stack (most recent call first):
  CMakeLists.txt:70 (include)


CMake Error at CMakeModules/AddZstdCompilationFlags.cmake:23 (CHECK_LINKER_FLAG):
  Unknown CMake command "CHECK_LINKER_FLAG".
Call Stack (most recent call first):
  CMakeModules/AddZstdCompilationFlags.cmake:57 (EnableCompilerFlag)
  CMakeLists.txt:71 (ADD_ZSTD_COMPILATION_FLAGS)
```

**Comment by mapleFU** [comment]
Well, didn't CI trigger building the example? I'll take a look tonight

**Comment by mapleFU** [comment]
I run 

```
export ARROW_BUILD_DIR=$(pwd)/arrow-build
export EXAMPLE_BUILD_DIR=$(pwd)/example

./run_static.sh
```

On my macos, it build success. I'll try it later on my wsl ubuntu

**Comment by mapleFU** [comment]
Oh, find out why. https://cmake.org/cmake/help/latest/module/CheckLinkerFlag.html 
This is introduced in CMake 3.18, but our minimal build is 3.0...

**Comment by mapleFU** [comment]
```
Get:79 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 cmake amd64 3.16.3-1ubuntu1.20.04.1 [3668 kB]
```

And the version we install is 3.16.3. So, it failed @kou

**Comment by kou** [comment]
Thanks for taking a look at this.
Could you open a new issue for this?

**Comment by mapleFU** [comment]
Create an issue here: https://github.com/apache/arrow/issues/34148

**Pull request merged**
