### PR TITLE
ARROW-12987: [C++][CI] Switch to bundled utf8proc with version 2.2 in Ubuntu 18.04 images

### PR DESCRIPTION
**Pull request by anthonylouisbsb**
The tests are failing in the builds because the **utf8proc** dependency in Ubuntu 18.04 package is outdated.

I take a look at the utf8proc repository and I check that the error related to the build was fixed by that Pull Request https://github.com/JuliaStrings/utf8proc/pull/134 that is part of the 2.2 release: https://github.com/JuliaStrings/utf8proc/releases/tag/v2.2.0, but the Ubuntu 18.04 has only the 2.1.0 version in its package manager.

### CODE REVIEW

**Comment by anthonylouisbsb** [comment]
@kszucs I think I do not have permission to manually start the crossbow builds using the bot.

So could you submit the `test-ubuntu-18.04-cpp-static` and the `test-ubuntu-18.04-cpp` nightly builds from this branch? Then we can check if the changes are fine and correct the problem. I already made some tests locally and are fine.

**Comment by kszucs** [comment]
@github-actions crossbow submit test-ubuntu-18.04-cpp-static test-ubuntu-18.04-cpp

Thanks @anthonylouisbsb for the fix! BTW The comment bot should allow you to submit crossbow tasks.

**Comment by anthonylouisbsb** [comment]
@github-actions crossbow submit test-ubuntu-18.04-cpp-static test-ubuntu-18.04-cpp

**Comment by anthonylouisbsb** [comment]
@kszucs Thanks for running the builds, I did not know that I can run the comment bot.

BTW, the builds are passing, so I think the changes are working fine.

**Review by kszucs — APPROVED** [review]

**Comment by kou** [comment]
If we require utf8proc 2.2.0 or later, how about adding version check in CMake?

```diff
diff --git a/cpp/cmake_modules/ThirdpartyToolchain.cmake b/cpp/cmake_modules/ThirdpartyToolchain.cmake
index ff55936c2..1350f2745 100644
--- a/cpp/cmake_modules/ThirdpartyToolchain.cmake
+++ b/cpp/cmake_modules/ThirdpartyToolchain.cmake
@@ -2275,7 +2275,7 @@ macro(build_utf8proc)
 endmacro()
 
 if(ARROW_WITH_UTF8PROC)
-  resolve_dependency(utf8proc)
+  resolve_dependency(utf8proc REQUIRED_VERSION "2.2.0")
 
   add_definitions(-DARROW_WITH_UTF8PROC)

```

**Comment by anthonylgf** [comment]
@kou You are correct, I forgot to add it in this Pull Request. I will open a new one adding that check.

**Comment by anthonylouisbsb** [comment]
@kou You are correct, I forgot to add it in this PR, I will open a new one adding that check.

**Comment by anthonylouisbsb** [comment]
@kou I created a PR adding the check about the UTF8PROC version:

https://github.com/apache/arrow/pull/10477

**Pull request closed without merging**
