### PR TITLE
GH-37635: [Format][C++][Go] Add app_metadata to FlightInfo and FlightEndpoint

### LINKED ISSUE #37635: [FlightRPC] FlightSQL: Expose custom query metadata
### Describe the enhancement requested

We'd like to be able to expose custom metadata related to a given query through our Arrow Flight SQL service. For example, it'd be great to expose `queryId`, `queryCost`, or `queryType`, which could be useful to clients/users.

It seems like the existing ability to add [custom metadata](https://arrow.apache.org/docs/format/Columnar.html#custom-application-metadata) could be leveraged to accomplish this, but the exact mechanics seem a little unclear. The easiest thing would be to expose it via the `Schema` metadata since every `FlightInfo` already includes one, making it easy to expose through existing implementations. However, this seems a little hacky conceptually since the metadata could be associated with the query and not the results themselves (although metadata for the results also makes sense).

Another option could be to add a way to expose custom metadata directly through `FlightInfo`, but this would likely require major changes in every language implementation.

As far as how this gets exposed on the client side, we'd likely need changes to the JDBC and ADBC drivers.

For JDBC, there could be a few methods:
- `PreparedStatement.getCustomMetadata()`
- `ResultSet.getCustomMetadata()`
- `ResultSetMetaData.getCustomMetadata()`

Thoughts?

### Component(s)

FlightRPC

### PR DESCRIPTION
**Pull request by zeroshade**
### Rationale for this change
As suggested here: https://github.com/apache/arrow/issues/37635#issuecomment-1712146541 this just adds an `app_metadata` field to FlightInfo and FlightEndpoint

### What changes are included in this PR?
Just the updated proto file and the generated Go code from the proto

### Are there any user-facing changes?

Yes.

**This PR includes breaking changes to public APIs.**

* Closes: #37635

### CODE REVIEW

**Comment by lidavidm** [comment]
Could we also add unit/integration tests?

**Comment by zeroshade** [comment]
@lidavidm currently in the process of doing so

**Comment by kou** [comment]
Vote thread: https://lists.apache.org/thread/113xm107ptn1t76txockp11oc7wlh0ok

**Comment by lidavidm** [comment]
I think we generally require integration tests as well?

**Comment by zeroshade** [comment]
I'll set up integration tests for this sometime this week!

**Comment by lidavidm** [comment]
Can you rebase? It appears integration tests didn't run

**Review by lidavidm — APPROVED** [review]

**Comment by zeroshade** [comment]
rebased!

**Review by kou — APPROVED** [review]
+1

**Comment by kou** [comment]
I'll merge #37867 and rebase this to fix CI failures.

**Comment by zeroshade** [comment]
Thanks @kou! Hopefully we can get one more vote on the ML so that we can close the vote and merge this. I'll see if i can poke some people

**Comment by pitrou** [comment]
To be clear, there's no requirement that the `app_metadata` in a `FlightData` is the same the `app_metadata` for the `FlightInfo` or `FlightEndpoint` which led to that data?

**Comment by zeroshade** [comment]
@pitrou correct there's no requirement for it, the integration test is just using that to validate the values are as expected

**Pull request merged**
