### PR TITLE
ARROW-6066: [Website] Fix blog post author header

### PR DESCRIPTION
**Pull request by nealrichardson**
This fixes the author metadata logic in a few ways:
 
1. If the author isn't listed in contributors.yml, it is printed verbatim with no href
2. To make this work in the /blog/ page, the partial template has to null out the author_name variable so that the previous pass in the for loop doesn't spill over
3. The author link is either "homepage" if given, else a link to their GitHub page if "githubId" is given, else a link to the Apache phonebook
4. Logic for this header was consolidated in a single _include partial and used in both the main blog page and the individual permalinked pages

Before: 
image
image

After:
image
image

This is also now documented in the README.

While I was in there, I also deleted some unused templates.

### CODE REVIEW

**Review by pitrou — APPROVED** [review]
I've never touched the Web site, but this looks basically ok. Perhaps someone more experienced with it wants to take a look though.

**Comment by nealrichardson** [comment]
I deployed this to https://enpiar.com/arrow-site/blog/ so you can verify there. Some relative path links are still busted due to https://issues.apache.org/jira/browse/ARROW-4473 but you can verify the behavior change still.

**Comment by jorisvandenbossche** [comment]
If I click on the anchor next to a blog title (going to eg https://enpiar.com/blog/2019/07/02/0.14.0-release/), I get a 404 error. I suppose this is due to the bug you linked to above?

**Comment by nealrichardson** [comment]
Yeah, Jekyll doesn't handle relative URLs appropriately. The correct URL is https://enpiar.com/arrow-site/blog/2019/07/02/0.14.0-release/ because the "base URL" for this test site is https://enpiar.com/arrow-site/. This is not a problem on arrow.apache.org, nor if you serve locally.

**Review by wesm — APPROVED** [review]
+1, looks fine to me.

**Pull request closed without merging**
