### PR TITLE
ARROW-1562: [C++] Numeric kernel implementations for add

### PR DESCRIPTION
**Pull request by fexolm**
It's just an initial AddKernel implementation (work in progress). I could not come up with a better implementation of type inference, so I want to hear your thoughts about implementation.

### CODE REVIEW

**Comment by fsaintjacques** [comment]
Multiple notes:

1. The Compare kernels only support comparing the same type, it expects the caller to decide (via Cast kernel) how to deal with mis-matching types. I think this would be the most simple and sane behavior.
2. The Sum kernels [upcast](https://github.com/apache/arrow/blob/master/cpp/src/arrow/compute/kernels/sum-internal.h#L38-L55) to the widest type. This might be less of an issue here, but I think we should take a decision.
3. I wouldn't merge this without supporting null, this is too frequent to avoid.
4. This code is regular enough to support other basic arithmetic operations, i.e Addition, Substraction, Multiplication, Division.

**Comment by emkornfield** [comment]
@fexolm it looks like @fsaintjacques gave some feedback on implementation do you  need more guidance?

**Comment by fexolm** [comment]
@emkornfield no, I just can not find the time to finish this. I will return to this as soon as I get time.

**Comment by fexolm** [comment]
@fsaintjacques, @emkornfield
I've removed type inference from the code, also add nulls support.
BTW I haven't decided yet how it can be architecturally generalized to support other arithmetic operations. I see, that almost all the code could be reused in other operations, but not sure how to implement it.
Maybe it would be better to do this in other pr, because I'm not sure I have enough time for it now.

**Comment by emkornfield** [comment]
Thanks @fexolm @fsaintjacques do you have time to review?

**Comment by fsaintjacques** [comment]
Will review again.

**Comment by fsaintjacques** [comment]
I created https://issues.apache.org/jira/browse/ARROW-7017 as a followup.

**Pull request closed without merging**
