### PR TITLE
ARROW-312: [Java] IPC file round trip tool for integration testing

### PR DESCRIPTION
**Pull request by wesm**

### CODE REVIEW

**Comment by wesm** [comment]
@julienledem I can't figure out how to actually run this executable -- setting the right classpath, etc.

**Comment by julienledem** [comment]
@wesm I will take a look

**Comment by julienledem** [comment]
Here is a change with a unit test:
https://github.com/wesm/arrow/pull/1
I will add packaging to run later

**Comment by wesm** [comment]
+1. I'll work on integration testing in a new branch

**Pull request closed without merging**
