### PR TITLE
ARROW-12136: [Rust][DataFusion] Reduce default batch_size to 8192

### PR DESCRIPTION
**Pull request by Dandandan**
I did some comparisons with different batch sized with TCP-H on SF=1 in memory / 16 partitions. We chose a higher batch_size earlier as DF had some problems with smaller batch sizes (in hash join, but also because it missed the CoalesceBatches node).
Smaller batch sizes have some performance benefit: more (possible) parallelism for smaller tables, batches are available sooner (think e.g. of `CoalesceBatches` with highly selective filter) and therefore more parallelism, etc.
Also, memory usage can be reduced.

Currently it seems a value around 8000 is the sweet spot for SF=1, only query 1 is faster with a slightly smaller batch size.

image

### CODE REVIEW

**Comment by seddonm1** [comment]
Does this result look the same with SF > 1?

**Comment by Dandandan** [comment]
> Does this result look the same with SF > 1?

It seems so, yes. On SF=10:
``` 
q 1

32000 996.21 ms
16000 828.83 ms
8000  714.61 ms
4000  685.30 ms

q 5
32000 2094.11 ms
16000 2051.94 ms
8000  2014.32 ms
```

**Comment by seddonm1** [comment]
Cool. LGTM!

**Review by alamb — APPROVED** [review]
Thanks @Dandandan

**Pull request closed without merging**
