### PR TITLE
GH-43687: [C++] Compute: fix register kernel SimdLevel for AddMinMax512AggKernels

### PR DESCRIPTION
**Pull request by mapleFU**
### Rationale for this change

See https://github.com/apache/arrow/issues/43687

### What changes are included in this PR?

Change Registered AVX2 to AVX512

### Are these changes tested?

No

### Are there any user-facing changes?

maybe bugfix

* GitHub Issue: #43687

### CODE REVIEW

**Review by zanmato1984 — APPROVED** [review]
+1

**Review by pitrou — APPROVED** [review]

**Review by felipecrv — APPROVED** [review]
I'm approving and we should merge this, but I'm working on a PR that removes the SimdLevel template parameter alltogether as there is no need to runtime dispatch different SIMD levels when we are relying on compiler auto-vectorization.

Discussion here: https://github.com/apache/arrow/pull/7871

**Review by pitrou — APPROVED** [review]

**Comment by mapleFU** [comment]
Will merge this firstly

**Comment by felipecrv** [comment]
@ursabot please benchmark command=cpp-micro --suite-filter=arrow-acero-aggregate-benchmark --benchmark-filter=MinMaxKernel* --iterations=3

**Pull request merged**
