### PR TITLE
ARROW-13814: [CI] Fix Spark master integration tests

### PR DESCRIPTION
**Pull request by BryanCutler**
Increase the maven code cache to the recommend 1g to fix Spark Scala tests with latest Arrow.

### CODE REVIEW

**Comment by BryanCutler** [comment]
@github-actions crossbow submit test-conda-python-3.8-spark-master

**Comment by BryanCutler** [comment]
@github-actions crossbow submit test-conda-python-3.8-spark-master

**Comment by BryanCutler** [comment]
@github-actions crossbow submit test-conda-python-3.8-spark-master

**Comment by BryanCutler** [comment]
Hmm, not sure what's causing the problem. I can reproduce it locally, then I make a change and seems to be fixed but then pushing the change has no effect here..

**Comment by BryanCutler** [comment]
@kiszk do you have any clue why we are having trouble compiling Spark master + Arrow Java master?

**Comment by BryanCutler** [comment]
Looks like it has been failing for a while, first failure was on May 13 and seems to be related to this issue https://issues.apache.org/jira/browse/SPARK-35387 also fixed on May 13. I'll try the same fix here.

**Comment by BryanCutler** [comment]
@github-actions crossbow submit test-conda-python-3.8-spark-master

**Comment by BryanCutler** [comment]
Looks like I finally found the culprit :sweat_smile: 
Could you please review @kszucs or @jorisvandenbossche ?

**Review by kiszk — APPROVED** [review]
It looks more hungry :)

**Comment by BryanCutler** [comment]
Merged to master, thanks @kiszk

**Pull request closed without merging**
