### PR TITLE
ARROW-5789: [C++] Minor fixes for warnings, remove unused ubsan.cc

### PR DESCRIPTION
**Pull request by emkornfield**
* Cleanup some unused warning generated on MacOS, when asserts are turned off
* ubsan.cc isn't used since the code does internal linkage, trying to make it do external linkage seems to break MSVC.  Given it is only a byte of data the replication across compilation units doesn't seem to warrant a lot of time invested fixing this.

### CODE REVIEW

**Review by pitrou — APPROVED** [review]
+1.

**Comment by kszucs** [comment]
@emkornfield appveyor is failing

**Comment by emkornfield** [comment]
@kszucs yes sorry put this in wip till I can take a look

**Comment by emkornfield** [comment]
Travis on my repo: https://ci.appveyor.com/project/ApacheSoftwareFoundation/arrow/builds/25726136

**Review by kszucs — APPROVED** [review]

**Pull request closed without merging**
