### PR TITLE
ARROW-16811: [C++] Remove default exec context from Expression::Bind

### PR DESCRIPTION
**Pull request by westonpace**
Removes the default from the ExecContext argument in Expression::Bind

### CODE REVIEW

**Review by bkietz — APPROVED** [review]

**Comment by pitrou** [comment]
@westonpace It seems this PR needs updating and conflicts being fixed.

**Comment by rtpsw** [comment]
@westonpace, I moved forward with resolving the conflicts.

**Comment by rtpsw** [comment]
Looks like the CI failures are unrelated to the changes.

**Comment by westonpace** [comment]
Closing my stale PRs

**Pull request closed without merging**
