### PR TITLE
ARROW-1984: [Java] Make DateMilliVector.getObject() return a LocalDate

### PR DESCRIPTION
**Pull request by yongbozhang**
See issue description at https://issues.apache.org/jira/browse/ARROW-1984
Note: this is a API breaking change.

### CODE REVIEW

**Comment by wesm** [comment]
Can you start a mailing list discussion about this?

**Comment by emkornfield** [comment]
Per discussion on mailing list can we revise this to make the accessor a new method

**Comment by emkornfield** [comment]
@yongbozhang do you want to proceed with the outcome of the mailing list discussion?

**Comment by yongbozhang** [comment]
@emkornfield  I don't think adding a helper method like getDate() in DateMilliVector.java will help the situation too much (people most possibly will still firstly call getObject and get surprised) or maybe I don't have enough knowledge to make the judgement. I'm reading more documentations to understand the project better, e.g. how getObject() is used. Meanwhile, please proceed without me if you think that's the right fix.

**Comment by emkornfield** [comment]
I believe getObject is mostly meant for debugging/potentially final conversion to java.  We can always revisit this if it seems to be an issue that other people are surprised by.  Thanks for the PR, I'll close for now.

**Pull request closed without merging**
