### PR TITLE
ARROW-9279: [C++] Implement PrettyPrint for Scalars

### PR DESCRIPTION
**Pull request by tianchen92**

### CODE REVIEW

**Comment by nealrichardson** [comment]
@tianchen92 could you please rebase this? would you like to try to get this in the 2.0 release?

@pitrou could you please take a look?

**Comment by pitrou** [comment]
This is too involved for the 2.0 release.

**Comment by tianchen92** [comment]
@pitrou @nealrichardson Sorry for the delay, I have rebased this PR.

**Comment by bkietz** [comment]
Closing this for now

**Pull request closed without merging**
