### PR TITLE
ARROW-16313: [R] Ensure assume_timezone options are always initialized

### PR DESCRIPTION
**Pull request by pitrou**

### CODE REVIEW

**Review by kszucs — APPROVED** [review]

**Comment by kszucs** [comment]
@pitrou should this resolve https://issues.apache.org/jira/browse/ARROW-16298 as well?

**Comment by thisisnic** [comment]
@github-actions crossbow submit  test-fedora-r-clang-sanitizer

**Comment by thisisnic** [comment]
@github-actions crossbow submit test-ubuntu-18.04-r-sanitizer

**Comment by thisisnic** [comment]
Wasn't sure either @kszucs so have triggered those builds above.

**Comment by pitrou** [comment]
@github-actions crossbow submit -g r

**Comment by pitrou** [comment]
It should, it's the same error (I hadn't seen the JIRA? sorry).

**Comment by pitrou** [comment]
@github-actions crossbow submit -g r

**Comment by pitrou** [comment]
The only error remaining in test-fedora-r-clang-sanitizer is the usual Snappy issue.

**Comment by kszucs** [comment]
Thanks for fixing it! Merging.

**Pull request closed without merging**
