### PR TITLE
ARROW-8081: [Plasma] Fix memory limit bug & improve code

### PR DESCRIPTION
**Pull request by suquark**
This PR fixes https://issues.apache.org/jira/browse/ARROW-8081

The memory limit was set at the `getopt` section. I fix it by moving this part to somewhere later than the huge pages section. Also I find mixed use of `char *` and `std::string` for socket names, and now they are all using `std::string` now.

Also convert `ARROW_CHECK_OK` to `ASSERT_OK` because all other unit tests in Arrow are using `ASSERT_OK`  now.

### CODE REVIEW

**Comment by suquark** [comment]
Ready for review now.

**Comment by suquark** [comment]
Hi @pcmoritz, could you help reviewing this PR? Thanks!

**Comment by suquark** [comment]
Re-trigger all tests since there are random failures.

**Comment by emkornfield** [comment]
Hi @suquark sorry for the late response.  It looks like there are merge conflicts now, would you mind rebasing and I can take a look afterwards?

**Comment by wesm** [comment]
@suquark could you take a look?

**Comment by wesm** [comment]
I'm closing this. We need to have a discussion about the future of this code on the mailing list

**Pull request closed without merging**
