### PR TITLE
ARROW-16638: [Go][Parquet] Fix skipping large number of rows in boolean columns

### PR DESCRIPTION
**Pull request by mdepero**
Boolean columns still have an issue when skipping a large number of rows, due to the buffer passed for `values` not being large enough. If batch size to skip is 1024, the buffer allocated for values when skipping a boolean column is only 128, resulting in an index out of bounds panic.

This PR assumes the buffer passed for `values` when skipping a boolean column contains 1 byte per 8 bool values, and explicitly creates a bool slice with `len(buf)*8` capacity.

### CODE REVIEW

**Comment by mdepero** [comment]
@zeroshade note that this PR allocates additional memory to skip, but I don't see a much better way to patch given how the generic column reader [allocates scratch space](https://github.com/apache/arrow/blob/master/go/parquet/file/column_reader.go#L439) and there not being a good way [to convert](https://github.com/apache/arrow/blob/master/go/parquet/file/column_reader_types.gen.go#L209-L211) a `[]byte` buffer into `[]bool` where 8 bool values map to each byte?

**Comment by zeroshade** [comment]
@mdepero In the `parquet/internal/utils` package there is a function `BytesToBools` which explicitly is an efficient conversion from bitpacked bytes to a `[]bool`. It assumes that the slices are already sized appropriately (`len(out)` should equal `len(in)*8`).

That being said, there might be a way we can get around this by changing the implementation slightly. 

Since the `columnChunkReader` is embedded in the typed readers, we don't "technically" need to do `cr.columnChunkReader.skipValues(...` and could instead do `cr.skipValues(...`. I only specified the `cr.columnChunkReader` portion to make it explicit. The benefit there if we convert it to being just `cr.skipValues` is that we can then override the `skipValues` function for the `BooleanColumnChunkReader` to allocate the *correct* amount of scratch space, it does result in some duplication of code but I think it's a better solution to avoid the extra allocation where possible. As another, forward looking idea, I'd probably want to have the scratch space use a pool of buffers rather than allocating a new scratch space for every skip but that can be done as a later change. Anyways, did that all make sense as something you could do? 

Let me know if you have any questions. Thanks again for this!

**Comment by mdepero** [comment]
@zeroshade My understanding of `BytesToBools` would still require separately allocated memory for bytes and bools, and it just copies the values from byte encoding to []bool's?

Assuming `make([]bool, n)` only allocates 1 byte per 8 bool values, is it better to do two allocations each of size (n/8) bytes or one allocation of size (n) bytes? I've pushed a new version that retains the scratch space and only allocates once, but that one allocation is now n bytes since the cast from `[]byte` to `[]bool` creates 1 bool per 1 bytes. I do agree it's a bit hacky to simply ignore the buf passed into the skipValues readFn, which approach do you recommend?

**Comment by mdepero** [comment]
@zeroshade SGTM, referenced a new Jira issue in the TODO. Thanks!

**Comment by zeroshade** [comment]
@mdepero Perfect! once the Travis builds finish and succeed i'll merge this!

Thanks again!

**Pull request closed without merging**
