### PR TITLE
ARROW-11488: [Rust] Don't leak memory in StructBuilder

### PR DESCRIPTION
**Pull request by sfackler**
This PR fixes the following MIRI error (example from  https://github.com/apache/arrow/pull/9373/checks?check_run_id=1830406627):

```
test array::builder::tests::test_string_dictionary_builder_with_reserved_null_value ... ok
error: Undefined Behavior: trying to reborrow for SharedReadWrite at alloc9600855, but parent tag <26451274> does not have an appropriate item in the borrow stack
    --> arrow/src/array/builder.rs:1434:9
     |
1434 |         self.field_anys[i].downcast_mut::<T>()
     |         ^^^^^^^^^^^^^^^^^^ trying to reborrow for SharedReadWrite at alloc9600855, but parent tag <26451274> does not have an appropriate item in the borrow stack
     |
     = help: this indicates a potential bug in the program: it performed an invalid operation, but the rules it violated are still experimental
     = help: see https://github.com/rust-lang/unsafe-code-guidelines/blob/master/wip/stacked-borrows.md for further information
             
     = note: inside `array::builder::StructBuilder::field_builder::<array::builder::GenericStringBuilder<i32>>` at arrow/src/array/builder.rs:1434:9
note: inside `array::builder::tests::test_struct_array_builder` at arrow/src/array/builder.rs:2824:30
    --> arrow/src/array/builder.rs:2824:30
     |
2824 |           let string_builder = builder
     |  ______________________________^
2825 | |             .field_builder::<StringBuilder>(0)
     | |______________________________________________^
note: inside closure at arrow/src/array/builder.rs:2810:5
    --> arrow/src/array/builder.rs:2810:5
     |
2810 | /     fn test_struct_array_builder() {
2811 | |         let string_builder = StringBuilder::new(4);
2812 | |         let int_builder = Int32Builder::new(4);
2813 | |
...    |
2889 | |         }
2890 | |     }
     | |_____^
     = note: inside `<[closure@arrow/src/array/builder.rs:2810:5: 2890:6] as 
```

### CODE REVIEW

**Comment by vertexclique** [comment]
Miri checks have caught this in here:
https://github.com/apache/arrow/runs/1729267740#step:5:676

It shouldn't error out in Miri runs after this PR.

**Review by alamb — COMMENTED** [review]
Thanks @sfackler  for the contribution! Fixing bugs by deleting code is 👌  -- I can't wait to see how this change fares in CI

FWIW I ran this PR locally like this:
```
`$ MIRIFLAGS="-Zmiri-disable-isolation" cargo +nightly miri test -- test_struct_array_builder
```

And it passed for me 👍  with your PR while it fails on master. I am feeling optimisitic!

**Review by alamb — APPROVED** [review]

**Review by jorgecarleitao — APPROVED** [review]
Thanks a lot for this. LGTM :)

**Review by sunchao — APPROVED** [review]
+1 on removing some unsafe code. I'm curious how it leaks memory though - isn't the vector dropped in the end?

**Comment by sfackler** [comment]
Calling mem::forget on the `Vec<Box<dyn ArrayBuilder>>` prevents the vector's destructor from running.

**Comment by alamb** [comment]
I double checked that MIRI made if farther than it used to  so 🎉  It still isn't clean but the error in struct builder is no longer present

https://github.com/apache/arrow/pull/9409/checks?check_run_id=1826096427

**Comment by sunchao** [comment]
> Calling mem::forget on the Vec<Box<dyn ArrayBuilder>> prevents the vector's destructor from running.

Hmm isn't that the purpose? 
```rust
        let builders = std::mem::replace(&mut self.field_builders, Vec::new());
        std::mem::forget(builders);
```
the `builders` is forgotten here but the destructor for `self.field_any` will still be invoked right?

**Comment by sfackler** [comment]
field_any does not free the memory used for builders's vector. It does free the builders themselves, but that is a separate thing.

**Pull request closed without merging**
