### PR TITLE
[WIP] [C++] DenseUnionArray

### PR DESCRIPTION
**Pull request by pcmoritz**
This is work in progress, a first pass at implementing DenseUnionArray for Arrow. It is ported over from https://github.com/ray-project/arrow/commit/0707062979e99e136656bf7ebfda7f4eb722b5ce.

### CODE REVIEW

**Comment by wesm** [comment]
ARROW-373 contained a bit of refactoring so you'll need to rebase, sorry about that

**Comment by pcmoritz** [comment]
Thanks for letting me know! Going forward, do you want to have only one union array class and make it dense or sparse depending on the type field?

**Comment by wesm** [comment]
that seems acceptable for now, we may want dedicated container classes at some point, though.

**Comment by wesm** [comment]
@pcmoritz how would you like to proceed? In the course of implementing unions, we'll also want to add integration tests once ARROW-394 and associated JIRAs are in

**Comment by pcmoritz** [comment]
Let's try to get this in a form where it is mergeable, this means making the equals function work and having some more tests on the C++ side. I can't yet promise how soon I'll get to that, I hope I'll have time next week. I'm happy if somebody continues on it earlier if this is blocking.

We also should make sure that we have some specification of the binary format so Java and C++ use the same format of course.

**Comment by wesm** [comment]
@pcmoritz this is specified in https://github.com/apache/arrow/blob/master/java/vector/src/main/java/org/apache/arrow/vector/schema/TypeLayout.java#L67

**Comment by wesm** [comment]
Since I've done a lot of work recently on the IPC code and integration testing and have that all fresh in my head, I'll go ahead and do the union implementation in the next week or two. Will report back

**Pull request closed without merging**
