### PR TITLE
ARROW-742: [C++] Use gflags from toolchain; Resolve cmake FindGFlags …

### PR DESCRIPTION
**Pull request by maxhora**
…and FindGTest Windows issues.

### CODE REVIEW

**Review by xhochy — APPROVED** [review]
+1, LGTM

**Comment by wesm** [comment]
This is breaking my local toolchain builds on Linux. Investigating

**Comment by MaxRis** [comment]
@wesm , I have not tested changes on Linux, but maybe you need to remove all previously generated cmakefiles and run cmake again. Might ${GFLAGS_HOME} is not set correctly.

**Comment by wesm** [comment]
It was missing the static library suffix, fixed in #763

**Pull request closed without merging**
