### PR TITLE
ARROW-2570: [Python] Add support for writing parquet files with LZ4 compression

### PR DESCRIPTION
**Pull request by veprbl**

### CODE REVIEW

**Review by pitrou — APPROVED** [review]
LGTM.

**Comment by pitrou** [comment]
Thanks @veprbl ! The AppVeyor failure looks unrelated.

**Comment by pitrou** [comment]
@veprbl can you auto-assign the JIRA issue to yourself?

**Comment by veprbl** [comment]
@pitrou I were not able to self assign a JIRA issue. Perhaps there are not enough permissions for me to do that or I couldn't find the option. If you can, feel free to assign me.

**Comment by pitrou** [comment]
I think @xhochy can give you the permissions.

**Comment by xhochy** [comment]
@veprbl Assigned to issue to you.

**Pull request closed without merging**
