### PR TITLE
GH-43249: [C++][Parquet] remove useless template parameter of `DeltaLengthByteArrayEncoder`

### PR DESCRIPTION
**Pull request by IndifferentArea**
### Rationale for this change

see https://github.com/apache/arrow/issues/43249

### What changes are included in this PR?

remove template parameter of DeltaLengthByteArrayEncoder

### Are these changes tested?

Covered by existing

### Are there any user-facing changes?

No.

* GitHub Issue: #43249

### CODE REVIEW

**Review by mapleFU — APPROVED** [review]
Give my +1 because https://github.com/apache/parquet-format/blob/master/Encodings.md#delta-length-byte-array-delta_length_byte_array--6 only supports ByteArray

The DELTA_BYTE_ARRAY might uses this because it uses DeltaLengthByteArray but might also works for FLBA. But I think only one encoder type is enough, cc @rok @pitrou for idea

**Review by pitrou — APPROVED** [review]
+1, LGTM

**Review by rok — APPROVED** [review]
Looks good!

**Comment by mapleFU** [comment]
Thanks all, merged

**Pull request merged**
