### PR TITLE
ARROW-3159: [Plasma] Plasma tensor writing c++/python integration test

### PR DESCRIPTION
**Pull request by pcmoritz**

### CODE REVIEW

**Comment by pitrou** [comment]
@pcmoritz Do you want to revive this PR?

**Comment by wesm** [comment]
This seems like it would be easy to rebase. @pcmoritz do you have a moment to look into it? I think we might have a better approach to handle the threading library argument

**Comment by pcmoritz** [comment]
Yeah, I can get this merged!

**Comment by emkornfield** [comment]
@pcmoritz are you still planning on working on this, otherwise I think we should probably close it.

**Comment by bkietz** [comment]
@pcmoritz closing this for now

**Pull request closed without merging**
