### PR TITLE
ARROW-6860: [Python][C++] Do not link shared libraries monolithically to pyarrow.lib, add libarrow_python_flight.so

### PR DESCRIPTION
**Pull request by wesm**
Adding a new shared library libarrow_python_flight.so that allows us to link libarrow_flight and this new library to the Cython _flight extension. I initially tried moving the Flight Python bindings directly to libarrow_flight but realized this would create a transitive dependency on libpython which is not desirable. Any shared library that uses Python C APIs is expected to be loaded into a running Python interpreter and not linked explicitly to libpython

Because Apache ORC also needs to statically link Protocol Buffers, I have disabled it in the manylinux wheels. Hopefully we can come up with a solution where projects like Apache Beam, TensorFlow, and others can all use Protocol Buffers together and not have these problems

### CODE REVIEW

**Comment by wesm** [comment]
Hm, it looks like this strategy isn't going to work. I'll have to generate `libarrow_flight_python.so`. Stay tuned

**Comment by wesm** [comment]
OK, I think I have done it (modulo unit tests)

**Review by lidavidm — APPROVED** [review]
Looks good pending CI.

FWIW, we've resorted to only ever linking dynamically to avoid issues around Protobuf/gRPC...

**Comment by wesm** [comment]
Ah. Suggests we should might bundle protobuf shared libs in the pyarrow wheel. Fun times

**Comment by lidavidm** [comment]
> Ah. Suggests we should might bundle protobuf shared libs in the pyarrow wheel. Fun times

I think that actually won't help, on further thought :( The Protobuf manylinux1 wheel statically links Protobuf.

**Comment by wesm** [comment]
+1

**Pull request closed without merging**
