### PR TITLE
ARROW-1826: [JAVA] Avoid branching in copyFrom for fixed width scalars

### PR DESCRIPTION
**Pull request by siddharthteotia**
cc @jacques-n , @BryanCutler , @icexelloss 

Note: there was no performance regression or different behavior introduced as part of refactor patches.

This is something I had noticed in the old code during refactoring but lost track of it. copyFrom function for fixed width scalars does a double check if the cell in the source vector is NULL or not. The old code used to do the same.

There is a straightforward way to avoid double check but the new changes avoid branch all-together; since it is fine to copy garbage from source vector as long as the validity bit is copied correctly to indicate NULL or non-NULL value in the target cell.

Will add unit tests.

### CODE REVIEW

**Comment by icexelloss** [comment]
Looks good. Please add unit test.

**Comment by jacques-n** [comment]
lgtm. Agree that unit test would be good if we don't already have them.

**Comment by siddharthteotia** [comment]
This can be merged. Added unit tests as necessary.

**Comment by jacques-n** [comment]
Looks good +1

@siddharthteotia, can you merge this? No need to rely on Wes to do these things.

**Comment by BryanCutler** [comment]
+1

**Comment by wesm** [comment]
Merging in case Sidd hasn't got the Gitbox stuff set up yet

**Comment by siddharthteotia** [comment]
@wesm , just finished that setup

**Comment by siddharthteotia** [comment]
I was late by a few milli seconds I guess :)

**Pull request closed without merging**
