### PR TITLE
ARROW-1983: [C++/Python][WIP] Implement metadata writing support

### PR DESCRIPTION
**Pull request by pearu**
This PR adds another sink to parquet writers for collecting metadata of datasets.

- [x] Implement reader for the metadata file of a dataset
- [x] Implement tests

### CODE REVIEW

**Comment by wesm** [comment]
I'm away until 4/22 but will look more closely at this then.

**Review by wesm — COMMENTED** [review]
At a glance, I'm not fond of this approach to solving the problem. Many new constructor APIs are introduced and this seems to introduce a lot of boilerplate and complexity. 

It seems like what is required is a public API on `parquet::ParquetFileWriter` to write that file's metadata to an in-progress _metadata file once the file is completed. The C++ logic surrounding the read and write of the `_metadata` file may benefit from some convenience classes. Does this sound right?

**Comment by wesm** [comment]
Right, I think the approach would be to add a method to `ParquetWriter` in `_parquet.pyx` that appends that file's metadata to an in-progress _metadata file.

Where is the _metadata file format (with concatenated metadata like this) documented, or is it a convention of Hive and/or Spark?

**Comment by pearu** [comment]
Re concatenated metadata file format documentation: there is none to my knowledge (which may be limited on this matter).

**Comment by hatemhelal** [comment]
> Where is the _metadata file format (with concatenated metadata like this) documented, or is it a convention of Hive and/or Spark?

I tried finding a document for this and eventually found my way to [ParquetFileWriter.java](https://github.com/apache/parquet-mr/blob/master/parquet-hadoop/src/main/java/org/apache/parquet/hadoop/ParquetFileWriter.java#L933) which are marked as deprecated.  

It would be helpful to know more about the background for that decision but I haven't been able to glean much from the git logs or the related JIRAs.

**Comment by martindurant** [comment]
Commenting here, as on JIRA my comment seems to have been swallowed (please forgive if they pop back out again later)

I don't know about deprecated, and I wouldn't hold my breath over a Parquet 2.0... the metadata file is very useful in the context of Dask, so that we can know what files exist in the dataset without doing a glob, and we can do simple filtering on max/min values without having to touch every file, which can be very slow on remote storage.

The spec certainly allows for a metadata file even if it could be seen as more of a convention from Hive: a column chunk allows for a file_path attribute, indicating that the data itself is in another file (which, actually, doesn't need to be a proper parquet file, but in practice always is).

You could indeed construct the metadata by repeatedly appending to a file, since you will know that everything in the file is the thrift footer block except for the PAR1 bytes. However, you will not preserve row-group order in general, which might be important, and writes had better be atomic. Furthermore, remote storage will usually *not allow* small appends from multiple processes in this way.

**Comment by pearu** [comment]
> Furthermore, remote storage will usually _not allow_ small appends from multiple processes in this way.

The "multiple processes" part must be something that Dask does and is not directly relevant to Arrow that always writes a dataset from a single process. Do you have recommendations what the Arrow dataset creation interface should be? One approach would be that when datasets from multiple processes are written (say, by Arrow `write_to_dataset`) then at the end one would collect and merge the _metadata files (from different processes) to one?

**Comment by pearu** [comment]
The deprecation notes to ParquetFileWriter.java were introduces in https://github.com/apache/parquet-mr/pull/429 . It's not clear to me what is are the alternatives to having metadata files.

**Comment by martindurant** [comment]
I imagine just having the write-a-partition (i.e., dataframe or table to file) also return the piece object, and then a separate function that takes a set of piece objects and creates a metadata file from them. An arrow function can do the two steps in one, or Dask can collect the output pieces, depending on how this is called. The only wrinkle is, that the output piece objects will need to have the paths within them set to be relative to the root directory of the dataset.

**Comment by mrocklin** [comment]
To echo what @martindurant is saying, we definitely don't want a function that appends a bit of metadata to a metadata file.  We want to be able to get the metadata from a row group and pass that around as data.  We'd like to move all of those pieces of metadata to one process and then have that one process combine them and write the metadata file in one shot.

**Comment by wesm** [comment]
Not sure how to proceed from here. Do you want me to take over this project?

**Comment by mrocklin** [comment]
> Not sure how to proceed from here. Do you want me to take over this project?

I'm not sure if that's directed to me.  If so, I have no preferences on who does this work (as long as it isn't me :) )

**Comment by wesm** [comment]
`FileMetaData` is already serializable: https://github.com/apache/arrow/blob/master/python/pyarrow/_parquet.pyx#L378. We could add a C++ function that takes a collection of `FileMetaData` and concatenates them to produce the `_metadata` file (this would save you from having to do this munging logic in Dask).

One minor issue I see currently is that the `file_path` attribute in `ColumnChunk` is not being set. We'll have to add a method on `parquet::ParquetFileWriter` to add a path (since the file path is not part of any constructor) so that this field gets populated when the metadata is being built. 

I think I understand what is required so if @pearu can let me know what he wants to do we can go from there

**Comment by pearu** [comment]
I would be happy to finish this task but need some guidance to ensure that the implementation follows Arrows principles and be usable by Dask.

When writing a table to parquet file (Python `write_table` function), I don't see how one can collect the `FileMetaData` instances as the FileMetaData instance is created in `FileSerializer::Close` as local variable and `Close` is called in the destructor. There is one way but that might be suboptimal: read the `FileMetaData` from the footer of the dataset piece.
@wesm , have you thought about where or how the collection of `FileMetaData` should be created?

**Comment by martindurant** [comment]
Reading back from the file certainly seems suboptimal, and with remote storage maybe not possible (because they may not promise immediate consistency)

**Comment by wesm** [comment]
@pearu I haven't looked closely yet but I would suggest an idempotent `Finalize` method and storing the finalized metadata in the writer object

**Comment by pearu** [comment]
https://github.com/apache/arrow/compare/master...Quansight:pearu/arrow-1983-2 introduces `ParquetFileWriter::metadata` that finalizes and returns file metadata instance (as `shared_ptr`).

To get a hang of the file metadata after writing the table, I would introduce a new method (or alter the current method with the third argument)
```
::arrow::Status FileWriter::WriteTable(const ::arrow::Table& table,
                                       int64_t chunk_size,
                                       std::unique_ptr<FileMetaData>* file_metadata);
```

In Python, `ParquetWriter.write_table` would return the file metadata instance (or set the `ParquetWriter.metadata` attribute after writing).

@wesm , does the above sound a reasonable approach?

**Comment by wesm** [comment]
@pearu `FileWriter::WriteTable` can be called multiple times, so I would add a method like `FileWriter::metadata` or `FileWriter::GetMetadata`. I am not sure if it is possible off hand to obtain the metadata without rendering the `FileWriter` object unusable, but I am not sure we need to worry too much about the object being used if it is in an unusable state as long as we document it clearly for the time being

**Comment by pearu** [comment]
I have added `FileWriter::metadata` method and exposed this to Python.
In order to retrieve file metadata, the writer `close` must be called as it triggers the rendering. On the other hand, `ParquetFileWriter::Close` also resets `contents_` that holds the file metadata instance. Disabling `contents_.reset()` (so data file metadata instance is kept alive) allows getting the metadata via Python `ParquetWriter.metadata` property.
I think there are two options re enabling  `contents_.reset()`:
1. either move the file metadata instance out of the `Contents` so that it will be kept alive after `Close` call
2. or split the `Close` method into `Finalize` and `Close` so that the file metadata can be retrieved only after calling `Finalize` and before calling `Close`. Before `Finalize` and after `Close` the file metadata would not be available.

@wesm, what to do you think?

**Comment by pearu** [comment]
Never mind, I found a cleaner solution: add file metadata shared ptr to ParquetFileWriter that will be initialized after calling `Close` and before resetting `contents_` in `ParquetFileWriter::Close`.

**Comment by jorisvandenbossche** [comment]
@pearu can this PR be closed, or does it still contain useful content (for writing metadata?) that was not merged in the other PR #4236 ?

**Comment by pearu** [comment]
Yes, this can be closed as the approach of resolving the original issue in PR #4236 is different.

**Pull request closed without merging**
