### PR TITLE
ARROW-5435: [Java] Add test for IntervalYearVector#getAsStringBuilder

### PR DESCRIPTION
**Pull request by tianchen92**
Related to [ARROW-5435](https://issues.apache.org/jira/browse/ARROW-5435).
This adds a test for `IntervalYearVector.getAsStringBuilder`.

### CODE REVIEW

**Comment by tianchen92** [comment]
cc @emkornfield

**Comment by jacques-n** [comment]
-1. This seems like something that should be done in application layer, not Arrow. The internal representation is months, not years and months and we shouldn't be doing arbitrary math between equivalent periods in the base impl.

**Comment by tianchen92** [comment]
@jacques-n Two questions:
1. Before [ARROW-2015](https://issues.apache.org/jira/browse/ARROW-2015), getMethod return Period with year and month, Was it intentional to change that now return Period with total month?
2. getAsStringBuilder returns string like "2 years 3 months", this should also be done in application layer and here just return "27 months"?
thanks!

**Comment by emkornfield** [comment]
@jacques-n based on your feedback, I think fixing the asString builder to only output months makes sense?

**Comment by tianchen92** [comment]
@emkornfield @jacques-n Should I do some work on this or just close this PR? Thanks

**Comment by emkornfield** [comment]
My thoughts: I think ideally the toString should be consistent with the data but I agree with @jacques-n that we probably shouldn't normalize the underlying data.  

@BryanCutler I think you did the refactor to include java8 types, do you have more context on this?

**Comment by tianchen92** [comment]
@emkornfield Thanks a lot for your feedback. I fixed the behavior of getAsStringBuilder, please help take a look.

**Comment by BryanCutler** [comment]
>-1. This seems like something that should be done in application layer, not Arrow. The internal representation is months, not years and months and we shouldn't be doing arbitrary math between equivalent periods in the base impl.

I agree with this. Also, I think `getAsStringBuilder()` was meant to put the the internal data in a more readable format, so it makes sense to display it as years/months/days.

**Comment by BryanCutler** [comment]
@tianchen92 it would be great if you could make your test work for `getAsStringBuilder`. It doesn't look like it is currently tested.

**Comment by tianchen92** [comment]
> @tianchen92 it would be great if you could make your test work for `getAsStringBuilder`. It doesn't look like it is currently tested.

Sure, I updated this PR, please take a look, thanks a lot!

**Review by BryanCutler — APPROVED** [review]
LGTM

**Comment by BryanCutler** [comment]
Merged to master, thanks @tianchen92 !

**Pull request closed without merging**
