### PR TITLE
[TEST] Revert "ARROW-11475: [C++] Upgrade mimalloc"

### PR DESCRIPTION
**Pull request by dianaclarke**
This reverts commit 8780ca4b12d30a0118c3114edcad27da907d8e7c.

### CODE REVIEW

**Comment by dianaclarke** [comment]
@ursabot please benchmark

**Comment by dianaclarke** [comment]
@ursabot please benchmark

**Comment by dianaclarke** [comment]
@ursabot please benchmark

**Comment by pitrou** [comment]
Should we keep this PR open now that mimalloc has been reverted in git master?

**Comment by dianaclarke** [comment]
I'm still playing with these numbers. So far, I know:

All of the benchmarks that either improved or regressed with mimalloc version 2 were C++ benchmarks. None were Python or R benchmarks.

I wrote a little script that first created a skip list of any benchmark that regressed or improved in the placebo run on machine `ursa-thinkcentre-m75q` (which was 4% of the benchmarks). Then I generated a list of benchmarks that got better or worse under version 2 of mimalloc, minus that skip list.

With the skips in mind (at a threshold of 5%) 180 benchmarks got worse with version 2 of mimalloc, and 42 got better.

Here are the top 10 benchmarks that got worse.

```[114% worse, 'arrow-compute-scalar-cast-benchmark.CastInt64ToDoubleUnsafe, 524288/1000']
[114% worse, 'arrow-compute-scalar-cast-benchmark.CastInt64ToDoubleUnsafe, 524288/10']
[114% worse, 'arrow-compute-scalar-cast-benchmark.CastInt64ToDoubleUnsafe, 524288/1']
[115% worse, 'arrow-compute-scalar-cast-benchmark.CastInt64ToDoubleUnsafe, 524288/2']
[115% worse, 'arrow-compute-scalar-cast-benchmark.CastInt64ToDoubleUnsafe, 524288/0']
[124% worse, 'arrow-compute-scalar-string-benchmark.AsciiUpper']
[124% worse, 'arrow-compute-scalar-string-benchmark.AsciiLower']
[127% worse, 'arrow-io-memory-benchmark.BufferOutputStreamLargeWrites, real_time']
[137% worse, 'arrow-io-memory-benchmark.BufferOutputStreamSmallWrites, real_time']
[316% worse, 'arrow-compute-vector-selection-benchmark.TakeInt64RandomIndicesWithNulls, 524288/1']
```

And here are the top 10 that got better.

```[55% better, 'arrow-compute-scalar-arithmetic-benchmark.ArrayScalarKernel, <Add, Int32Type>/524288/0']
[55% better, 'arrow-compute-scalar-arithmetic-benchmark.ArrayScalarKernel, <Add, Int32Type>/524288/100']
[54% better, 'arrow-compute-scalar-arithmetic-benchmark.ArrayScalarKernel, <AddChecked, Int8Type>/524288/0']
[54% better, 'arrow-compute-scalar-arithmetic-benchmark.ArrayScalarKernel, <AddChecked, UInt8Type>/524288/0']
[42% better, 'arrow-compute-scalar-arithmetic-benchmark.ArrayScalarKernel, <AddChecked, UInt8Type>/524288/100']
[41% better, 'arrow-compute-scalar-arithmetic-benchmark.ArrayScalarKernel, <MultiplyChecked, Int8Type>/524288/100']
[30% better, 'arrow-compute-vector-sort-benchmark.ArraySortIndicesInt64Narrow, 32768/10000']
[25% better, 'arrow-compute-scalar-arithmetic-benchmark.ArrayScalarKernel, <Add, UInt32Type>/524288/100']
[25% better, 'arrow-compute-scalar-arithmetic-benchmark.ArrayScalarKernel, <Add, UInt32Type>/524288/0']
[25% better, 'arrow-compute-scalar-arithmetic-benchmark.ArrayScalarKernel, <Subtract, Int32Type>/524288/0']
```

So, if we want to try and track down the mimalloc bug in version 2, I would start with this benchmark since it regressed 316%.

`arrow-compute-vector-selection-benchmark.TakeInt64RandomIndicesWithNulls/524288/1`

**Comment by pitrou** [comment]
Hmm, most of the top/bottom 10 you're quoting look like false positives, as they shouldn't be memory allocation-heavy except for the `BufferOutputStream` benchmarks.

**Comment by dianaclarke** [comment]
They are stable on mimalloc-1.6 though... and when I toggle between mimalloc-1.6 & mimalloc-2.0, mimalloc-2.0 always shows a spike in regressions and mimalloc-1.6 is stable.

**Comment by pitrou** [comment]
If I run `AsciiLower` manually, for example, I don't see any difference between mimalloc 1.6 and 2.0, even accross multiple runs. That's on Ubuntu 20.04 with gcc 9.

**Comment by pitrou** [comment]
I've tried `CastInt64ToDoubleUnsafe` and `TakeInt64RandomIndicesWithNulls` as well and, while they show a bit more variation from run to run, I don't see any obvious regression between the two mimalloc versions...

**Comment by dianaclarke** [comment]
Thanks for testing locally, and providing more data points & clues!

I do think something is up here. Every run with mimalloc-2.0 show a significantly higher number of regressions compared to all other runs. I have no clue why though.

I'll close this for now. We can always revisit when we try to bump it again. I had hoped to be able to provide the mimalloc team with a minimal reproducer, but I doubt I would be able to (given my lack of C++ experience).

**Pull request closed without merging**
