### PR TITLE
ARROW-1666: [GLib] Enable gtk-doc on Travis CI Mac environment

### PR DESCRIPTION
**Pull request by wagavulin**
The current build script for Travis CI (`ci/travis_before_script_c_glib.sh`) does not use `--enable-gtk-doc` option on Mac. Now it can be used also on Mac, so it should be enabled to check build status.

### CODE REVIEW

**Comment by kou** [comment]
Test on macOS is failed in building Arrow C++ before building Arrow GLib.
It's not expected. Parallel build by [`make -j4`](https://travis-ci.org/apache/arrow/jobs/287047542#L1945) may have a problem.

**Comment by wesm** [comment]
This seems like a transient error

```
dyld: lazy symbol binding failed: Symbol not found: _utimensat
  Referenced from: /usr/local/Cellar/cmake/3.9.4/bin/cmake
  Expected in: /usr/lib/libSystem.B.dylib
dyld: Symbol not found: _utimensat
  Referenced from: /usr/local/Cellar/cmake/3.9.4/bin/cmake
  Expected in: /usr/lib/libSystem.B.dylib
```

Can you rebase this PR and update the PR title to start with `ARROW-1666:`?

**Comment by wagavulin** [comment]
Thank you for your advice. I `rebase`d and `push`ed again, then Arrow C++ can be built now. However it failed to build Arrow Glib. I will investigate more.

**Comment by wesm** [comment]
Thank you. Please make sure also to capitalize the letters in the start of the PR title, so "ARROW-1666:" instead of "Arrow-1666". Our PR merge tool is case sensitive

**Comment by kou** [comment]
https://travis-ci.org/apache/arrow/jobs/290064651 (C++ on macOS) is failed because of timeout:

https://travis-ci.org/apache/arrow/jobs/290064651#L8466

```text
The job exceeded the maximum time limit for jobs, and has been terminated.
```

We may need to reduce build time. Anyway, it's not a scope of this pull request.

**Comment by kou** [comment]
https://travis-ci.org/apache/arrow/jobs/290064660
It seems that Arrow GLib test failure isn't our problem. The build isn't started. And the build is for Meson on Linux. It's not related of this pull request.

So +1. I'll merge this when I have time to do it and the title is fixed ("Arrow -> ARROW"). It'll be in a few days.
(If someone can merge this, you can do it.)

**Comment by wesm** [comment]
I can merge as soon as the title is fixed.

**Comment by kou** [comment]
Thanks!

**Comment by wagavulin** [comment]
I have updated the title. Thanks!

**Review by wesm — APPROVED** [review]
+1

**Pull request closed without merging**
