### PR TITLE
GH-41044: [C++] formatting.h: Make sure space is allocated for the 'Z' when formatting timestamps

### PR DESCRIPTION
**Pull request by felipecrv**
### What changes are included in this PR?

A test that reproduces an issue found by the fuzzer and a fix for it.

### Are these changes tested?

 - A test
 - Comments clarifying somethings around `formatting.h`
 - Increasing the size of the local buffer used to format timestamps

The issue was introduced only recently (unreleased): #39272
* GitHub Issue: #41044

### CODE REVIEW

**Review by kou — APPROVED** [review]
+1

**Review by zeroshade — APPROVED** [review]

**Comment by pitrou** [comment]
Thanks @felipecrv . The regression file must also be added to https://github.com/apache/arrow-testing/tree/master/data (which will test it in the ASAN UBSAN build).

**Comment by AlenkaF** [comment]
Thank you for fixing this @felipecrv!

**Comment by felipecrv** [comment]
> Thanks @felipecrv . The regression file must also be added to https://github.com/apache/arrow-testing/tree/master/data (which will test it in the ASAN UBSAN build).

Done here https://github.com/apache/arrow-testing/pull/100

@pitrou is `arrow-testing` bumped automatically or I should do it as well once the PR above is merged?

**Comment by pitrou** [comment]
It's a regular git submodule, so you should open a PR here to bump it.

**Comment by felipecrv** [comment]
> It's a regular git submodule, so you should open a PR here to bump it.

https://github.com/apache/arrow/pull/41139

**Pull request merged**
