### PR TITLE
ARROW-3943: [R] vignette

### PR DESCRIPTION
**Pull request by romainfrancois**

### CODE REVIEW

**Comment by xhochy** [comment]
@romainfrancois I wondering whether we could combine this into the general Sphinx documentation. We are currently merging the Python and C++ infrastructure with the general Arrow format documentation over at https://github.com/apache/arrow/pull/2856

Disclaimer: As I'm not an R expert, I have no idea how well this plays with the R ecosystem.

**Comment by romainfrancois** [comment]
Could be interesting. I have the opposite disclaimer though.

**Comment by xhochy** [comment]
@wesm As you know both worlds, can you help us here?

**Comment by xhochy** [comment]
So a vignette is a something between a TL;DR paragraph and the fully fledged package documentation? This means we would probably have the vignette and would write a fully featured documentation somewhere else? That sounds good to me.

**Comment by wesm** [comment]
Right, the vignette is something akin to a "getting started" guide

**Comment by nealrichardson** [comment]
This PR is stale and I think we should close it. The vignette content is a good start, and I'd be happy to help contribute to it on a new PR.

**Pull request closed without merging**
