### PR TITLE
ARROW-14792: [C++] Fix crash when reading DELTA_BYTE_ARRAY Parquet file

### PR DESCRIPTION
**Pull request by pitrou**
Should fix the following issues (found by OSS-Fuzz):

* https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=41221
* https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=41222

### CODE REVIEW

**Comment by pitrou** [comment]
@shanhuuang It looks like it would be desirable to have distinct tests for delta-encoded Parquet files with and without nulls (missing values). Would you like to do that as a separate JIRA/PR?

**Comment by shanhuuang** [comment]
> @shanhuuang It looks like it would be desirable to have distinct tests for delta-encoded Parquet files with and without nulls (missing values). Would you like to do that as a separate JIRA/PR?

Yes, I'll do it during this week :)

**Comment by pitrou** [comment]
@shanhuuang Other than that, does this PR look ok?

**Comment by shanhuuang** [comment]
> @shanhuuang Other than that, does this PR look ok?

Yes, it looks good to me. It's pretty nice to use `VisitNullBitmapInline`

**Comment by pitrou** [comment]
I will merge then. Thank you!

**Pull request closed without merging**
