### PR TITLE
ARROW-12400: [Rust] Re-enable tests in arrow::array::transform

### PR DESCRIPTION
**Pull request by tustvold**
These tests were all commented out in #9329. Given the PR made changes to the commented out code, I'm inclined to think this was an accidental omission? If not, happy for this to be closed :grinning: 

FYI @jorgecarleitao 

Signed-off-by: Raphael Taylor-Davies <r.taylordavies@googlemail.com>

### CODE REVIEW

**Review by alamb — APPROVED** [review]
Thank you @tustvold

**Review by jorgecarleitao — APPROVED** [review]
Thanks a lot, @tustvold  👍

**Comment by kszucs** [comment]
@andygrove I assume we'd like to have it in the release.

**Comment by alamb** [comment]
> @andygrove I assume we'd like to have it in the release.


FWIW @kszucs  I don't think this is something that we should hold the release for -- it does not have any change to the actual code, only the tests.

**Comment by kszucs** [comment]
Ok, thought that implementation was affected as well. I'm still waiting for other PRs so feel free to merge on green.

**Pull request closed without merging**
