### PR TITLE
ARROW-7165: [C++] passing memory table to hash functions

### PR DESCRIPTION
**Pull request by xuechendi**
This PR is to propose some ideas to support groupby in arrow compute.
In [JIRA 7165](https://issues.apache.org/jira/browse/ARROW-7165), I summarized some steps in my opinion which is required to support groupby.
1. change functions in arrow/compute/hash to support a input memo_table.(In this PR)
2. add splitarray function to use dict encode array as input to split current array. I know we have "take", split is quite like "take", while produces multiple array as output.(in comming PR, codes are done)
So I hope I can get some input here, to see if this is a right path, or you guys already have another plan.
=================
In this PR, I moved memo_table from inside RegularHashKernelImpl class member to the API function, so user can either pass memo_table or init memo_table there.

Signed-off-by: Chendi Xue <chendi.xue@intel.com>

### CODE REVIEW

**Comment by xuechendi** [comment]
@wesm , I think you have some works in arrow/compute, hope you can give me some feedback.

**Comment by wesm** [comment]
I'm a bit hesitant to express views one way or another without seeing an implementation of a hash aggregation fully worked out. Does that make sense?

**Comment by xuechendi** [comment]
> I'm a bit hesitant to express views one way or another without seeing an implementation of a hash aggregation fully worked out. Does that make sense?

I see, my current "group by hash aggregation" is a combination of "encode dict" + "splitarray" + "aggregate", hope below graph can make my design more clear, after getting a encodedArray from the grouping column, we can use that encodedArray to split all arrays in one batch and then perform aggregate to each array. 
groupby_hash_aggregate
and we can use one hash_table(memo_table) for multiple batches so data within same group from different batches can be splitted into same array.
I have completed all codes in my side, while I felt it will be a ton of effort to fix the naming convention for arrow, so I hope I can get some input firstly of knowing if you want to see such an implementation?

**Comment by xuechendi** [comment]
@wesm , and that is why I submitted the first PR(this one), to make hash_table as an input argument for methods inside arrow/compute/kernels/hash.h

**Comment by xuechendi** [comment]
@wesm , so despite of the whole "GroupBy hash aggregation" design, do you think this PR makes sense to you, if so, I will work on the CI issue fixing. If you don't think this PR makes sense, I will close it.

**Comment by wesm** [comment]
In general, I am not in favor of "speculative" refactoring. Since there are no unit tests in this patch, that's how this seems to me. I think we need to take a step back and have a broader discussion about the implementation strategy for hash aggregations and other grouping algortihms. Once a strategy has been agreed upon, I do not think we should be accepting any patch until a meaningful algorithm (and associated unit tests) have been implemented.

**Comment by xuechendi** [comment]
> In general, I am not in favor of "speculative" refactoring. Since there are no unit tests in this patch, that's how this seems to me. I think we need to take a step back and have a broader discussion about the implementation strategy for hash aggregations and other grouping algortihms. Once a strategy has been agreed upon, I do not think we should be accepting any patch until a meaningful algorithm (and associated unit tests) have been implemented.

I see, thanks, @wesm , is there a development discussion meeting we can attend to propose our idea of groupby hash aggregation, or we simply submit design doc on JIRA so anyone interested will comment on that? Which is a prefer way?

**Comment by xuechendi** [comment]
@wesm , and for this PR, I apologize that I missed to submit unit tests as well, so it looks like a 'patch' to you, actually it is more like a new interface, anyway, I can either add a unittest to make it more clear to you, or we can have a broader discussion on the whole plan firstly, and hold on this PR our we have an agreement on the design path.

**Comment by wesm** [comment]
@xuechendi the appropriate place would be the dev@ mailing list -- you can create JIRA issues that map onto the concrete development steps. To reiterate, it's fine if the project takes a while or yields a large pull request, but I think we need to get the target algorithm (for example, a hash/group sum) fully worked out so that we can assess whether the implementation approach is valid.

**Comment by xuechendi** [comment]
@wesm , I see, thanks so much for the information, I'll send to dev@ maillist. :)

**Comment by wesm** [comment]
Closing. I think some more discussion about hash aggregation is required, let's do that and then decide what code changes are necessary

**Pull request closed without merging**
