### PR TITLE
ARROW-6130: [Release] Use 0.15.0 as the next release

### PR DESCRIPTION
**Pull request by kou**
See discussion on the mailing list:
[Discuss] Do a 0.15.0 release before 1.0.0?
https://lists.apache.org/thread.html/98b59e461c8937d33660214028dcd78a47f52fbb762217d996194941@%3Cdev.arrow.apache.org%3E

### CODE REVIEW

**Comment by kou** [comment]
@ursabot crossbow package -g linux

**Comment by kou** [comment]
These commits except 66362f8 are generated by the following command line:

```bash
PREPARE_DEFAULT=0 PREPARE_VERSION_POST_TAG=1 PREPARE_DEB_PACKAGE_NAMES=1 dev/release/00-prepare.sh 0.14.1 0.15.0
```

**Comment by kou** [comment]
Ah, we need to update versions in `java/**/pom.xml` too.

**Review by pitrou — COMMENTED** [review]
I had no idea the version number was hardcoded in so many places :-o Do you use an automated script to update them?

**Comment by kou** [comment]
Yes: https://github.com/apache/arrow/pull/5007#issuecomment-518039650

**Comment by wesm** [comment]
Can this be merged?

**Comment by kou** [comment]
Yes.

**Review by wesm — APPROVED** [review]
+1

**Pull request closed without merging**
