### PR TITLE
ARROW-8226: [Go] Implement 64 bit offsets binary builder

### PR DESCRIPTION
**Pull request by richardartoul**

### CODE REVIEW

**Comment by richardartoul** [comment]
@sbinet this is the new one

**Comment by richardartoul** [comment]
@wesm Mind taking a look at this?

**Comment by emkornfield** [comment]
ping @sbinet do you think you will have time to take a look?

**Comment by wesm** [comment]
Hm, at a high level it seems like it might be better to have a separate set of LargeBinary types rather than try to pack both 32-bit and 64-bit into the same types. This means some code duplication (given Go's current generics/templates situation) but perhaps for the best

**Comment by wesm** [comment]
@sbinet could you assist with this?

**Comment by richardartoul** [comment]
Just wanted to share that I probably can't contribute any more time to getting this merged, we've moved away from Arrow for our project (we still use the format in some cases, but its our own implementation of builders) at this. Nothing to do with the project itself, we just needed more control over allocations and serialization and it was easier for us if implemented it all ourselves

**Comment by wesm** [comment]
Well, that is definitely a bummer. I hope to see some growth in the Go developer community here in the future. I'll close this PR for now then

**Pull request closed without merging**
