### PR TITLE
ARROW-9261: [Python] Fix CA certificate lookup with S3 filesystem on manylinux

### PR DESCRIPTION
**Pull request by pitrou**
The AWS SDK on manylinux packages uses a custom-compiled libcurl that is configured for the certificates of the build system.  However, there's no standard location for CA certificates on Linux, so we must instead configure the filesystem layer at runtime with Python's own TLS configuration values (which are assumed to be correct, otherwise Python itself couldn't connect to TLS hosts).

### CODE REVIEW

**Comment by pitrou** [comment]
@github-actions crossbow submit -g wheel

**Comment by pitrou** [comment]
The manylinux import test [fails](https://dev.azure.com/ursa-labs/crossbow/_build/results?buildId=14018&view=logs&j=0da5d1d9-276d-5173-c4c4-9d4d4ed14fdb&t=3367cfe7-6aa5-5a88-c888-e6814d74f6eb&l=248) after removing `libz.so`, because it is necessary for some standard library modules.
@xhochy @kszucs Any idea how to circumvent this?

**Comment by xhochy** [comment]
> The manylinux import test [fails](https://dev.azure.com/ursa-labs/crossbow/_build/results?buildId=14018&view=logs&j=0da5d1d9-276d-5173-c4c4-9d4d4ed14fdb&t=3367cfe7-6aa5-5a88-c888-e6814d74f6eb&l=248) after removing `libz.so`, because it is necessary for some standard library modules.
> @xhochy @kszucs Any idea how to circumvent this?

Oh, where is this removing happening, do we do that in our scripts or is this `manylinux1`?

**Comment by pitrou** [comment]
@xhochy In https://github.com/apache/arrow/blob/master/dev/tasks/python-wheels/manylinux-test.sh#L33 . I'm sure there's a better way to do that (e.g. spawn a minimal Python docker image).

**Comment by pitrou** [comment]
Amusingly, even a minimal Debian or Ubuntu Docker image has `liblz4` and `liblzma`. I think we can simply change the script not to remove the zlib.

**Comment by pitrou** [comment]
@github-actions crossbow submit -g wheel

**Review by wesm — APPROVED** [review]
+1. This looks like it was truly a joy to complete

**Comment by wesm** [comment]
Hm not so fast. The macOS py35 failure seems legitimate

https://travis-ci.org/github/ursa-labs/crossbow/builds/703242650#L10060

**Comment by pitrou** [comment]
I'm restarting that build just in case, seems it seems to fail contacting Github. But macOS wheel builds don't enable S3 anyway, so I doubt this has anything to do with this PR.

**Pull request closed without merging**
