### PR TITLE
ARROW-11821: [Rust] Edit Rust README

### PR DESCRIPTION
**Pull request by pierwill**
Edits and fixes for some missing words, punctuation, and wording.

### CODE REVIEW

**Comment by alamb** [comment]
@pierwill  thank you -- why did you close this PR?

**Comment by pierwill** [comment]
Ah! Hello, @alamb! Creating an account on a new service seemed like a lot for a simple docs PR. 🐑 😬

**Comment by alamb** [comment]
@pierwill  I understand your position. Conveniently I have been working on a script to improve the experience (https://github.com/apache/arrow/pull/9594) so I am going to reopen this PR and create the JIRA for it. It seems a shame to lose your work over a process issue

**Comment by alamb** [comment]
The integration test failures look like https://issues.apache.org/jira/browse/ARROW-11717 (since hopefully fixed)

**Review by alamb — APPROVED** [review]
Thanks @pierwill

**Pull request closed without merging**
