### PR TITLE
ARROW-8740: [CI] Fix archery option in pandas master cron test

### PR DESCRIPTION
**Pull request by kszucs**

### CODE REVIEW

**Comment by wesm** [comment]
Hm, there was a test failure

```
____________ TestConvertMetadata.test_table_column_subset_metadata _____________

self = <pyarrow.tests.test_pandas.TestConvertMetadata object at 0x7f759a900960>

    def test_table_column_subset_metadata(self):
        # ARROW-1883
        # non-default index
        for index in [
                pd.Index(['a', 'b', 'c'], name='index'),
                pd.date_range("2017-01-01", periods=3, tz='Europe/Brussels')]:
            df = pd.DataFrame({'a': [1, 2, 3],
                               'b': [.1, .2, .3]}, index=index)
            table = pa.Table.from_pandas(df)
    
            table_subset = table.remove_column(1)
            result = table_subset.to_pandas()
>           tm.assert_frame_equal(result, df[['a']])
E           AssertionError: (None, <Day>)

opt/conda/envs/arrow/lib/python3.7/site-packages/pyarrow/tests/test_pandas.py:506: AssertionError
```

**Comment by jorisvandenbossche** [comment]
The failure in pandas master is covered in https://issues.apache.org/jira/browse/ARROW-8643. It's an easy fix, but I am discussion on the pandas side whether the change shouldn't be reverted there (now, until that discussion is settled, it's maybe easier to fix the test here anyway, to avoid the failure. Will do a quick PR)

**Comment by jorisvandenbossche** [comment]
-> https://github.com/apache/arrow/pull/7124

**Review by kszucs — COMMENTED** [review]
+1

**Pull request closed without merging**
