### PR TITLE
ARROW-1192: [JAVA] Use buffer slice for splitAndTransfer in List and …

### PR DESCRIPTION
**Pull request by StevenMPhillips**
…Union vectors

Includes a fix for splitAndTransfer in BitVector for the case when split length is 0

### CODE REVIEW

**Comment by xhochy** [comment]
@StevenMPhillips Can you give a bit more context on this change so that I'm able to review it?

**Comment by wesm** [comment]
Needs a unit test also

**Comment by jacques-n** [comment]
@siddharthteotia, can you take over this pull request and add some unit tests?

The goal of this PR was to update some vectors so they were more efficient at splitting vectors into subvectors. Many vectors are already efficient, minimizing manipulation of data. However, the ListVector and BitVector were doing far more work than necessary. In Dremio we use splitAndTransfer when unrolling lists. Ensuring that these apis are efficient substantially reduces CPU overhead during this operation. See the code using it here: https://github.com/dremio/dremio-oss/blob/master/sabot/kernel/src/main/java/com/dremio/sabot/op/flatten/FlattenTemplate.java#L205.

Probably makes sense to move our Dremio code for this class over to Arrow as well: 

https://github.com/dremio/dremio-oss/blob/master/sabot/kernel/src/test/java/com/dremio/exec/vector/TestSplitAndTransfer.java

**Comment by siddharthteotia** [comment]
Sure. I will add the unit tests.

**Comment by siddharthteotia** [comment]
I have opened a new PR -- https://github.com/apache/arrow/pull/901

**Comment by wesm** [comment]
This one can be closed

**Comment by wesm** [comment]
Can this be closed?

**Comment by wesm** [comment]
@StevenMPhillips can you close?

**Pull request closed without merging**
