### PR TITLE
GH-39208: [C++][Parquet] Remove deprecated AppendRowGroup(int64_t num_rows)

### LINKED ISSUE #39208: [C++][Parquet] Minor: Remove deprecated `AppendRowGroup(int64_t num_rows)`
### Describe the enhancement requested

`ParquetFileWriter::Contents::AppendRowGroup` is mark as deprecated in 1.3.0, I'd like to remove it

```c++
    /// \note Deprecated since 1.3.0
    RowGroupWriter* AppendRowGroup(int64_t num_rows);
```

### Component(s)

C++, Parquet

### PR DESCRIPTION
**Pull request by mapleFU**
### Rationale for this change

Described in issue

### What changes are included in this PR?

Remove the function below:

```
    /// \note Deprecated since 1.3.0
    RowGroupWriter* AppendRowGroup(int64_t num_rows);
```

### Are these changes tested?

no

### Are there any user-facing changes?

no

* Closes: #39208

### CODE REVIEW

**Comment by mapleFU** [comment]
cc @pitrou @wgtmac

**Comment by pitrou** [comment]
@github-actions crossbow -g cpp

**Review by pitrou — APPROVED** [review]
+1, thank you @mapleFU

**Comment by pitrou** [comment]
@github-actions crossbow submit -g cpp

**Comment by pitrou** [comment]
@mapleFU Can you rebase from main?

**Comment by mapleFU** [comment]
done

**Comment by pitrou** [comment]
@github-actions crossbow submit -g cpp

**Pull request merged**
