### PR TITLE
ARROW-8416: [Python] Add feather alias for ipc format in dataset API

### PR DESCRIPTION
**Pull request by jorisvandenbossche**

### CODE REVIEW

**Review by kszucs — APPROVED** [review]
LGTM

**Review by bkietz — APPROVED** [review]
LGTM

I'd like to add "arrow" to the list of aliases

**Comment by nealrichardson** [comment]
Odd failure, seems unrelated? https://github.com/apache/arrow/pull/6919/checks?check_run_id=583691774#step:6:2519

**Comment by bkietz** [comment]
Agreed, unrelated.
Merging

**Pull request closed without merging**
