### PR TITLE
ARROW-1020: [Format] Revise language for Timestamp type in Schema.fbs to avoid possible confusion about tz-naive timestamps

### PR DESCRIPTION
**Pull request by wesm**

### CODE REVIEW

**Review by xhochy — APPROVED** [review]
+1, would like someone else to review also as I'm not very "fluent" in timestamp logic.

**Comment by wesm** [comment]
@julienledem? The main change here was removing the "UTC" from the top comment, which was misleading (it gave the impression that the timestamps may be normalized to UTC, which is not necessarily the case for tz-naive timestamps)

**Comment by wesm** [comment]
+1. I think this is OK

**Comment by julienledem** [comment]
@wesm Yes, this looks good. Thanks

**Pull request closed without merging**
