### PR TITLE
ARROW-11549: [C++][Gandiva] Fix issues with FilterCacheKey caused by ToString() not distinguishing null and 'null'

### PR DESCRIPTION
**Pull request by niyue**
This is the same fix as https://github.com/apache/arrow/pull/9453

The previous PR (https://github.com/apache/arrow/pull/9453) got stale and cannot be merged, and I simply copied the modification in that PR to get ARROW-11549 addressed.

P.S.: the author of PR #9453 is my friend and former co-worker, and he got some personal matter and may not merge the PR now.

### CODE REVIEW

**Comment by niyue** [comment]
@KirillLykov @projjal  could you please help to review? Thanks.

**Review by projjal — APPROVED** [review]

**Review by KirillLykov — APPROVED** [review]
changes are all clear to me

**Comment by niyue** [comment]
@KirillLykov @projjal Is there anything else I need to do before the PR merge? I probably don't have the permission to merge, could you please help to merge the PR? Thanks.

**Comment by projjal** [comment]
> @KirillLykov @projjal Is there anything else I need to do before the PR merge? I probably don't have the permission to merge, could you please help to merge the PR? Thanks.

@pravindra @praveenbingo  Can one of you merge this PR

**Comment by KirillLykov** [comment]
@projjal I cannot since I'm not committer

**Comment by niyue** [comment]
@pravindra @praveenbingo could you please help to merge the PR? Thanks.

**Comment by projjal** [comment]
@niyue Can you rebase this patch. Ravindra retriggered the workflow but there are still (likely unrelated) failures

**Comment by niyue** [comment]
@projjal I rebase to the latest from master branch. Could you please check it out? Thanks.

**Comment by niyue** [comment]
@pravindra It seems this PR is not merged while https://issues.apache.org/jira/browse/ARROW-11549 was marked as resolved by this PR, is this expected?

**Comment by projjal** [comment]
@niyue The PR is merged https://github.com/apache/arrow/commit/b5fed26e36ed346fc5bc990f1a628cdaad6679bd

**Comment by niyue** [comment]
Got it. Thanks.

**Pull request closed without merging**
