### PR TITLE
GH-33973: [Python][Docs] Update documentation for Parquet filter keyword

### LINKED ISSUE #33973: [Python] Parquet `to_table` pythondoc is outdated
### Describe the bug, including details regarding any error messages, version, and platform.

The filter states that it needs it in DNF format, but since the `use_legacy_dataset=False` is now the default, we can also push in an expression. If you supply a DNF format, it will be converted into an expression later on: 

https://github.com/apache/arrow/blob/master/python/pyarrow/parquet/core.py#L2414-L2416

### Component(s)

Python

### PR DESCRIPTION
**Pull request by Fokko**
### Rationale for this change

I wrote a converter from an arbitrary expression to DNF, but this was not needed after learning that it just accepts an expression now.

Closes #33973

### CODE REVIEW

**Comment by westonpace** [comment]
I don't have a problem with this change but wonder if the root cause might be a little more fundamental.  I wonder if `ParquetDataset` itself should be deprecated.  The docs you probably want are [pyarrow.dataset.dataset](https://arrow.apache.org/docs/python/generated/pyarrow.dataset.dataset.html#pyarrow.dataset.dataset) and [pyarrow.dataset.Dataset](https://arrow.apache.org/docs/python/generated/pyarrow.dataset.Dataset.html#pyarrow.dataset.Dataset) (though filter would be provided by [pyarrow.dataset.Dataset.to_table](https://arrow.apache.org/docs/python/generated/pyarrow.dataset.Dataset.html#pyarrow.dataset.Dataset.to_table) which unfortunately redirects its documentation to [pyarrow.dataset.Scanner.from_dataset](https://arrow.apache.org/docs/python/generated/pyarrow.dataset.Scanner.html#pyarrow.dataset.Scanner.from_dataset) :cold_sweat: )

**Comment by Fokko** [comment]
@westonpace 

> The docs you probably want are [pyarrow.dataset.dataset](https://arrow.apache.org/docs/python/generated/pyarrow.dataset.dataset.html#pyarrow.dataset.dataset) and [pyarrow.dataset.Dataset](https://arrow.apache.org/docs/python/generated/pyarrow.dataset.Dataset.html#pyarrow.dataset.Dataset)

I would agree with you, but I went for a lower API because I want to re-use the connection. More background is provided [here](https://github.com/apache/arrow/issues/33972), and the dataset only accepts paths. If you think it is worthwhile to accept `NativeFile` there as well, let me know, and happy to raise a PR.

> which unfortunately redirects its documentation to [pyarrow.dataset.Scanner.from_dataset](https://arrow.apache.org/docs/python/generated/pyarrow.dataset.Scanner.html#pyarrow.dataset.Scanner.from_dataset) 😰 )

Do you want me to create a PR to copy those docs? Because of the redirect, the arguments are also not showing up in PyCharm. Let me know and I'll create a PR.

**Comment by westonpace** [comment]
> Do you want me to create a PR to copy those docs? Because of the redirect, the arguments are also not showing up in PyCharm. Let me know and I'll create a PR.

Yes, I think that is a good idea but I might CC @jorisvandenbossche or @amol- to weigh in on whether they know some better way to avoid the duplication or have a preference here (I normally focus on the C++ end of things.)

**Comment by jorisvandenbossche** [comment]
@Fokko thanks for the catch! You are currently updating the docstring of ParquetDataset, but we should do the same update for read_table:

https://github.com/apache/arrow/blob/78a8da42d1fc364e84286afc88a25fa5b819d092/python/pyarrow/parquet/core.py#L2775

(I think it's also `read_table` you are using in PyIceberg, and not `ParquetDataset`?)




> > Do you want me to create a PR to copy those docs? Because of the redirect, the arguments are also not showing up in PyCharm. Let me know and I'll create a PR.
> 
> Yes, I think that is a good idea but I might CC @jorisvandenbossche or @amol- to weigh in on whether they know some better way to avoid the duplication or have a preference here (I normally focus on the C++ end of things.)

Yeah, I think we should prefer some duplication if that gives better docstrings. I agree the indirection for the user right now isn't very user friendly. 
We might be able to share some part of the docstring and inject that in multiple places to avoid duplicating the actual content, if that doesn't make things too complicated.

**Comment by Fokko** [comment]
@jorisvandenbossche Updating table one is a good suggestion indeed. Updated that one as well 👍🏻 

> (I think it's also read_table you are using in PyIceberg, and not ParquetDataset?)

Currently, [we use the `read_table` indeed](https://github.com/apache/iceberg/blob/master/python/pyiceberg/io/pyarrow.py#L510-L517). I've also played around with the ParquetDataset, and it looked very similar. However, we don't need the lazy nature of the dataset, so directly loading a table makes more sense in our situation.

> Yeah, I think we should prefer some duplication if that gives better docstrings. I agree the indirection for the user right now isn't very user friendly.
> We might be able to share some part of the docstring and inject that in multiple places to avoid duplicating the actual content, if that doesn't make things too complicated.

Makes a lot of sense, I think sharing would be best. Let me create a separate PR for that

**Comment by Fokko** [comment]
@jorisvandenbossche first a bit of cleanup in https://github.com/apache/arrow/pull/34034

**Comment by jorisvandenbossche** [comment]
One more thing about the docstring: for both read_table and ParquetDataset, the docstring also injects the content of `_DNF_filter_doc` (which holds the actual explanation of how the filter is expressed in this list of tuples form). We should probably update that to start with saying that the filter can either be a pyarrow Expression, or this DNF list of tuples form.

**Comment by Fokko** [comment]
@jorisvandenbossche Good call. I've updated the docstring and added an example.

**Comment by Fokko** [comment]
@jorisvandenbossche WDYT?

**Review by jorisvandenbossche — APPROVED** [review]
Thanks!

**Pull request merged**
