### PR TITLE
ARROW-10797: [C++] Vendor and use PCG random generator library

### PR DESCRIPTION
**Pull request by pitrou**

### CODE REVIEW

**Comment by pitrou** [comment]
This exposes a small precision issue in the variance kernel tests in MinGW32 on 32-bit floats (because of rounding issues perhaps?):
https://github.com/pitrou/arrow/runs/2400347814?check_suite_focus=true#step:10:831

According to Numpy, the two float64 values differ by 5 ULPs:
```python
>>> a
1011966660.249961
>>> b
1011966660.2499604
>>> np.testing.assert_array_max_ulp(a, b)
Traceback (most recent call last):
  File "<ipython-input-15-48fada135e2b>", line 1, in <module>
    np.testing.assert_array_max_ulp(a, b)
  File "/home/antoine/miniconda3/envs/pyarrow/lib/python3.7/site-packages/numpy/testing/_private/utils.py", line 1643, in assert_array_max_ulp
    (maxulp, np.max(ret)))
AssertionError: Arrays are not almost equal up to 1 ULP (max difference is 5 ULP)
```

**Comment by cyb70289** [comment]
Should be the MinGW32 rounding issue we met with many times before.
Guess PCG generator produces different random numbers than std::default_random_engine. So this issue is always there, just not revealed by previous test data.
I think we can disable the random test for MinGW32. ASSERT_DOUBLE_EQ expects at most 4ULP diff, it's almost there.

**Comment by pitrou** [comment]
Ok, I added a skip on MinGW32.

**Review by cyb70289 — APPROVED** [review]
+1. CI failures looks not related.

**Comment by cyb70289** [comment]
@github-actions crossbow submit -g nightly

**Comment by cyb70289** [comment]
CentOS error may be caused by gcc-4.8 build failure from earlier pr.

**Pull request closed without merging**
