### PR TITLE
ARROW-13668: [Python] Add `write_batch` and `write` methods to `ParquetWriter`

### PR DESCRIPTION
**Pull request by save-buffer**
Also adds a small test to make sure these methods do the right thing

### CODE REVIEW

**Review by westonpace — COMMENTED** [review]
Could you add docstrings for these methods?  I realize there wasn't one before for write_table but we can go ahead and fix that now.  You could probably use the same strings that are in `pyarrow.ipc.RecordBatchFileWriter`.

**Review by westonpace — APPROVED** [review]
LGTM, @amol- / @jorisvandenbossche do you have any thoughts on this?  This should help bring the APIs for the ParquetWriter in sync with the API for RecordBatchFileWriter and RecordBatchStreamWriter.

**Review by jorisvandenbossche — COMMENTED** [review]
Thanks! Some comments on the docstrings

**Comment by save-buffer** [comment]
I've updated the docstring to clarify the maximum size, but please double check my wording

**Review by jorisvandenbossche — APPROVED** [review]
Thanks for the update!

**Pull request closed without merging**
