### PR TITLE
GH-38909: [Packaging] Drop support for Ubuntu 23.04

### LINKED ISSUE #38909: [Packaging] Drop support for Ubuntu 23.04
### Describe the enhancement requested

It will reach EOL on 2024-01 and our next major release will not be happen in this year.

### Component(s)

Packaging

### PR DESCRIPTION
**Pull request by kou**
### Rationale for this change

It will reach EOL on 2024-01 and our next major release will not be happen in this year.

### What changes are included in this PR?

Remove Ubuntu 23.04 related codes and files.

### Are these changes tested?

Yes.

### Are there any user-facing changes?

Yes.
* Closes: #38909

### CODE REVIEW

**Comment by kou** [comment]
@github-actions crossbow submit -g ubuntu

**Review by raulcd — COMMENTED** [review]
I think we also have to remove this, right?
https://github.com/apache/arrow/blob/main/dev/tasks/linux-packages/apache-arrow-apt-source/apt/ubuntu-lunar/Dockerfile

**Comment by kou** [comment]
Good catch! You're right.
I've removed it.

**Comment by kou** [comment]
@github-actions crossbow submit ubuntu-*

**Review by raulcd — APPROVED** [review]
The CI failure is unrelated as is related to: https://github.com/apache/arrow/issues/38981

**Pull request merged**
