### PR TITLE
GH-40454: [CI][Debian] Update Debian to 12 from 11

### PR DESCRIPTION
**Pull request by kou**
### Rationale for this change

Debian 11 will reach EOL on 2024-07.

### What changes are included in this PR?

* Use Debian 12.
* Enable build options that can't be enabled with Debian 11.
  * `ARROW_AZURE`
  * `ARROW_FLIGHT_SQL`
  * `ARROW_WITH_OPENTELEMETRY`

### Are these changes tested?

Yes.

### Are there any user-facing changes?

No.
* GitHub Issue: #40454

### CODE REVIEW

**Comment by kou** [comment]
@github-actions crossbow submit test-debian-*

**Comment by kou** [comment]
@github-actions crossbow submit test-debian-*

**Comment by kou** [comment]
@github-actions crossbow submit test-debian-*

**Comment by kou** [comment]
@github-actions crossbow submit test-debian-*

**Comment by kou** [comment]
@github-actions crossbow submit test-debian-*

**Comment by raulcd** [comment]
@github-actions crossbow submit -g python

**Review by raulcd — COMMENTED** [review]
@kou Thanks for the PR! this is great. We are doing other things on this PR apart from updating debian version, like enabling AZURE build, etc. I am ok with it but should we reference it on the title/description or do it on a different PR?

**Comment by kou** [comment]
> We are doing other things on this PR apart from updating debian version, like enabling AZURE build, etc. I am ok with it but should we reference it on the title/description or do it on a different PR?

You're right. I've update the description. I keep the title for now because these changes are PR details. (Title should describes summary not details.)

**Comment by kou** [comment]
@github-actions crossbow submit test-debian-12-python-3-amd64 -g python

**Comment by kou** [comment]
@github-actions crossbow submit -g python

**Comment by raulcd** [comment]
@github-actions crossbow submit test-debian-12*

**Comment by kou** [comment]
Can we merge this?

**Review by raulcd — APPROVED** [review]
Thanks @kou !

**Pull request merged**
