### PR TITLE
go: fix 404 link to cpu readme

### PR DESCRIPTION
**Pull request by rasa**

### CODE REVIEW

**Review by sbinet — COMMENTED** [review]
LGTM.

could you change the commit message to look more like the others?
_e.g.:_
```
Go: fix link to cpu package documentation
```

**Comment by sbinet** [comment]
@stuartcarnie @alexandreyc

**Comment by stuartcarnie** [comment]
LGTM @sbinet

**Comment by kou** [comment]
Normally, we should open an issue on JIRA for all pull requests: https://issues.apache.org/jira/browse/ARROW
See also: https://cwiki.apache.org/confluence/display/ARROW/Contributing+to+Apache+Arrow

But we accept tiny fix such as a trivial typo fix without issue. In this case, we don't need a JIRA issue.
So I'll merge this after I fix the commit message. We use "[Go] ${SUMMARY}" format for commit message.

**Comment by kou** [comment]
I've merged. Thanks for your contribution!

**Pull request merged**
