### PR TITLE
ARROW-11616: [Rust][DataFusion] Add collect_partitioned on DataFrame

### PR DESCRIPTION
**Pull request by seddonm1**
The DataFrame API has a `collect` method which invokes the `collect(plan: Arc<dyn ExecutionPlan>) -> Result<Vec<RecordBatch>>` function which will collect records into a single vector of RecordBatches removing any partitioning via `MergeExec`.

This PR adds the DataFrame `collect_partitioned` method so that partitioning can be maintained. This allows easy passing into a new `MemTable`.

@andygrove

### CODE REVIEW

**Review by andygrove — APPROVED** [review]
Nice improvement. Thanks @seddonm1. At some point we may want collect to return an iterator over batches rather than a vec.

**Review by Dandandan — APPROVED** [review]
👍 looks useful to me

**Review by alamb — COMMENTED** [review]
Looks good to me too -- Thanks @seddonm1 !

**Comment by alamb** [comment]
> Nice improvement. Thanks @seddonm1. At some point we may want collect to return an iterator over batches rather than a vec.

@andygrove  I think we already kind of have this -- namely `SendableRecordBatchStream` (the thing you get from calling `execute` directly is an "Iterator" (well, it is an `async` iterator). To get an actual `Iterator` from the async one, we would probably need to buffer the `RecordBatch`es anyway so I think making that buffering clear to the end user by passing out a `Vec` is a reasonable API. That is my $0.02 anyways

**Pull request closed without merging**
