### PR TITLE
ARROW-3503: [Python] Allow config hadoop_bin in pyarrow hdfs.py

### PR DESCRIPTION
**Pull request by WenboZhao**

### CODE REVIEW

**Review by wesm — COMMENTED** [review]
Looks good, but would be good to document this feature

**Comment by WenboZhao** [comment]
Thanks @wesm . Where should I  add the documentation? I could include the documentation change into this CR.

**Comment by wesm** [comment]
In that same document: https://github.com/apache/arrow/blob/master/python/doc/source/filesystems.rst

**Comment by WenboZhao** [comment]
While I update the doc, I am thinking `HADOOP_EXECUTABLE` could be a better name? What do you think?

**Comment by wesm** [comment]
@WenboZhao sounds good to me

**Comment by wesm** [comment]
@WenboZhao did you want to change this to HADOOP_EXECUTABLE? I can do it, too

**Comment by fsaintjacques** [comment]
I'd say keep it as `HADOOP_BIN` and merge.

**Comment by emkornfield** [comment]
@WenboZhao sorry for the delay on this, if you want to rebase, I can take a look and merge if it is still applicable.

**Comment by wesm** [comment]
Closing this. This conflicts with several patches that have happened since last October, so I think this needs to be revisited fresh

https://github.com/apache/arrow/commits/master/python/pyarrow/hdfs.py

**Pull request closed without merging**
