### PR TITLE
ARROW-12846: [Release] Reduce download/upload bandwidth for APT/Yum repositories

### PR DESCRIPTION
**Pull request by kou**
Summary:

Generating metadata for APT/Yum repositories from all .deb/.rpm
on local from scratch

    ||
    \/

Generating metadata for APT/Yum repositories only for built .deb/.rpm
and merging the generated metadata and existing metadata
(Released .deb/.rpm aren't downloaded.)

Before:

  For RC:
    1. Download built .deb/.rpm for RC
    2. Sign the built .deb/.rpm
    3. Upload the signed built .deb/.rpm to
       https://apache.jfrog.io/ui/native/arrow/{debian,centos,...}-rc
    3. Download all released .deb/.rpm from
       https://apache.jfrog.io/ui/native/arrow/{debian,centos,...}
    4. Download the all built and signed .deb/.rpm from
       https://apache.jfrog.io/ui/native/arrow/{debian,centos,...}-rc
    5. Generate metadata for APT/Yum repositories with local .deb/.rpm
       from scratch
    6. Upload the metadata for APT/Yum repositories to
       https://apache.jfrog.io/ui/native/arrow/{debian,centos,...}-rc

  For release:
    1. Download the all .deb/.rpm and metadata for APT/Yum repositories from
       https://apache.jfrog.io/ui/native/arrow/{debian,centos,...}-rc
    2. Upload the downloaded files to
       https://apache.jfrog.io/ui/native/arrow/{debian,centos,...}

After:

  For RC:
    1. Download the built .deb/.rpm for RC
    2. Sign the built .deb/.rpm
    3. Generate metadata for APT/Yum repositories for the built and
       signed .deb/.rpm
    4. Download metadata for APT/Yum repositories from
       https://apache.jfrog.io/ui/native/arrow/{debian,centos,...}
    5. Merge metadata of 3. and 4.
    6. Upload the built and signed .deb/.rpm and the merged metadata
       for APT/Yum repositories to
       https://apache.jfrog.io/ui/native/arrow/{debian,centos,...}-rc

  For release:
    1. Download only uploaded files by 6. for RC from
       https://apache.jfrog.io/ui/native/arrow/{debian,centos,...}-rc
    2. Upload the downloaded files to
       https://apache.jfrog.io/ui/native/arrow/{debian,centos,...}

### CODE REVIEW

**Comment by kou** [comment]
Some problems may exist because I can't test with Artifactory. Because I don't have staging environment. I'll fix remained problems in the release process for 6.0.0.

**Comment by kou** [comment]
Unfortunately, no...

The current https://apache.jfrog.io/ui/native/arrow/{debian,centos,...} includes packages and metadata for 5.0.0.
If we use a 5.0.0 RC, this tasks generate wrong APT/Yum repositories that include duplicated entries for 5.0.0 packages.

We can test this by creating 6.0.0-alpha0.

FYI: I tested general logic of this with packages.groonga.org and packages.red-data-tools.org: https://github.com/red-data-tools/packages.red-data-tools.org/blob/master/repository-task.rb

**Comment by kszucs** [comment]
> After:
> 
> For RC:
> 1. Download the built .deb/.rpm for RC 
> 2. Sign the built .deb/.rpm 
> 3. Generate metadata for APT/Yum repositories for the built and signed .deb/.rpm 
> 4. Download metadata for APT/Yum repositories from [https://apache.jfrog.io/ui/native/arrow/{debian,centos,...}](https://apache.jfrog.io/ui/native/arrow/%7Bdebian,centos,...%7D)
> 5. Merge metadata of 3. and 4. 
> 6. Upload the built and signed .deb/.rpm and the merged metadata for APT/Yum repositories to [https://apache.jfrog.io/ui/native/arrow/{debian,centos,...}-rc](https://apache.jfrog.io/ui/native/arrow/%7Bdebian,centos,...%7D-rc)
> 

Aren't the RC and non-RC repositories have the own metadata? Previously we had different versions uploaded to them.

> Some problems may exist because I can't test with Artifactory. Because I don't have staging environment. I'll fix remained problems in the release process for 6.0.0.

Is `packages.groonga.org` hosted on artifactory? 
Couldn't we use a new postfix, like `{debian,centor,...}-staging` to test the new upload script on the apache artifactory account?

**Review by kszucs — APPROVED** [review]
Tha changes look good to me, though I'd like to try this out :)

**Comment by kou** [comment]
> Aren't the RC and non-RC repositories have the own metadata? Previously we had different versions uploaded to them.

They have own metadata.

Here is workflow:

  * 6.0.0 RC0:
    * debian/ has metadata only for packages <= 5.0.0
    * debian-rc: has metadata for packages <= 6.0.0
  * 6.0.0:
    * debian/ has metadata for packages <= 6.0.0 (Copied from debian-rc/)
    * debian-rc/ has metadata for packages <= 6.0.0

> Couldn't we use a new postfix, like `{debian,centor,...}-staging` to test the new upload script on the apache artifactory account?

It's a good idea! I'll do it.

**Comment by kszucs** [comment]
@kou did you have the chance to try it out on artifactory?

**Comment by kou** [comment]
I've pushed staging support (`STAGING=yes` environment variable enables it) and tested by the staging support.
But the current size limit of Artifactory (100GB) isn't enough for staging support.
If we create staging directories for {almalinux,amazon-linux,centos,debian,ubuntu}, 100GB over size is required. I tested creating staging directories for each distribution. And I deleted all staging directories for now.

Removing old Python packages from https://apache.jfrog.io/ui/native/arrow/python/ and https://apache.jfrog.io/ui/native/arrow/python-rc/ may help us. They are largest size directories. And we already pushed them to PyPI and conda-forge.

**Comment by kou** [comment]
@github-actions crossbow submit -g linux

**Comment by kou** [comment]
@github-actions crossbow submit -g linux

**Comment by kou** [comment]
@github-actions crossbow submit -g linux

**Comment by kou** [comment]
@kszucs Ready to merge.

**Review by kszucs — APPROVED** [review]
Great! Thanks Kou!

**Pull request closed without merging**
