### PR TITLE
ARROW-5071: [Archery] Implement running benchmark suite

### PR DESCRIPTION
**Pull request by fsaintjacques**
- Implements the `archery benchmark run` sub-command that performs a single run without comparing to another run. This is the main basic blocks to run a benchmark and publish the result to a database, e.g. codespeed and/or custom db. Push is not provided in this PR.
- Implements serializing/de-serializing the result of a run in JSON. 
- Improved the `from_rev_or_path` method to also support the previous point json output. Thus, you can compare a mixture of commit(s)/build(s)/run's output(s). Effectively adding support for comparing on cached results of a run. 
- Implements redirecting the output to a named file via `--output`, `-` means stdout (the defaults).
- Improved the `GoogleBenchmarkRunner` to output partial results to stdout for progress feedback.

### CODE REVIEW

**Comment by fsaintjacques** [comment]
@pitrou this adds your requested feature to compare against offline data.

**Comment by nealrichardson** [comment]
Should the JSON benchmark output format be documented? Any special instructions for those writing or modifying benchmarks (naming, how to maintain continuity with historical data and when to break it, etc.) so that they work correctly in this system?

**Comment by fsaintjacques** [comment]
I don't think it's worth documenting yet, as the goal is to simply pass the serialized state from one archery sub-command to another.

Adding documentation on writing/modifying benchmarks is definitively worth it. It reminds me that we need to add version to benchmark metadata once we want to track this in a (persisted) database.

**Comment by nealrichardson** [comment]
Ok. 

How necessary is version in the benchmark metadata itself? Isn't version knowable based on timestamp?

**Comment by fsaintjacques** [comment]
I'd say git commit is a better proxy for version. The problem with having only the proxy (say commit or timestamp), is that you can't decided whether 2 samples are comparable.

By version, I didn't mean an actual human/semver version, but a key to differentiate if 2 named benchmarks are comparable. Usually, the shasum of the function body (file in our case because it's the easiest proxy) will dictate if the benchmarks are comparable.

Note that this is low-medium priority as benchmark body don't change often, and you can always work around this by renaming the benchmark (making the old version not comparable with the new name) and making this an official policy.

**Review by kszucs — APPROVED** [review]
LGTM, thanks @fsaintjacques!

**Pull request closed without merging**
