### PR TITLE
ARROW-1728: [C++] Run clang-format checks in Travis CI

### PR DESCRIPTION
**Pull request by wesm**
While this will result in more build failures, it will help keep master clean to avoid unrelated noise diffs in later patches (which has been frequently happening)

### CODE REVIEW

**Comment by wesm** [comment]
Alright, we are looking good:

```
Scanning dependencies of target check-format
clang-format checks failed, run 'make format' to fix
make[3]: *** [CMakeFiles/check-format] Error 255
make[2]: *** [CMakeFiles/check-format.dir/all] Error 2
make[1]: *** [CMakeFiles/check-format.dir/rule] Error 2
make: *** [check-format] Error 2
```

I'll revert the flake and if others are in agreement about failing on clang-format issues we can merge this.

**Comment by wesm** [comment]
@xhochy are you OK with this?

**Comment by wesm** [comment]
+1, I'm going to go out on a limb here and merge this. If failing builds due to clang-format becomes onerous, I will be happy to revisit the issue

**Comment by xhochy** [comment]
@wesm I'm ok with this. If this gets onerous, it might be worth taking a look at how easy it would be to program a bot that could `clang-format` someone's PR (but I guess this is not worth the effort just for Arrow).

**Comment by wesm** [comment]
Now that we have gitbox unless contributors uncheck the "allow edits from maintainers" box, we can also do the clang-format ourselves if that's blocking a time-sensitive PR getting merged. The one downside is that getting the right version of clang-format on Windows and macOS may be more work than on Linux; we probably should add instructions to help contributors

**Comment by xhochy** [comment]
On macOS it is a simple `brew install llvm@{version}`. I think currently the autodetection of the correct version is broken there and only working for me as I have a quickfix-symlink in place, made https://issues.apache.org/jira/browse/ARROW-1742 for this.

**Pull request closed without merging**
