### PR TITLE
WIP: [Release] Verify release-18.1.0-rc2

### PR DESCRIPTION
**Pull request by kou**
PR to verify Release Candidate

### CODE REVIEW

**Comment by kou** [comment]
@github-actions crossbow submit  --group verify-rc-source --param release=18.1.0 --param rc=2

**Comment by amoeba** [comment]
@github-actions crossbow submit verify-rc-source-integration-linux-ubuntu-22.04-amd64

**Comment by amoeba** [comment]
@github-actions crossbow submit verify-rc-source-windows

**Comment by kou** [comment]
Revision: apache-arrow-18.1.0-rc2

Submitted crossbow builds: [ursacomputing/crossbow @ release-18.1.0-rc2-0](https://github.com/ursacomputing/crossbow/branches/all?query=release-18.1.0-rc2-0)

|Task|Status|
|----|------|
|almalinux-8-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11828263321/job/32958028506)|
|almalinux-8-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11828263291/job/32958028063)|
|almalinux-9-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11828263397/job/32958029004)|
|almalinux-9-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11828263605/job/32958030498)|
|amazon-linux-2023-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11828263997/job/32958033085)|
|amazon-linux-2023-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11828263138/job/32958026841)|
|centos-7-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11828263688/job/32958030931)|
|centos-8-stream-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11828264200/job/32958034512)|
|centos-8-stream-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11828264311/job/32958034917)|
|centos-9-stream-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11828263892/job/32958032924)|
|centos-9-stream-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11828263648/job/32958030918)|
|conan-maximum|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11828263186/job/32958027198)|
|conan-minimum|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11828264017/job/32958034058)|
|debian-bookworm-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11828263609/job/32958030706)|
|debian-bookworm-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11828263027/job/32958026122)|
|debian-trixie-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11828264043/job/32958033974)|
|debian-trixie-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11828263375/job/32958028993)|
|java-jars|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11828263902/job/32958036878)|
|matlab|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11828264051/job/32958036869)|
|nuget|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11828263657/job/32958030778)|
|python-sdist|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11828263172/job/32958027227)|
|r-binary-packages|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11828262989/job/32958045040)|
|test-debian-12-docs|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11828263376/job/32958029027)|
|ubuntu-focal-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11828263945/job/32958032993)|
|ubuntu-focal-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11828263495/job/32958029243)|
|ubuntu-jammy-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11828263884/job/32958032930)|
|ubuntu-jammy-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11828263581/job/32958030591)|
|ubuntu-noble-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11828264116/job/32958034346)|
|ubuntu-noble-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11828264152/job/32958034473)|
|wheel-macos-monterey-cp310-cp310-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11828263162/job/32958027201)|
|wheel-macos-monterey-cp310-cp310-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11828263205/job/32958027430)|
|wheel-macos-monterey-cp311-cp311-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11828264019/job/32958033112)|
|wheel-macos-monterey-cp311-cp311-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11828264181/job/32958034528)|
|wheel-macos-monterey-cp312-cp312-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11828263780/job/32958031154)|
|wheel-macos-monterey-cp312-cp312-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11828263361/job/32958028477)|
|wheel-macos-monterey-cp313-cp313-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11828263998/job/32958033958)|
|wheel-macos-monterey-cp313-cp313-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11828264255/job/32958034675)|
|wheel-macos-monterey-cp313-cp313t-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11828263814/job/32958031272)|
|wheel-macos-monterey-cp313-cp313t-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11828263204/job/32958027457)|
|wheel-macos-monterey-cp39-cp39-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11828262982/job/32958026103)|
|wheel-macos-monterey-cp39-cp39-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11828263293/job/32958028048)|
|wheel-manylinux-2-28-cp310-cp310-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11828264285/job/32958034931)|
|wheel-manylinux-2-28-cp310-cp310-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11828264164/job/32958034488)|
|wheel-manylinux-2-28-cp311-cp311-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11828263644/job/32958030897)|
|wheel-manylinux-2-28-cp311-cp311-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11828264299/job/32958034733)|
|wheel-manylinux-2-28-cp312-cp312-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11828263782/job/32958031160)|
|wheel-manylinux-2-28-cp312-cp312-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11828264294/job/32958034965)|
|wheel-manylinux-2-28-cp313-cp313-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11828263544/job/32958029303)|
|wheel-manylinux-2-28-cp313-cp313-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11828263100/job/32958026899)|
|wheel-manylinux-2-28-cp313-cp313t-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11828264110/job/32958034328)|
|wheel-manylinux-2-28-cp313-cp313t-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11828264281/job/32958034735)|
|wheel-manylinux-2-28-cp39-cp39-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11828264378/job/32958067117)|
|wheel-manylinux-2-28-cp39-cp39-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11828262947/job/32958026085)|
|wheel-manylinux-2014-cp310-cp310-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11828263485/job/32958029232)|
|wheel-manylinux-2014-cp310-cp310-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11828263330/job/32958028492)|
|wheel-manylinux-2014-cp311-cp311-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11828262984/job/32958026105)|
|wheel-manylinux-2014-cp311-cp311-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11828263250/job/32958027451)|
|wheel-manylinux-2014-cp312-cp312-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11828264113/job/32958035795)|
|wheel-manylinux-2014-cp312-cp312-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11828263985/job/32958033086)|
|wheel-manylinux-2014-cp313-cp313-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11828263399/job/32958029018)|
|wheel-manylinux-2014-cp313-cp313-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11828264223/job/32958034663)|
|wheel-manylinux-2014-cp313-cp313t-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11828263753/job/32958031021)|
|wheel-manylinux-2014-cp313-cp313t-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11828263118/job/32958026922)|
|wheel-manylinux-2014-cp39-cp39-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11828264093/job/32958034209)|
|wheel-manylinux-2014-cp39-cp39-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11828263819/job/32958031264)|
|wheel-windows-cp310-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11828263589/job/32958030489)|
|wheel-windows-cp311-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11828263184/job/32958027257)|
|wheel-windows-cp312-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11828264084/job/32958034159)|
|wheel-windows-cp313-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11828263635/job/32958029274)|
|wheel-windows-cp39-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11828263073/job/32958026625)|

**Comment by assignUser** [comment]
@github-actions crossbow submit  --group verify-rc-binaries --group verify-rc-wheels --param release=18.1.0 --param rc=2

**Comment by amoeba** [comment]
@github-actions crossbow submit verify-rc-binaries-jars-linux-conda-latest-amd64

**Comment by amoeba** [comment]
@github-actions crossbow submit verify-rc-binaries-jars-linux-conda-latest-amd64 --param release=18.1.0 --param rc=2

**Pull request merged**
