### PR TITLE
[Release] Verify 7.0.0 RC8 [WIP]

### PR DESCRIPTION
**Pull request by kszucs**

### CODE REVIEW

**Comment by kszucs** [comment]
@github-actions crossbow submit --group verify-rc-source --param release=7.0.0 --param rc=8

**Comment by kou** [comment]
@github-actions crossbow submit verify-rc-jars-amd64 --param release=7.0.0 --param rc=8

**Comment by kszucs** [comment]
@github-actions crossbow submit verify-rc-source-windows --param release=7.0.0 --param rc=8

**Comment by kszucs** [comment]
@github-actions crossbow submit -g verify-rc-binaries --param release=7.0.0 --param rc=8

**Comment by kszucs** [comment]
@github-actions crossbow submit -g verify-rc-jars --param release=7.0.0 --param rc=8

**Comment by kszucs** [comment]
@github-actions crossbow submit verify-rc-wheels

**Comment by kszucs** [comment]
@github-actions crossbow submit -g verify-rc-wheels --param release=7.0.0 --param rc=8

**Comment by kszucs** [comment]
@github-actions crossbow submit -g verify-rc-wheels-windows --param release=7.0.0 --param rc=8

**Comment by kszucs** [comment]
@github-actions crossbow submit -g verify-rc-wheels-windows --param release=7.0.0 --param rc=8

**Comment by kszucs** [comment]
@github-actions crossbow submit verify-rc-wheels-windows --param release=7.0.0 --param rc=8

**Comment by kszucs** [comment]
@github-actions crossbow submit -g verify-rc-jars --param release=7.0.0 --param rc=8

**Comment by kou** [comment]
We've release 7.0.0.

**Pull request closed without merging**
