### PR TITLE
ARROW-7709: [Python] Preserve column name in conversion from Table column to pandas for non-ns timestamps

### PR DESCRIPTION
**Pull request by jorisvandenbossche**
https://issues.apache.org/jira/browse/ARROW-7709

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
cc @BryanCutler

**Comment by jorisvandenbossche** [comment]
@ursabot crossbow submit test-conda-python-3.7-spark-master

**Comment by kszucs** [comment]
[AMD64 Conda Crossbow Submit (#88672)](https://ci.ursalabs.org/#builders/98/builds/481) builder has been succeeded.

Revision: 211440d0426519bca44da1d4b886ed7e4e357304

Submitted crossbow builds: [ursa-labs/crossbow @ ursabot-467](https://github.com/ursa-labs/crossbow/branches/all?query=ursabot-467)

|Task|Status|
|----|------|
|test-conda-python-3.7-spark-master|[CircleCI](https://circleci.com/gh/ursa-labs/crossbow/tree/ursabot-467-circle-test-conda-python-3.7-spark-master)|

**Comment by kszucs** [comment]
@jorisvandenbossche we still have test failures. Could you investigate further?

Meanwhile I'm adding integration test for the latest spark release to see the regressions if any.

**Comment by jorisvandenbossche** [comment]
@BryanCutler would you be able to help investigate this?

```
======================================================================
FAIL: test_grouped_over_window_with_key (pyspark.sql.tests.test_pandas_grouped_map.GroupedMapInPandasTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/spark/python/pyspark/sql/tests/test_pandas_grouped_map.py", line 588, in test_grouped_over_window_with_key
    self.assertTrue(all([r[0] for r in result]))
AssertionError: False is not true

----------------------------------------------------------------------
Ran 20 tests in 213.859s

FAILED (failures=1)
```

**Comment by BryanCutler** [comment]
Sure, I can take a look today

**Comment by BryanCutler** [comment]
This fix looks good to me.

The new test failure seems to be when a `StructArray` has a child that is a timestamp with a timezone, the `to_pandas` conversion outputs an int64 instead of a timestamp

```python
In [1]: import pyarrow as pa 
   ...: import pandas as pd 
   ...: arr = pa.array([{'start': pd.Timestamp.now(), 'end': pd.Timestamp.now()}]) 
   ...:                                                                                                                      

In [2]: arr.to_pandas()                                                                                   
Out[2]: 
0    {'end': 2020-01-29 11:38:02.792681, 'start': 2...
dtype: object

In [3]: ts = pd.Timestamp.now()                                                                                              

In [4]: arr2 = pa.array([ts], type=pa.timestamp('us', tz='America/New_York'))                                                

In [5]: arr2.to_pandas()                                                                                  
Out[5]: 
0   2020-01-29 06:38:47.848944-05:00
dtype: datetime64[ns, America/New_York]

In [6]: arr = pa.StructArray.from_arrays([arr2, arr2], ['start', 'stop'])                                                    

In [7]: arr.to_pandas()                                                                                   
Out[7]: 
0    {'start': 1580297927848944000, 'stop': 1580297...
dtype: object
```

I'll open up a new JIRA for this.

**Comment by BryanCutler** [comment]
I made https://issues.apache.org/jira/browse/ARROW-7723 to track

**Comment by kszucs** [comment]
Thanks @bryancutler for investigating it. Shall we consider this as a blocker for 0.16?

**Review by BryanCutler — APPROVED** [review]

**Comment by BryanCutler** [comment]
>Thanks @BryanCutler for investigating it. Shall we consider this as a blocker for 0.16?

I think so because it's a regression and possible it could impact users, although it would only surface with a `pandas_udf` over a window and specifically looking at the window range. I'll mark it as a blocker for now and we can discuss if it should be changed.

**Pull request closed without merging**
