### PR TITLE
ARROW-9534: [Rust] [DataFusion] Add functions to create literal expressions

### PR DESCRIPTION
**Pull request by andygrove**

### CODE REVIEW

**Comment by andygrove** [comment]
@jorgecarleitao fyi

**Comment by jorgecarleitao** [comment]
Nice! I just needed this in my ballista's PR!

following [this SO answer](https://stackoverflow.com/a/40776087/931303), what do you think of

```
trait Literal {
    fn lit(&self) -> ScalarValue;
}

impl Literal for i32 {
    fn lit(&self) -> ScalarValue {
        ScalarValue::Int(self.clone())
    }
}
impl Literal for bool {
    fn lit(&self) -> ScalarValue {
        ScalarValue::Boolean(self.clone())
    }
}

fn lit<T: Literal>(n: T) -> ScalarValue {
    n.lit()
}

# usage:
# lit(2);
# lit(true);
```

this way, the user does not have to import nor remember the value's type; they can just call `lit`. It seems to be a common pattern in rust.

**Comment by andygrove** [comment]
@jorgecarleitao Oh, that is much nicer. Do you want to PR that and I'll close this one?

**Comment by jorgecarleitao** [comment]
I can take it.

**Pull request closed without merging**
