### PR TITLE
ARROW-717: [C++] Implement IPC zero-copy round trip for tensors

### PR DESCRIPTION
**Pull request by wesm**
This patch provides:

```python
WriteTensor(tensor, file, &metadata_length, &body_length));
std::shared_ptr<Tensor> result;
ReadTensor(offset, file, &result));
```

Also implemented `Tensor::Equals` and did some refactoring / code simplification in compare.cc

### CODE REVIEW

**Comment by wesm** [comment]
green build: https://travis-ci.org/wesm/arrow/builds/216839036

**Comment by wesm** [comment]
rebased

**Review by xhochy — APPROVED** [review]

**Comment by wesm** [comment]
rebased. merging on green build

**Comment by wesm** [comment]
Here's the appveyor build: https://ci.appveyor.com/project/wesm/arrow/build/1.0.32

**Pull request closed without merging**
