### PR TITLE
ARROW-12489: [Developer] autotune is broken

### PR DESCRIPTION
**Pull request by jonkeane**

### CODE REVIEW

**Comment by jonkeane** [comment]
@github-actions autotune

**Comment by jonkeane** [comment]
@github-actions autotune

**Comment by kou** [comment]
Did you confirm this on your fork?
You can confirm this on your fork by the following:

1. Push this change to your fork's master
2. Create a test pull request on your fork
3. Comment `@github-actions autotune` on the test pull request

**Comment by jonkeane** [comment]
Yup, it works on my fork: https://github.com/jonkeane/arrow/runs/2422954470?check_suite_focus=true

**Review by kou — APPROVED** [review]
Great!

+1

**Pull request closed without merging**
