### PR TITLE
GH-41720: [C++][Acero] Remove an useless parameter for QueryContext::Init called in hash_join_benchmark 

### PR DESCRIPTION
**Pull request by ZhangHuiGui**
### Rationale for this change
My local compilation parameters will include the compilation of some basic benchmarks. I discovered this compilation problem today. It seems that #41334 of `QueryContext::Init` is not synchronized to `hash_join_benchmark.cc`, and CI has not found this problem. .

### What changes are included in this PR?
Remove the first arg .

### Are these changes tested?
Needn't

### Are there any user-facing changes?
No

* GitHub Issue: #41720

### CODE REVIEW

**Comment by ZhangHuiGui** [comment]
@zanmato1984  PTAL this?
@kou Should our CI include full benchmark compilation? Seems current hash_join_benchmark compiled by `ARROW_BUILD_OPENMP_BENCHMARKS` not included in CI?

**Review by zanmato1984 — APPROVED** [review]
+1. Thanks for catching this!

**Comment by zanmato1984** [comment]
Though the fix is small enough, I don't think it is a minor change as there is code modification. Could you open an issue and subject this PR to it? Thanks. @ZhangHuiGui

**Review by mapleFU — APPROVED** [review]

**Comment by kou** [comment]
Can we measure how much `-DARROW_BUILD_OPENMP_BENCHMARKS=ON` increases CI time?

The following change will enable the benchmark on "C++ / AMD64 Conda C++ AVX2":

```diff
diff --git a/docker-compose.yml b/docker-compose.yml
index a1d8f60a26..0c9784cc0d 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -285,6 +285,7 @@ services:
     environment:
       <<: [*common, *ccache, *sccache, *cpp]
       ARROW_BUILD_BENCHMARKS: "ON"
+      ARROW_BUILD_OPENMP_BENCHMARKS: "ON"
       ARROW_BUILD_EXAMPLES: "ON"
       ARROW_ENABLE_TIMING_TESTS:  # inherit
       ARROW_EXTRA_ERROR_CONTEXT: "ON"
```

**Comment by ZhangHuiGui** [comment]
> Can we measure how much `-DARROW_BUILD_OPENMP_BENCHMARKS=ON` increases CI time?
> 
> The following change will enable the benchmark on "C++ / AMD64 Conda C++ AVX2":
> 
> ```diff
> diff --git a/docker-compose.yml b/docker-compose.yml
> index a1d8f60a26..0c9784cc0d 100644
> --- a/docker-compose.yml
> +++ b/docker-compose.yml
> @@ -285,6 +285,7 @@ services:
>      environment:
>        <<: [*common, *ccache, *sccache, *cpp]
>        ARROW_BUILD_BENCHMARKS: "ON"
> +      ARROW_BUILD_OPENMP_BENCHMARKS: "ON"
>        ARROW_BUILD_EXAMPLES: "ON"
>        ARROW_ENABLE_TIMING_TESTS:  # inherit
>        ARROW_EXTRA_ERROR_CONTEXT: "ON"
> ```
Added, but I’m not sure how to compare it with the previous CI compilation time.

**Comment by kou** [comment]
We can CI logs for it.

Anyway... The parameter wasn't used...: https://github.com/apache/arrow/actions/runs/9152098620/job/25159059866?pr=41716#step:6:864

Could you also add this?

```diff
diff --git a/ci/scripts/cpp_build.sh b/ci/scripts/cpp_build.sh
index a1f40fc360..6a3a53f253 100755
--- a/ci/scripts/cpp_build.sh
+++ b/ci/scripts/cpp_build.sh
@@ -120,6 +120,7 @@ else
     -DARROW_BUILD_BENCHMARKS=${ARROW_BUILD_BENCHMARKS:-OFF} \
     -DARROW_BUILD_EXAMPLES=${ARROW_BUILD_EXAMPLES:-OFF} \
     -DARROW_BUILD_INTEGRATION=${ARROW_BUILD_INTEGRATION:-OFF} \
+    -DARROW_BUILD_OPENMP_BENCHMARKS=${ARROW_BUILD_OPENMP_BENCHMARKS:-OFF} \
     -DARROW_BUILD_SHARED=${ARROW_BUILD_SHARED:-ON} \
     -DARROW_BUILD_STATIC=${ARROW_BUILD_STATIC:-ON} \
     -DARROW_BUILD_TESTS=${ARROW_BUILD_TESTS:-OFF} \
```

**Comment by ZhangHuiGui** [comment]
off:
[AMD64 Conda C++ AVX2](https://github.com/apache/arrow/actions/runs/9152098620/job/25159059866?pr=41716#logs)
succeeded 7 hours ago in 26m 43s

on:
[AMD64 Conda C++ AVX2](https://github.com/apache/arrow/actions/runs/9154084580/job/25164035145?pr=41716#logs)
succeeded 4 hours ago in 5m 42s

It seems to have decreased a lot...

**Comment by kou** [comment]
It's caused by ccache.

The "off" case wasn't cached: https://github.com/apache/arrow/actions/runs/9152098620/job/25159059866?pr=41716#step:6:2944

```text
   Hits:               14 / 882 ( 1.59%)
  Misses:            868 / 882 (98.41%)
```

The "on" case cached: https://github.com/apache/arrow/actions/runs/9154084580/job/25164035145?pr=41716#step:6:2956

```text
  Hits:              895 / 1765 (50.71%)
  Misses:            870 / 1765 (49.29%)
```

I think that about 6min with cache isn't a problem.

**Review by pitrou — APPROVED** [review]

**Pull request merged**
