### PR TITLE
ARROW-15739: [C++] Bump xsimd to latest version

### PR DESCRIPTION
**Pull request by cyb70289**

### CODE REVIEW

**Comment by cyb70289** [comment]
@ursabot please benchmark lang=C++

**Review by pitrou — APPROVED** [review]
Neat improvement, thank you @cyb70289 !

**Comment by peterphalen** [comment]
I think this could have introduced an error on my machine. When I `make` arrow I end up with this error:

```
error: ‘make_sized_batch_t’ in namespace ‘xsimd’ does not name a template type
   using simd_batch = xsimd::make_sized_batch_t<int8_t, 16>;
```

Any thoughts?

**Comment by pitrou** [comment]
@peterphalen Did you try a clean build (delete the CMake build dir then rebuild)?

**Comment by pitrou** [comment]
@peterphalen Did you try a clean build (delete the CMake build dir then rebuild)?

**Comment by peterphalen** [comment]
@pitrou Would that mean simply deleting the `~/arrow/cpp/build` directory and then following the installation steps again? I'm not sure if this is relevant but this is my first time installing arrow so there's no very old version lying around the machine.

**Comment by peterphalen** [comment]
It looks like this issue was resolved for me with help from this thread: https://github.com/apache/arrow/issues/35470
Specifically, running `cmake -DARROW_CXX=-march=native ..` and `cmake -DARROW_SIMD_LEVEL=NONE ..` and then re-running `make` got me past the error. I've hit another error now, but it appears unrelated and I think someone is helping me with it. Thank you!

**Pull request closed without merging**
