### PR TITLE
ARROW-4943: [Python] Add type conversion before connect to HDFS

### PR DESCRIPTION
**Pull request by DeliangFan**
Fix HDFS connection fails due to TypeError.

### CODE REVIEW

**Comment by DeliangFan** [comment]
@xhochy would you please take a review, thanks

**Comment by DeliangFan** [comment]
Can anyone tell me why appveyor/pr gets following failing.

C:\projects\arrow>conda create -n arrow -q -y --file=ci\conda_env_python.yml python=3.6 numpy=1.14 thrift-cpp=0.11 boost-cpp llvmdev=7.0.* clangdev=7.0.* --file=ci\conda_env_cpp.yml -c conda-forge   || exit /B 
Collecting package metadata: ...working... done
Solving environment: ...working... failed
PackagesNotFoundError: The following packages are not available from current channels:
  - thrift-cpp[version='0.12.0,0.11.*']

**Comment by xhochy** [comment]
@DeliangFan please rebase on master, there the failure should be fixed.

**Comment by DeliangFan** [comment]
@xhochy  Hi, xhochy, I have push a new rebased branch, please take a review, thanks!

**Comment by wesm** [comment]
I think @pitrou fixed this already, can you confirm

**Comment by DeliangFan** [comment]
@wesm Hi, wesm, I spend lots of time in building the lastest arrow, but still failed to build. Could you please show me the commit pushed by pitrou.

**Comment by wesm** [comment]
https://github.com/apache/arrow/pull/3975

**Pull request closed without merging**
