### PR TITLE
ARROW-9264: [C++][Parquet] Refactor and modernize schema conversion code

### PR DESCRIPTION
**Pull request by emkornfield**
Split this off from ARROW-8493 because enough code moved around to
warrant a review without other functional changes.

- Rename max_ to either current_ or removed entirely
- During SchemaField generation remove one check for grouped
  child fields.
- Add a field that will be required for generalized resolution
  ARROW-8493
- Use Result<> instead of output parameter for type conversions.
- Move code from reader_interal to schema.cc to align function declarations with header file.

### CODE REVIEW

**Comment by emkornfield** [comment]
CC @wesm

**Comment by wesm** [comment]
Great, I'll review tomorrow. The PR I just merged https://github.com/apache/arrow/commit/cca2db1cfb12bb12a4c018dcf60796352b27f1e2 caused a small conflict so you may need to manually rebase that small change

**Comment by emkornfield** [comment]
resolved the change and redid the removal of the variable cleanup.

**Review by wesm — APPROVED** [review]
+1

**Pull request closed without merging**
