### PR TITLE
ARROW-7577: [CI][C++] Check OSS-Fuzz build in Github Actions

### PR DESCRIPTION
**Pull request by pitrou**
This doesn't run the fuzzers, but checks they build correctly.

### CODE REVIEW

**Comment by kszucs** [comment]
@pitrou I still don't know a handy way to test GHA cron jobs, just copying them to a `_cron.yml` once they pass on a PR :)

Did you test it, do you have a link for a passed build?

**Comment by pitrou** [comment]
It's tested in the checks above.

**Comment by kszucs** [comment]
Indeed, I've added support for that trigger a week ago...

**Review by kszucs — APPROVED** [review]
LGTM, thanks @pitrou!

**Pull request closed without merging**
