### PR TITLE
WIP: [Release] Verify release-14.0.0-rc2

### PR DESCRIPTION
**Pull request by kou**
PR to verify Release Candidate

### CODE REVIEW

**Comment by kou** [comment]
@github-actions crossbow submit  --group verify-rc-source --param release=14.0.0 --param rc=2

**Comment by raulcd** [comment]
Revision: 2dcee3f82c6cf54b53a64729fd81840efa583244

Submitted crossbow builds: [ursacomputing/crossbow @ release-14.0.0-rc2-0](https://github.com/ursacomputing/crossbow/branches/all?query=release-14.0.0-rc2-0)

|Task|Status|
|----|------|
|almalinux-8-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-14.0.0-rc2-0-github-almalinux-8-amd64)|
|almalinux-8-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-14.0.0-rc2-0-github-almalinux-8-arm64)|
|almalinux-9-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-14.0.0-rc2-0-github-almalinux-9-amd64)|
|almalinux-9-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-14.0.0-rc2-0-github-almalinux-9-arm64)|
|amazon-linux-2023-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/6572656848/job/17854180397)|
|amazon-linux-2023-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-14.0.0-rc2-0-github-amazon-linux-2023-arm64)|
|centos-7-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-14.0.0-rc2-0-github-centos-7-amd64)|
|centos-8-stream-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-14.0.0-rc2-0-github-centos-8-stream-amd64)|
|centos-8-stream-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-14.0.0-rc2-0-github-centos-8-stream-arm64)|
|centos-9-stream-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-14.0.0-rc2-0-github-centos-9-stream-amd64)|
|centos-9-stream-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-14.0.0-rc2-0-github-centos-9-stream-arm64)|
|conan-maximum|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-14.0.0-rc2-0-github-conan-maximum)|
|conan-minimum|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/6572655238/job/17854175760)|
|debian-bookworm-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-14.0.0-rc2-0-github-debian-bookworm-amd64)|
|debian-bookworm-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-14.0.0-rc2-0-github-debian-bookworm-arm64)|
|debian-bullseye-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/6572657215/job/17854181211)|
|debian-bullseye-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-14.0.0-rc2-0-github-debian-bullseye-arm64)|
|debian-trixie-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-14.0.0-rc2-0-github-debian-trixie-amd64)|
|debian-trixie-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/6572656406/job/17854179006)|
|java-jars|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/6572659202/job/17854187068)|
|nuget|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-14.0.0-rc2-0-github-nuget)|
|python-sdist|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/6572655510/job/17854176376)|
|r-binary-packages|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/6572657696/job/17854182649)|
|test-ubuntu-22.04-docs|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-14.0.0-rc2-0-github-test-ubuntu-22.04-docs)|
|ubuntu-focal-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/6572658021/job/17854183497)|
|ubuntu-focal-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-14.0.0-rc2-0-github-ubuntu-focal-arm64)|
|ubuntu-jammy-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/6572656124/job/17854178321)|
|ubuntu-jammy-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-14.0.0-rc2-0-github-ubuntu-jammy-arm64)|
|ubuntu-lunar-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-14.0.0-rc2-0-github-ubuntu-lunar-amd64)|
|ubuntu-lunar-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-14.0.0-rc2-0-github-ubuntu-lunar-arm64)|
|wheel-clean|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-14.0.0-rc2-0-github-wheel-clean)|
|wheel-macos-big-sur-cp310-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-14.0.0-rc2-0-github-wheel-macos-big-sur-cp310-arm64)|
|wheel-macos-big-sur-cp311-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-14.0.0-rc2-0-github-wheel-macos-big-sur-cp311-arm64)|
|wheel-macos-big-sur-cp312-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-14.0.0-rc2-0-github-wheel-macos-big-sur-cp312-arm64)|
|wheel-macos-big-sur-cp38-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-14.0.0-rc2-0-github-wheel-macos-big-sur-cp38-arm64)|
|wheel-macos-big-sur-cp39-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/6572660359/job/17854187899)|
|wheel-macos-mojave-cp310-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-14.0.0-rc2-0-github-wheel-macos-mojave-cp310-amd64)|
|wheel-macos-mojave-cp311-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-14.0.0-rc2-0-github-wheel-macos-mojave-cp311-amd64)|
|wheel-macos-mojave-cp312-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/6572668064/job/17854203256)|
|wheel-macos-mojave-cp38-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-14.0.0-rc2-0-github-wheel-macos-mojave-cp38-amd64)|
|wheel-macos-mojave-cp39-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-14.0.0-rc2-0-github-wheel-macos-mojave-cp39-amd64)|
|wheel-manylinux-2-28-cp310-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/6572669349/job/17854206327)|
|wheel-manylinux-2-28-cp310-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/6572665736/job/17854197438)|
|wheel-manylinux-2-28-cp311-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-14.0.0-rc2-0-github-wheel-manylinux-2-28-cp311-amd64)|
|wheel-manylinux-2-28-cp311-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-14.0.0-rc2-0-github-wheel-manylinux-2-28-cp311-arm64)|
|wheel-manylinux-2-28-cp312-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/6572662173/job/17854190630)|
|wheel-manylinux-2-28-cp312-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-14.0.0-rc2-0-github-wheel-manylinux-2-28-cp312-arm64)|
|wheel-manylinux-2-28-cp38-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-14.0.0-rc2-0-github-wheel-manylinux-2-28-cp38-amd64)|
|wheel-manylinux-2-28-cp38-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-14.0.0-rc2-0-github-wheel-manylinux-2-28-cp38-arm64)|
|wheel-manylinux-2-28-cp39-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/6572672026/job/17854211876)|
|wheel-manylinux-2-28-cp39-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-14.0.0-rc2-0-github-wheel-manylinux-2-28-cp39-arm64)|
|wheel-manylinux-2014-cp310-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-14.0.0-rc2-0-github-wheel-manylinux-2014-cp310-amd64)|
|wheel-manylinux-2014-cp310-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/6572669998/job/17854207780)|
|wheel-manylinux-2014-cp311-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/6572672564/job/17854213224)|
|wheel-manylinux-2014-cp311-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-14.0.0-rc2-0-github-wheel-manylinux-2014-cp311-arm64)|
|wheel-manylinux-2014-cp312-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/6572661128/job/17854189251)|
|wheel-manylinux-2014-cp312-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/6572659542/job/17854186551)|
|wheel-manylinux-2014-cp38-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/6572665342/job/17854196681)|
|wheel-manylinux-2014-cp38-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/6572666042/job/17854198383)|
|wheel-manylinux-2014-cp39-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/6572666399/job/17854199231)|
|wheel-manylinux-2014-cp39-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/6572673048/job/17854214102)|
|wheel-windows-cp310-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/6572658663/job/17854184656)|
|wheel-windows-cp311-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/6572663730/job/17854193793)|
|wheel-windows-cp312-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/6572655784/job/17854177363)|
|wheel-windows-cp38-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/6572675107/job/17854219279)|
|wheel-windows-cp39-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/6572677670/job/17854228410)|

**Comment by raulcd** [comment]
@ursabot please benchmark

**Comment by raulcd** [comment]
@github-actions crossbow submit  --group verify-rc-binaries --group verify-rc-wheels --param release=14.0.0 --param rc=2

**Comment by raulcd** [comment]
@kou @kszucs any idea why it might be taking more than 6 hours to install system dependencies for `verify-rc-binaries-wheels-macos-11-amd64` ? On the previous release it took 6 minutes: https://github.com/ursacomputing/crossbow/actions/runs/5899732992/job/16002716613
I am trying to understand if there is an issue with the new runner image:
```
Image: macos-11
  Version: 20230921.4
  Included Software: https://github.com/actions/runner-images/blob/macOS-11/20230921.4/images/macos/macos-11-Readme.md
  Image Release: [https://github.com/actions/runner-images/releases/tag/macOS-11%2F](https://github.com/actions/runner-images/releases/tag/macOS-11%2F20230921.4)
```
vs the old:
```
   Image: macos-11
  Version: 20230812.3
  Included Software: https://github.com/actions/runner-images/blob/macOS-11/20230812.3/images/macos/macos-11-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/macOS-11%2F20230812.3
```
All jobs are successful except that one. I am thinking on sending the vote email nevertheless as both:
* verify-rc-binaries-wheels-macos-11-arm64 
* verify-rc-binaries-wheels-macos-12-amd64

where successful with the wheels and the current failure is timing out installing system dependencies, nothing to do verifying the wheels.

**Comment by raulcd** [comment]
I am surprised as installing system dependencies takes a reasonable amount of time both on macos12-amd64 and macos11-arm64 (10-15 minutes)

**Comment by kszucs** [comment]
Do the nightly builds pass? Nonetheless, it looks like a build issue rather than an issue with the release itself, so I think it is fine to send out the vote. We should be able to verify them locally until the verification builds are fixed.

**Comment by kszucs** [comment]
Looking at the rest of the builds there are test errors in the go source verification tasks. cc @zeroshade

**Comment by raulcd** [comment]
Thanks @kszucs the go verification issue has been fixed. Is an issue in the verification script!

**Comment by kou** [comment]
I agree with kszucs. It's not a blocker.
I think that Homebrew waits for a user input.
BTW, we should set timeout for this case...

**Pull request merged**
