### PR TITLE
ARROW-17389: [Python] Properly exclude tests when PYARROW_INSTALL_TESTS=0

### PR DESCRIPTION
**Pull request by milesgranger**
Will fix [ARROW-17389](https://issues.apache.org/jira/browse/ARROW-17389)

It appears when `PYARROW_INSTALL_TESTS=0`, setuptools would continue to add importable packages anyway:
(would also include warnings for `pyarrow.tests` and other sub packages.)
```
    ############################
    # Package would be ignored #
    ############################
    Python recognizes 'pyarrow.tests.parquet' as an importable package,
    but it is not listed in the `packages` configuration of setuptools.

    'pyarrow.tests.parquet' has been automatically added to the distribution only
    because it may contain data files, but this behavior is likely to change
    in future versions of setuptools (and therefore is considered deprecated).

    Please make sure that 'pyarrow.tests.parquet' is included as a package by using
    the `packages` configuration field or the proper discovery methods
    (for example by using `find_namespace_packages(...)`/`find_namespace:`
    instead of `find_packages(...)`/`find:`).

    You can read more about "package discovery" and "data files" on setuptools
    documentation page.
 ```
 
 Adding in an explicit `package_dir` seems to resolve the issue.
 
Tested locally with both `bdist` and `bdist_wheel`
`sdist` will still include tests, as I believe it's using `MANIFEST.in`.
 ```
$ PYARROW_INSTALL_TESTS=0 python setup.py bdist_wheel > output.txt
$ cat output.txt | grep tests | wc -l
0
 ```

### CODE REVIEW

**Comment by musicinmybrain** [comment]
Testing this on the [libarrow package in Fedora Linux](https://src.fedoraproject.org/rpms/libarrow), specifically on top of my [open PR](https://src.fedoraproject.org/rpms/libarrow/pull-request/2), I find that it works as advertised with respect to `pyarrow.tests`, which I’m quite happy about. However, I do find that `pyarrow.conftest` is still installed.

**Comment by milesgranger** [comment]
I can't seem to convince setuptools to ignore a _specific_ file using `exclude`. However, can "trick" it by instead having a `pyarrow.conftest` package with everything currently in `conftest.py` moved into `pyarrow.conftest.__init__`. 😅 

Probably shouldn't do that though. Would be easier maybe to move tests out of `pyarrow` but I think there are situations where tests are desired to be packaged up, and perhaps just as tricky to do the inverse in that scenario?

cc @jorisvandenbossche

**Comment by jorisvandenbossche** [comment]
There are a bunch of failures, because now test data is no longer included by default?

(if we don't find an easy way to exclude conftest.py, I would just leave it like that; it's already useful you discovered that the tests weren't actually excluded)

**Comment by milesgranger** [comment]
Bare with me, I have it working locally, just need to sort out CI discrepancies. 😅

**Comment by milesgranger** [comment]
Switching in https://github.com/apache/arrow/pull/13904/commits/12c0fff70d4962005f77b6f9a726097af6057e4b to move `pyarrow/tests` to `tests`. Still installing them in the `pyarrow.tests` when `PYARROW_INSTALL_TESTS` is set. 

AppVeyor is failing as expected in other PRs and master, and the docs I think is un-releated.

**Comment by milesgranger** [comment]
Reference to setuptools adding back excluded packages: https://github.com/pypa/setuptools/issues/3340#issuecomment-1219321087

**Comment by milesgranger** [comment]
After a tour of different ways to avoid adding the tests, seems maybe using `exclude_package_data` is the easiest. Unfortunately it'll still come with `pyarrow/conftest.py` but even moving tests out of the package directory would still require it due to doc testing needing conftest to run from inside `pyarrow`. 

Leaving the different implementations for any passersby. 😄

**Comment by musicinmybrain** [comment]
Thank you for taking the time to investigate this.

**Comment by milesgranger** [comment]
@jorisvandenbossche do you think this is ready?

**Review by jorisvandenbossche — APPROVED** [review]
Yes, thanks!

**Comment by jorisvandenbossche** [comment]
In the end this didn't "really" close ARROW-17389, since conftest.py is still not excluded. But I am not sure it is worth keeping open that issue?

**Comment by milesgranger** [comment]
Unfortunate, I agree, at least the bulk of tests are gone.

Even though `exclude_package_data` [considers non-python files](https://github.com/pypa/setuptools/issues/2269#issuecomment-661757116), thus why we couldn't easily exclude it there.

AFAIK, if we really want to close it
- Wait for setuptools update to not auto-include, then convert `conftest.py` to `pyarrow.conftest.__init__.py` and exclude `pyarrow.conftest` 
- Custom `setup(cmdclass, ...)` to exclude files.
- ....something else?

**Pull request merged**
