### PR TITLE
GH-44127: [CI][R] Fix util_enable_core_dumps.sh path

### PR DESCRIPTION
**Pull request by kou**
### Rationale for this change

Checkout directory is `arrow/` not `./`.

### What changes are included in this PR?

Add missing `arrow/` prefix.

### Are these changes tested?

Yes.

### Are there any user-facing changes?

No.
* GitHub Issue: #44127

### CODE REVIEW

**Comment by kou** [comment]
@github-actions crossbow submit -g r

**Comment by jonkeane** [comment]
Any idea what's going on with the binary builds @assignUser ?

I'm seeing `Error: Unable to find any artifacts for the associated workflow` and then it looks like we're getting release versions after that (which we rightfully catch!) I've not seen that before

**Comment by kou** [comment]
Ah, we're mixing `download-artifact@v4` and upload-artifact@v3`.

**Comment by kou** [comment]
@github-actions crossbow submit -g r

**Review by jonkeane — APPROVED** [review]
Thank you for this!

**Pull request merged**
