### PR TITLE
ARROW-17915: [C++] Error when using Substrait ProjectRel

### PR DESCRIPTION
**Pull request by vibhatha**
The existing test cases didn't cover multi-expressions and the faulty logic wasn't covered because of that.

### CODE REVIEW

**Comment by vibhatha** [comment]
cc @paleolimbot could you please take a look. This was a trivial change (which was actually a typo in the original code which wasn't covered by the tests). Extremely sorry about the inconvenience.

**Comment by vibhatha** [comment]
> Thanks!
> 
> I now get a different issue (also probably related to the Substrait that I'm generating!)
> 
> ```r
> library(arrow, warn.conflicts = FALSE)
> #> Some features are not enabled in this build of Arrow. Run `arrow_info()` for more information.
> 
> plan_as_json <- '{
>   "extensionUris": [
>     {
>       "extensionUriAnchor": 1,
>       "uri": "https://github.com/apache/arrow/blob/master/format/substrait/extension_types.yaml"
>     }
>   ],
>   "relations": [
>     {
>       "rel": {
>         "project": {
>           "common": {
>             "emit": {"outputMapping": [2]
>             }
>           },
>           "input": {
>             "read": {
>               "baseSchema": {
>                 "names": ["int"],
>                 "struct": {
>                   "types": [{"i32": {"nullability": "NULLABILITY_NULLABLE"}}]
>                 }
>               },
>               "localFiles": {
>                 "items": [
>                   {
>                     "uriFile": "file:///var/folders/gt/l87wjg8s7312zs9s7c1fgs900000gn/T//Rtmph5wiTQ/file1260f24ace0d2",
>                     "parquet": {
> 
>                     }
>                   }
>                 ]
>               }
>             }
>           },
>           "expressions": [
>             {"selection": {"directReference": {"structField": {"field": 0}}}}
>           ]
>         }
>       }
>     }
>   ]
> }'
> 
> temp_parquet <- tempfile()
> write_parquet(data.frame(int = 1:5), temp_parquet)
> plan_as_json <- gsub("THIS_IS_THE_TEMP_FILE", temp_parquet, plan_as_json)
> arrow:::do_exec_plan_substrait(plan_as_json)
> #> Error: Invalid: No match for FieldRef.FieldPath(2) in FieldPath(0): int32
> #> FieldPath(0): int32
> #> /Users/deweydunnington/Desktop/rscratch/arrow/cpp/src/arrow/type.h:1796  CheckNonEmpty(matches, root)
> #> /Users/deweydunnington/Desktop/rscratch/arrow/cpp/src/arrow/compute/exec/expression.cc:437  ref->FindOne(in)
> #> /Users/deweydunnington/Desktop/rscratch/arrow/cpp/src/arrow/compute/exec/project_node.cc:68  expr.Bind(*inputs[0]->output_schema(), plan->exec_context())
> #> /Users/deweydunnington/Desktop/rscratch/arrow/cpp/src/arrow/compute/exec/exec_plan.cc:535  MakeExecNode(this->factory_name, plan, std::move(inputs), *this->options, registry)
> #> /Users/deweydunnington/Desktop/rscratch/arrow/cpp/src/arrow/compute/exec/exec_plan.cc:530  std::get<Declaration>(input).AddToPlan(plan, registry)
> ```
> 
> Created on 2022-10-03 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)

@paleolimbot I doubt the following. 

The schema contains a single field. And then we have a single expression which would make a total of 2 fields in the final output from this projection. In the emit we are asking to emit the field with index 2. Since we have only 2 fields, the indices would be [0, 1] and there is no index 2. 

## Example


```C++

compute::ExecContext exec_context;
auto dummy_schema = schema({field("A", int32())});

// creating a dummy dataset using a dummy table
auto input_table = TableFromJSON(dummy_schema, {R"([
    [10],
    [20],
    [30]
])"});

const std::string substrait_json = R"({
  "relations": [{
    "root": {
      "input": {
        "project": {
          "common": {
            "emit": {
              "outputMapping": [0, 1]
            }
          },
          "input": {
            "read": {
              "common": {
                "direct": {
                }
              },
              "baseSchema": {
                "names": ["A"],
                "struct": {
                  "types": [{
                    "i32": {
                      "typeVariationReference": 0,
                      "nullability": "NULLABILITY_REQUIRED"
                    }
                  }],
                  "typeVariationReference": 0,
                  "nullability": "NULLABILITY_REQUIRED"
                }
              },
              "namedTable": {
                "names": ["SIMPLEDATA"]
              }
            }
          },
          "expressions": [{
            "selection": {
              "directReference": {
                "structField": {
                  "field": 0
                }
              },
              "rootReference": {
              }
            }
          }]
        }
      }
    }
  }]
})";

ASSERT_OK_AND_ASSIGN(auto buf, internal::SubstraitFromJSON("Plan", substrait_json));

NamedTableProvider table_provider = AlwaysProvideSameTable(std::move(input_table));

ConversionOptions conversion_options;
conversion_options.named_table_provider = std::move(table_provider);

std::shared_ptr<Table> output_table;

std::shared_ptr<compute::SinkNodeConsumer> consumer =
    std::make_shared<compute::TableSinkNodeConsumer>(&output_table,
                                                     default_memory_pool());


std::shared_ptr<ExtensionIdRegistry> sp_ext_id_reg = MakeExtensionIdRegistry();
ExtensionIdRegistry* ext_id_reg = sp_ext_id_reg.get();
ExtensionSet ext_set(ext_id_reg);

ASSERT_OK_AND_ASSIGN(
    std::shared_ptr<compute::ExecPlan> plan,
    DeserializePlan(*buf, std::move(consumer), default_extension_id_registry(),
                    &ext_set, conversion_options));

ASSERT_OK(plan->StartProducing());
ASSERT_FINISHES_OK(plan->finished());

std::cout << "Output Table" << std::endl;

std::cout << output_table->ToString() << std::endl;

```

Here we set the emit indices to [0, 1] so we should get two columns in the output table

```bash
Output Table
FieldPath(0): int32
FieldPath(1): int32
----
FieldPath(0):
  [
    [
      10,
      20,
      30
    ]
  ]
FieldPath(1):
  [
    [
      10,
      20,
      30
    ]
  ]
```

If we used,

```json
"emit": {
              "outputMapping": [0]
}
```

We get,

```bash
Output Table
FieldPath(0): int32
----
FieldPath(0):
  [
    [
      10,
      20,
      30
    ]
  ]
```

To provide better names for columns, we can use names in the root relation. That PR is WIP: https://github.com/apache/arrow/pull/14292

Hope this helps you. If this is not clear, please let me know.

**Comment by vibhatha** [comment]
@paleolimbot just curious 

```bash
"file:///var/folders/gt/l87wjg8s7312zs9s7c1fgs900000gn/T//Rtmph5wiTQ/file1260f24ace0d2"
```

Do you get this file path by using Temporary directory API? And are you working on Mac M1?

**Comment by vibhatha** [comment]
> You are totally right...sorry for the indirection! That is indeed a tempfile path on a Mac (I forgot to restart my session before reprexing that one 😬 ).
> 
> After fixing the issues you noted, I'm down to one failing test after building on your branch! Again, it's an index error but I'm _pretty sure_ it's not an off-by-one (or maybe you can help me spot my error!). What I _think_ this plan does is:
> 
> * Reads a 1-column Parquet
> * Computes two new columns: a copy of the first column, and the first column plus 10, then uses emit to only select the second and third columns of the output.
> * Computes one new column: a copy of the second column, then uses emit to only select the first column
> 
> Both of these steps work in isolation, but together, they fail.
> 
> ```r
> library(arrow, warn.conflicts = FALSE)
> #> Some features are not enabled in this build of Arrow. Run `arrow_info()` for more information.
> 
> plan_as_json <- '{
>   "extensionUris": [
>     {
>       "extensionUriAnchor": 1,
>       "uri": "https://github.com/substrait-io/substrait/blob/main/extensions/functions_arithmetic.yaml"
>     }
>   ],
>   "extensions": [
>     {
>       "extensionFunction": {
>         "extensionUriReference": 1,
>         "functionAnchor": 2,
>         "name": "add"
>       }
>     }
>   ],
>   "relations": [
>     {
>       "rel": {
>         "project": {
>           "common": {"emit": {"outputMapping": [2]}},
>           "input": {
>             "project": {
>               "common": {"emit": {"outputMapping": [1, 2]}},
>               "input": {
>                 "read": {
>                   "baseSchema": {
>                     "names": ["int"],
>                     "struct": {"types": [{"i32": {}}]}
>                   },
>                   "localFiles": {
>                     "items": [
>                       {"uriFile": "file://THIS_IS_THE_TEMP_FILE", "parquet": {}}
>                     ]
>                   }
>                 }
>               },
>               "expressions": [
>                 {"selection": {"directReference": {"structField": {"field": 0}}}},
>                 {
>                   "scalarFunction": {
>                     "functionReference": 2,
>                     "outputType": {"i32": {}},
>                     "arguments": [
>                       {"enum": {"unspecified": {}}},
>                       {"value": {"selection": {"directReference": {"structField": {"field": 0}}}}},
>                       {"value": {"literal": {"fp64": 10}}}
>                     ]
>                   }
>                 }
>               ]
>             }
>           },
>           "expressions": [
>             {"selection": {"directReference": {"structField": {"field": 0}}}}
>           ]
>         }
>       }
>     }
>   ]
> }'
> 
> temp_parquet <- tempfile()
> write_parquet(data.frame(int = 1:5), temp_parquet)
> plan_as_json <- gsub("THIS_IS_THE_TEMP_FILE", temp_parquet, plan_as_json)
> arrow:::do_exec_plan_substrait(plan_as_json)
> #> Error: Invalid: No match for FieldRef.FieldPath(2) in FieldPath(1): int32
> #> FieldPath(2): double
> #> /Users/deweydunnington/Desktop/rscratch/arrow/cpp/src/arrow/type.h:1796  CheckNonEmpty(matches, root)
> #> /Users/deweydunnington/Desktop/rscratch/arrow/cpp/src/arrow/compute/exec/expression.cc:437  ref->FindOne(in)
> #> /Users/deweydunnington/Desktop/rscratch/arrow/cpp/src/arrow/compute/exec/project_node.cc:68  expr.Bind(*inputs[0]->output_schema(), plan->exec_context())
> #> /Users/deweydunnington/Desktop/rscratch/arrow/cpp/src/arrow/compute/exec/exec_plan.cc:535  MakeExecNode(this->factory_name, plan, std::move(inputs), *this->options, registry)
> #> /Users/deweydunnington/Desktop/rscratch/arrow/cpp/src/arrow/compute/exec/exec_plan.cc:530  std::get<Declaration>(input).AddToPlan(plan, registry)
> #> /Users/deweydunnington/Desktop/rscratch/arrow/cpp/src/arrow/compute/exec/exec_plan.cc:530  std::get<Declaration>(input).AddToPlan(plan, registry)
> ```
> 
> Created on 2022-10-04 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)
> 
> The more readable dplyr synatax is:
> 
> ```r
> # remotes::install_github("paleolimbot/substrait-r@enable-arrow")
> # (requires libarrow built against #14295)
> library(substrait, warn.conflicts = FALSE)
> library(dplyr, warn.conflicts = FALSE)
> 
> # Adds a column to the end
> data.frame(int = 1:5) |> 
>   arrow_substrait_compiler() |> 
>   mutate(int10 = int + 10) |> 
>   collect()
> #> # A tibble: 5 × 2
> #>     int int10
> #>   <int> <dbl>
> #> 1     1    11
> #> 2     2    12
> #> 3     3    13
> #> 4     4    14
> #> 5     5    15
> 
> # Selects the first column
> data.frame(int = 1:5) |> 
>   arrow_substrait_compiler() |> 
>   select(int) |> 
>   collect()
> #> # A tibble: 5 × 1
> #>     int
> #>   <int>
> #> 1     1
> #> 2     2
> #> 3     3
> #> 4     4
> #> 5     5
> 
> # Chaining together fails
> data.frame(int = 1:5) |> 
>   arrow_substrait_compiler() |> 
>   mutate(int10 = int + 10) |> 
>   select(int) |> 
>   collect()
> #> Error: Invalid: No match for FieldRef.FieldPath(2) in FieldPath(1): int32
> #> FieldPath(2): double
> #> /Users/deweydunnington/Desktop/rscratch/arrow/cpp/src/arrow/type.h:1796  CheckNonEmpty(matches, root)
> #> /Users/deweydunnington/Desktop/rscratch/arrow/cpp/src/arrow/compute/exec/expression.cc:437  ref->FindOne(in)
> #> /Users/deweydunnington/Desktop/rscratch/arrow/cpp/src/arrow/compute/exec/project_node.cc:68  expr.Bind(*inputs[0]->output_schema(), plan->exec_context())
> #> /Users/deweydunnington/Desktop/rscratch/arrow/cpp/src/arrow/compute/exec/exec_plan.cc:535  MakeExecNode(this->factory_name, plan, std::move(inputs), *this->options, registry)
> #> /Users/deweydunnington/Desktop/rscratch/arrow/cpp/src/arrow/compute/exec/exec_plan.cc:530  std::get<Declaration>(input).AddToPlan(plan, registry)
> #> /Users/deweydunnington/Desktop/rscratch/arrow/cpp/src/arrow/compute/exec/exec_plan.cc:530  std::get<Declaration>(input).AddToPlan(plan, registry)
> ```
> 
> Created on 2022-10-04 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)

First of all thanks for finding out another issue. I added a fix for it. 

Your understanding about the plan is accurate. 

Flow of Operators: Read ==> Project -> Emit(Project) -> Project -> Emit(Project)
Schema Field changing  ==>  1 Field -> 3 Fields -> 2 Fields -> 3 Fields -> 1 Field

**Comment by vibhatha** [comment]
@westonpace CIs says the approval is needed. But I am not sure why. This is not my first contribution though :/

**Comment by vibhatha** [comment]
@paleolimbot great!
And thanks for running the CIs.

**Review by bkietz — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
