### PR TITLE
ARROW-5240: [C++][CI] pin cmake_format

### PR DESCRIPTION
**Pull request by emkornfield**
Hopefull this fixes the broken build.  Going to file a JIRA issue and file a ticket as this verifies a fix.

### CODE REVIEW

**Comment by emkornfield** [comment]
Will work on a longer term fix once I have time to validate advice from https://github.com/cheshirekow/cmake_format/issues/107

**Review by pitrou — APPROVED** [review]
LGTM

**Comment by pitrou** [comment]
@emkornfield Can you open a JIRA for the longer term fix?

**Comment by emkornfield** [comment]
Opened: https://issues.apache.org/jira/browse/ARROW-5245

**Pull request closed without merging**
