### PR TITLE
ARROW-8488: [R] Remove VALUE_OR_STOP and STOP_IF_NOT_OK macros

### PR DESCRIPTION
**Pull request by fsaintjacques**
Prefer templated functions over macro to align with the C++ style.

### CODE REVIEW

**Comment by nealrichardson** [comment]
autotune

**Comment by nealrichardson** [comment]
autotune everything

**Comment by fsaintjacques** [comment]
Neat!

**Comment by fsaintjacques** [comment]
One thing, the checks are gone?

**Comment by nealrichardson** [comment]
No idea why it didn't run checks on the commit that was pushed

**Pull request closed without merging**
