### PR TITLE
ARROW-17102: [R] Test fails on R minimal nightly builds due to Parquet writing

### PR DESCRIPTION
**Pull request by thisisnic**

### CODE REVIEW

**Comment by thisisnic** [comment]
@github-actions crossbow submit test-r-offline-minimal

**Comment by thisisnic** [comment]
@github-actions crossbow submit test-r-offline-minimal

**Comment by thisisnic** [comment]
@github-actions crossbow submit test-r-minimal-build

**Comment by dragosmg** [comment]
LGTM, thanks!

**Review by dragosmg — APPROVED** [review]

**Review by assignUser — APPROVED** [review]
Thanks! LGTM

**Pull request merged**
