### PR TITLE
GH-44373: [Packaging][Java] Fix brew link to Python 3.13 on macOS

### PR DESCRIPTION
**Pull request by raulcd**
### Rationale for this change

Java-jars are currently failing on macOS to install Python 3.13 because `python@3.13` (`python` is an alias of `python@3.13` now) isn't installed yet. Our link failure workaround is updating already installed `python@*` with `--overwrite` explicitly. `python@3.13` (`python`) isn't installed on GitHub Actions runner yet. So `brew bundle` installs `python` without `--overwrite`.

### What changes are included in this PR?

Install `python` with `--overwrite` explicitly before `brew bundle`.

### Are these changes tested?

Via CI

### Are there any user-facing changes?

No
* GitHub Issue: #44373

### CODE REVIEW

**Comment by raulcd** [comment]
@github-actions crossbow submit java-jars

**Comment by raulcd** [comment]
@github-actions crossbow submit java-jars

**Comment by raulcd** [comment]
@github-actions crossbow submit java-jars

**Comment by raulcd** [comment]
The only way I've found to fix the issue temporary is to pin `python` to 3.12 on `cpp/Brewfile`. @kou any other suggestion?
I think we could temporary pin to python@3.12 for the release to fix java-jars but I am unsure of other possible things to try.

**Comment by kou** [comment]
@github-actions crossbow submit java-jars

**Comment by kou** [comment]
We can fix this by running `brew install --overwrite python` explicitly before `brew bundle`.
See the updated description for more details.

**Review by kou — APPROVED** [review]
+1

**Pull request merged**
