### PR TITLE
MINOR: [Docs] Fix wrong list formatting for Integration Testing documentation

### PR DESCRIPTION
**Pull request by llama90**
### Rationale for this change

Fix wrong list formatting in specification for Integration Testing

### What changes are included in this PR?

Add new line to correct alignment.

### Are these changes tested?

Yes. I have verified the changes by building the documentation.

### Are there any user-facing changes?

Yes. the updated documentation will be visible to users.

### CODE REVIEW

**Comment by llama90** [comment]
Before: 

image

After:

image

**Comment by llama90** [comment]
@kou Could you review this when your free time? Thank you as always.

**Comment by kou** [comment]
@github-actions crossbow submit preview-docs

**Comment by kou** [comment]
http://crossbow.voltrondata.com/pr_docs/43090/format/Integration.html#json-test-data-format

**Review by kou — APPROVED** [review]
+1

**Pull request merged**
