### PR TITLE
ARROW-3090: [Rust] Accompany error messages with assertions

### PR DESCRIPTION
**Pull request by paddyhoran**

### CODE REVIEW

**Review by kszucs — APPROVED** [review]
LGTM

**Comment by kszucs** [comment]
Thanks @paddyhoran !

**Comment by sunchao** [comment]
Come late to this. We should also change the expected message for the tests. Currently it is all `should_panic(expected = "")`.

**Comment by kszucs** [comment]
@sunchao In a follow-up PR? Could You create a ticket for that?

**Comment by paddyhoran** [comment]
Good point @sunchao.  I guess we should not re-open the jira due to our custom tooling so I can do this is a follow up [jira](https://issues.apache.org/jira/browse/ARROW-3177).

**Comment by sunchao** [comment]
Sure. I just filed https://issues.apache.org/jira/browse/ARROW-3178.

**Comment by sunchao** [comment]
Oops I didn't see that you've already filed one @paddyhoran . I'll close mine.

**Pull request closed without merging**
