### PR TITLE
ARROW-7167: [CI][Python] Add nightly tests for additional pandas versions to Github Actions

### PR DESCRIPTION
**Pull request by jorisvandenbossche**

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
@kszucs is there a way to trigger the cron job on this PR, to ensure that it works correctly?

**Comment by jorisvandenbossche** [comment]
@kszucs with some additional fixes, this seems to work now. So will revert the temp changes

**Review by kszucs — APPROVED** [review]
LGTM

**Comment by kszucs** [comment]
Appveyor failure is unrelated, merging.

**Pull request closed without merging**
