### PR TITLE
ARROW-9192: [CI][Rust] Add support for running clippy

### PR DESCRIPTION
**Pull request by houqp**
The goal of this PR is not to fix all the clippy errors/warnings in arrow crate, but to make sure no new linting errors are introduced in the future so we can slowly fix the remaining errors.

### CODE REVIEW

**Review by paddyhoran — APPROVED** [review]
LGTM, thanks @houqp.

@kszucs can you take a look at this also please when you get a chance.

**Comment by wesm** [comment]
Hm I think this lint step should be merged into the main Lint workflow. @kszucs can you help?

**Comment by houqp** [comment]
@kszucs let me know if there is anything i can help to move it to the main lint workflow.

**Comment by houqp** [comment]
@kszucs  gentle ping, let me know what's the best way for me to help.

**Comment by kszucs** [comment]
> Hm I think this lint step should be merged into the main Lint workflow. @kszucs can you help?

It would be nice to have it integrated to archery, but since it's only triggered for the rust changes I think it's fine to defer it to a follow-up. 

Created ARROW-9295: [Archery] Support rust clippy in the lint command.

**Comment by kszucs** [comment]
@houqp sorry for the late response. I moved the lint job to the macos build to spare some CI resource and also changed to check all crates.

**Comment by kszucs** [comment]
Created another follow-up to enable more clippy rules: ARROW-9296: [CI][Rust] Enable more clippy lint checks

**Review by kszucs — APPROVED** [review]
Thanks for working on this! Merging on green.

**Comment by houqp** [comment]
Thanks @kszucs , at the mean time, I will try to fix more linting errors and see if we can just run clippy as is without the custom linting script before you start adding it to Archery.

**Pull request closed without merging**
