### PR TITLE
GH-38824: [Go] Enable GC checks

### LINKED ISSUE #38824: [Go] Enable GC checks
### Describe the enhancement requested

Judging by this [sporadic failure](https://github.com/apache/arrow/actions/runs/6943203792/job/18887771947?pr=38799#step:8:19738), it seems we should enable GC checks on unsafe pointers in CGo builds:
https://github.com/apache/arrow/actions/runs/6943203792/job/18887771947?pr=38799#step:8:19738

```
runtime: marked free object in span 0x7efb82dd4608, elemsize=80 freeindex=8 (bad use of unsafe.Pointer? try -d=checkptr)
```

### Component(s)

Go, Integration

### PR DESCRIPTION
**Pull request by pitrou**
### What changes are included in this PR?

Our codebase has many uses of `unsafe.Pointer`. It may be a good idea to add debug checks for these uses in CI builds, especially where data crosses C boundaries.

### Are these changes tested?

Yes.

### Are there any user-facing changes?

No.

* Closes: #38824

### CODE REVIEW

**Comment by pitrou** [comment]
I wonder if this is making Go CI builds slower than they were. I see a ton of `unsafe.Pointer` usage in our Go codebase.

**Comment by pitrou** [comment]
> I wonder if this is making Go CI builds slower than they were. I see a ton of `unsafe.Pointer` usage in our Go codebase.

Answer: CI builds seem roughly the same time as before.

**Comment by pitrou** [comment]
@github-actions crossbow submit -g go

**Review by zeroshade — APPROVED** [review]
LGTM thanks!

**Pull request merged**
