### PR TITLE
ARROW-2709: [Python] Write a dataset without converting arrow table to pandas

### PR DESCRIPTION
**Pull request by na11an**
Hello,

I would like to ask you to have a look on the careful suggestion for the issue.
I think that It would be temporary alternative for large data set before preparing group-by operation although it seems to be not efficient in terms of performance.

Best regards,

### CODE REVIEW

**Comment by na11an** [comment]
I would propose some implementation plan including benchmarks in C++ through one or more JIRA issue to verify whether it's more efficient. Thank you for a quick response and advice. I just wanted to close last pull request due to lots of conflicts.

**Comment by wesm** [comment]
-1. I want the proper C++ work completed instead. Here are the steps:

* Struct hash: https://issues.apache.org/jira/browse/ARROW-3978
* Integer argsort part of https://issues.apache.org/jira/browse/ARROW-1566
* Take function https://issues.apache.org/jira/browse/ARROW-772

These are the three things you need to do the groupby-split operation natively against an Arrow table. There is a slight complication which is implementing "take" against chunked arrays. This could be mitigated by doing the groupby-split at the contiguous record batch level

cc @fsaintjacques @kszucs

**Comment by na11an** [comment]
Thank you for the comment. I needed some time to get familiar with the project and c++ language before the suggestion. I think that someone already tried contributing for struct hash but it wasn't completed yet. Would anyone have a look on the change and share the opinion or idea to merge it?  
I hope to contribute this project step by step if I could.

Thank you in advance.

https://github.com/apache/arrow/pull/1563

cc @fsaintjacques @kszucs

**Comment by wesm** [comment]
Out of these things, the struct hash is the most difficult thing (to do efficiently). We'll get to it eventually, but it may be a few months

**Pull request closed without merging**
