### PR TITLE
ARROW-1968: [C++/Python] Add basic unit tests for ORC reader

### PR DESCRIPTION
**Pull request by pitrou**
These use the example files published in the Apache ORC repository.

### CODE REVIEW

**Comment by wesm** [comment]
How big are the data files in total? In general I prefer not to check binary files for testing into git. The ORC git repository is quite large because of this

**Comment by pitrou** [comment]
Right now it's a bit more than 1MB.

We'll need some data files anyway. Just testing our reader against our writer wouldn't ensure we implemented them properly.

PS: my ORC clone's `.git` is 23 MB, which is smaller than Arrow's!

**Comment by wesm** [comment]
Hm, if you `git gc` and trim your local branches it's smaller:

```
$ git clone git@github.com:apache/arrow.git arrow-clean
Cloning into 'arrow-clean'...
remote: Counting objects: 28800, done.
remote: Compressing objects: 100% (20/20), done.
remote: Total 28800 (delta 8), reused 12 (delta 5), pack-reused 28775
Receiving objects: 100% (28800/28800), 14.05 MiB | 5.01 MiB/s, done.
Resolving deltas: 100% (19879/19879), done.
(arrow-dev) 23:58 ~/code $ cd arrow-clean/
(arrow-dev) 23:58 ~/code/arrow-clean  (master)$ du -d 1 .git
8.0K	.git/info
15M	.git/objects
52K	.git/hooks
28K	.git/refs
32K	.git/logs
16M	.git
```

vs 

```
$ ..
(arrow-dev) 23:58 ~/code $ git clone git@github.com:apache/orc.git orc-clean
Cloning into 'orc-clean'...
remote: Counting objects: 15979, done.
remote: Compressing objects: 100% (22/22), done.
remote: Total 15979 (delta 2), reused 8 (delta 1), pack-reused 15956
Receiving objects: 100% (15979/15979), 21.92 MiB | 4.96 MiB/s, done.
Resolving deltas: 100% (9591/9591), done.
(arrow-dev) 23:59 ~/code $ cd orc-clean
(arrow-dev) 23:59 ~/code/orc-clean  (master)$ du -d 1 .git
8.0K	.git/info
23M	.git/objects
52K	.git/hooks
28K	.git/refs
32K	.git/logs
23M	.git
```

Maybe it makes sense to create an auxiliary repository for static testing data (which can be snapshotted into release tarballs). What do you think?

**Comment by pitrou** [comment]
Well, 1MB sounds quite small to me, so I think a separate repo is overkill for now (and would add complexity and fragility to the build/test chain).

**Comment by pitrou** [comment]
As a data point, my Numpy clone has a 114MB `.git`.

**Comment by wesm** [comment]
Okay. It can be a slippery slope -- 1MB is OK but IMHO 50MB is not. The "git is forever" thing is bothersome -- if we check these files in, we'll never be rid of them (unless we rewrite history with `git filter-branch`, but that's a last resort); every clone and every CI build will download them. 

So if we find ourselves tempted to add more binary files in the future, we should reconsider the strategy.

**Comment by wesm** [comment]
I have created https://github.com/apache/arrow-testing in the event that we wish to use a submodule approach or shallow clone for testing

**Review by wesm — APPROVED** [review]
+1. Thanks for doing this

**Comment by wesm** [comment]
I'm sorry to obsess over the file sizes, but I'm looking at

```
-rw-rw-r-- 1 wesm wesm  19313 Aug 16 12:12 decimal.jsn.gz
-rw-rw-r-- 1 wesm wesm  16337 Aug 16 12:12 decimal.orc
-rw-rw-r-- 1 wesm wesm  25093 Aug 16 12:12 decimal.pickle.bz2
-rw-rw-r-- 1 wesm wesm   2547 Aug 16 12:12 json_to_pickle.py
-rw-rw-r-- 1 wesm wesm    934 Aug 16 12:12 README.md
-rw-rw-r-- 1 wesm wesm     50 Aug 16 12:12 TestOrcFile.emptyFile.jsn.gz
-rw-rw-r-- 1 wesm wesm    523 Aug 16 12:12 TestOrcFile.emptyFile.orc
-rw-rw-r-- 1 wesm wesm    323 Aug 16 12:12 TestOrcFile.test1.jsn.gz
-rw-rw-r-- 1 wesm wesm   1711 Aug 16 12:12 TestOrcFile.test1.orc
-rw-rw-r-- 1 wesm wesm    607 Aug 16 12:12 TestOrcFile.test1.pickle.bz2
-rw-rw-r-- 1 wesm wesm 182453 Aug 16 12:12 TestOrcFile.testDate1900.jsn.gz
-rw-rw-r-- 1 wesm wesm  30941 Aug 16 12:12 TestOrcFile.testDate1900.orc
-rw-rw-r-- 1 wesm wesm 994703 Aug 16 12:12 TestOrcFile.testDate1900.pickle.bz2
```

Is there a reason to check in the bzipped pickle? Dropping TestOrcFile.testDate1900.pickle.bz2 would save nearly a megabyte

**Comment by pitrou** [comment]
The JSON file is much slower to load, it takes several seconds. I don't remember the exact number.
Another option would be to generate a smaller file (that file's contents are extremely repetitive), but I don't know how to do that without going through Arrow, which would bias the test a bit.

**Comment by pitrou** [comment]
I'm worried about the complication this would bring to our dev setup. Is there a way to trim the Parquet data files instead? We don't need all the rows.

**Comment by wesm** [comment]
I agree; my argument is that it's inevitable that we're going to have to do this at some point. It could be now or a year from now

What I'd be proposing is for users to add these steps to their development process

```
 2053  git clone git@github.com:wesm/arrow.git submodule-arrow-test
 2057  git checkout testing-submodule 
 2058  git submodule init
 2059  git submodule update
 2061  export ARROW_TEST_DATA=`pwd`/submodules/arrow-testing/data
```

see https://github.com/wesm/arrow/tree/testing-submodule

You could skip these steps and the affected tests would be skipped

**Comment by wesm** [comment]
Maybe to also motivate my mania about this:

```
$ ll ~/arrow-thirdparty/
total 159556
-rw-rw-r-- 1 wesm wesm 103363944 Apr 11 10:31 boost.tar.gz
-rw-rw-r-- 1 wesm wesm  19838761 Jul 16 22:38 brotli.tar.gz
-rw-rw-r-- 1 wesm wesm    681752 Jul 16 22:38 flatbuffers.tar.gz
-rw-rw-r-- 1 wesm wesm    126850 Jul 16 22:38 gbenchmark.tar.gz
-rw-rw-r-- 1 wesm wesm     96408 Jul 16 22:38 gflags.tar.gz
-rw-rw-r-- 1 wesm wesm  13692045 Jul 16 22:38 grpc.tar.gz
-rw-rw-r-- 1 wesm wesm   1281617 Jul 16 22:38 gtest.tar.gz
-rw-rw-r-- 1 wesm wesm    208019 Jul 16 22:38 lz4.tar.gz
-rw-rw-r-- 1 wesm wesm  13390471 Jul 16 22:38 orc.tar.gz
-rw-rw-r-- 1 wesm wesm   2609846 May 20  2017 protobuf.tar.gz
-rw-rw-r-- 1 wesm wesm   1019402 Jul 16 22:38 rapidjson.tar.gz
-rw-rw-r-- 1 wesm wesm   1509026 May 21  2017 snappy.tar.gz
-rw-rw-r-- 1 wesm wesm   3667154 Dec  7  2017 thrift.tar.gz
-rw-rw-r-- 1 wesm wesm    571091 Apr 28  2013 zlib.tar.gz
-rw-rw-r-- 1 wesm wesm   1300584 Jul 16 22:38 zstd.tar.gz
```

So the size of the Boost tarball is a bit ridiculous, but two other large dependencies Brotli and ORC are large precisely because of shipping binary files (and built Javadoc). I'm routinely developing on plane wifi or mobile hotspot and this kind of thing drives me nuts; so if we check in binary files, we're doing exactly the thing that I hate =) 

I'm willing to let it go for now so long as the _next time_ someone wants to check in binary files we do the right thing

**Comment by wesm** [comment]
Looking at the JSON thing. `pandas.read_json` is a lot faster than the approach in json_to_pickle.py

**Comment by wesm** [comment]
@pitrou I changed the tests to lean on pandas for the heavy lifting so the pickles can be removed

**Comment by pitrou** [comment]
Ah, cool :-) That sounds much better.

**Comment by wesm** [comment]
The Python 3.5 failure here is fixed by a newer version of pandas. manylinux1 is pinned on pandas 0.20.3. I'm going to try to bump the version and push a new version of the base image to quay.io

**Comment by wesm** [comment]
Thank goodness. +1

**Pull request closed without merging**
