### PR TITLE
ARROW-8460: [Packaging][deb] Reduce disk usage on building packages

### PR DESCRIPTION
**Pull request by kou**

### CODE REVIEW

**Comment by kou** [comment]
@github-actions crossbow submit -g linux

**Comment by kou** [comment]
@github-actions crossbow submit debian-*-amd64 ubuntu-*-amd64

**Comment by kou** [comment]
@github-actions crossbow submit debian-*-amd64 ubuntu-*-amd64

**Comment by kszucs** [comment]
FYI you can use wildcards to select tasks now.

**Review by kszucs — APPROVED** [review]
Thanks Kou!

**Comment by kou** [comment]
Yes! I'm using it. It's very helpful!

**Pull request closed without merging**
