### PR TITLE
ARROW-11259: [Python][Dataset] Allow creating nested field ref

### PR DESCRIPTION
**Pull request by pitrou**
We can't yet filter on a nested field ref, so this merely adds syntactical support.

### CODE REVIEW

**Review by bkietz — COMMENTED** [review]
This patch seems well put together of itself, but does it add value to support construction of nested field references if we can't filter on them yet? It seems first we should refactor the parts of scan which depend on non nested field refs (`ScanOptions::MaterializedFields`, `SetProjection`) before exposing anything in python

**Comment by pitrou** [comment]
> but does it add value to support construction of nested field references if we can't filter on them yet

Probably not, but it also should be relatively orthogonal to future refactors?

**Comment by jorisvandenbossche** [comment]
We *do* plan to support nested field references in filters? If so I am fine with already merging this, but no strong opinion.

**Comment by pitrou** [comment]
Should I close this PR? @bkietz

**Comment by jorisvandenbossche** [comment]
Now there is actual support for nested field refs (https://github.com/apache/arrow/pull/11466), this PR can be revived?

**Comment by pitrou** [comment]
@jorisvandenbossche Do you want to take it up?

**Comment by jorisvandenbossche** [comment]
Yes, will do

**Pull request closed without merging**
