### PR TITLE
ARROW-2321: [C++] Release verification script fails with if CMAKE_INSTALL_LIBDIR is not $ARROW_HOME/lib

### PR DESCRIPTION
**Pull request by cpcloud**

### CODE REVIEW

**Review by wesm — APPROVED** [review]
+1. Did you get this failure due to multiarch?

**Comment by cpcloud** [comment]
@wesm What do you mean by multiarch here? `lib64` was being created by default, but I'm not sure what causes that to begin with.

**Comment by cpcloud** [comment]
Looks like it's just part of cmake's `GNUInstallDirs`: https://github.com/Kitware/CMake/blob/master/Modules/GNUInstallDirs.cmake#L223

**Comment by wesm** [comment]
It depends on the Linux distro and whether things have been set up to do both lib32 and lib64 builds

**Comment by cpcloud** [comment]
It looks like cmake is making the decision based on these criteria, which arch linux satisfies: https://github.com/Kitware/CMake/blob/master/Modules/GNUInstallDirs.cmake#L204-L207

**Comment by wesm** [comment]
Cool, makes sense, thanks

**Pull request closed without merging**
