### PR TITLE
ARROW-8384: [Python][C++] Allow configuring Kerberos ticket cache path

### PR DESCRIPTION
**Pull request by pitrou**

### CODE REVIEW

**Comment by pitrou** [comment]
@kszucs This is simple and would be nice to have in 0.17.0 :-)

**Comment by pitrou** [comment]
Note that I've checked `docker-compose run --rm conda-python-hdfs` locally.

**Comment by pitrou** [comment]
CI failure is unrelated.

**Comment by pitrou** [comment]
@github-actions crossbow submit -g wheel

**Comment by pitrou** [comment]
@github-actions crossbow submit -g conda

**Comment by pitrou** [comment]
@github-actions crossbow submit -g conda

**Review by kszucs — APPROVED** [review]
LGTM

**Pull request closed without merging**
