### PR TITLE
ARROW-12829: [GLib][Ruby] Add support for Apache Arrow Flight

### PR DESCRIPTION
**Pull request by kou**

### CODE REVIEW

**Comment by kou** [comment]
@mrkn What do you think about `gaflight_` prefix?

If we follow Apache Arrow Dataset GLib convention, we use `gaf_` prefix. But this convention will cause conflict/confusion when we add Apache Arrow DXX (such as DataFrame) GLib. How about using `ga#{module}_` prefix such as `gaflight_` and `gadataset_`?

**Comment by mrkn** [comment]
I don't have any objection for employing `gaflight` prefix, but only thing I worry about is that `ga` prefix of `gaflight` may be too short?

**Comment by kou** [comment]
OK. Let's try `gaXXX_`. If `gaXXX_` conflicts with other products, we can rethink this.

**Comment by kou** [comment]
@github-actions crossbow submit -g linux

**Comment by kou** [comment]
+1

**Pull request closed without merging**
