### PR TITLE
MINOR: [Dev] Remove Dane from collaborators list

### PR DESCRIPTION
**Pull request by raulcd**
### Rationale for this change

Dane is a new committer.

### What changes are included in this PR?

Remove the collaborator list.

### Are these changes tested?

Not required.

### Are there any user-facing changes?

No

### CODE REVIEW

**Comment by danepitkin** [comment]
Thanks, Raul! Great idea ;)

**Review by danepitkin — APPROVED** [review]

**Comment by danepitkin** [comment]
🎉

**Comment by danepitkin** [comment]
@raulcd How can I regain access to github actions? https://github.com/apache/arrow/pull/42113#issuecomment-2161733022

**Comment by assignUser** [comment]
You have to make your apache org status public, it's hidden by default: https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-your-membership-in-organizations/publicizing-or-hiding-organization-membership

**Comment by danepitkin** [comment]
Thank you!!

**Pull request merged**
