### PR TITLE
ARROW-4275: [C++] [Gandiva] Fix slow decimal test

### PR DESCRIPTION
**Pull request by pravindra**
- removed static variant of test
- fixed a bug in cache lookup

### CODE REVIEW

**Review by pitrou — COMMENTED** [review]
I can't really comment on the fix, though the speedup is very nice. Should you perhaps add a test for the caching mechanism?

**Comment by pravindra** [comment]
> I can't really comment on the fix, though the speedup is very nice. Should you perhaps add a test for the caching mechanism?

thanks. added the test.

**Comment by wesm** [comment]
rebased

**Comment by pravindra** [comment]
@praveenbingo @pitrou please review

**Review by praveenbingo — APPROVED** [review]
+1, looks good.

Thanks for fixing this.

**Review by pitrou — APPROVED** [review]
+1, thanks you! Will wait for CI and then merge.

**Pull request closed without merging**
