### PR TITLE
ARROW-7291: [Dev] Fix FORMAT_DIR

### PR DESCRIPTION
**Pull request by mrkn**

### CODE REVIEW

**Comment by mrkn** [comment]
@wesm When I tried to run `update-flatbuffers.sh` with flatc version 1.11.0 on Ubuntu bionic, I got [a large number of changes](https://github.com/mrkn/arrow/commit/5293296366ad34308a7abcc6655392e2ab458741) although I didn't change the format.

I selected flatc version 1.11.0 because [the vendored flatbuffers version is 1.11.0](https://github.com/apache/arrow/blob/master/cpp/thirdparty/flatbuffers/include/flatbuffers/base.h#L138-L140).

Should we apply these changes?

**Comment by pitrou** [comment]
> Should we apply these changes?

They look reasonable to me at least. @kou

**Comment by wesm** [comment]
I'm +1 on this change (it came up elsewhere) and OK to update the generated files for 1.11

**Comment by kou** [comment]
+1

@mrkn Could you apply these changes? Then we can merge this.

**Comment by mrkn** [comment]
@kou Done.

**Review by wesm — APPROVED** [review]
+1

**Pull request closed without merging**
