### PR TITLE
ARROW-5194: [C++][Plasma] TEST(PlasmaSerialization, GetReply) is failing

### PR DESCRIPTION
**Pull request by thrasibule**

### CODE REVIEW

**Review by pitrou — COMMENTED** [review]
Thanks for posting this, and sorry for the delay. Wouldn't it be better to define `operator==` in `struct PlasmaObject`?

**Comment by pitrou** [comment]
Sorry for the delay. I'm looking at this again.

**Review by pitrou — APPROVED** [review]
LGTM. Rebased, will wait for CI.

**Comment by emkornfield** [comment]
merging

**Comment by emkornfield** [comment]
@pitrou I think @thrasibule needs to be added as a contributor in JIRA to get the JIRA assigned to him.

**Comment by pitrou** [comment]
@emkornfield Done.

**Pull request closed without merging**
