### PR TITLE
ARROW-5685: [Packaging][deb] Add support for Apache Arrow Datasets

### PR DESCRIPTION
**Pull request by kou**

### CODE REVIEW

**Comment by kou** [comment]
@ursabot crossbow package -g linux

**Comment by kou** [comment]
@ursabot crossbow package -g linux

**Comment by kou** [comment]
@kszucs Can we use https://travis-ci.org/ursa-labs/crossbow/builds/548880402 instead of https://travis-ci.org/ursa-labs/crossbow/branches for debian-stretch status badge link?

**Comment by pitrou** [comment]
Does this make sense? The datasets library is an empty shell for now. @wesm 
(also, what is the reason for making it a separate DLL?)

**Comment by wesm** [comment]
@pitrou among other things, I want to move the Parquet<->Arrow implementation from src/parquet/arrow to src/arrow/dataset/parquet. This means that libarrow_dataset needs to link to both libarrow and libparquet

**Comment by kou** [comment]
@ursabot crossbow package centos-6

**Comment by kou** [comment]
This is not needed for now.
I want to suppress warnings in `.deb` build process. `.deb` build process reports missing files that are installed but not included in any `.deb`.

**Comment by kou** [comment]
+1
All packages are buildable.

**Pull request closed without merging**
