### PR TITLE
GH-37651: [C#] expose ArrowArrayConcatenator.Concatenate

### LINKED ISSUE #37651: [C#] Expose ArrowArrayConcatenator.Concatenate
### Describe the enhancement requested

Other libraries, such as upcoming drivers written in C#, need the ability to concatenate arrays, particularly for metadata calls.

### Component(s)

C#

### PR DESCRIPTION
**Pull request by davidhcoe**
### Rationale for this change

New C# drivers need the ability to concatenate arrays, particularly for metadata calls. 

### What changes are included in this PR?

Converts a previously internal class and method to a public class and method. 

### Are these changes tested?

No substantive product changes were made. All tests still pass.

### Are there any user-facing changes?

It exposes previously hidden functionality. 

Resolves https://github.com/apache/arrow/issues/37651 

* Closes: #37651

### CODE REVIEW

**Comment by davidhcoe** [comment]
@lidavidm - can you help with this one?

**Review by lidavidm — APPROVED** [review]

**Comment by lidavidm** [comment]
Looks like there's test failures/you may want to rebase or merge?

**Comment by lidavidm** [comment]
Oh, I guess this has to be updated to remove `BindingFlags.NonPublic`?

https://github.com/apache/arrow/blob/b30d9616bb5056692b4b90a5e67b9a5ac206b2d0/csharp/test/Apache.Arrow.Tests/ArrowArrayConcatenatorTests.cs#L112-L113

**Comment by lidavidm** [comment]
Or really: presumably reflection is no longer required for this test

**Comment by davidhcoe** [comment]
> Or really: presumably reflection is no longer required for this test

good catch. I will fix the test.

**Review by lidavidm — APPROVED** [review]

**Pull request merged**
