### PR TITLE
GH-37721: [C++] Dependency: bump aws-sdk to 1.11.68 and avoid memory leak

### LINKED ISSUE #37721: [C++] Memory leak in s3 filesystem
### Describe the bug, including details regarding any error messages, version, and platform.

The AWS cpp sdk version that is used to build debian packages contains a memory leak bug that was already fixed upstream: https://github.com/aws/aws-sdk-cpp/pull/2373.

When running a simple test binary compiled with address sanitizer we get these errors:

```
Direct leak of 144 byte(s) in 1 object(s) allocated from:
    #0 0x7f735ea959cf in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:69
    #1 0x7f73590df498 in CRYPTO_zalloc (/lib/x86_64-linux-gnu/libcrypto.so.3+0x231498)

Indirect leak of 512 byte(s) in 6 object(s) allocated from:
    #0 0x7f735ea959cf in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:69
    #1 0x7f73590df498 in CRYPTO_zalloc (/lib/x86_64-linux-gnu/libcrypto.so.3+0x231498)

Indirect leak of 32 byte(s) in 1 object(s) allocated from:
    #0 0x7f735ea959cf in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:69
    #1 0x7f735915a8b1 in OPENSSL_sk_deep_copy (/lib/x86_64-linux-gnu/libcrypto.so.3+0x2ac8b1)

Indirect leak of 27 byte(s) in 2 object(s) allocated from:
    #0 0x7f735ea959cf in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:69
    #1 0x7f73590e0af5 in CRYPTO_strdup (/lib/x86_64-linux-gnu/libcrypto.so.3+0x232af5)

Indirect leak of 5 byte(s) in 1 object(s) allocated from:
    #0 0x7f735ea959cf in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:69
    #1 0x7f73590e0c5e in CRYPTO_strndup (/lib/x86_64-linux-gnu/libcrypto.so.3+0x232c5e)  
```

Can you bump the version of the sdk in https://github.com/apache/arrow/blob/main/cpp/thirdparty/versions.txt#L54C1-L54C27? It might also be good to sync it to the version used in https://github.com/apache/arrow/blob/main/ci/conda_env_cpp.txt#L18C1-L18C20.

### Component(s)

C++

### PR DESCRIPTION
**Pull request by mapleFU**
### Rationale for this change

See https://github.com/apache/arrow/issues/37721

### What changes are included in this PR?

Bump aws-sdk version to https://github.com/aws/aws-sdk-cpp/releases/tag/1.11.68

### Are these changes tested?

Already have S3 test

### Are there any user-facing changes?

no

* Closes: #37721

### CODE REVIEW

**Comment by mapleFU** [comment]
cc @kou

**Comment by mapleFU** [comment]
Oh seems last update has do much more things, should I also upgrade the submodule?

**Comment by kou** [comment]
The last update: #33808

> Oh seems last update has do much more things, should I also upgrade the submodule?

I think so...

And the current error message https://github.com/apache/arrow/actions/runs/6197952334/job/16827490393?pr=37736#step:7:1658 indicates that we also need to change how to build AWS SDK for C++...
If you aren't familiar with CMake, this task may be difficult...

**Comment by mapleFU** [comment]
Sounds interesting, I'll have a try this weekend

**Comment by h-vetinari** [comment]
What's special about 1.11.68? Upstream is at [1.11.168](https://github.com/aws/aws-sdk-cpp/tags) (note the extra "1"; it's 100 patch versions further), while conda-forge is now at 1.11.156 (also being synced back here in https://github.com/apache/arrow/pull/37624)

**Comment by mapleFU** [comment]
https://github.com/apache/arrow/blob/main/ci/conda_env_cpp.txt#L18C1-L18C20

Here it uses 1.11.68 @h-vetinari 

I find aws-sdk release it version very frequently, and I don't know if it's better to use a "stable" release rather than a "latest" release. Do you have some advices?

**Comment by h-vetinari** [comment]
> I find aws-sdk release it version very frequently, and I don't know if it's better to use a "stable" release rather than a "latest" release. Do you have some advices?

They're all equally good / bad / stable / unstable. The very likely only reason your environment got stuck on 1.11.68, is that this was the newest version in conda-forge for a while, because we were exactly figuring out how to [deal](https://github.com/conda-forge/aws-sdk-cpp-feedstock/issues/662) with the flood of versions. We've now solved this, and will be rebuilding once every ~20 versions (at random! there's really no reason to choose one or the other).

**Comment by mapleFU** [comment]
Thanks for your advice, let me have a try

**Comment by kou** [comment]
No problem. :-)
Thanks for working on this.

**Pull request closed without merging**
