### PR TITLE
ARROW-7502: [Integration] Remove Spark patch not needed

### PR DESCRIPTION
**Pull request by BryanCutler**
This removed ARROW-6429.patch that was used to patch Apache Spark master to fix compilation with Arrow 0.15+. Now Spark master has been updated to use Arrow 0.15.1 and the patch is not needed, it is currently being skipped for testing.

### CODE REVIEW

**Comment by jacques-n** [comment]
+1 
Thanks for fixing @BryanCutler!

**Comment by BryanCutler** [comment]
@ursabot crossbow submit docker-spark-integration

**Comment by BryanCutler** [comment]
@ursabot crossbow submit test-conda-python-3.7-spark-master

**Review by nealrichardson — APPROVED** [review]
The integration test job passes and the other CI failures are known/ticketed/flaky.

**Comment by BryanCutler** [comment]
merged to master, thanks @jacques-n and @nealrichardson !

**Pull request closed without merging**
