### PR TITLE
GH-43421: [C++] Use C++17's nested namespaces

### PR DESCRIPTION
**Pull request by IndifferentArea**
### Rationale for this change

see #36620 #43421

### What changes are included in this PR?

concatenate nested namespace by clang-tidy

### Are these changes tested?

yes

### Are there any user-facing changes?

no

* GitHub Issue: #36620
* GitHub Issue: #43421

### CODE REVIEW

**Comment by mapleFU** [comment]
This patch LGTM, but would you mind split it to sub-patches like: https://github.com/apache/arrow/pull/38929 ?

**Comment by IndifferentArea** [comment]
> This patch LGTM, but would you mind split it to sub-patches like: #38929 ?

fine, I'll explain some extra info there.

**Comment by IndifferentArea** [comment]
2 checks from MacOS failed, but I passed all test in my local mac with the same cmake macros and compiler version.
Could someone taught me how to fix it please?

**Comment by felipecrv** [comment]
Please split this into smaller PRs so it's reviewable.

**Pull request closed without merging**
