### PR TITLE
ARROW-4778: [C++/Python] manylinux1: Update Thrift to 0.12.0 

### PR DESCRIPTION
**Pull request by xhochy**

### CODE REVIEW

**Review by kszucs — APPROVED** [review]
LGTM

**Comment by xhochy** [comment]
> @xhochy are You going to tag it as https://github.com/apache/arrow/blob/master/dev/tasks/python-wheels/travis.linux.yml#L48 ?

I'm not sure what you're asking me? ;)

**Comment by xhochy** [comment]
I wasn't aware anymore that crossbow also depends on the image name. Do you have an idea for a more central place that crossbow and Travis both use the same image name source? It has really been annoying how often we forgot to adjust one of the three places.

**Comment by kszucs** [comment]
Perhaps wrap the big docker command with a script...

**Comment by kszucs** [comment]
Created issue for it: https://issues.apache.org/jira/browse/ARROW-4790

**Pull request closed without merging**
