### PR TITLE
ARROW-6716: [Rust] Bump nightly to nightly-2019-09-25 to fix CI

### PR DESCRIPTION
**Pull request by andygrove**
Rust 1.40.0-nightly just got released and caused builds to start failing

### CODE REVIEW

**Comment by andygrove** [comment]
@kszucs I think I'll need your help with this. See https://ci.ursalabs.org/#/builders/93/builds/1348

**Comment by andygrove** [comment]
Seems like ursabot is not picking up latest nightly yet .. we might just have to wait until tomorrow to sort this out

```
info: syncing channel updates for 'nightly-2019-09-25-x86_64-unknown-linux-gnu'
info: latest update on 2019-09-25, rust version 1.39.0-nightly (6ef275e6c 2019-09-24)
```

**Comment by paddyhoran** [comment]
> Rust 1.40.0-nightly just got released and caused builds to start failing

I'm a little confused, I though the effect of [this](https://github.com/apache/arrow/blob/master/rust/rust-toolchain#L1) means that we don't pick up the new nightly (we keep using the 2019-07-30 one) so why did a new nightly cause builds to start failing?

**Comment by andygrove** [comment]
I thought that too, but my PR from last night https://github.com/apache/arrow/pull/5509 failed in travis because it was using `rustc 1.40.0-nightly (37538aa13 2019-09-25)` and rustfmt has some minor differences:

```
active toolchain

----------------

nightly-x86_64-unknown-linux-gnu (environment override by RUSTUP_TOOLCHAIN)

rustc 1.40.0-nightly (37538aa13 2019-09-25)

Diff in /home/travis/build/apache/arrow/rust/arrow/src/array/builder.rs at line 1458:

         let mut builder = StructBuilder::new(fields, fi{code}eld_builders);

         assert!(builder.field_builder::<BinaryBuilder>(0).is_none());

     }

-

 }
```

**Comment by paddyhoran** [comment]
Hmm, it must be due to the version number bump.  With the release of 1.38 on stable, Beta is now 1.39 and nightly is now 1.40.

As the nightly version just changed to 1.40 there is no build on 2019-06-30 for this version (1.40) so it defaults to the most recent nightly.

It would be great to get back to Stable (or even Beta) eventually.

**Comment by andygrove** [comment]
Yes, I actually created https://issues.apache.org/jira/browse/ARROW-6717 earlier to start tracking the work to get to stable, but I'm not sure what the issues are beyond the use of packed_simd. Do you remember what the other blockers are?

**Comment by paddyhoran** [comment]
I think the only feature from nightly that we can't do without is specialization.  You can now disable the use of `packed_simd` and it is behind a feature, so specialization is the only blocker to building on stable again.

Once specialization lands we can switch SIMD to an opt-in feature rather than an opt-out feature and make stable the default.

**Comment by andygrove** [comment]
So this fixed Travis, but looks like one of the windows c++ builds was cancelled.

**Comment by kszucs** [comment]
@andygrove the buildbot git fetch issue seems transient, might be caused by a force-push.

**Review by kszucs — APPROVED** [review]
LGTM

**Review by paddyhoran — APPROVED** [review]
LGTM

**Pull request closed without merging**
