### PR TITLE
ARROW-1336: [C++] Add arrow::schema factory function, simply some awkward constructors 

### PR DESCRIPTION
**Pull request by wesm**

### CODE REVIEW

**Comment by wesm** [comment]
cc @cpcloud 

I'm not sure why Appveyor is upset

**Comment by pcmoritz** [comment]
Have you considered naming it make_schema? That'd go well with std::make_unique, std::make_shared, std::make_pair, etc; then you can also get rid of ::arrow:: (I assume that was to avoid name clashes).

**Review by cpcloud — APPROVED** [review]
LGTM

**Comment by wesm** [comment]
@pcmoritz I did think of that; this is more consistent with functions like `arrow::field`, `arrow::timestamp`, etc. I would rather change everything than do something inconsistent, so perhaps we can revisit if there are strong feelings about the naming style of these factory functions

I wonder what is going on with the segfault in Travis CI, we should try to figure that out (I have seen it before): opned ARROW-1338

**Pull request closed without merging**
