### PR TITLE
ARROW-3647: [R] Fix R bit64 crash and formatting

### PR DESCRIPTION
**Pull request by javierluraschi**
Fix for https://issues.apache.org/jira/browse/ARROW-3647 by adding a dependency to `bit64` in `arrow` which will avoid letting `bit64` be unloaded while `arrow` is loaded.

Additionally, fix for https://github.com/rstudio/sparklyr/issues/1736, which was preventing tibbles using `integer64` to be formatted properly if `bit64` was not loaded explicitly.

CC: @romainfrancois

### CODE REVIEW

**Comment by romainfrancois** [comment]
LGTM

**Comment by wesm** [comment]
+1

**Comment by hadley** [comment]
It's not clear to me that this fix is correct — I don't think you can generally expect to unload R packages containing C code and still have things work.

**Comment by wesm** [comment]
Am I correct that this fix allows the loading of bit64 to be deferred?

**Comment by hadley** [comment]
As far as I can see, the fix does the opposite - it forces loading of bit64 when arrow is loaded

**Pull request closed without merging**
