### PR TITLE
ARROW-17691: [Go] Implement Take for Primitive Types

### PR DESCRIPTION
**Pull request by zeroshade**

### CODE REVIEW

**Review by cyb70289 — APPROVED** [review]
LGTM

**Comment by zeroshade** [comment]
Thanks for taking a look @cyb70289! BTW: when you get a chance, if you could describe the process you went through for implementing the ARM assembly versions of the SIMD stuff since c2goasm doesn't fully support ARM yet, I'd love a quick writeup of it so I can try it myself to get those up and running.

**Comment by cyb70289** [comment]
> Thanks for taking a look @cyb70289! BTW: when you get a chance, if you could describe the process you went through for implementing the ARM assembly versions of the SIMD stuff since c2goasm doesn't fully support ARM yet, I'd love a quick writeup of it so I can try it myself to get those up and running.

Actually, I'm not familiar with c2go ;-)
@guyuqi did all the Arm optimization in arrow-go and he is an expert of this topic.

**Comment by guyuqi** [comment]
>> _if you could describe the process you went through for implementing the ARM assembly versions of the SIMD stuff since >>c2goasm doesn't fully support ARM yet_

Yes,  [c2goasm](https://github.com/minio/c2goasm) doesn't fully support ARM yet.
We could leverage [asm2plan9s](https://github.com/minio/asm2plan9s) to genrate the Go assembly from Gcc assemble.

First, we could generate the Gcc assembly (gcc -S ) from source `*.c`.
Then manually format it following the [example](https://github.com/minio/asm2plan9s/blob/master/example.s).
At last,  generate BYTE sequences for Go assembly  by asm2plan9s.

**Comment by guyuqi** [comment]
> Thanks for taking a look @cyb70289! BTW: when you get a chance, if you could describe the process you went through for implementing the ARM assembly versions of the SIMD stuff since c2goasm doesn't fully support ARM yet, I'd love a quick writeup of it so I can try it myself to get those up and running.

@zeroshade 
I have implemented  some Arm assembly for Arrow Go several months ago.
Would you please help to list the rest part of Arm assembly of the Arrow SIMD stuff in the new created jira tickets? 
Then they would be found well and I'd like to help to implement them. :-)

**Comment by zeroshade** [comment]
Hey @guyuqi! Thanks! The newer assembly was added to `go/arrow/compute/internal/kernels/_lib` for implementing compute kernels. Thanks!

**Comment by guyuqi** [comment]
> Hey @guyuqi! Thanks! The newer assembly was added to `go/arrow/compute/internal/kernels/_lib` for implementing compute kernels. Thanks!

OK, I see.  For I'm working on the other stuff,  I'd like to contribute it on the next month. Thanks, @zeroshade .

**Pull request merged**
