### PR TITLE
ARROW-8800: [C++] Split ChunkedArray into arrow/chunked_array.h/cc

### PR DESCRIPTION
**Pull request by wesm**
This also splits apart table_test.cc into multiple compilation units. I did some cleanup of includes but more can certainly be done going forward

### CODE REVIEW

**Comment by wesm** [comment]
I'll rebase and fix the test failures, but absent objections I'd like to merge this before it causes more conflicts

**Comment by nealrichardson** [comment]
FYI @wesm I just pushed to this branch

**Comment by wesm** [comment]
ah thank you

**Comment by wesm** [comment]
+1

**Pull request closed without merging**
