### PR TITLE
ARROW-2655: [C++] Fix compiler warnings with gcc 7

### PR DESCRIPTION
**Pull request by wesm**
I experienced a couple warnings causing build failures with `-Wconversion -Werror` with gcc 7.3.0

Also fixes ARROW-2669

### CODE REVIEW

**Comment by xhochy** [comment]
This seems to break a lot of other stuff.

**Comment by wesm** [comment]
I will take a closer look, was on the airplane when working on this

**Comment by wesm** [comment]
I'm going to merge this once I get the build passing as it's making it hard for me to look at other branches on Ubuntu 18.04

**Comment by wesm** [comment]
+1

**Pull request closed without merging**
