### PR TITLE
ARROW-3095: [Plasma] Move plasma store

### PR DESCRIPTION
**Pull request by pcmoritz**
@pitrou Does this fix the issue for you?

### CODE REVIEW

**Comment by pcmoritz** [comment]
I'm a little confused on what is going on in travis, it is passing on my branch: https://travis-ci.org/pcmoritz/arrow/builds/418474001?utm_source=github_status&utm_medium=notification

Could there be any caching happening?

**Comment by wesm** [comment]
I just rebased your PR to see

**Comment by pcmoritz** [comment]
Thanks! It seems to fail again with the same error unfortunately...

**Comment by wesm** [comment]
OK, we can investigate.

**Comment by pcmoritz** [comment]
Ah ok thanks, I was working on the non-rebased version. Good catch :)

**Review by wesm — APPROVED** [review]
+1. This is passing save for the Ruby build

**Pull request closed without merging**
