### PR TITLE
GH-33954: [C++][Parquet] Preserve field-id for nested type

### LINKED ISSUE #33954: [C++][Parquet] FieldToNode does not preserve field-id for nested type
### Describe the bug, including details regarding any error messages, version, and platform.

The function below converts arrow schema to parquet schema.
```cpp
Status FieldToNode(const std::string& name, const std::shared_ptr<Field>& field,
                   const WriterProperties& properties,
                   const ArrowWriterProperties& arrow_properties, NodePtr* out);
```

It should preserve field-id of each parquet column but the implementation fails to do it for nested type.

### Component(s)

C++, Parquet

### PR DESCRIPTION
**Pull request by wgtmac**
### Rationale for this change

Function below converts arrow schema to parquet schema and preserves field-id for primitive types but loses that information for nested types.
```cpp
Status FieldToNode(const std::string& name, const std::shared_ptr<Field>& field,
                   const WriterProperties& properties,
                   const ArrowWriterProperties& arrow_properties, NodePtr* out);
```

In the Apache Iceberg, field-ids are assigned to all column types. We need to keep field-id of all columns.

### What changes are included in this PR?

Fix `FieldToNode` to preserve field-id of STRUCT/MAP/LIST types.

### Are these changes tested?

Added a test case in the `cpp/src/parquet/arrow/arrow_schema_test.cc`.

### Are there any user-facing changes?

No.
* Closes: #33954

### CODE REVIEW

**Comment by wgtmac** [comment]
@pitrou @wjones127 Could you please take a look? Thanks!

**Review by pitrou — APPROVED** [review]
This looks good to me. @jorisvandenbossche Do you remember if there were any problems with Parquet field ids?

**Comment by jorisvandenbossche** [comment]
> This looks good to me. @jorisvandenbossche Do you remember if there were any problems with Parquet field ids?

I remember that we had previous PRs where we wondered what to do with it. Your comment at this PR summarizes how we currently handle it (https://github.com/apache/arrow/pull/10289#issuecomment-839634828):

> Based on my understanding, it seems that we should:
> * when reading from Parquet, reflect Parquet field_ids (if any) under the `PARQUET:field_id` metadata key
> * when writing to Parquet, generate Parquet field_ids from the `PARQUET:field_id` metadata key (if present)
> * not attempt to auto-generate any field_ids if they are not present in metadata

So correctly preserving the field-ids for nested types seems to follow that. 

@wgtmac the current test does a full roundtrip of the arrow<->parquet schemas, so I assume this indirectly also covers that we correctly write them to Parquet if the information is present in the field metadata of an Arrow schema?

**Comment by wgtmac** [comment]
> > This looks good to me. @jorisvandenbossche Do you remember if there were any problems with Parquet field ids?
> 
> I remember that we had previous PRs where we wondered what to do with it. Your comment at this PR summarizes how we currently handle it ([#10289 (comment)](https://github.com/apache/arrow/pull/10289#issuecomment-839634828)):
> 
> > Based on my understanding, it seems that we should:
> > 
> > * when reading from Parquet, reflect Parquet field_ids (if any) under the `PARQUET:field_id` metadata key
> > * when writing to Parquet, generate Parquet field_ids from the `PARQUET:field_id` metadata key (if present)
> > * not attempt to auto-generate any field_ids if they are not present in metadata
> 
> So correctly preserving the field-ids for nested types seems to follow that.
> 
> @wgtmac the current test does a full roundtrip of the arrow<->parquet schemas, so I assume this indirectly also covers that we correctly write them to Parquet if the information is present in the field metadata of an Arrow schema?

Yes, the current fix preserves all field-ids that exist in the `PARQUET:field_id` metadata key for all data types. This is required if we intend to write a parquet file which contains nested types to follow what the Apache Iceberg expects. @jorisvandenbossche

**Pull request merged**
