### PR TITLE
ARROW-4034: [Ruby] Add support :append option to FileOutputStream

### PR DESCRIPTION
**Pull request by kou**

### CODE REVIEW

**Comment by kou** [comment]
@ismurray This solves #3175.

**Review by shiro615 — APPROVED** [review]
LGTM

**Comment by jlforever** [comment]
@kou and @shiro615 and @ismurray

Quick follow about this pull request. I am currently testing through the `red-parquet` gem's `test-arrow-table.rb` unit test. In it, there is a high level call on L:45 that does:

``` ruby
@table.save(tempfile.path)
```
which will cascade to `Arrow::Table#save` and in that method, it will instantiate a new `TableSaver` domain object, that will provide an output wrapper that enables the eventual output in different instructed file format (raw, csv etc).

Looking at the `Arrow::Table#save` interface, looks like it allows for an optional option param to bind as the second parameter, which, for example, potentially can invoke a call like:

``` ruby
# just an example, not concrete and can be any other option key value pairing
# that will be digested internally by these domain classes via contracts as needed
#
@table.save(tempfile.path, { append: true })
```
In my opinion, that is good and flexible as it will eventually also cascade to bind onto `TableSaver` class's constructor when an object of that class is instantiated. That said, once it is in `TableSaver` object instance I don't think the saver will notify the eventual use of `FileOutputStream.open` interface to be able to bind into the new `append` parameter that is added to this changeset.  Specially, I am referencing the `TableSaver#save_raw` that current has this implementation:

``` ruby
def save_raw(writer_class)
  FileOutputStream.open(@path, false) do |output|
    writer_class.open(output, @table.schema) do |writer|
      writer.write_table(@table)
    end
  end
end
```
which has the 2nd parameter default to of the output stream, always default to `false`. 

Maybe this is intended, as the `Arrow::Table` is instructed to always write to a persistence file (parquet file in my case) in non-append mode? But just want to start this conversation and explore whether that is a possible further extension that can be built on top of this changeset here.

**Comment by kou** [comment]
It's a good idea.
Can you open a JIRA ticket for this? https://issues.apache.org/jira/projects/ARROW/issues/
Do you want to implement this?

**Comment by jlforever** [comment]
@kou yes, I will open up a JIRA ticket for this and can also spend some time to tackle this via a PR.

**Pull request closed without merging**
