### PR TITLE
ARROW-16731: [C++] Bump version of vendored mimalloc

### PR DESCRIPTION
**Pull request by pitrou**
The 2.0 line should probably be stable enough now.

### CODE REVIEW

**Comment by pitrou** [comment]
@github-actions crossbow submit -g cpp

**Comment by pitrou** [comment]
The Fedora 35 build fails because the mimalloc library is installed in `lib64` but is then looked for in `lib`:
```
-- Install configuration: "DEBUG"
-- Installing: /build/cpp/mimalloc_ep/src/mimalloc_ep/lib64/mimalloc-2.0/libmimalloc-debug.a
-- Installing: /build/cpp/mimalloc_ep/src/mimalloc_ep/lib64/cmake/mimalloc-2.0/mimalloc.cmake
-- Installing: /build/cpp/mimalloc_ep/src/mimalloc_ep/lib64/cmake/mimalloc-2.0/mimalloc-debug.cmake
-- Installing: /build/cpp/mimalloc_ep/src/mimalloc_ep/include/mimalloc-2.0/mimalloc.h
-- Installing: /build/cpp/mimalloc_ep/src/mimalloc_ep/include/mimalloc-2.0/mimalloc-override.h
-- Installing: /build/cpp/mimalloc_ep/src/mimalloc_ep/include/mimalloc-2.0/mimalloc-new-delete.h
-- Installing: /build/cpp/mimalloc_ep/src/mimalloc_ep/lib64/cmake/mimalloc-2.0/mimalloc-config.cmake
-- Installing: /build/cpp/mimalloc_ep/src/mimalloc_ep/lib64/cmake/mimalloc-2.0/mimalloc-config-version.cmake
[ ... ]
/usr/bin/ld: cannot find mimalloc_ep/src/mimalloc_ep/lib/mimalloc-2.0/libmimalloc-debug.a: No such file or directory
```

**Comment by pitrou** [comment]
@github-actions crossbow submit -g cpp

**Comment by kou** [comment]
@github-actions crossbow submit test-fedora-35-cpp

**Comment by jonkeane** [comment]
I'm still digging into why this didn't get the standard github message, but here is the conbench run for the ursa-i9 machine: https://conbench.ursa.dev/runs/bf64d0ec945a465ca149d1c720f9d59b/ (and comparison: https://conbench.ursa.dev/compare/runs/843570a8b602439b8dca5efbfad23b85...bf64d0ec945a465ca149d1c720f9d59b/)

**Pull request merged**
