### PR TITLE
ARROW-4550: [JS] Fix AMD pattern

### PR DESCRIPTION
**Pull request by mbostock**
Untested but proposed fix to #3629 using the standard UMD pattern as generated by Rollup.

### CODE REVIEW

**Comment by kou** [comment]
Could you open a issue on JIRA https://issues.apache.org/jira/browse/ARROW and prepend "ARROW-XXXX: [JS] " to title of this pull request?

See also: https://cwiki.apache.org/confluence/display/ARROW/Contributing+to+Apache+Arrow

**Comment by domoritz** [comment]
I created https://issues.apache.org/jira/browse/ARROW-4550. 

@mbostock can you rename the PR title to "ARROW-4550: [JS] Fix AMD pattern"?

**Comment by mbostock** [comment]
Renamed as requested. Thanks for looking at this!

**Comment by TheNeuralBit** [comment]
@trxcllnt can you take a look at this? you're much more familiar with the build system

**Comment by trxcllnt** [comment]
This looks ok to me. IIRC I used one of the [standard UMD templates](https://github.com/umdjs/umd), and possibly modified it to match Webpack's [`umdNamedDefine`](https://webpack.js.org/configuration/output/#outputumdnameddefine) output. I haven't used AMD in quite a while, so :+1: from me if this fixes it for @mbostock

**Comment by TheNeuralBit** [comment]
Ok I'll do a smoke test locally then merge. Thanks @mbostock!

**Comment by TheNeuralBit** [comment]
@mbostock is there a way to test this change in Observable before we cut an actual release?

**Comment by mbostock** [comment]
@TheNeuralBit Yes, if you have the generated file somewhere, you can require the URL. GitHub makes this a little tricky because they force the content-type to be text/plain, but you can workaround that like so:

```js
require(await fetch("https://gist.githubusercontent.com/mbostock/f421358acd00c94badaceed4d4034d36/raw/51026b908d68b94e191e8b4f3d5f46c41a4e00ac/amd-test.js").then(response => response.blob()).then(blob => URL.createObjectURL(blob)))
```

https://beta.observablehq.com/d/9e7bac640df7d65a

https://gist.github.com/mbostock/f421358acd00c94badaceed4d4034d36

**Comment by mbostock** [comment]
Any update on when this will be released? It’s been a bummer that Apache Arrow is broken out of the box (at least on Observable) for about thirty days despite a fix being merged.

**Comment by xhochy** [comment]
We will integrate the JS releases in the mainline releases and hopefully release this next week as 0.13.0

**Comment by wesm** [comment]
BTW absolutely nothing has blocked making a JavaScript release sooner, but no one has initiated those conversations on the mailing list

**Comment by wesm** [comment]
(i.e. @mbostock you or anyone could have asked on dev@arrow.apache.org about making a release as soon as this patch was merged)

**Comment by mbostock** [comment]
I didn’t think it was necessary to request a release given that the maintainers were apparently aware of the library being broken by evidence of the fact that this PR was merged, but I will keep that in mind for the future.

**Comment by wesm** [comment]
Yes, in the future, when something like this comes up, I would recommend being a "squeaky wheel" until you get what you need. The community must be given the opportunity to inspect the software before publishing it to NPM (a good thing IMHO, in light of some of the problems the ecosystem has had) but the release process is not complicated

**Comment by TheNeuralBit** [comment]
Sorry @mbostock you're right we should've been on top of this. 

I'm in favor of cutting an 0.4.1 release ASAP, all the JIRAs tagged for that release are [already closed](https://issues.apache.org/jira/projects/ARROW/versions/12344961) and several of them are bugfixes for 0.4.0. We can integrate with the mainline releases after that.

**Comment by wesm** [comment]
The new package is up https://www.npmjs.com/package/apache-arrow/v/0.4.1. Please let us know if any issues

**Comment by mbostock** [comment]
Thanks! 👍 I’ve sent [a corresponding suggestion](https://observablehq.com/compare/5583ca12f2112e3a...42bb458c8c58f885) to the Introduction to Apache Arrow on Observable.

**Comment by kou** [comment]
@mbostock Could you create a JIRA account and tell me your account? I want to set you to the assignee of https://issues.apache.org/jira/browse/ARROW-4550 . Then we can list your name in 0.13.0 release note.

**Pull request closed without merging**
