### PR TITLE
GH-39350: [CI] Update upload-artifact and download-artifact actions to v4

### LINKED ISSUE #39350: [CI] Update upload-artifact and download-artifact versions to v4
### Describe the enhancement requested

Dependabot opened this PR: https://github.com/apache/arrow/pull/39284#event-11279329073

We have to update also the upload-artifact action to v4.

We should try to update all of them and be consistent.

### Component(s)

Continuous Integration

### PR DESCRIPTION
**Pull request by raulcd**
### Rationale for this change

Update to newer version of GH action.

### What changes are included in this PR?

Update upload-artifact and download-artifact actions to v4

### Are these changes tested?

Will run Archery tasks

### Are there any user-facing changes?

No
* Closes: #39350

### CODE REVIEW

**Comment by raulcd** [comment]
@github-actions crossbow submit -g packaging

**Comment by raulcd** [comment]
@github-actions crossbow submit -g r

**Comment by raulcd** [comment]
@github-actions crossbow submit r-binary-packages

**Comment by raulcd** [comment]
@github-actions crossbow submit test-r-arrow-backwards-compatibility

**Comment by raulcd** [comment]
@github-actions crossbow submit r-binary-packages

**Comment by raulcd** [comment]
@github-actions crossbow submit r-binary-packages

**Comment by raulcd** [comment]
@github-actions crossbow submit r-binary-packages

**Comment by kou** [comment]
Done by #44086.

**Pull request closed without merging**
