### PR TITLE
ARROW-1156: [C++/Python] Expand casting API, add UnaryKernel callable. Use Cast in appropriate places when converting from pandas

### PR DESCRIPTION
**Pull request by wesm**
cc @cloud-fan 

With this patch we now try to cast to indicated type on ingest of objects from pandas:

```
In [3]: arr = np.array([None] * 5)

In [4]: pa.Array.from_pandas(arr)
Out[4]: 
<pyarrow.lib.NullArray object at 0x7f6cf1485d18>
[
  NA,
  NA,
  NA,
  NA,
  NA
]

In [5]: pa.Array.from_pandas(arr, type=pa.int32())
Out[5]: 
<pyarrow.lib.Int32Array object at 0x7f6cf1485d68>
[
  NA,
  NA,
  NA,
  NA,
  NA
]
```

I also added zero-copy casts from integers of the right size to each of the date and time types.

Includes refactoring for ARROW-1481.

### CODE REVIEW

**Comment by wesm** [comment]
@xhochy the way you would use the CastKernel is something like

```
std::unique_ptr<CastKernel> func;
RETURN_NOT_OK(GetCastFunction(*array.type(), out_type, options, &func));

// Obtain preallocate internal::ArrayData

(*func)(ctx, array, out_data.get());

RETURN_IF_ERROR(ctx);

std::shared_ptr<Array> result;
RETURN_NOT_OK(internal::MakeArray(out_data, &result));
```

We can iterate on the API of course

**Comment by wesm** [comment]
Making a little progress!

```python
In [2]: arr = pa.array([1,2,3,4,5])

In [3]: arr
Out[3]: 
<pyarrow.lib.Int64Array object at 0x7fb737f04868>
[
  1,
  2,
  3,
  4,
  5
]

In [4]: arr.cast(pa.int8())
Out[4]: 
<pyarrow.lib.Int8Array object at 0x7fb737f04b38>
[
  1,
  2,
  3,
  4,
  5
]

In [5]: arr = pa.array([100000])

In [6]: arr.cast(pa.int16())
---------------------------------------------------------------------------
ArrowInvalid                              Traceback (most recent call last)
<ipython-input-6-88dd446f3079> in <module>()
----> 1 arr.cast(pa.int16())

~/code/arrow/python/pyarrow/array.pxi in pyarrow.lib.Array.cast (/home/wesm/code/arrow/python/build/temp.linux-x86_64-3.5/lib.cxx:23822)()
    136 
    137         with nogil:
--> 138             check_status(Cast(_context(), self.ap[0], target_type.sp_type,
    139                               options, &result))
    140 

~/code/arrow/python/pyarrow/error.pxi in pyarrow.lib.check_status (/home/wesm/code/arrow/python/build/temp.linux-x86_64-3.5/lib.cxx:7775)()
     75         message = frombytes(status.message())
     76         if status.IsInvalid():
---> 77             raise ArrowInvalid(message)
     78         elif status.IsIOError():
     79             raise ArrowIOError(message)

ArrowInvalid: Integer value out of bounds
```

**Comment by wesm** [comment]
This is completed

**Review by xhochy — COMMENTED** [review]
+1, API looks nice from just looking at it. I'm going to spent some time to see if I can use it in `parquet-cpp`. Feel free to merge, we can then iterate on it later on.

**Pull request closed without merging**
