### PR TITLE
GH-34148: [C++] Revert zstd back to 1.5.2

### LINKED ISSUE #34148: [C++] Minimal build failed in crossbow because of zstd v1.5.4 requires CMake v3.18
### Describe the bug, including details regarding any error messages, version, and platform.

After patch https://github.com/apache/arrow/pull/34114 is merged, crossbow CI was broken: https://github.com/ursacomputing/crossbow/actions/runs/4153851721/jobs/7185765610#step:3:1131

This is because zstd v1.5.4 introduce [CheckLinkerFlag](https://cmake.org/cmake/help/latest/module/CheckLinkerFlag.html), which is introduced in https://github.com/facebook/zstd/pull/3392 . And our crossbow CI install cmake 3.16, which didn't support it.

### Component(s)

C++, Developer Tools

### PR DESCRIPTION
**Pull request by mapleFU**
### Rationale for this change

This patch part reverts https://github.com/apache/arrow/pull/34114 . But it didn't revert the logic for url and sha256 change.

### What changes are included in this PR?

zstd version revert back to v1.5.2

### Are these changes tested?

no

### Are there any user-facing changes?

no

* Closes: #34148

### CODE REVIEW

**Comment by mapleFU** [comment]
@kou @assignUser I didn't revert logic for using release url rather than sha256 here. Just revert zstd version

**Comment by kou** [comment]
@github-actions crossbow submit example-cpp-minimal-build-static

**Comment by mapleFU** [comment]
The building issue is same as https://github.com/apache/arrow/issues/34188 ...

**Review by kou — APPROVED** [review]
+1

We can ignore it for now.

**Pull request merged**
