### PR TITLE
ARROW-6506: [C++] Fix validation of ExtensionArray with struct storage type

### PR DESCRIPTION
**Pull request by jorisvandenbossche**
https://issues.apache.org/jira/browse/ARROW-6506

### CODE REVIEW

**Review by pitrou — APPROVED** [review]
LGTM

**Comment by jorisvandenbossche** [comment]
@pitrou on apveyor their is a segfault during the python csv tests (which does not seem related to this PR). Is that a known failure?

**Comment by pitrou** [comment]
It's the first time I see that. I'm gonna retry the build just in case.

**Comment by pitrou** [comment]
@jorisvandenbossche Can you fix the C++ lint failure on Travis? The Java failure looks unrelated (I got it on another PR)

**Comment by jorisvandenbossche** [comment]
> Can you fix the C++ lint failure on Travis?

I need to make it a habit to run those locally .. (or configure my editor to do that)

**Comment by pitrou** [comment]
It will soon become muscle memory :-)

**Comment by wesm** [comment]
I run the following bash function every time before I `git commit`

```
function arrow_preflight {
    ARROW_PREFLIGHT_DIR=$ARROW_ROOT/cpp/preflight-build
    mkdir -p $ARROW_PREFLIGHT_DIR
    pushd $ARROW_ROOT/cpp
    python build-support/lint_cpp_cli.py src || return

    pushd apidoc
    doxygen || return
    popd

    popd
    pushd $ARROW_PREFLIGHT_DIR
    arrow_cmake
    ninja format
    ninja lint || return
    popd
    pushd $ARROW_ROOT
    ./run-cmake-format.py
    popd
    flake8 $ARROW_ROOT/dev || return
    pushd $ARROW_ROOT/python
    flake8 --count pyarrow || return
    flake8 --count --config=.flake8.cython pyarrow || return
    popd
}
```

**Comment by wesm** [comment]
There were flakes on Joris's Travis CI so I'll just wait for Travis to run on here later today

**Comment by jorisvandenbossche** [comment]
The remaining travis failure seems to be java related.

**Comment by pitrou** [comment]
Thank you @jorisvandenbossche !

**Pull request closed without merging**
