### PR TITLE
GH-40152: [C++] Remove redundant invocation of BatchesFromTable

### PR DESCRIPTION
**Pull request by ywgrit**
### What changes are included in this PR?
This PR fixes a minor performances bug in TableSorter::SortInternal, which invokes BatchesFromTable to get record batches that have been built already.

### Are these changes tested?

Yes, by existing tests.

### Are there any user-facing changes?

No.

* GitHub Issue: #40152

### CODE REVIEW

**Review by benibus — APPROVED** [review]
Code looks good to me. Just make sure to format the title so it'll automatically link to the original issue (https://github.com/apache/arrow/pull/40173#issuecomment-1955732106), e.g:
```
GH-40152: [C++] Remove redunant invocation....
```

**Review by pitrou — APPROVED** [review]

**Comment by pitrou** [comment]
I rebased and will wait for CI.

**Comment by pitrou** [comment]
Ok, the Python test suite failures are because we are Feb 29. They will disappear tomorrow and reappear in 2028 :-)

**Comment by ywgrit** [comment]
> I rebased and will wait for CI.
Thanks

**Pull request merged**
