### PR TITLE
ARROW-12506: [Python] Improve modularity of pyarrow codebase: _feather module

### PR DESCRIPTION
**Pull request by amol-**

### CODE REVIEW

**Review by jorisvandenbossche — COMMENTED** [review]
Looks good to me (I think it's fine to do it in step-wise PRs like this)

**Comment by amol-** [comment]
Removed draft status, I moved the next bunch of work I was doing into another branch and PR. I'll try to attach all the PRs to the same JIRA issue.

**Review by jorisvandenbossche — APPROVED** [review]

**Review by pitrou — CHANGES_REQUESTED** [review]
Can you extract the feather-related declarations from `pyarrow/includes/libarrow.pxd` and move them to a new `pyarrow/includes/libarrow_feather.pxd`? 

Other than that, LGTM.

**Review by pitrou — APPROVED** [review]

**Comment by pitrou** [comment]
CI failure seems unrelated, I'm merging. Thank you @amol- !

**Pull request closed without merging**
