### PR TITLE
ARROW-14393: [C++] GTest linking errors during the source release verification

### PR DESCRIPTION
**Pull request by kszucs**
Pin budled gtest to 1.10.0 as required by the thirdparty toolchain: https://github.com/apache/arrow/blob/master/cpp/cmake_modules/ThirdpartyToolchain.cmake#L1814

vcpkg crossbow build which was failing with the same reason as the source release verification script: https://github.com/ursacomputing/crossbow/runs/3951554360

### CODE REVIEW

**Review by lidavidm — APPROVED** [review]

**Comment by pitrou** [comment]
Why was this done? If you're using the conda package, you shouldn't use the bundled version, and vice-versa.

**Comment by lidavidm** [comment]
IIRC the issue was: we required GTest 1.11, but still installed 1.10 via Conda, and in the end we would use the headers from 1.10 but link to 1.11, because the `-I` directive for the Conda prefix's `include` dir came first. There's a longer discussion on Zulip.

**Comment by pitrou** [comment]
ARROW_GTEST_BUILD_VERSION is not the required version, it's only the version used when building a bundled version. It shouldn't conflict with the conda-installed version.

**Comment by pitrou** [comment]
However, it's an error to both install it with Conda _and_ ask CMake to build a bundled version. I have no clue where this happens, because the release script is a mess.

**Comment by lidavidm** [comment]
Ah, sorry, I misunderstood then - but regardless, the failing builds were building GTest from source, so we still had the version mismatch.

The Zulip discussion starts [here](https://ursalabs.zulipchat.com/#narrow/stream/180245-dev/topic/6.2E0.2E0.20release.20timing/near/258354489)

The better fix would probably have been to prioritize the bundled include directory over the Conda one.

**Pull request closed without merging**
