### PR TITLE
ARROW-8005: [Tools] Update apache mirror links

### PR DESCRIPTION
**Pull request by fsaintjacques**
Change urls from `www*.apache.org/dist` to `downloads.apache.org`.

### CODE REVIEW

**Review by kszucs — APPROVED** [review]
Thanks @fsaintjacques!

**Comment by kszucs** [comment]
@fsaintjacques [seems like](https://github.com/apache/arrow-site/pull/51#issuecomment-607987816) we have more occurrences, could you please update them as well?

**Comment by fsaintjacques** [comment]
I believe that it only applies to the www* sub domain.

**Comment by wesm** [comment]
Yeah, I think this only applies to verification of keys and checksums of releases, so it's fine for us to keep using `https://dist.apache.org/repos/dist/dev/arrow` in our scripts

**Review by wesm — APPROVED** [review]
+1

**Pull request closed without merging**
