### PR TITLE
[EXP] Buildbot workflow for GitHub Actions

### PR DESCRIPTION
**Pull request by kszucs**

### CODE REVIEW

**Comment by kszucs** [comment]
@pitrou I've experienced some flakiness with spinning up the Minio server from the C++ test suite. Have not had that with the buildmaster nor locally.

**Comment by pitrou** [comment]
@kszucs First time I see that, too...

**Comment by pitrou** [comment]
Should this PR be left open?

**Comment by kszucs** [comment]
Nope, we can close it. Fairly easy to reopen if we want to.

**Pull request closed without merging**
