### PR TITLE
ARROW-9524: [CI][Gandiva] Fix c++ unit test failure in Gandiva nightly build

### PR DESCRIPTION
**Pull request by projjal**
This unit test : https://github.com/apache/arrow/blob/d9525f1b19c00e440b3af83a68d1f2bba89a0a24/cpp/src/arrow/ipc/read_write_test.cc#L322 requires test data to pass.

### CODE REVIEW

**Comment by projjal** [comment]
@github-actions crossbow submit -g gandiva

**Comment by wesm** [comment]
you might want to rebase now that I merged ARROW-9512

**Comment by projjal** [comment]
@github-actions crossbow submit -g gandiva

**Comment by projjal** [comment]
@wesm Can you approve?

**Review by kszucs — APPROVED** [review]

**Comment by kszucs** [comment]
Thanks @projjal!

**Pull request closed without merging**
