### PR TITLE
ARROW-2176: [C++] Extend DictionaryBuilder to support delta dictionaries

### PR DESCRIPTION
**Pull request by alendit**

### CODE REVIEW

**Review by xhochy — COMMENTED** [review]
On a first pass this looks ok. Can you add a describing comment to the DictionaryBuilder class on how to use it to get DeltaDictionaries?

**Comment by alendit** [comment]
Added a comment to the `DictionaryBuilder` and ammended the comments on `Finish` and `FinishInternal`. Also rebased on newest `master`.

**Comment by wesm** [comment]
rebaed

**Comment by alendit** [comment]
There was a typo in the last commit. Fixed it and rebased again.

**Review by xhochy — APPROVED** [review]
+1, LGTM

@pitrou / @wesm / @cpcloud please also have a look at this

**Comment by wesm** [comment]
I'm still going to review this and see if there's anything we want to improve. We also need to integrate this with the IPC read path

**Comment by alendit** [comment]
I have a half-done optimization which avoids buffer chaining and double lookups. I also have some ideas about IPC reader and writer. I'll submit them as a separate JIRAs.

**Pull request closed without merging**
