### PR TITLE
ARROW-6362: [C++] Allow customizing S3 credentials provider

### PR DESCRIPTION
**Pull request by pitrou**
Also provide API facilities to use the default provider chain
(looks up environment variables and config files), or a hard-coded
access / secret key pair.

### CODE REVIEW

**Review by fsaintjacques — APPROVED** [review]
Tested locally the narrative test with both environment variables and `$HOME/.aws/credentials` with success.

I recommend the following patch for improved testing:
```
diff --git a/cpp/src/arrow/filesystem/s3fs_narrative_test.cc b/cpp/src/arrow/filesystem/s3fs_narrative_test.cc
index f2ef3235f..ba1758a83 100644
--- a/cpp/src/arrow/filesystem/s3fs_narrative_test.cc
+++ b/cpp/src/arrow/filesystem/s3fs_narrative_test.cc
@@ -193,7 +193,7 @@ void TestBucket(int argc, char** argv) {
 
 void TestMain(int argc, char** argv) {
   S3GlobalOptions options;
-  options.log_level = S3LogLevel::Fatal;
+  options.log_level = FLAGS_verbose ? S3LogLevel::Debug : S3LogLevel::Fatal;
   ASSERT_OK(InitializeS3(options));
 
   if (FLAGS_clear) {
```

CI failure is https://issues.apache.org/jira/browse/ARROW-6509

**Comment by fsaintjacques** [comment]
@pitrou I added the change, feel free to squash if you want a single commit.

**Comment by pitrou** [comment]
Thanks. There's no need to squash since the merge script will do it anyway.

**Comment by pitrou** [comment]
Rebased.

**Pull request closed without merging**
