### PR TITLE
ARROW-11833: [C++]  Fix missing architecture flag for vendored fast_float

### PR DESCRIPTION
**Pull request by timkpaine**
Please don't merge until upstream https://github.com/fastfloat/fast_float/pull/63

### CODE REVIEW

**Comment by timkpaine** [comment]
this has now been merged upstream

**Comment by pitrou** [comment]
We can merge this, but we'll also want to update the vendored fast_float version (it would presumably fix the failures seen in the Valgrind CI job). @nealrichardson, what do you think?

**Comment by nealrichardson** [comment]
No objection from me, my fast_float patch has also been merged upstream

**Comment by pitrou** [comment]
Opened PR #9709 to bump vendored fast_float version.

**Comment by pitrou** [comment]
#9709 was merged, closing.

**Pull request closed without merging**
