### PR TITLE
ARROW-9018: [C++] Remove APIs that were marked as deprecated in 0.17.0 and prior

### PR DESCRIPTION
**Pull request by wesm**
These are mostly Status APIs that now use Result.

### CODE REVIEW

**Review by pitrou — APPROVED** [review]
+1. Feels good to remove all this :-)

**Comment by kou** [comment]
This breaks Turbodbc: https://github.com/dask/dask/blob/master/dask/dataframe/io/parquet/arrow.py#L9

Turbodbc uses `Status AllocateResizableBuffer(MemoryPool* pool, ...)`: https://github.com/blue-yonder/turbodbc/blob/master/cpp/turbodbc_arrow/Test/tests/arrow_result_set_test.cpp#L113

@xhochy Could you change Turbodbc to use `Result<std::unique_ptr<ResizableBuffer>> AllocateResizableBuffer(const int64_t size, MemoryPool* pool = NULLPTR)`?

**Comment by xhochy** [comment]
@kou Thanks for the heads-up, made a PR: https://github.com/blue-yonder/turbodbc/pull/270

**Comment by kou** [comment]
Great!

**Pull request closed without merging**
