### PR TITLE
ARROW-5727: [Python] [CI] Install pytest-faulthandler before running tests

### PR DESCRIPTION
**Pull request by pitrou**

### CODE REVIEW

**Comment by pitrou** [comment]
I'm regenerating the manylinux build images...

**Comment by pitrou** [comment]
Images uploaded to quay.io now.

**Comment by pitrou** [comment]
Travis-CI build: https://travis-ci.org/pitrou/arrow/builds/550347796
AppVeyor build: https://ci.appveyor.com/project/pitrou/arrow/builds/25531096

**Review by wesm — APPROVED** [review]
+1

**Pull request closed without merging**
