### PR TITLE
GH-42167: [CI] Upgrade the version of vcpkg in .env

### PR DESCRIPTION
**Pull request by adamreeve**
### Rationale for this change

See #42167

### What changes are included in this PR?

* Upgrades the version of vcpkg in .env to the 2024.04.26 version
  * I didn't use the more recent 2024.05.24 release tag as this fails to build boost libraries due to boost updating the tags of the 1.85.0 release and causing hash mismatches
* Upgrade the version of CMake installed in the Python Manylinux docker build due to glog requiring 3.22 or higher
* Rebase the `ports.patch` file

### Are these changes tested?

Yes, this doesn't change behaviour so should be covered by existing tests

### Are there any user-facing changes?

No
* GitHub Issue: #42167

### CODE REVIEW

**Comment by assignUser** [comment]
@github-actions crossbow submit -g vcpkg

**Comment by assignUser** [comment]
@kou should we add those to the vcpkg group?

**Comment by kou** [comment]
It's a good idea!

**Comment by raulcd** [comment]
there seems to be an error on some vcpkg builds to download sqlite3:
```
[DEBUG] 1000: execute_process(curl --fail -L https://sqlite.org/2024/sqlite-autoconf-3450300.tar.gz --create-dirs --output /Users/runner/work/crossbow/crossbow/vcpkg/downloads/sqlite-autoconf-3450300.zip.86985.part)
[DEBUG] 1000: cmd_execute_and_stream_data() returned 7 after    29593 us
error: Failed to download from mirror set
error: https://sqlite.org/2024/sqlite-autoconf-3450300.tar.gz:
```

**Comment by adamreeve** [comment]
> there seems to be an error on some vcpkg builds to download sqlite3:

It looks like the sqlite.org server is having issues. Their website is also failing to load for me, although sometimes succeeding. Hopefully it's a temporary issue that will be resolved soon.

**Comment by adamreeve** [comment]
Looks like the sqlite.org issue should hopefully be resolved now: https://sqlite.org/forum/forumpost/8b1864855e

Can the failing tests be re-run?

**Comment by kou** [comment]
OK! Done!

**Review by kou — APPROVED** [review]
+1

**Pull request merged**
