### PR TITLE
GH-40806: [C++] Correctly report asimd/neon in GetRuntimeInfo

### LINKED ISSUE #40806: [C++] Add support to GetRuntimeInfo for reporting ASIMD/NEON
### Describe the enhancement requested

PyArrow and R arrow have user-facing functions that call into Arrow C++'s `arrow::GetRuntimeInfo()` to report on build and runtime SIMD support:

https://github.com/apache/arrow/blob/4a4d5802bf501dfedb98785587aba53396a46dee/cpp/src/arrow/config.cc#L74-L80

`GetRuntimeInfo` calls into `MakeSimdLevelString` to populate a `RuntimeInfo` object.
 On ARM-based systems, "none" is reported for both SIMD levels which I think is caused by a there being no branch for `CpuInfo::ASIMD`:

https://github.com/apache/arrow/blob/f710ac52b049806515a14445b242c3ec819fb99d/cpp/src/arrow/config.cc#L52-L64

1. Should we add a branch for `CpuInfo::ASIMD`?
2. If so, would it make more sense to call it ASIMD or NEON? They're [related but slightly different concepts](https://developer.arm.com/documentation/dht0002/a/Introducing-NEON/What-is-NEON-) and I'm not sure what language users will be most familiar with and which makes more sense alongside other values.

### Component(s)

C++

### PR DESCRIPTION
**Pull request by amoeba**
### What changes are included in this PR?

New case to conditional in `MakeSimdLevelString` which makes `GetRuntimeInfo` report correctly on respective CPUs. I chose to have it report "neon". Lowercase to match other strings and "neon" instead of "asimd" because I think that makes more sense to users. I'm not 100% sure which is more correct.

Fixes #40806

### Are these changes tested?

We don't have automated tests for this. I did install the R package and, on my M1 laptop it reports 'neon' now instead of 'none' before:

```r
> arrow_info()
...
SIMD Level          neon
Detected SIMD Level neon
```

### Are there any user-facing changes?

No.
* GitHub Issue: #40806

### CODE REVIEW

**Comment by mapleFU** [comment]
Looks ok to me, but I'm not so familiar with arm. Will wait for yibo's comments

**Review by cyb70289 — APPROVED** [review]

**Comment by cyb70289** [comment]
Thanks @amoeba !

**Comment by amoeba** [comment]
Thanks @cyb70289 and @mapleFU!

**Comment by pitrou** [comment]
Hello,
There are two problems with this PR:
1. the possible values should reflect the allowed values for `ARROW_USER_SIMD_LEVEL` (which "neon" is not part of)
2. it broke the [arm64 wheel tests](https://github.com/ursacomputing/crossbow/actions/runs/8526875367/job/23357055648#step:10:791):
```
=================================== FAILURES ===================================
______________________________ test_runtime_info _______________________________

    def test_runtime_info():
        info = pa.runtime_info()
        assert isinstance(info, pa.RuntimeInfo)
        possible_simd_levels = ('none', 'sse4_2', 'avx', 'avx2', 'avx512')
>       assert info.simd_level in possible_simd_levels
E       AssertionError: assert 'neon' in ('none', 'sse4_2', 'avx', 'avx2', 'avx512')
E        +  where 'neon' = RuntimeInfo(simd_level='neon', detected_simd_level='neon').simd_level
```

Can this perhaps be reverted?

**Comment by cyb70289** [comment]
oops, then it should be reverted

**Comment by pitrou** [comment]
Ok, I've opened https://github.com/apache/arrow/pull/40980 to revert.

**Comment by amoeba** [comment]
Thanks for catching this @pitrou.

**Pull request merged**
