### PR TITLE
GH-40154: [C++][Parquet] Separate encoders and decoder

### PR DESCRIPTION
**Pull request by pitrou**
### Rationale for this change

`encoding.cc` is quite large nowadays : around 4000 lines of code, which makes code navigation cumbersome. It combines the functionality of encoders and decoders, however, those use distinct infrastructures and do not share any code.

Other areas of Parquet tend to separate the reading and writing facilities: for example, `column_reader.cc` vs. `column_writer.cc`.

### What changes are included in this PR?

The main change is to move encoders to `encoder.cc`, decoders to `decoder.cc`, and remove `encoding.cc`.

A small improvement is also to remove the inclusion of `arrow/util/spaced.h` in `encoding.h` by moving the `TypedDecoder<T>::DecodeSpaced` implementation into `decoder.cc`.

Note the massive code shuffle may obscure the git history quite a bit. `git log -C` doesn't seem able to track earlier versions of the encoder and decoder code, but `git blame -C` is.

### Are these changes tested?

By existing tests.

### Are there any user-facing changes?

No.

* GitHub Issue: #40154

### CODE REVIEW

**Comment by pitrou** [comment]
@mapleFU @felipecrv @wgtmac This splits encoders and decoder into two separate files, but keeps a single `encoding.h` header. Does that sound ok?

**Comment by pitrou** [comment]
I've checked that `git blame -C` is able to trace back through the history for `encoder.cc` and `decoder.cc` (though `git log -C` isn't, for some reason).

**Comment by wgtmac** [comment]
I just took a glimpse of it. It looks great!

**Comment by mapleFU** [comment]
LGTM

**Review by wgtmac — APPROVED** [review]

**Comment by pitrou** [comment]
@github-actions crossbow submit -g cpp

**Pull request merged**
