### PR TITLE
ARROW-17153: [CI][Homebrew] Require glib-utils

### PR DESCRIPTION
**Pull request by kou**

### CODE REVIEW

**Comment by kou** [comment]
@github-actions crossbow submit homebrew-cpp

**Comment by kou** [comment]
@github-actions crossbow submit homebrew-cpp

**Comment by kou** [comment]
+1

**Comment by raulcd** [comment]
Could [this nightly packaging failure for java-jars](https://github.com/ursacomputing/crossbow/runs/7445570916?check_suite_focus=true) be related?
```
Installing glib-utils
Warning: 'glib-utils' formula is unreadable: No available formula with the name "glib-utils". Did you mean git-utils?
Warning: No available formula with the name "glib-utils". Did you mean git-utils?
==>Searching for similarly named formulae...
This similarly named formula was found:
git-utils
To install it, run:
  brew install git-utils
==>Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==>Searching taps on GitHub...
Error: No formulae found in taps.
Installing glib-utils has failed!
```

**Comment by kou** [comment]
Yes. I'll fix this soon.

**Pull request merged**
