### PR TITLE
ARROW-1748: [GLib] Add GArrowRecordBatchBuilder

### PR DESCRIPTION
**Pull request by kou**

### CODE REVIEW

**Comment by kou** [comment]
I don't know why C++ and Python tests are failed on Linux and macOS.
Is #1268 related?

**Comment by cpcloud** [comment]
@kou Not sure about c++ but #1268 fixes python tests.

**Comment by kou** [comment]
@cpcloud Thanks. I'll rebase on master and confirm Travis CI result after #1268 is merged.

**Comment by kou** [comment]
I rebased and confirmed all tests on Travis CI are green.

**Review by wesm — APPROVED** [review]
+1, thanks @kou!

**Pull request closed without merging**
