### PR TITLE
GH-39640: [Docs] Pin pydata-sphinx-theme to 0.14.1

### LINKED ISSUE #39640: [Docs] The message appearing when selecting dev version of the documentation is wrong
### Describe the bug, including details regarding any error messages, version, and platform.

When I navigate to: https://arrow.apache.org/docs/dev/index.html

I see the following message:
image

`This is documentation for version 0.14.0.`
The version should appear as `15.0.0 (dev)` or something like that.

### Component(s)

Documentation

### PR DESCRIPTION
**Pull request by AlenkaF**
The version warning banner in the documentation has the wrong version: it currently uses `pydata-sphinx-version` instead of Arrow dev version. Testing if the update in upstream fixes this error in version `14.0.1`.
* Closes: #39640

### CODE REVIEW

**Comment by AlenkaF** [comment]
@github-actions crossbow submit preview-docs

**Comment by AlenkaF** [comment]
Forgot the versions banner can't be tested with GitHub actions. Will try to set up the docs locally so that the versions can be tested.

**Comment by AlenkaF** [comment]
Tested locally, version `14.0.1` of `pydata-sphinx-theme` fixes this issue:

--- TOP ---
Screenshot 2024-01-17 at 16 20 10

--- BOTTOM with package version ---
Screenshot 2024-01-17 at 16 20 14

**Comment by AlenkaF** [comment]
cc @raulcd

**Review by raulcd — APPROVED** [review]
Thanks @AlenkaF .

This seems to be the upstream PR that fixes the issue in case someone takes a look in the future: https://github.com/pydata/pydata-sphinx-theme/pull/1446

**Comment by jorisvandenbossche** [comment]
Hmm, I would have thought that `pydata-sphinx-theme=0.14` would install the latest 0.14.x version (at least that was my intention when adding the pin), but apparently not ...

**Comment by jorisvandenbossche** [comment]
OK, for pip requirements, it should probably have been `~= 0.14` or `==0.14.*` (for conda I suppose what I did works)

**Pull request merged**
