### PR TITLE
ARROW-9438: [CI] Add spark patch to compile with recent Arrow Java changes

### PR DESCRIPTION
**Pull request by BryanCutler**
Recent changes in Arrow Java from ARROW-9300 now require adding a dependency on arrow-memory-netty to provide a default allocator. This adds a patch to build spark with the required dependency.

### CODE REVIEW

**Comment by BryanCutler** [comment]
@ursabot crossbow submit test-conda-python-3.8-spark-master

**Comment by BryanCutler** [comment]
This should fix the issues with Spark Scala tests, but there will most likely still be a failure with PySpark grouped map test with structs of timestamps. That will need a bit more effort and another patch cc @kszucs

**Comment by kszucs** [comment]
@ursabot crossbow submit test-conda-python-3.8-spark-master

**Comment by rymurr** [comment]
I should have been aware of the effects ARROW-9300 was goign to have downstream. Anything I can assist with @BryanCutler ?

**Comment by bkietz** [comment]
Timezone related failure from [crossbow](https://github.com/apache/arrow/pull/7746#issuecomment-658105107) https://github.com/ursa-labs/crossbow/runs/868904910#step:6:14426

**Comment by wesm** [comment]
AFAICT this can be merged? The timestamp related problems will require follow up work

**Comment by BryanCutler** [comment]
Thanks @kszucs for fixing up the Docker file!

> I should have been aware of the effects ARROW-9300 was goign to have downstream. Anything I can assist with @BryanCutler ?

No worries @rymurr ! The java changes were pretty minimal and I think that's all working well now. 

> AFAICT this can be merged? The timestamp related problems will require follow up work

The current timezone failure is the result of https://github.com/apache/arrow/pull/7604 and was expected here. Since this improves a little to only 1 known failure, I think this is ok to be merged. I will open another PR for the remaining issue when I'm able to get to it.

**Review by wesm — APPROVED** [review]
+1

**Pull request closed without merging**
