### PR TITLE
MINOR: [Docs] Update implementation matrix for view types in arrow-rs

### PR DESCRIPTION
**Pull request by wiedld**
### Rationale for this change

BinaryView and Utf8View are now supported in arrow-rs [as of the 52.0.0 release](https://github.com/apache/arrow-rs/issues/5374#issuecomment-2261464353).

### What changes are included in this PR?

Add two checkmarks for the Data Type support.

### Are these changes tested?

N/A

### Are there any user-facing changes?

N/A

### CODE REVIEW

**Comment by kou** [comment]
@github-actions crossbow submit preview-docs

**Comment by kou** [comment]
@alamb arrow-rs doesn't support Large Binary View/Large Utf8 View yet, right?

**Review by alamb — APPROVED** [review]
Thank you @wiedld

**Comment by alamb** [comment]
I double checked that there is no more use of the merging script mentioned in 
 https://arrow.apache.org/docs/developers/reviewing.html and recent PRs like https://github.com/apache/arrow/pull/44170 appear to have been merged via the github button.

> @github-actions crossbow submit preview-docs


@kou do we need to wait for any other tests for the docs? All the tests I can see on this PR and the crossbow docs in https://github.com/apache/arrow/pull/44175#issuecomment-2363164210 seem to be passing now

**Comment by kou** [comment]
The preview URL: http://crossbow.voltrondata.com/pr_docs/44175/status.html

**Comment by kou** [comment]
Thanks for confirming the Large Binary View/Large Utf8 View statuses.

I confirmed that rendered HTML is good.

We're still using the merge script https://github.com/apache/arrow/blob/main/dev/merge_arrow_pr.py . I used it to merge https://github.com/apache/arrow/pull/44170 .

All document related CIs were passed. So this is ready to merge. I'll merge this by the merge script.

**Comment by alamb** [comment]
Thank you @kou

**Pull request merged**
