### PR TITLE
ARROW-17067: [C++][Gandiva] Fixing Errors in substring Index

### PR DESCRIPTION
**Pull request by SG011**
Fixing the Errors in Substring_index Also added a change in a comment in floor function

### CODE REVIEW

**Comment by SG011** [comment]
@ViniciusSouzaRoque can you review this?

**Review by ViniciusSouzaRoque — APPROVED** [review]
Now this is working like the java side.
**LGTM**

**Comment by ViniciusSouzaRoque** [comment]
> @ViniciusSouzaRoque can you review this? Also can you convey Ravindra to merge the sqrt pr?

About SQRT we need wait projjal's approve, but I will request merge to Ravindra when that happens

**Comment by SG011** [comment]
@projjal can you review this?

**Comment by amol-** [comment]
Closing because it has been untouched for a while, in case it's still relevant feel free to reopen and move it forward 👍

**Pull request closed without merging**
