### PR TITLE
ARROW-14217: [Python][CI] Add support for python 3.10

### PR DESCRIPTION
**Pull request by kszucs**

### CODE REVIEW

**Comment by kszucs** [comment]
@github-actions crossbow submit *cp310*

**Comment by kszucs** [comment]
@github-actions crossbow submit wheel-macos-big-sur-cp310*

**Comment by kszucs** [comment]
@github-actions crossbow submit *cp310*

**Comment by kszucs** [comment]
@github-actions crossbow submit wheel-manylinux*cp310*

**Comment by kszucs** [comment]
@github-actions crossbow submit wheel-manylinux*cp310*

**Comment by pitrou** [comment]
Why don't you start by adding a GHA entry for Python 3.10?

**Comment by kszucs** [comment]
> Why don't you start by adding a GHA entry for Python 3.10?

You mean an additional conda based build?

**Comment by kszucs** [comment]
@github-actions crossbow submit wheel-manylinux*cp310*

**Comment by pitrou** [comment]
> You mean an additional conda based build?

Hmm, my bad, there's no conda package available.

**Comment by kszucs** [comment]
@github-actions crossbow submit wheel-manylinux*cp310*

**Comment by kszucs** [comment]
The manylinux builds are working, but the testing docker images have not been released yet - matter of days I guess.

For the rest of the wheels we need to wait for the next numpy release.

**Comment by kszucs** [comment]
@github-actions crossbow submit test-conda-python-3.10

**Comment by pitrou** [comment]
"test-conda-python-3.10" will fail as long as Numpy and other packages are not available yet for Python 3.10 on conda-forge.

**Comment by pitrou** [comment]
> We may also need to bump the manylinux image tag because the interpreter path indicates [cypthon version 3.10-rc2](https://github.com/ursacomputing/crossbow/runs/3886034769?check_suite_focus=true#step:7:3184)

The wheel has the right tag apparently: "pyarrow-6.0.0.dev470-cp310-cp310-manylinux_2_12_x86_64.manylinux2010_x86_64.whl".
See https://github.com/ursacomputing/crossbow/runs/3886034769?check_suite_focus=true#step:7:6079

**Comment by pitrou** [comment]
I'm not sure what waiting would bring here. We have a working fine to fix the tests already, and we can produce manylinux wheels. We can add the rest later.

**Comment by pitrou** [comment]
Yes, that sounds good to me.

**Review by kszucs — COMMENTED** [review]
+1, merging on green

**Pull request closed without merging**
