### PR TITLE
ARROW-16567: [Doc][Python] Sphinx Copybutton should ignore IPython prompt text

### PR DESCRIPTION
**Pull request by AlenkaF**

### CODE REVIEW

**Comment by AlenkaF** [comment]
The CI error is not connected
```
/opt/conda/envs/arrow/lib/python3.9/site-packages/pyarrow/compute.py:201: RuntimeWarning: Python binding for RankOptions not exposed
  warnings.warn("Python binding for {} not exposed"
````
and will be removed when https://github.com/apache/arrow/pull/13327 is merged.

**Comment by pitrou** [comment]
Note the actual CI error is:
```
PR01: Parameters {'thrift_string_size_limit', 'thrift_container_size_limit'} not documented
```

and should be fixed if you rebase from master (it's my fault, sorry).

**Review by pitrou — APPROVED** [review]
+1, I'm assuming you tested it :-)

**Comment by AlenkaF** [comment]
Oh, thanks for the info! Now I get why it is happening elsewhere also =)
Yes, tested it - have it recorded! :D

**Pull request merged**
