### PR TITLE
ARROW-5698: [R] Fix docker-compose build

### PR DESCRIPTION
**Pull request by wesm**

### CODE REVIEW

**Comment by wesm** [comment]
@ursabot crossbow test docker-r

**Comment by wesm** [comment]
@kszucs seems like ursabot crossbow triggers are down

**Comment by wesm** [comment]
It's weird that the Circle CI badge says Failed when the job is still running

**Comment by wesm** [comment]
+1

**Comment by kszucs** [comment]
I'm aware of that, but hasn't found a solution yet, I'll try to update the badges' url to the ones provided by shields.io

**Pull request closed without merging**
