### PR TITLE
ARROW-5330: [CI] Run Python Flight tests on Travis [skip appveyor]

### PR DESCRIPTION
**Pull request by pitrou**

### CODE REVIEW

**Comment by pitrou** [comment]
+1

**Comment by pitrou** [comment]
@lihalite @wesm Any objection?

**Comment by lihalite** [comment]
I see this in the logs:

```
SKIPPED [1] /home/travis/build/apache/arrow/python/pyarrow/tests/test_flight.py:33: could not import 'pyarrow.flight'
```

It looks like PyArrow still doesn't build the Flight components.

**Comment by pitrou** [comment]
Uh, really? I'm gonna take a look.

**Comment by pitrou** [comment]
Ok, Unix shell being a lame language as usual...

**Comment by pitrou** [comment]
Of course I still failed it :-/

**Review by wesm — APPROVED** [review]
+1

**Review by ghost — APPROVED** [review]
LGTM.

**Comment by pitrou** [comment]
For reference: non-truncated Travis log here: https://travis-ci.org/pitrou/arrow/jobs/534945439

**Pull request closed without merging**
