### PR TITLE
ARROW-7750: [Release] Make the source release verification script restartable

### PR DESCRIPTION
**Pull request by kszucs**
Executing the verification script can take quite some time, so creating a new environment in case if anything fails is time consuming.
Let the script reuse the same build directory for source release verification.

Need to export `TMPDIR` environment variable. @kou shall we use an argument instead?

### CODE REVIEW

**Comment by nealrichardson** [comment]
I attempted to use this when verifying the release candidate but did not realize I had to set an env var to have a persistent directory. It otherwise succeeded, but then the `rm -rf $TMPDIR` at the end failed to delete the dir in /tmp. 

```
+ TEST_SUCCESS=yes
+ echo 'Release candidate looks good!'
Release candidate looks good!
+ exit 0
+ cleanup
+ '[' yes = yes ']'
+ rm -fr /var/folders/jf/t7_zsd293791z5qwt2_bv8640000gn/T/
rm: /var/folders/jf/t7_zsd293791z5qwt2_bv8640000gn/T/: Operation not permitted
```

Not critical since the verification already succeeded I guess.

**Review by kszucs — COMMENTED** [review]
+1

**Comment by kou** [comment]
Environment variable is OK but the name, `TMPDIR`,  isn't suitable.
Because `TMPDIR` is too generic. Many commands such as `mktemp` refer `TMPSDIR`. And macOS defines `TMPDIR` by default.

`ARROW_TMPDIR`, `TEST_TMPDIR` or something is better.

**Comment by kszucs** [comment]
@kou filed an issue https://issues.apache.org/jira/browse/ARROW-7771

**Pull request closed without merging**
