### PR TITLE
GH-35609: [Docs] Enable the build of subsections of the documentation

### LINKED ISSUE #35609: [Docs] Enable the build of subsections of the documentation
### Describe the enhancement requested

We should add new `make` commands to be able to build only a subset of the docs like we can currently do with `make python`.

Connected to the work in https://github.com/apache/arrow/issues/30627, this issue would be easy first solution without needing to make separate sphinx projects and use Intersphinx.

The links will in this case break but the documentation can still be built and the development can be hugely simplified with it.

### Component(s)

Documentation

### PR DESCRIPTION
**Pull request by AlenkaF**
### Rationale for this change

Ease the process of building the documentation for dev purposes.

### What changes are included in this PR?

- `make` options to build subsections of the documentation (format, developers, cpp together with existing python)
- `make` option for auto-build of the docs
- added info about the new make commands
* Closes: #35609

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
@github-actions crossbow submit preview-docs

**Comment by AlenkaF** [comment]
@github-actions crossbow submit preview-docs

**Comment by AlenkaF** [comment]
@github-actions crossbow submit preview-docs

**Comment by jorisvandenbossche** [comment]
When trying `make dev` (on a clean build), I get warnings about the images not being found:

```
/home/joris/scipy/repos/arrow/docs/source/developers/guide/architectural_overview.rst:: WARNING: image file not readable: developers/images/R_architectural_overview.png
/home/joris/scipy/repos/arrow/docs/source/developers/guide/documentation.rst:: WARNING: image file not readable: developers/images/edit_page.jpeg
/home/joris/scipy/repos/arrow/docs/source/developers/guide/documentation.rst:: WARNING: image file not readable: developers/images/github_edit_page.jpeg
...
```

Is that a consequence of building only the subdirectory?

**Comment by AlenkaF** [comment]
Yeah, unfortunately this is a consequence of building from the subdirectory.

The source dir is in this case `docs/source/developers/` but the link of the picture points to the subdir named `developers/` which only exists if the source dir is `docs/source`

```
R package Architectural Overview
--------------------------------

.. figure:: /developers/images/R_architectural_overview.png
   :alt: Main parts of R package architecture: dplyr-*,
         dplyr-funcs*, tools, tests and src/.
```

**Comment by jorisvandenbossche** [comment]
When just building the format docs (`make format`), I see that some images _do_ work, though. Those use a relative path, so that could maybe be a solution

**Comment by jorisvandenbossche** [comment]
So eg `.. figure:: ../images/R_architectural_overview.png` instead of `.. figure:: /developers/images/R_architectural_overview.png`

**Comment by AlenkaF** [comment]
Oh, this is great. Sorry I haven't noticed it before, thanks!
Will correct 👍

**Comment by jorisvandenbossche** [comment]
@github-actions crossbow submit preview-docs

**Review by jorisvandenbossche — APPROVED** [review]
Thanks!

**Pull request merged**
