### PR TITLE
ARROW-9821: [Rust][DataFusion] Make crate::logical_plan and crate::physical_plan modules

### PR DESCRIPTION
**Pull request by alamb**
This is a proposal PR that I thought would be easier to do via PR rather than email. FYI @jorgecarleitao and @andygrove 

The context is that I plan to make `LogicalPlan` based on traits to allow extensibility, rather than a hard coded enum, to mirror how `ExecutionPlans` work. 

As an initial smalls step towards this goal, I propose consistent module naming for logical and physical plans

So after this PR we have the top level modules:
* logical_plan
* physical_plan
* optimizer (currently depends on both logical_plan and physical_plan)
* execution (has context, and df)

The logical change here is quite small:

Commit 1 has the result of running these commands:
```
mkdir logical_plan
git mv logicalplan.rs logical_plan/mod.rs
git mv execution/physical_plan .
```

And the next two commits simply update all references to the new module locations, and the last formats the code for good measure

As follow on PRs (as I define the LogicalPlanNode trait) I would likely propose splitting the logical_plan/mod.rs into other smaller modules.

### CODE REVIEW

**Review by andygrove — APPROVED** [review]
Thanks @alamb I had been intending to do something similar myself. LGTM pending CI.

**Comment by jorgecarleitao** [comment]
LGTM after lint. It makes much more sense to me, also!

**Comment by andygrove** [comment]
@alamb @jorgecarleitao There are 4 approved DataFusion PRs (including this one) that need merging. Do you have any preference as to which order they get merged in? I can imagine that there are going to be conflicts with this one, so probably will need to rebase this after the other 3 are merged?

**Comment by alamb** [comment]
I suggest merging Jorge's first and I will rebase mine

**Comment by alamb** [comment]
I have rebased and collapsed this together into a single commit as there were quite a few conflicts. Here are the commands I used (mostly for my own records if/when I have to do this again):

```
cd arrow/rust/datafusion
mkdir src/logical_plan
git mv src/logicalplan.rs src/logical_plan/mod.rs
git mv src/execution/physical_plan src
find . -name '*.rs' | xargs sed -i '' -e 's|execution::physical_plan|physical_plan|g'
find . -name '*.rs' | xargs sed -i '' -e 's|logicalplan|logical_plan|g'
# manually touch up datafusion/src/lib.rs, etc
git commit -a -m 'ARROW-9821: [Rust][DataFusion] Make crate::logical_plan and crate::physical_plan modules'
```

**Comment by andygrove** [comment]
@alamb Sorry, needs one more rebase.

**Comment by alamb** [comment]
> @alamb Sorry, needs one more rebase.

No problem -- done

**Pull request closed without merging**
