### PR TITLE
ARROW-4872: [Python] Keep backward compatibility for ParquetDatasetPiece

### PR DESCRIPTION
**Pull request by kszucs**
Still needs to run dask integration test.

### CODE REVIEW

**Comment by wesm** [comment]
Appveyor failure appears to be a transient flake

```
Command "python setup.py egg_info" failed with error code 1 in C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-_0vb4snu\
You are using pip version 10.0.1, however version 19.0.3 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
'clcache' is not recognized as an internal or external command,
operable program or batch file.
'clcache' is not recognized as an internal or external command,
operable program or batch file.
'clcache' is not recognized as an internal or external command,
operable program or batch file.
Start-Process : This command cannot be run due to the error: The system cannot 
find the file specified.
At line:1 char:1
+ Start-Process clcache-server
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Start-Process], InvalidOp 
   erationException
    + FullyQualifiedErrorId : InvalidOperationException,Microsoft.PowerShell.C 
   ommands.StartProcessCommand
 
Command exited with code 1
```

**Comment by kszucs** [comment]
The dask instegration test has issues with the format of `pandas_metadata['index_columns']`:
`TypeError: unhashable type: 'dict'`. I'm investigating it.

Did We change the pandas metadata BTW?

**Comment by kszucs** [comment]
Full error: 
```python
    def _parse_pandas_metadata(pandas_metadata):
        """Get the set of names from the pandas metadata section

        Parameters
        ----------
        pandas_metadata : dict
            Should conform to the pandas parquet metadata spec

        Returns
        -------
        index_names : list
            List of strings indicating the actual index names
        column_names : list
            List of strings indicating the actual column names
        storage_name_mapping : dict
            Pairs of storage names (e.g. the field names for
            PyArrow) and actual names. The storage and field names will
            differ for index names for certain writers (pyarrow > 0.8).
        column_indexes_names : list
            The names for ``df.columns.name`` or ``df.columns.names`` for
            a MultiIndex in the columns

        Notes
        -----
        This should support metadata written by at least

        * fastparquet>=0.1.3
        * pyarrow>=0.7.0
        """
        index_storage_names = pandas_metadata['index_columns']
        index_name_xpr = re.compile(r'__index_level_\d+__')

        # older metadatas will not have a 'field_name' field so we fall back
        # to the 'name' field
        pairs = [(x.get('field_name', x['name']), x['name'])
                 for x in pandas_metadata['columns']]

        # Need to reconcile storage and real names. These will differ for
        # pyarrow, which uses __index_leveL_d__ for the storage name of indexes.
        # The real name may be None (e.g. `df.index.name` is None).
        pairs2 = []
        for storage_name, real_name in pairs:
            if real_name and index_name_xpr.match(real_name):
                real_name = None
            pairs2.append((storage_name, real_name))
        index_names = [name for (storage_name, name) in pairs2
                       if name != storage_name]

        # column_indexes represents df.columns.name
        # It was added to the spec after pandas 0.21.0+, and implemented
        # in PyArrow 0.8. It's not currently impelmented in fastparquet.
        column_index_names = pandas_metadata.get("column_indexes", [{'name': None}])
        column_index_names = [x['name'] for x in column_index_names]

        # Now we need to disambiguate between columns and index names. PyArrow
        # 0.8.0+ allows for duplicates between df.index.names and df.columns
        if not index_names:
            # For PyArrow < 0.8, Any fastparquet. This relies on the facts that
            # 1. Those versions used the real index name as the index storage name
            # 2. Those versions did not allow for duplicate index / column names
            # So we know that if a name is in index_storage_names, it must be an
            # index name
            index_names = list(index_storage_names)  # make a copy
>           index_storage_names2 = set(index_storage_names)
E           TypeError: unhashable type: 'dict'

opt/conda/lib/python3.6/site-packages/dask/dataframe/io/parquet.py:91: TypeError
```

@wesm if You have a quick hint how to resolve it please share with me :)
The best I can think of to introduce a new key and use that instead of `column_indexes`.

**Comment by wesm** [comment]
This is because of https://github.com/pandas-dev/pandas/pull/25709

I don't know at a glance what to do about it. I'm traveling today and tomorrow and so not sure how much time I will have to work on this

**Comment by kszucs** [comment]
@martindurant it looks like We won't be able to remain fully compatible with the latest dask release, see the error above, but theoretically it only impacts files written by pyarrow.

**Comment by martindurant** [comment]
cc @jcrist @mrocklin , not sure who has time to deal with this. I think parquet-written-by-arrow is a pretty important case for us!

**Comment by wesm** [comment]
I'm looking at this right now

**Comment by wesm** [comment]
I'm going to try to create a PR to dask to get the integration tests passing again on master at least. 

@martindurant @jcrist can you please give feedback on the proposed metadata changes in https://github.com/pandas-dev/pandas/pull/25709 to allow `RangeIndex` to be stored as metadata rather than serialized as a column? This is a bit time-sensitive because we are about to cut an Arrow release with these changes.

**Comment by wesm** [comment]
This is very difficult to resolve. I don't think that the way that Dask interacts with either pyarrow or fastparquet is very sustainable, and I think it should be rethought. 

The interactions between the index storage, the metadata (and the inconsistent implementations thereof), and the logic that infers divisions do not look good at all to me. I'm looking at this code in particular: https://github.com/dask/dask/blob/master/dask/dataframe/io/parquet.py#L795.

I'm inclined to just let this be broken to force resolution within dask, which may require a fair bit of refactoring. If we keep piling hacks on top of our existing hacks, things are just going to get worse.

**Comment by wesm** [comment]
I reverted the metadata for serialized (non-Range) indexes to be just a string instead of `{'kind': 'serialized', 'field_name': index.name}`. I'll update the pandas PR when I can

**Comment by mrocklin** [comment]
> I don't think that the way that Dask interacts with either pyarrow or fastparquet is very sustainable, and I think it should be rethought.

> The interactions between the index storage (and the way that the problem of index storage is left to the Parquet implementation), the metadata (and the inconsistent implementations thereof), and the logic that infers divisions do not look good at all to me.

Entirely agreed.  I started a full rewrite of Dask's parquet reader here, starting with the Arrow side of it.

https://github.com/dask/dask/pull/4336

However, I ran into some missing pieces in arrow, like the ability to collect metadata and write metadata files.  I would like to find some time to continue pushing on things on the Dask side here if we can quickly get a few things into Arrow.  I've tried finding resources local to me to do this, but so far haven't had luck.  I agree that generarlly it would be nice to retire the old implementations, both for future features, and for general maintenance.

(sorry for my delay in response here.  was handling personal things over the last few days).

**Comment by wesm** [comment]
@mrocklin thank you, that sounds great. I can personally make some time for this if needed potentially in early April or sometime in May to sprint on the things the Dask needs, if it helps with maintainability

Could you start a thread on the mailing list about this and we can enumerate the JIRA issues needed to move things forward?

**Comment by mrocklin** [comment]
Sure.  I'll review the PR again and summarize what I think would be nice to have in Arrow, and what we think would be a good long term contract.  Most of the fires of the day are out.  Hopefully I'll get to this this afternoon.

**Comment by mrocklin** [comment]
Sent

Do Dask devs need to worry about anything here for the next PyArrow release?  It looks like some commit went in that maintained backwards compatibility.  Thanks for that.

**Comment by wesm** [comment]
The 0.13 release breaks a solid chunk of the current Dask test suite (though maybe current workflows are preserved, and existing datasets can be read fine). I spent a couple hours on it but it's a big job to fix; a lot of details of how index columns are serialized in the file have leaked into the `_get_pyarrow_divisions` function. 

Given the changes we made (where RangeIndex is no longer converted to a serialized column of integers, it is stored as metadata), there is nothing that causes a fundamental issue with the way that Dask deals with pandas indexes, but all the code that is aware of the metadata and index serialization needs to be better compartmentalized and decoupled from Dask's business logic regarding divisions

**Comment by mrocklin** [comment]
If you have thoughts on the plan laid out in the rewrite PR linked to above
I would welcome those.  It would be good to make sure that that contract is
something that Arrow is comfortable living with long term.

**Comment by mrocklin** [comment]
> Could you start a thread on the mailing list about this and we can enumerate the JIRA issues needed to move things forward?

https://lists.apache.org/thread.html/6df7cc6585b09149d5735cb0c3190fef49a5d906ff1331bf01626809@%3Cdev.arrow.apache.org%3E

**Comment by mrocklin** [comment]
> The 0.13 release breaks a solid chunk of the current Dask test suite

@martindurant , just checking, but are you or someone else at Anaconda tracking this?  This seems pretty critical to me.

**Comment by martindurant** [comment]
We/I have an eye on this. 
Since the breaking change was reverted, we are awaiting to see what arrow wants to do next, happy to be involved. Again, there is a chance I am misunderstanding, please correct me if I'm wrong here.

As you know, the parquet code in Dask is messy, but we can probably work around any problem fairly easily with version-specific special cases as a stopgap. The bigger issue of rewriting the whole module probably won't happen soon

(also cc @jcrist )

**Comment by martindurant** [comment]
Am I wrong that the change referred to there was reverted? Again, I may be wrong here, but I thought that the [metadata change](https://github.com/pandas-dev/pandas/pull/25709) referenced remains unmerged, so not moving forward with the change in pyarrow seemed ok to me.

> or else drop fastparquet support.

a rapidly moving arrow target seems like the wrong reason to suggest this.

**Comment by mrocklin** [comment]
Agreed.  Lets continue that conversation in https://github.com/dask/dask/pull/4336 ?

**Comment by wesm** [comment]
I'm about to go off the grid until April 22 so I won't be able to help until then at earliest.

**Comment by wesm** [comment]
> a rapidly moving arrow target seems like the wrong reason to suggest this.

I don't think this is an accurate characterization. The problem we are dealing with is broken encapsulation of pandas-in-Parquet serialization details in Dask. I think it would be best to focus efforts on addressing the problem there

**Comment by mrocklin** [comment]
> I'm about to go off the grid until April 22 so I won't be able to help until then at earliest.

Enjoy!

**Pull request closed without merging**
