### PR TITLE
ARROW-3326: [Python] Add NativeFile.align method, wrapping arrow::ipc::AlignStream

### PR DESCRIPTION
**Pull request by wesm**

### CODE REVIEW

**Comment by pitrou** [comment]
I'm not sure what this means to expose this on the Python side.

More generally, I still think the notion of the alignment of a stream doesn't have a lot of meaning. I think IPC messages should have their size rounded to 64, instead of trying to align the stream separately. @fsaintjacques

**Review by fsaintjacques — CHANGES_REQUESTED** [review]
There's a type size error.

**Comment by wesm** [comment]
Well, this is available in Ruby already, so this is partly for API parity

https://github.com/apache/arrow/blob/9d007b1eed283af6cf3b2120f36bced1b27cfe73/c_glib/test/test-buffer-input-stream.rb#L34

This patch doesn't have much to do with IPC directly. Alignment issues are part of the IPC protocol implementation -- if we want to change anything there we should examine in a separate JIRA.

I've adopted the long-term view that these classes may be used for many purposes -- if the user is producing a serialized message of some kind from the Python API without necessarily using the built-in IPC protocol classes, it would be useful to be able to write alignment bytes without having to resort to arithmetic by hand.

**Comment by pitrou** [comment]
Every format has its own way of defining padding and alignment (or neither of them, if they don't mandate any). I don't think providing a generic version of this is useful.

**Comment by wesm** [comment]
Alright, well, since I've done the work I'll leave my branch up in case it proves useful in the future.

**Pull request closed without merging**
