### PR TITLE
ARROW-95: Add Jekyll-based website publishing toolchain, migrate existing arrow-site

### PR DESCRIPTION
**Pull request by wesm**
This also renders the format Markdown documents on the website. Used the Apache Calcite website for guidance about best practices with Jekyll. 

See rendered website at https://wesm.github.io/arrow-site-test/

### CODE REVIEW

**Comment by cpcloud** [comment]
Is there a way to see the site before merging this? No big deal, just curious.

**Comment by wesm** [comment]
https://wesm.github.io/arrow-site-test/

**Comment by wesm** [comment]
Fixing RAT warnings about missing licenses

**Comment by cpcloud** [comment]
Looks good. Are the java/python docs supposed to be throwing 404s?

**Comment by cpcloud** [comment]
The new format is much easier to navigate :)

**Comment by wesm** [comment]
They are supposed to be throwing 404s. I'm working on build instructions for updating the docs. Think we may need a Dockerfile for Python to make it reproducible

**Comment by wesm** [comment]
I took the liberty of updating http://arrow.apache.org/. Now http://arrow.apache.org/docs/java/ is live. Working on http://arrow.apache.org/docs/python/

**Comment by cpcloud** [comment]
Sweet, looks awesome!

**Comment by wesm** [comment]
Now the Python docs are up http://arrow.apache.org/docs/python/. @xhochy can we take down the readthedocs version?

**Comment by wesm** [comment]
The navbar doesn't show up on mobile right now. May need to do a dedicated patch with mobile improvements

**Review by julienledem — APPROVED** [review]
awesome!

**Comment by xhochy** [comment]
Awesome! I made https://pyarrow.readthedocs.io/en/latest/ private.

**Pull request closed without merging**
