### PR TITLE
WIP: [C++] Demonstrate C++ OTel instrumentation

### PR DESCRIPTION
**Pull request by lidavidm**
Instructions:

```
$ mkdir otlp
$ nvim otlp/config.dev.yml
exporters:
  file:
    path: /dev/stdout
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: "0.0.0.0:4318"
        cors_allowed_origins:
        - '*'
service:
  pipelines:
    traces:
      receivers:
      - otlp
      exporters:
      - file
$ docker run --rm -it -p 4317:4317 -p 4318:4318 -v (pwd)/otlp:/cfg otel/opentelemetry-collector:0.40.0 --config=/cfg/config.dev.yml
# In another terminal
$ pwd
/path/to/arrow/repo/root
$ mkdir build; cd build
$ cmake ../cpp -DCMAKE_BUILD_TYPE=RelWithDebInfo -GNinja -DCMAKE_INSTALL_PREFIX=$(pwd)/../install -DCMAKE_INSTALL_LIBDIR=lib -DARROW_DATASET=ON -DARROW_PARQUET=ON -DARROW_JSON=ON -DARROW_CSV=ON -DARROW_WITH_SNAPPY=ON -DARROW_WITH_LZ4=ON -DARROW_S3=ON -DARROW_ENGINE=ON -DARROW_WITH_OPENTELEMETRY=ON
$ ninja install
$ cd ../r
$ export ARROW_HOME=$(pwd)/../install
$ export LD_LIBRARY_PATH=$(pwd)/../install/lib
$ env LIBARROW_DOWNLOAD=false LIBARROW_BUILD=false ARROW_R_DEV=true R CMD INSTALL .
$ R -e 'remotes::install_github("ursacomputing/arrowbench")'
$ env ARROW_TRACING_BACKEND=otlp_http R -e 'library(arrowbench);run_benchmark(tpc_h, engine=c("arrow"), query_id=c(1), format=c("parquet"), scale_factor=c(1))'
# Go look at the terminal running the OTLP collector
```

### CODE REVIEW

**Comment by lidavidm** [comment]
CC @westonpace @felipeblazing @jonkeane @mbrobbel

**Comment by westonpace** [comment]
Asking users to run a separate docker container to get logs feels a bit heavyweight, especially for Windows.  I do get that this is more flexible but how much more work would it be to have a naive ability to dump to a file from Arrow?  This can be a task for another day.

**Comment by lidavidm** [comment]
We could enable the built-in stdout logger, though that logs in a format that's very not-amenable to parsing. We could also restore the JSON logger from the original PR, though that would need some updates to log in a spec-compliant way. Or we could use https://github.com/open-telemetry/opentelemetry-cpp/pull/1111.

**Comment by jonkeane** [comment]
FWIW, stdout might be the easiest lift to get this into conbench (well one I merge https://github.com/ursacomputing/arrowbench/pull/43 we can have conbench consume the stdout from that). 

Conbench could certainly be extended to look for a dump file and store that too, but it would be a slightly bigger lift.

**Comment by lidavidm** [comment]
Ok, I think we can hook up logging JSON to stdout/stderr then.

**Comment by lidavidm** [comment]
I filed ARROW-15044 for this.

**Comment by lidavidm** [comment]
In #11925 we now have two exporters that can be enabled by env var, with some samples of the output - hopefully that'll work for Conbench

**Pull request closed without merging**
