### PR TITLE
ARROW-3713: [Rust] Implement BinaryArrayBuilder

### PR DESCRIPTION
**Pull request by paddyhoran**
Builds on [ARROW-3644](https://github.com/apache/arrow/pull/2914) and [ARROW-3787](https://github.com/apache/arrow/pull/2957).

### CODE REVIEW

**Comment by paddyhoran** [comment]
Thanks @xhochy.  I'll wait until [ARROW-3787](https://github.com/apache/arrow/pull/2957) is merged (which is needed) then rebase.

**Comment by kszucs** [comment]
@paddyhoran You can rebase now.

**Comment by paddyhoran** [comment]
@kszucs @sunchao @andygrove I think this is ready for review now

**Review by sunchao — APPROVED** [review]
LGTM. I see that in Rust we need to call `append(true)` first before appending the actual values while in C++ the order is the opposite. But it looks fine to me.

**Review by kszucs — APPROVED** [review]
LGTM

**Pull request closed without merging**
