### PR TITLE
ARROW-4188: [Rust] Move Rust README to top level rust directory

### PR DESCRIPTION
**Pull request by andygrove**

### CODE REVIEW

**Comment by andygrove** [comment]
Ready for review @sunchao @paddyhoran

**Comment by sunchao** [comment]
Hmm.. this means `arrow` doesn't have a README then. I'm not sure which is better - perhaps we should have README on both the top level dir and `arrow`.

**Comment by andygrove** [comment]
Yes that would make sense. What would you recommend goes in at the `arrow/rust/arrow` level?

**Comment by sunchao** [comment]
I think that should be a README about the arrow crate, as eventually it will be shown in places like crates.io.

**Comment by andygrove** [comment]
@sunchao OK, how about this ... top level README shows info about submodules for people just running `cargo test` at that level

**Comment by sunchao** [comment]
This sounds better to me. Thanks. I think this is a good start and in future we can add more information to both READMEs.

**Review by sunchao — APPROVED** [review]

**Review by kszucs — APPROVED** [review]
LGTM

**Pull request closed without merging**
