### PR TITLE
ARROW-1152: [Cython] read_tensor should work with a readable file

### PR DESCRIPTION
**Pull request by pcmoritz**

### CODE REVIEW

**Comment by wesm** [comment]
Thanks for looking into this. Could you add a unit test?

**Comment by pcmoritz** [comment]
I added the unit test and made sure it doesn't pass on the current master.

**Review by wesm — APPROVED** [review]
+1, thank you! Not sure why the glib test failed, @kou any idea? merging this since it couldn't be related

**Comment by kou** [comment]
It's a GLib bindings bug. I'll fix it. Thank for notifying it!

**Pull request closed without merging**
