### PR TITLE
ARROW-11028: [Rust] Make a few pattern matches more idiomatic

### PR DESCRIPTION
**Pull request by huitseeker**
Some pattern-matches can be replaced by a direct combinator equivalent.

### CODE REVIEW

**Review by jorgecarleitao — APPROVED** [review]
Thanks a lot @huitseeker , definitely more idiomatic and easier to read 👍

**Review by Dandandan — APPROVED** [review]

**Comment by jorgecarleitao** [comment]
@huitseeker , could you rebase?

**Comment by alamb** [comment]
Thanks for the contribution @huitseeker !

**Comment by huitseeker** [comment]
@jorgecarleitao done.

**Pull request closed without merging**
