### PR TITLE
ARROW-3936: [C++] Add _O_NOINHERIT to the file open flags on Windows

### PR DESCRIPTION
**Pull request by philjdf**
Unlike Linux, Windows doesn't let you delete files that are currently opened by another process. So if you create a child process while a Parquet file is open, with the current code the file handle is inherited to the child process, and the parent process can't then delete the file after closing it without the child process terminating first. 

By default, Win32 file handles are not inheritable (likely because of the aforementioned problems). Except for _wsopen_s, which tries to maintain POSIX compatibility.

This is a serious problem for us.

We would argue that specifying _O_NOINHERIT by default in the _MSC_VER path is a sensible approach and would likely be the correct behaviour as it matches the main Win32 API.

However, it could be that some developers rely on the current inheritable behaviour. In which case, the Arrow public API should take a boolean argument on whether the created file descriptor should be inheritable. But this would break API backward compatibility (unless a new overloaded method is introduced).

Is forking and inheriting Arrow internal file descriptor something that Arrow actually means to support?

What do we think of the proposed fix?

### CODE REVIEW

**Comment by philjdf** [comment]
@pitrou: https://issues.apache.org/jira/browse/ARROW-3936, done.

**Comment by philjdf** [comment]
@pitrou The code formatting is fixed now.

**Review by pitrou — APPROVED** [review]
LGTM

**Comment by wesm** [comment]
Is there a way to unit test this?

**Comment by pitrou** [comment]
Not trivially I think. Windows doesn't have `fork()` so you'd need to spawn a child process, have it to grab the same handle (how? perhaps by passing its value on the command line?) and fail. In C++ that would probably entail a lot of boilerplate code.

**Comment by wesm** [comment]
I figured as much. No worries

**Pull request closed without merging**
