### PR TITLE
Fix building manylinux wheels

### PR DESCRIPTION
**Pull request by pitrou**
(hopefully)

### CODE REVIEW

**Comment by pitrou** [comment]
@ursabot crossbow submit -g wheel

**Comment by pitrou** [comment]
@kszucs

**Comment by kszucs** [comment]
https://github.com/ursa-labs/crossbow/branches/all?query=build-739

**Comment by pitrou** [comment]
It looks like all the wheels are ok, except the macOS wheels for unrelated reasons. I'll open a JIRA.

**Comment by pitrou** [comment]
Superseded by #6546.

**Pull request closed without merging**
