### PR TITLE
ARROW-8332: [C++] Don't require Thrift compiler for Parquet build

### PR DESCRIPTION
**Pull request by kou**

### CODE REVIEW

**Comment by kou** [comment]
@github-actions crossbow submit test-debian-10-cpp

**Comment by wesm** [comment]
Oh thank you for taking care of this @kou

**Comment by wesm** [comment]
@github-actions crossbow submit test-debian-10-cpp

**Comment by kou** [comment]
+1
test-debian-10-cpp uses system Thrift without thrift-compiler.

**Pull request closed without merging**
