### PR TITLE
ARROW-1795: [Plasma] Change evict policy

### PR DESCRIPTION
**Pull request by luchy0120**
change size to required_space

### CODE REVIEW

**Comment by pcmoritz** [comment]
Thanks! Can you revert the last commit? We still like to evict at least a certain amount to avoid having lots of small eviction requrests!

**Comment by robertnishihara** [comment]
@luchy0120 Thanks for the fix!

**Comment by luchy0120** [comment]
with pleasure

**Comment by pcmoritz** [comment]
+1 Thanks a lot :)

**Comment by robertnishihara** [comment]
@luchy0120 can you move the last commit to a separate PR? It'd be good to get this one merged with just the bug fix.

**Comment by luchy0120** [comment]
Ok , I'll  fire another pull request . Also , I  found  another situation which we didn't take into account,I'll
 make some change in the code

**Comment by luchy0120** [comment]
Oh , I'm so sorry . I add too much contents in my branch before you merge the old one. Any way , I 
fire a new PR ,  I think that one is better. I explain the code in my Jira ticket.

**Comment by robertnishihara** [comment]
@luchy0120 did you ever have a chance to open a new PR about this? I can do it as well if that's simpler.

**Comment by luchy0120** [comment]
@robertnishihara ,  I've created a new pr #1305 , also I've updated the jira  [arrow-1795](https://issues.apache.org/jira/browse/ARROW-1795) , sorry for the inconvenience

**Comment by luchy0120** [comment]
@robertnishihara , also , if my idea doesn't follow your design , it's simpler for you to fix this

**Comment by robertnishihara** [comment]
Thanks @luchy0120, i started #1317. I think I understand the bug pointed out in https://issues.apache.org/jira/browse/ARROW-1795, and I tried to explain it in #1317. Can you take a look at #1317?

**Comment by luchy0120** [comment]
@robertnishihara ,  I don't have much knowledge about the design and I can't see the whole picture. What I care about is  whether plasma will crash if I put it into production and read/write data 1000 times. I'm trying to bring plasma to our project . So I want to make sure it will not crash . I don't think it is reasonable that if I put data smaller than the initialized amount ,it will throw exception saying out-of-memory. As I don't see any doc talking about eviction or should I evict data myself , sometimes I 
need to check some source code in order to  get some knowledge on my own. I didn't receive feedback
of my issue https://issues.apache.org/jira/projects/ARROW/issues/ARROW-1792  so I search the error and
 try to figure out the reason. I've been working on this for several weeks so emotionally I want plasma to be  more stable and more welcoming.

**Comment by robertnishihara** [comment]
That's a good point. I think a good solution to the out-of-memory error would be to have a mode where plasma only uses one memory mapped file. That should fix the issue.

As for https://issues.apache.org/jira/projects/ARROW/issues/ARROW-1792, I'm hoping to get to that later today.

Thanks for all the work uncovering issues with plasma! This'll definitely help stabilize things much more quickly.

**Pull request closed without merging**
