### PR TITLE
ARROW-7155: [Java][CI] add maven wrapper

### PR DESCRIPTION
**Pull request by wgx731**
My first commit to the project, let me know your feedback and glad to contribute to Apache Arrow.

### CODE REVIEW

**Comment by wgx731** [comment]
Sorry for the confusion, the pull request is for [ARROW-7155](https://issues.apache.org/jira/browse/ARROW-7155). Thanks

**Comment by wgx731** [comment]
I am new to [Apache Rat](https://creadur.apache.org/rat), can someone help me with [this issue](https://github.com/apache/arrow/pull/5819/checks?check_run_id=301145010)?

Thanks

**Comment by emkornfield** [comment]
@wgx731 thank you for the contribution.  Apache RAT checks to make sure all files have the apache license header.  In this case: java/.mvn/wrapper/maven-wrapper.properties does not.  Ideally an Apache header would be added to that file.  If necessary it can be whitelisted.

Is it necessary to checkin the JAR file, I have concerns about doing that.   That issue aside, other things that I think would be necessary before being able to merge this are:
1. An update to documentation for getting started in java and developer documentation (an appropriate link) for how to upgrade these lists.
2. Incorporating this into CI so we can ensure it works properly.

CC @BryanCutler @praveenbingo have you used this before?  Any thoughts on the utility?

**Comment by wgx731** [comment]
> @wgx731 thank you for the contribution. Apache RAT checks to make sure all files have the apache license header. In this case: java/.mvn/wrapper/maven-wrapper.properties does not. Ideally an Apache header would be added to that file. If necessary it can be whitelisted.
> 
> Is it necessary to checkin the JAR file, I have concerns about doing that. That issue aside, other things that I think would be necessary before being able to merge this are:
> 
> 1. An update to documentation for getting started in java and developer documentation (an appropriate link) for how to upgrade these lists.
> 2. Incorporating this into CI so we can ensure it works properly.
> 
> CC @BryanCutler @praveenbingo have you used this before? Any thoughts on the utility?

Hi @emkornfield,

Thanks for the feedback. Please see my answers to your feedback below:

1. For `maven-wrapper.properties` file is used to indicate where to download maven binaries. I think we can whitelisted it, you can refer to example in [apache camel](https://github.com/apache/camel/blob/master/.mvn/wrapper/maven-wrapper.properties).
2. I will help to update and documentation on how to use maven wrapper during weekend.
3. I will help to update CI to use maven wrapper during weekend as well.

Thanks again for the comments, please wait for my update.

Best Regards,
Eric

**Comment by emkornfield** [comment]
Hi @wgx731, can you please address the need to check in a JAR file first.  I have a strong preference against doing this.

**Comment by wgx731** [comment]
> Hi @wgx731, can you please address the need to check in a JAR file first. I have a strong preference against doing this.
> 
> I also, am not sure if we really need this for Arrow. Arrow isn't something we expect users to run out of the box since it only provides a library embedded in other systems.

Hi @emkornfield, for the JAR file, it's the normal practice for build tool with wrapper features, you can find out more below:
https://github.com/apache/camel/tree/master/.mvn/wrapper 
https://docs.gradle.org/current/userguide/gradle_wrapper.html

With that said, I totally agree with you that we need to access the benefit for this. As this is my first attempt therefore I have picked something that I am familiar and easy to start. 

If the community agrees that this is not approach apache arrow wants to go, please help to close the pull request, I will try to find other issues I can help with, and please share some good ideas/issues for me to start as well.

Cheers,
**Eric**

**Comment by emkornfield** [comment]
Hi Eric, 
I appreciate you trying to make Arrow better.  Personally, I would lean against doing this even if other projects are packaging a checked in jar file, but there might be others that are interested in seeing this checked in (I cced a couple on my original comment). But it might pay to send an e-mail to the dev mailing list to see if others are interested in adopting this change.

**Comment by wgx731** [comment]
> Hi Eric,
> I appreciate you trying to make Arrow better. Personally, I would lean against doing this even if other projects are packaging a checked in jar file, but there might be others that are interested in seeing this checked in (I cced a couple on my original comment). But it might pay to send an e-mail to the dev mailing list to see if others are interested in adopting this change.

Hi @emkornfield, thanks for the feedback again. Unfortunately, for the checked in jar file we can't remove it if we want to use maven wrapper. 

Personally, I prefer to use JIRA instead of mailing list, so I will wait for reply in [JIRA ticket](https://issues.apache.org/jira/browse/ARROW-7155). As my laptop is broken during the weekend, I will continue to resolve the other **2 concern** after I got my laptop fix.

Thank you very much.

Best Regards,
**Eric**

**Comment by BryanCutler** [comment]
Thanks for contributing to the project @wgx731. Arrow Java has worked for me with a standard Maven installation. It would help if you could summarize the benefits of what this adds or what problems this solves.

**Comment by wgx731** [comment]
> Thanks for contributing to the project @wgx731. Arrow Java has worked for me with a standard Maven installation. It would help if you could summarize the benefits of what this adds or what problems this solves.

Hi @BryanCutler, 

Sorry for the late reply. I was a bit busy this week. 

I think there are _2 main benefits_ of using maven wrapper based on my experience:
1. Make it really easy for developers who stuck in **Windows environment** can start working on Apache arrow (e.g. Windows **Maven** and **Docker** are not that good)
2. Easy to switch to other maven versions (e.g. maven 4.0 if there is one)

Again, as I have said earlier, the main point from me of this pull request is just to find a starting point for my journey with Apache arrow, I can totally understand if it doesn't add much value. Feel free to close the pull request and ticket if that's case.

By the way, I have tried my best to update the **Dockerfile** and **README** to reflect the changes needed to make use of maven wrapper.

Let me know if any other information is needed.

Thank you very much.

Best Regards,
Eric

**Comment by wgx731** [comment]
> @wgx731 thank you for the contribution. Apache RAT checks to make sure all files have the apache license header. In this case: java/.mvn/wrapper/maven-wrapper.properties does not. Ideally an Apache header would be added to that file. If necessary it can be whitelisted.
> 
> Is it necessary to checkin the JAR file, I have concerns about doing that. That issue aside, other things that I think would be necessary before being able to merge this are:
> 
> 1. An update to documentation for getting started in java and developer documentation (an appropriate link) for how to upgrade these lists.
> 2. Incorporating this into CI so we can ensure it works properly.
> 
> CC @BryanCutler @praveenbingo have you used this before? Any thoughts on the utility?

Hi @emkornfield,

I have done my best for your request on documentation and CI part, thanks.

 Best Regards,
**Eric**

**Comment by jacques-n** [comment]
Per other comments, I think we shouldn't merge this. Closing out.

**Pull request closed without merging**
