### PR TITLE
GH-43878: [Go][Release] Remove Go related codes from our release scripts

### PR DESCRIPTION
**Pull request by raulcd**
### Rationale for this change

The Go implementation is moving to apache/arrow-go from go/ in apache/arrow.

### What changes are included in this PR?

Remove go related release scripts from apache/arrow

### Are these changes tested?

The source verification is tested via archery

### Are there any user-facing changes?

Yes, Go will not be releases as part of Apache Arrow anymore.
* GitHub Issue: #43878

### CODE REVIEW

**Comment by raulcd** [comment]
@zeroshade does this urls will have to point here `https://pkg.go.dev/github.com/apache/arrow-go/go/v18` once we release?
https://github.com/apache/arrow/blob/18319d30e558af72f72ea58c7d7996e781777643/docs/source/index.rst?plain=1#L107

https://github.com/apache/arrow/blob/18319d30e558af72f72ea58c7d7996e781777643/r/_pkgdown.yml#L79
Is there any way to point to latest so we don't have to bump the release on arrow when we release arrow-go?

**Comment by raulcd** [comment]
@github-actions crossbow submit verify-rc-source-*

**Comment by raulcd** [comment]
Ubuntu 20.04 issues are unrelated:
- https://github.com/apache/arrow/issues/44173

**Comment by kou** [comment]
How about creating https://arrow.apache.org/go/ as the canonical Apache Arrow Go website?
We can link to https://pkg.go.dev/github.com/apache/arrow-go/v${LATEST} from the URL.

**Comment by raulcd** [comment]
> How about creating https://arrow.apache.org/go/ as the canonical Apache Arrow Go website?

How can I do this?

**Comment by kou** [comment]
We can use `.asf.yaml`:
* The ADBC case: https://github.com/apache/arrow-adbc/blob/fc51e60087f835810a01775bf303577462c4df04/.asf.yaml#L39-L41
* The Apache Arrow FlightSQL adapter for PostgreSQL case: https://github.com/apache/arrow-flight-sql-postgresql/blob/5d2f0d4994519879c33e3c791d4ee562264397f8/.asf.yaml#L38-L40

With the `publish:` configuration in apache/arrow-go's `.asf.yaml`, we can deploy the asf-site branch content to https://arrow.apache.org/go/ .

**Comment by kou** [comment]
https://github.com/apache/arrow-go/issues/139

**Comment by raulcd** [comment]
@kou are you ok for me merging this? The docs, once deployed with the release, will point to `https://arrow.apache.org/go/ ` but this can be merged as is so we can unblock removing the go code from this repo.

**Comment by kou** [comment]
Yes!

**Review by raulcd — COMMENTED** [review]
:+1:

**Pull request merged**
