### PR TITLE
ARROW-3631: [C#] Add Appveyor configuration

### PR DESCRIPTION
**Pull request by wesm**

### CODE REVIEW

**Comment by wesm** [comment]
cc @chutchinson for review

**Review by eerhardt — APPROVED** [review]
Looks good to me! Thanks for doing this, @wesm.

**Comment by chutchinson** [comment]
@wesm Looks good.

**Comment by wesm** [comment]
Successful appveyor build on my fork: https://ci.appveyor.com/project/wesm/arrow/builds/22287780

**Comment by eerhardt** [comment]
If you don’t specify a TFM, it runs against all the TFMs in the csproj. We only have 1, so I think we are fine here.

**Comment by eerhardt** [comment]
@wesm - I see this didn't fully fix the issue. The C# tests are not running in CI because the filtering logic needs to be updated.

For example see https://ci.appveyor.com/project/ApacheSoftwareFoundation/arrow/builds/22671460/job/nk1nn59k5njie720

```
Build started
git clone -q https://github.com/apache/arrow.git C:\projects\arrow
git fetch -q origin +refs/pull/3662/merge:
git checkout -qf FETCH_HEAD
Running Install scripts
python ci\detect-changes.py > generated_changes.bat
Affected files: [u'csharp/src/Apache.Arrow/Field.Builder.cs', u'csharp/src/Apache.Arrow/Schema.Builder.cs', u'csharp/test/Apache.Arrow.Tests/SchemaBuilderTests.cs', u'csharp/test/Apache.Arrow.Tests/TypeTests.cs']
Affected topics:
{'c_glib': False,
 'cpp': False,
 'dev': False,
 'docs': False,
 'go': False,
 'integration': False,
 'java': False,
 'js': False,
 'python': False,
 'r': False,
 'ruby': False,
 'rust': False,
 'site': False}
call generated_changes.bat
call ci\appveyor-filter-changes.bat
===
=== No C++ or Python changes, exiting job
===
Build was forcibly terminated
Build success
```

I can fix up the filtering logic. But my quetion is: what is the process here? Do I re-open the ARROW-3631 JIRA to do the work? Or do I log a new JIRA?

**Pull request closed without merging**
