### PR TITLE
ARROW-5187: [Rust] Add ability to convert StructArray to RecordBatch

### PR DESCRIPTION
**Pull request by nevi-me**
The CPP version (http://arrow.apache.org/docs/python/generated/pyarrow.StructArray.html?highlight=flatten#pyarrow.StructArray.flatten) returns `Vec<ArrayRef>`, so not sure if we should also do the same.
My justification for returning a `RecordBatch` is that we have the added convenience of not losing the schema of the columns.
I'm using this for reading rows from a SQL database into Arrow data.

### CODE REVIEW

**Comment by kszucs** [comment]
It might be better to call the cpp version as `unnest` instead of flatten. This implementation does a conversion to `RecordBatch` thus I'd consider to implement a conversion trait instead. What do You think @nevi-me?

**Comment by nevi-me** [comment]
I didn't give it much thought, I like the conversion trait more. I'll update this

**Review by kszucs — APPROVED** [review]
It was quick, thanks @nevi-me!

**Comment by nevi-me** [comment]
@kszucs I used `unreachable!()` because I couldn't find a way of extracting the fields from the `StructArray`. I also noted that our implementation's light on helpful methods (e.g. I might want to get a list of all the arrays without iterating).
I'll add JIRAs to address those

**Comment by kszucs** [comment]
Ok, sounds good! Mering on green.

**Pull request closed without merging**
