### PR TITLE
MINOR: Testing new M1 runners configuration

### PR DESCRIPTION
**Pull request by raulcd**
This PR is not intended to be merged I am just adding this to validate the configuration of the new M1 runners added for the nightly builds.

### CODE REVIEW

**Comment by raulcd** [comment]
@github-actions crossbow submit verify-rc-source*macos-arm64

**Comment by amaldonadomat** [comment]
@github-actions crossbow submit verify-rc-source*macos-arm64

**Comment by raulcd** [comment]
@github-actions crossbow submit verify-rc-source*macos-arm64

**Comment by raulcd** [comment]
@github-actions crossbow submit verify-rc-source*macos-arm64

**Comment by raulcd** [comment]
@github-actions crossbow submit verify-rc-source*macos-arm64

**Comment by raulcd** [comment]
@github-actions crossbow submit verify-rc-source*macos-arm64

**Comment by raulcd** [comment]
@github-actions crossbow submit verify-rc-source*macos-arm64

**Comment by raulcd** [comment]
@github-actions crossbow submit verify-rc-source*macos-arm64

**Comment by raulcd** [comment]
@github-actions crossbow submit verify-rc-source*macos-arm64

**Comment by raulcd** [comment]
@github-actions crossbow submit verify-rc-source*macos-arm64

**Comment by raulcd** [comment]
The M1 jobs are successful again after adding 2 more self hosted MAC M1s. Closing this PR as it was only for testing.
We have 3 self hosted M1s now.

**Pull request closed without merging**
