### PR TITLE
ARROW-927: C++/Python: Add manylinux1 builds to Travis matrix

### PR DESCRIPTION
**Pull request by xhochy**
Also pre-builds flatbuffers and gtest so that they are only build once.

### CODE REVIEW

**Comment by wesm** [comment]
The manylinux1 build took 32 minutes, almost 20 minutes more than the next slowest build -- I'm concerned this is going to affect developer productivity. What do you think about setting up a separate repo (and give committers push/admin on it) and periodically updating the build to run in CircleCI? I know that the point of this is to not break the packaging build, but this would help others be proactive about checking that things still work properly.

**Comment by xhochy** [comment]
The base problem here that we spent all time building dependencies like boost, openssl and flatbuffers. I'm going to set up a separate build that will package the thirdparties into a docker image that we then can pull in Travis.

**Comment by wesm** [comment]
The build time is better, but still not great. The OS X build varies in time from 13-25 minutes based on the time of day; one benefit of the build is that it's Linux only so generally starts up right away. 

build_times

I think the way to make things faster would be to also include the rest of parquet-cpp's thirdparty toolchain (especially Thrift) in the Docker image. What do you think? Doesn't have to get done in this patch

**Comment by xhochy** [comment]
I'll include Thrift & co in the docker imager but first I need to adjust it so that the size of the image itself is a lot smaller, currently pulling the image takes a long time.

**Review by wesm — APPROVED** [review]
+1

**Pull request closed without merging**
