### PR TITLE
ARROW-11154: [CI][C++] Move homebrew crossbow tests off of Travis-CI

### PR DESCRIPTION
**Pull request by nealrichardson**

### CODE REVIEW

**Comment by nealrichardson** [comment]
@github-actions crossbow submit homebrew-r-autobrew

**Comment by nealrichardson** [comment]
@github-actions crossbow submit homebrew-r-autobrew

**Comment by nealrichardson** [comment]
@github-actions crossbow submit homebrew-r-autobrew

**Comment by nealrichardson** [comment]
@github-actions crossbow submit homebrew-cpp

**Comment by nealrichardson** [comment]
@github-actions crossbow submit homebrew-cpp

**Review by kou — APPROVED** [review]
+1

Thanks!

**Pull request closed without merging**
