### PR TITLE
MINOR: [Rust][Docs] Update Rust FlightSQL status doc

### PR DESCRIPTION
**Pull request by Jefffrey**
### Rationale for this change

Updating arrow-rs FlightSQL support status on site: https://arrow.apache.org/docs/status.html#flight-sql

arrow-rs issue: https://github.com/apache/arrow-rs/issues/4337

### CODE REVIEW

**Comment by Jefffrey** [comment]
cc @tustvold @alamb 

Based this off what I could find in https://github.com/apache/arrow-rs/blob/bd19a624469df652f24ee37b65056535ff665769/arrow-flight/src/client.rs

Let me know if I missed anything or if it's inaccurate

**Review by alamb — APPROVED** [review]
Thank you @Jefffrey  -- the other thing I have been thinking about recently is that maybe it is time to remove the "experimental" name from the flightsql feature in the arrow crate 🤔

**Comment by Jefffrey** [comment]
To be fair, the arrow doc does state that FlightSQL is still experimental:

https://arrow.apache.org/docs/format/FlightSql.html

So it would make sense that the feature in arrow-rs crate is also named experimental, I suppose?

**Comment by alamb** [comment]
> To be fair, the arrow doc does state that FlightSQL is still experimental:
> 
> https://arrow.apache.org/docs/format/FlightSql.html
> 
> So it would make sense that the feature in arrow-rs crate is also named experimental, I suppose?

Yes, that makes sense

There was a discussion on the mailing list a while back about marking FlightSQL as non experimental https://lists.apache.org/thread/qoshg8mln3t2ovr90o1yklz4yrpv503h but it seems like we haven't actually done that yet 

:)

**Comment by alamb** [comment]
Thanks @Jefffrey

**Pull request merged**
