### PR TITLE
ARROW-9916: [RUST] Avoid cloning array data

### PR DESCRIPTION
**Pull request by jhorstmann**
Extracted from #8092 for easier review

### CODE REVIEW

**Comment by jorgecarleitao** [comment]
Great work and nice approach of going through the flamegraph. LGTM.

As a note, I ran DataFusion's benchmarks of this against master:

```
aggregate_query_no_group_by                                                                            
                        time:   [80.374 us 80.801 us 81.205 us]
                        change: [-2.8204% -0.7165% +1.3842%] (p = 0.56 > 0.05)
                        No change in performance detected.
Found 5 outliers among 100 measurements (5.00%)
  1 (1.00%) high mild
  4 (4.00%) high severe

aggregate_query_group_by                                                                            
                        time:   [128.83 us 129.32 us 129.87 us]
                        change: [-5.1220% -3.0698% -1.0298%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 10 outliers among 100 measurements (10.00%)
  5 (5.00%) high mild
  5 (5.00%) high severe

aggregate_query_group_by_with_filter                                                                            
                        time:   [204.17 us 204.46 us 204.77 us]
                        change: [-4.8251% -2.6720% -0.4294%] (p = 0.01 < 0.05)
                        Change within noise threshold.
Found 20 outliers among 100 measurements (20.00%)
  9 (9.00%) high mild
  11 (11.00%) high severe
```

If you think that there is a query that particularly benefits from this, feel free to add it to the `arrow` cargo bench

**Comment by jhorstmann** [comment]
I saw the biggest effect when doing lexicographic sorting and added some benchmarks for sorting. On my laptop the run to run variation was much to high, but on an ec2 m5a.xlarge the improvement is up to 20%:

```
     Running /home/ubuntu/arrow/rust/target/release/deps/sort_limit_query_sql-934168e24deec398
Gnuplot not found, using plotters backend
sort_and_limit_by_int   time:   [123.66 us 123.75 us 123.85 us]                                  
                        change: [-18.110% -17.989% -17.840%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 4 outliers among 100 measurements (4.00%)
  1 (1.00%) low mild
  2 (2.00%) high mild
  1 (1.00%) high severe

sort_and_limit_by_float time:   [115.25 us 115.37 us 115.50 us]                                    
                        change: [-15.139% -14.976% -14.812%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 5 outliers among 100 measurements (5.00%)
  4 (4.00%) high mild
  1 (1.00%) high severe

sort_and_limit_lex_by_int                                                                            
                        time:   [134.29 us 134.39 us 134.49 us]
                        change: [-21.700% -21.591% -21.485%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 4 outliers among 100 measurements (4.00%)
  1 (1.00%) low mild
  1 (1.00%) high mild
  2 (2.00%) high severe

sort_and_limit_lex_by_string                                                                            
                        time:   [133.06 us 133.15 us 133.24 us]
                        change: [-21.846% -21.728% -21.610%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 5 outliers among 100 measurements (5.00%)
  1 (1.00%) low mild
  3 (3.00%) high mild
  1 (1.00%) high severe
```

**Review by jorgecarleitao — APPROVED** [review]

**Review by alamb — APPROVED** [review]
I also think this code looks like an improvement;

Initially I was surprised that `clone`ing an `Arc` is all that expensive. However, I am able to reproduce the improved benchmark results on my laptop (details below) and clearly there were many calls to `Arc::clone` occuring! Nice work @jhorstmann 



<details>
  <summary>Click to see my benchmark results</summary>


```
alamb@ip-192-168-1-129 rust % ARROW_TEST_DATA=`pwd`/../testing/data cargo bench --bench sort_limit_query_sql
</testing/data cargo bench --bench sort_limit_query_sql
   Compiling arrow v2.0.0-SNAPSHOT (/Users/alamb/Software/arrow/rust/arrow)
   Compiling parquet v2.0.0-SNAPSHOT (/Users/alamb/Software/arrow/rust/parquet)
   Compiling arrow-flight v2.0.0-SNAPSHOT (/Users/alamb/Software/arrow/rust/arrow-flight)
   Compiling datafusion v2.0.0-SNAPSHOT (/Users/alamb/Software/arrow/rust/datafusion)
    Finished bench [optimized] target(s) in 27.87s
     Running target/release/deps/sort_limit_query_sql-0a0647a8d51ac719
Gnuplot not found, using plotters backend
sort_and_limit_by_int   time:   [151.72 us 154.61 us 157.83 us]
                        change: [-21.643% -19.276% -17.011%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 15 outliers among 100 measurements (15.00%)
  8 (8.00%) high mild
  7 (7.00%) high severe

sort_and_limit_by_float time:   [133.00 us 134.00 us 135.07 us]
                        change: [-18.032% -16.063% -14.210%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 5 outliers among 100 measurements (5.00%)
  3 (3.00%) high mild
  2 (2.00%) high severe

sort_and_limit_lex_by_int
                        time:   [160.47 us 162.85 us 165.41 us]
                        change: [-19.361% -17.641% -15.840%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 9 outliers among 100 measurements (9.00%)
  8 (8.00%) high mild
  1 (1.00%) high severe

sort_and_limit_lex_by_string
                        time:   [154.76 us 155.91 us 157.30 us]
                        change: [-14.978% -13.075% -10.876%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 13 outliers among 100 measurements (13.00%)
  6 (6.00%) high mild
  7 (7.00%) high severe

```
</details>

**Review by andygrove — APPROVED** [review]
Fantastic!

**Pull request closed without merging**
