### PR TITLE
ARROW-1324: [C++] Add support for bundled Boost with MSVC

### PR DESCRIPTION
**Pull request by kou**

### CODE REVIEW

**Comment by wesm** [comment]
This is ARROW-1324?

**Comment by kou** [comment]
Oh, I didn't notice ARROW-1324. Thanks.

**Comment by kou** [comment]
Build test by GitHub Actions CI is green: https://github.com/kou/arrow/commit/33cf5339a7b822589070097af8fb75ac0e59fb02/checks

**Comment by pitrou** [comment]
Does it work in debug mode as well?

Also, where does the Github Actions job execute? Does Github provide Windows builders?

**Review by wesm — APPROVED** [review]
+1

**Comment by wesm** [comment]
I assume that Github Actions is a wrapper around Azure Devops, so it will gain any capabilities that that system has

**Comment by kou** [comment]
> Does it work in debug mode as well?

In this test, we just use "Debug" mode: https://github.com/apache/arrow/pull/5337/files#diff-e403caafa9fe7ef57c326a49e49baef4R52

```bat
           cmake --build build\cpp --config Debug --target Install
```

But I confirmed that this change works with "Release" mode on local machine.

> Also, where does the Github Actions job execute? Does Github provide Windows builders?

GitHub provides Windows builders: https://help.github.com/en/articles/about-github-actions#virtual-environment

> GitHub hosts Linux, macOS, and Windows virtual environments to run your workflows.

**Pull request closed without merging**
