### PR TITLE
ARROW-7320: [C++] Specify CMAKE_INSTALL_LIBDIR for gbenchmark

### PR DESCRIPTION
**Pull request by MaChengxin**
This is to fix the build error on bullx Linux.

### CODE REVIEW

**Comment by MaChengxin** [comment]
Note: I tested this solution on ``maint-0.15.x`` and ``master``.
On ``maint-0.15.x`` there would be a successful build after the fix, while on ``master`` it has another unrelated build error after ``arrow-type-benchmark`` was built.

**Comment by MaChengxin** [comment]
I did a ``python3 run-cmake-format.py`` in an attempt to let the unsuccessful check pass.
However it turned out it was not only my change that didn't satisfy the formatter. 51 files relating to CMake has to be updated.
So, is this check failure acceptable?

**Comment by pitrou** [comment]
@MaChengxin You need to install cmake-format 0.5.2.

**Comment by pitrou** [comment]
cc @kou

**Review by kou — APPROVED** [review]
+1
We can merge this once CI is green.

**Comment by pitrou** [comment]
Thank you @MaChengxin !

**Pull request closed without merging**
