### PR TITLE
ARROW-5439: [Java] [WIP] Write EOS identifier for sequential readers

### PR DESCRIPTION
**Pull request by jgm-ktg**

### CODE REVIEW

**Comment by jgm-ktg** [comment]
Will add test case when I can

**Comment by emkornfield** [comment]
@jgm-ktg normally we like to see unit tests at the same time that we merge code, when do you think you will be able to add one?  Maybe label the PR as WIP or close it until you can add one?

**Comment by jgm-ktg** [comment]
> @jgm-ktg normally we like to see unit tests at the same time that we merge code, when do you think you will be able to add one? Maybe label the PR as WIP or close it until you can add one?

@emkornfield I have to grab a few minutes here and there for contributions since I have to focus mostly on my other work.  For this reason I thought I would stage a PR even though I know it isn't done... this way if I never come back, or it takes some time, any onlooker has the opportunity to run with it if they so choose.

If you and other major contributors think it is better not to have the pending work public in a PR until I know I can finish it, I will adjust.  I marked it WIP for now.  I suppose another option is that I could put the proposed code in JIRA until I'm "really done" ?

**Comment by emkornfield** [comment]
Closing in favor of: https://github.com/apache/arrow/pull/4966

**Pull request closed without merging**
