### PR TITLE
[WIP] Restore simpler ARROW_R_WITH_ARROW wrapping

### PR DESCRIPTION
**Pull request by nealrichardson**
Without the ARROW_R_WITH_ARROW wrapping around the code in arrowExports.cpp, if Arrow C++ is not available, the build fails--as expected. However, it does so with on the order of 10,000 lines of compiler errors because all 400 function definitions in that file fail to compile.

For 4.0, given that CRAN is running Solaris checks again, we need to not fail anymore. We could just restore the previous wrapping of every function, but I wanted to try something lighter weight. 

Going forward, once we decide that ARROW_R_WITH_ARROW must always be true, we should fail earlier and clearer, maybe in `configure` if possible, so that the user's terminal doesn't blow up and so they can see what the actual problem is.

### CODE REVIEW

**Comment by jonkeane** [comment]
I've taken a look at this and I think this is an overall better (temporary?) solution than wrapping each function call. Absolutely agree that an earlier + clearer error will be good when we can do that. 

I haven't yet run this locally (yet), but I wanted to confirm my reading of the test suite is correct: All of the operative tests will be skipped on CRAN (when/if the C++ library is unavailable) because of [our wrapping of `test_that`](https://github.com/apache/arrow/blob/master/r/tests/testthat/helper-arrow.R#L58-L63) and [setting `..skip.tests` when arrow isn't available](https://github.com/apache/arrow/blob/master/r/tests/testthat/helper-arrow.R#L19) (tangentially: could we move up our `test_that` wrapper so they are closer, or do we need the `test_that` wrapping lower down for some other reason?).

Overall, I think it's good to reduce the code duplication (which makes searching for strings harder) and to me has a slightly easier to see that everything in the arrowExports.cpp will be not included if that one variable is set (compared to now where it might look like we are selectively turning on or off functions as opposed to turning each one of individually).

**Comment by nealrichardson** [comment]
@ianmcook do you have an opinion on this?

**Comment by ianmcook** [comment]
> @ianmcook do you have an opinion on this?

Just on the basis of how much code was removed by ARROW-10735 versus how little code is added here, this seems sensible, but I haven't dug into this enough to have a well-informed opinion

**Comment by nealrichardson** [comment]
Ok. Then I'll merge this, rebase #9896, and doublecheck that the experience is what we want and tweak anything else there.

**Comment by nealrichardson** [comment]
nevermind, I decided to cherry-pick this into #9896. Closing.

**Pull request closed without merging**
