### PR TITLE
GH-35177: [Docs][Python] Suppress "WARNING: autosummary: failed to import serialize"

### LINKED ISSUE #35177: [Docs][Python] WARNING: autosummary: failed to import serialize
### Describe the bug, including details regarding any error messages, version, and platform.

https://github.com/apache/arrow/actions/runs/4697870159/jobs/8329453509#step:6:12728

```text
/arrow/docs/source/python/api/ipc.rst:60: WARNING: autosummary: failed to import serialize.
Possible hints:
* KeyError: 'serialize'
* ModuleNotFoundError: No module named 'serialize'
* ModuleNotFoundError: No module named 'pyarrow.serialize'
* AttributeError: module 'pyarrow' has no attribute 'serialize'
* ValueError: not enough values to unpack (expected 2, got 1)
/arrow/docs/source/python/api/ipc.rst:60: WARNING: autosummary: failed to import serialize_to.
Possible hints:
* AttributeError: module 'pyarrow' has no attribute 'serialize_to'
* ModuleNotFoundError: No module named 'pyarrow.serialize_to'
* KeyError: 'serialize_to'
* ValueError: not enough values to unpack (expected 2, got 1)
* ModuleNotFoundError: No module named 'serialize_to'
/arrow/docs/source/python/api/ipc.rst:60: WARNING: autosummary: failed to import deserialize.
Possible hints:
* ModuleNotFoundError: No module named 'pyarrow.deserialize'
* ModuleNotFoundError: No module named 'deserialize'
* AttributeError: module 'pyarrow' has no attribute 'deserialize'
* KeyError: 'deserialize'
* ValueError: not enough values to unpack (expected 2, got 1)
/arrow/docs/source/python/api/ipc.rst:60: WARNING: autosummary: failed to import deserialize_components.
Possible hints:
* KeyError: 'deserialize_components'
* AttributeError: module 'pyarrow' has no attribute 'deserialize_components'
* ValueError: not enough values to unpack (expected 2, got 1)
* ModuleNotFoundError: No module named 'deserialize_components'
* ModuleNotFoundError: No module named 'pyarrow.deserialize_components'
/arrow/docs/source/python/api/ipc.rst:60: WARNING: autosummary: failed to import deserialize_from.
Possible hints:
* ModuleNotFoundError: No module named 'deserialize_from'
* KeyError: 'deserialize_from'
* ModuleNotFoundError: No module named 'pyarrow.deserialize_from'
* ValueError: not enough values to unpack (expected 2, got 1)
* AttributeError: module 'pyarrow' has no attribute 'deserialize_from'
/arrow/docs/source/python/api/ipc.rst:60: WARNING: autosummary: failed to import read_serialized.
Possible hints:
* AttributeError: module 'pyarrow' has no attribute 'read_serialized'
* ModuleNotFoundError: No module named 'pyarrow.read_serialized'
* KeyError: 'read_serialized'
* ModuleNotFoundError: No module named 'read_serialized'
* ValueError: not enough values to unpack (expected 2, got 1)
/arrow/docs/source/python/api/ipc.rst:60: WARNING: autosummary: failed to import SerializedPyObject.
Possible hints:
* ModuleNotFoundError: No module named 'SerializedPyObject'
* KeyError: 'SerializedPyObject'
* ModuleNotFoundError: No module named 'pyarrow.SerializedPyObject'
* ValueError: not enough values to unpack (expected 2, got 1)
* AttributeError: module 'pyarrow' has no attribute 'SerializedPyObject'
/arrow/docs/source/python/api/ipc.rst:60: WARNING: autosummary: failed to import SerializationContext.
Possible hints:
* ModuleNotFoundError: No module named 'pyarrow.SerializationContext'
* KeyError: 'SerializationContext'
* ModuleNotFoundError: No module named 'SerializationContext'
* AttributeError: module 'pyarrow' has no attribute 'SerializationContext'
* ValueError: not enough values to unpack (expected 2, got 1)
```

### Component(s)

Documentation, Python

### PR DESCRIPTION
**Pull request by AlenkaF**
* Closes: #35177

### CODE REVIEW

**Comment by AlenkaF** [comment]
@kou the docs build is without warnings now: https://github.com/apache/arrow/actions/runs/4720245538/jobs/8372049452?pr=35182

**Comment by raulcd** [comment]
@github-actions crossbow submit test-ubuntu-default-docs

**Comment by raulcd** [comment]
Sorry for triggering that job, I just created an [issue](https://github.com/apache/arrow/issues/35192) because I thought it was not happening on main but on the 12.0.0 release but it seems to happen on main too. The issue is unrelated to this PR.

**Review by kou — APPROVED** [review]
+1

Yes. The `logo` failure is unrelated.

**Pull request merged**
