### PR TITLE
GH-34037: [Python][Docs] Fix Table.drop docstring

### LINKED ISSUE #34037: [Python][Docs] Fix docstring violations for Table.drop
### Describe the bug, including details regarding any error messages, version, and platform.

I saw this in when updating some docstrings:
```
pyarrow.lib.Table.drop
-> pyarrow.lib.Table.drop(self, columns)
PR01: Parameters {'columns'} not documented

pyarrow.lib.Table.drop
-> pyarrow.lib.Table.drop(self, columns)
PR01: Parameters {'columns'} not documented

pyarrow.lib.Table.drop
-> pyarrow.lib.Table.drop(self, columns)
PR01: Parameters {'columns'} not documented

Total number of docstring violations: 3
```

I think we should deprecate `drop` in favor of `drop_columns`.

### Component(s)

Python

### PR DESCRIPTION
**Pull request by Fokko**
It throws errors in the CI, while I was working on other docstrings:

```
pyarrow.lib.Table.drop
-> pyarrow.lib.Table.drop(self, columns)
PR01: Parameters {'columns'} not documented

pyarrow.lib.Table.drop
-> pyarrow.lib.Table.drop(self, columns)
PR01: Parameters {'columns'} not documented

pyarrow.lib.Table.drop
-> pyarrow.lib.Table.drop(self, columns)
PR01: Parameters {'columns'} not documented

Total number of docstring violations: 3
```

### Are there any user-facing changes?

* Closes: #34037

### CODE REVIEW

**Comment by Fokko** [comment]
cc @jorisvandenbossche @westonpace this fixes the CI on master 👍🏻

**Comment by kou** [comment]
@github-actions crossbow submit test-ubuntu-default-docs

**Comment by westonpace** [comment]
The `test-ubuntu-default-docs` job was missing substrait but that was fixed two days ago.  Maybe rebase this?

As for the fix, was the intention to deprecate `pyarrow.Table.drop`?  It isn't clear to me from the original ticket though it would make sense.  CC @danepitkin @amol-

**Comment by Fokko** [comment]
@westonpace Thanks, I've just rebased the PR.

I got the impression that it was to be deprecated according to the original docstring. My personal opinion is that having duplicate methods will confuse users, and there should be a single way of dropping columns. Calling `.drop` on a table implies to me that it will drop the whole table. Therefore I figured it made sense to deprecate it for now.

**Comment by westonpace** [comment]
@github-actions crossbow submit test-ubuntu-default-docs

**Comment by mapleFU** [comment]
(So, can this patch be merged? Seems some of my patch is blocked by pydoc...)

**Comment by wgtmac** [comment]
> (So, can this patch be merged? Seems some of my patch is blocked by pydoc...)

Same here: https://github.com/apache/arrow/actions/runs/4110851940/jobs/7094056424

**Review by jorisvandenbossche — APPROVED** [review]
@Fokko Thanks for the PR!

I am personally fine with also actually deprecating the method (instead of keeping it as an alias), but I removed that here from this PR to just focus on fixing the docstring validation so that this can be merged quickly (on the deprecation I had some minor comments).

**Comment by Fokko** [comment]
> I am personally fine with also actually deprecating the method (instead of keeping it as an alias), but I removed that here from this PR to just focus on fixing the docstring validation so that this can be merged quickly (on the deprecation I had some minor comments).

No problem at all, feel free to change such a PR any time to get it in. Getting the CI green is the most important part 🚀

**Pull request merged**
