### PR TITLE
ARROW-11510 : [Python] Add note that pip >= 19.0 is required to get binary packages

### PR DESCRIPTION
**Pull request by westonpace**
Added warning to Python install documentation mentioning required pip version

### CODE REVIEW

**Comment by westonpace** [comment]
screenshot

**Comment by westonpace** [comment]
@jorisvandenbossche mind a quick review?

**Review by jorisvandenbossche — APPROVED** [review]
Looks good, thanks!

**Comment by westonpace** [comment]
@jorisvandenbossche sorry to bother but if it looks good can you merge this in? I don't have permission.

**Comment by jorisvandenbossche** [comment]
Thanks!

**Pull request closed without merging**
