### PR TITLE
ARROW-4423: [C++] Upgrade vendored gmock/gtest to 1.8.1

### PR DESCRIPTION
**Pull request by emkornfield**
This change seems to indicate an alternative would be to force the build to be Release type (and avoid the naming magic).  It doesn't appear that the conda feedstock (https://github.com/conda-forge/gtest-feedstock/blob/master/recipe/build.sh) builds debug for linux at all.  it does for windows though:
(https://github.com/conda-forge/gtest-feedstock/blob/master/recipe/bld.bat) I'm not sure if we care a lot about this?

### CODE REVIEW

**Comment by xhochy** [comment]
Rebased.

**Comment by wesm** [comment]
I can try to look at the Windows build later if you can't figure it out. BTW you can get free Windows 10 ISO from Microsoft so setting up a windows dev environment isn't as hard as you might think

**Comment by emkornfield** [comment]
Thanks.  I think I should be able to handle everything.  My first step is
to figure out Trusty errors (I also have a Windows VM) setup so I can look
at that as well it might just take a little while.

**Review by xhochy — APPROVED** [review]
+1, LGTM

Leaving merging to @wesm as he reported problems with `gtest` recently (that have hopefully been resolved).

**Review by wesm — APPROVED** [review]
+1. I'll rebase my ARROW-47 patch on this

**Pull request closed without merging**
