### PR TITLE
[CI] Temporary fix for conda-forge migration

### PR DESCRIPTION
**Pull request by kszucs**
Conda-forge's recent migration caused various error on our CI https://travis-ci.org/apache/arrow/builds/479973875
This is just a temporary solution for the release.

### CODE REVIEW

**Comment by kszucs** [comment]
@pitrou seems like the builds are going to pass, I had to disable pickle5 though. Could You please review?

**Comment by pitrou** [comment]
Is it possible to know why the pickle5 install failed?

**Comment by kszucs** [comment]
Here is the log: https://travis-ci.org/apache/arrow/jobs/479999980#L8068

**Comment by pitrou** [comment]
I saw that. Do you know if it's possible to get the full build log? Perhaps by passing `-vvv` or something?

**Comment by kszucs** [comment]
@pitrou see https://travis-ci.org/apache/arrow/jobs/480034658#L8083

**Comment by pitrou** [comment]
@kszucs Thanks! I will try to push a fix.

**Comment by kszucs** [comment]
Meanwhile can We move forward with the release?
I'd cut RC3.

**Comment by pitrou** [comment]
Sounds good to me.

**Comment by pitrou** [comment]
@kszucs I've released a new pickle5 version which should fix the issue. Is it possible to try again?

**Comment by kszucs** [comment]
sure, I restart the build

**Comment by kszucs** [comment]
https://travis-ci.org/apache/arrow/jobs/480034658

**Comment by pitrou** [comment]
Looks like it's working fine. Thanks for your patience with this :-)

**Comment by kszucs** [comment]
+1

**Pull request merged**
