### PR TITLE
ARROW-6103: [Release][Java] Remove mvn release plugin 

### PR DESCRIPTION
**Pull request by andygrove**
We want to stop using the maven release plugin because it commits to the repo both in the `prepare` and `perform` tasks and adds complexity to the release process.

This PR removes the plugin and updates the release preparation script to use the maven versions plugin to update the version number in the pom files.

We will need to run `mvn deploy` to publish the artifacts and I'm not sure where that needs to happen (`mvn release:perform` was previously invoking the `deploy` phase).

### CODE REVIEW

**Comment by andygrove** [comment]
@kszucs @nealrichardson @kou I think this is basically what we need to do. I am not set up to test the release process locally so it would be good if I could pair with someone else on these changes.

**Comment by kou** [comment]
Sorry for my late response.

We have a post manual(!) task that publishes Java packages to the Maven Central Repository: https://cwiki.apache.org/confluence/display/ARROW/Release+Management+Guide#ReleaseManagementGuide-UpdatingJavaMavenartifactsinMavencentral
Can we do it by `mvn deploy` with source archive?

**Comment by andygrove** [comment]
> 
> 
> Sorry for my late response.
> 
> We have a post manual(!) task that publishes Java packages to the Maven Central Repository: https://cwiki.apache.org/confluence/display/ARROW/Release+Management+Guide#ReleaseManagementGuide-UpdatingJavaMavenartifactsinMavencentral
> Can we do it by `mvn deploy` with source archive?

Yes, that is my assumption.

**Comment by kou** [comment]
Great!

Can we only build Java packages(*) without publishing to the Maven Central Repository for testing? For example, our nightly Gandiva for Java builds[1] just build `*.jar` without publishing to the Maven Central Repository. The built `*.jar` are uploaded to GitHub releases[2] by Crossbow. We can use the uploaded `*.jar` to test Gandiva for Java packages.

(*) I'm sorry but I don't know much about Java packages. Is `*.jar` a Java package in the Maven Central Repository? Or we need to build something else?

[1]: https://github.com/apache/arrow/tree/master/dev/tasks/gandiva-jars
[2]: https://github.com/ursacomputing/crossbow/releases/tag/nightly-2021-01-20-0-github-gandiva-jar-ubuntu

**Comment by andygrove** [comment]
@kou Sorry, I didn't see your questions until now. Yes, we can build the Java artifacts without pushing them. Let me explain more about the Maven release process though.

Java binaries are typically just the JAR files, but when we publish to a Maven repository we also need to publish Maven artifacts, which are XML files containing metadata about the JAR files.

Most projects use `mvn package` to build JAR files. You can also install Maven artifacts to the local Maven repo (`~/.m2/repository`) with `mvn install` so that they can be discovered by other Maven projects built locally.

We will want to run `mvn publish` to do the actual release to Sonatype or wherever. We can just run this from the source release though (note that this is different to running `mvn release` which would tag the repo and then call `mvn publish` ).

cc @nealrichardson

**Comment by nealrichardson** [comment]
Ping @andygrove @kou, we're coming up on release time again, are we going to get this done/merged?

**Comment by kou** [comment]
@kszucs I think that the following related tasks are remained to release with this change:

* Remove the `apache-arrow-${version}` tag dependency from `dev/release/02-source.sh`. (Should we use `apache-arrow-${version}-rc${N}` instead?)
* Add `dev/release/post-XX-tag.sh` that create and push `apache-arrow-${version}` tag.
* Add `dev/release/post-XX-version.sh` that bumps version to `5.0.0-SNAPSHOT`.
* Add `dev/release/post-XX-java.sh` that releases Java packages by `mvn deploy`.  (Do we still need https://cwiki.apache.org/confluence/display/ARROW/Release+Management+Guide#ReleaseManagementGuide-UpdatingJavaMavenartifactsinMavencentral manual step with `mvn deploy`?)
* (Not related) Remove `dev/release/post-00-rebase.sh`

Can we work on them as follow-up tasks? Or should we do them in this pull request?

**Comment by kszucs** [comment]
> @kszucs I think that the following related tasks are remained to release with this change:
> 
> * Remove the `apache-arrow-${version}` tag dependency from `dev/release/02-source.sh`. (Should we use `apache-arrow-${version}-rc${N}` instead?)
> * Add `dev/release/post-XX-tag.sh` that create and push `apache-arrow-${version}` tag.
> * Add `dev/release/post-XX-version.sh` that bumps version to `5.0.0-SNAPSHOT`.
> * Add `dev/release/post-XX-java.sh` that releases Java packages by `mvn deploy`.  (Do we still need https://cwiki.apache.org/confluence/display/ARROW/Release+Management+Guide#ReleaseManagementGuide-UpdatingJavaMavenartifactsinMavencentral manual step with `mvn deploy`?)
I guess so. Could we test mvn deploy before actually going to production?
> * (Not related) Remove `dev/release/post-00-rebase.sh`
> 
> Can we work on them as follow-up tasks? Or should we do them in this pull request?

Do you mean that we should incorporate these changes to this PR?

**Comment by kou** [comment]
If we can complete all related works before we start 4.0.0 release process, we can choose either approach (multiple pull requests and only this pull request).
But if we can't complete, we should complete all related works in one pull request. If we work on this by multiple pull requests, this work blocks 4.0.0 release.
We can choose either approach after we release 4.0.0.

**Comment by andygrove** [comment]
@kou @kszucs Let me know if/how I can help with this work

**Comment by kszucs** [comment]
Thanks Andy! Going to ask my questions in a separate comment.

I updated the preparation script to automatically create the necessary branches and tag the release. 
After the following commands: 

```console
$ git checkout release-4.0.0
$ # commit fixes required for the release
$ 01-prepare.sh 4.0.0 5.0.0 0
```

I have the following git history:

```console
# post-tag commits bumping the versions to the new development version numbers
54ed24c39 (HEAD -> release-4.0.0-rc0) [Release] Update .deb package names for 5.0.0
4757d2d08 [Release] Update versions for 5.0.0-SNAPSHOT

# pre-tag commits: changelog update and version bumps
# the actual tag will point to the last version bump commit
ab83815a1 (tag: apache-arrow-4.0.0) [Release] Update versions for 4.0.0
ea248a9fe [Release] Update .deb/.rpm changelogs for 4.0.0
e67ba60f1 [Release] Update CHANGELOG.md for 4.0.0

# the head of the release branch where we can place release related patches without blocking the development on the master branch
c3d27a899 (release-4.0.0) [Release] Fix a something else required for the release
8671464f9 [Release] Fix a cmake error
263365500 [Release] Fix a wheel packaging issue

# this will be the HEAD of the master branch during the release
b17a52751 (remove-mvn-release-plugin) Create the release branch explicitly before prepare 
5960e4391 Force delete branch
f559480e6 Don't remove the remote tracking branch
6aca9078a Exit if RC branch already exists
```

The `release-4.0.0` branch and `apache-arrow-4.0.0` tag can be pushed upstream. Once we have finished with the release, we can create a pull request from `release-4.0.0` branch and update the version numbers on master and add any supplemental patches which were required to cut the release.

**Comment by kszucs** [comment]
As @kou has described, we are going to need a `dev/release/post-XX-java.sh` script to call `mvn deploy`. 
Using the previous mvn release plugin the perform step created a staged maven artifact in the apache maven repository (I assume sonatype nexus) which we "verified/released" manually from its web UI.

@andygrove will manually calling `mvn deploy` do the same thing?

**Comment by andygrove** [comment]
> @andygrove will manually calling `mvn deploy` do the same thing?

Yes. I need to get up to speed again with this today but I assume that previously we were running `mvn release:perform`? If so it performed the following steps:

```
Performing a release runs the following release phases:

- Checkout from an SCM URL with optional tag
- Run the predefined Maven goals to release the project (by default, deploy site-deploy)
```

Copied from the docs here: https://maven.apache.org/maven-release/maven-release-plugin/examples/perform-release.html

**Comment by kszucs** [comment]
> Yes. I need to get up to speed again with this today but I assume that previously we were running `mvn release:perform`? If so it performed the following steps:

Nice! Given that we can handle the rest of the scripting. Thanks again Andy!

**Comment by kou** [comment]
@andygrove Can we split `mvn deploy` to building artifacts task and uploading artifacts task? We want to build artifacts in CI and run only upload task on local machine in the future.

For example, Gandiva's jar needs to bundle all of `libgandiva.so` for Linux, `libgandiva.dylib` for macOS and `gandiva.dll` for Windows. We can't do it on local machine. But we can do it in CI.
See also: https://issues.apache.org/jira/browse/ARROW-11135

**Comment by andygrove** [comment]
@kou Use `mvn package` to bulid artifacts without deploying them

**Review by kszucs — APPROVED** [review]
Tested the release scripts locally. We can address any new issues during the release on the release branch.

**Comment by kou** [comment]
@andygrove Thanks! Do you know `mvn XXX` command line (`mvn upload` or something?) to upload built artifacts?

**Comment by andygrove** [comment]
> @andygrove Thanks! Do you know `mvn XXX` command line (`mvn upload` or something?) to upload built artifacts?

@kou You can just run the `mvn deploy` command. It will build from source again. You might be able to skip running the tests by adding `-DskipTests`.

It is also possible to upload existing artifacts using `mvn deploy:deploy-file` but that seems like unnecessary extra work. https://maven.apache.org/plugins/maven-deploy-plugin/deploy-file-mojo.html

**Comment by kou** [comment]
@andygrove Thanks! We don't want to build from source locally again. So `mvn deploy` doesn't match our use case. It seems that `mvn deploy:deploy-file` will match our use case!

**Pull request closed without merging**
