### PR TITLE
ARROW-10644: [Python] Consolidate path/filesystem handling in pyarrow.dataset and pyarrow.fs

### PR DESCRIPTION
**Pull request by jorisvandenbossche**

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
- Slight downside is that we now do a `get_file_info` twice, but only in the case of a local file path with no filesystem specified (so I think for this case this is less of a concern, but I could still go through hoops to pass it through)
- I added the ability to specify a `filesystem` as a string (the functionality @kszucs added to `pyarrow.dataset`) to the general utilities in `pyarrow.fs`, which means that other functions (eg `parquet.read_table`) also gain this functionality. I should still add a test for that (or if this is not desired, I could also hide this behind an optional keyword, but I think it is good to be consistent in what we accept across submodules).

**Comment by jorisvandenbossche** [comment]
@github-actions crossbow submit -g integration

**Review by pitrou — APPROVED** [review]
+1. I see no obvious problems here.

**Comment by pitrou** [comment]
@jorisvandenbossche Is the CI satisfactory?

**Comment by jorisvandenbossche** [comment]
I added a test, this should be good now

**Comment by pitrou** [comment]
Thank you @jorisvandenbossche !

**Pull request closed without merging**
