### PR TITLE
ARROW-703: Fix issue where setValueCount(0) doesn’t work in the case that we’ve shipped vectors across the wire

### PR DESCRIPTION
**Pull request by julienledem**

### CODE REVIEW

**Comment by julienledem** [comment]
@jacques-n: Could you suggest a unit test for this?

**Comment by jacques-n** [comment]
I'm still trying to figure out a reproduction...

**Comment by julienledem** [comment]
I think the fix i small enough that we can merge it as is.

**Comment by julienledem** [comment]
+1

**Pull request closed without merging**
