### PR TITLE
GH-35588: [Java] returning a constant hashCode for null values, resolves #35588

### LINKED ISSUE #35588: [Java] NullVector returning an inconsistent hash for null values between vectors
### Describe the bug, including details regarding any error messages, version, and platform.

It's currently [implemented](https://github.com/apache/arrow/blob/cd6e2a4d2b9373b942da18b4cc82cb41431764d9/java/vector/src/main/java/org/apache/arrow/vector/NullVector.java#L281) as `31 * valueCount`, which returns a different hashCode for null values from different-length `NullVector`s. Presumably this should be a constant value?

James

### Component(s)

Java

### PR DESCRIPTION
**Pull request by jarohen**
resolves #35588

### Are these changes tested?

I've run `mvn test` locally, and got the following:

```
[INFO]
[INFO] Results:
[INFO]
[ERROR] Errors:
[ERROR]   TestTls.connectTls:43->test:111->lambda$test$6:118 Runtime java.io.FileNotFoundException: /home/james/src/juxt/arrow/java/flight/flight-core/../../../testing/data/flight/cert0.pem (No such file or directory)
[ERROR]   TestTls.connectTlsDisableServerVerification:93->test:111->lambda$test$6:118 Runtime java.io.FileNotFoundException: /home/james/src/juxt/arrow/java/flight/flight-core/../../../testing/data/flight/cert0.pem (No such file or directory)
[ERROR]   TestTls.rejectHostname:76->test:111->lambda$test$6:118 Runtime java.io.FileNotFoundException: /home/james/src/juxt/arrow/java/flight/flight-core/../../../testing/data/flight/cert0.pem (No such file or directory)
[ERROR]   TestTls.rejectInvalidCert:61->test:111->lambda$test$6:118 Runtime java.io.FileNotFoundException: /home/james/src/juxt/arrow/java/flight/flight-core/../../../testing/data/flight/cert0.pem (No such file or directory)
[INFO]
[ERROR] Tests run: 108, Failures: 0, Errors: 4, Skipped: 20
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Apache Arrow Java Root POM 11.0.0:
[INFO]
[INFO] Apache Arrow Java Root POM ......................... SUCCESS [  6.392 s]
[INFO] Arrow Format ....................................... SUCCESS [  2.151 s]
[INFO] Arrow Memory ....................................... SUCCESS [  2.000 s]
[INFO] Arrow Memory - Core ................................ SUCCESS [  3.617 s]
[INFO] Arrow Memory - Unsafe .............................. SUCCESS [  2.478 s]
[INFO] Arrow Memory - Netty ............................... SUCCESS [  3.567 s]
[INFO] Arrow Vectors ...................................... SUCCESS [  9.042 s]
[INFO] Arrow Compression .................................. SUCCESS [  2.722 s]
[INFO] Arrow Tools ........................................ SUCCESS [  3.561 s]
[INFO] Arrow JDBC Adapter ................................. SUCCESS [  5.981 s]
[INFO] Arrow Plasma Client ................................ SUCCESS [  2.069 s]
[INFO] Arrow Flight ....................................... SUCCESS [  1.839 s]
[INFO] Arrow Flight Core .................................. FAILURE [ 20.163 s]
[INFO] Arrow Flight GRPC .................................. SKIPPED
[INFO] Arrow Flight SQL ................................... SKIPPED
[INFO] Arrow Flight SQL JDBC Driver ....................... SKIPPED
[INFO] Arrow Flight Integration Tests ..................... SKIPPED
[INFO] Arrow AVRO Adapter ................................. SKIPPED
[INFO] Arrow Algorithms ................................... SKIPPED
[INFO] Arrow Performance Benchmarks ....................... SKIPPED
```

so it looks like I've not got some certificates that are required to test Flight Core?

### CODE REVIEW

**Review by lidavidm — COMMENTED** [review]
Thanks! 

Would a quick unit test be possible?

(I'll kick off CI too)

**Comment by jarohen** [comment]
I mean, it would, but it'd be checking the method returns 31?

**Comment by lidavidm** [comment]
I was thinking something that checked it was consistent between vectors of different lengths, so a regression test, but fair enough, it's sorta trivial.

**Comment by lidavidm** [comment]
Thanks again!

**Comment by jarohen** [comment]
Cheers @lidavidm!

**Pull request merged**
