### PR TITLE
ARROW-7050: [R] Fix compiler warnings in R bindings

### PR DESCRIPTION
**Pull request by nealrichardson**
One is the one Jeroen caught, and then there are a few new ones related to the result vs. status changes.

This also adds `-Werror` to the GitHub Actions and Appveyor builds for R to hopefully catch these going forward.

### CODE REVIEW

**Review by wesm — APPROVED** [review]
+1. To fail the build you would probably want to specify `-Werror` in an environment variable, `ARROW_R_CXXFLAGS` would probably be it. Feel free to try it here or in a follow up PR

https://github.com/apache/arrow/blob/master/r/configure#L109

**Comment by nealrichardson** [comment]
`-Werror` caught some new ones on master: https://ci.appveyor.com/project/ApacheSoftwareFoundation/arrow/builds/29287896/job/3q0utif5bs5eelf0

Fixed those; really would like to merge this before any additional Result changes (and associated deprecation warnings) hit master (cc @pitrou @bkietz )

**Review by wesm — APPROVED** [review]
+1

**Review by kou — APPROVED** [review]
+1

**Pull request closed without merging**
