### PR TITLE
ARROW-13265: [R] cli valgrind errors in nightlies

### PR DESCRIPTION
**Pull request by jonkeane**

### CODE REVIEW

**Comment by jonkeane** [comment]
@github-actions crossbow submit test-r-linux-valgrind

**Comment by jonkeane** [comment]
@github-actions crossbow submit test-r-linux-valgrind

**Comment by nealrichardson** [comment]
Can you add a comment explains why this env var is being set? Link to the cli issue maybe too. 

Should we remove this change once cli is fixed or does it not really matter?

**Comment by jonkeane** [comment]
Thanks, I've added comments + a link. It also looks like a {cli} fix is already in a PR (though it'll need to be released to cran to help us on this front). 

I do think we should remove it once it is fixed in the interest of cleanliness and the possibility something like this crops up again (or the incredibly unlikely circumstance we do something interacting with threaded-cli that causes an error) since this env var is (likely) not set on BDR's valgrind checking machine.

**Pull request closed without merging**
