### PR TITLE
ARROW-10300: [Rust] Improve documentation for TPC-H benchmark

### PR DESCRIPTION
**Pull request by andygrove**
The main change in this PR is adding documentation for converting `tbl` files to CSV and Parquet using a public Docker image from the Ballista project [1]. This is a short term solution until we can provide a utility within the Arrow Rust project and I filed 
https://issues.apache.org/jira/browse/ARROW-10464 for the longer-term solution.

[1] https://github.com/ballista-compute/ballista

### CODE REVIEW

**Comment by andygrove** [comment]
@rdettai @alamb fyi

**Review by jorgecarleitao — APPROVED** [review]
LGTM. Thanks a lot for the write-up.

I did not have time nor disk to test this, so could wait for others' to validate that this addresses the concern.

**Review by alamb — APPROVED** [review]
I tested out the instructions locally and they worked for me. I say :shipit: ! Some notes are below in case that helps anyone else

I hit some problems compiling tpch-dbgen on mac but that has nothing to do with these instructions. I had to make some small changes to switch references from `<malloc.h>` to `<stdlib.h>`:

```
alamb@ip-10-0-0-49 tpch-dbgen % git diff --ignore-space-change | cat
git diff --ignore-space-change | cat
diff --git a/bm_utils.c b/bm_utils.c
index cbfc400..da38de5 100644
--- a/bm_utils.c
+++ b/bm_utils.c
@@ -68,7 +68,8 @@
 #include <ctype.h>
 #include <math.h>
 #ifndef _POSIX_SOURCE
-#include <malloc.h>
+//#include <malloc.h>
+#include <stdlib.h>
 #endif /* POSIX_SOURCE */
 #include <fcntl.h>
 #include <sys/types.h>
diff --git a/varsub.c b/varsub.c
index 5fbdf46..6e2f280 100644
--- a/varsub.c
+++ b/varsub.c
@@ -41,7 +41,7 @@
 */
 #include <stdio.h>
 #ifndef _POSIX_SOURCE
-#include <malloc.h>
+#include <stdlib.h>
 #endif /* POSIX_SOURCE */
 #if (defined(_POSIX_)||!defined(WIN32))
 #include <unistd.h>
```

This is the command I ran locally: 

```
docker run -v /tmp/tpch-dbgen:/mnt/tpch-dbgen -it ballistacompute/spark-benchmarks:0.4.0-SNAPSHOT \
  convert-tpch \
  --input /mnt/tpch-dbgen \
  --input-format tbl \
  --output /mnt/tpch/parquet \
  --output-format parquet \
  --partitions 64

```

**Comment by rdettai** [comment]
Works perfectly! But it is pulling opaque binaries from dockerhub which is not great... if I have some time, I'll try to bake a Dockerfile that builds everything from source ;-)

**Comment by andygrove** [comment]
@rdettai The source Dockerfile is here but needs to be built in the context of the Ballista build process: https://github.com/ballista-compute/ballista/blob/main/spark/benchmarks/Dockerfile

**Comment by andygrove** [comment]
As I mentioned in the PR description, the real solution is going to be to write a Rust version of this conversion process.

**Pull request closed without merging**
