### PR TITLE
ARROW-3757: [R] R bindings for Flight RPC client

### PR DESCRIPTION
**Pull request by nealrichardson**
This provides some basic methods for interacting with a Flight RPC server via `pyarrow` and `reticulate`.

### CODE REVIEW

**Comment by wesm** [comment]
Cool! What do you think about making this part of the master R project (versus as a separate CRAN package)? I can look at the lower-level details later

**Comment by nealrichardson** [comment]
> What do you think about making this part of the master R project (versus as a separate CRAN package)?

We could. When I started trying this, I don't think I had a great understanding of what Flight really is, so I assumed this would be big and worthy of its own package. (I also was curious to test the workflow of having an R package that wrapped something with pyarrow.) But in the end, there's not a lot of (R) code here, and no new hard dependencies, so we could fold it in to `arrow`.

**Comment by nealrichardson** [comment]
@lidavidm do you have any opinions about this?

**Review by lidavidm — APPROVED** [review]
I can't claim to know R, but the Python bits look fine.

**Review by wesm — APPROVED** [review]
+1 here, may need to be rebased to make sure nothing has been broken in the meantime

**Pull request closed without merging**
