### PR TITLE
ARROW-7937: [Python][Packaging] Remove boost from the macos wheels

### PR DESCRIPTION
**Pull request by kszucs**

### CODE REVIEW

**Comment by kszucs** [comment]
@ursabot crossbow submit -g wheel

**Comment by kszucs** [comment]
@ursabot crossbow submit wheel-osx-cp37m

**Comment by pitrou** [comment]
`test_parquet.py` isn't being run here? https://travis-ci.org/ursa-labs/crossbow/builds/654844820#L13211

**Comment by kszucs** [comment]
Seems like, but not sure why does it require cloudpickle

**Comment by kszucs** [comment]
`pytest.importorskip` is [misused](https://github.com/apache/arrow/blob/master/python/pyarrow/tests/test_parquet.py#L2803), so the whole module is skipped.

**Comment by pitrou** [comment]
The perils of abusing pytest magic...

**Comment by kszucs** [comment]
@ursabot crossbow submit -g wheel

**Comment by kszucs** [comment]
FileSystem.from_uri fails on py35, created jira https://issues.apache.org/jira/browse/ARROW-7936

**Review by kszucs — COMMENTED** [review]
+1

**Pull request closed without merging**
