### PR TITLE
ARROW-858: Remove boost_regex from arrow dependencies

### PR DESCRIPTION
**Pull request by cpcloud**

### CODE REVIEW

**Comment by wesm** [comment]
cc @robertnishihara @pcmoritz -- sorry to back track on this but using regexen in decimals seemed like more trouble than it was worth. @cpcloud could you open a JIRA for this? Thanks

**Comment by cpcloud** [comment]
Done: https://issues.apache.org/jira/browse/ARROW-858

**Comment by cpcloud** [comment]
Now to get builds passing.

**Review by wesm — APPROVED** [review]
+1, thanks! Here's the passing Appveyor build: https://ci.appveyor.com/project/cpcloud/arrow/build/1.0.44

**Pull request closed without merging**
