### PR TITLE
ARROW-17422: [C++][CI] Linux builds are missing dependencies

### PR DESCRIPTION
**Pull request by assignUser**

### CODE REVIEW

**Comment by assignUser** [comment]
@github-actions crossbow submit -g linux

**Comment by kou** [comment]
Oh, sorry. https://github.com/apache/arrow/pull/13883 misses some changes.

Could you try the following patch instead of the changes in this pull request?

```diff
diff --git a/dev/tasks/linux-packages/apache-arrow/debian/control.in b/dev/tasks/linux-packages/apache-arrow/debian/control.in
index 12729cbf9f..edf117cd7e 100644
--- a/dev/tasks/linux-packages/apache-arrow/debian/control.in
+++ b/dev/tasks/linux-packages/apache-arrow/debian/control.in
@@ -145,6 +145,7 @@ Depends:
   libbrotli-dev,
   libbz2-dev,
 @USE_SYSTEM_C_ARES@  libc-ares-dev,
+  libcurl4-openssl-dev,
 @USE_SYSTEM_GRPC@  libgrpc++-dev,
   liblz4-dev,
   libre2-dev,
diff --git a/dev/tasks/linux-packages/apache-arrow/yum/arrow.spec.in b/dev/tasks/linux-packages/apache-arrow/yum/arrow.spec.in
index 5fe63284d0..6930340d41 100644
--- a/dev/tasks/linux-packages/apache-arrow/yum/arrow.spec.in
+++ b/dev/tasks/linux-packages/apache-arrow/yum/arrow.spec.in
@@ -272,6 +272,7 @@ Requires:	bzip2-devel
 %if %{use_flight}
 Requires:	c-ares-devel
 %endif
+Requires:	curl-devel
 %if %{use_gcs}
 Requires:	json-devel
 %endif
```

The error is occurred in a test Docker container. In a test Docker container, dependencies must be installed as dependencies of `libarrow-dev`/`arrow-devel` automatically.

The changes in this pull request install curl on host. But the error isn't related to host environment.

**Comment by assignUser** [comment]
@github-actions crossbow submit -g linux

**Comment by assignUser** [comment]
@kou thanks for the pointers! Is the whole system creating the linux packages documented somewhere?

**Review by kou — APPROVED** [review]
+1

> Is the whole system creating the linux packages documented somewhere?

Sorry. I didn't write it yet...

Here is the overview:

1. Prepare host environment: Install Ruby, Docker and so on.
2. Prepare build environment: Build Docker images with `dev/tasks/linux-packages/apache-arrow/{apt,yum}/*/Dockefile`.
3. Build packages in the built Docker images: Run `rake apt:build`/`rake yum:build` in `dev/tasks/linux-packages/apache-arrow/`
4. Prepare test: Prepare APT/Yum repositories for test on host filesystem.
5. Run test in a clean target Docker image: For Debian GNU/Linux bullseye, we use `debian:bullseye` for the clean target Docker image. We use `dev/release/verify-{apt,yum}.sh` to test packages. This is invoked by `rake apt:test`/`rake yum:test` in `dev/tasks/linux-packages/`.

**Pull request merged**
