### PR TITLE
ARROW-7354: [C++] Fix crash in test-io-hdfs

### PR DESCRIPTION
**Pull request by pitrou**

### CODE REVIEW

**Comment by kszucs** [comment]
@ursabot crossbow submit test-conda-python-3.7-hdfs-2.9.2

**Review by kszucs — APPROVED** [review]
Thanks @pitrou!

**Comment by wesm** [comment]
Why was the code wrong before (was something changed regarding multithreading when using the Status-based APIs)?

**Comment by pitrou** [comment]
The test was using concrete class `HdfsReadableFile` which doesn't inherit the deprecated methods. So `file->ReadAt(3, 3, &buffer)` was calling `HdfsReadableFile::ReadAt(int64_t position, int64_t nbytes, void* out)`...

**Comment by wesm** [comment]
Oh I see, thanks

**Pull request closed without merging**
