### PR TITLE
ARROW-5495: [C++] Update some dependency URLs from http to https

### PR DESCRIPTION
**Pull request by wesm**
HTTPS is more secure. 

I will leave this patch up in case anyone else wants to look for HTTP URLs to change to HTTPS. It's a bit hard to find them because of the `http://` in the Apache license header. Maybe we should change our Apache license headers to use https?

### CODE REVIEW

**Comment by pitrou** [comment]
> Maybe we should change our Apache license headers to use https?

That sounds fine to me, but would RAT complain?

**Comment by nealrichardson** [comment]
FWIW https://www.apache.org/licenses/LICENSE-2.0 resolves just fine, though http://www.apache.org/licenses/LICENSE-2.0 does not redirect to it (see also https://issues.apache.org/jira/projects/ARROW/issues/ARROW-5417).

**Comment by pitrou** [comment]
Answer: RAT complains because released versions do not accepts https variants of the license URL (but it may be fixed in RAT snapshots).
See upstream issues:
- https://issues.apache.org/jira/browse/RAT-212
- https://issues.apache.org/jira/browse/LEGAL-457

**Review by pitrou — APPROVED** [review]
+1.

**Pull request closed without merging**
