### PR TITLE
ARROW-15147: [CI][C++][Gandiva] Fix broken nigthly builds related to boost dependencies

### PR DESCRIPTION
**Pull request by anthonylouisbsb**
Fix the broken nightly builds for the missing CRC dependency.

### CODE REVIEW

**Comment by anthonylouisbsb** [comment]
@github-actions crossbow submit -g java-jars

**Comment by anthonylouisbsb** [comment]
@github-actions crossbow submit java-jars

**Comment by anthonylouisbsb** [comment]
The build failed because of a commit hash, that error is strange to me, I will try to run it againt.

**Comment by anthonylouisbsb** [comment]
@github-actions crossbow submit java-jars

**Comment by kou** [comment]
It's related to #11974.
It seems that we need all Git history to build `.jar`.

How about this?

```diff
diff --git a/dev/tasks/java-jars/github.yml b/dev/tasks/java-jars/github.yml
index 221f98514..dc61eab2f 100644
--- a/dev/tasks/java-jars/github.yml
+++ b/dev/tasks/java-jars/github.yml
@@ -80,7 +80,7 @@ jobs:
     runs-on: macos-latest
     needs: [build-cpp-macos, build-cpp-ubuntu]
     steps:
-      {{ macros.github_checkout_arrow()|indent }}
+      {{ macros.github_checkout_arrow(fetch_depth=0)|indent }}
       - name: Download Linux C++ Libraries
         uses: actions/download-artifact@v2
         with:
diff --git a/dev/tasks/macros.jinja b/dev/tasks/macros.jinja
index d8f2816ee..11bd6b090 100644
--- a/dev/tasks/macros.jinja
+++ b/dev/tasks/macros.jinja
@@ -25,13 +25,14 @@ on:
       - "*-github-*"
 {% endmacro %}
 
-{%- macro github_checkout_arrow() -%}
+{%- macro github_checkout_arrow(fetch_depth=1) -%}
   - name: Checkout Arrow
     uses: actions/checkout@v2
     with:
-      repository: {{ arrow.github_repo }}
-      ref: {{ arrow.head }}
+      fetch-depth: {{ fetch_depth }}
       path: arrow
+      ref: {{ arrow.head }}
+      repository: {{ arrow.github_repo }}
       submodules: recursive
 {% endmacro %}
 ```

**Comment by anthonylouisbsb** [comment]
@kou I applied your changes, I will re run the task.

**Comment by anthonylouisbsb** [comment]
@github-actions crossbow submit java-jars

**Comment by kou** [comment]
@github-actions crossbow submit -g nightly

**Review by kou — APPROVED** [review]
+1

**Pull request closed without merging**
