### PR TITLE
ARROW-8634: [Java] Add Getting Started section to Java README

### PR DESCRIPTION
**Pull request by andygrove**
Currently, it is difficult to get started with Arrow Java because there are no examples, and no "getting started" guide.

This PR adds a couple of trivial examples as a starting point.

### CODE REVIEW

**Comment by emkornfield** [comment]
@andygrove there is a getting started guide but it is apparently hard to find.  See: https://arrow.apache.org/docs/java/vector.html, https://arrow.apache.org/docs/java/ipc.html and https://arrow.apache.org/docs/java/vector_schema_root.html

These are generated by RST files in docs/source/java/ one reason why they aren't discoverable is the link to the Javadocs seems to clober index.rst perhaps you could make this PR about fixing that or adding links to the ones provided (I think they provide more complete examples on a quick perusal).

**Review by emkornfield — CHANGES_REQUESTED** [review]
See note on PR it would be good to reconcile this with existing prose docs.

**Comment by andygrove** [comment]
Ah, I wish I had found this documentation before I started using Arrow Java! OK, I will just add links to the README instead then. Thanks.

**Comment by emkornfield** [comment]
LGTM, thanks, sorry you had to learn the hard way.

**Pull request closed without merging**
