### PR TITLE
PARQUET-1538: [C++] Encryption key management

### PR DESCRIPTION
**Pull request by revit13**

### CODE REVIEW

**Comment by wesm** [comment]
I presume this should be rebased after PARQUET-1300 goes in? Might be better to centralize some of these interfaces in common header files relating to encryption

**Comment by revit1976** [comment]
@wesm -- Yes, this pr should be rebased after PARQUET-1300 goes in. We intend to revist its design and implementation after PARQUET-1300 will go in.

**Comment by wesm** [comment]
@revit1976 now that PARQUET-1300 is merged, what do you think about picking this up again?

**Comment by revit1976** [comment]
@wesm the design of this feature is under construction, under
https://docs.google.com/document/d/1bEu903840yb95k9q2X-BlsYKuXoygE4VnMDl9xz_zhk/edit?usp=sharing
(all feedback is welcome). 
Once the design is complete, we'll proceed with its implementation.

**Comment by wesm** [comment]
What is the status of this?

**Comment by ggershinsky** [comment]
We're experimenting with the design of this technology, there are significant changes since this pull request was created. 
However, this work is converging, and I'll post an updated design doc for a community discussion in two or three weeks. After the discussion is over (or if there are no comments), we'll create new pull requests with the key management implementation.

**Comment by wesm** [comment]
Thanks. I'm closing this PR for now in the interest of paring down our PR queue

**Pull request closed without merging**
