### PR TITLE
ARROW-7846: [Python][Dev] Remove dependencies on six

### PR DESCRIPTION
**Pull request by pitrou**
We're Python 3-only now, except in the PR merge script.

### CODE REVIEW

**Comment by pitrou** [comment]
@wesm @kou @xhochy  Do you think it's useful to keep Python 2 compatibility for the merge script?

**Comment by kszucs** [comment]
On most of the platforms python 2 is still the default interpreter, so moving py2 compatibility could cause problems for the committers.

**Comment by kszucs** [comment]
Seems like archery was already python [3 only](https://github.com/apache/arrow/blob/master/dev/archery/setup.py#L23-L24).

**Review by kszucs — APPROVED** [review]
LGTM

**Comment by wesm** [comment]
@pitrou I think it's okay to leave it as is until it needs to be worked on, some systems still have default Python 2.7 but we can remove it later and modernize the script

**Comment by kou** [comment]
I don't have strong opinion but I think that we can drop Python 2.7 support.

**Pull request closed without merging**
