### PR TITLE
GH-38711: [CI] Rollback aws-cli for preview documentation

### LINKED ISSUE #38711: [CI][Docs] Docs preview jobs failing
### Describe the bug, including details regarding any error messages, version, and platform.

The crossbow docs preview jobs have started failing with message:

```
Run aws s3 cp build/docs/ $BUCKET/pr_docs/38693/ --recursive
/home/runner/work/_temp/70d5ef2e-28c6-49e6-8af5-fca87c77e[1](https://github.com/ursacomputing/crossbow/actions/runs/6860473195/job/18654366354#step:10:1)39.sh: line 1: aws: command not found
Error: Process completed with exit code 127.
```
on the Upload preview to S3 step.

Examples:
- https://github.com/ursacomputing/crossbow/actions/runs/6860473195/job/18654366354
- https://github.com/ursacomputing/crossbow/actions/runs/6857464984/job/18646604692

cc @assignUser 

### Component(s)

Continuous Integration

### PR DESCRIPTION
**Pull request by llama90**
### Rationale for this change

Restored the Runner image to not delete `aws-cli` for the execution of the `preview-docs` command.

### Are these changes tested?

No

### Are there any user-facing changes?

No

* Closes: #38711

### CODE REVIEW

**Comment by llama90** [comment]
@kou Would it be possible for you to assist in testing this part? I understood `aws-sam` to be related to SAM (Serverless Application Model) and therefore did not restore it.

**Comment by kou** [comment]
@github-actions crossbow submit preview-docs

**Comment by kou** [comment]
Sure!
(I think that you can also submit a job by `@github-actions crossbow submit preview-docs` because your commits exist in apache/arrow.)

**Review by kou — APPROVED** [review]
+1

**Pull request merged**
