### PR TITLE
GH-44642: [Java] VariableWidthViewVectorBenchmarks

### PR DESCRIPTION
**Pull request by ViggoC**
* GitHub Issue: apache/arrow-java#41
* GitHub Issue: #41

### CODE REVIEW

**Comment by kou** [comment]
Could you open a new issue for this? This is not a "MINOR" change. See also the auto-generated comment: https://github.com/apache/arrow/pull/44634#issuecomment-2455022681

**Comment by ViggoC** [comment]
@kou Sure.

**Comment by kou** [comment]
Sorry. Could you open a new PR in https://github.com/apache/arrow-java ?
We're moving `java/` to apache/arrow-java from apache/arrow.

**Comment by ViggoC** [comment]
@kou okay

**Pull request closed without merging**
