### PR TITLE
ARROW-7297: [C++] Add value accessor in sparse tensor class

### PR DESCRIPTION
**Pull request by rok**
This is to add a SparseTensor value accessor like `Tensor::Value<T>`.
See [ARROW-7297](https://issues.apache.org/jira/browse/ARROW-7297).

### CODE REVIEW

**Comment by pitrou** [comment]
What is the point of exposing such an inefficient primitive?

**Comment by rok** [comment]
@pitrou this would be useful if the user wants to read some data from a sparse tensor but doesn't want to go via dense format.
Perhaps a more pragmatic approach would be to return a slice of the sparse tensor that can be then converted to dense before being read.

**Comment by pitrou** [comment]
Or perhaps some kind of iteration facility? That would avoid the O(n) behaviour.

**Comment by rok** [comment]
Got it. So like a reader that would take a series of points and cache in between reads? We'd have to have read points be sorted I suppose.

**Comment by rok** [comment]
With guarantee of COO being sorted we could do O(log n). We could already do O(log n) for CSR and CSC as they are sorted. CSF has O(ndim) lookup complexity.

**Comment by pitrou** [comment]
I think the driving question should be the use cases. Is there a need for random access to singular values?

**Comment by mrkn** [comment]
I'm the original reporter of the JIRA ticket, but I don't know whether or not there are actual use cases of random access to values in sparse tensors.  The JIRA ticket came from the existence of value accessing features in scipy's sparse tensors.

I guess my mistake is making the ticket priority Major.  It should be Minor at the creation time.

I think the feature mentioned in the JIRA ticket presumably can be a different way from providing `SparseTensor::Value<T>` function.  IMO, the functionality can be decomposed the following sub-features, and providing them can be alternative to only `SparseTensor::Value<T>`.

- Iterating existing indices in a SparseIndex
- Finding the given index in a SparseIndex and returning the offset of the index
- Returning the value of the given offset
- Making the slice of a SparseTensor

By the way, this implementation proposal is not acceptable even if there are any realistic use cases of `SparseTensor::Value<T>`.  `CalculateValueOffset` function should be implemented in each subclass of SparseIndex class.

**Comment by rok** [comment]
This is a potential [usecase](https://issues.apache.org/jira/browse/ARROW-8679).

**Comment by mrkn** [comment]
IMO SparseTensor is not appropriate for implementing the counterpart of pandas's sparse series because pandas's sparse series is a 1-dimensional array.  We should introduce the same 1-dimensional sparse array data format for such purpose.

If we add a new data format and class of such a 1-dimensional sparse array, the class will have `Value<T>` function, and its implementation won't be inefficient.

**Comment by rok** [comment]
> IMO SparseTensor is not appropriate for implementing the counterpart of pandas's sparse series because pandas's sparse series is a 1-dimensional array. We should introduce the same 1-dimensional sparse array data format for such purpose.

Good point, it's not a good match.

**Comment by rok** [comment]
@pitrou I am not sure about the value of this primitive. There are [valid use cases](https://pytorch.org/cppdocs/notes/tensor_basics.html#efficient-access-to-tensor-elements) however I'm not sure we have interest from the community. If you don't see immediate use for this I'll close it.

**Comment by pitrou** [comment]
I don't think the Arrow sparse tensor classes see much use directly, so I would favor closing and moving on. @amol-  Any objection?

**Comment by cyb70289** [comment]
Close this PR as it looks inactive. Feel free to reopen if necessary.

**Pull request closed without merging**
