### PR TITLE
ARROW-6671: [C++][Python] Use more consistent names for sparse tensor items

### PR DESCRIPTION
**Pull request by mrkn**

### CODE REVIEW

**Comment by mrkn** [comment]
This pull-request renames the following names:

- SparseTensorCOO → SparseCOOTensor
- SparseTensorCSR → SparseCSRMatrix
- sparse_tensor_coo → sparse_coo_tensor
- sparse_tensor_csr → sparse_csr_matrix

And, this removes SparseMatrixCSR symbol.

**Comment by mrkn** [comment]
This pull-request will break #4990.

**Comment by pitrou** [comment]
@wesm

**Review by pitrou — APPROVED** [review]
+1. Will merge once green.

**Pull request closed without merging**
