### PR TITLE
ARROW-5863: [Python] Use atexit module for extension type finalization to avoid segfault

### PR DESCRIPTION
**Pull request by wesm**
As reported on JIRA, the following script provokes a segfault 

```
#! /usr/bin/env python

import pyarrow
import sys
del sys.modules['pyarrow.lib']
```

For some reason this does not trigger the destruction of the private `_ExtensionTypesInitializer` object. Not sure why (Antoine may know). Using the atexit module instead seems to do the trick

### CODE REVIEW

**Comment by wesm** [comment]
+1

Travis CI build: https://travis-ci.org/wesm/arrow/builds/555965259
Appveyor: https://ci.appveyor.com/project/wesm/arrow/builds/25830311

**Comment by pitrou** [comment]
I'm not sure I understand the underlying cause either. It seems the module-wide `_ExtensionTypesInitializer` instance was never destroyed. Would be worth opening a Cython issue for advice, IMHO.

**Comment by wesm** [comment]
I opened https://github.com/cython/cython/issues/3039

**Comment by scoder** [comment]
In order to prevent common cases for crashes or other weird behaviour at shutdown, module-level cleanup is not enabled by default. Does pyarrow use it?

https://github.com/cython/cython/blob/3c4e11ddcf5634cf15c786e22ac1835a419a3622/Cython/Compiler/Options.py#L63-L67

The comment in there is not entirely correct for Py3 anymore, where the cleanup is triggered by CPython's module object cleanup. That might not be at system exit but when actually unloading the module for whatever (rare) reason, even before exiting. It's still typically the system exit, though.

**Comment by scoder** [comment]
Updated the comment [here](https://github.com/cython/cython/commit/f5de8c4292432753edfe9a05272fe26474a5a030#diff-1cbb0854b3f1695a32f7f1611f5107eb).

**Pull request closed without merging**
