### PR TITLE
WIP: [Release] Verify release-15.0.2-rc3

### PR DESCRIPTION
**Pull request by raulcd**
PR to verify Release Candidate

### CODE REVIEW

**Comment by raulcd** [comment]
@github-actions crossbow submit  --group verify-rc-source --param release=15.0.2 --param rc=3

**Comment by raulcd** [comment]
Revision: e03105efc38edca4ca429bf967a17b4d0fbebe40

Submitted crossbow builds: [ursacomputing/crossbow @ release-15.0.2-rc3-0](https://github.com/ursacomputing/crossbow/branches/all?query=release-15.0.2-rc3-0)

|Task|Status|
|----|------|
|almalinux-8-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/tree/release-15.0.2-rc3-0-github-almalinux-8-amd64)|
|almalinux-8-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/tree/release-15.0.2-rc3-0-github-almalinux-8-arm64)|
|almalinux-9-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/tree/release-15.0.2-rc3-0-github-almalinux-9-amd64)|
|almalinux-9-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/tree/release-15.0.2-rc3-0-github-almalinux-9-arm64)|
|amazon-linux-2023-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/tree/release-15.0.2-rc3-0-github-amazon-linux-2023-amd64)|
|amazon-linux-2023-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/tree/release-15.0.2-rc3-0-github-amazon-linux-2023-arm64)|
|centos-7-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/tree/release-15.0.2-rc3-0-github-centos-7-amd64)|
|centos-8-stream-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/tree/release-15.0.2-rc3-0-github-centos-8-stream-amd64)|
|centos-8-stream-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8265635931/job/22611737239)|
|centos-9-stream-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/tree/release-15.0.2-rc3-0-github-centos-9-stream-amd64)|
|centos-9-stream-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8265635911/job/22611736625)|
|conan-maximum|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8265635902/job/22611736888)|
|conan-minimum|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8265635487/job/22611734470)|
|debian-bookworm-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8265635624/job/22611735230)|
|debian-bookworm-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8265635313/job/22611733920)|
|debian-bullseye-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8265635848/job/22611735919)|
|debian-bullseye-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/tree/release-15.0.2-rc3-0-github-debian-bullseye-arm64)|
|debian-trixie-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8265635633/job/22611735381)|
|debian-trixie-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8265635846/job/22611735922)|
|java-jars|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8265636170/job/22611745849)|
|nuget|[GitHub Actions](https://github.com/ursacomputing/crossbow/tree/release-15.0.2-rc3-0-github-nuget)|
|python-sdist|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8265635279/job/22611733547)|
|r-binary-packages|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8265636085/job/22611740385)|
|test-ubuntu-22.04-docs|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8265636238/job/22611746670)|
|ubuntu-focal-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/tree/release-15.0.2-rc3-0-github-ubuntu-focal-amd64)|
|ubuntu-focal-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8265635990/job/22611737792)|
|ubuntu-jammy-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/tree/release-15.0.2-rc3-0-github-ubuntu-jammy-amd64)|
|ubuntu-jammy-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/tree/release-15.0.2-rc3-0-github-ubuntu-jammy-arm64)|
|ubuntu-mantic-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8265635539/job/22611734520)|
|ubuntu-mantic-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8265635403/job/22611734029)|
|wheel-macos-big-sur-cp310-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/tree/release-15.0.2-rc3-0-github-wheel-macos-big-sur-cp310-arm64)|
|wheel-macos-big-sur-cp311-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/tree/release-15.0.2-rc3-0-github-wheel-macos-big-sur-cp311-arm64)|
|wheel-macos-big-sur-cp312-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/tree/release-15.0.2-rc3-0-github-wheel-macos-big-sur-cp312-arm64)|
|wheel-macos-big-sur-cp38-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/tree/release-15.0.2-rc3-0-github-wheel-macos-big-sur-cp38-arm64)|
|wheel-macos-big-sur-cp39-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8265635547/job/22611734581)|
|wheel-macos-catalina-cp310-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8265636351/job/22611748324)|
|wheel-macos-catalina-cp311-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8265636282/job/22611747470)|
|wheel-macos-catalina-cp312-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8265636157/job/22611745487)|
|wheel-macos-catalina-cp38-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8265636404/job/22611755188)|
|wheel-macos-catalina-cp39-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8265635885/job/22611736661)|
|wheel-manylinux-2-28-cp310-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8265636326/job/22611747925)|
|wheel-manylinux-2-28-cp310-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/tree/release-15.0.2-rc3-0-github-wheel-manylinux-2-28-cp310-arm64)|
|wheel-manylinux-2-28-cp311-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8265636195/job/22611746521)|
|wheel-manylinux-2-28-cp311-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/tree/release-15.0.2-rc3-0-github-wheel-manylinux-2-28-cp311-arm64)|
|wheel-manylinux-2-28-cp312-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8265636338/job/22611747618)|
|wheel-manylinux-2-28-cp312-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8265635631/job/22611735303)|
|wheel-manylinux-2-28-cp38-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/tree/release-15.0.2-rc3-0-github-wheel-manylinux-2-28-cp38-amd64)|
|wheel-manylinux-2-28-cp38-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8265635615/job/22611735035)|
|wheel-manylinux-2-28-cp39-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8265635365/job/22611734075)|
|wheel-manylinux-2-28-cp39-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8265635291/job/22611733580)|
|wheel-manylinux-2014-cp310-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/tree/release-15.0.2-rc3-0-github-wheel-manylinux-2014-cp310-amd64)|
|wheel-manylinux-2014-cp310-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8265635364/job/22611734005)|
|wheel-manylinux-2014-cp311-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/tree/release-15.0.2-rc3-0-github-wheel-manylinux-2014-cp311-amd64)|
|wheel-manylinux-2014-cp311-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/tree/release-15.0.2-rc3-0-github-wheel-manylinux-2014-cp311-arm64)|
|wheel-manylinux-2014-cp312-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8265635212/job/22611733378)|
|wheel-manylinux-2014-cp312-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8265635914/job/22611736983)|
|wheel-manylinux-2014-cp38-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8265635870/job/22611736333)|
|wheel-manylinux-2014-cp38-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8265635946/job/22611737315)|
|wheel-manylinux-2014-cp39-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/tree/release-15.0.2-rc3-0-github-wheel-manylinux-2014-cp39-amd64)|
|wheel-manylinux-2014-cp39-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8265636713/job/22611773088)|
|wheel-windows-cp310-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8265635831/job/22611735887)|
|wheel-windows-cp311-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8265635645/job/22611735546)|
|wheel-windows-cp312-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8265636051/job/22611737954)|
|wheel-windows-cp38-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8265636617/job/22611758535)|
|wheel-windows-cp39-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8265635613/job/22611735001)|

**Comment by kou** [comment]
@github-actions crossbow submit  --group verify-rc-binaries --group verify-rc-wheels --param release=15.0.2 --param rc=3

**Comment by raulcd** [comment]
For `verify-rc-binaries-wheels-macos-11-arm64` see: https://github.com/apache/arrow/issues/40546

**Comment by raulcd** [comment]
@github-actions crossbow submit verify-rc-binaries-jars-* --group verify-rc-wheels --param release=15.0.2 --param rc=3

**Comment by raulcd** [comment]
@github-actions crossbow submit verify-rc-binaries-jars-* --param release=15.0.2 --param rc=3

**Comment by raulcd** [comment]
@ursabot please benchmark

**Pull request merged**
