### PR TITLE
ARROW-16763: [Packaging][RPM] Add support for CentOS Stream 9

### PR DESCRIPTION
**Pull request by kou**

### CODE REVIEW

**Comment by kou** [comment]
@github-actions crossbow submit amazon-linux-* almalinux-* centos-*

**Comment by kou** [comment]
@github-actions crossbow submit amazon-linux-* almalinux-* centos-*

**Comment by kou** [comment]
@github-actions crossbow submit centos-*

**Comment by kou** [comment]
@github-actions crossbow submit centos-*

**Review by cyb70289 — APPROVED** [review]

**Pull request merged**
