### PR TITLE
ARROW-6337: [R] Changed as_tible to as_dataframe in the R package

### PR DESCRIPTION
**Pull request by jameslamb**
See [ARROW-6337](https://issues.apache.org/jira/browse/ARROW-6337) for background on this PR.

### CODE REVIEW

**Review by nealrichardson — CHANGES_REQUESTED** [review]
Acknowledging that naming things is hard, I'm not a fan of `as_dataframe`. That doesn't look right to me. I'd prefer `as_data_frame`, or even `data_frame` is better IMO--I'm not sure "as" adds any value. 

What do you think?

**Comment by jameslamb** [comment]
> Acknowledging that naming things is hard, I'm not a fan of `as_dataframe`. That doesn't look right to me. I'd prefer `as_data_frame`, or even `data_frame` is better IMO--I'm not sure "as" adds any value.
> 
> What do you think?

IMO `as_data_frame` or `return_data_frame` is more informative than `data_frame`, so it's obvious in code that it isn't, for example, a flag used to allow you to pass in `parse_options` as a data frame instead of named list or something.

As long as we're keeping the "change output type with a flag" pattern, my preferences in order are:

1. `as_data_frame`
2. `return_data_frame`
3. `data_frame`

I hold that opinion lightly though, and I'll defer to whatever you think is best on this one. Let me know what you'd like to do and I'd be happy to update the PR today!

**Comment by nealrichardson** [comment]
Alright, then `as_data_frame` seems to be the compromise solution. Let's go with that.

**Comment by jameslamb** [comment]
> Alright, then `as_data_frame` seems to be the compromise solution. Let's go with that.

🤝 updated to `as_data_frame` and rebased to most recent `master`

**Comment by nealrichardson** [comment]
+1, thanks!

**Pull request closed without merging**
