### PR TITLE
PARQUET-1788: Remove UBSan when rep/dev levels are null

### PR DESCRIPTION
**Pull request by emkornfield**

### CODE REVIEW

**Review by fsaintjacques — APPROVED** [review]

**Comment by emkornfield** [comment]
@wesm or @xhochy since this technically falls inside the "parquet code base" would can you review/merge?

**Review by wesm — APPROVED** [review]
+1

**Comment by wesm** [comment]
Is this UBSan issue reflected in any unit test?

**Comment by emkornfield** [comment]
It is covered by read/write arrow tests.  The ubsan check was only added last September it seems so might not be in the compiler our CI uses

**Comment by wesm** [comment]
Roger. I guess we might set up a UBSan target with clang "bleeding"

**Pull request closed without merging**
