### PR TITLE
ARROW-813: [Python] setup.py sdist must also bundle dependent cmake m…

### PR DESCRIPTION
**Pull request by xhochy**
…odules

### CODE REVIEW

**Review by wesm — APPROVED** [review]
+1. Will wait for build

**Comment by xhochy** [comment]
This fails on Windows, solutions seems to be to run `git config core.symlinks true` before the build (see https://github.com/appveyor/ci/issues/650) Not sure if that is a path we should go. cc @MaxRis

**Comment by MaxRis** [comment]
@xhochy , usage of `git config core.symlinks true` looks much better than alternative script based solutions for Windows. It seems that on Windows created symlinks will not work with FAT32 filesystem, only with NTFS ( http://stackoverflow.com/a/11664406/2266412 ). Personally, I haven't seen wide usage of symlinks on Windows.

**Comment by xhochy** [comment]
Apache RAT fails on compressed tarballs with symlinks, will ignore them for now but I raised an issue upstream: https://issues.apache.org/jira/browse/RAT-235

**Comment by wesm** [comment]
Appveyor still failing it seems, odd

**Comment by xhochy** [comment]
Fixed: https://ci.appveyor.com/project/xhochy/arrow/build/1.0.317

**Pull request closed without merging**
