### PR TITLE
ARROW-1249: [JAVA] expose fillEmpties from Nullable variable length vectors

### PR DESCRIPTION
**Pull request by siddharthteotia**
This will allow us to do some cleanup in Dremio where we have written wrapper routines using Reflection to access the fillEmpties method of mutator.

Unit tests have been added.

### CODE REVIEW

**Comment by siddharthteotia** [comment]
@jacques-n 

Some cleanup and refactoring in Dremio (LastSetters.java, Vectors.java and their callers) is being done as part of:

https://dremio.atlassian.net/browse/DX-8510 -- this PR
https://dremio.atlassian.net/browse/DX-8268 -- no PR need as the changes pertained to Dremio.
https://dremio.atlassian.net/browse/DX-8267 -- PR https://github.com/apache/arrow/pull/868 into apache-arrow merged

Once the Arrow related changes are available in Dremio, we can do the cleanup as a single JIRA. Multiple JIRAs are there just to track the items.

**Comment by siddharthteotia** [comment]
Retriggered the build.

**Comment by wesm** [comment]
The build failure was unrelated to your changes. Pending ARROW-1253 I think it's OK to merge if that particular build entry fails

**Comment by siddharthteotia** [comment]
Thanks @wesm

**Comment by siddharthteotia** [comment]
The build job timed out again. Since the time limit issue with Travis CI build is a known problem, this PR can probably be merged.

**Review by wesm — APPROVED** [review]
+1. I will put up a patch about build performance on that one later tonight if possible, worst case tomorrow

**Pull request closed without merging**
