### PR TITLE
ARROW-695: Add decimal integration test.

### PR DESCRIPTION
**Pull request by icexelloss**

### CODE REVIEW

**Comment by icexelloss** [comment]
cc @wesm @cpcloud 

This adds integration test for Decimal. Currently it's failing on C++ side with:

```
==========================================================
Testing file /tmp/tmpz8z0ri71/generated_decimal.json
==========================================================
-- Creating binary inputs
/home/icexelloss/workspace/arrow/cpp/test-build/debug/json-integration-test --integration --arrow=/tmp/tmp541io3l1/5654a62e468343628465123c48896895_generated_decimal.json_to_arrow --json=/tmp/tmpz8z0ri71/generated_decimal.json --mode=JSON_TO_ARROW
Command failed: /home/icexelloss/workspace/arrow/cpp/test-build/debug/json-integration-test --integration --arrow=/tmp/tmp541io3l1/5654a62e468343628465123c48896895_generated_decimal.json_to_arrow --json=/tmp/tmpz8z0ri71/generated_decimal.json --mode=JSON_TO_ARROW
With output:
--------------
Error message: Invalid: field mode not found

--------------

```

but it's possible that I didn't generate the json file correctly.

**Comment by wesm** [comment]
I can look at the C++ side today or tomorrow -- I don't think we have tested IPC or JSON round trip for decimals so that may have to get done first (ARROW-696).

**Comment by icexelloss** [comment]
Aha, I missed ARROW-696. Yeah let's wait for ARROW-696 then.

**Comment by wesm** [comment]
Rebased

**Comment by wesm** [comment]
@icexelloss the integration tests passed, nice work

**Review by wesm — APPROVED** [review]
+1, will merge once all tests pass

**Comment by BryanCutler** [comment]
Great, thanks @icexelloss and @wesm!

**Pull request closed without merging**
