### PR TITLE
ARROW-8264: [Rust] [DataFusion] Add utility for printing batches

### PR DESCRIPTION
**Pull request by andygrove**
This PR adds a utility for printing batches and updates the examples to call this code. This makes the examples more concise and the output more consistent.

The code was previously in the CLI but is now in the new utils module.

```
$ cargo run --example csv_sql
   Compiling datafusion v1.0.0-SNAPSHOT (/home/andy/git/andygrove/arrow/rust/datafusion)
    Finished dev [unoptimized + debuginfo] target(s) in 4.16s
     Running `target/debug/examples/csv_sql`
+----+----------------------+--------------------+
| c1 | MIN                  | MAX                |
+----+----------------------+--------------------+
| a  | 0.02182578039211991  | 0.9567595541247681 |
| e  | 0.01479305307777301  | 0.9965400387585364 |
| d  | 0.061029375346466685 | 0.9748360509016578 |
| c  | 0.2667177795079635   | 0.991517828651004  |
| b  | 0.04893135681998029  | 0.9185813970744787 |
+----+----------------------+--------------------+


```

### CODE REVIEW

**Review by paddyhoran — APPROVED** [review]
LGTM

**Comment by andygrove** [comment]
CI error is unrelated to my changes:

```
FAILED: boost_ep-prefix/src/boost_ep-stamp/boost_ep-download 
cd /build/cpp/boost_ep-prefix/src && /usr/bin/cmake -P /build/cpp/boost_ep-prefix/src/boost_ep-stamp/boost_ep-download-DEBUG.cmake && /usr/bin/cmake -E touch /build/cpp/boost_ep-prefix/src/boost_ep-stamp/boost_ep-download
CMake Error at boost_ep-stamp/boost_ep-download-DEBUG.cmake:16 (message):
  Command failed: 1

   '/usr/bin/cmake' '-Dmake=' '-Dconfig=' '-P' '/build/cpp/boost_ep-prefix/src/boost_ep-stamp/boost_ep-download-DEBUG-impl.cmake'
```

**Comment by kszucs** [comment]
@andygrove are the changes covered with tests?

**Comment by wesm** [comment]
@andygrove the change detection in the GitHub Actions configuration may be sensitive to certain `git merge` cases under the hood. If you are only touching the rust/ directory then no need to worry about other failing CI jobs

**Comment by nealrichardson** [comment]
Looks like rebase solved the CI issues.

**Comment by andygrove** [comment]
So the issue was that I had originally touched a CI file to add a Rust example that is not currently tested by CI. I ended up rebasing without that change. Thanks for the help.

@kszucs I added a unit test.

**Pull request closed without merging**
