### PR TITLE
ARROW-5723:[C++][Arrow] Fix crossbow failure

### PR DESCRIPTION
**Pull request by praveenbingo**
Refactor code to compile in the devtoolset compiler.

### CODE REVIEW

**Review by pitrou — APPROVED** [review]
LGTM. Do you have an example of the build failures?

**Comment by kszucs** [comment]
We should re-run those builds.

**Comment by praveenbingo** [comment]
https://travis-ci.com/dremio/arrow-build/builds/116803123

I tried using the same docker and it passes now.

**Comment by kszucs** [comment]
@ursabot crossbow package -g gandiva

**Comment by praveenbingo** [comment]
Kicked it off in my travis too : https://travis-ci.org/praveenbingo/arrow-build/builds

**Pull request closed without merging**
