### PR TITLE
ARROW-12034: [Developer Tools] Formalize Minor PRs

### PR DESCRIPTION
**Pull request by emkornfield**

### CODE REVIEW

**Comment by emkornfield** [comment]
Is there a good way to test this, especially the GHA part?

**Comment by kou** [comment]
The PR title check job is ran on the master branch.

You can test this change by the following:

  1. Push the change to  https://github.com/emkornfield/arrow/tree/master (not apache/arrow)
  2. Create a test PR on https://github.com/emkornfield/arrow (not apache/arrow)

e.g.: https://github.com/kou/arrow/pull/10 is a test PR that was used to test my change.

**Comment by emkornfield** [comment]
Thanks @kou, finally had a time to test this out.  It seems to work. One question is if I should add a GHA that provides positive confirmation that the "MINOR:" title is correct.

**Comment by kou** [comment]
I don't think that we need it but it may be able to implement by the following:

```diff
diff --git a/.github/workflows/dev_pr/link.js b/.github/workflows/dev_pr/link.js
index 550a9cd39..c27b5f8f1 100644
--- a/.github/workflows/dev_pr/link.js
+++ b/.github/workflows/dev_pr/link.js
@@ -19,6 +19,9 @@ function detectJIRAID(title) {
   if (!title) {
     return null;
   }
+  if (title.startsWith("MINOR: ") {
+    return "MINOR";
+  }
   const matched = /^(WIP:?\s*)?((ARROW|PARQUET)-\d+)/.exec(title);
   if (!matched) {
     return null;
@@ -47,15 +50,20 @@ async function haveComment(github, context, pullRequestNumber, body) {
 }
 
 async function commentJIRAURL(github, context, pullRequestNumber, jiraID) {
-  const jiraURL = `https://issues.apache.org/jira/browse/${jiraID}`;
-  if (await haveComment(github, context, pullRequestNumber, jiraURL)) {
+  let body;
+  if (jiraID === "MINOR") {
+    body = 'This is a minor PR.';
+  } else {
+    body = `https://issues.apache.org/jira/browse/${jiraID}`;
+  }
+  if (await haveComment(github, context, pullRequestNumber, body)) {
     return;
   }
   await github.issues.createComment({
     owner: context.repo.owner,
     repo: context.repo.repo,
     issue_number: pullRequestNumber,
-    body: jiraURL
+    body: body
   });
 }
 ```

**Comment by emkornfield** [comment]
@kou I tend to agree it might not be need, just might need some getting used of no GHA if MINOR is specified.  If people complain, I'll try adding the proposed diff as a follow-up.

**Review by alamb — APPROVED** [review]
The basic idea looks good to me. Thank you @emkornfield 

I do not know how to test the automation / scripts other than "in production" but that might be ok for this kind of PR

**Comment by emkornfield** [comment]
> I do not know how to test the automation / scripts other than "in production" but that might be ok for this kind of PR

@kou gave the pointer of testing on my fork above, which I did.

**Comment by wesm** [comment]
+1 from me on the content

**Comment by emkornfield** [comment]
I'll wait until at least Friday and then merge unless anyone objects.

**Review by kou — APPROVED** [review]
+1

**Pull request closed without merging**
