### PR TITLE
[Site] Add Antoine to committers list

### PR DESCRIPTION
**Pull request by pitrou**
I'm assuming this doesn't need a jIRA?

### CODE REVIEW

**Comment by xhochy** [comment]
This is fine. @pitrou Do you take care of updating the site or should I do that?

**Comment by pitrou** [comment]
I tried the procedure for updating the site but there's something suspicious in the diff I get locally:
```diff
diff --git a/blog/index.html b/blog/index.html
index cfddf8f..68d251d 100644
--- a/blog/index.html
+++ b/blog/index.html
@@ -304,7 +304,7 @@ computational libraries within the project.</p>
   <div class="container">
     <h2>
       Apache Arrow 0.8.0 Release
-      <a href="/blog/2017/12/18/0.8.0-release/" class="permalink" title="Permalink">∞</a>
+      <a href="/blog/2017/12/19/0.8.0-release/" class="permalink" title="Permalink">∞</a>
     </h2>
```

It seems the date of that blog post was changed after it was pushed to arrow.apache.org. The header for the blog post is:
```
$ head -n7 _posts/2017-12-19-0.8.0-release.md 
---
layout: post
title: "Apache Arrow 0.8.0 Release"
date: "2017-12-19 00:01:00 -0400"
author: wesm
categories: [release]
---
```

What should we do here? This risks breaking existing links.

**Comment by xhochy** [comment]
Yes that's because you're probably located in Europe. The generated permalink is dependent on your location (and your local timezone). I think when you deploy from the US east coast timezone, the permalink will be for 2017-12-18. 

(not 100% sure about that, would be good to have a permanent solution to this problem).

**Comment by xhochy** [comment]
I think Wes (east coast) wrote that article and Sidd (west coast) deployed it. 

A valid fix could be to set the date to something so it's "2017-12-19" for everyone.

**Comment by pitrou** [comment]
Amusingly, the asf-site repo has two copies of the blog post "Java vector improvements":
```
$ find -name "java-vector-improvements"
./blog/2017/12/18/java-vector-improvements
./blog/2017/12/19/java-vector-improvements
```

**Comment by pitrou** [comment]
Ok, https://github.com/apache/arrow/pull/1858 seems to do the trick here.

**Comment by pitrou** [comment]
I've pushed the site update. Nothing seems broken.

**Pull request merged**
