### PR TITLE
ARROW-9284: [Java] fix getMinorTypeForArrowType with dense unions

### PR DESCRIPTION
**Pull request by lidavidm**
We added a new minor type but didn't adjust the type -> minor type mapping.

### CODE REVIEW

**Review by rymurr — APPROVED** [review]
You beat me to it! https://github.com/apache/arrow/pull/7290/files#diff-2be1b706e7360a9277f320b59176ce6eR812

+1 from me

**Comment by lidavidm** [comment]
> You beat me to it! https://github.com/apache/arrow/pull/7290/files#diff-2be1b706e7360a9277f320b59176ce6eR812
> 
> +1 from me

Ah, I just noticed it when I went to test Arrow master internally, should have figured you would have run into it too :sweat_smile:

**Comment by lidavidm** [comment]
If the format changes get through, we can just land your PR and fix all this once and for all.

**Comment by lidavidm** [comment]
Superseded by ARROW-1692/#7290.

**Pull request closed without merging**
