### PR TITLE
ARROW-16694: [Packaging][Python] Use Mamba instead of conda to build conda environment for windows packaging jobs

### PR DESCRIPTION
**Pull request by raulcd**
Conda windows packaging jobs have been failing since the 26th of May.
There was a problem when creating the conda environment using conda with the boa requirement having conflicts.
This PR updates the Azure pipeline to use Mamba instead of conda to create the environment as the upstream feedstock does:
https://github.com/conda-forge/arrow-cpp-feedstock/blob/main/.azure-pipelines/azure-pipelines-win.yml

### CODE REVIEW

**Comment by raulcd** [comment]
@github-actions crossbow submit conda-win-vs2017-py37*

**Comment by raulcd** [comment]
@github-actions crossbow submit conda-win-vs2017-py37*

**Comment by raulcd** [comment]
@github-actions crossbow submit conda-win-vs2017-py38

**Comment by raulcd** [comment]
@github-actions crossbow submit conda-win-vs2017-*

**Comment by raulcd** [comment]
@kszucs @kou this PR fixes the conda packaging jobs that have been failing for Windows for some time. Let me know what you think.

**Review by kou — APPROVED** [review]
+1

Great!

**Pull request merged**
