### PR TITLE
ARROW-10863: [Python] Fix pandas skip in ExtensionArray.to_pandas test

### PR DESCRIPTION
**Pull request by jorisvandenbossche**

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
@github-actions crossbow submit -g integration wheel

**Comment by jorisvandenbossche** [comment]
@github-actions crossbow submit -g wheel

**Comment by jorisvandenbossche** [comment]
@github-actions crossbow submit -g integration

**Comment by pitrou** [comment]
@jorisvandenbossche Are you happy with the build results? If so, will merge.

**Review by kou — APPROVED** [review]
+1

Thanks!

**Comment by jorisvandenbossche** [comment]
Hmm, the pandas master/nightly builds are failing, and it is in tests that I touched, it seems unrelated (just by accident that a recent change in pandas master also impacted those tests). It seems that the pytest monkeypatching functionality cannot handle inherited methods. 
Will take a look at that tomorrow.

**Pull request closed without merging**
