### PR TITLE
ARROW-5142: Make all "conda" calls into "call conda" on Windows CI scripts

### PR DESCRIPTION
**Pull request by pitrou**
Simply calling "conda" can exit the script silently and hide some failures. @xhochy @kszucs

### CODE REVIEW

**Comment by pitrou** [comment]
@kszucs Is #3832 supposed to have fixed this?

**Comment by pitrou** [comment]
Answer: it doesn't. See https://ci.appveyor.com/project/pitrou/arrow/builds/23392731/job/2baew6u1wsfu7nlk#L4326
```
(wheel_test) C:\projects\arrow>python -c "import pyarrow"   || exit /B 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Miniconda36-x64\envs\wheel_test\lib\site-packages\pyarrow\__init__.py", line 47, in <module>
    from pyarrow.lib import cpu_count, set_cpu_count
ImportError: DLL load failed: The specified module could not be found.
```

**Comment by pitrou** [comment]
Issue still not fixed. @kszucs is there a JIRA tracking it? Otherwise i'll have to create one.
```
(wheel_test) C:\projects\arrow>python -c "import pyarrow"   || exit /B 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Miniconda36-x64\envs\wheel_test\lib\site-packages\pyarrow\__init__.py", line 47, in <module>
    from pyarrow.lib import cpu_count, set_cpu_count
ImportError: DLL load failed: The specified module could not be found.
```

**Comment by kszucs** [comment]
Not yet, We need to port the changes from the wheel PR.

**Comment by wesm** [comment]
Is there a JIRA for this?

**Comment by pitrou** [comment]
I don't think so.

**Comment by pitrou** [comment]
Actually, yes, there is :-)

**Comment by pitrou** [comment]
This is still failing after rebase:
https://ci.appveyor.com/project/pitrou/arrow/builds/24762352/job/bvca9u5j8folkgen

Does this mean our Windows wheels may be unusable? @nealrichardson

**Comment by wesm** [comment]
This certainly looks bad. I'm making ARROW-5142 a blocker for the release so we can investigate what is going on

**Comment by pitrou** [comment]
Rebased, wheel testing still [fails](https://ci.appveyor.com/project/pitrou/arrow/build/job/fy9oiatheknwi1us). However, it [succeeds](https://ci.appveyor.com/project/Ursa-Labs/crossbow/builds/25447052) in crossbow.

**Comment by wesm** [comment]
Ugh, very weird. I wonder what's different between the environments

**Comment by wesm** [comment]
Maybe we should only test the wheel in Crossbow, rather than both places

**Comment by pitrou** [comment]
That sounds reasonable to me, but we need to be notified when builds fail (daily?).

**Comment by pitrou** [comment]
Fixed in master.

**Pull request closed without merging**
