### PR TITLE
MINOR: [R] Remove writing_bindings from _pkgdown.yml

### PR DESCRIPTION
**Pull request by nealrichardson**
### Rationale for this change

Missed this in #41576

### Are these changes tested?

We should make sure.

### Are there any user-facing changes?

No.

### CODE REVIEW

**Comment by nealrichardson** [comment]
@github-actions crossbow-submit debian-docs

**Comment by nealrichardson** [comment]
@github-actions crossbow submit debian-docs

**Comment by nealrichardson** [comment]
I can't seem to trigger the docs build, but I confirmed locally that pkgdown builds.

**Comment by kou** [comment]
@github-actions crossbow submit preview-docs

**Pull request merged**
