### PR TITLE
ARROW-11375: [Rust] Fix deprecation warning in clippy

### PR DESCRIPTION
**Pull request by jorgecarleitao**
Master and all PRs are failing with a deprecation warning in clippy. This fixes it.

### CODE REVIEW

**Comment by alamb** [comment]
It seems like perhaps this is related to the release of criterion: https://crates.io/crates/criterion/0.3.4 (On Jan 24 2021)

**Comment by alamb** [comment]
The `Clippy` test still is failing; I found I had to run `cargo update` in my local arrow checkout to reproduce the failure.

**Review by alamb — COMMENTED** [review]
Thanks for handling this @jorgecarleitao - ❤️ 

I think there is still some clippy errors (I can see them locally too when I run `cargo update`) but this PR fixes some of them so merging it in seems like a good idea to me.

 I can take a crack at updating the error too later today if you don't get around to it.

**Comment by jorgecarleitao** [comment]
It should be fixed now. :)

**Comment by alamb** [comment]
Screen Shot 2021-01-25 at 9 28 56 AM
Looking clean and green 💚

**Review by alamb — APPROVED** [review]

**Review by nevi-me — APPROVED** [review]
we need not wait for Travis

**Comment by alamb** [comment]
I will file a JIRA ticket and merge this in

**Pull request closed without merging**
