### PR TITLE
ARROW-15294: [R] Remove arrow-without-arrow and other Solaris hacks

### PR DESCRIPTION
**Pull request by assignUser**
The r_witout_arrow ci should fail now (and should be removed before merging?)

### CODE REVIEW

**Comment by assignUser** [comment]
@jonkeane could you review this?

I have removed the `r-without-arrow` workflow, should we introduce a build with `LIBARROW_MINIMAL=true` instead, as this is not being tested anywhere afaik?

**Comment by assignUser** [comment]
Hm can't look at the failing crossbow logs, the azure failure has no failed tests but errors out anyway?

**Comment by jonkeane** [comment]
Getting to the crossbow build logs is difficult, but here are a few we might need to look into, though the ones that I've found manually are all the same as in our current nightlies, so this should be ok

**Review by jonkeane — APPROVED** [review]
Looks good, I'll merge once the CI finishes

**Pull request closed without merging**
