### PR TITLE
ARROW-5505: [R] namespace cleanup

### PR DESCRIPTION
**Pull request by nealrichardson**
This patch:

* renames `array()` to `arrow_array()` and `table()` to `arrow_table()` to avoid collision with base R functions of the same name. AFAICT there are no callers out there of those functions (i.e. I checked `sparklyr` and I'm not aware of anything else depending on `arrow` in any way).
* Prunes a trailing `-` from a test file name
* Moves `crayon` and `vctrs` from Imports to Suggests, in response to a `R CMD CHECK` note. `crayon` was only used in one place in the package and makes sense to be optional; `vctrs` is only used in tests.

### CODE REVIEW

**Comment by romainfrancois** [comment]
🤔 I understand the issue with masking the base package, but I'm not sure I like `arrow_array()` and `arrow_table()` for these factories, esp that other factories, e.g. `record_batch()` or `chunked_array()` presumably stay the same ?

`vctrs` used to be more important earlier in the development, specifically when `array()` took `...` and `vctrs::vec_c()` would collapse the `...` into one vector. So yeah it's totally fine to move it to Suggests, perhaps we can even get rid of it for the tests. 

We can totally just not use `crayon` at all.

**Comment by nealrichardson** [comment]
Fair point, I worried about that too. My preference would be to namespace everything ([like sparklyr](https://spark.rstudio.com/reference/)), e.g. `arrow_record_batch`, rather than masking the base functions, but that was a bigger, more disruptive change so I wanted to try this. Happy to try that out if you're open to it--I think it also raises some design questions about how we want the R developer interface to Arrow to look and feel, which is a good thing to think about anyway.

**Comment by romainfrancois** [comment]
Yeah, maybe it's worth have a broader discussion about the interface as a whole. These functions `array()`, `chunked_array()`, `table()`, and `record_batch()` are factories that make objects, maybe they should be e.g. : 

`new_Array()`, `new_ChunkedArray()`, `new_Table()`, `new_RecordBatch()`

Maybe the R6 classes should be made more user visible and then they would be e.g. 

`Array$new()`, `ChunkedArray$new()`, `Table$new()`, `RecordBatch$new()` ...

In any case, we should be consistent in what we do, and not just prefixing with `arrow_` for the cases where we do mask another function.

**Comment by nealrichardson** [comment]
Closing for now; we can continue the discussion on Jira/elsewhere and revisit.

**Pull request closed without merging**
