### PR TITLE
GH-36994: [Java][CI] Enable support for JDK21

### LINKED ISSUE #36994: [Java][CI] Enable JDK 21
### Describe the enhancement requested

Java 21 is the next long-term support (LTS) version after Java 17 and is scheduled to be released in September 2023. 

### Component(s)

Java

### LINKED ISSUE #37914: [Java][CI]: Enable support for JDK21
### Describe the enhancement requested

Enable last Java release JDK21 support

### Component(s)

Java

### PR DESCRIPTION
**Pull request by davisusanibar**
### Rationale for this change

Enable support for last Java JDK 21 version 

### What changes are included in this PR?

To be able to build Arrow Java using JDK21

### Are these changes tested?

For initial testing, Amazon Corretto was used, but at the end Temurin JDK21 docker image should be used.

### Are there any user-facing changes?

No

Closes: https://github.com/apache/arrow/issues/37914
* Closes: #37914
* Closes: #36994

### CODE REVIEW

**Comment by davisusanibar** [comment]
FYI Consider: https://adoptium.net/blog/2023/09/temurin21-delay/

**Comment by lidavidm** [comment]
It seems minus that flaky test, things work on Java 21?

**Comment by davisusanibar** [comment]
> It seems minus that flaky test, things work on Java 21?

I tested it locally without problems and also on my local PR at https://github.com/davisusanibar/arrow/pull/8. The current errors are caused by memory leaks.

Is it possible to rerun failed job tasks?

**Comment by lidavidm** [comment]
I kicked the Java jobs

**Pull request closed without merging**
