### PR TITLE
ARROW-3392: [Python] Support filters in disjunctive normal form in ParquetDataset

### PR DESCRIPTION
**Pull request by xhochy**

### CODE REVIEW

**Comment by xhochy** [comment]
cc @rgruener

**Comment by xhochy** [comment]
This hits https://github.com/pandas-dev/pandas/pull/21688 with Pandas 0.23.x

**Review by wesm — APPROVED** [review]
+1

**Comment by xhochy** [comment]
Feel free to merge. Once the full predicate pushdown support is merged, I will have to add a lot more documentation.

**Pull request closed without merging**
