### PR TITLE
ARROW-425: Add private API to get python Table from a C++ object

### PR DESCRIPTION
**Pull request by xhochy**

### CODE REVIEW

**Comment by xhochy** [comment]
Use case: https://github.com/blue-yonder/turbodbc/pull/26

**Comment by wesm** [comment]
cool! what's your experience been like using Boost::Python vs. Cython?

**Review by wesm — APPROVED** [review]
+1

**Comment by xhochy** [comment]
I mostly work in Cython, probably because I normally started from Python code that needs something native/performance. Boost::Python is rather nice if you start from C++ and want to expose something to Python. In the end, I'm happy the less I have to deal with any of both. Pure C++ and pure Python are still more comfortable than a mixing of them. Thus I'm quite excited that you only need 2 lines of code to transform a C++ Arrow Table to a Python one.

**Pull request closed without merging**
