### PR TITLE
ARROW-1529: [GLib] Use Xcode 8.3 on Travis CI

### PR DESCRIPTION
**Pull request by kou**

### CODE REVIEW

**Comment by kou** [comment]
I need more time because 1 hour is needed for 1 try...
I'll work on this tomorrow again.

**Comment by wesm** [comment]
I'll keep an eye on https://travis-ci.org/kou/arrow/jobs/274639892. I don't think this needs to block the 0.7.0 release candidate so I will proceed to make the source release whether or not this passes

**Comment by kou** [comment]
I agree with you.

**Comment by kou** [comment]
I upgraded Xcode then the failure is gone.

**Review by wesm — APPROVED** [review]
+1. We'll have to rebase master on the release branch once the vote passes

**Pull request closed without merging**
