### PR TITLE
ARROW-16828: [R][Packaging] Enable Brotli and BZ2 on MacOS and Windows

### PR DESCRIPTION
**Pull request by wjones127**
MacOS was missing Brotli and BZ2. Windows was missing BZ2. After this, MacOS and Windows will have all compressions shipped in binaries.

### CODE REVIEW

**Comment by wjones127** [comment]
@github-actions crossbow submit homebrew-r-autobrew

**Comment by wjones127** [comment]
@github-actions crossbow submit homebrew-r-autobrew

**Review by nealrichardson — APPROVED** [review]
Thanks! Let's remember to upstream these changes to @jeroen 's versions of these scripts before release (should be safe to add anytime).

**Comment by nealrichardson** [comment]
Probably should be PRs to rtools-packages and rtools-backports as well

**Pull request merged**
