### PR TITLE
ARROW-11479: [Rust] [Parquet] Add Method to get compressed size of columns from row group metadata

### PR DESCRIPTION
**Pull request by manojkarthick**
Add method `compressed_size()` to get compressed column data size in a row group. The JVM [parquet-mr](https://github.com/apache/parquet-mr) library provides a method to get the same [here](https://github.com/apache/parquet-mr/blob/0a4e3eea991f7588c9c5e056e9d7b32a76eed5da/parquet-hadoop/src/main/java/org/apache/parquet/hadoop/metadata/BlockMetaData.java#L114) . This would help in calculating the total compressed size alongside the uncompressed size of the Parquet file.

### CODE REVIEW

**Review by sunchao — APPROVED** [review]
LGTM

**Review by alamb — APPROVED** [review]
I wonder if it would be possible to add a test for this API (mostly so that someone doesn't delete it by accident thinking it isn't used)?

**Comment by manojkarthick** [comment]
> I wonder if it would be possible to add a test for this API (mostly so that someone doesn't delete it by accident thinking it isn't used)?

Thank you @alamb ! Could you provide any pointers on what kind of test would be relevant here? I thought of adding a test, but couldn't come up with one that is useful.

**Comment by alamb** [comment]
@manojkarthick How about something along the lines of https://github.com/apache/arrow/blob/8a134013494eb7b15004ea7bba8bca8a9562ffdd/rust/parquet/src/file/metadata.rs#L656

The test could create a  row group metadata with two columns and assert that `compressed_size()` returns the sum of the columns' size?

**Comment by alamb** [comment]
Thanks @manojkarthick !

It looks like there is a small linter failure now [link](https://github.com/apache/arrow/pull/9401/checks?check_run_id=1825802194):

```
error: redundant clone
   --> parquet/src/file/metadata.rs:757:68
    |
757 |         let row_group_meta = RowGroupMetaData::builder(schema_descr.clone())
    |                                                                    ^^^^^^^^ help: remove this
    |
    = note: `-D clippy::redundant-clone` implied by `-D warnings`
note: this value is dropped without further use
   --> parquet/src/file/metadata.rs:757:56
    |
757 |         let row_group_meta = RowGroupMetaData::builder(schema_descr.clone())
    |                                                        ^^^^^^^^^^^^
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#redundant_clone

error: aborting due to previous error

```

**Comment by alamb** [comment]
(you can run clippy locally via `cargo clippy --all-targets --workspace -- -D warnings -A clippy::redundant_field_names`) if you  want to run it the same as we run it in CI

**Comment by manojkarthick** [comment]
> (you can run clippy locally via `cargo clippy --all-targets --workspace -- -D warnings -A clippy::redundant_field_names`) if you want to run it the same as we run it in CI

Thanks @alamb ! I've fixed the clippy failure.

**Comment by alamb** [comment]
Thanks again @manojkarthick 👍

**Comment by manojkarthick** [comment]
Thanks a lot @alamb !

**Pull request closed without merging**
