### PR TITLE
GH-34496: [C++][Parquet] fix parquet unittest in `MakePages` when num_values = 0

### LINKED ISSUE #34496: [C++][Parquet] Parquet Unittest `RecordReaderStressTest` may segment fault
### Describe the bug, including details regarding any error messages, version, and platform.

In `RecordReaderStressTest.StressTest`.

```c++
  std::default_random_engine gen(seed1);
  // Generate random number of pages with random number of values per page.
  std::uniform_int_distribution<int> d(0, 2000);
  const int num_pages = d(gen);
  const int levels_per_page = d(gen);
```

If `num_pages == 0`, then, it will cause:

```c++
// Generates pages from randomly generated data
template <typename Type>
static inline int MakePages(...) {
  int num_levels = levels_per_page * num_pages; // -> to 0
  ...
    // Create repitition levels
  if (max_rep_level > 0) {
    rep_levels[0] = 0; // --> invalid memory visit
  }
``` 

This is introduced in https://github.com/apache/arrow/pull/14879

### Component(s)

C++, Parquet

### PR DESCRIPTION
**Pull request by mapleFU**
### Rationale for this change

https://github.com/apache/arrow/issues/34496

### What changes are included in this PR?

tiny change about num_values handling 0 values

### Are these changes tested?

no, because itself is testing

### Are there any user-facing changes?

no

* Closes: #34496

### CODE REVIEW

**Comment by mapleFU** [comment]
cc @emkornfield @wjones127

**Comment by mapleFU** [comment]
ping @emkornfield @wjones127

**Comment by emkornfield** [comment]
LGTM.  Need to setup merging again, unless someone else gets to it again.

**Comment by mapleFU** [comment]
So can you help merging this patch? I meet a crash when running ut, so write this fixing @emkornfield

**Comment by mapleFU** [comment]
So can you help merging this patch? I meet a crash when running ut, so write this fixing @emkornfield

**Comment by wgtmac** [comment]
I hit the same issue here. This fix looks good to me, should we merge it? @emkornfield @wjones127 @westonpace

**Review by westonpace — APPROVED** [review]
Thanks for catching and cleaning this up.

**Pull request merged**
