### PR TITLE
GH-15136: [Python][macOS] Use `@rpath` for libarrow_python.dylib

### LINKED ISSUE #15136: [Python] Python C++ libraries no longer in pyarrow/lib directory
### Describe the bug, including details regarding any error messages, version, and platform.

Prior to #14925, libraries such as `arrow_python.dylib` were installed in both `python/pyarrow` and `python/pyarrow/lib`. Afterward, they are only present in `python/pyarrow`, and when I build in place and run `import pyarrow` I get:

```
ImportError: dlopen(/Users/willjones/Documents/arrows/arrow/python/pyarrow/lib.cpython-310-darwin.so, 0x0002): Library not loaded: '/Users/willjones/Documents/arrows/arrow/python/pyarrow/lib/libarrow_python.1100.dylib'
```

It seems my dev environment relied on that `lib` directory and I suspect I am not alone.

### Component(s)

Python

### PR DESCRIPTION
**Pull request by kou**
* Closes: #15136

### CODE REVIEW

**Comment by kou** [comment]
@github-actions crossbow submit -g python

**Comment by kou** [comment]
@github-actions crossbow submit -g python

**Comment by kou** [comment]
@github-actions crossbow submit -g wheel

**Comment by kou** [comment]
@github-actions crossbow submit -g conda

**Comment by kou** [comment]
@wjones127 Could you confirm that this solves #15136 in your environment?

**Comment by wjones127** [comment]
Building off this branch, I can import pyarrow 👍 

Looks like it is using `@rpath`:
```
> otool pyarrow/lib.cpython-310-darwin.so -L
pyarrow/lib.cpython-310-darwin.so:
        @rpath/libarrow_python.dylib (compatibility version 0.0.0, current version 0.0.0)
        /Users/willjones/mambaforge/envs/arrow-dev/lib/libarrow.1100.dylib (compatibility version 1100.0.0, current version 1100.0.0)
        @rpath/libc++.1.dylib (compatibility version 1.0.0, current version 1.0.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1311.100.3)
```

**Review by wjones127 — APPROVED** [review]

**Comment by kou** [comment]
Thanks for confirming this.
I merge this.

**Pull request merged**
