### PR TITLE
ARROW-3509: [C++] Standardize on using Field in Type/Array

### PR DESCRIPTION
**Pull request by emkornfield**
I think there is potentially more consolidaion on the builders but this seems like a reasonable place to make the PR.

### CODE REVIEW

**Comment by bkietz** [comment]
@emkornfield could you rebase so GHA jobs are unskipped?

**Comment by emkornfield** [comment]
@bkietz done.

**Comment by wesm** [comment]
The arrow/compute changes are OK here. The rebase shouldn't be too complicated when I get there

**Comment by emkornfield** [comment]
Is it typical for GHA to be queued for hours?

**Comment by nealrichardson** [comment]
Not typical, but it's certainly the case today.

**Comment by wesm** [comment]
Perhaps someone ran a SQL query and determined that our builds are costing Microsoft a lot of money (only half joking)

**Comment by bkietz** [comment]
@emkornfield looks like you missed a (now deprecated) usage of `children() : arrow/json/test_common.h:108:57` https://github.com/apache/arrow/pull/7132/checks?check_run_id=667758585#step:6:765

**Comment by emkornfield** [comment]
@bkietz yeah, I just pushed what I hope will catch the rest.

**Review by bkietz — APPROVED** [review]
Thanks @emkornfield!
I'll merge when Appveyor completes

**Pull request closed without merging**
