### PR TITLE
ARROW-11608: [CI] Fix turbodbc nightly

### PR DESCRIPTION
**Pull request by xhochy**

### CODE REVIEW

**Comment by xhochy** [comment]
@github-actions crossbow submit test-conda-python-3.7-turbodbc-master

**Comment by xhochy** [comment]
@github-actions crossbow submit test-conda-python-3.7-turbodbc-master

**Comment by xhochy** [comment]
@github-actions crossbow submit test-conda-python-3.7-turbodbc-master

**Comment by xhochy** [comment]
@github-actions crossbow submit test-conda-python-3.7-turbodbc-master

**Comment by xhochy** [comment]
@github-actions crossbow submit test-conda-python-3.7-turbodbc-master

**Comment by xhochy** [comment]
@github-actions crossbow submit test-conda-python-3.7-turbodbc-*

**Comment by xhochy** [comment]
The failure in `Integration / AMD64 Conda Integration Test` should be unrelated. Thus this is ready for a merge.

**Review by kszucs — APPROVED** [review]
Thanks Uwe!

**Pull request closed without merging**
