### PR TITLE
ARROW-8473: [Rust] Untick "Statistics support"

### PR DESCRIPTION
**Pull request by k-stanislawek**
The statistics are not supported in parquet-rs. Search for "statistics" in src/column/writer.rs or reader.rs for confirmation.
https://issues.apache.org/jira/browse/ARROW-8473

### CODE REVIEW

**Comment by wesm** [comment]
Seems like it might be better to track features in JIRA?

**Comment by Pand9** [comment]
@wesm I'm just a user that noticed incorrect information. I think fixing it is higher priority than figuring out a complete solution.

As a user, I can provide feedback that Parquet's feature documentation (Rust and otherwise) needs some love. Some informations I found out later on, that would save me a lot of time, include:
- No "append mode" support in any client (even though format seems designed for it).
- Not sure about any kind of "index" support.
- No "bloom filter" in Rust.
- Version 1 vs Version 2 - what are differences? Looking at code, differences seem cosmetic.

**Comment by paddyhoran** [comment]
Thanks @Pand9,

We appreciate your feedback and I know it can be frustrating as a user to find lacking (or no) documentation.

Unfortunately, all the contributors on the Rust implementation are all volunteers working on this in our spare time.  After spending time working through these frustrations please consider opening JIRA's (this will help others to know where to start if they want to work on the issues you raised) to record what you found or opening further PR's to update documentation.

**Review by sunchao — APPROVED** [review]
LGTM. Yes statistics support is not there yet. We really haven't updated the list for a long time and since then new features such as bloom-filter, encryption, indexing, etc were added. We probably should update this soon.

**Pull request closed without merging**
