### PR TITLE
PARQUET-1519: [C++] Hide TypedColumnReader implementation behind virtual interfaces, remove use of "extern template class"

### PR DESCRIPTION
**Pull request by wesm**
This leaves the public API for reading columns unchanged. This avoids linking brittleness with "extern template class" and makes the ABI more stable, for whatever that's worth

If this is deemed uncontroversial (and I hope that it is) I'll do the same for the column writers in a separate patch

### CODE REVIEW

**Comment by wesm** [comment]
@majetideepak @xhochy for your review

**Comment by wesm** [comment]
@kszucs @xhochy the manylinux1 build is failing

```
Requirement already satisfied: six>=1.0.0 in /home/travis/build/apache/arrow/pyarrow-test-3.6/lib/python3.6/site-packages (from pyarrow==0.12.1.dev99+g81e419c) (1.12.0)
Requirement already satisfied: numpy>=1.14 in /home/travis/build/apache/arrow/pyarrow-test-3.6/lib/python3.6/site-packages (from pyarrow==0.12.1.dev99+g81e419c) (1.16.0)
Installing collected packages: pyarrow
Successfully installed pyarrow-0.12.1.dev99+g81e419c
+python -c 'import pyarrow; import tensorflow'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/travis/build/apache/arrow/pyarrow-test-3.6/lib/python3.6/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/home/travis/build/apache/arrow/pyarrow-test-3.6/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 88, in <module>
    from tensorflow.python import keras
  File "/home/travis/build/apache/arrow/pyarrow-test-3.6/lib/python3.6/site-packages/tensorflow/python/keras/__init__.py", line 29, in <module>
    from tensorflow.python.keras import datasets
  File "/home/travis/build/apache/arrow/pyarrow-test-3.6/lib/python3.6/site-packages/tensorflow/python/keras/datasets/__init__.py", line 25, in <module>
    from tensorflow.python.keras.datasets import imdb
  File "/home/travis/build/apache/arrow/pyarrow-test-3.6/lib/python3.6/site-packages/tensorflow/python/keras/datasets/imdb.py", line 25, in <module>
    from tensorflow.python.keras.preprocessing.sequence import _remove_long_seq
  File "/home/travis/build/apache/arrow/pyarrow-test-3.6/lib/python3.6/site-packages/tensorflow/python/keras/preprocessing/__init__.py", line 30, in <module>
    from tensorflow.python.keras.preprocessing import image
  File "/home/travis/build/apache/arrow/pyarrow-test-3.6/lib/python3.6/site-packages/tensorflow/python/keras/preprocessing/image.py", line 23, in <module>
    from keras_preprocessing import image
  File "/home/travis/build/apache/arrow/pyarrow-test-3.6/lib/python3.6/site-packages/keras_preprocessing/image/__init__.py", line 8, in <module>
    from .dataframe_iterator import DataFrameIterator
  File "/home/travis/build/apache/arrow/pyarrow-test-3.6/lib/python3.6/site-packages/keras_preprocessing/image/dataframe_iterator.py", line 11, in <module>
    from pandas.api.types import is_numeric_dtype
ModuleNotFoundError: No module named 'pandas'
```

**Comment by xhochy** [comment]
Tracking the manylinux1 failure in https://issues.apache.org/jira/browse/ARROW-4424

**Comment by majetideepak** [comment]
Since the external API is going to be the same, +1.
https://issues.apache.org/jira/browse/PARQUET-1519 talks about linking issues (inside parquet/encoding.h). Is there a link with more details that can be posted in the JIRA for future reference?
Thanks!

**Comment by wesm** [comment]
I wrote on the JIRA

**Pull request closed without merging**
