### PR TITLE
GH-43400: [C++] Ensure using bundled GoogleTest when we use bundled GoogleTest

### PR DESCRIPTION
**Pull request by kou**
### Rationale for this change

If we use bundled GoogleTest and system other dependencies such as Boost, our include path options may be:

* `-isystem /opt/homebrew/include` (for Boost)
* `-isystem build_dir/_deps/googletest-src/googletest` (for bundled GoogleTest)
* `-isystem build_dir/_deps/googletest-src/googlemock` (for bundled GoogleTest)

With this order, GoogleTest headers in `/opt/homebrew/include/` are used with bundled GoogleTest. It may cause link errors.

### What changes are included in this PR?

This change introduces a new CMake target
`arrow::GTest::gtest_headers` that has include paths for bundled GoogleTest. And it's always used as the first link library of all test program. With this change, our include path options are:

* `-isystem build_dir/_deps/googletest-src/googletest` (for bundled GoogleTest)
* `-isystem build_dir/_deps/googletest-src/googlemock` (for bundled GoogleTest)
* `-isystem /opt/homebrew/include` (for Boost)

With this order, we can always use our bundled GoogleTest.

`arrow::GTest::gtest_headers` is defined only when we use bundled GoogleTest. So this doesn't change the system GoogleTest case.

### Are these changes tested?

Yes.

### Are there any user-facing changes?

Yes.
* GitHub Issue: #43400

### CODE REVIEW

**Comment by kou** [comment]
@github-actions crossbow submit java-jars

**Comment by assignUser** [comment]
This is an issue I have seen before with other dependencies when bundled deps are used (e.g. due to version mismatch) but they are also installed on the system, this solution works for gtest but I usually recommend to either upgrade or remove the system dependency...

**Comment by kou** [comment]
> this solution works for gtest but I usually recommend to either upgrade or remove the system dependency...

My recommendation is "use system dependencies as much as possible" or "remove the system dependency".

BTW, can we merge this?

**Review by assignUser — APPROVED** [review]
I assume the special header target is necessary instead of just linking to gtest  first?

**Comment by kou** [comment]
Ah, are you suggesting the existing `brew uninstall googletest` approach?

**Comment by assignUser** [comment]
@kou ah no, my question was why you need to create `gtest_headers`, could you not also just link against the normal `gtest` target first? Or would that mess with the link order for gtest deps?

**Comment by kou** [comment]
> I assume the special header target is necessary instead of just linking to gtest first?

Right.
If a test executable needs `arrow_testing_shared`, the test executable needs to link to `arrow_testing_shared` and `GTest::gtest*` but GoogleTest header files must exist before `arrow_testing_shared` and other system dependencies such as `OpenSSL::*`. If we have the special header target, we can use `GTest::gtest_headers`, `OpenSSL::*`, `arrow_testing_shared` and `GTest::gtest` order.

**Comment by kou** [comment]
> Ah, are you suggesting the existing `brew uninstall googletest` approach?

Sorry. I wrote this comment before I saw https://github.com/apache/arrow/pull/43465#pullrequestreview-2206426207 .

**Pull request merged**
