### PR TITLE
ARROW-2852: [Rust] Make Array sync and send

### PR DESCRIPTION
**Pull request by liurenjie1024**
Mark array as Sync and Send would be useful for multithread processing. It's also safe since they have no interior mutability.

### CODE REVIEW

**Comment by liurenjie1024** [comment]
@andygrove @xhochy Could you please help to review this?

**Comment by xhochy** [comment]
@liurenjie1024 I'm not really comfortable in Rust. Maybe someone of the other people that previously reviewed Rust PR might give this a review. Then I would be happy to merge.

**Comment by kszucs** [comment]
Do You have tests for it?

**Comment by liurenjie1024** [comment]
@kszucs I add some test for it now.

**Comment by andygrove** [comment]
Hi @liurenjie1024 I have started reviewing this. I'd love to hear about your use case that is prompting this change so I can understand the motivation better.

**Comment by wesm** [comment]
@andygrove It looks like @liurenjie1024 is working on a time series analytic database in Rust: https://github.com/liurenjie1024/zeus

**Comment by liurenjie1024** [comment]
@wesm @andygrove  LOL. Yes I'm working on it and plan to use arrow as in memory data structures.

**Review by andygrove — APPROVED** [review]
This looks good to me. I started with Box then moved to Rc so moving to Arc seems like the next logical step. Thanks @liurenjie1024 for helping to push the Rust implementation forward!

**Comment by wesm** [comment]
Thanks! Merging. The CI failure is unrelated. We should rekindle the Cargo / Rust release discussion

**Pull request closed without merging**
