### PR TITLE
ARROW-5678: [R][Lint] Fix hadolint docker linting error

### PR DESCRIPTION
**Pull request by kszucs**

### CODE REVIEW

**Comment by wesm** [comment]
Are these the result of a new version of hadolint?

**Comment by fsaintjacques** [comment]
I think they are, but we've got the warning long ago of apt/apt-get. @kszucs, it's also complaining about pinning gem versions.

**Comment by kszucs** [comment]
The new release has shipped new rules, I've fixed this one: https://github.com/hadolint/hadolint/commit/56fd3e1eed0e418b3a72dc619fc4282951d425e7#diff-04c6e90faac2675aa89e2176d2eec7d8R187

And blacklisted `--no-install-recommends` one.

**Comment by wesm** [comment]
Do you want to disable the Ruby gem warning also for now?

**Comment by wesm** [comment]
Ignored

**Review by wesm — APPROVED** [review]
Passing Travis build here https://travis-ci.org/kszucs/arrow/builds/548783552

+1

**Pull request closed without merging**
