### PR TITLE
WIP: [Release] Verify release-15.0.1-rc0

### PR DESCRIPTION
**Pull request by raulcd**
PR to verify Release Candidate

### CODE REVIEW

**Comment by raulcd** [comment]
@github-actions crossbow submit  --group verify-rc-source --param release=15.0.1 --param rc=0

**Comment by raulcd** [comment]
Revision: 5ce6ff434c1e7daaa2d7f134349f3ce4c22683da

Submitted crossbow builds: [ursacomputing/crossbow @ release-15.0.1-rc0-0](https://github.com/ursacomputing/crossbow/branches/all?query=release-15.0.1-rc0-0)

|Task|Status|
|----|------|
|almalinux-8-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8019689740/job/21907991053)|
|almalinux-8-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8019690141/job/21907992802)|
|almalinux-9-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8019690215/job/21907993251)|
|almalinux-9-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/tree/release-15.0.1-rc0-0-github-almalinux-9-arm64)|
|amazon-linux-2023-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8019690266/job/21907993764)|
|amazon-linux-2023-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8019690411/job/21907994767)|
|centos-7-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/tree/release-15.0.1-rc0-0-github-centos-7-amd64)|
|centos-8-stream-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8019689990/job/21907991725)|
|centos-8-stream-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8019690541/job/21907995776)|
|centos-9-stream-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8019689573/job/21907990715)|
|centos-9-stream-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8019690566/job/21907996053)|
|conan-maximum|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8019690885/job/21907997073)|
|conan-minimum|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8019690359/job/21907994335)|
|debian-bookworm-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8019690375/job/21907994383)|
|debian-bookworm-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8019690941/job/21907997334)|
|debian-bullseye-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8019689939/job/21907991681)|
|debian-bullseye-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8019690146/job/21907993001)|
|debian-trixie-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8019690376/job/21907994627)|
|debian-trixie-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8019689902/job/21907991482)|
|java-jars|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8019690027/job/21907995234)|
|nuget|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8019689413/job/21907990210)|
|python-sdist|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8019689456/job/21907990405)|
|r-binary-packages|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8019689808/job/21907991338)|
|test-ubuntu-22.04-docs|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8019690894/job/21907997060)|
|ubuntu-focal-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8019689632/job/21907990785)|
|ubuntu-focal-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/tree/release-15.0.1-rc0-0-github-ubuntu-focal-arm64)|
|ubuntu-jammy-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8019689554/job/21907990608)|
|ubuntu-jammy-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8019689781/job/21907991169)|
|ubuntu-mantic-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/tree/release-15.0.1-rc0-0-github-ubuntu-mantic-amd64)|
|ubuntu-mantic-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8019690506/job/21907995519)|
|wheel-macos-big-sur-cp310-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/tree/release-15.0.1-rc0-0-github-wheel-macos-big-sur-cp310-arm64)|
|wheel-macos-big-sur-cp311-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8019690297/job/21907994184)|
|wheel-macos-big-sur-cp312-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8019690896/job/21907997287)|
|wheel-macos-big-sur-cp38-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8019690335/job/21907994305)|
|wheel-macos-big-sur-cp39-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8019690105/job/21907992724)|
|wheel-macos-catalina-cp310-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/tree/release-15.0.1-rc0-0-github-wheel-macos-catalina-cp310-amd64)|
|wheel-macos-catalina-cp311-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8019690373/job/21907994615)|
|wheel-macos-catalina-cp312-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8019689733/job/21907991087)|
|wheel-macos-catalina-cp38-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8019690415/job/21907994790)|
|wheel-macos-catalina-cp39-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8019690508/job/21907996459)|
|wheel-manylinux-2-28-cp310-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8019689385/job/21907990224)|
|wheel-manylinux-2-28-cp310-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/tree/release-15.0.1-rc0-0-github-wheel-manylinux-2-28-cp310-arm64)|
|wheel-manylinux-2-28-cp311-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8019690120/job/21907992571)|
|wheel-manylinux-2-28-cp311-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8019690516/job/21907995894)|
|wheel-manylinux-2-28-cp312-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8019690173/job/21907993171)|
|wheel-manylinux-2-28-cp312-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8019690143/job/21907992778)|
|wheel-manylinux-2-28-cp38-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8019690528/job/21907996211)|
|wheel-manylinux-2-28-cp38-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8019690022/job/21907992071)|
|wheel-manylinux-2-28-cp39-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8019690948/job/21907997281)|
|wheel-manylinux-2-28-cp39-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8019690567/job/21907996198)|
|wheel-manylinux-2014-cp310-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8019690329/job/21907994201)|
|wheel-manylinux-2014-cp310-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/tree/release-15.0.1-rc0-0-github-wheel-manylinux-2014-cp310-arm64)|
|wheel-manylinux-2014-cp311-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8019690774/job/21907996791)|
|wheel-manylinux-2014-cp311-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/tree/release-15.0.1-rc0-0-github-wheel-manylinux-2014-cp311-arm64)|
|wheel-manylinux-2014-cp312-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8019690802/job/21907996996)|
|wheel-manylinux-2014-cp312-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8019690639/job/21907996268)|
|wheel-manylinux-2014-cp38-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8019690659/job/21907996409)|
|wheel-manylinux-2014-cp38-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8019690420/job/21907994974)|
|wheel-manylinux-2014-cp39-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8019690153/job/21907992886)|
|wheel-manylinux-2014-cp39-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8019690114/job/21907992525)|
|wheel-windows-cp310-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8019689894/job/21907991697)|
|wheel-windows-cp311-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8019690979/job/21908031300)|
|wheel-windows-cp312-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8019690318/job/21907993890)|
|wheel-windows-cp38-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8019690084/job/21907992397)|
|wheel-windows-cp39-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8019689855/job/21907991355)|

**Comment by raulcd** [comment]
@github-actions crossbow submit  --group verify-rc-binaries --group verify-rc-wheels --param release=15.0.1 --param rc=0

**Comment by kou** [comment]
Ah, sorry. I should have used `apache-arrow-15.0.1` tag or `maint-15.0.1` branch to run `dev/release/05-binary-upload.sh`. (I used `main` instead.)

I'm re-running `dev/release/05-binary-upload.sh` on `apache-arrow-15.0.1` to fix verify-rc-binaries-apt-linux-amd64.

**Comment by kou** [comment]
Done. Re-run verify-rc-binaries-apt-linux-amd64.

**Comment by raulcd** [comment]
There seems to be a different error for Windows builds on `test_dateutil_tzinfo_to_string`:
```
         tz = dateutil.tz.gettz('Europe/Paris')
>       assert pa.lib.tzinfo_to_string(tz) == 'Europe/Paris'
E       AssertionError: assert 'Europe/Monaco' == 'Europe/Paris'
E         - Europe/Paris
E         + Europe/Monaco
```
@jorisvandenbossche @AlenkaF have you seen this error before?

**Comment by AlenkaF** [comment]
> There seems to be a different error for Windows builds on `test_dateutil_tzinfo_to_string`:
> 
> ```
>          tz = dateutil.tz.gettz('Europe/Paris')
> >       assert pa.lib.tzinfo_to_string(tz) == 'Europe/Paris'
> E       AssertionError: assert 'Europe/Monaco' == 'Europe/Paris'
> E         - Europe/Paris
> E         + Europe/Monaco
> ```
> 
> @jorisvandenbossche @AlenkaF have you seen this error before?

I haven't seen it before and also can't reproduce it on MacOS.

As mentioned on Zulip channel, there was a [new release of the dateutil](https://dateutil.readthedocs.io/en/latest/changelog.html#version-2-9-0-2024-02-29) package. The version of `python-dateutil`:

- on AppVeyor build is `2.8.2`:
https://ci.appveyor.com/project/ApacheSoftwareFoundation/arrow/builds/49256840?fullLog=true#L465
- on `verify-rc-binaries-wheels-windows` build is `2.9.0`
https://github.com/ursacomputing/crossbow/actions/runs/8103088008/job/22164107523#step:6:208

I do not see how the changes in the new dateutil version would affect the Windows builds though ...

**Comment by raulcd** [comment]
@ursabot please benchmark

**Comment by austin3dickey** [comment]
The benchmarks failed because they couldn't build the pyarrow wheel due to https://github.com/apache/arrow/issues/40386.

**Comment by raulcd** [comment]
Thanks @austin3dickey ! I am creating the 15.0.2 release which only contains 4 fixes at the moment, 3 of them are CI/build issues that won't affect performance.
I will run the benchmarks there.

**Pull request merged**
