### PR TITLE
ARROW-13628: [Rust] Activate IPC month_day_nano_interval integration test for rust

### PR DESCRIPTION
**Pull request by b41sh**
arrow-rs has added `MONTH_DAY_NANO` interval type in PR [#779](https://github.com/apache/arrow-rs/pull/779), we need to enable integration tests for it.

### CODE REVIEW

**Comment by kszucs** [comment]
@houqp the tests are failing

**Comment by alamb** [comment]
Rust PR has been merged https://github.com/apache/arrow/pull/11238

**Comment by alamb** [comment]
Thank you @pitrou

**Comment by b41sh** [comment]
Thanks for your help @pitrou @alamb

**Pull request closed without merging**
