### PR TITLE
ARROW-2536: [Rust] optimize capacity allocation for ListBuilder

### LINKED ISSUE #1983: Rust: ListBuilder::with_capacity should allocate 1 more element for offsets?
```
    /// Create a ListBuilder with the specified capacity
    pub fn with_capacity(n: usize) -> Self {
        let data = Builder::with_capacity(n);
        let mut offsets = Builder::with_capacity(n);
        offsets.push(0_i32);
        ListBuilder { data, offsets }
    }
```

When creating ListBuilder with_capacity shouldn't we allocate 1 more element for offsets because we are pushing 0 element there immediately? @andygrove

### PR DESCRIPTION
**Pull request by kanekv**
Supposed to fix #1983 @andygrove

### CODE REVIEW

**Comment by andygrove** [comment]
I filed a JIRA for this issue: https://issues.apache.org/jira/browse/ARROW-2536

@Kane-Sendgrid could you prefix the PR title with `ARROW-2536: [Rust]` please

**Comment by Kane-Sendgrid** [comment]
@andygrove done, thanks!

**Comment by andygrove** [comment]
@Kane-Sendgrid The build is failing because of a code formatting issue. Looks like the comment might be wrong format. We use `cargo fmt` to format code before committing and the build fails is formatting is off.

**Comment by Kane-Sendgrid** [comment]
@andygrove fixed

**Review by xhochy — APPROVED** [review]
+1, LGTM

**Comment by xhochy** [comment]
@Kane-Sendgrid do you have a JIRA id so I can assign this to you?

**Pull request closed without merging**
