### PR TITLE
GH-43506: [Java] Fix TestFragmentScanOptions result not match

### PR DESCRIPTION
**Pull request by jinchengchenghh**
### Rationale for this change
JNI test was not tested in CI. So the test failed but passed the CI.
The parseChar function should return char but return bool, a typo error.

### Are these changes tested?
Yes

### Are there any user-facing changes?
No

* GitHub Issue: apache/arrow#43506
* GitHub Issue: #43506

### CODE REVIEW

**Comment by vibhatha** [comment]
Rename to ->  GH-43506: [Java] Fix TestFragmentScanOptions result not match

**Comment by vibhatha** [comment]
@github-actions crossbow submit -g java

**Comment by vibhatha** [comment]
@jinchengchenghh I think still there is an inaccuracy in the test case. One CI is failing.

**Comment by vibhatha** [comment]
Still the CI is failing...

**Comment by vibhatha** [comment]
Still failing right...

**Comment by jinchengchenghh** [comment]
I will take a look today.

**Comment by jinchengchenghh** [comment]
Only gandiva failed now. @vibhatha

**Comment by vibhatha** [comment]
@jinchengchenghh it seems like there is a symbol not found issue again; https://github.com/apache/arrow/actions/runs/10363135011/job/28686234425?pr=43639#step:7:20512

**Comment by jinchengchenghh** [comment]
Do I need to disable this test in this PR? Or you will create a new PR to disable it?

**Comment by vibhatha** [comment]
@kou shall we disable this like the last time but note this as an issue and comment in the code?

**Comment by kou** [comment]
Yes but why is this happen again? Was #43503 not enough?

**Comment by vibhatha** [comment]
> Yes but why is this happen again? Was #43503 not enough?

The tests related to Gandiva passed when we merged that PR, but it failed due to the exact reason in this PR. We might have missed something as it seems.

**Comment by jinchengchenghh** [comment]
Yes, this test `ProjectorTest.testMakeProjectorParallel` is not disabled while `ProjectorTest.testMakeProjector` is disabled.
https://github.com/apache/arrow/blob/main/java/gandiva/src/test/java/org/apache/arrow/gandiva/evaluator/ProjectorTest.java#L152

Does it not occur before?

**Comment by vibhatha** [comment]
We should check that trace. We may have missed it.

**Comment by vibhatha** [comment]
@jinchengchenghh let's disable this too.

**Comment by jinchengchenghh** [comment]
Yes, I think we could disable the gandiva test in a separate PR. Can we merge this one first? @vibhatha

**Review by lidavidm — APPROVED** [review]

**Comment by lidavidm** [comment]
@github-actions crossbow submit -g java

**Comment by jinchengchenghh** [comment]
Can you help merge this one? @vibhatha Thanks!

**Comment by vibhatha** [comment]
@jinchengchenghh I don't have merge rights. @lidavidm will definitely merge this as it is already approved. LGTM as well.

**Comment by jinchengchenghh** [comment]
Ok. Thanks for your kindly review. @vibhatha

**Review by vibhatha — APPROVED** [review]

**Comment by vibhatha** [comment]
@jinchengchenghh did we file a new issue for the Gandiva failure?

**Comment by jinchengchenghh** [comment]
Maybe we can use the exists issue https://github.com/apache/arrow/issues/43576

**Comment by vibhatha** [comment]
Sure let's do that.

**Review by lidavidm — APPROVED** [review]

**Comment by lidavidm** [comment]
@vibhatha do we need to ping any Gandiva maintainers to figure out the failures?

**Comment by vibhatha** [comment]
@lidavidm I think so. And I think @kou also tried to fix this earlier.

**Comment by lidavidm** [comment]
ok, let me dig

**Comment by vibhatha** [comment]
Thanks @lidavidm, I am not well versed in this part of the project.

**Pull request merged**
