### PR TITLE
GH-36820: [C++] Remove a needless return in Acero ScanNode::AddScanTasks

### LINKED ISSUE #36820: [C++] Acero: ScanNode::AddScanTasks has unreached return value
### Describe the enhancement requested

```c++
      return Status::OK();
      // The "list fragments" task doesn't actually end until the fragments are
      // all scanned.  This allows us to enforce fragment readahead.
      return list_and_scan_done;
```

Seems this has two return values. I don't know the logic should return `list_and_scan_done` for blocking or just a `OK` here.

### Component(s)

C++

### PR DESCRIPTION
**Pull request by mapleFU**
### Rationale for this change

`ScanNode::AddScanTasks` has multiple return value. This patch remove the latter one.

### What changes are included in this PR?

Just remove some code.

### Are these changes tested?

no

### Are there any user-facing changes?

no

* Closes: #36820

### CODE REVIEW

**Comment by kou** [comment]
(I'm not sure the details of this code too.)

If we don't need to return `list_and_scan_done`, it seems that we can remove all `list_and_scan_done` related codes too.

**Comment by mapleFU** [comment]
Let me wait for weston's idea...Actually I'm not sure whether we need to return `OK()` or `list_and_scan_done`

**Comment by mapleFU** [comment]
@westonpace would you mind take a look? Just two line fix

**Review by westonpace — APPROVED** [review]
Thanks.  I changed the need for this future in https://github.com/apache/arrow/issues/32768 but it was very clumsy of me to leave this return statement here.  Sorry.

You could probably change this method to return void but the method will also hopefully be going away entirely as part of https://github.com/apache/arrow/pull/35889 so I'm fine if you want to stick with this minimal change.

**Comment by westonpace** [comment]
And yes, we should be able to remove `list_and_scan_done` entirely but it is not too important since this method is going away.

**Comment by mapleFU** [comment]
Close this issue and wait for https://github.com/apache/arrow/pull/35889 to be merged :-)

**Pull request closed without merging**
