### PR TITLE
ARROW-3248: [C++] Add "arrow" prefix to Arrow core unit tests, use PREFIX instead of file name for csv, io, ipc tests. Modular target cleanup

### PR DESCRIPTION
**Pull request by wesm**
I added a section to the cpp/README.md about the modular build targets.

### CODE REVIEW

**Comment by pitrou** [comment]
Shouldn't the CI scripts be updated to build the relevant targets? Or does plain "make" still build all enabled targets?

**Comment by wesm** [comment]
Yeah, a naked `make` still builds everything. I want to disable this and add an "all" target. That's https://issues.apache.org/jira/browse/ARROW-3184 so can do that in a separate patch

**Comment by wesm** [comment]
OK to merge this once the build looks good?

**Comment by wesm** [comment]
@TheNeuralBit @trxcllnt the JS jobs are failing with

```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for gulp@next
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'apache-arrow'
npm ERR! notarget 
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/travis/.npm/_logs/2018-12-10T22_33_26_272Z-debug.log
The command "$TRAVIS_BUILD_DIR/ci/travis_before_script_js.sh" failed and exited with 1 during .
```

**Comment by wesm** [comment]
Appveyor build https://ci.appveyor.com/project/wesm/arrow/builds/20910494.

Merging this. I take responsibility for any fallout from this change =)

**Comment by wesm** [comment]
I missed a small breakage in the protocol integration tests. I just pushed a fix in https://github.com/apache/arrow/pull/3153

**Pull request closed without merging**
