### PR TITLE
ARROW-4815: [Rust] [DataFusion] Add support for SQL wilcard operator

### PR DESCRIPTION
**Pull request by andygrove**

### CODE REVIEW

**Comment by andygrove** [comment]
@sinistersnare FYI

**Comment by andygrove** [comment]
@paddyhoran @nevi-me Any objection to me merging this one?

**Review by paddyhoran — APPROVED** [review]
LGTM

**Comment by kou** [comment]
@andygrove This commit on master failed Rust lint: https://github.com/apache/arrow/runs/537449095

```text
2020-03-26T19:06:49.5792511Z Diff in /arrow/rust/datafusion/src/sql/planner.rs at line 272:
2020-03-26T19:06:49.5793877Z                  Ok(Expr::Literal(ScalarValue::Utf8(s.clone())))
2020-03-26T19:06:49.5794168Z              }
2020-03-26T19:06:49.5794309Z  
2020-03-26T19:06:49.5795629Z -            ASTNode::SQLAliasedExpr(ref expr, ref alias) => {
2020-03-26T19:06:49.5796217Z -                Ok(Alias(Arc::new(self.sql_to_rex(&expr, schema)?), alias.to_owned()))
2020-03-26T19:06:49.5796537Z -            }
2020-03-26T19:06:49.5796703Z +            ASTNode::SQLAliasedExpr(ref expr, ref alias) => Ok(Alias(
2020-03-26T19:06:49.5796913Z +                Arc::new(self.sql_to_rex(&expr, schema)?),
2020-03-26T19:06:49.5797166Z +                alias.to_owned(),
2020-03-26T19:06:49.5797325Z +            )),
2020-03-26T19:06:49.5797459Z  
2020-03-26T19:06:49.5797599Z              ASTNode::SQLIdentifier(ref id) => {
2020-03-26T19:06:49.5797792Z                  match schema.fields().iter().position(|c| c.name().eq(id)) {```

Could you check this?

**Comment by paddyhoran** [comment]
A fix will be included in #6724

**Comment by kou** [comment]
OK!

**Pull request closed without merging**
