### PR TITLE
ARROW-13355: [R] ensure that sf is installed in our revdep job

### PR DESCRIPTION
**Pull request by jonkeane**

### CODE REVIEW

**Comment by jonkeane** [comment]
@github-actions crossbow submit revdep-r-check

**Comment by jonkeane** [comment]
@github-actions crossbow submit revdep-r-check

**Comment by jonkeane** [comment]
@github-actions crossbow submit revdep-r-check

**Comment by mont1985** [comment]
@#``

**Review by nealrichardson — APPROVED** [review]

**Pull request closed without merging**
