### PR TITLE
ARROW-4071: [Rust] Add rustfmt as a pre-commit hook

### PR DESCRIPTION
**Pull request by ntrinquier**

### CODE REVIEW

**Comment by ntrinquier** [comment]
Hum, I just saw the discussion on [this PR](https://github.com/apache/arrow/pull/3210#discussion_r242551709). I'll create the hook with `pre-commit`.

**Comment by paddyhoran** [comment]
Thanks @ntrinquier.  Sorry I should have left a link to that discussion on the Jira.

**Comment by kszucs** [comment]
Could You please use https://github.com/apache/arrow/blob/master/.pre-commit-config.yaml ?

**Review by kszucs — APPROVED** [review]
LGTM Thanks @ntrinquier!

**Pull request closed without merging**
