### PR TITLE
ARROW-6622 [R]: SubTreeFileSystem path error on Windows

### PR DESCRIPTION
**Pull request by romainfrancois**

### CODE REVIEW

**Comment by romainfrancois** [comment]
Should this also use `normalizePath()` every where a path is handed down the C++ layer ?

**Comment by nealrichardson** [comment]
I tried that and it was not great: https://github.com/apache/arrow/pull/5445

I'll tinker on this more today.

**Comment by pitrou** [comment]
This PR needn't be left open, right?

**Comment by nealrichardson** [comment]
Correct.

**Pull request closed without merging**
