### PR TITLE
ARROW-1326: [Python] Fix Sphinx Build in Travis CI, treat Sphinx warnings as errors

### PR DESCRIPTION
**Pull request by wesm**

### CODE REVIEW

**Review by xhochy — APPROVED** [review]
+1, LGTM merge once build is fixed.

**Comment by wesm** [comment]
Really strange error, I am not sure why a Sphinx build passed in Linux but failed on macOS: https://travis-ci.org/apache/arrow/jobs/260425194#L7860. Any ideas?

**Comment by wesm** [comment]
Triggering another build to see if it's transient

**Comment by wesm** [comment]
So apparently the problem is that `pyarrow.field` and `pyarrow.Field` are distinct symbols, but many OS X systems have case insensitive file systems. 

I inserted a workaround so that the docs do build warning-free on OS X, but I think this shows once more that we set up a Docker environment for building the website so that it's reproducible

I disabled the Sphinx build on macOS since I don't think we should be having to contend with this in our Travis CI builds

**Pull request closed without merging**
