### PR TITLE
ARROW-14894: [R] Integer overflow in write_parquet chunk size calculation

### PR DESCRIPTION
**Pull request by thisisnic**

### CODE REVIEW

**Comment by jonkeane** [comment]
This looks good to me and should work. We lose a bit of precision with floats, but this is a heuristic anyway, so that shouldn't be a big deal.

The only thing that might be nice is a test (which would be long running if we were to test it directly, of course). I wonder if it would make sense to pull [this code](https://github.com/apache/arrow/blob/6c236ca72b0bc96c18fbeb57ba36047a1d55aa62/r/R/parquet.R#L205-L222) out into a separate function that takes the dims as input and returns `chunk_size`. Then we could test the logic on arbitrarily large numbers without needing to generate the data itself. This is very much scope creep, so feel free to punt that to a separate ticket.

**Review by jonkeane — APPROVED** [review]

**Comment by romainfrancois** [comment]
I agree with @jonkeane about factoring out in a separate function and then test that function. 

@paleolimbot yeah indeed `$num_rows` gives an `int`: 

```cpp
// [[arrow::export]]
int Table__num_rows(const std::shared_ptr<arrow::Table>& x) { return x->num_rows(); }
```

As a short term, perhaps it could instead be: 

```cpp
// [[arrow::export]]
SEXP Table__num_rows(const std::shared_ptr<arrow::Table>& x) {
  auto out = x->num_rows();

  if (out > std::numeric_limits<int>::max()) {
    return Rf_ScalarReal(out);
  } else {
    return Rf_ScalarInteger(out);
  }
}
```

although that can probably be better supported by `cpp11` somehow.

**Comment by romainfrancois** [comment]
Maybe we can incubate something like this here: 

```cpp
struct r_vec_size{
  r_vec_size(R_xlen_t x) : value(x){}
  
  R_xlen_t value;
};

namespace cpp11 {
  inline SEXP as_sexp(r_vec_size size) {
    R_xlen_t x = size.value;
    if (x > std::numeric_limits<int>::max()) {
      return Rf_ScalarReal(x);
    } else {
      return Rf_ScalarInteger(x);
    }
  }
}
```

so that functions may return `r_vec_size`. There are probably more places where besides `Table$num_rows` where this would be useful.

**Comment by romainfrancois** [comment]
At the very least, if we were to just use `double` we should make some alias `using r_size = double` or something so that we can spot them. 

But otherwise, this was just trying to remain compatible with R: 

``` r
str(length(raw(2^30)))
#>  int 1073741824
str(length(raw(2^31)))
#>  num 2.15e+09
```

<sup>Created on 2021-12-03 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>

**Review by jonkeane — APPROVED** [review]
A few (minor) test additions

**Comment by thisisnic** [comment]
> At the very least, if we were to just use `double` we should make some alias `using r_size = double` or something so that we can spot them.
> 
> But otherwise, this was just trying to remain compatible with R:
> 
> ```r
> str(length(raw(2^30)))
> #>  int 1073741824
> str(length(raw(2^31)))
> #>  num 2.15e+09
> ```
> 
> Created on 2021-12-03 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)

Good call!  I have opened a separate JIRA to deal with this: https://issues.apache.org/jira/browse/ARROW-14989

**Pull request closed without merging**
