### PR TITLE
ARROW-16372: [Python] Use IPC over Parquet for tests where Parquet is unnecessary

### PR DESCRIPTION
**Pull request by amol-**
Because Parquet is optional and isn't supported on big-endian platforms yet.

### CODE REVIEW

**Review by raulcd — APPROVED** [review]
LGTM

**Comment by kou** [comment]
Can we remove Python on s390x test from `allow_failures`?

```diff
diff --git a/.travis.yml b/.travis.yml
index a2ce0af63b..f906ba8686 100644
--- a/.travis.yml
+++ b/.travis.yml
@@ -164,7 +164,6 @@ jobs:
 
   allow_failures:
     - name: "Java on s390x"
-    - name: "Python on s390x"
 
 before_install:
   - eval "$(python ci/detect-changes.py)"
```

**Comment by jorisvandenbossche** [comment]
Not that it matters for this particular test, but I think in general we should probably default to use IPC / feather format as the file format for such non-file-format-specific tests, as that is always guaranteed to roundtrip exactly and thus avoid potential issues with CSV parsing.

**Review by pitrou — APPROVED** [review]
+1 as well, though you might as well do the switch to IPC as @jorisvandenbossche suggested

**Comment by amol-** [comment]
> +1 as well, though you might as well do the switch to IPC as @jorisvandenbossche suggested

Switched to IPC.
In general, in tests, I tend to prefer human readable formats, when the test fail, they are easier to debug. That's why by default I used CSV.

**Pull request closed without merging**
