### PR TITLE
GH-38263 [C++]: Prefer to call string_view::data() instead of begin() where a char pointer is expected

### LINKED ISSUE #38263: [C++] Compilation errors with re2 2023.06.02 on windows
### Describe the bug, including details regarding any error messages, version, and platform.

Due to some build changes, it took a while for conda-forge to ship re2 2023.06.02, but now that we're [trying](https://github.com/conda-forge/arrow-cpp-feedstock/pull/1200) to compile arrow against that, we get some failures, though only on windows:
```
[221/463] Building CXX object src\arrow\CMakeFiles\arrow_shared.dir\compute\kernels\scalar_string_ascii.cc.obj
FAILED: src/arrow/CMakeFiles/arrow_shared.dir/compute/kernels/scalar_string_ascii.cc.obj 
C:\PROGRA~1\MICROS~2\2022\ENTERP~1\VC\Tools\MSVC\1429~1.301\bin\HostX64\x64\cl.exe  /nologo /TP -DABSL_CONSUME_DLL -DARROW_EXPORTING -DARROW_HAVE_RUNTIME_AVX2 -DARROW_HAVE_RUNTIME_AVX512 -DARROW_HAVE_RUNTIME_BMI2 -DARROW_HAVE_RUNTIME_SSE4_2 -DARROW_HDFS -DARROW_MIMALLOC -DARROW_S3_HAS_CRT -DARROW_WITH_BROTLI -DARROW_WITH_BZ2 -DARROW_WITH_LZ4 -DARROW_WITH_RE2 -DARROW_WITH_SNAPPY -DARROW_WITH_TIMING_TESTS -DARROW_WITH_UTF8PROC -DARROW_WITH_ZLIB -DARROW_WITH_ZSTD -DAWS_AUTH_USE_IMPORT_EXPORT -DAWS_CAL_USE_IMPORT_EXPORT -DAWS_CHECKSUMS_USE_IMPORT_EXPORT -DAWS_COMMON_USE_IMPORT_EXPORT -DAWS_COMPRESSION_USE_IMPORT_EXPORT -DAWS_CRT_CPP_USE_IMPORT_EXPORT -DAWS_EVENT_STREAM_USE_IMPORT_EXPORT -DAWS_HTTP_USE_IMPORT_EXPORT -DAWS_IO_USE_IMPORT_EXPORT -DAWS_MQTT_USE_IMPORT_EXPORT -DAWS_S3_USE_IMPORT_EXPORT -DAWS_SDKUTILS_USE_IMPORT_EXPORT -DAWS_SDK_VERSION_MAJOR=1 -DAWS_SDK_VERSION_MINOR=11 -DAWS_SDK_VERSION_PATCH=156 -DAWS_USE_IO_COMPLETION_PORTS -DBOOST_ALL_DYN_LINK -DBOOST_ALL_NO_LIB -DPROTOBUF_USE_DLLS -DURI_STATIC_BUILD -DUSE_IMPORT_EXPORT -DUSE_IMPORT_EXPORT=1 -DUSE_WINDOWS_DLL_SEMANTICS -D_CRT_SECURE_NO_WARNINGS -D_ENABLE_EXTENDED_ALIGNED_STORAGE -Darrow_shared_EXPORTS -I%SRC_DIR%\cpp\build\src -I%SRC_DIR%\cpp\src -I%SRC_DIR%\cpp\src\generated -external:I%SRC_DIR%\cpp\thirdparty\flatbuffers\include -external:I%SRC_DIR%\cpp\thirdparty\hadoop\include -external:ID:\bld\apache-arrow_1697190508068\_h_env\Library\include -external:I%SRC_DIR%\cpp\build\mimalloc_ep\src\mimalloc_ep\include\mimalloc-2.0 -external:W0 /DWIN32 /D_WINDOWS  /GR /EHsc /D_SILENCE_TR1_NAMESPACE_DEPRECATION_WARNING  /EHsc /wd5105 /bigobj /utf-8 /W3 /wd4800 /wd4996 /wd4065  /MD /O2 /Ob2 /DNDEBUG -std:c++17 /showIncludes /Fosrc\arrow\CMakeFiles\arrow_shared.dir\compute\kernels\scalar_string_ascii.cc.obj /Fdsrc\arrow\CMakeFiles\arrow_shared.dir\ /FS -c %SRC_DIR%\cpp\src\arrow\compute\kernels\scalar_string_ascii.cc
%SRC_DIR%\cpp\src\arrow\compute\kernels\scalar_string_ascii.cc(2093): error C2440: 'initializing': cannot convert from 'std::_String_view_iterator<_Traits>' to 'const char *'
        with
        [
            _Traits=std::char_traits<char>
        ]
%SRC_DIR%\cpp\src\arrow\compute\kernels\scalar_string_ascii.cc(2093): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
%SRC_DIR%\cpp\src\arrow\compute\kernels\scalar_string_ascii.cc(2066): note: while compiling class template member function 'arrow::Status arrow::compute::internal::`anonymous-namespace'::RegexSubstringReplacer<arrow::BinaryType>::ReplaceString(std::string_view,arrow::TypedBufferBuilder<uint8_t,void> *) const'
%SRC_DIR%\cpp\src\arrow\compute\kernels\scalar_string_ascii.cc(1970): note: see reference to function template instantiation 'arrow::Status arrow::compute::internal::`anonymous-namespace'::RegexSubstringReplacer<arrow::BinaryType>::ReplaceString(std::string_view,arrow::TypedBufferBuilder<uint8_t,void> *) const' being compiled
%SRC_DIR%\cpp\src\arrow\compute\kernels\scalar_string_ascii.cc(1957): note: see reference to class template instantiation 'arrow::compute::internal::`anonymous-namespace'::RegexSubstringReplacer<arrow::BinaryType>' being compiled
%SRC_DIR%\cpp\src\arrow\compute\kernels\scalar_string_ascii.cc(1955): note: while compiling class template member function 'arrow::Status arrow::compute::internal::`anonymous-namespace'::ReplaceSubstring<arrow::BinaryType,arrow::compute::internal::`anonymous-namespace'::RegexSubstringReplacer<arrow::BinaryType>>::Exec(arrow::compute::KernelContext *,const arrow::compute::ExecSpan &,arrow::compute::ExecResult *)'
%SRC_DIR%\cpp\src\arrow/compute/kernels/codegen_internal.h(1243): note: see reference to function template instantiation 'arrow::Status arrow::compute::internal::`anonymous-namespace'::ReplaceSubstring<arrow::BinaryType,arrow::compute::internal::`anonymous-namespace'::RegexSubstringReplacer<arrow::BinaryType>>::Exec(arrow::compute::KernelContext *,const arrow::compute::ExecSpan &,arrow::compute::ExecResult *)' being compiled
%SRC_DIR%\cpp\src\arrow/compute/kernels/codegen_internal.h(1240): note: see reference to class template instantiation 'arrow::compute::internal::`anonymous-namespace'::ReplaceSubstring<arrow::BinaryType,arrow::compute::internal::`anonymous-namespace'::RegexSubstringReplacer<arrow::BinaryType>>' being compiled
%SRC_DIR%\cpp\src\arrow\compute\kernels\scalar_string_ascii.cc(2158): note: see reference to function template instantiation 'arrow::compute::ArrayKernelExec (__cdecl *arrow::compute::internal::GenerateVarBinaryToVarBinary<arrow::compute::internal::`anonymous-namespace'::ReplaceSubstringRegex,>(arrow::compute::internal::detail::GetTypeId))(arrow::compute::KernelContext *,const arrow::compute::ExecSpan &,arrow::compute::ExecResult *)' being compiled
%SRC_DIR%\cpp\src\arrow\compute\kernels\scalar_string_ascii.cc(2104): error C2440: '=': cannot convert from 'std::_String_view_iterator<_Traits>' to 'const char *'
        with
        [
            _Traits=std::char_traits<char>
        ]
%SRC_DIR%\cpp\src\arrow\compute\kernels\scalar_string_ascii.cc(2104): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
```

Normally there shouldn't be big API changes in re2 (though they did change the SOVERSION per that release). This happens both with/without the unity build.

### Component(s)

C++, Packaging

### PR DESCRIPTION
**Pull request by felipecrv**
### Rationale for this change

The MSVC compiler doesn't seem to allow user code to assume `std::string_view::const_iterator` is `const char*`, so using only `re2::StringPiece` and preferring to call `.data()` instead of `.begin()` should make things more uniform across different compilers and STL implementations.

### What changes are included in this PR?

 - Using `re2::StringPiece` instead of `std::string_view` to interact with `re2`
 - Use `data()` instead of `begin()` where a `char*` is expected

### Are these changes tested?

Yes, by existing tests.
* Closes: #38263

### CODE REVIEW

**Comment by h-vetinari** [comment]
> Using `re2::StringPiece` instead of `std::string_view` to interact with `re2`

When compiling with C++17 (as we are doing in conda-forge) those are exactly the same type. Unless arrow enforces compilation with an earlier C++ standard somewhere, I don't see how that could be the issue.

**Comment by felipecrv** [comment]
> > Using `re2::StringPiece` instead of `std::string_view` to interact with `re2`
> 
> When compiling with C++17 (as we are doing in conda-forge) those are exactly the same type. Unless arrow enforces compilation with an earlier C++ standard somewhere, I don't see how that could be the issue.

See the second commit changing from `.begin()` to `.data()`.

**Comment by h-vetinari** [comment]
Thanks a lot! I've tested the changes here on top of 13.0.0 in https://github.com/conda-forge/arrow-cpp-feedstock/pull/1200, and it compiles and passes the tests 🥳

**Comment by h-vetinari** [comment]
FYI @jorisvandenbossche @raulcd 
This should IMO not miss the 14.0 release; risk should be minimal (for reference, I backported it all the way back to 10.x on the conda-forge feedstock without issues), and it's necessary to handle newer re2 versions like we are using in conda-forge now.

**Comment by raulcd** [comment]
> This should IMO not miss the 14.0 release

I agree, I'll add it to 14.0.0

**Review by pitrou — APPROVED** [review]

**Review by raulcd — APPROVED** [review]
Merging to add to 14.0.0

**Comment by raulcd** [comment]
@github-actions crossbow submit test-build-vcpkg-win

**Comment by felipecrv** [comment]
> @felipecrv I am validating but this seems to make the `test-build-vcpkg-win` build to fail on the maintenance branch:
> 
> ```
> D:/a/crossbow/crossbow/arrow/cpp/src/arrow/compute/kernels/scalar_string_ascii.cc(1970,1): error C2664: 'arrow::Status arrow::compute::internal::`anonymous-namespace'::RegexSubstringReplacer<arrow::LargeStringType>::ReplaceString(re2::StringPiece,arrow::TypedBufferBuilder<uint8_t,void> *) const': cannot convert argument 1 from 'std::string_view' to 're2::StringPiece' (compiling source file D:\a\crossbow\crossbow\arrow\cpp\build\src\arrow\CMakeFiles\arrow_shared.dir\Unity\unity_21_cxx.cxx) [D:\a\crossbow\crossbow\arrow\cpp\build\src\arrow\arrow_shared.vcxproj]
> D:/a/crossbow/crossbow/arrow/cpp/src/arrow/compute/kernels/scalar_string_ascii.cc(1970,1): message : No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called (compiling source file D:\a\crossbow\crossbow\arrow\cpp\build\src\arrow\CMakeFiles\arrow_shared.dir\Unity\unity_21_cxx.cxx) [D:\a\crossbow\crossbow\arrow\cpp\build\src\arrow\arrow_shared.vcxproj]
> D:/a/crossbow/crossbow/arrow/cpp/src/arrow/compute/kernels/scalar_string_ascii.cc(2066,10): message : see declaration of 'arrow::compute::internal::`anonymous-namespace'::RegexSubstringReplacer<arrow::LargeStringType>::ReplaceString' (compiling source file D:\a\crossbow\crossbow\arrow\cpp\build\src\arrow\CMakeFiles\arrow_shared.dir\Unity\unity_21_cxx.cxx) [D:\a\crossbow\crossbow\arrow\cpp\build\src\arrow\arrow_shared.vcxproj]
> D:/a/crossbow/crossbow/arrow/cpp/src/arrow/compute/kernels/scalar_string_ascii.cc(1962): message : while compiling class template member function 'arrow::Status arrow::compute::internal::`anonymous-namespace'::ReplaceSubstring<arrow::LargeStringType,arrow::compute::internal::`anonymous-namespace'::RegexSubstringReplacer<arrow::LargeStringType>>::Replace(arrow::compute::KernelContext *,const arrow::compute::ExecSpan &,const Replacer &,arrow::compute::ExecResult *)' [D:\a\crossbow\crossbow\arrow\cpp\build\src\arrow\arrow_shared.vcxproj]
>           with
>           [
>               Replacer=arrow::compute::internal::`anonymous-namespace'::RegexSubstringReplacer<arrow::LargeStringType>
>           ] (compiling source file D:\a\crossbow\crossbow\arrow\cpp\build\src\arrow\CMakeFiles\arrow_shared.dir\Unity\unity_21_cxx.cxx)
> D:/a/crossbow/crossbow/arrow/cpp/src/arrow/compute/kernels/scalar_string_ascii.cc(1958): message : see reference to function template instantiation 'arrow::Status arrow::compute::internal::`anonymous-namespace'::ReplaceSubstring<arrow::LargeStringType,arrow::compute::internal::`anonymous-namespace'::RegexSubstringReplacer<arrow::LargeStringType>>::Replace(arrow::compute::KernelContext *,const arrow::compute::ExecSpan &,const Replacer &,arrow::compute::ExecResult *)' being compiled [D:\a\crossbow\crossbow\arrow\cpp\build\src\arrow\arrow_shared.vcxproj]
>           with
>           [
>               Replacer=arrow::compute::internal::`anonymous-namespace'::RegexSubstringReplacer<arrow::LargeStringType>
>           ] (compiling source file D:\a\crossbow\crossbow\arrow\cpp\build\src\arrow\CMakeFiles\arrow_shared.dir\Unity\unity_21_cxx.cxx)
> D:\a\crossbow\crossbow\arrow\cpp\src\arrow/compute/kernels/codegen_internal.h(1249): message : see reference to class template instantiation 'arrow::compute::internal::`anonymous-namespace'::ReplaceSubstring<arrow::LargeStringType,arrow::compute::internal::`anonymous-namespace'::RegexSubstringReplacer<arrow::LargeStringType>>' being compiled (compiling source file D:\a\crossbow\crossbow\arrow\cpp\build\src\arrow\CMakeFiles\arrow_shared.dir\Unity\unity_21_cxx.cxx) [D:\a\crossbow\crossbow\arrow\cpp\build\src\arrow\arrow_shared.vcxproj]
> D:/a/crossbow/crossbow/arrow/cpp/src/arrow/compute/kernels/scalar_string_ascii.cc(2158): message : see reference to function template instantiation 'arrow::compute::ArrayKernelExec (__cdecl *arrow::compute::internal::GenerateVarBinaryToVarBinary<arrow::compute::internal::`anonymous-namespace'::ReplaceSubstringRegex,>(arrow::compute::internal::detail::GetTypeId))(arrow::compute::KernelContext *,const arrow::compute::ExecSpan &,arrow::compute::ExecResult *)' being compiled (compiling source file D:\a\crossbow\crossbow\arrow\cpp\build\src\arrow\CMakeFiles\arrow_shared.dir\Unity\unity_21_cxx.cxx) [D:\a\crossbow\crossbow\arrow\cpp\build\src\arrow\arrow_shared.vcxproj]
> ```
> 
> See: https://github.com/ursacomputing/crossbow/actions/runs/6533642461/job/17739225267

Alright. I will push a fix now.

**Pull request merged**
