### PR TITLE
ARROW-11162: [C++][Parquet] Fix invalid cast on Decimal256 Parquet data

### PR DESCRIPTION
**Pull request by pitrou**
The invalid cast would occur when a variable-length bytearray field would be
decoded as Decimal256 Arrow data.

Should fix the following issue:
- https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=28750

Found by OSS-Fuzz.

### CODE REVIEW

**Comment by pitrou** [comment]
@emkornfield It appears the code path this PR fixes (ByteArray -> Decimal256) isn't tested currently, though the ByteArray -> Decimal128 is tested.

**Comment by emkornfield** [comment]
LGTM.  I'll add a test for decimal256 (I thought this was covered by our some of the templated tests, I'll figure try to figure out why it wasn't).

**Comment by pitrou** [comment]
I've added a test, will merge if green.

**Comment by pitrou** [comment]
The AppVeyor failure is probably due to https://bugs.python.org/issue38091 - which is fixed in Python 3.9, but has not been backported.

**Comment by pitrou** [comment]
Travis-CI build: https://travis-ci.com/github/pitrou/arrow/builds/212858874

**Pull request closed without merging**
