### PR TITLE
ARROW-1325: [R] Bootstrapping R bindings subproject

### PR DESCRIPTION
**Pull request by Bernolt**
test CI (after rebasing master)

### CODE REVIEW

**Comment by wesm** [comment]
I wouldn't worry about the Plasma issue -- if you're getting it on master, please open a JIRA so that others can take a look

**Comment by pcmoritz** [comment]
Yeah, don't worry about the Plasma issue (but feel free to push your fix, we can see if that fixes it -- see also https://github.com/apache/arrow/pull/2207)

**Comment by Bernolt** [comment]
Ok. I think I can fix the CI/plasma issue.
I will remove the plasma changes from this PR, and work on a fix from #2207 .

**Comment by jameslamb** [comment]
@wesm @Bernolt I'm interesting in keeping an eye on the progress of R bindings for Arrow. Is this PR the official place where that development is happening? Or is it just one possible proposal? Can you recommend how I can best track the progress for R?

Thanks!

**Comment by jameslamb** [comment]
Awesome! Thank you so much for the quick and detailed response.

**Comment by romainfrancois** [comment]
as of soon, a chunk of my work time (~2days/week) will be dedicated to R/arrow work, so things should start moving soon.

**Comment by wesm** [comment]
Closing this PR since work is proceeding in the original one

**Pull request closed without merging**
