### PR TITLE
Bump Jackson to 2.9.6

### PR DESCRIPTION
**Pull request by Fokko**
Hi all,

Jackson is incompatible with upstream versions, therefore bump the Jackson version to a more recent one. I bumped into some issues with libraries that are using a more recent version of Jackson. This can be fixed by adding exclusions and then it works without any issues. So no breaking changes in the API's.

Cheers, Fokko

### CODE REVIEW

**Comment by jacques-n** [comment]
Since this can be managed by downstream consumers without a changes to Arrow, we should probably evaluate whether we want to make this change in Arrow. I know that Jackson changes have historically been problematic for consumption at Dremio and wonder whether that is true for other tools as well.

I wonder whether we should actually not be depending on Jackson in Arrow. It seems like it is only used a little bit and maybe we could use something more lightweight in the compile dependency and move JsonFileReader/Writer to tests (and jackson to a test dependency). I don't think people use those outside of tests. (Or move to a separate module that does depend on Jackson).

**Comment by wesm** [comment]
This is only used for integration testing AFAIK. Seems unnecessary to have to depend on this in production

**Comment by Fokko** [comment]
Jackson is a compile dependency, so it will ship with the version: https://mvnrepository.com/artifact/org.apache.arrow/arrow-vector/0.10.0

Also it is used throughout the code, not only in the test code: https://github.com/apache/arrow/search?q=jackson&unscoped_q=jackson

**Comment by wesm** [comment]
This was just upgraded to 2.9.8 today

**Comment by Fokko** [comment]
Cool, thanks!

**Pull request closed without merging**
