### PR TITLE
ARROW-1544: [JS] Export Vector types

### PR DESCRIPTION
**Pull request by trxcllnt**
Resolves https://issues.apache.org/jira/browse/ARROW-1544

### CODE REVIEW

**Comment by wesm** [comment]
Can you add "ARROW-1544:" to the PR title and rebase on apache/master? I force pushed the branch after the release vote passed

**Comment by trxcllnt** [comment]
@wesm done. I can also squash the commits if you prefer.

**Comment by wesm** [comment]
No problem. We have a merge tool (https://github.com/apache/arrow/blob/master/dev/merge_arrow_pr.py) that handles squashing and updating JIRA (it uses the PR title to do this)

**Review by wesm — APPROVED** [review]
+1, will merge this once the build runs

**Comment by wesm** [comment]
thanks @trxcllnt!

**Pull request closed without merging**
