### PR TITLE
MINOR: [Go] check nil buffer in SizeInBytes

### PR DESCRIPTION
**Pull request by Yifeng-Sigma**
### Rationale for this change

image

Saw a nil error. Unclear to me how this nil buffer got constructed, because when building the arrow data we seem to already check it. But we should do a nil check here anyway 

### What changes are included in this PR?

Added a nil check. 

### Are there any user-facing changes?

No.

### CODE REVIEW

**Comment by zeroshade** [comment]
Looks good to me, can you add a unit test for this?

**Comment by Yifeng-Sigma** [comment]
> Looks good to me, can you add a unit test for this?

I tried but didn't figure out a way to build with nil buffer. 
in NewData() we checked nil buffers. 
image

**Comment by zeroshade** [comment]
Creating an Array with no null values should produce something with a nil validity bitmap. Alternately you should be able to use `NewData` to create a Data object passing `[]*memory.Buffer{nil, buffer}` since it's valid to have a nil validity bitmap if there are no nulls. I'll see if i can put together a unit test that reproduces the original crash that I can add for you

**Comment by zeroshade** [comment]
@Yifeng-Sigma Adding the following to `data_test.go` will provide a test that should fail without this change and should succeed with this change:

image

**Comment by Yifeng-Sigma** [comment]
> @Yifeng-Sigma Adding the following to `data_test.go` will provide a test that should fail without this change and should succeed with this change:
> 
> 
> 
> image
> 
> 

Great, thanks! Can you add that in this PR?

**Comment by Yifeng-Sigma** [comment]
> @Yifeng-Sigma Adding the following to `data_test.go` will provide a test that should fail without this change and should succeed with this change:
> 
> image

Thanks! added to the PR.

**Review by zeroshade — APPROVED** [review]

**Pull request merged**
