### PR TITLE
ARROW-825: [Python] Rename pyarrow.from_pylist to pyarrow.array, test on tuples

### PR DESCRIPTION
**Pull request by wesm**
The idea is to make this function more semantically analogous to `numpy.array` -- convert to native data structure with optional explicit type.

### CODE REVIEW

**Comment by wesm** [comment]
Rebased

**Review by xhochy — COMMENTED** [review]
Now that this method has a much more general name, I would expect it to also be able to take NumPy Arrays and convert them in a fast path.

**Comment by wesm** [comment]
Agreed. Let's open a new JIRA for this? The existing NumPy import assumes the pandas memory model / null encoding, but here I think we would want to import as-is without any null assumptions

**Comment by wesm** [comment]
I created https://issues.apache.org/jira/browse/ARROW-838

**Comment by wesm** [comment]
+1

**Pull request closed without merging**
