### PR TITLE
ARROW-944: [Python] Compatibility with pandas < 0.19.0

### PR DESCRIPTION
**Pull request by jreback**
compat with pandas < 0.19.0

### CODE REVIEW

**Comment by julienledem** [comment]
thanks @jreback, could you update the title of your PR to add a quick summary?
something like: "ARROW-944: [Python] Compatibility with pandas < 0.19.0"
(this goes in the commit)
cc @xhochy

**Comment by wesm** [comment]
@jreback can you update the PR title? Thanks

**Comment by wesm** [comment]
ping

**Comment by jreback** [comment]
done

**Comment by jreback** [comment]
hmm I think I pushed to this branch accidently. going to close this one and do in #649

**Pull request closed without merging**
