### PR TITLE
ARROW-8077: [Python][Packaging] Add Windows Python 3.5 wheel build script

### PR DESCRIPTION
**Pull request by wesm**
This is my best guess of what will work once ARROW-8067 is fixed (this problem arose after 0.16.0 in https://github.com/apache/arrow/commit/c707d8b121172ecb1ab5ffa65e80cb8f846a83b1). @kszucs can you assist with the Crossbow setup? @pitrou may need your help fixing ARROW-8067

### CODE REVIEW

**Comment by kszucs** [comment]
Yep. I can submit the task manually or if you can take a look at and merge #6571 then the comment bot will be operational again.

**Comment by kszucs** [comment]
@github-actions --help

**Comment by kszucs** [comment]
@github-actions crossbow submit wheel-manylinux1-cp35m

**Comment by kszucs** [comment]
@github-actions crossbow submit wheel-win-cp35m

**Comment by kszucs** [comment]
@github-actions crossbow submit wheel-win-cp35m

**Comment by wesm** [comment]
Can we remove "Ursabot" from the help?

**Comment by wesm** [comment]
It's curious that this isn't impacted by https://issues.apache.org/jira/browse/ARROW-8067. Maybe I got that issue because of something fishy about my local environment?

**Comment by kszucs** [comment]
@github-actions crossbow submit wheel-win-cp35m

**Comment by kszucs** [comment]
> It's curious that this isn't impacted by https://issues.apache.org/jira/browse/ARROW-8067. Maybe I got that issue because of something fishy about my local environment?

It bothers me as well, I have not managed to clearly find the root cause. For example our appveyor toolchain build using conda is passing however it fails on gha also in conda.

**Comment by pitrou** [comment]
Where does it fail on GHA?

**Comment by kszucs** [comment]
The build was rightfully [complaining](https://github.com/apache/arrow/runs/505630213) about missing numpy, thought that numpy is in conda_env_cpp.yml

**Review by kszucs — APPROVED** [review]
The build is [passing](https://ci.appveyor.com/project/Ursa-Labs/crossbow/builds/31445169#L2652) and produces wheel with proper version number.

**Pull request closed without merging**
