### PR TITLE
PARQUET-1369: Disregard column sort order if statistics max/min are equal

### PR DESCRIPTION
**Pull request by rgruener**
I need to still fix this PR up a little but I have now moved it from the old parquet-cpp repo

### CODE REVIEW

**Comment by rgruener** [comment]
@majetideepak This is ready for review again

**Comment by xhochy** [comment]
The build fails under windows, probably due to min and max being somewhere defined. You would either have to change the orders of the includes or define NOMINMAX somewhere.

**Comment by wesm** [comment]
`arrow/util/windows_compatibility.h` has to be included before including the STL headers

**Comment by wesm** [comment]
Pushed a fix to the unit test that should make things compile on Windows

**Pull request closed without merging**
