### PR TITLE
ARROW-6045: [C++] Add benchmark for double and float encoding/decoding, as well as NaN encoding

### PR DESCRIPTION
**Pull request by itamarst**
Was testing report that NaN encoding was slow. Couldn't reproduce it, but may as well have the benchmark.

### CODE REVIEW

**Comment by wesm** [comment]
I probably fixed this in https://github.com/apache/arrow/commit/250e97c70f497581bca412dfd2a654a1f9736064#diff-7fea663f71cf7f71bdda3fd6bd21727d

**Comment by itamarst** [comment]
The original report was, I believe, against the old parquet-cpp repo, so I figured it might have been fixed here.

**Comment by pitrou** [comment]
@fsaintjacques

**Comment by emkornfield** [comment]
@itamarst, generally we ask that a corresponding JIRA be opened and the PRs are title as PARQUET-XXX: [C++] description.

**Comment by itamarst** [comment]
Will do later this week.

**Comment by itamarst** [comment]
@emkornfield done!

**Comment by wesm** [comment]
I would have expected the performance problem to occur when writing whole files because of the statistics vectorization between 0.13 and 0.14.

**Review by wesm — APPROVED** [review]
+1. I ran clang-format

**Comment by wesm** [comment]
Sadly the performance got worse from 0.13.0 to 0.14.1. I opened

https://issues.apache.org/jira/browse/ARROW-6051

**Pull request closed without merging**
