### PR TITLE
ARROW-629: [JS] Add unit test suite

### PR DESCRIPTION
**Pull request by TheNeuralBit**
I created a basic unit test suite that tests reading an arrow file generated by the c++ side of the integration tests.
Currently the tests only work in node, so we can access the local filesystem, but we should be able to find a way to execute the tests in browsers using karma.

### CODE REVIEW

**Review by xhochy — APPROVED** [review]
+1, this looks nice. Although I dislike adding the file, it's fine for me for the beginning (seeing that you already made a JIRA about this)

**Comment by wesm** [comment]
Note this patch is included in the other PR

**Comment by xhochy** [comment]
Already noted. Reviewing those now ;)

**Comment by wesm** [comment]
@TheNeuralBit can you close? thanks

**Pull request closed without merging**
