### PR TITLE
GH-37470: [Python][Parquet] Add missing arguments to `ParquetFileWriteOptions`

### LINKED ISSUE #37470: [Python][Parquet] `write_page_index` to be set for Datasets
### Describe the bug, including details regarding any error messages, version, and platform.

```python
>>> pyarrow.dataset.ParquetFileFormat().make_write_options(write_page_index=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pyarrow/_dataset_parquet.pyx", line 182, in pyarrow._dataset_parquet.ParquetFileFormat.make_write_options
  File "pyarrow/_dataset_parquet.pyx", line 540, in pyarrow._dataset_parquet.ParquetFileWriteOptions.update
TypeError: unexpected parquet write option: write_page_index
```

### Component(s)

Python

### PR DESCRIPTION
**Pull request by judahrand**
### Rationale for this change

I think this may have been missed when this feature was added.

### Are there any user-facing changes?

* Closes: #37470

### CODE REVIEW

**Review by mapleFU — COMMENTED** [review]
Would you mind add a test for `write_page_index`? Since we need to ensure page index would be written.

Besides, disable statistics for column can force only write offset-index, maybe we can just test them

**Comment by judahrand** [comment]
> Would you mind add a test for `write_page_index`? Since we need to ensure page index would be written.

I've added a basic test for this.

**Comment by mapleFU** [comment]
Great! I'll take a careful round later. By the way we can disable statistics to just disable Column Index but write offset index. Maybe this could be add to doc later.

**Comment by judahrand** [comment]
> Great! I'll take a careful round later. By the way we can disable statistics to just disable Column Index but write offset index. Maybe this could be add to doc later.

Are you saying `write_statistics=False, wrtie_page_index=True` will write the OffsetIndex but not the ColumnIndex? If that's the case then I'd absolutely agree the docs should be updated as currently they suggest that `write_statistics` is ignored if `write_page_index=True`! But this should probably be separate as the docs will need updating in `pyarrow.parquet` too?

**Comment by judahrand** [comment]
> > Great! I'll take a careful round later. By the way we can disable statistics to just disable Column Index but write offset index. Maybe this could be add to doc later.
> 
> Are you saying `write_statistics=False, wrtie_page_index=True` will write the OffsetIndex but not the ColumnIndex? If that's the case then I'd absolutely agree the docs should be updated as currently they suggest that `write_statistics` is ignored if `write_page_index=True`! But this should probably be a separate PR as the docs will need updating in `pyarrow.parquet` too?

That is indeed what you were saying as the test shows! That behaviour strikes me as quite unintuitive!

**Review by mapleFU — COMMENTED** [review]
The logic is ok here, however, I think we should export the flag to `parquet/core.py`, and from  that to `_dataset_parquet.pyx`. You can take a look at your another patch ( https://github.com/apache/arrow/pull/37665/ ). Since just a `_dataset_parquet` config is hard to use for users.

**Comment by mapleFU** [comment]
> That is indeed what you were saying as the test shows! That behaviour strikes me as quite unintuitive!

Cause I'm the author of that behavior lol

When disable collect statistics, currently it would be hard to collect the `ColumnIndex`, because `ColumnIndex` relies on `Statistics`.

Also, by the way, by default, if column index is enabled, the page header statistics will not be written. (Since spec says if column index exists, page header is not tent to be written)

**Comment by judahrand** [comment]
> When disable collect statistics, currently it would be hard to collect the `ColumnIndex`, because `ColumnIndex` relies on `Statistics`.

Yeah, that makes sense! Would be good to clarify in the docs - will see if I get to it in another PR. 

> Also, by the way, by default, if column index is enabled, the page header statistics will not be written. (Since spec says if column index exists, page header is not tent to be written)

Yeah, what gets written and what doesn't is quite confusing. In fact the spec doesn't techincally say that the page-level statistics when writing the ColumnIndex but that it isn't recommended (one might want both in order to support old readers).
https://github.com/apache/parquet-format/blob/master/PageIndex.md#technical-approach

It's probably sensible default behaviour but it'd be nice to force being able to write both.

**Comment by judahrand** [comment]
> The logic is ok here, however, I think we should export the flag to `parquet/core.py`, and from that to `_dataset_parquet.pyx`. You can take a look at your another patch ( #37665 ). Since just a `_dataset_parquet` config is hard to use for users.

The flags are already there! They were just never added to the `ParquetFileWriteOptions`:
https://github.com/apache/arrow/blob/e56726c161df1d588f2f6197dbdd0c0011f14855/python/pyarrow/parquet/core.py#L976

**Review by mapleFU — APPROVED** [review]
Sorry for late reply. Finally I got this. User can write the data with these options in ParquetWriter python sdk, but cannot use them with `ParquetFileWriteOptions`.

This is LGTM.

@jorisvandenbossche @AlenkaF Would you mind take a look

**Review by AlenkaF — APPROVED** [review]
LGTM 👍

**Comment by AlenkaF** [comment]
One thought: would it be worth adding docstrings for `ParquetFileWriteOptions` and adding examples of use to the [Python user guide](https://arrow.apache.org/docs/dev/python/dataset.html)? As a separate issue?

**Comment by mapleFU** [comment]
Any updates? Should we rerun `continuous-integration/appveyor/pr` and checkin if it's a unrelated flacky test?

**Comment by AlenkaF** [comment]
> Any updates? Should we rerun `continuous-integration/appveyor/pr` and checkin if it's a unrelated flacky test?

The failing AppVeyor test would be fixed with rebasing the branch (https://github.com/apache/arrow/issues/37555).

It would be good to see if something can be done regarding the documentation ([see](https://github.com/apache/arrow/pull/37469#issuecomment-1721611686)) before merging.

**Comment by judahrand** [comment]
> Any updates? Should we rerun `continuous-integration/appveyor/pr` and checkin if it's a unrelated flacky test?

Yes, please - if it doesn't pass on a second run I'll look into it today.

**Comment by judahrand** [comment]
> > Any updates? Should we rerun `continuous-integration/appveyor/pr` and checkin if it's a unrelated flacky test?
> 
> The failing AppVeyor test would be fixed with rebasing the branch (#37555).

Thanks, I've done this now.

> It would be good to see if something can be done regarding the documentation ([see](https://github.com/apache/arrow/pull/37469#issuecomment-1721611686)) before merging.

I can try to make time to get to this but it feels like a pretty independent issue - especially as the `WriteOptions` classes don't even appear in the Python docs: https://arrow.apache.org/docs/python/api/dataset.html#classes. It feels like it would make more sense to add documentation for IPC, CSV, ORC, and Parquet FileWriteOptions all in one PR?

**Comment by AlenkaF** [comment]
> I can try to make time to get to this but it feels like a pretty independent issue - especially as the `WriteOptions` classes don't even appear in the Python docs: https://arrow.apache.org/docs/python/api/dataset.html#classes. It feels like it would make more sense to add documentation for IPC, CSV, ORC, and Parquet FileWriteOptions all in one PR?

Agree totally, it deserves a special issue for sure! What you propose sounds great, thank you!
It would be enough for now just to open a separate issue and link it from here, so we do not forget.

**Comment by judahrand** [comment]
> Agree totally, it deserves a special issue for sure! What you propose sounds great, thank you! It would be enough for now just to open a separate issue and link it from here, so we do not forget.

#37800

**Comment by mapleFU** [comment]
All test passed now, can we try to checkin this patch? :-)

**Comment by AlenkaF** [comment]
Great, will merge 👍

**Pull request merged**
