### PR TITLE
ARROW-5737: [Crossbow] Use Python version version 2.7 in the gandiva tasks

### PR DESCRIPTION
**Pull request by praveenbingo**
- Use 2.7 version of python in the manylinux crossbow gandiva build.

### CODE REVIEW

**Comment by praveenbingo** [comment]
@ursabot crossbow package -g gandiva

**Comment by praveenbingo** [comment]
@ursabot crossbow package -g gandiva

Triggering another build. Looks like the other build failed with permission issues(not sure whats happening there).

**Comment by kszucs** [comment]
@ursabot crossbow package -g gandiva

**Review by pitrou — APPROVED** [review]
LGTM. Need to check that CI and packaging builds succeed.

**Comment by kszucs** [comment]
Both tasks are passing, one just couldn't upload the artifacts, sadly that occasionally occurs with travis.

**Comment by kszucs** [comment]
Cancelled the travis tasks, the changes are unrelated.

**Review by kszucs — APPROVED** [review]
Thanks @praveenbingo!

**Pull request closed without merging**
