### PR TITLE
ARROW-5697: [GLib] Use system pkg-config in c_glib/Dockerfile to correctly find system libraries such as libglib

### PR DESCRIPTION
**Pull request by wesm**
The conda-provided pkg-config was being used

### CODE REVIEW

**Comment by wesm** [comment]
@kou or @shiro615 can you assist?

**Comment by kou** [comment]
Sure.
I'll take a look this.

**Comment by fsaintjacques** [comment]
@kou note that I added the path in PKG_CONFIG_PATH because conda's pkg-config is getting picked up.

Is glib installed twice? `-I/usr/lib/include/glib-2.0 -I/usr/lib/lib/x86_64-linux-gnu/glib-2.0/include`

**Comment by kou** [comment]
I couldn't try this yet but GLib installs its headers to two locations. `/usr/include/glib-2.0` is for platform independent headers. `/usr/lib/x86_64-linux-gnu/glib-2.0/include` is for platform dependent headers. For example, they depend on `long` size on the system.

**Comment by kou** [comment]
@ursabot crossbow test docker-c_glib

**Comment by kou** [comment]
I've fixed this.
This problem is caused by `pkg-config` provided by Conda. (`PATH=/opt/conda/bin:$PATH` in `cpp/Dockerfile`)
We should use system `pkg-config` to use system libraries such as GLib.

**Comment by wesm** [comment]
Sounds good. Thank you for fixing

**Review by kou — APPROVED** [review]
+1
CI is green. I'll merge this.

**Pull request closed without merging**
