### PR TITLE
ARROW-2828: [JS] Refactor Data, Vectors, Visitor, Typings, build, tests, dependencies

### PR DESCRIPTION
**Pull request by trxcllnt**
It's the big one; The Great ArrowJS Refactor of 2018. Thanks for bearing with me through yet another huge PR. [Check out this sweet gif](https://user-images.githubusercontent.com/178183/50551046-19a94d00-0c30-11e9-80ed-74b9290e8c49.gif) of all the new features in action. With streaming getting to a good place, we've already started working on demos/integrations with other projects like [uber/deck.gl](https://github.com/Pessimistress/deck.gl/tree/a5940e20cb1659a44cba7839082b0803a997a12f/test/apps/arrow) :tada:

### The JIRAs

In addition to everything I detail below, this PR closes the following JIRAs:

* [ARROW-2828](https://issues.apache.org/jira/browse/ARROW-2828): Refactor Vector Data classes
* [ARROW-2839](https://issues.apache.org/jira/browse/ARROW-2839): Support whatwg/streams in IPC reader/writer
* [ARROW-2235](https://issues.apache.org/jira/browse/ARROW-2235): Add tests for IPC messages split across multiple buffers
* [ARROW-3337](https://issues.apache.org/jira/browse/ARROW-3337): IPC writer doesn't serialize the dictionary of nested Vectors
* [ARROW-3689](https://issues.apache.org/jira/browse/ARROW-3689): Upgrade to TS 3.1
* [ARROW-3560](https://issues.apache.org/jira/browse/ARROW-3560): Remove @std/esm
* [ARROW-3561](https://issues.apache.org/jira/browse/ARROW-3561): Update ts-jest
* [ARROW-2778](https://issues.apache.org/jira/browse/ARROW-2778): Add Utf8Vector.from
* [ARROW-2766](https://issues.apache.org/jira/browse/ARROW-2766): Add ability to construct a Table from a list of Arrays/TypedArrays

### The stats

The gulp scripts have been updated to parallelize as much as possible. These are the numbers from my Intel Core i7-8700K CPU @ 3.70GHz × 12 running Ubuntu 18.04 and node v11.6.0:

```sh
$ time npm run build
[22:11:04] Finished 'build' after 39 s

real	0m40.341s
user	4m55.428s
sys	0m5.559s
```
```sh
$ npm run test:coverage
=============================== Coverage summary ===============================
Statements   : 90.45% ( 4321/4777 )
Branches     : 76.7% ( 1570/2047 )
Functions    : 84.62% ( 1106/1307 )
Lines        : 91.5% ( 3777/4128 )
================================================================================

Test Suites: 21 passed, 21 total
Tests:       5644 passed, 5644 total
Snapshots:   0 total
Time:        16.023s
```

### The fixes

* `Vector#indexOf(value)` works for all DataTypes
* `Vector#set(i, value)` now works for all DataTypes
* Reading from node streams is now fully zero-copy
* The IPC writers now serialize dictionaries of nested Vectors correctly (ARROW-3337)
* DictionaryBatches marked as `isDelta` now correctly updates the dictionaries for all Vectors that point to that dictionary, even if they were created before the delta batch arrived
* A few `arrow2csv` fixes:
  * Ignore `stdin` if it's a TTY
  * Now read all the Arrow formats from `stdin`
  * Always show the `help` text when we don't understand the input
  * Proper backpressure support to play nicely with other Unix utilities like `head` and `less`
* [Fixes an unfiled bug](https://github.com/trxcllnt/arrow/commit/070ec9809a9f5822d62268252d0570366ec40883) we encountered last week where JS would throw an error creating RowProxies for a Table or Struct with duplicate column names

### The upgrades

* New zero-copy Message/RecordBatchReaders!
  * [`RecordBatchReader.from()`](https://github.com/trxcllnt/arrow/blob/b58e29bc83675583238bbb94fba2f3ebf8f1e4aa/js/test/unit/ipc/reader/from-inference-tests.ts#L37) will peek at the underlying bytes, and return the correct implementation based on whether the data is an Arrow File, Stream, or JSON
  * [`RecordBatchFileReader`](https://github.com/trxcllnt/arrow/blob/b58e29bc83675583238bbb94fba2f3ebf8f1e4aa/js/test/unit/ipc/reader/file-reader-tests.ts#L74) now supports random-access seek, enabling more efficient web-worker/multi-process workflows
  * [`RecordBatchStreamReader`](https://github.com/trxcllnt/arrow/blob/b58e29bc83675583238bbb94fba2f3ebf8f1e4aa/js/test/unit/ipc/reader/streams-dom-tests.ts#L119) can now read multiple tables from the same underlying socket
  * `MessageReader` now [guarantees/enforces](https://github.com/trxcllnt/arrow/blob/b58e29bc83675583238bbb94fba2f3ebf8f1e4aa/js/src/ipc/message.ts#L126) message body byte alignment (this one even surfaced bugs in [node core](https://github.com/nodejs/node/issues/24817) and the [DOM streams polyfill](https://github.com/MattiasBuelens/web-streams-polyfill/issues/3))
* New RecordBatchWriters
  * Adds RecordBatchJSONWriter, RecordBatchFileWriter and RecordBatchStreamWriter
  * Adds static `RecordBatchWriter.writeAll()` method to easily write a Table or stream of RecordBatches
  * Both sync and async flushes based on the WritableSink
* Full integration with platform I/O primitives
  * We can still synchronously read JSON, Buffers, `Iterable<Buffer>`, or `AsyncIterable<Buffer>`
  * In node, we can now read from any [`ReadableStream`](https://nodejs.org/docs/latest/api/stream.html#stream_class_stream_readable), [`fs.FileHandle`](https://nodejs.org/docs/latest/api/fs.html#fs_class_filehandle)
  * In the browser, we can read from any [`ReadableStream` or `ReadableByteStream`](https://developer.mozilla.org/en-US/docs/Web/API/ReadableStream), or the [`Response`](https://developer.mozilla.org/en-US/docs/Web/API/Response) returned from the `fetch()` API. (Wrapping the [FileReader](https://developer.mozilla.org/en-US/docs/Web/API/FileReader) is still todo)
  * We also [accept Promises](https://github.com/Pessimistress/deck.gl/blob/a5940e20cb1659a44cba7839082b0803a997a12f/test/apps/arrow/loader.js#L20) of any of the above
  * New convenience methods for integrating with node or DOM streams
    * [`throughNode()`](https://github.com/trxcllnt/arrow/blob/b58e29bc83675583238bbb94fba2f3ebf8f1e4aa/js/test/unit/ipc/reader/streams-node-tests.ts#L54)/[`throughDOM()`](https://github.com/trxcllnt/arrow/blob/b58e29bc83675583238bbb94fba2f3ebf8f1e4aa/js/test/unit/ipc/reader/streams-dom-tests.ts#L50)
    * [`toReadableNodeStream()`](https://github.com/trxcllnt/arrow/blob/b58e29bc83675583238bbb94fba2f3ebf8f1e4aa/js/test/unit/ipc/reader/streams-node-tests.ts#L69)/[`toReadableDOMStream()`](https://github.com/trxcllnt/arrow/blob/b58e29bc83675583238bbb94fba2f3ebf8f1e4aa/js/test/unit/ipc/reader/streams-dom-tests.ts#L65)
    * [`pipe()`](https://github.com/trxcllnt/arrow/blob/b58e29bc83675583238bbb94fba2f3ebf8f1e4aa/js/test/unit/ipc/writer/streams-node-tests.ts#L91)/[`pipeTo()`/`pipeThrough()`](https://github.com/trxcllnt/arrow/blob/b58e29bc83675583238bbb94fba2f3ebf8f1e4aa/js/test/unit/ipc/writer/streams-dom-tests.ts#L92)
* Generic type parameters inherited from `DataType` now flow recursively
  ```js
  const table = Table.from<{ str: Utf8, i32: Int32, bools: List<Bool> }>(data);
  table.get(0); // will be of type { str: string, i32: number, bools: BoolVector }
  ```
* New simplified [`Data` class](https://github.com/trxcllnt/arrow/blob/b58e29bc83675583238bbb94fba2f3ebf8f1e4aa/js/src/data.ts)
* New simplified, faster `Visitor` class with support for optional, more narrow [`visitT` implementations](https://github.com/trxcllnt/arrow/blob/b58e29bc83675583238bbb94fba2f3ebf8f1e4aa/js/src/visitor.ts#L181)
  * New specialized Visitor implementations to enable runtime reflection (e.g. dynamically lookup the Vector constructor for a given DataType)
* New abstract `Chunked` base class for the applicative (concat) operation
  * public `chunkedInst.chunks` field is the list of inner chunks
* New `Column` class extends `Chunked`, combines `Field` with the chunks (provides access to the field `name` from the Schema)
* `RecordBatch#concat(...batchesOrTables)` now returns a Table
* Table now extends `Chunked`, so it inherits:
  * `Table#slice(from, to)`
  * `Table#concat(...batchesOrTables)`
  * `Table#getChildAt(i)` exists, alias of `getColumnAt(i)`
* `Table#getColumn[At]()` returns a Column

### The breaking changes

* All the old IPC functions are gone, but the new APIs will live for much longer
* `Table#batches` is now `Table#chunks`, which it inherits from `Chunked` (maybe controversial, open to aliasing)
* `Table#batchesUnion` is now just... the Table instance itself (also maybe controversial, open to aliasing)
* `DataType#TType` is now `DataType#typeId` -- it should have always been this, was a typo. Easy to alias if necessary.
* The complicated View classes are now gone, logic centralized as specialized [`Visitors`](https://github.com/trxcllnt/arrow/tree/b58e29bc83675583238bbb94fba2f3ebf8f1e4aa/js/src/visitor)

### The tests

* **Tests no longer rely on any C++ or Java generated integration files**
* Integration tests have been moved into `bin/integration.js`, and they finish much quicker
* The tsconfig files have been tweaked to speed up test run time and improve the async debugging experience
* A streaming `RecordBatchJSONWriter` has been implemented so we can easily debug and validate written output
  * The JSON results are also tested against the corresponding binary representation, similar to the integration tests
* A [suite of test-data helpers](https://github.com/trxcllnt/arrow/blob/d9970bb9a6a9d80bbe07b321dc6389bccf1b0835/js/test/generate-test-data.ts) have been added to auto-generate data for validation at runtime
  * They produce the underlying Arrow VectorData buffers, as well as the expected plain-JS-value representation [for verification](https://github.com/trxcllnt/arrow/blob/d9970bb9a6a9d80bbe07b321dc6389bccf1b0835/js/test/unit/generated-data-tests.ts#L23)
  * This allows us to test all possible type configuration combinations, e.g. [all types Dictionary-encode](https://github.com/trxcllnt/arrow/blob/d9970bb9a6a9d80bbe07b321dc6389bccf1b0835/js/test/data/tables.ts#L61), all types serialize when nested, etc.
* A [suite of IO test helpers](https://github.com/trxcllnt/arrow/blob/d9970bb9a6a9d80bbe07b321dc6389bccf1b0835/js/test/unit/ipc/helpers.ts#L36) has been added
  * We use [`memfs`](https://www.npmjs.com/package/memfs) to mock the file system, which contributes to test performance improvements
  * This enables us to [easily test](https://github.com/trxcllnt/arrow/blob/d9970bb9a6a9d80bbe07b321dc6389bccf1b0835/js/test/unit/ipc/reader/file-reader-tests.ts#L38) all the flavors of io primitives across node and browser environments
* A vscode debugging launch configuration has been added to ease the process of contributing more tests (and because I've been asked for mine so often)

### The build

* Faster
* Node 11+ (needs `Symbol.asyncIterator` enabled)
* Closure-compiler upgrades and build enhancements mean we can auto-generate the externs file during compilation, rather than maintaining it by hand

### Misc

* Added `arrow2csv` to `js/bin/arrow2csv`, so anybody with the JS project dependencies installed can easily view a CSV-ish thing (`cat foo.arrow | js/bin/arrow2csv.js`)

### Todos

* Docs/Recipes/Examples
* Highlight/write more tools (like `arrow2csv`)
* Flesh out the RecordBatchWriters a bit more
* Gather feedback on the new RecordBatchReader APIs

### CODE REVIEW

**Comment by xhochy** [comment]
@trxcllnt This seems to include some unwanted commits. Can you rebase on latest master?

**Comment by trxcllnt** [comment]
@xhochy I've tried doing `git rebase apache/master`, but each time it rebases all the way back to the initial commit, then fails with a merge conflict on the `README.md` file. I'm happy to give it another shot if you have any tips (also available in slack).

**Comment by xhochy** [comment]
@trxcllnt Also had a look at this and I don't know what's going wrong here. Really puzzled.

**Comment by wesm** [comment]
I can look at fixing this tomorrow. How much do you care about maintaining the commit history?

**Comment by wesm** [comment]
The problem is that this patch started before the Parquet monorepo merge. Something about the merged repo history confuses rebase when the base commit is before the merge

**Comment by wesm** [comment]
Done. Please `git reset --hard` to that commit

**Comment by trxcllnt** [comment]
Thanks @wesm, I pulled and it all looks good. We can do feedback in followup PRs or discussions on the mailing list. Let me know if I can help point out where things are, or if you have any questions about what's going on.

The [`generated-data-tests`](https://github.com/trxcllnt/arrow/blob/js-data-refactor/js/test/unit/generated-data-tests.ts#L23) are a great place to start. In addition to [comprehensive tests](https://github.com/trxcllnt/arrow/blob/js-data-refactor/js/test/unit/ipc/reader/stream-reader-tests.ts#L50) across all the kinds of I/O primitives we want to support, I've tried to add as many real-world scenarios as possible (like [reading](https://github.com/trxcllnt/arrow/blob/js-data-refactor/js/test/unit/ipc/reader/streams-node-tests.ts#L116) and [writing](https://github.com/trxcllnt/arrow/blob/js-data-refactor/js/test/unit/ipc/writer/streams-node-tests.ts#L233) multiple tables to the same stream), which come from use cases at Graphistry. If you're curious about how the I/O tests work, check out [`ipc/helpers.ts`](https://github.com/trxcllnt/arrow/blob/js-data-refactor/js/test/unit/ipc/helpers.ts). That's helper functions to generate and validate each I/O primitive.

Here's a checklist to build and test locally:
* install/update to node v11.x ([`nvm install node`](https://github.com/creationix/nvm) will update to the latest)
* `$ cd arrow/js && rm -rf node_modules && npm install` to ensure libraries are up to date
* `$ npx gulp` will clean, build, and test everything

While there are always things to improve, I feel good this is ready to merge. I've been updating the Graphistry codebase to use the new APIs with no issues, and I've [started work](https://github.com/trxcllnt/fastify-arrow) ([tweet](https://twitter.com/inlineptx/status/1081535471044354048)) on libraries to integrate with other tools in the node ecosystem.

**Comment by TheNeuralBit** [comment]
Thanks for this Paul!
I've just been going through some smoke tests for now and everything looks good to me so far. I ran the benchmarks and noticed some changes. I posted the output from a run on master and a run on the refactor branch [here](https://gist.github.com/TheNeuralBit/9824ca1c0cfa016144fec96564e9d6ae).

Some notable changes (master -> refactor):
Accessing numeric vector by index - (49.81 ms -> 81.31 ms)
Accessing dictionary-encoded utf8 vector by index - (2758.32 ms -> 824.92 ms) :+1: 
Iterating over dictionary-encoded utf8 vector - (3152 ms -> 583.7 ms) :+1: 
slice toArray numeric vector - (1.34 ms -> 1.1 ms) :+1: 
slice toArray dictionary-encoded utf8 vector - (3147.78 ms -> 659.42 ms) :+1: 
DataFrame countBy dictionary-encoded utf8 vector - (9.95 ms -> 17.24 ms)
DataFrame filter-scan dictionary-encoded utf8 vector - (25.62ms -> 31.9ms)

Interestingly there seems to be a huge improvement in anything that decodes utf8 data. Is that because we're [using Buffer.fromString to decode utf8](https://github.com/apache/arrow/pull/3290/files#diff-8070df59d1295d866e11228d0ef6cea5R25) in node now?

There are some minor regressions elsewhere, but nothing to be too concerned about. Might be worth trying to tackle in some follow-up PRs though.

**Comment by wesm** [comment]
@TheNeuralBit if you could let me know when you're +1 on merging this, I can go ahead. I am swamped this week so don't want to hold this up, and I will do my best to leave some comments when I can for post-merge follow up work

**Comment by trxcllnt** [comment]
> @TheNeuralBit: Interestingly there seems to be a huge improvement in anything that decodes utf8 data. Is that because we're using Buffer.fromString to decode utf8 in node now?

Yep, node's [Buffer](https://github.com/nodejs/node/blob/728505acd5452c6682e9756bc0bd8d31df5c764c/lib/buffer.js#L645) is [implemented](https://github.com/nodejs/node/blob/ad10cc57ee5303761d6b35b1c6c68f16b60a9f99/src/node_buffer.cc#L1073) in C++, so I try to use that if available. Theoretically browsers should be able to do the something similar [to node with the TextEncoder](https://github.com/nodejs/node/blob/ad10cc57ee5303761d6b35b1c6c68f16b60a9f99/src/node_buffer.cc#L1037), but I haven't validated it yet.

For the chunked-random-access tests, I was expecting to take a bit of a hit, since the binary-search in [`ChunkedVector#search()`](https://github.com/apache/arrow/blob/6bcaad6acb3db97c90a7d26a42c87db5cc06299b/js/src/vector/chunked.ts#L171) isn't inlined anymore and incurs a few more hash lookups + a function call.

But before we make that change, I was thinking we could probably see a boost by making our search a bit more intelligent too. If we pick the starting chunk as the search index divided by the average chunk length (discarding the shortest and longest), then instead of starting at 0 every time and almost guaranteeing `log(n)` lookup,  we'd often find the chunk on the first few iterations.

There's also probably a bit of a hit due to the vector method rebinding [starting here](https://github.com/apache/arrow/blob/6bcaad6acb3db97c90a7d26a42c87db5cc06299b/js/src/vector/index.ts#L131), as well as the [getters for each buffer](https://github.com/apache/arrow/blob/6bcaad6acb3db97c90a7d26a42c87db5cc06299b/js/src/vector/base.ts#L62) being pass-throughs back to the Vector's `Data` instance, instead of copying them onto the Vector on startup.

I tried to bind them as closely to the Vector instance as possible (at the bottom of `src/vector/index.ts`, where I bind again on vector initialization), but we may have to go further and update the Visitors that need to be _super_ fast (like the [GetVisitor](https://github.com/apache/arrow/blob/6bcaad6acb3db97c90a7d26a42c87db5cc06299b/js/src/visitor/get.ts#L42)) to operate directly on Data instances instead of Vectors. I think I made sure the Visitor typings would allow that, but we'll just have to update the implementations.

DictionaryVectors are going to be a bit trickier. When we see a DictionaryBatch with the `isDelta` flag set, there may exist DictionaryVectors who need to be told about the new concatenated `dictionary` values (for example, someone may update the indices, or concat two DictionaryVectors together). Even trickier, Vectors at different levels in the Schema tree may reference the same dictionary, which means we can't just scan the children of the RecordBatch or Table to know which ones to update (or serialize, which was the source of bug [ARROW-3337](https://issues.apache.org/jira/browse/ARROW-3337)).

But since the `Dictionary` DataType only exists once per dictionary id, and the Vector hierarchy matches the Schema Field hierarchy, the solution I came up with was to store both the `dictionary` value DataTypes (Utf8, etc.) _and_ dictionary-encoded Fields (along with their `Dictionary` wrapper pseudo-DataTypes) [in the Schema](https://github.com/apache/arrow/blob/6bcaad6acb3db97c90a7d26a42c87db5cc06299b/js/src/schema.ts#L34), and elevate the `dictionary` values reference to [hang off the `Dictionary` wrapper DataType](https://github.com/apache/arrow/blob/6bcaad6acb3db97c90a7d26a42c87db5cc06299b/js/src/type.ts#L473).

When we're reading or writing, we keep track of a the singleton `dictionary` values DataType, to ensure it's always [set as the `T` in a `Dictionary<T>`](https://github.com/apache/arrow/blob/6bcaad6acb3db97c90a7d26a42c87db5cc06299b/js/src/ipc/metadata/message.ts#L353) for each new dictionary-encoded Field. As we read each new or `isDelta` DictionaryBatch, load (or load-and-concat) the `dictionary` values Vector, [assigning it to each of the `Dictionary` wrapper instances](https://github.com/apache/arrow/blob/6bcaad6acb3db97c90a7d26a42c87db5cc06299b/js/src/ipc/reader.ts#L358) of each dictionary-encoded Field.

**Comment by trxcllnt** [comment]
@TheNeuralBit I did a pass last night on performance -- less binding, fewer getters, stuff like that. Here's the results I'm seeing now:

```
                                  test name |   master (ops/sec) |  branch (ops/sec) | % change   |
Table.from                                  |             914.00 |            624.00 |  -31.73% ❌ |
readBatches                                 |           1,113.00 |            623.00 |  -44.03% ❌ |
lat.get(idx)                                |           19.16.00 |             19.22 |    0.31% ➖ |
lng.get(idx)                                |           19.24.00 |             19.05 |   -0.99% ➖ |
origin.get(idx)                             |               0.50 |              1.12 |  124.00% ✔️ |
destination.get(idx)                        |               0.52 |              1.07 |  105.77% ✔️ |
lat[Symbol.iterator]()                      |              16.69 |             16.14 |   -3.30% ➖ |
lng[Symbol.iterator]()                      |              16.72 |             17.10 |    2.27% ✔️ |
origin[Symbol.iterator]()                   |               0.51 |              1.11 |  117.65% ✔️ |
destination[Symbol.iterator]()              |               0.53 |              1.04 |   96.23% ✔️ |
lat.slice().toArray()                       |           1,381.00 |          1,520.00 |   10.07% ✔️ |
lng.slice().toArray()                       |           1,568.00 |          1,426.00 |   -9.06% ➖ |
origin.slice().toArray()                    |               0.49 |              1.12 |  128.57% ✔️ |
destination.slice().toArray()               |               0.48 |              1.10 |  129.17% ✔️ |
lat.slice()                                 |          27,965.00 |         48,678.00 |   74.07% ✔️ |
lng.slice()                                 |          29,425.00 |         42,739.00 |   45.25% ✔️ |
origin.slice()                              |           5,092.00 |         41,802.00 |  720.93% ✔️ |
destination.slice()                         |           4,814.00 |         48,367.00 |  904.72% ✔️ |
DF CountBy [origin]                         |             153.00 |            285.00 |   86.27% ✔️ |
DF CountBy [destination]                    |             153.00 |            262.00 |   71.24% ✔️ |
DF Filter-Scan-Count [lat > 0]              |              30.00 |             35.19 |   17.30% ✔️ |
DF Filter-Scan-Count [lng > 0]              |              29.81 |             34.75 |   16.57% ✔️ |
DF Filter-Scan-Count [origin === "Seattle"] |              59.68 |             56.08 |   -6.03% ➖ |
DF Count [lat > 0]                          |             121.00 |            180.00 |   48.76% ✔️ |
DF Count [lng > 0]                          |             119.00 |            182.00 |   52.94% ✔️ |
DF Count [origin === "Seattle"]             |               0.55 |              1.26 |  129.09% ✔️ |
```

**Comment by TheNeuralBit** [comment]
Wow! Thanks for tackling the perf stuff - Those numbers look great! I re-ran the benchmarks on my laptop and found a similar improvement :tada: 

I don't think I'll have time for a thorough code review in the near future, but I've ran your branch through various tests to make sure the features I'm interested in still work, so I'm :+1: on this.

LGTM @wesm

**Comment by trxcllnt** [comment]
And after the latest pass, I got the numbers for the two parse tests back up:
```
                      test name |   master (ops/sec) |  branch (ops/sec) | % change   |
Table.from                      |             914.00 |             1,549 |   64.61% ✔️ |
readBatches                     |           1,113.00 |             1,671 |   50.13% ✔️ |
```

**Comment by wesm** [comment]
Merging this. Can you resolve all the relevant JIRAs? Thank you!

**Comment by trxcllnt** [comment]
thanks @wesm!

**Pull request closed without merging**
