### PR TITLE
ARROW-587: Add fix version to PR merge tool 

### PR DESCRIPTION
**Pull request by wesm**
This was ported from parquet-mr/parquet-cpp and modified to work in Python 2 and 3

### CODE REVIEW

**Comment by wesm** [comment]
Tried merging #1245 but there was a bug. Will keep at it until this script is right

**Review by xhochy — APPROVED** [review]
+1

Are these fixes relevant for parquet-cpp, too? Can you port them there?

**Comment by wesm** [comment]
Yeah, we should do that because parquet-cpp is Python 2 only

**Comment by wesm** [comment]
opened ARROW-1739 about fixing the broken build (unrelated to this patch)

**Pull request closed without merging**
