### PR TITLE
ARROW-2974: [Python] Replace usages of "source activate" with "conda activate" in CI scripts

### PR DESCRIPTION
**Pull request by kszucs**
Also includes temporary pin to meson 0.47.1 in the glib build per ARROW-3186

### CODE REVIEW

**Comment by wesm** [comment]
If you do this, then you need to undo the path modification in 

https://github.com/apache/arrow/blob/master/ci/travis_env_common.sh#L23

and replace it with something like

```
source $MINICONDA/etc/profile.d/conda.sh
```

**Comment by kszucs** [comment]
Well, I forgot that. Thanks!

**Comment by wesm** [comment]
This contains a temporary fix for ARROW-3186, i.e. the mesonbuild bug we've been seeing

**Review by wesm — APPROVED** [review]
+1. Merging this with the temporary fix for ARROW-3186 until that can be investigated separately

**Pull request closed without merging**
