### PR TITLE
ARROW-14187: [Python] Performance Regression on file-read benchmark

### PR DESCRIPTION
**Pull request by amol-**

### CODE REVIEW

**Comment by amol-** [comment]
@ursabot please benchmark name=file-read lang=Python

**Comment by pitrou** [comment]
I'm ok with the change but it is completely unrelated to file reading performance (which doesn't go through the Python conversion path).

**Comment by amol-** [comment]
> I'm ok with the change but it is completely unrelated to file reading performance (which doesn't go through the Python conversion path).

Sorry, left this as a branch because I couldn't see locally how the original PR changes impacted the benchmarks, so I opened a PR to tweak them and see if it had any impact on the conbench. I also tried doing a `git bisect` locally to spot the commit that introduced slowdowns, but couldn't see any real difference in the benchmarks.

We will have to dig further if we want to actually find the culprit of the slowdown, I'm having an hard time proving it's related to the changes in https://github.com/apache/arrow/pull/11076 that seemed the original culprit of the slower timings.

**Comment by amol-** [comment]
@ursabot please benchmark name=file-read lang=Python

**Comment by amol-** [comment]
@ursabot please benchmark name=file-read lang=Python

**Comment by amol-** [comment]
@ursabot please benchmark name=file-read lang=Python

**Comment by amol-** [comment]
@ursabot please benchmark name=file-read lang=Python

**Comment by amol-** [comment]
@ursabot please benchmark name=file-read lang=Python

**Comment by pitrou** [comment]
Does it make sense to keep this PR open?

**Comment by amol-** [comment]
Closing as invalid

**Pull request closed without merging**
