### PR TITLE
PARQUET-1458: [C++] parquet::CompressionToString not recognizing brotli compression

### PR DESCRIPTION
**Pull request by hatemhelal**

### CODE REVIEW

**Comment by wesm** [comment]
Looks like this branch needs to be rebased. I recommend that you try to avoid ever using "git merge" and instead only use "git rebase" or "git rebase -i" (since squashed commits are often much easier to rebase). Let me know if you need help

**Comment by hatemhelal** [comment]
Thanks @wesm , really appreciate you taking the time to look at this so quickly!  This was my first attempt at a PR for this project and wasn't sure which process to follow.  This PR is for PARQUET-1458 but I wasn't able to assign that to myself.  Is that something you can help with?  I'll go read up on rebase...

**Comment by wesm** [comment]
I just made you a contributor on Parquet and assigned the issue to you.

Rebasing this branch is going to be pretty complicated, so I'll take care of it for you for now. I'm going to force push this branch, so when I'm done you want to

```
git fetch origin
git reset --hard origin/parquet_1458_stable
```

**Comment by wesm** [comment]
Done

**Review by wesm — APPROVED** [review]
+1. Thanks for fixing this

**Comment by wesm** [comment]
The Travis CI failure is unrelated. I'll merge once the Windows build looks good

**Comment by hatemhelal** [comment]
Thanks @wesm, really appreciate the help.  This PR a first attempt at ironing out some of the details of learning how to contribute.  I've gone through the contributions page, do you have any other recommended reading?  Happy to help.

**Comment by wesm** [comment]
At some point someone should document various git workflows. I'm not sure when I'll have time to get to it personally

**Comment by hatemhelal** [comment]
I can take a first stab at documenting at least how to manage working with the mathworks/arrow fork, and if it makes sense that could be integrated into the contributors guide.  Might be a few days before I have some time to do that.

**Pull request closed without merging**
