### PR TITLE
ARROW-3784: [R] Array with type fails with x is not a vector

### PR DESCRIPTION
**Pull request by romainfrancois**
closes #2956 using a better approach. This reserves the `type` argument for when we'll really use it. 

```r
> library(arrow)
> array(1:10, type = int16())
arrow::Array 
[
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10
] 
Warning message:
The `type` argument is currently ignored 
```

### CODE REVIEW

**Review by wesm — APPROVED** [review]
+1

**Comment by wesm** [comment]
The R CI failed

````
0.81schecking Rd \usage sections ... WARNING
Undocumented arguments in documentation object 'array'
  ‘type’
Undocumented arguments in documentation object 'chunked_array'
  ‘type’
Functions with \usage entries need to have the appropriate \alias
entries, and all their arguments documented.
The \usage entries must correspond to syntactically valid R code.
See chapter ‘Writing R documentation files’ in the ‘Writing R
Extensions’ manual.checking installed package size ... NOTE
  installed size is  9.8Mb
  sub-directories of 1Mb or more:
    libs   8.1Mb
    R      1.6Mbchecking S3 generic/method consistency ... NOTE
Found the following apparent S3 methods exported but not registered:
  print.integer64 str.integer64
See section ‘Registering S3 methods’ in the ‘Writing R Extensions’
manual.
```

**Comment by romainfrancois** [comment]
fixed now. Can we remove R from allowed failures ? I'd see these faster.

**Comment by wesm** [comment]
R is still failing very often due to rate limiting problems. These failures would distress other developers, I think

**Comment by wesm** [comment]
Merging this. I need to set myself up so I can run these unit tests locally. Can you add instructions on running the unit tests to https://github.com/apache/arrow/blob/master/r/README.md? We should also put together a guide for people to set up their development environment for the first time perhaps on the wiki https://cwiki.apache.org/confluence/display/ARROW

**Comment by wesm** [comment]
Sounds good. We need to make sure that folks who don't do R development every day can still make improvements to the C++ code (or fix up API changes, etc.)

**Pull request closed without merging**
