### PR TITLE
ARROW-8487: [FlightRPC] Provide a way to target a particular payload size

### PR DESCRIPTION
**Pull request by lidavidm**
I'd appreciate feedback on this. This is a specialized API to limit the payload size when a client is sending data to a server. 

While Flight by default removes the gRPC-level limits on message sizes, we've found setting server-side limits on the size of incoming messages is still useful to ensure clients don't overwhelm a server/exhaust server memory by sending very large messages. However, if you exceed the limit at the gRPC level, the server resets the connection, making it hard for a client to recover gracefully. This PR adds an optional client-side check, so the client can catch the error and retry with a smaller record batch, or provide a meaningful error to the user if the batch cannot be made small enough.

Unlike solutions involving `pa.ipc.get_record_batch_size`, this avoids duplicate re-serialization of the record batch.

This is essentially a flight-specific version of [ARROW-5377](https://issues.apache.org/jira/browse/ARROW-5377). I proposed a candidate API there, but it's much more complex than the solution here.

### CODE REVIEW

**Comment by pitrou** [comment]
Sorry for the delay. If I understand correctly, the client configures the write size limit because it doesn't trust itself to always limit the write size when deciding on the size of record batches?

**Comment by lidavidm** [comment]
> Sorry for the delay. If I understand correctly, the client configures the write size limit because it doesn't trust itself to always limit the write size when deciding on the size of record batches?

Essentially, yes. Checking the size of a record batch before writing it may be expensive. `pa.ipc.get_record_batch_size` runs at a couple hundred MiB/s, but Flight itself can achieve those speeds as well, so you'd be halving your effective throughput. What this does is instead implement a post-serialization check, so that in the common case, you serialize, check the size computed, and write; if you do happen to exceed the size, then you bail out with an error and can try to write a smaller batch.

Of course, the server enforces a limit as well, but the server limit is a worse user experience as the only way gRPC can handle a too-large message is to disconnect the client entirely.

As commented on [ARROW-5377](https://issues.apache.org/jira/browse/ARROW-5377)), we could instead expose IpcPayload, either directly, or by offering APIs that let you work with an opaque wrapper around an IpcPayload (and do nothing except get its size and proceed with/cancel the write).

No worries on the delay!

**Comment by pitrou** [comment]
I think we could expose `IpcPayload` indeed. It seems stable, and is simple enough. @wesm Would you have any concerns about it?

**Comment by wesm** [comment]
I don't have a problem with it

**Comment by lidavidm** [comment]
I'll close this and take a look at the other approach then, thank you both!

**Pull request closed without merging**
