### PR TITLE
PARQUET-1481: [C++] Throw exception when encountering bad Thrift metadata in RecordReader

### PR DESCRIPTION
**Pull request by wesm**

### CODE REVIEW

**Comment by wesm** [comment]
cc @hatemhelal @xhochy 

Given the somewhat esoteric nature of this issue I'm not sure it's worth adding an example file to apache/parquet-testing, but we can do so if you like

**Comment by hatemhelal** [comment]
Although unlikely, seems worth testing at least for the test coverage.  Happy to help out by writing the test (I had made a start on it...)

**Comment by wesm** [comment]
No worries. I'll create a "bad_data" directory in apache/parquet-testing and add a test for it

**Review by majetideepak — APPROVED** [review]
+1 LGTM

**Pull request closed without merging**
