### PR TITLE
ARROW-935: [Java] Build Javadoc and site with OpenJDK8 in Java CI build

### PR DESCRIPTION
**Pull request by wesm**

### CODE REVIEW

**Comment by wesm** [comment]
@julienledem this is failing due to extreme Maven verbosity. I don't know Java stuff well enough to set the right logging or suppressions. Could you take a look? thanks

**Comment by xhochy** [comment]
@wesm you could set the log level by `export MAVEN_OPTS='-Dorg.slf4j.simpleLogger.defaultLogLevel=warn'` to warning. That produce significantly (~90%) less logging.

**Comment by wesm** [comment]
Thanks @xhochy, giving that a try

**Comment by wesm** [comment]
+1, thanks for the tip!

**Pull request closed without merging**
