### PR TITLE
ARROW-7795: [Rust] Added support for NOT

### PR DESCRIPTION
**Pull request by jorgecarleitao**

### CODE REVIEW

**Review by andygrove — APPROVED** [review]
@jorgecarleitao This looks great, thanks! I think you need to rebase against master now to fix the tests.

**Comment by jorgecarleitao** [comment]
@andygrove , thanks a lot for reviewing it! Rebased and force pushed.

**Comment by andygrove** [comment]
Thanks @jorgecarleitao .. if you want to create a JIRA a/c I can assign the resolved ticket to you

https://github.com/apache/arrow/blob/master/docs/source/developers/contributing.rst

**Comment by jorgecarleitao** [comment]
what does "JIRA a/c" mean? I did create the issue here: https://issues.apache.org/jira/browse/ARROW-7795 some time ago.

**Comment by andygrove** [comment]
Sorry, I missed that. I've added your user to the "Contributors" role in this project and assigned that JIRA to you. You should also be able to self-assign JIRAs now.

**Pull request closed without merging**
