### PR TITLE
ARROW-7613: [Rust] Remove redundant :: prefixes

### PR DESCRIPTION
**Pull request by 95th**

### CODE REVIEW

**Comment by kszucs** [comment]
@95th linter is complaining

**Comment by 95th** [comment]
@kszucs windows build failing with:
```
File not found - *_generated.rs
```
Not sure why.. 

cc @andygrove

**Review by nevi-me — APPROVED** [review]
Hi @95th , may you please rebase against master, the Windows CI issue is fixed.

@andygrove we could also just merge this as it the CI failure is unrelated, what do you think?

**Comment by 95th** [comment]
@nevi-me rebased

**Comment by kszucs** [comment]
Thanks @95th! Merging.

**Pull request closed without merging**
