### PR TITLE
ARROW-15928: [C++] Fix crashes and implement chunked array support for replace_with_mask function

### PR DESCRIPTION
**Pull request by lidavidm**

### CODE REVIEW

**Comment by lidavidm** [comment]
This does not handle the mask or the replacements being chunked arrays, though it will reject those explicitly. A chunked mask could probably be handled (there's a helper inside chunked_array.h) with some adjustments to how we treat the offset, but chunked replacements would probably require us to template out the code a lot more.

**Comment by jorisvandenbossche** [comment]
@lidavidm what's the status of this PR? (it's probably it doesn't yet handle all cases, can be tracked as new JIRAs?)

**Comment by lidavidm** [comment]
The original bug should be fixed and other cases explicitly error instead of crashing.

**Review by kszucs — APPROVED** [review]
LGTM

**Pull request closed without merging**
