### PR TITLE
PARQUET-1631: [C++] ParquetInputWrapper::GetSize returns Tell

### PR DESCRIPTION
**Pull request by czxrrr**

### CODE REVIEW

**Comment by czxrrr** [comment]
@wesm here is the patch. Can you also add me as a contributor to Arrow and Parquet so that I can assign JIRAs? Thanks!

**Comment by wesm** [comment]
Done, and assigned the issue to you

**Comment by wesm** [comment]
I was curious why the unit test was passing before and it seems it had only worked "by accident". I believe I've fixed that now

**Review by wesm — APPROVED** [review]
+1

**Pull request closed without merging**
