### PR TITLE
ARROW-1643: [Python] Accept hdfs:// prefixes in parquet.read_table and attempt to connect to HDFS

### PR DESCRIPTION
**Pull request by ehsantn**
This patch enables pq.read_table, pq.write_table, and pq.ParquetFile to accept HDFS URI and connect to HDFS.

### CODE REVIEW

**Review by xhochy — APPROVED** [review]
+1, LGTM

I rebased the code, once the build is green again, I will merge.

**Comment by wesm** [comment]
This is failing due to flakes. I want to make a couple tweaks to the patch, also, going to check it out locally and modify, in addition to fixing the flakes

**Comment by wesm** [comment]
This patch adds support for reading datasets (in addition to single files) that are located in HDFS, but this functionality is not tested, only reading single files. @ehsantn do you have time to add a unit test for reading a multi-file dataset from an HDFS uri?

**Comment by wesm** [comment]
Note that the testing situation for HDFS right now is really not good (there is a Dockerfile and a test script, but it isn't being actively used and so likely to be bitrotting). I opened https://issues.apache.org/jira/browse/ARROW-2248 about doing something about this

**Comment by ehsantn** [comment]
Thanks @xhochy and @wesm for help. Sure, I'll add a unittest for a multi-file dataset.

Yes, we need proper HDFS testing infrastructure. I test using a local HDFS setup.

**Comment by wesm** [comment]
Looks like I missed a couple issues that Travis turned up (I was testing on Python 3.5), let me know if you need help getting the build passing

**Comment by wesm** [comment]
We should try to close this issue out this week -- if no one else can take a look I will find some time for it

**Comment by ehsantn** [comment]
Sorry @wesm, I was busy with unexpected tasks. Looking at it now; will hopefully finish tomorrow.

**Comment by ehsantn** [comment]
Looks like the last travis config got stuck installing Lua, so maybe it just needs restarting. I don't have a Windows setup to look at the Windows error at the moment. There are two HDFS tests that are failing also but the errors seem unrelated to me. Can someone look at them?

**Comment by wesm** [comment]
Restarted the build. Can you rebase? I think the appveyor build will pass then

**Comment by ehsantn** [comment]
Appveyor didn't pass after rebase.

**Comment by xhochy** [comment]
The error could be legitimate, someone with access to a Windows machine should have a look into it.

**Comment by wesm** [comment]
I will take a look and see if we can get this into 0.9.0

**Comment by wesm** [comment]
+1. I fixed the Windows problem. Let me see if the HDFS docker setup still works while the build is running

**Pull request closed without merging**
