### PR TITLE
ARROW-12738: [C++/Python/R] Update conda variant files

### PR DESCRIPTION
**Pull request by xhochy**

### CODE REVIEW

**Comment by xhochy** [comment]
@github-actions crossbow submit -g conda

**Comment by xhochy** [comment]
@github-actions crossbow submit conda-osx-clang-py36-r40

**Comment by xhochy** [comment]
@github-actions crossbow submit conda-osx-clang-py36-r40

**Comment by xhochy** [comment]
@github-actions crossbow submit -g conda

**Review by kszucs — APPROVED** [review]
Thanks @xhochy!

**Pull request closed without merging**
