### PR TITLE
ARROW-3444: [Python] Add Array/ChunkedArray/Table nbytes attribute

### PR DESCRIPTION
**Pull request by jorisvandenbossche**
https://issues.apache.org/jira/browse/ARROW-3444

Question is then what the expected result is for a sliced array? (because the buffers do not take that into account)

### CODE REVIEW

**Comment by dhirschfeld** [comment]
> *Question is then what the expected result is for a sliced array? (because the buffers do not take that into account)*

I think it would be very misleading if it didn't report the size of the actual number of elements rather than the number of elements in the entire buffer.

e.g. `pyarrow` would hopefully follow `numpy` here:
```python
In [2]: import numpy as np

In [3]: x = np.random.randn(1000, 1000)

In [4]: x.size, x.nbytes
Out[4]: (1000000, 8000000)

In [5]: x[::10, ::10].size, x[::10, ::10].nbytes
Out[5]: (10000, 80000)

In [6]: x[:1, :1].size, x[:1, :1].nbytes
Out[6]: (1, 8)
```

**Comment by dhirschfeld** [comment]
There is a trap here in that referencing a single element in a view won't release a potentially very large buffer, but it's a gotcha that anyone familiar with numpy will know about - if you want to release the memory take an explicit copy.

I think there's a huge benefit in following the numpy precedent so peoples code and intuitions will be more portable.

**Review by pitrou — APPROVED** [review]
+1. Will merge when green.

**Comment by jorisvandenbossche** [comment]
@dhirschfeld I agree it would be surprising if it did not report the size of the actual array but rather the size of the entire buffer.

I checked, and also `__sizeof__` in numpy only looks at the actual slice and not the full array.

@pitrou what's your thought on this?  (the +1 means you are fine with the current behaviour, or think this is fine as a follow-up ?)

**Comment by pitrou** [comment]
@dhirschfeld I agree that following Numpy would ideally be better here, but probably harder (especially for variable-length types such as list).

**Pull request closed without merging**
