### PR TITLE
ARROW-1303: [C++] Support downloading Boost

### PR DESCRIPTION
**Pull request by kou**
CentOS 6 ships old Boost. If we support downloading Boost, we'll build
RPM for CentOS 6 easily.

### CODE REVIEW

**Review by wesm — APPROVED** [review]
+1. I will try this out locally before merging. As one question, do you think it's worth explicitly opting in to vendored Boost (`-DARROW_BOOST_VENDORED=ON`), since if someone has forgotten to set $BOOST_ROOT then this long-ish build will start

as a second question, do you think one would ever use `-DARROW_BOOST_USE_SHARED=on` with vendored Boost?

**Comment by kou** [comment]
> As one question, do you think it's worth explicitly opting in to vendored Boost (`-DARROW_BOOST_VENDORED=ON`), since if someone has forgotten to set $BOOST_ROOT then this long-ish build will start

I've implemented.

**Comment by kou** [comment]
> do you think one would ever use `-DARROW_BOOST_USE_SHARED=on` with vendored Boost?

The default value of `ARROW_BOOST_USE_SHARED` is `on`. So most of vendoered Boost users use `ARROW_BOOST_USE_SHARED`.

But I think that we can always disable shared libraries even if `ARROW_BOOST_USE_SHARED` is `on`. Because shared libraries are only used for test. Shared libraries aren't needed for test.

I've changed.

**Comment by wesm** [comment]
Works like a charm. Thanks @kou!

**Pull request closed without merging**
