### PR TITLE
ARROW-4562: [C++] Avoid copies when serializing Flight data

### PR DESCRIPTION
**Pull request by pitrou**
Also massage the Flight headers to avoid unnecessary includes and declarations.

### CODE REVIEW

**Comment by pitrou** [comment]
cc @lihalite for reviewing

**Comment by lihalite** [comment]
This looks good to me, but I will build+test it later today and give it another look.

**Review by ghost — APPROVED** [review]

**Comment by pitrou** [comment]
AppVeyor build at https://ci.appveyor.com/project/pitrou/arrow/builds/22491271

**Comment by wesm** [comment]
Nice work =)

**Comment by wesm** [comment]
I tried to quantify the improvement that this has but `arrow-flight-benchmark` produces very noisy results for me, anywhere from 2000-2700 MB/s. We'll want to improve the benchmark to do a longer, more rigorous test to get a higher precision number

**Comment by pitrou** [comment]
To make benchmark results more stable you can use something like:
```
$ taskset -c 1,3 ./build/release/arrow-flight-benchmark -num_streams 32 -num_threads 1
```

I get 2.5 GB/s before the PR and 2.9 GB/s after. A significant improvement, though not earth-shattering.

**Comment by pitrou** [comment]
With:
```
$ taskset -c 1,3 perf record --call-graph=dwarf ./build/release/arrow-flight-benchmark -records_per_stream 20000000 -num_streams 16 -num_threads 1 -records_per_batch 100000
```

78% of the entire benchmark runtime (server + client) seems spent in `grpc_byte_buffer_reader_readall`.

**Comment by wesm** [comment]
So based on the implementation of grpc_byte_buffer_reader_readall, https://github.com/grpc/grpc/blob/618a3f561d4a93f263cca23abad086ed8f4d5e86/src/core/lib/surface/byte_buffer_reader.cc#L112, we should understand why this is being called

* is there ZLIB compression by default? 
* are the multiple slices in the result, if so why is that? 

given that we've done zero configuration of grpc i would guess there are some knobs to turn that may affect this

**Comment by pitrou** [comment]
@wesm See Zulip discussion ("gRPC scalability").

**Comment by pitrou** [comment]
Compression isn't enabled (otherwise it would be visible in perf traces).

**Comment by wesm** [comment]
@pitrou can we move those discussions here? Others should be able to see them (our Zulip is not public/archived)

**Comment by wesm** [comment]
(or JIRA)

**Comment by pitrou** [comment]
Hmm, yes, I had forgotten that Zulip wasn't public. I'll repost to the ML.

**Pull request closed without merging**
