### PR TITLE
GH-38216: [R] open_dataset(format = "json") not documented

### LINKED ISSUE #38216: [R] `open_dataset(format = "json")` not documented
### Describe the bug, including details regarding any error messages, version, and platform.

In the roxygen header for the `format` argument to `open_dataset()`, "json" isn't documented even though it is supported.

### Component(s)

R

### PR DESCRIPTION
**Pull request by Divyansh200102**
fixes #38216 
* Closes: #38216

### CODE REVIEW

**Review by thisisnic — CHANGES_REQUESTED** [review]
Thanks for making this PR, @Divyansh200102!  A couple of things to suggest:

1. The ".Rd" files in the package are automatically generated from the Roxygen headers above the functions in the package, and so the change needs to be made by adding the documentation in line 115 in `dataset.R`:

https://github.com/apache/arrow/blob/4bf777a6ad716e3d60f96446b0c37bc4752990b4/r/R/dataset.R#L114-L115

Then, if you run `devtools::document()` in R the change in `open_dataset.Rd` will be automatically generated. (if you're only making the changes in the GitHub editor, let me know and I can run `devtools::document()` myself and push the change for you)

2.  We only currently support newline-delimited JSON (aka ND-JSON), so we should be clear about that so that users don't mistakenly think we support all JSON

**Comment by Divyansh200102** [comment]
i am making the changes in the github editor so please push the changes.

**Comment by Divyansh200102** [comment]
is it fine now? and since i am editing on the github editor can u please run devtools::document() in R and push the changes in open_dataset.Rd in yourself

**Comment by jonkeane** [comment]
I tried to fix the docs on using out bot, but looks like the github bot can’t push to this fork: https://github.com/apache/arrow/actions/runs/6550133348/job/17788582932#step:13:8 

I'm not sure if this is something you've configured @Divyansh200102 to disallow pushes to your fork from upstream, or if it's something that is wrong with the bot generally.

**Comment by Divyansh200102** [comment]
> I tried to fix the docs on using out bot, but looks like the github bot can’t push to this fork: https://github.com/apache/arrow/actions/runs/6550133348/job/17788582932#step:13:8
> 
> I'm not sure if this is something you've configured @Divyansh200102 to disallow pushes to your fork from upstream, or if it's something that is wrong with the bot generally.

shall i create a new pull request??

**Comment by jonkeane** [comment]
> shall i create a new pull request??

Nope, don't worry about it — I pulled it locally and updated them. Once the CI is green I'll approve + merge. 

Thanks for your contribution!

**Review by thisisnic — APPROVED** [review]

**Pull request merged**
