### PR TITLE
ARROW-3765: [Gandiva] Segfault when the validity bitmap has not been allocated

### PR DESCRIPTION
**Pull request by suquark**
https://issues.apache.org/jira/browse/ARROW-3765

### CODE REVIEW

**Comment by suquark** [comment]
Ready to merge.

**Review by pcmoritz — APPROVED** [review]
LGTM! Does one of you want to have a look @pravindra @praveenbingo

**Review by praveenbingo — APPROVED** [review]
LGTM +1. Thanks for doing this.

**Comment by pravindra** [comment]
sorry, I looked at this a bit late. An additional change is required for the if-else and boolean expression handling where we directly access the validity bitmap. I'll open a jira for that.

**Pull request closed without merging**
