### PR TITLE
GH-43519: [Python][CI][Packaging] Use released versions to build and test wheels on Python 3.13

### PR DESCRIPTION
**Pull request by jorisvandenbossche**
### Rationale for this change

Now that numpy, cython and pandas all have releases that support Python 3.13, we can remove the extra index and ensure that we are building our wheels with the released version instead of nightly dev version.

* GitHub Issue: #43519

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
@github-actions crossbow submit -g wheel

**Comment by jorisvandenbossche** [comment]
I forgot that the free-threading build is of course using the same requirements files, and for those builds we still need cython main (there is not yet a cython release with freethreaded support/wheels).

I do think it is important to build are main released wheels with a released version of numpy/cython, so we will have to add the pip flags depending on using a free-threaded python build or not.

**Comment by jorisvandenbossche** [comment]
@github-actions crossbow submit wheel*cp313t*

**Comment by jorisvandenbossche** [comment]
@github-actions crossbow submit wheel-macos*cp313t*

**Comment by jorisvandenbossche** [comment]
(the macos arm64 is passing now after restarting it, but so the first time it was failing with a segfault in `/test_flight_async.py`, that might be something to later stress test more under the free-threaded build)

**Review by pitrou — APPROVED** [review]

**Comment by jorisvandenbossche** [comment]
@github-actions crossbow submit -g wheel

**Comment by jorisvandenbossche** [comment]
The mac Python 3.9 build shows those warnings, which might explain the failures:

```
WARNING: Target directory /Users/runner/work/crossbow/crossbow/build-env/lib/python3.9/site-packages/wheel-0.44.0.dist-info already exists. Specify --upgrade to force replacement.
WARNING: Target directory /Users/runner/work/crossbow/crossbow/build-env/lib/python3.9/site-packages/wheel already exists. Specify --upgrade to force replacement.
WARNING: Target directory /Users/runner/work/crossbow/crossbow/build-env/lib/python3.9/site-packages/distutils-precedence.pth already exists. Specify --upgrade to force replacement.
WARNING: Target directory /Users/runner/work/crossbow/crossbow/build-env/lib/python3.9/site-packages/setuptools already exists. Specify --upgrade to force replacement.
WARNING: Target directory /Users/runner/work/crossbow/crossbow/build-env/lib/python3.9/site-packages/pkg_resources already exists. Specify --upgrade to force replacement.
WARNING: Target directory /Users/runner/work/crossbow/crossbow/build-env/lib/python3.9/site-packages/_distutils_hack already exists. Specify --upgrade to force replacement.
```

**Comment by jorisvandenbossche** [comment]
@github-actions crossbow submit wheel-macos-*

**Comment by jorisvandenbossche** [comment]
@github-actions crossbow submit -g wheel

**Comment by jorisvandenbossche** [comment]
cc @raulcd

**Review by raulcd — COMMENTED** [review]
This looks good to me. Could you rebase to fix the CI failures?

**Review by raulcd — APPROVED** [review]
Thanks @jorisvandenbossche

**Pull request merged**
