### PR TITLE
[Go] Cherry-pick changes for OTEL to maintenance branch

### PR DESCRIPTION
**Pull request by zeroshade**
As discussed on #14883 and the mailing list, cherry-picking fixes back to v10 maintenance branch for unofficial source release for Open Telemetry to utilize until the v11 release in mid-january.

CC @lquerel

### CODE REVIEW

**Comment by kou** [comment]
* We need to fix "Source Release and Merge Script" failures: https://github.com/apache/arrow/actions/runs/3706751030/jobs/6284266855
* We MUST NOT use "Squash and merge" button nor `dev/merge_arrow_pr_.py` to merge this because it squashes commits. We need to use `git checkout maint-10.0.x && git merge fix-for-tel && git push apache maint-10.0.x` or something.

**Comment by kou** [comment]
Hmm. "Source Release and Merge Script" failed in the current `maint-10.0.x`...
https://github.com/apache/arrow/actions/runs/3475106733/jobs/5808974593

**Comment by zeroshade** [comment]
@kou I can do those steps, but do you want me to wait until the "Source Release and Merge Script" issue is addressed?

**Comment by kou** [comment]
> do you want me to wait until the "Source Release and Merge Script" issue is addressed?

Yes. In general, we should keep CI green. :-)

**Comment by zeroshade** [comment]
@kou I agree wholeheartedly :) 

After #14987 gets merged i'll cherry-pick that into this branch also and re-run the CI

**Comment by kou** [comment]
Merged.

**Comment by zeroshade** [comment]
I've added your commit to this, once all the CI is green i'll merge this in the way you suggested.

**Pull request merged**
