### PR TITLE
ARROW-13881: [C++][FlightRPC][Packaging] Ensure Flight is packaged with advanced TLS options on Windows

### PR DESCRIPTION
**Pull request by lidavidm**

### CODE REVIEW

**Comment by lidavidm** [comment]
@github-actions crossbow submit conda-win-vs2017-py39

**Comment by lidavidm** [comment]
The last passing build for the Windows/Conda builds don't detect TlsCredentialsOptions: https://dev.azure.com/ursacomputing/crossbow/_build/results?buildId=10962&view=logs&j=4c86bc1b-1091-5192-4404-c74dfaad23e7&t=1e0e7149-0c33-565b-af41-050b54dd61be&l=467

This PR sets the flag to fail if not found for the Windows builds too, and tries to fix the detection.

**Comment by pitrou** [comment]
@github-actions crossbow submit -g wheel

**Review by pitrou — APPROVED** [review]
+1. The macOS wheel build failures look unrelated.

**Pull request closed without merging**
