### PR TITLE
ARROW-16174: [Python] Fix FixedSizeListArray.flatten() on sliced input

### PR DESCRIPTION
**Pull request by milesgranger**
[ARROW-16174](https://issues.apache.org/jira/browse/ARROW-16174)

Current behavior
```python
import pyarrow as pa

array = pa.array([[1], [2], [3]], type=pa.list_(pa.int64(), list_size=1))
array[2:].flatten().to_pylist()
[1, 2, 3]
```

After this patch
```python
import pyarrow as pa

array = pa.array([[1], [2], [3]], type=pa.list_(pa.int64(), list_size=1))
array[2:].flatten().to_pylist()
[3]
```

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
By inheriting from BaseListArray, we also inherit the `value_parent_indices` and `value_lengths` methods. Can you check (and test) that those are actually working? (I don't know if those kernels are implemented for fixed size lists) 
They are also not super useful for fixed size lists, since they will be constant (or constantly increasing), but if working, I suppose it doesn't hurt to have them.

**Comment by milesgranger** [comment]
Ready for another round as time permits. :)

**Review by AlenkaF — APPROVED** [review]
+1

I have re-run the linter CI job.

**Review by pitrou — APPROVED** [review]

**Comment by pitrou** [comment]
@milesgranger Do you have Github Actions enabled on your fork?

**Comment by milesgranger** [comment]
@pitrou I do, is that bad?
image

**Comment by pitrou** [comment]
I see that lint was successful here: https://github.com/milesgranger/arrow/actions/runs/3051787384

**Pull request merged**
