### PR TITLE
ARROW-16190: [CI][R] Implement CI on Apple M1 for R

### PR DESCRIPTION
**Pull request by assignUser**

### CODE REVIEW

**Comment by assignUser** [comment]
@github-actions crossbow submit  verify-rc-binaries-wheels-macos-11-arm6 wheel-macos-big-sur-*-arm64

**Comment by assignUser** [comment]
The binaries job can not work due to no rc and the other failure is unrelated and also happening in the nightlies)

**Comment by assignUser** [comment]
@github-actions crossbow submit r-binary-packages

**Comment by assignUser** [comment]
@nealrichardson this should be ready :)

**Comment by assignUser** [comment]
I reverted the last commit as the removal is now integrated into the runner clean up.

**Review by nealrichardson — APPROVED** [review]
Confirmed that I can download and install the new package on my m1 mac

**Pull request merged**
