### PR TITLE
ARROW-15782: [C++] Fix Findre2Alt.cmake to check RE2_ROOT variable first

### PR DESCRIPTION
**Pull request by sfc-gh-hyu**

### CODE REVIEW

**Review by kou — APPROVED** [review]
+1

**Comment by sfc-gh-hyu** [comment]
@kou May I ask why this PR is closed? Looks like you approved the PR, but did not merge it.

**Comment by kou** [comment]
GitHub says "closed" but your change was merged into master.
This is caused because we use our merge tool instead of GitHub's merge button.

See also: https://github.com/apache/arrow/pull/12004#issuecomment-1031955625

It may be better that we document about this somewhere... Do you want to work on the documentation task?

**Comment by kou** [comment]
Or we may be able to use GitHub's merge API instead of `git push`. Then GitHub will say "merged" not "closed".

**Comment by sfc-gh-hyu** [comment]
Ah I see. Thanks! This indeed confuses me. Anyway, I'm glad this is accepted!

**Pull request closed without merging**
