### PR TITLE
GH-43667: [Java] Keeping Flight default header size consistent between server and client 

### PR DESCRIPTION
**Pull request by PANKAJ9768**
### What changes are included in this PR?
Flight client can send header size larger than server can accept. This PR is to keep default values consistent across server and client.

### Are there any user-facing changes?

* GitHub Issue: #43667

### CODE REVIEW

**Comment by vibhatha** [comment]
@lidavidm this needs approval for the CIs.

**Comment by vibhatha** [comment]
@PANKAJ9768 would it be possible to test if the expected is happening?

**Comment by PANKAJ9768** [comment]
> @PANKAJ9768 would it be possible to test if the expected is happening?

Added test cases

**Review by lidavidm — APPROVED** [review]

**Comment by lidavidm** [comment]
```
[WARN] /build/java/flight/flight-core/src/test/java/org/apache/arrow/flight/TestFlightService.java:157: First sentence of Javadoc is missing an ending period. [SummaryJavadoc]
```

**Comment by PANKAJ9768** [comment]
> ```
> [WARN] /build/java/flight/flight-core/src/test/java/org/apache/arrow/flight/TestFlightService.java:157: First sentence of Javadoc is missing an ending period. [SummaryJavadoc]
> ```

Update doc to eliminate this warning, Please re review

**Review by lidavidm — APPROVED** [review]

**Comment by jbonofre** [comment]
Correct me if I'm wrong, but `maxMetadataSize` goes from 2KB (gRPC default) to 2MB (the `MAX_GRPC_SIZE`). It can be problematic as the headers (metadata) transport is a bit costly.
I think both client and server should "agree" on a appropriate default size.
Just my $0.01 😄

**Comment by lidavidm** [comment]
I don't think it costs anything to bump the limit right?

**Pull request merged**
