### PR TITLE
ARROW-11150: [Rust] Add Arrow Rust Community section to Rust README

### PR DESCRIPTION
**Pull request by andygrove**

### CODE REVIEW

**Comment by andygrove** [comment]
@alamb @jorgecarleitao fyi

**Review by jorgecarleitao — APPROVED** [review]
LGTM

**Comment by jorgecarleitao** [comment]
Thanks @andygrove !

**Review by nevi-me — APPROVED** [review]

**Review by alamb — APPROVED** [review]
Thanks @andygrove  -- I also double checked the links and everything looked good to me. 👍

**Pull request closed without merging**
