### PR TITLE
ARROW-11266: [Rust][DataFusion] Implement vectorized hashing for hash aggregate [WIP]

### PR DESCRIPTION
**Pull request by Dandandan**
This is a WIP PR for implementing a similar approach to hashing as used in the hash join.
For the hash-aggregate heavy query TCPH query 1 this speeds it up (without collision checking, although that should not significantly impact performance) by ~30%.

TODO:
- [ ] Implement collision checking
- [ ] Add test for collisions
- [ ] Move some code to hash utils
- [ ] Implement hashing for f32 / f64 (a PR has been merged recently with group by f32/f64 support)

Benchmark results
PR
```
Query 1 iteration 0 took 457.0 ms
Query 1 iteration 1 took 459.7 ms
Query 1 iteration 2 took 459.3 ms
Query 1 iteration 3 took 461.1 ms
Query 1 iteration 4 took 456.8 ms
Query 1 iteration 5 took 460.6 ms
Query 1 iteration 6 took 462.0 ms
Query 1 iteration 7 took 462.3 ms
Query 1 iteration 8 took 461.0 ms
Query 1 iteration 9 took 466.4 ms
Query 1 avg time: 460.63 ms
```

Vectorized hashing branch:
```
Query 1 iteration 0 took 650.0 ms
Query 1 iteration 1 took 648.5 ms
Query 1 iteration 2 took 646.8 ms
Query 1 iteration 3 took 646.2 ms
Query 1 iteration 4 took 645.7 ms
Query 1 iteration 5 took 643.0 ms
Query 1 iteration 6 took 649.5 ms
Query 1 iteration 7 took 649.5 ms
Query 1 iteration 8 took 643.4 ms
Query 1 iteration 9 took 643.6 ms
Query 1 avg time: 646.63 ms
```

### CODE REVIEW

**Comment by andygrove** [comment]
Really great work @Dandandan !

**Review by alamb — COMMENTED** [review]
This looks great -- thank you for forging ahead here @Dandandan 👍

**Comment by alamb** [comment]
@Dandandan I am closing this PR for the time being to clean up the Rust/Arrow PR backlog.  Please let me know if this is a mistake

**Comment by Dandandan** [comment]
@alamb thanks, probably will open this or a new one if/when I continue with it

**Comment by alamb** [comment]
Closing this PR for now; We can reopen it if need be

**Pull request closed without merging**
