### PR TITLE
WIP: [Release] Verify release-18.1.0-rc0

### PR DESCRIPTION
**Pull request by kou**
PR to verify Release Candidate

### CODE REVIEW

**Comment by kou** [comment]
@github-actions crossbow submit  --group verify-rc-source --param release=18.1.0 --param rc=0

**Comment by mapleFU** [comment]
Just wondering should the fixing below in?
* https://github.com/apache/arrow/pull/44542 
* https://github.com/apache/arrow/pull/44387

**Comment by assignUser** [comment]
@mapleFU that's a bit late :( are these critical?

**Comment by assignUser** [comment]
rc1 started

**Comment by amoeba** [comment]
Hey @mapleFU, while it would be nice to have the fixes in, I think both can wait until 19.0.0. Happy to continue discussing it though.

- https://github.com/apache/arrow/pull/44542 is a segfault (i.e. Critical Fix) which would be a good reason to consider it but I don't think it's a high impact one. I marked the corresponding issue accordingly.
- https://github.com/apache/arrow/pull/44387 doesn't look like a critical fix

**Pull request closed without merging**
