### PR TITLE
GH-34011: [Python][Doc] Add pyarrow.substrait to pyarrow's API reference docs

### LINKED ISSUE #34011: [Python][Doc] add pyarrow.substrait to pyarrow's API reference docs
### Describe the enhancement requested

It is currently missing despite the fact that `pyarrow.substrait.run_query` has a decent docstring.

### Component(s)

Documentation

### PR DESCRIPTION
**Pull request by westonpace**
* Closes: #34011

### CODE REVIEW

**Comment by westonpace** [comment]
image

**Comment by westonpace** [comment]
image

**Review by Fokko — APPROVED** [review]

**Review by jorisvandenbossche — APPROVED** [review]
Thanks!

**Comment by jorisvandenbossche** [comment]
@westonpace it seems there is also a "complete documentation" build, and that is now failing on master because of missing substrait (that build didn't run here on this PR in the latest commit)

**Comment by jorisvandenbossche** [comment]
I opened https://github.com/apache/arrow/pull/34024 to fix this

**Pull request merged**
