### PR TITLE
ARROW-9409: [CI][Crossbow] Nightly conda-r fails

### PR DESCRIPTION
**Pull request by nealrichardson**
It's annoying that we need to declare these separately

### CODE REVIEW

**Comment by nealrichardson** [comment]
@github-actions crossbow submit *conda-r*

**Comment by nealrichardson** [comment]
@github-actions crossbow submit *conda-r*

**Comment by nealrichardson** [comment]
Ok I've worked around the decor issue but now there's what appears to be a legit failure, a segfault on the new dictionary integration test: https://github.com/ursa-labs/crossbow/runs/859461851?check_suite_focus=true#step:6:4357 cc @romainfrancois

**Comment by nealrichardson** [comment]
Also cc @xhochy. IDK how serious this is; I personally have never used this conda setup, and what would make more sense would be to test the actual conda recipe

**Comment by nealrichardson** [comment]
@github-actions crossbow submit test-conda-r-4.0

**Comment by nealrichardson** [comment]
@github-actions crossbow submit test-conda-r-4.0

**Comment by xhochy** [comment]
I'm using this to setup my development environment. The conda recipe only has the run dependencies, that's useful for building the final package but not for developing things.

**Pull request closed without merging**
