### PR TITLE
ARROW-3780: [R] Fix promotion of int16

### PR DESCRIPTION
**Pull request by javierluraschi**
Fix for https://issues.apache.org/jira/browse/ARROW-3780

### CODE REVIEW

**Comment by wesm** [comment]
Hm, I wonder if this can be reproduced easily with unit tests

**Comment by javierluraschi** [comment]
I don't think so since we don't support int16 in R and this code is only hit when a conversion triggers, I believe. However, it does feel like we need a way to provide conversions from R.

**Comment by wesm** [comment]
Well, I think we need to devise a way to write unit tests for this code. Essentially what may be required is an optional Rcpp extension where we can write down the Arrow test cases in C++, materialize them in R, and then execute the code in question

**Comment by javierluraschi** [comment]
Any objections against using the same Rcpp codebase? Obviously, shipping test code is not ideal, but can be quite pragmatic and reasonable as long as the test code does not cause side effects. In this case, we would add something like `CreateTestVector()` which would create the required test vectors.

**Comment by wesm** [comment]
No objections from me. There might be some way to only conditionally compile the test code

**Comment by javierluraschi** [comment]
Updated, anything else? Otherwise, can we merge? Thank you!

**Comment by romainfrancois** [comment]
I'd rather test this after this is dealt with: https://issues.apache.org/jira/browse/ARROW-3741

**Comment by javierluraschi** [comment]
Removed tests, @romainfrancois has a better idea to test this.

**Comment by wesm** [comment]
@romainfrancois @javierluraschi how would you like to proceed on this one?

**Comment by javierluraschi** [comment]
Looks like some other PR already took this fix (https://github.com/apache/arrow/blob/master/r/src/array.cpp#L538), so this one can be closed.

**Comment by wesm** [comment]
Cool, thanks!

**Comment by wesm** [comment]
I would encourage you to think about a testing strategy things that don't fit into the testthat test suite, even if it's something as crude as generating a bunch of Arrow data files with a Python script and then testing against those

**Comment by romainfrancois** [comment]
I'd like to avoid this as much as possible, but will consider it. That can fit in the testthat process.

**Pull request closed without merging**
