### PR TITLE
GH-39863: [C++]  Thirdparty: Bump google benchmark to 1.8.3

### LINKED ISSUE #39863: [C++] Bump bundled Google benchmark version
### Describe the enhancement requested

Title says it all.

### Component(s)

Benchmarking, C++

### PR DESCRIPTION
**Pull request by Cerdore**
## Rationale for this change
Bump benchmark to 1.8.3

## What changes are included in this PR?
Bump benchmark to 1.8.3

## Are these changes tested?
Already has testing

## Are there any user-facing changes?
no

* Closes: #39863

### CODE REVIEW

**Comment by kou** [comment]
@ursabot please benchmark lang=C++

**Comment by pitrou** [comment]
@austin3dickey The wording of the conbench summary at https://github.com/apache/arrow/runs/21102698059 is a bit unexpected, might this be due to the changes in this PR?

**Comment by austin3dickey** [comment]
@pitrou Thanks for bringing that to my attention - that's unrelated to this PR. I recently upgraded `conda` on the machine that ran your benchmarks, and it seems to have put a break in Conbench history since the `-isystem` path changed. I will fix this so new benchmarks can be compared to old benchmarks.

In the meantime, you can check this link for comparisons: https://conbench.ursa.dev/compare/runs/97f46fae7b544173b9bfdc9962cf8051...e2a595b8ca9d41d4916b309b6c4ec42b/

(Sorry that page takes so long to load; I will fix that problem soon.)

**Comment by austin3dickey** [comment]
I fixed the broken history in Conbench and manually reviewed the comparison I linked above. It looks good to me. I don't think this change has much of a performance effect on any of the benchmarks.

**Comment by kou** [comment]
@ursabot please benchmark lang=C++

**Comment by kou** [comment]
@Cerdore Could you rebase on main?

**Comment by Cerdore** [comment]
> @Cerdore Could you rebase on main?

Already rebased

**Comment by Cerdore** [comment]
@ursabot please benchmark lang=C++

**Comment by pitrou** [comment]
@github-actions crossbow submit -g cpp

**Comment by pitrou** [comment]
@github-actions crossbow submit -g cpp

**Comment by pitrou** [comment]
@github-actions crossbow submit -g cpp

**Review by pitrou — APPROVED** [review]
Thanks for the PR, @Cerdore ! I'll merge now.

**Pull request merged**
