### PR TITLE
GH-35243: [C#] Implement MapType

### LINKED ISSUE #35243: [C#] Implement MapType
### Describe the enhancement requested

Hello,

i started dev on new implementation of MapType, im wondering how it should be built ?

I think is a list of Struct which are like `KeyValuePair` c# class

```csharp
using System.Collections.Generic;

namespace Apache.Arrow.Types
{
    public class MapType : NestedType
    {
        public override ArrowTypeId TypeId => ArrowTypeId.Map;
        public override string Name => "map";

        public Field KeyField => Fields[0];
        public Field ValueField => Fields[0];

        public IArrowType ValueDataType => Fields[0].DataType;

        public MapType(IArrowType keyType, IArrowType valueType, bool nullable)
            : this(new Field("key", keyType, false), new Field("value", keyType, false), nullable)
        {
        }

        public MapType(Field keyField, Field valueField, bool nullable)
            : this(new StructType(new List<Field>() { keyField, valueField }), nullable)
        {
        }

        public MapType(StructType structType, bool nullable) : this(new ListType(new Field("key_value", structType, nullable)), nullable)
        {
        }

        public MapType(ListType listType, bool nullable) : this(new Field("key_values", listType, nullable))
        {
        }

        public MapType(Field keyValueField) : base(keyValueField)
        {
        }

        public override void Accept(IArrowTypeVisitor visitor) => Accept(this, visitor);
    }
}
```

### Component(s)

C#

### PR DESCRIPTION
**Pull request by Platob**
Implement new MapType with array

Tested with IPC tests

* Closes: #35243

### CODE REVIEW

**Comment by Tommo56700** [comment]
@Platob do you plan to resolve the outstanding conflicts and submit this? I would really appreciate this feature!

**Comment by CurtHagenlocher** [comment]
@Platob I've taken your branch, merged the latest changes from main and added support for Map in the C API. I'm currently working on adding a few more tests as well as Archery support. Would you like to pull the changes from my branch when I'm done or should I submit a separate PR?

**Comment by CurtHagenlocher** [comment]
Okay, I'm done with my changes and I pushed them to https://github.com/CurtHagenlocher/arrow/tree/Map.

**Comment by Platob** [comment]
Damn sorry forgot I still had this pending, thank you @CurtHagenlocher, I did a version where we would need more primary control to scale up on more complex structures, I'm using a version #35299

**Review by westonpace — CHANGES_REQUESTED** [review]
I reviewed https://github.com/apache/arrow/pull/37885 which (if I understand correctly) includes these changes and things look pretty good.  Sorry that the review was so late.  Please re-request review if we want to return to this PR for some reason.

**Comment by lidavidm** [comment]
Going to close this since the other PR was merged, but if you want to revisit this please feel free to reopen/file a new issue.

**Pull request closed without merging**
