### PR TITLE
ARROW-10971: [Rust][DataFusion] WIP Left join with multiple batches

### PR DESCRIPTION
**Pull request by Dandandan**
Current PR shows failing unit test with multiple batches.
Here "3,7,9,NULL,NULL" is appearing twice, it should be there only once.

### CODE REVIEW

**Comment by Dandandan** [comment]
@jorgecarleitao 

Do you maybe have an idea in which ways this could be solved?
The _most efficient_ way I think / read about would to keep a boolean / bit vector per element or key on the left and just scan / filter the ones at the end that are not marked and produce those extra rows.

Maybe an easier intermediate solution would be to iterate over the batches and update a  `Hashset<Vec<u8>>` or something like currently is done _per batch_.

But I'm not sure how both options fit in the current design (with `SendableRecordBatchStream`, poll next, etc).

So if you have some hints would be very appreciated :)

**Comment by jorgecarleitao** [comment]
Hi @Dandandan . My first impression is that we need a `Arc<Mutex` to share the visited keys and skip them after the first observation. I think we need to pass that state as mutable to `build_join_indexes` and update it there.

**Comment by alamb** [comment]
@Dandandan 
What is the status of this PR?

As part of trying to clean up the backlog of Rust PRs in this repo, I am going  through seemingly stale PRs and pinging the authors to see if there are any plans to continue the work or conversation.

**Comment by Dandandan** [comment]
@alamb status is that it this unsolved as of now. Closing for now

**Pull request closed without merging**
