### PR TITLE
GH-37983: [JS] Allow nullable fields in table when constructed from vector with nulls

### LINKED ISSUE #37983: [JS] when creating a Table from Vectors, arrow always infers non-nullable Fields
### Describe the bug, including details regarding any error messages, version, and platform.

The following javascript code against `apache-arrow` 13.x...
``` js
const arrow = require('apache-arrow');
console.log((new arrow.Table({x: arrow.vectorFromArray([1, 2, null, 4])})).schema.fields);
```

...inappropriately results in the following

``` js
[
  Field {
    name: 'x',
    type: Float64 [Float] { precision: 2 },
    nullable: false,
    metadata: Map(0) {}
  }
]
```

Note that the field is marked as non-nullable. This causes all sorts of fun downstream issues

### Component(s)

JavaScript

### PR DESCRIPTION
**Pull request by domoritz**
We check whether a vector has nulls and then create the schema accordingly.

* Closes: #37983

### CODE REVIEW

**Comment by bmschmidt** [comment]
LGTM.

**Review by bmschmidt — APPROVED** [review]
LGTM.

**Comment by trxcllnt** [comment]
@domoritz the `nullCount` property is lazily computed, so accessing like this will materialize it for each Vector. This seems like a potentially huge performance hit?

**Comment by domoritz** [comment]
Oh, yes, that would be much better. I was actually surprised that vectors don't have a nullable property.

**Comment by domoritz** [comment]
Will do in https://github.com/apache/arrow/issues/39435

**Pull request merged**
