### PR TITLE
ARROW-11159: [Developer] Consolidate pull request related jobs

### PR DESCRIPTION
**Pull request by kou**

### CODE REVIEW

**Comment by kou** [comment]
Demo: https://github.com/kou/arrow/pull/10

**Review by jorgecarleitao — APPROVED** [review]
There is no reason to have them in multiple lines when the status report is opened, so, LGTM. 

I am curious as to why this addresses the slow queue. AFAIK all these jobs run in seconds.

**Comment by kou** [comment]
This may not address the slow queue... We don't know without try...

**Comment by jorgecarleitao** [comment]
My hypothesis for a slow queue is that it is driven by cost: we simply have too many expensive (but unnecessary) jobs running.

1. Every push triggers a 30m+ job (integration tests). Only about 5m of this job is the actual testing
2. jobs are not canceled if there is a push after the push that triggered the job, even though those jobs are very likely not relevant once there is a new commit / rebase.
3. there are jobs from language X running on very push to a user's repo, even when code for X does not change.

These 3 aspects very quickly fill any queue.

**Comment by kou** [comment]
1. It seems that we need to speed up integration test job. (Caching built binaries and reusing not changed binaries?)
2. https://github.com/apache/arrow/graphs/commit-activity shows that we have about 10 pushes in apache/arrow master per day. If we can fix 1., this may not be a critical.
3. It seems that we need auto cancel feature that exists on Travis CI and AppVeyor.

**Pull request closed without merging**
