### PR TITLE
GH-41127: [CI] Use GitHub Actions instead of Azure Pipelines for docker-tests

### PR DESCRIPTION
**Pull request by kou**
### Rationale for this change

We don't want to maintain multiple CI platforms to reduce maintenance cost.

### What changes are included in this PR?

Use GitHub Actions for docker-tests.

### Are these changes tested?

Yes.

### Are there any user-facing changes?

No.
* GitHub Issue: #41127

### CODE REVIEW

**Comment by kou** [comment]
@github-actions crossbow submit test-conda-cpp-valgrind test-debian-12-python-3-amd64 test-ubuntu-20.04-python-3 test-fedora-39-python-3 test-r-linux-valgrind test-ubuntu-r-sanitizer test-fedora-r-clang-sanitizer test-debian-12-go-*

**Comment by assignUser** [comment]
Oh this is great! Thank you kou!

**Comment by kou** [comment]
I think that the test-conda-cpp-valgrind failure is unrelated.
Can we merge this?

**Comment by raulcd** [comment]
> I think that the test-conda-cpp-valgrind failure is unrelated. Can we merge this?

It is unrelated, it has been failing for a while on Azure already: https://github.com/apache/arrow/issues/41004

@kou would you add it to the 16.0.0 maint branch?

**Review by raulcd — APPROVED** [review]
LGTM!
Thanks @kou

**Comment by kou** [comment]
We don't need #41001 for 16.0.0!

**Pull request merged**
