### PR TITLE
ARROW-1510: [GLib] Support cast

### PR DESCRIPTION
**Pull request by kou**

### CODE REVIEW

**Review by wesm — APPROVED** [review]
+1, looks fine except for CI failure

**Comment by kou** [comment]
GLib on Ubuntu Trusty Tahr is old to use `G_DECLARE_DERIVABLE_TYPE` macro.
I'm trying to use newer GLib on Travis CI.

**Comment by kou** [comment]
Now, Travis CI works.

**Comment by wesm** [comment]
Thanks!

**Pull request closed without merging**
