### PR TITLE
ARROW-7282: [Python] IO functions should raise the right exceptions

### PR DESCRIPTION
**Pull request by pitrou**
When an Arrow IO function fails, it should be turned into the appropriate
Python exception subclass, e.g. FileNotFoundError in case the requested
file or directory is missing.

### CODE REVIEW

**Comment by pitrou** [comment]
@emkornfield @jorisvandenbossche

**Comment by pitrou** [comment]
Rebased.

**Review by jorisvandenbossche — APPROVED** [review]
The python part looks good to me

**Comment by pitrou** [comment]
Rebased. @wesm @xhochy Any comments on this?

**Review by xhochy — APPROVED** [review]
+1, LGTM

**Comment by pitrou** [comment]
AppVeyor build: https://ci.appveyor.com/project/pitrou/arrow/builds/29601625
Will merge when finished and green.

**Pull request closed without merging**
