### PR TITLE
ARROW-3223: [GLib] Use the same shared object versioning rule in C++

### PR DESCRIPTION
**Pull request by kou**

### CODE REVIEW

**Comment by kou** [comment]
@shiro615 Can you review this?

**Comment by shiro615** [comment]
This PR looks good to me.

**Comment by shiro615** [comment]
How about adding how to build with Meson to the README? I think that it is kindness to have an explanation about Meson and Ninja in README. I want to work on another pull request.

**Review by wesm — APPROVED** [review]
+1. Can add more build instructions to the README in a follow up patch

**Comment by kou** [comment]
> How about adding how to build with Meson to the README? I think that it is kindness to have an explanation about Meson and Ninja in README. I want to work on another pull request.

It's a good idea. Go ahead!

**Pull request closed without merging**
