### PR TITLE
ARROW-16941: [Java][Dataset] Update more jni_util.h paths

### PR DESCRIPTION
**Pull request by kou**
This is a follow-up of #13481.

We also need to update jni_util.h path in
java/dataset/src/main/cpp/jni_util_test.cc.

Removing "./" is needless but it's redundant.

### CODE REVIEW

**Comment by kou** [comment]
Cc: @lwhite1

**Review by lidavidm — APPROVED** [review]
Thanks for catching this, Kou (would have thought CI tests this, does it not?)

**Comment by kou** [comment]
It seems that we don't have a job that uses `ARROW_JNI=ON` and `ARROW_BUILD_TESTS=ON`.

**Comment by kou** [comment]
Should we also add the following change to this pull request?

```diff
diff --git a/ci/docker/linux-apt-jni.dockerfile b/ci/docker/linux-apt-jni.dockerfile
index 6673b001d7..be6562eae6 100644
--- a/ci/docker/linux-apt-jni.dockerfile
+++ b/ci/docker/linux-apt-jni.dockerfile
@@ -69,7 +69,7 @@ ARG cmake=3.11.4
 RUN wget -nv -O - https://github.com/Kitware/CMake/releases/download/v${cmake}/cmake-${cmake}-Linux-x86_64.tar.gz | tar -xzf - -C /opt
 ENV PATH=/opt/cmake-${cmake}-Linux-x86_64/bin:$PATH
 
-ENV ARROW_BUILD_TESTS=OFF \
+ENV ARROW_BUILD_TESTS=ON \
     ARROW_DATASET=ON \
     ARROW_FLIGHT=OFF \
     ARROW_GANDIVA_JAVA=ON \
```

**Comment by lidavidm** [comment]
Yes, let's make sure at least one CI job covers this.

**Comment by kou** [comment]
OK. I enable it.

**Comment by kou** [comment]
+1

**Pull request merged**
