### PR TITLE
GH-38206: [CI] Remove more pre-installed files

### LINKED ISSUE #38206: [Packaging][Release] Some linux packages fail with no space left on device
### Describe the bug, including details regarding any error messages, version, and platform.

Some Linux packages are failing with No space left on device again even when we are already using `{{ macros.github_free_space()|indent }}` on those.
[centos-9-stream-amd64](https://github.com/ursacomputing/crossbow/actions/runs/6480007571/job/17594658693)
[ubuntu-focal-amd64](https://github.com/ursacomputing/crossbow/actions/runs/6480008417/job/17594661580)

### Component(s)

Packaging, Release

### PR DESCRIPTION
**Pull request by kou**
### Rationale for this change

We need more disk space...

### What changes are included in this PR?

Remove more pre-installed files.

### Are these changes tested?

Yes.

### Are there any user-facing changes?

No.
* Closes: #38206

### CODE REVIEW

**Comment by kou** [comment]
@github-actions crossbow submit centos-9-stream-amd64 ubuntu-focal-amd64

**Comment by assignUser** [comment]
Did gh reduce default disk size or something, this is crazy ...

**Comment by assignUser** [comment]
https://github.com/actions/runner-images/issues/8166#issuecomment-1693424389

>I talked to my colleagues, they told me that "sometimes" vm is provisioned with small disk. it is bug.

:exploding_head: :see_no_evil:

**Comment by kou** [comment]
@github-actions crossbow submit centos-9-stream-amd64 ubuntu-focal-amd64

**Comment by kou** [comment]
@github-actions crossbow submit centos-9-stream-amd64 ubuntu-focal-amd64

**Comment by kou** [comment]
@github-actions crossbow submit centos-9-stream-amd64 ubuntu-focal-amd64

**Review by raulcd — APPROVED** [review]
Thanks for tackling this @kou !
I am merging it and adding it to 14.0.0 if we have more issues I might temporary spin up some self-hosted runners at least to be able to release.

**Pull request merged**
