### PR TITLE
GH-44079: [C++][Parquet] Remove deprecated APIs

### PR DESCRIPTION
**Pull request by pitrou**
### What changes are included in this PR?

Remove APIs that have been deprecated more than one year ago (i.e. in 2023 or before).

* GitHub Issue: #44079

### CODE REVIEW

**Comment by mapleFU** [comment]
cc @emkornfield

**Review by mapleFU — APPROVED** [review]
+1 for me

**Review by emkornfield — APPROVED** [review]

**Comment by pitrou** [comment]
Rebased, will wait for CI

**Review by zanmato1984 — APPROVED** [review]
Though I'm kind of new to parquet codebase, the change looks good enough to me. +1.

**Pull request merged**
