### PR TITLE
ARROW-3953: [Python] Compat with pandas 0.24 rename of MultiIndex labels -> codes

### PR DESCRIPTION
**Pull request by jorisvandenbossche**

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
I am not fully sure if I should add a test for this. The result of this patch is that there should be no warnings about the deprecation, so I could add an assert that there are no warnings in one of the tests? 

Is pandas master tested only in a nightly test build? Or also in travis?

**Comment by wesm** [comment]
I think we have a docker-compose target for testing against pandas master. cc @kszucs

**Comment by xhochy** [comment]
These instructions for the pandas tests can be found at https://github.com/apache/arrow/blob/5704d8d644154f21597125d14d20c9e9ae4379d0/docker-compose.yml#L246-L252

**Comment by kszucs** [comment]
@jorisvandenbossche a test case would be nice

**Comment by jorisvandenbossche** [comment]
Are the docker-compose / crossbow tests also run somewhere on CI, or are you supposed to run them locally? (if I add a test, it could only fail on pandas master, so it wouldn't be catched on travis I think?)

**Comment by kszucs** [comment]
@jorisvandenbossche You can make the test case dependent on pandas' version

**Comment by pitrou** [comment]
I'm not sure it's worth writing a test for this, TBH.

**Comment by jorisvandenbossche** [comment]
Sorry, I will be mainly on holidays the comings weeks, so won't be able to add a test until after (I had some problems compiling yesterday I first need to solve).

A test would be something like adding the following assert to one of the existing tests:

```
with pytest.warns(None) as record:
    # existing conversion from arrow table to pandas
    ...
# assert pandas raises no FutureWarning about codes being deprecated
assert len([w for w in record if w.category is FutureWarning and 'labels' in str(w.message)]) == 0
```

I think it can be nice to add it to make sure we don't introduce a usage of `labels` again, but it's certainly not essential, because the fact that tests are passing both on released pandas and pandas master is the actual test for the functionality.

**Comment by xhochy** [comment]
I would also be happy merging this without a test, @kszucs do you feel strongly about this and could add one?

**Comment by kszucs** [comment]
Not necessarily, but if `order is the soul of everything` then `testing is the soul of engineering`

**Review by kszucs — APPROVED** [review]
Thanks @jorisvandenbossche

**Pull request closed without merging**
