### PR TITLE
ARROW-16295: [CI][Release] Use windows-2019 for verify-rc-source-windows

### PR DESCRIPTION
**Pull request by kou**
Because windows-2016 is deprecated:
https://github.com/actions/virtual-environments/issues/4312

### CODE REVIEW

**Comment by kou** [comment]
@github-actions crossbow submit verify-rc-source-windows

**Comment by kou** [comment]
@github-actions crossbow submit verify-rc-source-windows

**Comment by kou** [comment]
@github-actions crossbow submit verify-rc-source-windows

**Review by kszucs — APPROVED** [review]
The build error is unrelated, thanks Kou!

**Pull request closed without merging**
