### PR TITLE
ARROW-10392: [C++][Gandiva] Avoid string copy while evaluating IN expression

### PR DESCRIPTION
**Pull request by pprudhvi**

### CODE REVIEW

**Comment by pprudhvi** [comment]
@github-actions crossbow submit -g gandiva

**Comment by pprudhvi** [comment]
still couldn't avoid string copy - the copy is now happening inside HashTable
`#0 0x00007f8b9e690159 in __lll_unlock_wake_private () from /lib64/libc.so.6
#1 0x00007f8b9e60df78 in _L_unlock_14902 () from /lib64/libc.so.6
#2 0x00007f8b9e60afe5 in malloc () from /lib64/libc.so.6
#3 0x00007f8b9d3d20cd in operator new(unsigned long) () from /lib64/libstdc++.so.6
#4 0x00007f8b9d430c79 in std::string::_Rep::_S_create(unsigned long, unsigned long, std::allocator<char> const&) () from /lib64/libstdc++.so.6
#5 0x00007f8b9d432531 in char* std::string::_S_construct<char const*>(char const*, char const*, std::allocator<char> const&, std::forward_iterator_tag) () from /lib64/libstdc++.so.6
#6 0x00007f8b9d4325ed in std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, unsigned long, std::allocator<char> const&) () from /lib64/libstdc++.so.6
#7 0x00007f8b595c7c4a in std::_Hashtable<nonstd::sv_lite::basic_string_view<char, std::char_traits<char> >, nonstd::sv_lite::basic_string_view<char, std::char_traits<char> >, std::allocator<nonstd::sv_lite::basic_string_view<char, std::char_traits<char> > >, std::__detail::_Identity, std::equal_to<nonstd::sv_lite::basic_string_view<char, std::char_traits<char> > >, std::hash<nonstd::sv_lite::basic_string_view<char, std::char_traits<char> > >, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, true, true> >::count(nonstd::sv_lite::basic_string_view<char, std::char_traits<char> > const&) const () from /data/yarn/data/usercache/dremio/appcache/application_1603758047742_0001/container_1603758047742_0001_01_000003/tmp/libgandiva_jni.so87f06318-3d22-4bda-be14-ef2458081d87
#8 0x00007f8b595c7258 in gdv_fn_in_expr_lookup_utf8 () from /data/yarn/data/usercache/dremio/appcache/application_1603758047742_0001/container_1603758047742_0001_01_000003/tmp/libgandiva_jni.so87f06318-3d22-4bda-be14-ef2458081d87`

@bkietz , any reason why the copy is happening even when we are looking for a string_view in hashtable<string_view>?

**Comment by pprudhvi** [comment]
Turns out string_view hash function internally creates a string 
https://github.com/martinmoene/string-view-lite/blob/master/include/nonstd/string_view.hpp#L1583

**Comment by pprudhvi** [comment]
@github-actions crossbow submit -g gandiva

**Review by bkietz — COMMENTED** [review]
This looks good to me, any idea what is causing the linker errors?

**Comment by pprudhvi** [comment]
_MinGW link problem is caused by msys2/MINGW-packages#7170 .
It'll be fixed in upstream._

 https://github.com/apache/arrow/pull/8521#issuecomment-716210482

**Review by pravindra — APPROVED** [review]

**Pull request closed without merging**
