### PR TITLE
GH-36809: [Python] MapScalar.as_py with custom field name

### LINKED ISSUE #36809: [Python] KeyError in MapScalar with custom field name
### Describe the bug, including details regarding any error messages, version, and platform.

It is possible to customize the name of the value field for `pa.MapType`. I believe it's a niche feature used for compatibility with parquet and it doesn't change the semantic of the map type. 

this feature causes a KeyError in `MapScalar.as_py`:

```
def test_bug_in_pyarrow():
    assert pa.scalar(
        [("foo", "bar")],
        pa.map_(
            pa.string(),
            pa.field("value", pa.string()),
        ),
    ).as_py() == [("foo", "bar")]

    with pytest.raises(KeyError, match=r"value"):
        pa.scalar(
            [("foo", "bar")],
            pa.map_(
                pa.string(),
                pa.field("map_value", pa.string()),
            ),
        ).as_py()

```

### Component(s)

Python

### PR DESCRIPTION
**Pull request by 0x26res**
### Rationale for this change

`MapScalar.as_py` doesn't take into account custom key/value field names

### What changes are included in this PR?

Fix and tests 

### Are these changes tested?

Simple unit test

### Are there any user-facing changes?

No API changes.
* Closes: #36809

### CODE REVIEW

**Comment by kou** [comment]
Could you revert updating submodules?
It seems that we don't need them.

**Comment by 0x26res** [comment]
> Could you revert updating submodules? It seems that we don't need them.

I agree, I didn't intend to do that. Do you know which git command I need to run to revert them?

**Comment by kou** [comment]
The following command lines will work:

```console
$ cd cpp/submodules/parquet-testing
$ git checkout b2e7cc755159196e3a068c8594f7acbaecfdaaac
$ cd -
$ cd testing
$ git checkout 47f7b56b25683202c1fd957668e13f2abafc0f12
$ cd -
$ git add cpp/submodules/parquet-testing testing
$ git commit
$ git push
```

**Comment by 0x26res** [comment]
That worked, thanks 👍

**Comment by 0x26res** [comment]
@kou do you mind reviewing again? Thanks.

**Review by kou — APPROVED** [review]
+1

**Pull request merged**
