### PR TITLE
GH-39122: [C++] [Parquet] FLBA reader reading preallocs and null count check

### LINKED ISSUE #39122: [C++] [Parquet] FLBA reader does not pre-reserve memory
### Describe the enhancement requested

We can reserve memory before running loops in reading.
Also we can put check on zero null count not to check validity bit mask when there are no nulls.
https://github.com/apache/arrow/blob/f7286a95304a848033d96817f704ace0765c0ec7/cpp/src/parquet/column_reader.cc#L2074-L2090

We can get this situation when we have optional fields in a batch without having nulls here
https://github.com/apache/arrow/blob/ef3797d997bd7a283ddf19055bc69441ae3e7a16/cpp/src/parquet/column_reader.cc#L77-L93

### Component(s)

C++, Parquet

### PR DESCRIPTION
**Pull request by Hattonuri**
We can reserve memory before running loops in reading.
Also we can put check on zero null count, because this function can get it despite called Spaced

This code is run here if column descriptor HasSpacedValues
https://github.com/apache/arrow/blob/ef3797d997bd7a283ddf19055bc69441ae3e7a16/cpp/src/parquet/column_reader.cc#L1194-L1227

But this function does not look on actual values
https://github.com/apache/arrow/blob/ef3797d997bd7a283ddf19055bc69441ae3e7a16/cpp/src/parquet/column_reader.cc#L77-L93

In my case i have many optional decimal fields, but they can be null only in the beginning and the ending and i think that this scenario is not rare

For now i have a flamegraph of my reading looking like this(even I don't only have decimals in schema their parsing takes most of the time). And I optimize that part of FLBA record reader appends
image

### Are there any user-facing changes?

* Closes: #39122

### CODE REVIEW

**Comment by pitrou** [comment]
This looks ok to me.

Note this could probably be improved still. The silly part in this code is that we are generating a bitmap in `valid_bits`, then read it again bit by bit and append bit by bit into the final bitmap... The alternative would be to build the buffers separately (one `BufferBuilder` for the data and one `TypedBufferBuilder<bool>` for the null bitmap).

**Comment by pitrou** [comment]
Also, did you run any benchmarks?

**Comment by mapleFU** [comment]
LGTM, waiting for Bitmap part finished

**Comment by pitrou** [comment]
I opened #39124 for an alternative.

**Comment by pitrou** [comment]
I did a quick-and-dirty benchmark on PLAIN-encoded uncompressed FLBA columns:
* on git main: 465 MB/s
* with this PR: 600 MB/s
* with PR #39124: 715 MB/s

**Comment by mapleFU** [comment]
Since https://github.com/apache/arrow/pull/39124 is merged, would you mind close this pr?

**Pull request closed without merging**
