### PR TITLE
[Release] Prepare 8.0.0

### PR DESCRIPTION
**Pull request by kszucs**
It's hard to see the current status of the nightly builds, so submit them from this PR.

### CODE REVIEW

**Comment by kszucs** [comment]
@github-actions crossbow submit -g packaging -g verify-rc -g test

**Comment by kszucs** [comment]
`verify-rc-binaries-*` are expected to fail

**Comment by thisisnic** [comment]
@github-actions crossbow submit test-r-devdocs

**Comment by kszucs** [comment]
Closing since the preparation is done.

**Pull request closed without merging**
