### PR TITLE
ARROW-8237: [Python][Documentation] Review Python developer documentation, add Dockerfile showing minimal source build with conda and pip/virtualenv

### PR DESCRIPTION
**Pull request by wesm**
This provides Dockerfile setups to build both with Fedora 31 (very recent) and Ubuntu 18.04, both with conda and pip/virtualenv methods

I made the Python developer instructions a bit more minimal. It's unclear that the average developer needs to build Gandiva and Flight, for example. It's fairly clear how to enable these optional components if they are desired.

### CODE REVIEW

**Comment by wesm** [comment]
@JacekPliszka take a look at the packages being installed and the build_venv.sh script, I'm able to build the project fine with pip and virtualenv / no conda on Fedora 31. If you are fail to follow the script it may give clues about what is wrong with your environment.

**Comment by JacekPliszka** [comment]
@wesm 
 
thank you, this works for me.

I just have 2 minor corrections - fedora uses podman and selinux blocks runing the scripts.

So I would suggest:

a) adding 
```
RUN mkdir /io

COPY build_conda.sh /io/
COPY build_venv.sh /io/
```

To Dockerfile.fedora - alternative would be adding --security-opt label=disable to podman run options - whatever you prefer

b) run with

podman build -f=Dockerfile.fedora -t=arrow_fedora_minimal
podman run --rm -t -i -v $PWD:/io arrow_fedora_minimal /io/build_venv.sh

**Comment by wesm** [comment]
Did you find out what's wrong with your host OS? i.e. running the build steps outside of a container environment.

**Comment by JacekPliszka** [comment]
> Did you find out what's wrong with your host OS? i.e. running the build steps outside of a container environment.

No. When I run it directly on OS it worked too.

**Comment by JacekPliszka** [comment]
Added some corrections to my branch - waiting for tests to finish - when they are OK I will raise pull request.

**Comment by wesm** [comment]
Alright. I'll go ahead and merge this.

I'm not sure about the docker/podman thing, this seems like an extra complication.

**Comment by wesm** [comment]
+1

**Comment by JacekPliszka** [comment]
> Alright. I'll go ahead and merge this.
> 
> I'm not sure about the docker/podman thing, this seems like an extra complication.

On Fedora/RH docker is replaced by podman so if you want something to be working out of box then podman should be used.  Using docker requires installing docker CE and downgrading from cgroups v2 to cgroups v1.

I do not like having 2 tools instead of one but I believe it is better to have it like this.

Maybe comment should be added that docker config is the base one and  in case of problems user should first try docker instead of podman to ensure issues are not podman related.

**Comment by JacekPliszka** [comment]
I've created pull request with my changes 

https://github.com/apache/arrow/pull/6845

I

**Pull request closed without merging**
