### PR TITLE
ARROW-3049: [C++/Python] Fix reading empty ORC file

### PR DESCRIPTION
**Pull request by pitrou**

### CODE REVIEW

**Comment by pitrou** [comment]
There's a crash in the Ruby tests that seems related (it occurs in test_orc.rb), but I'm not really able to understand whether the Ruby codebase needs adapting here. @kou would you like to give me a help?

**Comment by kou** [comment]
Sure.
I'll look into this in a few days.

**Comment by pitrou** [comment]
I don't think it's specifically a C/glib problem, rather a general problem in the semantics and/or implementation of column selection. It's not obvious how Orc selects columns and the lack of documentation doesn't help. I'll leave it to @jcrist

**Comment by kou** [comment]
I've pushed a fix https://github.com/apache/arrow/pull/2449/commits/676175fbbecd1a7aeb6eca1a32bb6e96023eef16

We need to use column selected schema not the original schema for table.

It may be better that we pass the read schema for table to `ReadBatch` and reuse it for batches.

**Comment by pitrou** [comment]
That's what I did initially, but when I tried to write some selection tests on the Python side, I got bogus results (try e.g. reading only some columns in the `TestOrcFile.emptyFile` example). I'm not sure whether the issue is on the Python or C++ side.

**Comment by kou** [comment]
I tried to share the same schema in all record batches: https://github.com/apache/arrow/pull/2449/commits/0ce0adc0f3217741f41fd55bbeb47cb633060bf5
CI is green.

Can we merge this pull request?

**Pull request closed without merging**
