### PR TITLE
ARROW-14179: [C++][C] Do not export/import null bitmap for union and null types

### PR DESCRIPTION
**Pull request by pitrou**
Union and Null types don't support a validity bitmap according to the buffer layout spec:
https://arrow.apache.org/docs/format/Columnar.html#buffer-listing-for-each-layout

However, Arrow C++ internally stored an empty null bitmap buffer for these types.
We must therefore be careful not to export this buffer accross the C data interface.

On import, we support both layouts for compatibility.

### CODE REVIEW

**Comment by pitrou** [comment]
@zeroshade @kszucs @roee88 @jorgecarleitao  You may be interested in this.

**Comment by zeroshade** [comment]
@pitrou Thanks for the heads up!

The Go implementation already expects there to be no null bitmap for Null types on importing, and internally there is no null bitmap in the implementation of null types so #11220 implementing the exporting wouldn't include it either. So it already conforms to this.

**Comment by jorgecarleitao** [comment]
Thanks for the heads-up!

In arrow2 we are exporting the null buffer of the `Union` as a null pointer -  I did not notice that this was not in spec :/

We are importing under the same assumption:
* the 0th buffer is the validity, 
* 1st is types,
* 2nd is offsets (if sparse)

Shifting all the buffers by one in the union array from pyarrow 5 to pyarrow 6 is an issue but fortunately will not result in UB on older importers that consume a dense union:

* ignore the 0th buffer (it should read `i8`)
* interpret the 1st buffer as `i8` (it should read `i32`)

since `size_of<i8>() < size_of<i32>()`, the importer will not read out of bounds when accessing the types (and will just read wrong types).

**Comment by pitrou** [comment]
Well, on the import it's relatively easy: depending on `n_buffers` you know which format you're receiving (just like in this PR's code).

**Comment by jorgecarleitao** [comment]
Let's say that this was the other way around, i.e. that we were converting our exporters to present buffer 1 as `i8` when before was `i32`. For an array of length 10, an older importer (e.g. `pyarrow==3`) would be reading up to ` 10 * 4` bytes from that buffer (10 * size of `i32`), when the buffer only had `10` bytes (10 * size of `i8`). This is an out of bound read, which is a security vulnerability.

I was just pointing out that this change does not introduce such a vulnerability because we are moving the export from a smaller buffer (`i8`) to a larger buffer (`i32`), which makes older importers to break, but not to expose any out of bound reads.

**Comment by pitrou** [comment]
@jorgecarleitao An old importer should probably refuse an export with the wrong number of buffers.

**Comment by pitrou** [comment]
I am going to merge this.

**Pull request closed without merging**
