### PR TITLE
[Release] Release 4.0.0-RC0

### PR DESCRIPTION
**Pull request by kszucs**
Version updates and supplemental patches from RC0

### CODE REVIEW

**Comment by kszucs** [comment]
@github-actions crossbow submit --group verify-rc-source --param release=4.0.0 --param rc=0

**Comment by kszucs** [comment]
@andygrove strangely the rust verification fails with some minor `error msg` `quote escaping` `test assertion`. Could it be due to the nightly toolchain used in the verification script?

**Comment by kszucs** [comment]
@github-actions crossbow submit verify-rc-source-*-rust

**Comment by andygrove** [comment]
> @andygrove strangely the rust verification fails with some minor `error msg` `quote escaping` `test assertion`. Could it be due to the nightly toolchain used in the verification script?

I don't know for sure but that would be my guess too.

**Comment by kszucs** [comment]
@github-actions crossbow submit verify-rc-source-linux-ruby

**Comment by kszucs** [comment]
@github-actions crossbow submit --group verify-rc --param release=4.0.0 --param rc=0

**Comment by kszucs** [comment]
@github-actions crossbow submit --param release=4.0.0 --param rc=0 verify-rc-binaries-apt verify-rc-binaries-binary

**Comment by kszucs** [comment]
@github-actions crossbow submit --param release=4.0.0 --param rc=0 verify-rc-binaries-apt verify-rc-wheels-windows

**Pull request merged**
