### PR TITLE
ARROW-836: add test for pandas conversion of timedelta, currently unimplemented

### PR DESCRIPTION
**Pull request by jreback**
xref https://github.com/pandas-dev/pandas/pull/16004

### CODE REVIEW

**Comment by jreback** [comment]
so looks like this type should be added. The impl should be almost exactly like ``TimestampType`` (but no need for timezones). and the units would be exactly the same as supported by Timestamps.

**Comment by wesm** [comment]
Agreed -- we have a SQL-compliant "interval" type (https://github.com/apache/arrow/blob/master/format/Schema.fbs#L143), but no absolute timedelta. The implementation would be the same as Time (https://github.com/apache/arrow/blob/master/format/Schema.fbs#L106), though perhaps we can relax the storage constraint and use 64 bits for everything. 

Would you mind opening a JIRA and prefixing the PR title with ARROW-XXX:? thanks @jreback !

**Comment by jreback** [comment]
yes I think the current definition of ``IntervalType`` is not going to work here; that looks for year/months.

**Comment by jreback** [comment]
https://issues.apache.org/jira/browse/ARROW-835

**Comment by wesm** [comment]
Cool, as a bookkeeping matter can you also make a JIRA for this patch and update the PR title? https://github.com/apache/arrow#how-to-contribute

**Comment by jreback** [comment]
done: https://issues.apache.org/jira/browse/ARROW-836

**Review by wesm — APPROVED** [review]
+1

**Pull request closed without merging**
