### PR TITLE
ARROW-3923: [Java] JDBC Time Fetches Without Timezone

### PR DESCRIPTION
**Pull request by mikepigott**
https://issues.apache.org/jira/browse/ARROW-3923

Hello!  I was reading through the JDBC source code and I noticed that a java.util.Calendar was required for creating an Arrow Schema and Arrow Vectors from a JDBC ResultSet, when none is required.

This change makes the Calendar optional.

Unit Tests:
The existing SureFire plugin configuration uses a UTC calendar for the database, which is the default Calendar in the existing code.  Likewise, no changes to the unit tests are required to provide adequate coverage for the change.

### CODE REVIEW

**Comment by xhochy** [comment]
@jacques-n @siddharthteotia @BryanCutler Can you have a look a this?

**Comment by BryanCutler** [comment]
I'm not too familiar with this module, let's ping the original author @atuldambalkar and @laurentgo to possibly take a look

**Comment by wesm** [comment]
@siddharthteotia @laurentgo @atuldambalkar can you review?

**Comment by laurentgo** [comment]
I'll try to give a review asap, but there some danger on relying on the default timezone, especially as Arrow is fairly explicit about timezones (that said, haven't fully reviewed it yet, so might be have addressed...)

**Comment by mikepigott** [comment]
Thanks @laurentgo for taking a look!  I was looking through the Arrow code and it looks like there are various [variations on timestamp types](https://github.com/apache/arrow/blob/apache-arrow-0.11.1/java/vector/src/main/java/org/apache/arrow/vector/types/Types.java#L807-L822), and not all of them require a time zone.

The current code forces everything to UTC if a time zone isn't provided, which didn't seem right to me, because the database field itself may not have a time zone attached to it.  Likewise, it didn't seem right to enforce a time zone when Arrow didn't appear to need one.

**Comment by atuldambalkar** [comment]
Hi @mikepigott
Sorry for not reverting earlier. I looked at all the JIRAs - this one, 3965 and 3966. I understand that the fixes for 3966 which is Pull-3134 pretty much supersede earlier pull requests this one 3066 and 3133. In that I will only review Pull 3134. I hope this is okay.

**Comment by mikepigott** [comment]
Hi, 3966 supercedes 3965, but this one is independent - if this PR was rejected, I didn't want to impact those two.  Thanks for taking a look!

**Comment by atuldambalkar** [comment]
Hi @mikepigott - I looked at JDBC ResultSet API and I tend to agree with your changes and use the Calendar object if explicitly provided by the caller. Basically, in case of non-availability of Calendar object from the caller, we will be falling back to the way JDBC ResultSet API implements Date/Time related API. 

Hi @laurentgo - What's your opinion?

**Review by praveenbingo — COMMENTED** [review]
would this be backward incompatible? previously UTC would have been used and not the local calendar..

**Comment by mikepigott** [comment]
@praveenbingo - yes, you are right, this is a backwards-incompatible change.  I have a separate PR, #3965 that introduces a configuration object.  If that PR is approved before this one, I'm happy to rework this PR to use the configuration object and prevent this from being backwards-incompatible.

**Comment by praveenbingo** [comment]
@mikepigott - Done. Please go ahead with your suggestion. Thanks.

**Comment by atuldambalkar** [comment]
Sounds good @praveenbingo @mikepigott . I will take a look at PR 3966.

**Comment by mikepigott** [comment]
@praveenbingo: I have pulled in the `JdbcToArrowConfig` from master and reverted the breaking change.  This is ready for your review!

**Review by praveenbingo — APPROVED** [review]
looks good. Thanks @mikepigott 

@wesm @siddharthteotia - Could you please help merging.

**Comment by xhochy** [comment]
@siddharthdave If there are no objections from your side, I'll merge this tomorrow.

**Comment by xhochy** [comment]
Thank you @mikepigott !

**Pull request closed without merging**
