### PR TITLE
ARROW-1355: [Java] Make Arrow buildable with jdk9

### PR DESCRIPTION
**Pull request by laurentgo**
Make Arrow buildable with jdk9:
- upgrade checkstyle plugin to 6.19
- upgrade assembly plugin to 3.0.0
- update jmockit version to 1.33

Also add travis entry to build using Oracle JDK9 EA

### CODE REVIEW

**Comment by wesm** [comment]
Looks like this is failing in javadoc. As a triage you might add an option to the Java build script to disable the javadoc build

**Comment by laurentgo** [comment]
I suspect that it might be because travis ci is using an older version of the prerelease? I'll do some quick checks locally to confirm

**Comment by laurentgo** [comment]
It's actually a bug in doxia which uses an old version of commons-lang not compatible with the new version scheme for JDK introduced in Java9 (see https://issues.apache.org/jira/browse/DOXIASITETOOLS-177)

The issue is fixed, but no release has been done yet, so site won't work with jdk9 for now.

**Review by wesm — APPROVED** [review]
+1, thanks @laurentgo!

**Pull request closed without merging**
