### PR TITLE
ARROW-2250: [Python] Do not create a subprocess for plasma but just use existing process

### PR DESCRIPTION
**Pull request by mitar**

### CODE REVIEW

**Comment by mitar** [comment]
cc @robertnishihara

**Comment by wesm** [comment]
Could you explain the rationale for this change? My understanding is that the Plasma store is intended to run as a separate process; we would be remiss to be testing it operating in some other mode

**Comment by mitar** [comment]
See issue ARROW-2250. So the issue is that now you have two process when you run `plasma_store`. Outside Python process which is not doing anything else besides `wait()` on the child process. If this is so, just replace the parent with the child. So instead of two separate processes you have one. This is what you/we want.

**Comment by wesm** [comment]
I see, this only impacts the `plasma_store` executable created by distutils (https://github.com/apache/arrow/blob/master/python/setup.py#L462). OK, makes sense, thank you

**Comment by mitar** [comment]
Yes. :-)

**Review by wesm — APPROVED** [review]
+1

**Pull request closed without merging**
