### PR TITLE
ARROW-3578: [Release] Fix RAT spurious failures

### PR DESCRIPTION
**Pull request by fsaintjacques**
- Adds cpp/cmake_modules/FindArrow.cmake to excludes
- Updates source verify docker image with clang-7 support
- Improve source release script to test any hash

### CODE REVIEW

**Comment by fsaintjacques** [comment]
I ran the following (you may need to change the hash to test locally): 

`release_hash=c91e8747efd1c1cdcbac02528c6c20462c4574df dev/release/02-source.sh 0.13.0 `

**Comment by kou** [comment]
> * Adds cpp/cmake_modules/FindArrow.cmake to excludes

Why should we add this to excludes? It has correct license header. Is it a RAT tool problem?

> " Updates source verify docker image with clang-7 support
> " Improve source release script to test any hash

The changes for them are good but I think that they are not related to "Fix RAT spurious failures". Should we create another pull request(s) for them?

**Comment by fsaintjacques** [comment]
I added it to the exclude because I saw a very similar cmake files in the exclude list. Didn't investigate why it complained, opened rat.txt and turned back quickly.

I could create other PRs, but I think the change are small enough that they can be incorporated here.

**Comment by kszucs** [comment]
@fsaintjacques perhaps could You please add it to docker-compose? Then We would test it in the nightlies.

**Comment by fsaintjacques** [comment]
@kszucs there's a bit to refactor since we can't run a docker inside a docker so I'd only docker-compose 2 lines in the script. Do you want me to open a ticket for it instead of adding it here?

**Comment by kou** [comment]
I looked into this. This is caused by hard link in tar.gz.

I wrote a Ruby script to list non file/directory entries in tar.gz:

```ruby
require "zlib"
require "rubygems/package"

Zlib::GzipReader.open(ARGV[0]) do |input|
  Gem::Package::TarReader.new(input) do |reader|
    reader.each do |entry|
      case entry.header.typeflag
      when "0" # file
      when "5" # directory
      else
        p [entry.header.typeflag, entry.full_name]
      end
    end
  end
end
```

It shows the followings for apache-arrow-0.12.1.tar.gz:

```text
["1", "apache-arrow-0.12.1/cpp/cmake_modules/FindArrow.cmake"]
["L", "././@LongLink"]
...
["L", "././@LongLink"]
["1", "apache-arrow-0.12.1/python/cmake_modules/CompilerInfo.cmake"]
["1", "apache-arrow-0.12.1/python/cmake_modules/FindLLVM.cmake"]
["1", "apache-arrow-0.12.1/python/cmake_modules/FindArrowCuda.cmake"]
["1", "apache-arrow-0.12.1/python/cmake_modules/FindGFlags.cmake"]
["1", "apache-arrow-0.12.1/python/cmake_modules/FindThrift.cmake"]
["1", "apache-arrow-0.12.1/python/cmake_modules/FindLz4.cmake"]
["1", "apache-arrow-0.12.1/python/cmake_modules/FindParquet.cmake"]
["1", "apache-arrow-0.12.1/python/cmake_modules/Findjemalloc.cmake"]
["1", "apache-arrow-0.12.1/python/cmake_modules/FindSnappy.cmake"]
["1", "apache-arrow-0.12.1/python/cmake_modules/FindGPerf.cmake"]
["1", "apache-arrow-0.12.1/python/cmake_modules/SnappyConfig.h"]
["1", "apache-arrow-0.12.1/python/cmake_modules/FindFlatbuffers.cmake"]
["1", "apache-arrow-0.12.1/python/cmake_modules/FindClangTools.cmake"]
["1", "apache-arrow-0.12.1/python/cmake_modules/FindZLIB.cmake"]
["1", "apache-arrow-0.12.1/python/cmake_modules/UseCython.cmake"]
["1", "apache-arrow-0.12.1/python/cmake_modules/FindPythonLibsNew.cmake"]
["1", "apache-arrow-0.12.1/python/cmake_modules/BuildUtils.cmake"]
["1", "apache-arrow-0.12.1/python/cmake_modules/FindGTest.cmake"]
["1", "apache-arrow-0.12.1/python/cmake_modules/FindGLOG.cmake"]
["1", "apache-arrow-0.12.1/python/cmake_modules/FindZSTD.cmake"]
["1", "apache-arrow-0.12.1/python/cmake_modules/FindGBenchmark.cmake"]
["1", "apache-arrow-0.12.1/python/cmake_modules/FindBz2.cmake"]
["1", "apache-arrow-0.12.1/python/cmake_modules/ThirdpartyToolchain.cmake"]
["1", "apache-arrow-0.12.1/python/cmake_modules/FindInferTools.cmake"]
["1", "apache-arrow-0.12.1/python/cmake_modules/FindPlasma.cmake"]
["1", "apache-arrow-0.12.1/python/cmake_modules/san-config.cmake"]
["1", "apache-arrow-0.12.1/python/cmake_modules/FindProtobuf.cmake"]
["1", "apache-arrow-0.12.1/python/cmake_modules/FindGandiva.cmake"]
["1", "apache-arrow-0.12.1/python/cmake_modules/SnappyCMakeLists.txt"]
["1", "apache-arrow-0.12.1/python/cmake_modules/FindNumPy.cmake"]
["1", "apache-arrow-0.12.1/python/cmake_modules/FindRE2.cmake"]
["1", "apache-arrow-0.12.1/python/cmake_modules/SetupCxxFlags.cmake"]
["1", "apache-arrow-0.12.1/python/cmake_modules/FindArrow.cmake"]
["1", "apache-arrow-0.12.1/python/cmake_modules/FindBrotli.cmake"]
```

"L" typeflag in tar means the next entry has long name. So we can ignore it.

"1" typeflag in tar means hard link. So we can remove needless entries from `rat_exclude_files.txt` by resolving hard links. We can do this by `--hard-dereferences` option in GNU tar. (But BSD tar doesn't have the option.)

So this fix isn't suitable. I'll create a pull request to resolve hard links.

@fsaintjacques Could you open JIRA issues for `release_hash` and `dev/release/source/Dockerfile` and resend pull requests for them?

**Comment by fsaintjacques** [comment]
@kou done via https://github.com/apache/arrow/pull/4031

**Comment by fsaintjacques** [comment]
and https://github.com/apache/arrow/pull/4032

**Pull request closed without merging**
