### PR TITLE
ARROW-11633: [CI][Doc] Maven default skin not found

### PR DESCRIPTION
**Pull request by kszucs**
Trying to fix documentation build via disabling mvn HTTP pooling.

### CODE REVIEW

**Comment by kszucs** [comment]
@github-actions crossbow submit test-ubuntu-20.10-docs

**Comment by westonpace** [comment]
You might try the less extreme version first (although that would require upgrading to Maven 3.6.3)

**Comment by kszucs** [comment]
@github-actions crossbow submit test-ubuntu-20.10-docs

**Review by kszucs — COMMENTED** [review]
+1

**Pull request closed without merging**
