### PR TITLE
WIP: DO NOT MERGE: Apache Arrow Flight SQL adapter for PostgreSQL plan

### PR DESCRIPTION
**Pull request by kou**
This is a document to discuss this project.

See
https://github.com/kou/arrow/blob/flight-sql-postgresql/flight-sql-postgresql.md for rendered version.

### CODE REVIEW

**Comment by alamb** [comment]
Thank you for starting this discussion @kou  -- we are interested in this feature at InfluxData and we may have some more detail to share soon.

**Comment by jacobmarble** [comment]
I'm also curious about use cases. Deployed [PostgreSQL FE/BE](https://www.postgresql.org/docs/15/protocol.html) clients number in the zillions, so there would seem to be more interest in a proxy enabling those applications to use FlightSQL services.

**Comment by kou** [comment]
@alamb @jacobmarble Thanks for your comments!

> It might help to start this document with an expected usecase.

It makes sense. I'll add it.

> I originally thought it was to allow clients that spoke the postgres (front-end / back-end protocol) protocol to connect to a FlightSQL server
>
> But now it is primarily to allow clients that speak FlightSQL to speak directly to a posgres server

Ah, sorry. Your understanding is correct. I didn't think the use case. I think that we cover this use case by ADBC. (cc: @lidavidm)

Is PostgreSQL protocol important in your use case? ADBC isn't suitable?

BTW, I think that the approach you mentioned has serialize/deserialize overhead that Apache Arrow project wants to eliminate.

**Comment by lidavidm** [comment]
Yes, the ADBC driver wraps libpq and should let you work with other databases that use the PostgreSQL wire protocol, with the caveat that it has to convert the data (of course). 

Both tools serve complementary purposes: as you mention, there are many projects besides PostgreSQL that use its wire protocol. The ADBC driver provides access to them. At the same time, PostgreSQL and its derivatives are quite popular. The hope is that by pushing the conversion onto the server and using columnar data/Arrow for transport and at the edge, we can achieve better performance overall for clients that want Arrow data. 

I suppose you have a third goal: using the PostgreSQL protocol/drivers/clients as the lingua franca, placing it sort of in between the roles of Flight SQL and JDBC/ODBC? I don't think anyone's actively working towards that.

**Comment by bkmgit** [comment]
What is needed for authentication? Could pluggable authentication modules be used?  How often could authentication be required - in particular are there performance requirements?

**Comment by kou** [comment]
> What is needed for authentication?

Integration with user information in PostgreSQL. We should not require users to configure additional authentication related things.

> Could pluggable authentication modules be used?

I think that we shouldn't do it. We should only use information in PostgreSQL. 

> How often could authentication be required - in particular are there performance requirements?

Always. All connections must be associated with an user.

**Comment by alamb** [comment]
> Ok. And those clients use the wire protocol directly(ish), so they can't take advantage of the JDBC or ODBC Flight SQL drivers, presumably?

That is correct. In the ideal future world, it will be FlightSQL (via ADBC perhaps or native support) all the way down. Until we get there it is important to work with the existing ecosystem

> ADBC may not help there, unless they're using DBAPI/SQLAlchemy in Python, where the ADBC bindings implement DBAPI and work(ish) with the rest of the stack.

👍

**Comment by kou** [comment]
I've added use cases:

* https://github.com/kou/arrow/blob/flight-sql-postgresql/flight-sql-postgresql.md#use-cases
* https://github.com/apache/arrow/pull/33716/commits/3ed670e9cc5e8d88af969963fe0ae7dc28212e15

> * ETL
> * Interactive/exploratory data analysis

**Comment by kou** [comment]
I've created https://github.com/apache/arrow-flight-sql-postgresql .

**Pull request closed without merging**
