### PR TITLE
ARROW-2071: [Python] Fix test slowness on Travis-CI

### PR DESCRIPTION
**Pull request by pitrou**
The pytorch build from the "soumith" channel can be buggy and fail importing with a symbol error.  In that case avoid trying "import torch" extremely often as this spends CPU time in the dynamic loader.

Also lighten the plasma tests when run with Valgrind.

The main offending job is down to 29 minutes, with 2 minutes being taken by the Python tests.

### CODE REVIEW

**Review by wesm — APPROVED** [review]
+1, thanks for digging through this and also silencing various installations. Will merge once build passes

**Comment by wesm** [comment]
The pytorch conda packages are enormous. How important is it that we test this on each CI build (versus in some kind of nightly integration test)?

```
The following packages will be downloaded:
    package                    |            build
    ---------------------------|-----------------
    libgcc-5.2.0               |                0         1.1 MB  defaults
    pillow-5.0.0               |           py27_0         958 KB  conda-forge
    libtiff-4.0.9              |                0         511 KB  conda-forge
    libtorch-0.1.12            |          nomkl_0         1.7 MB  defaults
    olefile-0.44               |           py27_0          50 KB  conda-forge
    torchvision-0.1.9          |   py27hdb88a65_1          86 KB  soumith
    openblas-0.2.19            |                2        14.1 MB  conda-forge
    numpy-1.13.1               |py27_blas_openblas_200         8.4 MB  conda-forge
    pytorch-0.2.0              |py27ha262b23_4cu75       312.2 MB  soumith
    mkl-2017.0.3               |                0       129.5 MB  defaults
    ------------------------------------------------------------
                                           Total:       468.6 MB
```

cc @cpcloud @robertnishihara @pcmoritz

**Comment by wesm** [comment]
I opened https://issues.apache.org/jira/browse/ARROW-2093

**Comment by wesm** [comment]
pytorch also seems to be overriding the `nomkl` metapackage

**Comment by robertnishihara** [comment]
@wesm Some sort of nightly CI would be sufficient.

**Comment by robertnishihara** [comment]
@pitrou nice job tracking this down! So the reason the serialization tests were so slow was the repeated attempts to do `import pytorch`? That's a little surprising.

**Comment by pitrou** [comment]
@robertnishihara Yes. I've kept the `perf` data around:
```
# Children      Self  Command        Shared Object                                     Symbol                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
#
    40.96%    40.93%  py.test        ld-2.23.so                                        [.] do_lookup_x
    25.17%    25.15%  py.test        ld-2.23.so                                        [.] strcmp
    15.91%    15.90%  py.test        ld-2.23.so                                        [.] check_match
    13.87%     0.00%  py.test        libdl-2.23.so                                     [.] dlopen_doit
    13.87%     0.00%  py.test        [unknown]                                         [.] 0x00007ffd98ad0699
    13.80%     0.01%  py.test        ld-2.23.so                                        [.] _dl_catch_error
    13.79%     0.00%  py.test        ld-2.23.so                                        [.] dl_open_worker
    13.69%     2.78%  py.test        ld-2.23.so                                        [.] _dl_relocate_object
    10.65%    10.51%  py.test        ld-2.23.so                                        [.] _dl_lookup_symbol_x
```

**Comment by wesm** [comment]
That's pretty crazy. Nice detective work =)

**Pull request closed without merging**
