### PR TITLE
ARROW-8369: [CI] Fix crossbow wildcard groups

### PR DESCRIPTION
**Pull request by nealrichardson**

### CODE REVIEW

**Comment by nealrichardson** [comment]
@github-actions crossbow submit -g r

**Comment by nealrichardson** [comment]
@github-actions crossbow submit -g r

**Comment by nealrichardson** [comment]
@github-actions crossbow submit -g nightly

**Comment by nealrichardson** [comment]
@kszucs @wesm A few things I've noticed:

1. Apparently you can't start a glob with `*`. Maybe that's a yaml thing? Maybe not. Didn't try to debug.
2. If you have a group that has a glob pattern and then something else, only the first glob is used. In the R task list above, there are two entries in the group definition, and the second one (`macos-r-autobrew`) was not included.
3. The nightly group fails (see [here](https://github.com/apache/arrow/runs/569544168?check_suite_focus=true)), my guess is that the greedy pattern matching is pulling in jobs that we weren't including previously and that don't actually work.
4. Y'all should do an audit of what's included and what isn't. I fixed a handful of discrepancies between what was run before and what is being run now (assuming of course that they run), but there may be more. And as (3) suggests, there may be stale, broken tasks in the yaml that should be cleaned out.

**Comment by wesm** [comment]
Maybe this is a good opportunity to bootstrap a small unit test suite

**Comment by kszucs** [comment]
> @kszucs @wesm A few things I've noticed:
> 
> 1. Apparently you can't start a glob with `*`. Maybe that's a yaml thing? Maybe not. Didn't try to debug.
Yes, that is reserved for YAML anchors. If use enclose it with quotes then yaml will treat it as string so it will work.
> 2. If you have a group that has a glob pattern and then something else, only the first glob is used. In the R task list above, there are two entries in the group definition, and the second one (`macos-r-autobrew`) was not included.
That's because I renamed `macos-r-autobrew`  to `homebrew-r-autobrew` ala the existsing `homebrew-cpp-autobrew` - so `macos-r-autobrew` doesn't exists anymore.
> 3. The nightly group fails (see [here](https://github.com/apache/arrow/runs/569544168?check_suite_focus=true)), my guess is that the greedy pattern matching is pulling in jobs that we weren't including previously and that don't actually work.
I'm investigating this.
> 4. Y'all should do an audit of what's included and what isn't. I fixed a handful of discrepancies between what was run before and what is being run now (assuming of course that they run), but there may be more. And as (3) suggests, there may be stale, broken tasks in the yaml that should be cleaned out.
I'm trying to add a subcommand to validate the configuration.

**Comment by nealrichardson** [comment]
Re: validation, I agree with @wesm that this sounds like something that belongs in a test suite. Make sure that all groups refer to tasks that exist, and make sure that all tasks render their templates without error.

**Comment by kszucs** [comment]
I've added logic to test the configuration in #6875 I'll implement proper unittests for crossbow once I port it to archery.

**Comment by kszucs** [comment]
@github-actions crossbow submit --dry-run -g r

**Review by kszucs — APPROVED** [review]

**Pull request closed without merging**
