### PR TITLE
ARROW-14606: [CI] PYARROW_TEST_S3_REGION other than us-east-1 breaks tests

### PR DESCRIPTION
**Pull request by jeszyb**
Pass the specified region to the test.

### CODE REVIEW

**Comment by pitrou** [comment]
This is changing the intent of the test: see https://issues.apache.org/jira/browse/ARROW-11235

**Comment by jeszyb** [comment]
Thanks for the review @pitrou. IIUC the original intent was to ensure that `fs` ends up being valid which will still be true iff the provided test region is correct. Ensuring that tests pass while changing regions reduces maintenance burden. Maybe I'm missing something?

**Comment by pitrou** [comment]
The test is checking that `S3FileSystem(anonymous=True)` is correctly able to infer a region. Your change makes this idiom untested.

**Comment by jeszyb** [comment]
Got it. Thanks again @pitrou , will find another way to solve this. Closing.

**Pull request closed without merging**
