### PR TITLE
ARROW-6318: [Integration] Run tests against pregenerated files

### PR DESCRIPTION
**Pull request by emkornfield**
- Updates testing module to point to latest master which contains files
- Refactors integration tests:
  - Move skips to use the build in skip functionality
  - generalize compare_implementation to a take a function to run tests

We could potentially provide more metadata as part of the checked in files, as this change relies a little too much on file name convention, but it does the jobs.

### CODE REVIEW

**Comment by emkornfield** [comment]
Personal travis CI run: https://travis-ci.org/emkornfield/arrow/jobs/580759660

**Comment by wesm** [comment]
Cool, looks good to me. We need to remove the use of `--gold_dirs` from the integration test Travis script before merging

**Comment by emkornfield** [comment]
> We need to remove the use of --gold_dirs from the integration test Travis script before merging

Don't we want to run this as part of travis?  Could you elaborate?

**Comment by wesm** [comment]
I see, I thought this parameter was exclusive with the endogenous tests.

**Review by wesm — APPROVED** [review]
+1. I think soon we should refactor integration_test.py into a small Python package

**Comment by wesm** [comment]
https://issues.apache.org/jira/browse/ARROW-6466

**Pull request closed without merging**
