### PR TITLE
ARROW-4634: [Rust] [Parquet] Reorganize test_common

### PR DESCRIPTION
**Pull request by liurenjie1024**
Currently test_common mod is just one file, and when we need to add more test utils into it, things may messed up, so I propose to make test_common a directory with multi sub mods.

@andygrove @sunchao Please help to review this.

### CODE REVIEW

**Comment by liurenjie1024** [comment]
@andygrove @sunchao Could you please help to review this? It's a small refactor, but blocking the parquet arrow reader.

**Review by sunchao — APPROVED** [review]
LGTM

**Review by nevi-me — APPROVED** [review]

**Comment by liurenjie1024** [comment]
@wesm @andygrove We've got two LGTMs, help to merge this?

**Comment by wesm** [comment]
@sunchao is a committer... are you set up to merge patches?

**Comment by sunchao** [comment]
@wesm sorry I haven't setup this yet (just know I can merge patches now). Will explore how to do it.

**Pull request closed without merging**
