### PR TITLE
ARROW-5963: [R] R Appveyor job does not test changes in the C++ library

### PR DESCRIPTION
**Pull request by nealrichardson**
This changes the PKGBUILD script to use the local checkout to build the C++ library.

### CODE REVIEW

**Comment by nealrichardson** [comment]
Here's a passing appveyor build: https://ci.appveyor.com/project/nealrichardson/arrow/builds/26053084

**Review by wesm — APPROVED** [review]
+1. Probably want to rename this PKGBUILD file to something more descriptive, but can do that another time

**Comment by nealrichardson** [comment]
It's not a name of my choosing, it's what they're called everywhere: https://wiki.archlinux.org/index.php/PKGBUILD

cf. https://github.com/msys2/MINGW-packages

**Comment by wesm** [comment]
Right, but you copy it here

https://github.com/apache/arrow/blob/master/ci/appveyor-build-r.sh#L42

so you could call it `PKGBUILD_MINGW` or something to people understand what it is by the name

**Pull request closed without merging**
