### PR TITLE
ARROW-3546: [Python] Provide testing setup to verify wheel binaries work in one or more common Linux distributions

### PR DESCRIPTION
**Pull request by kszucs**
Waiting for [build-349](https://github.com/kszucs/crossbow/branches/all?utf8=%E2%9C%93&query=build-349)

### CODE REVIEW

**Comment by wesm** [comment]
So the problem with this is that the build environment and the test environment are the same. Would this have caught ARROW-3514?

**Comment by wesm** [comment]
Oh I see it's a different environment. We need to demonstrate that the ARROW-3514 bug reproduces

**Comment by kszucs** [comment]
I've tried it locally:

```bash
$ docker run -it python:3.6-slim bash
root@cf561b62da5a:/# pip install pyarrow
root@cf561b62da5a:/# python
```
```python
Python 3.6.6 (default, Oct 16 2018, 07:20:07)
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import io
>>> import pyarrow as pa
>>> import pyarrow.parquet as pq
>>>
>>> table = pa.Table.from_arrays([pa.array(['abc', 'def'])], ['some_col'])
>>> f = io.BytesIO()
>>> pq.write_table(table, f, compression='gzip')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/pyarrow/parquet.py", line 1125, in write_table
    writer.write_table(table, row_group_size=row_group_size)
  File "/usr/local/lib/python3.6/site-packages/pyarrow/parquet.py", line 376, in write_table
    self.writer.write_table(table, row_group_size=row_group_size)
  File "pyarrow/_parquet.pyx", line 934, in pyarrow._parquet.ParquetWriter.write_table
  File "pyarrow/error.pxi", line 83, in pyarrow.lib.check_status
pyarrow.lib.ArrowIOError: Arrow error: IOError: zlib deflate failed, output buffer too small
```

**Comment by wesm** [comment]
OK, great, thank you!

**Comment by kszucs** [comment]
I've removed the centos test images because there is a total `u vs mu` chaos in dockerland.

**Review by wesm — APPROVED** [review]
+1, this looks great, thank you!

**Pull request closed without merging**
