### PR TITLE
GH-40174: [C++][CI][Parquet] Fixing parquet column_writer_test building

### LINKED ISSUE #40174: [CI][C++][Parquet] test-build-vcpk-win is failing with: 'ThrowsMessage': is not a member of 'testing'
### Describe the bug, including details regarding any error messages, version, and platform.

The [test-build-vcpkg-win](https://github.com/ursacomputing/crossbow/actions/runs/7981983646/job/21794701691) has been failing with the following error:
```
D:/a/crossbow/crossbow/arrow/cpp/src/parquet/column_writer_test.cc(486,18): error C2039: 'ThrowsMessage': is not a member of 'testing' [D:\a\crossbow\crossbow\arrow\cpp\build\src\parquet\parquet-writer-test.vcxproj]
D:/a/crossbow/crossbow/arrow/cpp/vcpkg_installed/x64-windows/include\gmock/gmock.h(71): message : see declaration of 'testing' [D:\a\crossbow\crossbow\arrow\cpp\build\src\parquet\parquet-writer-test.vcxproj]
D:/a/crossbow/crossbow/arrow/cpp/src/parquet/column_writer_test.cc(486,1): error C2873: 'ThrowsMessage': symbol cannot be used in a using-declaration [D:\a\crossbow\crossbow\arrow\cpp\build\src\parquet\parquet-writer-test.vcxproj]
D:/a/crossbow/crossbow/arrow/cpp/src/parquet/column_writer_test.cc(921,1): error C2065: 'ThrowsMessage': undeclared identifier [D:\a\crossbow\crossbow\arrow\cpp\build\src\parquet\parquet-writer-test.vcxproj]
D:/a/crossbow/crossbow/arrow/cpp/src/parquet/column_writer_test.cc(921,1): error C2275: 'parquet::ParquetException': illegal use of this type as an expression [D:\a\crossbow\crossbow\arrow\cpp\build\src\parquet\parquet-writer-test.vcxproj]
D:\a\crossbow\crossbow\arrow\cpp\src\parquet/exception.h(87): message : see declaration of 'parquet::ParquetException' [D:\a\crossbow\crossbow\arrow\cpp\build\src\parquet\parquet-writer-test.vcxproj]
D:/a/crossbow/crossbow/arrow/cpp/src/parquet/column_writer_test.cc(921,1): error C2672: 'testing::internal::MakePredicateFormatterFromMatcher': no matching overloaded function found [D:\a\crossbow\crossbow\arrow\cpp\build\src\parquet\parquet-writer-test.vcxproj]
D:/a/crossbow/crossbow/arrow/cpp/src/parquet/column_writer_test.cc(921,1): error C2737: 'gtest_ar': const object must be initialized [D:\a\crossbow\crossbow\arrow\cpp\build\src\parquet\parquet-writer-test.vcxproj]
D:/a/crossbow/crossbow/arrow/cpp/src/parquet/column_writer_test.cc(925,1): error C2065: 'ThrowsMessage': undeclared identifier [D:\a\crossbow\crossbow\arrow\cpp\build\src\parquet\parquet-writer-test.vcxproj]
D:/a/crossbow/crossbow/arrow/cpp/src/parquet/column_writer_test.cc(925,1): error C2275: 'parquet::ParquetException': illegal use of this type as an expression [D:\a\crossbow\crossbow\arrow\cpp\build\src\parquet\parquet-writer-test.vcxproj]
D:\a\crossbow\crossbow\arrow\cpp\src\parquet/exception.h(87): message : see declaration of 'parquet::ParquetException' [D:\a\crossbow\crossbow\arrow\cpp\build\src\parquet\parquet-writer-test.vcxproj]
D:/a/crossbow/crossbow/arrow/cpp/src/parquet/column_writer_test.cc(925,1): error C2672: 'testing::internal::MakePredicateFormatterFromMatcher': no matching overloaded function found [D:\a\crossbow\crossbow\arrow\cpp\build\src\parquet\parquet-writer-test.vcxproj]
D:/a/crossbow/crossbow/arrow/cpp/src/parquet/column_writer_test.cc(925,1): error C2737: 'gtest_ar': const object must be initialized [D:\a\crossbow\crossbow\arrow\cpp\build\src\parquet\parquet-writer-test.vcxproj]
D:/a/crossbow/crossbow/arrow/cpp/src/parquet/column_writer_test.cc(933,1): error C2065: 'ThrowsMessage': undeclared identifier [D:\a\crossbow\crossbow\arrow\cpp\build\src\parquet\parquet-writer-test.vcxproj]
D:/a/crossbow/crossbow/arrow/cpp/src/parquet/column_writer_test.cc(933,1): error C2275: 'parquet::ParquetException': illegal use of this type as an expression [D:\a\crossbow\crossbow\arrow\cpp\build\src\parquet\parquet-writer-test.vcxproj]
D:\a\crossbow\crossbow\arrow\cpp\src\parquet/exception.h(87): message : see declaration of 'parquet::ParquetException' [D:\a\crossbow\crossbow\arrow\cpp\build\src\parquet\parquet-writer-test.vcxproj]
D:/a/crossbow/crossbow/arrow/cpp/src/parquet/column_writer_test.cc(933,1): error C2672: 'testing::internal::MakePredicateFormatterFromMatcher': no matching overloaded function found [D:\a\crossbow\crossbow\arrow\cpp\build\src\parquet\parquet-writer-test.vcxproj]
D:/a/crossbow/crossbow/arrow/cpp/src/parquet/column_writer_test.cc(933,1): error C2737: 'gtest_ar': const object must be initialized [D:\a\crossbow\crossbow\arrow\cpp\build\src\parquet\parquet-writer-test.vcxproj]
```
This is also happening on the 15.0.1 maintenance branch.
It is related to this change: https://github.com/apache/arrow/commit/5d7f66190eec05f4fc0b9a1a17635ca6c68c828f

### Component(s)

C++, Continuous Integration, Parquet

### PR DESCRIPTION
**Pull request by mapleFU**
### Rationale for this change

Remove `ThrowsMessage` for CI build.

### What changes are included in this PR?

Remove `ThrowsMessage` for CI build.

### Are these changes tested?

no need

### Are there any user-facing changes?

no

* Closes: #40174

### CODE REVIEW

**Comment by mapleFU** [comment]
@raulcd how can I test the specific case? (I don't have windows machine by myside)

**Comment by raulcd** [comment]
You can trigger the crossbow build via `@github-actions crossbow submit test-build-vcpkg-win`

**Comment by mapleFU** [comment]
@github-actions crossbow submit test-build-vcpkg-win

**Review by raulcd — COMMENTED** [review]
The change is fixing the build so I am :+1: but better to get a review from someone with better C++ skills than me :)

**Comment by mapleFU** [comment]
https://github.com/google/googletest/blob/5df0241ea4880e5a846775d3efc8b873f7b36c31/googlemock/include/gmock/gmock-matchers.h#L5426

Guess it's a library version problem because it rely on ThrowsMessage ...

**Comment by raulcd** [comment]
It seems we have been pinning gtest on this build for a really long time:
https://github.com/apache/arrow/pull/10306
https://github.com/apache/arrow/blob/main/cpp/vcpkg.json#L55

We probably could try to update that.

**Comment by raulcd** [comment]
> We probably could try to update that.

Probably opening a different issue, not necessarily here

**Review by pitrou — APPROVED** [review]
Interesting. Perhaps `GTEST_HAS_EXCEPTIONS` is disabled in some configurations. Regardless, thanks for the fix.

**Pull request merged**
