### PR TITLE
ARROW-202: Integrate with appveyor ci for windows

### PR DESCRIPTION
**Pull request by xhochy**
This only adds yet a successful compilation for windows. Tests don't
run.

### CODE REVIEW

**Comment by xhochy** [comment]
Head over to https://github.com/xhochy/arrow/pull/2 to see Appveyor in action.

**Comment by wesm** [comment]
nice! I admit I have not been looking forward to adding Windows compatibility, but it will help a lot with uptake

**Comment by xhochy** [comment]
As I'm neither a windows user, I may not get this running. But I have a bit of hope that once we got Arrow building for Windows, it will be a lot easier for someone to actually contribute the missing pieces to have it running on Windows.

**Comment by wesm** [comment]
I have access to a Windows machine with VS 2015, so I can help with debugging / trying things out as a user

**Comment by xhochy** [comment]
This is now in a state where the PR could be merged.

I also updated the reference in LICENSE and NOTICE for `cpp/cmake_modules/CompilerInfo.cmake` to Kudu and used the more verbose style as seen in the parquet-mr license references.

**Comment by wesm** [comment]
+1

**Pull request closed without merging**
