### PR TITLE
ARROW-2310: First commit for addressing javadoc warnings

### PR DESCRIPTION
**Pull request by renato2099**
First commit for addressing javadoc warnings

### CODE REVIEW

**Comment by wesm** [comment]
Javadoc warnings on the Flatbuffers-generated classes should be ignored. Can you open an issue upstream in google/flatbuffers about fixing this?

**Comment by renato2099** [comment]
ok let's see if we can get some help from them :)

**Comment by wesm** [comment]
@siddharthteotia looks like we have some progress on warnings here

**Comment by wesm** [comment]
Closing this as @BryanCutler has been working on in patches the last few weeks, feel free to discuss w/ bryan and help with patches there

**Pull request closed without merging**
