### PR TITLE
GH-38811: [R] Actually use fetched cmake on macos

### LINKED ISSUE #38811: [R] cmake download doesn't work on macOS
### Describe the bug, including details regarding any error messages, version, and platform.

When downloading from https://github.com/Kitware/CMake/releases/download/v3.26.4/cmake-3.26.4-macos-universal.tar.gz in nixlibs.R, this will result in a `CMake.app` being located on the path, we need to add on to the path `CMake.app/Contents/bin/` instead of just `bin`

### Component(s)

R

### PR DESCRIPTION
**Pull request by jonkeane**
### Rationale for this change

We sometimes need to use a more modern cmake, before this change although we downloaded a functioning cmake on macos, we didn't have the correct path for it. 

### What changes are included in this PR?

Resolves #38811 so that cmake is useable when downloaded on macos. This also restores the local source build jobs to be testing that source builds work (which is what the Ci jobs say they are doing). I believe these jobs started using binaries when we overhauled the build system last release.

### Are these changes tested?

Yes, in CI with the local (source) install jobs in crossbow)

### Are there any user-facing changes?

* Closes: #38811

### CODE REVIEW

**Comment by jonkeane** [comment]
@github-actions crossbow submit test-r-install-local

**Comment by jonkeane** [comment]
@github-actions crossbow submit test-r-install-local

**Comment by jonkeane** [comment]
@github-actions crossbow submit test-r-install-local

**Review by assignUser — APPROVED** [review]
Nice, thanks for fixing that. The different bin location might also be the reason for the download even happening despite cmake being installed?

**Comment by assignUser** [comment]
> I believe these jobs started using binaries when we overhauled the build system last release.

Ah good catch!

**Comment by assignUser** [comment]
I'll merge & cherry pick this into the cran branch later today(friday).

**Comment by jonkeane** [comment]
> The different bin location might also be the reason for the download even happening despite cmake being installed?

I don't think this is what's happening. We do `Sys.which("cmake")` (among other ways) to try and find it, which should find it if it's on the path correctly. I guess it's possible that the cmake installation instructions might lead to someone doing something like putting the cmake.app on their path and not the bin dir inside, but that's effectively not installed given paths + shells (and would be a cmake issue upstream if it were true)

**Pull request merged**
