### PR TITLE
ARROW-922: Allow Flatbuffers and RapidJSON to be used locally on Windows

### PR DESCRIPTION
**Pull request by cpcloud**

### CODE REVIEW

**Review by wesm — APPROVED** [review]
+1, merge on green build. @kou there's a glib test failure here, seems unrelated if you want to take a look

**Comment by cpcloud** [comment]
@wesm This is green on appveyor.

**Comment by kou** [comment]
It's not related this change. We can merge this change.

I'll submit a pull request to fix the test failure.

**Comment by kou** [comment]
#622 will fix the test failure.

**Pull request closed without merging**
