### PR TITLE
ARROW-5710: [C++] Allow compiling Gandiva with Ninja on Windows

### PR DESCRIPTION
**Pull request by pitrou**
Ninja is faster than msbuild, especially in combination with clcache.

### CODE REVIEW

**Comment by pitrou** [comment]
Toolchain job took 17 minutes here: https://ci.appveyor.com/project/pitrou/arrow/builds/25502434 (as opposed to 30+ minutes with `msbuild`).

**Comment by wesm** [comment]
manylinux1 appears to have barfed on this, perhaps due to an ancient Python in the Docker image

```
cd /tmp/build-PY3.6-16/src/gandiva/precompiled && python /arrow/cpp/src/gandiva/precompiled/../make_precompiled_bitcode.py /arrow/cpp/src/gandiva/precompiled_bitcode.cc.in /tmp/build-PY3.6-16/src/gandiva/irhelpers.bc /tmp/build-PY3.6-16/src/gandiva/precompiled_bitcode.cc
  File "/arrow/cpp/src/gandiva/precompiled/../make_precompiled_bitcode.py", line 22
    marker = b"<DATA_CHARS>"
                           ^
SyntaxError: invalid syntax
```

**Comment by pitrou** [comment]
Indeed... it's Python 2.4 :-o

**Comment by pitrou** [comment]
AppVeyor build: https://ci.appveyor.com/project/pitrou/arrow/builds/25521383

**Pull request closed without merging**
