### PR TITLE
ARROW-7466: [CI][Java] Fix gandiva-jar-osx nightly build failure

### PR DESCRIPTION
**Pull request by projjal**

### CODE REVIEW

**Comment by wesm** [comment]
Does this solve the issue or...?

**Comment by projjal** [comment]
> Does this solve the issue or...?

Its still failing. From the build log it seems its still picking jdk13 despite setting the JDK version to 11 in the travis config. I am looking into this.

**Comment by wesm** [comment]
I see. We should probably move this job off of Travis at some point. Does setting JAVA_HOME explicitly work?

**Comment by projjal** [comment]
> I see. We should probably move this job off of Travis at some point. Does setting JAVA_HOME explicitly work?

Fixed it in https://github.com/apache/arrow/pull/6099.

**Pull request closed without merging**
