### PR TITLE
ARROW-4086: [WIP] [Java] Add apis for summary of root allocator

### PR DESCRIPTION
**Pull request by pravindra**

### CODE REVIEW

**Comment by pravindra** [comment]
@vancobuca @siddharthteotia @praveenbingo

**Review by icexelloss — APPROVED** [review]
LGTM

**Comment by jacques-n** [comment]
A few thoughts:
* Do we really need to expose root allocator? 
* What do you think about have a summary object as opposed to a string? That way people can choose how to present it.
* How do I know what the current allocator is at?
* How do I ask for the summary from my current node up to level X? For example, if we have 5 levels of allocators and a rejection happens due to a limit at the 3rd level, it would be useful when that allocation fails to report the tree for 3..5. How would we do that?

**Comment by pravindra** [comment]
> A few thoughts:
> 
> * Do we really need to expose root allocator?
> * What do you think about have a summary object as opposed to a string? That way people can choose how to present it.
> * How do I know what the current allocator is at?
> * How do I ask for the summary from my current node up to level X? For example, if we have 5 levels of allocators and a rejection happens due to a limit at the 3rd level, it would be useful when that allocation fails to report the tree for 3..5. How would we do that?

you are right, my fix doesn't address this. Instead, I can add APIs for 
1. getParentAllocator()
2. getChildAllocators() -> may return null if DEBUG is false

It will be easy to build code outside the allocator for multiple scenarios including -
a. walk upto root, and dump summary for N levels below
b. walk upto first ascendant who is over-limit, and dump summary for N levels below
c. walk upto first ascendant who is over-limit, and dump summary for all levels from that ascendant to the current allocator.

Does that look reasonable ?

**Comment by pravindra** [comment]
I'm going to redo this change with more precise information being returned in the exception.

**Comment by emkornfield** [comment]
@pravindra did you ever get around to making the update?  What are the next steps here?

**Comment by pravindra** [comment]
> @pravindra did you ever get around to making the update? What are the next steps here?

I didn't make the changes yet. I'll work on this next week.

**Comment by pravindra** [comment]
abandoning this PR since the code has changed a lot since then. I'll open a fresh PR.

**Pull request closed without merging**
