### PR TITLE
ARROW-9766: [C++][Parquet] Add EngineVersion for toggling between new and old logic

### PR DESCRIPTION
**Pull request by emkornfield**

### CODE REVIEW

**Comment by pitrou** [comment]
Is there a reason to introduce this and burden the API with a new setting? If the "new" engine supports a superset of what the current engine supports, then it seems it should just replace the current engine.

**Comment by emkornfield** [comment]
@pitrou that is the plan, but since there will be a decent amount of new code, I think it is worth-while to provide the option.  Once the new engine is implemented that will become the default.  

FWIW, I took a similar approach with supporting nested writes as well.

**Comment by emkornfield** [comment]
actually, change might be invasive enough that this probably won't mitigate risk, we can hold off until I get a little further.

**Comment by emkornfield** [comment]
Going to close this as its been demonstrated existing implementations probably have bugs so, I'm going to focus on a replacing instead of adding code.

**Pull request closed without merging**
