### PR TITLE
WIP: [Release] Verify release-10.0.0-rc0

### PR DESCRIPTION
**Pull request by kou**
PR to verify Release Candidate

### CODE REVIEW

**Comment by kou** [comment]
@github-actions crossbow submit  --group verify-rc-source --param release=10.0.0 --param rc=0

**Comment by kou** [comment]
Revision: 89f9a0948961f6e94f1ef5e4f310b707d22a3c11

Submitted crossbow builds: [ursacomputing/crossbow @ release-10.0.0-rc0-0](https://github.com/ursacomputing/crossbow/branches/all?query=release-10.0.0-rc0-0)

|Task|Status|
|----|------|
|almalinux-8-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/3293273243/jobs/5429596033)|
|almalinux-8-arm64|[Travis CI](https://github.com/ursacomputing/crossbow/runs/9018322965)|
|almalinux-9-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/3293277144/jobs/5429604499)|
|almalinux-9-arm64|[Travis CI](https://github.com/ursacomputing/crossbow/runs/9018309857)|
|amazon-linux-2-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/3293275375/jobs/5429600755)|
|amazon-linux-2-arm64|[Travis CI](https://github.com/ursacomputing/crossbow/runs/9018303115)|
|centos-7-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/3293282507/jobs/5429616198)|
|centos-8-stream-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/3293283325/jobs/5429617749)|
|centos-8-stream-arm64|[Travis CI](https://github.com/ursacomputing/crossbow/runs/9018341062)|
|centos-9-stream-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/3293274630/jobs/5429599188)|
|centos-9-stream-arm64|[Travis CI](https://github.com/ursacomputing/crossbow/runs/9018293949)|
|conan-maximum|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/3293280665/jobs/5429612106)|
|conan-minimum|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/3293275799/jobs/5429601631)|
|debian-bookworm-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/3293275006/jobs/5429599999)|
|debian-bookworm-arm64|[Travis CI](https://github.com/ursacomputing/crossbow/runs/9018345005)|
|debian-bullseye-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/3293284403/jobs/5429620273)|
|debian-bullseye-arm64|[Travis CI](https://github.com/ursacomputing/crossbow/runs/9018330722)|
|java-jars|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/3293279721/jobs/5430056585)|
|nuget|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/3293279516/jobs/5429609235)|
|python-sdist|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/3293268562/jobs/5429585810)|
|r-binary-packages|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/3293269473/jobs/5430160643)|
|test-ubuntu-default-docs|[Azure](https://github.com/ursacomputing/crossbow/runs/9019705026)|
|ubuntu-bionic-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/3293285242/jobs/5429622027)|
|ubuntu-bionic-arm64|[Travis CI](https://github.com/ursacomputing/crossbow/runs/9018327485)|
|ubuntu-focal-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/3293273926/jobs/5429597577)|
|ubuntu-focal-arm64|[Travis CI](https://github.com/ursacomputing/crossbow/runs/9018333285)|
|ubuntu-jammy-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/3293280160/jobs/5429610945)|
|ubuntu-jammy-arm64|[Travis CI](https://github.com/ursacomputing/crossbow/runs/9018335273)|
|wheel-macos-big-sur-cp310-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/3293270526/jobs/5429590168)|
|wheel-macos-big-sur-cp310-universal2|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/3293281827/jobs/5429614604)|
|wheel-macos-big-sur-cp38-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/3293278180/jobs/5429606853)|
|wheel-macos-big-sur-cp39-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/3293285941/jobs/5429623544)|
|wheel-macos-big-sur-cp39-universal2|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/3293284125/jobs/5429619584)|
|wheel-macos-mojave-cp310-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/3293270197/jobs/5429589363)|
|wheel-macos-mojave-cp37-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/3293277552/jobs/5429605345)|
|wheel-macos-mojave-cp38-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/3293283698/jobs/5429618582)|
|wheel-macos-mojave-cp39-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/3293276669/jobs/5429603362)|
|wheel-manylinux2014-cp310-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/3293269980/jobs/5429588884)|
|wheel-manylinux2014-cp310-arm64|[Travis CI](https://github.com/ursacomputing/crossbow/runs/9018307468)|
|wheel-manylinux2014-cp37-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/3293276140/jobs/5429602287)|
|wheel-manylinux2014-cp37-arm64|[Travis CI](https://github.com/ursacomputing/crossbow/runs/9018305237)|
|wheel-manylinux2014-cp38-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/3293271941/jobs/5429593271)|
|wheel-manylinux2014-cp38-arm64|[Travis CI](https://github.com/ursacomputing/crossbow/runs/9018304119)|
|wheel-manylinux2014-cp39-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/3293285546/jobs/5429622736)|
|wheel-manylinux2014-cp39-arm64|[Travis CI](https://github.com/ursacomputing/crossbow/runs/9018317846)|
|wheel-windows-cp310-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/3293277850/jobs/5429606044)|
|wheel-windows-cp37-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/3293271454/jobs/5429592172)|
|wheel-windows-cp38-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/3293280892/jobs/5429612760)|
|wheel-windows-cp39-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/3293270877/jobs/5429590858)|

**Comment by assignUser** [comment]
The conan failure happens due to missing grpc binaries, so unrelated? https://github.com/ursacomputing/crossbow/actions/runs/3293280665/jobs/5430783359#step:5:620

**Comment by kou** [comment]
Yes. It's unrelated.
#14453 solved it but it's not cherry-picked because it's not a critical problem for 10.0.0.

**Comment by kou** [comment]
@github-actions crossbow submit  --group verify-rc-binaries --group verify-rc-wheels --param release=10.0.0 --param rc=0

**Comment by kou** [comment]
@github-actions crossbow submit verify-rc-binaries-apt-linux-amd64 --param release=10.0.0 --param rc=0

**Comment by kou** [comment]
@github-actions crossbow submit verify-rc-binaries-apt-linux-amd64 --param release=10.0.0 --param rc=0

**Pull request merged**
