### PR TITLE
ARROW-7761: [C++][Python] Support S3 URIs

### PR DESCRIPTION
**Pull request by pitrou**
Allow instantiating an S3 filesystem instance from a `s3://user:pass@bucket/path?params...` URI.

### CODE REVIEW

**Comment by fsaintjacques** [comment]
Works great :D

```
01:build/ (pr/6403✗) $ time release/dataset-parquet-scan-example file:///home/fsaintjacques/datasets/nyc-tlc/parquet
Table size: 746

real    0m3.248s
user    0m5.832s
sys     0m0.203s
01:build/ (pr/6403✗) $ time release/dataset-parquet-scan-example 's3://123:12345678@nyc-tlc/parquet?scheme=http&endpoint_override=localhost:9000'
Table size: 746

real    0m5.600s
user    0m7.557s
sys     0m0.474s
```

**Comment by fsaintjacques** [comment]
One thing that I noted in my local integration, I had to explicit the global init of S3. I think it might be worth providing a default or implicitly calling the init step in `FileSystemFromUri`.

**Review by fsaintjacques — APPROVED** [review]

**Comment by pitrou** [comment]
@fsaintjacques Could you try again now?

**Comment by fsaintjacques** [comment]
I had pushed a change to the dataset example, it seems to be lost did you push force before pulling? It was a small change, I can make it again.

**Comment by pitrou** [comment]
Oh, sorry. Yes, I force-pushed after rebasing :-/

**Comment by fsaintjacques** [comment]
It should pass the CI, I'll merge after. The diff of the dataset example shows how well designed the APIs is.

**Pull request closed without merging**
