### PR TITLE
ARROW-17869: [Java][Gandiva] Implement Reserve for JavaBuffer

### PR DESCRIPTION
**Pull request by js8544**
Java's buffer type doesn't support reserve, which causes java-jars to fail.

### CODE REVIEW

**Comment by js8544** [comment]
@github-actions crossbow submit java-jars

**Comment by js8544** [comment]
@github-actions crossbow submit java-jars

**Comment by js8544** [comment]
@github-actions crossbow submit java-jars

**Comment by kou** [comment]
@github-actions crossbow submit java-jars

**Comment by kou** [comment]
Hmm... It's strange...

**Comment by js8544** [comment]
@github-actions crossbow submit java-jars

**Comment by js8544** [comment]
Brew's LLVM 15 enables z3 by default, and it's shared linked. So at task Build Java Jars, it's required to have libz3 installed on the system. There are several ways to solve this:

1. Add a `brew install z3` task to Build Java Jars task
2. Pin LLVM for java to 14. Currently it uses `arrow/cpp/Brewfile`. We can create another Brewfile in `arrow/java` and pin it in the new file.
3. We can also pin LLVM to 14 for all MacOS builds at `arrow/cpp/Brewfile`. Because LLVM 15 is noticably slower than LLVM 14 somehow. It can also speed up the build time for other MacOS CI tasks.

Which way is preferred? cc @kou @pitrou

**Comment by kou** [comment]
3. for now but we need a new Jira issue for unpinning.

**Comment by js8544** [comment]
> 3. for now but we need a new Jira issue for unpinning.

I've pinned Brew llvm version to 14. Also filed https://issues.apache.org/jira/browse/ARROW-17902 to track current workarounds for LLVM 15 related issues.

**Comment by js8544** [comment]
@github-actions crossbow submit java-jars

**Comment by js8544** [comment]
@github-actions crossbow submit java-jars

**Comment by js8544** [comment]
@github-actions crossbow submit java-jars

**Comment by js8544** [comment]
@github-actions crossbow submit java-jars

**Comment by pitrou** [comment]
Hmm... it would be much more desirable to implement Reserve on Java-exported buffers instead. @lwhite1 @lidavidm Could one of you help perhaps?

**Comment by lidavidm** [comment]
From a quick glance only: why are we reserving if we're resizing immediately afterwards anyways?

**Comment by js8544** [comment]
> From a quick glance only: why are we reserving if we're resizing immediately afterwards anyways?

Because the `resize` implementation for `SimpleBuffer` doesn't amotize the `realloc` costs, if we don't reserve, there will be N reallocs, one for each `resize` call. Now it's reduced to log2(N), since with each reserve we double the buffer size. We still need to call `resize` to track the actual size.

**Comment by lidavidm** [comment]
Ah, thanks for the explanation. I think it would be best if we could implement reserve for Java-allocated buffers, but I am not familiar with the code and don't have time to look at it.

**Comment by lidavidm** [comment]
That said: it seems like we could recycle the logic for resize here to also implement reserve? https://github.com/apache/arrow/blob/5fd54bc6c39613adcc3d196669c28182e12cbec0/java/gandiva/src/main/cpp/jni_common.cc#L715-L753

**Comment by js8544** [comment]
> That said: it seems like we could recycle the logic for resize here to also implement reserve?
> 
> https://github.com/apache/arrow/blob/5fd54bc6c39613adcc3d196669c28182e12cbec0/java/gandiva/src/main/cpp/jni_common.cc#L715-L753

It seems like we can. I can take a look later today if you don't have time for it.

**Comment by pitrou** [comment]
@js8544 Are you closing this PR in favor of another one?

**Comment by js8544** [comment]
> @js8544 Are you closing this PR in favor of another one?

@pitrou Yes, I will submit another PR once https://github.com/apache/arrow/pull/14310 is merged since this change requires llvm@14.

**Pull request closed without merging**
