### PR TITLE
ARROW-1134 - Allow C++/CLI projects to build with Arrow

### PR DESCRIPTION
**Pull request by TobyShaw**
I'm going to attempt a few things:

In public headers:
Hide mutexes through pimpl pattern.
Replace nullptr with __nullptr when building in C++/CLI mode.

### CODE REVIEW

**Comment by TobyShaw** [comment]
Work-in-progress.

**Comment by wesm** [comment]
I'm happy to help you with this, I will let you work for a bit, but if you add me as a collaborator on your fork I can do some work on e.g. hiding mutex

**Comment by TobyShaw** [comment]
Sure thing, added.

**Comment by wesm** [comment]
I've got all the mutexes excluded from public headers. What is the prescribed solution for `nullptr`?

**Comment by wesm** [comment]
I think I'm going to extract this mutex PIMPL-ization into a separate patch so this need not linger too long, and we can deal with nullptr in another patch

**Comment by wesm** [comment]
See ARROW-1641. I will put up a patch for this soon as I can

**Comment by TobyShaw** [comment]
Eek, sorry about the inactivity.

As for the nullptr stuff, the solution I've tested is with macros

```
#ifdef __cplusplus_cli
#define NULLPTR __nullptr
#else
#define NULLPTR nullptr
#endif
```
And using NULLPTR instead of nullptr.

**Comment by wesm** [comment]
Would

```
#ifdef __cplusplus_cli
#define nullptr __nullptr
#endif
```

work also?

**Comment by TobyShaw** [comment]
My compiler complained about redefining a keyword when I tried that.

**Comment by wesm** [comment]
superseded by #1228

**Pull request closed without merging**
