### PR TITLE
ARROW-9962: [Python] Fix conversion to_pandas with tz-aware index column and fixed offset timezones

### PR DESCRIPTION
**Pull request by jorisvandenbossche**

### CODE REVIEW

**Comment by alippai** [comment]
`StringToTzinfo` always creates `pytz.FixedOffset`, while it could create `timezone(timedelta(hours=*,minutes=*))`. I assume technically they are interchangeable, but this way it doesn't survive the pandas roundtrip. Does the pyarrow roundtrip test compare the string values?

**Comment by jorisvandenbossche** [comment]
@alippai I think it's mostly for historical reasons that we always use pytz to recreate a timezone object (eg pandas also historically always used pytz, but nowadays accepts multiple timezone types). It probably makes some sense to use the stdlib timezone where possible (eg for a fixed offset timezone), so we could switch to that, but I personally wouldn't start with tracking the exact package / class.

**Comment by alippai** [comment]
@jorisvandenbossche makes sense, thanks. TIL one more "standard" class is coming: https://docs.python.org/3.9/whatsnew/3.9.html#zoneinfo. Looks like it's replacing `pytz.timezone`. Also this timezone handling looks like an endless rabbit hole: https://blog.ganssle.io/articles/2018/03/pytz-fastest-footgun.html. At least for fixed offsets the new standard doesn't make any difference.

**Review by kszucs — APPROVED** [review]
LGTM, merging on green.

**Comment by kszucs** [comment]
@jorisvandenbossche seems like python3.5 build is failing

**Comment by jorisvandenbossche** [comment]
Yes, it's an actual failure that I still needed to take a look at. But the problem is that I can't reproduce it locally (well, it might be specific to Python 3.5, but I don't have a py 3.5 development environment ... and conda not supporting py3.5 doesn't make it easier to quickly set that up).

**Comment by jorisvandenbossche** [comment]
@github-actions crossbow submit -g integration

**Comment by jorisvandenbossche** [comment]
OK, I am just going to skip it for older pandas versions .. On the older pandas version, it's the assert_frame_equal that is failing, but the actual result and expected result are the same with old version or recent version of pandas (well the difference between expected/result is the same, but on recent versions pandas ignores this difference of pytz.UTC vs datetime.timezone.utc)

**Pull request closed without merging**
