### PR TITLE
ARROW-3270: [Release] Adjust release verification scripts to recent parquet migration

### PR DESCRIPTION
**Pull request by kszucs**
Still unclear how to test it.

### CODE REVIEW

**Comment by xhochy** [comment]
This will only be testable once we have made a release candidate. Then we adjust and test the script.

**Comment by kszucs** [comment]
I'm planning to port it to crossbow with a proper test suite for the next release. Until that simply just review and merge it?

**Comment by kszucs** [comment]
Actually if we separate the downloading step and verify a local folder it's going to be testable with artifacts downloaded from github releases.

**Review by wesm — APPROVED** [review]
+1

**Pull request closed without merging**
