### PR TITLE
GH-37394: [C++][S3] Use AWS_SDK_VERSION_* instead of try_compile()

### LINKED ISSUE #37394: [C++][S3] CRT support may not be detected
### Describe the enhancement requested

See the following comments:

* https://github.com/apache/arrow/issues/34118#issuecomment-1690528581
* https://github.com/apache/arrow/issues/34118#issuecomment-1692645100
* https://github.com/apache/arrow/issues/34118#issuecomment-1693764387

### Component(s)

C++

### PR DESCRIPTION
**Pull request by kou**
### Rationale for this change

I don't know why but `try_compile()` based `Aws::SDKOptions::ioOptions` detection seems not work on some environments. Some unrelated errors may be happen.

### What changes are included in this PR?

Using `AWS_SDK_VERSION_{MAJOR,MINOR,PATCH}` instead of `try_compile()`.

Downside: `AWS_SDK_VERSION_*` are available since 1.9.7 or later but `Aws::SDKOptions::ioOptions` is available since 1.9.0. So we can't detect `Aws::SDKOptions::ioOptions` with [1.9.0,1.9.6]. I think that it's acceptable.

### Are these changes tested?

Yes.

### Are there any user-facing changes?

Yes.
* Closes: #37394

### CODE REVIEW

**Comment by kou** [comment]
@austinzh Could you try this?

**Comment by kou** [comment]
@github-actions crossbow submit wheel-manylinux-2014-cp38-amd64

**Comment by austinzh** [comment]
> @austinzh Could you try this?
 OMP_NUM_THREADS=1 python
```python
>>> os.getpid()
676616
>>> import pyarrow as pa
>>> import pyarrow.fs as fs
```
```bash
ps -T -p 676616
    PID    SPID TTY          TIME CMD
 676616  676616 pts/309  00:00:00 python
 676616  698827 pts/309  00:00:00 jemalloc_bg_thd
 676616  700384 pts/309  00:00:00 AwsEventLoop 1
```
It work!

**Review by austinzh — APPROVED** [review]
LGTM. Thanks for the fix

**Comment by kou** [comment]
Thanks for confirming this.
I'll merge this.

**Pull request merged**
