### PR TITLE
ARROW-15417: [Python][Packaging] Use vcpkg manifest to install wheel dependencies; downgrade AWS SDK by building the bundled version

### PR DESCRIPTION
**Pull request by kszucs**

### CODE REVIEW

**Comment by kszucs** [comment]
@github-actions crossbow submit wheel-windows-cp37-amd64

**Comment by kszucs** [comment]
@github-actions crossbow submit -g wheel

**Comment by kszucs** [comment]
Need to rebuild the windows images.

**Comment by kszucs** [comment]
@github-actions crossbow submit wheel-manylinux* wheel-macos*

**Comment by kszucs** [comment]
@github-actions crossbow submit wheel-manylinux* wheel-macos*

**Comment by kszucs** [comment]
@github-actions crossbow submit wheel-macos-big-sur-*

**Comment by kszucs** [comment]
@github-actions crossbow submit wheel-manylinux2014-cp38-amd64

**Comment by kszucs** [comment]
@github-actions crossbow submit wheel-manylinux* wheel-macos*

**Comment by kszucs** [comment]
@github-actions crossbow submit wheel-macos-big-sur-cp39-universal2

**Comment by kszucs** [comment]
@github-actions crossbow submit wheel-macos-big-sur-cp39-universal2

**Comment by kszucs** [comment]
@github-actions crossbow submit wheel-macos-big-sur-cp39-universal2

**Comment by kszucs** [comment]
@github-actions crossbow submit wheel-macos-big-sur-cp39-universal2

**Comment by kszucs** [comment]
@github-actions crossbow submit wheel-macos-big-sur-cp39-universal2

**Comment by kszucs** [comment]
@github-actions crossbow submit wheel-macos-big-sur-cp39-universal2

**Comment by kszucs** [comment]
@github-actions crossbow submit wheel-manylinux* wheel-macos*

**Comment by kszucs** [comment]
@github-actions crossbow submit wheel-manylinux* wheel-macos*

**Comment by kszucs** [comment]
@github-actions crossbow submit test-ubuntu-20.04-cpp-bundled

**Comment by kszucs** [comment]
@github-actions crossbow submit wheel-windows-*

**Comment by kszucs** [comment]
@github-actions crossbow submit wheel-windows-*

**Comment by kszucs** [comment]
@github-actions crossbow submit -g nightly

**Comment by kszucs** [comment]
@github-actions crossbow submit wheel-macos-big-sur-cp310-universal2

**Comment by kszucs** [comment]
@github-actions crossbow submit wheel-macos-big-sur-cp310-universal2

**Comment by kszucs** [comment]
@github-actions crossbow submit wheel-macos-big-sur-cp310-universal2

**Comment by kszucs** [comment]
@github-actions crossbow submit wheel-manylinux* wheel-macos*

**Comment by kszucs** [comment]
@github-actions crossbow submit wheel-windows-*

**Comment by kszucs** [comment]
@github-actions crossbow submit java-jars

**Comment by kszucs** [comment]
@github-actions crossbow submit java-jars

**Review by kou — COMMENTED** [review]
https://github.com/ursacomputing/crossbow/runs/4915602118?check_suite_focus=true#step:6:1075

Link errors are happen. It seems missing symbols are provided by Windows' system DLL. We may need to add more link flags in `build_awssdk()` in `cpp/cmake_modules/ThirdpartyToolchain.cmake`.

**Comment by kszucs** [comment]
If you don't mind I'll leave the duplicated `boost-crc` line there because it would invalidate the docker cache for both the manylinux and windows images taking hours to rebuild :)

**Comment by kszucs** [comment]
@github-actions crossbow submit wheel-windows-*

**Comment by kou** [comment]
> If you don't mind I'll leave the duplicated `boost-crc` line there because it would invalidate the docker cache for both the manylinux and windows images taking hours to rebuild :)

I see. We can clean up this after we release 7.0.0.

**Comment by kszucs** [comment]
@github-actions crossbow submit java-jars

**Comment by kszucs** [comment]
@github-actions crossbow submit java-jars

**Review by kszucs — COMMENTED** [review]
+1

**Pull request closed without merging**
