### PR TITLE
ARROW-8406: [C++][Python] Fix file URI handling

### PR DESCRIPTION
**Pull request by pitrou**
* Special-case `file` URI parsing to disallow relative paths
* Special-case Windows `file` URIs with a drive letter
* Revamp `ParseFileSystemUri` 
* Fix some C++ and Python tests

### CODE REVIEW

**Comment by pitrou** [comment]
@ursabot crossbow submit -g wheel

**Comment by pitrou** [comment]
@kszucs How does one run the Azure Windows builds?

**Comment by jorisvandenbossche** [comment]
The nightlies that are failing are eg "conda-win-vs2015-py3"

**Comment by jorisvandenbossche** [comment]
@ursabot crossbow submit conda-win-vs2015-py36"

**Comment by jorisvandenbossche** [comment]
@github-actions crossbow submit conda-win-vs2015-py36

**Comment by pitrou** [comment]
@github-actions crossbow submit conda-win-vs2015-py37

**Comment by pitrou** [comment]
@github-actions crossbow submit conda-win-vs2015-py37

**Comment by pitrou** [comment]
@github-actions crossbow submit conda-win-vs2015-py37

**Comment by jorisvandenbossche** [comment]
@github-actions crossbow submit conda-win-vs2015-py37

**Comment by pitrou** [comment]
@github-actions crossbow submit wheel-win-cp38

**Comment by kszucs** [comment]
Build failure is unrelated.

**Review by kszucs — APPROVED** [review]
LGTM, thanks for doing this!

**Pull request closed without merging**
