### PR TITLE
ARROW-2769: [C++][Python] Deprecate and rename add_metadata methods

### PR DESCRIPTION
**Pull request by kszucs**
`WithMetadata` and `with_metadata` in the C++ and Python implementations respectively are better describing the immutable nature of the methods, so depart the previous `AddMetadata` and `add_metadata` methods.

### CODE REVIEW

**Comment by kszucs** [comment]
@ursabot build

**Comment by kszucs** [comment]
@ursabot build

**Comment by kszucs** [comment]
@ursabot build

**Comment by kszucs** [comment]
@ursabot build

**Comment by kszucs** [comment]
@ursabot build

**Comment by kszucs** [comment]
@ursabot build

**Comment by kszucs** [comment]
@ursabot build

**Comment by kszucs** [comment]
@ursabot build

**Comment by kszucs** [comment]
@ursabot build

**Comment by kszucs** [comment]
@ursabot build

**Review by kou — APPROVED** [review]
+1

**Pull request closed without merging**
