### PR TITLE
Java pushdown filter

### PR DESCRIPTION
**Pull request by noahfrn**
Conditional on #14287 - This adds an interface through JNI for strings to be passed, and then parsed into expressions to perform pushdown filtering via the datasets API.

### CODE REVIEW

**Comment by zinking** [comment]
@NoahFournier  could this be pushed forward ?

**Comment by NoahFournier** [comment]
Hey @zinking, I think the future direction for filtering in Arrow will likely be provided via substrait. To work around this for now, you can take a look at: [G-Research/datafusion-java](https://github.com/G-Research/datafusion-java) to see if that unblocks you right away.

**Comment by zinking** [comment]
I think it's fine for now, there are plenty of serialization schemes for expressions.

**Comment by NoahFournier** [comment]
What do you mean by serialization schemes for expressions ? Would be interested to know how you worked around this.

**Comment by zinking** [comment]
> What do you mean by serialization schemes for expressions ? Would be interested to know how you worked around this.

you can see my workaround [here] (https://github.com/apache/arrow/commit/b1426b1460cfde0cec562f92380b84af1021de50) using json serializations. 

subtrait might be the correct direction. but it's not progressing as expected.

**Pull request closed without merging**
