### PR TITLE
MINOR: [Docs][Java] Fix installation documentation for BOM file

### PR DESCRIPTION
**Pull request by wForget**
### Rationale for this change

We should import `arrow-bom` in `dependencyManagement`.

### What changes are included in this PR?

Import `arrow-bom` module in `dependencyManagement`

### Are these changes tested?

No

### Are there any user-facing changes?

Documentation

### CODE REVIEW

**Comment by wForget** [comment]
@jduo could you please take a look?

**Review by jduo — APPROVED** [review]
LGTM.

**Comment by kou** [comment]
@github-actions crossbow submit preview-docs

**Comment by raulcd** [comment]
The failure of the `preview-docs` job is related to: https://github.com/apache/arrow/issues/39942

**Pull request merged**
