### PR TITLE
ARROW-5886: [Python][Packaging] Manylinux1/2010 compliance issue with libz

### PR DESCRIPTION
**Pull request by kszucs**

### CODE REVIEW

**Comment by kszucs** [comment]
@ursabot crossbow package wheel-manylinux1-cp37m

**Comment by kszucs** [comment]
@ursabot crossbow package wheel-manylinux1-cp37m

**Comment by kszucs** [comment]
@ursabot crossbow package wheel-manylinux1-cp37m

**Comment by kszucs** [comment]
@ursabot crossbow package wheel-manylinux1-cp37m

**Comment by kszucs** [comment]
@ursabot crossbow package wheel-manylinux1-cp37m

**Comment by kszucs** [comment]
@ursabot crossbow package wheel-osx-cp37m

**Comment by kszucs** [comment]
@ursabot crossbow package wheel-osx-cp37m wheel-manylinux1-cp37m

**Comment by kszucs** [comment]
@ursabot crossbow package wheel-osx-cp37m

**Comment by kszucs** [comment]
@ursabot crossbow package wheel-osx-cp37m

**Comment by kszucs** [comment]
@ursabot crossbow package -g wheel

**Comment by kszucs** [comment]
The windows builds require https://github.com/apache/arrow/pull/4833

**Comment by kszucs** [comment]
@ursabot crossbow package -g wheel

**Comment by kszucs** [comment]
@wesm @xhochy could we link zlib statically? Does its license permits it?

**Comment by xhochy** [comment]
Yes, we can link it statically. We had that before.

**Comment by kszucs** [comment]
Since mojave zlib is not available on mac by default, and zlib is not part of the manylinux specs. So statically linking would be the best IMO.

**Comment by kszucs** [comment]
@ursabot crossbow package -g wheel

**Comment by kszucs** [comment]
@xhochy what were those security reasons why bundling zlib shared library was required? According to that should we keep this PR as is?

**Comment by xhochy** [comment]
> @xhochy what were those security reasons why bundling zlib shared library was required? According to that should we keep this PR as is?

The idea was that so you would get the security upgrades through the system. But this would actually apply to all other dependencies we have. The main recommendation will be here then, if you want security updates: either build your own wheels or use conda.

**Review by wesm — APPROVED** [review]
+1. This patch is excruciating just to look at. Thanks @kszucs for working on this

**Pull request closed without merging**
