### PR TITLE
ARROW-15: Fix a naming typo for memory.AllocationManager.AllocationOutcome

### PR DESCRIPTION
**Pull request by lw-lin**
Rename FORCED_SUCESS to FORCED_SUC**_C_**ESS in memory.AllocationManager.AllocationOutcome.

### CODE REVIEW

**Comment by proflin** [comment]
No other place in Arrow refers `AllocationOutcome.FORCED_SUCESS`, so this renaming should be OK. Also, test suite passes.

This is fairly a small change, @jacques-n @wesm would you mind taking a look when you have time? Cheers.

**Comment by zhonghongxia** [comment]
array.h : Determine if a slot if null. For inner loops. Does *not* boundscheck  “ is this should be " is null"....?

**Comment by wesm** [comment]
@zhonghongxia yes, that's also a typo, happy to accept patches to improve the C++ library code comments or documentation =)

**Comment by wesm** [comment]
+1

**Pull request closed without merging**
