### PR TITLE
GH-45069: [R][CI] Fix r-binary-packages crossbow job

### PR DESCRIPTION
**Pull request by amoeba**
### Rationale for this change

GitHub phased out R from their Ubuntu images in their 24.04 image and this job started failing because of it. We now need to install R ourselves if a job needs it and uses ubuntu-latest (>=24.04).

### What changes are included in this PR?

Change in GHA workflow config to always install R.

### Are these changes tested?

They're testing here with crossbow.

### Are there any user-facing changes?

No.

* GitHub Issue: #45069

### CODE REVIEW

**Comment by amoeba** [comment]
@github-actions crossbow submit r-binary-packages

**Comment by amoeba** [comment]
I think my hunch was right, @assignUser can you take a look whenever you have a chance?

**Comment by amoeba** [comment]
This isn't quite ready to be merged. The final step fails to find Rscript so I'll see how we can get that installed too.

**Comment by amoeba** [comment]
@github-actions crossbow submit r-binary-packages

**Comment by amoeba** [comment]
This looks good now.

**Review by kou — APPROVED** [review]
+1

**Comment by amoeba** [comment]
Thanks!

**Pull request merged**
