### PR TITLE
GH-40591: [R] Add extra CSS for navbar on pkgdown website

### LINKED ISSUE #40591: [Docs][R] Contrast issues in the navbar on the website
### Describe the bug, including details regarding any error messages, version, and platform.

Hello, this is a minor detail but it's hard to read some of the text in the navbar on the website, specifically the version number (next to "Arrow R Package") and the text in the search box:

image

I also think the text for section names ("Get started", etc.) could be a bit lighter. I use Firefox (current is 123.0.1) in case it's a browser-specific thing.

### Component(s)

Documentation, R

### PR DESCRIPTION
**Pull request by etiennebacher**
### Rationale for this change

This PR fixes https://github.com/apache/arrow/issues/40591. It adds some CSS rules for better readibility of text in the navbar on the `pkgdown` website.

### What changes are included in this PR?

Three new CSS rules, one for each change in the navbar:
* put the section text (e.g "Get started") in light gray. I chose light gray and not white because white is used when we hover the text;
* put the version number in light gray
* put the "Search for" placeholder in light gray

### Are these changes tested?

Not applicable

### Are there any user-facing changes?

Only visual changes on the website:

* before:

image

* after:

image

* GitHub Issue: #40591

### CODE REVIEW

**Comment by amoeba** [comment]
Hi @etiennebacher, this looks good to me as-is. Thanks for taking care of it.

Note to reviewers: When looking at this, I wanted to see if we could avoid adding pkgdown's extra.css to make this simpler but it looks like the cosmo theme doesn't provide an appropriate utility class, presumably since it's not designed around a black navbar. There are some in-built utility classes that are close but are either too light or too dark. So I think this is a reasonable approach.

**Comment by kou** [comment]
@github-actions crossbow submit preview-docs

**Comment by amoeba** [comment]
http://crossbow.voltrondata.com/pr_docs/40610/r/index.html looks good to me. @kou do you agree? I tested locally too.

**Review by kou — APPROVED** [review]
+1

@amoeba Do you want to merge this as a new committer? :-)

**Comment by amoeba** [comment]
Sure! And thanks :)

**Comment by amoeba** [comment]
Thanks @etiennebacher, we really appreciate you taking the time to contribute this.

**Pull request merged**
