### PR TITLE
[Minor]: Mac m1 minor test fix [WIP]

### PR DESCRIPTION
**Pull request by vibhatha**
This is a minor test fix for the conda build on Mac M1.

### CODE REVIEW

**Comment by xhochy** [comment]
This should not be necessary. These variables should be picked up automatically

**Comment by vibhatha** [comment]
@xhochy I understand. Let me see what I am missing in the Mac environment.

**Comment by xhochy** [comment]
Can you post a log indicating what went wrong?

**Comment by vibhatha** [comment]
@xhochy as you suggested this was not needed. It might have been some issue in my setup. I will close this one now.

**Pull request closed without merging**
