### PR TITLE
GH-43796: [C++] Indent preprocessor directives

### PR DESCRIPTION
**Pull request by kou**
### Rationale for this change

This is for easy to read.

FYI: Google C++ style guide doesn't require indent in preprocessor directives nor deny it:

https://google.github.io/styleguide/cppguide.html#Preprocessor_Directives

```cpp
// Good - directives at beginning of line
  if (lopsided_score) {
#if DISASTER_PENDING      // Correct -- Starts at beginning of line
    DropEverything();
# if NOTIFY               // OK but not required -- Spaces after #
    NotifyClient();
# endif
#endif
    BackToNormal();
  }
```

### What changes are included in this PR?

* Add clang-format configurations for preprocessor directives indentation
* Apply these configurations

### Are these changes tested?

Yes.

### Are there any user-facing changes?

No.
* GitHub Issue: #43796

### CODE REVIEW

**Review by lidavidm — APPROVED** [review]

**Review by sgilmore10 — APPROVED** [review]

**Review by zanmato1984 — APPROVED** [review]
LGTM.

Just one nit: I think the PR title doesn't reflect all the aspects of the change. Maybe we can change it to just "indent preprocessor directives"?

**Comment by kou** [comment]
(I'll fix the lint failure later.)

**Comment by kou** [comment]
The discussion thread: https://lists.apache.org/thread/gb2dpphhwz358zfb03k9ly18gs92rzdr

**Comment by kou** [comment]
No objection in the discussion thread.

**Comment by kou** [comment]
I'll merge this.

**Pull request merged**
