### PR TITLE
MINOR: [C++][Parquet] Fix some comments and style in Statistics

### PR DESCRIPTION
**Pull request by mapleFU**
### Rationale for this change

Statistics uses some virtual functions in constructor, so here I change it to explicit call rather than implicit virtual fn call. And I also fixed some comments typo

### What changes are included in this PR?

Some code style and comment fix in parquet statistics

### Are these changes tested?

No, and no tests are need.

### Are there any user-facing changes?

no

### CODE REVIEW

**Comment by mapleFU** [comment]
@pitrou Mind take a look? This patch is small and didn't change any impl logics...

**Comment by pitrou** [comment]
@wgtmac @emkornfield  Would you like to comment on this? The changes look fine on the principle.

**Comment by wgtmac** [comment]
> @wgtmac @emkornfield Would you like to comment on this? The changes look fine to me on the principle.

Looking good on my side.

**Comment by mapleFU** [comment]
@pitrou @wjones127 Mind take a look?

**Review by wjones127 — APPROVED** [review]

**Comment by emkornfield** [comment]
Apologies, seems OK to me, not clear exactly why we prefer full references to the static methods?

**Comment by mapleFU** [comment]
> Apologies, seems OK to me, not clear exactly why we prefer full references to the static methods?

Personally it's confusing. Calling "virtual" method in dtor and ctor is not virtual. But user is easy to take it as virtual.

**Pull request merged**
