### PR TITLE
ARROW-7694: [Packaging][deb][RPM] Add support for RC to repository packages

### PR DESCRIPTION
**Pull request by kou**

### CODE REVIEW

**Comment by kou** [comment]
@ursabot cross submit -g linux

**Comment by kou** [comment]
@ursabot crossbow submit -g linux

**Comment by kszucs** [comment]
[AMD64 Conda Crossbow Submit (#88544)](https://ci.ursalabs.org/#builders/98/builds/478) builder has been succeeded.

Revision: 167cc1bf9bb711c76385ebcd148020b45aefb205

Submitted crossbow builds: [ursa-labs/crossbow @ ursabot-465](https://github.com/ursa-labs/crossbow/branches/all?query=ursabot-465)

|Task|Status|
|----|------|
|centos-6|[Azure](https://dev.azure.com/ursa-labs/crossbow/_build/latest?definitionId=1&branchName=ursabot-465-azure-centos-6)|
|centos-7|[Azure](https://dev.azure.com/ursa-labs/crossbow/_build/latest?definitionId=1&branchName=ursabot-465-azure-centos-7)|
|centos-8|[Azure](https://dev.azure.com/ursa-labs/crossbow/_build/latest?definitionId=1&branchName=ursabot-465-azure-centos-8)|
|debian-buster|[Azure](https://dev.azure.com/ursa-labs/crossbow/_build/latest?definitionId=1&branchName=ursabot-465-azure-debian-buster)|
|debian-stretch|[Azure](https://dev.azure.com/ursa-labs/crossbow/_build/latest?definitionId=1&branchName=ursabot-465-azure-debian-stretch)|
|ubuntu-bionic|[Azure](https://dev.azure.com/ursa-labs/crossbow/_build/latest?definitionId=1&branchName=ursabot-465-azure-ubuntu-bionic)|
|ubuntu-disco|[Azure](https://dev.azure.com/ursa-labs/crossbow/_build/latest?definitionId=1&branchName=ursabot-465-azure-ubuntu-disco)|
|ubuntu-eoan|[Azure](https://dev.azure.com/ursa-labs/crossbow/_build/latest?definitionId=1&branchName=ursabot-465-azure-ubuntu-eoan)|
|ubuntu-xenial|[Azure](https://dev.azure.com/ursa-labs/crossbow/_build/latest?definitionId=1&branchName=ursabot-465-azure-ubuntu-xenial)|

**Review by kszucs — APPROVED** [review]
LGTM, thanks Kou for fixing it so quickly!

**Pull request closed without merging**
