### PR TITLE
GH-37936: [CI] Fix integration testing in rc-verify nightly builds

### LINKED ISSUE #37936: [CI] Fix integration testing in rc-verify nightly builds
### Describe the bug, including details regarding any error messages, version, and platform.

gh-37537 inadvertently broke some nightly builds, for example:
https://github.com/ursacomputing/crossbow/actions/runs/6326190228/job/17179241564#step:6:69362
```pytb

Traceback (most recent call last):
  File "/tmp/arrow-HEAD.5Yox5/venv-source/bin/archery", line 8, in <module>
    sys.exit(archery())
  File "/tmp/arrow-HEAD.5Yox5/venv-source/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/tmp/arrow-HEAD.5Yox5/venv-source/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/tmp/arrow-HEAD.5Yox5/venv-source/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/tmp/arrow-HEAD.5Yox5/venv-source/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/tmp/arrow-HEAD.5Yox5/venv-source/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/arrow/dev/archery/archery/cli.py", line 748, in integration
    from .integration.runner import write_js_test_json, run_all_tests
  File "/arrow/dev/archery/archery/integration/runner.py", line 30, in <module>
    from . import cdata
  File "/arrow/dev/archery/archery/integration/cdata.py", line 18, in <module>
    import cffi
ModuleNotFoundError: No module named 'cffi'
```

### Component(s)

Continuous Integration, Integration, Release

### PR DESCRIPTION
**Pull request by pitrou**
* Closes: #37936

### CODE REVIEW

**Comment by pitrou** [comment]
@github-actions crossbow submit -g verify-rc-source

**Comment by pitrou** [comment]
@github-actions crossbow submit -g verify-rc-source

**Comment by pitrou** [comment]
@github-actions crossbow submit verify-rc-source-integration-macos*

**Comment by pitrou** [comment]
@github-actions crossbow submit verify-rc-source-integration-macos*

**Comment by pitrou** [comment]
@github-actions crossbow submit verify-rc-source-integration*

**Comment by pitrou** [comment]
Unfortunately the verify-rc scripts are so horrendously slow and so unstable that it's difficult to get a clear idea of successes and failures.

@kou Are you able to review this?

**Comment by pitrou** [comment]
I see a lot of spurious "permission denied" at the end of the macOS integration build (otherwise successful):
https://github.com/ursacomputing/crossbow/actions/runs/6341262518/job/17224519021#step:4:6375

**Comment by kou** [comment]
In general, these changes look good. But there are some failures. For example:

verify-rc-source-integration-linux-almalinux-8-amd64

https://github.com/ursacomputing/crossbow/actions/runs/6341261220/job/17224514818#step:6:584

```text
/arrow/go/arrow/internal/cdata_integration /arrow/go /arrow /
go: downloading golang.org/x/xerrors v0.0.0-20220907171357-04be3eba64a2
go: downloading golang.org/x/sys v0.12.0
go: downloading github.com/google/flatbuffers v23.5.26+incompatible
go: downloading github.com/klauspost/compress v1.16.7
go: downloading github.com/pierrec/lz4/v4 v4.1.18
go: downloading github.com/goccy/go-json v0.10.2
go: downloading github.com/zeebo/xxh3 v1.0.2
go: downloading github.com/klauspost/cpuid/v2 v2.2.5
error obtaining VCS status: exit status 128
	Use -buildvcs=false to disable VCS stamping.
```

I can help fixing remaining failures in the next week.

**Comment by pitrou** [comment]
> In general, these changes look good. But there are some failures. For example:
> 
> verify-rc-source-integration-linux-almalinux-8-amd64

I noticed that one, but I have no idea what the actual issue is, and whether it's related to these changes.

@zeroshade

**Comment by zeroshade** [comment]
@pitrou @kou Starting with go-1.18, go will attempt to stamp version control information in any binary that is built with the go toolchain. I'm guessing that the config setting up the env isn't maintaining the `.git` folder after the clone or something so it's unable to find the vcs info that it wants to try to stamp the binary. If there's a reason why we're not maintaining the vcs info in the file system for the verification, then it probably makes the most sense to just add the `-buildvcs=false` argument to the build command for the integration test binaries. we're not distributing the binaries built with the verification scripts anyways, so I don't see any problem with disabling the vcs stamping

**Comment by pitrou** [comment]
@github-actions crossbow submit verify-rc-source-integration*

**Comment by pitrou** [comment]
Ok, I think I have fixed the Go issue (it works locally), but we'll have to wait a couple hours for the Crossbow results now.

**Comment by pitrou** [comment]
I'm sorry, but I think it's pointless to wait for all those integration tasks that are failing for unrelated reasons. I will merge this CI, as it does make things better anyway.

**Pull request merged**
