### PR TITLE
GH-39390: [C++] Thirdparty: bump default zlib to 1.3

### LINKED ISSUE #39390: [C++] Thirdparty: Bump zlib to 1.3
### Describe the enhancement requested

zlib 1.3 is released, which containing some bugfix: https://github.com/madler/zlib/releases/tag/v1.3

We're currently default using zlib 1.2.13, so maybe we can bump it

### Component(s)

C++

### PR DESCRIPTION
**Pull request by mapleFU**
### Rationale for this change

This patch bump default zlib to 1.3 (currently we're default using 1.2.13 as default). 1.3 includes some bugfixes.

### What changes are included in this PR?

Update vendor in arrow

### Are these changes tested?

Maybe we already has tests?

### Are there any user-facing changes?

no

* Closes: #39390

### CODE REVIEW

**Review by wgtmac — APPROVED** [review]
+1

Should we trigger the crossbow check for cpp?

**Comment by kou** [comment]
@github-actions crossbow submit -g cpp -g wheel -g r

**Comment by mapleFU** [comment]
@pitrou Would you mind take a look?

**Comment by pitrou** [comment]
@github-actions crossbow submit -g nightly-tests -g r

**Review by pitrou — APPROVED** [review]
+1

**Comment by mapleFU** [comment]
Emmm don't know whether failed ut is related

```
[ RUN      ] TestAzuriteFileSystem.CreateDirFailureDirectoryWithMissingContainer
unknown file: Failure
C++ exception with description "Connection closed before getting full response or response is less than expected. Expected response length = 254. Read until now = 231" thrown in the test body.
```

Also is this a new flacky test?

**Comment by pitrou** [comment]
I don't think they are related. I have restarted the jobs.

**Comment by davisusanibar** [comment]
Hi, 

Trying to build cpp dependencies for Java JNI libraries and receiving the following error message:

````
$ arrow/java: mvn generate-resources -Pgenerate-libs-jni-macos-linux -N
...
-- Downloading...
   dst='/Users/dsusanibar/Documents/business/voltron/fork/vibhatha/arrow/cpp-jni/zlib_ep-prefix/src/zlib-1.3.tar.gz'
   timeout='none'
   inactivity timeout='none'
-- Using src='https://zlib.net/fossils/zlib-1.3.tar.gz'
-- verifying file...
       file='/Users/dsusanibar/Documents/business/voltron/fork/vibhatha/arrow/cpp-jni/zlib_ep-prefix/src/zlib-1.3.tar.gz'
-- SHA256 hash of
    /Users/dsusanibar/Documents/business/voltron/fork/vibhatha/arrow/cpp-jni/zlib_ep-prefix/src/zlib-1.3.tar.gz
  does not match expected value
    expected: 'ff0ba4c292013dbc27530b3a81e1f9a813cd39de01ca5e0f8bf355702efa593e'
      actual: '92e1f7b660b942a8365b54da7f098d4ed04f2d68f0219dfd192f2002b1d648f0'
-- Hash mismatch, removing...
````

Then if I change the hash to `ff0ba4c292013dbc27530b3a81e1f9a813cd39de01ca5e0f8bf355702efa593e` I am seeing:

````
$ arrow/java: mvn generate-resources -Pgenerate-libs-jni-macos-linux -N
...
-- stderr output is:
CMake Error at zlib_ep-stamp/download-zlib_ep.cmake:170 (message):
  Each download failed!

    error: downloading 'https://apache.jfrog.io/artifactory/arrow/thirdparty/7.0.0/zlib-1.3.tar.gz' failed
          status_code: 22
          status_string: "HTTP response code said error"
          log:
````

**Comment by kou** [comment]
I've uploaded https://apache.jfrog.io/artifactory/arrow/thirdparty/7.0.0/zlib-1.3.tar.gz as a mirror.

**Pull request merged**
