### PR TITLE
ARROW-5112: [Go] implement writing IPC Arrow stream/file

### PR DESCRIPTION
**Pull request by sbinet**
Needs #4228.

### CODE REVIEW

**Comment by sbinet** [comment]
PTAL @stuartcarnie @alexandreyc @nickpoorman

**Review by nickpoorman — APPROVED** [review]
LGTM

**Review by stuartcarnie — APPROVED** [review]
It is a large PR, so I was looking though the commits for tests. I don't have a sense of the amount of coverage but I do see lots of tests.

LGTM 🎉

**Comment by sbinet** [comment]
yeah... I don't know why the code coverage app didn't post its report...
I'll try to post mine in the coming days.

**Pull request closed without merging**
