### PR TITLE
ARROW-15171: [C++][Java] Update ORC to 1.7.2

### PR DESCRIPTION
**Pull request by williamhyun**
This PR aims to bump ORC to 1.7.2.

Apache ORC 1.7.2 is a maintenance release with the following bug fixes.

- https://github.com/apache/orc/releases/tag/v1.7.2
- https://orc.apache.org/news/2021/12/20/ORC-1.7.2/

### CODE REVIEW

**Comment by pitrou** [comment]
Rebased.

**Review by pitrou — APPROVED** [review]
+1, let's wait for CI

**Comment by pitrou** [comment]
@github-actions crossbow -g cpp

**Comment by pitrou** [comment]
@github-actions crossbow submit -g cpp

**Comment by dongjoon-hyun** [comment]
Thank you, @williamhyun and @pitrou !

**Pull request closed without merging**
