### PR TITLE
ARROW-9837: [Rust][DataFusion] Added provider for variable

### PR DESCRIPTION
**Pull request by wqc200**
Select @@Version, @name;

@@Version is a variable, and if we want to get its value, we should get it from outside the system.
@@Version is a system variable, @name is user defined variable.

### CODE REVIEW

**Review by andygrove — APPROVED** [review]
LGTM

**Comment by andygrove** [comment]
Sorry @wqc200 could you rebase again? Another PR got merged, causing this conflict.

**Review by andygrove — CHANGES_REQUESTED** [review]
The last commit is a merge commit with changes unrelated to this PR.

Please rebase rather than merge.

**Comment by wqc200** [comment]
> The last commit is a merge commit with changes unrelated to this PR.
> 
> Please rebase rather than merge.

Ok, I rebase it now

**Review by andygrove — APPROVED** [review]

**Pull request closed without merging**
