### PR TITLE
ARROW-13669: [C++] Fix variant emplace methods (add brackets)

### PR DESCRIPTION
**Pull request by emkornfield**

### CODE REVIEW

**Comment by emkornfield** [comment]
@bkietz not sure if this was intentional.

**Comment by bkietz** [comment]
@emkornfield [`function-try-block`](https://en.cppreference.com/w/cpp/language/function-try-block) is legal C++, is it not preferred style?

**Comment by emkornfield** [comment]
I would need to check the compiler flags, etc that I was using but this failed for me on one of my dev setups.

I don't know about style, but this form of syntax is certainly new to me.  Does it provide any advantages of standard method definitions?

**Comment by emkornfield** [comment]
From the page you linked above:
> The primary purpose of function-try-blocks is to respond to an exception thrown from the member initializer list in a constructor by logging and rethrowing, modifying the exception object and rethrowing, throwing a different exception instead, or terminating the program. They are rarely used with destructors or with regular functions.

**Review by bkietz — APPROVED** [review]

**Pull request closed without merging**
