### PR TITLE
ARROW-2048: [Python/C++] Upate Thrift pin to 0.11

### PR DESCRIPTION
**Pull request by xhochy**

### CODE REVIEW

**Comment by xhochy** [comment]
Tested locally, we might need to retrigger one Travis job if it starts before quay.io has built the base Docker image.

**Comment by xhochy** [comment]
`thrift-cpp=0.11.0` for OSX was not uploaded, will have to look at the feedstock

**Comment by xhochy** [comment]
PR for the feedstock: https://github.com/conda-forge/thrift-cpp-feedstock/pull/17

**Comment by xhochy** [comment]
Waiting for https://travis-ci.org/conda-forge/thrift-cpp-feedstock/builds/334773696 to pass, then we can retrigger Travis here.

**Comment by wesm** [comment]
Triggered build

**Pull request closed without merging**
