### PR TITLE
ARROW-6394 [Java] Support conversions between delta vector and partial sum vector

### PR DESCRIPTION
**Pull request by liyafan82**
What is a delta vector/partial sum vector?

Given an integer vector a with length n, its partial sum vector is another integer vector b with length n + 1, with values defined as:

b(0) = initial sum
b(i ) = a(0) + a(1) + ... + a(i - 1) i = 1, 2, ..., n

Given an integer vector with length n + 1, its delta vector is another integer vector b with length n, with values defined as:

b(i ) = a(i ) - a(i - 1), i = 0, 1, ... , n -1

In this issue, we provide utilities to convert between vector and partial sum vector. It is interesting to note that the two operations corresponding to the discrete integration and differentian.

These conversions have wide applications. For example,

1. The run-length vector proposed by Micah is based on the partial sum vector, while the deduplication functionality is based on delta vector. This issue provides conversions between them.

2. The current VarCharVector/VarBinaryVector implementations are based on partial sum vector. We can transform them to delta vectors before IPC, to reduce network traffic.

3. Converting to delta can be considered as a way for data compression. To further reduce the data volume, the operation can be applied more than once, to further reduce data volume.

### CODE REVIEW

**Comment by liyafan82** [comment]
@emkornfield Do you think this change deserves a discussion in the ML?

**Comment by emkornfield** [comment]
@liyafan82 I think I've commented before, but I think what needs to be discussed on the mailing list are:
1.  General plans for algorithms to make sure we can get consensus on what belongs in Arrow and what doesn't.
2.  A plan for making existing algorithms and new ones as efficient as possible.  Write now I believe there is a fairly high cost to all the algorithms because they rely on megamorphic virtual calls.  
3. Any other criteria that needs to be met to move algorithms from experimental/contrib status.  If this is the desired intent of the contributions.  Otherwise, while I appreciate the contributions, I am investing a lot of time in reviewing these, and it is not clear if there will be any users of work.

I'm going to hold off on doing reviews for anything more in algorithms until we have this discussion and come to consensus on the ML.

**Comment by liyafan82** [comment]
> @liyafan82 I think I've commented before, but I think what needs to be discussed on the mailing list are:
> 
> 1. General plans for algorithms to make sure we can get consensus on what belongs in Arrow and what doesn't.
> 2. A plan for making existing algorithms and new ones as efficient as possible.  Write now I believe there is a fairly high cost to all the algorithms because they rely on megamorphic virtual calls.
> 3. Any other criteria that needs to be met to move algorithms from experimental/contrib status.  If this is the desired intent of the contributions.  Otherwise, while I appreciate the contributions, I am investing a lot of time in reviewing these, and it is not clear if there will be any users of work.
> 
> I'm going to hold off on doing reviews for anything more in algorithms until we have this discussion and come to consensus on the ML.

@emkornfield 
Thanks a lot for your comments. I am sorry for asking the same question repeatedly.
I think I need to significantly lower the bar for initiating discussions in the ML, because even for apparently small features, there are points to discuss.

**Comment by emkornfield** [comment]
> Thanks a lot for your comments. I am sorry for asking the same question repeatedly. I think I need to significantly lower the bar for initiating discussions in the ML, because even for apparently small features, there are points to discuss.

@liyafan82 thanks for starting a conversation on this.  I wasn't asking specifically for this feature for a discussion.  Rather, there are a lot of small features that in aggregate take a lot of time to review and I'm not sure there is a cohesive plan around what exactly is going into the algorithm package.   What I am asking for is a document, that outlines the plan for this package.  A good example is [Wes's document on the C++ datasets document](https://docs.google.com/document/d/1QOuz_6rIUskM0Dcxk5NwP8KhKn_qK6o_rFV3fbHQ_AM/edit).  In addition to the rough set of features that are intended to be added, it would be good to discuss the overall approach to making them performant as possible (something Jacques brought up in reference to "adapters", but I think applies equally to algorithms).

**Comment by liyafan82** [comment]
> > Thanks a lot for your comments. I am sorry for asking the same question repeatedly. I think I need to significantly lower the bar for initiating discussions in the ML, because even for apparently small features, there are points to discuss.
> 
> @liyafan82 thanks for starting a conversation on this. I wasn't asking specifically for this feature for a discussion. Rather, there are a lot of small features that in aggregate take a lot of time to review and I'm not sure there is a cohesive plan around what exactly is going into the algorithm package. What I am asking for is a document, that outlines the plan for this package. A good example is [Wes's document on the C++ datasets document](https://docs.google.com/document/d/1QOuz_6rIUskM0Dcxk5NwP8KhKn_qK6o_rFV3fbHQ_AM/edit). In addition to the rough set of features that are intended to be added, it would be good to discuss the overall approach to making them performant as possible (something Jacques brought up in reference to "adapters", but I think applies equally to algorithms).

@emkornfield Thanks a lot for sharing your thoughts. I can see that you are taking a lot of time to review our code. We really appreciate that, and I would like do anything I could to offload your burden.

The suggestion about design doc is good. However, the content of the algorithms package is generally driven by application. This is because I think we should support an algorithm only when 

1) the algorithm is needed or will be needed shortly. 
2) there is a wide range of applications for the algorithm.

Therefore, it is difficult to give a plan for the algorithms that will be supported. For example, this particular PR is driven by the following applications:

1) conversions of the two different memory layouts for RLE vector.
2) the observation that delta vector will save space by small byte widths (as indicated by you).

The above points convinces me that this feature will be used and will have wide range of applications, so I opened this issue. However, this was unexpected a few days ago.

The above is an explanation. Below are TODOs for me, in response to your comments:

1) If there is any feature that is well planned, I will provide a document to make it clear.
2) I will provide more detailed descriptions to make reviewing easier.
3) I will try to make small algorithms/features independent, and self-contained, so little background is required.

Your comments about implementation approach and performance is reasonable for me. 

If there is anything misunderstood by me, or anything I could do, please let me know. Thank you.

Any comment is highly welcome and deeply appreciated.

**Comment by liyafan82** [comment]
To avoid megamorphic virtual function calls, we need to consider each combination of input/output vector types. So code generation is appropriate here.
What do you think? @emkornfield

**Comment by emkornfield** [comment]
Given discussion, on ML, i'll review as is without code-gen for now.

**Comment by emkornfield** [comment]
+1, thank you.

**Pull request closed without merging**
