### PR TITLE
WIP: [Release] Verify release-16.0.0-rc0

### PR DESCRIPTION
**Pull request by raulcd**
PR to verify Release Candidate

### CODE REVIEW

**Comment by raulcd** [comment]
@github-actions crossbow submit  --group verify-rc-source --param release=16.0.0 --param rc=0

**Comment by raulcd** [comment]
Revision: 6a28035c2b49b432dc63f5ee7524d76b4ed2d762

Submitted crossbow builds: [ursacomputing/crossbow @ release-16.0.0-rc0-0](https://github.com/ursacomputing/crossbow/branches/all?query=release-16.0.0-rc0-0)

|Task|Status|
|----|------|
|almalinux-8-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/tree/release-16.0.0-rc0-0-github-almalinux-8-amd64)|
|almalinux-8-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/tree/release-16.0.0-rc0-0-github-almalinux-8-arm64)|
|almalinux-9-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/tree/release-16.0.0-rc0-0-github-almalinux-9-amd64)|
|almalinux-9-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/tree/release-16.0.0-rc0-0-github-almalinux-9-arm64)|
|amazon-linux-2023-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/tree/release-16.0.0-rc0-0-github-amazon-linux-2023-amd64)|
|amazon-linux-2023-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/tree/release-16.0.0-rc0-0-github-amazon-linux-2023-arm64)|
|centos-7-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8707767713/job/23883544014)|
|centos-8-stream-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8707768388/job/23883550949)|
|centos-8-stream-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8707768047/job/23883546506)|
|centos-9-stream-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8707768465/job/23883551597)|
|centos-9-stream-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8707768219/job/23883547827)|
|conan-maximum|[GitHub Actions](https://github.com/ursacomputing/crossbow/tree/release-16.0.0-rc0-0-github-conan-maximum)|
|conan-minimum|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8707768719/job/23883553483)|
|debian-bookworm-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8707768178/job/23883547820)|
|debian-bookworm-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8707768717/job/23883554663)|
|debian-bullseye-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/tree/release-16.0.0-rc0-0-github-debian-bullseye-amd64)|
|debian-bullseye-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8707767879/job/23883544839)|
|debian-trixie-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8707768434/job/23883551273)|
|debian-trixie-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8707767874/job/23883544885)|
|java-jars|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8707768062/job/23883552814)|
|matlab|[GitHub Actions](https://github.com/ursacomputing/crossbow/tree/release-16.0.0-rc0-0-github-matlab)|
|nuget|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8707768525/job/23883551947)|
|python-sdist|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8707767856/job/23883544798)|
|r-binary-packages|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8707768726/job/23883553578)|
|test-ubuntu-22.04-docs|[GitHub Actions](https://github.com/ursacomputing/crossbow/tree/release-16.0.0-rc0-0-github-test-ubuntu-22.04-docs)|
|ubuntu-focal-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8707768501/job/23883551710)|
|ubuntu-focal-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8707768498/job/23883551606)|
|ubuntu-jammy-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8707768045/job/23883545988)|
|ubuntu-jammy-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8707768239/job/23883547821)|
|ubuntu-noble-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8707768503/job/23883551673)|
|ubuntu-noble-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8707768210/job/23883546853)|
|wheel-macos-big-sur-cp310-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8707768773/job/23883553825)|
|wheel-macos-big-sur-cp311-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8707768627/job/23883553181)|
|wheel-macos-big-sur-cp312-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8707768444/job/23883551343)|
|wheel-macos-big-sur-cp38-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8707768765/job/23883554678)|
|wheel-macos-big-sur-cp39-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8707768417/job/23883550969)|
|wheel-macos-catalina-cp310-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8707768587/job/23883553200)|
|wheel-macos-catalina-cp311-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8707768314/job/23883549999)|
|wheel-macos-catalina-cp312-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8707768234/job/23883548053)|
|wheel-macos-catalina-cp38-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/tree/release-16.0.0-rc0-0-github-wheel-macos-catalina-cp38-amd64)|
|wheel-macos-catalina-cp39-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8707768923/job/23883555272)|
|wheel-manylinux-2-28-cp310-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8707767728/job/23883544028)|
|wheel-manylinux-2-28-cp310-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8707767755/job/23883544023)|
|wheel-manylinux-2-28-cp311-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8707768090/job/23883546902)|
|wheel-manylinux-2-28-cp311-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8707768069/job/23883546891)|
|wheel-manylinux-2-28-cp312-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8707768027/job/23883545746)|
|wheel-manylinux-2-28-cp312-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8707768831/job/23883554917)|
|wheel-manylinux-2-28-cp38-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8707768039/job/23883545730)|
|wheel-manylinux-2-28-cp38-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8707768847/job/23883554975)|
|wheel-manylinux-2-28-cp39-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8707768801/job/23883554756)|
|wheel-manylinux-2-28-cp39-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8707767813/job/23883544570)|
|wheel-manylinux-2014-cp310-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/tree/release-16.0.0-rc0-0-github-wheel-manylinux-2014-cp310-amd64)|
|wheel-manylinux-2014-cp310-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8707768676/job/23883553446)|
|wheel-manylinux-2014-cp311-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8707768916/job/23883555239)|
|wheel-manylinux-2014-cp311-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8707768841/job/23883554955)|
|wheel-manylinux-2014-cp312-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8707767979/job/23883545076)|
|wheel-manylinux-2014-cp312-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8707768871/job/23883555191)|
|wheel-manylinux-2014-cp38-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/tree/release-16.0.0-rc0-0-github-wheel-manylinux-2014-cp38-amd64)|
|wheel-manylinux-2014-cp38-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8707768629/job/23883553237)|
|wheel-manylinux-2014-cp39-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8707768729/job/23883553517)|
|wheel-manylinux-2014-cp39-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8707767698/job/23883544018)|
|wheel-windows-cp310-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8707768246/job/23883548122)|
|wheel-windows-cp311-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8707768427/job/23883551270)|
|wheel-windows-cp312-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8707768054/job/23883546492)|
|wheel-windows-cp38-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8707768266/job/23883548128)|
|wheel-windows-cp39-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/8707768048/job/23883546484)|

**Comment by kou** [comment]
@github-actions crossbow submit  --group verify-rc-binaries --group verify-rc-wheels --param release=16.0.0 --param rc=0

**Comment by kou** [comment]
verify-rc-binaries-wheels-windows:

https://github.com/ursacomputing/crossbow/actions/runs/8715262993/job/23907626092#step:6:5681

```text
E   pyarrow.lib.ArrowInvalid: IANA time zone database is unavailable but required by ORC. Please install it to /usr/share/zoneinfo or set TZDIR env to the installed directory
```

This is related to #40609 and #40697.
I think that we can avoid this by preparing time zone database in the verification script like https://github.com/apache/arrow/pull/40609/files#diff-8f8e277288306ff8aafdaa7ab9871d21c0cfcad57ecd463f583a4afa9c852ab5R64-R67 .

**Comment by kou** [comment]
(I think that this is not a blocker.)

**Comment by raulcd** [comment]
> I think that this is not a blocker.

I agree. I will send the vote. Thanks @kou

**Comment by raulcd** [comment]
@ursabot please benchmark

**Review by domoritz — COMMENTED** [review]
Here are some changes that we had tagged for Arrow 16 that we would love to have included in the release: https://github.com/apache/arrow/pull/41261. They are all in main.

**Pull request merged**
