### PR TITLE
ARROW-18052: [Python] Support passing create_dir thru pq.write_to_dataset

### PR DESCRIPTION
**Pull request by milesgranger**
Will fix [ARROW-18052](https://issues.apache.org/jira/browse/ARROW-18052)

Should likely need a test, but curious if we should add another `write_dataset_kwargs`(?) collection parameter for `pq.write_to_dataset` for those kwargs that ought to be passed onto `ds.write_dataset`.

### CODE REVIEW

**Review by jorisvandenbossche — COMMENTED** [review]
I think on the short term this seems as the best solution. That only means we need to remember, when adding a new (non-format specific) keyword to `write_dataset`, to also add it here. But it does result in a nicer API than another "kwargs"-like object.

Would indeed be good to add a test.

**Comment by milesgranger** [comment]
It became more apparent we're already mixing `kwargs`. Updated it to be more dynamic in matching kwargs to `ds.write_dataset` and remainder going to `make_write_options` when `use_legacy_dataset=False`. Along with a matching test.

**Comment by jorisvandenbossche** [comment]
@milesgranger you accidentally added some parquet data file

**Review by jorisvandenbossche — APPROVED** [review]
Thanks, that seems as a good general solution!

**Comment by jorisvandenbossche** [comment]
Could you just rebase / merge master once more to ensure CI is passing?

**Comment by milesgranger** [comment]
@jorisvandenbossche seems okay, failure unrelated it appears.

**Pull request merged**
