### PR TITLE
ARROW-12810: [Python] Stop AWS SDK from looking for metadata service

### PR DESCRIPTION
**Pull request by lidavidm**
This significantly speeds up Python tests.

I opted to put it in Python instead of in the shell script so that interactive local development also benefits.

### CODE REVIEW

**Comment by lidavidm** [comment]
Before:
```
================================================== slowest 10 durations ===================================================
159.74s call     pyarrow/tests/test_fs.py::test_s3_proxy_options
15.99s call     pyarrow/tests/test_dataset.py::test_open_dataset_from_s3_with_filesystem_uri
15.22s call     pyarrow/tests/test_fs.py::test_s3_real_aws_region_selection
3.19s call     pyarrow/tests/test_fs.py::test_s3_real_aws
3.12s call     pyarrow/tests/test_dataset.py::test_write_dataset_s3
2.03s setup    pyarrow/tests/test_fs.py::test_open_input_stream[S3FileSystem-gzip-256-compress]
2.02s call     pyarrow/tests/test_fs.py::test_filesystem_is_functional_after_pickling[S3FileSystem]
2.02s setup    pyarrow/tests/test_dataset.py::test_open_dataset_from_uri_s3
2.01s setup    pyarrow/tests/test_dataset.py::test_open_dataset_from_uri_s3_fsspec
2.01s setup    pyarrow/tests/test_dataset.py::test_write_dataset_s3
```

After:
```
================================================== slowest 10 durations ===================================================
0.69s call     pyarrow/tests/test_fs.py::test_s3_real_aws_region_selection
0.63s call     pyarrow/tests/test_fs.py::test_s3_options
0.31s call     pyarrow/tests/parquet/test_dataset.py::test_read_multiple_files[True]
0.27s setup    pyarrow/tests/test_dataset.py::test_make_fragment
0.25s call     pyarrow/tests/test_dataset.py::test_open_dataset_from_uri_s3_fsspec
0.22s setup    pyarrow/tests/test_dataset.py::test_open_dataset_from_uri_s3
0.21s call     pyarrow/tests/parquet/test_dataset.py::test_read_partitioned_directory_s3fs[True]
0.19s call     pyarrow/tests/test_dataset.py::test_union_dataset_from_other_datasets
0.18s call     pyarrow/tests/parquet/test_dataset.py::test_read_partitioned_directory_s3fs[False]
0.16s call     pyarrow/tests/parquet/test_dataset.py::test_read_multiple_files[False]
```

**Review by westonpace — APPROVED** [review]
LGTM, thanks for looking into this.  I wouldn't have thought to start here.

**Comment by lidavidm** [comment]
Ah, I ran into this earlier somewhere else and Neal suggested it back then. Plus you can see this same env var scattered throughout the Arrow repository as people have run into it again and again in different contexts, so really someone just needed to throw it into Python.

**Comment by jorisvandenbossche** [comment]
Nice, thanks!

**Comment by lidavidm** [comment]
Merging this; looks like Homebrew has having issues causing the MacOS build to time out.

**Pull request closed without merging**
