### PR TITLE
ARROW-5714: [JS] Inconsistent behavior in Int64Builder with/without BigNum

### PR DESCRIPTION
**Pull request by TheNeuralBit**
- Use stride in `DataBufferBuilder.set` to ensure that Int64Builder is consistent with and without BigNum.
- Use `WideBufferBuilder` for `Int64` and `Uint64` builders, even when `BigInt` is not available. Moves check for `BigInt` availability into `WideBufferBuilder`. (Thanks to Paul Taylor)

### CODE REVIEW

**Comment by trxcllnt** [comment]
@TheNeuralBit I was thinking about this more last night, and while this works for the JS-number case, it won't work if we try to set in a pair of `[lo,hi]`, so my thought was we should refactor the WideBufferBuilder so we could use it for the 64bit types, and just provide the BigInt TypedArray views if they're available.

**Comment by trxcllnt** [comment]
@TheNeuralBit https://github.com/TheNeuralBit/arrow/pull/3 here's a pull that should do what we want in FF

**Comment by TheNeuralBit** [comment]
@trxcllnt I merged your PR and also clarified the int64 generation for the builder tests. Does this look ok to you?

**Review by trxcllnt — APPROVED** [review]

**Comment by trxcllnt** [comment]
@theneuralbit yep, that looks great. thanks!

**Pull request closed without merging**
