### PR TITLE
GH-40649: [CI][Release][Java] Use Maven 3.8 for verify-rc-source-java-linux-almalinux-8-amd64

### PR DESCRIPTION
**Pull request by kou**
### Rationale for this change

#39696 requires Maven 3.6 or later.

### What changes are included in this PR?

Use Maven 3.8.

### Are these changes tested?

Yes.

### Are there any user-facing changes?

No.
* GitHub Issue: #40649

### CODE REVIEW

**Comment by kou** [comment]
@github-actions crossbow submit verify-rc-source-java-linux-almalinux-8-amd64

**Comment by vibhatha** [comment]
```bash
=============================
Build and test Java libraries
=============================
/arrow/java /arrow /
/arrow/dev/release/verify-release-candidate.sh: line 614: mvn: command not found
Failed to verify release candidate. See /tmp/arrow-HEAD.FB64e for details.
```

**Comment by kou** [comment]
@github-actions crossbow submit verify-rc-source-java-linux-almalinux-8-amd64

**Comment by vibhatha** [comment]
@kou this is a bit odd:https://github.com/ursacomputing/crossbow/actions/runs/8334984011/job/22809595263#step:6:53820
Should we re-run?

**Comment by kou** [comment]
> Should we re-run?
 
 Done!

**Comment by vibhatha** [comment]
@github-actions crossbow submit *java*

**Comment by vibhatha** [comment]
@github-actions crossbow submit verify-rc-source-java-linux-almalinux-8-amd64

**Comment by vibhatha** [comment]
@kou I think something is missing here. I am not quite sure what. Need to evaluate further.

**Comment by kou** [comment]
The error message:

https://github.com/ursacomputing/crossbow/actions/runs/8335526861/job/22811169947#step:6:52650

```text
Error:  Error occurred during initialization of boot layer
Error:  java.lang.module.FindException: Module flatbuffers.java not found, required by org.apache.arrow.vector
Error:  Error occurred during initialization of boot layer
Error:  java.lang.module.FindException: Module flatbuffers.java not found, required by org.apache.arrow.vector
```

**Comment by kou** [comment]
Is `flatbuffers.java` an auto generated file?

**Comment by kou** [comment]
It's referred from https://github.com/apache/arrow/blob/0956f3f7c9f8d4f976275cd670744b52ee30cbf3/java/vector/src/main/java/module-info.java#L43

**Comment by kou** [comment]
@jduo Do you know what is the problem of https://github.com/apache/arrow/pull/40650#issuecomment-2005663438 ? Should we use different Maven version? (Maven 3.8 has a problem?)

**Comment by vibhatha** [comment]
@kou is there a way to locally test this using docker/archery to reproduce if possible?

**Comment by jduo** [comment]
> It's referred from
> 
> https://github.com/apache/arrow/blob/0956f3f7c9f8d4f976275cd670744b52ee30cbf3/java/vector/src/main/java/module-info.java#L43

flatbuffers.java is the automatically generated module name for flatbuffers-java.jar (rather than being an actual .java file).

**Comment by jduo** [comment]
> @jduo Do you know what is the problem of [#40650 (comment)](https://github.com/apache/arrow/pull/40650#issuecomment-2005663438) ? Should we use different Maven version? (Maven 3.8 has a problem?)

When adding module support, I ran into issues with very specific versions of some plugins but don't remember the maven version itself being an issue. The ones that really caused problems were the maven-shade-plugin and the maven-analyze-plugin.

**Comment by kou** [comment]
> is there a way to locally test this using docker/archery to reproduce if possible?

You can use `archery docker run -e TEST_DEFAULT=0 TEST_JAVA=1 almalinux-verify-rc`.

**Comment by kou** [comment]
@jduo Thanks for taking a look at this. Hmm... It seems that we need to look into this to fix this...

**Comment by kou** [comment]
AlmaLinux 8 ships Maven 3.8.5.
#40514 used Maven 3.8.7 via conda and it worked.

It seems that Maven 3.8.5 doesn't work.

I close this in favor of #40514. #40514 also uses newer Maven.

**Pull request closed without merging**
