### PR TITLE
ARROW-11401: [Rust][DataFusion] Pass slices instead of Vec in DataFrame API

### PR DESCRIPTION
**Pull request by Dandandan**
This PR makes the API a bit more ergonomic to use (saving 3 characters per parameter), avoiding creating a `Vec` with a macro, or cloning an existing one.

It is also more consistent, for example `DataFrame::join` already was taking parameters by `&[&str]` instead of `Vec<&str>`.

This is a (big) backwards incompatible change.

### CODE REVIEW

**Review by andygrove — APPROVED** [review]
Thanks @Dandandan I am still working on getting out of the habit of using `Vec` for parameters

**Review by alamb — APPROVED** [review]
I think this is a good change -- and follows the general model of making the Rust implementation of Arrow/DataFusion use more idomatic (common) Rust patterns.

👍 

Thanks @Dandandan

**Review by alamb — COMMENTED** [review]
So one unintended consequence of this change that I missed is that for the APIs that take used to take `Vec<Expr>` and now take `&[Expr]` it effectively forces a second copy of the `Expr` in the common case - and the calls to `expr.to_vec()` are *deep cloning* the exprs.

I think taking `&[&str]` for args is still reasonable (compared to `Vec<&str>` but I think we should consider going back to `Vec<Expr>` (or perhaps something like `impl IntoIterator<Item=Expr>`) for the builder functions that expect Exprs.

What do you think @Dandandan  and @jorgecarleitao ?

BTW you can see a consequence of this change downstream here: https://github.com/influxdata/influxdb_iox/pull/718

**Comment by Dandandan** [comment]
@alamb I think you are right, there are two places now `pub fn sort` and `pub fn aggregate` and that do more cloning than before.

I could imagine this would lead to a bit more cloning in some cases, although most cases will be passing either a simple constant slice or a slice from an existing vec.
I will have a look to your PR.

**Comment by Dandandan** [comment]
@alamb what do you think of an implementation like the following? I'll try to create a PR for this later this week.
 
This would allow passing both an array (for simple contant cases like `sort([col("a")])`) and `Vecs`. For a `Vec`, `into()` is a no-op, for arrays it should be the same as using `vec![]`
```rust
    pub fn sort<T: Into<Vec<Expr>>>(&self, expr: T) -> Result<Self> {
        Ok(Self::from(&LogicalPlan::Sort {
            expr: expr.into(),
            input: Arc::new(self.plan.clone()),
        }))
    }

```

Apart from this, `Self::from` currently does another clone on the logical plan, copying the expressions one more time. This could be changed by having it not accepting a `&LogicalPlan` but a `LogicalPlan`.

**Comment by alamb** [comment]
@Dandandan  I think that idea looks good. What do you think about the following slightly more general (but possibly less efficient) version that takes an `impl IntoIterator`  instead:

```
  pub fn sort(&self, expr: impl IntoIterator<Item=Expr>) -> Result<Self> {
        Ok(Self::from(&LogicalPlan::Sort {
            expr: expr.into_iter().collect(),
            input: Arc::new(self.plan.clone()),
        }))
    }
```

I am not sure how much extra work, if any, that would require for `Vec<Expr>` but it would allow creating plans with things like values in a map:
```
let my_map: BTreeMap<&str, Expr> = ....;
builder = builder.sort(my_map.values())
```

**Comment by alamb** [comment]
@Dandandan  I can also take a crack at this later in the week if you don't get to it

**Comment by Dandandan** [comment]
Looks like this idea doesn't work for the `DataFrame` API as the methods return the trait object, which doesn't allow generic types.

**Pull request closed without merging**
