### PR TITLE
ARROW-13630: [CI][C++][s390x] Reduce parallelism to build Arrow library

### PR DESCRIPTION
**Pull request by kiszk**

### CODE REVIEW

**Comment by kiszk** [comment]
This PR change seems to avoid the compilation error as we can see https://app.travis-ci.com/github/apache/arrow/jobs/532092034

**Review by cyb70289 — APPROVED** [review]
Thanks @kiszk

**Comment by cyb70289** [comment]
I compared job running times. Looks there's no much difference.
History build time varies from 9min to 15min, this job is about 14min.
Given travis only provides 2 cores to a CI job, this change should be okay.

**Comment by kiszk** [comment]
Sometimes, the error is different as https://app.travis-ci.com/github/apache/arrow/jobs/532105509 due to hang up. It still seems to be a memory limitation issue.

**Pull request closed without merging**
