### PR TITLE
ARROW-1040: [GLib] Support tensor IO

### PR DESCRIPTION
**Pull request by kou**

### CODE REVIEW

**Review by wesm — APPROVED** [review]
+1

**Comment by wesm** [comment]
I presume you're creating JIRAs with a script? Would you mind setting the assignee and fix version when you do? Thanks

**Comment by kou** [comment]
> I presume you're creating JIRAs with a script?

No. I'm creating JIRA issues by hand. :<

> Would you mind setting the assignee and fix version when you do?

OK. I'll do.

**Comment by wesm** [comment]
Ah, it seemed so orderly I thought computer-generated =) With http://jira.readthedocs.io/en/latest/examples.html#issues we can create issues easily (similar to the merge PR script and changelog scripts) if that becomes useful

**Comment by kou** [comment]
Thanks for the information.
I may create a script and submit it as a pull request.

**Pull request closed without merging**
