### PR TITLE
GH-39848: [Python][Packaging] Build pyarrow wheels with numpy RC instead of nightly

### PR DESCRIPTION
**Pull request by jorisvandenbossche**
### Rationale for this change

Now NumPy has released a first RC for 2.0, we should update our PyArrow wheels to build with this released version instead of with the nightly numpy packages, to ensure we don't build our release wheels with an unstable numpy version.

### What changes are included in this PR?

Increased the version requirement for numpy for the installed packages at build time to `numpy>=2.0.0rc1`, to force installing this RC instead of numpy 1.26

### Are these changes tested?

The wheel tests ensure that those wheels still work with older versions of numpy
* GitHub Issue: #39848

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
@github-actions crossbow submit -g wheel

**Comment by jorisvandenbossche** [comment]
Ah, we are also running into the liblzma vcpkg issue now (https://github.com/microsoft/vcpkg/issues/37839 / https://github.com/microsoft/vcpkg/pull/37957)

**Comment by kou** [comment]
@github-actions crossbow submit -g wheel

**Comment by jorisvandenbossche** [comment]
@github-actions crossbow submit -g wheel

**Comment by raulcd** [comment]
The macOS wheels failure is the same issue that happens on [test-build-vcpkg-win](https://github.com/ursacomputing/crossbow/actions/runs/8639597931/job/23686197211). I am not sure why is it failing on installing grpc. See comment here: https://github.com/apache/arrow/issues/41124#issuecomment-2049325277

**Comment by raulcd** [comment]
Wheels have been fixed on main, can you rebase to have green CI before merge?

**Comment by jorisvandenbossche** [comment]
@github-actions crossbow submit -g wheel

**Review by raulcd — APPROVED** [review]
`Java JNI / AMD64 manylinux2014 Java JNI` is timing out after 90 minutes because is rebuilding the docker manylinux image. I am going to merge because it has nothing to do with this PR. The timeout was modified from 500 minutes to 90 minutes on this PR: https://github.com/apache/arrow/pull/40609/files#diff-d4336cc8304d9967e1e645bb86368d266ff4b96503aaea4aab2ded3bb398cd8e
We might have to increase it again.

**Comment by raulcd** [comment]
@jorisvandenbossche Should we create an issue to update the Numpy version from RC1 to the final released once numpy releases?

**Pull request merged**
