### PR TITLE
ARROW-18379: [Python] Change warnings to _warnings in _plasma_store_entry_point

### LINKED ISSUE #14693: _plasma_store_entry_point in pyarrow/__init__.py
### Describe the bug, including details regarding any error messages, version, and platform.

NameError: name 'warnings' is not defined.

In [`_plasma_store_entry_point`](https://github.com/apache/arrow/blob/master/python/pyarrow/__init__.py#L355-L357) function, `warnings` should be changed to `_warnings`. 

### Component

Python

### PR DESCRIPTION
**Pull request by AlenkaF**
This PR resolves https://github.com/apache/arrow/issues/14693.

### CODE REVIEW

**Comment by AlenkaF** [comment]
Testing the process of closing GitHub issues with PRs that do not have Jira linked to them. Observing:
- The warning about opening an associated Jira issue will need to be removed (will open a Jira issue for it, if I do not find any existing).
- Should we prepend the number of the GitHub issue to the title? Or is the title enough?

**Comment by AlenkaF** [comment]
Linked it to a Jira issue as this typo should be included in the first possible release.

**Comment by AlenkaF** [comment]
@milesgranger ming looking at this PR please? Just a small typo correction :)

**Review by milesgranger — APPROVED** [review]
Short and sweet! LGTM!

**Review by jorisvandenbossche — APPROVED** [review]

**Pull request merged**
