### PR TITLE
ARROW-8103: [R] Make default Linux build more minimal

### PR DESCRIPTION
**Pull request by nealrichardson**
The status quo is that on Linux, R package installation will result in a shell package that tells you to install C++ libraries and reinstall, unless you either (1) have already installed system packages or a dev build, or (2) set an environment variable (either `LIBARROW_DOWNLOAD=true`, or `NOT_CRAN=true` also works because many R users have that set locally already), in which case installation will look for a binary to download and fall back to downloading and building C++ from source. 

This patch changes the default behavior when no system packages are found: instead of building without Arrow C++, it will attempt to download and build the C++ dependencies from source, with optional features (compression libraries _but not jemalloc_) turned off. Setting an environment variable `LIBARROW_MINIMAL=false` will turn on those optional features, or they can be toggled individually with cmake-flavored env vars too (e.g. `ARROW_WITH_SNAPPY=ON`). If `LIBARROW_DOWNLOAD=true` or `NOT_CRAN=true` are set, as before it will look for a binary to download, and if not found, it will build from source with `LIBARROW_MINIMAL=false`.

In sum, this means that we will always be attempting to build the C++ libs from source on CRAN (and thus on everyone's Linux machines, assuming they don't already have Arrow C++ libs), as minimally as we can while still resulting in a fully functional `arrow` package. The fallback shell package that doesn't do anything should only happen if the C++ build fails for some reason, which we have found to be highly unlikely now that we've eliminated the flex and bison dependencies--having enough of a C++ toolchain for R and Rcpp is sufficient.

### CODE REVIEW

**Comment by nealrichardson** [comment]
@github-actions crossbow submit -g r

**Comment by wesm** [comment]
@nealrichardson to make sure I'm understanding, if an average Linux user types `install.packages(c("arrow))` what will be installed? A minimal C++ library with no thirdparty libraries (and no jemalloc)?

**Comment by nealrichardson** [comment]
@wesm without any env vars set, you won't get any compression libraries or jemalloc, but all of the other features that the R package relies on (parquet, compute, etc.) are built. See https://github.com/apache/arrow/blob/c75673c88b3fc4fc666cb0edb2cb3b126a29ce50/r/inst/build_arrow_static.sh#L46-L85. So, not quite "minimal", and not exactly "no thirdparty libraries" because it will still build boost_ep, rapidjson_ep, and thrift_ep. 

I didn't think it was worth the trouble to start turning off arrow features for this lighter build because it would negate the benefit--you'd still have to reinstall the package to do most things you'd want to use `arrow` for. And I'm told that install time isn't a blocking issue for CRAN. Turning off the thirdparty libraries does help with install time, in case it were to become an issue (you never know), but probably just as important it reduces risk of spurious errors like the ones we saw where bzip2 was failing to download.

**Comment by wesm** [comment]
OK. Since jemalloc makes a big difference in performance in many cases, if it's not burdensome I would include it in the default build if possible

**Comment by nealrichardson** [comment]
@github-actions crossbow submit -g r

**Comment by nealrichardson** [comment]
@github-actions crossbow submit test-r-linux-as-cran

**Comment by nealrichardson** [comment]
@github-actions crossbow submit test-r-linux-as-cran

**Comment by nealrichardson** [comment]
@github-actions crossbow submit test-r-linux-as-cran

**Comment by nealrichardson** [comment]
@github-actions crossbow submit test-r-linux-as-cran

**Pull request closed without merging**
