### PR TITLE
ARROW-5520: [Packaging] No NVIDIA CUDA toolkit for arm64

### PR DESCRIPTION
**Pull request by hrw**

### CODE REVIEW

**Comment by kou** [comment]
How to test this? (I don't have arm64 environment...)

**Comment by hrw** [comment]
Easiest way? s/arm64/amd64/ and do build. sbuild/pbuilder will not fetch "nvidia-cuda-toolkit" into build chroot.

**Comment by hrw** [comment]
Other option: AWS. There are arm64 machines.

**Comment by kou** [comment]
Thanks. I'll try with `s/arm64/amd64/g` first.

**Comment by kou** [comment]
I found that we can run `arm64v8/debian` Docker image on amd64 Debian GNU/Linux with `qemu-user-static` and `binfmt-support` packages.
I'll use this to test this.

**Comment by emkornfield** [comment]
@ursabot --help

**Comment by emkornfield** [comment]
@ursabot build

**Comment by emkornfield** [comment]
@ursabot build --help

**Comment by emkornfield** [comment]
@kou it looks like this passes on Ursabots ARM64, I think that probably means its ok?

**Comment by kou** [comment]
The Ursabot builds on ARM64 are unrelated. Because they don't create deb packages.
I'm testing this on local. I found that we need more work to build deb packages for arm64.
I'm working on here: https://github.com/kou/arrow/tree/packaging-deb-arm64

**Comment by kou** [comment]
I've opened #4588 because we need more work to complete deb package support for arm64.

**Pull request closed without merging**
