### PR TITLE
ARROW-5308: [Go] remove deprecated Feather format

### PR DESCRIPTION
**Pull request by sbinet**

### CODE REVIEW

**Comment by sbinet** [comment]
PTAL @wesm @stuartcarnie @alexandreyc

**Comment by wesm** [comment]
It's your call whether you want to keep or remove this code. I'd say to put your energy into supporting the official binary protocol well and wait for Feather to migrate to V2.

My plan for the way that Feather files will be able to distinguish between V1 and V2 files will be the magic number. Currently it is "FEA1" and it will change to "FEA2". I will probably maintain the FEA1 code path for a release or two so at least people have a version of the software that can convert their files from V1 to V2 and then I can delete the FEA1 implementation altogether.

**Comment by sbinet** [comment]
> I'd say to put your energy into supporting the official binary protocol well and wait for Feather to migrate to V2.

SGTM.

(I'll wait a bit for others to chime in and comment.)

**Comment by alexandreyc** [comment]
LGTM

I have nothing very interesting to add...

**Pull request closed without merging**
