### PR TITLE
WIP: [Release] Verify release-14.0.2-rc3

### PR DESCRIPTION
**Pull request by raulcd**
PR to verify Release Candidate

### CODE REVIEW

**Comment by raulcd** [comment]
@github-actions crossbow submit  --group verify-rc-source --param release=14.0.2 --param rc=3

**Comment by raulcd** [comment]
Revision: 740889f413af9b1ae1d81eb1e5a4a9fb4ce9cf97

Submitted crossbow builds: [ursacomputing/crossbow @ release-14.0.2-rc3-0](https://github.com/ursacomputing/crossbow/branches/all?query=release-14.0.2-rc3-0)

|Task|Status|
|----|------|
|almalinux-8-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-14.0.2-rc3-0-github-almalinux-8-amd64)|
|almalinux-8-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/7179538667/job/19549917971)|
|almalinux-9-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-14.0.2-rc3-0-github-almalinux-9-amd64)|
|almalinux-9-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-14.0.2-rc3-0-github-almalinux-9-arm64)|
|amazon-linux-2023-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/7179538550/job/19549917320)|
|amazon-linux-2023-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/7179538920/job/19549919306)|
|centos-7-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/7179539408/job/19549922196)|
|centos-8-stream-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/7179539327/job/19549921900)|
|centos-8-stream-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/7179539237/job/19549921345)|
|centos-9-stream-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-14.0.2-rc3-0-github-centos-9-stream-amd64)|
|centos-9-stream-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/7179538473/job/19549917048)|
|conan-maximum|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/7179538689/job/19549918302)|
|conan-minimum|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/7179539556/job/19549922548)|
|debian-bookworm-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/7179538201/job/19549915913)|
|debian-bookworm-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/7179539187/job/19549921180)|
|debian-bullseye-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/7179538595/job/19549917550)|
|debian-bullseye-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/7179539278/job/19549921442)|
|debian-trixie-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/7179538361/job/19549916553)|
|debian-trixie-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/7179539373/job/19549921630)|
|java-jars|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/7179538977/job/19549923468)|
|nuget|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/7179538375/job/19549916454)|
|python-sdist|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/7179538659/job/19549918020)|
|r-binary-packages|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/7179539538/job/19549922610)|
|test-ubuntu-22.04-docs|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-14.0.2-rc3-0-github-test-ubuntu-22.04-docs)|
|ubuntu-focal-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/7179538742/job/19549918331)|
|ubuntu-focal-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-14.0.2-rc3-0-github-ubuntu-focal-arm64)|
|ubuntu-jammy-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/7179538969/job/19549919661)|
|ubuntu-jammy-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-14.0.2-rc3-0-github-ubuntu-jammy-arm64)|
|ubuntu-lunar-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/7179538607/job/19549917580)|
|ubuntu-lunar-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/7179539382/job/19549921769)|
|wheel-clean|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/7179539504/job/19549922394)|
|wheel-macos-big-sur-cp310-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/7179538369/job/19549916860)|
|wheel-macos-big-sur-cp311-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/7179539552/job/19549922492)|
|wheel-macos-big-sur-cp312-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/7179538587/job/19549917541)|
|wheel-macos-big-sur-cp38-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-14.0.2-rc3-0-github-wheel-macos-big-sur-cp38-arm64)|
|wheel-macos-big-sur-cp39-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/7179539060/job/19549920508)|
|wheel-macos-mojave-cp310-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/7179539462/job/19549922258)|
|wheel-macos-mojave-cp311-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/7179538673/job/19549918008)|
|wheel-macos-mojave-cp312-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-14.0.2-rc3-0-github-wheel-macos-mojave-cp312-amd64)|
|wheel-macos-mojave-cp38-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/7179538435/job/19549916586)|
|wheel-macos-mojave-cp39-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/7179539171/job/19549920886)|
|wheel-manylinux-2-28-cp310-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/7179538980/job/19549919878)|
|wheel-manylinux-2-28-cp310-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/7179538894/job/19549919403)|
|wheel-manylinux-2-28-cp311-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/7179538199/job/19549915994)|
|wheel-manylinux-2-28-cp311-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/7179538775/job/19549918629)|
|wheel-manylinux-2-28-cp312-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/7179539262/job/19549921503)|
|wheel-manylinux-2-28-cp312-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-14.0.2-rc3-0-github-wheel-manylinux-2-28-cp312-arm64)|
|wheel-manylinux-2-28-cp38-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/7179538789/job/19549918606)|
|wheel-manylinux-2-28-cp38-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/7179539317/job/19549921989)|
|wheel-manylinux-2-28-cp39-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/7179538732/job/19549918336)|
|wheel-manylinux-2-28-cp39-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/7179539004/job/19549920006)|
|wheel-manylinux-2014-cp310-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/7179538339/job/19549916311)|
|wheel-manylinux-2014-cp310-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-14.0.2-rc3-0-github-wheel-manylinux-2014-cp310-arm64)|
|wheel-manylinux-2014-cp311-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/7179538693/job/19549918276)|
|wheel-manylinux-2014-cp311-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/7179538402/job/19549916609)|
|wheel-manylinux-2014-cp312-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/7179538448/job/19549916985)|
|wheel-manylinux-2014-cp312-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/7179539402/job/19549921540)|
|wheel-manylinux-2014-cp38-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/7179538895/job/19549919407)|
|wheel-manylinux-2014-cp38-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/7179538818/job/19549918883)|
|wheel-manylinux-2014-cp39-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/7179539481/job/19549922248)|
|wheel-manylinux-2014-cp39-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/7179539415/job/19549921986)|
|wheel-windows-cp310-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/7179538228/job/19549915703)|
|wheel-windows-cp311-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/7179538576/job/19549917401)|
|wheel-windows-cp312-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/7179539051/job/19549920468)|
|wheel-windows-cp38-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/7179538208/job/19549915655)|
|wheel-windows-cp39-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/7179538223/job/19549915641)|

**Comment by raulcd** [comment]
@kou this looks much better now :) do you want to upload the binaries? I'll upload the java-jars.

**Comment by kou** [comment]
OK! I'll do it!

**Comment by raulcd** [comment]
Thanks @kou ! Let me know once is done and I'll trigger the binary verification tasks!

**Comment by kou** [comment]
Done!

**Comment by raulcd** [comment]
@github-actions crossbow submit  --group verify-rc-binaries --group verify-rc-wheels --param release=14.0.2 --param rc=3

**Comment by raulcd** [comment]
The badge for: `verify-rc-binaries-wheels-linux-ubuntu-22.04-amd64` should be green now, not sure why is not updating :)

**Comment by raulcd** [comment]
At this point from the 3 failures (1 of the 4 red badges has succeeded but is not updated):
- verify-rc-binaries-apt-linux-amd64 --> I think we have not uploaded ubuntu lunar which is indeed an issue
- verify-rc-binaries-binary-linux-amd64 --> I've retried 13 times but is an issue with download artifacts. I have run the exact same locally on ubuntu 22.04 (as the GH runner) successfully with: `$ TEST_DEFAULT=0 TEST_BINARY=1 dev/release/verify-release-candidate.sh 14.0.2 3` I think we can test locally.
- verify-rc-binaries-wheels-macos-11-amd64 --> this timed out for the other releases on 14.0.x too.

I am pretty sure that if we upload Ubuntu lunar we can vote the release. @kou thoughts? The other Download failures have been solved after a bunch of retries.

**Comment by kou** [comment]
+1

> verify-rc-binaries-apt-linux-amd64 --> I think we have not uploaded ubuntu lunar which is indeed an issue

This was my fault. I've uploaded it. Sorry.

**Pull request merged**
