### PR TITLE
ARROW-6190: [C++] Define and declare functions regardless of NDEBUG

### PR DESCRIPTION
**Pull request by ozars**

### CODE REVIEW

**Comment by wesm** [comment]
Could you explain in the PR description how the status quo creates a problem?

**Comment by ozars** [comment]
Sure. That's the error I got:

```
test-arrowproject.cpp:(.text._ZN5arrow22FixedSizeBinaryBuilder12UnsafeAppendEN6nonstd7sv_lite17basic_string_viewIcSt11char_traitsIcEEE[_ZN5arrow22FixedSizeBinaryBuilder12UnsafeAppendEN6nonstd7sv_lite17basic_string_$
iewIcSt11char_traitsIcEEE]+0xd1): undefined reference to `arrow::FixedSizeBinaryBuilder::CheckValueSize(long)'
```

This happened after I used `FixedSizeBinaryBuilder::Append<NSIZE>` which calls `FixedSizeBinaryBuilder::UnsafeAppend(util::string_view)`, which in terms tries to call `FixedSizeBinaryBuilder::CheckValueSize(long)` if NDEBUG isn't defined. However NDEBUG isn't defined during Release build.

https://github.com/apache/arrow/blob/a0ee6377ce5931db11178ab8bd2517407aa6561a/cpp/src/arrow/array/builder_binary.h#L257-L262

https://github.com/apache/arrow/blob/a0ee6377ce5931db11178ab8bd2517407aa6561a/cpp/src/arrow/array/builder_binary.cc#L223-L227

I can try adding a minimal example in the afternoon if needed.

**Comment by wesm** [comment]
The issue is clear now. We'll want to add this information to the PR description for the sake of the changelog. I'll let @pitrou review

**Review by pitrou — APPROVED** [review]
Thanks for noticing this. The PR looks good to me.

**Comment by ozars** [comment]
Thanks.

**Pull request closed without merging**
