### PR TITLE
ARROW-7160: [C++] Update string_view backport

### PR DESCRIPTION
**Pull request by pitrou**

### CODE REVIEW

**Comment by emkornfield** [comment]
is the main diff here the ability to compare two string_views?

**Comment by pitrou** [comment]
No, to compare a string_view against something else.

**Comment by emkornfield** [comment]
+1, LGTM.

**Comment by emkornfield** [comment]
can't merge at the moment, can do it a little later if you don't get to it first

**Comment by pitrou** [comment]
Will do, thank you!

**Pull request closed without merging**
