### PR TITLE
ARROW-17979: [JS] Update status docs with JS capabilities

### PR DESCRIPTION
**Pull request by domoritz**

### CODE REVIEW

**Comment by nealrichardson** [comment]
I'm guessing this table is based off of the integration test support, and for these types, it appears there are not yet JS integration tests: https://github.com/apache/arrow/blob/master/dev/archery/archery/integration/datagen.py#L1588-L1664

ARROW-7900 is for null; not sure if there's an issue for the unions. Would it be easy to enable the integration tests for these types?

**Comment by domoritz** [comment]
Ahh, good to know. How involved is it to enable those tests? I don't have cycles to learn how to write integration tests right now, unfortunately.

**Comment by nealrichardson** [comment]
> Ahh, good to know. How involved is it to enable those tests? I don't have cycles to learn how to write integration tests right now, unfortunately.

I'm not sure. If it were me, I'd start by removing the `.skip_category('JS')` lines I linked above, at least for the types you think should work, and see if the integration tests pass on CI. 

The JS test runner is https://github.com/apache/arrow/blob/master/dev/archery/archery/integration/tester_js.py, which points at the files in https://github.com/apache/arrow/tree/master/js/bin. It's possible the tests will just work (if the implementation is correct), or it's possible that there is some JSON writer/reader specific to the integration tests that needs to be updated. 

@zeroshade has been in here recently, enabling more Go tests, so he may be able to advise too.

**Comment by domoritz** [comment]
https://issues.apache.org/jira/browse/ARROW-7900 suggests to me that enabling the null test won't work. I'll try the other ones.

**Comment by domoritz** [comment]
Well, doesn't look look like I can just enable the integration tests. 

Screenshot 2022-10-10 at 18 54 42

**Comment by zeroshade** [comment]
Looking at the code in `recordbatch.ts` in `collectDictionaries` it looks like it is accessing `data.dictionary` where `data` is one of the children and is getting an `undefined` value for one of those children which is why it is failing.

**Comment by amol-** [comment]
Closing because it has been untouched for a while, in case it's still relevant feel free to reopen and move it forward 👍

**Comment by amol-** [comment]
Closing because it has been untouched for a while, in case it's still relevant feel free to reopen and move it forward 👍

**Pull request closed without merging**
