### PR TITLE
ARROW-16013: [C++][Python] Signed overflow when using negative stride in NumPyStridedConverter

### PR DESCRIPTION
**Pull request by zagto**

### CODE REVIEW

**Comment by pitrou** [comment]
Is it possible to add a test that would fail without this fix?

**Comment by zagto** [comment]
Not in a way I know of.
- To reliably break it, we could use it on a numpy type, that is not a power of 2 in sizeof(). But that does not seem to exist x86_64. But for example long double on 32-bit x86 is 96-bit sizeof() (?)
- As long is the size is a power of two it depends on the behavior of signed overflow and the binary representation of negative numbers to work/break, which happens to make it work on common platforms.
- It could still break because of compiler optimizations, but then again that is something we can't really control in a test

**Comment by pitrou** [comment]
Ok, thanks. Can you then add a comment near your change pointing to the issue?

**Comment by zagto** [comment]
yes, added a comment

**Review by pitrou — APPROVED** [review]
Thank for the update @zagto, will merge.

**Pull request closed without merging**
