### PR TITLE
ARROW-5349: [WIP] Store file-path metadata

### PR DESCRIPTION
**Pull request by rjzamora**
This is a WIP PR to address [ARROW-5349](https://issues.apache.org/jira/browse/ARROW-5349).  From the python side, this exposes a `file_path` keyword argument to `write_table`.  The string is then used to populate file-path metadata for each column-chunk written.  

Here is a simple example:

```p
import os
import pandas as pd
import pyarrow.parquet as pq
import pyarrow as pa

df = pd.DataFrame({'a': ['A', 'B', 'C', 'D'], 'b': [1, 2, 3, 4]})
table = pa.Table.from_pandas(df)

metadata_list = []
path = "./smalldataset"; os.system('mkdir ' + path)
filename = path + "/part.0.parquet.dbg"
with open(filename, "wb") as f:
    pq.write_table(
        table,
        f,
        file_path=filename,
        metadata_collector=metadata_list
    )
meta = metadata_list[0].to_dict()
print(meta['row_groups'][0]['columns'][0]['file_path'])
```
Output: `./smalldataset/part.0.parquet.dbg`

This is a WIP - Please provide suggestions for cleaner solutions, etc.  Note that my C++ background is somewhat limited :)

### CODE REVIEW

**Comment by wesm** [comment]
hi @rjzamora I would prefer a solution that doesn't involve touching so many APIs. In my comment on ARROW-5349, I wrote "I would recommend adding a method on parquet::ParquetFileWriter that will set this attribute to a particular value for all column chunk metadata created. This method can be exposed then in Python". What do you think about this solution? This requires one new API endpoint in `parquet::arrow::FileWriter` and one new API in `ParquetFileWriter`, otherwise APIs are unchanged.

**Comment by rjzamora** [comment]
Thanks for the quick response @wesm - I completely agree that too many API's are touched.  Sorry I veered away from your suggestion, but I was having trouble figuring out an elegant way to utilize the `ColumnChunkMetaDataBuilder::set_file_path` API...   I am pretty confident that I can work out a much better solution

With that said, it is not immediately obvious to me how to modify the file-path metadata without adding additional methods (or modifying others) beyond the two APIs you mentioned.  I will take a closer look and follow up - Thanks again!

**Comment by wesm** [comment]
Well in terms of _public_ APIs those are the ones affected. Another option is to put the file path in the WriterProperties, what do you think about that?

**Comment by rjzamora** [comment]
Modifying the `WriterProperties` class does seem like a convenient solution to me.  My intuition is that it makes sense to add a `file_path_` member.  However, please do let me know if there is a good reason to avoid this approach.

**Comment by wesm** [comment]
That seems plenty reasonable to me

**Comment by jorisvandenbossche** [comment]
One remark on the actual functionality: this currently sets the file path both for the metadata written into the file itself, as for the metadata returned (appended to `metadata_collector`). 
I am not fully sure this is the desired behaviour (although it does not give problems when reading it back in, it seems, not sure if this file path is actually used currently in parquet-cpp). I don't know the parquet "common practices" well enough for that, but it is in any case not what fastparquet does, and we should probably check hive or spark that generate / read such datasets.

**Comment by wesm** [comment]
@jorisvandenbossche I think it's acceptable to set the path in the file's internal metadata. This metadata doesn't affect the operation of the library

**Comment by jorisvandenbossche** [comment]
In the parquet-cpp implementation, we currently indeed do not make use of `file_path` when reading, so setting it does not have any effect. 
But are we sure that it is the same for other implementation? (just a question, I have no idea)

The thrift description is quite clear it should not be set and that the path should be relative to the file (which is also not true here): "File where column data is stored.  If not set, assumed to be same file as metadata.  This path is relative to the current file."

**Comment by wesm** [comment]
So in the case that we have

```
$UUID.parquet
_metadata
```

The file_path in both cases is `$UUID.parquet`. So I think there is no conflict because the column data is in that file.

**Comment by jorisvandenbossche** [comment]
Even in such a case, other libraries (or at least fastparquet, I didn't try out others) don't set the file_path in the metadata inside the file. 
But once you have a nested dataset like

```
A=0/
    $UUID.parquet
A=1/
    $UUID.parquet
_metadata
```

then the file_path would be `A=0/$UUID.parquet`, in which this would be wrong if it is inside the file itself?

**Comment by wesm** [comment]
I'm not sure. Someone should look at parquet-mr or Impala (both developed under the supervision of people who designed Parquet) to see what they do. I don't think that fastparquet should be used as a point of truth since it was developed outside of the Apache Parquet community

**Comment by rjzamora** [comment]
I don't think there is anything wrong with setting the `file_path` in the footer metadata when there is a single file, or when all files are in the same directory.  To obey the thrift defintion of `file_path`, the value should just be the file name (without the path).  There would also be no problem in general if the `file_path` corresponded to the absolute path of the data (which was my mistaken assumption when I prepared this PR).  

Unfortunately, if `file_path` corresponds to a relative path, then the hypothetical example shared by @jorisvandenbossche is an obvious problem, because the footer would need to have a different value than the standalone metadata file (`_metadata`).  It seems that this kind of nested file structure should be supported, so I think that this example disqualifies the solution I have implemented so far.

Perhaps it is necessary to add a new C++ API (exposed in python) to modify the contents of an existing metadata object?  My understanding of the current arrow-parquet implementation is that a `FileMetaData` object becomes immutable once it is created.  There is a good chance that my understanding is wrong here,  but I am not seeing a straightforward way to modify the `ColumnChunkMetaData` after the fact.

**Comment by wesm** [comment]
I suggest you seek assistance on dev@parquet.apache.org, I don't have sufficient knowledge of what other systems are doing to know how to proceed

**Comment by mrocklin** [comment]
@martindurant may also be able to provide a perspective here

**Comment by martindurant** [comment]
I have been commenting on the sibling issue - but I won't be able to help with how the struct is stored or modified on the c++ side.

> I don't think there is anything wrong with setting the file_path in the footer metadata when there is a single file, or when all files are in the same directory.

The thrift spec seems to indicate that you should not. An obvious problem, is that the existence of the path can be indicative that a file needs to be opened. Even if it's the same file, this can have an overhead.

> It seems that this kind of nested file structure should be supported, so I think that this example disqualifies the solution I have implemented so far.

Agreed, you cannot have both.

**Comment by mrocklin** [comment]
From my perspective I don't see a reason to have the filename included in the metadata included in each file.  I'm alread at that file, presumably I don't need the filename any longer.  

I do very much want the filename when I'm reading the `_metadata` file.  Actually, for large datasets on cloud-based systems, getting the filenames where all row groups live is critical.  Otherwise we have to do a listing on 10k objects, which can take a surprisingly long time.  

Ideally when writing a partition, Arrow would do whatever is proper for footer metadata (I don't care about the file path here) but would return metadata objects to me in Python that had the appropriate file path set, or else would tell me the file path and the metadata and would provide me a mechanism to add the file path to the metadata.

In cases where a single Python call writes many separate files (such as happening when partitioning) then I would probably expect to get many separate metadata objects, each with the file path appropriately set, or I would expect to get separate metadata objects and associated file paths, and it would be up to me to properly clean up the filepath (by truncating it or adding a root directory to it) and then assign it back into the metadata object as I wrote all of them to the metadata file.

Does this make sense?  I *think* I've understood the concerns above, but I may be missing something.

**Comment by martindurant** [comment]
> it would be up to me to properly clean up the filepath

I would expect either
- we get a filename back with the metadata piece, can work out what the path in the metadata object should be and call some method to set it, for each one or
- the filenames in the metadata piece are correctly set by the writer and the outer layer doesn't do anything, which means the writer needs to know the root path.

Note that these paths are always relative.

**Comment by mrocklin** [comment]
+1 on @martindurant 's comment

**Comment by rjzamora** [comment]
@mrocklin The hope here was just that we could set the `file_path` attribute in the metadata as it was being created, allowing the following step of writing the `_metadata` file to be straightforward (you just need to take in a vector of `FileMetaData` objects, and write them to a file).  

My understanding of the `FileMetaData` implementation is that the `file_path` attributes cannot be changed in a trivial way - Instead, I *think* new metadata objects will need to be created from scratch when `_metadata` is written.

**Comment by martindurant** [comment]
> My understanding of the FileMetaData implementation

Obviously I can't speak to the implementation, but one would *think* it possible to write the metadata without a path and then change the path before passing back. Of course, if making a new instance is fast, well, why not?

**Comment by mrocklin** [comment]
> @mrocklin The hope here was just that we could set the file_path attribute in the metadata as it was being created, allowing the following step of writing the _metadata file to be straightforward (you just need to take in a vector of FileMetaData objects, and write them to a file).

This is the second option provided by @martindurant above

> the filenames in the metadata piece are correctly set by the writer and the outer layer doesn't do anything, which means the writer needs to know the root path.

> My understanding of the FileMetaData implementation is that the file_path attributes cannot be changed in a trivial way - Instead, I think new metadata objects will need to be created from scratch when _metadata is written.

That seems fine to me.  I suspect that these things are smallish.  If not, then presumably we would have to change the implementation to allow mutation.

**Comment by wesm** [comment]
I strongly suggest we take this discussion to the Apache Parquet dev mailing list. There's folks with an interest in Hive, Spark, Dremio, Impala, Presto, and other heavy Parquet users there who can comment. It won't take a lot of time and it may spare us some work

cc @majetideepak @xhochy

**Comment by wesm** [comment]
In Impala, it is checked that the file_path() attribute matches the path of the file

https://github.com/apache/impala/blob/d423979866c737005882f54d157819e43897a5e8/be/src/exec/parquet/parquet-column-readers.cc#L1123

so my guess is that writing the same path value in both places will not cause problems, but we should solicit more feedback

**Comment by jorisvandenbossche** [comment]
@rjzamora Given https://github.com/apache/arrow/pull/4386, I think this can be closed now?

So the PR of Wes (https://github.com/apache/arrow/pull/4386) resolves that one can set the file path on the FileMetadata object returned by the arrow parquet writers (through metadata_collector). Which means that a user of the python API (such as dask) can set the appropriate file path for the collected metadata objects before combining them.

As a reference, I checked what PySpark does last week, and here is a small dataset file written by it, in case somebody wants to inspect such a partitioned dataset: [test_pyspark_dataset.zip](https://github.com/apache/arrow/files/3222719/test_pyspark_dataset.zip) (and as expected, it sets only the file path in the `_metadata` file).

For the full workflow of writing a partitioned dataset, I think the main remaining item is to be able to write (and combine) a list of FileMetadata objects into a single metadata file (https://issues.apache.org/jira/browse/ARROW-1983). @rjzamora is that something you would like to look into as well?

**Comment by rjzamora** [comment]
Thanks @wesm and @jorisvandenbossche!  Yes, we can close this.  I am defintely happy to look into the combined `_metadata` write (https://issues.apache.org/jira/browse/ARROW-1983).  I am away from the computer today, but should have something tomorrow.

**Comment by wesm** [comment]
Yes @rjzamora if you could submit a patch to incrementally write FileMetaData to an `arrow::io::OutputStream*` and also to read such a `_metadata` file that would be great

**Comment by wesm** [comment]
I wrote in more detail on ARROW-1983 about the ask

**Comment by rjzamora** [comment]
@wesm Excellent - thanks!

**Pull request closed without merging**
