### PR TITLE
ARROW-14801: [JS][Release] WIP Verify javascript releases

### PR DESCRIPTION
**Pull request by bkmgit**

### CODE REVIEW

**Comment by pitrou** [comment]
@bkmgit Sorry for the silence here. Is this PR ready for review?

**Comment by pitrou** [comment]
cc @raulcd @assignUser

**Comment by bkmgit** [comment]
Still working on this. Thanks for the check.

**Comment by amol-** [comment]
Closing because it has been untouched for a while, in case it's still relevant feel free to reopen and move it forward 👍

**Pull request closed without merging**
