### PR TITLE
ARROW-16541: [R] [CI] Reduce the number of times lintr is run

### PR DESCRIPTION
**Pull request by dragosmg**
This PR will reduce the number of times `lintr::lint_package()` is being run to 1 (run only on the current release). At present it runs on each branch of the Windows CI workflows.

### CODE REVIEW

**Comment by dragosmg** [comment]
@github-actions crossbow submit -g r

**Comment by thisisnic** [comment]
Thanks - this looks good.  Before I approve this, any idea why the workflow you edited hasn't run here?  Not sure if the CI is a little behind or something else?

**Comment by dragosmg** [comment]
I have no idea. Judging by the workflow file, it should:
```
on:
  push:
    paths:
      - ".github/workflows/r.yml"
     ...
  pull_request:
    paths:
      - ".github/workflows/r.yml"
```

**Comment by assignUser** [comment]
It didn't run because it's broken: https://github.com/apache/arrow/actions/runs/2331023570
The issue are the double quotes, replace them with single quotes and this should work as expected (see [docs](https://docs.github.com/en/actions/learn-github-actions/expressions#literals))

**Review by thisisnic — APPROVED** [review]
Looks good - CI shows it's clearly only running on that particular job now - thanks for making this change @dragosmg!

**Pull request closed without merging**
