### PR TITLE
ARROW-713: [C++] Fix cmake linking issue in new IPC benchmark

### PR DESCRIPTION
**Pull request by jeffknupp**

### CODE REVIEW

**Review by wesm — APPROVED** [review]
+1, thanks. I had hacked around this in #440 but this is a better fix

**Comment by wesm** [comment]
@jeffknupp can you change the PR title to start with ARROW-713: ? thanks

**Comment by jeffknupp** [comment]
@wesm updated

**Review by xhochy — APPROVED** [review]
+1, thanks!

**Pull request closed without merging**
