### PR TITLE
GH-36828: [C++][Parquet] Make buffered RowGroupSerializer using BufferedPageWriter

### LINKED ISSUE #36828: [C++][Parquet] Parquet: buffered column writer uses unbuffered page writer
### Describe the bug, including details regarding any error messages, version, and platform.

https://github.com/apache/arrow/pull/35886/files#r1271424177

In `RowGroupSerializer::InitColumns`, the `buffered` flag is ignored after https://github.com/apache/arrow/pull/35886. Causing Buffered RowGroup Writer uses unbuffered page writer.

### Component(s)

C++, Parquet

### PR DESCRIPTION
**Pull request by mapleFU**
### Rationale for this change

See https://github.com/apache/arrow/issues/36828

### What changes are included in this PR?

Add `buffered` argument when building `PageWriter`

### Are these changes tested?

no

### Are there any user-facing changes?

no

* Closes: #36828

### CODE REVIEW

**Comment by mapleFU** [comment]
@wgtmac @pitrou
Also cc @yyang52

**Review by wgtmac — APPROVED** [review]
+1

**Comment by yyang52** [comment]
LGTM, thanks for the fixing!

**Comment by raulcd** [comment]
@pitrou this doesn't seem to be a blocker for 13.0.0 , right?

**Comment by wgtmac** [comment]
> @pitrou this doesn't seem to be a blocker for 13.0.0 , right?

You're right. That commit is not included in the release branch.

**Comment by pitrou** [comment]
@wgtmac Do you want to merge?

**Pull request merged**
