### PR TITLE
[CI][R] Allow failures in R Appveyor job

### PR DESCRIPTION
**Pull request by wesm**
Setting this temporarily until the cloud.r-project.org DNS issue is resolved

### CODE REVIEW

**Comment by pitrou** [comment]
Do those still happen?

**Comment by pitrou** [comment]
@nealrichardson

**Comment by nealrichardson** [comment]
Nope: https://downforeveryoneorjustme.com/r-project.org is green

**Comment by wesm** [comment]
Cool, glad this is not needed =)

**Pull request closed without merging**
