### PR TITLE
ARROW-7590: [C++] Don't ignore managed files in thirdparty

### PR DESCRIPTION
**Pull request by plusplusjiajia**
Fix https://issues.apache.org/jira/browse/ARROW-7590

### CODE REVIEW

**Comment by kou** [comment]
Thanks for the pull request.
But we should not install to `${SOURCE_DIR}/cpp/thirdparty/*-install`. We should install to `${BUILD_DIR}/**/*-install`.

It means that we should change install path in `cpp/cmake_modules/ThirdpartyToolchain.cmake` such as https://github.com/apache/arrow/blob/master/cpp/cmake_modules/ThirdpartyToolchain.cmake#L1170 to use `${BUILD_DIR}/**/*-install` like https://github.com/apache/arrow/blob/master/cpp/cmake_modules/ThirdpartyToolchain.cmake#L2205 instead of ignoring `${SOURCE_DIR}/cpp/thirdparty/*-install`.

With the CMake fix, we will be able to use `/thirdparty/*.tar*` and `/thirdparty/offline.env` instead of `thirdparty/` in `.gitignore`.

**Comment by plusplusjiajia** [comment]
> Thanks for the pull request.
> But we should not install to `${SOURCE_DIR}/cpp/thirdparty/*-install`. We should install to `${BUILD_DIR}/**/*-install`.
> 
> It means that we should change install path in `cpp/cmake_modules/ThirdpartyToolchain.cmake` such as https://github.com/apache/arrow/blob/master/cpp/cmake_modules/ThirdpartyToolchain.cmake#L1170 to use `${BUILD_DIR}/**/*-install` like https://github.com/apache/arrow/blob/master/cpp/cmake_modules/ThirdpartyToolchain.cmake#L2205 instead of ignoring `${SOURCE_DIR}/cpp/thirdparty/*-install`.
> 

Thanks for the suggestion.

> With the CMake fix, we will be able to use `/thirdparty/*.tar*` and `/thirdparty/offline.env` instead of `thirdparty/` in `.gitignore`.

I know `sh download_dependencies.sh` will download the dependencies to thirdparty folder, but I can'f find the offline.env file, the environment variables for offline Arrow build just `echo`. Could you tell me the way to create offline.env?

**Comment by kou** [comment]
Sorry. `offline.env` was created by me on local machine.
Normally, it doesn't exit. We don't need to care about it.

**Review by kou — APPROVED** [review]
+1
I'm waiting for CI.

**Comment by kou** [comment]
Failed tests aren't unrelated.
I'll merge this.

**Pull request closed without merging**
