### PR TITLE
[C++] Fix name of interval type

### PR DESCRIPTION
**Pull request by alexandreyc**

### CODE REVIEW

**Comment by wesm** [comment]
This type is as yet unimplemented/unused anywhere else in the library

**Comment by alexandreyc** [comment]
Yes that's what I discovered when looking for inspiration for the Go implementation.

I don't think I'm able to implement the C++ version though.

Should we leave the name as it is?

**Comment by wesm** [comment]
@alexandreyc I recommend that you do not create a Go implementation until the Format-level discussions are resolved around this. There is an active mailing list discussion

**Review by pitrou — APPROVED** [review]
+1. Looks harmless to me. We can probably also do without a JIRA on this one.

**Comment by kszucs** [comment]
Agree with @pitrou. Merging.

**Pull request merged**
