### PR TITLE
ARROW-12719: [C++] Allow passing S3 canned ACL as output stream metadata

### PR DESCRIPTION
**Pull request by pitrou**
This allows users to specify access rights when creating a file with the S3 filesystem.

Canned ACL values are described in https://docs.aws.amazon.com/AmazonS3/latest/userguide/acl-overview.html#canned-acl

### CODE REVIEW

**Review by lidavidm — APPROVED** [review]
LGTM.

A bit unfortunate it's not easily testable.

**Comment by melikekahya** [comment]
Hi, can you share an example for Python?

**Comment by lidavidm** [comment]
@melikekahya you can follow https://github.com/apache/arrow-cookbook/issues/156

**Comment by pitrou** [comment]
@melikekahya Something like:
```python
    # `fs` is an S3 filesystem
    metadata = {'ACL': 'public-read'}
    with fs.open_output_stream('myfile.txt', metadata=metadata) as f:
        ...
```

**Pull request closed without merging**
