### PR TITLE
ARROW-2302: [GLib] Unify GNU Autotools build and Meson build into one Travis CI job

### PR DESCRIPTION
**Pull request by kou**

### CODE REVIEW

**Comment by pitrou** [comment]
The C/glib build here took 16 minutes while it took on the order of 3 minutes before: https://travis-ci.org/apache/arrow/builds/373029547
Is that expected?

**Comment by kou** [comment]
Umm.
It may be a network problem.

  * `travis_install_linux.sh`:
    * [Before](https://travis-ci.org/apache/arrow/jobs/371023432#L491): took 11.12s
    * [After](https://travis-ci.org/apache/arrow/jobs/373029554#L500): took 355.60s
  * `travis_before_script_cpp.sh --only-library`:
    * [Before](https://travis-ci.org/apache/arrow/jobs/371023432#L621): took 43.14s
    * [After](https://travis-ci.org/apache/arrow/jobs/373029554#L632): took 189.50s

This change doesn't include changes of these scripts.

**Comment by pitrou** [comment]
Ok, I'm restarting the build to be sure.

**Review by pitrou — APPROVED** [review]
LGTM.

**Review by xhochy — APPROVED** [review]
+1, LGTM

Build times are back at 5min

**Pull request closed without merging**
