### PR TITLE
MINOR: [C++][Parquet] Fix test failure when codec is disabled

### PR DESCRIPTION
**Pull request by wgtmac**
### Rationale for this change

When parquet-cpp was built without any codec enabled, some test cases fail like below:
```
cmake .. -DCMAKE_BUILD_TYPE=Debug \
         -DARROW_PARQUET=ON \
         -DARROW_BUILD_TESTS=ON \
         -DARROW_WITH_ZLIB=OFF \
         -DARROW_WITH_ZSTD=OFF \
         -DARROW_WITH_SNAPPY=OFF 

ctest -j16 --output-on-failure

[----------] Global test environment tear-down
[==========] 110 tests from 31 test suites ran. (697 ms total)
[  PASSED  ] 104 tests.
[  SKIPPED ] 1 test, listed below:
[  SKIPPED ] TestDumpWithLocalFile.DumpOutput
[  FAILED  ] 5 tests, listed below:
[  FAILED  ] TestBooleanRLE.TestBooleanScanner
[  FAILED  ] TestBooleanRLE.TestBatchRead
[  FAILED  ] TestTextDeltaLengthByteArray.TestTextScanner
[  FAILED  ] TestTextDeltaLengthByteArray.TestBatchRead
[  FAILED  ] TestCheckDataPageCrc.SnappyPageV1
```

### What changes are included in this PR?

Protect the failed test cases with macros to avoid failure.

### Are these changes tested?

Make sure all unit tests pass.

### Are there any user-facing changes?

No

### CODE REVIEW

**Comment by wgtmac** [comment]
@kou @wjones127 @pitrou A minor fix

**Comment by wgtmac** [comment]
**AMD64 Windows 2019 C++17** build is broken: https://github.com/apache/arrow/actions/runs/4172253626/jobs/7228085530

```
FAILED: debug/arrow-compute-scalar-temporal-benchmark.exe 
cmd.exe /C "cd . && "C:\Program Files\CMake\bin\cmake.exe" -E vs_link_exe --intdir=src\arrow\compute\kernels\CMakeFiles\arrow-compute-scalar-temporal-benchmark.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100226~1.0\x64\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100226~1.0\x64\mt.exe --manifests  -- C:\PROGRA~2\MICROS~2\2019\ENTERP~1\VC\Tools\MSVC\1429~1.301\bin\Hostx64\x64\link.exe /nologo src\arrow\compute\kernels\CMakeFiles\arrow-compute-scalar-temporal-benchmark.dir\Unity\unity_0_cxx.cxx.obj  /out:debug\arrow-compute-scalar-temporal-benchmark.exe /implib:debug\arrow-compute-scalar-temporal-benchmark.lib /pdb:debug\arrow-compute-scalar-temporal-benchmark.pdb /version:0.0 /machine:x64  /NODEFAULTLIB:LIBCMT /debug /INCREMENTAL /subsystem:console  Shlwapi.lib  gbenchmark_ep\src\gbenchmark_ep-install\lib\benchmark_main.lib  gbenchmark_ep\src\gbenchmark_ep-install\lib\benchmark.lib  debug\arrow_testing.lib  debug\arrow.lib  "C:\Program Files\OpenSSL-Win64\lib\VC\libcrypto64MDd.lib"  "C:\Program Files\OpenSSL-Win64\lib\VC\libssl64MDd.lib"  orc_ep-install\lib\orc.lib  protobuf_ep-install\lib\libprotobuf.lib  utf8proc_ep-install\lib\utf8proc_static.lib  re2_ep-install\lib\re2.lib  googletest_ep-prefix\lib\gtest_maind.lib  googletest_ep-prefix\lib\gtestd.lib  googletest_ep-prefix\lib\gmockd.lib  "C:\Program Files\OpenSSL-Win64\lib\VC\libcrypto64MDd.lib"  lz4_ep-install\lib\lz4.lib  zlib_ep\src\zlib_ep-install\lib\zlibstaticd.lib  zstd_ep-install\lib\zstd_static.lib  snappy_ep\src\snappy_ep-install\lib\snappy.lib  mimalloc_ep\src\mimalloc_ep\lib\mimalloc-2.0\mimalloc-static-debug.lib  bcrypt.lib  psapi.lib  ws2_32.lib  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
LINK Pass 1: command "C:\PROGRA~2\MICROS~2\2019\ENTERP~1\VC\Tools\MSVC\1429~1.301\bin\Hostx64\x64\link.exe /nologo src\arrow\compute\kernels\CMakeFiles\arrow-compute-scalar-temporal-benchmark.dir\Unity\unity_0_cxx.cxx.obj /out:debug\arrow-compute-scalar-temporal-benchmark.exe /implib:debug\arrow-compute-scalar-temporal-benchmark.lib /pdb:debug\arrow-compute-scalar-temporal-benchmark.pdb /version:0.0 /machine:x64 /NODEFAULTLIB:LIBCMT /debug /INCREMENTAL /subsystem:console Shlwapi.lib gbenchmark_ep\src\gbenchmark_ep-install\lib\benchmark_main.lib gbenchmark_ep\src\gbenchmark_ep-install\lib\benchmark.lib debug\arrow_testing.lib debug\arrow.lib C:\Program Files\OpenSSL-Win64\lib\VC\libcrypto64MDd.lib C:\Program Files\OpenSSL-Win64\lib\VC\libssl64MDd.lib orc_ep-install\lib\orc.lib protobuf_ep-install\lib\libprotobuf.lib utf8proc_ep-install\lib\utf8proc_static.lib re2_ep-install\lib\re2.lib googletest_ep-prefix\lib\gtest_maind.lib googletest_ep-prefix\lib\gtestd.lib googletest_ep-prefix\lib\gmockd.lib C:\Program Files\OpenSSL-Win64\lib\VC\libcrypto64MDd.lib lz4_ep-install\lib\lz4.lib zlib_ep\src\zlib_ep-install\lib\zlibstaticd.lib zstd_ep-install\lib\zstd_static.lib snappy_ep\src\snappy_ep-install\lib\snappy.lib mimalloc_ep\src\mimalloc_ep\lib\mimalloc-2.0\mimalloc-static-debug.lib bcrypt.lib psapi.lib ws2_32.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:src\arrow\compute\kernels\CMakeFiles\arrow-compute-scalar-temporal-benchmark.dir/intermediate.manifest src\arrow\compute\kernels\CMakeFiles\arrow-compute-scalar-temporal-benchmark.dir/manifest.res" failed (exit code 1120) with the following output:
LINK : warning LNK4217: symbol '?RegisterBenchmarkInternal@internal@benchmark@@YAPEAVBenchmark@12@PEAV312@@Z (class benchmark::internal::Benchmark * __cdecl benchmark::internal::RegisterBenchmarkInternal(class benchmark::internal::Benchmark *))' defined in 'benchmark.lib(benchmark_register.cc.obj)' is imported by 'unity_0_cxx.cxx.obj' in function '"void __cdecl arrow::compute::`dynamic initializer for 'benchmark_uniq_100BenchmarkStrftime''(void)" (??__Ebenchmark_uniq_100BenchmarkStrftime@compute@arrow@@YAXXZ)'
LINK : warning LNK4217: symbol '?InitializeStreams@internal@benchmark@@YAHXZ (int __cdecl benchmark::internal::InitializeStreams(void))' defined in 'benchmark.lib(benchmark.cc.obj)' is imported by 'unity_0_cxx.cxx.obj' in function '"void __cdecl benchmark::internal::`dynamic initializer for 'stream_init_anchor''(void)" (??__Estream_init_anchor@internal@benchmark@@YAXXZ)'
LINK : warning LNK4217: symbol '?iterations@State@benchmark@@QEBA_JXZ (public: __int64 __cdecl benchmark::State::iterations(void)const )' defined in 'benchmark.lib(benchmark_runner.cc.obj)' is imported by 'unity_0_cxx.cxx.obj' in function '"void __cdecl arrow::compute::BenchmarkAssumeTimezone(class benchmark::State &)" (?BenchmarkAssumeTimezone@compute@arrow@@YAXAEAVState@benchmark@@@Z)'
LINK : warning LNK4217: symbol '?FinishKeepRunning@State@benchmark@@AEAAXXZ (private: void __cdecl benchmark::State::FinishKeepRunning(void))' defined in 'benchmark.lib(benchmark.cc.obj)' is imported by 'unity_0_cxx.cxx.obj' in function '"public: bool __cdecl benchmark::State::StateIterator::operator!=(struct benchmark::State::StateIterator const &)const " (??9StateIterator@State@benchmark@@QEBA_NAEBU012@@Z)'
LINK : warning LNK4217: symbol '?Unit@Benchmark@internal@benchmark@@QEAAPEAV123@W4TimeUnit@3@@Z (public: class benchmark::internal::Benchmark * __cdecl benchmark::internal::Benchmark::Unit(enum benchmark::TimeUnit))' defined in 'benchmark.lib(benchmark_register.cc.obj)' is imported by 'unity_0_cxx.cxx.obj' in function '"void __cdecl arrow::BenchmarkSetArgsWithSizes(class benchmark::internal::Benchmark *,class std::vector<__int64,class std::allocator<__int64> > const &)" (?BenchmarkSetArgsWithSizes@arrow@@YAXPEAVBenchmark@internal@benchmark@@AEBV?$vector@_JV?$allocator@_J@std@@@std@@@Z)'
LINK : warning LNK4217: symbol '?Args@Benchmark@internal@benchmark@@QEAAPEAV123@AEBV?$vector@_JV?$allocator@_J@std@@@std@@@Z (public: class benchmark::internal::Benchmark * __cdecl benchmark::internal::Benchmark::Args(class std::vector<__int64,class std::allocator<__int64> > const &))' defined in 'benchmark.lib(benchmark_register.cc.obj)' is imported by 'unity_0_cxx.cxx.obj' in function '"void __cdecl arrow::BenchmarkSetArgsWithSizes(class benchmark::internal::Benchmark *,class std::vector<__int64,class std::allocator<__int64> > const &)" (?BenchmarkSetArgsWithSizes@arrow@@YAXPEAVBenchmark@internal@benchmark@@AEBV?$vector@_JV?$allocator@_J@std@@@std@@@Z)'
LINK : warning LNK4217: symbol '?Apply@Benchmark@internal@benchmark@@QEAAPEAV123@P6AXPEAV123@@Z@Z (public: class benchmark::internal::Benchmark * __cdecl benchmark::internal::Benchmark::Apply(void (__cdecl*)(class benchmark::internal::Benchmark *)))' defined in 'benchmark.lib(benchmark_register.cc.obj)' is imported by 'unity_0_cxx.cxx.obj' in function '"void __cdecl arrow::compute::`dynamic initializer for 'benchmark_uniq_100BenchmarkStrftime''(void)" (??__Ebenchmark_uniq_100BenchmarkStrftime@compute@arrow@@YAXXZ)'
unity_0_cxx.cxx.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: struct benchmark::State::StateIterator __cdecl benchmark::State::begin(void)" (__imp_?begin@State@benchmark@@QEAA?AUStateIterator@12@XZ) referenced in function "void __cdecl arrow::compute::BenchmarkAssumeTimezone(class benchmark::State &)" (?BenchmarkAssumeTimezone@compute@arrow@@YAXAEAVState@benchmark@@@Z)
unity_0_cxx.cxx.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: struct benchmark::State::StateIterator __cdecl benchmark::State::end(void)" (__imp_?end@State@benchmark@@QEAA?AUStateIterator@12@XZ) referenced in function "void __cdecl arrow::compute::BenchmarkAssumeTimezone(class benchmark::State &)" (?BenchmarkAssumeTimezone@compute@arrow@@YAXAEAVState@benchmark@@@Z)
unity_0_cxx.cxx.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: void __cdecl benchmark::State::SetBytesProcessed(__int64)" (__imp_?SetBytesProcessed@State@benchmark@@QEAAX_J@Z) referenced in function "public: __cdecl arrow::RegressionArgs::~RegressionArgs(void)" (??1RegressionArgs@arrow@@QEAA@XZ)
unity_0_cxx.cxx.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: void __cdecl benchmark::State::SetItemsProcessed(__int64)" (__imp_?SetItemsProcessed@State@benchmark@@QEAAX_J@Z) referenced in function "void __cdecl arrow::compute::BenchmarkAssumeTimezone(class benchmark::State &)" (?BenchmarkAssumeTimezone@compute@arrow@@YAXAEAVState@benchmark@@@Z)
unity_0_cxx.cxx.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: __int64 __cdecl benchmark::State::range(unsigned __int64)const " (__imp_?range@State@benchmark@@QEBA_J_K@Z) referenced in function "public: __cdecl arrow::RegressionArgs::RegressionArgs(class benchmark::State &,bool)" (??0RegressionArgs@arrow@@QEAA@AEAVState@benchmark@@_N@Z)
unity_0_cxx.cxx.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: __cdecl benchmark::internal::FunctionBenchmark::FunctionBenchmark(char const *,void (__cdecl*)(class benchmark::State &))" (__imp_??0FunctionBenchmark@internal@benchmark@@QEAA@PEBDP6AXAEAVState@2@@Z@Z) referenced in function "void __cdecl arrow::compute::`dynamic initializer for 'benchmark_uniq_100BenchmarkStrftime''(void)" (??__Ebenchmark_uniq_100BenchmarkStrftime@compute@arrow@@YAXXZ)
unity_0_cxx.cxx.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: virtual __cdecl benchmark::internal::FunctionBenchmark::~FunctionBenchmark(void)" (__imp_??1FunctionBenchmark@internal@benchmark@@UEAA@XZ) referenced in function "public: virtual void * __cdecl benchmark::internal::FunctionBenchmark::`scalar deleting destructor'(unsigned int)" (??_GFunctionBenchmark@internal@benchmark@@UEAAPEAXI@Z)
debug\arrow-compute-scalar-temporal-benchmark.exe : fatal error LNK1120: 7 unresolved externals
[287/489] Linking CXX executable debug\arrow-dataset-file-ipc-test.exe
[288/489] Linking CXX executable debug\arrow-compute-vector-sort-benchmark.exe
FAILED: debug/arrow-compute-vector-sort-benchmark.exe 
cmd.exe /C "cd . && "C:\Program Files\CMake\bin\cmake.exe" -E vs_link_exe --intdir=src\arrow\compute\kernels\CMakeFiles\arrow-compute-vector-sort-benchmark.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100226~1.0\x64\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100226~1.0\x64\mt.exe --manifests  -- C:\PROGRA~2\MICROS~2\2019\ENTERP~1\VC\Tools\MSVC\1429~1.301\bin\Hostx64\x64\link.exe /nologo src\arrow\compute\kernels\CMakeFiles\arrow-compute-vector-sort-benchmark.dir\Unity\unity_0_cxx.cxx.obj  /out:debug\arrow-compute-vector-sort-benchmark.exe /implib:debug\arrow-compute-vector-sort-benchmark.lib /pdb:debug\arrow-compute-vector-sort-benchmark.pdb /version:0.0 /machine:x64  /NODEFAULTLIB:LIBCMT /debug /INCREMENTAL /subsystem:console  Shlwapi.lib  gbenchmark_ep\src\gbenchmark_ep-install\lib\benchmark_main.lib  gbenchmark_ep\src\gbenchmark_ep-install\lib\benchmark.lib  debug\arrow_testing.lib  debug\arrow.lib  "C:\Program Files\OpenSSL-Win64\lib\VC\libcrypto64MDd.lib"  "C:\Program Files\OpenSSL-Win64\lib\VC\libssl64MDd.lib"  orc_ep-install\lib\orc.lib  protobuf_ep-install\lib\libprotobuf.lib  utf8proc_ep-install\lib\utf8proc_static.lib  re2_ep-install\lib\re2.lib  googletest_ep-prefix\lib\gtest_maind.lib  googletest_ep-prefix\lib\gtestd.lib  googletest_ep-prefix\lib\gmockd.lib  "C:\Program Files\OpenSSL-Win64\lib\VC\libcrypto64MDd.lib"  lz4_ep-install\lib\lz4.lib  zlib_ep\src\zlib_ep-install\lib\zlibstaticd.lib  zstd_ep-install\lib\zstd_static.lib  snappy_ep\src\snappy_ep-install\lib\snappy.lib  mimalloc_ep\src\mimalloc_ep\lib\mimalloc-2.0\mimalloc-static-debug.lib  bcrypt.lib  psapi.lib  ws2_32.lib  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
LINK Pass 1: command "C:\PROGRA~2\MICROS~2\2019\ENTERP~1\VC\Tools\MSVC\1429~1.301\bin\Hostx64\x64\link.exe /nologo src\arrow\compute\kernels\CMakeFiles\arrow-compute-vector-sort-benchmark.dir\Unity\unity_0_cxx.cxx.obj /out:debug\arrow-compute-vector-sort-benchmark.exe /implib:debug\arrow-compute-vector-sort-benchmark.lib /pdb:debug\arrow-compute-vector-sort-benchmark.pdb /version:0.0 /machine:x64 /NODEFAULTLIB:LIBCMT /debug /INCREMENTAL /subsystem:console Shlwapi.lib gbenchmark_ep\src\gbenchmark_ep-install\lib\benchmark_main.lib gbenchmark_ep\src\gbenchmark_ep-install\lib\benchmark.lib debug\arrow_testing.lib debug\arrow.lib C:\Program Files\OpenSSL-Win64\lib\VC\libcrypto64MDd.lib C:\Program Files\OpenSSL-Win64\lib\VC\libssl64MDd.lib orc_ep-install\lib\orc.lib protobuf_ep-install\lib\libprotobuf.lib utf8proc_ep-install\lib\utf8proc_static.lib re2_ep-install\lib\re2.lib googletest_ep-prefix\lib\gtest_maind.lib googletest_ep-prefix\lib\gtestd.lib googletest_ep-prefix\lib\gmockd.lib C:\Program Files\OpenSSL-Win64\lib\VC\libcrypto64MDd.lib lz4_ep-install\lib\lz4.lib zlib_ep\src\zlib_ep-install\lib\zlibstaticd.lib zstd_ep-install\lib\zstd_static.lib snappy_ep\src\snappy_ep-install\lib\snappy.lib mimalloc_ep\src\mimalloc_ep\lib\mimalloc-2.0\mimalloc-static-debug.lib bcrypt.lib psapi.lib ws2_32.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:src\arrow\compute\kernels\CMakeFiles\arrow-compute-vector-sort-benchmark.dir/intermediate.manifest src\arrow\compute\kernels\CMakeFiles\arrow-compute-vector-sort-benchmark.dir/manifest.res" failed (exit code 1120) with the following output:
LINK : warning LNK4217: symbol '?RegisterBenchmarkInternal@internal@benchmark@@YAPEAVBenchmark@12@PEAV312@@Z (class benchmark::internal::Benchmark * __cdecl benchmark::internal::RegisterBenchmarkInternal(class benchmark::internal::Benchmark *))' defined in 'benchmark.lib(benchmark_register.cc.obj)' is imported by 'unity_0_cxx.cxx.obj' in function '"void __cdecl arrow::compute::`dynamic initializer for 'benchmark_uniq_23_benchmark_''(void)" (??__Ebenchmark_uniq_23_benchmark_@compute@arrow@@YAXXZ)'
LINK : warning LNK4217: symbol '?InitializeStreams@internal@benchmark@@YAHXZ (int __cdecl benchmark::internal::InitializeStreams(void))' defined in 'benchmark.lib(benchmark.cc.obj)' is imported by 'unity_0_cxx.cxx.obj' in function '"void __cdecl benchmark::internal::`dynamic initializer for 'stream_init_anchor''(void)" (??__Estream_init_anchor@internal@benchmark@@YAXXZ)'
LINK : warning LNK4217: symbol '?iterations@State@benchmark@@QEBA_JXZ (public: __int64 __cdecl benchmark::State::iterations(void)const )' defined in 'benchmark.lib(benchmark_runner.cc.obj)' is imported by 'unity_0_cxx.cxx.obj' in function '"void __cdecl arrow::compute::ArraySortFuncBenchmark<struct arrow::compute::SortRunner,class arrow::Array>(class benchmark::State &,struct arrow::compute::SortRunner const &,class std::shared_ptr<class arrow::Array> const &)" (??$ArraySortFuncBenchmark@USortRunner@compute@arrow@@VArray@3@@compute@arrow@@YAXAEAVState@benchmark@@AEBUSortRunner@01@AEBV?$shared_ptr@VArray@arrow@@@std@@@Z)'
LINK : warning LNK4217: symbol '?FinishKeepRunning@State@benchmark@@AEAAXXZ (private: void __cdecl benchmark::State::FinishKeepRunning(void))' defined in 'benchmark.lib(benchmark.cc.obj)' is imported by 'unity_0_cxx.cxx.obj' in function '"public: bool __cdecl benchmark::State::StateIterator::operator!=(struct benchmark::State::StateIterator const &)const " (??9StateIterator@State@benchmark@@QEBA_NAEBU012@@Z)'
LINK : warning LNK4217: symbol '?Unit@Benchmark@internal@benchmark@@QEAAPEAV123@W4TimeUnit@3@@Z (public: class benchmark::internal::Benchmark * __cdecl benchmark::internal::Benchmark::Unit(enum benchmark::TimeUnit))' defined in 'benchmark.lib(benchmark_register.cc.obj)' is imported by 'unity_0_cxx.cxx.obj' in function '"void __cdecl arrow::BenchmarkSetArgsWithSizes(class benchmark::internal::Benchmark *,class std::vector<__int64,class std::allocator<__int64> > const &)" (?BenchmarkSetArgsWithSizes@arrow@@YAXPEAVBenchmark@internal@benchmark@@AEBV?$vector@_JV?$allocator@_J@std@@@std@@@Z)'
LINK : warning LNK4217: symbol '?Args@Benchmark@internal@benchmark@@QEAAPEAV123@AEBV?$vector@_JV?$allocator@_J@std@@@std@@@Z (public: class benchmark::internal::Benchmark * __cdecl benchmark::internal::Benchmark::Args(class std::vector<__int64,class std::allocator<__int64> > const &))' defined in 'benchmark.lib(benchmark_register.cc.obj)' is imported by 'unity_0_cxx.cxx.obj' in function '"void __cdecl arrow::BenchmarkSetArgsWithSizes(class benchmark::internal::Benchmark *,class std::vector<__int64,class std::allocator<__int64> > const &)" (?BenchmarkSetArgsWithSizes@arrow@@YAXPEAVBenchmark@internal@benchmark@@AEBV?$vector@_JV?$allocator@_J@std@@@std@@@Z)'
LINK : warning LNK4217: symbol '?ArgsProduct@Benchmark@internal@benchmark@@QEAAPEAV123@AEBV?$vector@V?$vector@_JV?$allocator@_J@std@@@std@@V?$allocator@V?$vector@_JV?$allocator@_J@std@@@std@@@2@@std@@@Z (public: class benchmark::internal::Benchmark * __cdecl benchmark::internal::Benchmark::ArgsProduct(class std::vector<class std::vector<__int64,class std::allocator<__int64> >,class std::allocator<class std::vector<__int64,class std::allocator<__int64> > > > const &))' defined in 'benchmark.lib(benchmark_register.cc.obj)' is imported by 'unity_0_cxx.cxx.obj' in function '"void __cdecl arrow::compute::`dynamic initializer for 'benchmark_uniq_28_benchmark_''(void)" (??__Ebenchmark_uniq_28_benchmark_@compute@arrow@@YAXXZ)'
LINK : warning LNK4217: symbol '?ArgNames@Benchmark@internal@benchmark@@QEAAPEAV123@AEBV?$vector@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$allocator@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@@std@@@Z (public: class benchmark::internal::Benchmark * __cdecl benchmark::internal::Benchmark::ArgNames(class std::vector<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::allocator<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > > const &))' defined in 'benchmark.lib(benchmark_register.cc.obj)' is imported by 'unity_0_cxx.cxx.obj' in function '"void __cdecl arrow::compute::ArrayRankSetArgs(class benchmark::internal::Benchmark *)" (?ArrayRankSetArgs@compute@arrow@@YAXPEAVBenchmark@internal@benchmark@@@Z)'
LINK : warning LNK4217: symbol '?Apply@Benchmark@internal@benchmark@@QEAAPEAV123@P6AXPEAV123@@Z@Z (public: class benchmark::internal::Benchmark * __cdecl benchmark::internal::Benchmark::Apply(void (__cdecl*)(class benchmark::internal::Benchmark *)))' defined in 'benchmark.lib(benchmark_register.cc.obj)' is imported by 'unity_0_cxx.cxx.obj' in function '"void __cdecl arrow::compute::ArraySortIndicesSetArgs(class benchmark::internal::Benchmark *)" (?ArraySortIndicesSetArgs@compute@arrow@@YAXPEAVBenchmark@internal@benchmark@@@Z)'
unity_0_cxx.cxx.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: struct benchmark::State::StateIterator __cdecl benchmark::State::begin(void)" (__imp_?begin@State@benchmark@@QEAA?AUStateIterator@12@XZ) referenced in function "void __cdecl arrow::compute::DatumSortIndicesBenchmark(class benchmark::State &,struct arrow::Datum const &,class arrow::compute::SortOptions const &)" (?DatumSortIndicesBenchmark@compute@arrow@@YAXAEAVState@benchmark@@AEBUDatum@2@AEBVSortOptions@12@@Z)
unity_0_cxx.cxx.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: struct benchmark::State::StateIterator __cdecl benchmark::State::end(void)" (__imp_?end@State@benchmark@@QEAA?AUStateIterator@12@XZ) referenced in function "void __cdecl arrow::compute::DatumSortIndicesBenchmark(class benchmark::State &,struct arrow::Datum const &,class arrow::compute::SortOptions const &)" (?DatumSortIndicesBenchmark@compute@arrow@@YAXAEAVState@benchmark@@AEBUDatum@2@AEBVSortOptions@12@@Z)
unity_0_cxx.cxx.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: void __cdecl benchmark::State::SetBytesProcessed(__int64)" (__imp_?SetBytesProcessed@State@benchmark@@QEAAX_J@Z) referenced in function "public: __cdecl arrow::RegressionArgs::~RegressionArgs(void)" (??1RegressionArgs@arrow@@QEAA@XZ)
unity_0_cxx.cxx.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: void __cdecl benchmark::State::SetItemsProcessed(__int64)" (__imp_?SetItemsProcessed@State@benchmark@@QEAAX_J@Z) referenced in function "void __cdecl arrow::compute::ArraySortFuncBenchmark<struct arrow::compute::SortRunner,class arrow::Array>(class benchmark::State &,struct arrow::compute::SortRunner const &,class std::shared_ptr<class arrow::Array> const &)" (??$ArraySortFuncBenchmark@USortRunner@compute@arrow@@VArray@3@@compute@arrow@@YAXAEAVState@benchmark@@AEBUSortRunner@01@AEBV?$shared_ptr@VArray@arrow@@@std@@@Z)
unity_0_cxx.cxx.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: __int64 __cdecl benchmark::State::range(unsigned __int64)const " (__imp_?range@State@benchmark@@QEBA_J_K@Z) referenced in function "public: __cdecl arrow::compute::RankRunner::RankRunner(class benchmark::State &)" (??0RankRunner@compute@arrow@@QEAA@AEAVState@benchmark@@@Z)
unity_0_cxx.cxx.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: __cdecl benchmark::internal::FunctionBenchmark::FunctionBenchmark(char const *,void (__cdecl*)(class benchmark::State &))" (__imp_??0FunctionBenchmark@internal@benchmark@@QEAA@PEBDP6AXAEAVState@2@@Z@Z) referenced in function "void __cdecl arrow::compute::`dynamic initializer for 'benchmark_uniq_23_benchmark_''(void)" (??__Ebenchmark_uniq_23_benchmark_@compute@arrow@@YAXXZ)
unity_0_cxx.cxx.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: virtual __cdecl benchmark::internal::FunctionBenchmark::~FunctionBenchmark(void)" (__imp_??1FunctionBenchmark@internal@benchmark@@UEAA@XZ) referenced in function "public: virtual void * __cdecl benchmark::internal::FunctionBenchmark::`scalar deleting destructor'(unsigned int)" (??_GFunctionBenchmark@internal@benchmark@@UEAAPEAXI@Z)
debug\arrow-compute-vector-sort-benchmark.exe : fatal error LNK1120: 7 unresolved externals
ninja: build stopped: subcommand failed.
```

Not sure if it is related to https://github.com/apache/arrow/pull/33731 @kou

**Comment by kou** [comment]
Oh, could you open a new issue for it and mention to @wjones127 in the issue?

**Review by kou — APPROVED** [review]
+1

**Comment by wgtmac** [comment]
> Oh, could you open a new issue for it and mention to @wjones127 in the issue?

Created https://github.com/apache/arrow/issues/34188. Thanks @kou!

**Pull request merged**
