### PR TITLE
ARROW-18036: [C++] Use BUILD_TESTING=OFF for abseil-cpp

### PR DESCRIPTION
**Pull request by nealrichardson**
In practice I believe that tests were off by default, but this at least switches us to an argument that is respected and removes the warning about unknown cmake args.

### CODE REVIEW

**Comment by pitrou** [comment]
I hope this also reduces build times? :-)

**Comment by pitrou** [comment]
Revision: db99b320ed8fb997f775049f965f088665c30ff1

Submitted crossbow builds: [ursacomputing/crossbow @ absl-no-tests-0](https://github.com/ursacomputing/crossbow/branches/all?query=absl-no-tests-0)

|Task|Status|
|----|------|
|almalinux-8-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:absl-no-tests-0-github-almalinux-8-amd64)|
|almalinux-8-arm64|[TravisCI](https://app.travis-ci.com/github/ursacomputing/crossbow/branches)|
|almalinux-9-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:absl-no-tests-0-github-almalinux-9-amd64)|
|almalinux-9-arm64|[TravisCI](https://app.travis-ci.com/github/ursacomputing/crossbow/branches)|
|amazon-linux-2-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:absl-no-tests-0-github-amazon-linux-2-amd64)|
|amazon-linux-2-arm64|[TravisCI](https://app.travis-ci.com/github/ursacomputing/crossbow/branches)|
|centos-7-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:absl-no-tests-0-github-centos-7-amd64)|
|centos-8-stream-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:absl-no-tests-0-github-centos-8-stream-amd64)|
|centos-8-stream-arm64|[TravisCI](https://app.travis-ci.com/github/ursacomputing/crossbow/branches)|
|centos-9-stream-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:absl-no-tests-0-github-centos-9-stream-amd64)|
|centos-9-stream-arm64|[TravisCI](https://app.travis-ci.com/github/ursacomputing/crossbow/branches)|
|conan-maximum|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:absl-no-tests-0-github-conan-maximum)|
|conan-minimum|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:absl-no-tests-0-github-conan-minimum)|
|conda-clean|[Azure](https://dev.azure.com/ursacomputing/crossbow/_build/latest?definitionId=1&branchName=absl-no-tests-0-azure-conda-clean)|
|conda-linux-gcc-py310-arm64|[Azure](https://dev.azure.com/ursacomputing/crossbow/_build/latest?definitionId=1&branchName=absl-no-tests-0-azure-conda-linux-gcc-py310-arm64)|
|conda-linux-gcc-py310-cpu|[Azure](https://dev.azure.com/ursacomputing/crossbow/_build/latest?definitionId=1&branchName=absl-no-tests-0-azure-conda-linux-gcc-py310-cpu)|
|conda-linux-gcc-py310-cuda|[Azure](https://dev.azure.com/ursacomputing/crossbow/_build/latest?definitionId=1&branchName=absl-no-tests-0-azure-conda-linux-gcc-py310-cuda)|
|conda-linux-gcc-py310-ppc64le|[Azure](https://dev.azure.com/ursacomputing/crossbow/_build/latest?definitionId=1&branchName=absl-no-tests-0-azure-conda-linux-gcc-py310-ppc64le)|
|conda-linux-gcc-py37-arm64|[Azure](https://dev.azure.com/ursacomputing/crossbow/_build/latest?definitionId=1&branchName=absl-no-tests-0-azure-conda-linux-gcc-py37-arm64)|
|conda-linux-gcc-py37-cpu-r40|[Azure](https://dev.azure.com/ursacomputing/crossbow/_build/latest?definitionId=1&branchName=absl-no-tests-0-azure-conda-linux-gcc-py37-cpu-r40)|
|conda-linux-gcc-py37-cpu-r41|[Azure](https://dev.azure.com/ursacomputing/crossbow/_build/latest?definitionId=1&branchName=absl-no-tests-0-azure-conda-linux-gcc-py37-cpu-r41)|
|conda-linux-gcc-py37-cuda|[Azure](https://dev.azure.com/ursacomputing/crossbow/_build/latest?definitionId=1&branchName=absl-no-tests-0-azure-conda-linux-gcc-py37-cuda)|
|conda-linux-gcc-py37-ppc64le|[Azure](https://dev.azure.com/ursacomputing/crossbow/_build/latest?definitionId=1&branchName=absl-no-tests-0-azure-conda-linux-gcc-py37-ppc64le)|
|conda-linux-gcc-py38-arm64|[Azure](https://dev.azure.com/ursacomputing/crossbow/_build/latest?definitionId=1&branchName=absl-no-tests-0-azure-conda-linux-gcc-py38-arm64)|
|conda-linux-gcc-py38-cpu|[Azure](https://dev.azure.com/ursacomputing/crossbow/_build/latest?definitionId=1&branchName=absl-no-tests-0-azure-conda-linux-gcc-py38-cpu)|
|conda-linux-gcc-py38-cuda|[Azure](https://dev.azure.com/ursacomputing/crossbow/_build/latest?definitionId=1&branchName=absl-no-tests-0-azure-conda-linux-gcc-py38-cuda)|
|conda-linux-gcc-py38-ppc64le|[Azure](https://dev.azure.com/ursacomputing/crossbow/_build/latest?definitionId=1&branchName=absl-no-tests-0-azure-conda-linux-gcc-py38-ppc64le)|
|conda-linux-gcc-py39-arm64|[Azure](https://dev.azure.com/ursacomputing/crossbow/_build/latest?definitionId=1&branchName=absl-no-tests-0-azure-conda-linux-gcc-py39-arm64)|
|conda-linux-gcc-py39-cpu|[Azure](https://dev.azure.com/ursacomputing/crossbow/_build/latest?definitionId=1&branchName=absl-no-tests-0-azure-conda-linux-gcc-py39-cpu)|
|conda-linux-gcc-py39-cuda|[Azure](https://dev.azure.com/ursacomputing/crossbow/_build/latest?definitionId=1&branchName=absl-no-tests-0-azure-conda-linux-gcc-py39-cuda)|
|conda-linux-gcc-py39-ppc64le|[Azure](https://dev.azure.com/ursacomputing/crossbow/_build/latest?definitionId=1&branchName=absl-no-tests-0-azure-conda-linux-gcc-py39-ppc64le)|
|conda-osx-arm64-clang-py310|[Azure](https://dev.azure.com/ursacomputing/crossbow/_build/latest?definitionId=1&branchName=absl-no-tests-0-azure-conda-osx-arm64-clang-py310)|
|conda-osx-arm64-clang-py38|[Azure](https://dev.azure.com/ursacomputing/crossbow/_build/latest?definitionId=1&branchName=absl-no-tests-0-azure-conda-osx-arm64-clang-py38)|
|conda-osx-arm64-clang-py39|[Azure](https://dev.azure.com/ursacomputing/crossbow/_build/latest?definitionId=1&branchName=absl-no-tests-0-azure-conda-osx-arm64-clang-py39)|
|conda-osx-clang-py310|[Azure](https://dev.azure.com/ursacomputing/crossbow/_build/latest?definitionId=1&branchName=absl-no-tests-0-azure-conda-osx-clang-py310)|
|conda-osx-clang-py37-r40|[Azure](https://dev.azure.com/ursacomputing/crossbow/_build/latest?definitionId=1&branchName=absl-no-tests-0-azure-conda-osx-clang-py37-r40)|
|conda-osx-clang-py37-r41|[Azure](https://dev.azure.com/ursacomputing/crossbow/_build/latest?definitionId=1&branchName=absl-no-tests-0-azure-conda-osx-clang-py37-r41)|
|conda-osx-clang-py38|[Azure](https://dev.azure.com/ursacomputing/crossbow/_build/latest?definitionId=1&branchName=absl-no-tests-0-azure-conda-osx-clang-py38)|
|conda-osx-clang-py39|[Azure](https://dev.azure.com/ursacomputing/crossbow/_build/latest?definitionId=1&branchName=absl-no-tests-0-azure-conda-osx-clang-py39)|
|conda-win-vs2019-py310|[Azure](https://dev.azure.com/ursacomputing/crossbow/_build/latest?definitionId=1&branchName=absl-no-tests-0-azure-conda-win-vs2019-py310)|
|conda-win-vs2019-py37-r40|[Azure](https://dev.azure.com/ursacomputing/crossbow/_build/latest?definitionId=1&branchName=absl-no-tests-0-azure-conda-win-vs2019-py37-r40)|
|conda-win-vs2019-py37-r41|[Azure](https://dev.azure.com/ursacomputing/crossbow/_build/latest?definitionId=1&branchName=absl-no-tests-0-azure-conda-win-vs2019-py37-r41)|
|conda-win-vs2019-py38|[Azure](https://dev.azure.com/ursacomputing/crossbow/_build/latest?definitionId=1&branchName=absl-no-tests-0-azure-conda-win-vs2019-py38)|
|conda-win-vs2019-py39|[Azure](https://dev.azure.com/ursacomputing/crossbow/_build/latest?definitionId=1&branchName=absl-no-tests-0-azure-conda-win-vs2019-py39)|
|debian-bookworm-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:absl-no-tests-0-github-debian-bookworm-amd64)|
|debian-bookworm-arm64|[TravisCI](https://app.travis-ci.com/github/ursacomputing/crossbow/branches)|
|debian-bullseye-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:absl-no-tests-0-github-debian-bullseye-amd64)|
|debian-bullseye-arm64|[TravisCI](https://app.travis-ci.com/github/ursacomputing/crossbow/branches)|
|example-cpp-minimal-build-static|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:absl-no-tests-0-github-example-cpp-minimal-build-static)|
|example-cpp-minimal-build-static-system-dependency|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:absl-no-tests-0-github-example-cpp-minimal-build-static-system-dependency)|
|example-python-minimal-build-fedora-conda|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:absl-no-tests-0-github-example-python-minimal-build-fedora-conda)|
|example-python-minimal-build-ubuntu-venv|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:absl-no-tests-0-github-example-python-minimal-build-ubuntu-venv)|
|homebrew-cpp|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:absl-no-tests-0-github-homebrew-cpp)|
|homebrew-r-autobrew|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:absl-no-tests-0-github-homebrew-r-autobrew)|
|homebrew-r-brew|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:absl-no-tests-0-github-homebrew-r-brew)|
|java-jars|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:absl-no-tests-0-github-java-jars)|
|nuget|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:absl-no-tests-0-github-nuget)|
|python-sdist|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:absl-no-tests-0-github-python-sdist)|
|r-binary-packages|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:absl-no-tests-0-github-r-binary-packages)|
|test-alpine-linux-cpp|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:absl-no-tests-0-github-test-alpine-linux-cpp)|
|test-build-cpp-fuzz|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:absl-no-tests-0-github-test-build-cpp-fuzz)|
|test-build-vcpkg-win|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:absl-no-tests-0-github-test-build-vcpkg-win)|
|test-conda-cpp|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:absl-no-tests-0-github-test-conda-cpp)|
|test-conda-cpp-valgrind|[Azure](https://dev.azure.com/ursacomputing/crossbow/_build/latest?definitionId=1&branchName=absl-no-tests-0-azure-test-conda-cpp-valgrind)|
|test-conda-python-3.10|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:absl-no-tests-0-github-test-conda-python-3.10)|
|test-conda-python-3.7|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:absl-no-tests-0-github-test-conda-python-3.7)|
|test-conda-python-3.7-hdfs-2.9.2|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:absl-no-tests-0-github-test-conda-python-3.7-hdfs-2.9.2)|
|test-conda-python-3.7-hdfs-3.2.1|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:absl-no-tests-0-github-test-conda-python-3.7-hdfs-3.2.1)|
|test-conda-python-3.7-pandas-0.24|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:absl-no-tests-0-github-test-conda-python-3.7-pandas-0.24)|
|test-conda-python-3.7-pandas-latest|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:absl-no-tests-0-github-test-conda-python-3.7-pandas-latest)|
|test-conda-python-3.7-spark-v3.1.2|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:absl-no-tests-0-github-test-conda-python-3.7-spark-v3.1.2)|
|test-conda-python-3.8|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:absl-no-tests-0-github-test-conda-python-3.8)|
|test-conda-python-3.8-hypothesis|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:absl-no-tests-0-github-test-conda-python-3.8-hypothesis)|
|test-conda-python-3.8-pandas-latest|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:absl-no-tests-0-github-test-conda-python-3.8-pandas-latest)|
|test-conda-python-3.8-pandas-nightly|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:absl-no-tests-0-github-test-conda-python-3.8-pandas-nightly)|
|test-conda-python-3.8-spark-v3.2.0|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:absl-no-tests-0-github-test-conda-python-3.8-spark-v3.2.0)|
|test-conda-python-3.9|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:absl-no-tests-0-github-test-conda-python-3.9)|
|test-conda-python-3.9-dask-latest|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:absl-no-tests-0-github-test-conda-python-3.9-dask-latest)|
|test-conda-python-3.9-dask-master|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:absl-no-tests-0-github-test-conda-python-3.9-dask-master)|
|test-conda-python-3.9-pandas-master|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:absl-no-tests-0-github-test-conda-python-3.9-pandas-master)|
|test-conda-python-3.9-spark-master|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:absl-no-tests-0-github-test-conda-python-3.9-spark-master)|
|test-debian-10-cpp-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:absl-no-tests-0-github-test-debian-10-cpp-amd64)|
|test-debian-10-cpp-i386|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:absl-no-tests-0-github-test-debian-10-cpp-i386)|
|test-debian-11-cpp-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:absl-no-tests-0-github-test-debian-11-cpp-amd64)|
|test-debian-11-cpp-i386|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:absl-no-tests-0-github-test-debian-11-cpp-i386)|
|test-debian-11-go-1.17|[Azure](https://dev.azure.com/ursacomputing/crossbow/_build/latest?definitionId=1&branchName=absl-no-tests-0-azure-test-debian-11-go-1.17)|
|test-debian-11-python-3|[Azure](https://dev.azure.com/ursacomputing/crossbow/_build/latest?definitionId=1&branchName=absl-no-tests-0-azure-test-debian-11-python-3)|
|test-debian-c-glib|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:absl-no-tests-0-github-test-debian-c-glib)|
|test-debian-ruby|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:absl-no-tests-0-github-test-debian-ruby)|
|test-fedora-35-cpp|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:absl-no-tests-0-github-test-fedora-35-cpp)|
|test-fedora-35-python-3|[Azure](https://dev.azure.com/ursacomputing/crossbow/_build/latest?definitionId=1&branchName=absl-no-tests-0-azure-test-fedora-35-python-3)|
|test-fedora-r-clang-sanitizer|[Azure](https://dev.azure.com/ursacomputing/crossbow/_build/latest?definitionId=1&branchName=absl-no-tests-0-azure-test-fedora-r-clang-sanitizer)|
|test-r-arrow-backwards-compatibility|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:absl-no-tests-0-github-test-r-arrow-backwards-compatibility)|
|test-r-depsource-bundled|[Azure](https://dev.azure.com/ursacomputing/crossbow/_build/latest?definitionId=1&branchName=absl-no-tests-0-azure-test-r-depsource-bundled)|
|test-r-depsource-system|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:absl-no-tests-0-github-test-r-depsource-system)|
|test-r-dev-duckdb|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:absl-no-tests-0-github-test-r-dev-duckdb)|
|test-r-devdocs|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:absl-no-tests-0-github-test-r-devdocs)|
|test-r-gcc-11|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:absl-no-tests-0-github-test-r-gcc-11)|
|test-r-gcc-12|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:absl-no-tests-0-github-test-r-gcc-12)|
|test-r-install-local|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:absl-no-tests-0-github-test-r-install-local)|
|test-r-install-local-minsizerel|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:absl-no-tests-0-github-test-r-install-local-minsizerel)|
|test-r-linux-as-cran|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:absl-no-tests-0-github-test-r-linux-as-cran)|
|test-r-linux-rchk|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:absl-no-tests-0-github-test-r-linux-rchk)|
|test-r-linux-valgrind|[Azure](https://dev.azure.com/ursacomputing/crossbow/_build/latest?definitionId=1&branchName=absl-no-tests-0-azure-test-r-linux-valgrind)|
|test-r-minimal-build|[Azure](https://dev.azure.com/ursacomputing/crossbow/_build/latest?definitionId=1&branchName=absl-no-tests-0-azure-test-r-minimal-build)|
|test-r-offline-maximal|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:absl-no-tests-0-github-test-r-offline-maximal)|
|test-r-offline-minimal|[Azure](https://dev.azure.com/ursacomputing/crossbow/_build/latest?definitionId=1&branchName=absl-no-tests-0-azure-test-r-offline-minimal)|
|test-r-rhub-debian-gcc-devel-lto-latest|[Azure](https://dev.azure.com/ursacomputing/crossbow/_build/latest?definitionId=1&branchName=absl-no-tests-0-azure-test-r-rhub-debian-gcc-devel-lto-latest)|
|test-r-rhub-debian-gcc-release-custom-ccache|[Azure](https://dev.azure.com/ursacomputing/crossbow/_build/latest?definitionId=1&branchName=absl-no-tests-0-azure-test-r-rhub-debian-gcc-release-custom-ccache)|
|test-r-rhub-ubuntu-gcc-release-latest|[Azure](https://dev.azure.com/ursacomputing/crossbow/_build/latest?definitionId=1&branchName=absl-no-tests-0-azure-test-r-rhub-ubuntu-gcc-release-latest)|
|test-r-rocker-r-base-latest|[Azure](https://dev.azure.com/ursacomputing/crossbow/_build/latest?definitionId=1&branchName=absl-no-tests-0-azure-test-r-rocker-r-base-latest)|
|test-r-rstudio-r-base-4.1-opensuse153|[Azure](https://dev.azure.com/ursacomputing/crossbow/_build/latest?definitionId=1&branchName=absl-no-tests-0-azure-test-r-rstudio-r-base-4.1-opensuse153)|
|test-r-rstudio-r-base-4.2-centos7-devtoolset-8|[Azure](https://dev.azure.com/ursacomputing/crossbow/_build/latest?definitionId=1&branchName=absl-no-tests-0-azure-test-r-rstudio-r-base-4.2-centos7-devtoolset-8)|
|test-r-rstudio-r-base-4.2-focal|[Azure](https://dev.azure.com/ursacomputing/crossbow/_build/latest?definitionId=1&branchName=absl-no-tests-0-azure-test-r-rstudio-r-base-4.2-focal)|
|test-r-ubuntu-22.04|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:absl-no-tests-0-github-test-r-ubuntu-22.04)|
|test-r-versions|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:absl-no-tests-0-github-test-r-versions)|
|test-skyhook-integration|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:absl-no-tests-0-github-test-skyhook-integration)|
|test-ubuntu-18.04-cpp|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:absl-no-tests-0-github-test-ubuntu-18.04-cpp)|
|test-ubuntu-18.04-cpp-release|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:absl-no-tests-0-github-test-ubuntu-18.04-cpp-release)|
|test-ubuntu-18.04-cpp-static|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:absl-no-tests-0-github-test-ubuntu-18.04-cpp-static)|
|test-ubuntu-18.04-r-sanitizer|[Azure](https://dev.azure.com/ursacomputing/crossbow/_build/latest?definitionId=1&branchName=absl-no-tests-0-azure-test-ubuntu-18.04-r-sanitizer)|
|test-ubuntu-20.04-cpp|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:absl-no-tests-0-github-test-ubuntu-20.04-cpp)|
|test-ubuntu-20.04-cpp-17|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:absl-no-tests-0-github-test-ubuntu-20.04-cpp-17)|
|test-ubuntu-20.04-cpp-bundled|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:absl-no-tests-0-github-test-ubuntu-20.04-cpp-bundled)|
|test-ubuntu-20.04-cpp-thread-sanitizer|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:absl-no-tests-0-github-test-ubuntu-20.04-cpp-thread-sanitizer)|
|test-ubuntu-20.04-python-3|[Azure](https://dev.azure.com/ursacomputing/crossbow/_build/latest?definitionId=1&branchName=absl-no-tests-0-azure-test-ubuntu-20.04-python-3)|
|test-ubuntu-22.04-cpp|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:absl-no-tests-0-github-test-ubuntu-22.04-cpp)|
|test-ubuntu-c-glib|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:absl-no-tests-0-github-test-ubuntu-c-glib)|
|test-ubuntu-default-docs|[Azure](https://dev.azure.com/ursacomputing/crossbow/_build/latest?definitionId=1&branchName=absl-no-tests-0-azure-test-ubuntu-default-docs)|
|test-ubuntu-ruby|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:absl-no-tests-0-github-test-ubuntu-ruby)|
|ubuntu-bionic-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:absl-no-tests-0-github-ubuntu-bionic-amd64)|
|ubuntu-bionic-arm64|[TravisCI](https://app.travis-ci.com/github/ursacomputing/crossbow/branches)|
|ubuntu-focal-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:absl-no-tests-0-github-ubuntu-focal-amd64)|
|ubuntu-focal-arm64|[TravisCI](https://app.travis-ci.com/github/ursacomputing/crossbow/branches)|
|ubuntu-jammy-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:absl-no-tests-0-github-ubuntu-jammy-amd64)|
|ubuntu-jammy-arm64|[TravisCI](https://app.travis-ci.com/github/ursacomputing/crossbow/branches)|
|wheel-macos-big-sur-cp310-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:absl-no-tests-0-github-wheel-macos-big-sur-cp310-arm64)|
|wheel-macos-big-sur-cp310-universal2|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:absl-no-tests-0-github-wheel-macos-big-sur-cp310-universal2)|
|wheel-macos-big-sur-cp38-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:absl-no-tests-0-github-wheel-macos-big-sur-cp38-arm64)|
|wheel-macos-big-sur-cp39-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:absl-no-tests-0-github-wheel-macos-big-sur-cp39-arm64)|
|wheel-macos-big-sur-cp39-universal2|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:absl-no-tests-0-github-wheel-macos-big-sur-cp39-universal2)|
|wheel-macos-mojave-cp310-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:absl-no-tests-0-github-wheel-macos-mojave-cp310-amd64)|
|wheel-macos-mojave-cp37-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:absl-no-tests-0-github-wheel-macos-mojave-cp37-amd64)|
|wheel-macos-mojave-cp38-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:absl-no-tests-0-github-wheel-macos-mojave-cp38-amd64)|
|wheel-macos-mojave-cp39-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:absl-no-tests-0-github-wheel-macos-mojave-cp39-amd64)|
|wheel-manylinux2014-cp310-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:absl-no-tests-0-github-wheel-manylinux2014-cp310-amd64)|
|wheel-manylinux2014-cp310-arm64|[TravisCI](https://app.travis-ci.com/github/ursacomputing/crossbow/branches)|
|wheel-manylinux2014-cp37-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:absl-no-tests-0-github-wheel-manylinux2014-cp37-amd64)|
|wheel-manylinux2014-cp37-arm64|[TravisCI](https://app.travis-ci.com/github/ursacomputing/crossbow/branches)|
|wheel-manylinux2014-cp38-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:absl-no-tests-0-github-wheel-manylinux2014-cp38-amd64)|
|wheel-manylinux2014-cp38-arm64|[TravisCI](https://app.travis-ci.com/github/ursacomputing/crossbow/branches)|
|wheel-manylinux2014-cp39-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:absl-no-tests-0-github-wheel-manylinux2014-cp39-amd64)|
|wheel-manylinux2014-cp39-arm64|[TravisCI](https://app.travis-ci.com/github/ursacomputing/crossbow/branches)|
|wheel-windows-cp310-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:absl-no-tests-0-github-wheel-windows-cp310-amd64)|
|wheel-windows-cp37-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:absl-no-tests-0-github-wheel-windows-cp37-amd64)|
|wheel-windows-cp38-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:absl-no-tests-0-github-wheel-windows-cp38-amd64)|
|wheel-windows-cp39-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:absl-no-tests-0-github-wheel-windows-cp39-amd64)|

**Comment by kou** [comment]
How about adding `-DBUILD_TESTING=OFF` to common CMake arguments instead?

```diff
index e9e71328af..7bad61ae1e 100644
--- a/cpp/cmake_modules/ThirdpartyToolchain.cmake
+++ b/cpp/cmake_modules/ThirdpartyToolchain.cmake
@@ -771,6 +771,7 @@ endif()
 set(EP_COMMON_CMAKE_ARGS
     ${EP_COMMON_TOOLCHAIN}
     ${EP_COMMON_CMAKE_ARGS}
+    -DBUILD_TESTING=OFF
     -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
     -DCMAKE_C_FLAGS=${EP_C_FLAGS}
     -DCMAKE_C_FLAGS_${UPPERCASE_BUILD_TYPE}=${EP_C_FLAGS}
@@ -2687,8 +2688,8 @@ macro(build_absl)
   set(absl_VERSION ${ARROW_ABSL_BUILD_VERSION})
   set(ABSL_PREFIX "${CMAKE_CURRENT_BINARY_DIR}/absl_ep-install")
   set(ABSL_INCLUDE_DIR "${ABSL_PREFIX}/include")
-  set(ABSL_CMAKE_ARGS "${EP_COMMON_CMAKE_ARGS}" -DABSL_RUN_TESTS=OFF
-                      -DCMAKE_INSTALL_LIBDIR=lib "-DCMAKE_INSTALL_PREFIX=${ABSL_PREFIX}")
+  set(ABSL_CMAKE_ARGS "${EP_COMMON_CMAKE_ARGS}" -DCMAKE_INSTALL_LIBDIR=lib
+                      "-DCMAKE_INSTALL_PREFIX=${ABSL_PREFIX}")
   set(ABSL_BUILD_BYPRODUCTS)
   set(ABSL_LIBRARIES)
 
```

`BUILD_TESTING` is a common CMake option that is used by CTest. `include(CTest)` provides `BUILD_TESTING`: https://cmake.org/cmake/help/latest/module/CTest.html

FYI: Our bundled Abseil disables its test by default: https://github.com/abseil/abseil-cpp/blob/20211102.0/CMakeLists.txt#L49-L51
So build time will not be changed.

**Comment by nealrichardson** [comment]
> How about adding `-DBUILD_TESTING=OFF` to common CMake arguments instead?

Sounds good. If we do this, we should also delete the other `-DBUILD_TESTING=OFF` scattered about--there are 6 others in the thirdparty toolchain, and looks like `BUILD_TESTING` shows up in a few other places too.

**Comment by pitrou** [comment]
Hi @nealrichardson , do you want to update this PR?

**Comment by nealrichardson** [comment]
> Hi @nealrichardson , do you want to update this PR?

Sure, at some point I can get back around to this, though feel free to grab it if you want. It's not all that significant and doesn't affect build times or content, IIUC.

**Comment by amol-** [comment]
Closing because it has been untouched for a while, in case it's still relevant feel free to reopen and move it forward 👍

**Pull request closed without merging**
