### PR TITLE
ARROW-9437: [Python][Packaging] Homebrew fails to install build dependencies in the macOS wheel builds

### PR DESCRIPTION
**Pull request by kszucs**

### CODE REVIEW

**Comment by kszucs** [comment]
@github-actions crossbow submit wheel-osx-*

**Comment by kszucs** [comment]
This heavily increases the build time (by ~1000s), I'm trying to find an alternative solution.

**Comment by kszucs** [comment]
@github-actions crossbow submit wheel-osx-cp37m

**Comment by kszucs** [comment]
@github-actions crossbow submit wheel-osx-cp37m

**Comment by kszucs** [comment]
@github-actions crossbow submit wheel-osx-*

**Comment by wesm** [comment]
Yikes, 10 minutes to reinstall mercurial!

**Comment by kszucs** [comment]
> Yikes, 10 minutes to reinstall mercurial!

Yeah, but at least it resolves the build failures for now.

**Review by kszucs — COMMENTED** [review]
+1, the build failure is unrelated.

**Pull request closed without merging**
