### PR TITLE
GH-43672: [C#] Schema should be optional on FlightInfo

### PR DESCRIPTION
**Pull request by ndglover**
### Rationale for this change

Schema is not required on a FlightInfo message and sometimes needs to be lazily evaluated on the server. This PR allows schema to be null on the FlightInfo since it will be picked up later when requests with those tickets are made.

### Are these changes tested?
Yes, added a test to confirm this behaviour

### Are there any user-facing changes?

* GitHub Issue: #43672

### CODE REVIEW

**Comment by ndglover** [comment]
@CurtHagenlocher - any chance you could give this a quick review please?

**Comment by ndglover** [comment]
Hi all, sorry to @ so many people but I've had this PR outstanding for review for some time. Would anyone be able to give it a look over and merge if good. I'm keen to get a new release with this added and don't want to fork if possible,
@adamreeve 
@assignUser
@jonkeane 
@kou 
@raulcd

**Review by raulcd — COMMENTED** [review]
The change looks good to me but I don't have enough knowledge around the C# code base to know whether other changes would be required. I've triggered the CI jobs.

**Comment by CurtHagenlocher** [comment]
I'm sorry; I forgot about this PR :(.

**Comment by CurtHagenlocher** [comment]
Test failure looks unrelated

**Review by CurtHagenlocher — APPROVED** [review]

**Comment by ndglover** [comment]
Thanks @CurtHagenlocher @raulcd - much appreciated.

What's the process for making this into a release?

**Comment by raulcd** [comment]
This will be part of the 18.0.0. We do quarterly releases and the 18.0.0 release is schedule for next month.

**Pull request merged**
