### PR TITLE
ARROW-13538: [R] [CI] Don't test DuckDB in the minimal build

### PR DESCRIPTION
**Pull request by jonkeane**
Also request the correct version of duckdb now that it's been released.

### CODE REVIEW

**Comment by jonkeane** [comment]
@github-actions crossbow submit test-r-minimal

**Comment by jonkeane** [comment]
@github-actions crossbow submit test-r-minimal-build

**Comment by jonkeane** [comment]
@github-actions crossbow submit -g r

**Review by nealrichardson — CHANGES_REQUESTED** [review]
Can you rebase and resolve conflicts? I did a similar run_duckdb_examples on a branch I just merged in order to resolve some lint/broken rd messages, so we're conflicting. 

Also, check the new regexp in ci/scripts/r_deps.sh: can you tweak that so that it still drops duckdb now that there's an explicit version listed?

**Comment by jonkeane** [comment]
OK, thanks all done

**Pull request closed without merging**
