### PR TITLE
ARROW-6603: [C#] - Nullable Array Support

### PR DESCRIPTION
**Pull request by abbotware**
These are some static helper methods that use that extend the  existing API in a way to write out lists of null able primitives (ints, doubles, strings, etc) by creating a the correct ValidityBitmaps

I have unit tests, and will add them shortly - just creating the PR to discuss code integration

### CODE REVIEW

**Comment by eerhardt** [comment]
I think it would be better if the existing `Builder` classes had these methods on them. For example, `PrimitiveArrayBuilder` should have a way of appending a `null` to an array.

/cc @chutchinson

**Comment by abbotware** [comment]
@eerhardt - I tried but I don't think its possible as the internals assume <T> is non-nullable  - the best I could do is make extension methods

**Comment by eerhardt** [comment]
> I don't think its possible as the internals assume <T> is non-nullable

Can you elaborate on this? I don't understand what you mean.

`PrimitiveArrayBuilder`'s internals use an `ArrowBuffer.Builder<T> ValueBuffer`, which yes assume that `T` is non-nullable (because all ArrowBuffers are buffers for non-nullable primitive values - int, double, etc.). However, the way Arrow works is that there is ANOTHER buffer called the "the validity (or “null”) bitmap". This would be another "buffer builder" next to the `ValueBuffer` inside `PrimitiveArrayBuilder` and it would keep track of which indices are null and which are valid.

This way, consumers only need to deal with a single "builder" - the `PrimitiveArrayBuilder`. Then they could add `5`, `10`, `null`, `8` to a builder and call `.Build()` and get ArrowArray that contained the correct values and the correct validity bitmap in one shot.

Check out the C++ implementation if you are interested.

C++ base `ArrayBuilder` has a `null_bitmap_builder`:

https://github.com/apache/arrow/blob/249a12f131fa9e53aff035e5e5ad4ee6e38c3d05/cpp/src/arrow/array/builder_base.h#L207

and the derived `NumericBuilder` has the values builder:

https://github.com/apache/arrow/blob/249a12f131fa9e53aff035e5e5ad4ee6e38c3d05/cpp/src/arrow/array/builder_primitive.h#L253

**Comment by wesm** [comment]
What is the status of this?

**Comment by eerhardt** [comment]
@abbotware - have you considered my feedback I've given above?

**Comment by abbotware** [comment]
@eerhardt - when i first looked at the implementation PrimitiveArray / Builder- it looked pretty broken:

`  public IList<T?> ToList(bool includeNulls = false)
`
That method in particular made no sense - you are skipping over null values.  so a list of 10 items would be a list of 8 items if 2 of them were null.  And you would lose ordering since items have been removed.  

the method is already returning T? - so why filter out nulls by default?    The caller should already be expecting null.

looking at it now - it probably just needs an overload of `Append(T?)` and `AppendRange(IEnumerable<T?>) `

**Comment by zgramana** [comment]
@eerhardt I'd like to chime in that I have just come across this conversation after implementing an alternative approach much more in line with other Arrow language implementations.

In particular, I really just finished out the previously stubbed `NullBitmapBuffer` already in the codebase.

The most significant change comes with the following addition to `IArrowArrayBuilder<T, out TArray, out TBuilder>`:

```csharp
public interface IArrowArrayBuilder<T, out TArray, out TBuilder> : IArrowArrayBuilder<TArray, TBuilder>
    where TArray : IArrowArray
    where TBuilder : IArrowArrayBuilder<TArray>
{
    TBuilder Append(T value);
    TBuilder Append(ReadOnlySpan<T> span);
    TBuilder AppendRange(IEnumerable<T> values);
    TBuilder AppendNull(); // <- Works with non-nullable types too
    TBuilder Swap(int i, int j);
    TBuilder Set(int index, T value);
}
```

The work includes adding the supporting work for implementation of `AppendNull` to `PrimitiveArrayBuilder` and `Binary.BuilderBase` and then removing the hardcoded `0`'s passed to `nullCount` in `ArrayData` constructors.

I also added two tests to `ArrayBuilderTests`:
* The first includes a number of `null` scenarios using `TestArrayBuilder<T,U>(...)`.
* The second includes a `StringArray.Builder` scenario with mixed `null` and `string.Empty` scenarios. For the later, I implemented it such that `string.Empty` is considered a valid value (so it increments `Offset` without adding an bytes to `ValueBuffer`. When a null string is passed to  `Append` it will invoke `AppendNull` internally instead.
* All 160 (existing + new) tests pass. :-)

I have requested internal approval to be able to submit a PR and get a CCLA signed. If you can hold off on merging this PR, I would like the opportunity to have my alternate approach considered as well.

**Comment by zgramana** [comment]
@eerhardt I've just submitted https://github.com/apache/arrow/pull/7032 for review/discussion

**Comment by eerhardt** [comment]
Thank you for this contribution, @abbotware.

However, my opinion is that #7032 is more inline with how null support should be designed for the builder APIs. It also more closely models how the other languages do it as well.

I think we should move forward with #7032's design and implementation to resolve ARROW-6603.

**Comment by eerhardt** [comment]
Thanks again for this work, @abbotware.

I'm going to close this PR out in favor of #7032. @abbotware - can you check out the functionality added there?

**Comment by olgacarpenter** [comment]
@eerhardt is there an example anywhere on how to create an arrow file with nullable columns?  Or, can you provide one?

**Comment by eerhardt** [comment]
You can use the `XXXArray.Builder` class and the `AppendNull()` method. See below:

```C#
using Apache.Arrow;

FloatArray.Builder builder = new FloatArray.Builder();
builder.Append(5);
builder.Append(4);
builder.Append(3);
builder.Append(2);
builder.Append(1);
builder.AppendNull();
builder.Append(0);

FloatArray floatArray = builder.Build();
for (int i = 0; i < floatArray.Length; i++)
{
    Console.WriteLine(floatArray.GetValue(i));
}
```

produces:

```
5
4
3
2
1

0
```

**Pull request closed without merging**
