### PR TITLE
GH-33895: [Release] Add a script to add new owner of our RubyGems

### LINKED ISSUE #33895: [Release] Add a script to add new owner of our RubyGems
### Describe the enhancement requested

The following command lines should be scripted:

https://arrow.apache.org/docs/dev/developers/release.html#post-release-tasks

```bash
gem owner red-arrow -a NEW_ACCOUNT
gem owner red-arrow-cuda -a NEW_ACCOUNT
gem owner red-arrow-dataset -a NEW_ACCOUNT
gem owner red-arrow-flight -a NEW_ACCOUNT
gem owner red-arrow-flight-sql -a NEW_ACCOUNT
gem owner red-gandiva -a NEW_ACCOUNT
gem owner red-parquet -a NEW_ACCOUNT
gem owner red-plasma -a NEW_ACCOUNT
```

### Component(s)

Developer Tools

### PR DESCRIPTION
**Pull request by kou**
### What changes are included in this PR?

Scripted existing command lines in our documentation.

### Are these changes tested?

Yes.

### Are there any user-facing changes?

No.
* Closes: #33895

### CODE REVIEW

**Review by assignUser — COMMENTED** [review]
+1

**Comment by assignUser** [comment]
Ah one minor thing how about we name the script `add-ruby-owner.sh` to make it a bit more descriptive?

**Review by raulcd — APPROVED** [review]
Agree with the comment from @assignUser

**Comment by kou** [comment]
I think that the current name is better. So including "owner" in a script name is too descriptive. But it's not a strong opinion. :-)

We may want to add more scripts to automate a new account invitations. I wanted to hide details (e.g.: "owner" for RubyGems) from existing package maintainers. If we add a script for Python, we need to use "collaborator" not "owner". If we add a script for JavaScript, we need to use "maintainer" not "owner".

`account-ruby.sh` shows that this script prepares account related things for Ruby. (`new-account-ruby.sh` may be better.)
`account-python.sh` and `account-js.sh` are for Python and JavaScript.

**Review by assignUser — APPROVED** [review]
Ok that makes sense.

**Pull request merged**
