### PR TITLE
MINOR: [CI] Bump actions/{download,upload}-artifact version

### PR DESCRIPTION
**Pull request by pitrou**
v2 and v3 are deprecated and can fail CI builds, bump to v4.

### CODE REVIEW

**Comment by pitrou** [comment]
@github-actions crossbow submit -g nightly-tests

**Comment by pitrou** [comment]
@github-actions crossbow submit *wheel*cp312*

**Review by assignUser — APPROVED** [review]
An important bump, thanks!

**Comment by pitrou** [comment]
@github-actions crossbow submit test-r-install-local* test-r-versions test-r-linux-as-cran

**Pull request merged**
