### PR TITLE
ARROW-950: [Website] Add Google Analytics tag to site

### PR DESCRIPTION
**Pull request by wesm**
I created this GA property. I will be happy to give access to any PMC who wishes to look at the analytics data. It would be better to be collecting the site visitor data than not.

### CODE REVIEW

**Comment by wesm** [comment]
+1

**Comment by kou** [comment]
I'm interested in this. Please give me access. My Google Analytics account is `koutou@gmail.com`.

**Comment by wesm** [comment]
Done

**Comment by kou** [comment]
Thanks! Confirmed.

**Comment by xhochy** [comment]
@wesm please also add me

**Pull request closed without merging**
