### PR TITLE
ARROW-13580: [C++] quoted_strings_can_be_null only applied to string columns

### PR DESCRIPTION
**Pull request by westonpace**
Allow quoted nulls if quoted_strings_can_be_null is true

### CODE REVIEW

**Comment by pitrou** [comment]
Well, the docstring looks quite clear to me:
```c++
  /// Whether string / binary columns can have quoted null values.
  ///
  /// If true *and* `strings_can_be_null` is true, then quoted strings in
  /// "null_values" are also considered null for string columns.  Otherwise,
  /// quoted strings are never considered null.
```

Perhaps it's beneficial to change the behaviour?

**Comment by kkraus14** [comment]
Agreed that it's beneficial to change the behavior and docstring to allow for treating empty quoted strings as null in the case of numeric columns.

Bigger picture, CSVs are a mess where we should ideally allow controlling options like `null_values`, `true_values`, `false_values`, `quoted_strings_can_be_null` on a per-column level in addition to globally.

**Comment by westonpace** [comment]
Ah, if this is a behavior change then I can update that docstring as well.  I'll add, in support of my argument, that we parsed quoted non-nulls as integers.  For example:

```
>>> pyarrow.csv.read_csv(io.BytesIO(b'A\n"1"\n"2"\n'))
pyarrow.Table
A: int64
```

**Review by pitrou — APPROVED** [review]
+1, will merge

**Comment by pitrou** [comment]
AppVeyor build on my fork: https://ci.appveyor.com/project/pitrou/arrow/builds/40577420

**Pull request closed without merging**
