### PR TITLE
ARROW-341: [Python] Move pyarrow's C++ code to the main C++ source tree, install libarrow_python and headers

### PR DESCRIPTION
**Pull request by wesm**
This will enable third parties to link to `libarrow_python`.

For now, the pyarrow build system continues to use CMake -- for the purpose of resolving the thirdparty toolchain we may or may not want to go completely to distutils, but we can sort that out later.

### CODE REVIEW

**Comment by wesm** [comment]
One downside to this change is that the C++ libraries are now dependent on the Python interpreter version (see corresponding changes for Travis CI), similar to Boost.Python. I think the benefits outweigh the downsides, though.

**Comment by xhochy** [comment]
@wesm This definitely breaks the `manylinux1` packages. Once this branch has a stable state, I would like to PR into this branch to get them working again. I'm a bit reluctant to add this to Travis as it would extend our build times even further.

**Comment by wesm** [comment]
This branch is stable -- I think you can go ahead with the fixes. I made best efforts to treat arrow_python like you are treating the rest of the library stack

**Comment by wesm** [comment]
Rebased

**Comment by wesm** [comment]
@xhochy the manylinux1 build is broken because of the multiarch changes https://github.com/apache/arrow/commit/f5157a0af7046a618f159a5d0693a664f45658d7

```
-- Found the Arrow core library: /arrow-dist/lib64/libarrow.so
-- Found the Arrow IO library: /arrow-dist/lib64/libarrow_io.so
<SNIP>
make[2]: *** No rule to make target `/arrow-dist/lib/libarrow.so', needed by `build/release/libparquet.so'.  Stop.
```

This will have to get fixed in FindArrow.cmake in Parquet.

**Comment by wesm** [comment]
Suggest we merge this as is and fix up the build toolchain for manylinux1 in subsequent patches (I am happy to help, installed docker and just tried running the docker build)

**Comment by xhochy** [comment]
Ok, then let's continue first on the `parquet-cpp` side.

**Review by xhochy — APPROVED** [review]
+1, LGTM

**Comment by wesm** [comment]
Cool, merging, thank you

**Pull request closed without merging**
