### PR TITLE
ARROW-13124: [Ruby] Add support for memory view

### PR DESCRIPTION
**Pull request by kou**

### CODE REVIEW

**Review by mrkn — COMMENTED** [review]
Is it OK that this change assumes array items are always little-endian?

**Comment by kou** [comment]
I think that it's OK for now. There is no big-endian user for now.
Endianness information exists in schema not array. So we can't determine endianness only with array.

Should we assume native endianness instead of little-endian?

**Review by mrkn — APPROVED** [review]
The implementation seems good to me.

**Comment by mrkn** [comment]
> Should we assume native endianness instead of little-endian?

I think yes if the contents of ArrayData objects have big-endian data on a big-endian platform.

**Comment by kou** [comment]
OK. I'll remove `<` from formats and merge this.

**Comment by mrkn** [comment]
@kou Please don't forget to replace `e` and `E` with `f` and `d`, respectively.

**Comment by kou** [comment]
OK. I'll also update `b` and `B'.

**Comment by kou** [comment]
+1

**Pull request closed without merging**
