### PR TITLE
ARROW-6901: [Rust] [Parquet] Increment total_num_rows when closing a row group

### PR DESCRIPTION
**Pull request by bw-matthew**
This means that the total_num_rows written to the file will accurately reflect the row groups that were successfully written.

### CODE REVIEW

**Comment by bw-matthew** [comment]
It's failed linting, going to make those changes.

**Review by paddyhoran — COMMENTED** [review]
Looks reasonable to me, but I will let @sunchao or @sadikovi comment.  Shouldn't `total_num_rows` be `u64` instead of `i64`?

**Comment by bw-matthew** [comment]
I changed it to i64 because the RowGroupMetaData has i64 for the num_rows field (and the ColumnChunkMetaData has i64 for the num_values). All of these values cannot reasonably be negative so I understand what you are saying.

If you think it would be better to change them then I can do that, however I'm cautious about that approach because when I tried it it started interacting with things like the thrift conversion.

**Review by sadikovi — APPROVED** [review]
Looks good. Thanks for fixing it. 
Did you test that manually?

I had my private branch with the fixes, but I forgot to merge it somehow into upstream back then.

**Review by paddyhoran — APPROVED** [review]

**Comment by bw-matthew** [comment]
This PR updates the round trip tests to check that the correct value is present when reading the file metadata from the written file. Thanks for merging this.

**Comment by bw-matthew** [comment]
Just tested my branch again, it writes the correct row count now.

**Pull request closed without merging**
