### PR TITLE
ARROW-5523: [Python] [Packaging] Use HTTPS consistently for downloading wheel dependencies

### PR DESCRIPTION
**Pull request by nealrichardson**

### CODE REVIEW

**Comment by nealrichardson** [comment]
Will the crossbow wheel jobs rebuild the images (and test these) or not?

FWIW I went to all of the newly `https` URLs in the browser and they all resolve.

**Comment by nealrichardson** [comment]
@ursabot crossbow submit -g wheel

**Comment by nealrichardson** [comment]
manylinux1 fails like this:

```
[171/235] Building CXX object src/arrow/dataset/CMakeFiles/arrow_dataset_objlib.dir/scanner.cc.o
FAILED: src/arrow/dataset/CMakeFiles/arrow_dataset_objlib.dir/scanner.cc.o 
/usr/bin/ccache /opt/rh/devtoolset-2/root/usr/bin/c++  -DARROW_DS_EXPORTING -DARROW_JEMALLOC -DARROW_JEMALLOC_INCLUDE_DIR="" -DARROW_USE_SIMD -DARROW_WITH_BOOST_FILESYSTEM -DARROW_WITH_BROTLI -DARROW_WITH_BZ2 -DARROW_WITH_LZ4 -DARROW_WITH_SNAPPY -DARROW_WITH_ZLIB -DARROW_WITH_ZSTD -DURI_STATIC_BUILD -Isrc -I/arrow/cpp/src -I/arrow/cpp/src/generated -I/arrow/cpp/src/parquet -isystem /arrow/cpp/thirdparty/flatbuffers/include -isystem /arrow_boost_dist/include -isystem jemalloc_ep-prefix/src -isystem /usr/local/include -isystem /arrow/cpp/thirdparty/hadoop/include -O3 -DNDEBUG  -Wall -Wno-attributes -msse4.2  -O3 -DNDEBUG -fPIC   -std=gnu++11 -MD -MT src/arrow/dataset/CMakeFiles/arrow_dataset_objlib.dir/scanner.cc.o -MF src/arrow/dataset/CMakeFiles/arrow_dataset_objlib.dir/scanner.cc.o.d -o src/arrow/dataset/CMakeFiles/arrow_dataset_objlib.dir/scanner.cc.o -c /arrow/cpp/src/arrow/dataset/scanner.cc
In file included from /arrow/cpp/src/arrow/dataset/dataset_internal.h:30:0,
                 from /arrow/cpp/src/arrow/dataset/scanner.cc:25:
/arrow/cpp/src/arrow/util/iterator.h: In instantiation of ‘arrow::Iterator<T>::RangeIterator arrow::Iterator<T>::end() [with T = std::shared_ptr<arrow::RecordBatch>]’:
/arrow/cpp/src/arrow/dataset/scanner.cc:173:29:   required from here
/arrow/cpp/src/arrow/util/iterator.h:113:5: error: conversion from ‘std::shared_ptr<arrow::RecordBatch>’ to non-scalar type ‘arrow::Result<std::shared_ptr<arrow::RecordBatch> >’ requested
     RangeIterator() = default;
     ^
/arrow/cpp/src/arrow/util/iterator.h:147:46: note: synthesized method ‘arrow::Iterator<T>::RangeIterator::RangeIterator() [with T = std::shared_ptr<arrow::RecordBatch>]’ first required here 
   RangeIterator end() { return RangeIterator(); }
                                              ^
/arrow/cpp/src/arrow/util/iterator.h: In instantiation of ‘arrow::Iterator<T>::RangeIterator arrow::Iterator<T>::end() [with T = std::shared_ptr<arrow::dataset::ScanTask>]’:
/arrow/cpp/src/arrow/dataset/scanner.cc:190:31:   required from here
/arrow/cpp/src/arrow/util/iterator.h:113:5: error: conversion from ‘std::shared_ptr<arrow::dataset::ScanTask>’ to non-scalar type ‘arrow::Result<std::shared_ptr<arrow::dataset::ScanTask> >’ requested
     RangeIterator() = default;
     ^
/arrow/cpp/src/arrow/util/iterator.h:147:46: note: synthesized method ‘arrow::Iterator<T>::RangeIterator::RangeIterator() [with T = std::shared_ptr<arrow::dataset::ScanTask>]’ first required here 
   RangeIterator end() { return RangeIterator(); }
                                              ^
```

Maybe that's due to https://github.com/apache/arrow/commit/3d3ecfb157d4fbaaa09c92481f55a5c4db726c1f? Wheels were not tested on https://github.com/apache/arrow/pull/5976. Guess we'll see if master fails the same.

**Comment by nealrichardson** [comment]
Made https://issues.apache.org/jira/browse/ARROW-7381 for the manylinux1 issue

**Comment by kszucs** [comment]
@ursabot crossbow submit -g wheel

**Review by kszucs — APPROVED** [review]
Thanks @nealrichardson !

**Pull request closed without merging**
