### PR TITLE
ARROW-5755: [Rust] [Parquet] Derive clone for Type.

### PR DESCRIPTION
**Pull request by liurenjie1024**
Derive clone for type.

### CODE REVIEW

**Comment by liurenjie1024** [comment]
@sunchao @sadikovi @paddyhoran  Please help to review.

**Review by sunchao — APPROVED** [review]
LGTM on pending CI.

**Comment by sunchao** [comment]
The coverage drop is because it was broken for a long period of time. Interestingly that it does work now - I thought the fix will not work in #4700. cc @fsaintjacques .

**Comment by fsaintjacques** [comment]
@sunchao seems like it didn't segfault: https://travis-ci.org/apache/arrow/jobs/551302470#L1943

**Comment by sunchao** [comment]
@fsaintjacques yup - not sure what happened in the first run, but good so far :) (although the tests need to be fixed)

**Review by sadikovi — COMMENTED** [review]
LGTM

**Pull request closed without merging**
