### PR TITLE
ARROW-17687: [C++] Fix race condition in AsyncTaskScheduler (using semaphore)

### PR DESCRIPTION
**Pull request by aucahuasi**
Every time we use a shared `AsyncTaskScheduler::Throttle` between the parent `AsyncTaskScheduler` and the sub `AsyncTaskSchedulers`, we get a race condition: it seems the issue is at the moment we try to mark the final future as finished.
So far, this is the description of the issue: 
1. `DoSubmitTask` adds a callback and internally that callback marks the `finished_` future as done (see [here](https://github.com/apache/arrow/blob/ec579df631deaa8f6186208ed2a4ebec00581dfa/cpp/src/arrow/util/async_util.cc#L309))
2. After that point, the [scheduler's mutex](https://github.com/apache/arrow/blob/ec579df631deaa8f6186208ed2a4ebec00581dfa/cpp/src/arrow/util/async_util.cc#L351) gets invalidated and [the next time we want to lock](https://github.com/apache/arrow/blob/ec579df631deaa8f6186208ed2a4ebec00581dfa/cpp/src/arrow/util/async_util.cc#L262) we get this error:
`libc++abi: terminating with uncaught exception of type std::__1::system_error: mutex lock failed: Invalid argument`

One assumption is that [the destructor is being called in another thread](https://github.com/apache/arrow/blob/ec579df631deaa8f6186208ed2a4ebec00581dfa/cpp/src/arrow/util/async_util.cc#L204) and there we are deleting the scheduler instance and its attributes (including the mutex); so this invalidates the mutex at the end.

This PR is an attempt to solve the issue by using `arrow::util::CountingSemaphore`, the idea is to wait in the destructor and release the permit after we finish to mark the future.

There is [another PR with a similar idea](https://github.com/apache/arrow/pull/14298), but using a `std::shared_mutex` instead; after we can track the issue, we can discard any of the PRs and merge the one that makes sense (either the `std::shared_mutex` or the semaphore|cond_var PR).

### CODE REVIEW

**Comment by aucahuasi** [comment]
With these changes there is a deadlock (I guess is because we are marking the future as done and that triggers the destructor that is waiting for the release):
```cpp
debug/arrow-utility-test --gtest_filter=AsyncTaskScheduler.ScanningStress --verbose --gtest_repeat=10
arrow-utility-test(42416,0x106d04580) malloc: nano zone abandoned due to inability to preallocate reserved vm space.

Repeating all tests (iteration 1) . . .

Note: Google Test filter = AsyncTaskScheduler.ScanningStress
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from AsyncTaskScheduler
[ RUN      ] AsyncTaskScheduler.ScanningStress

```

**Comment by pitrou** [comment]
This seems to solve a complicated issue by adding another piece of complication, so I'm -1 on this approach.

**Comment by aucahuasi** [comment]
Thanks, yes it seems I'll be closing this PR soon, btw here is another related PR using a different approach:
https://github.com/apache/arrow/pull/14314

**Comment by aucahuasi** [comment]
Closing in favor of https://github.com/apache/arrow/pull/14314

**Pull request closed without merging**
