### PR TITLE
ARROW-11396: [JAVA] Update the private access permission from private to protected

### PR DESCRIPTION
**Pull request by JkSelf**
When using Arrow as the 3rd library, it is hard to add the custom function due to the private access permission. 
This PR update the private access permission from private to protected. Then we can easily expand new functions in the subclass.

### CODE REVIEW

**Comment by emkornfield** [comment]
I think there is likely a better design than this.  Could you articulate the concrete use-case (it looks like it has something to do with compression)?  At the very least, if we make these protected then we need to add javadoc on the contract that is intended.

**Comment by JkSelf** [comment]
@emkornfield Thanks for you reviewing.
We compressed the body buffers in native by calling c++ buffer comoression API and then read the RecordBatch with the compressed buffers using Java's IPC API based on the 0.17 version. And we block [this issue](https://issues.apache.org/jira/browse/ARROW-8803). So we resolved with this patch. It seems the compress and decompress framework already done in [ARROW-9010](https://issues.apache.org/jira/browse/ARROW-9010). So this PR may be not needed.

**Comment by emkornfield** [comment]
OK, but I'm still not sure this is the correct approach? It seems if you want to plugin in a custom codec then there should be a change to VectorLoader to take a decompressor factory (VectorUnloader can already specify a code for compression)?  Or do all decompression with native code and then share the record batch memory back with Java?

**Comment by JkSelf** [comment]
Yes, this approach may be not perfect. Arrow 3.0 can decompress the compressed buffer firstly and then load the decompressed buffer into the FieldVector, which can resolve the [issue](https://issues.apache.org/jira/browse/ARROW-8803). And I will close this PR. 
Thanks for your discussion again.

**Pull request closed without merging**
