### PR TITLE
MINOR: [Rust] [CI] Tag Ballista PRs

### PR DESCRIPTION
**Pull request by andygrove**
I did not create a JIRA for this one.

### CODE REVIEW

**Comment by andygrove** [comment]
@jorgecarleitao @alamb Is this all that is required?

**Review by jorgecarleitao — APPROVED** [review]
Yes, it is :) LGTM

**Comment by andygrove** [comment]
How do we merge PRs that have no JIRA? The `merge_arrow_pr` script fails.

**Comment by kou** [comment]
We can use the "Squash and merge" button in PR.

**Comment by emkornfield** [comment]
@andygrove were you synced to the latest version, i tried to update the merge tool to also work with minor PRs.

**Comment by alamb** [comment]
Nice

**Pull request merged**
