### PR TITLE
ARROW-1204: [C++] Remove WholeProgramOptimization(/GL) compilation fl…

### PR DESCRIPTION
**Pull request by maxhora**
…ag for lz4 and zstd libs

### CODE REVIEW

**Review by xhochy — COMMENTED** [review]
I'm a bit confused that we patch here using `git` although we have a non-git source tarball. Why cannot we use the `patch` command. Is there no equivalent on Windows/AppVeyor?

**Comment by wesm** [comment]
Right, there's no patch equivalent on Windows AFAIK

**Comment by wesm** [comment]
We should probably report these issues upstream?

**Comment by MaxRis** [comment]
@xhochy @wesm `patch` tool is available on Appveyor, but on clean Windows installation it's not. Usage of `patch` for Windows will create additional dependency to install.
But `conda`, for example, has `patch` tool for Windows.

**Comment by xhochy** [comment]
@MaxRis good to know. Then we can keep it this way as long as users don't complain for the git dependency ;)

**Review by wesm — APPROVED** [review]
+1, thanks @MaxRis!

**Pull request closed without merging**
