### PR TITLE
GH-39291: [Docs] Remove the "Show source" links from doc pages

### LINKED ISSUE #39291: [Docs] Show source links to 404 page
### Describe the bug, including details regarding any error messages, version, and platform.

In the Arrow documentation one could use the "Show source" link to check the source of the documentation or even more important the source code in the API docs. This doesn't work currently as it links to a 404 No found page.

https://arrow.apache.org/docs/dev/cpp/api/datatype.html --> https://arrow.apache.org/docs/dev/_sources/cpp/api/datatype.rst.txt

### Component(s)

Documentation

### PR DESCRIPTION
**Pull request by Divyansh200102**
### Rationale for this change
To fix the show source button links to 404 page problem

### What changes are included in this PR?
The show source button link will be removed.

### Are these changes tested?
Not yet

### Are there any user-facing changes?
Yes

* Closes: #39291
* GitHub Issue: #39291

### CODE REVIEW

**Comment by kou** [comment]
@github-actions crossbow submit preview-docs

**Comment by kou** [comment]
http://crossbow.voltrondata.com/pr_docs/40167

**Comment by kou** [comment]
The "Show Source" doesn't exist:

* Current: https://arrow.apache.org/docs/developers/index.html
* Changed: http://crossbow.voltrondata.com/pr_docs/40167/developers/index.html

@AlenkaF @jorisvandenbossche Can we merge this?

**Review by jorisvandenbossche — APPROVED** [review]
Thanks!

**Pull request merged**
