### PR TITLE
ARROW-15414: [Java] Fix RangeEqualsVisitor for BitVector

### PR DESCRIPTION
**Pull request by wzx140**

### CODE REVIEW

**Comment by wzx140** [comment]
Please see: https://issues.apache.org/jira/browse/ARROW-15414

**Comment by wzx140** [comment]
@liyafan82 Could you please review it? Really thanks! This problem is very similar to ARROW-13981

**Review by liyafan82 — APPROVED** [review]
LGTM.

**Review by lidavidm — APPROVED** [review]
Thanks!

**Pull request closed without merging**
