### PR TITLE
ARROW-8291: [Packaging] Conda nightly builds can't locate Numpy

### PR DESCRIPTION
**Pull request by kszucs**

### CODE REVIEW

**Comment by kszucs** [comment]
@github-actions crossbow submit -g conda

**Comment by pitrou** [comment]
So this means cmake 3.17 doesn't work inside conda-build?

**Comment by pitrou** [comment]
Reported upstream at https://gitlab.kitware.com/cmake/cmake/-/issues/20525

**Comment by kszucs** [comment]
I managed to locally reproduce the issue and pinning cmake has resolved it. Also tried to build arrow-cpp-feedstock on my fork and that was working without the pin - perhaps it fails with pyarrow (have not checked the log yet).

**Comment by pitrou** [comment]
@xhochy Thoughts?

**Comment by wesm** [comment]
Should we merge this?

**Pull request closed without merging**
