### PR TITLE
ARROW-16043: [C++][Filesystem][S3] Add missing empty content for creating directory

### PR DESCRIPTION
**Pull request by kou**
We can't omit body to create a directory.

### CODE REVIEW

**Comment by kou** [comment]
@github-actions crossbow submit homebrew-r-brew

**Review by lidavidm — APPROVED** [review]
Thanks, kou! The linked AWS SDK commit doesn't really give much context on why this changed, unfortunately…the [docs](https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutObject.html) do say this should be optional, so I wonder why this became required in the SDK.

**Comment by kou** [comment]
Sorry. I describe this problem.

Recent AWS SDK for C++ adds checksum automatically by  
https://github.com/aws/aws-sdk-cpp/commit/01e61b3137f90509e71765ee7e3b4a39e2e8de91 . The checksum is calculated by request body. If request body is `nullptr`, this problem is occurred.

Each request type knows whether checksum is needed or not. We use `PutObjectRequest` for creating a directory. And it requires `md5` checksum by default by https://github.com/aws/aws-sdk-cpp/commit/24b3cc68451c80a96fbbe133921273b07151d453 .

> the [docs](https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutObject.html) do say this should be optional, so I wonder why this became required in the SDK.

Could you quote the sentence for it? I couldn't find it in the docs...

We may report this as a bug to ASW SDK for C++.

**Comment by lidavidm** [comment]
I may have misunderstood. I was looking at this (emphasis added):

> The base64-encoded 128-bit MD5 digest of the message (without the headers) according to RFC 1864. This header can be used as a message integrity check to verify that the data is the same data that was originally sent. **Although it is optional**, we recommend using the Content-MD5 mechanism as an end-to-end integrity check. For more information about REST request authentication, see [REST Authentication](https://docs.aws.amazon.com/AmazonS3/latest/dev/RESTAuthentication.html).

**Comment by kou** [comment]
Thanks!

It seems that the docs says checksum is optional but doesn't say anything whether body is optional or not.

**Comment by lidavidm** [comment]
Ah, ok, right. Thanks for the explanation.

**Review by jonkeane — APPROVED** [review]
This is fantastic, thanks for the quick response!

**Comment by kou** [comment]
I'll merge this for green CI.

**Pull request closed without merging**
