### PR TITLE
MINOR: [R] Remove duplicated heading

### PR DESCRIPTION
**Pull request by thisisnic**
Remove duplicated heading introduced in #13748

### CODE REVIEW

**Comment by eitsupi** [comment]
As I commented on https://github.com/apache/arrow/pull/13748#discussion_r941275309, this is an intentional duplication to generate Rd files by using roxygen2.

**Review by assignUser — APPROVED** [review]
Even if intentional I think 1:1 duplicating the title for the body is unnecessary imo and would frustrate me as a user(for having to read the same thing twice), likely the reason I missed it the first time around 🙈 It also does not match the overall doc style of the package afaik. e.g.:
```
#' Read a Parquet file
#'
#' '[Parquet](https://parquet.apache.org/)' is a columnar storage file format.
```

**Comment by kou** [comment]
Please use your fork to create a feature branch. Please don't use apache/arrow for it.

**Comment by thisisnic** [comment]
> Please use your fork to create a feature branch. Please don't use apache/arrow for it.

Apologies, didn't realise I'd done that.

**Pull request closed without merging**
