### PR TITLE
GH-34789: [CI][Python] Update the Python versions in our nightly CI matrix

### LINKED ISSUE #34789: [CI][Python] Update the Python versions in our nightly CI matrix
Generally, we tend to test with quite old python versions. For the core tests like the `test-conda-python-xx` builds, we test on the full range of supported python versions (3.7-3.11). But for some other custom integrations tests, we test mostly with old versions:

https://github.com/apache/arrow/blob/ddd0a337174e57cdc80b1ee30dc7e787acfc09f6/dev/tasks/tasks.yml#L1506-L1513

Pandas doesn't actually support python 3.7 anymore, so because we use that version for the "latest" build, we don't actually get latest pandas.

Also for example the HDFS tests are using python 3.7

### PR DESCRIPTION
**Pull request by jorisvandenbossche**
* Closes: #34789

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
@github-actions crossbow submit test-conda-python-3.11-hypothesis test-conda-python-3.10-substrait

**Review by raulcd — COMMENTED** [review]
Thanks @jorisvandenbossche! Any reason why for some of the jobs we have bumped to Python 3.10 and for others to Python 3.11?

**Comment by jorisvandenbossche** [comment]
Just to have a bit variation in the versions, I didn't think too much about it. If something seems odd, feel free to comment on it!

**Comment by raulcd** [comment]
Looks good to me, just wondering whether there was any reason behind it! Thanks!

**Comment by jorisvandenbossche** [comment]
@github-actions crossbow submit  test-conda-python-3.10-hdfs-2.9.2 test-conda-python-3.10-hdfs-3.2.1

**Comment by jorisvandenbossche** [comment]
The HDFS ones are failing on main with the same error (which seems an actual test failure to fix), so merging

**Pull request merged**
