### PR TITLE
ARROW-14224: [C++] Try to reduce build time/memory usage

### PR DESCRIPTION
**Pull request by lidavidm**
Fixes an issue with OOM in some CI builds. Also, reduces the build time of one particular object file which was taking ~8 minutes in release builds with AddressSanitizer/UBSan enabled. 

The file in question was templating the base dictionary builder once for each index and value type. Instead, use a type-erased index builder type so that we need only template twice per value type (one with AdaptiveIntBuilder, one with the type-erased builder).

### CODE REVIEW

**Comment by lidavidm** [comment]
@github-actions crossbow submit test-ubuntu-18.04-r-sanitizer

**Comment by pitrou** [comment]
@ursabot please benchmark lang=c++

**Comment by pitrou** [comment]
@ursabot please benchmark lang=C++

**Review by pitrou — APPROVED** [review]
Thanks a lot for doing this. I noticed builder_dict.cc taking a lot of time to compile, but was clueless where it came from.

We should ensure there's no important benchmark regression before merging this.

**Pull request closed without merging**
