### PR TITLE
ARROW-1553: [JAVA] Implement setInitialCapacity for MapWriter 

### PR DESCRIPTION
**Pull request by siddharthteotia**
Implement setInitialCapacity for MapWriter and pass on this capacity during lazy creation of child vectors

cc @jacques-n , @StevenMPhillips

### CODE REVIEW

**Comment by icexelloss** [comment]
LGTM. Maybe we want a test for MapWriter?

**Comment by jacques-n** [comment]
LGTM. Definitely helps our use case. Agree with @icexelloss that we should add a test as well for this situation.

**Comment by siddharthteotia** [comment]
Added unit test

**Comment by siddharthteotia** [comment]
Can this be merged?

**Review by wesm — APPROVED** [review]
+1

**Pull request closed without merging**
