### PR TITLE
ARROW-12909: [R][Release] Build of ubuntu-docs is failing

### PR DESCRIPTION
**Pull request by thisisnic**
This PR ensures that the same version of r-base and r-recommended is installed to prevent errors when they end up with different versions.

### CODE REVIEW

**Comment by thisisnic** [comment]
Reading the dev mailing list, I think this is already solved; closing

**Comment by jorgecarleitao** [comment]
Thanks a lot, @thisisnic ; this solves it 👍

**Comment by thisisnic** [comment]
@github-actions crossbow submit test-ubuntu-20.10-docs

**Comment by thisisnic** [comment]
@github-actions crossbow submit test-ubuntu-20.10-docs

**Pull request closed without merging**
