### PR TITLE
ARROW-5199:[Java] Add unsafe access methods to ArrowBuf

### PR DESCRIPTION
**Pull request by yuruiz**
Add unsafe access method to ArrowBuf to allow external user to access underlying memory chunk without extra boundary check overhead

### CODE REVIEW

**Comment by jacques-n** [comment]
I'd like to propose that we get ARROW-3191 merged first and then change how to do this. I think it probably makes sense to simply implement an UncheckedBuf<R> which can simply be a set of accessors along with a memory address that interacts with the underlying memory via unchecked methods. The generic <R> can hold a reference object (which may be ArrowBuf) but could be anything else, too. Since the address is exposed in ArrowBuf, you can grab that to create an UncheckedBuf. There is no need for these methods to be directly attached to the ArrowBuf class.

**Comment by yuruiz** [comment]
> I'd like to propose that we get ARROW-3191 merged first and then change how to do this. I think it probably makes sense to simply implement an UncheckedBuf which can simply be a set of accessors along with a memory address that interacts with the underlying memory via unchecked methods. The generic can hold a reference object (which may be ArrowBuf) but could be anything else, too. Since the address is exposed in ArrowBuf, you can grab that to create an UncheckedBuf. There is no need for these methods to be directly attached to the ArrowBuf class.

Sure, it makes sense to merge ARROW-3191 first. I would prefer having explicit unsafe method so that the external caller would be aware that such a method have no boundary check. If we simply providing an UncheckedBuf implementation if could be quite confusing about the semantics of each accessor.

**Comment by jacques-n** [comment]
The UncheckedBuf can have the methods be called getUnsafe(). UncheckedBuf is not a subclass of ArrowBuf, it is simply something that holds a reference to ArrowBuf.

**Comment by emkornfield** [comment]
@yuruiz can you clarify the use case for this?  Does using the BoundsChecking configuration not work for you?

**Comment by yuruiz** [comment]
> @yuruiz can you clarify the use case for this? Does using the BoundsChecking configuration not work for you?

HI @emkornfield , by boundsChecking flag are you referring the flag introduced by this [PR](https://github.com/apache/arrow/pull/4288) ?  I can update it if that is the preferred way.

**Comment by emkornfield** [comment]
That flag is for verifying a value is set when retrieving.  I was referring to [this](https://github.com/apache/arrow/blob/ccdaa9f2a4c1af1222df840b608e2ef465d331fc/java/memory/src/main/java/org/apache/arrow/memory/BoundsChecking.java) which is the same thing for checking bounds on addresses.

**Comment by yuruiz** [comment]
> That flag is for verifying a value is set when retrieving. I was referring to [this](https://github.com/apache/arrow/blob/ccdaa9f2a4c1af1222df840b608e2ef465d331fc/java/memory/src/main/java/org/apache/arrow/memory/BoundsChecking.java) which is the same thing for checking bounds on addresses.

That looks good. I would close this PR.

**Pull request closed without merging**
