### PR TITLE
GH-44982: [C++] Add support for building system OpenTelemetry

### PR DESCRIPTION
**Pull request by kou**
### Rationale for this change

We don't need to disallow `-Dopentelemetry-cpp_SOURCE=SYSTEM`.

### What changes are included in this PR?

Remove forcing `opentelemetry-cpp_SOURCE=AUTO`.

### Are these changes tested?

Yes.

### Are there any user-facing changes?

Yes.
* GitHub Issue: #44982

### CODE REVIEW

**Comment by kou** [comment]
@github-actions crossbow submit -g cpp -g linux -g wheel

**Comment by kou** [comment]
@github-actions crossbow submit -g cpp -g linux -g wheel -g r

**Comment by kou** [comment]
@github-actions crossbow submit test-fedora-39-cpp

**Review by assignUser — APPROVED** [review]

**Comment by kou** [comment]
I'll merge this.

**Pull request merged**
