### PR TITLE
GH-40077: [CI] Use GitHub hosted M1 macOS runner

### PR DESCRIPTION
**Pull request by kou**
### Rationale for this change

If we use GitHub hosted M1 macOS runner instead of self-hosted M1 macOS runner, we don't need to maintain self-hosted M1 macOS runner.

### What changes are included in this PR?

Use GitHub hosted M1 macOS runner except `r-binary-packages`'s `r-packages` job. It uses macOS 11 but GitHub hosted M1 macOS runner is 13 or 14.

### Are these changes tested?

Yes.

### Are there any user-facing changes?

No.
* GitHub Issue: #40077

### CODE REVIEW

**Comment by kou** [comment]
@github-actions crossbow submit java-jars wheel-macos-*-arm64 r-binary-packages

**Comment by kou** [comment]
@github-actions crossbow submit verify-rc-source-*-macos-arm64

**Comment by kou** [comment]
Can we use `macos-13-arm64` or `macos-14-arm64` to verify RC of wheels?

https://github.com/apache/arrow/blob/6a7a6ee308b69c12f46f874cb3d52892e172d7b7/dev/tasks/tasks.yml#L1007-L1014

Is `macos-11` important here?

**Comment by kou** [comment]
@github-actions crossbow submit java-jars wheel-macos-*-arm64 r-binary-packages verify-rc-source-*-macos-arm64

**Comment by assignUser** [comment]
Imo I think we can drop the self hosted M1 for r-binary-packages as well, then we can retire the runner completely. It don't recall ever having an issue with the package related to the macos version (and x86 is even run on macos 13). The issues are usually with the environment setup (e.g. gnu libtool being on the path etc.)

**Comment by kou** [comment]
OK. Let's try with GitHub hosted runner.

**Comment by kou** [comment]
@github-actions crossbow submit java-jars wheel-macos-big-sur-cp310-arm64 r-binary-packages verify-rc-source-cpp-macos-arm64

**Comment by kou** [comment]
@github-actions crossbow submit wheel-macos-big-sur-cp310-* r-binary-packages

**Comment by kou** [comment]
@github-actions crossbow submit wheel-macos-big-sur-cp310-* r-binary-packages

**Comment by kou** [comment]
@github-actions crossbow submit wheel-macos-*-cp310-*

**Comment by kou** [comment]
@github-actions crossbow submit wheel-macos-*-cp310-*

**Comment by kou** [comment]
@github-actions crossbow submit wheel-macos-*-cp310-*

**Comment by kou** [comment]
@assignUser Could you check the artifacts of https://github.com/ursacomputing/crossbow/actions/runs/8220036683 ? It uses GitHub hosted runners.

**Comment by kou** [comment]
@github-actions crossbow submit wheel-macos-*-cp310-*

**Comment by pitrou** [comment]
Could we also add a PR C++ job on macOS ARM64? (or perhaps as a separate PR)

**Comment by kou** [comment]
Sure. We should do it in a separated PR because we have a separated issue for it.

**Comment by kou** [comment]
Hmm. It seems that we need #40418 for the wheel failures.

**Comment by kou** [comment]
@github-actions crossbow submit wheel-macos-*-cp38-*

**Comment by kou** [comment]
> I suppose the "install packages" step in the arm64 wheel builds will get faster once vcpkg results are cached?

Yes. The previous arm64 template doesn't use NuGet based cache but I unified amd64/arm64 templates in this PR. So the arm64 template can also use NuGet based cache. It'll reduce build time.

**Comment by kou** [comment]
Should we wait for #40418 before we merge this?

**Comment by pitrou** [comment]
I think it would be better to wait for https://github.com/apache/arrow/pull/40418.

**Comment by kou** [comment]
@github-actions crossbow submit wheel-macos-*-arm64

**Comment by kou** [comment]
Green. I'll merge this.

**Pull request merged**
