### PR TITLE
GH-31148: [Dev] Update URLs in the repo to point to main

### LINKED ISSUE #31148: [Dev] Update URLs in the repo to point to main
This should happen after INFRA makes the switch. It's not urgent for github URLs because github will automatically redirect.

**Reporter**: [Neal Richardson](https://issues.apache.org/jira/browse/ARROW-15696) / @nealrichardson

<sub>**Note**: *This issue was originally created as [ARROW-15696](https://issues.apache.org/jira/browse/ARROW-15696). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

### LINKED ISSUE #32804: [Dev] Remove "master" from default_branch property of Target class in core.py after migration to "main" as the default Git branch
As a follow up to [ARROW-15693](https://github.com/apache/arrow/pull/13975), support for the name "master" in the `default_branch` property of the `Target` class defined in `dev/archery/archery/crossbow/core.py` should be removed after the migration to "main" as the default Git branch is complete.

Making this change will also require updating the implementation of the `Target.is_default_branch()` method to use the keyword `is` instead of `in` for checking whether on the default branch.

**Reporter**: [Kevin Gurney](https://issues.apache.org/jira/browse/ARROW-17552) / @kevingurney

<sub>**Note**: *This issue was originally created as [ARROW-17552](https://issues.apache.org/jira/browse/ARROW-17552). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

### LINKED ISSUE #33215: [Dev] Replace hard-coded string "master" with "main" in dev/archery/archery/crossbow/core.py after default branch migration
<https://github.com/apache/arrow/pull/14033> uses several heuristics to determine the default Git branch name for the upstream apache/arrow project. When the heuristics fail to detect the default branch name, the strategy used in <https://github.com/apache/arrow/pull/14033> currently falls back to using the hard-coded branch name "master".

After <https://github.com/apache/arrow/pull/14033> is merged and after the upstream apache/arrow GitHub repository migrates to using "main" as the default branch name, the hard-coded string "master" should be replaced with "main" inside of the implementation of the computed property "default_branch_name" of the "Repo" class in dev/archery/archery/crossbow/core.py.

A similar instance of hard-coded "master" is used in `[dev/merge_arrow_pr.py](https://github.com/apache/arrow/pull/14533/files#diff-4aea0167b68c23bb8725640aec90bfc1d4caed14e9c21e1b64d65a54f9b47e63)` and it needs to be updated as well.

**Reporter**: [Kevin Gurney](https://issues.apache.org/jira/browse/ARROW-18011) / @kevingurney

<sub>**Note**: *This issue was originally created as [ARROW-18011](https://issues.apache.org/jira/browse/ARROW-18011). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

### LINKED ISSUE #34232: [R] AMD64 Ubuntu 20.04 R 4.2 CI is failing due to branch rename
### Describe the bug, including details regarding any error messages, version, and platform.

https://github.com/apache/arrow/actions/runs/4200029606/jobs/7285619420

```
  ══ Failed tests ════════════════════════════════════════════════════════════════
  ── Error ('test-io.R:73'): make_readable_file() works for non-filesystem URLs ──
  Error in `url(file, open = "rb")`: cannot open the connection to 'https://github.com/apache/arrow/raw/master/r/inst/v0.7.1.parquet'
  Backtrace:
      ▆
   1. └─arrow:::make_readable_file("https://github.com/apache/arrow/raw/master/r/inst/v0.7.1.parquet") at test-io.R:73:2
   2.   └─base::tryCatch(...)
   3.     └─base (local) tryCatchList(expr, classes, parentenv, handlers)
   4.       └─base (local) tryCatchOne(expr, names, parentenv, handlers[[1L]])
   5.         └─value[[3L]](cond)
   6.           ├─arrow:::MakeRConnectionInputStream(url(file, open = "rb"))
   7.           └─base::url(file, open = "rb")
```

We need to change `https://github.com/apache/arrow/raw/master/r/inst/v0.7.1.parquet` to `https://github.com/apache/arrow/raw/main/r/inst/v0.7.1.parquet`

### Component(s)

R

### PR DESCRIPTION
**Pull request by jorisvandenbossche**
* Closes: #31148
* Closes: #33215
* Closes: #32804
* Closes: #34232

### CODE REVIEW

**Review by domoritz — APPROVED** [review]

**Review by lidavidm — APPROVED** [review]

**Comment by jorisvandenbossche** [comment]
The R tests are failing because the URLs don't yet exist

**Comment by jorisvandenbossche** [comment]
@github-actions crossbow -g test

**Comment by jorisvandenbossche** [comment]
@github-actions crossbow submit -g test

**Comment by kevingurney** [comment]
@jorisvandenbossche - thank you for making these changes!

**Comment by jorisvandenbossche** [comment]
I didn't run all nightly (packaging and release verification) tests here, so didn't verify everything. But since this PR fixes some failures that otherwise happen on PRs, I am going to merge this, and we can follow-up if needed for the other builds.

**Comment by jorisvandenbossche** [comment]
@kevingurney and thank you for the preparatory work!

**Pull request merged**
