### PR TITLE
ARROW-10693: [Rust] [DataFusion] Add support to left join

### PR DESCRIPTION
**Pull request by jorgecarleitao**
This PR adds support to the left join in DataFusion.

The PR is divided in two: 
* the first commit extends `MutableDataArray` with an API to allow itself be extended by null values.
* the second commit uses this new API to add enable left joins in DataFusion

### CODE REVIEW

**Comment by jorgecarleitao** [comment]
fyi @alamb @andygrove :)

**Comment by andygrove** [comment]
I haven't reviewed in detail yet but LGTM

**Review by andygrove — APPROVED** [review]
LGTM. Thanks @jorgecarleitao

**Comment by Dandandan** [comment]
Awesome that the "main" join support is now in!

**Pull request closed without merging**
