### PR TITLE
ARROW-10287: [C++] Avoid std::random_device

### PR DESCRIPTION
**Pull request by pitrou**
std::random_device may block on some systems, even for long times.

### CODE REVIEW

**Comment by pitrou** [comment]
@kszucs

**Review by bkietz — APPROVED** [review]

**Comment by pitrou** [comment]
@github-actions crossbow submit conda-cpp-valgring

**Comment by pitrou** [comment]
@github-actions crossbow submit conda-cpp-valgrind

**Comment by pitrou** [comment]
@crossbow submit conda-cpp-valgrind

**Comment by pitrou** [comment]
This PR now also fixes the Valgrind failures.

**Comment by kszucs** [comment]
Thanks Antoine!

**Pull request closed without merging**
