### PR TITLE
ARROW-3687: [Rust] Anything measuring array slots should be `usize`

### PR DESCRIPTION
**Pull request by paddyhoran**

### CODE REVIEW

**Review by kszucs — APPROVED** [review]
Nice change!

**Comment by kszucs** [comment]
Because this brakes backward compatibility scheduling it to `0.13` release is reasonable.

**Review by andygrove — APPROVED** [review]
Awesome!

**Comment by crepererum** [comment]
+1

**Comment by wesm** [comment]
Do we need to preserve backwards compatibility in the Rust library yet?

**Comment by crepererum** [comment]
@wesm I don't think so, since we're still making many changes to the library and (IMHO) it's still somewhat in the design phase. Also, there are [no public consumers yet](https://crates.io/crates/arrow/reverse_dependencies).

**Comment by kszucs** [comment]
Cool! So re-schedule to `0.12`?

**Comment by andygrove** [comment]
I would like to see this in 0.12

**Pull request closed without merging**
