### PR TITLE
ARROW-2934: [Packaging] Add checksums creation to sign subcommand

### PR DESCRIPTION
**Pull request by cpcloud**
cs

### CODE REVIEW

**Review by wesm — APPROVED** [review]
+1

**Comment by kszucs** [comment]
LGTM

**Comment by cpcloud** [comment]
Merging on green

**Comment by cpcloud** [comment]
Had to change `.sig` to `.asc` for gpg signatures in accordance with [these ASF guidelines](https://www.apache.org/dev/release-distribution.html#sigs-and-sums)

**Comment by kszucs** [comment]
Thanks for the link!

**Pull request closed without merging**
