### PR TITLE
GH-43519: [Python][CI] Add Python 3.13 conda test build

### PR DESCRIPTION
**Pull request by jorisvandenbossche**
### Rationale for this change

When adding Python 3.13 support (https://github.com/apache/arrow/pull/43539), conda was not yet ready to support Python 3.13. But over the last weeks most conda packages having being updated, so trying again.

* GitHub Issue: #43519

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
@github-actions crossbow submit test-conda-python-3.13

**Comment by jorisvandenbossche** [comment]
@github-actions crossbow submit test-conda-python-3.13

**Comment by jorisvandenbossche** [comment]
@github-actions crossbow submit test-conda-python-3.13

**Comment by jorisvandenbossche** [comment]
@github-actions crossbow submit test-conda-python-*

**Comment by jorisvandenbossche** [comment]
Not entirely sure if it is worth adding this as long as we have to specify a custom channel (`--channel conda-forge/label/python_rc`), but the current version of the PR seems to work.

**Comment by jorisvandenbossche** [comment]
@github-actions crossbow submit test-conda-python-*

**Comment by raulcd** [comment]
Thanks @jorisvandenbossche , I missed that PR

**Review by raulcd — APPROVED** [review]
LGTM

**Pull request merged**
