### PR TITLE
ARROW-12241: [Python] Make CSV cancellation test more robust

### PR DESCRIPTION
**Pull request by pitrou**
* Make the interruptible workload larger
* Ensure KeyboardInterrupt doesn't stop the test suite

### CODE REVIEW

**Comment by pitrou** [comment]
@cyb70289 Can you try this PR?

**Comment by cyb70289** [comment]
> @cyb70289 Can you try this PR?

Test passed with this change.

If I make workload smaller, test will fail with `KeyboardInterrupt didn't interrupt CSV reading`, but not killing the pytest process. Looks good.

**Review by jorisvandenbossche — APPROVED** [review]
Looks good!

I suppose this is fast / small enough to not yet mark it with large_memory or so? (on my laptop, this test now takes around 1.5s, which is still acceptable, certainly given that the full `test_csv.py` only takes around 5s)

**Comment by pitrou** [comment]
It's fast merely because it's interrupted :-) Otherwise it could take 10 seconds or more.

**Pull request closed without merging**
