### PR TITLE
ARROW-14513: [Release][Go] Add /v6 suffix to release-6.0.0

### PR DESCRIPTION
**Pull request by zeroshade**

### CODE REVIEW

**Comment by domoritz** [comment]
Is this ready to be merged?

**Comment by emkornfield** [comment]
Yes, I think so.

**Comment by zeroshade** [comment]
@emkornfield hmmm, does this not get merged the same way? I may have messed something up. 😢

**Comment by emkornfield** [comment]
I don't see why it wouldn't be merged using the merge script?

**Comment by zeroshade** [comment]
@emkornfield I used the merge script. it looks like it merged it to the release-6.0.0 branch as desired, but didn't close this PR? I think. Should I manually close this then?

**Comment by emkornfield** [comment]
Yeah, we might want to file a bug about that?  Or maybe it is intended behavior because it expects to only close on master?

**Comment by zeroshade** [comment]
I'm assuming it's because of the expectation that it would only close on master. I'll close this now. Is there anything else I need to do here? Or am I good with getting this as part of a 6.0.1 patch release along with the javascript patch they wanted to push out?

**Comment by emkornfield** [comment]
I think this should be fine, we now need to get a 6.0.1 release done, so it might be worth pinging the dev@ thread. I imagine there might be a desire for a little bake time in case any additional issues crop up.

**Pull request closed without merging**
