### PR TITLE
ARROW-9043: [Go] Temporarily copy LICENSE.txt to go/

### PR DESCRIPTION
**Pull request by wesm**
See #7351. Once `go mod` can follow symlinks this should be replaced by a symlink.

### CODE REVIEW

**Comment by kszucs** [comment]
Ouch, this is annoying.

**Review by kszucs — APPROVED** [review]

**Comment by wesm** [comment]
Hm maybe this was merged too quickly. It sounds like we can avoid the copied license and instead rename the root LICENSE.txt to LICENSE. Can you help with this? Many packaging scripts will need to be updated

**Comment by kszucs** [comment]
I saw that renaming the top level license could work, but wasn't entirely clear from the comments. Merged because this should work until we try out the renaming. Created a jira to track this https://issues.apache.org/jira/browse/ARROW-9044

**Comment by jba** [comment]
Sorry to be a pain, folks. But the LICENSE file needs to be at the go module root, which is `go/arrow`.

**Pull request closed without merging**
