### PR TITLE
GH-35961: [C++][FlightSQL] Accept Protobuf 3.12.0 or later

### LINKED ISSUE #35961: [C++][FlightSQL] Accept Protobuf 3.12.0 or later
### Describe the enhancement requested

`FlightSql.proto` uses `optional`.

`optional` is added in Protobuf 3.12.0 as an experimental feature:

https://github.com/protocolbuffers/protobuf/releases/tag/v3.12.0

> [experimental] Singular, non-message typed fields in proto3 now support presence tracking. This is enabled by adding the "optional" field label and passing the --experimental_allow_proto3_optional flag to protoc. 

`optional` was marked as a official feature in Protobuf 3.15.0:

https://github.com/protocolbuffers/protobuf/releases/tag/v3.15.0

> Optional fields for proto3 are enabled by default, and no longer require the --experimental_allow_proto3_optional flag.

We require Protobuf 3.15.0 or later for Flight SQL but Ubuntu 22.04 LTS ships Protobuf 3.12.4: https://packages.ubuntu.com/search?keywords=protobuf-compiler

If we accept Protobuf 3.12.0 or later by usung `--experimental_allow_proto3_optional` flag, we can use system Protobuf on Ubuntu 22.04. It reduces CI time and deb package build time.

### Component(s)

C++, FlightRPC

### PR DESCRIPTION
**Pull request by kou**
### Rationale for this change

We can use `optional` with Protobuf 3.12.0 by specifying `--experimental_allow_proto3_optional` explicitly.

If we accept Protobuf 3.12.0 or later for Flight SQL, we can use system Protobuf on Ubuntu 22.04. Because Ubuntu 22.04 ships Protobuf 3.12.4.

### What changes are included in this PR?

Specify  `--experimental_allow_proto3_optional` explicitly when Protobuf is < 3.15.0. 

### Are these changes tested?

Yes.

### Are there any user-facing changes?

Yes.
* Closes: #35961

### CODE REVIEW

**Comment by kou** [comment]
@github-actions crossbow submit ubuntu-jammy-* ubuntu-kinetic-*

**Comment by kou** [comment]
@github-actions crossbow submit test-ubuntu-22.04-cpp

**Review by lidavidm — APPROVED** [review]
LGTM. Thanks!

**Comment by raulcd** [comment]
is the failure related?
```
 /build/apache-arrow-13.0.0.dev186/cpp/src/arrow/flight/sql/server.cc:364:20: error: could not convert ‘any.google::protobuf::Any::PackFrom((* & message))’ from ‘void’ to ‘bool’
  364 |   if (!any.PackFrom(message)) {
      |        ~~~~~~~~~~~~^~~~~~~~~
      |                    |
      |                    void
/build/apache-arrow-13.0.0.dev186/cpp/src/arrow/flight/sql/server.cc:364:20: error: in argument to unary !
```

**Comment by kou** [comment]
Oh, it's related. I'll take a look at it.

**Comment by kou** [comment]
@github-actions crossbow submit ubuntu-jammy-* ubuntu-kinetic-* debian-bullseye-* test-ubuntu-*-cpp test-debian-*-cpp

**Comment by raulcd** [comment]
@kou are the issues found on the RC1 failed jobs related to the new Protobuf version on MacOS for AMD and ARM64 supposed to be solved with this one?
```
 /Applications/Xcode_14.2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: ../../release/libarrow.a(util_avx2.cc.o) has no symbols
ld: illegal thread local variable reference to regular symbol __ZN6google8protobuf8internal15ThreadSafeArena13thread_cache_E for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
A couple of examples:
* [verify-rc-source-python-macos-arm64](https://github.com/ursacomputing/crossbow/actions/runs/5201543997/jobs/9381858254)
* [verify-rc-source-python-macos-amd64](https://github.com/ursacomputing/crossbow/actions/runs/5201543279/jobs/9381856029)

**Comment by raulcd** [comment]
To give more context as shared with Zulip, I think this is due to the new version of protobuf on hombrew that was merged yesterday:
https://github.com/Homebrew/homebrew-core/pull/132957 and https://github.com/Homebrew/homebrew-core/pull/132988

**Comment by kou** [comment]
I think that it's not related to the problem.
I've opened #35987. See it for details.

**Comment by kou** [comment]
@github-actions crossbow submit ubuntu-jammy-* ubuntu-kinetic-* debian-bullseye-* test-ubuntu-*-cpp test-debian-*-cpp-*

**Comment by kou** [comment]
@github-actions crossbow submit ubuntu-focal-* debian-bookworm-*

**Comment by kou** [comment]
+1

**Pull request merged**
