### PR TITLE
ARROW-5162: [Rust] [Parquet] Rename mod reader to arrow.

### PR DESCRIPTION
**Pull request by liurenjie1024**
Rename mod reader to arrow,

### CODE REVIEW

**Comment by liurenjie1024** [comment]
@sunchao @andygrove @nevi-me Please help review.

**Review by nevi-me — APPROVED** [review]
I saw Chao's comment about renaming this. Approving on that basis

**Comment by sunchao** [comment]
@liurenjie1024 Looks good. Could you address the CI failure though?

**Comment by liurenjie1024** [comment]
@sunchao CI error fixed.

**Review by andygrove — APPROVED** [review]

**Review by sunchao — APPROVED** [review]

**Pull request closed without merging**
