### PR TITLE
ARROW-7249: [CI] Release test fails in master due to new arrow-flight Rust crate

### PR DESCRIPTION
**Pull request by andygrove**

### CODE REVIEW

**Review by nevi-me — APPROVED** [review]

**Comment by kou** [comment]
@kszucs Can we remove https://github.com/apache/arrow/blob/master/.github/workflows/dev.yml#L56 check to run for each pull request?
(Can we also remove https://github.com/apache/arrow/blob/master/.github/workflows/dev.yml#L92 too?)

**Comment by kszucs** [comment]
@kou The reason why I've removed them from running on each PR to reduce the number of the triggered builds. See the mailing list thread about the queueing concerns. The docs build takes fairly long time, in contrary of the source release test. 

@andygrove have you run the source release test? Because the master is still failing.

**Comment by andygrove** [comment]
Sorry. I will look at this as soon as I can but can't get to a computer for
a couple of hours.

**Comment by kou** [comment]
@kszucs Thanks. The mailing list discussion is https://lists.apache.org/thread.html/8fefdebd76742fe4ffb2ee7d0fa88ddf2b3229c55935c146b0d97e52@%3Cdev.arrow.apache.org%3E , right?
I've opened https://issues.apache.org/jira/browse/ARROW-7255 to enable the source release test on pull request.

**Comment by kszucs** [comment]
@kou yes, that is it.

**Pull request closed without merging**
