### PR TITLE
ARROW-10385: [C++][Gandiva] Add support for LLVM 11

### PR DESCRIPTION
**Pull request by kou**
LLVM link failures in MinGW build are caused by https://github.com/msys2/MINGW-packages/issues/7170 .
They aren't fixed by this pull request. The problem will be fixed in upstream.

### CODE REVIEW

**Comment by kou** [comment]
@github-actions crossbow submit -g nightly

**Comment by kou** [comment]
@github-actions crossbow submit homebrew-cpp nuget

**Comment by kou** [comment]
Remaining issues:

  * MinGW link error

**Comment by kou** [comment]
@github-actions crossbow submit -g nightly

**Comment by kou** [comment]
MinGW link problem is caused by https://github.com/msys2/MINGW-packages/issues/7170 .
It'll be fixed in upstream.

I'll merge this in a few days if nobody objects it. Because MinGW build is failed without this change because MSYS2 migrates its LLVM to 11 from 10 and LLVM 10 isn't available.

**Comment by pprudhvi** [comment]
@kou can we merge this?

**Comment by kou** [comment]
OK.
Let's merge this.

**Pull request closed without merging**
