### PR TITLE
ARROW-12770: [Plasma][C++][JAVA] Add Metrics API for clients to get share memory usage

### PR DESCRIPTION
**Pull request by jikunshang**
Implement an API for Plasma clients to get share memory usage

### CODE REVIEW

**Comment by emkornfield** [comment]
It looks like this might be failing tests on bigendian machines (see CI).  Also can we separate C++ and JNI compoments into two separate issues/PRs.

**Comment by jikunshang** [comment]
> It looks like this might be failing tests on bigendian machines (see CI). Also can we separate C++ and JNI compoments into two separate issues/PRs.

Thanks for your comments. Fixed big endian issue. Is it as expected that JNI CI exceed 40 mins?

**Comment by emkornfield** [comment]
> Thanks for your comments. Fixed big endian issue. Is it as expected that JNI CI exceed 40 mins?

Could be I think queue times have been going up dramatically.

**Comment by amol-** [comment]
Closing because it has been untouched for a while, in case it's still relevant feel free to reopen and move it forward 👍

**Pull request closed without merging**
