### PR TITLE
ARROW-589: C++: Use system provided shared jemalloc if static is unavailable

### PR DESCRIPTION
**Pull request by xhochy**

### CODE REVIEW

**Review by wesm — APPROVED** [review]
+1

**Comment by wesm** [comment]
Looks like Travis CI may have been impacted by the S3 outage. Perhaps we should wait to merge any more patches until we have builds running again

**Comment by xhochy** [comment]
Green build: https://travis-ci.org/xhochy/arrow/builds/207314255

**Comment by wesm** [comment]
Thanks

**Comment by wesm** [comment]
merging

**Pull request closed without merging**
