### PR TITLE
ARROW-4115: [Gandiva] zero-init boolean data bufs

### PR DESCRIPTION
**Pull request by pravindra**

### CODE REVIEW

**Comment by pravindra** [comment]
@wesm @shyambits2004

**Review by shyambits2004 — APPROVED** [review]
lgtm

**Comment by wesm** [comment]
Do you want to conditionally do this only if `ARROW_VALGRIND` is defined? It's not a major performance penalty so not big deal either way

**Comment by pravindra** [comment]
> Do you want to conditionally do this only if `ARROW_VALGRIND` is defined? It's not a major performance penalty so not big deal either way

the ARROW_VALGRIND flag is passed only for the test binaries, but this code is part of libgandiva. so, it'll require more changes. I think it's okay to do the bzero unconditionally.

**Review by wesm — APPROVED** [review]
+1

**Pull request closed without merging**
