### PR TITLE
ARROW-5559: [C++] Add an IpcOptions structure

### PR DESCRIPTION
**Pull request by pitrou**
Switch existing APIs to take IpcOptions rather than individual option arguments.

### CODE REVIEW

**Comment by pitrou** [comment]
@wesm @lihalite any concerns?

**Review by ghost — APPROVED** [review]
Looks good to me on the Flight side.

**Comment by wesm** [comment]
Will review

**Comment by kszucs** [comment]
@ursabot build

**Comment by pitrou** [comment]
Rebased.

**Comment by pitrou** [comment]
@ursabot build

**Comment by wesm** [comment]
Sorry for the delay. Looking at this now

**Review by wesm — APPROVED** [review]
+1. Didn't see anything crazy, thank you for doing this

**Pull request closed without merging**
