### PR TITLE
MINOR: [C++] Bump arrow-testing to include repro file for #41044

### PR DESCRIPTION
**Pull request by felipecrv**
### What changes are included in this PR?

Bump `arrow-testing` to include the latest commit.

### CODE REVIEW

**Comment by kou** [comment]
Could you also add this to run CI for C++?

```diff
diff --git a/.github/workflows/cpp.yml b/.github/workflows/cpp.yml
index 1d10be3b5b..f9de0c245b 100644
--- a/.github/workflows/cpp.yml
+++ b/.github/workflows/cpp.yml
@@ -21,6 +21,7 @@ on:
   push:
     paths:
       - '.github/workflows/cpp.yml'
+      - '.gitmodules'
       - 'ci/docker/**'
       - 'ci/scripts/cpp_*'
       - 'ci/scripts/install_azurite.sh'
@@ -34,6 +35,7 @@ on:
   pull_request:
     paths:
       - '.github/workflows/cpp.yml'
+      - '.gitmodules'
       - 'ci/docker/**'
       - 'ci/scripts/cpp_*'
       - 'ci/scripts/install_azurite.sh'
```

**Comment by kou** [comment]
Ah, it will not detect `testing` change... This?

```diff
diff --git a/.github/workflows/cpp.yml b/.github/workflows/cpp.yml
index 1d10be3b5b..dd5abbe1b4 100644
--- a/.github/workflows/cpp.yml
+++ b/.github/workflows/cpp.yml
@@ -31,6 +31,7 @@ on:
       - 'cpp/**'
       - 'docker-compose.yml'
       - 'format/Flight.proto'
+      - 'testing'
   pull_request:
     paths:
       - '.github/workflows/cpp.yml'
@@ -44,6 +45,7 @@ on:
       - 'cpp/**'
       - 'docker-compose.yml'
       - 'format/Flight.proto'
+      - 'testing'
 
 concurrency:
   group: ${{ github.repository }}-${{ github.head_ref || github.sha }}-${{ github.workflow }}
```

**Comment by felipecrv** [comment]
Done.

**Review by pitrou — APPROVED** [review]
Thanks @felipecrv !

**Pull request merged**
