### PR TITLE
ARROW-9671: [C++] Fix a bug in BasicDecimal128 constructor that interprets uint64_t integers with highest bit set as negative.

### PR DESCRIPTION
**Pull request by MingyuZhong**

### CODE REVIEW

**Review by emkornfield — APPROVED** [review]
LGTM, will merge once CI is green.

**Comment by emkornfield** [comment]
Looks like formatting needs to be run:

```
   template <typename T,
-            typename = typename std::enable_if<std::is_integral<T>::value &&
-                                               (sizeof(T) <= sizeof(uint64_t)), T>::type>
+            typename = typename std::enable_if<
+                std::is_integral<T>::value && (sizeof(T) <= sizeof(uint64_t)), T>::type>
   constexpr BasicDecimal128(T value) noexcept
-      : BasicDecimal128(value >= T{0} ? 0 : -1,
-                        static_cast<uint64_t>(value)) {}
+      : BasicDecimal128(value >= T{0} ? 0 : -1, static_cast<uint64_t>(value)) {}
```

**Comment by kiszk** [comment]
good catch!

**Comment by emkornfield** [comment]
It seems travis is having issues today.  I'm going to go ahead and merge this.

**Pull request closed without merging**
