### PR TITLE
GH-37814: [Go][Parquet] Round trip Parquet schema

### LINKED ISSUE #37814: [Go][Parquet] Round trip Parquet schema
### Describe the bug, including details regarding any error messages, version, and platform.

I'm using `pqarrow.FromParquet()` and `pqarrow.ToParquet()` to transform a Parquet schema into an Arrow schema and back.  It may be that I can avoid this, but I'm starting with a Parquet schema and want to make use of the `pqarrow.FileWriter`, so it seems like I need to work with an Arrow schema.

This is likely user error, but I was surprised to see that repetition information was lost when going from a Parquet schema to an Arrow schema and back.  Specifically, repeated fields in Parquet become required lists.

Here is an example test that tries to round trip a schema with a single repeated bool field:
```go
func TestRoundTripSchema(t *testing.T) {
	fields := schema.FieldList{
		schema.NewBooleanNode("bools", parquet.Repetitions.Repeated, -1),
	}
	root, err := schema.NewGroupNode("root", parquet.Repetitions.Required, fields, -1)
	require.NoError(t, err)
	parquetSchema1 := schema.NewSchema(root)

	arrowSchema, err := pqarrow.FromParquet(parquetSchema1, nil, nil)
	require.NoError(t, err)

	writerProps := parquet.NewWriterProperties(
		parquet.WithRootName("root"),
		parquet.WithRootRepetition(parquet.Repetitions.Required),
	)
	parquetSchema2, err := pqarrow.ToParquet(arrowSchema, writerProps, pqarrow.DefaultWriterProps())
	require.NoError(t, err)

	assert.True(t, parquetSchema1.Equals(parquetSchema2))
	assert.Equal(t, parquetSchema1.String(), parquetSchema2.String())
}
```

The difference in the (string representation of the) schemas looks like this:
```diff
--- Expected
+++ Actual
@@ -1,3 +1,7 @@
 required group field_id=-1 root {
-  repeated boolean field_id=-1 bools;
+  required group field_id=-1 bools (List) {
+    repeated group field_id=-1 list {
+      optional boolean field_id=-1 element;
+    }
+  }
 }
```

I see that there is some special meaning to the the `metadata.KeyValueMetadata` pairs passed to [`pqarrow.FromParquet()`](https://pkg.go.dev/github.com/apache/arrow/go/v13@v13.0.0/parquet/pqarrow#FromParquet).  Should I be passing information about whether to use lists or repeated values there?  Or is there a [`parquet.WriterProperty`](https://pkg.go.dev/github.com/apache/arrow/go/v13@v13.0.0/parquet#WriterProperty) that I should be passing along to [`pqarrow.ToParquet()`](https://pkg.go.dev/github.com/apache/arrow/go/v13@v13.0.0/parquet/pqarrow#ToParquet)?

Thanks for any suggestions on how to retain the original repetition when round-tripping a Parquet schema through an Arrow schema.

### Component(s)

Go, Parquet

### PR DESCRIPTION
**Pull request by tschaub**
### Rationale for this change

This makes it possible to round trip a Parquet schema through the `pqarrow.FromParquet()` and `pqarrow.ToParquet()` functions, maintaining the field repetition from the original schema.

### What changes are included in this PR?

The changes make it so the `pqarrow.FromParquet()` function adds `"PARQUET:repetition"` metadata to the Arrow fields.  The `pqarrow.ToParquet()` function then uses this to restore the original repetition when creating the Parquet schema.  This is similar to the existing `"PARQUET:field_id"` metadata.

### Are these changes tested?

A new `TestRoundTripSchema` function is added and existing tests are updated to reflect the new field metadata.

### Are there any user-facing changes?

Before this change, if you started with a Parquet schema that had a repeated field, after calling `pqarrow.FromParquet()` to create an Arrow schema and then `pqarrow.ToParquet()` to create a Parquet schema, the previously repeated field would now be a list.  After this change, the repeated field is still a repeated field.

* Closes: #37814

### CODE REVIEW

**Comment by tschaub** [comment]
I'm marking this as a draft while I track down an issue using the `pqarrow.FileWriter` to write records with repeated fields (works when the parquet schema has a list field, not when it has a repeated primitive).

**Comment by tschaub** [comment]
@zeroshade (or others) - I haven't been able to get to the bottom of the issue mentioned above, and I could use some input.

I might be working with a flawed understanding of things, so I'll describe how I think things are supposed to work first.  My assumption is an Arrow `array.List` can either be represented in Parquet using a repeated primitive field or a group field with a primitive nested in it.

For example, I thought an `array.List` containing `array.Float64` data could be written to Parquet using either of the two schema below.

A repeated primitive field:
```
required group root {
  repeated double numbers;
}
```

Or a primitive nested in a group annotated as a list:
```
required group root {
  required group numbers (LIST) {
    repeated group list {
      optional double element;
    }
  }
}
```

The `pqarrow.FileWriter` currently uses the nested group structure when creating a Parquet schema.  The changes in this branch make it so the file writer conditionally uses a repeated primitive instead - this happens if the passed Arrow schema was converted from a Parquet schema that uses a repeated primitive.

I'm finding that record writing works when using a Parquet schema with the nested group but that it doesn't work when using a schema with a repeated primitive.

I tried to write tests to demonstrate the issue based on the latest in `main`, but I don't think it can be done using the exported `pqarrow.NewFileWriter()` function.  So in an effort to narrow things down, I created a similar `pqarrow.NewFileWriterForTesting()` function that accepts both a Parquet schema and an Arrow schema (instead of creating the former from the latter).

With that new function, this test passes:
```go
func TestRoundTripListOfFloat64(t *testing.T) {
	inputNumbers := []float64{10, 9, 8}
	name := "numbers"

	parquetSchema := schema.NewSchema(schema.MustGroup(
		schema.NewGroupNode("root", parquet.Repetitions.Required, schema.FieldList{
			schema.MustGroup(schema.ListOf(
				schema.NewFloat64Node(name, parquet.Repetitions.Optional, -1),
				parquet.Repetitions.Required,
				-1,
			)),
		}, -1),
	))

	outputNumbers := roundTripFloat64s(t, parquetSchema, name, inputNumbers)
	assert.Equal(t, inputNumbers, outputNumbers)
	// this passes
}
```

But this test fails:
```go
func TestRoundTripRepeatedFloat64(t *testing.T) {
	inputNumbers := []float64{10, 9, 8}
	name := "numbers"

	parquetSchema := schema.NewSchema(schema.MustGroup(
		schema.NewGroupNode("root", parquet.Repetitions.Required, schema.FieldList{
			schema.NewFloat64Node(name, parquet.Repetitions.Repeated, -1),
		}, -1),
	))

	outputNumbers := roundTripFloat64s(t, parquetSchema, name, inputNumbers)
	assert.Equal(t, inputNumbers, outputNumbers)
	// this fails
	// expected: []float64{10, 9, 8}
	// actual  : []float64(nil)
}
```

See https://github.com/apache/arrow/compare/main...tschaub:arrow:write-repeated for the `roundTripFloat64s` function and the `pqarray.NewFileWriterForTesting`.  (Those changes are based on the latest in the `main` branch, not the changes in this branch).

I've stepped through the Arrow column writer writing code and can confirm that the `defLevels` are different in the two tests above (`[3, 3, 3]` for the passing case vs `[2, 2, 2]` for the failing case), but I can't make sense of why the values are not getting written in the case of the schema with the repeated primitive.

I know this is an unsolicited change, and a lot to dig into, but I appreciate any thoughts that others have.

**Comment by zeroshade** [comment]
I'll try to dig into this a bit when I have the chance, but offhand the fact that the defLevels are different would be expected as the schema is different and has fewer levels in it. That said, offhand I think the issue is that a single repeated primitive node is simply not being seen as a LIST field. If we look at the [parquet format spec](https://github.com/apache/parquet-format/blob/master/LogicalTypes.md#backward-compatibility-rules), the first thing I notice is that the schema

```
required group root {
  repeated double numbers;
}
```

Doesn't contain any field tagged with the `LIST` logical type, however the spec also says:

> This does not affect repeated fields that are not annotated: A repeated field that is neither contained by a LIST- or MAP-annotated group nor annotated by LIST or MAP should be interpreted as a required list of required elements where the element type is the type of the field.

We handle this case here: https://github.com/apache/arrow/blob/main/go/parquet/pqarrow/schema.go#L889 

However, i think the writer assumes that we are using the proper 3-level annotation struct which is what we generate when calling `ToParquet` to convert an arrow schema into a Parquet schema. So without having dug into this yet, my initial gut feeling is that the issue is going to be in `path_builder.go` which is where we construct the deflevels and rep levels that we're going to write. In theory the resulting defLevels to write this should be all 0 as this should get converted into a non-nullable list of non-nullable elements.

Hope this helps, and i'll try to find some time to dig into this further next week.

**Comment by tschaub** [comment]
Thanks for the response, @zeroshade.

I've decided to abandon the effort to retain the input Parquet schema while using the `pqarrow.FileWriter`.  I'll close this and the associated ticket for now.  If anybody else has a need to preserve the input Parquet schema while using the `pqarrow.FileWriter`, perhaps it can be revisited later.

**Pull request closed without merging**
