### PR TITLE
ARROW-6366: [Java] Make field vectors final explicitly

### PR DESCRIPTION
**Pull request by liyafan82**
According to the discussion in https://lists.apache.org/thread.html/836d3b87ccb6e65e9edf0f220829a29edfa394fc2cd1e0866007d86e@%3Cdev.arrow.apache.org%3E, field vectors should not be extended, so they should be made final explicitly.

### CODE REVIEW

**Review by ghost — APPROVED** [review]
This needs rebasing, but looks good on principle.

**Comment by liyafan82** [comment]
> This needs rebasing, but looks good on principle.

@lihalite Rebased. Thanks for your comments.

**Comment by emkornfield** [comment]
@lihalite Can this be merged?

**Comment by lihalite** [comment]
@emkornfield yes, this is good. (Sorry, haven't yet set everything up...need to do it from home.)

**Comment by emkornfield** [comment]
+1, thank you.

**Pull request closed without merging**
