### PR TITLE
ARROW-18389: [CI][Python] Update nightly test-conda-python-3.7-pandas-0.24 to pandas >= 1.0

### PR DESCRIPTION
**Pull request by raulcd**

### CODE REVIEW

**Comment by pitrou** [comment]
@raulcd Is this ready for review?

**Comment by raulcd** [comment]
@pitrou I was waiting for https://github.com/apache/arrow/pull/14716 to be merged to rebase and trigger the tests again but might be a little overkill. Let me know if you want me to do that or if you are ok as it is.

**Comment by pitrou** [comment]
If you can do it right now, why not.

**Comment by raulcd** [comment]
@github-actions crossbow submit test-conda-python-3.7-pandas-1.0

**Review by kou — APPROVED** [review]
+1

**Pull request merged**
