### PR TITLE
[Release] Verify 3.0.0 release candidate

### PR DESCRIPTION
**Pull request by kszucs**

### CODE REVIEW

**Comment by kszucs** [comment]
@github-actions crossbow submit -p release=3.0.0 -p rc=1 -g verify-rc

**Comment by kszucs** [comment]
@kou I think the xenial package must be fixed by removing libprotobuf from the [xenial control file](https://github.com/apache/arrow/blob/master/dev/tasks/linux-packages/apache-arrow/debian.ubuntu-xenial/control#L22), so exclude it from `ARROW_SYSTEM_DEPENDENCIES` cmake variable.

**Comment by kou** [comment]
Oh, sorry.
https://github.com/apache/arrow/pull/9251 fixes it but it's not a blocker of this RC.
Because users have a workaround: `apt install -y libprotobuf-dev`

**Comment by kszucs** [comment]
I'm going to cut RC2 with #9244 included.

**Comment by kszucs** [comment]
@github-actions crossbow submit -p release=3.0.0 -p rc=2 verify-rc-source-*

**Comment by kszucs** [comment]
@github-actions crossbow submit -p release=3.0.0 -p rc=2 verify-rc-source-*

**Comment by kszucs** [comment]
@github-actions crossbow submit -p release=3.0.0 -p rc=2 verify-rc-binaries-*

**Comment by kszucs** [comment]
@github-actions crossbow submit -p release=3.0.0 -p rc=2 verify-rc-wheels-*

**Comment by kou** [comment]
It seems that https://apache.bintray.com/arrow/debian-rc/pool/buster/main/a/apache-arrow/libparquet-glib300-dbgsym_3.0.0-1_arm64.deb is broken.
It's uploaded to bintray.com (I can see it in Web UI) but it's not published.

Could you delete the `debian-rc` version and re-upload Debian related files?

**Comment by kszucs** [comment]
Yes, I'm working on it.

**Comment by kszucs** [comment]
I'm re-uploading ubuntu-rc as well.

**Comment by kszucs** [comment]
Should be good now.

**Comment by kou** [comment]
This is not a blocker but arm64 APT packages miss `gir1.2-gandiva-1.0` and `gir1.2-arrow-dataset-1.0` packages: #9260 (Sorry)
It can be fixed by downloading them to local `packages/build-25/XXX/` (`build-25` is right?) manually:

```bash
#!/bin/sh

set -eux

for target in debian-buster ubuntu-xenial ubuntu-bionic ubuntu-focal ubuntu-groovy; do
  curl -o packages/build-25/${target}-arm64/gir1.2-arrow-dataset-1.0_3.0.0-1_arm64.deb \
       https://github.com/ursacomputing/crossbow/releases/download/build-25-travis-${target}-arm64/gir1.2-arrow-dataset-1.0_3.0.0-1_arm64.deb
  curl -o packages/build-25/${target}-arm64/gir1.2-gandiva-1.0_3.0.0-1_arm64.deb \
       https://github.com/ursacomputing/crossbow/releases/download/build-25-travis-${target}-arm64/gir1.2-gandiva-1.0_3.0.0-1_arm64.deb
done
```

and re-uploading Debian and Ubuntu files.

But it's not required because this is not a blocker. (I think that nobody uses them.)

**Comment by kszucs** [comment]
I uploaded them, so theoretically they should be available.

**Comment by kou** [comment]
Thanks! But it doesn't work because of my failure... Sorry...
I forget to add the `-L` (redirect) curl option in the above script...

Anyway, we should mark this is a known problem of 3.0.0.

**Comment by kou** [comment]
#9273 is not a blocker but we can't use `dev/release/post-06-csharp.sh`. We need to upload NuGet packages manually. (I'll do.)

**Comment by kszucs** [comment]
> Thanks! But it doesn't work because of my failure... Sorry...
> I forget to add the `-L` (redirect) curl option in the above script...
> 
> Anyway, we should mark this is a known problem of 3.0.0.

Updated.

**Comment by kou** [comment]
Confirmed. Thanks!

**Comment by nevi-me** [comment]
@kszucs @kou I assume this is stale?

**Comment by kou** [comment]
Yes. Thanks for notify this.
We can close this because we've released 3.0.0.

**Pull request closed without merging**
