### PR TITLE
ARROW-3036: [Go] implement array.NewSlice

### PR DESCRIPTION
**Pull request by sbinet**
This CL implements the ability to slice a given array.Interface,
i.e. the Go equivalent of:

```
  vs := []float64{1, 2, 3, 4}
  sub := vs[1:3]
```

also, to support sub-slicing, offsets' support had to be implemented inside the `array.Data` and nullbitmap types.
namely, the `arrow/internal/bitutil.CountSetBits` function had to be modified to support counting bits from an arbitrary offset.
this resulted in a minor (?) speed-bump:

```
    name                 old time/op    new time/op    delta
    CountSetBits_3-8       8.16ns ± 1%    8.18ns ± 0%  +0.31%  (p=0.000 n=19+18)
    CountSetBits_32-8      7.62ns ± 1%    7.79ns ± 1%  +2.24%  (p=0.000 n=18+18)
    CountSetBits_128-8     6.80ns ± 1%    7.03ns ± 1%  +3.40%  (p=0.000 n=18+19)
    CountSetBits_1000-8    18.7ns ± 0%    17.8ns ± 1%  -4.92%  (p=0.000 n=16+20)
    CountSetBits_1024-8    16.1ns ± 0%    16.1ns ± 1%  +0.44%  (p=0.000 n=20+20)
    
    name                 old alloc/op   new alloc/op   delta
    CountSetBits_3-8        0.00B          0.00B         ~     (all equal)
    CountSetBits_32-8       0.00B          0.00B         ~     (all equal)
    CountSetBits_128-8      0.00B          0.00B         ~     (all equal)
    CountSetBits_1000-8     0.00B          0.00B         ~     (all equal)
    CountSetBits_1024-8     0.00B          0.00B         ~     (all equal)
    
    name                 old allocs/op  new allocs/op  delta
    CountSetBits_3-8         0.00           0.00         ~     (all equal)
    CountSetBits_32-8        0.00           0.00         ~     (all equal)
    CountSetBits_128-8       0.00           0.00         ~     (all equal)
    CountSetBits_1000-8      0.00           0.00         ~     (all equal)
    CountSetBits_1024-8      0.00           0.00         ~     (all equal)
```

I believe some of that speed bump could be recoup'd (see `FIXME` in `go/arrow/internal/bitutil/bitutil.go`)

@stuartcarnie PTAL.

needs https://github.com/apache/arrow/pull/2412.

### CODE REVIEW

**Review by stuartcarnie — APPROVED** [review]
Thanks for adding slicing; it was something I planned to add

**Comment by sbinet** [comment]
@stuartcarnie, thanks :)
Have you any input/idea wrt the comment in CountSetBits ?

**Comment by stuartcarnie** [comment]
@sbinet those changes to `CountSetBits` are a minor performance hit, so I'm not concerned

**Comment by sbinet** [comment]
rebased on top of latest master.

**Comment by pitrou** [comment]
Needs rebasing again :-)

**Comment by wesm** [comment]
@pitrou you should be able to rebase this branch yourself and the other patches will drop out automatically

**Comment by wesm** [comment]
I rebase contributors' branches all the time

**Comment by pitrou** [comment]
Well, there are conflicts here and I don't really feel competent to fix conflicts in the Go base (though they might be trivial).

**Comment by pitrou** [comment]
Or you mean the conflicts are only because @sbinet based one PR on top of the other? Let's see.

**Comment by pitrou** [comment]
Ok, rebased... though I should have started with the dependent PR :-)

**Comment by sbinet** [comment]
sorry about that.
I actually don't know what's the custom here wrt stacked PRs.
(but I figured it was easier to ask for forgiveness)

**Comment by pitrou** [comment]
@sbinet I think we're always rebasing here, which sometimes minimizes conflicts.

**Comment by sbinet** [comment]
ok.

**Review by wesm — APPROVED** [review]
+1. Rebased, will merge once the Go build runs

**Pull request closed without merging**
