### PR TITLE
ARROW-954: Flag for compiling Arrow with header-only boost

### PR DESCRIPTION
**Pull request by pcmoritz**

### CODE REVIEW

**Review by xhochy — COMMENTED** [review]
I would prefer if we re-introduced the `ARROW_HDFS`  option again or if we could eliminate boost filesystem completely (very wishful thinking :D).

But I'm fine with this for the moment, just waiting for the AppVeyor build to turn green.

**Comment by wesm** [comment]
Yes, I think would be good to reintroduce `ARROW_HDFS`. If it becomes a long term issue we can create a leaf library.

**Comment by wesm** [comment]
I think you could set the current BOOST_HEADER_ONLY variable based on whether `ARROW_HDFS` is on; so if there are more options in the future that preclude a header-only build then this code is easier to maintain

**Comment by pcmoritz** [comment]
Thanks, I reintroduced `ARROW_HDFS`

**Comment by pcmoritz** [comment]
actually I think I deactivated more tests than needed if the boost static/dynamic libraries are not available, please hang on with merging

**Comment by pcmoritz** [comment]
should be ready now

**Comment by xhochy** [comment]
I'm just a bit confused how we detect the location of the boost headers for `boost::multiprecision` now in the case that we built with headers only. It seems that in this case `find_package(Boost)` is never run.

**Comment by wesm** [comment]
That's an issue, because it will only work if Boost is installed at system level. So we still need to run find_package(Boost)

**Comment by pcmoritz** [comment]
You are right, that's an oversight on my part, I'll fix it!

I wonder if there is a good way to test for problems like this in the future. What would be ideal would be a travis build that tries to run a large number of different configurations infrequently (like once a day).

**Comment by wesm** [comment]
We could test for this particular issue by using a toolchain Boost from conda-forge (rather than the Ubuntu system packages), or we could do that in a separate integration testing repo (easier to Dockerize with Circle CI)

**Comment by pcmoritz** [comment]
I tested it like this:

Create a new EC2 ubuntu 16.04 instance, `apt-get install build-essential cmake` and:
- Install anaconda from https://www.continuum.io/downloads#linux
- `conda install -c conda-forge boost=1.64.0`
- `git clone https://github.com/pcmoritz/arrow`
- `cd arrow; git checkout boost-header-only`
- `cd cpp; mkdir build; cd build; cmake -DARROW_HDFS=OFF ..; make`

It found the boost from conda and compiled and decimal-test runs.

**Review by xhochy — APPROVED** [review]
+1, will merge once the builds have finished.

**Comment by pcmoritz** [comment]
hm, looks like travis failed b/c the parquet-cpp repo timed out, everything passed on my branch:

https://travis-ci.org/pcmoritz/arrow/builds/230050584?utm_source=github_status&utm_medium=notification

**Pull request closed without merging**
