### PR TITLE
ARROW-1017: [Python] Fix memory leaks in conversion to pandas.DataFrame

### PR DESCRIPTION
**Pull request by wesm**
Notes:

* `PyList_Append` increments ref count, so new objects must be DECREF'd after being inserted
* `PyArray_SimpleNewFromDescr` does not set `NPY_ARRAY_OWNDATA`, neither does `NewFromDescr`

### CODE REVIEW

**Review by xhochy — APPROVED** [review]
+1, LGTM

**Comment by wesm** [comment]
This is a serious enough problem that I think we should do a 0.3.1. What do you think?

**Comment by cpcloud** [comment]
Does it makes sense to follow up with a C++ test that can verify specific refcounts?

**Comment by wesm** [comment]
Sure, it would be a bit of work but a good idea. I put the test script here at least to eyeball whether there is a memory leak

**Comment by wesm** [comment]
see ARROW-1026

**Pull request closed without merging**
