### PR TITLE
WIP: [Release] Verify release-10.0.1-rc0

### PR DESCRIPTION
**Pull request by kou**
PR to verify Release Candidate

### CODE REVIEW

**Comment by kou** [comment]
@github-actions crossbow submit  --group verify-rc-source --param release=10.0.1 --param rc=0

**Comment by kou** [comment]
Revision: a6eabc2b890030578131aecc5e85900597d694a4

Submitted crossbow builds: [ursacomputing/crossbow @ release-10.0.1-rc0-0](https://github.com/ursacomputing/crossbow/branches/all?query=release-10.0.1-rc0-0)

|Task|Status|
|----|------|
|almalinux-8-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/3475281997/jobs/5809342447)|
|almalinux-8-arm64|[Travis CI](https://github.com/ursacomputing/crossbow/runs/9513494437)|
|almalinux-9-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/3475287093/jobs/5809353173)|
|almalinux-9-arm64|[Travis CI](https://github.com/ursacomputing/crossbow/runs/9513526649)|
|amazon-linux-2-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/3475294306/jobs/5809368702)|
|amazon-linux-2-arm64|[Travis CI](https://github.com/ursacomputing/crossbow/runs/9513515215)|
|centos-7-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/3475294549/jobs/5809369290)|
|centos-8-stream-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/3475293994/jobs/5809368166)|
|centos-8-stream-arm64|[Travis CI](https://github.com/ursacomputing/crossbow/runs/9513483102)|
|centos-9-stream-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/3475284733/jobs/5809348031)|
|centos-9-stream-arm64|[Travis CI](https://github.com/ursacomputing/crossbow/runs/9513493436)|
|conan-maximum|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/3475284912/jobs/5809348418)|
|conan-minimum|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/3475291043/jobs/5809361835)|
|debian-bookworm-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/3475287844/jobs/5809354728)|
|debian-bookworm-arm64|[Travis CI](https://github.com/ursacomputing/crossbow/runs/9513503005)|
|debian-bullseye-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/3475290051/jobs/5809359955)|
|debian-bullseye-arm64|[Travis CI](https://github.com/ursacomputing/crossbow/runs/9513505727)|
|java-jars|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/3475293229/jobs/5809366537)|
|nuget|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/3475281600/jobs/5809341563)|
|python-sdist|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/3475289816/jobs/5809359524)|
|r-binary-packages|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/3475288883/jobs/5809367514)|
|test-ubuntu-default-docs|[Azure](https://github.com/ursacomputing/crossbow/runs/9513520218)|
|ubuntu-bionic-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/3475292182/jobs/5809363986)|
|ubuntu-bionic-arm64|[Travis CI](https://github.com/ursacomputing/crossbow/runs/9513520937)|
|ubuntu-focal-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/3475293542/jobs/5809366988)|
|ubuntu-focal-arm64|[Travis CI](https://github.com/ursacomputing/crossbow/runs/9513485901)|
|ubuntu-jammy-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/3475280956/jobs/5809339650)|
|ubuntu-jammy-arm64|[Travis CI](https://github.com/ursacomputing/crossbow/runs/9513490199)|
|wheel-macos-big-sur-cp310-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/3475286735/jobs/5809352456)|
|wheel-macos-big-sur-cp311-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/3475290303/jobs/5809360598)|
|wheel-macos-big-sur-cp38-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/3475285367/jobs/5809349506)|
|wheel-macos-big-sur-cp39-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/3475289549/jobs/5809358910)|
|wheel-macos-mojave-cp310-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/3475286058/jobs/5809351034)|
|wheel-macos-mojave-cp311-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/3475292690/jobs/5809365159)|
|wheel-macos-mojave-cp37-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/3475281409/jobs/5809340962)|
|wheel-macos-mojave-cp38-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/3475284089/jobs/5809346783)|
|wheel-macos-mojave-cp39-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/3475280238/jobs/5809338205)|
|wheel-manylinux2014-cp310-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/3475279308/jobs/5809336227)|
|wheel-manylinux2014-cp310-arm64|[Travis CI](https://github.com/ursacomputing/crossbow/runs/9513500526)|
|wheel-manylinux2014-cp311-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/3475293750/jobs/5809367671)|
|wheel-manylinux2014-cp311-arm64|[Travis CI](https://github.com/ursacomputing/crossbow/runs/9513508684)|
|wheel-manylinux2014-cp37-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/3475282705/jobs/5809343994)|
|wheel-manylinux2014-cp37-arm64|[Travis CI](https://github.com/ursacomputing/crossbow/runs/9513507705)|
|wheel-manylinux2014-cp38-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/3475283633/jobs/5809345846)|
|wheel-manylinux2014-cp38-arm64|[Travis CI](https://github.com/ursacomputing/crossbow/runs/9513501562)|
|wheel-manylinux2014-cp39-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/3475289174/jobs/5809357814)|
|wheel-manylinux2014-cp39-arm64|[Travis CI](https://github.com/ursacomputing/crossbow/runs/9513491812)|
|wheel-windows-cp310-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/3475294948/jobs/5809370418)|
|wheel-windows-cp311-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/3475284348/jobs/5809347308)|
|wheel-windows-cp37-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/3475281189/jobs/5809340280)|
|wheel-windows-cp38-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/3475279702/jobs/5809337217)|
|wheel-windows-cp39-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/3475291602/jobs/5809362853)|

**Comment by kou** [comment]
@nealrichardson @paleolimbot @thisisnic [r-binary-packages](https://github.com/ursacomputing/crossbow/actions/runs/3475288883/jobs/5809504360) failed. Could you confirm this?

```text
Attaching package: ‘arrow’

The following object is masked from ‘package:utils’:

    timestamp

Error in parquet___arrow___ArrowReaderProperties__Make(isTRUE(use_threads)) : 
  Cannot call parquet___arrow___ArrowReaderProperties__Make(). See https://arrow.apache.org/docs/r/articles/install.html for help installing Arrow C++ libraries. 
Calls: read_parquet ... <Anonymous> -> parquet___arrow___ArrowReaderProperties__Make
Execution halted
```

Note that the same error is happen on master too: https://github.com/ursacomputing/crossbow/actions/runs/3468776645/jobs/5795178913

**Comment by thisisnic** [comment]
Weird, that error is triggered when the C++ library hasn't been built with enough functionality to support the R package, so I'd expect it to be something odd happening with the CI rather than a code change. I've re-triggered the job to make sure it's not some transient issue.

**Comment by thisisnic** [comment]
Hmm, failed again almost immediately: https://github.com/ursacomputing/crossbow/actions/runs/3475288883/jobs/5817793906 

I'm not sure what's going on there.

**Comment by assignUser** [comment]
@thisisnic seems to be an issue with the rocker image overriding the repo settings and forcefull installing the packages via apt and thus installing `r-cran-arrow` instead of the local package: https://github.com/ursacomputing/crossbow/actions/runs/3475288883/jobs/5817793906#step:13:321 

We might need/want to replace that image to stop that. Should not matter for this release though :+1:

**Comment by kou** [comment]
> We might need/want to replace that image to stop that. Should not matter for this release though +1

If the test is failed, R binaries aren't uploaded: https://github.com/ursacomputing/crossbow/actions/runs/3475288883/jobs/5809989647

Is it OK for R? If it's OK, I'll continue with the failure.

**Comment by eitsupi** [comment]
> seems to be an issue with the rocker image overriding the repo settings and forcefull installing the packages via apt and thus installing `r-cran-arrow` instead of the local package: [ursacomputing/crossbow/actions/runs/3475288883/jobs/5817793906#step:13:321](https://github.com/ursacomputing/crossbow/actions/runs/3475288883/jobs/5817793906#step:13:321)

This seems to be due to `rocker/r-buntu:22.04` configuring [bspm](https://github.com/Enchufa2/bspm).
`bspm` replaces the behavior of the `install.packages` function and sets apt to install the R packages.
I recommend that you simply stop using this image.

@eddelbuettel Did you push the image to DockerHub without updating the Dockerfile on GitHub?
It seems that bspm is indeed installed on `rocker/r-ubuntu@sha256:68f72a15f0e972556fb3dfd80b6394c34315722cb9b3e7a3a917a869152f7c40` even though the [Dockerfile](https://github.com/rocker-org/ubuntu-lts/blob/bbbd6dbdb83c9c8c2dd05a1c5cf847a5b488a8a2/jammy/Dockerfile) shows that bspm is not installed.

**Comment by eddelbuettel** [comment]
@eitsupi If so then only by accident.  But I did 'batch' update a few (layered) containers following the R 4.2.2 release and may inadvertendly (by doing this manually) crossed 'tags' and Dockerfiles.  Building and pushing a new image '22.04' (also as 'jammy') now.   And yes, you are correct: `bspm` should not be in this base layer but one above.

**Comment by kou** [comment]
@eitsupi Thanks for the information!

Do you know Docker images that can be replaced with https://github.com/apache/arrow/blob/master/dev/tasks/r/github.packages.yml#L247-L250 ?

**Comment by eitsupi** [comment]
> Do you know Docker images that can be replaced with [`master`/dev/tasks/r/github.packages.yml#L247-L250](https://github.com/apache/arrow/blob/master/dev/tasks/r/github.packages.yml?rgh-link-date=2022-11-16T23%3A29%3A20Z#L247-L250) ?

I think `rocker/r-ubuntu:22.04` can be replaced by `rstudio/r-base:jammy`.
As @eddelbuettel says, this change in behavior seems to have been an accident, so I think it can be left as is.
(However, I think the build system needs to be reviewed, as it is not good for this type of accident to happen.)

As for `rocker/r-ver`, it also should be possible to replace it with the image provided by rstudio (Posit).
https://github.com/rstudio/r-docker

However, the update mechanism of `rocker/r-ver` that I maintain has been fully automated on GitHub for over a year now, so I don't think an accident like this will happen.
https://github.com/rocker-org/rocker-versioned2

**Comment by eddelbuettel** [comment]
@kou "It's complicated."  @eitsupi and I are both behind Rocker, and these choices present two different and not exactly interchangeable options with different settings.  No in two characters: "no".  In more words: "it depends, they both have their (different) use cases".  I do all my CI with r-ubuntu / r-bspm / r2u as I want current toolchains and current CRAN easily.  YMMV.

**Comment by eddelbuettel** [comment]
> in behavior seems to have been an accident,

And if so, has been fixed.  Did you try the container I uploaded ~20 mins ago?

**Comment by assignUser** [comment]
>     And if so, has been fixed. Did you try the container I uploaded ~20 mins ago?

I'll re-run the job

**Comment by eitsupi** [comment]
@eddelbuettel

> And if so, has been fixed. Did you try the container I uploaded ~20 mins ago?

I pulled from DockerHub, but the digest does not seem to have changed.

image


> It seems that bspm is indeed installed on `rocker/r-ubuntu@sha256:68f72a15f0e972556fb3dfd80b6394c34315722cb9b3e7a3a917a869152f7c40` even though the [Dockerfile](https://github.com/rocker-org/ubuntu-lts/blob/bbbd6dbdb83c9c8c2dd05a1c5cf847a5b488a8a2/jammy/Dockerfile) shows that bspm is not installed.

**Comment by assignUser** [comment]
Indeed: https://github.com/ursacomputing/crossbow/actions/runs/3468776645/jobs/5828306179#step:13:321

**Comment by eddelbuettel** [comment]
My bad, in the rush I did 

```
 2157  docker build --no-cache -t rocker/r-ubuntu:jammy .
 2158  #docker build --no-cache -t rocker/r-ubuntu:jammy .
 2159  docker push rocker/r-ubuntu:jammy 
 2160  docker push rocker/r-ubuntu:22.04 
```

which replaced one but not both of these.  I skipped the build step for 22,04

Will ship and update 22.04 tag in a minute or two -- now building.

**Comment by eddelbuettel** [comment]
Rebuilt and repushed.  I used `--no-cache` on both hence different sha1 (which confused me for a second so I did a rebuild or two).  They should both work are identical, based on the same Dockerfile.

```sh
edd@rob:~/git/rocker-ubuntu-lts/jammy(master)$ docker images |head -3
REPOSITORY                           TAG             IMAGE ID       CREATED          SIZE
rocker/r-ubuntu                      jammy           7214e2c7ed54   7 minutes ago    743MB
rocker/r-ubuntu                      22.04           091427e0bcf7   11 minutes ago   743MB
edd@rob:~/git/rocker-ubuntu-lts/jammy(master)$ 
```

**Comment by kou** [comment]
@eitsupi Sorry! I misunderstood.

@eddelbuettel Thanks! It worked: https://github.com/ursacomputing/crossbow/actions/runs/3468776645/jobs/5828688028

**Comment by kou** [comment]
@github-actions crossbow submit  --group verify-rc-binaries --group verify-rc-wheels --param release=10.0.1 --param rc=0

**Pull request merged**
