### PR TITLE
ARROW-11021: [Rust] Update dependencies

### PR DESCRIPTION
**Pull request by Dandandan**
Updates dependencies bytes,. rustyline, rand and zstd.
Notably, the zstd upgrade includes some nice perf. improvements https://github.com/facebook/zstd/releases/tag/v1.4.7 .

I skipped updating `rand` in `arrow` for now, as it requires quite some changes in the benchmark code.

### CODE REVIEW

**Review by alamb — APPROVED** [review]
looks good to me -- thanks @Dandandan

**Comment by Dandandan** [comment]
Seems a release of `sqlparser` I did broke the CI build on master as it contained a breaking change. I've just yanked the version and will release `0.7` instead.

**Comment by alamb** [comment]
thanks @Dandandan  -- let me know if I can do anything to help

**Comment by Dandandan** [comment]
Thanks @alamb it should be fine with the next run, locally it runs as well as a recent CI build https://github.com/apache/arrow/pull/9035 is green

**Pull request closed without merging**
