### PR TITLE
WIP: [Release] Verify release-13.0.0-rc0

### PR DESCRIPTION
**Pull request by kou**
PR to verify Release Candidate

### CODE REVIEW

**Comment by kou** [comment]
@github-actions crossbow submit  --group verify-rc-source --param release=13.0.0 --param rc=0

**Comment by raulcd** [comment]
Revision: ac2d207611ce25c91fb9fc90d5eaff2933609660

Submitted crossbow builds: [ursacomputing/crossbow @ release-13.0.0-rc0-0](https://github.com/ursacomputing/crossbow/branches/all?query=release-13.0.0-rc0-0)

|Task|Status|
|----|------|
|almalinux-8-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc0-0-github-almalinux-8-amd64)|
|almalinux-8-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc0-0-github-almalinux-8-arm64)|
|almalinux-9-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc0-0-github-almalinux-9-amd64)|
|almalinux-9-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc0-0-github-almalinux-9-arm64)|
|amazon-linux-2023-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc0-0-github-amazon-linux-2023-amd64)|
|amazon-linux-2023-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc0-0-github-amazon-linux-2023-arm64)|
|centos-7-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc0-0-github-centos-7-amd64)|
|centos-8-stream-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc0-0-github-centos-8-stream-amd64)|
|centos-8-stream-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc0-0-github-centos-8-stream-arm64)|
|centos-9-stream-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc0-0-github-centos-9-stream-amd64)|
|centos-9-stream-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc0-0-github-centos-9-stream-arm64)|
|conan-maximum|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc0-0-github-conan-maximum)|
|conan-minimum|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc0-0-github-conan-minimum)|
|debian-bookworm-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc0-0-github-debian-bookworm-amd64)|
|debian-bookworm-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc0-0-github-debian-bookworm-arm64)|
|debian-bullseye-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc0-0-github-debian-bullseye-amd64)|
|debian-bullseye-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/5603618385/jobs/10250482470)|
|debian-trixie-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc0-0-github-debian-trixie-amd64)|
|debian-trixie-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc0-0-github-debian-trixie-arm64)|
|java-jars|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc0-0-github-java-jars)|
|nuget|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc0-0-github-nuget)|
|python-sdist|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/5603618671/jobs/10250483056)|
|r-binary-packages|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc0-0-github-r-binary-packages)|
|test-ubuntu-default-docs|[Azure](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc0-0-azure-test-ubuntu-default-docs)|
|ubuntu-focal-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc0-0-github-ubuntu-focal-amd64)|
|ubuntu-focal-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc0-0-github-ubuntu-focal-arm64)|
|ubuntu-jammy-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/5603618057/jobs/10250481795)|
|ubuntu-jammy-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc0-0-github-ubuntu-jammy-arm64)|
|ubuntu-lunar-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc0-0-github-ubuntu-lunar-amd64)|
|ubuntu-lunar-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/5603620876/jobs/10250488591)|
|wheel-clean|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc0-0-github-wheel-clean)|
|wheel-macos-big-sur-cp310-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc0-0-github-wheel-macos-big-sur-cp310-arm64)|
|wheel-macos-big-sur-cp311-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/5603619090/jobs/10250484035)|
|wheel-macos-big-sur-cp38-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc0-0-github-wheel-macos-big-sur-cp38-arm64)|
|wheel-macos-big-sur-cp39-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc0-0-github-wheel-macos-big-sur-cp39-arm64)|
|wheel-macos-mojave-cp310-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/5603621072/jobs/10250489109)|
|wheel-macos-mojave-cp311-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc0-0-github-wheel-macos-mojave-cp311-amd64)|
|wheel-macos-mojave-cp38-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc0-0-github-wheel-macos-mojave-cp38-amd64)|
|wheel-macos-mojave-cp39-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc0-0-github-wheel-macos-mojave-cp39-amd64)|
|wheel-manylinux-2-28-cp310-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc0-0-github-wheel-manylinux-2-28-cp310-amd64)|
|wheel-manylinux-2-28-cp310-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc0-0-github-wheel-manylinux-2-28-cp310-arm64)|
|wheel-manylinux-2-28-cp311-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc0-0-github-wheel-manylinux-2-28-cp311-amd64)|
|wheel-manylinux-2-28-cp311-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/5603617658/jobs/10250481006)|
|wheel-manylinux-2-28-cp38-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/5603625333/jobs/10250498182)|
|wheel-manylinux-2-28-cp38-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc0-0-github-wheel-manylinux-2-28-cp38-arm64)|
|wheel-manylinux-2-28-cp39-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/5603622673/jobs/10250492793)|
|wheel-manylinux-2-28-cp39-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc0-0-github-wheel-manylinux-2-28-cp39-arm64)|
|wheel-manylinux-2014-cp310-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/5603619314/jobs/10250484757)|
|wheel-manylinux-2014-cp310-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc0-0-github-wheel-manylinux-2014-cp310-arm64)|
|wheel-manylinux-2014-cp311-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc0-0-github-wheel-manylinux-2014-cp311-amd64)|
|wheel-manylinux-2014-cp311-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc0-0-github-wheel-manylinux-2014-cp311-arm64)|
|wheel-manylinux-2014-cp38-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc0-0-github-wheel-manylinux-2014-cp38-amd64)|
|wheel-manylinux-2014-cp38-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc0-0-github-wheel-manylinux-2014-cp38-arm64)|
|wheel-manylinux-2014-cp39-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc0-0-github-wheel-manylinux-2014-cp39-amd64)|
|wheel-manylinux-2014-cp39-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/5603619516/jobs/10250485300)|
|wheel-windows-cp310-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/5603617367/jobs/10250480356)|
|wheel-windows-cp311-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc0-0-github-wheel-windows-cp311-amd64)|
|wheel-windows-cp38-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/5603620623/jobs/10250487886)|
|wheel-windows-cp39-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/5603621853/jobs/10250491177)|

**Comment by raulcd** [comment]
@kou I think the [almalinux-8-arm64](https://github.com/ursacomputing/crossbow/actions/runs/5603619671/jobs/10250485740) package was successfully uploaded, I don't think I should re-trigger the job, do you think that's fine?

**Comment by kou** [comment]
You're correct. We don't need to re-trigger the almalinux-8-arm64 job. I don't know why `archery crossbow status --validate` failed even when all artifacts are "OK" but https://github.com/ursacomputing/crossbow/releases/tag/release-13.0.0-rc0-0-github-almalinux-8-arm64 has all artifacts.

But we need to re-run some jobs that aren't ran such as almalinux-9-arm64. (This may be a GitHub problem.)

I re-ran the test-ubuntu-default-docs job: https://github.com/ursacomputing/crossbow/runs/15185873603
Because it failed with a "no space left" error.

**Comment by raulcd** [comment]
Revision: ac2d207611ce25c91fb9fc90d5eaff2933609660

Submitted crossbow builds: [ursacomputing/crossbow @ release-13.0.0-rc0-1](https://github.com/ursacomputing/crossbow/branches/all?query=release-13.0.0-rc0-1)

|Task|Status|
|----|------|
|almalinux-9-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc0-1-github-almalinux-9-arm64)|
|centos-9-stream-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/5608813396/jobs/10261671759)|
|conan-maximum|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc0-1-github-conan-maximum)|
|debian-bullseye-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc0-1-github-debian-bullseye-amd64)|
|debian-trixie-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/5608813840/jobs/10261672884)|
|r-binary-packages|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc0-1-github-r-binary-packages)|
|wheel-manylinux-2-28-cp311-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/5608814428/jobs/10261674199)|
|wheel-manylinux-2-28-cp39-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/5608813620/jobs/10261672228)|
|wheel-manylinux-2014-cp310-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/5608813110/jobs/10261671177)|
|wheel-manylinux-2014-cp311-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/5608815043/jobs/10261675667)|
|wheel-manylinux-2014-cp38-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/5608814673/jobs/10261674804)|

**Comment by raulcd** [comment]
@github-actions crossbow submit --group verify-rc-source --param release=13.0.0 --param rc=0

**Comment by raulcd** [comment]
Revision: ac2d207611ce25c91fb9fc90d5eaff2933609660

Submitted crossbow builds: [ursacomputing/crossbow @ release-13.0.0-rc0-2](https://github.com/ursacomputing/crossbow/branches/all?query=release-13.0.0-rc0-2)

|Task|Status|
|----|------|
|preview-docs|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/5610257617/jobs/10264996579)|

**Comment by raulcd** [comment]
Revision: ac2d207611ce25c91fb9fc90d5eaff2933609660

Submitted crossbow builds: [ursacomputing/crossbow @ release-13.0.0-rc0-3](https://github.com/ursacomputing/crossbow/branches/all?query=release-13.0.0-rc0-3)

|Task|Status|
|----|------|
|preview-docs|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc0-3-github-preview-docs)|

**Comment by raulcd** [comment]
Revision: ac2d207611ce25c91fb9fc90d5eaff2933609660

Submitted crossbow builds: [ursacomputing/crossbow @ release-13.0.0-rc0-4](https://github.com/ursacomputing/crossbow/branches/all?query=release-13.0.0-rc0-4)

|Task|Status|
|----|------|
|preview-docs|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc0-4-github-preview-docs)|

**Comment by raulcd** [comment]
Revision: ac2d207611ce25c91fb9fc90d5eaff2933609660

Submitted crossbow builds: [ursacomputing/crossbow @ release-13.0.0-rc0-5](https://github.com/ursacomputing/crossbow/branches/all?query=release-13.0.0-rc0-5)

|Task|Status|
|----|------|
|preview-docs|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/5613215944/job/15208748864)|

**Comment by kou** [comment]
@github-actions crossbow submit  --group verify-rc-binaries --group verify-rc-wheels --param release=13.0.0 --param rc=0

**Comment by raulcd** [comment]
@ursabot please benchmark

**Comment by westonpace** [comment]
https://github.com/apache/arrow/pull/36813 may be a blocker

**Comment by raulcd** [comment]
I am closing this as we will be creating a new RC.

**Pull request closed without merging**
