### PR TITLE
WIP: [Release] Verify release-18.0.0-rc0

### PR DESCRIPTION
**Pull request by kou**
PR to verify Release Candidate

### CODE REVIEW

**Comment by kou** [comment]
@github-actions crossbow submit  --group verify-rc-source --param release=18.0.0 --param rc=0

**Comment by kou** [comment]
Revision: d0e7d07dfdcbf5382932292e512d7b9013b29cb6

Submitted crossbow builds: [ursacomputing/crossbow @ release-18.0.0-rc0-1](https://github.com/ursacomputing/crossbow/branches/all?query=release-18.0.0-rc0-1)

|Task|Status|
|----|------|
|almalinux-8-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11364842050/job/31611711323)|
|almalinux-8-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/tree/release-18.0.0-rc0-1-github-almalinux-8-arm64)|
|almalinux-9-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11364842024/job/31611711414)|
|almalinux-9-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11364841023/job/31611706620)|
|amazon-linux-2023-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11364841774/job/31611709783)|
|amazon-linux-2023-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11364841676/job/31611708635)|
|centos-7-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/tree/release-18.0.0-rc0-1-github-centos-7-amd64)|
|centos-8-stream-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11364841655/job/31611708421)|
|centos-8-stream-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11364842077/job/31611712038)|
|centos-9-stream-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11364842317/job/31611713859)|
|centos-9-stream-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11364842371/job/31611714865)|
|conan-maximum|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11364841019/job/31611706835)|
|conan-minimum|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11364842251/job/31611713434)|
|debian-bookworm-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11364842048/job/31611711388)|
|debian-bookworm-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/tree/release-18.0.0-rc0-1-github-debian-bookworm-arm64)|
|debian-trixie-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/tree/release-18.0.0-rc0-1-github-debian-trixie-amd64)|
|debian-trixie-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/tree/release-18.0.0-rc0-1-github-debian-trixie-arm64)|
|java-jars|[GitHub Actions](https://github.com/ursacomputing/crossbow/tree/release-18.0.0-rc0-1-github-java-jars)|
|matlab|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11364842086/job/31611715971)|
|nuget|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11364842118/job/31611712501)|
|python-sdist|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11364842414/job/31611715090)|
|r-binary-packages|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11364841882/job/31611732011)|
|test-debian-12-docs|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11364841192/job/31611707243)|
|ubuntu-focal-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/tree/release-18.0.0-rc0-1-github-ubuntu-focal-amd64)|
|ubuntu-focal-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11364842066/job/31611711774)|
|ubuntu-jammy-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11364842419/job/31611715003)|
|ubuntu-jammy-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11364842106/job/31611712422)|
|ubuntu-noble-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11364841831/job/31611709758)|
|ubuntu-noble-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11364841275/job/31611707510)|
|wheel-macos-monterey-cp310-cp310-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11364842277/job/31611713791)|
|wheel-macos-monterey-cp310-cp310-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11364841788/job/31611709335)|
|wheel-macos-monterey-cp311-cp311-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11364842428/job/31611715115)|
|wheel-macos-monterey-cp311-cp311-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/tree/release-18.0.0-rc0-1-github-wheel-macos-monterey-cp311-cp311-arm64)|
|wheel-macos-monterey-cp312-cp312-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11364842228/job/31611713387)|
|wheel-macos-monterey-cp312-cp312-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11364842215/job/31611713438)|
|wheel-macos-monterey-cp313-cp313-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11364842270/job/31611713624)|
|wheel-macos-monterey-cp313-cp313-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/tree/release-18.0.0-rc0-1-github-wheel-macos-monterey-cp313-cp313-arm64)|
|wheel-macos-monterey-cp313-cp313t-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11364841440/job/31611707941)|
|wheel-macos-monterey-cp313-cp313t-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11364841047/job/31611706552)|
|wheel-macos-monterey-cp39-cp39-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11364842353/job/31611714370)|
|wheel-macos-monterey-cp39-cp39-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11364841609/job/31611708350)|
|wheel-manylinux-2-28-cp310-cp310-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11364842365/job/31611714566)|
|wheel-manylinux-2-28-cp310-cp310-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11364841927/job/31611710538)|
|wheel-manylinux-2-28-cp311-cp311-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11364841711/job/31611709302)|
|wheel-manylinux-2-28-cp311-cp311-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11364841570/job/31611708159)|
|wheel-manylinux-2-28-cp312-cp312-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11364842035/job/31611711091)|
|wheel-manylinux-2-28-cp312-cp312-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11364841793/job/31611709510)|
|wheel-manylinux-2-28-cp313-cp313-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11364841691/job/31611708716)|
|wheel-manylinux-2-28-cp313-cp313-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11364841205/job/31611707255)|
|wheel-manylinux-2-28-cp313-cp313t-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11364841398/job/31611707899)|
|wheel-manylinux-2-28-cp313-cp313t-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11364842382/job/31611714882)|
|wheel-manylinux-2-28-cp39-cp39-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11364842198/job/31611712844)|
|wheel-manylinux-2-28-cp39-cp39-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11364841296/job/31611707579)|
|wheel-manylinux-2014-cp310-cp310-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11364841901/job/31611710133)|
|wheel-manylinux-2014-cp310-cp310-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11364842524/job/31611756828)|
|wheel-manylinux-2014-cp311-cp311-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11364842040/job/31611711379)|
|wheel-manylinux-2014-cp311-cp311-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11364842332/job/31611714275)|
|wheel-manylinux-2014-cp312-cp312-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11364842169/job/31611713195)|
|wheel-manylinux-2014-cp312-cp312-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11364841864/job/31611710058)|
|wheel-manylinux-2014-cp313-cp313-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11364842027/job/31611711072)|
|wheel-manylinux-2014-cp313-cp313-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11364841016/job/31611706550)|
|wheel-manylinux-2014-cp313-cp313t-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11364842150/job/31611712713)|
|wheel-manylinux-2014-cp313-cp313t-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11364841944/job/31611710549)|
|wheel-manylinux-2014-cp39-cp39-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11364841792/job/31611709675)|
|wheel-manylinux-2014-cp39-cp39-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11364842208/job/31611712957)|
|wheel-windows-cp310-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11364842291/job/31611714027)|
|wheel-windows-cp311-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11364841055/job/31611706494)|
|wheel-windows-cp312-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11364842180/job/31611712801)|
|wheel-windows-cp313-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11364842485/job/31611756832)|
|wheel-windows-cp39-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11364842225/job/31611713187)|

**Comment by kou** [comment]
@github-actions crossbow submit  --group verify-rc-binaries --group verify-rc-wheels --param release=18.0.0 --param rc=0

**Comment by raulcd** [comment]
The Linux and macOS wheels errors are tracked here:
- https://github.com/apache/arrow/issues/44459

The Windows one is different and is tracked here:
- https://github.com/apache/arrow/issues/44461

**Pull request merged**
