### PR TITLE
ARROW-8225: [Rust] Rust Arrow IPC reader must respect continuation markers.

### PR DESCRIPTION
**Pull request by maxburke**
A continuation marker (value of 0xffffffff) in a message size block is
used to align the next block to an 8-byte boundary. This value needs to
be skipped over if encountered.

### CODE REVIEW

**Review by paddyhoran — APPROVED** [review]
LGTM pending CI (looks like you have some lints to fix)

**Comment by maxburke** [comment]
Saw those; not sure why they came up because I hadn't changed those files, perhaps they were from another merge? Anyways, working to fix!

**Comment by paddyhoran** [comment]
Yea, it happens.  I guess `fmt` was updated in CI or something.  Thanks @maxburke

**Comment by maxburke** [comment]
@paddyhoran All clear!

**Comment by wesm** [comment]
You've got a conflict from the testing submodule. I'm unable to edit your branch to fix it -- I pushed a fixed branch here

https://github.com/wesm/arrow/tree/rust_continuation

**Comment by maxburke** [comment]
Right, sorry, fixed.

**Comment by kou** [comment]
+1
CI is green. I'll merge this.

**Pull request closed without merging**
