### PR TITLE
ARROW-5333: [C++] Clamp build option summary width to 90

### PR DESCRIPTION
**Pull request by bkietz**
@pitrou how does this look:

```
-- Compile and link options:
-- 
--   ARROW_CXXFLAGS                                                        [default=""] ""
--       Compiler flags to append when compiling Arrow
-- 
--   ARROW_BUILD_STATIC                                                   [default=ON] OFF
--       Build static libraries
-- 
--   ARROW_BUILD_SHARED                                                   [default=ON] OFF
--       Build shared libraries
-- 
--   ARROW_NO_DEPRECATED_API                                             [default=OFF] OFF
--       Exclude deprecated APIs from build
```

I don't *think* I touched anything but formatting, but... This is a draft because I'm getting an error:
```
CMake Error: INSTALL(EXPORT) given unknown export "arrow_targets"
```

### CODE REVIEW

**Comment by kou** [comment]
Where can I see the full log message for the `arrow_targets` error?

**Comment by bkietz** [comment]
@kou I saw it locally and expected to see it in at least one CI job but it's nowhere. I'll rebase and retry locally. If I see it again I'll paste the log in a comment

**Comment by bkietz** [comment]
oh, found one error: I was attempting to test with 
```shell-session
~/arrow/cpp/tmp-build $ cmake .. # ARROW_BUILD_TESTS etc off by default
```
which is an error as it results in no concrete build targets. We should maybe add a more helpful warning about that

**Comment by bkietz** [comment]
Failure seems unrelated: https://github.com/apache/arrow/pull/5844/checks?check_run_id=342740047#step:5:1552

**Review by pitrou — APPROVED** [review]
+1. Thank you @bkietz !

**Pull request closed without merging**
