### PR TITLE
ARROW-12086: [C++] Fix environment variables for bzip2, utf8proc URLs

### PR DESCRIPTION
**Pull request by pitrou**
This should fix offline builds after having run `./thirdparty/download_dependencies.sh`.

### CODE REVIEW

**Comment by nealrichardson** [comment]
Should/can we add a crossbow job for this--something that runs the download script, blocks some connection/ports, and tests that the build succeeds?

**Comment by pitrou** [comment]
I wonder if that can be done reliably. Especially as the job needs to communicate with the CI provider?

**Review by kou — APPROVED** [review]
+1

We'll be able to simulate offline environment by removing `/etc/resolv.conf` in Docker container.

**Comment by nealrichardson** [comment]
I made ARROW-12095 about adding a nightly job for this.

**Pull request closed without merging**
