### PR TITLE
GH-40700: [Go][CI] Update go.sum dependencies

### PR DESCRIPTION
**Pull request by raulcd**
### Are there any user-facing changes?

* GitHub Issue: #40700

### CODE REVIEW

**Comment by raulcd** [comment]
@github-actions crossbow submit -g go

**Comment by raulcd** [comment]
ok, I tried. I did run `go mod tidy` locally but it still fails. @zeroshade any idea what might be the problem with the nightly job failure for `test-debian-12-go-1.21`?

**Comment by zeroshade** [comment]
I'm not at my computer at the moment, but try outright deleting the go.sum file and then running go mod tidy to regenerate it.

**Comment by raulcd** [comment]
@github-actions crossbow submit -g go

**Comment by raulcd** [comment]
@github-actions crossbow submit -g go

**Comment by raulcd** [comment]
> try outright deleting the go.sum file and then running go mod tidy to regenerate it.

It doesn't seem to work. It is not urgent, take a look whenever you have some time! @zeroshade

**Pull request closed without merging**
