### PR TITLE
PARQUET-1586: [C++] Add --dump options to parquet-reader tool to dump def/rep levels

### PR DESCRIPTION
**Pull request by rip-nsk**

### CODE REVIEW

**Review by xhochy — APPROVED** [review]
+1, LGTM

**Comment by wesm** [comment]
The unit test that was added here appears to have trailing whitespace at line ends, which makes things very difficult in text editors that are configured to strip trailing whitespace. I will try to fix

**Comment by wesm** [comment]
I'm going to disable that particular output check and open a JIRA. Having trailing whitespace in files is not a good idea

**Comment by rip-nsk** [comment]
> I'm going to disable that particular output check and open a JIRA. Having trailing whitespace in files is not a good idea

I'll fix this as part of ARROW-5433 by adding column separator '|'

**Pull request closed without merging**
