### PR TITLE
ARROW-18318: [Python] Expose Scalar.validate()

### PR DESCRIPTION
**Pull request by buaazhwb**

### CODE REVIEW

**Review by pitrou — APPROVED** [review]
Thanks @buaazhwb ! I rebased and will merge if CI passes.

**Comment by buaazhwb** [comment]
@pitrou  Not yet. The public registeration has been disabled. Are there any doc for creating a jira account？

**Comment by pitrou** [comment]
@buaazhwb I should be able to create one for you. Do I just use the same ID and e-mail address as for Github?

Note that in the future, we will only be using Github issues, so please don't create any new JIRA issues.

**Comment by buaazhwb** [comment]
@pitrou OK. Thanks for your help!

**Pull request merged**
