### PR TITLE
ARROW-15831: [Java] Upgrade Flight dependencies

### PR DESCRIPTION
**Pull request by BryanCutler**
This upgrades Flight dependencies for grpc -> 1.44. , netty -> 4.1.72.Final and protobuf -> 3.19.4.

### CODE REVIEW

**Comment by BryanCutler** [comment]
Looks like this is causing a failure, I'll have to look into it
```
Warning:  Used undeclared dependencies found:
Warning:     io.netty:netty-transport-classes-epoll:jar:4.1.72.Final:compile
Warning:  Unused declared dependencies found:
Warning:     io.netty:netty-transport-native-epoll:jar:linux-x86_64:4.1.72.Final:compile
```

**Review by lidavidm — APPROVED** [review]
LGTM.

epoll shouldn't be required for Flight/gRPC, it just enables a different implementation under the hood.

**Comment by BryanCutler** [comment]
Thanks @lidavidm !

**Comment by anthonylouisbsb** [comment]
@BryanCutler @lidavidm could you take a look on [this ticket](https://issues.apache.org/jira/browse/ARROW-15954) when you be able to?

I think that PR broke one of the nigthly builds.

**Comment by lidavidm** [comment]
Thanks, I believe this is already tracked at ARROW-15889

**Pull request closed without merging**
