### PR TITLE
ARROW-997: [Java] Implementing transferPair for FixedSizeListVector

### PR DESCRIPTION
**Pull request by elahrvivaz**

### CODE REVIEW

**Comment by wesm** [comment]
The OS X build failure was unrelated. @julienledem can you take a look? thanks

**Review by julienledem — COMMENTED** [review]
This looks OK to me.
@StevenMPhillips can you take a look?

**Comment by wesm** [comment]
@StevenMPhillips @julienledem can you review today so we can get this into the 0.4 release? Thanks

**Comment by StevenMPhillips** [comment]
LGTM

**Pull request closed without merging**
