### PR TITLE
ARROW-13992: [R] CI jobs should use the latest version of rcmdcheck

### PR DESCRIPTION
**Pull request by thisisnic**

### CODE REVIEW

**Comment by thisisnic** [comment]
@github-actions crossbow submit *

**Comment by jonkeane** [comment]
I took a look at a few of the errors, and they mostly seem to be in installing dependencies. I wonder if we should add in `GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}` (as recommended by r-lib/actions: https://github.com/r-lib/actions/blob/60e594624f0d630cdbf6bc9deee7b0771f77e0f3/.github/workflows/check-release.yaml#L15) to the GHA jobs at least to reduce those from happening. This is scope creep from this specific change, of course.

**Comment by thisisnic** [comment]
@jonkeane I wanted to add the relevant PAT to the task described in `dev/tasks/r/github.macos.autobrew.yml ` (it was failing at installed dev rcmdcheck without it), but (see the last but one PR), I did it wrong.  Given that the params that are passed in at the top level get printed out, I was a bit hesitant to try again and risk printing out the PAT.  Any idea how I could go about it without messing things up?

**Comment by jonkeane** [comment]
We should confirm this with @kszucs to make sure, but in my understanding they will be masked (and they are limited to the lifetime of the job anyway, though I only learned that by reading https://docs.github.com/en/actions/reference/authentication-in-a-workflow again just now!).

We already have at least one example of [using something like this](https://github.com/apache/arrow/blob/master/dev/tasks/python-wheels/github.osx.arm64.yml#L155) which [obfuscates it appropriately](https://github.com/ursacomputing/crossbow/runs/3648587031#step:11:31).

We could consider removing `printenv` (notably in [`ci/scripts/r_test.sh`](https://github.com/apache/arrow/blob/556c14c7a520163aa6dbfe351ba22207c7ce74a9/ci/scripts/r_test.sh#L27) ) but also [in two more places as well](https://github.com/apache/arrow/search?q=printenv) to be extra extra careful. (Maybe replace that with a macro that lists a few of the vars we end up caring about like `ARROW_R_DEV`?

**Comment by thisisnic** [comment]
Closing this ticket as the change is now in the released version of rcmdcheck

**Pull request closed without merging**
