### PR TITLE
PARQUET-1463: [C++] Utilize common hashing machinery for dictionary encoding

### PR DESCRIPTION
**Pull request by pitrou**

### CODE REVIEW

**Comment by pitrou** [comment]
A crude micro-benchmark doesn't show any significant performance difference. I don't know if we have more significant benchmarks.

**Comment by wesm** [comment]
cc @xhochy @majetideepak 

@pitrou thanks so much for doing this. I will review the code and also run some before/after write perf benchmarks to kick the tires

**Review by xhochy — COMMENTED** [review]
This is LGTM. In the absence of benchmarks I often use http://www.nyc.gov/html/tlc/html/about/trip_record_data.shtml as the basis for real world data in performance testing.

**Comment by pitrou** [comment]
Ok, I tested on a subset of taxi data. It's a bit faster with this PR. Actually, dictionary encoding does not seem to slow things down (anymore?):
```python
>>> %time table = csv.read_csv("yellow.csv")                                                                                                                      
CPU times: user 1.11 s, sys: 309 ms, total: 1.41 s
Wall time: 105 ms
>>> table                                                                                                                                                         
pyarrow.Table
VendorID: int64
tpep_pickup_datetime: timestamp[s]
tpep_dropoff_datetime: timestamp[s]
passenger_count: int64
trip_distance: double
RatecodeID: int64
store_and_fwd_flag: string
PULocationID: int64
DOLocationID: int64
payment_type: int64
fare_amount: double
extra: double
mta_tax: double
tip_amount: double
tolls_amount: double
improvement_surcharge: double
total_amount: double
>>> table.num_rows                                                                                                                                                
999998
>>> %time pq.write_table(table, pa.BufferOutputStream(), coerce_timestamps='ms', use_dictionary=True)                                                             
CPU times: user 337 ms, sys: 3 ms, total: 340 ms
Wall time: 339 ms
>>> %time pq.write_table(table, pa.BufferOutputStream(), coerce_timestamps='ms', use_dictionary=False)                                                            
CPU times: user 334 ms, sys: 11.4 ms, total: 345 ms
Wall time: 345 ms
```

(note how reading the data from CSV is faster in wall-clock time than saving it to Parquet ;-))

**Comment by xhochy** [comment]
Thanks @pitrou for the optimization. The Parquet write path is something we have never looked into performance optimization as it was already quite fast in its basic form. So there's probably still some low hanging fruit.

**Review by wesm — APPROVED** [review]
+1. I'll run some ad hoc perf tests when I can out of my own curiosity and post results here

**Pull request closed without merging**
