### PR TITLE
ARROW-6404: [C++] Always use release build type by default

### PR DESCRIPTION
**Pull request by kou**

### CODE REVIEW

**Comment by kou** [comment]
@bkietz Do you remember why `NOT GENERATOR_IS_MULTI_CONFIG` is added in https://github.com/apache/arrow/commit/248f2ce87daa50c752d66e816deaad1e4900416e ?
`GENERATOR_IS_MULTI_CONFIG` is true for Visual Studio. So `NOT GENERATOR_IS_MULTI_CONFIG` is false for Visual Studio.

**Comment by wesm** [comment]
We had a problem where DEBUG build type was being set here. See git blame for the relevant patch

**Comment by wesm** [comment]
See https://github.com/apache/arrow/commit/248f2ce87daa50c752d66e816deaad1e4900416e

and https://issues.apache.org/jira/browse/ARROW-5414

the issue of DEBUG build being set was only occurring for "Ninja" generator type on Windows.

**Comment by bkietz** [comment]
@kou for multi config generators [this option is not used](https://github.com/Kitware/CMake/blob/9860b4c5e8756cb58c4cdfc27a14194f823aa0ab/Help/manual/cmake-buildsystem.7.rst#user-content-id154)

>  The buildsystem for the IDEs such as Visual Studio and Xcode are generated independent of the build-configuration, and the actual build configuration is not known until build-time.

**Comment by kou** [comment]
@wesm @bkietz Thanks for the information.
I misunderstood that 248f2ce tried to fix all generators for Windows. I understood that the commit tried to fix only "Ninja" generator for Windows.

Then we should replace all `if("${UPPERCASE_BUILD_TYPE}" STREQUAL "RELEASE")` related codes with `${CONFIGURATION}_RELEASE` and so on.

I'll work on this but it may take some time.

**Comment by wesm** [comment]
I just rebased this. In master I think the Ninja build issue is fixed. Do we want to set flags to remove the various STREQUAL things?

**Comment by kou** [comment]
> Do we want to set flags to remove the various STREQUAL things?

Yes. I'll work on this.

**Comment by wesm** [comment]
Is this still a problem? It seems like the immediate issues have been resolved

**Comment by wesm** [comment]
Oops did not mean to close

**Comment by kou** [comment]
There is no immediate issue.
There is an advanced issue: We can't use multi config feature with Visual Studio build.

If you don't like opened pull request, we can close this for now.
I'll recreate a pull request when I work on.

**Comment by emkornfield** [comment]
@kou it looks like this needs a rebase?

**Comment by kou** [comment]
We need to rebase and use another approach.
It seems that opened pull request isn't liked, I close this for now. I'll reopen or create a new pull request when I can work on this.

**Pull request closed without merging**
