### PR TITLE
 ARROW-193: typos "int his" fix to "in this"

### PR DESCRIPTION
**Pull request by lfzCarlosC**
For the instruction , typos "int his" is fixed to "in this"

### CODE REVIEW

**Comment by wesm** [comment]
Can you create a JIRA and prefix the PR title with `ARROW-XXX:` where XXX is the JIRA number?

**Comment by lfzCarlosC** [comment]
ok. already done

**Comment by wesm** [comment]
+1

**Comment by wesm** [comment]
I had to cherry-pick manually (there was a leading space in the PR title), can you please close the PR? Thank you

**Comment by wesm** [comment]
Can you close the PR? Thank you

**Comment by lfzCarlosC** [comment]
sorry,just not be so familiar with this. Already closed.

Fangzhou

**Pull request closed without merging**
