### PR TITLE
GH-35186: [CI][C++] Improve GoogleTest detection on Windows + vcpkg

### LINKED ISSUE #35186: [CI][C++] VCPKG nightly build fails due to GTestAlt not found
### Describe the bug, including details regarding any error messages, version, and platform.

The job for [test-build-vcpkg-win](https://github.com/ursacomputing/crossbow/actions/runs/4716183723/jobs/8363679418) has been failing for the last days on our nightly jobs. With the following error:
```
 CMake Warning (dev) at C:/Program Files/CMake/share/cmake-3.26/Modules/ExternalProject.cmake:3091 (message):
  The DOWNLOAD_EXTRACT_TIMESTAMP option was not given and policy CMP0135 is
  not set.  The policy's OLD behavior will be used.  When using a URL
  download, the timestamps of extracted files should preferably be that of
  the time of extraction, otherwise code that depends on the extracted
  contents might not be rebuilt if the URL changes.  The OLD behavior
  preserves the timestamps from the archive instead, but this is usually not
  what you want.  Update your project to the NEW behavior or specify the
  DOWNLOAD_EXTRACT_TIMESTAMP option with a value of true to avoid this
  robustness issue.
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.26/Modules/ExternalProject.cmake:4208 (_ep_add_download_command)
  cmake_modules/ThirdpartyToolchain.cmake:2052 (externalproject_add)
  CMakeLists.txt:506 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found GTest: D:/a/crossbow/crossbow/arrow/cpp/vcpkg_installed/x64-windows/share/GTest/GTestConfig.cmake (found suitable version "1.10.0", minimum required is "1.10.0")  
CMake Error at C:/Program Files/CMake/share/cmake-3.26/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
-- GTest can't be used with C++17. Use -DGTest_SOURCE=BUNDLED.
-- Configuring incomplete, errors occurred!
  Could NOT find GTestAlt (missing: GTestAlt_CXX_STANDARD_AVAILABLE)
  (Required is at least version "1.10.0")
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.26/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  cmake_modules/FindGTestAlt.cmake:60 (find_package_handle_standard_args)
  C:/vcpkg/scripts/buildsystems/vcpkg.cmake:852 (_find_package)
  cmake_modules/ThirdpartyToolchain.cmake:285 (find_package)
  cmake_modules/ThirdpartyToolchain.cmake:2223 (resolve_dependency)
  CMakeLists.txt:506 (include)
```

This is also failing on the maintenance branch for 12.0.0 so I think this should be fixed before the RC is created.

### Component(s)

C++, Continuous Integration

### PR DESCRIPTION
**Pull request by kou**
### Rationale for this change

We must be able to use GoogleTest installed by vcpkg on Windows.

### What changes are included in this PR?

Add missing `-DCMAKE_CXX_STANDARD`.

### Are these changes tested?

Yes.

### Are there any user-facing changes?

Yes.
* Closes: #35186

### CODE REVIEW

**Comment by kou** [comment]
@github-actions crossbow submit test-build-vcpkg-win

**Comment by kou** [comment]
@github-actions crossbow submit test-build-vcpkg-win

**Comment by kou** [comment]
@github-actions crossbow submit test-build-vcpkg-win

**Comment by kou** [comment]
@github-actions crossbow submit test-build-vcpkg-win

**Comment by kou** [comment]
+1

**Review by raulcd — APPROVED** [review]
Thanks @kou

**Pull request merged**
