### PR TITLE
GH-36920: [Java][Docs] Add ARROW_JSON var to maven build profile

### LINKED ISSUE #36920: [Java][Docs] ARROW_JSON var not included in maven build profile
### Describe the bug, including details regarding any error messages, version, and platform.

JSON support was recently added to the dataset module. The current maven profiles don't set the var to enable it, which causes tests to fail:

```
[ERROR] Errors:
[ERROR]   TestFileSystemDataset.testBaseJsonRead:443 » Runtime illegal file format id: 4
[INFO]
[ERROR] Tests run: 29, Failures: 0, Errors: 1, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Apache Arrow Java Root POM 13.0.0-SNAPSHOT:
[INFO]
[INFO] Apache Arrow Java Root POM ......................... SUCCESS [  8.771 s]
...
[INFO] Arrow Java C Data Interface ........................ SUCCESS [  7.379 s]
[INFO] Arrow Java Dataset ................................. FAILURE [  8.457 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
```

### Component(s)

Java

### PR DESCRIPTION
**Pull request by danepitkin**
### Rationale for this change

JSON support in the datasets module was recently introduced. Update the maven build profile and build documentation to reflect this. Similar to https://github.com/apache/arrow/pull/36899

### What changes are included in this PR?

* update maven build profile
* update build docs

### Are these changes tested?

Yes, tested locally on M1 Mac.

### Are there any user-facing changes?

No
* Closes: #36920

### CODE REVIEW

**Comment by danepitkin** [comment]
@github-actions crossbow submit java

**Comment by danepitkin** [comment]
@github-actions crossbow submit _java_

**Comment by danepitkin** [comment]
@github-actions crossbow submit java-jars

**Review by kou — APPROVED** [review]
+1

**Pull request merged**
