### PR TITLE
GH-43378: [Java][CI] Don't configure multithreading when building javadocs

### PR DESCRIPTION
**Pull request by danepitkin**
### Rationale for this change

Apparently some maven plugins are not thread safe and started throwing errors in the `test-debian-12-docs` CI job when building javadocs.

### What changes are included in this PR?

* Remove multithreading config when building javadocs

### Are these changes tested?

CI

### Are there any user-facing changes?

No
* GitHub Issue: #43378

### CODE REVIEW

**Comment by danepitkin** [comment]
@github-actions crossbow submit test-debian-12-docs

**Comment by danepitkin** [comment]
@github-actions crossbow submit test-debian-12-docs

**Comment by danepitkin** [comment]
@github-actions crossbow submit test-debian-12-docs

**Comment by danepitkin** [comment]
@github-actions crossbow submit test-debian-12-docs

**Comment by danepitkin** [comment]
@github-actions crossbow submit test-debian-12-docs

**Comment by danepitkin** [comment]
@github-actions crossbow submit test-debian-12-docs

**Comment by danepitkin** [comment]
@github-actions crossbow submit test-debian-12-docs

**Review by kou — APPROVED** [review]
+1

Great!

**Comment by vibhatha** [comment]
Thanks @danepitkin for fixing this.

**Comment by laurentgo** [comment]
maven-site-plugin is supposedly thread-safe according to https://issues.apache.org/jira/browse/MSITE-873. Should we report the issue upstream?

**Comment by danepitkin** [comment]
> maven-site-plugin is supposedly thread-safe according to https://issues.apache.org/jira/browse/MSITE-873. Should we report the issue upstream?

Good point. Should we first try upgrading to latest first? We are using maven-site-plugin v3.12.1 (defined in the parent apache pom I believe), but latest is v4.0.0-M9.

**Comment by danepitkin** [comment]
I'm also not able to reproduce it locally on a different platform (macos). I wonder if it could be that we have an incompatible version matrix configured between the different maven plugins that specifically plagues our CI?

**Comment by danepitkin** [comment]
Actually, I do see this warning from this CI job. 

```
Warning:  *****************************************************************
Warning:  * Your build is requesting parallel execution, but this         *
Warning:  * project contains the following plugin(s) that have goals not  *
Warning:  * marked as thread-safe to support parallel execution.          *
Warning:  * While this /may/ work fine, please look for plugin updates    *
Warning:  * and/or request plugins be made thread-safe.                   *
Warning:  * If reporting an issue, report it against the plugin in        *
Warning:  * question, not against Apache Maven.                           *
Warning:  *****************************************************************
Warning:  The following plugins are not marked as thread-safe in Arrow Bill of Materials:
Warning:    org.apache.maven.plugins:maven-site-plugin:3.12.1
Warning:  
Warning:  Enable debug to see precisely which goals are not marked as thread-safe.
Warning:  *****************************************************************
```

https://github.com/ursacomputing/crossbow/actions/runs/10394740527/job/28785211517

**Comment by danepitkin** [comment]
Ah, this was fixed in v3.20 and v4.X according to the Jira ticket https://issues.apache.org/jira/browse/MSITE-873

**Comment by danepitkin** [comment]
According to the Jira ticket (https://issues.apache.org/jira/browse/MSITE-873) this was fixed in 3.20+. We just need to upgrade if we want to use multithreading. The best approach is probably to use a later apache parent pom, which does use a later version.

**Pull request merged**
