### PR TITLE
ARROW-5452: [R] Add API documentation website (pkgdown)

### PR DESCRIPTION
**Pull request by nealrichardson**
I've deployed a test page at https://enpiar.com/arrow-r-site/ (source: https://github.com/nealrichardson/arrow-r-site) containing the result of building the pkgdown site. 

There's a lot of work to be done to flesh out the docs to make them actually useful, but this patch gives us the foundation and makes very visible where the docs are inadequate.

One thing I'd like to do before finishing this patch is add the necessary scripts etc. to `/dev/gen_apidocs/` so that the R docs are built alongside the js and java docs.

### CODE REVIEW

**Comment by xhochy** [comment]
One note here `gen_apidocs` is actually a bit outdated and we have moved most of this into `docker-compose build/run docs` but not fully. But I guess from the current site, we should either extend the `docs` target or add a new container that builds `apidocs` for R in the main `docker-compose.yml`.

**Comment by nealrichardson** [comment]
Sorry @xhochy if I'm being dense, but where exactly would you like me to put the build script logic? Are there docs that I should update while I'm in there?

**Comment by nealrichardson** [comment]
I propose that we merge this now and defer the build script work to https://issues.apache.org/jira/browse/ARROW-5497. There's more documentation cleanup I'd like to do and I'd rather not keep dealing with merge conflicts. As is, this patch does not affect any current build artifacts, it just adds the config necessary to build the documentation site whenever we choose to.

**Review by romainfrancois — APPROVED** [review]
That looks fine for an initial setup. Should it have something like https://github.com/tidyverse/dplyr/blob/master/.travis.yml#L20 to build the pkgdown on travis and deploy continuously ?

**Comment by xhochy** [comment]
@nealrichardson Have a look at https://github.com/apache/arrow/blob/master/docs/Dockerfile and https://github.com/apache/arrow/blob/master/ci/docker_build_sphinx.sh Add that and a docs-r entry in the main `docker-compose.yml` should be sufficient to get it running in the docker setup. But actually I would rather like to see that we also add the R build to the above linked files.

**Pull request closed without merging**
