### PR TITLE
ARROW-8573: [Rust] Upgrade Rust to 1.44 nightly

### PR DESCRIPTION
**Pull request by andygrove**
Now that Rust 1.43.0 is released, we should upgrade to 1.44 nightly. It looks like there were changes in rustfmt rules.

### CODE REVIEW

**Comment by nevi-me** [comment]
@paddyhoran we might have to try a different nightly, as sometimes a day's version might have no rustfmt. The change I made in that PR installs a nightly version, I don't know how to make GHA install a stable version of rustfmt

**Comment by markhildreth** [comment]
@andygrove I think there is going to be more to this than this PR. The "nightly-2019-11-14" string [can be found in a few places](https://github.com/apache/arrow/search?q=nightly-2019-11-14&unscoped_q=nightly-2019-11-14), including some of the build scripts (notice that the workflows run for this PR are still called "2019-11-14").

@nevi-me @paddyhoran The problem with this error seems to be that the change was only made in rust-toolchain. As a result, the GHA workflows will still build a Windows environment with a nightly-2019-11-14 toolchain. When cargo attempts to build, it will notice that the toolchain is out of date with the `rust-toolchain` file, and attempt to pull the new toolchain on-the-fly. However, it doesn't pull `rust fmt` when this occurs.

```
installed toolchains
--------------------

stable-x86_64-pc-windows-msvc
nightly-2019-11-14-x86_64-pc-windows-msvc

active toolchain
----------------

nightly-2019-11-14-x86_64-pc-windows-msvc (directory override for '\\?\D:\a\arrow\arrow')
rustc 1.41.0-nightly (ded5ee001 2019-11-13)

+ mkdir -p /d/a/arrow/arrow/build/rust
+ pushd /d/a/arrow/arrow/rust
/d/a/arrow/arrow/rust /d/a/arrow/arrow
+ RUSTFLAGS='-D warnings'
+ cargo build --all-targets
info: syncing channel updates for 'nightly-2020-04-22-x86_64-pc-windows-msvc'
info: latest update on 2020-04-22, rust version 1.44.0-nightly (45d050cde 2020-04-21)
info: downloading component 'cargo'
info: downloading component 'rust-std'
info: downloading component 'rustc'
info: installing component 'cargo'
info: installing component 'rust-std'
info: installing component 'rustc'
```

**Comment by nevi-me** [comment]
@andygrove this failure (https://git.data-engine.co.za/nevi-me/ifrs16-front-end-angular/pipelines/1830) doesn't make sense to me. On my machine, the relevant file is formatted correctly. @jorisvandenbossche we'll fix the lint CI failure here.

**Comment by markhildreth** [comment]
@nevi-me I don't have access to the failure you linked to (on domain `git.data-engine.co.za`, but if you mean the failure showing up in CI, there was a change to that file on master checked in after this branch was created. Rebasing a local branch onto master should cause the error to appear locally.

**Comment by nevi-me** [comment]
Thanks @markhildreth, I didn't see that the branch wasn't rebased into master. We should be fine now.

**Comment by kszucs** [comment]
@nevi-me you can ignore the failed ursabot builder, I've turned it off.

**Review by kszucs — APPROVED** [review]
LGTM

**Review by nevi-me — APPROVED** [review]

**Pull request closed without merging**
