### PR TITLE
ARROW-7513: [JS][tutorial] - Rich cols part 1

### PR DESCRIPTION
**Pull request by lmeyerov**
Introduces vector.from and table constructor for wide ints, dicts, and nested structs

Defers lower-level data/builder APIs for part 2

### CODE REVIEW

**Review by TheNeuralBit — APPROVED** [review]

**Comment by TheNeuralBit** [comment]
Thanks Leo!

**Comment by t829702** [comment]
the https://arrow.apache.org/docs/js/ documentation is still much less, incomplete if comparing to other implementations,  Especially can someone explain how to write arrow files?  before I can start play with apache-arrow, how can I convert my existing dataset to arrow format?
https://arrow.apache.org/docs/js/classes/recordbatchwriter.html (where are howto using RecordBatchWriter, RecordBatchFileWriter, & RecordBatchStreamWriter)

Wonder is this [Implementation Status](https://arrow.apache.org/docs/status.html) kept current? Look at other releases have 1.0.0 and 1.0.1 but on NPM the apache-arrow is still left at 0.17

**Comment by lmeyerov** [comment]
Now that RAPIDS is supporting more Arrow types, this is a timely question ( cc @trxcllnt  @TheNeuralBit  )

**Comment by trxcllnt** [comment]
@t829702 I'm working on https://issues.apache.org/jira/browse/ARROW-8394, and we should be able to release 1.0 after that.

As for conversion, you can take a look at some of these examples:
* [csv-to-arrow-js](https://github.com/trxcllnt/csv-to-arrow-js)
* [fastify-arrow plugin](https://github.com/trxcllnt/fastify-arrow)
* [arrow-to-parquet-js](https://github.com/trxcllnt/arrow-to-parquet-js)

I also have a few random demos in my [codepen profile](https://codepen.io/trxcllnt/pens/public).

**Pull request closed without merging**
