### PR TITLE
Allow LLVM 11

### PR DESCRIPTION
**Pull request by fxcoudert**
Homebrew now ships LLVM 11. This prevents us rebuilding arrow from source:

```
CMake Warning at cmake_modules/FindLLVMAlt.cmake:27 (find_package):
  Could not find a configuration file for package "LLVM" that is compatible
  with requested version "10".
```

### CODE REVIEW

**Comment by terencehonles** [comment]
It looks like there are more changes needed since the builder is still broken https://github.com/apache/arrow/pull/8492/checks?check_run_id=1279869182

**Comment by terencehonles** [comment]
Following up after the discussion in https://github.com/Homebrew/homebrew-core/pull/63177#issuecomment-713157947 it looks like supporting LLVM 11 would be a good idea in the long term it is no longer a blocker to compiling arrow from source.

(I was able to fix this for the GitHub workflow by updating the [cpp/Brewfile](https://github.com/apache/arrow/pull/8386/files#diff-87eb96363e17dbc9cb816c99123f76f25d63eb48920dd785a486ee59ee1997a1L28-R28) to only reference llvm@8 instead of llvm@8 and llvm)

**Comment by kou** [comment]
@fxcoudert Thanks for sending feedback from Homebrew!

I think that we need more changes to support LLVM 11 like we did by 6a1cdbc66c5ddfaeb426ac4deea9da0ea284849f for LLVM 10.

It may be difficult for people who don't familiar with Apache Arrow build system. I'll take over this.

**Comment by pprudhvi** [comment]
@kou looks like this requires code changes, will we be able to build gandiva on centos with llvm 8?

**Comment by kou** [comment]
> will we be able to build gandiva on centos with llvm 8?

I think so.

**Comment by kou** [comment]
#8521

**Pull request closed without merging**
