### PR TITLE
MINOR: [Dev] Remove westonpace from compute reviews and add to acero reviews in CODEOWNERS

### PR DESCRIPTION
**Pull request by westonpace**

### CODE REVIEW

**Comment by mapleFU** [comment]
By the way, who can I ask for help in `compute` module now?

**Comment by westonpace** [comment]
> By the way, who can I ask for help in compute module now?

@mapleFU 

Feel free to ping me still if you want.  I can probably review the occasional PR.  I can't keep up with all of them though.  You might also ask @felipecrv @pitrou @bkietz @lidavidm and @benibus (any of you feel free to correct me if needed).

**Review by kou — APPROVED** [review]
+1

**Comment by mapleFU** [comment]
Thanks! Thanks for your help!

**Pull request merged**
