### PR TITLE
ARROW-15949: [Python] Do not require Parquet encryption when Parquet is disabled

### PR DESCRIPTION
**Pull request by pitrou**
Fix the Java C Data Interface Integration build failure.

### CODE REVIEW

**Comment by pitrou** [comment]
@github-actions crossbow submit -g nightly

**Comment by lidavidm** [comment]
I can close #12639?

**Comment by pitrou** [comment]
> I can close #12639?

Oops, sorry, I hadn't noticed that PR. Yes, I suppose you can close it :-S

**Comment by lidavidm** [comment]
Sorry, I should've filed a JIRA for it first.

**Pull request closed without merging**
