### PR TITLE
ARROW-10388: [Java] Fix Spark integration build failure

### PR DESCRIPTION
**Pull request by liyafan82**
Please see https://issues.apache.org/jira/browse/ARROW-10388

### CODE REVIEW

**Comment by kou** [comment]
@github-actions crossbow submit *-spark-*

**Comment by liyafan82** [comment]
The first test (test-conda-python-3.7-spark-branch-3.0) failed because of lacking a library on the class path:
```
Caused by: java.lang.RuntimeException: No DefaultAllocationManager found on classpath. Can't allocate Arrow buffers. Please consider adding arrow-memory-netty or arrow-memory-unsafe as a dependency.
```

**Comment by emkornfield** [comment]
@liyafan82 I applied a small cleanup patch.  If this looks good and CI is green we should go ahead and merge this and open up a separate JIRA for the allocator issue.

**Comment by liyafan82** [comment]
> @liyafan82 I applied a small cleanup patch. If this looks good and CI is green we should go ahead and merge this and open up a separate JIRA for the allocator issue.

@emkornfield Sounds reasonable. Thanks.

**Comment by liyafan82** [comment]
Merging this, as something is wrong with continuous-integration/travis-ci/pr

**Comment by liyafan82** [comment]
I have opened https://issues.apache.org/jira/browse/SPARK-33279 to track the build failure on spark-3.0 branch.

**Pull request closed without merging**
