### PR TITLE
ARROW-13282: [C++] Remove obsolete generated files

### PR DESCRIPTION
**Pull request by edponce**
This PR removes obsolete generated files from src/arrow/util/, namely bpacking_avx2_generated.h and bpacking_avx512_generated.h.

### CODE REVIEW

**Comment by edponce** [comment]
@pitrou please review

**Review by cyb70289 — APPROVED** [review]
+1

**Comment by cyb70289** [comment]
s390x c++ ci failure is not related

**Comment by kou** [comment]
It was fixed by #10681.

**Comment by cyb70289** [comment]
Thanks @edponce !

**Pull request closed without merging**
