### PR TITLE
WIP: [Release] Verify release-13.0.0-rc2

### PR DESCRIPTION
**Pull request by kou**
PR to verify Release Candidate

### CODE REVIEW

**Comment by kou** [comment]
@github-actions crossbow submit  --group verify-rc-source --param release=13.0.0 --param rc=2

**Comment by raulcd** [comment]
Revision: c604084e7c62747780f91d6f8419c47feb4b20fb

Submitted crossbow builds: [ursacomputing/crossbow @ release-13.0.0-rc2-0](https://github.com/ursacomputing/crossbow/branches/all?query=release-13.0.0-rc2-0)

|Task|Status|
|----|------|
|almalinux-8-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc2-0-github-almalinux-8-amd64)|
|almalinux-8-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc2-0-github-almalinux-8-arm64)|
|almalinux-9-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc2-0-github-almalinux-9-amd64)|
|almalinux-9-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc2-0-github-almalinux-9-arm64)|
|amazon-linux-2023-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc2-0-github-amazon-linux-2023-amd64)|
|amazon-linux-2023-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc2-0-github-amazon-linux-2023-arm64)|
|centos-7-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc2-0-github-centos-7-amd64)|
|centos-8-stream-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc2-0-github-centos-8-stream-amd64)|
|centos-8-stream-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc2-0-github-centos-8-stream-arm64)|
|centos-9-stream-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/5732103475/job/15534384281)|
|centos-9-stream-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc2-0-github-centos-9-stream-arm64)|
|conan-maximum|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc2-0-github-conan-maximum)|
|conan-minimum|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/5732102595/job/15534381174)|
|debian-bookworm-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc2-0-github-debian-bookworm-amd64)|
|debian-bookworm-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc2-0-github-debian-bookworm-arm64)|
|debian-bullseye-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc2-0-github-debian-bullseye-amd64)|
|debian-bullseye-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc2-0-github-debian-bullseye-arm64)|
|debian-trixie-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/5732102973/job/15534382558)|
|debian-trixie-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/5732103332/job/15534383748)|
|java-jars|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc2-0-github-java-jars)|
|nuget|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc2-0-github-nuget)|
|python-sdist|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc2-0-github-python-sdist)|
|r-binary-packages|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/5732105222/job/15534390011)|
|test-ubuntu-default-docs|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/5732103696/job/15534385144)|
|ubuntu-focal-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/5732102258/job/15534380121)|
|ubuntu-focal-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/5732105753/job/15534391719)|
|ubuntu-jammy-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc2-0-github-ubuntu-jammy-amd64)|
|ubuntu-jammy-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/5732102761/job/15534381879)|
|ubuntu-lunar-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc2-0-github-ubuntu-lunar-amd64)|
|ubuntu-lunar-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/5732105493/job/15534390873)|
|wheel-clean|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc2-0-github-wheel-clean)|
|wheel-macos-big-sur-cp310-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/5732103909/job/15534385859)|
|wheel-macos-big-sur-cp311-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc2-0-github-wheel-macos-big-sur-cp311-arm64)|
|wheel-macos-big-sur-cp38-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/5732104942/job/15534389195)|
|wheel-macos-big-sur-cp39-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc2-0-github-wheel-macos-big-sur-cp39-arm64)|
|wheel-macos-mojave-cp310-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc2-0-github-wheel-macos-mojave-cp310-amd64)|
|wheel-macos-mojave-cp311-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc2-0-github-wheel-macos-mojave-cp311-amd64)|
|wheel-macos-mojave-cp38-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc2-0-github-wheel-macos-mojave-cp38-amd64)|
|wheel-macos-mojave-cp39-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc2-0-github-wheel-macos-mojave-cp39-amd64)|
|wheel-manylinux-2-28-cp310-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/5732103119/job/15534383068)|
|wheel-manylinux-2-28-cp310-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc2-0-github-wheel-manylinux-2-28-cp310-arm64)|
|wheel-manylinux-2-28-cp311-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/5732106013/job/15534392353)|
|wheel-manylinux-2-28-cp311-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/5732106947/job/15534394532)|
|wheel-manylinux-2-28-cp38-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc2-0-github-wheel-manylinux-2-28-cp38-amd64)|
|wheel-manylinux-2-28-cp38-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/5732107392/job/15534395780)|
|wheel-manylinux-2-28-cp39-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/5732104301/job/15534387086)|
|wheel-manylinux-2-28-cp39-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/5732106293/job/15534393147)|
|wheel-manylinux-2014-cp310-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc2-0-github-wheel-manylinux-2014-cp310-amd64)|
|wheel-manylinux-2014-cp310-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/5732107105/job/15534395044)|
|wheel-manylinux-2014-cp311-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc2-0-github-wheel-manylinux-2014-cp311-amd64)|
|wheel-manylinux-2014-cp311-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc2-0-github-wheel-manylinux-2014-cp311-arm64)|
|wheel-manylinux-2014-cp38-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/5732102417/job/15534380491)|
|wheel-manylinux-2014-cp38-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/5732107596/job/15534396445)|
|wheel-manylinux-2014-cp39-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc2-0-github-wheel-manylinux-2014-cp39-amd64)|
|wheel-manylinux-2014-cp39-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/5732109801/job/15534403052)|
|wheel-windows-cp310-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/5732109644/job/15534402646)|
|wheel-windows-cp311-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc2-0-github-wheel-windows-cp311-amd64)|
|wheel-windows-cp38-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-13.0.0-rc2-0-github-wheel-windows-cp38-amd64)|
|wheel-windows-cp39-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/5732104750/job/15534388569)|

**Comment by raulcd** [comment]
@ursabot please benchmark

**Comment by raulcd** [comment]
@github-actions crossbow submit  --group verify-rc-binaries --group verify-rc-wheels --param release=13.0.0 --param rc=2

**Comment by raulcd** [comment]
Closing in favor of new RC in order to include the fix for https://github.com/apache/arrow/issues/36892

**Pull request closed without merging**
