### PR TITLE
ARROW-4088: [Python] Table.from_batches() fails when passed a schema with metadata

### PR DESCRIPTION
**Pull request by kszucs**
`check_metadata=False` flag wasn't propagated down to `Field::Equals` at https://github.com/apache/arrow/blob/master/cpp/src/arrow/table.cc#L406

### CODE REVIEW

**Comment by wesm** [comment]
Tests fail

**Comment by kszucs** [comment]
I was testing that the issue occurs if I turn on the metadata checking, forgot to turn it [off](https://github.com/apache/arrow/pull/3256/commits/b2698995f7537ec52559fc45363ce1ef4bc698f7#diff-74388640577855d01824e59501ea2791L406) :)

**Review by xhochy — APPROVED** [review]
+1, LGTM

I did not see on first look that this really fixes the reported issue. After a second careful one: it does. Would be nice to mention it in the description how it was fixed as `from_batches` is never called in the newly added tests.

**Comment by kszucs** [comment]
@xhochy added a short desc

**Pull request closed without merging**
