### PR TITLE
ARROW-11839: [C++] Use xsimd for generation of accelerated bit-unpacking

### PR DESCRIPTION
**Pull request by pitrou**
The custom per-ISA code generation scripts (AVX2, AVX512) are replaced with a single code generation script that outputs xsimd code for any SIMD bit-width, in an ISA-agnostic way.

Also add a Neon optimized version of bit-unpacking that leverages the generated code for 128-bit SIMD.

### CODE REVIEW

**Comment by pitrou** [comment]
Merging this is currently blocked by xsimd issues https://github.com/xtensor-stack/xsimd/issues/421 and https://github.com/xtensor-stack/xsimd/issues/422.

**Comment by pitrou** [comment]
@jianxind @cyb70289 Feel free to take a look. It would be interesting to get performance numbers on Neon (one affected benchmark should be `parquet-encoding-benchmark`, perhaps also `parquet-column-io-benchmark` and `parquet-arrow-reader-writer-benchmark`).

**Comment by cyb70289** [comment]
I tested Neon performance of `parquet-encoding-benchmark`, `parquet-column-io-benchmark` and `parquet-arrow-reader-writer-benchmark`. No obvious difference found against master branch.

Compiler does good optimization for `bpacking` code. Disassembler shows `shift` and `and` operations are vectorized. https://godbolt.org/z/41G8Ta

**Comment by pitrou** [comment]
Interesting, thank you.

**Comment by pitrou** [comment]
TODO: switch to SafeLoad as in PR #9835

**Comment by nealrichardson** [comment]
Is there anything left to do here (other than perhaps rebase and hope CI is fixed)?

**Comment by pitrou** [comment]
@nealrichardson We must make sure that compilation works on all C++ builds.

**Comment by pitrou** [comment]
Crossbow builds: https://github.com/ursacomputing/crossbow/branches/all?query=build-217

**Comment by pitrou** [comment]
Will merge now.

**Pull request closed without merging**
