### PR TITLE
ARROW-1868: [Java] Cleanup usage of Types.MinorType to MinorType

### PR DESCRIPTION
**Pull request by BryanCutler**
Cleanup usage specifying Types.MinorType to just MinorType in vector classes and tests, and removed unused imports.

### CODE REVIEW

**Review by icexelloss — APPROVED** [review]
LGTM!

**Comment by BryanCutler** [comment]
Thanks @icexelloss!  Does this cleanup look ok from your end @siddharthteotia ?

**Comment by BryanCutler** [comment]
I'll commit this later today if no more comments

**Review by siddharthteotia — APPROVED** [review]
+1, Thanks, @BryanCutler

**Comment by BryanCutler** [comment]
Merged to master, thanks @icexelloss and @siddharthteotia

**Pull request closed without merging**
