### PR TITLE
GH-41630: [Benchmarking] Fix out-of-source build in benchmarks

### PR DESCRIPTION
**Pull request by assignUser**
### Rationale for this change

Broken benchmarks after #41455 
### What changes are included in this PR?

Use /tmp/arrow as build dir.

### Are there any user-facing changes?

* GitHub Issue: #41630

### CODE REVIEW

**Comment by assignUser** [comment]
@ursabot please benchmark

**Comment by assignUser** [comment]
@ursabot please benchmark

**Comment by assignUser** [comment]
@ursabot please benchmark

**Review by kou — APPROVED** [review]
+1

**Pull request merged**
