### PR TITLE
ARROW-7682: [Packaging] Add support for arm64 APT/Yum repositories

### PR DESCRIPTION
**Pull request by kou**
Reimplement all logic of 03-binary.sh and post-02-binary.sh by
Ruby. It supports parallel download and upload. It also supports auto
retrying. It makes release process faster.

Ruby code is ran in Docker. Ruby is not required on host.

### CODE REVIEW

**Comment by kou** [comment]
I've tested on https://bintray.com/kou/arrow/ .

You can test uploaded binaries by the followings:

APT:

```bash
sudo apt install -y qemu-user-static # Debian GNU/Linux buster or Ubuntu 18.10 or later is required.
docker run -it --rm arm64v8/ubuntu:disco
apt update
apt install -y wget
wget https://dl.bintray.com/kou/arrow/ubuntu-rc/apache-arrow-archive-keyring-latest-disco.deb
apt install -y ./apache-arrow-archive-keyring-latest-disco.deb
sed -i'' -e 's,https://apache.bintray.com/arrow/ubuntu,https://dl.bintray.com/kou/arrow/ubuntu-rc,g' /etc/apt/sources.list.d/apache-arrow.sources # Use https://bintray.com/kou/arrow/
apt update
apt install -y libarrow-glib-dev
```
Yum:

```bash
sudo apt install -y qemu-user-static # Debian GNU/Linux buster or Ubuntu 18.10 or later is required.
docker run -it --rm arm64v8/centos:7
yum install -y https://dl.bintray.com/kou/arrow/centos-rc/7/apache-arrow-release-latest.rpm
ed -i'' -e 's,https://apache.bintray.com/arrow/centos,https://dl.bintray.com/kou/arrow/centos-rc,g' /etc/yum.repos.d/Apache-Arrow.repo # Use https://bintray.com/kou/arrow/
yum install -y arrow-glib-devel
```

**Comment by kou** [comment]
We need to update https://arrow.apache.org/install/ to use `apache-arrow-keyring-archive` for APT and `apache-arrow-release` for Yum. I'll do it after this pull request is merged.

**Comment by kou** [comment]
We also need to update https://cwiki.apache.org/confluence/display/ARROW/Release+Management+Guide to use `dev/release/.env`. I'll do it after this pull request is merged.

**Comment by kou** [comment]
I tested this change on Debian GNU/Linux sid and macOS Catalina.

**Comment by kou** [comment]
@kszucs Can I do `dev/release/03-binary.sh` and `dev/release/post-02-binary.sh` in 0.16.0 release process?

**Comment by kszucs** [comment]
@kou sure, when should we cut rc0 then?

**Comment by kou** [comment]
Sorry. We have discussed this on `dev@arrow.apache.org`. I'll answer this on `dev@arrow.apache.org`.

**Review by kszucs — APPROVED** [review]
LGTM, thanks @kou!

**Pull request closed without merging**
