### PR TITLE
ARROW-15475: [C++][Python] Add a space after commas in pretty-print output

### PR DESCRIPTION
**Pull request by jeszyb**

### CODE REVIEW

**Review by cyb70289 — APPROVED** [review]
LGTM

**Comment by pitrou** [comment]
@jeszyb Should `Status PrettyPrint(const ChunkedArray& chunked_arr, ...)` also be modified?

**Comment by pitrou** [comment]
@jeszyb This needs rebasing from master now. Also did you see my question above?

**Comment by jorisvandenbossche** [comment]
@jeszyb do you have time to update this?

**Comment by amol-** [comment]
Closing because it has been untouched for a while, in case it's still relevant feel free to reopen and move it forward 👍

**Pull request closed without merging**
