### PR TITLE
ARROW-231 [C++]: Add typed Resize to PoolBuffer

### PR DESCRIPTION
**Pull request by JohanMabille**
I also added a typed Reserve to be consistent. Let me know what you think.

### CODE REVIEW

**Review by wesm — COMMENTED** [review]
This looks good to me, @xhochy since this may simplify code in parquet-cpp, does this work for you?

**Review by xhochy — APPROVED** [review]
+1, it will make code much more readable!

**Comment by wesm** [comment]
Cool, I'm merging since OS X on Travis is cranky lately. thanks @JohanMabille!

**Comment by wesm** [comment]
@JohanMabille would you mind opening an account in issues.apache.org/jira so that I can assign JIRAs to you? thanks!

**Comment by JohanMabille** [comment]
@wesm sure!

**Pull request closed without merging**
