### PR TITLE
GH-38562: [Packaging] Add support for Ubuntu 23.10

### LINKED ISSUE #38562: [Packaging] Install on Ubuntu 23.10
### Describe the enhancement requested

Hi

I want to upgrade my machine to Ubuntu 23.10, released a month ago. But in the repository is there only support for 23.04? 

There will be support for 23.10 in the future? or I will have to wait until 24.04? Is there a way to install the 23.04 version on 23.10? Is it possible?

### Component(s)

Release

### PR DESCRIPTION
**Pull request by kou**
### Rationale for this change

Ubuntu 23.10 released on 2023-10.

### What changes are included in this PR?

Build packages for Ubuntu 23.10.

### Are these changes tested?

Yes.

### Are there any user-facing changes?

No.
* Closes: #38562

### CODE REVIEW

**Comment by kou** [comment]
@github-actions crossbow submit ubuntu-mantic-*

**Comment by assignUser** [comment]
Have we always supported non LTS versions? If so I am -.9 on that

**Comment by kou** [comment]
> Have we always supported non LTS versions?

Yes.

> If so I am -.9 on that

Why? To reduce CI time? Or To reduce maintenance cost?

Regarding CI time: It will not be a problem. We have at most 2 (1 in general) non-LTS versions. It will not increase CI time so much. (I'll remove Ubuntu 23.04 support after we merge this.)

Regarding maintenance cost: Maintenance cost will be reduced by supporting non-LTS versions. If we don't support non-LTS version continually, we need large work to support the next LTS version (24.04). If we support non-LTS version continually, we can adapt Ubuntu changes step by step. It'll reduce total maintenance cost. And I'll maintain non-LTS versions as usual.

**Comment by assignUser** [comment]
Ok, that makes sense :) +1

> (I'll remove Ubuntu 23.04 support after we merge this.)

Because 23.10 is sufficent and compatible to create packages usable for 23.04?

**Comment by kou** [comment]
> Because 23.10 is sufficient and compatible to create packages usable for 23.04?

No. Packages for 23.10 will not work on 23.04...

Because we will not release the next version before 23.04 reach EOL.

**Review by assignUser — APPROVED** [review]

**Comment by almejo** [comment]
Happy to see that only one approval is left. Support for arrow is the only thing stopping from upgrading to 23.10

**Review by raulcd — APPROVED** [review]
LGTM

**Comment by almejo** [comment]
How much time is until it reach the repositories?

**Comment by raulcd** [comment]
Hi @almejo In order to reach the official repositories we require an Apache Arrow release. This is targeted for our next release, 15.0.0. We have a 3 month release cadence and the 15.0.0 is expected for January.

**Comment by kou** [comment]
You can download needed `*.deb` from https://github.com/ursacomputing/crossbow/releases/tag/actions-1df9c0570d-github-ubuntu-mantic-amd64 and install them by `apt install ./*.deb` (`./` is important) for now.

**Comment by almejo** [comment]
Thank you very much. I wanted to use the repo sooner, but the solution of using that links is great!

Thanks for all!!!

**Pull request merged**
