### PR TITLE
ARROW-12251: [Rust] Add Ballista to CI

### PR DESCRIPTION
**Pull request by andygrove**
Add `cargo build` and `cargo test` steps for Ballista. I will address fmt and clippy separately.

### CODE REVIEW

**Comment by andygrove** [comment]
The build fails due to:

```
error: failed to run custom build command for `snmalloc-sys v0.2.26`
```

Root cause is that cmake is not installed.


@Dandandan What is your recommendation? Do we need to use custom builder images?

**Comment by mjp41** [comment]
This came up for another project, and they added support for building snmalloc-[rs/sys] without cmake:

> build_cc: use of cc crate instead of cmake (cmake still default) as builder (more platform agnostic)
> https://github.com/SchrodingerZhu/snmalloc-rs/pull/118

Personally, I would prefer snmalloc to be built with cmake, as that is what we test the most.  But, if that is not possible for your scenario, this option is there.

**Comment by Dandandan** [comment]
Thanks @mjp41 I think that's a great option.

**Comment by andygrove** [comment]
I modified this PR to build without default features, just so we can enable CI quickly. I filed https://issues.apache.org/jira/browse/ARROW-12331 for the follow-up work for snmalloc.

**Comment by andygrove** [comment]
I confirmed that CI ran the build and tests for Ballista so will go ahead and merge this.

**Pull request closed without merging**
