### PR TITLE
ARROW-8521: [Release] Update CHANGELOG.md to include patch releases

### PR DESCRIPTION
**Pull request by kszucs**
Generated by the following command from #7162 

```bash
archery release --jira-cache /tmp/archery-cache changelog regenerate
```

Here is the new rendered [CHANGELOG.md](https://github.com/apache/arrow/blob/aa77709098739fe866ff7fba887054e4d1001621/CHANGELOG.md)

We may want to run the new curation script as well to update the jira fix versions for the issues resolved right after the release cuts (then regenerate the changelog again).

We can also improve the script to organize the changelog around components in the future since that information is already available in #7162

### CODE REVIEW

**Comment by wesm** [comment]
Based on what I can tell people aren't consistent about classifying things as Improvements vs. New Features (and sometimes the distinction is unclear), so I feel like those categories should be grouped together. Thoughts?

**Comment by nealrichardson** [comment]
I agree that the only consistent distinction we use is bug vs. not bug. And even if we had a meaningful distinction between new feature and improvement, I'm not sure a reader of the changelog would know what that was or even care.

**Comment by kszucs** [comment]
So we shouldn't add a label for the improvements nor the new features, just for the bug fixes?

**Comment by nealrichardson** [comment]
I would just say everything that is not a Bug goes under "New Features"

**Comment by wesm** [comment]
"New Features and Improvements" as the header would be good

**Comment by kszucs** [comment]
Ok, updating.

**Review by wesm — APPROVED** [review]
+1

**Pull request closed without merging**
