### PR TITLE
ARROW-8049: [C++] Bump thrift to 0.13 and require cmake 3.10 for it

### PR DESCRIPTION
**Pull request by nealrichardson**
See https://github.com/apache/arrow/pull/9483#issuecomment-792322123

### CODE REVIEW

**Comment by kou** [comment]
@github-actions autotune

**Comment by kou** [comment]
@github-actions crossbow submit -g linux

**Comment by kou** [comment]
@github-actions autotune

**Comment by nealrichardson** [comment]
@kou I don't know if the Travis failures are meaningful, but there is the expected failure on `ubuntu-xenial-amd64`. I believe the patch for working around the cmake 3.10 requirement in thrift is small, should we do that? Or should we change the xenial job to download new cmake? Or drop the job entirely since it's EOL next month (right)?

**Comment by kou** [comment]
We can ignore the Travis CI failures.

I don't think that we release 4.0.0 in this month. So we can drop Ubuntu 16.04 jobs entirely. I'll work on it as a separated task. Please wait for a while. ARROW-11910

FYI: Ubuntu 16.04 EOL: https://help.ubuntu.com/community/EOL#Ubuntu_16.04_Xenial_Xerus

**Comment by nealrichardson** [comment]
> Please wait for a while

👍 are you picking up ARROW-11910 now? This isn't urgent for me, though it's blocking the boost upgrade, which is blocking the switch off of bintray URLs for boost, which needs to happen for 4.0 given bintray's May 1 shutdown date. So I don't want to let this wait too long.

**Comment by nealrichardson** [comment]
Lol, while I was asking if you were doing it soon, you were making the PR :)

**Comment by kou** [comment]
Done. :-)

Could you rebase on the master?

**Comment by nealrichardson** [comment]
Rebased, PTAL

**Comment by kou** [comment]
@github-actions crossbow submit -g linux-amd64

**Review by kou — APPROVED** [review]
+1

**Pull request closed without merging**
