### PR TITLE
ARROW-7773: [Python] Replace fs.get_target_stats by ls/info

### PR DESCRIPTION
**Pull request by fhoering**

### CODE REVIEW

**Comment by pitrou** [comment]
I don't mind renaming `get_target_stats`, but I certainly don't think we should have redundant APIs that do basically the same thing.
1. There should be only one method to list files and their information
2. There's no need for a `detail` argument when the underlying C++ method always returns detailed info, anyway

**Comment by fhoering** [comment]
>1. There should be only one method to list files and their information
Can you explain why ? Personally, I find two separate methods clearer to separate the responsabilities.
i.e. what happens when get_target_stats is called on a directory ? listing or sending the information of the directory ?

I know you solved this with the Selector object but again this seems to me like like reinveting the wheel. So I would prefer sticking to what existed before and what has been also done in fsspec. This works, is easy and no need to relearn a new concept.

ls => list information of the directory 
info => give infos about files & directories

To be really consistent this kind of implies to also remove the mode where one passes a list of files to ls/get_target_stats and moves this to info (or another method called batched_info)


> 2. There's no need for a detail argument when the underlying C++ method always returns detailed > info, anyway
Can you develop ? 
When using 'ls' it is imo more convenient to just see the file names by default and then when one needs more info it sends all the details.

**Comment by pitrou** [comment]
Look at your `ls` method. It takes a "str, list of str or FileSelector". It's doing everything `get_target_stats` did.

And please let's not take `fsspec` as an example. I consider it an ugly API, full of redundant methods.

**Comment by fhoering** [comment]
> Look at your ls method. It takes a "str, list of str or FileSelector". It's doing everything >get_target_stats did.

I kept all those options because I was afraid of changing it to much and do it in small steps as advised in the JIRA ticket. 

But yes as a next step I would like to remove accepting Selector and move the 'list of str' for directory.file infos into the info method:

def info(path) => infos for path, path is str or list of str for batched mode
def ls(path, detail=False) => listing directory contents, takes str only

I you agree on this I will amend this PR.


> And please let's not take fsspec as an example. I consider it an ugly API, full of redundant methods.

Can you please develop why ? I'm interested to hear the exact arguments.
I worked with the API from dask/hdfs3 (that seems very similar to fsspec) for a long time and I honestly think it is very nice and very easy to use.

**Comment by pitrou** [comment]
My main gripe with `fsspec` is the large number of redundant APIs and small convenience methods. When there are redundant APIs, it adds a maintenance burden and it also makes choice more difficult for the user (because it's not obvious whether some APIs are better - e.g. more performant - than others).

Here I would agree with separating two concerns into separate methods:
* listing a file or explicit list of files
* listing files by navigating through a directory (the C++ `Selector` API)

So you would have something like:
* `fs.list_file(file_path: str or [str]) -> FileStats or [FileStats]`
* `fs.list_dir(dir_path: str, recurse=False) -> [FileStats]`

(names can be improved)

**Comment by fhoering** [comment]
> My main gripe with fsspec is the large number of redundant APIs and small convenience methods. When there are redundant APIs, it adds a maintenance burden and it also makes choice more difficult for the user (because it's not obvious whether some APIs are better - e.g. more performant - than others).

I totally agree on all this. That's why I don't want to add new alias methods everywhere.

But OK. I feel like this will end up with too many discussions and eventually get inconsistent (and therefore worse). So after reflection it is maybe a bad idea to try to fit my use case inside the new FileSystem API.

So if will abandon this PR and work on a wrapper (after the next 2 weeks where I'm in holidays) that brings back at least all the previous methods from the old FileSystem.
Then still this wrapper could be the new external documented Fs and FileSystem could stay internal to arrow.

**Comment by fhoering** [comment]
> My main gripe with fsspec is the large number of redundant APIs and small convenience methods. When there are redundant APIs, it adds a maintenance burden and it also makes choice more difficult for the user (because it's not obvious whether some APIs are better - e.g. more performant - than others).

I totally agree on all this. That's why I don't want to add new alias methods everywhere.

But OK. I feel like this will end up with too many discussions and eventually get inconsistent (and therefore worse). So after reflection it is maybe a bad idea to try to fit my use case inside the new FileSystem API.

So if will abandon this PR and work on a wrapper (after the next 2 weeks where I'm in holidays) that brings back at least all the previous methods from the old FileSystem.
Then still this wrapper could be the new external documented Fs and FileSystem could stay internal to arrow.

**Comment by fhoering** [comment]
In any case I still haven't understood how you count on keeping the compatibility to the old FileSystem. If it is just deprecated in favor of the new one I'm not the last person talking about this I think.

**Pull request closed without merging**
