### PR TITLE
ARROW-12543: [CI][Python] Fix test-conda-python-3.9 build (gdb version conflict)

### PR DESCRIPTION
**Pull request by jorisvandenbossche**

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
@github-actions crossbow submit test-conda-python-3.9

**Comment by pitrou** [comment]
As I suggested on the JIRA, you could also install `gdb` using `apt-get` in the base `conda.dockerfile`. There's no need to get it from conda-forge.

**Comment by jorisvandenbossche** [comment]
@github-actions crossbow submit test-conda-python-3.9

**Review by kszucs — APPROVED** [review]
Thanks Joris!

**Pull request closed without merging**
