### PR TITLE
ARROW-3562: [R] Disallow creation of objects with shared_ptr<T>(nullptr), use bits64::integer64

### PR DESCRIPTION
**Pull request by romainfrancois**
Follow up to #2749 with the following fixes: 

 - shared_ptr of `nullptr` don't construct R6 objects
 - int64 uses `bit64::integer64`, based on https://github.com/r-lib/vctrs/pull/121

### CODE REVIEW

**Comment by wesm** [comment]
Seems like we've got more meaningless churn on the Rcpp files, do you know what's going on?

**Comment by wesm** [comment]
This is enough meaningful work to merit an entry in the changelog, so I made a JIRA

**Comment by wesm** [comment]
The Rcpp output is non-alphabetical again. Is this a bug or an old version?

**Comment by wesm** [comment]
I guess it could help to use lowercase filenames

**Comment by romainfrancois** [comment]
The build failure is spurious. Related to https://github.com/r-lib/remotes/issues/210#issuecomment-430643547

**Review by wesm — APPROVED** [review]
+1. Thanks!

**Pull request closed without merging**
