### PR TITLE
ARROW-2991: [CI] Remove some AppVeyor build configurations

### PR DESCRIPTION
**Pull request by pitrou**
Remove two build configurations:
- Release build with Ninja and VS2015 (we already have a Release build with
  Ninja and VS2017, and a Debug build with Ninja and VS2015)
- Release build with NMake (we don't care much about NMake enough to add
  10+ minutes of build time)

### CODE REVIEW

**Review by wesm — APPROVED** [review]
+1

**Comment by pitrou** [comment]
Latest AppVeyor build took 26 minutes (wall clock time).

**Comment by wesm** [comment]
That's great, thank you. Merging this

**Comment by pitrou** [comment]
Oops, I made a mistake in the JIRA id (should have been ARROW-2991, not ARROW-2992).

**Comment by wesm** [comment]
Ah, not a big deal

**Pull request closed without merging**
