### PR TITLE
ARROW-13381: [C++] ArrayFromJSON doesn't work for float value dictionary type

### PR DESCRIPTION
**Pull request by edponce**
This PR adds float/double cases for dictionary converter.

### CODE REVIEW

**Comment by lidavidm** [comment]
Thanks for the quick fix.

What does this have to do with Flight?

**Comment by nirandaperera** [comment]
> Thanks for the quick fix.
> 
> What does this have to do with Flight?

I added Flight because I thought this needs to be added in the Flight code. :grin:

**Comment by nirandaperera** [comment]
Thanks @edponce

**Review by lidavidm — APPROVED** [review]
Thanks, LGTM

**Comment by lidavidm** [comment]
MacOS failure looks unrelated.

**Pull request closed without merging**
