### PR TITLE
GH-44831: [CI] Build Java for integration tests from arrow-java

### LINKED ISSUE #44831: [Java][CI] Use apache/arrow-java for integration test
### Describe the enhancement requested

After apache/arrow-java works.

We should use apache/arrow-java like apache/arrow-go: https://github.com/apache/arrow/blob/a6fe59592c643d591ee719041dd2b5d8b9ada7d6/.github/workflows/integration.yml#L117

### Component(s)

Continuous Integration, Java

### LINKED ISSUE #44945: [Java] Remove java/
### Describe the enhancement requested

We're moving `java/` to https://github.com/apache/arrow-java .

### Component(s)

Java

### PR DESCRIPTION
**Pull request by lidavidm**
### Rationale for this change

We moved `java/` in apache/arrow to apache/arrow-java. We should use apache/arrow-java to integration tests.

### What changes are included in this PR?

* Remove `java/`
* Use apache/arrow-java for integration test

### Are these changes tested?

Yes.

### Are there any user-facing changes?

No.

* GitHub Issue: #44945
* GitHub Issue: #44831

### CODE REVIEW

**Comment by lidavidm** [comment]
We can't actually merge this until we finish deleting the rest of the existing Java code here.

**Comment by lidavidm** [comment]
It seems integration works...

**Comment by lidavidm** [comment]
Updated, I think the macOS issue is not related.

**Review by kou — APPROVED** [review]
+1

**Pull request merged**
