### PR TITLE
GH-35728: [CI][Python] Move test_total_bytes_allocated to a subprocess to improve reliability

### LINKED ISSUE #35728: [Python] `test_total_bytes_allocated` failing on CI
### Describe the bug, including details regarding any error messages, version, and platform.

In https://github.com/conda-forge/arrow-cpp-feedstock/pull/1053, I currently have a failing test `test_total_bytes_allocated` on arrow 12 (though not arrow 11 or before), but some commit between arrow 12 and current `main` seems to have fixed this[^1] - any ideas?

This is currently holding up all our migrations on the arrow-feedstock and is very high priority for us in conda-forge. Possible solutions:
* someone tells me that it's fine to skip that test
* we identify the relevant changes that regressed this from 11->12 and revert them (on the feedstock)
* we identify what fixed the issue between 12 & main and I backport those changes (on the feedstock)

[^1]: as confirmed in #35637

_Originally posted by @h-vetinari in https://github.com/apache/arrow/issues/35637#issuecomment-1552650935_
            

### Component(s)

Packaging

### PR DESCRIPTION
**Pull request by raulcd**
### Rationale for this change

Currently some conda and wheels jobs are failing due to this error:

```
 =================================== FAILURES ===================================
__________________________ test_total_bytes_allocated __________________________

    def test_total_bytes_allocated():
>       assert pa.total_allocated_bytes() == 0
E       assert 1216 == 0
E        +  where 1216 = <built-in function total_allocated_bytes>()
E        +    where <built-in function total_allocated_bytes> = pa.total_allocated_bytes
```

### What changes are included in this PR?

As suggested on the issue trying to move this test to a subprocess to see if it improves reliabilit.

### Are these changes tested?

Archery and CI

### Are there any user-facing changes?

No
* Closes: #35728

### CODE REVIEW

**Comment by raulcd** [comment]
@github-actions crossbow submit wheel-manylinux-*

**Comment by raulcd** [comment]
@github-actions crossbow submit wheel-manylinux-2014-*-arm64

**Comment by raulcd** [comment]
@github-actions crossbow submit wheel-manylinux-2014-cp310-arm64

**Comment by raulcd** [comment]
the flaky failures seem unrelated to this test now but to s3
```
 Timeout (0:05:00)!
Thread 0x0000ffff8fcca420 (most recent call first):
  File "/tmp/arrow-HEAD.1rhW8/venv-wheel-3.8-manylinux_2_17_aarch64.manylinux2014_aarch64/lib64/python3.8/site-packages/pyarrow/tests/test_fs.py", line 1122 in test_s3_options
  File "/tmp/arrow-HEAD.1rhW8/venv-wheel-3.8-manylinux_2_17_aarch64.manylinux2014_aarch64/lib64/python3.8/site-packages/_pytest/python.py", line 194 in pytest_pyfunc_call
  File "/tmp/arrow-HEAD.1rhW8/venv-wheel-3.8-manylinux_2_17_aarch64.manylinux2014_aarch64/lib64/python3.8/site-packages/pluggy/_callers.py", line 80 in _multicall
  File "/tmp/arrow-HEAD.1rhW8/venv-wheel-3.8-manylinux_2_17_aarch64.manylinux2014_aarch64/lib64/python3.8/site-packages/pluggy/_manager.py", line 112 in _hookexec
  File "/tmp/arrow-HEAD.1rhW8/venv-wheel-3.8-manylinux_2_17_aarch64.manylinux2014_aarch64/lib64/python3.8/site-packages/pluggy/_hooks.py", line 433 in __call__
  File "/tmp/arrow-HEAD.1rhW8/venv-wheel-3.8-manylinux_2_17_aarch64.manylinux2014_aarch64/lib64/python3.8/site-packages/_pytest/python.py", line 1788 in runtest
  File "/tmp/arrow-HEAD.1rhW8/venv-wheel-3.8-manylinux_2_17_aarch64.manylinux2014_aarch64/lib64/python3.8/site-packages/_pytest/runner.py", line 169 in pytest_runtest_call
  File "/tmp/arrow-HEAD.1rhW8/venv-wheel-3.8-manylinux_2_17_aarch64.manylinux2014_aarch64/lib64/python3.8/site-packages/pluggy/_callers.py", line 80 in _multicall
  File "/tmp/arrow-HEAD.1rhW8/venv-wheel-3.8-manylinux_2_17_aarch64.manylinux2014_aarch64/lib64/python3.8/site-packages/pluggy/_manager.py", line 112 in _hookexec
  File "/tmp/arrow-HEAD.1rhW8/venv-wheel-3.8-manylinux_2_17_aarch64.manylinux2014_aarch64/lib64/python3.8/site-packages/pluggy/_hooks.py", line 433 in __call__
  File "/tmp/arrow-HEAD.1rhW8/venv-wheel-3.8-manylinux_2_17_aarch64.manylinux2014_aarch64/lib64/python3.8/site-packages/_pytest/runner.py", line 262 in <lambda>
  File "/tmp/arrow-HEAD.1rhW8/venv-wheel-3.8-manylinux_2_17_aarch64.manylinux2014_aarch64/lib64/python3.8/site-packages/_pytest/runner.py", line 341 in from_call
  File "/tmp/arrow-HEAD.1rhW8/venv-wheel-3.8-manylinux_2_17_aarch64.manylinux2014_aarch64/lib64/python3.8/site-packages/_pytest/runner.py", line 261 in call_runtest_hook
  File "/tmp/arrow-HEAD.1rhW8/venv-wheel-3.8-manylinux_2_17_aarch64.manylinux2014_aarch64/lib64/python3.8/site-packages/_pytest/runner.py", line 222 in call_and_report
  File "/tmp/arrow-HEAD.1rhW8/venv-wheel-3.8-manylinux_2_17_aarch64.manylinux2014_aarch64/lib64/python3.8/site-packages/_pytest/runner.py", line 133 in runtestprotocol
  File "/tmp/arrow-HEAD.1rhW8/venv-wheel-3.8-manylinux_2_17_aarch64.manylinux2014_aarch64/lib64/python3.8/site-packages/_pytest/runner.py", line 114 in pytest_runtest_protocol
  File "/tmp/arrow-HEAD.1rhW8/venv-wheel-3.8-manylinux_2_17_aarch64.manylinux2014_aarch64/lib64/python3.8/site-packages/pluggy/_callers.py", line 80 in _multicall
  File "/tmp/arrow-HEAD.1rhW8/venv-wheel-3.8-manylinux_2_17_aarch64.manylinux2014_aarch64/lib64/python3.8/site-packages/pluggy/_manager.py", line 112 in _hookexec
  File "/tmp/arrow-HEAD.1rhW8/venv-wheel-3.8-manylinux_2_17_aarch64.manylinux2014_aarch64/lib64/python3.8/site-packages/pluggy/_hooks.py", line 433 in __call__
  File "/tmp/arrow-HEAD.1rhW8/venv-wheel-3.8-manylinux_2_17_aarch64.manylinux2014_aarch64/lib64/python3.8/site-packages/_pytest/main.py", line 349 in pytest_runtestloop
  File "/tmp/arrow-HEAD.1rhW8/venv-wheel-3.8-manylinux_2_17_aarch64.manylinux2014_aarch64/lib64/python3.8/site-packages/pluggy/_callers.py", line 80 in _multicall
  File "/tmp/arrow-HEAD.1rhW8/venv-wheel-3.8-manylinux_2_17_aarch64.manylinux2014_aarch64/lib64/python3.8/site-packages/pluggy/_manager.py", line 112 in _hookexec
  File "/tmp/arrow-HEAD.1rhW8/venv-wheel-3.8-manylinux_2_17_aarch64.manylinux2014_aarch64/lib64/python3.8/site-packages/pluggy/_hooks.py", line 433 in __call__
  File "/tmp/arrow-HEAD.1rhW8/venv-wheel-3.8-manylinux_2_17_aarch64.manylinux2014_aarch64/lib64/python3.8/site-packages/_pytest/main.py", line 324 in _main
  File "/tmp/arrow-HEAD.1rhW8/venv-wheel-3.8-manylinux_2_17_aarch64.manylinux2014_aarch64/lib64/python3.8/site-packages/_pytest/main.py", line 270 in wrap_session
  File "/tmp/arrow-HEAD.1rhW8/venv-wheel-3.8-manylinux_2_17_aarch64.manylinux2014_aarch64/lib64/python3.8/site-packages/_pytest/main.py", line 317 in pytest_cmdline_main
  File "/tmp/arrow-HEAD.1rhW8/venv-wheel-3.8-manylinux_2_17_aarch64.manylinux2014_aarch64/lib64/python3.8/site-packages/pluggy/_callers.py", line 80 in _multicall
  File "/tmp/arrow-HEAD.1rhW8/venv-wheel-3.8-manylinux_2_17_aarch64.manylinux2014_aarch64/lib64/python3.8/site-packages/pluggy/_manager.py", line 112 in _hookexec
  File "/tmp/arrow-HEAD.1rhW8/venv-wheel-3.8-manylinux_2_17_aarch64.manylinux2014_aarch64/lib64/python3.8/site-packages/pluggy/_hooks.py", line 433 in __call__
  File "/tmp/arrow-HEAD.1rhW8/venv-wheel-3.8-manylinux_2_17_aarch64.manylinux2014_aarch64/lib64/python3.8/site-packages/_pytest/config/__init__.py", line 166 in main
  File "/tmp/arrow-HEAD.1rhW8/venv-wheel-3.8-manylinux_2_17_aarch64.manylinux2014_aarch64/lib64/python3.8/site-packages/_pytest/config/__init__.py", line 189 in console_main
  File "/tmp/arrow-HEAD.1rhW8/venv-wheel-3.8-manylinux_2_17_aarch64.manylinux2014_aarch64/lib64/python3.8/site-packages/pytest/__main__.py", line 5 in <module>
  File "/usr/lib64/python3.8/runpy.py", line 87 in _run_code
  File "/usr/lib64/python3.8/runpy.py", line 194 in _run_module_as_main
```

**Review by pitrou — APPROVED** [review]

**Comment by raulcd** [comment]
@pitrou are you ok merging this? All the failures are known unrelated nightly failures

**Comment by pitrou** [comment]
@raulcd Yes, please merge!

**Pull request merged**
