### PR TITLE
ARROW-12834: [Python] Expose pre_buffer for IPC fragments

### PR DESCRIPTION
**Pull request by lidavidm**
This exposes the same API as for Parquet fragments.

### CODE REVIEW

**Comment by lidavidm** [comment]
See https://github.com/ursacomputing/benchmarks/pull/45 for the accompanying benchmark.

**Comment by lidavidm** [comment]
@ursabot please benchmark

**Comment by lidavidm** [comment]
Oh no, I forgot to scope it to just Python :(

**Comment by lidavidm** [comment]
Hmm. It's unclear if there's an improvement. Nominally there is compared to the contender but it seems the contender was just slow. I was hoping the pre_buffer=true would be faster than the pre_buffer=false within the same run.

image

**Comment by lidavidm** [comment]
I'd like to test this myself on EC2 and see why we don't get any expected benefit.

**Comment by lidavidm** [comment]
Running on EC2 with more iterations, it seems there's a small benefit, with some variance (from EC2?) throwing it off.

Conbench for `pre_buffer=True`:

```
    "stats": {
        "batch_id": "3104564f6b8244fb814465fbbf6a19cb",
        "data": [
            "14.430056",
            "16.669666",
            "38.752780",
            "15.887550",
            "12.784942",
            "13.485059",
            "12.358206",
            "12.877868",
            "11.940915",
            "12.250891"
        ],
        "iqr": "3.058287",
        "iterations": 10,
        "max": "38.752780",
        "mean": "16.143793",
        "median": "13.181464",
        "min": "11.940915",
        "q1": "12.464890",
        "q3": "15.523177",
        "run_id": "3104564f6b8244fb814465fbbf6a19cb",
        "stdev": "8.100836",
        "time_unit": "s",
        "times": [],
        "timestamp": "2021-05-25T15:32:39.462551+00:00",
        "unit": "s"
    },
```

Conbench for `pre_buffer=False`:
```
    "stats": {
        "batch_id": "e09c0ea9372145ca81aab93f30c08940",
        "data": [
            "15.748755",
            "15.441451",
            "15.636802",
            "15.699552",
            "15.200788",
            "14.816090",
            "14.998590",
            "14.502809",
            "15.451343",
            "15.484191"
        ],
        "iqr": "0.549510",
        "iterations": 10,
        "max": "15.748755",
        "mean": "15.298037",
        "median": "15.446397",
        "min": "14.502809",
        "q1": "15.049140",
        "q3": "15.598650",
        "run_id": "e09c0ea9372145ca81aab93f30c08940",
        "stdev": "0.411182",
        "time_unit": "s",
        "times": [],
        "timestamp": "2021-05-25T15:36:19.423906+00:00",
        "unit": "s"
    },
```

**Comment by lidavidm** [comment]
@ursabot please benchmark lang=Python

**Comment by lidavidm** [comment]
Conbench does show a marked difference on the i9-9960x though it seems variation is very high for that benchmark anyways when comparing to the contender.

**Comment by lidavidm** [comment]
@westonpace any thoughts on this? It seems to have only a small benefit at best, so maybe we should just close this instead.

**Comment by westonpace** [comment]
Unfortunately, I think I agree with closing.  The "common" path for IPC is hot-in-memory reads so the actual "read" calls should be more or less a no-op.  S3/IPC is also probably a pretty uncommon path.  For non-S3 the kernel should be doing its own coalescing.  Maybe the reason there isn't much benefit is because IPC is always doing a full read of the file so there are no real gaps.  Though if we want to start optimizing for partial reads I think there is more we'd have to do than just coalesce.

So maybe a "close, but reopen and investigate further if there is a compelling use case".

**Comment by lidavidm** [comment]
Makes sense. I would also guess that record batches are also generally large enough that there's no need for further coalescing, unlike Parquet where the column-chunk granularity makes coalescing a highly effective optimization.

**Pull request closed without merging**
