### PR TITLE
ARROW-15671: [GLib] Generate vapi for Vala community 

### PR DESCRIPTION
**Pull request by taozuhong**

### CODE REVIEW

**Comment by kou** [comment]
Thanks.
Could you also add sample programs for all modules written in Vala to `c_glib/example/vala/`?

**Comment by taozuhong** [comment]
It's a huge project, I'm not sure that I have time to do it.

**Comment by kou** [comment]
@github-actions crossbow submit -g linux

**Comment by kou** [comment]
It seems that we can't use Crossbow, our CI tool, with `master` branch.
I'll create a new branch and open a new pull request for this.

**Comment by kou** [comment]
Closed in favor of #12993.

**Pull request closed without merging**
