### PR TITLE
ARROW-12103: [C++] Correctly handle unaligned access in bit-unpacking code

### PR DESCRIPTION
**Pull request by pitrou**
Found by the ubuntu-r-sanitizer job.

### CODE REVIEW

**Review by lidavidm — APPROVED** [review]
I can't claim to really understand the SIMD code, but using SafeLoad everywhere does make it consistent with the non-vectorized version.

**Comment by nealrichardson** [comment]
@github-actions crossbow submit test-ubuntu-18.04-r-sanitizer

**Review by cyb70289 — APPROVED** [review]

**Comment by cyb70289** [comment]
Sanitizer test has succeeded. CI failure is not related. Will merge.

**Comment by pachamaltese** [comment]
just to check a result:
@github-actions crossbow submit test-ubuntu-18.04-r-sanitizer

**Comment by cyb70289** [comment]
@github-actions crossbow submit test-ubuntu-18.04-r-sanitizer

**Pull request closed without merging**
