### PR TITLE
ARROW-17498: [CI] Fix build failure when tests are not specified on Spark integration tests

### PR DESCRIPTION
**Pull request by raulcd**

### CODE REVIEW

**Comment by raulcd** [comment]
@github-actions crossbow submit test-conda-python*spark*

**Comment by raulcd** [comment]
I've validated that with this change we are running the same amount of tests on spark master than we were running before it started failing:
`Total number of tests run: 84`
This is the latest successful Nighly job: https://github.com/ursacomputing/crossbow/runs/7935265982

**Comment by raulcd** [comment]
@jorisvandenbossche I am not entirely sure who could take a look on this fix for the nightly failure on the spark master test.

**Comment by kou** [comment]
@kiszk You may want to review this as an Apache Spark committer.

**Comment by kiszk** [comment]
@kou Thanks, I will see it  
cc @BryanCutler

**Comment by raulcd** [comment]
Thanks! Giving a little bit of context for the reviewers. Our nightly builds for spark master started failing when [this commit](https://github.com/apache/spark/commit/3ed382f391911ec4a79fb204f4986728017dfa4a) was merged on spark, with the following error:
```
Testing Spark:
org.apache.spark.sql.execution.arrow
org.apache.spark.sql.execution.vectorized.ColumnarBatchSuite
org.apache.spark.sql.execution.vectorized.ArrowColumnVectorSuite
Using `mvn` from path: /spark/build/apache-maven-3.8.6/bin/mvn
[WARNING] format.skipSources set, ignoring main directories
[WARNING] format.skipTestSources set, ignoring validateOnly directories
[WARNING] No sources specified, skipping formatting
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M7:test (test) on project spark-parent_2.12: No tests matching pattern "none" were executed! (Set -Dsurefire.failIfNoSpecifiedTests=false to ignore this error.) -> [Help 1]
```
Here the link to the CI failure [test-conda-python-3.9-spark-master](https://github.com/ursacomputing/crossbow/runs/7942893732?check_suite_focus=true)
This change fixes the issue as prompted on the error message. I have validated that the same amount of tests are executed as previous nightly builds that were successful.

**Comment by raulcd** [comment]
I've just realised that this commit was reverted on spark master: https://github.com/apache/spark/commit/b6192126351ea2ae658e2f0cfd8c57baf3f1d900 that's why tonight's nightly build was successful.

**Comment by BryanCutler** [comment]
> I've just realised that this commit was reverted on spark master: https://github.com/apache/spark/commit/b6192126351ea2ae658e2f0cfd8c57baf3f1d900 that's why tonight's nightly build was successful.

So can this issue be closed or do we still need the additional option?

**Comment by kiszk** [comment]
@raulcd Thank you very much for tracking the latest changes in Spark. Which URL is the latest successful log? It would be good to note here for future reference.

Then, we could close this issue.

**Comment by raulcd** [comment]
Thanks everyone! 
I am closing the issue but will keep an eye in case it fails again when the dependencies are upgraded on the spark side:
This is the successful nightly build from tonight:
- [test-conda-python-3.9-spark-master](https://github.com/ursacomputing/crossbow/runs/7985493881?check_suite_focus=true)

**Pull request closed without merging**
