### PR TITLE
ARROW-1606: [Python] Copy .lib files in addition to .dll when bundling libraries for Windows

### PR DESCRIPTION
**Pull request by wesm**
I don't have access to a Windows machine at the moment to try this out locally. I will try from wesm/arrow-dist on Appveyor in the meantime

### CODE REVIEW

**Comment by wesm** [comment]
Appveyor build to test this out: https://ci.appveyor.com/project/wesm/arrow-dist/build/1.0.5

I will take a look at the wheels when it completes and make sure both the .lib and .dll files are there

**Review by xhochy — CHANGES_REQUESTED** [review]
This is not enough sadly. The generated wheel does not include the necessary libs. The bundling is a two-step process. We need the same code in the CMakeLists.txt also.

**Comment by wesm** [comment]
Ah you're right. Let me take a look

**Comment by wesm** [comment]
Shoot, I'm out of time to work on this right now. I'll have access to a Windows machine to develop this locally tonight

**Comment by wesm** [comment]
OK, I think this should do it, hopefully I didn't mess something up

**Review by xhochy — APPROVED** [review]
+1, verified that the `lib` files are included in the wheel

**Pull request closed without merging**
