### PR TITLE
ARROW-3469: [Gandiva] Add gandiva travis OSX entry

### PR DESCRIPTION
**Pull request by pravindra**

### CODE REVIEW

**Comment by wesm** [comment]
@pravindra @pitrou @kszucs @xhochy we don't have to do it in this PR, but I would like to propose the following:

* Split the current C++ build into 2 builds: one for C++ and another for Python
* Test all C++ including Gandiva in a single CI entry
* Ensure that code coverage data is uploaded consistently

Does this sound good? If so, let's create JIRA issues to capture the work

**Comment by pravindra** [comment]
> On Oct 16, 2018, at 12:27 AM, Wes McKinney <notifications@github.com> wrote:
> 
> @pravindra <https://github.com/pravindra> @pitrou <https://github.com/pitrou> @kszucs <https://github.com/kszucs> @xhochy <https://github.com/xhochy> we don't have to do it in this PR, but I would like to propose the following:
> 
> Split the current C++ build into 2 builds: one for C++ and another for Python
> Test all C++ including Gandiva in a single CI entry
> Ensure that code coverage data is uploaded consistently
> Does this sound good? If so, let's create JIRA issues to capture the work
> 
> 

Sounds good. Couple of things :

1. Till we fix ARROW-3501, gandiva can build only with gcc 4.9. Is that ok ?
2. What should we do for java ? Single CI entry for arrow and gandiva, or different ones ?
    - The gandiva build for java requires cpp library to be built

**Comment by pitrou** [comment]
@wesm There are several C++ / Python jobs already. Should they all be split? We might want to cut down on the number of jobs at some point (or perhaps move independent implementations to separate repos).

**Comment by kszucs** [comment]
That sounds reasonable to me. It's a more straightforward way to separate builds - at first I was surprised that there is no python entry in the travis matrix.

**Comment by wesm** [comment]
> perhaps move independent implementations to separate repos

We should discuss this on the mailing list. I am against breaking up the monorepo -- I think that we should scale our process using tools that we develop rather than conforming to the objectively crude affordances of Travis CI and Appveyor. Implementations that are independent now may not be so in the future by the nature of the project -- any implementation could integrate with Gandiva, for example, and that would become much more difficult to develop if the code is fragmented in multiple repositories.

**Comment by pravindra** [comment]
abandoning this request - building a fresh one on top of the changes for ARROW-3472

**Comment by pravindra** [comment]
Closing this PR. will open a fresh one on top of the changes for ARROW-3472.

**Pull request closed without merging**
