### PR TITLE
ARROW-3885: [Rust] Release prepare step should increment Rust version

### PR DESCRIPTION
**Pull request by andygrove**

### CODE REVIEW

**Comment by wesm** [comment]
I wonder if this is something we could automate as part of the release process.

**Comment by andygrove** [comment]
I will attempt to do that ... looks like it is easy enough with `sed`

**Comment by wesm** [comment]
@kou I agree with you. One complexity is that we need to be able to produce development version numbers using setuptools_scm when building the Python wheels. Feel free to open a JIRA and we can discuss

**Comment by kou** [comment]
I've opened https://issues.apache.org/jira/browse/ARROW-3938 for general version update.

**Comment by andygrove** [comment]
@wesm @kou This is ready for review again

**Comment by kou** [comment]
Thanks. CI is green. But GitHub says "This branch cannot be rebased due to conflicts". I'll rebase on master again.

**Review by kou — APPROVED** [review]
CI is green.
I'll merge this.

**Pull request closed without merging**
