### PR TITLE
ARROW-2875: [Packaging] Don't attempt to download arrow archive in linux builds

### PR DESCRIPTION
**Pull request by kszucs**
Waiting for the [linux builds](https://github.com/kszucs/crossbow/branches/all?utf8=%E2%9C%93&query=build-238)...

### CODE REVIEW

**Comment by kou** [comment]
It may not be a good change.
I think that we should use the official source archive for released package instead of building a source archive for packaging.

BTW, if we don't use the official source archive at www.apache.org, we should remove related codes instead of commenting out them.

**Comment by kou** [comment]
I read https://cwiki.apache.org/confluence/display/ARROW/Release+Management+Guide .
In our release process, we release the official source archive by `dev/release/02-source.sh` then we release other packages such as packages for Java and Python. So I think that we can download the official source archive from www.apache.org.

**Comment by wesm** [comment]
We should have a way to switch between development builds (use snapshots from git) and release builds (use apache.org source archive from the dist system)

**Comment by kszucs** [comment]
I'm creating a jira ticket for this.

**Comment by kou** [comment]
I've created #2295. Can we close this pull request?

**Comment by kou** [comment]
> I think We should enable `building from source archive` feature for all of the builds, including conda, wheel etc.

Ah, I missed it. I considered only .deb/.rpm. Sorry. I agree with you. 

> How about adding a new target in crossbow, to build (and verify) apache source archives instead of a git repository?

It looks good to me. #2295 will help it. If we specify `ARROW_VERSION=0.10.0`, `ARROW_VERSION=0.10.0-rc1` and so on, .deb/.rpm building tasks download a source archive and use it.

**Comment by kszucs** [comment]
@wesm thoughts? I'm planning something like:

`python crossbow.py submit --from-archive --version 0.10.0` 
or 
`python crossbow.py submit --from-archive <apache resource link>` (need to parse version number)

**Comment by kszucs** [comment]
ping @wesm

**Comment by wesm** [comment]
I think it would be OK to build the packages for the release vote from the git tag. Using the source tarball from the dist system seems like overkill.

**Comment by wesm** [comment]
like `python crossbow submit --tag apache-arrow-0.10.0`

**Comment by kszucs** [comment]
Currently crossbow does this implicitly if that tag is checked out in the local arrow repository.
However this conflicts with @kou's recent PR https://github.com/apache/arrow/pull/2295

**Comment by kszucs** [comment]
I mean, it's easier to just checkout the tag's commit like crossbow currently does and simply don't let the rake task to download the archive.
What's the exact advantage of building from apache archive? We can be sure that all of the binaries are using the same `official` source (which is more of less guaranteed by git currently)?

**Comment by wesm** [comment]
It's more "proper" from an ASF perspective in that we have some validation that all the packages can be produced correctly using the signed+released source archive. From the ASF point of view, the git repo is merely an implementation detail, the source artifact is the only "true" way to come by the software

**Comment by kszucs** [comment]
Ok, convinced me.

**Comment by kszucs** [comment]
@wesm @cpcloud If We're settled with git builds, then We should fix the linux tasks.

With `0.9.1` it works according to the latest nightly build: https://github.com/kszucs/crossbow/branches/all?utf8=%E2%9C%93&query=nightly

With `0.10.0` tag, linux builds attempt to download the archive instead of using the git repository: https://travis-ci.org/kszucs/crossbow/builds/409932367

This is why I've submitted this PR. 
Meanwhile I'm moving forward with the source builds, but that involves more work.

**Comment by wesm** [comment]
At this point we should take the shortest path to being able to release. Otherwise we're going to miss the window to release this week (realistically a good RC needs to go out by EOD Wednesday at very latest)

**Comment by kszucs** [comment]
Ok, testing the linux build with this change. I'll let You know whether it works or not (last time it worked).

**Comment by kszucs** [comment]
Seems like it's working, but I want to wait a full build: https://github.com/kszucs/crossbow/tree/build-295 too

**Comment by cpcloud** [comment]
I'll be monitoring this and merging as soon as all of the package builds look green.

**Comment by cpcloud** [comment]
The remaining builds are here: https://github.com/kszucs/crossbow/branches/all?page=1&query=build-297&utf8=%E2%9C%93

**Comment by cpcloud** [comment]
@kou can you answer @kszucs's question here when you have a chance?

**Comment by kou** [comment]
`0.10.0rc1` isn't good because `0.10.0rc1` is placed after `0.10.0` by ASCII sort. (`0.10.0~rc1` is the best.)
But we can fix it after we release 0.10.0. Because normal users don't use 0.10.0rc1. And we can resolve the version number problem by just removing rc packages.

**Comment by cpcloud** [comment]
Ok then I will merge on all packages green.

**Comment by cpcloud** [comment]
This one appears to have failed, but looks spurious: https://travis-ci.org/kszucs/crossbow/builds/410026051?utm_source=github_status&utm_medium=notification

**Comment by kou** [comment]
I want to revert `dev/tasks/linux-packages/Rakefile` change after we release 0.10.0.
We don't need the change by #2323 work.

**Comment by cpcloud** [comment]
Merging.

**Comment by kszucs** [comment]
@kou Definitely, this is just a short term fix, because #2323 would probably delay the release.

**Pull request closed without merging**
