### PR TITLE
ARROW-2498: [Java] Use java 1.8 instead of java 1.7

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by xhochy** [comment]
@siddharthteotia @BryanCutler @jacques-n Is this ready to be merged?

**Review by BryanCutler — APPROVED** [review]
+1

**Comment by BryanCutler** [comment]
Also cc @icexelloss .  I'll commit this later today if no more comments.

**Comment by BryanCutler** [comment]
merged to master, thanks @agrove-rms !

**Pull request closed without merging**
