### PR TITLE
ARROW-12267: [Rust] Implement support for timestamps in JSON writer

### PR DESCRIPTION
**Pull request by alamb**
# Rationale
I want to write timestamps to JSON (e.g. https://github.com/influxdata/influxdb_iox/pull/1104) and when I did so I got a panic :)

When I tried to write a`TimestampNanosecondArray` I got the following error:

```
thread 'influxdb_ioxd::http::tests::test_query_json' panicked at 'Unsupported datatype: Timestamp(
    Nanosecond,
    None,
)', /Users/alamb/.cargo/git/checkouts/arrow-3a9cfebb6b7b2bdc/3e825a7/rust/arrow/src/json/writer.rs:326:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

# Changes
Add support for `DataType::Timestamp`, and tests for same

I did not add support for the other date / time / duration types, but instead filed a ticket to add such support: https://issues.apache.org/jira/browse/ARROW-12317

### CODE REVIEW

**Comment by alamb** [comment]
FYI @houqp

**Review by houqp — APPROVED** [review]
Good timing, I am planning to work on support for Date32 and other date related data types this weekend :)

I am thinking of adding an option to return these type of values as numbers instead of human readable strings for better ser/de performance, what do you think about that?

**Comment by alamb** [comment]
> I am thinking of adding an option to return these type of values as numbers instead of human readable strings for better ser/de performance, what do you think about that?

@houqp  I think an option for such behavior is a reasonable idea.

One question I have is if dates / timestamps / etc are produced as numbers, how would the other side know what type to use? 

Like if we made JSON like this:
```
{
  "name": "foo",
  "time": 1234456788
}
```

Is `time` a `Timestamp`? A `Time`? a `u64`? something else?

**Comment by houqp** [comment]
The caller would need to obtain the response schema first, in most cases, the schema should be static. In case of API responses, it would be part of the API spec.

I would expect most of the users to use the string encoded format and only resort to numbers for performance critical use-cases. For example, in Airflow, by changing the column type from string encoded date time to timestamp numbers, we reduced the frontend load time by almost 90% :)

**Comment by alamb** [comment]
@houqp  thanks -- that makes sense. Sending timestamps encoded as strings is definitely not a good idea for performance :)

**Pull request closed without merging**
