### PR TITLE
ARROW-16737: [C++] Bump vendored version of zstd

### PR DESCRIPTION
**Pull request by raulcd**

### CODE REVIEW

**Comment by raulcd** [comment]
@github-actions crossbow submit -g cpp

**Comment by raulcd** [comment]
@github-actions crossbow submit -g cpp

**Comment by pitrou** [comment]
CI failures look unrelated. @raulcd Is there a reason this PR is still a draft?

**Comment by raulcd** [comment]
> CI failures look unrelated. @raulcd Is there a reason this PR is still a draft?

I was just waiting for a bunch of the errors to be resolved on master to rebase and ensure this does not add more noise to the current failures but apart from that, there's no real reason. I am marking it as ready for review.

**Pull request merged**
