### PR TITLE
ARROW-10940: [Rust] Extend sort kernel to ListArray

### PR DESCRIPTION
**Pull request by waynexia**
This supports sort on `GenericListArray` and `FixedSizeListArray`.

### CODE REVIEW

**Comment by waynexia** [comment]
There are some points I'm not very clear about:
1. Ordering. I didn't find a definition of `List` in the documentation or CPP implementation. So I use something like lexicographical order (refer to `sort_list()` in sort.rs) to compare two lists. Please let me know if I missed anything about the ordering's definition.
2. Nulls. It seems that nulls element in list array is different than [documentation](http://arrow.apache.org/docs/format/Columnar.html#variable-size-list-layout). As `From<ArrayData>` requires buffers number should be 1 (0 in `FixedSizeListArray`) which is not the same as the spec. It says that variable sized list has two buffers for "validate bitmap" and "offsets". In the current implementation validate bitmap is placed in `ArrayData`'s `null_bitmap`. I think nullable array in `List` cannot be represented in this way?

**Comment by jorgecarleitao** [comment]
Hi @waynexia . Thanks a lot for this. I think that the idea of a list_sort is a bit different: in the test you wrote, it would correspond to:

```
            vec![
                Some(vec![1, 0]),
                Some(vec![4, 3, 2, 1]),
                Some(vec![2, 3, 4]),
                Some(vec![3, 3, 3, 3]),
                Some(vec![1, 1]),
            ],
            Some(SortOptions {
                descending: false,
                nulls_first: false,
            }),
            vec![
                Some(vec![0, 1]),
                Some(vec![1, 2, 3, 4]),
                Some(vec![2, 3, 4]),
                Some(vec![3, 3, 3, 3]),
                Some(vec![1, 1]),
            ],
```

i.e. it is a operator that operates on the individual entries of the array, and sorts them individually. This would correspond to the `array_sort` operator in Spark: https://spark.apache.org/docs/latest/api/sql/index.html#array_sort

**Comment by waynexia** [comment]
Thanks for your reply @jorgecarleitao. Sorry for the incorrect understand I've made. 

So the required `list_sort` is not part of `Sort( ArrayRef )` in `sort.rs` which will rearrange the given array. But a method of `ListArray` that performs `Sort` on each underlying sub-array, right?

And then where do you think is a proper place to put `list_sort`, a separate file under `compute/kernel` or as a member function of `ListArray`, or someplace else. Please let me know what do you think :raised_hands:

BTW, is the current implementation that rearranges the input array needed to be part of `Sort`?

**Comment by waynexia** [comment]
> There are some points I'm not very clear about ...

For the first one, thanks to @jorgecarleitao. This is not a problem that should be considered when implementing `list_sort`.

For the second point, I find some examples and think I can make it clear. `List Array` is an (at least) two-level ArrayData with `valids_bitmap` on each level to represent nulls in `List` itself and its child data.

**Comment by jorgecarleitao** [comment]
FWIW, I find it useful to go through the array equality code whenever I need to remember how an array is described, because, in the end, the equality is the operator that will dictate how the expected and observed results match.

**Comment by waynexia** [comment]
> FWIW, I find it useful to go through the array equality code whenever I need to remember how an array is described, because, in the end, the equality is the operator that will dictate how the expected and observed results match.

Thanks, this is really helpful for me!

And one more thing, what about this: 
> BTW, is the current implementation that rearranges the input array needed to be part of Sort?

**Comment by jorgecarleitao** [comment]
@waynexia , good question. In general, yes: arrow arrays are immutable and thus we can't sort them in place. Therefore, we use two steps:

1. get the index array that would sort the array
2. `take` items from the array according to said indexes

The second point is where we "re-arrange" the array.

Sorry for the delay and keep the questions coming if you have them. :)

**Comment by waynexia** [comment]
Hi @jorgecarleitao，very appreciate your clear explanation! But I am sorry that I don't seem to describe it very well, please allow me to explain my question again.

The code in this PR does not implement `list_sort`, but another function that sorts (so-called rearrange) the subarray of the List Array level (maybe this is part of the "sort" kernel?). 

And the point is while implementing the functionality required by `list_array`, does this current code need to be preserved and moved forward? Thanks for your time ☺

**Comment by waynexia** [comment]
I found `SortExec` in `datafusion/physical_plan/sort.rs`, is it requested by ARROW-10355?

One thing that may matter is `SortExec` requires every individual entry to be of the same length, unlike this [example](https://github.com/apache/arrow/pull/8856#issuecomment-739675217)

**Comment by jorgecarleitao** [comment]
Hi @waynexia , ahh, got it.

It could be interpreted as such, yes: this PR is the implementation of a `sort` of a `ListArray`, based on the lexicographic order of the individual items on the list (a bit like how a `string` also has a natural order based on the individual items).

If you want please file a new issue on Jira for that, and let's review this PR based on that (in which case `sort` is the right place to put it).

**Comment by waynexia** [comment]
Okay, thanks for your help. I filed ARROW-10940 for this PR.

There are some works to do like support fixed-size list and i64 indices type. I'll finish it in a few days :)

**Comment by waynexia** [comment]
Hi @jorgecarleitao @nevi-me, I think this is ready for review. Could you please take a look and let me know what do you think about this? Thanks!

**Comment by nevi-me** [comment]
Hi @waynexia, thank you for taking this on, and I apologise for the delay, I haven't had enough time to review PRs.

I suggest that we keep the `list_sort` in the sort kernel for now. We already have other ListArray-specific kernels like `ListArray::contains(PrimitiveArray)` in the other kernel modules, so we can keep to that practise for now. @jorgecarleitao do you concur?

We can later move all ListArray-specific functions to a separate module.

I'll review this over the weekend.

**Comment by waynexia** [comment]
> I suggest that we keep the list_sort in the sort kernel for now.

Hi @nevi-me, thanks for your reply. From my understanding, `list_sort` is not implemented in this pr. To avoid ambiguity, let me say that `list_sort` stands for an operator in `DataFusion`, and this pr implements the `ListArray` part of the `sort` kernel. Am I right @jorgecarleitao?

> We can later move all ListArray-specific functions to a separate module.

I agree with this.

**Comment by nevi-me** [comment]
Hey @waynexia, I understand. It's effectively `array_sort` at https://github.com/nevi-me/rust-dataframe/blob/d4ae4ae6a2541b6625e702a350bb08efe42d6975/src/functions/array.rs#L328 , right?

**Comment by waynexia** [comment]
Yes, I think ARROW-10355 requests something like that. But I didn't understand it clearly at the beginning and made this "wrong" PR :stuck_out_tongue:

**Review by jorgecarleitao — APPROVED** [review]
LGTM. Thanks a lot @waynexia for your patience, persistence and hard work here. Really appreciated!

I do not have any comments: the PR looks agood as is, and the tests cover it in depth.

**Comment by waynexia** [comment]
Appreciate you too @jorgecarleitao, this cannot be done without your help.

**Pull request closed without merging**
