### PR TITLE
GH-40318: [C++][Docs] Add documentation of array factories

### PR DESCRIPTION
**Pull request by vyasr**
### Rationale for this change

These factory functions are generally useful and available, so documenting them helps external users find them without having to search the source code.

### What changes are included in this PR?

This PR adds the array factories in arrow/array/util.h into a doxygen group for array factories and adds that group to the Sphinx C++ API documentation.

### Are these changes tested?

I built the docs locally to verify.

### Are there any user-facing changes?

Nothing to the API, only docs.

* GitHub Issue: #40318

### CODE REVIEW

**Comment by vyasr** [comment]
Question, are there bots set up to close the associated issue when this PR merges? Normally I would comment with one of Github's recognized keywords (Closes #X) but I'm guessing that's not necessary here.

**Comment by vyasr** [comment]
The CI test failures look odd and unrelated to the changeset.

**Comment by kou** [comment]
@github-actions crossbow submit preview-docs

**Comment by kou** [comment]
> Question, are there bots set up to close the associated issue when this PR merges? Normally I would comment with one of Github's recognized keywords (Closes #X) but I'm guessing that's not necessary here.

We'll do it by our merge script: https://github.com/apache/arrow/blob/main/dev/merge_arrow_pr.py

So you don't need to do anything.

**Comment by vyasr** [comment]
Looks like the [Cython 3.0.9 release yesterday](https://cython.readthedocs.io/en/latest/src/changes.html#id2) broke the Python build. I can open a separate issue.

**Comment by vyasr** [comment]
Following up on #40386 and #40387

**Comment by pitrou** [comment]
@github-actions crossbow submit preview-docs

**Review by pitrou — APPROVED** [review]
Good addition to the docs, thank you!

**Pull request merged**
