### PR TITLE
ARROW-9462:[Go] The Indentation after the first Record in arrjson writer is incorrect

### PR DESCRIPTION
**Pull request by fredgan**

### CODE REVIEW

**Comment by fredgan** [comment]
@sbinet

**Review by sbinet — COMMENTED** [review]
Thanks.
Perhaps add a little test to make sure no regression sneaks in?

**Comment by fredgan** [comment]
@sbinet Hi Sebastien, I agree. 
But should I just compare `makeNullRecords` output json file with the expected output json? It looks not so "perfect" because there are 12 cases. Or you have any other idea suggested to me?

**Comment by sbinet** [comment]
(apologies: I don't get notifications when a commit is force-pushed, and also I am on holidays with spotty internet access)
I'd say just create a minimal dataset to go through the mechanics of your indentation improvement.

I see you've went the extra mile and generated a bunch of XyzPrettyJsons tests.
perhaps just one with an array of int64s would suffice? (or 2: one with an array of primitives, another with an array of structs?)

**Comment by fredgan** [comment]
@sbinet  Well, I considered about it. 

But in my eyes, it's not only for regression of indentation, but also for the other parts of json serialization.

There is another benefit that we can read the arrow data by json for whom are not familiar to Arrow.

**Comment by fredgan** [comment]
@sbinet OK, good point. I renamed them, and moved them to `arrjson_test.go`.

**Review by sbinet — APPROVED** [review]

**Pull request closed without merging**
