### PR TITLE
ARROW-3045: [Python] Remove nullcheck from ipc Message and MessageReader

### PR DESCRIPTION
**Pull request by kszucs**

### CODE REVIEW

**Comment by kszucs** [comment]
@pitrou Just wanted to ask, what's the advantage of separating `ipc.pxi` and `ipc.py`?

**Comment by crepererum** [comment]
@kszucs can you please state in the ticket or in the commit message why this check can be removed? (or why it was there in the first place?)

**Comment by kszucs** [comment]
@cerebrodata Sure, updated the jira ticket's description.

**Comment by kszucs** [comment]
`Go` step fails on travis.

**Comment by wesm** [comment]
I'm responsible. I don't know that I necessarily see the advantage of Cythonizing bigchunks of public API boilerplate if they aren't performance sensitive; the idea was the minimize reduce generated code size and in some cases make debugging / pdb stepping easier

**Review by wesm — APPROVED** [review]
+1

**Pull request closed without merging**
