### PR TITLE
ARROW-15186: [C++][Python][Docs] Add hierarchy to compute docs, then sort alphabetically

### PR DESCRIPTION
**Pull request by bkmgit**

### CODE REVIEW

**Comment by bkmgit** [comment]
@lidavidm Review would be helpful

**Comment by pitrou** [comment]
I don't think it makes sense to sort these alphabetically. For example, "Compute Options" ends up buried in the middle of function lists. Instead, we should keep them categorized and ordered logically.

**Comment by lidavidm** [comment]
Agreed with Antoine. The sort order might be improved, but we should keep options separate, keep arithmetic functions grouped, etc. (perhaps we need another level of hierarchy)

**Comment by bkmgit** [comment]
Ok, can add another level of hierarchy

**Comment by bkmgit** [comment]
@pitrou @lidavidm  Maybe the following is ok as a hierarchy? The aim is to clarify the current ordering. The comparison functions can have a link from the string section to the numeric section.

# Compute Functions
## 1. The Generic Compute API
###  a. Functions and function registry
###  b. Input shapes
###  c. Invoking functions
## 2. Implicit casts
###  a. Common numeric type
## 3. Supported Type Categories
## 4. Reduction functions
####  I. Aggregations
####  II. Grouped by aggregations ("group by")
## 5. Element-wise ("scalar") functions
###  a. Mathematical functions
#### I. Arithmetic functions
#### II. Bit-wise functions
#### III. Comparison functions
#### IV. Logarithmic functions
#### V. Logical functions
#### VI. Rounding functions
#### VII. Trigonometric functions
###  b. String functions
#### I. Comparison functions
#### II. String component extraction
#### III. String joining
#### IV. String padding
#### V. String predicates
#### VI. String slicing
#### VII. String splitting
#### VIII. String transforms
#### IX. String trimming
###  c. Other functions
#### I. Conversions
#### II. Containment tests
#### III. Categorizations
#### IV. Selecting / multiplexing
#### V. Structural transforms
### e. Temporal functions
#### I. Temporal component extraction
#### II. Temporal difference
#### III. Timezone handling
## 4. Array-wise ("vector") functions
#### I. Associative transforms
#### II. Selections
#### III. Sorts and partitions
#### IV. Structural transforms

**Comment by bkmgit** [comment]
The above is for C++, can use something similar for Python, but not all the categories are the same.

**Comment by edponce** [comment]
Maybe this hierarchical organization can be mimicked in the compute folder/files structure to better compartmentalize functions.

**Comment by amol-** [comment]
Closing because it has been untouched for a while, in case it's still relevant feel free to reopen and move it forward 👍

**Pull request closed without merging**
