### PR TITLE
ARROW-17949: [C++][Docs] Remove the use of clcache from Windows dev docs

### PR DESCRIPTION
**Pull request by AlenkaF**

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
Do we still want to mention something about that you can use ccache instead?

**Comment by assignUser** [comment]
It would also be possible to use [sccache in local storage mode](https://github.com/mozilla/sccache#local), they explicitly support windows. For our cmake to use sccache in local mode you HAVE to set `SCCACHE_DIR` as it is ignored otherwise.

**Comment by AlenkaF** [comment]
I added info about the possible use of `sccache` in local storage mode: https://github.com/apache/arrow/pull/14529/commits/f3b583ac643828cf7f2fd0d3aba92c9875689732

@assignUser do you mind reviewing please?

**Comment by assignUser** [comment]
@github-actions crossbow submit preview-docs

**Comment by assignUser** [comment]
http://crossbow.voltrondata.com/pr_docs/14529

**Review by assignUser — APPROVED** [review]

**Pull request merged**
