### PR TITLE
ARROW-6773: [C++] Fix filter kernel when filtering with a boolean Array slice

### PR DESCRIPTION
**Pull request by nealrichardson**

### CODE REVIEW

**Review by bkietz — APPROVED** [review]

**Comment by nealrichardson** [comment]
Travis passing on my fork: https://travis-ci.org/nealrichardson/arrow/builds/592762538

**Comment by nealrichardson** [comment]
Appveyor failure is something with installing glib? https://ci.appveyor.com/project/ApacheSoftwareFoundation/arrow/builds/27837139/job/kcgd1nufrsgcjqf0

**Comment by bkietz** [comment]
It does look unrelated. I'll try restarting it to see if it evaporates

**Comment by nealrichardson** [comment]
I already restarted it (well, requested to restart it, so now it's in the queue again)

**Comment by nealrichardson** [comment]
Appveyor failed again but this also seems to be failing on master. @kou do you know what's up with https://ci.appveyor.com/project/ApacheSoftwareFoundation/arrow/builds/27840001/job/tgnp57wisjvhyf9a? 

```
An error occurred while installing glib2 (3.3.7), and Bundler cannot continue.
Make sure that `gem install glib2 -v '3.3.7' --source 'https://rubygems.org/'`
succeeds before bundling.
```

**Comment by kou** [comment]
This is not a Apache Arrow problem.
This is a glib2 gem problem. I'll fix it soon. Please ignore this for now.

**Comment by kou** [comment]
#5572 will solve this.

**Comment by kou** [comment]
#5572 has been merged.
Rebasing will solve this problem.

**Comment by bkietz** [comment]
In that case I'm merging this

**Pull request closed without merging**
