### PR TITLE
ARROW-10735: [R] Remove arrow-without-arrow wrapping

### PR DESCRIPTION
**Pull request by nealrichardson**
Key features: 

* if arrowExports.* are not modified, they are not rewritten. This means that if there are no cpp changes, then nothing gets recompiled, which makes local dev faster (when you have ARROW_R_DEV=true set)
* refactoring of codegen.R to be more consistently aware of "features" that can be flagged, like we have currently for `arrow` and `s3` and potentially may get more of in the future with additional build-time features. Importantly, the wrapping with the fake implementation that we currently have for all functions has been encapsulated in such a way that we can choose whether to make some features always on or not. 

A single commit (https://github.com/apache/arrow/pull/9209/commits/a963e7c63de84dd0693b46773e733f8a03cf58f8) adds an `if` statement that effectively removes the arrow-without-arrow wrapping while still keeping S3 support optional (-2,795 lines of code). 

IMO we should go with this for a while, and if there is no further problems, we can remove the `ARROW_R_WITH_ARROW` flags everywhere. Or if we decide to change our minds, we just remove the `if` statement in codegen.R, nothing else to restore.

In order to fully remove the flagging, we'd need to remove all occurrences of `ARROW_R_WITH_ARROW` and also the special test handling of this, which includes another environment variable that is set in CI.

### CODE REVIEW

**Comment by nealrichardson** [comment]
@benchmark me

**Comment by ElenaHenderson** [comment]
test

**Comment by jonkeane** [comment]
LGTM

**Comment by nealrichardson** [comment]
I've made ARROW-11392 for the final removal of the arrow-without-arrow flagging

**Pull request closed without merging**
