### PR TITLE
ARROW-12217: [C++] Cleanup cpp examples source files naming

### PR DESCRIPTION
**Pull request by cyb70289**
Replace hyphon with underscore.

### CODE REVIEW

**Comment by cyb70289** [comment]
In case CI doesn't build these examples. I tested with `-DARROW_BUILD_EXAMPLES=ON -DARROW_COMPUTE=ON -DARROW_PARQUET=ON -DARROW_DATASET=ON -DPARQUET_REQUIRE_ENCRYPTION=ON -DPARQUET_BUILD_EXAMPLES=ON`, and see all examples built correctly.

**Comment by kou** [comment]
@github-actions crossbow submit -g nightly

**Comment by cyb70289** [comment]
Valgrind test failed for hash aggregate kernel: https://github.com/ursacomputing/crossbow/runs/2276204020?check_suite_focus=true#step:6:3029
Not related to this patch, but it looks like a bug need fix.

**Review by kou — APPROVED** [review]
+1

Thanks!

**Pull request closed without merging**
