### PR TITLE
ARROW-5349: [C++][Parquet] Add method to set file path in a parquet::FileMetaData instance

### PR DESCRIPTION
**Pull request by wesm**
This is an RFC based on the discussion ongoing. If this seems like the accepted approach I'll add a Python unit test

### CODE REVIEW

**Comment by wesm** [comment]
@rjzamora

**Comment by rjzamora** [comment]
@wesm Thanks for putting this PR  together!  I am pretty sure that this is exactly the solution we want/need - I just pulled the code and everything behaves exactly the way I want it to.

I'm really sorry for missing this simple solution myself!  I had completely missunderstood a few important details about the thrift/parquet interface.

**Review by xhochy — APPROVED** [review]
+1, LGTM

This should be independent of the ML thread onto where to set the file path.

**Comment by wesm** [comment]
This PR wasn't quite finished since the Python side is not tested

**Pull request closed without merging**
