### PR TITLE
ARROW-4192: [CI] Fix broken dev/run_docker_compose.sh script

### PR DESCRIPTION
**Pull request by fsaintjacques**

### CODE REVIEW

**Comment by wesm** [comment]
rebased

**Comment by kszucs** [comment]
We should probably port gen_apidocs to the top level docker-compose and remove these.

**Comment by fsaintjacques** [comment]
I might take a look next week for getting rid of `dev/docker-compose.yml`.

https://issues.apache.org/jira/browse/ARROW-4309
https://issues.apache.org/jira/browse/ARROW-4405
https://issues.apache.org/jira/browse/ARROW-4415

**Comment by fsaintjacques** [comment]
@kszucs I think this can be merged.

**Review by wesm — APPROVED** [review]
+1

**Pull request closed without merging**
