### PR TITLE
ARROW-17982: [C++][Java] Update ORC to 1.8.0

### PR DESCRIPTION
**Pull request by wgtmac**
This PR aims to upgrade ORC to version 1.8.0.

Apache ORC 1.8.0 is the most recent release:
https://github.com/apache/orc/releases/tag/v1.8.0
https://orc.apache.org/news/2022/09/03/ORC-1.8.0

### CODE REVIEW

**Comment by wgtmac** [comment]
Could you please take a look? @kou @pitrou 

Also cc @dongjoon-hyun  @williamhyun

**Comment by kou** [comment]
@github-actions crossbow submit -g nightly-release -g nightly-tests -g nightly-packaging

**Review by kou — APPROVED** [review]
+1

All failures are unrelated.

**Comment by dongjoon-hyun** [comment]
Thank you, @wgtmac and @kou .

**Pull request merged**
