### PR TITLE
ARROW-8832: [Python] Provide better error message when S3/HDFS is not enabled in installation

### PR DESCRIPTION
**Pull request by jorisvandenbossche**

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
@pitrou what would you think of something like this? 

I saw several times users being confused about the typical AttributeError (eg https://github.com/apache/arrow/issues/7443, https://issues.apache.org/jira/browse/ARROW-8832). 
This way, we could provide a more informative error message when pyarrow is not built with support for the specific filesystem (the error message in the PR can be further improved then)

**Comment by jorisvandenbossche** [comment]
Updated.

Of course, now you added S3 support in wheels, this change will be less needed.

**Comment by pitrou** [comment]
Only Linux wheels ;-)

**Comment by jorisvandenbossche** [comment]
Ah, yes ;) Certainly still useful then.

Are you fine with not testing this on CI? (I tested it locally by disabling S3, and in the end it is only a different error message).  
Although writing a test that is skipped when S3 is available is also not that hard, actually.

**Comment by pitrou** [comment]
Yes, it's ok if it's not tested, IMHO.

**Pull request closed without merging**
