### PR TITLE
ARROW-538: [C++] Set up AddressSanitizer (ASAN) builds

### PR DESCRIPTION
**Pull request by xhochy**
Most of the infrastructure was already in place, only needed to fix the gtest build.

We will now build with AddressSanitizer activated on OSX.

### CODE REVIEW

**Review by wesm — APPROVED** [review]
+1, pending green build

**Comment by xhochy** [comment]
@wesm it will fail again. There is some problem with the output of CompilerInfo on Travis, I need the next build to give me the relevant output and I can try to fix from there on.

**Comment by wesm** [comment]
@xhochy you can download Xcode 6.4 and install it alongside your Xcode 8 to help debug. Once you unpack the Xcode.app, rename it to Xcode-6.4.app. I have code in my toolchain setup like

```
function xcode64 {
    export XCODE_ROOT=/Applications/Xcode-6.app/Contents/Developer
    export DEVELOPER_DIR=$XCODE_ROOT
    osx_toolchain
}
```

**Comment by xhochy** [comment]
Turns out that Xcode 6.4 has no support for AddressSanitizer, deactivated again for now on Travis until we move to a newer version.

**Review by wesm — APPROVED** [review]
+1

**Pull request closed without merging**
