### PR TITLE
DO NOT MERGE: Try to reproduce wheel failures

### PR DESCRIPTION
**Pull request by lidavidm**

### CODE REVIEW

**Comment by lidavidm** [comment]
@github-actions crossbow submit wheel-manylinux2014-*-amd64

**Comment by lidavidm** [comment]
@github-actions crossbow submit wheel-manylinux2014-*-amd64

**Comment by jorisvandenbossche** [comment]
For the faulthandler part, I tried this a while ago as well to debug some other segfault in CI, and my conclusion then was that pytest nowadays already does that by default: https://docs.pytest.org/en/7.1.x/how-to/failures.html#faulthandler

**Comment by lidavidm** [comment]
Hmm, interesting, because I don't actually see the traceback in past runs. Possibly there is no Python-side traceback then, in which case hopefully catchsegv grabs it.

**Comment by jorisvandenbossche** [comment]
Yeah, also from local development, my experience is that enabling the python faulthandler module most of the time doesn't actually result in more information being printed (at least when developing arrow, unless I am all the time using it wrongly)

**Comment by lidavidm** [comment]
Ah right, now I remember why catchsegv isn't great. We're building in release mode...

```

Backtrace:
/usr/local/lib/python3.9/site-packages/pyarrow/libarrow.so.1100(+0x17b5bb7)[0x7fed49842bb7]
/usr/local/lib/python3.9/site-packages/pyarrow/libarrow.so.1100(+0x17a1d83)[0x7fed4982ed83]
/usr/local/lib/python3.9/site-packages/pyarrow/libarrow.so.1100(+0x591c6a)[0x7fed4861ec6a]
/usr/local/lib/python3.9/site-packages/pyarrow/libarrow.so.1100(+0x16d882f)[0x7fed4976582f]
/usr/local/lib/python3.9/site-packages/pyarrow/libarrow.so.1100(+0x591c6a)[0x7fed4861ec6a]
/usr/local/lib/python3.9/site-packages/pyarrow/libarrow.so.1100(+0x12d5a94)[0x7fed49362a94]
/usr/local/lib/python3.9/site-packages/pyarrow/libarrow.so.1100(+0x591c6a)[0x7fed4861ec6a]
/lib/x86_64-linux-gnu/libc.so.6(+0x3b4d7)[0x7fed4c6c94d7]
/lib/x86_64-linux-gnu/libc.so.6(+0x3b67a)[0x7fed4c6c967a]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf1)[0x7fed4c6b1d11]
python(_start+0x2a)[0x559a27a1508a]
```

**Comment by lidavidm** [comment]
Reconstructed backtrace on #15054

**Pull request closed without merging**
