### PR TITLE
ARROW-1667: [GLib] Support Meson

### PR DESCRIPTION
**Pull request by kou**

### CODE REVIEW

**Comment by kou** [comment]
I'll try to add a Travis CI configuration for it.

**Comment by xhochy** [comment]
Just for my personal understanding: This will now add Meson as a second build system to the Glib build, autotools is still supported as-is?

**Comment by kou** [comment]
Yes. Because it's difficult to install Meson to old platforms such as Ubuntu 14.04 and CentOS 6. When we drop these platforms support, we only use Meson.

I'll mark Meson as the primary (recommended) build system and GNU Autotools a second build system (for old platforms) in the near future.

**Comment by kou** [comment]
Now, Arrow GLib is buildable with Meson.

**Comment by kou** [comment]
+1

**Comment by wesm** [comment]
Thanks @kou!!

**Pull request closed without merging**
