### PR TITLE
ARROW-14825: [C++] Temporal component extraction function for extracting epiyear

### PR DESCRIPTION
**Pull request by rok**
This is to resolve [ARROW-14825](https://issues.apache.org/jira/browse/ARROW-14825).

### CODE REVIEW

**Comment by rok** [comment]
Would `us_year` be a better name as it's consistent with already present `us_week` name?

**Comment by lidavidm** [comment]
us_year seems to better in that regard. (Looking it up - it turns out "epiweek" means something different in the US vs the rest of the world? Oof.)

**Comment by rok** [comment]
> us_year seems to better in that regard. (Looking it up - it turns out "epiweek" means something different in the US vs the rest of the world? Oof.)

Well we're looking to mirror [lubridate's epiyear](https://lubridate.tidyverse.org/reference/year.html) for our R implementation, see [ARROW-14824](https://issues.apache.org/jira/browse/ARROW-14824).
We could also call it us_epiyear to preventively disambiguate.

**Comment by lidavidm** [comment]
us_epiyear makes sense.

**Comment by rok** [comment]
@lidavidm Switched to `us_epiweek`.

**Comment by lidavidm** [comment]
Ah, the function doc description needs to be line-wrapped.

**Comment by rok** [comment]
Fixed.

**Comment by jorisvandenbossche** [comment]
Should there then also be an equivalent `epiweek` kernel?

**Comment by rok** [comment]
@jorisvandenbossche we currently have `us_week` and `iso_week`. `us_week` is `us_epiyear`-like. We kind of have two camps here - `iso` and `us/epi`. Very much open to suggestions on naming here.

**Comment by jorisvandenbossche** [comment]
OK, I see. For consistency with `us_week`, could then also call it `us_year`? Or is that too vague?

**Comment by jorisvandenbossche** [comment]
The "us_week" was also a new invented name at the time? (or is that used elsewhere)

**Comment by rok** [comment]
> The "us_week" was also a new invented name at the time? (or is that used elsewhere)

So was `assume_timezone`. I suppose we've crossed that threshold. I'll change to `us_year`.

**Comment by rok** [comment]
@jorisvandenbossche done.

**Review by lidavidm — APPROVED** [review]

**Pull request closed without merging**
