### PR TITLE
WIP: [Release] Verify release-17.0.0-rc0

### PR DESCRIPTION
**Pull request by raulcd**
PR to verify Release Candidate

### CODE REVIEW

**Comment by raulcd** [comment]
@github-actions crossbow submit  --group verify-rc-source --param release=17.0.0 --param rc=0

**Comment by raulcd** [comment]
Revision: 741356c06dacfc3e6070443703f6bb1f2e9ffee1

Submitted crossbow builds: [ursacomputing/crossbow @ release-17.0.0-rc0-0](https://github.com/ursacomputing/crossbow/branches/all?query=release-17.0.0-rc0-0)

|Task|Status|
|----|------|
|almalinux-8-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/9845378786/job/27180798616)|
|almalinux-8-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/9845379087/job/27180800416)|
|almalinux-9-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/9845379084/job/27180800316)|
|almalinux-9-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/9845379134/job/27180800759)|
|amazon-linux-2023-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/9845380099/job/27180805571)|
|amazon-linux-2023-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/9845379804/job/27180804180)|
|centos-7-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/9845380190/job/27180806063)|
|centos-8-stream-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/9845378905/job/27180799867)|
|centos-8-stream-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/9845379956/job/27180804219)|
|centos-9-stream-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/9845378825/job/27180799027)|
|centos-9-stream-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/9845378990/job/27180800029)|
|conan-maximum|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/9845380102/job/27180805508)|
|conan-minimum|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/9845378800/job/27180798773)|
|debian-bookworm-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/9845380105/job/27180805734)|
|debian-bookworm-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/9845379372/job/27180801944)|
|debian-trixie-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/9845379094/job/27180800414)|
|debian-trixie-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/9845380123/job/27180805895)|
|java-jars|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/9845380077/job/27180808732)|
|matlab|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/9845379913/job/27180807810)|
|nuget|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/9845378847/job/27180799228)|
|python-sdist|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/9845378804/job/27180798631)|
|r-binary-packages|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/9845379688/job/27180803380)|
|test-debian-12-docs|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/9845379751/job/27180803727)|
|ubuntu-focal-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/9845379767/job/27180803877)|
|ubuntu-focal-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/9845380191/job/27180806283)|
|ubuntu-jammy-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/9845378805/job/27180798907)|
|ubuntu-jammy-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/9845380270/job/27180806675)|
|ubuntu-noble-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/9845379710/job/27180803639)|
|ubuntu-noble-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/tree/release-17.0.0-rc0-0-github-ubuntu-noble-arm64)|
|wheel-macos-big-sur-cp310-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/tree/release-17.0.0-rc0-0-github-wheel-macos-big-sur-cp310-arm64)|
|wheel-macos-big-sur-cp311-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/9845379198/job/27180801097)|
|wheel-macos-big-sur-cp312-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/9845379100/job/27180800537)|
|wheel-macos-big-sur-cp38-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/9845379069/job/27180800174)|
|wheel-macos-big-sur-cp39-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/9845378836/job/27180798917)|
|wheel-macos-catalina-cp310-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/9845379612/job/27180803139)|
|wheel-macos-catalina-cp311-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/9845379595/job/27180803208)|
|wheel-macos-catalina-cp312-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/9845380003/job/27180804841)|
|wheel-macos-catalina-cp38-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/9845379658/job/27180803550)|
|wheel-macos-catalina-cp39-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/9845380106/job/27180805587)|
|wheel-manylinux-2-28-cp310-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/9845379517/job/27180802775)|
|wheel-manylinux-2-28-cp310-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/9845380192/job/27180806083)|
|wheel-manylinux-2-28-cp311-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/9845379166/job/27180801065)|
|wheel-manylinux-2-28-cp311-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/9845378857/job/27180799595)|
|wheel-manylinux-2-28-cp312-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/9845379324/job/27180801905)|
|wheel-manylinux-2-28-cp312-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/9845380258/job/27180806688)|
|wheel-manylinux-2-28-cp38-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/9845379150/job/27180800740)|
|wheel-manylinux-2-28-cp38-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/9845379322/job/27180801933)|
|wheel-manylinux-2-28-cp39-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/9845378866/job/27180799502)|
|wheel-manylinux-2-28-cp39-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/9845378841/job/27180799187)|
|wheel-manylinux-2014-cp310-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/9845379436/job/27180802377)|
|wheel-manylinux-2014-cp310-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/9845380004/job/27180805012)|
|wheel-manylinux-2014-cp311-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/9845379424/job/27180802652)|
|wheel-manylinux-2014-cp311-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/9845379260/job/27180801507)|
|wheel-manylinux-2014-cp312-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/tree/release-17.0.0-rc0-0-github-wheel-manylinux-2014-cp312-amd64)|
|wheel-manylinux-2014-cp312-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/9845379885/job/27180804186)|
|wheel-manylinux-2014-cp38-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/9845379427/job/27180802254)|
|wheel-manylinux-2014-cp38-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/9845379702/job/27180803154)|
|wheel-manylinux-2014-cp39-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/9845379265/job/27180801662)|
|wheel-manylinux-2014-cp39-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/9845380242/job/27180806606)|
|wheel-windows-cp310-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/9845378784/job/27180798608)|
|wheel-windows-cp311-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/9845379031/job/27180800135)|
|wheel-windows-cp312-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/9845379102/job/27180800804)|
|wheel-windows-cp38-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/9845378934/job/27180799830)|
|wheel-windows-cp39-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/9845379261/job/27180801700)|

**Comment by raulcd** [comment]
I'll investigate tomorrow what is wrong on the verification tasks but it seems that the changes for the tags / gh releases (here: https://github.com/apache/arrow/commit/6ec2f222ff7a6ad9dcb3b5b7edc38c414259aee2) have done something wrong to the `tar.gz` on the `02-source.sh` and both binaries and verification tasks are failing due to an empty tar file.
FYI @sgilmore10 @kou

**Comment by sgilmore10** [comment]
> I'll investigate tomorrow what is wrong on the verification tasks but it seems that the changes for the tags / gh releases (here: [6ec2f22](https://github.com/apache/arrow/commit/6ec2f222ff7a6ad9dcb3b5b7edc38c414259aee2)) have done something wrong to the `tar.gz` on the `02-source.sh` and both binaries and verification tasks are failing due to an empty tar file.

Sorry about that @raulcd! Kevin and I will take a look at this asap.

**Comment by raulcd** [comment]
> Sorry about that @raulcd! Kevin and I will take a look at this asap.

No worries, I've just added you FYI, happy if you can take a look otherwise I'll start to investigate tomorrow as is pretty late here at the moment :) But it seems is just the `tar.gz` name once untared. It changed from 16.1.0-rc1 release (https://dist.apache.org/repos/dist/dev/arrow/apache-arrow-16.1.0-rc1/):
```
$ tar zxvf apache-arrow-16.1.0.tar.gz 
...
$ ls
apache-arrow-16.1.0  apache-arrow-16.1.0.tar.gz
```
to 17.0.0-rc0 (https://dist.apache.org/repos/dist/dev/arrow/apache-arrow-17.0.0-rc0/)
```
$ tar zxvf apache-arrow-17.0.0.tar.gz
...
$ ls
apache-arrow-17.0.0-rc0  apache-arrow-17.0.0.tar.gz
```
See `-rc0` is present on the tar.gz name which is unexpected

**Comment by sgilmore10** [comment]
> > Sorry about that @raulcd! Kevin and I will take a look at this asap.
> 
> No worries, I've just added you FYI, happy if you can take a look otherwise I'll start to investigate tomorrow as is pretty late here at the moment :) But it seems is just the `tar.gz` name once untared. It changed from 16.1.0-rc1 release (https://dist.apache.org/repos/dist/dev/arrow/apache-arrow-16.1.0-rc1/):
> 
> ```
> $ tar zxvf apache-arrow-16.1.0.tar.gz 
> ...
> $ ls
> apache-arrow-16.1.0  apache-arrow-16.1.0.tar.gz
> ```
> 
> to 17.0.0-rc0 (https://dist.apache.org/repos/dist/dev/arrow/apache-arrow-17.0.0-rc0/)
> 
> ```
> $ tar zxvf apache-arrow-17.0.0.tar.gz
> ...
> $ ls
> apache-arrow-17.0.0-rc0  apache-arrow-17.0.0.tar.gz
> ```
> 
> See `-rc0` is present on the ~tar.gz~ directory name which is unexpected

That's a good catch. @kevingurney and I were able to confirm this on our end as well. We'll take a look at `02-source.sh` and see if there's anything obviously wrong there.

**Comment by sgilmore10** [comment]
Actually, it looks like there's a bug in [`dev/release/utils-create-release-tarball.sh`](https://github.com/apache/arrow/blob/main/dev/release/utils-create-release-tarball.sh). The name of the directory from which the tarball is created is based on the git tag, and therefore, contains the `rcN` suffix. Adding a separate variable called `tag_no_rc` and using that as the folder name should resolve the issue.

**Comment by kou** [comment]
Could you open a PR for main?
We can cherry-pick it to release branch after we merge it into main.

**Comment by sgilmore10** [comment]
Just submitted a PR (#43200) that should fix the issue. Sorry for the inconvenience this has caused you @raulcd!

**Pull request closed without merging**
