### PR TITLE
ARROW-940: [JS] Generate multiple artifacts

### PR DESCRIPTION
**Pull request by TheNeuralBit**
Running `npm run build` now produces three sets of artifacts: 
* `lib/`: CommonJS modules with typescript declarations
* `lib-esm/`: ES6 modules with typescript declarations
* `_bundles/`: minified and un-minified bundles with source maps for use in the browser

This PR also adds `.npmigore` and `bower.json` to get ready for packaging releases for both npm and bower

### CODE REVIEW

**Review by wesm — APPROVED** [review]
+1. Nice, I am no expert but looks fine to me. Merging

**Comment by wesm** [comment]
What does `i += 1|0` mean in javascript?

**Comment by TheNeuralBit** [comment]
adding `|0` is a way of forcing the engine to treat a value as an integer, it can improve performance sometimes so I just got in the habit of writing loops that way.
I wouldn't be opposed to switching all those lines to `i++` to make tslint happy though

**Comment by wesm** [comment]
Got it. Thanks for the explanation :)

**Pull request closed without merging**
