### PR TITLE
GH-44967: [MATLAB] Add ReadTable method to RecordBatchFileReader

### PR DESCRIPTION
**Pull request by samuelpwlim**
### Rationale for this change

Added a method to read the entire file as a table.

### What changes are included in this PR?

Added a method to RecordBatchFileReader files and a corresponding unit test to record_batch_file_reader.cc

### Are these changes tested?

Unit test added to record_batch_file_reader.cc

### CODE REVIEW

**Comment by samuelpwlim** [comment]
I'm not sure how to link the JIRA issue to this GitHub issue, any help would be appreciated

**Comment by kou** [comment]
We've migrated to GitHub issues from JIRA. See also: #44936

Where did you find JIRA related information?

**Comment by samuelpwlim** [comment]
I noticed this output from the DEV PR / Process (pull_request_target) workflow under the "Add Issue Link" task
`Unhandled error: ReferenceError: getJiraInfo is not defined`

**Comment by kou** [comment]
Oh, it may be a problem caused by #44936.
Could you open a new issue for the problem?

**Comment by samuelpwlim** [comment]
Yes, I will also fix my code. Thank you!

**Comment by kou** [comment]
Ah, no. I wanted to create a new issue for https://github.com/apache/arrow/pull/44965#issuecomment-2526612989 not a copy of #32671.

**Comment by kou** [comment]
You misunderstood #32671.
It's for the C++ implementation https://github.com/apache/arrow/tree/main/cpp not the MATLAB implementation https://github.com/apache/arrow/issues/44967 .

**Comment by samuelpwlim** [comment]
I apologize. I will close the issue I made and reopen a new one concerning the JIRA issue.
I will also close this PR and reopen a new one that addresses the C++ implementation.

**Comment by kou** [comment]
Yes.

Just in case:

* You can close https://github.com/apache/arrow/issues/44967 because it seems that the MATLAB implementation doesn't need a feature in this PR
* Could you open a new issue for https://github.com/apache/arrow/pull/44965#issuecomment-2526612989 ?
* You can close this PR
* You can open a new PR for https://github.com/apache/arrow/issues/32671

**Comment by samuelpwlim** [comment]
Thank you very much! Would I tag the new issue with [Docs] or [C++] or something else?

**Comment by kou** [comment]
Could you use `[CI][Dev]`?

**Comment by samuelpwlim** [comment]
#44968 Please let me know if this looks okay.
I apologize again for the misunderstanding. This is my first time contributing to an open-source

**Comment by kou** [comment]
It looks okay!

**Pull request closed without merging**
