### PR TITLE
ARROW-10207: [C++] Allow precomputing output string/list offsets in kernels

### PR DESCRIPTION
**Pull request by pitrou**

### CODE REVIEW

**Comment by pitrou** [comment]
The main complication here is with the "contiguous preallocation" feature. I'm not sure how much of it is desirable, since if you have a chunked input, you may want it to remain chunked...

**Comment by wesm** [comment]
Hm, I am not sure whether the contiguous allocation feature is worth the trouble. I'll review this

**Review by wesm — APPROVED** [review]
+1 pending CI

**Comment by pitrou** [comment]
Rebased and fixed conflict.

**Pull request closed without merging**
