### PR TITLE
ARROW-2357: [Python] Add microbenchmark for PandasObjectIsNull()

### PR DESCRIPTION
**Pull request by pitrou**
Also add Decimal fodder for other benchmarks. @cpcloud

### CODE REVIEW

**Comment by pitrou** [comment]
Sample result:
```
[100.00%] ··· Running microbenchmarks.PandasObjectIsNull.time_PandasObjectIsNull                                                                      ok
[100.00%] ···· 
               ========= =============
                  type                
               --------- -------------
                  int     1.56±0.01ms 
                 float    1.55±0.01ms 
                 object     1.43±0ms  
                decimal    22.8±0.3ms 
               ========= =============
```

**Comment by pitrou** [comment]
Also the output of other decimal-enabled benchmarks:
```
[ 14.29%] ··· Running convert_builtins.ConvertArrayToPyList.time_convert                                                                              ok
[ 14.29%] ···· 
               ============ =============
                   type                  
               ------------ -------------
                  int32      20.1±0.06ms 
                  uint32     21.0±0.05ms 
                  int64       20.8±0.2ms 
                  uint64      21.5±0.2ms 
                 float32      20.2±0.2ms 
                 float64     20.8±0.08ms 
                   bool       19.4±0.1ms 
                 decimal      184±0.2ms  
                  binary      22.3±0.3ms 
                 binary10     22.0±0.2ms 
                  ascii       35.3±0.1ms 
                 unicode      76.2±0.2ms 
                int64 list    183±0.2ms  
                  struct       324±2ms   
               ============ =============

[ 28.57%] ··· Running convert_builtins.ConvertPyListToArray.time_convert                                                                              ok
[ 28.57%] ···· 
               ==================== =============
                       type                      
               -------------------- -------------
                      int32          5.51±0.07ms 
                      uint32          5.42±0.1ms 
                      int64           6.11±0.1ms 
                      uint64         4.96±0.09ms 
                     float32         5.18±0.03ms 
                     float64         5.19±0.04ms 
                       bool          4.28±0.01ms 
                     decimal          187±0.4ms  
                      binary          8.18±0.1ms 
                     binary10         8.39±0.1ms 
                      ascii           13.1±0.3ms 
                     unicode          30.0±0.6ms 
                    int64 list        52.8±0.5ms 
                      struct           31.1±2ms  
                struct from tuples     30.4±2ms  
               ==================== =============

[ 42.86%] ··· Running convert_builtins.InferPyListToArray.time_infer                                                                                  ok
[ 42.86%] ···· 
               ============ =============
                   type                  
               ------------ -------------
                  int64       11.7±0.1ms 
                 float64     10.4±0.07ms 
                   bool      9.35±0.03ms 
                 decimal      381±0.5ms  
                  binary      14.5±0.1ms 
                  ascii       19.8±0.2ms 
                 unicode      37.6±0.6ms 
                int64 list    101±0.07ms 
               ============ =============
```

**Comment by pitrou** [comment]
The C/glib failures on Travis-CI are mysterious as this PR is not touching any related code:
https://travis-ci.org/apache/arrow/jobs/361127786
https://travis-ci.org/apache/arrow/jobs/361127785

@kou

**Comment by pitrou** [comment]
I opened ARROW-2377 for the CI failures.

**Comment by kou** [comment]
The failures should be worked on #1826 . You can ignore them in this pull request.

**Review by xhochy — APPROVED** [review]
+1, LGTM

**Pull request closed without merging**
