### PR TITLE
ARROW-10178: [CI] Remove patch to fix Spark master build

### PR DESCRIPTION
**Pull request by BryanCutler**
Spark master branch has been updated for Arrow 1.0.1, the patch to fix Java compilation can be removed.

### CODE REVIEW

**Comment by BryanCutler** [comment]
@ursabot crossbow submit test-conda-python-3.8-spark-master

**Comment by BryanCutler** [comment]
I think we might have to add a patch to fix that nested timezone problem from earlier in #7804 , but lets see how the integration run goes

**Comment by BryanCutler** [comment]
Spark needs to be patched again to handle structs with timestamps, adding the patch here and it can be removed after SPARK-32285 is complete.

**Comment by BryanCutler** [comment]
@ursabot crossbow submit test-conda-python-3.8-spark-master

**Comment by BryanCutler** [comment]
@kszucs the Spark integration tests are passing for master branch with this change, could you take a look? Thanks!

**Comment by emkornfield** [comment]
> Spark needs to be patched again to handle structs with timestamps, adding the patch here and it can be removed after SPARK-32285 is complete. This is due to the changes in #7816

Was this patch necessary before?  I thought we should be running Spark in a backwards compatibility mode that doesn't honor the TZ info. (maybe this got dropped from the patch?)

**Comment by BryanCutler** [comment]
Oh, I didn't see there was a backwards compatible setting. I ran the tests locally and obviously failed without it. Let me remove the patch and run again here.

**Comment by BryanCutler** [comment]
@ursabot crossbow submit test-conda-python-3.8-spark-master

**Review by jorisvandenbossche — APPROVED** [review]
Thanks!

**Comment by kszucs** [comment]
Thanks Bryan!

**Pull request closed without merging**
