### PR TITLE
[WIP] ARROW-831: switch from boost::regex to std::regex

### PR DESCRIPTION
**Pull request by pcmoritz**

### CODE REVIEW

**Comment by wesm** [comment]
I'm able to replicate this error locally with Xcode 6.4, and

```
static const std::regex DECIMAL_PATTERN("(\\+?|-?)((0*)(\\d*))(\\.(\\d+))?", std::regex::ECMAScript);
```

doesn't work either. So we'll need to rewrite this regex to work with C++11 regexes

**Comment by cpcloud** [comment]
Do trivial regexen match?

**Comment by wesm** [comment]
I think this might be a bug with XCode 6 since this seems to work fine with gcc 4.9 and MSVC =(

**Comment by wesm** [comment]
I think the best option may be to write a POSIX-compliant regex (the current regex doesn't compile with `std::regex::extended`), any takers? There's a separate issue which is that the Status code in the `Decimal` constructor when parsing a string goes unchecked.

**Comment by pcmoritz** [comment]
std::regex seems to not be supported in g++ <= 4.8:
http://stackoverflow.com/questions/12530406/is-gcc-4-8-or-earlier-buggy-about-regular-expressions

Do we still want this for 0.3 then? Supporting g++ 4.8 seems important, afaik it is the standard in ubuntu 14.04, which is still widely used.

**Comment by wesm** [comment]
OK, that sounds good for now. Eventually I want to add https://github.com/google/re2 to our toolchain for faster string analytics based on regexen, and at that point maybe we can switch away from std::regex. It's too bad that the C++11 regex implementation took a while to reach maturity.

**Comment by wesm** [comment]
Now that https://github.com/apache/arrow/pull/567 is in, let's close this? Thanks

**Pull request closed without merging**
