### PR TITLE
MINOR: [C++][clang-tidy] Disable modernize-use-nodiscard check 

### PR DESCRIPTION
**Pull request by felipecrv**
Not all functions that return a value should have a `[[nodiscard]]`.

`[[nodiscard]]` adds noise and is better used for functions that:
 1. Return a `Status` or some kind of error code
 2. Have a confusing name like the STL container's `empty()`. The STL uses  `[[nodiscard]]` for `empty()` so people are less likely to call it believing it has the same effect of `clear()`.

### CODE REVIEW

**Comment by felipecrv** [comment]
@pitrou

**Review by pitrou — APPROVED** [review]
Good idea. I know @lidavidm was bitten by this at some point :-)

**Comment by felipecrv** [comment]
> Good idea. I know @lidavidm was bitten by this at some point :-)

I've seen that code review. :)

**Comment by lidavidm** [comment]
Thank you!

And yes, the clangd LSP server is very aggressive about suggesting this, which will affect anyone using Emacs, VSCode, etc.

**Pull request merged**
