### PR TITLE
ARROW-4543: [C#] Update Flat Buffers code to latest version

### PR DESCRIPTION
**Pull request by eerhardt**
- Update FlatBuffers code to latest version.
- Mark all FlatBuffer types as internal.

Note: I didn't use the latest `.fbs` file version because it included the SparseTensor support. Using the latest `.fbs` change caused problems with the `Tensor` generation. I have a [question if the latest `.fbs` file is correct](https://github.com/apache/arrow/pull/2546#discussion_r256549256).

/cc @chutchinson @stephentoub - FYI

### CODE REVIEW

**Comment by eerhardt** [comment]
@wesm @xhochy - how do I re-run the travis-ci? I don't think the failure is related to my proposed change.

**Comment by kou** [comment]
I restarted the failed job manually.
You can re-run all jobs by force push.

**Review by xhochy — APPROVED** [review]
+1, the build failure is unrelated. 

@eerhardt Can you add a line to the README on how to update these files?

**Comment by eerhardt** [comment]
> Can you add a line to the README on how to update these files?

Done.  Thanks for the review.

**Review by kszucs — APPROVED** [review]

**Comment by kszucs** [comment]
Thanks @eerhardt!

**Pull request closed without merging**
