### PR TITLE
GH-43492: [C++] Thirdparty: Bump lz4 to 1.10.0

### PR DESCRIPTION
**Pull request by mapleFU**
### Rationale for this change

Bump lz4 to latest ( 1.10.0 )

### What changes are included in this PR?

Bump lz4 to latest ( 1.10.0 )

### Are these changes tested?

Covered by existing

### Are there any user-facing changes?

no

* GitHub Issue: #43492

### CODE REVIEW

**Comment by mapleFU** [comment]
@github-actions crossbow submit -g cpp -g wheel

**Comment by pitrou** [comment]
@github-actions crossbow submit -g python

**Comment by pitrou** [comment]
@mapleFU Can you rebase from main?

**Comment by mapleFU** [comment]
done

**Comment by pitrou** [comment]
@github-actions crossbow submit -g python

**Review by pitrou — APPROVED** [review]
CI failures look unrelated, LGTM

**Pull request merged**
