### PR TITLE
ARROW-9979: [Rust] Fix arrow crate clippy lints

### PR DESCRIPTION
**Pull request by nevi-me**
This fixes a lot of clippy errors and warnings. We currently have over 600 such, and they tend to cause a lot of noise while working.

This PR only includes changes to arrow, one change to datafusion and integration testing. I've left parquet out to potentially open a separare PR.

Thoughts @andygrove @alamb @jorgecarleitao @paddyhoran?

### CODE REVIEW

**Review by alamb — APPROVED** [review]
I skimmed the changes and overall I think they look like a good improvement to me (especially the removal of `vec!` and `clone()` calls. Nice work

**Review by jorgecarleitao — APPROVED** [review]
LGTM. Thanks a lot!

I would be fine to place clippy under CI checks and READMEs to reduce merge conflicts during rebasing on top of these type of commits.

**Comment by nevi-me** [comment]
Thanks @alamb @jorgecarleitao, I've opened https://issues.apache.org/jira/browse/ARROW-9978 to keep track of all clippy work. I'll wait for @andygrove and @paddyhoran's opinions before going ahead with the merge.

It's unfortunately going to be disruptive to existing open PRs, but at the same time I'd like to merge this sooner so I can bank this work (it's the third time I work on clippy lints)

**Review by andygrove — APPROVED** [review]
Thanks for taking on this work @nevi-me .. this LGTM!

**Pull request closed without merging**
