### PR TITLE
ARROW-5172: [Go] implement reading fixed-size binary arrays from Arrow file

### PR DESCRIPTION
**Pull request by sbinet**

### CODE REVIEW

**Comment by sbinet** [comment]
needs #4158

**Comment by sbinet** [comment]
PTAL @stuartcarnie @alexandreyc @nickpoorman

**Comment by sbinet** [comment]
(the Travis-CI error is unrelated (JDK-9 is acting up?))

**Comment by wesm** [comment]
https://issues.apache.org/jira/browse/ARROW-5223

**Review by stuartcarnie — APPROVED** [review]
LGTM

**Pull request closed without merging**
