### PR TITLE
GH-35181: [R] Bump R package version number in versions.json

### LINKED ISSUE #35181: [R] Minor bump and fix to tests for R package version
### Describe the bug, including details regarding any error messages, version, and platform.

The associated PR was marked as 12.0.0. I am creating an issue only because it can be added to the 12.0.0 after the feature freeze.
The issue is to correct a minor version change for R.

### Component(s)

R

### PR DESCRIPTION
**Pull request by thisisnic**
This PR corrects a missed R package version number increase
* Closes: #35181

### CODE REVIEW

**Comment by thisisnic** [comment]
This is failing due to one of the release tests; @kou  - could this be because I'm editing the release scripts and we've cut an RC but not done the release yet?

**Comment by kou** [comment]
Ah, yes. Our test didn't assume that we have `X.Y.Z.?` version.
I'll take a look at this.

**Comment by kou** [comment]
> > Could this be because I'm editing the release scripts and we've cut an RC but not done the release yet?
>
> Ah, yes.

Sorry. No. I think that it's just a test problem.

**Comment by kou** [comment]
I've pushed a fix for the failure.

**Review by raulcd — APPROVED** [review]
:+1:

**Pull request merged**
