### PR TITLE
ARROW-9354: [C++] Turbodbc latest fails to build in the integration tests

### PR DESCRIPTION
**Pull request by kszucs**

### CODE REVIEW

**Comment by kszucs** [comment]
@github-actions crossbow submit test-*-turbodbc-*

**Comment by kszucs** [comment]
@xhochy we should push the patch upstream (and turbodbc has a couple of compile warnings as well).

**Comment by xhochy** [comment]
> @xhochy we should push the patch upstream (and turbodbc has a couple of compile warnings as well).

Can you just PR that against `turbodbc`? I can merge and release directly if that helps.

**Comment by kszucs** [comment]
> > @xhochy we should push the patch upstream (and turbodbc has a couple of compile warnings as well).
> 
> Can you just PR that against `turbodbc`? I can merge and release directly if that helps.

Sure. Would you prefer that?

**Comment by xhochy** [comment]
> Sure. Would you prefer that?

Yes, keeping patches in the Arrow CI jobs is prone to get lost.

**Comment by kszucs** [comment]
Created a PR upstream.

**Comment by kszucs** [comment]
@github-actions crossbow submit test-conda-python-3.7-turbodbc-master

**Comment by kszucs** [comment]
@xhochy submitted a crossbow build to test that the upstream patch works

**Comment by kszucs** [comment]
I'm closing this because the upstream patch has already resolved the integration failure against turbodbc master. The latest release will fail until turbodbc cuts a new release including the patch.

**Pull request closed without merging**
