### PR TITLE
ARROW-17233: [Packaging][Linux] Update artifact patterns

### PR DESCRIPTION
**Pull request by kou**
Add `--validate` option to `archery crossbow status`.
If `--validate` is specified and there are any missing artifacts, `archery crossbow status --validate` is existed
with non-zero exit code. We can use it for CI to detect missing artifacts.

We can't use `@github-actions crossbow submit` for this change because this isn't merged into the master branch
yet. See https://github.com/ursacomputing/crossbow/branches/all?query=build-674 that is submitted `nightly-packages`
manually.

### CODE REVIEW

**Comment by kou** [comment]
@github-actions crossbow submit ubuntu-bionic-*

**Comment by kou** [comment]
@github-actions crossbow submit ubuntu-bionic-*

**Comment by kou** [comment]
@github-actions crossbow submit ubuntu-bionic-*

**Comment by kou** [comment]
@github-actions crossbow submit ubuntu-bionic-*

**Comment by kou** [comment]
@github-actions crossbow submit ubuntu-bionic-*

**Comment by kou** [comment]
@github-actions crossbow submit ubuntu-bionic-*

**Comment by kou** [comment]
@kszucs Could you review this? See the pull request description for details.

**Review by kszucs — APPROVED** [review]
LGTM, thanks @kou!

**Pull request merged**
