### PR TITLE
ARROW-2825: [C++] Add AllocateBuffer / AllocateResizableBuffer variants with default memory pool

### PR DESCRIPTION
**Pull request by pitrou**

### CODE REVIEW

**Comment by pitrou** [comment]
@alendit

**Review by xhochy — APPROVED** [review]
+1, LGTM

**Comment by pitrou** [comment]
@xhochy The manylinux job failure looks unrelated, is it tracked somewhere?

**Comment by xhochy** [comment]
I opened https://issues.apache.org/jira/browse/ARROW-2850 and am looking into it. Sadly adding the flag does not suffice as it is not correctly picked up by `parquet-cpp`.

**Pull request closed without merging**
