### PR TITLE
GH-41005: [CI] HDFS and skyhook tests require docker compose usage because they require multiple containers

### PR DESCRIPTION
**Pull request by raulcd**
### Rationale for this change

We are currently using docker run but we require linked containers to be also started.

### What changes are included in this PR?

Use docker compose instead of docker 

### Are these changes tested?

Via archery

### Are there any user-facing changes?
No
* GitHub Issue: #41005

### CODE REVIEW

**Comment by raulcd** [comment]
@github-actions crossbow submit test-conda-python-3.10-hdfs-*

**Comment by raulcd** [comment]
@github-actions crossbow submit test-skyhook-integration

**Comment by raulcd** [comment]
@github-actions crossbow submit test-conda-python-3.10-hdfs-*

**Review by kou — APPROVED** [review]
+1

**Pull request merged**
