### PR TITLE
GH-35413: [Python] Add concrete floating point array types to pyarrow public API

### LINKED ISSUE #35413: [Docs] DoubleArray and FloatingPointArray are missing from generated Python docs
### Describe the bug, including details regarding any error messages, version, and platform.

https://arrow.apache.org/docs/python/api/arrays.html lists the concrete array types available in Pyarrow. But some are missing: https://github.com/apache/arrow/blob/205ceb99389d2d5060551ebcba17635185c74d9d/python/pyarrow/array.pxi#L1870-L1885 lists the float16/float32/float64 concrete array types, and they don't appear in the generated table, nor do their direct links (eg https://arrow.apache.org/docs/python/generated/pyarrow.DoubleArray.html) work. 

### Component(s)

Documentation, Python

### PR DESCRIPTION
**Pull request by spenczar**
### Rationale for this change

These concrete types appear to have been overlooked.

### What changes are included in this PR?

n/a

### Are these changes tested?

n/a

### Are there any user-facing changes?

Yes - I didn't rebuild docs, do I need to do that?
* Closes: #35413

### CODE REVIEW

**Comment by pitrou** [comment]
@spenczar Thanks for this. We should probably also change https://github.com/apache/arrow/blob/main/docs/source/python/api/arrays.rst

**Comment by spenczar** [comment]
@pitrou Sure, done.

I also noticed that FixedShapeTensorArray is missing, and HalfFloatScalar is missing from that .rst page as well. I can bundle in adding those to this PR, or do it separately, whatever works.

Do I need to manually do any doc generation?

**Comment by pitrou** [comment]
> I also noticed that FixedShapeTensorArray is missing, and HalfFloatScalar is missing from that .rst page as well. I can bundle in adding those to this PR, or do it separately, whatever works.

You can just do it in this PR.

> Do I need to manually do any doc generation?

No, CI takes care of that normally.

**Review by jorisvandenbossche — APPROVED** [review]
Thanks @spenczar !

**Pull request merged**
