### PR TITLE
GH-45006: [CI][Python] Fix test_memory failures

### PR DESCRIPTION
**Pull request by pitrou**
`test_memory.py` has started failing on some builds after https://github.com/apache/arrow/pull/44951 was merged

* GitHub Issue: #45006

### CODE REVIEW

**Comment by pitrou** [comment]
@github-actions crossbow submit -g python

**Comment by pitrou** [comment]
@github-actions crossbow *wheel*cp312*

**Review by raulcd — COMMENTED** [review]
The change LGTM, I am just wondering, is there any case where we test `jemalloc` for pyarrow? Do we want to?

**Comment by pitrou** [comment]
> The change LGTM, I am just wondering, is there any case where we test `jemalloc` for pyarrow?

What do you mean? It's still tested in `test_memory.py`, it's just not mandatory anymore.

**Comment by pitrou** [comment]
Ah, perhaps we should ensure that it's enabled on some CI tests indeed. Will take a look.

**Comment by pitrou** [comment]
@github-actions crossbow submit -g python -g cpp

**Comment by raulcd** [comment]
Yes, sorry, that's what I meant. If we were enabling jemalloc for Python builds on any of our CI builds.

**Comment by pitrou** [comment]
It looks like we will have to disable mimalloc for the thread sanitizer test.

**Comment by pitrou** [comment]
@github-actions crossbow submit test-ubuntu-24.04-cpp-thread-sanitizer

**Review by jorisvandenbossche — APPROVED** [review]

**Pull request merged**
