### PR TITLE
ARROW-13203: [R] Fix optional component checks causing failures

### PR DESCRIPTION
**Pull request by ianmcook**

### CODE REVIEW

**Comment by ianmcook** [comment]
@github-actions crossbow submit test-r-without-arrow

**Comment by ianmcook** [comment]
@github-actions crossbow submit test-r-minimal-build

**Comment by ianmcook** [comment]
@github-actions crossbow submit test-r-without-arrow

**Comment by ianmcook** [comment]
@github-actions crossbow submit test-r-without-arrow

**Comment by ianmcook** [comment]
@github-actions crossbow submit test-r-without-arrow

**Comment by jonkeane** [comment]
@github-actions crossbow submit test-r-linux-rchk test-r-minimal-build

**Review by jonkeane — APPROVED** [review]
Looks good to me, I triggered two more builds (the minimal should be fine, but just in case something funny happened in the subsequent commits, and the rchk one looked like it was the exact same error, so would be good to know if it is also magically resolved)

**Pull request closed without merging**
