### PR TITLE
ARROW-4802: [Python] Follow symlinks when deriving Hadoop classpath for HDFS

### PR DESCRIPTION
**Pull request by chenfj068**
If HADOOP_HOME is a symlink, the '-L' option needs to be passed to the find command

### CODE REVIEW

**Comment by wesm** [comment]
I changed the PR title

**Review by wesm — APPROVED** [review]
+1

**Comment by wesm** [comment]
@chenfj068 can you let me know your JIRA id so I can assign this issue to you?

**Comment by chenfj068** [comment]
@wesm my JIRA id is `Tiger068` . Thanks

**Pull request closed without merging**
