### PR TITLE
ARROW-5049: [Python] org/apache/hadoop/fs/FileSystem class not found when pyarrow FileSystem used in spark

### PR DESCRIPTION
**Pull request by chenfj068**
Ensure hadoop-common-{version} jar is  in the classpath

### CODE REVIEW

**Comment by chenfj068** [comment]
Does something wrong with continuous-integration test  @wesm 
```
Summary coverage rate:
  lines......: 54.9% (27117 of 49402 lines)
  functions..: 59.9% (37213 of 62171 functions)
  branches...: no data found
~/build/apache/arrow/python ~/build/apache/arrow
~/build/apache/arrow/cpp/apidoc ~/build/apache/arrow/python ~/build/apache/arrow
~/build/apache/arrow/python ~/build/apache/arrow
/home/travis/build/apache/arrow/pyarrow-test-3.6/lib/python3.6/site-packages/sphinx/util/docutils.py:311: RemovedInSphinx30Warning: function based directive support is now deprecated. Use class based directive instead.
  RemovedInSphinx30Warning)
Exception occurred:
  File "/home/travis/build/apache/arrow/pyarrow-test-3.6/lib/python3.6/site-packages/breathe/renderer/sphinxrenderer.py", line 38, in parse_definition
    ast = parser.parse_declaration("class")
TypeError: parse_declaration() missing 1 required positional argument: 'directiveType'
The full traceback has been saved in /tmp/sphinx-err-jr4dg9oi.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.

```

**Comment by emkornfield** [comment]
This change looks good to me, but I want to try running hdfs integration tests against it before merging.

**Comment by emkornfield** [comment]
Sorry, I've been delayed in testing this, I should be able to get to it by end of week.

**Comment by kszucs** [comment]
@emkornfield let me know if You need any help with running the integration tests

**Comment by emkornfield** [comment]
@kszucs if you could that would be great, I've been busier than expected so I haven't been able to get to it

**Comment by emkornfield** [comment]
Tests pass locally for me.  Thank you for the contribution.

**Pull request closed without merging**
