### PR TITLE
ARROW-13384: [C++] Specify minimum required zstd version in cmake

### PR DESCRIPTION
**Pull request by nealrichardson**

### CODE REVIEW

**Comment by nealrichardson** [comment]
@github-actions crossbow submit homebrew-r-autobrew

**Comment by nealrichardson** [comment]
^ that should fail but should fail differently: it should say that the version requirement isn't met. Then once the bottle is upgraded, it should work on retry.

**Comment by kszucs** [comment]
There are more failing builds: https://github.com/apache/arrow/pull/10659#issuecomment-882712592

Interestingly the debian 10 based builds have ZSTD with version `1.3.8` but the issue is still there: https://github.com/ursacomputing/crossbow/runs/3106411669?check_suite_focus=true#step:8:316

**Comment by kszucs** [comment]
@github-actions crossbow submit test-debian-10-cpp

**Comment by nealrichardson** [comment]
The autobrew job didn't fail as expected, maybe cmake found something newer on the system but then still used the old 1.3.5 when compiling?

**Comment by kszucs** [comment]
The API has been stabilized at `1.4.0`, see https://github.com/facebook/zstd/commit/d7d89513d6a216cfa920208ce82f9128616bab7c#diff-e51691a217ef645007ebc5dd6db0539c32d0a531aad5823873adb12d995341b5R177

**Comment by kszucs** [comment]
@github-actions crossbow submit test-debian-10-cpp homebrew-r-autobrew

**Comment by kszucs** [comment]
@github-actions crossbow submit test-ubuntu-* test-debian-*

**Comment by kszucs** [comment]
@github-actions crossbow submit ubuntu-bionic-* debian-buster-*

**Comment by kszucs** [comment]
@kou can we make both utcf8proc and zstd optional [at this line](https://github.com/apache/arrow/blob/master/dev/tasks/linux-packages/apache-arrow/debian/libarrow-dev.install#L10)?

**Comment by kou** [comment]
Could you try the following? It's dirty but will work...

```diff
diff --git a/dev/tasks/linux-packages/apache-arrow/debian/libarrow-dev.install b/dev/tasks/linux-packages/apache-arrow/debian/libarrow-dev.install
index 83ddad126..ccd0c4e5b 100644
--- a/dev/tasks/linux-packages/apache-arrow/debian/libarrow-dev.install
+++ b/dev/tasks/linux-packages/apache-arrow/debian/libarrow-dev.install
@@ -6,8 +6,7 @@ usr/lib/*/cmake/arrow/Find*Alt.cmake
 usr/lib/*/cmake/arrow/FindArrow.cmake
 usr/lib/*/cmake/arrow/FindBrotli.cmake
 usr/lib/*/cmake/arrow/FindLz4.cmake
-usr/lib/*/cmake/arrow/FindSnappy.cmake
-usr/lib/*/cmake/arrow/Find[uz]*.cmake
+usr/lib/*/cmake/arrow/Find[Suz]*.cmake
 usr/lib/*/cmake/arrow/arrow-config.cmake
 usr/lib/*/libarrow.a
 usr/lib/*/libarrow.so
```

**Comment by kou** [comment]
@github-actions crossbow submit amazon-linux-* centos-*

**Comment by kszucs** [comment]
@github-actions crossbow submit ubuntu-bionic-* debian-buster-*

**Comment by kszucs** [comment]
@github-actions crossbow submit amazon-linux-* centos-*

**Comment by kszucs** [comment]
@github-actions crossbow submit amazon-linux-2-amd64

**Comment by kszucs** [comment]
@github-actions crossbow submit -g nightly

**Review by kou — APPROVED** [review]
+1

**Pull request closed without merging**
