### PR TITLE
ARROW-6848: [C++] Support building libraries targeting C++14 or higher

### PR DESCRIPTION
**Pull request by wesm**
This seemed pretty simple. The C++ standard targeted by default is still C++11 but some users might want to target a higher standard (e.g. to get C++17 `std::string_view`). I also disabled use of `-std=gnu++11`. Not sure what are the implications of this but the test suite seemed fine locally.

### CODE REVIEW

**Comment by wesm** [comment]
@kou @brills @kszucs could use your advice on possible concerns regarding the -std=gnu++11 to -std=c++11 change when using gcc

**Comment by wesm** [comment]
Well this is weird

```
CMake Error in src/plasma/CMakeLists.txt:
  Target "plasma-external-store-tests" requires the language dialect "CXXOFF"
  , but CMake does not know the compile flags to use to enable it.
CMake Error in src/plasma/CMakeLists.txt:
  Target "plasma-client-tests" requires the language dialect "CXXOFF" , but
  CMake does not know the compile flags to use to enable it.
```

**Comment by wesm** [comment]
OK I guess I'm a bit out of my depth on the CMAKE_CXX_EXTENSIONS issue. If anyone has ideas about what to do let me know

**Review by kou — COMMENTED** [review]
I'm OK with `gnu++11` -> `c++11` if our Linux packages can be built well.

**Comment by kou** [comment]
Should we link to ARROW-6848 instead of ARROW-6800?

**Comment by wesm** [comment]
@kou thanks, I applied your suggestions

**Comment by wesm** [comment]
@github-actions crossbow submit -g linux

**Comment by wesm** [comment]
@github-actions crossbow submit centos-7-aarch64 ubuntu-focal-arm64

**Comment by wesm** [comment]
The ARM64 failures look unrelated to these changes, otherwise this seems ok, what do you think @kou ?

**Comment by kou** [comment]
They are unrelated.
I extended timeout.

**Comment by kou** [comment]
Should we add jobs for `-DCMAKE_CXX_STANDARD=14` and `-DCMAKE_CXX_STANDARD=17` in this pull request? Or follow up pull requests?

**Comment by kou** [comment]
@github-actions crossbow submit centos-7-aarch64 ubuntu-focal-arm64

**Review by kou — APPROVED** [review]
+1

**Comment by wesm** [comment]
> Should we add jobs for `-DCMAKE_CXX_STANDARD=14` and `-DCMAKE_CXX_STANDARD=17` in this pull request? Or follow up pull requests?

I think follow up.

**Comment by kou** [comment]
OK.

**Comment by wesm** [comment]
You're more than welcome to add them to this PR, too (I'm pretty clumsy with the build configurations). It's true that the "feature" added by this PR is not represented by any test.

**Comment by kou** [comment]
I'll try it in this pull request.

**Comment by kou** [comment]
@github-actions crossbow submit test-ubuntu-20.04-*

**Comment by kou** [comment]
@github-actions crossbow submit test-ubuntu-20.04-*

**Comment by brills** [comment]
We ([tfx-bsl](https://github.com/tensorflow/tfx-bsl)) have been building against the shared library shipped with pyarrow wheels (current built with gnu++11) without a problem despite that we use c++11. So this change is likely a no-op to us (at least for arrow 0.16, 0.17). But we only use a small subset of arrow headers.

**Comment by kou** [comment]
@github-actions crossbow submit centos-7-aarch64 ubuntu-focal-arm64

**Comment by kou** [comment]
@github-actions crossbow submit centos-7-aarch64 ubuntu-focal-arm64

**Comment by kou** [comment]
@github-actions crossbow submit centos-7-aarch64 ubuntu-focal-arm64

**Comment by kou** [comment]
@github-actions crossbow submit test-ubuntu-20.04-*

**Comment by kou** [comment]
@github-actions crossbow submit test-ubuntu-20.04-*

**Comment by kou** [comment]
+1
CI failures are unrelated.

**Pull request closed without merging**
