### PR TITLE
GH-37145: [Python] support boolean columns with bitsize 1 in from_dataframe

### LINKED ISSUE #37145: [Python] support boolean columns with bitsize 1 in from_dataframe
### Describe the enhancement requested

Add support for boolean columns with bitsize 1 in the `from_dataframe` function of the Dataframe Interchange Protocol implementation.

See: https://github.com/apache/arrow/issues/33982#issuecomment-1669278644

### Component(s)

Python

### PR DESCRIPTION
**Pull request by AlenkaF**
### Rationale for this change

Bit-packed booleans are currently not supported in the `from_dataframe` of the Dataframe Interchange Protocol.

Note: We currently represent booleans in the pyarrow implementation as `uint8` which will also need to be changed in a follow-up PR (see https://github.com/data-apis/dataframe-api/issues/227). 

### What changes are included in this PR?

This PR adds the support for bit-packed booleans when consuming a dataframe interchange object.

### Are these changes tested?

Only locally, currently!
* Closes: #37145

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
Implementation looks good, just needs some tests then (I assume the problem here is that we ourselves don't generate this (yet), so we can't actually test it easily?)

**Comment by AlenkaF** [comment]
> Implementation looks good, just needs some tests then (I assume the problem here is that we ourselves don't generate this (yet), so we can't actually test it easily?)

Yeah 😬 I think the only other library that **will** use bit-packed booleans is Polars.

I guess this PR should stay draft until we generate this ourselves?

**Comment by jorisvandenbossche** [comment]
Maybe we can also merge this, if you can test it locally with polars, and then open an issue to remind ourselves to add tests for it later (or when we export such data ourselves). 

Merging this sooner rather than later would be good, as otherwise it breaks polars->pyarrow conversion

**Comment by AlenkaF** [comment]
OK, I will test one more time and then ping you for merge (or I can do it, if that is OK).

I plan to create an issue for us to export bit-packed boolean data so we can discuss what would be the correct approach. I will add the note about the tests there.

**Comment by AlenkaF** [comment]
Tested the code from the [original report](https://github.com/apache/arrow/issues/33982#issuecomment-1669278644):

Screenshot 2023-10-04 at 15 06 36


We can marge.

**Review by jorisvandenbossche — APPROVED** [review]
Thanks for testing!

**Pull request merged**
