### PR TITLE
GH-15122: [Benchmarking][Python] Set ARROW_INSTALL_NAME_RPATH=ON for benchmark builds

### LINKED ISSUE #15122: [Benchmarking][Python] Benchmark builds on `test-mac-arm` are failing
Benchmark builds on `test-mac-arm` started failing on 12/21/2022 after https://github.com/apache/arrow/pull/14925 was merged into main . The first failed build: https://buildkite.com/apache-arrow/arrow-bci-benchmark-on-test-mac-arm/builds/2070

Steps to reproduce the issue on `test-mac-arm`:
```
cd ~
rm -rf arrow
git clone https://github.com/apache/arrow.git
cd arrow
conda create -y -n arrow-commit -c conda-forge \
  --file ci/conda_env_unix.txt \
  --file ci/conda_env_cpp.txt \
  --file ci/conda_env_python.txt \
  compilers \
  python=3.8 \
  pandas \
  aws-sdk-cpp \
  r
conda activate arrow-commit
pip install -r python/requirements-build.txt -r python/requirements-test.txt
source dev/conbench_envs/hooks.sh set_arrow_build_and_run_env_vars
export RANLIB=`which $RANLIB`
export AR=`which $AR`
export ARROW_JEMALLOC=OFF
ci/scripts/cpp_build.sh $(pwd) $(pwd)
ci/scripts/python_build.sh $(pwd) $(pwd)
(arrow-commit) voltrondata@m1mini01 arrow % python
Python 3.8.15 | packaged by conda-forge | (default, Nov 22 2022, 08:49:06) 
[Clang 14.0.6 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyarrow
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/voltrondata/miniconda3/envs/arrow-commit/lib/python3.8/site-packages/pyarrow/_init_.py", line 65, in <module>
    import pyarrow.lib as _lib
ImportError: dlopen(/Users/voltrondata/miniconda3/envs/arrow-commit/lib/python3.8/site-packages/pyarrow/lib.cpython-38-darwin.so, 2): Library not loaded: /Users/voltrondata/arrow/python/build/lib.macosx-11.0-arm64-cpython-38/pyarrow/lib/libarrow_python.1100.dylib
  Referenced from: /Users/voltrondata/miniconda3/envs/arrow-commit/lib/python3.8/site-packages/pyarrow/lib.cpython-38-darwin.so
  Reason: image not found
>>>
```

### Component(s)

Benchmarking

### PR DESCRIPTION
**Pull request by ElenaHenderson**
* Closes: #15122

### CODE REVIEW

**Comment by ElenaHenderson** [comment]
@ursabot please benchmark

**Comment by ElenaHenderson** [comment]
@ursabot please benchmark

**Comment by ElenaHenderson** [comment]
@kou May I please have your review?

The benchmarks are running on test-mac-arm now and ubuntu benchmark machines. Thus build https://buildkite.com/apache-arrow/arrow-bci-benchmark-on-test-mac-arm/builds/2102 has status Failed because one benchmark failed but it is not related to this change at all.

**Review by assignUser — APPROVED** [review]
+1

**Pull request merged**
