### PR TITLE
GH-44844: [CI] Uninstall pkg-config entirely on verification and java-jars macOS jobs

### PR DESCRIPTION
**Pull request by raulcd**
### Rationale for this change

Jobs are failing on nightlies.

### What changes are included in this PR?

Remove pkg-config entirely as we've done on other CI jobs.

### Are these changes tested?

Yes via archery

### Are there any user-facing changes?

No
* GitHub Issue: #44844

### CODE REVIEW

**Comment by raulcd** [comment]
@github-actions crossbow submit java-jars verify-rc-source-*macos-*

**Comment by raulcd** [comment]
@github-actions crossbow submit java-jars

**Comment by raulcd** [comment]
@github-actions crossbow submit java-jars verify-rc-source-ruby-macos-amd64

**Comment by raulcd** [comment]
@github-actions crossbow submit verify-rc-source-ruby-macos-amd64

**Comment by raulcd** [comment]
@github-actions crossbow submit java-jars verify-rc-source-*macos-*

**Comment by raulcd** [comment]
@kou the `verify-rc-source-ruby-macos-amd64` job is also related to `pkg-config` when installing meson but I haven't seen other failures on amd64 so I am not entirely sure what is going on on this one.

**Comment by kou** [comment]
Meson doesn't find `pkgconf` by default. So we need to specify it explicitly. See also:
* https://github.com/apache/arrow/pull/44798#issuecomment-2489968836
* https://github.com/apache/arrow/pull/44798/commits/afeb15e27b670f352ced1db11a3df62568f83d77

**Comment by kou** [comment]
@github-actions crossbow submit verify-rc-source-ruby-macos-*

**Review by kou — APPROVED** [review]
+1

**Comment by raulcd** [comment]
Thanks @kou

**Pull request merged**
