### PR TITLE
GH-44974: [Dev] Fix minor issue handling

### PR DESCRIPTION
**Pull request by pitrou**
### Rationale for this change

The current implementation works for `GH-XXX` PRs but doesn't work for `MINOR` PRs.

### What changes are included in this PR?

Add a missing `issue.kind` check.

### Are these changes tested?

Yes.

### Are there any user-facing changes?

No.

* GitHub Issue: #44974

### CODE REVIEW

**Comment by pitrou** [comment]
Not sure how to test this before it reaches git main @raulcd

**Review by raulcd — COMMENTED** [review]
I've tested on my fork.
In order to test it I merge the change on my fork on main and create a PR against my fork, see this PR as an example:
https://github.com/raulcd/arrow/pull/86
I had to also apply this change:
https://github.com/raulcd/arrow/commit/c2970257d5caba25107d50e9b7295a93edd979cb
otherwise it fails on the `Check issue` step as seen on this action failure:
https://github.com/raulcd/arrow/actions/runs/12237252551/job/34132570615
with my change applied it is successful as seen here:
https://github.com/raulcd/arrow/actions/runs/12237520289/job/34133461978?pr=86
I've also created a PR with an associated issue with `GH-` prefix, which is successful and performs the required steps. See here:
https://github.com/raulcd/arrow/actions/runs/12237616405/job/34133767858?pr=88
and the PR: https://github.com/raulcd/arrow/pull/88

**Review by kou — APPROVED** [review]
+1

**Comment by raulcd** [comment]
This is not going to fix the issue, it still requires this commit to be included:
https://github.com/raulcd/arrow/commit/c2970257d5caba25107d50e9b7295a93edd979cb

**Comment by kou** [comment]
Oh, sorry. I checked only changes. I should have also checked affected file names.

**Pull request merged**
