### PR TITLE
ARROW-4609: [C++] Use google benchmark from toolchain

### PR DESCRIPTION
**Pull request by xhochy**

### CODE REVIEW

**Comment by kszucs** [comment]
@xhochy CI is failing.

**Comment by wesm** [comment]
The linker command looks fishy:

```
: && /home/travis/build/apache/arrow/cpp-toolchain/bin/ccache /usr/lib/ccache/g++  -ggdb -O0  -Wall -Wconversion -Wno-sign-conversion -Werror -msse4.2  -B/home/travis/build/apache/arrow/cpp-toolchain/bin -g  -rdynamic src/arrow/CMakeFiles/arrow-column-benchmark.dir/column-benchmark.cc.o  -o debug/arrow-column-benchmark  -Wl,-rpath,/home/travis/build/apache/arrow/cpp-build/debug:/home/travis/build/apache/arrow/cpp-toolchain/lib debug/libarrow_benchmark_main.a debug/libarrow_testing.so.13.0.0 debug/libarrow.so.13.0.0 -ldl /home/travis/build/apache/arrow/cpp-toolchain/lib/libdouble-conversion.a /home/travis/build/apache/arrow/cpp-toolchain/lib/libboost_system.so /home/travis/build/apache/arrow/cpp-toolchain/lib/libboost_filesystem.so /home/travis/build/apache/arrow/cpp-toolchain/lib/libboost_regex.so /home/travis/build/apache/arrow/cpp-toolchain/lib/libgtest.a /home/travis/build/apache/arrow/cpp-toolchain/lib/libgmock_main.a /home/travis/build/apache/arrow/cpp-toolchain/lib/libgmock.a -ldl /home/travis/build/apache/arrow/cpp-toolchain/lib/libbenchmark.a -lpthread jemalloc_ep-prefix/src/jemalloc_ep/dist//lib/libjemalloc_pic.a -pthread -lrt -Wl,-rpath-link,/home/travis/build/apache/arrow/cpp-toolchain/lib && :
```

the `-lpthread` is wrong. Our handling of pthreads is dealt with by the `Threads::Threads` variable which correctly adds `-pthread` (@fsaintjacques  was just telling me about the difference between these two things). This unfortunately is coming from gbenchmark's cmake config

```
set_target_properties(benchmark::benchmark PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "-lpthread"
)
```

This is a bug in gbenchmark. We may have to patch gbenchmark in conda-forge. See

https://stackoverflow.com/a/39547577/776560

also

https://github.com/apache/arrow/blob/master/cpp/cmake_modules/ThirdpartyToolchain.cmake#L397
* https://github.com/apache/arrow/blob/master/cpp/CMakeLists.txt#L837

**Comment by wesm** [comment]
I just submitted a PR to gbenchmark

https://github.com/google/benchmark/pull/771

**Comment by wesm** [comment]
Google accepted my PR. In the meantime I think we can handle this in the conda-forge build

https://github.com/conda-forge/benchmark-feedstock/pull/4

**Comment by wesm** [comment]
Hm, it looks like the gbenchmark fix was not sufficient. It seems that the conda-forge packages for gbenchmark are not usable with the Ubuntu Xenial system compilers

cc @pitrou

**Comment by pitrou** [comment]
libstdc++ on 18.04 (Bionic) does have the required symbols:
```
$ nm --defined-only --demangle /home/antoine/miniconda3/envs/pyarrow/lib/libstdc++.so.6 | \grep std::thread::_M_start_thread
00000000000b8738 T std::thread::_M_start_thread(std::shared_ptr<std::thread::_Impl_base>)
00000000000b869e T std::thread::_M_start_thread(std::shared_ptr<std::thread::_Impl_base>, void (*)())
00000000000b8576 T std::thread::_M_start_thread(std::unique_ptr<std::thread::_State, std::default_delete<std::thread::_State> >, void (*)())
```

Perhaps it's a matter of linker option order? Does `libbenchmark.a` have to come before `libarrow.so`?

**Comment by wesm** [comment]
In Travis here I think the Ubuntu 16.04 toolchain is being used

**Comment by wesm** [comment]
What do you want to do with this patch? Seems that using the CF packages with Ubuntu Xenial's gcc 5.4 is a non-starter

**Comment by xhochy** [comment]
I'm addressing this in https://github.com/apache/arrow/pull/3688

**Pull request closed without merging**
