### PR TITLE
ARROW-16955: [CI] Upgrade setup-python github action to v4

### PR DESCRIPTION
**Pull request by raulcd**

### CODE REVIEW

**Comment by raulcd** [comment]
@zeroshade I don't think the failure has anything to do with the change I made as the python version installed for archery is a different one than the used inside the docker container but I wanted to validate with you if you think it might be related. Have you seen this failure before? I have tried locally and it worked:
```
$ DEBIAN=11 docker-compose run --rm debian-go-cgo-python
...
+ python test_export_to_cgo.py
test_get_batch (__main__.TestGoToPython) ... ok
test_get_schema (__main__.TestGoToPython) ... ok
test_record_batch (__main__.TestPythonToGo) ... record batch matches huzzah!
ok
test_schema (__main__.TestPythonToGo) ... schema matches! Huzzah!
ok
test_batch_roundtrip (__main__.TestRoundTrip) ... ok
test_schema_roundtrip (__main__.TestRoundTrip) ... ok

----------------------------------------------------------------------
Ran 6 tests in 0.045s

OK
...
```
and the version is the same one that gets installed on the runner:
```
$ DEBIAN=11 docker-compose run --rm debian-go-cgo-python /bin/bash
root@88d538328e7f:/go# python --version
Python 3.9.2
```

**Comment by raulcd** [comment]
This is the failure on the github runner:
```
 ======================================================================
FAIL: test_record_batch (__main__.TestPythonToGo)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/arrow/go/arrow/cdata/test/test_export_to_cgo.py", line 103, in test_record_batch
    cgotest.importRecordBatch(self.ptr_schema, self.ptr_array)
  File "/usr/lib/python3.9/contextlib.py", line 124, in __exit__
    next(self.gen)
  File "/arrow/go/arrow/cdata/test/test_export_to_cgo.py", line 82, in assert_pyarrow_memory_released
    self.assertEqual(
AssertionError: 352 != 0 : PyArrow memory was not adequately released: 352 bytes lost
----------------------------------------------------------------------
Ran 6 tests in 0.107s
```

**Comment by raulcd** [comment]
@kou I think the single job failure is not related (maybe we can re-run the failed job?). What do you think about this change?

**Comment by zeroshade** [comment]
@raulcd I haven't managed to narrow down what makes that intermittent failure, I'm guessing there's some nuance to the Python garbage collector / how it interacts with calling the callback to Go that I'm missing. Generally if you just re-run the job it'll go away. Once I have the time to dig deeper on that I'll try to fix it, but for now just re-running it should be sufficient.

**Review by kou — APPROVED** [review]
+1

I re-ran the job and it passed. We can dig on it later as @zeroshade said.

**Pull request merged**
