### PR TITLE
ARROW-8294: [Flight] Add DoExchange to Flight.proto

### PR DESCRIPTION
**Pull request by lidavidm**
This is the proposed addition of the DoExchange endpoint to Flight for the mailing list discussion.

### CODE REVIEW

**Comment by jacques-n** [comment]
I'm in support of this. +1

**Comment by pitrou** [comment]
LGTM as well.

**Comment by wesm** [comment]
Vote about this is open on the mailing list

**Review by wesm — APPROVED** [review]
+1. Merging since vote has carried on the ML

**Pull request closed without merging**
