### PR TITLE
ARROW-1991: [Website] Fix Docker documentation build

### PR DESCRIPTION
**Pull request by wesm**
@kou something is failing here, I'm not sure what's different here vs. Travis CI (not sure if this is what's failing the doc build):

```
  DOC   Building HTML
../arrow-glib-docs.xml:25: warning: failed to load external entity "../xml/gtkdocentities.ent"
  %gtkdocentities;
                  ^
Entity: line 1: 
 %gtkdocentities; 
                 ^
../arrow-glib-docs.xml:29: parser error : Entity 'package_name' not defined
    <title>&package_name; Reference Manual</title>
                         ^
../arrow-glib-docs.xml:31: parser error : Entity 'package_string' not defined
      for &package_string;.
                          ^
warning: failed to load external entity "../xml/basic-array.xml"
../arrow-glib-docs.xml:43: element include: XInclude error : could not load ../xml/basic-array.xml, and no fallback was found
warning: failed to load external entity "../xml/composite-array.xml"
../arrow-glib-docs.xml:44: element include: XInclude error : could not load ../xml/composite-array.xml, and no fallback was found
../xml/array-builder.xml:25: warning: failed to load external entity "../xml/xml/gtkdocentities.ent"
  %gtkdocentities;
```

### CODE REVIEW

**Comment by kou** [comment]
I'll look into this.

**Comment by kou** [comment]
It's caused by old GTK-Doc. Can we use Ubuntu 16.04 LTS instead of 14.04 LTS to use more recent GTK-Doc?

[0001-Update-GTK-Doc-to-build-GLib-document-perfectly.txt](https://github.com/apache/arrow/files/1628405/0001-Update-GTK-Doc-to-build-GLib-document-perfectly.txt)

**Comment by kou** [comment]
Thanks. Then the attached patch at https://github.com/apache/arrow/pull/1472#issuecomment-357436941 will fix this problem.

**Comment by wesm** [comment]
Applied the patch and rebuilt the image (`docker-compose build gen_apidocs`) but then:

```
Making distclean in arrow-glib
make[1]: Entering directory '/apache-arrow/arrow/c_glib/arrow-glib'
/bin/bash: /home/ubuntu/miniconda/envs/pyarrow-dev/lib/libtinfo.so.5: no version information available (required by /bin/bash)
/bin/bash: /home/ubuntu/miniconda/envs/pyarrow-dev/lib/libtinfo.so.5: no version information available (required by /bin/bash)
 cd .. && /bin/bash /apache-arrow/arrow/c_glib/config/missing automake-1.14 --foreign arrow-glib/Makefile
/bin/bash: /home/ubuntu/miniconda/envs/pyarrow-dev/lib/libtinfo.so.5: no version information available (required by /bin/bash)
/apache-arrow/arrow/c_glib/config/missing: line 81: automake-1.14: command not found
WARNING: 'automake-1.14' is missing on your system.
         You should only need it if you modified 'Makefile.am' or
         'configure.ac' or m4 files included by 'configure.ac'.
         The 'automake' program is part of the GNU Automake package:
         <http://www.gnu.org/software/automake>
         It also requires GNU Autoconf, GNU m4 and Perl in order to run:
         <http://www.gnu.org/software/autoconf>
         <http://www.gnu.org/software/m4/>
         <http://www.perl.org/>
Makefile:533: recipe for target 'Makefile.in' failed
make[1]: *** [Makefile.in] Error 127
make[1]: Leaving directory '/apache-arrow/arrow/c_glib/arrow-glib'
Makefile:511: recipe for target 'distclean-recursive' failed
make: *** [distclean-recursive] Error 1
```

Not sure what I did wrong

**Comment by kou** [comment]
This patch may fix this.

[0001-Disable-auto-re-configure-on-GLib-doc-build.txt](https://github.com/apache/arrow/files/1637256/0001-Disable-auto-re-configure-on-GLib-doc-build.txt)

**Comment by wesm** [comment]
+1

**Pull request closed without merging**
