### PR TITLE
GH-44828: [Java][Release] Remove Java from release scripts

### PR DESCRIPTION
**Pull request by lidavidm**
### Rationale for this change
Java has been moved to its own repo.

### What changes are included in this PR?
Remove Java/Maven from dev/release.

### Are these changes tested?

N/A

### Are there any user-facing changes?

No
* GitHub Issue: #44828

### CODE REVIEW

**Comment by lidavidm** [comment]
@github-actions crossbow submit -g verify-rc-source

**Review by kou — APPROVED** [review]
+1

But we should merge this after we update docs for 18.1.0. Because it uses `post-10-docs.sh` that is changed by this PR.

**Comment by lidavidm** [comment]
I think 18.1.0 is out - are we good to go here? If so I'll rebase

**Comment by kou** [comment]
Yes! Let's merge this!

**Pull request merged**
