### PR TITLE
ARROW-11306: [Packaging][Ubuntu][16.04] Add missing libprotobuf-dev dependency

### PR DESCRIPTION
**Pull request by kou**

### CODE REVIEW

**Comment by kou** [comment]
@github-actions crossbow submit ubuntu-xenial-*

**Comment by kou** [comment]
@github-actions crossbow submit -p release=3.0.0 -p rc=1 verify-rc-apt

**Comment by kou** [comment]
@github-actions crossbow submit -p release=3.0.0 -p rc=1 verify-rc-binaries-apt

**Review by kszucs — APPROVED** [review]
Things look good, merging on green crossbow builds.

**Comment by kou** [comment]
We'll fix the new Groovy error as another task.

**Pull request closed without merging**
