### PR TITLE
One definition/repetition level test

### PR DESCRIPTION
**Pull request by carols10cents**
Hey @nevi-me, before I go write a bunch of these, is this what would be useful for testing levels? Is there an easier way to create the arrays? 

I'm basing these on [tests in the C++ implementation](https://github.com/apache/arrow/blob/4bbb74713c6883e8523eeeb5ac80a1e1f8521674/cpp/src/parquet/arrow/path_internal_test.cc) that have a nice JSON constructor, and I tried using the [JSON Reader](https://github.com/apache/arrow/blob/4bbb74713c6883e8523eeeb5ac80a1e1f8521674/rust/arrow/src/json/reader.rs) but I couldn't get what I created with the JSON Reader to what I created that I currently have here :-/ 

Thank you for any feedback you have!

### CODE REVIEW

**Comment by nevi-me** [comment]
If you don't mind, can we keep this as a draft, so I can also add the work that I've been doing on repetitions? I've been focusing more on nested def and rep, such a headache though.

**Comment by carols10cents** [comment]
Yup, we can keep this as a draft, no problem! I'll be rebasing and adding to this on Wednesday.

**Comment by carols10cents** [comment]
@nevi-me So @shepmaster and I wrote some more tests, but they're failing and we're not sure if our setup is wrong or if they're expected to fail? What do you think?

**Comment by carols10cents** [comment]
I think I'm going to close this one for now; I don't think it's useful until the def/rep levels are a bit further along.

**Pull request closed without merging**
