### PR TITLE
ARROW-4163: [Gandiva] Add logical query plan to Gandiva protobuf

### PR DESCRIPTION
**Pull request by andygrove**
I'm creating this PR to start a discussion around adding logical query plans to the Gandiva protobuf definition.

I would like a standardized way of defining queries against Arrow data sources.

I am interested in contributing a Rust implementation of query execution to Arrow.

### CODE REVIEW

**Comment by wesm** [comment]
hey @andygrove -- I think we should take a step back and discuss this on the mailing list. 

The Gandiva library as it stands right now is not a query engine or an execution engine, properly speaking. It is a _subgraph compiler_ for creating accelerated expressions for use inside another execution or query engine. 

For this reason I am -1 on adding this to Gandiva until a more rigorous design effort takes place to decide where to build an actual query/execution engine (which includes file / dataset scanners, projections, joins, aggregates, filters, etc.) in C++. My preference is to start building a from-the-ground-up system that will call into Gandiva to compile expressions during execution

**Comment by wesm** [comment]
If you want to start creating an (experimental) Protobuf / Flatbuffer definition to define a general query execution plan (separate from Gandiva) to assist with building a query engine in Rust, I think that is fine, but I want to make sure we are being deliberate and layering the project components in a good way

**Comment by wesm** [comment]
I replied on the mailing list, we can continue discussing there

**Comment by andygrove** [comment]
See discussion on mailing list ...

**Pull request closed without merging**
