### PR TITLE
WIP: [R] Verify CRAN release-18.1.0-rc2

### PR DESCRIPTION
**Pull request by amoeba**
> [!CAUTION]
> Do not merge this PR.
>
> This PR is being used to prepare for the CRAN submission for 18.1.0.

See packaging checklist: https://github.com/apache/arrow/issues/44913.

### CODE REVIEW

**Comment by amoeba** [comment]
@github-actions crossbow submit --group r

**Comment by amoeba** [comment]
@github-actions crossbow submit r-recheck-most

**Comment by amoeba** [comment]
@github-actions crossbow submit r-recheck-most

**Comment by jonkeane** [comment]
The devdocs build always seems to fail on these branches but that's ok. I suspect (but haven't dug to the bottom to confirm this) is that we are installing from apt the release version and we are installing the same version so our use-the-dev-version code isn't catching like it does in all other circumstances. (it failed for https://github.com/apache/arrow/pull/44523 as well, but it is passing in the nightlies)

The failure of `test-r-rhub-debian-gcc-devel-lto-latest` is a bit more concerning. It looks like that's been failing for 12 days now. I don't see anything obvious in our repo just after https://github.com/apache/arrow/compare/27bbd593625122a4a25d9471c8aaf5df54a6dcf9...0cdbdac413fa1e7acaf0362eb8ca8fd1911d2a9e but I also don't see any changes in the image that these run on either: https://github.com/r-hub/containers/commits/main/ *But* those tests [don't run on CRAN](https://github.com/apache/arrow/blob/50f2d6e04e8323119d4dd31506827ee398d6b8e4/r/tests/testthat/test-dplyr-funcs-datetime.R#L269), so we should be ok to submit, though we should make an issue and figure out what's up there.

The recheck job looks red, but I think it's ok looking at the output? Am I reading that correctly?

**Comment by amoeba** [comment]
Thanks for taking a look @jonkeane. 

1. Re: `devocs-ubuntu`: Ah, yep. I should've checked previous runs. Good thing to note.
2. Re: `test-r-rhub-debian-gcc-devel-lto-latest`, I'll file an issue for that in a bit. 
3. Re: `r-recheck`: I agree that this is just noise and that we're good in terms of revdep checks.

**Comment by amoeba** [comment]
Closing as we're done testing and 18.1.0 is on CRAN.

**Pull request closed without merging**
