### PR TITLE
ARROW-2071: [Python] Lighten serialization tests

### PR DESCRIPTION
**Pull request by pitrou**
Attempt to reduce running times on Travis-CI.

Note this PR integrates the contents of PR #1548 to get the builds running at all.

### CODE REVIEW

**Comment by pitrou** [comment]
Ok, we're down to:
```
39.21s call     pyarrow-test-3.6/lib/python3.6/site-packages/pyarrow/tests/test_serialization.py::test_primitive_serialization
21.64s call     pyarrow-test-3.6/lib/python3.6/site-packages/pyarrow/tests/test_serialization.py::test_custom_serialization
```

compared to (before):
```
236.05s call     pyarrow-test-3.6/lib/python3.6/site-packages/pyarrow/tests/test_serialization.py::test_custom_serialization
38.78s call     pyarrow-test-3.6/lib/python3.6/site-packages/pyarrow/tests/test_serialization.py::test_primitive_serialization
```

It still don't understand what makes those tests so long in the first place. @wesm

**Comment by pitrou** [comment]
Here are the runtimes on the manylinux Travis-CI job:
```
========================== slowest 15 test durations ===========================
3.96s call     tests/test_plasma.py::TestPlasmaClient::test_create_with_metadata
2.35s call     tests/test_plasma.py::TestPlasmaClient::test_get
1.91s call     tests/test_plasma.py::TestPlasmaClient::test_subscribe_deletions
1.53s call     tests/test_plasma.py::TestPlasmaClient::test_store_full
1.32s call     tests/test_plasma.py::TestPlasmaClient::test_subscribe
1.27s call     tests/test_plasma.py::TestPlasmaClient::test_use_one_memory_mapped_file
1.15s call     tests/test_plasma.py::TestPlasmaClient::test_create_existing
1.10s call     tests/test_feather.py::TestFeatherReader::test_buffer_bounds_error
0.98s call     tests/test_parquet.py::test_decimal_roundtrip
0.75s call     tests/test_serialization.py::test_deserialize_buffer_in_different_process
0.64s call     tests/test_plasma.py::TestPlasmaClient::test_many_hashes
0.46s call     tests/test_parquet.py::test_read_pandas_column_subset
0.46s call     tests/test_parquet.py::test_pandas_parquet_native_file_roundtrip
0.35s call     tests/test_parquet.py::test_pandas_parquet_column_multiindex
0.33s call     tests/test_serialization.py::test_primitive_serialization
======== 513 passed, 47 skipped, 3 xfailed, 9 warnings in 27.87 seconds ========
```

There's really something weird with the offending Travis-CI job. Perhaps because it's building in debug mode?

**Comment by xhochy** [comment]
The offending job is compiled in debug mode and is run inside of valgrind. This is really costly, we should probably think of if we should run all Python versions inside of valgrind or simply activate ASAN on the Linux LLVM build.

**Comment by pitrou** [comment]
I might have misread, but I don't think the Python tests are run inside Valgrind?

**Comment by xhochy** [comment]
oh, yes. We only run the C++ tests inside of valgrind, then the only thing that comes to my mind is that they are build in debug mode.

**Comment by xhochy** [comment]
@pitrou can you rebase? The diff view includes some brotli changes and I'm a bit scared that a merge to master would mess things up. Otherwise this looks good to go.

**Comment by pitrou** [comment]
Rebased now.

**Review by xhochy — APPROVED** [review]
+1, nice!

**Pull request closed without merging**
