### PR TITLE
PARQUET-1704: [C++] Add re-usable encryption buffer to SerializedPageWriter

### PR DESCRIPTION
**Pull request by orozery**
See: https://issues.apache.org/jira/browse/PARQUET-1704

### CODE REVIEW

**Comment by pitrou** [comment]
Sounds reasonable. Same question as on the other PR: can the buffer size grow unbounded?

Also, out of curiosity: which profiler GUI are you using on your screeshot?

**Comment by orozery** [comment]
The encryption buffer size equals the size of the compressed page size + few more bytes.
The compressed page size is bounded approximately by the page size property (set at Parquet::WriterProperties, and defaults to 1MB).
So yes, its size is bounded.

The screenshot is of kcachegrind, parsing on output from callgrind.

**Review by pitrou — APPROVED** [review]
+1 from me.

**Comment by pitrou** [comment]
Pinging @wesm in case he wants to give this a look.

**Comment by pitrou** [comment]
Rebased, will merge if green.

**Pull request closed without merging**
