### PR TITLE
ARROW-973: [Website] Add FAQ page

### PR DESCRIPTION
**Pull request by nealrichardson**
This needs at least one more answer and probably other questions that get asked frequently.

### CODE REVIEW

**Comment by pitrou** [comment]
"""Flatbuffers is a domain-agnostic low-level building block for binary data formats. It cannot be used directly for data analysis tasks without a lot of manual scaffolding. Arrow on the other hand is a data layer aimed directly at the needs of data analysis, providing elaborate data types (including extensible logical types), built-in support for "null" values (a.k.a "N/A"), and an expanding toolbox of I/O and computing facilities.

Anecdotically, the Arrow file format uses Flatbuffers under the hood to facilitate low-level metadata serialization. However, Arrow data has much richer semantics than Flatbuffers data."""

**Comment by pitrou** [comment]
"""How stable is the Arrow format? Is it risky to start using it now in my application?

In general, we do not recommend the Arrow *file* format for long-term disk persistence of data yet.

However, the Arrow *in-memory* format is considered stable, and we pledge to only make backwards-compatible additions such as additional datatypes. We encourage people to start building Arrow-based in-memory computing applications right now, and choose a suitable file format for disk storage if necessary. The Arrow libraries include adapters for several file formats, including Parquet, ORC, CSV and JSON.
"""

(is "pledge" too strong perhaps? "strive"?)

**Comment by pitrou** [comment]
PS: should the FAQ be part of the Sphinx docs?

**Comment by wesm** [comment]
I can see the argument for using the Sphinx docs, while having a link from the titlebar on the main webpage

**Comment by nealrichardson** [comment]
I'll add the link to the title bar regardless. IMO it makes more sense here, at the top level alongside the installation guide, rather than nested under `/docs/`.

**Comment by pitrou** [comment]
The main point of having this be a Sphinx doc would be to easily cross-reference between the FAQ and other doc sections. Anyway, the .md is simple enough that it can be easily converted to .rst later ;-)

**Comment by nealrichardson** [comment]
Yep, and probably not worth considering until there's something we want to cross-reference.

**Review by wesm — APPROVED** [review]
+1. see https://issues.apache.org/jira/browse/ARROW-5543 about sphinxifying

**Pull request closed without merging**
