### PR TITLE
GH-39876: [C++] Thirdparty: Bump zlib to 1.3.1

### LINKED ISSUE #39876: [C++] Thirdparty: Bump zlib to 1.3.1
### Describe the enhancement requested

zlib 1.3.1 is released, which containing some bugfix: https://github.com/madler/zlib/releases/tag/v1.3.1

We're currently default using zlib 1.3, so maybe we can bump it

### Component(s)

C++

### PR DESCRIPTION
**Pull request by mapleFU**
### Rationale for this change

zlib 1.3.1 is the latest release.

### What changes are included in this PR?

Bump zlib to 1.3.1

### Are these changes tested?

Already has testing

### Are there any user-facing changes?

no

* Closes: #39876

### CODE REVIEW

**Review by zeroshade — APPROVED** [review]
LGTM assuming no issues in CI

**Comment by mapleFU** [comment]
@github-actions crossbow submit -g nightly-tests -g r

**Comment by mapleFU** [comment]
@github-actions crossbow submit -g nightly-tests -g r

**Comment by mapleFU** [comment]
cc @kou @pitrou

**Review by kou — APPROVED** [review]
+1

**Pull request merged**
