### PR TITLE
ARROW-5371: [Release] Add tests for dev/release/00-prepare.sh

### PR DESCRIPTION
**Pull request by kou**
Test is implemented by Ruby and test-unit.

How to test:

  * Clone the current Git repository for test
  * Run `dev/release/00-prepare.sh` in test test repository
  * Check diff in `git log -n 1 -p`

### CODE REVIEW

**Comment by kou** [comment]
AppVeyor build failure is unrelated because this doesn't touch any Windows related things.
https://ci.appveyor.com/project/ApacheSoftwareFoundation/arrow/builds/24640234

**Comment by shiro615** [comment]
I got the following result on macOS.
<details><summary>details</summary>

```rb
$ dev/release/run-test.rb                                         (git)-[release-prepare-test]
Loaded suite release
Started
.F
===============================================================================================
/Users/shiro/dev/arrow_kou/dev/release/00-prepare-test.rb:29:in `setup'
/Users/shiro/.rbenv/versions/2.6.0/lib/ruby/2.6.0/tmpdir.rb:89:in `mktmpdir'
/Users/shiro/dev/arrow_kou/dev/release/00-prepare-test.rb:32:in `block in setup'
/Users/shiro/dev/arrow_kou/dev/release/00-prepare-test.rb:32:in `chdir'
/Users/shiro/dev/arrow_kou/dev/release/00-prepare-test.rb:39:in `block (2 levels) in setup'
     73:
     74:   def test_update_version_pre_tag
     75:     prepare("VERSION_PRE_TAG")
  => 76:     assert_equal([
     77:                    {
     78:                      path: "c_glib/configure.ac",
     79:                      hunks: [
/Users/shiro/dev/arrow_kou/dev/release/00-prepare-test.rb:76:in `test_update_version_pre_tag'
<[{:hunks=>
   [["-m4_define([arrow_glib_version], 0.14.0-SNAPSHOT)",
     "+m4_define([arrow_glib_version], 0.14.0)"]],
  :path=>"c_glib/configure.ac"},
 {:hunks=>[["-version = '0.14.0-SNAPSHOT'", "+version = '0.14.0'"]],
  :path=>"c_glib/meson.build"},
 {:hunks=>
   [["-set(ARROW_VERSION \"0.14.0-SNAPSHOT\")",
     "+set(ARROW_VERSION \"0.14.0\")"]],
  :path=>"cpp/CMakeLists.txt"},
 {:hunks=>
   [["-    <Version>0.14.0-SNAPSHOT</Version>",
     "+    <Version>0.14.0</Version>"]],
  :path=>"csharp/Directory.Build.props"},
 {:hunks=>
   [["-  \"version\": \"0.14.0-SNAPSHOT\"", "+  \"version\": \"0.14.0\""]],
  :path=>"js/package.json"},
 {:hunks=>
   [["-set(MLARROW_VERSION \"0.14.0-SNAPSHOT\")",
     "+set(MLARROW_VERSION \"0.14.0\")"]],
  :path=>"matlab/CMakeLists.txt"},
 {:hunks=>
   [["-default_version = '0.14.0-SNAPSHOT'", "+default_version = '0.14.0'"]],
  :path=>"python/setup.py"},
 {:hunks=>[["-Version: 0.13.0.9000", "+Version: 0.14.0"]],
  :path=>"r/DESCRIPTION"},
 {:hunks=>[["-VERSION = 0.13.0.9000", "+VERSION = 0.14.0"]],
  :path=>"r/src/Makevars.win"},
 {:hunks=>[["-  VERSION = \"0.14.0-SNAPSHOT\"", "+  VERSION = \"0.14.0\""]],
  :path=>"ruby/red-arrow-cuda/lib/arrow-cuda/version.rb"},
 {:hunks=>[["-  VERSION = \"0.14.0-SNAPSHOT\"", "+  VERSION = \"0.14.0\""]],
  :path=>"ruby/red-arrow/lib/arrow/version.rb"},
 {:hunks=>[["-  VERSION = \"0.14.0-SNAPSHOT\"", "+  VERSION = \"0.14.0\""]],
  :path=>"ruby/red-gandiva/lib/gandiva/version.rb"},
 {:hunks=>[["-  VERSION = \"0.14.0-SNAPSHOT\"", "+  VERSION = \"0.14.0\""]],
  :path=>"ruby/red-parquet/lib/parquet/version.rb"},
 {:hunks=>[["-  VERSION = \"0.14.0-SNAPSHOT\"", "+  VERSION = \"0.14.0\""]],
  :path=>"ruby/red-plasma/lib/plasma/version.rb"},
 {:hunks=>[["-version = \"0.14.0-SNAPSHOT\"", "+version = \"0.14.0\""]],
  :path=>"rust/arrow/Cargo.toml"},
 {:hunks=>[["-version = \"0.14.0-SNAPSHOT\"", "+version = \"0.14.0\""]],
  :path=>"rust/datafusion/Cargo.toml"},
 {:hunks=>[["-datafusion = \"0.14.0-SNAPSHOT\"", "+datafusion = \"0.14.0\""]],
  :path=>"rust/datafusion/README.md"},
 {:hunks=>[["-version = \"0.14.0-SNAPSHOT\"", "+version = \"0.14.0\""]],
  :path=>"rust/parquet/Cargo.toml"},
 {:hunks=>
   [["-parquet = \"0.14.0-SNAPSHOT\"", "+parquet = \"0.14.0\""],
    ["-See [crate documentation](https://docs.rs/crate/parquet/0.14.0-SNAPSHOT) on available API.",
     "+See [crate documentation](https://docs.rs/crate/parquet/0.14.0) on available API."]],
  :path=>"rust/parquet/README.md"}]> expected but was
<[{:hunks=>
   [["-m4_define([arrow_glib_version], 0.14.0-SNAPSHOT)",
     "+m4_define([arrow_glib_version], 0.14.0)"]],
  :path=>"c_glib/configure.ac"},
 {:hunks=>[["-version = '0.14.0-SNAPSHOT'", "+version = '0.14.0'"]],
  :path=>"c_glib/meson.build"},
 {:hunks=>
   [["-set(ARROW_VERSION \"0.14.0-SNAPSHOT\")",
     "+set(ARROW_VERSION \"0.14.0\")"]],
  :path=>"cpp/CMakeLists.txt"},
 {:hunks=>
   [["-    <Version>0.14.0-SNAPSHOT</Version>",
     "+    <Version>0.14.0</Version>"],
    ["-</Project>", "+</Project>"]],
  :path=>"csharp/Directory.Build.props"},
 {:hunks=>
   [["-  \"version\": \"0.14.0-SNAPSHOT\"", "+  \"version\": \"0.14.0\""]],
  :path=>"js/package.json"},
 {:hunks=>
   [["-set(MLARROW_VERSION \"0.14.0-SNAPSHOT\")",
     "+set(MLARROW_VERSION \"0.14.0\")"]],
  :path=>"matlab/CMakeLists.txt"},
 {:hunks=>
   [["-default_version = '0.14.0-SNAPSHOT'", "+default_version = '0.14.0'"]],
  :path=>"python/setup.py"},
 {:hunks=>[["-Version: 0.13.0.9000", "+Version: 0.14.0"]],
  :path=>"r/DESCRIPTION"},
 {:hunks=>[["-VERSION = 0.13.0.9000", "+VERSION = 0.14.0"]],
  :path=>"r/src/Makevars.win"},
 {:hunks=>[["-  VERSION = \"0.14.0-SNAPSHOT\"", "+  VERSION = \"0.14.0\""]],
  :path=>"ruby/red-arrow-cuda/lib/arrow-cuda/version.rb"},
 {:hunks=>[["-  VERSION = \"0.14.0-SNAPSHOT\"", "+  VERSION = \"0.14.0\""]],
  :path=>"ruby/red-arrow/lib/arrow/version.rb"},
 {:hunks=>[["-  VERSION = \"0.14.0-SNAPSHOT\"", "+  VERSION = \"0.14.0\""]],
  :path=>"ruby/red-gandiva/lib/gandiva/version.rb"},
 {:hunks=>[["-  VERSION = \"0.14.0-SNAPSHOT\"", "+  VERSION = \"0.14.0\""]],
  :path=>"ruby/red-parquet/lib/parquet/version.rb"},
 {:hunks=>[["-  VERSION = \"0.14.0-SNAPSHOT\"", "+  VERSION = \"0.14.0\""]],
  :path=>"ruby/red-plasma/lib/plasma/version.rb"},
 {:hunks=>[["-version = \"0.14.0-SNAPSHOT\"", "+version = \"0.14.0\""]],
  :path=>"rust/arrow/Cargo.toml"},
 {:hunks=>[["-version = \"0.14.0-SNAPSHOT\"", "+version = \"0.14.0\""]],
  :path=>"rust/datafusion/Cargo.toml"},
 {:hunks=>[["-datafusion = \"0.14.0-SNAPSHOT\"", "+datafusion = \"0.14.0\""]],
  :path=>"rust/datafusion/README.md"},
 {:hunks=>
   [["-version = \"0.14.0-SNAPSHOT\"", "+version = \"0.14.0\""],
    ["-rand = \"0.5\"", "+rand = \"0.5\""]],
  :path=>"rust/parquet/Cargo.toml"},
 {:hunks=>
   [["-parquet = \"0.14.0-SNAPSHOT\"", "+parquet = \"0.14.0\""],
    ["-See [crate documentation](https://docs.rs/crate/parquet/0.14.0-SNAPSHOT) on available API.",
     "+See [crate documentation](https://docs.rs/crate/parquet/0.14.0) on available API."]],
  :path=>"rust/parquet/README.md"}]>

diff:
  [{:hunks=>
     [["-m4_define([arrow_glib_version], 0.14.0-SNAPSHOT)",
       "+m4_define([arrow_glib_version], 0.14.0)"]],
    :path=>"c_glib/configure.ac"},
   {:hunks=>[["-version = '0.14.0-SNAPSHOT'", "+version = '0.14.0'"]],
    :path=>"c_glib/meson.build"},
   {:hunks=>
     [["-set(ARROW_VERSION \"0.14.0-SNAPSHOT\")",
       "+set(ARROW_VERSION \"0.14.0\")"]],
    :path=>"cpp/CMakeLists.txt"},
   {:hunks=>
     [["-    <Version>0.14.0-SNAPSHOT</Version>",
?      "+    <Version>0.14.0</Version>"]],
+     ["-</Project>", "+</Project>"]],
    :path=>"csharp/Directory.Build.props"},
   {:hunks=>
     [["-  \"version\": \"0.14.0-SNAPSHOT\"", "+  \"version\": \"0.14.0\""]],
    :path=>"js/package.json"},
   {:hunks=>
     [["-set(MLARROW_VERSION \"0.14.0-SNAPSHOT\")",
       "+set(MLARROW_VERSION \"0.14.0\")"]],
    :path=>"matlab/CMakeLists.txt"},
   {:hunks=>
     [["-default_version = '0.14.0-SNAPSHOT'", "+default_version = '0.14.0'"]],
    :path=>"python/setup.py"},
   {:hunks=>[["-Version: 0.13.0.9000", "+Version: 0.14.0"]],
    :path=>"r/DESCRIPTION"},
   {:hunks=>[["-VERSION = 0.13.0.9000", "+VERSION = 0.14.0"]],
    :path=>"r/src/Makevars.win"},
   {:hunks=>[["-  VERSION = \"0.14.0-SNAPSHOT\"", "+  VERSION = \"0.14.0\""]],
    :path=>"ruby/red-arrow-cuda/lib/arrow-cuda/version.rb"},
   {:hunks=>[["-  VERSION = \"0.14.0-SNAPSHOT\"", "+  VERSION = \"0.14.0\""]],
    :path=>"ruby/red-arrow/lib/arrow/version.rb"},
   {:hunks=>[["-  VERSION = \"0.14.0-SNAPSHOT\"", "+  VERSION = \"0.14.0\""]],
    :path=>"ruby/red-gandiva/lib/gandiva/version.rb"},
   {:hunks=>[["-  VERSION = \"0.14.0-SNAPSHOT\"", "+  VERSION = \"0.14.0\""]],
    :path=>"ruby/red-parquet/lib/parquet/version.rb"},
   {:hunks=>[["-  VERSION = \"0.14.0-SNAPSHOT\"", "+  VERSION = \"0.14.0\""]],
    :path=>"ruby/red-plasma/lib/plasma/version.rb"},
   {:hunks=>[["-version = \"0.14.0-SNAPSHOT\"", "+version = \"0.14.0\""]],
    :path=>"rust/arrow/Cargo.toml"},
   {:hunks=>[["-version = \"0.14.0-SNAPSHOT\"", "+version = \"0.14.0\""]],
    :path=>"rust/datafusion/Cargo.toml"},
   {:hunks=>[["-datafusion = \"0.14.0-SNAPSHOT\"", "+datafusion = \"0.14.0\""]],
    :path=>"rust/datafusion/README.md"},
+  {:hunks=>
?  {:hunks=>[["-version = \"0.14.0-SNAPSHOT\"", "+version = \"0.14.0\""]],
?
+     ["-rand = \"0.5\"", "+rand = \"0.5\""]],
    :path=>"rust/parquet/Cargo.toml"},
   {:hunks=>
     [["-parquet = \"0.14.0-SNAPSHOT\"", "+parquet = \"0.14.0\""],
      ["-See [crate documentation](https://docs.rs/crate/parquet/0.14.0-SNAPSHOT) on available API.",
       "+See [crate documentation](https://docs.rs/crate/parquet/0.14.0) on available API."]],
    :path=>"rust/parquet/README.md"}]
Failure: test_update_version_pre_tag(PrepareTest)
===============================================================================================

Finished in 6.669908 seconds.
-----------------------------------------------------------------------------------------------
2 tests, 2 assertions, 1 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
50% passed
```
</details>

We may need to change to add `\n` like the following.

```diff
diff --git a/csharp/Directory.Build.props b/csharp/Directory.Build.props
index 2e345cb8..841f981c 100644
--- a/csharp/Directory.Build.props
+++ b/csharp/Directory.Build.props
@@ -38,4 +38,4 @@
     <Content Include="$(RepoRoot)LICENSE.txt" Pack="true" PackagePath="" />
   </ItemGroup>
-</Project>
\ No newline at end of file
+</Project>

diff --git a/rust/parquet/Cargo.toml b/rust/parquet/Cargo.toml
index b444a72b..1bf35661 100644
--- a/rust/parquet/Cargo.toml
+++ b/rust/parquet/Cargo.toml
@@ -44,4 +44,4 @@ arrow = { path = "../arrow" }
 [dev-dependencies]
 lazy_static = "1"
-rand = "0.5"
\ No newline at end of file
+rand = "0.5"
```

**Comment by kou** [comment]
Thanks for confirming this on macOS.
I've applied your diff.

Any other comments? I'll merge this when CI is green.

**Comment by wesm** [comment]
CI is passed. I opened https://issues.apache.org/jira/browse/ARROW-5398 about the Python Flight failure

**Comment by kou** [comment]
OK. I'll merge this.
If someone has any comments, feel free to open a new JIRA issue.

**Comment by kou** [comment]
@shiro615 Do you want to work on the following release related issues?

* [ARROW-5077 [Rust] Release process should change Cargo.toml to use release versions](https://issues.apache.org/jira/browse/ARROW-5077)
* [ARROW-5092 [C#] Source Link doesn't work with the C# release script](https://issues.apache.org/jira/browse/ARROW-5092)

Now, we can work on them with test.

**Comment by shiro615** [comment]
Yes. I'll try to work on them.

**Comment by kou** [comment]
Great!
If you have any problems, feel free to ask me on these issue or newly created pull requests.

**Pull request closed without merging**
