### PR TITLE
GH-38814: [C++][Parquet] Update parquet.thrift to sync with 2.10.0

### LINKED ISSUE #38814: [C++][Parquet] Update parquet.thrift to sync with 2.10.0
### Describe the enhancement requested

Apache Parquet has just released its format version 2.10.0: https://parquet.apache.org/blog/2023/11/20/2.10.0/. We need to update parquet.thirft and its generated source files to be in sync.

### Component(s)

C++, Parquet

### PR DESCRIPTION
**Pull request by wgtmac**
### Rationale for this change

Apache Parquet has just released its format version 2.10.0: https://parquet.apache.org/blog/2023/11/20/2.10.0/. We need to update parquet.thirft and its generated source files to be in sync.

### What changes are included in this PR?

Update parquet.thirft and its generated source files.

### Are these changes tested?

Make sure all tests pass.

### Are there any user-facing changes?

I don't think so.
* Closes: #38814

### CODE REVIEW

**Comment by wgtmac** [comment]
I just updated the thrift file. cc @pitrou @emkornfield

**Review by mapleFU — APPROVED** [review]
+1, Thanks!

**Comment by pitrou** [comment]
@github-actions crossbow submit -g cpp

**Comment by wgtmac** [comment]
> @github-actions crossbow submit -g cpp

Just curious, when should we execute this command? @pitrou

**Comment by wgtmac** [comment]
https://github.com/ursacomputing/crossbow/actions/runs/6943255937/job/18887922572 failed with following error. Let me create an issue:

```
[ RUN      ] TestArrowReaderAdHoc.ReadFloat16Files
/arrow/cpp/src/parquet/arrow/arrow_reader_writer_test.cc:4129: Failure
Failed
'reader->ReadTable(&table)' failed with NotImplemented: Support for codec 'snappy' not built
Google Test trace:
/arrow/cpp/src/parquet/arrow/arrow_reader_writer_test.cc:4123: path = /arrow/cpp/submodules/parquet-testing/data/float16_nonzeros_and_nans.parquet
[  FAILED  ] TestArrowReaderAdHoc.ReadFloat16Files (1 ms)
[----------] 6 tests from TestArrowReaderAdHoc (11 ms total)
```

**Comment by pitrou** [comment]
> > @github-actions crossbow submit -g cpp
> 
> Just curious, when should we execute this command? @pitrou

There is no rule about this. In this case, I was wondering if the newly-generated Thrift files could fail compiling on some platforms.

Just use your committer's intuition, really :-)

**Review by pitrou — APPROVED** [review]
+1, CI failures look unrelated

**Comment by mapleFU** [comment]
Does it has any rules for these codec in parquet-testing? Seems brotli, lz4/lz4_raw, zstd, snappy are all used there...

**Comment by mapleFU** [comment]
Will merge in one day if other doesn't have negative views.

**Pull request merged**
