### PR TITLE
WIP: [Release] Verify release-12.0.1-rc1

### PR DESCRIPTION
**Pull request by kou**
PR to verify Release Candidate

### CODE REVIEW

**Comment by kou** [comment]
@github-actions crossbow submit  --group verify-rc-source --param release=12.0.1 --param rc=1

**Comment by raulcd** [comment]
@github-actions crossbow submit  --group verify-rc-binaries --group verify-rc-wheels --param release=12.0.1 --param rc=1

**Comment by raulcd** [comment]
Revision: 36e5d972a54e31062c2f23f8155c325d8da6edfb

Submitted crossbow builds: [ursacomputing/crossbow @ release-12.0.1-rc1-with-bundled-protobuf-7](https://github.com/ursacomputing/crossbow/branches/all?query=release-12.0.1-rc1-with-bundled-protobuf-7)

|Task|Status|
|----|------|
|verify-rc-source-cpp-macos-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/5220571964/jobs/9423802984)|
|verify-rc-source-cpp-macos-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/5220572340/jobs/9423803661)|
|verify-rc-source-cpp-macos-conda-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/5220571395/jobs/9423801585)|
|verify-rc-source-csharp-macos-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/5220572849/jobs/9423804749)|
|verify-rc-source-csharp-macos-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/5220570563/jobs/9423800071)|
|verify-rc-source-go-macos-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/5220572853/jobs/9423804800)|
|verify-rc-source-go-macos-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/5220573686/jobs/9423806914)|
|verify-rc-source-integration-macos-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/5220570841/jobs/9423800524)|
|verify-rc-source-integration-macos-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/5220573463/jobs/9423806334)|
|verify-rc-source-integration-macos-conda-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/5220572106/jobs/9423803258)|
|verify-rc-source-java-macos-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/5220571087/jobs/9423801003)|
|verify-rc-source-js-macos-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/5220572552/jobs/9423804015)|
|verify-rc-source-js-macos-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/5220573351/jobs/9423805987)|
|verify-rc-source-python-macos-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/5220571578/jobs/9423801941)|
|verify-rc-source-python-macos-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/5220570159/jobs/9423799348)|
|verify-rc-source-python-macos-conda-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/5220573195/jobs/9423805594)|
|verify-rc-source-ruby-macos-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/5220573017/jobs/9424160950)|
|verify-rc-source-ruby-macos-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/5220570384/jobs/9423799691)|

**Comment by raulcd** [comment]
The source verification tasks on Mac above have been run with the following patch to use bundled Protobuf:
```
diff --git a/dev/release/verify-release-candidate.sh b/dev/release/verify-release-candidate.sh
index 12e6d9c..9bb39b2 100755
--- a/dev/release/verify-release-candidate.sh
+++ b/dev/release/verify-release-candidate.sh
@@ -602,6 +602,10 @@ test_and_install_cpp() {
     ARROW_CMAKE_OPTIONS="${ARROW_CMAKE_OPTIONS:-} -G ${CMAKE_GENERATOR}"
   fi
 
+  if [ "$(uname)" == "Darwin" ]; then
+    brew uninstall --force protobuf abseil grpc
+  fi
+
   cmake \
     -DARROW_BOOST_USE_SHARED=ON \
     -DARROW_BUILD_EXAMPLES=OFF \
@@ -638,6 +642,7 @@ test_and_install_cpp() {
     -DCMAKE_INSTALL_PREFIX=$ARROW_HOME \
     -DCMAKE_UNITY_BUILD=${CMAKE_UNITY_BUILD:-OFF} \
     -DGTest_SOURCE=BUNDLED \
+    -DProtobuf_SOURCE=BUNDLED \
     -DPARQUET_BUILD_EXAMPLES=ON \
     -DPARQUET_BUILD_EXECUTABLES=ON \
     -DPARQUET_REQUIRE_ENCRYPTION=ON \
```

**Comment by kou** [comment]
FYI: We can do it in `dev/tasks/verify-rc/`:

```diff
diff --git a/dev/tasks/verify-rc/github.macos.amd64.yml b/dev/tasks/verify-rc/github.macos.amd64.yml
index 506975e19..0b3b1b05b 100644
--- a/dev/tasks/verify-rc/github.macos.amd64.yml
+++ b/dev/tasks/verify-rc/github.macos.amd64.yml
@@ -51,6 +51,7 @@ jobs:
           brew install --overwrite git
           brew bundle --file=arrow/cpp/Brewfile
           brew bundle --file=arrow/c_glib/Brewfile
+          brew uninstall protobuf abseil grpc
       {% endif %}
 
       - uses: actions/setup-java@v2
@@ -69,6 +70,7 @@ jobs:
       - name: Run verification
         shell: bash
         env:
+          ARROW_CMAKE_OPTIONS: -DProtobuf_SOURCE=BUNDLED
           TEST_DEFAULT: 0
           TEST_{{ target|upper }}: 1
         {% if use_conda %}
diff --git a/dev/tasks/verify-rc/github.macos.arm64.yml b/dev/tasks/verify-rc/github.macos.arm64.yml
index 75a061c4d..d4c2f96be 100644
--- a/dev/tasks/verify-rc/github.macos.arm64.yml
+++ b/dev/tasks/verify-rc/github.macos.arm64.yml
@@ -40,11 +40,13 @@ jobs:
       - name: Run verification
         shell: bash
         env:
+          ARROW_CMAKE_OPTIONS: -DProtobuf_SOURCE=BUNDLED
           TEST_DEFAULT: 0
           TEST_{{ target|upper }}: 1
         run: |
           brew bundle --file=arrow/cpp/Brewfile
           brew bundle --file=arrow/c_glib/Brewfile
+          brew uninstall protobuf abseil grpc
           export PATH="$(brew --prefix node@16)/bin:$PATH"
           export PATH="$(brew --prefix ruby)/bin:$PATH"
           export PKG_CONFIG_PATH="$(brew --prefix ruby)/lib/pkgconfig"
```

**Comment by zeroshade** [comment]
@raulcd @kou I believe the currently failing Go benchmarking tests were addressed and fixed by https://github.com/apache/arrow/commit/b98342c000d55c4017571aa549fe56f9c87ebc96 If it matters / if we want to incorporate that etc.

**Comment by raulcd** [comment]
> @raulcd @kou I believe the currently failing Go benchmarking tests were addressed and fixed by [b98342c](https://github.com/apache/arrow/commit/b98342c000d55c4017571aa549fe56f9c87ebc96) If it matters / if we want to incorporate that etc.

which benchmarks? On the release branch I usually validate the source verification, binary generation and binary verification tasks and those were all successful. I am unsure whether the CI PR individual jobs are expected to pass but they usually don't, if those are the ones you are referring to.

**Comment by raulcd** [comment]
@ursabot please benchmark

**Comment by raulcd** [comment]
@ursabot please benchmark

**Pull request merged**
