### PR TITLE
ARROW-782: [C++] API cleanup, change public member access in DataType classes to functions, use class instead of struct

### PR DESCRIPTION
**Pull request by wesm**
Breaking APIs isn't ideal, but this one is fairly long overdue. The DataType classes are more than passive data carriers, and Google's C++ guide recommends using class instead of struct for this. That means we should put members in protected or private scope, and access them.

I also renamed a couple of things to help with code clarity

* `DataType::type` is now `DataType::id()`
* `Array::type_enum` is not `Array::type_id`

### CODE REVIEW

**Comment by wesm** [comment]
@kou I changed ` std::shared_ptr<DataType>*` to `DataType*`, it didn't seem like the object created has explicit ownership of this object but correct me if I'm wrong about that

**Comment by kou** [comment]
I think that it may cause GC related crash in bindings. But I'm not sure without trying it. So it's OK the change. If the change has a problem, I just revert the change.

**Comment by wesm** [comment]
Ok, the problem now is that the `type()` method returns a new shared_ptr; I will let you take care of it

**Comment by wesm** [comment]
+1

**Pull request closed without merging**
