### PR TITLE
ARROW-2613: [Docs] Update the gen_apidocs docker script

### PR DESCRIPTION
**Pull request by xhochy**

### CODE REVIEW

**Comment by xhochy** [comment]
@kou This sadly fails for Glib with the following:

```
+ make -j4 'GTK_DOC_V_XREF=: '
(CDPATH="${ZSH_VERSION+.}:" && cd .. && /bin/bash /apache-arrow/arrow/c_glib/config/missing autoheader)
/bin/bash: /home/ubuntu/miniconda/envs/pyarrow-dev/lib/libtinfo.so.5: no version information available (required by /bin/bash)
/bin/bash: /home/ubuntu/miniconda/envs/pyarrow-dev/lib/libtinfo.so.5: no version information available (required by /bin/bash)
rm -f stamp-h1
/bin/bash: /home/ubuntu/miniconda/envs/pyarrow-dev/lib/libtinfo.so.5: no version information available (required by /bin/bash)
touch ../config.h.in
/bin/bash: /home/ubuntu/miniconda/envs/pyarrow-dev/lib/libtinfo.so.5: no version information available (required by /bin/bash)
/bin/bash: /home/ubuntu/miniconda/envs/pyarrow-dev/lib/libtinfo.so.5: no version information available (required by /bin/bash)
cd . && /bin/bash ./config.status config.h
/bin/bash: /home/ubuntu/miniconda/envs/pyarrow-dev/lib/libtinfo.so.5: no version information available (required by /bin/bash)
/bin/bash: /home/ubuntu/miniconda/envs/pyarrow-dev/lib/libtinfo.so.5: no version information available (required by /bin/bash)
config.status: creating config.h
config.status: config.h is unchanged
/bin/bash: /home/ubuntu/miniconda/envs/pyarrow-dev/lib/libtinfo.so.5: no version information available (required by /bin/bash)
/bin/bash: /home/ubuntu/miniconda/envs/pyarrow-dev/lib/libtinfo.so.5: no version information available (required by /bin/bash)
make  all-recursive
/bin/bash: /home/ubuntu/miniconda/envs/pyarrow-dev/lib/libtinfo.so.5: no version information available (required by /bin/bash)
make[1]: Entering directory '/apache-arrow/arrow/c_glib/build_apidocs'
/bin/bash: /home/ubuntu/miniconda/envs/pyarrow-dev/lib/libtinfo.so.5: no version information available (required by /bin/bash)
Making all in arrow-glib
make[2]: Entering directory '/apache-arrow/arrow/c_glib/build_apidocs/arrow-glib'
/bin/bash: /home/ubuntu/miniconda/envs/pyarrow-dev/lib/libtinfo.so.5: no version information available (required by /bin/bash)
/bin/bash: /home/ubuntu/miniconda/envs/pyarrow-dev/lib/libtinfo.so.5: no version information available (required by /bin/bash)
/bin/bash: /home/ubuntu/miniconda/envs/pyarrow-dev/lib/libtinfo.so.5: no version information available (required by /bin/bash)
  GEN      stamp-enums.c
  GEN      stamp-enums.h
/bin/bash: line 3: --identifier-prefix: command not found
/bin/bash: line 3: --identifier-prefix: command not found
Makefile:1225: recipe for target 'stamp-enums.c' failed
make[2]: *** [stamp-enums.c] Error 127
make[2]: *** Waiting for unfinished jobs....
Makefile:1213: recipe for target 'stamp-enums.h' failed
make[2]: *** [stamp-enums.h] Error 127
make[2]: Leaving directory '/apache-arrow/arrow/c_glib/build_apidocs/arrow-glib'
Makefile:526: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/apache-arrow/arrow/c_glib/build_apidocs'
Makefile:437: recipe for target 'all' failed
make: *** [all] Error 2
```

This looks like a required tool is not installed but I was unable to figure out which one.

**Comment by kou** [comment]
It's caused by GLib version mismatch.

The system GLib is 2.56.1 and the GLib installed by Miniconda is 2.55.0.
In the current configuration, we find the system GLib by `pkg-config` but we use `libglib.so` of the Miniconda GLib.

The following patch fixes this situation:

```diff
diff --git a/dev/gen_apidocs/create_documents.sh b/dev/gen_apidocs/create_documents.sh
index c6b19fd0..8571624a 100755
--- a/dev/gen_apidocs/create_documents.sh
+++ b/dev/gen_apidocs/create_documents.sh
@@ -26,7 +26,6 @@ export ARROW_BUILD_TYPE=release
 export ARROW_HOME=$(pwd)/apidocs-dist
 export PARQUET_HOME=$(pwd)/apidocs-dist
 CONDA_BASE=/home/ubuntu/miniconda
-export PKG_CONFIG_PATH=$(pwd)/apidocs-dist/lib/pkgconfig:${PKG_CONFIG_PATH}
 export PATH=${CONDA_BASE}/bin:${PATH}
 # For newer GCC per https://arrow.apache.org/docs/python/development.html#known-issues
 export CXXFLAGS="-D_GLIBCXX_USE_CXX11_ABI=0"
@@ -52,6 +51,8 @@ source activate pyarrow-dev
 export ARROW_BUILD_TOOLCHAIN=$CONDA_PREFIX
 export PARQUET_BUILD_TOOLCHAIN=$CONDA_PREFIX
 export LD_LIBRARY_PATH=$(pwd)/apidocs-dist/lib:${CONDA_PREFIX}/lib:${LD_LIBRARY_PATH}
+export PKG_CONFIG_PATH=${CONDA_PREFIX}/lib/pkgconfig:${PKG_CONFIG_PATH}
+export PKG_CONFIG_PATH=$(pwd)/apidocs-dist/lib/pkgconfig:${PKG_CONFIG_PATH}
 
 CPP_BUILD_DIR=$(pwd)/arrow/cpp/build_apidocs
 
```

**Comment by kou** [comment]
This is a trivial comment.

We just need `libglib2.0-dev` instead of `libgtk2.0-dev` for Apache Arrow GLib:

```diff
diff --git a/dev/gen_apidocs/Dockerfile b/dev/gen_apidocs/Dockerfile
index bac8dc21..a0ccbc4e 100644
--- a/dev/gen_apidocs/Dockerfile
+++ b/dev/gen_apidocs/Dockerfile
@@ -36,7 +36,7 @@ RUN apt-get update && \
         libgirepository1.0-dev \
         gtk-doc-tools \
         autogen \
-        libgtk2.0-dev \
+        libglib2.0-dev \
         autoconf-archive \
         npm
 
```

**Comment by kou** [comment]
Ah, sorry. `libglib2.0-dev` is already installed as a dependency of `libgirepository1.0-dev`.
We can replace `libgtk2.0-dev` with `libtool`.

And `autogen` isn't needed. It's not related with `c_glib/autogen.sh`.

```diff
diff --git a/dev/gen_apidocs/Dockerfile b/dev/gen_apidocs/Dockerfile
index bac8dc21..13a6ff4a 100644
--- a/dev/gen_apidocs/Dockerfile
+++ b/dev/gen_apidocs/Dockerfile
@@ -35,8 +35,7 @@ RUN apt-get update && \
         gobject-introspection \
         libgirepository1.0-dev \
         gtk-doc-tools \
-        autogen \
-        libgtk2.0-dev \
+        libtool \
         autoconf-archive \
         npm
 
```

**Comment by xhochy** [comment]
@kou Thanks! That worked, I have also updated the GLib docs now.

**Review by wesm — APPROVED** [review]
+1

**Pull request closed without merging**
