### PR TITLE
ARROW-13003: [C++] Fix key map unaligned access

### PR DESCRIPTION
**Pull request by cyb70289**

### CODE REVIEW

**Comment by cyb70289** [comment]
@github-actions crossbow submit test-ubuntu-18.04-r-sanitizer

**Comment by cyb70289** [comment]
https://issues.apache.org/jira/browse/ARROW-13003

**Comment by cyb70289** [comment]
Error logs without this PR:
https://dev.azure.com/ursacomputing/crossbow/_build/results?buildId=6217&view=logs&j=0da5d1d9-276d-5173-c4c4-9d4d4ed14fdb&t=d9b15392-e4ce-5e4c-0c8c-b69645229181&l=842

**Comment by pitrou** [comment]
Rebased.

**Comment by pitrou** [comment]
@ursabot please benchmark

**Pull request closed without merging**
