### PR TITLE
ARROW-510: Integration tests for all date and time combinations

### PR DESCRIPTION
**Pull request by wesm**
As soon as we have the Java support completed, I will rebase and then enable the date/time tests here to get a green build (or find other problems).

I fixed a couple C++ bugs to make integration testing against itself work.

### CODE REVIEW

**Comment by wesm** [comment]
cc @julienledem @BryanCutler @icexelloss

**Comment by icexelloss** [comment]
@wesm is there a Jira for implementing vector container for date and time?

**Comment by wesm** [comment]
See https://issues.apache.org/jira/browse/ARROW-510

ARROW-663 and ARROW-729

**Comment by wesm** [comment]
Closing since these commits were pulled into #475

**Pull request closed without merging**
