### PR TITLE
ARROW-4893: [C++] conda packages should use  inside of conda-build

### PR DESCRIPTION
**Pull request by xhochy**

### CODE REVIEW

**Comment by xhochy** [comment]
Crossbow: https://github.com/xhochy/crossbow/branches/all?utf8=%E2%9C%93&query=build-48

**Comment by wesm** [comment]
Since we aren't static linking a bunch of things now they'll have to be added to `run:` scope, at least: brotli, zstd, lz4-c, snappy, libprotobuf

**Comment by xhochy** [comment]
Actually that should not be needed. These packages should actually inject themselves into the `run` scope through `run_exports`. Seems like they don't have that defined. I'll add them here and fix the conda packages afterwards.

**Comment by xhochy** [comment]
Crossbow: https://github.com/xhochy/crossbow/branches/all?utf8=%E2%9C%93&query=build-50

**Comment by xhochy** [comment]
Jobs have all passed successfully.

**Review by wesm — APPROVED** [review]
+1, thank you!

**Pull request closed without merging**
