### PR TITLE
ARROW-16373: [Docs][CI] Small improvements to CI documentation

### PR DESCRIPTION
**Pull request by dragosmg**

### CODE REVIEW

**Review by jonkeane — COMMENTED** [review]
Should we also rename mentions of on-demand jobs in 

https://github.com/apache/arrow/blob/master/docs/source/developers/guide/step_by_step/pr_lifecycle.rst and https://github.com/apache/arrow/blob/master/docs/source/developers/guide/step_by_step/arrow_codebase.rst ? (Sorry, I would link the line numbers, but GH doesn't make that easy with the rst rendering!) I don't see any more references to `on-demand` though we do have a section in the R vignettes that should also be harmonized: https://github.com/apache/arrow/blob/3592f988b2aefab05357231378a539fc1766c4ec/r/vignettes/developers/workflow.Rmd#L187-L193

**Comment by dragosmg** [comment]
I also did a search for "on-demand" in docs and replaced with "extended" where appropriate.

**Comment by kou** [comment]
Could you open a new JIRA issue?
This is too large to say MINOR: https://github.com/apache/arrow/blob/master/CONTRIBUTING.md#Minor-Fixes

**Review by jonkeane — APPROVED** [review]
This looks good, thanks for the fixes!

**Pull request closed without merging**
