### PR TITLE
PARQUET-1845: [C++] Add expected results of Int96 in big-endian

### PR DESCRIPTION
**Pull request by kiszk**
This PR adds expected results of Int96 for parquet-internals-test in big-endian.

This PR assumes that uint_64 and uint_32 elements in Int96 are handled using a native endian for effectiveness.

### CODE REVIEW

**Comment by kiszk** [comment]
The failures may not be related to this PR.

**Comment by pitrou** [comment]
Hmm, I don't think that's right. `Int96` is the physical representation of 96-bit integers in Parquet files, and it's entirely little-endian. This means it should always have the same bit-representation, regardless of the platform's endianness.

I think there are several places that need to be fixed:
* the `Int96` tests in `parquet/arrow/arrow_reader_writer_test.cc`
* the various `ToImpalaTimestamp` conversion functions in `parquet/column_writer.h`
* the various `Int96` helper functions in `parquet/types.h`

(I may be missing one or more)

Note that `Int96` types are deprecated, so you may not want to lose your sweat over this.

**Comment by kiszk** [comment]
I understand your point. First, I implemented the approach ` entirely little-endian`.

Then, I reconsidered it. Each primitive type should be represented in a little-endian as shown [here](https://github.com/apache/parquet-format/blob/master/Encodings.md) in **Parquet serialized form (e.g. file)**.  For example, int32 is kept using a native endian in a memory or register. It will be converted from/to a little-endian when it will be serialized. I extended this to Int96. This is a background of the current decision.

Both approaches can work functionally correct. I understand that this is an implementation decision.

It is ok with your approach. At that time, I have one question. How will we handle other primitive types (e.g. int32 or double)? Do we keep other primitives in entirely little-endian on both platforms (little-endian and big-endian CPUs)?

**Comment by pitrou** [comment]
I think data should be kept in native endianness in memory (that is what the user would expect). What we must be careful is that Parquet data is encoded (and decoded) as little endian. Your PR doesn't address that, AFAICT.

**Comment by kiszk** [comment]
Thank you for your clarification. Based on this, `Int96` structure in memory can be represented in native endian. When it will be written into a file, we carefully have to keep it in a little-endian.

I just realized it that int32 in [int64, int32] is still a little-endian. After one or two hours, I will update this PR.

**Comment by kiszk** [comment]
At first, this PR address only test cases. This PR does not address the routines (like `column_writer.h`) yet. To update test cases can clarify the specification and implementation like this.

In this change, int96, which is a pair of uint64 and uint32, is stored in memory as follows:
```
For little-endian
Int96 Int96_min = {{1024, 2048, 4096}};
00 04 00 00 00 08 00 00 00 10 00 00
~~~~~~~~~~~~~~~~~~~~~~~ ~~~~~~~~~~~
uint64 (LE)             uint32 (LE)

For big-endian,
Int96 Int96_min = {{2048, 1024, 4096}};
00 00 08 00 00 00 04 00 00 00 10 00
~~~~~~~~~~~~~~~~~~~~~~~ ~~~~~~~~~~~
uint64 (BE)             uint32 (BE)
```

**Comment by pitrou** [comment]
Can you add the explanation you gave above (about the memory layout) somewhere in `parquet/types.h`? Thank you.

**Comment by kiszk** [comment]
Sure, at first, I derived this layout from [this method](https://github.com/apache/arrow/blob/master/cpp/src/parquet/types.h#L576). 

Other resources:
https://github.com/apache/arrow/issues/1920#issuecomment-541764279
https://stackoverflow.com/questions/53103762/cast-int96-timestamp-from-parquet-to-golang/53104516#53104516

**Comment by kiszk** [comment]
I have been thinking about place candidates of the interface between the native endian and a PARQUET little-endian. 

One of the good candidates is `Serialize()` in `parquet/column_writer.cc`.  Another candidate is `TypedBufferBuilder` in `arrow/buffer_builder.h`.

Regarding `Serialize()`, this is because there is [a conversion loop](https://github.com/apache/arrow/blob/master/cpp/src/parquet/column_writer.cc#L1781-1783) for Decimal128 that uses BigEndian. For big-endian, `Serialize()` of other primitive types including int96 needs to have such as conversion loop to little-endian. This is the first step.

While the above approach leads to additional overhead, it would be good to have new methods
`AppendLE` and `UnsafeAppendLE` in `TypedBufferBuilder` in addition to [`Append()` and `UnsafeAppend`](https://github.com/apache/arrow/blob/master/cpp/src/arrow/buffer_builder.h#L204-L240]. These new method ensures to write typed data in little-endian.

I think that we can support big-endian in Parquet using a two-step approach. What do you think?

**Comment by pitrou** [comment]
I've started a discussion on the [mailing-list](https://mail-archives.apache.org/mod_mbox/arrow-dev/) to make other people aware of your efforts.

I wonder if creating a `LETypedBufferBuilder` would make more sense than adding `AppendLE` methods (I don't think it makes sense to use two different endiannesses in a single buffer). It should probably be discussed on the ML.

As for `Serialize`, I can't really tell you. Parquet encoding routines seem a bit all over the place (most of it happens in `encoding.cc`). Perhaps other developers can chime in...

**Comment by kiszk** [comment]
Thank you for staring the discussion. I will watch at the thread.

Yeah, `LETypedBufferBuilder` makes sense. It looks better than adding `AppendLE`.

Regarding `Serialize`, it looks a good place where the class has both types of an element for Arrow and Parquet. But, encoding (i.e RLE and others) happens in `encoding.cc`. Let me check it tomorrow.

**Comment by kiszk** [comment]
I think that the current test cases for parquet writer do not have tests to verify the bit pattern of the generated parquet file. I will also create the test case in another PR since they are important on the different native endian platforms.

**Comment by pitrou** [comment]
@kiszk The preferred way to do that would be to add a file to the https://github.com/apache/parquet-testing repository. It's checked in as a submodule in `cpp/submodules` and used in the Parquet test suite.

**Comment by pitrou** [comment]
(also look for the "PARQUET_TEST_DATA" environment variable)

**Comment by kiszk** [comment]
Thank you for your suggestion. I think that these files are used only for read test now.

**Comment by pitrou** [comment]
Perhaps. If the reader is compatible with those files, and roundtripping works, then the writer is probably compliant as well.

**Comment by kiszk** [comment]
I agree with it. Once it is stable, it looks good. Under the development, developers want the reader and writer independently. At least, for me.

**Comment by kiszk** [comment]
After the 1-day investigation, I knew the implementation looks a little complicated.   
Regarding encoding, `TypedBufferBuilder` is used in some test cases, but it is not in some test cases. I am thinking about where we should make data little-endian.

**Comment by pitrou** [comment]
As a sidenote, I think you may want to start with Arrow unittests before trying to make Parquet unittests successful. Parquet relies on many Arrow facilities.

**Comment by kiszk** [comment]
@wesm do you have any comment on this change?

**Comment by wesm** [comment]
I haven't had a chance to look in detail. Perhaps someone on the Parquet mailing list might be able to help

**Comment by wesm** [comment]
I rebased, if the tests pass on s390x I'll merge this

**Pull request closed without merging**
