### PR TITLE
ARROW-3047: [C++/Python] Better build instructions with ORC

### PR DESCRIPTION
**Pull request by pitrou**
Also fix some markup and update a couple points.

### CODE REVIEW

**Review by wesm — APPROVED** [review]
+1. I think the nightly builds probably don't work anymore. We should fix that

**Comment by pitrou** [comment]
The latest nightly build seems fine:
https://travis-ci.org/apache/arrow/builds/415586849

**Comment by wesm** [comment]
@cpcloud set up nightlies using the scourge tool, posting to https://anaconda.org/twosigma/pyarrow. These have been failing for ~2 months

**Comment by cpcloud** [comment]
@wesm I'll decommission `scourge`. Can we upload the travis built nightlies to the apache channel?

**Comment by kszucs** [comment]
I have up to date nightlies running on my crossbow repo https://github.com/kszucs/crossbow/branches/all?utf8=%E2%9C%93&query=nightly

We should probably use another crossbow repo to build `"official"` nightlies.

**Comment by wesm** [comment]
No; ASF policy is not to endorse or promote nightly builds since users might confuse them for releases. 

The AMPLab Jenkins builds Spark nightly snapshots (https://amplab.cs.berkeley.edu/jenkins/job/spark-master-maven-snapshots/) -- I am not sure where they are uploaded, though

**Comment by wesm** [comment]
see http://www.apache.org/legal/release-policy.html#host-rc. We can list nightly build sources on the developer wiki

**Pull request closed without merging**
