### PR TITLE
ARROW-5663: [Packaging][RPM] Update CentOS packages for 0.14.0

### PR DESCRIPTION
**Pull request by kou**

### CODE REVIEW

**Comment by kou** [comment]
Don't merge this yet.
This needs #4623.

**Comment by wesm** [comment]
@kou are you sure we want to drop CentOS 6? Is it possible to update autoconf in the image where we build these packages?

**Comment by kou** [comment]
I think that we should avoid updating Autoconf because it's hard to maintain.

Here are our options to support CentOS 6:

1. Use release jemalloc tarball instead of snapshot tarball. Release tarball includes `configure`. So we don't need Autoconf.
2. Don't use jemalloc by `ARROW_JEMALLOC=OFF`.

This is a patch for 1:

```diff
diff --git a/cpp/cmake_modules/ThirdpartyToolchain.cmake b/cpp/cmake_modules/ThirdpartyToolchain.cmake
index fb2ba7b3..1d3895cb 100644
--- a/cpp/cmake_modules/ThirdpartyToolchain.cmake
+++ b/cpp/cmake_modules/ThirdpartyToolchain.cmake
@@ -320,7 +320,7 @@ if(DEFINED ENV{ARROW_JEMALLOC_URL})
   set(JEMALLOC_SOURCE_URL "$ENV{ARROW_JEMALLOC_URL}")
 else()
   set(JEMALLOC_SOURCE_URL
-      "https://github.com/jemalloc/jemalloc/archive/${JEMALLOC_VERSION}.tar.gz")
+      "https://github.com/jemalloc/jemalloc/releases/download/${JEMALLOC_VERSION}/jemalloc-${JEMALLOC_VERSION}.tar.bz2")
 endif()
 
 if(DEFINED ENV{ARROW_LZ4_URL})
@@ -1353,7 +1353,7 @@ if(ARROW_JEMALLOC)
     jemalloc_ep
     URL ${JEMALLOC_SOURCE_URL}
     PATCH_COMMAND touch doc/jemalloc.3 doc/jemalloc.html
-    CONFIGURE_COMMAND ./autogen.sh
+    CONFIGURE_COMMAND ./configure
                       "AR=${CMAKE_AR}"
                       "CC=${CMAKE_C_COMPILER}"
                       "--prefix=${JEMALLOC_PREFIX}"
```

I think that 1 is better than 2. Because we don't need Autoconf on other platforms such as macOS.

**Comment by wesm** [comment]
I agree with #1

**Comment by kou** [comment]
OK. I use 1 to keep CentOS 6 support.

**Comment by kou** [comment]
@ursabot crossbow package centos-6 centos-7

**Comment by kou** [comment]
@ursabot crossbow package centos-6 centos-7

**Comment by kou** [comment]
@ursabot crossbow package centos-6 centos-7

**Comment by kou** [comment]
@ursabot crossbow package centos-6 centos-7

**Comment by kou** [comment]
+1
CI is green.

**Pull request closed without merging**
