### PR TITLE
ARROW-8123: [Rust] [DataFusion] Add LogicalPlanBuilder

### PR DESCRIPTION
**Pull request by andygrove**
This PR introduces a LogicalPlanBuilder to make it easier to build logical plans. It also updates the SQL planner to use the LogicalPlanBuilder instead of constructing the logical plans directly, which simplifies the SQL planning logic.

Here is an example of the usage of the new builder.

```rust
        let plan = LogicalPlanBuilder::scan(
            "default",
            "employee.csv",
            &employee_schema(),
            Some(vec![0, 3]),
        )?
        .filter(col(1).eq(&lit_str("CO")))?
        .project(vec![col(0)])?
        .build()?;
```

### CODE REVIEW

**Comment by andygrove** [comment]
Note that the test failure is a genuine bug that was exposed by the changes in this PR. I am working on debugging this now.

**Comment by andygrove** [comment]
@kyle-mccarthy Please take a look as well. Thanks!

**Comment by andygrove** [comment]
@paddyhoran @nevi-me PTAL when you can.

**Comment by andygrove** [comment]
If there are no objections I'll merge this one soon. I don't think there is anything contentious in here and it fixes some bugs as well as simplifies the code.

**Review by paddyhoran — APPROVED** [review]
LGTM

**Pull request closed without merging**
