### PR TITLE
ARROW-3788: [Ruby] Add support for CSV parser written in C++

### PR DESCRIPTION
**Pull request by kou**
This is disabled by default because value conversion feature isn't enough for now.
We can enable it by specifying `:use_threads` option explicitly:

```ruby
Arrow::Table.load("xxx.csv", use_threads: true)
```

### CODE REVIEW

**Comment by kou** [comment]
@shiro615 Can you review this?

**Comment by wesm** [comment]
@kou could you clarify what you mean by "value conversion feature isn't enough for now"?

**Comment by kou** [comment]
For example, C++ CSV parser doesn't implement "true"/"false" to boolean conversion yet.

**Comment by kou** [comment]
Umm. `csv-converter-test.cc` has a test for "true"/"false" to boolean conversion.

**Comment by wesm** [comment]
Gotcha. Any problems you run into definitely report bugs =)

**Comment by kou** [comment]
Ah, `InferringColumnBuilder` doesn't support boolean yet.
I've opened a JIRA: https://issues.apache.org/jira/browse/ARROW-3791

**Review by shiro615 — APPROVED** [review]
LGTM

**Comment by kou** [comment]
I removed `use_threads` check and added explicit column type support.
I'll merge this.

**Pull request closed without merging**
