### PR TITLE
ARROW-12487: [C++][Dataset] Fix ScanBatches() hanging

### PR DESCRIPTION
**Pull request by lidavidm**
Errors weren't being handled in all paths.

### CODE REVIEW

**Comment by lidavidm** [comment]
If we need this for 4.0: https://github.com/lidavidm/arrow/tree/arrow-12487-4.0

**Review by westonpace — APPROVED** [review]
LGTM.  There is no notify on the exits in 193/198 but if I am reading this correctly that should be ok because you won't return false from the wait until you call resize (in which case you've passed lines 193/198).  It's good to have some tests for failed scans now too.  We should expand on those for 5.0

**Comment by kou** [comment]
Can we merge this?
Should we wait for a review by @bkietz ?

**Comment by lidavidm** [comment]
I think it's ok. Weston is also familiar with this code and I'm not sure if Ben would be able to get to it in time if you want to cut the release soon.

**Comment by kou** [comment]
Thanks.
But I don't have enough time to cut RC2 now. So it's not in a hurry now. Sorry.

Anyway, I'll merge this.

**Pull request closed without merging**
