### PR TITLE
ARROW-6302: [C++][Parquet][Python] Restore ordered type property when reading dictionary type with serialized Arrow schema

### PR DESCRIPTION
**Pull request by galuhsahid**
Closes 

* https://issues.apache.org/jira/browse/ARROW-6302
* https://issues.apache.org/jira/browse/ARROW-6345

### CODE REVIEW

**Comment by galuhsahid** [comment]
Hmm I have no clue why this fails on Python 2.7. @jorisvandenbossche would you mind to check this out? Thank you!

**Comment by wesm** [comment]
It may have to do with the pandas version -- 0.25.x is available for Python 3 but not 2.7 anymore. I can look at it, too

**Comment by wesm** [comment]
I ran into a related bug

https://issues.apache.org/jira/browse/ARROW-6345

I'm trying to find the root cause here

**Comment by wesm** [comment]
OK, ARROW-6345 is the root cause, fix incoming on this PR shortly

**Comment by wesm** [comment]
OK, fixed!

So the issue was binary vs. unicode. In Python 3 a cast from BinaryType to StringType (aka Unicode) was required while in Python 2 no type cast was required, but the type in the output Array needed to be replaced with the one with the `ordered` flag set, but because of ARROW-6345, the code did not detect that the type substitution was needed

**Review by wesm — APPROVED** [review]
+1

**Comment by wesm** [comment]
@galuhsahid thanks for the patch!

**Comment by galuhsahid** [comment]
@wesm Got it, so that's why it fails on Python 2. Thank you for the review & the fix!

**Pull request closed without merging**
