### PR TITLE
ARROW-5735: [C++] Pin boost-cpp=1.69.0 to fix MSVC builds

### PR DESCRIPTION
**Pull request by wesm**
See if this has anything to do with the failure we're seeing

### CODE REVIEW

**Comment by wesm** [comment]
This seems actually to be a Boost-related issue

```
-- Found Boost 1.70.0 at C:/Miniconda36-x64/envs/arrow/Library/lib/cmake/Boost-1.70.0
--   Requested configuration: QUIET COMPONENTS regex;system;filesystem
-- Found boost_headers 1.70.0 at C:/Miniconda36-x64/envs/arrow/Library/lib/cmake/boost_headers-1.70.0
-- Found boost_regex 1.70.0 at C:/Miniconda36-x64/envs/arrow/Library/lib/cmake/boost_regex-1.70.0
--   libboost_regex.lib
-- Adding boost_regex dependencies: headers
-- Found boost_system 1.70.0 at C:/Miniconda36-x64/envs/arrow/Library/lib/cmake/boost_system-1.70.0
--   libboost_system.lib
-- Adding boost_system dependencies: headers
-- Found boost_filesystem 1.70.0 at C:/Miniconda36-x64/envs/arrow/Library/lib/cmake/boost_filesystem-1.70.0
--   libboost_filesystem.lib
-- Adding boost_filesystem dependencies: headers
-- Boost 1.58 found.
-- Found Boost components:
   regex;system;filesystem
-- Boost include dir: 
-- Boost libraries: 
```

Here is from a passing Boost build:

```
-- Boost version: 1.69.0
-- Found the following Boost libraries:
--   regex
--   system
--   filesystem
-- Boost include dir: C:/Miniconda36-x64/envs/arrow/Library/include
-- Boost libraries: C:/Miniconda36-x64/envs/arrow/Library/lib/libboost_regex.libC:/Miniconda36-x64/envs/arrow/Library/lib/libboost_system.libC:/Miniconda36-x64/envs/arrow/Library/lib/libboost_filesystem.lib
```

It looks like Boost 1.70.0 is the culprit

https://ci.appveyor.com/project/wesm/arrow/builds/25537882/job/x8m8m38yy1qm4k2a?fullLog=true#L373

I'm going to try pinning to see if it fixes the build

**Comment by wesm** [comment]
Pinning Boost 1.69.0 seems to have done the trick, 1.70.0 must have been getting held back because of a constraint in the dependency graph until sometime today. We'll have to create a follow up issue to figure out why Boost 1.70.0 doesn't work properly with our Thirdparty build scripts

**Comment by wesm** [comment]
@ursabot crossbow package -g wheel

**Comment by wesm** [comment]
This caused a Boost warning -> build failure

```
FAILED: src/arrow/flight/CMakeFiles/arrow_flight_testing_static.dir/test-util.cc.obj 
C:\Miniconda36-x64\Scripts\clcache.exe  /nologo /TP -DARROW_FLIGHT_EXPORTING -DARROW_STATIC -DARROW_USE_SIMD -DARROW_WITH_BROTLI -DARROW_WITH_BZ2 -DARROW_WITH_LZ4 -DARROW_WITH_SNAPPY -DARROW_WITH_ZLIB -DARROW_WITH_ZSTD -DBOOST_ALL_NO_LIB -DGTEST_LINKED_AS_SHARED_LIBRARY=1 -DPROTOBUF_USE_DLLS -DURI_NO_UNICODE -DURI_STATIC_BUILD -D_CRT_SECURE_NO_WARNINGS -Isrc -I..\src -IC:\Miniconda36-x64\envs\arrow\Library\include -Iuriparser_ep-install\include -Igoogletest_ep-prefix\src\googletest_ep\include -I..\thirdparty\hadoop\include /DWIN32 /D_WINDOWS  /GR /EHsc   /EHsc /bigobj /W3 /wd4800 /wd4996 /WX /MP /MD /Od /UNDEBUG /showIncludes /Fosrc\arrow\flight\CMakeFiles\arrow_flight_testing_static.dir\test-util.cc.obj /Fdsrc\arrow\flight\CMakeFiles\arrow_flight_testing_static.dir\arrow_flight_testing_static.pdb /FS -c ..\src\arrow\flight\test-util.cc
C:\Miniconda36-x64\envs\arrow\Library\include\boost/process/detail/windows/wait_group.hpp(55): error C2220: warning treated as error - no 'object' file generated
C:\Miniconda36-x64\envs\arrow\Library\include\boost/process/detail/windows/wait_group.hpp(55): warning C4244: '-=': conversion from '__int64' to 'int', possible loss of data
[514/678] Building CXX object src\arrow\flight\CMakeFiles\arrow_flight_shared.dir\server_auth.cc.obj
[515/678] Building CXX object src\arrow\flight\CMakeFiles\arrow_flight_static.dir\protocol-internal.cc.obj
ninja: build stopped: subcommand failed.
(arrow) C:\projects\arrow\cpp\build>goto scriptexit 
```

My guess is this is legitimate https://ci.appveyor.com/project/ApacheSoftwareFoundation/arrow/builds/25544786/job/0cxpoyj723a06qb9

**Comment by pitrou** [comment]
Superseded by PR #4702

**Comment by wesm** [comment]
Thanks @pitrou

**Pull request closed without merging**
