### PR TITLE
ARROW-2269: [Python] Fixing paths for libs when building bdist

### PR DESCRIPTION
**Pull request by mitar**
Not sure why this is needed for me and why it was not discovered before. Let's see what CI says.

### CODE REVIEW

**Review by xhochy — CHANGES_REQUESTED** [review]
This needs to be an option to `setup.py` (and that was on my TODO but I forgot to make this one). We bundle a namespaced boost in our manylinux1 wheel builds and that is names as it is currently in the code. I can take care of fixing this.

**Comment by xhochy** [comment]
@mitar When you build these wheels in your setup, do you actually have the need to bundle Boost or would it be correctly installed on all target systems?

**Comment by mitar** [comment]
> When you build these wheels in your setup, do you actually have the need to bundle Boost or would it be correctly installed on all target systems?

I have no idea. I was just following [docs](https://github.com/apache/arrow/blob/master/python/doc/source/development.rst) and I wanted to build a wheel so that I can install it locally on my machine. Maybe I would not even have to first create a wheel to install it on my machine and I could just install it locally. But I went through wheel because this is what is shown in the documentation. I have not used any other flags. So I am not sure why I choose to bundle Boost vs. not bundle it.

**Comment by xhochy** [comment]
You should be able to install it with `python setup.py build_ext --build-type=release --with-parquet --with-plasma install` without the need of a wheel.

**Comment by mitar** [comment]
Seems obvious, but this should maybe be added to documentation?

**Comment by xhochy** [comment]
@mitar Definitively. We certainly lack a bit of documentation in general.

**Pull request closed without merging**
