### PR TITLE
ARROW-14647: [JS] fix bignumToNumber for negative numbers

### PR DESCRIPTION
**Pull request by bmatcuk**
`bignumToNumber` is giving incorrect results for negative numbers. For example, the following data exists in my dataset:

```javascript
// this represents the value -180846 but bignumToNumber() returns -18446744069414765000
const v = new Uint32Array([4294786450, 4294967295, 4294967295, 4294967295])
```

In this PR, I rewrote the function to handle negative numbers correctly. I've tested it locally. Not sure if there's a more efficient way to write the function. It basically checks the most significant bit to see if it's negative, and, if it is, applies the 2's compliment and multiplies by -1 at the end. I couldn't think of any safe way to avoid multiplying at the end since JS's Number type is not guaranteed to be able to handle the values BigNum can represent, so, there's going to (potentially) be some bits lost in the conversion. So, any bitwise method may result in losing more information than we'd like.

Thinking about it some more, I actually think the existing bignumToNumber will fail on anything with more than 64-bits - doesn't really have anything to do with the number being negative. The original function actually works on my example above if I only let it run on the first two 32-bits.

### CODE REVIEW

**Review by domoritz — APPROVED** [review]
Looks much simpler now. Can you add a test case?

**Comment by domoritz** [comment]
@bmatcuk could you add a unit test and confirm that this does not significantly affect performance?

**Comment by trxcllnt** [comment]
@domoritz shifting 64 vs. 32 bits will be slower, but seems like the price of correctness. I don't think we capture this in the current performance tests. Looking at the implementation, I'm not sure it could be much faster. Maybe swapping out the `for (word of words)` iterator for a numeric index counting loop, but seems minor. I vote we merge this as-is.

**Review by trxcllnt — APPROVED** [review]

**Comment by domoritz** [comment]
Okay. I'll merge it.

**Comment by domoritz** [comment]
Hmm, this doesn't look correct for decimals.

```
const num = [0xFFFFFFFE, 0xFFFFFFFF, 0xFFFFFFFF, 0xFFFFFFFF];  // -2
BN.decimal(new Uint32Array(num)).valueOf()
```

fails with `RangeError: Length out of range of buffer`

**Comment by trxcllnt** [comment]
Yeah I don't think we've ever had a conversion from the bytes to wide decimals. IIRC this was just for integers.

**Pull request closed without merging**
