### PR TITLE
ARROW-9582: [Rust] Add memory_size() method to Array [DRAFT]

### PR DESCRIPTION
**Pull request by andygrove**

### CODE REVIEW

**Comment by andygrove** [comment]
@nevi-me @paddyhoran @sunchao does this general approach seem ok to you?

**Comment by nevi-me** [comment]
> @nevi-me @paddyhoran @sunchao does this general approach seem ok to you?

Hi Andy, yes it does to me

**Comment by paddyhoran** [comment]
Looks fine to me.  Is it worth having `memory_used` (`len`) as well as `memory_size` (`capacity`)?

**Comment by sunchao** [comment]
Looks fine to me too. I also like `mem_used` or `memory_used` better but that is just a minor preference.

**Comment by andygrove** [comment]
@vertexclique Is working on a PR for this as well so I will likely close this one the new PR is up.

**Comment by andygrove** [comment]
Replaced by https://github.com/apache/arrow/pull/7874

**Pull request closed without merging**
