### PR TITLE
ARROW-11303: [Release][C++] Enable mimalloc in the windows verification script

### PR DESCRIPTION
**Pull request by kszucs**

### CODE REVIEW

**Comment by kszucs** [comment]
@github-actions crossbow submit -p release=3.0.0 -p rc=1 verify-rc-source-windows

**Comment by kszucs** [comment]
@github-actions crossbow submit -p release=3.0.0 -p rc=1 verify-rc-source-windows

**Comment by kszucs** [comment]
@github-actions crossbow submit -p release=3.0.0 -p rc=1 verify-rc-source-windows

**Comment by kszucs** [comment]
@github-actions crossbow submit -p release=3.0.0 -p rc=1 verify-rc-source-windows

**Comment by kszucs** [comment]
@github-actions crossbow submit -p release=3.0.0 -p rc=1 verify-rc-source-windows

**Review by kszucs — COMMENTED** [review]
+1

**Review by kou — APPROVED** [review]
+1

**Pull request closed without merging**
