### PR TITLE
ARROW-8789: [Rust] Add separate crate for integration test binaries

### PR DESCRIPTION
**Pull request by andygrove**
This PR simply adds a separate crate for integration test binaries with binaries that do nothing yet.

Since this crate is not one we ship, I think we can more freely accept PRs into this crate as we collaborate on the integration testing, and this will have lower overhead than maintaining a separate branch for integration testing, IMHO.

### CODE REVIEW

**Comment by paddyhoran** [comment]
> I think we can more freely accept PRs into this crate as we collaborate on the integration testing, and this will have lower overhead than maintaining a separate branch for integration testing, IMHO.

I agree.

**Review by paddyhoran — APPROVED** [review]
LGTM

**Comment by vertexclique** [comment]
Superb!

**Comment by andygrove** [comment]
I just need to fix the release scripts. I'll try and get that done later today.

**Review by nevi-me — APPROVED** [review]

**Review by sunchao — APPROVED** [review]
+1

**Pull request closed without merging**
