### PR TITLE
ARROW-2477: [Rust] Set up code coverage in CI

### PR DESCRIPTION
**Pull request by sunchao**
It may require some setup on the coveralls.io. I'm just giving it a blind try right now.

### CODE REVIEW

**Comment by xhochy** [comment]
Build is green but I'm unsure if this works, @sunchao please give a heads-up once this is ready.

**Comment by sunchao** [comment]
@xhochy : thanks, the build succeeded but coverage command failed with some strange error message. Will let you know once this succeeds.

**Comment by sunchao** [comment]
@xhochy : the latest commit successfully triggered `cargo coveralls` command but failed on cpp CI with error: `CondaHTTPError: HTTP 502 BAD GATEWAY for url <https://conda.anaconda.org/conda-forge/linux-64/lz4-c-1.8.1-0.tar.bz2>`, which I don't think is related to this PR.

Can you check if there's any code coverage info at `coveralls.io`? IMO this PR is good to merge now.

**Review by xhochy — APPROVED** [review]
+1, LGTM

There is some coverage reporting on https://coveralls.io/builds/16870264

**Pull request closed without merging**
