### PR TITLE
ARROW-4712: [C++][CI] fix build (sum.cc) has warnings in clang

### PR DESCRIPTION
**Pull request by emkornfield**

### CODE REVIEW

**Review by pitrou — APPROVED** [review]
+1

**Comment by pitrou** [comment]
AppVeyor build:
https://ci.appveyor.com/project/pitrou/arrow/builds/22715266

**Comment by wesm** [comment]
could these have been caught in CI?

**Comment by fsaintjacques** [comment]
It's weird because I build with clang-7, is it a different WARN_LEVEL?

**Comment by wesm** [comment]
I've found that the warnings can depend on which base gcc toolchain you have

**Comment by wesm** [comment]
Oh I think the issue is that the Mean patch introduced these issues but that was tested before the clang-7 fix yesterday https://github.com/apache/arrow/commit/e648a762586d1af3a294dd96054a78b90f6e71ec

**Pull request closed without merging**
