### PR TITLE
ARROW-11606: [Rust] [DataFusion] Add input schema to HashAggregateExec

### PR DESCRIPTION
**Pull request by andygrove**
To make it easier to implement serde for `HashAggregateExec` we need access to the schema that the aggregate expressions are compiled against. For `Partial` aggregates this is the same as the schema of the input. However, for `Final` aggregates it is not, which is why we need to add this additional schema information.

### CODE REVIEW

**Comment by andygrove** [comment]
@jorgecarleitao Does this make sense?

**Comment by jorgecarleitao** [comment]
Makes a lot of sense to me. 👍  Does it address the issue on Ballista?

**Comment by andygrove** [comment]
Yes, I think so. See https://github.com/ballista-compute/ballista/pull/505 ... I am going to finish testing this over the weekend.

**Review by jorgecarleitao — APPROVED** [review]
LGTM. Thanks @andygrove , and great work on Ballista so far . Putting DataFusion up to the test :)

**Review by alamb — APPROVED** [review]

**Comment by alamb** [comment]
FWIW @jorgecarleitao  and @andygrove  -- I have been using DataFusion quite heavily in IOx (e.g. https://github.com/influxdata/influxdb_iox/pull/795) and it is doing great. DataFusion is a really cool piece of software

**Comment by andygrove** [comment]
Thanks for the quick review and merge @jorgecarleitao and @alamb. I think distributed query execution will be working well enough in Ballista to support some TPC-H queries this weekend! The great news is that Ballista is now a tiny codebase. DataFusion is working out really well thanks to all the great work that went into 3.0.0 :heart:

**Pull request closed without merging**
