### PR TITLE
ARROW-17348: [C++] Add support for building bundled LZ4 with Visual C++ 2019 or later

### PR DESCRIPTION
**Pull request by kou**
LZ4 provides CMake configuration. We can add support for building
bundled LZ4 with Visual C++ 2019 or later by using it.

But this needs CMake 3.7 or later because
ExternaProject_Add(SOURCE_SUBDIR) is supported since CMake 3.7.

### CODE REVIEW

**Comment by kou** [comment]
@pykello You may want to test this on your environment.

**Comment by kou** [comment]
@github-actions crossbow submit -g nightly-tests -g nightly-packaging -g nightly-release

**Comment by pykello** [comment]
@kou this built successfully in my environment with LZ4 enabled & with both Relwithdebinfo & Debug configs. So this solves the problems I faced earlier. Thanks.

**Comment by kou** [comment]
@pykello Thanks for confirming this! I merge this.

**Pull request merged**
