### PR TITLE
WIP: [DOC] Test generating Java document

### PR DESCRIPTION
**Pull request by kiszk**

### CODE REVIEW

**Comment by kiszk** [comment]
@github-actions crossbow submit test-ubuntu-18.04-docs

**Comment by kiszk** [comment]
@github-actions crossbow submit test-ubuntu-18.04-docs

**Comment by kiszk** [comment]
@github-actions crossbow submit test-ubuntu-18.04-docs

**Comment by kiszk** [comment]
@github-actions crossbow submit test-ubuntu-18.04-docs

**Comment by emkornfield** [comment]
@kiszk any reason to keep this open?

**Comment by kiszk** [comment]
@emkornfield Thank you for pinging me. It should be closed.

**Pull request closed without merging**
