### PR TITLE
ARROW-5209: [Java] Provide initial performance benchmarks from SQL workloads

### PR DESCRIPTION
**Pull request by liyafan82**
In this PR, we provide the initial benchmark for running TPC-H SQL benchmark using Arrow.
The output looks like this:

Statistics for benchmark TPC-H Q1#Project & Filter:
Num of repeats = 10
Max duration = 0.64111ms
Min duration = 0.381478ms
Avg duration = 0.48580240000000013ms

If this is OK, we will provide more benchmarks in a similar manner.

### CODE REVIEW

**Comment by wesm** [comment]
question to @jacques-n and @siddharthteotia about what might be the best long-term strategy for benchmarking in Java. We would like to collect these benchmark results in a common benchmark database so we can monitor the performance of Java alongside other languages

cc @fsaintjacques

**Comment by fsaintjacques** [comment]
I'm not familiar with java benchmark frameworks. If it can support c++ benchmark output format (and go), there's not a lot of work involved to capture the results.

**Comment by jacques-n** [comment]
[JMH|https://openjdk.java.net/projects/code-tools/jmh/] is the goto for benchmarking in Java. We definitely don't want to right our own harness. Getting this right is its own science with the JIT. 

I don't really understand the example benchmarks in this commit. They seem somewhat arbitrary. We want to achieve maximum performance we interact directly with the memory using PlatformDependent (or similar).

**Comment by jacques-n** [comment]
One other comment, if people want to know more about the precariousness of Java microbenchmarks like this, they should spend some time on this blog: http://psy-lob-saw.blogspot.com/

**Comment by liyafan82** [comment]
> [JMH|https://openjdk.java.net/projects/code-tools/jmh/] is the goto for benchmarking in Java. We definitely don't want to right our own harness. Getting this right is its own science with the JIT.
> 
> I don't really understand the example benchmarks in this commit. They seem somewhat arbitrary. We want to achieve maximum performance we interact directly with the memory using PlatformDependent (or similar).

@jacques-n Thank you for your comments. JMH is reasonable benchmark framework.
The benchmarks are extracted from our SQL engine when processing an open SQL benchmark TPC-H. 
Our SQL engine is going to be made open source and merged into Apache Flink. Do you think it is reasonable?

**Comment by emkornfield** [comment]
@liyafan82 I think we added more targetted micro-benchmarks for the accessing for data.  Do you think this PR is still relevant?

**Comment by liyafan82** [comment]
> @liyafan82 I think we added more targetted micro-benchmarks for the accessing for data. Do you think this PR is still relevant?

Since there is no agreement such benchmarks should be added. Let's close this PR.

**Pull request closed without merging**
