### PR TITLE
ARROW-4578: [JS] Ensure Float16 is zero-copy, add more native BigInt support

### PR DESCRIPTION
**Pull request by trxcllnt**
This started as a continuation of https://github.com/apache/arrow/pull/3634, but grew enough to deserve its own PR. I've made a PR to my own fork that highlights just the changes here: https://github.com/trxcllnt/arrow/pull/8. I'll rebase this PR after https://github.com/apache/arrow/pull/3634 is merged so only these changes are included.

This PR reverts the behavior of `Float16Vector#toArray()` back to returning a zero-copy slice of the underlying `Uint16Array` data, and exposes the copying behavior via new `toFloat32Array()` and `toFloat64Array()` methods. `Float16Array.from()` will also convert any incoming 32 or 64-bit floats to Uint16s if necessary.

It also adds tighter integration with the new `BigInt`, `BigInt64Array`, and `BigUint64Array` primitives (if available):
1. Use the native `BigInt` to convert/stringify i64s/u64s
2. Support the `BigInt` type in element comparator and `indexOf()`
3. Add zero-copy `toBigInt64Array()` and `toBigUint64Array()` methods to `Int64Vector` and `Uint64Vector`, respectively

0.4.0 added support for basic conversion to the native `BigInt` when available, but would only create positive `BigInts`, and was slower than necessary. This PR uses the native Arrays to create the BigInts, so we should see some speed ups there. Ex:

```ts
const vec = Int64Vector.from(new Int32Array([-1, 2147483647]))
const big = vec.get(0)
assert(big[0] === -1) // true
assert(big[1] === 2147483647) // true
const num = 0n + big // or BigInt(big)
assert(num === (2n ** 63n - 1n)) // true
```

JIRAs associated with this PR are:
* [ARROW-4578](https://issues.apache.org/jira/browse/ARROW-4578) - Float16Vector toArray should be zero-copy
* [ARROW-4579](https://issues.apache.org/jira/browse/ARROW-4579) - Add more interop with BigInt/BigInt64Array/BigUint64Array
* [ARROW-4580](https://issues.apache.org/jira/browse/ARROW-4580) - Accept Iterables in IntVector/FloatVector from() signatures

### CODE REVIEW

**Comment by domoritz** [comment]
This is great. Native BigInt support will get better and better and so having good support for it in Arrow is great.

**Comment by TheNeuralBit** [comment]
:+1: I also appreciate you looking out for firefox users and handling the case where BigInt is not supported

Can you rebase now that #3634 is merged?

**Comment by trxcllnt** [comment]
@TheNeuralBit ok rebase is done. everything looks alright to me, let me know if you notice anything weird though.

**Review by TheNeuralBit — APPROVED** [review]
:+1: LGTM

**Pull request closed without merging**
