### PR TITLE
ARROW-13134: [C++][CI] Unpin conda package for aws-sdk-cpp

### PR DESCRIPTION
**Pull request by pitrou**

### CODE REVIEW

**Comment by pitrou** [comment]
@github-actions crossbow submit *conda*

**Review by xhochy — APPROVED** [review]
+1, if this really works. I would then afterwards update the global pin in conda-forge for the `aws-sdk-cpp`.

**Comment by xhochy** [comment]
> Note some builds still pick up an old version for some reason: https://github.com/ursacomputing/crossbow/runs/3883444274?check_suite_focus=true#step:7:642

No idea why this is happening. We could temporarily (or permantly) add a `>=1.9` to explicitly test the new SDK.

**Comment by pitrou** [comment]
@github-actions crossbow submit -g test-conda

**Pull request closed without merging**
