### PR TITLE
ARROW-3357: [Rust] Add a mutable buffer implementation

### PR DESCRIPTION
**Pull request by sunchao**
Currently we only have a immutable buffer implementation (`Buffer`). To implement various array builders, it's better to also have a mutable version of this so that we can keep appending data to a buffer. This PR adds a `MutableBuffer` struct which is growable and can be mutated. A mutable buffer can also be consumed and converted into a immutable buffer.

### CODE REVIEW

**Comment by paddyhoran** [comment]
+1, LGTM  I will re-base #2648 onto this once merged.

**Review by andygrove — APPROVED** [review]
LGTM

**Comment by kszucs** [comment]
Nightly rustfmt fails: https://travis-ci.org/apache/arrow/jobs/434918653#L860

**Comment by kszucs** [comment]
Thanks @sunchao !
Merging on green.

**Comment by sunchao** [comment]
Thanks @paddyhoran , @andygrove and @kszucs for the review! Fixed the lint issue (strange that it is not related to my change).

**Comment by kszucs** [comment]
That's because CI skips nightly [failures](https://github.com/apache/arrow/blob/master/.travis.yml#L228), it's just nicer without errors.

**Comment by sunchao** [comment]
Ah I see. Thanks for pointing out.

**Pull request closed without merging**
