### PR TITLE
ARROW-9158: [Rust][Datafusion] projection physical plan compilation should preserve nullability

### PR DESCRIPTION
**Pull request by houqp**

### CODE REVIEW

**Comment by houqp** [comment]
Since this PR added a test that creates mutable execution context, it needs to be rebased and updated after https://github.com/apache/arrow/pull/7464 get merged.

**Comment by houqp** [comment]
@paddyhoran rebased on top of latest master with merge of #7464, ready for review.

**Review by andygrove — APPROVED** [review]
LGTM

**Review by paddyhoran — APPROVED** [review]
LGTM, thanks @houqp

**Pull request closed without merging**
