### PR TITLE
ARROW-1689: [Python] Implement zero-copy conversions for DictionaryArray

### PR DESCRIPTION
**Pull request by Licht-T**
This PR closes [ARROW-1689](https://issues.apache.org/jira/browse/ARROW-1689).
I want to add the zero-copy option after https://github.com/apache/arrow/pull/1233 merged.

### CODE REVIEW

**Comment by njwhite** [comment]
Thanks - I wrote a test for this behaviour when working on my PR!

````
diff --git a/python/pyarrow/tests/test_convert_pandas.py b/python/pyarrow/tests/test_convert_pandas.py
index 8dd38582..21a5c82d 100644
--- a/python/pyarrow/tests/test_convert_pandas.py
+++ b/python/pyarrow/tests/test_convert_pandas.py
@@ -216,6 +216,19 @@ class TestPandasConversion(unittest.TestCase):
         result = pa.array([0, 1, 2]).to_pandas(zero_copy_only=True)
         npt.assert_array_equal(result, [0, 1, 2])
 
+    def test_zero_copy_dictionaries(self):
+        arr = pa.DictionaryArray.from_arrays(
+            np.array([0, 0]),
+            np.array(['A']))
+
+        result = arr.to_pandas(zero_copy_only=True)
+        values = pd.Categorical(['A', 'A'])
+
+        tm.assert_series_equal(
+            pd.Series(result),
+            pd.Series(values),
+           check_names=False)
+
     def test_zero_copy_failure_on_object_types(self):
         with self.assertRaises(pa.ArrowException):
             pa.array(['A', 'B', 'C']).to_pandas(zero_copy_only=True)
````

**Comment by Licht-T** [comment]
@njwhite Thank you very much!
@wesm Now reflected the master branch change into this PR!

**Comment by wesm** [comment]
Rebased and fixed flakes. The test case is failing, I will leave you to fix

**Comment by wesm** [comment]
Looking at this now to see if I can fix the test case

**Comment by wesm** [comment]
Had to resort to a little bit of dark magic (the PyCapsule API) to handle zero-copy dictionaries. When the dictionary values are not zero-copyable (the test case had strings, I changed this to be integers), this still raises

**Comment by wesm** [comment]
+1, will await builds

**Comment by Licht-T** [comment]
@wesm Wow! Thanks for your good idea! I didn't get such idea!

**Review by xhochy — APPROVED** [review]
+1, LGTM

**Pull request closed without merging**
