### PR TITLE
ARROW-6836: [Format] add a custom_metadata:[KeyValue] field to the Footer table in File.fbs

### PR DESCRIPTION
**Pull request by jgm-ktg**
This is ARROW-6836 ... a separate issue (ARROW-6837) pertains to accessing the new field.  Unsure whether these are separate issues and/or pull-requests.  In case they are separate, here is the format one.

### CODE REVIEW

**Comment by wesm** [comment]
I think it's OK for this to be separate as long as we follow up quickly with implementations in C++ and Java

**Comment by emkornfield** [comment]
Did we have a vote for this already? do we need one?

**Comment by emkornfield** [comment]
@wesm thoughts?

**Comment by wesm** [comment]
@emkornfield I am OK with merging this without a vote since it makes this table consistent with other metadata containers where we have `custom_metadata`. Sound good?

**Comment by emkornfield** [comment]
sounds good. merging.

**Comment by pitrou** [comment]
It seems the generated C++ code wasn't refreshed here.

**Comment by pitrou** [comment]
See https://github.com/apache/arrow/pull/6233 for the generated code update.

**Pull request closed without merging**
