### PR TITLE
ARROW-8519: [C++][Packaging] Reduce disk usage for external projects

### PR DESCRIPTION
**Pull request by kou**
This change removes built files after installing built files for
external projects. It reduces disk usage for external projects.

This may resolve "No space left on device" caused by building Linux
packages on GitHub Actions.

### CODE REVIEW

**Comment by kou** [comment]
@github-actions crossbow submit -g linux

**Comment by kou** [comment]
@github-actions crossbow submit -g linux

**Comment by kou** [comment]
@github-actions crossbow submit centos-*-amd64

**Comment by kou** [comment]
@github-actions crossbow submit -g linux

**Comment by kou** [comment]
@github-actions crossbow submit debian-buster-amd64 ubuntu-eoan-amd64 ubuntu-focal-amd64

**Comment by kou** [comment]
@github-actions crossbow submit debian-buster-amd64

**Comment by kou** [comment]
@github-actions crossbow submit debian-buster-amd64

**Comment by kou** [comment]
@github-actions crossbow submit -g linux -g linux-arm

**Comment by kszucs** [comment]
@kou we don't need to move to travis, I [managed to free up 23GB(https://github.com/apache/arrow/commit/b20f7091e63684804cb6ba76e4f72fcd38040cfd) of additional space on github actions, and we can free up more if required.

**Comment by kou** [comment]
Thanks!

**Pull request closed without merging**
