### PR TITLE
ARROW-4400: [CI] Switch to https repo for llvm

### PR DESCRIPTION
**Pull request by pravindra**

### CODE REVIEW

**Comment by pravindra** [comment]
> @pravindra I think the real issue why the messages mentioned in JIRA pop up is that the llvm apt now enforce `https`. You could try to install `apt-transport-https` and explicitly depend on a `https://apt.llvm.org/` instead of `http://llvm.org/apt/`

thanks, I'll try this out.

**Comment by pravindra** [comment]
@xhochy can you please merge my change ? The only pending issue is the rust formatting error, but since that's unrelated, I'll open a separate jira for that.

**Comment by pravindra** [comment]
opened ARROW-4403 for the rust failure.

**Review by kszucs — APPROVED** [review]
LGTM Thanks @pravindra!

**Pull request closed without merging**
