### PR TITLE
ARROW-10573: [C++] Align written buffers to specified value

### PR DESCRIPTION
**Pull request by njwhite**
IPC messages are forced to 8-byte alignment and ignore the `alignment` `IpcWriteOptions` setting. This inhibits zero-copy optimisations as non-8-byte-sized types can't be stored in contiguous memory.

### CODE REVIEW

**Comment by wesm** [comment]
Hm. Unaligned buffers are not compliant with the Arrow specification. This optimization is only useful in the extraordinarily narrow use case where all of the columns in the DataFrame are the same data type. Could you give a little more color on what problem you are solving?

**Comment by emkornfield** [comment]
[ML Discussion](https://lists.apache.org/thread.html/rca411c6a753cec1a960f9ed3a474ea3cbf196633f951b353d580aed9%40%3Cdev.arrow.apache.org%3E).  As I said there, I don't think this is a good approach either since it doesn't conform to the specification.

**Comment by njwhite** [comment]
@wesm I disagree with your assertion that it's only useful in an extraordinarily narrow use case - I've added a test case `test_contiguous_buffers_mixed_types` to show a zero-copy load of mixed-datatype DataFrame. The columns do have to be sorted by dtype for now (`df[df.dtypes.sort_values().index]`) if you want to eliminate consolidation, but `pyarrow` could easily do this under the hood. 

w.r.t. the spec, I see in _Implementations are **recommended** to allocate memory on aligned addresses_ [here](https://arrow.apache.org/docs/format/Columnar.html); my PR doesn't change the default behaviour of following the recommendation and 8-byte aligning the buffers. A user would have to opt in to creating unaligned files if they wanted the benefit of reading their DataFrames without copying the data.

My use case is to expose Arrow files saved on disk (and probably still resident in the OS' page cache) as Pandas Dataframes with as low a latency as possible. Copying the entire DataFrame from one place in memory to another (to strip out the padding) adds latency and memory pressure, far outweighing the performance benefit of 8-byte aligned reads.

**Comment by wesm** [comment]
From the specification

> Implementations are recommended to allocate memory on aligned addresses (multiple of 8- or 64-bytes) and pad (overallocate) to a length that is a multiple of 8 or 64 bytes. **When serializing Arrow data for interprocess communication, these alignment and padding requirements are enforced.**

So I guess it's a question whether we want to allow the creation of non-conforming IPC messages

**Comment by emkornfield** [comment]
I'm -1 on allowing non-conforming IPC implementations.

**Comment by njwhite** [comment]
@emkornfield @wesm thanks for the comments. What’s the process for updating the spec? As allowing unaligned buffers in IPC streams is backwards (but not forwards) compatible it’d be great to get it into v1.1!

**Comment by emkornfield** [comment]
> @emkornfield @wesm thanks for the comments. What’s the process for updating the spec? As allowing unaligned buffers in IPC streams is backwards (but not forwards) compatible it’d be great to get it into v1.1!

You can start a discussion thread on dev@ mailing list.  I'm not in favor of making this change to the specification, others might feel differently.

**Comment by njwhite** [comment]
@emkornfield thanks, I will. Can I ask why you don’t want unaligned buffers allowable in the spec? 

I’m not sure I understand the philosophy here though; Arrow has a lot of Python code to provide Pandas compatibility but if you always have to copy IPC data to use it from Pandas then your not getting any advantage from using Arrow as the underlying data format?

**Comment by emkornfield** [comment]
> I’m not sure I understand the philosophy here though; Arrow has a lot of Python code to provide Pandas compatibility but if you always have to copy IPC data to use it from Pandas then you’re not getting any advantage from using Arrow as the underlying data format?

My thinking here is Arrow isn't just about the python implementation.  There are all sorts of tweaks that might make one language/library pair more performant, but changing the spec and ensuring all the other implementations can handle it is is a bunch of work, and over time degrades compatibility between implementation (we are already behind on some other features that are already in the spec).  So in these cases, I tend to be conservative with changing the specification.

**Comment by pitrou** [comment]
It looks like there is consensus that the proposed changes are not desirable, so I'm going to close this PR. Sorry @njwhite , and thank you for contributing this!

**Pull request closed without merging**
