### PR TITLE
ARROW-617: [Format] Add additional Time metadata and comments based on discussion in ARROW-617

### PR DESCRIPTION
**Pull request by wesm**

### CODE REVIEW

**Review by xhochy — APPROVED** [review]
Fine with me!

**Comment by julienledem** [comment]
LGTM.
@jacques-n @StevenMPhillips ?

**Comment by BryanCutler** [comment]
LGTM

**Review by julienledem — COMMENTED** [review]
This looks good to me.
@jacques-n ?

**Comment by jacques-n** [comment]
lgtm too +1

Are there additional adjustments we need to make in the Java pojo classes to correctly reflect this change? Is there a follow-on jira for those?

**Comment by wesm** [comment]
Not yet. I just created ARROW-663. ARROW-582 will cover the JSON read/write support for integration testing. thanks all!

**Pull request closed without merging**
