### PR TITLE
ARROW-6457: [C++] Always set CMAKE_BUILD_TYPE if it is not defined

### PR DESCRIPTION
**Pull request by wesm**
This may be a dup of another issue, but I encountered this locally and this produces default RELEASE build type with both Ninja and MSVC build generator for me

### CODE REVIEW

**Comment by kou** [comment]
This is duplicated by #5247 .
This is a workaround. We can merge this for now. But we need to work on real fix. I'll work on real fix in #5247 but it takes some times.

**Comment by wesm** [comment]
Agreed. Thank you

**Comment by wesm** [comment]
Build seems OK here

https://ci.appveyor.com/project/wesm/arrow/builds/27192445

Merging this

**Comment by wesm** [comment]
Travis CI: https://travis-ci.org/wesm/arrow/builds/580986667

**Pull request closed without merging**
