### PR TITLE
PARQUET-1523: [C++] Vectorize comparator interface

### PR DESCRIPTION
**Pull request by majetideepak**

### CODE REVIEW

**Comment by wesm** [comment]
This isn't what I was thinking when I wrote PARQUET-1523. I thought the proposal was to remove the scalar virtual calls altogether -- this still has virtual calls on the hot path AFAICT. I would be willing to help with refactoring this further

**Comment by majetideepak** [comment]
Ok. I will make another pass.

**Comment by wesm** [comment]
@majetideepak do you have some time to look at this? I can also take a pass on it possibly end of this week or next week

**Comment by majetideepak** [comment]
@wesm I got side-tracked on fixing the build scripts for Vertica's build environment. I will likely finish that this week. I can only work on this next week. Feel free to take a pass on this if you get time before that.

**Comment by majetideepak** [comment]
@wesm I will work on this today and get back to you.

**Comment by wesm** [comment]
Thanks. I'll take a look at the build system improvements

**Comment by majetideepak** [comment]
@wesm I spent some more time with this but couldn't figure out a solution without virtual functions.
The challenge is that the comparator class depends on both the `Physical Type` and the `SortOrder (SIGNED, UNSIGNED)`. The `TypedRowGroupStatistics` class that requires this comparator is only templated on the `Physical Type`. How can we resolve this at compile-time?

**Comment by wesm** [comment]
Let me have a look at this with fresh eyes and see what I can come up with.

**Comment by wesm** [comment]
Making some progress on this. I will try to get a patch up by mid-week if not sooner

**Pull request closed without merging**
