### PR TITLE
ARROW-5045: [Rust] Code coverage silently failing in CI

### PR DESCRIPTION
**Pull request by sunchao**

### CODE REVIEW

**Review by fsaintjacques — APPROVED** [review]
LGTM, the OSX and appveyor failures are not related to this change.

**Comment by sunchao** [comment]
@fsaintjacques actually the PR was not ready to be merged yet, I was exploring cargo-tarpaulin but it was still failing with the following error (code coverage failure will not prevent CI from succeeding):

```
...FFFFFFFFFFFFF.plan: TableScan: people projection=Some([0, 1, 4])
.[ERROR tarpaulin] Failed to get test coverage! Error: Failed to run tests: A segfault occurred while executing tests
```

**Comment by fsaintjacques** [comment]
I did look at the output but didn't see any immediate errors (https://travis-ci.org/apache/arrow/jobs/550633131#L1761). Weird that travis hides the error in this case. To avoid this confusion in the future, might I suggest to either add the WIP keyword in the PR name or not publish it at all (you can activate travis on your fork before opening the PR).

**Comment by sunchao** [comment]
Yes that's correct. You'll have to expand the step to see the error :)

Good suggestion on the WIP. Let me do it next time. I'll file another JIRA and PR later.

**Pull request closed without merging**
