### PR TITLE
ARROW-5212: [Go] Support reserve for the data buffer in the BinaryBuilder

### PR DESCRIPTION
**Pull request by jsternberg**

### CODE REVIEW

**Review by stuartcarnie — APPROVED** [review]
Looks good to me – this is an important performance improvement when building arrays.

@wesm can you approve?

**Comment by jsternberg** [comment]
Oh, I need to update the commit message. I wrote it with both reserve and resize but ended up only keeping reserve.

**Review by sbinet — APPROVED** [review]
LGTM.

**Comment by sbinet** [comment]
(I'll wait a bit to give a chance to @alexandreyc to comment.)

**Comment by stuartcarnie** [comment]
thanks @sbinet – I thought I tagged you too 👍

**Comment by sbinet** [comment]
ah. @jsternberg could you add a test for this API?

thanks.

**Review by sbinet — CHANGES_REQUESTED** [review]
(please add a test for this new API, thanks.)

**Comment by jsternberg** [comment]
I updated the code with a test. The test calls `ReserveData` and then appends data to it and ensures the capacity doesn't change after the call to `ReserveData`.

**Review by sbinet — APPROVED** [review]

**Comment by sbinet** [comment]
thanks!

**Pull request closed without merging**
