### PR TITLE
ARROW-2503: [Python] Prevent trailing space character for string statistics

### PR DESCRIPTION
**Pull request by jneuff**
The trailing space is added in `parquet-cpp.` `pyarrow` calls the function `FormatStatValue` which adds the trailing space (https://github.com/apache/parquet-cpp/blob/master/src/parquet/types.cc#L52).

https://issues.apache.org/jira/browse/PARQUET-1283 is about fixing this behavior. Once the corresponding PR is merged into `parquet-cpp` and `pyarrow` is synced, the `test_parquet.py:test_parquet_column_statistics_api` will break for `str`. This PR fixes that breakage.

### CODE REVIEW

**Comment by xhochy** [comment]
I guess this depends on the PR in `parquet-cpp` as the statistics tests are failing?

**Comment by jneuff** [comment]
Sorry, I was a bit to eager to open this PR. I want to solve it without depending on the [PR](https://github.com/apache/parquet-cpp/pull/461) in `parquet-cpp`.

I'll reiterate.

**Comment by jneuff** [comment]
I updated the scope of this PR, see the description above.

**Comment by pitrou** [comment]
@jneuff, could you rebase this PR so that we get a fresh CI build?

**Comment by pitrou** [comment]
I opened a competing PR #1973 to get CI as soon as possible. Let's see which one ends first.

**Comment by xhochy** [comment]
@pitrou you should also have the right to push to contributor branches on github, no need to open new PRs if it's only a rebase.

**Comment by pitrou** [comment]
In the past I've messed up things while trying to push to contributor branches :-)

**Comment by pitrou** [comment]
Also the goal is to get an AppVeyor build on my account.

**Pull request closed without merging**
