### PR TITLE
ARROW-2731 Add external Orc capability

### PR DESCRIPTION
**Pull request by msarahan**
* [Michael Sarahan] ARROW-2731 add external ORC capability
* [Michael Sarahan] ARROW-2731 add orc/Exceptions.hh to adapter.cc

### CODE REVIEW

**Comment by wesm** [comment]
Rebased

**Comment by wesm** [comment]
@msarahan this is failing our linter, could you have a look?

**Comment by msarahan** [comment]
Looking into it.  Hopefully sorted now.  We'll see.  I think it was just that some of the CMakeLists.txt stuff was a bit out of order.

**Review by xhochy — APPROVED** [review]
+1, LGTM

**Pull request closed without merging**
