### PR TITLE
GH-23221: [C++] webassembly / pyodide / emscripten build support

### LINKED ISSUE #23221: [C++] Add/document configuration to build with WebAssembly
Not something I plan to work on, but given that https://github.com/finos/perspective created a custom wasm build of Arrow, it would seem a good idea to have a standard way for wasm projects to use the Arrow C++ library

**Reporter**: [Wes McKinney](https://issues.apache.org/jira/browse/ARROW-6894) / @wesm

<sub>**Note**: *This issue was originally created as [ARROW-6894](https://issues.apache.org/jira/browse/ARROW-6894). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

### PR DESCRIPTION
**Pull request by joemarshall**
This PR adds a cmake build preset for emscripten / pyodide, and updates the setup for pyarrow so that it is possible to build a webassembly version of libarrow, and a version of pyarrow which works on pyodide.

Things that changed:
1) Cmake preset ninja-release-emscripten-python
2) Platform/toolchain override for cmake on emscripten, to set various build parameters
3) Some fixes to cmake files - e.g. pyarrow can build with static libarrow now, and third party dependencies pass the toolchain file through.
4) pyarrow knows about ARROW_ENABLE_THREADING and doesn't use threads if they are not enabled in libarrow.
5) pyarrow sets defaults for inclusion of submodules based on their inclusion in the arrow build. e.g. pyarrow.parquet is built only if ARROW_PARQUET is set. This makes it possible to build in situations where you don't have access to set the build environment variables (e.g. in cross compiling situations like pyodide). It also seems to me to make sense - I can't see why you'd want to build pyarrow without parquet if you've built arrow with it, and the inverse is obviously not possible.

* Closes: #23221

### CODE REVIEW

**Comment by joemarshall** [comment]
Also fixes #34996 once this is in the pyodide package tree.

**Comment by joemarshall** [comment]
@kou I'm not sure who is the right person to review this - it's a smidgen of python / python packaging changes and cmake changes.

**Comment by kou** [comment]
Can we split this pull request to the C++ part and then the Python part for easy to review?

**Comment by joemarshall** [comment]
@kou - I've split out the cmake changes into #37821. Once they're in, I can update this one to be just the pyodide build side of things - I think the python build depends on them, so it isn't worth reviewing the python changes until 37821 is in?

**Comment by joemarshall** [comment]
Closing this as all changes are in the other PRs

**Pull request closed without merging**
