### PR TITLE
ARROW-14252 [R] Partial matching of arguments warning

### PR DESCRIPTION
**Pull request by dragosmg**

### CODE REVIEW

**Comment by nealrichardson** [comment]
Isn't there an option about warning about partial matching? Can/should we turn this on in our CI somewhere (like around [here](https://github.com/apache/arrow/blob/master/ci/scripts/r_test.sh#L45))?

**Comment by dragosmg** [comment]
We could set the option similar to the {lintr} CI [here](https://github.com/jimhester/lintr/blob/7100188e10a6f60bb652b613885abd795fe366eb/.github/workflows/lint-changed-files.yaml#L42).

**Comment by nealrichardson** [comment]
Could we add it to the .Rprofile we use in most of our CI jobs? https://github.com/apache/arrow/blob/master/ci/etc/rprofile#L44

@jonkeane ?

**Comment by nealrichardson** [comment]
Feel free to add those and let's see what happens

**Review by nealrichardson — APPROVED** [review]
Thanks! CI failures seem unrelated

**Pull request closed without merging**
