### PR TITLE
ARROW-3926: [Python] Add Gandiva bindings to Python manylinux1 wheels

### PR DESCRIPTION
**Pull request by xhochy**

### CODE REVIEW

**Comment by xhochy** [comment]
This currently only works for Python 3.5+ as using `__file__` in extension modules is not working consistently in Python 2.7. We need to find an alternative for that.

**Comment by kszucs** [comment]
@xhochy I ment running `import pyarrow.gandiva` in the manylinux crossbow tasks, to ensure gandiva is available during the packaging, see https://github.com/apache/arrow/blob/master/dev/tasks/python-wheels/linux-test.sh#L30

**Comment by kszucs** [comment]
All of the python packages are tested during the packaging builds, it's better to test twice.

**Comment by xhochy** [comment]
@pitrou do you have an idea for a Python 2.7 alternative for:

```
# python -c 'import pyarrow.gandiva'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "pyarrow/gandiva.pyx", line 85, in init pyarrow.gandiva
    _dll = ctypes.CDLL(__file__, ctypes.RTLD_GLOBAL)
NameError: name '__file__' is not defined
```

**Review by kszucs — COMMENTED** [review]
Forgot to +1

**Pull request closed without merging**
