### PR TITLE
ARROW-11983: [Python] Avoid ImportError calling from_pandas in threaded code

### PR DESCRIPTION
**Pull request by jorisvandenbossche**

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
@pitrou do you think it is worth it trying to construct a test for this?

**Comment by pitrou** [comment]
Does this actually fix the issue (were you able to reproduce)?

**Comment by jorisvandenbossche** [comment]
Good question .. I could reproduce it, and at the time I also checked that adding `import concurrent.futures.thread` to the script fixed the issue. But so the change in this PR itself actually doesn't fix it. I still need to add a top-level `import concurrent.futures.thread` or `from concurrent.futures import ThreadPoolExecutor` as well. Just the `from concurrent import futures` is not enough to fix it.

**Comment by pitrou** [comment]
That's what I thought :-)

**Comment by jorisvandenbossche** [comment]
Yeah, I should have checked again ;)

**Review by pitrou — APPROVED** [review]
+1

**Pull request closed without merging**
