### PR TITLE
ARROW-662: [Format] Move Schema flatbuffers into their own file that can be included

### PR DESCRIPTION
**Pull request by wesm**
@julienledem for some reason the Java build is failing for me locally (also on master):

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.2:testCompile (default-testCompile) on project arrow-vector: Compilation failure: Compilation failure:
[ERROR] /home/wesm/code/arrow/java/vector/src/test/java/org/apache/arrow/vector/types/pojo/TestSchema.java:[38] error: a type with the same simple name is already defined by the single-type-import of List
[ERROR] /home/wesm/code/arrow/java/vector/src/test/java/org/apache/arrow/vector/types/pojo/TestSchema.java:[64,19] error: List is abstract; cannot be instantiated
[ERROR] /home/wesm/code/arrow/java/vector/src/test/java/org/apache/arrow/vector/types/pojo/TestSchema.java:[81,19] error: List is abstract; cannot be instantiated
[ERROR] -> [Help 1]
```

### CODE REVIEW

**Comment by julienledem** [comment]
Possibly the same problem as Struct_ ? conflicting imports on the java side with java.util.List?
I will fetch your branch and take a look

**Comment by julienledem** [comment]
I get the same issue on my other PR. So this might not be related to your change:
https://travis-ci.org/apache/arrow/jobs/214111095
(a change in the FB compiler maybe?)

**Comment by julienledem** [comment]
It's probably a bad merge from two colliding PRs.
TestSchema imports both java.util.List and org.apache.arrow.vector.types.pojo.ArrowType.List
master is broken right now. I'm submitting a fix.

**Comment by julienledem** [comment]
See: https://github.com/apache/arrow/pull/430

**Comment by wesm** [comment]
Looks like the build has passed otherwise: https://travis-ci.org/apache/arrow/builds/214247299

**Review by xhochy — APPROVED** [review]
+1. LGTM

**Pull request closed without merging**
