### PR TITLE
GH-43703: [C++][Parquet][CI] Parquet: Introducing more bad_data for testing

### PR DESCRIPTION
**Pull request by mapleFU**
### Rationale for this change

Introducing more bad_data for testing

### What changes are included in this PR?

* Upgrade parquet-testing
* Introduce more bad_data
* Update fuzz generation

### Are these changes tested?

They're tests :-)

### Are there any user-facing changes?

no

* GitHub Issue: #43703

### CODE REVIEW

**Comment by pitrou** [comment]
Looks like there's a build failure on MSVC:
https://github.com/apache/arrow/actions/runs/10402488116/job/28807063898?pr=43708#step:9:1528

**Comment by mapleFU** [comment]
Fixed now

**Comment by pitrou** [comment]
@github-actions crossbow submit -g cpp

**Review by pitrou — APPROVED** [review]
+1, thank you @mapleFU

**Pull request merged**
