### PR TITLE
ARROW-4684: [Python] Debug Cython test failure

### PR DESCRIPTION
**Pull request by pitrou**

### CODE REVIEW

**Review by bkietz — APPROVED** [review]

**Comment by mrkn** [comment]
The reason why the test failed is `-fno-plt` option is not supported by gcc version 5.
Upgrading gcc can resolve this issue.

**Comment by wesm** [comment]
I wonder why `-fno-plt` is getting introduced suddenly. We can resolve the issue by using the `gcc_linux-64` and `gxx_linux-64` compiler toolchain packages. But then we aren't using gcc 5.4

**Comment by pitrou** [comment]
@msarahan

**Comment by msarahan** [comment]
@pitrou is there a reason why you pinged me here?  I don't see the ping anymore - just in my email.  Is there a reason why you're sticking with gcc 5.4?  That seems like a strange middle-ground between manylinux standard practice and completely modern.  Is there something about newer gcc that doesn't work as well for you?

**Comment by xhochy** [comment]
@pitrou I'm fixing this in my CMake refactor. There I plan to have a pure toolchain build and a pure Ubuntu (read: no conda) build.

**Comment by pitrou** [comment]
@msarahan That was about the `-fno-plt` issue but then I got an answer from the `conda-forge` gitter channel.

@xhochy Nice but I'd rather silence the errors in the meantime. CI failures are a nuisance.

**Comment by pitrou** [comment]
Hmm, silencing the `test_cython` error wasn't enough. Then it fails installing `pickle5`:
https://travis-ci.org/apache/arrow/jobs/499285776#L4033

In any case, it seems it's going to be fixed in conda-forge:
https://gitter.im/conda-forge/conda-forge.github.io?at=5c769889608c6f373631487f

> Jonathan J. Helmus
@jjhelmus
15:02
@pitrou The Python packages in defaults uses generic flags unless an environment variable is set by the compiler activation script. I'll look at porting that patch over to conda-forge.

**Comment by fsaintjacques** [comment]
@pitrou then I'd mark the build in the matrix as possible failure?

**Comment by pitrou** [comment]
@fsaintjacques Right.

**Comment by pitrou** [comment]
The underlying issue was solved in https://github.com/conda-forge/python-feedstock/pull/249, closing.

**Pull request closed without merging**
