### PR TITLE
ARROW-17517: [C++] Remove internal headers from substrait API

### PR DESCRIPTION
**Pull request by westonpace**

### CODE REVIEW

**Comment by westonpace** [comment]
I figured I should tackle this to brush up on the rules for includes myself to try and help keep things clean going forwards.  While I was at it I also did a bit of general header cleanup.  The only structural changes were moving MapNode into its own file (I think @save-buffer has a PR to remove this at some point anyways so it seemed easier to do this than try and hide it's impl in some way) and converting IdStorage to a virtual class to hide its implementation (depended on internal hashing stuff).

Attaching a snippet showing the compile tree from compiling `engine_substrait_consumption.cc` (which uses the engine API).
[deps.txt](https://github.com/apache/arrow/files/9570898/deps.txt)

**Comment by westonpace** [comment]
> It seems that you refer wrong Jira issue.

Oops, thanks :)

**Comment by westonpace** [comment]
I'm a little stumped by this Windows error.  MapNode is an abstract base class.  It is used by project_node.cc, filter_node.cc (both in arrow compute) and also by file_base.cc (in datasets).  In order for it to be seen by datasets I have to mark it as ARROW_EXPORT.  However, when I do so, I get duplicate symbols when linking arrow compute (presumably because project_node and filter_node each have implementations?)  If I remove ARROW_EXPORT then datasets fails to link because it can't find the symbols.

**Comment by pitrou** [comment]
The weird thing is that it works fine on AppVeyor.

**Comment by pitrou** [comment]
You probably need to rebase on master now and fix conflicts (switch to `std::optional`).

**Comment by westonpace** [comment]
> The weird thing is that it works fine on AppVeyor. Might be an issue with ccache...

@pitrou 

Looks like the rebase magically solved the Windows problem so maybe it was ccache then.  I think the remaining CI failures are unrelated.

**Comment by pitrou** [comment]
Rebased and fixed a small error compiling the Flight examples.

**Review by pitrou — APPROVED** [review]

**Comment by pitrou** [comment]
Hmm, the macOS build failures look unexpected but also unrelated to this.

**Comment by pitrou** [comment]
Thanks @westonpace ! I'm keeping the JIRA open for the small followup PR.

**Pull request merged**
