### PR TITLE
MINOR: [R] Remove duplicated heading

### PR DESCRIPTION
**Pull request by thisisnic**

### CODE REVIEW

**Comment by eitsupi** [comment]
It looks like you have not updated the Rd file.

**Comment by eitsupi** [comment]
@thisisnic Do you plan to modify the Rd file?

**Comment by thisisnic** [comment]
@thisisnic It's pretty low down my to-do list right now, but feel free to submit a PR if it's troubling you.

**Comment by eitsupi** [comment]
#13878

**Pull request closed without merging**
