### PR TITLE
GH-41375: [C#] Move to .NET 8.0

### LINKED ISSUE #41375: [C#] Move to net8.0 for running tests in workflows
### Describe the enhancement requested

Workflows currently target .NET 7.0, which will reach end of support on May 14, 2024 (three weeks from time of issue creation. .NET 8.0 is a "long term support" version -- apparently three years is "long term" -- so we should move to that.

### Component(s)

C#

### PR DESCRIPTION
**Pull request by CurtHagenlocher**
### What changes are included in this PR?

Changes to workflow infrastructure and projects to install and target net8.0 instead of net7.0.

### Are these changes tested?

Yes

### Are there any user-facing changes?

Users will need to install .NET 8 to run tests and examples. No impact on product code.

Closes #41375
* GitHub Issue: #41375

### CODE REVIEW

**Comment by CurtHagenlocher** [comment]
I *think* all the failing checks are due to the recent macos-latest change, but am not confident that it's the case.

**Comment by raulcd** [comment]
@github-actions crossbow submit nuget

**Comment by raulcd** [comment]
@github-actions crossbow submit *csharp*

**Comment by raulcd** [comment]
Change looks good to me. There is a single error on CI around the .NET jobs but I think is unrelated:
https://github.com/apache/arrow/actions/runs/8836761043/job/24264073837?pr=41376

```
Run ci/scripts/csharp_test.sh $(pwd)
+ source_dir=/Users/runner/work/arrow/arrow/csharp
+ '[' -z '' ']'
+ type python3
+ export PYTHON=python3
+ PYTHON=python3
+ python3 -m pip install pyarrow find-libpython
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try brew install
    xyz, where xyz is the package you are trying to
    install.
    
    If you wish to install a Python library that isn't in Homebrew,
    use a virtual environment:
    
    python3 -m venv path/to/venv
    source path/to/venv/bin/activate
    python3 -m pip install xyz
    
    If you wish to install a Python application that isn't in Homebrew,
    it may be easiest to use 'pipx install xyz', which will manage a
    virtual environment for you. You can install pipx with
    
    brew install pipx
    
    You may restore the old behavior of pip by passing
    the '--break-system-packages' flag to pip, or by adding
    'break-system-packages = true' to your pip.conf file. The latter
    will permanently disable this error.
    
    If you disable this error, we STRONGLY recommend that you additionally
    pass the '--user' flag to pip, or set 'user = true' in your pip.conf
    file. Failure to do this can result in a broken Homebrew installation.
    
    Read more about this behavior here: <https://peps.python.org/pep-0668/>

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.
```
@kou @assignUser is this something you've seen somewhere else?
I am happy to merge this PR as it seems related to the macOS changes for GitHub runners.

**Comment by kou** [comment]
We need to use venv as the message said or actions/setup-python.

**Comment by raulcd** [comment]
I've opened https://github.com/apache/arrow/issues/41390 to follow the error

**Review by raulcd — APPROVED** [review]

**Comment by assignUser** [comment]
Yeah, this is a recent change in the brew python. As kou said using venv solves it.

**Pull request merged**
