### PR TITLE
ARROW-5653: [C++] Ensure testing libraries are not installed

### PR DESCRIPTION
**Pull request by fsaintjacques**
libarrow_testing and libarrow_flight_testing should not be installed.
Also fix the unit tests with LD_LIBRARY_PATH due to install target and
cmake handling of RPATH.

### CODE REVIEW

**Comment by wesm** [comment]
@ursabot crossbow test docker

**Comment by wesm** [comment]
Looks like macOS is setting the install rpath in the executables

```
 2/65 Test  #2: plasma-client_tests ................***Failed    0.52 sec
Running plasma-client_tests, redirecting output into /Users/travis/build/apache/arrow/cpp-build/build/test-logs/plasma-client_tests.txt (attempt 1/1)
dyld: Library not loaded: /Users/travis/build/apache/arrow/cpp-install/lib/libarrow_testing.14.dylib
  Referenced from: /Users/travis/build/apache/arrow/cpp-build/debug/plasma-client_tests
  Reason: image not found
/Users/travis/build/apache/arrow/cpp/build-support/run-test.sh: line 97: 11021 Abort trap: 6           $TEST_EXECUTABLE "$@" 2>&1
     11022 Done                    | $ROOT/build-support/asan_symbolize.py
     11024 Done                    | ${CXXFILT:-c++filt}
     11026 Done                    | $ROOT/build-support/stacktrace_addr2line.pl $TEST_EXECUTABLE
     11028 Done                    | $pipe_cmd 2>&1
     11030 Done                    | tee $LOGFILE
~/build/apache/arrow/cpp-build/src/plasma
```

**Comment by fsaintjacques** [comment]
I'll close this in favor of https://github.com/apache/arrow/pull/4605

**Comment by StefanBruens** [comment]
Why was this closed? `libarrow_testing.{so,a}` is still installed, dito the header files.

**Comment by wesm** [comment]
Can you please open a Jira issue? To make sure this is fixed

**Pull request closed without merging**
