### PR TITLE
ARROW-9317: [Java] add few testcases for arrow-memory

### PR DESCRIPTION
**Pull request by dota17**

### CODE REVIEW

**Comment by emkornfield** [comment]
@dota17 thank you for the PR.  It looks like this is out of data after some refactoring.

**Comment by wesm** [comment]
@rymurr I assume this needs to be rebased / refactored?

**Comment by dota17** [comment]
@wesm Hi Wes, it has been refactored and the has been rebased.

**Review by rymurr — APPROVED** [review]
LGTM. Thanks @dota17

**Pull request closed without merging**
