### PR TITLE
ARROW-1456: [Python] Run s3fs unit tests in Travis CI

### PR DESCRIPTION
**Pull request by rok**
This is to enable Python S3 tests in CI with minio as requested in [ARROW-1456](https://issues.apache.org/jira/browse/ARROW-1456) and [ARROW-4208](https://issues.apache.org/jira/browse/ARROW-4208).

### CODE REVIEW

**Comment by kszucs** [comment]
@ursabot build

**Comment by rok** [comment]
@ursabot build

**Comment by rok** [comment]
@kszucs, I'd like to add [minio](https://github.com/apache/arrow/blob/f7f2805e2cdb593223d542ac228b3fd624acaffe/ci/docker_install_conda.sh#L44) binary and python `s3fs` package to the docker image. This would be to enable S3 CI tests. Do I need to do something besides this PR?

**Comment by rok** [comment]
[ARROW-6655](https://github.com/apache/arrow/pull/5423) seems to do this and more. @kszucs shall I close this PR once ARROW-6655 is merged?

**Comment by kszucs** [comment]
@rok yes, we should close it in favor of ARROW-6655. 

It introduces Minio for the filesystem bindings, and I've also updated the s3fs accordingly.

**Pull request closed without merging**
