### PR TITLE
ARROW-3944: [Python] Build manylinux1 docker image directly in the CI

### PR DESCRIPTION
**Pull request by xhochy**

### CODE REVIEW

**Comment by wesm** [comment]
Travis CI is too slow to build the whole toolchain in under 50 minutes

**Comment by kszucs** [comment]
@xhochy We could pull it first before rebuilding it, but its base image `quay.io/pypa/manylinux1_x86_64:latest` doesn't have any tags besides latest, so it can still trigger whole rebuilds.

**Comment by xhochy** [comment]
I tend to decline this PR as `not possible`. In the case where the user would adjust the base `yum` call, we would also fail to build the image.

**Comment by wesm** [comment]
Agreed

**Pull request closed without merging**
