### PR TITLE
ARROW-2225: [JS] support tables split across buffers

### PR DESCRIPTION
**Pull request by trxcllnt**
@TheNeuralBit somewhere along the way we lost this. Resolves https://issues.apache.org/jira/browse/ARROW-2225

### CODE REVIEW

**Comment by wesm** [comment]
Any way to test this?

**Comment by TheNeuralBit** [comment]
@wesm I'm working on testing it right now, I can merge when I'm done

**Comment by TheNeuralBit** [comment]
LGTM - Tested locally with an Arrow stream I manually split into a "Schema" and a "Batches" buffer.

We should definitely add a test for this, but I'm not sure how to do it right now.. any objections to waiting until we have a JS IPC writer?

**Comment by trxcllnt** [comment]
@TheNeuralBit yeah, that's what I was thinking too. I think we can sit tight since that's now back in progress.

**Comment by TheNeuralBit** [comment]
Created [ARROW-2235](https://issues.apache.org/jira/browse/ARROW-2235) to track test creation

**Pull request closed without merging**
