### PR TITLE
ARROW-697: JAVA Throw exception for record batches > 2GB

### PR DESCRIPTION
**Pull request by holdenk**
Add a test to verify that we throw a clear error message for record batches over 2GB. This entry point is easist to test without adding some magic bytes to the tests suite since its explicit on the input, and the other public entry points for deserialization have the same checks (just extracted from the metadata).

### CODE REVIEW

**Comment by holdenk** [comment]
I'm still new to the deserializer though so if I've missed something let me know.

**Comment by wesm** [comment]
The original problem in ARROW-697 is slightly different. Between 0.2 and 0.3, we changed the record batch lengths to be 64-bits instead of 32:

https://github.com/apache/arrow/blob/master/format/Message.fbs#L50

You can see the length being casted to int in my patch here:

https://github.com/apache/arrow/commit/ced9d766d70e84c4d0542c6f5d9bd57faf10781d#diff-5b26e7b5a174693cfda85a27e0ade86bR219

If `recordBatchFB.length()` exceeds INT32_MAX, an exception should be thrown there. If we are dealing with Boolean or Null type data, the size of the record batch payload may be less than 2GB. Separately raising on large message bodies like you've done here is a good idea, too (since we will be unable to compute an ArrowBuf slice exceeding 2GB).

**Comment by holdenk** [comment]
Ah, that makes sense. From looking through the Message.fbs it seemed like the recordBatchFB.length would have to be less than the message bodyLength size, but the Null type data makes sense. I'll update this PR to add those checks :)

**Review by wesm — APPROVED** [review]
+1, thanks @holdenk!

**Comment by wesm** [comment]
can you change the PR title to start with ARROW-697 -- the brackets are fouling up our PR merge tool. Thanks

**Comment by holdenk** [comment]
Done, thanks :)

**Pull request closed without merging**
