### PR TITLE
GH-39363: [C++] Use Cast() instead of CastTo() for Parquet 

### LINKED ISSUE #39363: [C++][Parquet] Use Cast() instead of CastTo() for Parquet
### Describe the enhancement requested

This is a sub-issue of the issue mentioned below.

* #35560 

As we can see in the parent issue, we can find tables organizing the related functions.

| file name         | code snippet                                                                               |
|-------------------|--------------------------------------------------------------------------------------------|
| file_parquet.cc   | `auto maybe_min = min->CastTo(field.type());`                                              |
| file_parquet.cc   | `auto maybe_max = max->CastTo(field.type());`                                              |

We need to use `Cast()` instead of `CastTo()` to remove legacy code.

### Component(s)

Parquet

### PR DESCRIPTION
**Pull request by llama90**
### Rationale for this change

Remove legacy code

### What changes are included in this PR?

Replace the legacy scalar CastTo implementation for Parquet.

### Are these changes tested?

Yes. It is passed by existing all test cases for Parquet.

### Are there any user-facing changes?

Maybe, Yes. 

There is a dependency on the Parquet schema that the user handles. There may be a problem if the user has to deal with a type for which Casting is not implemented. However, in this case, it should be treated as a new issue with an implementation that improves the `Cast` compute kernel.

* Closes: #39363

### CODE REVIEW

**Review by mapleFU — APPROVED** [review]

**Comment by mapleFU** [comment]
Thanks! Will rerun failed CI and merge it tommorow

**Comment by llama90** [comment]
@mapleFU I would like to kindly bring to your attention that the test (`C++ / AMD64 Windows MinGW MINGW32 C++ (pull_request)`) may not succeed until the following issue is resolved:

* https://github.com/apache/arrow/issues/39359

**Comment by mapleFU** [comment]
Oh, got it, let me merge it

**Comment by mapleFU** [comment]
Thanks @llama90 !

**Pull request merged**
