### PR TITLE
ARROW-14421: [C++] Implement Flight SQL

### PR DESCRIPTION
**Pull request by lidavidm**
Implement Flight SQL in C++ and Java, and add the protocol definitions.

This is a combination of multiple pull requests, merged into one branch before merging into master.

Closes #10906 (ARROW-12922).
Closes #11507 (ARROW-14421).
Closes #11989 (ARROW-15112).
Closes #12021 (ARROW-15187).
Closes #12035 (ARROW-15198).

### CODE REVIEW

**Comment by lidavidm** [comment]
This will need some wrangling when merged to ensure all the authors are preserved properly.

**Comment by rafael-telles** [comment]
Thanks @lidavidm ! :)

**Comment by lidavidm** [comment]
I'm asking around about the dev pipeline failures just to make sure of what's going on before proceeding.

**Comment by lidavidm** [comment]
FYI, this is the list of authors I plan to credit when merging, pulled out of Git (since the commits will be squashed):

```
Rafael Telles
Abner Eduardo Ferreira
Kyle Porter
Jose Almeida
Juscelino Junior
Ryan Nicholson
tifflhl
Vinicius Fraga
```

Please let me know if there's anyone else that should be credited or if I should update or correct any names. Thanks! (We need `Name <email>`, same format as Git)

**Comment by rafael-telles** [comment]
Thanks @lidavidm !
Please include James Duong <duong.james@gmail.com> (@jduo) in this list :)

**Comment by lidavidm** [comment]
Kicked the docs build (though it looks unrelated to what's happening here).

**Comment by lidavidm** [comment]
@crossbow submit -g nightly

**Comment by lidavidm** [comment]
@github-actions crossbow submit -g nightly

**Comment by lidavidm** [comment]
Ok! A few last things.

https://github.com/ursacomputing/crossbow/runs/4612261742?check_suite_focus=true
https://github.com/ursacomputing/crossbow/runs/4612255093?check_suite_focus=true

There's a failure with the unity build enabled. Looks like we have to explicitly state `arrow::Result` (since there's also `flight::Result`).

The rest of these I need to dig into more:

https://github.com/ursacomputing/crossbow/runs/4612239300?check_suite_focus=true
https://github.com/ursacomputing/crossbow/runs/4612279369?check_suite_focus=true

> Error:  Failed to execute goal pl.project13.maven:git-commit-id-plugin:2.2.2:revision (for-jars) on project arrow-java-root: Could not complete Mojo execution... Unable to find commits until some tag: Walk failure. Missing commit 16a9df1193bd3ed2b3b93dca7cc3302d2e9e8f31 -> [Help 1]

Not sure what Maven is going on about here. The commit is part of this branch... I need to look more into this.

https://dev.azure.com/ursacomputing/crossbow/_build/results?buildId=17746&view=logs&j=4c86bc1b-1091-5192-4404-c74dfaad23e7&t=d8957ec8-c17a-5786-57ed-2bf0e44aedfc
I would like to confirm that the version conflict is not solely due to sqlite here.

There's also some failures due to ARROW-15181. I'll try to get a patch up soon, since it seems the flight-sql tests are more prone to this.

**Comment by rafael-telles** [comment]
Thanks @lidavidm ! Looks like there is only one place we didn't explicitly use `arrow::Result`, this patch should fix it:

```diff
diff --git a/cpp/src/arrow/flight/sql/example/sqlite_statement_batch_reader.cc b/cpp/src/arrow/flight/sql/example/sqlite_statement_batch_reader.cc
index a5824ae255..08a03c4ca6 100644
--- a/cpp/src/arrow/flight/sql/example/sqlite_statement_batch_reader.cc
+++ b/cpp/src/arrow/flight/sql/example/sqlite_statement_batch_reader.cc
@@ -93,8 +93,8 @@ SqliteStatementBatchReader::SqliteStatementBatchReader(
       rc_(SQLITE_OK),
       already_executed_(false) {}
 
-Result<std::shared_ptr<SqliteStatementBatchReader>> SqliteStatementBatchReader::Create(
-    const std::shared_ptr<SqliteStatement>& statement_) {
+arrow::Result<std::shared_ptr<SqliteStatementBatchReader>>
+SqliteStatementBatchReader::Create(const std::shared_ptr<SqliteStatement>& statement_) {
   ARROW_RETURN_NOT_OK(statement_->Step());
 
   ARROW_ASSIGN_OR_RAISE(auto schema, statement_->GetSchema());
```

Do you prefer I open another PR for this?

**Comment by lidavidm** [comment]
Yeah, do you mind opening a quick PR?

**Comment by rafael-telles** [comment]
Sure! Just opened #12035

**Comment by lidavidm** [comment]
@github-actions crossbow submit -g nightly

**Comment by rafael-telles** [comment]
Took a look on these failures but they all seem unrelated to Flight SQL, beside the ARROW-15181 one.
Please let me know if there is anything else and I will try to solve as soon as possible.

**Comment by lidavidm** [comment]
Agreed, that's what I'm seeing as well. The PR for ARROW-15181 is up at #12037. I'll merge this now, thanks to everyone for all their work here!

**Comment by rafael-telles** [comment]
Thank you so much @lidavidm ! That's a very good way of ending 2021 for us :)
Happy holidays! :partying_face:

**Pull request closed without merging**
