### PR TITLE
ARROW-15941: [C++] Allow overriding the number of IO threads with an environment variable

### PR DESCRIPTION
**Pull request by pitrou**

### CODE REVIEW

**Comment by corleyma** [comment]
Slightly tangential to this PR, but does reading parquet (in particular, from remote sources like S3)  still use the cpu thread pool, or will pyarrow users reading remote parquet potentially benefit from this newly-added ability to tune the size of the IO threadpool?

**Comment by westonpace** [comment]
@corleyma That's the goal.  Although I think at the moment we sometimes incorrectly perform the read on the CPU thread pool (ARROW-14974).  We default to 8 threads which is generally pretty good for S3 but in some cases where we are reading a lot of files or files with many row groups from a remote data source, there has been a benefit from using more threads.

**Comment by corleyma** [comment]
@westonpace Thanks for the prompt response and further edification.  Whenever the usage of IO threadpool is more consistent (I guess when ARROW-14974 is resolved), it might be good to update the pyarrow documentation somewhere to nudge users toward this possibility... maybe somewhere in [this section](https://arrow.apache.org/docs/python/dataset.html#reading-from-cloud-storage)?  Alternatively, adding a dedicated section for some high level discussion of Arrow's threading model as it pertains to pyarrow users could also be helpful.

**Review by edponce — APPROVED** [review]

**Comment by edponce** [comment]
@pitrou There seems to be a ThreadPoolTest failing in CI (AMD64 Win C++17) but not sure if it is related to this PR. Everything else LGTM.

**Review by westonpace — APPROVED** [review]
Looks good.  It's a little odd that ARROW_IO_THREADS has no ARROW_CPU_THREADS counterpart.  I'll tackle ARROW-14702 later today and I can reference the two variables there as well when introducing the concepts of I/O and CPU thread pool.

**Comment by pitrou** [comment]
There is no ARROW_CPU_THREADS because you can use OMP_NUM_THREADS for that.

**Comment by westonpace** [comment]
Yes, sorry I wasn't clear (and more rambling than actually suggesting a change).  We do have environment variables for both of them but the names are very different.  Also, I understand the reasoning behind the OMP_NUM_THREADS name as it has some tradition in the domain.

**Comment by pitrou** [comment]
Right, the point is that if OMP_NUM_THREADS is already configured on a system of sorts, it automatically gets picked up by Arrow.

**Pull request closed without merging**
