### PR TITLE
ARROW-5206: [Java] Add APIs in MessageSerializer to directly serialize/deserialize ArrowBuf

### PR DESCRIPTION
**Pull request by tianchen92**
This PR is related to [ARROW-5206](https://issues.apache.org/jira/browse/ARROW-5206), add APIs in MessageSerializer to directly serialize/deserialize ArrowBuf.

### CODE REVIEW

**Comment by fsaintjacques** [comment]
A small note, the title should be `ARROW-5206: [Java] Add APIs in MessageSerializer...`

**Comment by wesm** [comment]
Changed the title to be more conforming to standard

**Comment by tianchen92** [comment]
@fsaintjacques @wesm Thanks for your reminder.

**Comment by tianchen92** [comment]
@wesm could you please help review this PR? thanks very much

**Comment by wesm** [comment]
@tianchen92 I'm not comfortable giving +1 to non-trivial Java PRs. Could @BryanCutler, @siddharthteotia, or @jacques-n take a look?

**Comment by tianchen92** [comment]
Thanks very much for your reply @wesm, I am not sure, do you mean to say that these APIs are not necessary or shouldn't added in MessageSerializer? I think provide methods to directly serialize ArrowBuf or even ValueVector may be helpful for users in some cases.
I would appreciate it if you could give me some comments, thanks very much! @BryanCutler @siddharthteotia @jacques-n

**Comment by wesm** [comment]
@tianchen92 I don't do Java. Someone else will have to review

**Comment by BryanCutler** [comment]
@tianchen92 , I'm not quite sure these APIs add much value because an `ArrowBuf` can be written directly with the `WriteChannel` (you can take a slice before to only write a chunk), or read directly with a `ReadChannel`.

**Comment by tianchen92** [comment]
@BryanCutler Thanks a lot for your comments, I think you are right, we can read/write ArrowBuf through WriteChannel.write(ByteBuffer buffer).
Ask an unrelated question, is there any way to directly serialize/deserialize ValueVector? If not, can we add these APIs? as I described in ARROW-5224. Thanks!

**Comment by BryanCutler** [comment]
@tianchen92 the usual way to serialize a ValueVector is by adding the Field to a `VectorSchemaRoot` and serializing it to a RecordBatch. This produces a standard IPC message that can be exchanged with other Arrow implementations. It is possible to just serialize a single vector, but it would probably have to be deserialized in Java as well, and I don't know if this adds much value. If you have a use case for this though, please go ahead and make another jira.

**Comment by tianchen92** [comment]
@BryanCutler Sure, thanks for your feedback, I will close this PR.

**Pull request closed without merging**
