### PR TITLE
ARROW-2423: [Python] Enable DataType, Field and plasma ObjectID equality checks against no…

### PR DESCRIPTION
**Pull request by kszucs**
…n pyarrow objects

Bumped cython version makes it possible https://github.com/apache/arrow/pull/1863

### CODE REVIEW

**Review by pitrou — APPROVED** [review]
LGTM, thank you.

**Comment by pitrou** [comment]
@kszucs, what is your JIRA username so that I can assign the issue to you?

**Comment by kszucs** [comment]
kszucs

**Comment by pitrou** [comment]
Unfortunately, it seems you can't be assigned issues to. @xhochy

**Comment by kszucs** [comment]
JIRA is my worst nightmare :)

**Comment by pitrou** [comment]
I think many people would agree with that!

**Comment by xhochy** [comment]
@kszucs Assigned the issue to you. You now also have the karma to do this on your in future.

**Pull request closed without merging**
