### PR TITLE
ARROW-10634: [C#][CI] Change the build version from 2.2 to 3.1 in CI

### PR DESCRIPTION
**Pull request by Ulimo**
Upgraded build version to 3.1 and C# version to 8.
Also added EmbedUntrackedSources so auto generated code will work with sourcelink.

This change is a requirement for #8694 and is isolating some of the changes that it required regarding upgrading net core version.

### CODE REVIEW

**Comment by Ulimo** [comment]
I did not change the version under examples, should FluentBuilderExample.csproj also be updated to 3.1?

**Comment by Ulimo** [comment]
@eerhardt sorry for pinging, notifying atleast that I added this PR, I understand that you are probably super busy, so mostly wondering when/if this can be reviewed? Or is there someone else in the csharp community for arrow that can review?

**Review by eerhardt — APPROVED** [review]
This looks good.

Sorry for the delay - and thanks for the ping. I hadn't seen the PR until then.

**Comment by eerhardt** [comment]
> should FluentBuilderExample.csproj also be updated to 3.1?

No, it doesn't build as part of CI. Let's just leave it for now. Maybe in the future we could add it as a unit test so it is protected against getting broken.

**Pull request closed without merging**
