### PR TITLE
ARROW-6312: [C++] Declare other required Libs.private to aid in static linking

### PR DESCRIPTION
**Pull request by michaelmaguire**
https://issues.apache.org/jira/browse/ARROW-6312

These are the Libs.private I needed in order to get my in-house *static* build working

### CODE REVIEW

**Comment by kou** [comment]
Could you open an issue on JIRA https://issues.apache.org/jira/projects/ARROW/issues and prepend "ARROW-${JIRA_ISSUE_ID}: [C++] " to the subject of this pull request?

https://arrow.apache.org/docs/developers/contributing.html#how-to-contribute-patches

And could you also provide information how to reproduce your problem?

This patch isn't acceptable because some people build Apache Arrow C++ without Snappy, zlib and so on.

**Comment by michaelmaguire** [comment]
> Could you open an issue on JIRA https://issues.apache.org/jira/projects/ARROW/issues and prepend "ARROW-${JIRA_ISSUE_ID}: [C++] " to the subject of this pull request?

Done!

**Comment by emkornfield** [comment]
@michaelmaguire thanks for creating the JIRA and updating the title, it doesn't look like you addressed @kou concerns about dynamically generating the dependencies.

**Comment by michaelmaguire** [comment]
> @michaelmaguire thanks for creating the JIRA and updating the title, it doesn't look like you addressed @kou concerns about dynamically generating the dependencies.

That is correct.  My proposed PR was considered unsuitable.  I'm happy to have raised awareness of the issue, I'm sorry I don't have time to address the problem in a way deemed suitable.

**Pull request closed without merging**
