### PR TITLE
ARROW-9520: [Rust] [DataFusion] Add support for aliased aggregate exprs

### PR DESCRIPTION
**Pull request by returnString**
First attempt at contributing to Arrow/DataFusion, just fixing this small issue around aliased aggregate columns. Please let me know if this isn't an ideal implementation!

### CODE REVIEW

**Review by alamb — APPROVED** [review]
Looks good to me. FYI @jorgecarleitao  / @andygrove

**Review by jorgecarleitao — APPROVED** [review]
Thanks a lot for your first contribution to DataFusion!

This is great: really neat and clean solution to this, @returnString !

LGTM

**Comment by jorgecarleitao** [comment]
Can you run locally `cargo fmt`, so that we fix all linting issues shown in the CI pipeline?

**Comment by andygrove** [comment]
Thanks @returnString this looks great but you'll need to run `cargo +stable fmt --all` to fix the linter check in CI before we can merge.

**Comment by returnString** [comment]
That's interesting, I've got rustfmt set to run on save whilst editing in vscode but I _was_ having some issues with code completion in the project too; I'll try and figure out what's up with that for any future contributions.

Are squash merges accepted for this project or would you prefer that I rebase the PR down to a single commit?

**Comment by alamb** [comment]
> Are squash merges accepted for this project or would you prefer that I rebase the PR down to a single commit?

There is some sort of automation script that merges arrow PRs -- I don't think there is any need to rebase to a single commit

**Review by andygrove — APPROVED** [review]
LGTM. Thanks @returnString

**Pull request closed without merging**
