### PR TITLE
ARROW-4474: Use signed integers in FlightInfo payload size fields

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Review by wesm — COMMENTED** [review]
I'm +1 on the change. The C++ bindings will have to be updated because they use `uint64_t`. @jacques-n will this pose any issue for Java?

**Comment by jacques-n** [comment]
I'm +1 as well. Java actually supports signed better.

**Comment by lihalite** [comment]
Alright, I've changed what I believe are all the relevant occurrences of `uint64_t` in the C++ API.

**Comment by pitrou** [comment]
Rebased. It seems Java doesn't need any changes (the relevant fields are already `long` in the code).

**Review by pitrou — APPROVED** [review]
+1

**Comment by pitrou** [comment]
Hmm I'm not sure what happened to the CI here. I'm sure the Travis build was green... Will re-trigger.

**Comment by pitrou** [comment]
The manylinux job now routinely times out after 50 minutes... @kszucs

**Comment by kszucs** [comment]
I suggest to test only python 2.7 and 3.6, I'll set that in #3484

**Comment by kszucs** [comment]
+1 merging

**Pull request closed without merging**
