### PR TITLE
ARROW-4981: [Ruby] Add support for CSV data encoding conversion

### PR DESCRIPTION
**Pull request by kou**

### CODE REVIEW

**Comment by fsaintjacques** [comment]
Failure seems legitimate.

**Comment by kou** [comment]
Ah, we need #3997 for this.

**Comment by kou** [comment]
I'll rebase on master when #3997 is merged.

**Comment by shiro615** [comment]
#3997 is merged. I've rebased on master.

**Review by shiro615 — APPROVED** [review]
LGTM

**Pull request closed without merging**
