### PR TITLE
ARROW-4582: [Python/C++] Acquire the GIL on Py_INCREF

### PR DESCRIPTION
**Pull request by xhochy**
Minimal reproducing example:

```
import dask
import pandas as pd
import pyarrow as pa
import numpy as np

def segfault_me(df):
    pa.Table.from_pandas(df, nthreads=1)


while True:
    df = pd.DataFrame(
        {"P": np.arange(0, 10), "L": np.arange(0, 10), "TARGET": np.arange(10, 20)}
    )
    dask.compute([
        dask.delayed(segfault_me)(df),
        dask.delayed(segfault_me)(df),
        dask.delayed(segfault_me)(df),
        dask.delayed(segfault_me)(df),
        dask.delayed(segfault_me)(df),
    ])
```

Segfaults are more likely when run in AddressSanitizer or otherwise slow system with many cores. It is important that always the same df is passed into the functions.

The issue was that the reference count of the underlying NumPy array was increased at the same time by multiple threads. The decrease happend then with a GIL, so the array was sometimes destroyed while still used.

### CODE REVIEW

**Comment by kszucs** [comment]
Would You mind adding a test for it?

**Comment by xhochy** [comment]
@kszucs I have no idea on how to test this. It's a race condition that occured really seldomly.

**Comment by xhochy** [comment]
Green AppVeyor build: https://ci.appveyor.com/project/xhochy/arrow/builds/22397027

**Comment by wesm** [comment]
@xhochy nice catch!! Taking a closer look

**Review by wesm — APPROVED** [review]
+1

**Pull request closed without merging**
