### PR TITLE
MINOR: [Docs] Replace "have" with "indicate" in the "Struct validity" section of the docs

### PR DESCRIPTION
**Pull request by stfdxv**
### Rationale for this change
This documentation [section](https://arrow.apache.org/docs/format/Columnar.html#struct-validity) says:
`...a child array might have a null in its validity bitmap...`
But an array can't have a null in its validity bitmap. It can only indicate a null with a bit equal to 0 in its validity bitmap.

### What changes are included in this PR?
Rewording

### Are these changes tested?
Renders normally

### Are there any user-facing changes?
Changes documentation only.

### CODE REVIEW

**Comment by stfdxv** [comment]
@github-actions crossbow submit preview-docs

**Comment by kou** [comment]
Is it intentional that you change the text instead of example validities?

**Comment by stfdxv** [comment]
I've made this PR for training purposes, as I'm new to this. It's useful but it's not connected with the issue GH-38883.
Please see my second PR https://github.com/apache/arrow/pull/38898, which deals with GH-38883.

**Comment by kou** [comment]
Ah, I see.

**Review by kou — APPROVED** [review]
+1

**Pull request merged**
