### PR TITLE
GH-38607: [Python] Disable PyExtensionType autoload

### LINKED ISSUE #38607: [Python] Disable PyExtensionType autoload
### Describe the bug, including details regarding any error messages, version, and platform.

PyExtensionType autoload is really a misfeature. It creates Python-specific extension types and using ExtensionType is almost the same complexity.

We should therefore disable PyExtensionType autoloading and deprecate PyExtensionType instantiation.

### Component(s)

Python

### PR DESCRIPTION
**Pull request by pitrou**
### Rationale for this change

PyExtensionType autoload is really a misfeature. It creates PyArrow-specific extension types, though using ExtensionType is almost the same complexity while allowing deserialization from non-PyArrow software.

### What changes are included in this PR?

* Disable PyExtensionType autoloading and deprecate PyExtensionType instantiation.
* Update the docs to emphasize ExtensionType.

### Are these changes tested?

Yes.

### Are there any user-facing changes?

Yes.

* Closes: #38607

### CODE REVIEW

**Comment by pitrou** [comment]
@raulcd You may want to pick this up once CI is green.

**Review by raulcd — APPROVED** [review]
CI looks good to me and the change also looks good to me.

**Comment by milovanderlinden** [comment]
Would it also be possible to patch this into version 12.0.1 or other versions that are compatible with python 3.7? I am stuck on a particula version and cannot patch.

**Comment by pitrou** [comment]
@milovanderlinden We have published a hotfix specifically for this:
https://pypi.org/project/pyarrow-hotfix/

**Pull request merged**
