### PR TITLE
ARROW-15882: [Python][CI] Ensure we are running hypothesis tests in the nightly hypothesis build

### PR DESCRIPTION
**Pull request by jorisvandenbossche**

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
@github-actions crossbow submit test-conda-python-3.8-hypothesis

**Comment by jorisvandenbossche** [comment]
@github-actions crossbow submit test-conda-python-3.8-hypothesis

**Comment by jorisvandenbossche** [comment]
This is not yet working, will have to debug locally (it seems be that the `--enable-hypothesis` flag is not working, or generally the setup from conftest.py is not working when not running the tests from a source checkout)

**Comment by jorisvandenbossche** [comment]
@github-actions crossbow submit test-conda-python-3.8-hypothesis

**Comment by jorisvandenbossche** [comment]
This is working now! But the tests are failing ..

```
opt/conda/envs/arrow/lib/python3.8/site-packages/pyarrow/tests/test_strategies.py::test_chunked_arrays FAILED [ 68%]
Fatal Python error: Segmentation fault

Current thread 0x00007f8d483a6740 (most recent call first):
  File "/opt/conda/envs/arrow/lib/python3.8/site-packages/pyarrow/tests/strategies.py", line 311 in arrays
  File "/opt/conda/envs/arrow/lib/python3.8/site-packages/hypothesis/strategies/_internal/core.py", line 1419 in do_draw
  File "/opt/conda/envs/arrow/lib/python3.8/site-packages/hypothesis/internal/conjecture/data.py", line 874 in draw
  File "/opt/conda/envs/arrow/lib/python3.8/site-packages/hypothesis/strategies/_internal/lazy.py", line 158 in do_draw
  File "/opt/conda/envs/arrow/lib/python3.8/site-packages/hypothesis/internal/conjecture/data.py", line 874 in draw
  File "/opt/conda/envs/arrow/lib/python3.8/site-packages/pyarrow/tests/strategies.py", line 338 in <listcomp>
  File "/opt/conda/envs/arrow/lib/python3.8/site-packages/pyarrow/tests/strategies.py", line 338 in record_batches
  File "/opt/conda/envs/arrow/lib/python3.8/site-packages/hypothesis/strategies/_internal/core.py", line 1419 in do_draw
  File "/opt/conda/envs/arrow/lib/python3.8/site-packages/hypothesis/internal/conjecture/data.py", line 874 in draw
  File "/opt/conda/envs/arrow/lib/python3.8/site-packages/hypothesis/strategies/_internal/lazy.py", line 158 in do_draw
  File "/opt/conda/envs/arrow/lib/python3.8/site-packages/hypothesis/internal/conjecture/data.py", line 874 in draw
  File "/opt/conda/envs/arrow/lib/python3.8/site-packages/hypothesis/strategies/_internal/collections.py", line 58 in <genexpr>
  File "/opt/conda/envs/arrow/lib/python3.8/site-packages/hypothesis/strategies/_internal/collections.py", line 58 in do_draw
  File "/opt/conda/envs/arrow/lib/python3.8/site-packages/hypothesis/internal/conjecture/data.py", line 874 in draw
  File "/opt/conda/envs/arrow/lib/python3.8/site-packages/hypothesis/strategies/_internal/strategies.py", line 818 in do_draw
  File "/opt/conda/envs/arrow/lib/python3.8/site-packages/hypothesis/internal/conjecture/data.py", line 874 in draw
  File "/opt/conda/envs/arrow/lib/python3.8/site-packages/hypothesis/strategies/_internal/lazy.py", line 158 in do_draw
  File "/opt/conda/envs/arrow/lib/python3.8/site-packages/hypothesis/internal/conjecture/data.py", line 874 in draw
  File "/opt/conda/envs/arrow/lib/python3.8/site-packages/hypothesis/strategies/_internal/strategies.py", line 818 in do_draw
  File "/opt/conda/envs/arrow/lib/python3.8/site-packages/hypothesis/internal/conjecture/data.py", line 874 in draw
  File "/opt/conda/envs/arrow/lib/python3.8/site-packages/hypothesis/strategies/_internal/collections.py", line 58 in <genexpr>
  File "/opt/conda/envs/arrow/lib/python3.8/site-packages/hypothesis/strategies/_internal/collections.py", line 58 in do_draw
  File "/opt/conda/envs/arrow/lib/python3.8/site-packages/hypothesis/internal/conjecture/data.py", line 878 in draw
  File "/opt/conda/envs/arrow/lib/python3.8/site-packages/hypothesis/core.py", line 596 in run
  File "/opt/conda/envs/arrow/lib/python3.8/site-packages/hypothesis/executors.py", line 47 in default_new_style_executor
  File "/opt/conda/envs/arrow/lib/python3.8/site-packages/hypothesis/core.py", line 637 in execute_once
  File "/opt/conda/envs/arrow/lib/python3.8/site-packages/hypothesis/core.py", line 699 in _execute_once_for_engine
  File "/opt/conda/envs/arrow/lib/python3.8/site-packages/hypothesis/internal/conjecture/engine.py", line 184 in __stoppable_test_function
  File "/opt/conda/envs/arrow/lib/python3.8/site-packages/hypothesis/internal/conjecture/engine.py", line 208 in test_function
  File "/opt/conda/envs/arrow/lib/python3.8/site-packages/hypothesis/internal/conjecture/engine.py", line 723 in generate_new_examples
  File "/opt/conda/envs/arrow/lib/python3.8/site-packages/hypothesis/internal/conjecture/engine.py", line 872 in _run
  File "/opt/conda/envs/arrow/lib/python3.8/site-packages/hypothesis/internal/conjecture/engine.py", line 470 in run
  File "/opt/conda/envs/arrow/lib/python3.8/site-packages/hypothesis/core.py", line 776 in run_engine
  File "/opt/conda/envs/arrow/lib/python3.8/site-packages/hypothesis/core.py", line 1159 in wrapped_test
  File "/opt/conda/envs/arrow/lib/python3.8/site-packages/pyarrow/tests/test_strategies.py", line 55 in test_record_batches
  File "/opt/conda/envs/arrow/lib/python3.8/site-packages/_pytest/python.py", line 192 in pytest_pyfunc_call
  File "/opt/conda/envs/arrow/lib/python3.8/site-packages/pluggy/_callers.py", line 39 in _multicall
  File "/opt/conda/envs/arrow/lib/python3.8/site-packages/pluggy/_manager.py", line 80 in _hookexec
  File "/opt/conda/envs/arrow/lib/python3.8/site-packages/pluggy/_hooks.py", line 265 in __call__
  File "/opt/conda/envs/arrow/lib/python3.8/site-packages/_pytest/python.py", line 1718 in runtest
  File "/opt/conda/envs/arrow/lib/python3.8/site-packages/_pytest/runner.py", line 168 in pytest_runtest_call
  File "/opt/conda/envs/arrow/lib/python3.8/site-packages/pluggy/_callers.py", line 39 in _multicall
  File "/opt/conda/envs/arrow/lib/python3.8/site-packages/pluggy/_manager.py", line 80 in _hookexec
  File "/opt/conda/envs/arrow/lib/python3.8/site-packages/pluggy/_hooks.py", line 265 in __call__
  File "/opt/conda/envs/arrow/lib/python3.8/site-packages/_pytest/runner.py", line 261 in <lambda>
  File "/opt/conda/envs/arrow/lib/python3.8/site-packages/_pytest/runner.py", line 340 in from_call
  File "/opt/conda/envs/arrow/lib/python3.8/site-packages/_pytest/runner.py", line 260 in call_runtest_hook
  File "/opt/conda/envs/arrow/lib/python3.8/site-packages/_pytest/runner.py", line 221 in call_and_report
  File "/opt/conda/envs/arrow/lib/python3.8/site-packages/_pytest/runner.py", line 132 in runtestprotocol
  File "/opt/conda/envs/arrow/lib/python3.8/site-packages/_pytest/runner.py", line 113 in pytest_runtest_protocol
  File "/opt/conda/envs/arrow/lib/python3.8/site-packages/pluggy/_callers.py", line 39 in _multicall
  File "/opt/conda/envs/arrow/lib/python3.8/site-packages/pluggy/_manager.py", line 80 in _hookexec
  File "/opt/conda/envs/arrow/lib/python3.8/site-packages/pluggy/_hooks.py", line 265 in __call__
  File "/opt/conda/envs/arrow/lib/python3.8/site-packages/_pytest/main.py", line 347 in pytest_runtestloop
  File "/opt/conda/envs/arrow/lib/python3.8/site-packages/pluggy/_callers.py", line 39 in _multicall
  File "/opt/conda/envs/arrow/lib/python3.8/site-packages/pluggy/_manager.py", line 80 in _hookexec
  File "/opt/conda/envs/arrow/lib/python3.8/site-packages/pluggy/_hooks.py", line 265 in __call__
  File "/opt/conda/envs/arrow/lib/python3.8/site-packages/_pytest/main.py", line 322 in _main
  File "/opt/conda/envs/arrow/lib/python3.8/site-packages/_pytest/main.py", line 268 in wrap_session
  File "/opt/conda/envs/arrow/lib/python3.8/site-packages/_pytest/main.py", line 315 in pytest_cmdline_main
  File "/opt/conda/envs/arrow/lib/python3.8/site-packages/pluggy/_callers.py", line 39 in _multicall
  File "/opt/conda/envs/arrow/lib/python3.8/site-packages/pluggy/_manager.py", line 80 in _hookexec
  File "/opt/conda/envs/arrow/lib/python3.8/site-packages/pluggy/_hooks.py", line 265 in __call__
  File "/opt/conda/envs/arrow/lib/python3.8/site-packages/_pytest/config/__init__.py", line 165 in main
  File "/opt/conda/envs/arrow/lib/python3.8/site-packages/_pytest/config/__init__.py", line 188 in console_main
  File "/opt/conda/envs/arrow/bin/pytest", line 11 in <module>
/arrow/ci/scripts/python_test.sh: line 55: 12994 Segmentation fault      (core dumped) pytest -r s -v ${PYTEST_ARGS} --pyargs pyarrow
139
Error: `docker-compose --file /home/runner/work/crossbow/crossbow/arrow/docker-compose.yml run --rm -e SETUPTOOLS_SCM_PRETEND_VERSION=8.0.0.dev207 conda-python-pandas` exited with a non-zero exit code 139, see the process log above.
```

**Comment by AlenkaF** [comment]
To me it looks like in case the strategy selects a timestamp that is out of range (for example `datetime.datetime(1677, 9, 21, 1, 34, 43)`, out-of-bounds error is raised. I can't find any info about the timestamp range in the docs though. Will try to set the limit to the strategy to see if that is actually the problem.


<details>
<summary>Failure output</summary>
<br>
Here is the failure output I get when running `pytest -r s -v -m hypothesis --enable-hypothesis --hypothesis-profile=ci pyarrow` locally:
<br><br>
<pre>

```python

========================================================================================================== FAILURES ===========================================================================================================
_____________________________________________________________________________________________________ test_record_batches _____________________________________________________________________________________________________

    @h.given(past.all_record_batches)
>   def test_record_batches(record_bath):

pyarrow/tests/test_strategies.py:55: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
pyarrow/tests/strategies.py:338: in record_batches
    children = [draw(arrays(field.type, size=rows)) for field in schema]
pyarrow/tests/strategies.py:338: in <listcomp>
    children = [draw(arrays(field.type, size=rows)) for field in schema]
../../pyarrow-dev-9/lib/python3.9/site-packages/hypothesis/internal/conjecture/data.py:879: in draw
    return strategy.do_draw(self)
../../pyarrow-dev-9/lib/python3.9/site-packages/hypothesis/strategies/_internal/lazy.py:168: in do_draw
    return data.draw(self.wrapped_strategy)
../../pyarrow-dev-9/lib/python3.9/site-packages/hypothesis/internal/conjecture/data.py:879: in draw
    return strategy.do_draw(self)
../../pyarrow-dev-9/lib/python3.9/site-packages/hypothesis/strategies/_internal/core.py:1430: in do_draw
    return self.definition(data.draw, *self.args, **self.kwargs)
pyarrow/tests/strategies.py:311: in arrays
    return pa.array(draw(values), type=ty)
../../pyarrow-dev-9/lib/python3.9/site-packages/hypothesis/internal/conjecture/data.py:879: in draw
    return strategy.do_draw(self)
../../pyarrow-dev-9/lib/python3.9/site-packages/hypothesis/strategies/_internal/lazy.py:168: in do_draw
    return data.draw(self.wrapped_strategy)
../../pyarrow-dev-9/lib/python3.9/site-packages/hypothesis/internal/conjecture/data.py:879: in draw
    return strategy.do_draw(self)
../../pyarrow-dev-9/lib/python3.9/site-packages/hypothesis/strategies/_internal/collections.py:185: in do_draw
    result.append(data.draw(self.element_strategy))
../../pyarrow-dev-9/lib/python3.9/site-packages/hypothesis/internal/conjecture/data.py:879: in draw
    return strategy.do_draw(self)
../../pyarrow-dev-9/lib/python3.9/site-packages/hypothesis/strategies/_internal/strategies.py:651: in do_draw
    return data.draw(strategy)
../../pyarrow-dev-9/lib/python3.9/site-packages/hypothesis/internal/conjecture/data.py:879: in draw
    return strategy.do_draw(self)
../../pyarrow-dev-9/lib/python3.9/site-packages/hypothesis/strategies/_internal/lazy.py:168: in do_draw
    return data.draw(self.wrapped_strategy)
../../pyarrow-dev-9/lib/python3.9/site-packages/hypothesis/internal/conjecture/data.py:879: in draw
    return strategy.do_draw(self)
../../pyarrow-dev-9/lib/python3.9/site-packages/hypothesis/strategies/_internal/core.py:1430: in do_draw
    return self.definition(data.draw, *self.args, **self.kwargs)
pyarrow/tests/strategies.py:213: in _pylist
    arr = draw(arrays(value_type, size=size, nullable=False))
../../pyarrow-dev-9/lib/python3.9/site-packages/hypothesis/internal/conjecture/data.py:879: in draw
    return strategy.do_draw(self)
../../pyarrow-dev-9/lib/python3.9/site-packages/hypothesis/strategies/_internal/lazy.py:168: in do_draw
    return data.draw(self.wrapped_strategy)
../../pyarrow-dev-9/lib/python3.9/site-packages/hypothesis/internal/conjecture/data.py:879: in draw
    return strategy.do_draw(self)
../../pyarrow-dev-9/lib/python3.9/site-packages/hypothesis/strategies/_internal/core.py:1430: in do_draw
    return self.definition(data.draw, *self.args, **self.kwargs)
pyarrow/tests/strategies.py:311: in arrays
    return pa.array(draw(values), type=ty)
pyarrow/array.pxi:316: in pyarrow.lib.array
    return _sequence_to_array(obj, mask, size, type, pool, c_from_pandas)
pyarrow/array.pxi:39: in pyarrow.lib._sequence_to_array
    chunked = GetResultValue(
pyarrow/error.pxi:143: in pyarrow.lib.pyarrow_internal_check_status
    return check_status(status)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

>   raise ArrowInvalid(message)
E   pyarrow.lib.ArrowInvalid: Could not convert datetime.datetime(1677, 9, 21, 1, 34, 43, tzinfo=<StaticTzInfo 'Etc/GMT-5'>) with type datetime.datetime: out of bounds for nanosecond resolution
E   /Users/alenkafrim/repos/arrow/cpp/src/arrow/python/python_to_arrow.cc:640  PyValue::Convert(this->primitive_type_, this->options_, value)
E   /Users/alenkafrim/repos/arrow/cpp/src/arrow/python/iterators.h:73  func(value, static_cast<int64_t>(i), &keep_going)
E   /Users/alenkafrim/repos/arrow/cpp/src/arrow/python/python_to_arrow.cc:1182  converter->Extend(seq, size)
```
</pre>
</details>

**Comment by AlenkaF** [comment]
@github-actions crossbow submit test-conda-python-3.8-hypothesis

**Comment by jorisvandenbossche** [comment]
@github-actions crossbow submit test-conda-python-3.8-hypothesis

**Comment by jorisvandenbossche** [comment]
@github-actions crossbow submit test-conda-python-3.8-hypothesis

**Pull request closed without merging**
