### PR TITLE
ARROW-13942: [Dev] Update cmake_format usage in autotune comment bot

### PR DESCRIPTION
**Pull request by kou**
This is a follow-up of #10571 / ARROW-8459 .

### CODE REVIEW

**Comment by kou** [comment]
I confirmed that this works well on https://github.com/kou/arrow/pull/10#issuecomment-915661313 :
https://github.com/kou/arrow/runs/3550837829?check_suite_focus=true#step:6:80

**Comment by kou** [comment]
@kszucs Do you want to review this?

**Review by kszucs — APPROVED** [review]
LGTM, thanks @kou!

**Comment by kou** [comment]
Thanks for the review!

I'll merge this.

**Pull request closed without merging**
