### PR TITLE
ARROW-6314: [C#] Implement IPC message format alignment changes, provide backwards compatibility and "legacy" option to emit old message format

### PR DESCRIPTION
**Pull request by eerhardt**
Porting the fix for ARROW-6314 to the C# library.

/cc @chutchinson @pgovind

### CODE REVIEW

**Comment by wesm** [comment]
Thanks @eerhardt!

**Review by pgovind — APPROVED** [review]
LGTM

**Comment by wesm** [comment]
Does this patch account for the EOS change under discussion on the mailing list?

**Comment by eerhardt** [comment]
> Does this patch account for the EOS change under discussion on the mailing list?

Yes, partially. The reader handles the first 4 bytes being `0` to mean stop reading after 4 bytes. And if it encounters a continuation token 0xFFFFFFFF and then a `0` it stops.

On the writer side, the C# API doesn't have a "Write end of stream" function. But maybe now it is important to add that method, since the EOS can take 2 formats depending on the options.

I can add that new API, if you think it makes sense.

**Comment by wesm** [comment]
Yes, that sounds good to me!

**Comment by eerhardt** [comment]
@pgovind @chutchinson - FYI I implemented a new method on `ArrowStreamWriter` - `WriteEndAsync()`, which will write the EOS signal. I also moved `ArrowFileWriter`'s `WriteFooterAsync` to instead just use `WriteEndAsync` from the base class. This means anyone using ArrowFileWriter will have a slight change - `WriteFooterAsync` => `WriteEndAsync`.

Please take another look.

**Review by pgovind — APPROVED** [review]

**Review by chutchinson — CHANGES_REQUESTED** [review]

**Pull request closed without merging**
