### PR TITLE
ARROW-13304: [C++] Unable to install nightly on Ubuntu 21.04 due to day of week options

### PR DESCRIPTION
**Pull request by rok**
To address [ARROW-13304](https://issues.apache.org/jira/browse/ARROW-13304).

### CODE REVIEW

**Review by lidavidm — APPROVED** [review]
Thanks, and apologies for the complications here.

**Comment by rok** [comment]
@lidavidm I don't think this solved the `CsvFileWriterOptions` yet. [See Jira](https://issues.apache.org/jira/browse/ARROW-13304?focusedCommentId=17378814&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-17378814).

**Comment by rok** [comment]
Moved the import to another location. Guessing.

**Comment by lidavidm** [comment]
Hmm, arrow/dataset/type_fwd.h defines CsvFileWriteOptions. Not sure why that's coming up.

**Comment by pachadotdev** [comment]
I can confirm this solves the problem, see https://t.co/f8FBXZobMj?amp=1

**Comment by pachadotdev** [comment]
@lidavidm can we merge this?

**Comment by rok** [comment]
I'm not sure all changes are optimal. @lidavidm please scrutinize :)

**Review by lidavidm — COMMENTED** [review]
@pachadotdev can you upload your entire compile log somewhere? It's unclear what's going wrong or if there's something else we're missing.

**Comment by rok** [comment]
Agreed on all points. Unfortunately I can't reproduce any of this.

**Comment by lidavidm** [comment]
Let's get CI here fixed (looks like arrowExports.cpp needs to be regenerated?) and have Pacha confirm that the fix still works. I'd still like to see a full install log if possible.

**Comment by rok** [comment]
> I mentioned this in Jira, but it might have gotten lost in the shuffle: We [have a crossbow job that installs (using the bundled approach, which is the default for end-users) on 21.04](https://github.com/apache/arrow/blob/master/dev/tasks/tasks.yml#L937-L946) which hasn't failed since it was implemented. What's different between our CI job and the approach that is allegedly failing?
> 
> If one wanted to build locally without the bundled approach (in case that's what we think the difference is), the following should work:
> 
> ```
> UBUNTU=21.04 CLANG_TOOLS=9 archery docker run ubuntu-r
> ```
> 
> and to run the job like it is by crossbow (i.e. a bundled build):
> 
> ```
> UBUNTU=21.04 CLANG_TOOLS=9 archery docker run -e ARROW_SOURCE_HOME="/arrow" -e FORCE_BUNDLED_BUILD=TRUE -e LIBARROW_BUILD=TRUE ubuntu-r
> ```

Thanks for the archery commands @jonkeane! I've tried these out (had to [update my docker to get around a build issue with gpg](https://stackoverflow.com/questions/66319610/gpg-error-in-ubuntu-21-04-after-second-apt-get-update-during-docker-build#comment118776758_66385784)) and I'm not seeing any errors on either master or this branch. So I'm really not sure what's happening here.

@pachadotdev are you running this on your laptop or in docker? If in docker perhaps you can try rebuilding your image?

**Comment by pitrou** [comment]
@pachadotdev Can you still reproduce this issue? Otherwise, we may close this PR.

**Comment by rok** [comment]
Can't reproduce. Closing.

**Pull request closed without merging**
