### PR TITLE
ARROW-3183: [Python] Fix get_library_dirs on Windows

### PR DESCRIPTION
**Pull request by vmuriart**

### CODE REVIEW

**Review by kszucs — COMMENTED** [review]
Could You please write a test case for it?

**Comment by xhochy** [comment]
@vmuriart The test actually fails on AppVeyor. Can you have a look?

**Comment by vmuriart** [comment]
Yea, I noticed that. I'll need to do a bit of research to see what's
different. I'll take a look on Monday since I dont access to my computer
till then.

**Comment by vmuriart** [comment]
I'm looking at this now, and looks like its a difference between how its being built in AppVeyor vs conda-forge.

On AppVeyor's log I am seeing that the library files are being placed in `site-packages`.
image

But if I look at where they are installed locally(when installed from conda-forge), they are on the folder I coded for.

**Comment by vmuriart** [comment]
If the library is installed through `pip` from `pypi` then the libraries are located inside of `site-packages\pyarrow`. So the location of where the binaries will end up is different in each case, which makes sense since the conda install has the binaries as part of `arrow-cpp` package.

Would it make sense to have both paths on the `get_library_dirs` to cover both cases?

**Review by wesm — APPROVED** [review]
+1. Thanks @vmuriart!

**Pull request closed without merging**
