### PR TITLE
ARROW-8872: [CI] Restore ci/detect-changes.py

### PR DESCRIPTION
**Pull request by pitrou**
This is needed for Travis-CI builds to function properly.
The file was mistakingly removed in db1c49a77f78152d442299082f6a663e59f91174, part of PR #7080 (fixing ARROW-8662).

### CODE REVIEW

**Comment by pitrou** [comment]
Travis-CI build: https://travis-ci.org/github/pitrou/arrow/builds/689214234

**Comment by pitrou** [comment]
Will merge.

**Comment by nealrichardson** [comment]
Oops! I saw that appveyor PR sitting there passing CI so I merged it. Unfortunately the Travis job that used that script again was added between when the commits were done and when I merged it :/

**Comment by kszucs** [comment]
Thanks Antoine!

**Pull request closed without merging**
