### PR TITLE
[Gandiva][C++] Fix implementation castBIT / castBoolean

### PR DESCRIPTION
**Pull request by Johnnathanalmeida**

### CODE REVIEW

**Comment by Johnnathanalmeida** [comment]
@github-actions crossbow submit java-jars

**Comment by Johnnathanalmeida** [comment]
@github-actions crossbow submit java-jars

**Comment by Johnnathanalmeida** [comment]
@github-actions crossbow submit java-jars

**Comment by Johnnathanalmeida** [comment]
@github-actions crossbow submit java-jars

**Comment by amol-** [comment]
Closing because it has been untouched for a while, in case it's still relevant feel free to reopen and move it forward 👍

**Pull request closed without merging**
