### PR TITLE
ARROW-8844: [C++] Transfer bitmap in words

### PR DESCRIPTION
**Pull request by cyb70289**
Copy/Invert bitmap in words improves performance significantly.
Partial aligned case jumps from 914M/s to 6.6G/s, and non aligned
case from 82M/s to 3.8G/s on my test machine.

### CODE REVIEW

**Comment by cyb70289** [comment]
Tested on AMD Zen1 with gcc-7.5

before (CopyBitmapWithOffsetBoth is added by this patch)
```
CopyBitmapWithoutOffset/8192                  190 ns          190 ns      3678223 bytes_per_second=40.0804G/s
CopyBitmapWithOffset/8192                    8548 ns         8548 ns        81846 bytes_per_second=914.007M/s
CopyBitmapWithOffsetBoth/8192               95447 ns        95445 ns         7334 bytes_per_second=81.8531M/s
```

after
```
CopyBitmapWithoutOffset/8192                  191 ns          191 ns      3670699 bytes_per_second=39.9939G/s
CopyBitmapWithOffset/8192                    1151 ns         1151 ns       600632 bytes_per_second=6.62768G/s
CopyBitmapWithOffsetBoth/8192                2018 ns         2018 ns       346761 bytes_per_second=3.78089G/s
```

**Comment by cyb70289** [comment]
There are similar codes in my three recent patches optimizing unaligned bitmap operations (logical, compare, copy). I opened a new jira to refine. https://issues.apache.org/jira/browse/ARROW-8979

**Comment by cyb70289** [comment]
@ursabot benchmark --suite-filter=arrow-bit-util-benchmark --benchmark-filter=CopyBitmapWithOffset

**Comment by fsaintjacques** [comment]
> [AMD64 Ubuntu 18.04 C++ Benchmark (#108408)](https://ci.ursalabs.org/#builders/73/builds/65) builder has been succeeded.
> 
> Revision: [ef4d77c](https://github.com/apache/arrow/commit/ef4d77ceabd23b51e052e4da58310ebacdc0fe9d)
> 
> ```diff
>   =============================  ===========  ===========  ============
>   benchmark                         baseline    contender        change
>   =============================  ===========  ===========  ============
>   CopyBitmapWithOffsetBoth/8192  2.48133e+09  2.48132e+09  -3.12173e-06
>   CopyBitmapWithOffset/8192      4.14268e+09  4.14273e+09   1.20158e-05
> ```

I'll need to fix this, tried to address this last time, weirdly it was fixed locally...

**Comment by wesm** [comment]
Is there a JIRA about fixing the legibility of the benchmark diff?

**Comment by fsaintjacques** [comment]
@ursabot benchmark --suite-filter=arrow-bit-util-benchmark --benchmark-filter=CopyBitmapWithOffset origin/master

**Comment by fsaintjacques** [comment]
@ursabot --help

**Comment by kszucs** [comment]
@ursabot build

**Comment by kszucs** [comment]
@ursabot benchmark

**Comment by kszucs** [comment]
@ursabot benchmark --suite-filter=arrow-bit-util-benchmark --benchmark-filter=CopyBitmapWithOffset origin/master

**Comment by kszucs** [comment]
@ursabot build

**Comment by fsaintjacques** [comment]
@ursabot benchmark --help

**Comment by fsaintjacques** [comment]
@ursabot benchmark --suite-filter=arrow-bit-util-benchmark --benchmark-filter=CopyBitmapWithOffset origin/master

**Comment by fsaintjacques** [comment]
once https://github.com/ursa-labs/ursabot/pull/197 is merged, we shouldn't need to specify `origin/master` as a baseline.

**Review by fsaintjacques — APPROVED** [review]

**Comment by wesm** [comment]
Needs rebase

**Comment by wesm** [comment]
The RTools 4.0 build was hanging so I triggered a new build

**Pull request closed without merging**
