### PR TITLE
ARROW-7288: [C++][R] read_parquet() freezes on Windows with Japanese locale

### PR DESCRIPTION
**Pull request by nealrichardson**

### CODE REVIEW

**Comment by nealrichardson** [comment]
@github-actions autotune

**Review by kou — APPROVED** [review]
+1

I like using RE2 not `boost::regex` because we already use RE2 in compute, Gandiva and Flight.
But it looks good to me if we use `boost::regex` for MinGW.

**Comment by nealrichardson** [comment]
@kou should I merge this and make a followup JIRA to switch to RE2? Or do you want to try doing RE2 now (started at #9332)?

**Comment by kou** [comment]
Could you wait for a few days? (You're not in a hurry, right?)
I want to consider how to solve this.

**Comment by nealrichardson** [comment]
Sure, no rush. Appreciate your looking into it. I was only trying a bunch of things because I've been hunting this bug for a long time and was excited to see it squashed :)

**Comment by kou** [comment]
How about using hand-written parser instead of regular expression? #9367

**Comment by nealrichardson** [comment]
Closing in favor of #9367

**Pull request closed without merging**
