### PR TITLE
ARROW-8664: [Java] Add flag to skip null check

### PR DESCRIPTION
**Pull request by rymurr**
All Vector containers should skip null check when null
check flag is enabled

### CODE REVIEW

**Comment by rdblue** [comment]
Looks good to me.

**Comment by wesm** [comment]
In the last adding a `getUnsafe` method was discussed. What do you think about that?

**Comment by jacques-n** [comment]
This looks good to me. +1.

> In the past adding a getUnsafe method was discussed. What do you think about that?

This ensures that the all methods are consistent with the current flag. I think the getUnsafe could make sense but seems like a separate thing.

**Comment by rymurr** [comment]
> This looks good to me. +1.
> 
> > In the past adding a getUnsafe method was discussed. What do you think about that?
> 
> This ensures that the all methods are consistent with the current flag. I think the getUnsafe could make sense but seems like a separate thing.

Captured this in https://issues.apache.org/jira/browse/ARROW-8738

**Comment by emkornfield** [comment]
Thanks @rymurr

**Pull request closed without merging**
