### PR TITLE
ARROW-11369: [DataFusion] Split physical_plan/expressions.rs

### PR DESCRIPTION
**Pull request by jorgecarleitao**
This PR splits the +4k LOC `expressions.rs` module in modules, one per expression, thereby making it easier to navigate and work with.

No backward incompatible changes are expected from this.

Each commit is an independent expression / logical change.

### CODE REVIEW

**Comment by jorgecarleitao** [comment]
The clippy error is unrelated.

**Review by alamb — APPROVED** [review]
Thanks @jorgecarleitao  -- this is great. ❤️ 

I went through the PR commit by commit spot checked things -- everything looked good to me though clearly I did not go through all the changes in detail.

FYI @seddonm1  in case this conflicts with work you are working on

**Comment by alamb** [comment]
Clippy error is addressed here: https://github.com/apache/arrow/pull/9314

**Comment by seddonm1** [comment]
Thanks @alamb and @jorgecarleitao . Good idea. I'll rebase and apply these changes. I think the next work will be to address the signatures so I'll be starting work again tomorrow.

**Review by andygrove — APPROVED** [review]
Thanks a lot for doing this @jorgecarleitao

**Comment by alamb** [comment]
🎉

**Pull request closed without merging**
