### PR TITLE
ARROW-17213: [C++] Fix for valgrind issue in test-r-linux-valgrind crossbow build

### PR DESCRIPTION
**Pull request by wesm**

### CODE REVIEW

**Comment by wesm** [comment]
@github-actions crossbow submit test-r-linux-valgrind

**Comment by wesm** [comment]
Thanks @paleolimbot I forgot about that API but that makes the fix a one-liner. I'm going to try to add a unit test that reproduces in the C++ unit tests (rather than having to wait 4 hours for the R valgrind test to run), but then we can merge this fix and cherry-pick into the release branch

**Comment by kou** [comment]
Is the linked JIRA correct?

**Comment by wesm** [comment]
No sorry I just fixed it

**Comment by wesm** [comment]
@kou you can merge this I will add a test in a separate PR

**Comment by wesm** [comment]
+1

**Pull request merged**
