### PR TITLE
ARROW-6408: [Rust] use "if cfg!" pattern

### PR DESCRIPTION
**Pull request by hengruo**
https://issues.apache.org/jira/browse/ARROW-6408

Thanks.

### CODE REVIEW

**Comment by paddyhoran** [comment]
Hey @hengruo thanks very mush for your contribution!  Can you assign the issue to yourself over on JIRA please?  I'm not sure if you have an account, I couldn't find you?

**Review by paddyhoran — APPROVED** [review]
Thanks @hengruo.  LGTM pending CI.

Did you run `fmt` over the code.  CI will check this and fail if not formatted correctly.  If you have not done this you can run `cargo +stable fmt --all` and it will auto format your code.

**Comment by hengruo** [comment]
> Thanks @hengruo. LGTM pending CI.
> 
> Did you run `fmt` over the code. CI will check this and fail if not formatted correctly. If you have not done this you can run `cargo +stable fmt --all` and it will auto format your code.

Yes, I have run it.

**Comment by paddyhoran** [comment]
> Yes, I have run it.

Ok great.  Just didn't want you to have to wait for CI to finish before finding out :)

**Comment by hengruo** [comment]
> Hey @hengruo thanks very mush for your contribution! Can you assign the issue to yourself over on JIRA please? I'm not sure if you have an account, I couldn't find you?

I have a JIRA account and the username is "hengruo", full name "Hengruo Zhang". I tried to assign it to myself, but there is no "Assign me" button under "Assignee". Could you please assign it to me?

**Comment by paddyhoran** [comment]
It's a permission issue that has come up before.  I e-mailed the mailing list to get it updated.

**Comment by fsaintjacques** [comment]
It seems compile time have increased, see the following timeout failures:
- https://travis-ci.org/apache/arrow/jobs/581454026
- https://circleci.com/gh/ursa-labs/crossbow/2571

**Comment by paddyhoran** [comment]
Thanks @fsaintjacques.

It would be surprising if this change would add much to compile times.  The failed ursa-labs build does not get to the Arrow sub-crate (where these changes were made).

I'll take a look at compile times locally when I get a chance.

**Comment by hengruo** [comment]
Thanks, @fsaintjacques .
+ @paddyhoran 
I built both my branch and the **master branch of original repo** locally on Windows 10 and Ubuntu 16.04. On Windows, they both succeeded but on Ubuntu, they both failed. I checked other PRs. It seems there is no passing PR for rust (either failed or waiting). 

`lz4-sys` crate seems the bottleneck.

**Comment by paddyhoran** [comment]
> I checked other PRs. It seems there is no passing PR for rust

[This](https://github.com/apache/arrow/pull/5269) one passed 2 days ago (the CI failure is not for Rust)

> On Windows, they both succeeded but on Ubuntu, they both failed

They failed locally? Failed with what error (I'm on windows)?

I wonder if something changed on nightly that is causing this.  Pinging others who might know..  @andygrove @sunchao @nevi-me @liurenjie1024

**Comment by hengruo** [comment]
@paddyhoran 

Those are the results of building on apache/arrow master branch:

ubuntu 16.04 + stable:
```
error[E0554]: #![feature] may not be used on the stable release channel
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/packed_simd-0.3.3/src/lib.rs:202:1
    |
202 | / #![feature(
203 | |     repr_simd,
204 | |     const_fn,
205 | |     platform_intrinsics,
...   |
215 | |     custom_inner_attributes
216 | | )]
    | |__^
```
ubuntu 16.04 + nightly:
get stuck on compiling `backtrace-sys` and `lz4-sys`.

on windows:
both stable and nightly can pass.

**Comment by nevi-me** [comment]
Hi @paddyhoran @hengruo I'm checking

**Comment by paddyhoran** [comment]
The AppVeyor build for Andy's PR was over 10m (almost 13) which seemed to be the threshold causing these PR's to fail.  @hengruo can you push a trivial update to re-trigger CI and see if the issue is gone please? 

You can make a trivial change and then undo it as all your commits will be squashed when this is merged.

**Comment by andygrove** [comment]
In https://issues.apache.org/jira/browse/ARROW-6100 I have suggested that
we pin to a specific nightly release, so that builds are deterministic, and
we are explicit about updating the version when there is a reason to do so.

FWIW a local "cargo test" after a "cargo clean" takes 58 seconds locally
for me on master. I am on Ubuntu 19.04 and rustc 1.38.0-nightly (dddb7fca0
2019-07-30).

**Comment by andygrove** [comment]
Let's see if this builds cleanly: https://github.com/apache/arrow/pull/5324

**Comment by hengruo** [comment]
@paddyhoran 
I specify the nightly toolchain version and all checks have passed. Thanks.

**Review by nevi-me — APPROVED** [review]
LGTM, thanks @hengruo

**Pull request closed without merging**
