### PR TITLE
ARROW-9436: [C++][CI] Fix Valgrind failure

### PR DESCRIPTION
**Pull request by pitrou**
Some bits were left uninitialized in the expected boolean array.

Also fix some warnings.

### CODE REVIEW

**Review by kszucs — APPROVED** [review]
LGTM, thanks Antoine!

**Comment by kszucs** [comment]
@github-actions crossbow submit conda-cpp-valgrind

**Comment by kszucs** [comment]
@github-actions crossbow submit test-conda-cpp-valgrind

**Review by wesm — APPROVED** [review]
+1. I ran this locally

**Pull request closed without merging**
