### PR TITLE
ARROW-16110: [C++] GcsFileSystem::Make ignores IOContext

### PR DESCRIPTION
**Pull request by rok**
This is to resolve [ARROW-16110](https://issues.apache.org/jira/browse/ARROW-16110).

### CODE REVIEW

**Comment by emkornfield** [comment]
LGTM

**Comment by emkornfield** [comment]
Yeah, nice catch.

**Comment by rok** [comment]
CI issues seem unrelated.

**Review by kou — APPROVED** [review]
+1

**Pull request closed without merging**
