### PR TITLE
GH-38286: [CI][R] Clean GitHub runner disk for ubuntu-r-only-r images

### LINKED ISSUE #38286: [CI][R] test-r-dev-duckdb fails with out of space on runner
### Describe the bug, including details regarding any error messages, version, and platform.

Both on the maintenance branch and nightlies the `test-r-dev-duckdb` task is failing with out of space:
Maint 14: https://github.com/ursacomputing/crossbow/actions/runs/6533643107/job/17743290845
Main: https://github.com/ursacomputing/crossbow/actions/runs/6527426645/job/17722261954

### Component(s)

Continuous Integration, R

### PR DESCRIPTION
**Pull request by raulcd**
### Rationale for this change
Fix CI failures for job that is getting out of space.

### What changes are included in this PR?

Using our free disk space script to add space for the ubuntu-r-only-r images.

### Are these changes tested?

On CI

### Are there any user-facing changes?
No
* Closes: #38286

### CODE REVIEW

**Comment by raulcd** [comment]
@github-actions crossbow submit test-r*

**Comment by raulcd** [comment]
@github-actions crossbow submit test-r*

**Comment by raulcd** [comment]
The `duck-db` errors have been solved and the rest of the errors seem unrelated. @assignUser thoughts?

**Review by jonkeane — APPROVED** [review]
This looks good to me. Are there any other places we should add this?

The failure for test-r-rhub-ubuntu-gcc-release-latest has been around for a long time, I didn't see another issue for it, but created https://github.com/apache/arrow/issues/38295

**Review by assignUser — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
