### PR TITLE
ARROW-3235: [Packaging] Update deb names

### PR DESCRIPTION
**Pull request by kou**
TODO: This should be done in release process automatically.

### CODE REVIEW

**Comment by kou** [comment]
We can work on the TODO in another pull request.

**Comment by kszucs** [comment]
Hi @kou! A bit unrelated to this issue, but wanted to ask You: do We ship parquet linux packages? I'm afraid no, but I've seen You already done that in read data tools' repository.

**Review by wesm — APPROVED** [review]
+1

**Comment by kou** [comment]
@kszucs If we include Parquet C++ source into Arrow's tar.gz, we should ship Linux packages for Parquet C++. (I'm sorry but I don't understand how to release Parquet C++ yet.)

Anyway, if Parquet C++ developers want the official Linux packages, I can contribute my work.

**Comment by kszucs** [comment]
@wesm any thoughts on this?

**Comment by wesm** [comment]
The Parquet sources will be shipped in the release tarball

**Pull request closed without merging**
