### PR TITLE
ARROW-9582: [Rust] Implement memory size methods

### PR DESCRIPTION
**Pull request by vertexclique**
This PR is a slightly extended version of the PR https://github.com/apache/arrow/pull/7853.

* `memory_used`: Only calculates internally held data size.
* `memory_capacity`: Calculates total physical memory size including vtable, pointed size and whatnot. (I am not sure about the name)

cc @andygrove @paddyhoran @nevi-me

### CODE REVIEW

**Review by andygrove — APPROVED** [review]
LGTM

**Comment by sunchao** [comment]
Instead of `buffer_memory_size` and `total_memory_size`, I'm thinking whether `memory_used` and `memory_capacity` makes more sense.

**Comment by vertexclique** [comment]
@sunchao even the latter is physical memory calculation, I addressed your comment. :)

**Comment by vertexclique** [comment]
Is this ok @andygrove ? Can we merge this one as it is?

**Comment by jhorstmann** [comment]
> Instead of `buffer_memory_size` and `total_memory_size`, I'm thinking whether `memory_used` and `memory_capacity` makes more sense.

I think the new names, or maybe the comments for those methods, are more confusing than before. The idea seemed to be to have one method returning the size of just the buffers and another method that includes additional memory overhead like pointers, offsets, arc and so on.

**Comment by andygrove** [comment]
I agree with @jhorstmann since I am also confused by the naming and comments.

My original requirement was for a method that would tell me how much physical memory is occupied by an array's buffers. I would call this something like `get_buffer_memory_size`. 

Others than asked for additional functionality to determine how much of the memory is actually being used for data. I suppose I would call this something like `get_buffer_utitilized_size`.

Then there is the idea of an additional method that returns the total memory used by an array, including the buffers and other attributes. I'm not sure why we need this, personally, but if we do then I suppose `get_array_memory_size` would work?

What do others think?

**Comment by jhorstmann** [comment]
The names proposed by @andygrove sound very clear to me. I also don't think there is a need for a method that includes additional attributes as that overhead should be comparatively low in applications that care about memory usage, and it is maybe not worth the additional code complexity.

**Comment by vertexclique** [comment]
> My original requirement was for a method that would tell me how much physical memory is occupied by an array's buffers. I would call this something like `get_buffer_memory_size`.

> Others than asked for additional functionality to determine how much of the memory is actually being used for data. I suppose I would call this something like `get_buffer_utitilized_size`.

> Then there is the idea of an additional method that returns the total memory used by an array, including the buffers and other attributes. I'm not sure why we need this, personally, but if we do then I suppose `get_array_memory_size` would work?

1. Changed to `get_buffer_memory_size` and `get_array_memory_size`. Since they correspond to that.

> ... I'm not sure why we need this, personally...

I am using this for memory estimation and eviction calculation in the db that I am writing. That is kind of important since these are also giving accurate results about what is resident.

**Review by andygrove — APPROVED** [review]
LGTM - thanks @vertexclique

**Pull request closed without merging**
