### PR TITLE
ARROW-2458: [Plasma] Use one thread pool per PlasmaClient

### PR DESCRIPTION
**Pull request by pcmoritz**
This removes the global `thread pool_` variable from the PlasmaClient.

cc @robertnishihara @pitrou

### CODE REVIEW

**Comment by pitrou** [comment]
Is there a risk of excessive resource consumption if there are several plasma clients around? I see that the thread pool is used for memcpy and hashing. I think a single global thread pool with # threads == # number of CPU cores would make more sense.

**Comment by pitrou** [comment]
In other words, I think the right way of improving the plasma client here would be to have some global thread pool policy for Arrow. That global policy can provide two separate thread pools, one for CPU-bound tasks (e.g. memcpy, hashing or compression) and one for IO-bound tasks (such as file or network tasks). The CPU-bound threadpool should have, by default, the machine's number of HW threads (*). The IO-bound threadpool can have a multiple of that number (e.g. 5x).

(*) e.g. through http://en.cppreference.com/w/cpp/thread/thread/hardware_concurrency

**Comment by pitrou** [comment]
Note we could also take an existing header-only C++11 thread pool implementation (example: https://github.com/inkooboo/thread-pool-cpp), though I'm not sure what our policy is for vendoring code. @fjetter @xhochy

**Comment by robertnishihara** [comment]
I think the approach in this PR makes sense since. @pitrou the problem that you point exists regardless because we already give each client its own thread pool when the clients are isolated in different processes, and this preserves the behavior when the clients are in the same process.

One thing that could help (though I would prefer doing it in a separate PR) is to let the user pass in the thread pool size to the constructor.

**Comment by pitrou** [comment]
> @pitrou the problem that you point exists regardless because we already give each client its own thread pool when the clients are isolated in different processes, and this preserves the behavior when the clients are in the same process.

I don't think preserving a behavior which is clearly detrimental is a good idea. It's true that when several processes have a thread pool each, there can be excessive resource consumption, but that's not a reason to reproduce the problem inside a single process as well.

By the way, it's not obvious to me what the issue is we are trying to solve. The JIRA issue says "This prevents us from using multiple PlasmaClients in the same process (one per thread)", but I don't understand why the current thread pool policy prevents that. Your clients will simply be sharing a single thread pool.

**Comment by xhochy** [comment]
> Note we could also take an existing header-only C++11 thread pool implementation (example: https://github.com/inkooboo/thread-pool-cpp), though I'm not sure what our policy is for vendoring code.

@pitrou Vendoring code is ok. We need to clearly mark that the code is vendored, e.g. by placing in a `thirdparty` directory. Additionally, this should be lined out in the `NOTICE` and `LICENSE` files. I think an important component for ASF policies is that it must be visible what code is just vendored, not submitted a code donation.

**Comment by pitrou** [comment]
As a sidenote, could someone explain what the goal of `PlasmaClient::Hash` is? What is the use case of computing an object's hash?

Also, is the returned value meant to be stable? It seems to me that any change to the pooling parameters (block size, number of threads) would give a different result value.

**Comment by pitrou** [comment]
Created ARROW-2479 for the thread pool policy issue.

**Comment by robertnishihara** [comment]
Thanks! The point of the hash is to have a simple way to check if two objects are identical. In particular, given that objects can be evicted from the object store, if an object is recreated in the object store after eviction, you can compare hashes to see if the two objects differ.

Note that the probably more important place where we use multiple threads is https://github.com/apache/arrow/blob/b8754eba4683e7300a751f60a2fc1eef152cea1d/cpp/src/arrow/util/memory.h#L34

This already seems to be thread safe (since the thread creation is encapsulated in the `parallel_memcopy` function). Though it has the same potential issue that you're raising here.

If we use a thread pool implementation then we should run some benchmarks before merging, because the performance requirements are pretty demanding here. We want low latency for small objects but also to be able to write to the object store at near the memory-bandwidth (ideally at least 20GB/s, though currently it seems a bit slower).

I'm still in favor of merging this PR since it fixes a segfault and has a very a simple design. If the thread pool approach ends up working out that'd be great since it would be nice to support applications with hundreds of plasma clients (which is something we've been trying recently).

**Comment by pitrou** [comment]
Fair enough.

**Review by pitrou — APPROVED** [review]
While the general approach is suboptimal, this fixes a thread safety issue, so +1.

**Pull request closed without merging**
