### PR TITLE
WIP ARROW-3873: [C++] Fix typo in CMakeLists.txt

### PR DESCRIPTION
**Pull request by pitrou**

### CODE REVIEW

**Comment by pitrou** [comment]
Hmm, it appears the build failed. Frankly I don't really know what this is for, but having a reference to PARQUET_BUILD_SHARED in the Arrow cmake files sounds intuitively wrong. @wesm ?

**Comment by wesm** [comment]
Yes, this looks like a copy-paste error. I'd have to look back through commit logs but there was an issue with CMake's behavior around symbol visibility flags. I can try to take a look today at this if it helps

**Comment by pitrou** [comment]
It would be nice if you could take a look, though I guess it's not terribly important. I just wanted to diagnose the build warnings mentioned here:
https://github.com/apache/parquet-cpp/pull/487#issuecomment-413473612

**Comment by wesm** [comment]
Got it, I will take a look

**Comment by wesm** [comment]
I can look into this this week

**Comment by wesm** [comment]
Now with `-fvisibility=hidden` gcc doesn't like the way that we are exporting symbols from our extern templates in libparquet

```
src/parquet/CMakeFiles/parquet-column_reader-test.dir/column_reader-test.cc.o: In function `parquet::test::TestPrimitiveReader_TestInt32FlatRequiredSkip_Test::TestBody()':
/home/wesm/code/arrow/cpp/build/../src/parquet/column_reader-test.cc:282: undefined reference to `parquet::TypedColumnReader<parquet::DataType<(parquet::Type::type)1> >::Skip(long)'
/home/wesm/code/arrow/cpp/build/../src/parquet/column_reader-test.cc:286: undefined reference to `parquet::TypedColumnReader<parquet::DataType<(parquet::Type::type)1> >::ReadBatch(long, short*, short*, int*, long*)'
/home/wesm/code/arrow/cpp/build/../src/parquet/column_reader-test.cc:293: undefined reference to `parquet::TypedColumnReader<parquet::DataType<(parquet::Type::type)1> >::Skip(long)'
/home/wesm/code/arrow/cpp/build/../src/parquet/column_reader-test.cc:297: undefined reference to `parquet::TypedColumnReader<parquet::DataType<(parquet::Type::type)1> >::ReadBatch(long, short*, short*, int*, long*)'
/home/wesm/code/arrow/cpp/build/../src/parquet/column_reader-test.cc:307: undefined reference to `parquet::TypedColumnReader<parquet::DataType<(parquet::Type::type)1> >::Skip(long)'
/home/wesm/code/arrow/cpp/build/../src/parquet/column_reader-test.cc:311: undefined reference to `parquet::TypedColumnReader<parquet::DataType<(parquet::Type::type)1> >::ReadBatch(long, short*, short*, int*, long*)'
src/parquet/CMakeFiles/parquet-column_reader-test.dir/column_reader-test.cc.o: In function `parquet::test::TestPrimitiveReader::CheckResults()':
/home/wesm/code/arrow/cpp/build/../src/parquet/column_reader-test.cc:102: undefined reference to `parquet::TypedColumnReader<parquet::DataType<(parquet::Type::type)1> >::ReadBatch(long, short*, short*, int*, long*)'
/home/wesm/code/arrow/cpp/build/../src/parquet/column_reader-test.cc:119: undefined reference to `parquet::TypedColumnReader<parquet::DataType<(parquet::Type::type)1> >::ReadBatch(long, short*, short*, int*, long*)'
src/parquet/CMakeFiles/parquet-column_reader-test.dir/column_reader-test.cc.o: In function `parquet::test::TestPrimitiveReader::CheckResultsSpaced()':
/home/wesm/code/arrow/cpp/build/../src/parquet/column_reader-test.cc:146: undefined reference to `parquet::TypedColumnReader<parquet::DataType<(parquet::Type::type)1> >::ReadBatchSpaced(long, short*, short*, int*, unsigned char*, long, long*, long*, long*)'
/home/wesm/code/arrow/cpp/build/../src/parquet/column_reader-test.cc:168: undefined reference to `parquet::TypedColumnReader<parquet::DataType<(parquet::Type::type)1> >::ReadBatchSpaced(long, short*, short*, int*, unsigned char*, long, long*, long*, long*)'
collect2: error: ld returned 1 exit status
```

I fiddled with this a little bit but don't know why the symbols are not being exported. As an aside, the mess of visibility modifiers on these templates has always struck me as a little bit fishy (I had to dig around in Chromium's codebase to learn the incantations to get things to work originally on gcc / clang / MSVC)

**Comment by wesm** [comment]
I might like to refactor things to make the extern templates unnecessary, which would be a good bit of work but perhaps for the best. This would be without altering the public API. I'll leave this issue open for a while before embarking on this

**Comment by wesm** [comment]
Yeah, I think so, let me rebase and see how things look. "extern template class" is now my most hated C++11 feature. It only makes sense if you are developing for a single compiler

**Comment by wesm** [comment]
@emkornfield unfortunately there are more usages of "extern template class" causing linking problems

```
FAILED: debug/parquet-comparison-test 
: && /usr/bin/ccache /home/wesm/miniconda/envs/arrow-3.7/bin/x86_64-conda_cos6-linux-gnu-c++  -Wno-noexcept-type -D_GLIBCXX_USE_CXX11_ABI=1 -fuse-ld=gold -ggdb -O0  -Wall -Wconversion -Wno-sign-conversion -Werror -msse4.2  -g  -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags   -rdynamic src/parquet/util/CMakeFiles/parquet-comparison-test.dir/comparison-test.cc.o  -o debug/parquet-comparison-test  -Wl,-rpath,/home/wesm/code/arrow/cpp/build/debug:/home/wesm/miniconda/envs/arrow-3.7/lib debug/libarrow_testing.so.13.0.0 googletest_ep-prefix/src/googletest_ep/lib/libgtest_main.a googletest_ep-prefix/src/googletest_ep/lib/libgtest.a -lpthread -ldl debug/libparquet.so.13.0.0 /home/wesm/miniconda/envs/arrow-3.7/lib/libthrift.a debug/libarrow.so.13.0.0 -ldl jemalloc_ep-prefix/src/jemalloc_ep/dist//lib/libjemalloc_pic.a -pthread -lrt -Wl,-rpath-link,/home/wesm/miniconda/envs/arrow-3.7/lib && :
/home/wesm/miniconda/envs/arrow-3.7/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld.gold: warning: discarding version information for __pthread_key_create@GLIBC_2.2.5, defined in unused shared library /home/wesm/miniconda/envs/arrow-3.7/bin/../x86_64-conda_cos6-linux-gnu/sysroot/lib/libpthread.so.0 (linked with --as-needed)
../src/parquet/util/comparison-test.cc:199: error: undefined reference to 'parquet::CompareDefault<parquet::DataType<(parquet::Type::type)2> >::CompareDefault()'
../src/parquet/util/comparison-test.cc:201: error: undefined reference to 'parquet::CompareDefault<parquet::DataType<(parquet::Type::type)2> >::operator()(long const&, long const&)'
../src/parquet/util/comparison-test.cc:202: error: undefined reference to 'parquet::CompareDefault<parquet::DataType<(parquet::Type::type)2> >::operator()(long const&, long const&)'
../src/parquet/util/comparison-test.cc:202: error: undefined reference to 'parquet::CompareDefault<parquet::DataType<(parquet::Type::type)2> >::operator()(long const&, long const&)'
../src/parquet/util/comparison-test.cc:203: error: undefined reference to 'parquet::CompareDefault<parquet::DataType<(parquet::Type::type)2> >::operator()(long const&, long const&)'
../src/parquet/util/comparison.h:39: error: undefined reference to 'vtable for parquet::CompareDefault<parquet::DataType<(parquet::Type::type)2> >'
/home/wesm/miniconda/envs/arrow-3.7/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld.gold: the vtable symbol may be undefined because the class is missing its key function
../src/parquet/util/comparison.h:103: error: undefined reference to 'parquet::CompareDefault<parquet::DataType<(parquet::Type::type)2> >::CompareDefault()'
../src/parquet/util/comparison.h:39: error: undefined reference to 'vtable for parquet::CompareDefault<parquet::DataType<(parquet::Type::type)1> >'
/home/wesm/miniconda/envs/arrow-3.7/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld.gold: the vtable symbol may be undefined because the class is missing its key function
../src/parquet/util/comparison.h:98: error: undefined reference to 'parquet::CompareDefault<parquet::DataType<(parquet::Type::type)1> >::CompareDefault()'
collect2: error: ld returned 1 exit status
[26/166] Building CXX object src/parquet/CMakeFiles/parquet-statistics-test.dir/statistics-test.cc.o
^C
ninja: build stopped: interrupted by user.
```

I opened https://issues.apache.org/jira/browse/PARQUET-1523 about improving the comparator performance while also removing "extern template class"

cc @majetideepak

**Comment by wesm** [comment]
These are the remaining public usages of this feature

```
../src/parquet/util/visibility.h:#define PARQUET_TEMPLATE_EXPORT PARQUET_EXPORT
../src/parquet/util/visibility.h:#define PARQUET_TEMPLATE_EXPORT
../src/parquet/util/comparison.cc:template class PARQUET_TEMPLATE_EXPORT CompareDefault<BooleanType>;
../src/parquet/util/comparison.cc:template class PARQUET_TEMPLATE_EXPORT CompareDefault<Int32Type>;
../src/parquet/util/comparison.cc:template class PARQUET_TEMPLATE_EXPORT CompareDefault<Int64Type>;
../src/parquet/util/comparison.cc:template class PARQUET_TEMPLATE_EXPORT CompareDefault<Int96Type>;
../src/parquet/util/comparison.cc:template class PARQUET_TEMPLATE_EXPORT CompareDefault<FloatType>;
../src/parquet/util/comparison.cc:template class PARQUET_TEMPLATE_EXPORT CompareDefault<DoubleType>;
../src/parquet/util/comparison.cc:template class PARQUET_TEMPLATE_EXPORT CompareDefault<ByteArrayType>;
../src/parquet/util/comparison.cc:template class PARQUET_TEMPLATE_EXPORT CompareDefault<FLBAType>;
../src/parquet/statistics.cc:template class PARQUET_TEMPLATE_EXPORT TypedRowGroupStatistics<BooleanType>;
../src/parquet/statistics.cc:template class PARQUET_TEMPLATE_EXPORT TypedRowGroupStatistics<Int32Type>;
../src/parquet/statistics.cc:template class PARQUET_TEMPLATE_EXPORT TypedRowGroupStatistics<Int64Type>;
../src/parquet/statistics.cc:template class PARQUET_TEMPLATE_EXPORT TypedRowGroupStatistics<Int96Type>;
../src/parquet/statistics.cc:template class PARQUET_TEMPLATE_EXPORT TypedRowGroupStatistics<FloatType>;
../src/parquet/statistics.cc:template class PARQUET_TEMPLATE_EXPORT TypedRowGroupStatistics<DoubleType>;
../src/parquet/statistics.cc:template class PARQUET_TEMPLATE_EXPORT TypedRowGroupStatistics<ByteArrayType>;
../src/parquet/statistics.cc:template class PARQUET_TEMPLATE_EXPORT TypedRowGroupStatistics<FLBAType>;
```

**Comment by pitrou** [comment]
This PR looks like it needs rebasing.

**Comment by wesm** [comment]
Yes. I'm going to close this and start fresh once we eliminate the last of `extern template class` in Parquet

**Pull request closed without merging**
