### PR TITLE
ARROW-8499: [C++][Dataset] In ScannerBuilder, batch_size will not wor…

### PR DESCRIPTION
**Pull request by zhztheplayer**
…k if projecter is not empty

### CODE REVIEW

**Review by bkietz — APPROVED** [review]

**Comment by wesm** [comment]
Unit test possible?

**Comment by zhztheplayer** [comment]
> Unit test possible?

Is unit test always required for a quick fix like this? I thought this may belong to the kind of changes that could be easily proved right.

**Comment by wesm** [comment]
As a matter of principle, functional correctness needs to be validated by tests. If you don't test then something that is working, but not tested, may stop working as the result of refactoring.

**Comment by zhztheplayer** [comment]
OK but as the PR is already merged, maybe a follow-up JIRA ticket is needed?

**Comment by wesm** [comment]
Yes, indeed. Thank you

**Pull request closed without merging**
