### PR TITLE
ARROW-13137: [C++][Documentation] Make in-table references consistent

### PR DESCRIPTION
**Pull request by AlenkaF**
Updated `compute.rst` adding Notes column where needed and unifying raw syntax for in-table references.

### CODE REVIEW

**Comment by pitrou** [comment]
@amol- Do you want to take a look?

**Review by jorisvandenbossche — APPROVED** [review]
Looks good to me!

**Comment by amol-** [comment]
LGTM

**Review by amol- — APPROVED** [review]
LGTM

**Comment by jorisvandenbossche** [comment]
Thanks @AlenkaF !

**Pull request closed without merging**
