### PR TITLE
MINOR: [JS] Update dependencies

### PR DESCRIPTION
**Pull request by domoritz**
Redoing https://github.com/apache/arrow/pull/33919 but without updating closure.

### CODE REVIEW

**Comment by domoritz** [comment]
Clocked by a release of https://github.com/google/flatbuffers/issues/7814

**Comment by assignUser** [comment]
Looks like most of the CI failures are caused by https://github.com/apache/arrow/issues/34446
Though there is now a merge conflict that needs resolving.

**Comment by domoritz** [comment]
Thanks. I merged main to hopefully resolve those.

**Comment by domoritz** [comment]
The go failues seem unrelated to my changes. This is good to go. @trxcllnt can you approve?

**Review by assignUser — APPROVED** [review]
+1

**Pull request merged**
