### PR TITLE
ARROW-7778: [Integration][C++] Enable nested dictionaries

### PR DESCRIPTION
**Pull request by pitrou**

### CODE REVIEW

**Comment by pitrou** [comment]
@wesm I would like your high-level opinion on this. With this PR, we can decode nested dictionaries if inner dictionaries are serialized before outer dictionaries on the IPC stream. This seems like a reasonable requirement to me, but of course it isn't spelled out in the format spec.

**Comment by pitrou** [comment]
Or should I ask on the ML?

**Comment by wesm** [comment]
Let's bring it up on the ML. Seems a reasonable requirement to me.

**Review by wesm — APPROVED** [review]
+1. I think we can return later and deal with the dictionaries-out-of-order issue later when it comes up

**Pull request closed without merging**
