### PR TITLE
ARROW-7692: [Rust] Simplify some Option / Result pattern matches

### PR DESCRIPTION
**Pull request by huitseeker**
Opinions on this loosely held, happy to accomodate review.

### CODE REVIEW

**Review by paddyhoran — APPROVED** [review]
LGTM, thanks @huitseeker

**Review by andygrove — APPROVED** [review]

**Comment by paddyhoran** [comment]
@andygrove can you assign this issue to @huitseeker on JIRA so it can be merged?  I used to be able to change permissions on JIRA but I seem to have lost it.

**Comment by kszucs** [comment]
@paddyhoran as a committer you should be able to assign users to the Contributors role in jira.

**Review by kszucs — APPROVED** [review]
Thanks @huitseeker!

**Pull request closed without merging**
