### PR TITLE
GH-37072: [C++] GetArrayView: allow non-nullable fields to be null if parent is null

### LINKED ISSUE #37072: null structarrays are poorly handled by cast
### Describe the bug, including details regarding any error messages, version, and platform.

This code should work:
```py
import pyarrow as pa
struct_type = pa.struct([pa.field("x", pa.int32(), nullable=False)])
nulls = pa.nulls(5, struct_type)

# The following is an error:
nulls = nulls.cast(struct_type)
```

The error message is:
```
ArrowInvalid: Can't view array of type struct<x: int32 not null> as struct<x: int32 not null>: nulls in input cannot be viewed as non-nullable
```

Indeed, if we `print(nulls)`, it contains null values in the non-nullable field `x`:
```
-- is_valid:
  [
    false,
    false,
    false,
    false,
    false
  ]
-- child 0 type: int32
  [
    null,
    null,
    null,
    null,
    null
  ]
```

But those are all invalid at the top-level _anyway_, so there's no reason `cast` ought to care. Either that, or it should be impossible to call `pa.nulls` on a struct with a non-nullable field anywhere in its hierarchy of fields, but that seems wrong too. That would imply that if _any_ field is non-nullable then the whole struct would be non-nullable, which clearly is not the intent. You should be able to have a null struct with non-nullable fields.

Ultimately, this is a C++ issue; Python is merely calling those functions.

### Component(s)

C++

### PR DESCRIPTION
**Pull request by felipecrv**
### Rationale for this change

The layout constraint checks in `GetArrayView` are too strict when they don't allow  non-nullable STRUCT fields to be null since STRUCT fields can legally have any value when the parent `Array` describes the entry as not valid.

Reproduction script

```python
import pyarrow as pa

struct_type = pa.struct([pa.field("x", pa.int32(), nullable=False)])
nulls = pa.nulls(5, struct_type)

# The following is an error:
nulls.cast(struct_type)
```

### What changes are included in this PR?

Allow the execution of `GetArrayView` with nulls in non-nullable fields iff the parent `Array` is 100% null. To cover all cases, the checks would have to be done value by value, but that would be expensive. This PR covers the cases where STRUCT arrays are created by `MakeArrayOfNull`. Kernels producing STRUCTs with a few nulls might be wiser to set validity bits to 1 on non-nullable fields even when the parent is null.

### Are these changes tested?

By existing tests and manual reproduction script.
* Closes: #37072

### CODE REVIEW

**Comment by pitrou** [comment]
I'm honestly not sure this is the right solution. If a field is not nullable, then ideally it shouldn't have any nulls even if it is shadowed by an all-nulls parent array.

Other implementations may also not like receiving such data over IPC or the C Data Interface.

Also, in any case, this should come with unit tests!

**Comment by felipecrv** [comment]
> If a field is not nullable, then ideally it shouldn't have any nulls even if it is shadowed by an all-nulls parent array.

But what value should a field of a struct have when the entire struct is a logical null? Isn't that completely undefined and a waste of time to be populated?

**Comment by pitrou** [comment]
It's undefined but it needs to be populated anyway :-) (we can't leave memory uninitialized as it can be serialized through IPC, for example)

`MakeArrayOfNull` already assigns a buffer full of zeros to all array buffers.

**Comment by felipecrv** [comment]
> MakeArrayOfNull already assigns a buffer full of zeros to all array buffers.

But what you are asking for here requires a validity buffer set to `0xff` on the children and data buffers set to `0` or some type-specific notion of default value.

**Comment by pitrou** [comment]
Right, it would add a bit of complexity, hopefully not too much. Most types would probably be ok with `0xff` for all buffer data. Perhaps (list/binary/dense union) offsets and run-ends would better be zero, though?

**Comment by lidavidm** [comment]
> Other implementations may also not like receiving such data over IPC or the C Data Interface.

Practically I think implementations are not great about using the nullability flag, instead relying mostly on the physical presence of nulls, but this is a chicken-and-egg issue.

> If a field is not nullable, then ideally it shouldn't have any nulls even if it is shadowed by an all-nulls parent array.

This sounds reasonable, but we should clarify this more generally? It sounds like we aren't precise enough with that field nullability means for the physical data.

**Comment by pitrou** [comment]
> This sounds reasonable, but we should clarify this more generally? It sounds like we aren't precise enough with that field nullability means for the physical data.

Hmm, it seems like this could be discussed on the mailing-list. Perhaps we don't want to impose undue constraints here.

**Comment by felipecrv** [comment]
> Right, it would add a bit of complexity, hopefully not too much. Most types would probably be ok with 0xff for all buffer data. Perhaps (list/binary/dense union) offsets and run-ends would better be zero, though?

If we were to got that route we would have to define the "default value" for each type similar to how protobuf 3 is allowed to omit data and default values are assumed.

 - Boolean - `false`
 - Number - `0.0`
 - List - empty list (offsets would have to be 0 and not `0xffffffff`)
 - Unions - the default value of the first type

> > This sounds reasonable, but we should clarify this more generally? It sounds like we aren't precise enough with that field nullability means for the physical data.
> 
> Hmm, it seems like this could be discussed on the mailing-list. Perhaps we don't want to impose undue constraints here.

I vote in favor of not imposing constraints. This is why I don't think the way to go here is "fixing" `MakeArrayOfNull` but relaxing the constraint checking that's failing on per-spec valid data.

**Comment by pitrou** [comment]
We don't need to officially define "default values", just make sure we don't produce invalid data (such as non-monotonic offsets). This is exactly the idea behind `ArrayBuilder::AppendEmptyValue`:
https://github.com/apache/arrow/blob/d330d1b36c87ea43bfd16e1bc43a4ff9876abb4b/cpp/src/arrow/array/builder_base.h#L156-L161

But this discussion can also regard other implementations, I think it would be useful to discuss on the ML.

**Comment by alippai** [comment]
My only insight here is that nullability in nested types and the need of fast paths are causing non-trivial performance degradation in parquet serde. So if restricting some edge cases helps here, likely it’ll help in other code paths as well.

**Comment by felipecrv** [comment]
> But this discussion can also regard other implementations, I think it would be useful to discuss on the ML.

The discussion is needed if we decide to put the definition of empty value (a better terminology than "default value" I used above) on the spec. My current position is that validation should be relaxed and not assume other implementations are producing non-null fields inside null structs.

For instance, I believe that a compute kernel, in the official implementation or other implementations, should be allowed to skip producing empty values inside of null structs. This can be a very meaningful improvement for structs with a large number of fields.

**Comment by felipecrv** [comment]
> If we follow your position, other implementations will be exposed to such data. So they will be affected anyway.

All I'm saying is that we be liberal in data that we receive (relaxed checks). We can still be strict in `MakeArrayOfNull` but we shouldn't rely on everyone producing non-null values in struct fields.

Starting a whole specification refinement discussion takes much more time than I thought would be required from me to fix this issue. If the relaxed checks is not an acceptable solution, I can close the PR and move on.

**Comment by felipecrv** [comment]
> My only insight here is that nullability in nested types and the need of fast paths are causing non-trivial performance degradation in parquet serde. So if restricting some edge cases helps here, likely it’ll help in other code paths as well.

@alippai on the Arrow->Parquet or on the Parquet->Arrow path?

**Comment by alippai** [comment]
This was list specific and for the parquet->arrow path: https://github.com/apache/arrow/issues/34510

I’ve read this issue again and as I understand both of the solutions would serialize into exactly the same parquet? Not sure which version the parsing will yield

**Comment by felipecrv** [comment]
Closing this in favor of #38252

**Pull request closed without merging**
