### PR TITLE
ARROW-4339: [C++][Python] Developer documentation overhaul for 0.13 release

### PR DESCRIPTION
**Pull request by wesm**
This was pretty much a huge pain but addresses accumulated documentation debt after the conda compiler migration and the CMake refactor. I suggest we not stress too much over small details on this and do more work to improve these docs in follow up PRs. I did the best I could under the circumstances and need to move on to other things now

I think the overall organization of the Sphinx project for developers is much improved, take a look (I will post a link to a published version for review)

JIRAs addressed by this PR and other things I did

* Update cpp/thirdparty/README.md given CMake refactor (this was totally out of date). This now directs users to the Sphinx C++ developer guide

* ARROW-4339: Move cpp/README.md to Sphinx documentation (and clean it up a lot!!)
* ARROW-4425: Move Contributing Guidelines from Confluence to Sphinx, update top level README
* ARROW-4232: Remove references to pre-gcc5 ABI issues
* ARROW-4165: Move Windows C++ developer guide to Sphinx (from cpp/apidoc/Windows.md)
* ARROW-4547: Update Python development instructions re: producing CUDA-enabled pyarrow
* ARROW-4326 / ARROW-3096: Update Python build instructions re: January 2019 compiler migration

### CODE REVIEW

**Comment by wesm** [comment]
I published this to https://wesm.github.io/arrow-site-test/

See the "Development and Contributing" section and particularly the new "C++ Development" page which was the most time consuming thing

**Comment by wesm** [comment]
I'll fix the Doxygen failure and do a read through to fix any obvious issues.

**Comment by wesm** [comment]
OK, I'm satisfied with this. I'll merge once the build is green. We can continue to address documentation improvements in follow up patches, so feel free to review here (or submit separate PRs)

**Review by xhochy — COMMENTED** [review]
Thank you for doing this pass over the documentation. This should help users a lot.

**Pull request closed without merging**
