### PR TITLE
ARROW-6771: [Packaging][Python] Missing pytest dependency from conda and wheel builds

### PR DESCRIPTION
**Pull request by kszucs**

### CODE REVIEW

**Comment by kszucs** [comment]
@ursabot crossbow submit -g conda

**Comment by kszucs** [comment]
@ursabot crossbow submit -g conda -g wheel

**Comment by kszucs** [comment]
@ursabot crossbow submit wheel-win-cp35m wheel-win-cp36m wheel-win-cp37m

**Comment by kszucs** [comment]
@ursabot crossbow submit wheel-win-cp35m wheel-win-cp36m wheel-win-cp37m

**Review by pitrou — APPROVED** [review]
+1

**Comment by pitrou** [comment]
Looks like Python 3.5 failed building? Personally, I'd be fine with dropping Python 3.5 packages, but should be checked on the ML.

**Comment by wesm** [comment]
Looks like there is a pip dependency conflict. I would also recommend dropping Python 3.5 Windows packages; these are unlikely to be used by very many people nowadays

**Comment by kszucs** [comment]
Ok, dropping it.

**Review by wesm — APPROVED** [review]
+1

**Comment by keller00** [comment]
Hi,

I'd like to help getting `pyarrow==0.16.0` released for Windows Python 3.5.
I have seen the issue here: https://ci.appveyor.com/project/Ursa-Labs/crossbow/builds/27848124
I'm not familiar with your release build procedure, but I have been trying to follow https://github.com/apache/arrow/blob/master/docs/source/developers/python.rst#building-on-windows
Note that I have replaced:
```
conda create -y -n pyarrow-dev -c conda-forge ^
    --file arrow\ci\conda_env_cpp.yml ^
    --file arrow\ci\conda_env_python.yml ^
    --file arrow\ci\conda_env_gandiva.yml ^
    python=3.7
```
with
```
conda create -y -n pyarrow-dev -c conda-forge ^
    --file arrow\ci\conda_env_cpp.yml ^
    --file arrow\ci\conda_env_python.yml ^
    --file arrow\ci\conda_env_gandiva.yml ^
    python=3.5
```
I also had to update `Cython` manually and that `python setup.py build_ext --inplace` seemed to do nothing, so I tried doing `pip wheel -w dist .` and this successfully built a wheel file for me.

I understand that `ursabot` is down, but when it comes back could you retry building the missing wheel?

If I am wrong about the build procedure please let me know, I'm really unfamiliar with Windows development.

**Comment by wesm** [comment]
@keller00 can we discuss on the mailing list or a new JIRA issue about this? Thanks

**Pull request closed without merging**
