### PR TITLE
ARROW-6358: [C++] Add FileSystem::DeleteDirContents

### PR DESCRIPTION
**Pull request by pitrou**

### CODE REVIEW

**Comment by pitrou** [comment]
Another possibility would be to expose two methods: `DeleteDir` (or `DeleteDirTree`) and `DeleteDirContents`.

**Comment by xhochy** [comment]
I would rather expose two methods as the function implementation can be completely different depending on the flag value.

**Comment by pitrou** [comment]
@xhochy Thanks, done.

**Review by xhochy — APPROVED** [review]

**Review by kou — APPROVED** [review]
+1

**Pull request closed without merging**
