### PR TITLE
PARQUET-1698: [C++] pre buffer whole row group

### PR DESCRIPTION
**Pull request by czxrrr**
Just a draft in order to gather advises.
@majetideepak

### CODE REVIEW

**Comment by wesm** [comment]
@czxrrr @lidavidm @pitrou per the mailing list discussion regarding read coalescing, I would propose that we implement a single feature where the user declares column indices to prebuffer, rather than having a separate feature to buffer the whole row group (since this is the special case where we "prebuffer all columns" and thus these are coalesced into a single big read). Does that sound reasonable?

**Comment by lidavidm** [comment]
@wesm yes, that makes sense. We can continue to work out how that actually gets implemented and how that gets exposed to Datasets. I've been a bit behind, else I'd draft some APIs or an implementation.

**Comment by wesm** [comment]
Also, it seems like externalizing IO scheduling in Parquet is a separate project somewhat orthogonal to this one

**Comment by pitrou** [comment]
@wesm That sounds reasonable as well, but I'm not very knowledgeable on Parquet.

**Comment by wesm** [comment]
Closing in favor of #6744

**Pull request closed without merging**
