### PR TITLE
ARROW-6522: [Python] Fix failing pandas tests on older pandas / older python

### PR DESCRIPTION
**Pull request by jorisvandenbossche**
https://issues.apache.org/jira/browse/ARROW-6522

### CODE REVIEW

**Comment by kszucs** [comment]
LGTM. I will submit a crossbow build with the nopandas tasks.

**Comment by kszucs** [comment]
@ursabot crossbow submit appveyor-wheel-win-cp35m

**Comment by kszucs** [comment]
@ursabot crossbow submit wheel-win-cp35m

**Comment by jorisvandenbossche** [comment]
OK, some other test is failing as well .. Let me take a look

**Comment by jorisvandenbossche** [comment]
@ursabot crossbow submit wheel-win-cp35m

**Review by pitrou — APPROVED** [review]
LGTM

**Comment by jorisvandenbossche** [comment]
The crossbow build is green now, so this should be good to go.

**Comment by pitrou** [comment]
Travis-CI: https://travis-ci.org/jorisvandenbossche/arrow/builds/583645736

**Pull request closed without merging**
