### PR TITLE
ARROW-6656: [Rust][Datafusion] Add MAX, MIN expressions

### PR DESCRIPTION
**Pull request by alippai**
This is a naive implementation, just copy-paste, may need some refactor :)

### CODE REVIEW

**Comment by andygrove** [comment]
@alippai please rebase

**Review by andygrove — COMMENTED** [review]
LGTM. Will approve once rebased. Thanks!

It would be possibly to refine these macros to be shared between MIN and MAX and pass in the comparison op but given there are only two cases I'm not sure it's worth the additional complexity.

**Review by andygrove — APPROVED** [review]
I went ahead and rebased this and fixed the conflict. LGTM pending CI.

**Comment by alippai** [comment]
Thank you, I wouldn't have time before Monday evening, you are the best!

**Comment by andygrove** [comment]
Needs rebasing again after merging another PR to master .... I will take care of it tonight and got both these PRs merged this weekend.

**Pull request closed without merging**
