### PR TITLE
GH-43194: [R] R_existsVarInFrame isn't available earlier than R 4.2

### LINKED ISSUE #43194: [R] `R_existsVarInFrame` isn't available earlier than R 4.2
### Describe the bug, including details regarding any error messages, version, and platform.

In #43173 we switched to using `R_existsVarInFrame` instead of `Rf_findVarInFrame3`, but `R_existsVarInFrame` isn't available before R 4.2, so we will need to do something to switch on this. 

### Component(s)

R

### PR DESCRIPTION
**Pull request by jonkeane**
### Rationale for this change

`R_existsVarInFrame` doesn't exist before R 4.2, so we need to fall back to `Rf_findVarInFrame3` if it is not defined.

Resolves #43194

### What changes are included in this PR?

`ifdef`s

### Are these changes tested?

Yes, in our extended CI `test-r-versions`, `test-r-rstudio-r-base-4.1-opensuse155`

### Are there any user-facing changes?

No

* GitHub Issue: #43194

### CODE REVIEW

**Comment by jonkeane** [comment]
@github-actions crossbow submit test-r-versions

**Comment by jonkeane** [comment]
@github-actions crossbow submit test-r-rstudio-r-base-4.1-opensuse155 r-binary-packages

**Comment by thisisnic** [comment]
crossbow submit test-r-versions

**Comment by thisisnic** [comment]
@github-actions crossbow submit test-r-versions

**Review by thisisnic — APPROVED** [review]
Looks good; I see the job failing on the nightlies but passing above after this change here.  

Do we want to cherry-pick this into the release?

**Pull request merged**
