### PR TITLE
ARROW-7611: [Packaging][Python] Fix artifacts patterns for wheel

### PR DESCRIPTION
**Pull request by kou**
See the followings for real artifact names:

  * https://github.com/ursa-labs/crossbow/releases/tag/nightly-2020-01-17-0-travis-wheel-osx-cp38
  * https://github.com/ursa-labs/crossbow/releases/tag/nightly-2020-01-17-0-appveyor-wheel-win-cp38

### CODE REVIEW

**Comment by nealrichardson** [comment]
If the artifacts are already there, what does this fix? Or put differently, what is broken?

**Comment by kou** [comment]
If these patterns aren't match, `crossbow download-artifacts` doesn't download uploaded artifacts (`pyarrow-0.15.0.dev606-cp38-cp38-macosx_10_9_x86_64.whl` and ``pyarrow-0.15.0.dev606-cp38-cp38m-win_amd64.whl`).
It means that we will not release them to Bintray (and PyPI) in release process.

**Comment by kou** [comment]
@ursabot crossbow submit wheel-osx-cp38 wheel-win-cp38

**Comment by kou** [comment]
`crossbow download-artifacts nightly-2020-01-19-0` doesn't download `wheel-win-cp38/*.whl` and `wheel-osx-cp38/*.whl` but
`crossbow download-artifacts ursabot-439` downloads them.

**Comment by kou** [comment]
BTW, I think that maintenance cost of `artifacts` in `dev/tasks/tasks.yml` is high for use. So I think that removing it and changing to download all uploaded files are better.

**Review by kszucs — APPROVED** [review]

**Comment by kszucs** [comment]
@kou created a jira for your proposal https://issues.apache.org/jira/browse/ARROW-7619

**Comment by kou** [comment]
Thanks!

**Pull request closed without merging**
