### PR TITLE
[Packaging][Python] Link brotli statically in the windows wheels

### PR DESCRIPTION
**Pull request by kszucs**

### CODE REVIEW

**Comment by kszucs** [comment]
@github-actions crossbow submit wheel-win-cp37m

**Comment by wesm** [comment]
I'm pretty confident you're going to have to restore -DBUILD_SHARED_LIBS=OFF to the brotli_ep build

**Comment by wesm** [comment]
@github-actions crossbow submit wheel-win-cp37m

**Comment by kszucs** [comment]
I think if we link brotly dinamically than we need to bundle the dll in pyarrow/cmakelist and setup.py into the wheel, so my original plan was to link it statically.

**Comment by wesm** [comment]
Take a closer look at the brotli_ep build

https://github.com/apache/arrow/blob/master/cpp/cmake_modules/ThirdpartyToolchain.cmake#L877

When you use `-DBrotli_SOURCE=BUNDLED`, it uses the static libraries regardless of whether `ARROW_BROTLI_USE_SHARED` is set or not. So the linking error that's happening must be caused by something else

**Comment by wesm** [comment]
@github-actions crossbow submit wheel-win-cp37m

**Comment by wesm** [comment]
I think part of the issue is that brotli is being installed by conda so this iteration will hopefully fix it

**Comment by wesm** [comment]
OK based on reading https://github.com/google/brotli/pull/655 unfortunately it appears that the conda-forge Brotli static libraries are broken on Windows. I'll open a ticket for that feedstock

**Comment by wesm** [comment]
@github-actions crossbow submit wheel-win-cp37m

**Comment by wesm** [comment]
@github-actions crossbow submit wheel-win-cp37m

**Comment by wesm** [comment]
I don't believe that Brotli is what's causing the linking problem

**Comment by wesm** [comment]
Closing this. Brotli is not the problem

**Pull request closed without merging**
