### PR TITLE
ARROW-17927: [C++] Avoid hitting thread limits in stress tests

### PR DESCRIPTION
**Pull request by pitrou**
Non-trivial use of SleepAsync() and SleepABitAsync() could end up running hundreds of threads at once, which could hit resource limits on some CI configurations.

The solution is unfortunately complicated for what it does, which is enforcing a maximum number of concurrently running async-sleeping threads.

### CODE REVIEW

**Comment by pitrou** [comment]
Revision: 2fd74d02216de0c8c05cbb496faa74fe20fdf47a

Submitted crossbow builds: [ursacomputing/crossbow @ thread-async-sleep-0](https://github.com/ursacomputing/crossbow/branches/all?query=thread-async-sleep-0)

|Task|Status|
|----|------|
|test-alpine-linux-cpp|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:thread-async-sleep-0-github-test-alpine-linux-cpp)|
|test-build-cpp-fuzz|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:thread-async-sleep-0-github-test-build-cpp-fuzz)|
|test-conda-cpp|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:thread-async-sleep-0-github-test-conda-cpp)|
|test-conda-cpp-valgrind|[Azure](https://dev.azure.com/ursacomputing/crossbow/_build/latest?definitionId=1&branchName=thread-async-sleep-0-azure-test-conda-cpp-valgrind)|
|test-debian-10-cpp-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:thread-async-sleep-0-github-test-debian-10-cpp-amd64)|
|test-debian-10-cpp-i386|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:thread-async-sleep-0-github-test-debian-10-cpp-i386)|
|test-debian-11-cpp-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:thread-async-sleep-0-github-test-debian-11-cpp-amd64)|
|test-debian-11-cpp-i386|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:thread-async-sleep-0-github-test-debian-11-cpp-i386)|
|test-fedora-35-cpp|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:thread-async-sleep-0-github-test-fedora-35-cpp)|
|test-ubuntu-18.04-cpp|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:thread-async-sleep-0-github-test-ubuntu-18.04-cpp)|
|test-ubuntu-18.04-cpp-release|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:thread-async-sleep-0-github-test-ubuntu-18.04-cpp-release)|
|test-ubuntu-18.04-cpp-static|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:thread-async-sleep-0-github-test-ubuntu-18.04-cpp-static)|
|test-ubuntu-20.04-cpp|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:thread-async-sleep-0-github-test-ubuntu-20.04-cpp)|
|test-ubuntu-20.04-cpp-17|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:thread-async-sleep-0-github-test-ubuntu-20.04-cpp-17)|
|test-ubuntu-20.04-cpp-bundled|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:thread-async-sleep-0-github-test-ubuntu-20.04-cpp-bundled)|
|test-ubuntu-20.04-cpp-thread-sanitizer|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:thread-async-sleep-0-github-test-ubuntu-20.04-cpp-thread-sanitizer)|
|test-ubuntu-22.04-cpp|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:thread-async-sleep-0-github-test-ubuntu-22.04-cpp)|

**Comment by pitrou** [comment]
@github-actions crossbow submit test-ubuntu-20.04-cpp-17

**Comment by pitrou** [comment]
@github-actions crossbow submit test-ubuntu-20.04-cpp-17

**Comment by pitrou** [comment]
For some reason, test-ubuntu-20.04-cpp-17 timed out twice in a row, then passed twice in a row. Other tests seem fine.

**Comment by lidavidm** [comment]
(I wish we could get a thread dump in cases like these…)

**Comment by pitrou** [comment]
Right. I've tried to reproduce locally but failed.

**Review by lidavidm — APPROVED** [review]

**Comment by pitrou** [comment]
Revision: af50bd348d630d5ed8909e23a46be756f527d3db

Submitted crossbow builds: [ursacomputing/crossbow @ thread-async-sleep2-0](https://github.com/ursacomputing/crossbow/branches/all?query=thread-async-sleep2-0)

|Task|Status|
|----|------|
|test-alpine-linux-cpp|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:thread-async-sleep2-0-github-test-alpine-linux-cpp)|
|test-build-cpp-fuzz|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:thread-async-sleep2-0-github-test-build-cpp-fuzz)|
|test-conda-cpp|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:thread-async-sleep2-0-github-test-conda-cpp)|
|test-conda-cpp-valgrind|[Azure](https://dev.azure.com/ursacomputing/crossbow/_build/latest?definitionId=1&branchName=thread-async-sleep2-0-azure-test-conda-cpp-valgrind)|
|test-debian-10-cpp-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:thread-async-sleep2-0-github-test-debian-10-cpp-amd64)|
|test-debian-10-cpp-i386|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:thread-async-sleep2-0-github-test-debian-10-cpp-i386)|
|test-debian-11-cpp-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:thread-async-sleep2-0-github-test-debian-11-cpp-amd64)|
|test-debian-11-cpp-i386|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:thread-async-sleep2-0-github-test-debian-11-cpp-i386)|
|test-fedora-35-cpp|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:thread-async-sleep2-0-github-test-fedora-35-cpp)|
|test-ubuntu-18.04-cpp|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:thread-async-sleep2-0-github-test-ubuntu-18.04-cpp)|
|test-ubuntu-18.04-cpp-release|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:thread-async-sleep2-0-github-test-ubuntu-18.04-cpp-release)|
|test-ubuntu-18.04-cpp-static|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:thread-async-sleep2-0-github-test-ubuntu-18.04-cpp-static)|
|test-ubuntu-20.04-cpp|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:thread-async-sleep2-0-github-test-ubuntu-20.04-cpp)|
|test-ubuntu-20.04-cpp-17|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:thread-async-sleep2-0-github-test-ubuntu-20.04-cpp-17)|
|test-ubuntu-20.04-cpp-bundled|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:thread-async-sleep2-0-github-test-ubuntu-20.04-cpp-bundled)|
|test-ubuntu-20.04-cpp-thread-sanitizer|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:thread-async-sleep2-0-github-test-ubuntu-20.04-cpp-thread-sanitizer)|
|test-ubuntu-22.04-cpp|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:thread-async-sleep2-0-github-test-ubuntu-22.04-cpp)|

**Comment by pitrou** [comment]
Trying an alternate approach in #14334. The main question being whether it'll work on Windows.

**Comment by pitrou** [comment]
Closing in favor of #14339.

**Pull request closed without merging**
