### PR TITLE
ARROW-8568: [C++] Fix decimal to decimal cast issues

### PR DESCRIPTION
**Pull request by pitrou**
- Allow same-scale casts
- Detect truncation when target precision is too small

### CODE REVIEW

**Comment by wesm** [comment]
The rebase headache of this should not be good bad, FWIW. Working furiously to refactor things...

**Comment by pitrou** [comment]
Woops, sorry, I had forgotten about the refactor. But, yeah, the changes are quite localized here.

**Comment by wesm** [comment]
No problem. I've been burning the midnight oil this week so it shouldn't delay too much longer

**Comment by pitrou** [comment]
I'm rebasing this.

**Comment by pitrou** [comment]
@wesm Would you like to validate the codegen additions here?

**Comment by wesm** [comment]
Yes will do

**Review by wesm — APPROVED** [review]
+1. Thank you for doing this refactoring, looks good

**Pull request closed without merging**
