### PR TITLE
ARROW-15442: [C++][Python] Skip GDB tests on a non-debug build

### PR DESCRIPTION
**Pull request by pitrou**
Even though the GDB extension should theoretically work with a release build, it's difficult to test for, as we can't lookup any variables from the GDB prompt.

### CODE REVIEW

**Comment by pitrou** [comment]
@github-actions crossbow submit -g python

**Comment by kszucs** [comment]
Can we remove the `PYARROW_TEST_GDB=OFF` flags from #12243 once this is merged?

**Comment by pitrou** [comment]
If these are all non-debug builds, then probably, yes.

**Comment by kszucs** [comment]
@github-actions crossbow submit wheel-macos-big-sur-*

**Comment by kszucs** [comment]
@pitrou shouldn't [FileNotFoundError: [Errno 2] No such file or directory: 'gdb'](https://github.com/ursacomputing/crossbow/runs/4938407207?check_suite_focus=true#step:11:4560) like errors be prevented by https://github.com/apache/arrow/blob/master/python/pyarrow/tests/test_gdb.py#L163 ?

**Comment by pitrou** [comment]
@kszucs It should :-(

**Comment by pitrou** [comment]
Hmm, I get the impression that `subprocess` may be using two slightly different approaches based on the exact arguments. I'll try to push a fix.

**Comment by pitrou** [comment]
Crossbow builds at https://github.com/ursacomputing/crossbow/branches/all?query=pitrou-1

**Comment by pitrou** [comment]
Also triggered Linux packaging Crossbow builds: https://github.com/ursacomputing/crossbow/branches/all?query=pitrou-3

**Comment by kszucs** [comment]
The builds are failing due to an unrelevant issue https://issues.apache.org/jira/browse/ARROW-15453

**Review by kszucs — APPROVED** [review]
Thanks Antoine!

**Pull request closed without merging**
