### PR TITLE
ARROW-3445: [GLib] Fix libarrow-glib link for libparquet-glib

### PR DESCRIPTION
**Pull request by kou**

### CODE REVIEW

**Comment by kszucs** [comment]
It went further, but it misses orc now https://gist.github.com/kszucs/a272080f512bd52a31fb13e6cd623ee1

**Comment by wesm** [comment]
Are the binary packages affected by this?

**Comment by kszucs** [comment]
AFAIK We don't have c_glib binaries for OSX

**Review by wesm — APPROVED** [review]
+1

**Comment by kou** [comment]
@kszucs Thanks for confirming it but the failure is unrelated. Because the original `CXXLD libparquet-glib.la` failure is built after `GISCAN Arrow-1.0.gir` and the `GISCAN Arrow-1.0.gir` worked well. So I think that the build just missedd something. (environment variable?)

**Comment by kou** [comment]
I've confirmed this change fix this case on macOS.

**Comment by kszucs** [comment]
Thanks @kou !

**Pull request closed without merging**
