### PR TITLE
PARQUET-1571: [C++] Fix BufferedInputStream when buffer exactly exhausted

### PR DESCRIPTION
**Pull request by pitrou**
Rework the BufferedInputStream implementation to make internal semantics more apparent.

### CODE REVIEW

**Comment by pitrou** [comment]
Note the PR contains potential performance improvements, though it depends exactly how `BufferedInputStream` is used.

**Review by xhochy — APPROVED** [review]
+1, LGTM

**Comment by wesm** [comment]
Note that for a while I've been wanting to consolidate the IO interfaces to not have "special" ones for Parquet, and use the same ones everywhere in both the Arrow and Parquet codebases. I may be able to spend some time on this after I am done with some of the initial variable dictionary stuff

**Comment by pitrou** [comment]
AppVeyor build at https://ci.appveyor.com/project/pitrou/arrow/builds/24396912

**Review by wesm — APPROVED** [review]
+1. I'm surprised this hasn't been an issue until now (cc @majetideepak)

**Pull request closed without merging**
