### PR TITLE
[Release] Verify 7.0.0 RC5 [WIP]

### PR DESCRIPTION
**Pull request by kszucs**
Source verification tasks: https://github.com/ursacomputing/crossbow/branches/all?query=build-599

### CODE REVIEW

**Comment by kszucs** [comment]
@github-actions crossbow submit --group verify-rc-source --param release=7.0.0 --param rc=5

**Comment by kszucs** [comment]
@github-actions crossbow submit -g verify-rc-binaries -g verify-rc-jars -g verify-rc-wheels --param release=7.0.0 --param rc=5

**Comment by ianmcook** [comment]
@github-actions crossbow submit verify-rc-wheels-windows

**Comment by kszucs** [comment]
Closing in favor of https://github.com/apache/arrow/pull/12235

**Pull request closed without merging**
