### PR TITLE
GH-37359: [C#] Add ToList() to Decimal128Array and Decimal256Array

### LINKED ISSUE #37359: [C#] Add ToList() to Decimal128Array and Decimal256Array
### Describe the enhancement requested

Add `ToList()` methods to `Decimal128Array` and `Decimal256Array` that function similarly to `PrimitiveArray.ToList()`.

### Component(s)

C#

### PR DESCRIPTION
**Pull request by DanTm99**
Add `ToList()` methods to `Decimal128Array` and `Decimal256Array`.

* Closes: #37359

### CODE REVIEW

**Comment by DanTm99** [comment]
@westonpace

**Comment by CurtHagenlocher** [comment]
@DanTm99 I'm curious whether you find useful to option to specify includeNulls=false. I recognize that it already exists for PrimitiveArray and think that API consistency is a valuable property, but at the same time I wonder about the kind of scenarios where this would be used.

If Decimal128Array and Decimal256Array were to implement IReadOnlyList<decimal?> and ICollection<decimal?> -- allowing efficient use of LINQ ToList() -- would that meet your use case?

**Comment by DanTm99** [comment]
@CurtHagenlocher yes, the use case I had for this would even be met by `Decimal128Array` and `Decimal256Array` just implementing `IEnumerable<decimal?>`, as all I need to do is use them with LINQ.

The reason I just added these `ToList()` methods was because it would meet my use case while also making the classes more consistent with `PrimitiveArray<T>`.

However, implementing `IReadOnlyList<decimal?>` and ICollection<decimal?>` should be done as part of a separate change, as this change was moreso to bring more consistency to this API.

**Comment by DanTm99** [comment]
@westonpace @CurtHagenlocher Conflict resolved. Ready to review.

**Review by CurtHagenlocher — APPROVED** [review]

**Pull request merged**
