### PR TITLE
MINOR: [Python][Doc] Added sort example to docs

### PR DESCRIPTION
**Pull request by tdunning**
I added an example to the docs, but wasn't exactly clear where the doc string for sort_indices came from. That  doc string could use a description of how sort_keys are used and a reference to take()

Is compute.cpp the right place to make changes? If so, I am happy to update this pull request to add more info.

### CODE REVIEW

**Comment by pitrou** [comment]
The docstrings are maintained as `FunctionDoc` objects in C++. Here is the one for `sort_indices`:
https://github.com/apache/arrow/blob/master/cpp/src/arrow/compute/kernels/vector_sort.cc#L1624

Then we have some Python machinery to generate descriptions for the various function parameters.

**Review by pitrou — APPROVED** [review]
Looks good to me, thank you.

**Comment by tdunning** [comment]
Antoine,

Is that the right place to push more information about how the Python
arguments work specifically?

**Comment by pitrou** [comment]
@tdunning If it's Python-specific then no.

**Review by cyb70289 — APPROVED** [review]
LGTM, +1
Thanks @tdunning

**Pull request closed without merging**
