### PR TITLE
ARROW-2239: [C++] Update Windows build docs

### PR DESCRIPTION
**Pull request by pitrou**
Recommend Ninja and clcache.

### CODE REVIEW

**Comment by pitrou** [comment]
@MaxRis does this look to you? I didn't want to switch the debug build instructions to Ninja as I haven't tested that works :-)

**Comment by MaxRis** [comment]
@pitrou looks great! Thank you!

**Review by xhochy — APPROVED** [review]
+1, LGTM

**Review by wesm — APPROVED** [review]
+1, thanks @pitrou!

**Pull request closed without merging**
