### PR TITLE
ARROW-17010: [Python] Remove deprecated APIs from <= 1.0.0 (top-level ipc, Value scalar classes, pyarrow.compat module)

### PR DESCRIPTION
**Pull request by jorisvandenbossche**
A first set of easy removals of deprecated functions / classes in the top-level namespace and the `pyarrow.compat` module.

### CODE REVIEW

**Review by pitrou — APPROVED** [review]

**Comment by pitrou** [comment]
@github-actions crossbow submit -g cpp

**Comment by pitrou** [comment]
Ouch, I didn't schedule the right Crossbow builds. My bad :-(

**Comment by pitrou** [comment]
@github-actions crossbow submit -g python

**Comment by jorisvandenbossche** [comment]
Thanks, should have thought about triggering all our nightly python / integration builds

**Pull request merged**
