### PR TITLE
GH-44222: [C++][Gandiva] Accept LLVM 19.1

### PR DESCRIPTION
**Pull request by kou**
### Rationale for this change

LLVM 19.1.0 was released.

### What changes are included in this PR?

Accept LLVM 19.1.0.

### Are these changes tested?

Yes.

### Are there any user-facing changes?

Yes.
* GitHub Issue: apache/arrow#44222
* GitHub Issue: #44222

### CODE REVIEW

**Comment by kou** [comment]
@github-actions crossbow submit -g cpp

**Comment by kou** [comment]
@github-actions crossbow submit java-jars

**Comment by kou** [comment]
+1

AppVeyor failure is GH-44234.

**Comment by vibhatha** [comment]
@kou I recently disabled some tests in Gandiva because of the issue mentioned here https://github.com/apache/arrow/issues/43981

Do you think re-enabling and testing would be a feasible idea with this change? 

cc @lidavidm

**Comment by lidavidm** [comment]
> @kou I recently disabled some tests in Gandiva because of the issue mentioned here #43981
> 
> Do you think re-enabling and testing would be a feasible idea with this change?
> 
> cc @lidavidm

Let's just leave it IMO, I hope the Gandiva maintainers can step back up to reenable the tests

**Comment by kou** [comment]
We can work on re-enabling them as a separated PR.
This can fix existing CI failures.

I'll merge this.

**Pull request merged**
