### PR TITLE
ARROW-11482: [Rust] improve take kernel performance of PrimitiveArray<T>

### PR DESCRIPTION
**Pull request by ritchie46**
This PR simplifies the `take_primitive` a little bit and increases performance by using the new `from_trusted_len_iterator` API.

```
take i32 512            time:   [678.68 ns 692.27 ns 709.58 ns]                          
                        change: [-11.636% -10.615% -9.2359%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 15 outliers among 100 measurements (15.00%)
  5 (5.00%) high mild
  10 (10.00%) high severe

take i32 1024           time:   [1.1393 us 1.1477 us 1.1637 us]                           
                        change: [-18.397% -17.829% -17.075%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 9 outliers among 100 measurements (9.00%)
  1 (1.00%) low mild
  3 (3.00%) high mild
  5 (5.00%) high severe

take i32 nulls 512      time:   [643.87 ns 644.11 ns 644.37 ns]                                
                        change: [-20.604% -20.531% -20.458%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 13 outliers among 100 measurements (13.00%)
  2 (2.00%) low mild
  6 (6.00%) high mild
  5 (5.00%) high severe

take i32 nulls 1024     time:   [1.1381 us 1.1384 us 1.1387 us]                                 
                        change: [-19.419% -19.054% -18.753%] (p = 0.00 < 0.05)
                        Performance has improved.
```

### CODE REVIEW

**Comment by jorgecarleitao** [comment]
Thanks @ritchie46 !

Note that this collides with #9301 .

**Comment by ritchie46** [comment]
> Thanks @ritchie46 !
> 
> Note that this collides with #9301 .

Right, great work on that PR! :) Then I will close this one.

I am also working on a perf increase of take_string. That one doesn't have collisions I presume?

**Comment by jorgecarleitao** [comment]
> Right, great work on that PR! :) Then I will close this one.

Thanks! :)

> I am also working on a perf increase of take_string. That one doesn't have collisions I presume?

No collisions, just go ahead and ping me if you need any help or a review. Note that there may be out-of-bound reads on that code. It would be awesome if those were taken care of :)

**Comment by ritchie46** [comment]
> Note that there may be out-of-bound reads on that code. It would be awesome if those were taken care of :)

Ah, right so we want to `panic` if we have out-of-bounds access even if `check-bounds == false`. There are quite some cases where I know upfront that all my indexes will be valid. Should we also expose an unsafe variant of the take kernels? Especially in groupby and join operations their performance is paramount.

**Comment by jorgecarleitao** [comment]
in my experiments leading to #9301 I found no significant perf different between both variants and so did not consider an `unsafe` version, I admit that since the PR already offered a -30%, I also did not bother much ^_^

once all our implementations are `safe`, IMO we should get rid of the take options and potentially offer an `unsafe` version like you said. What imo is not cool is having an implementation whose safety depends on a parameter. :P

**Comment by ritchie46** [comment]
>  I admit that since the PR already offered a -30%, I also did not bother much ^_^

LOL.. That I can imagine. 

> What imo is not cool is having an implementation whose safety depends on a parameter. :P

Agreed. I must say that I really notice the public API getting more idiomatic as well. It feels good to be able to use iterators for the fastest implementation!

**Pull request closed without merging**
