### PR TITLE
ARROW-5674: [Python] Missing pandas pytest markers from test_parquet.py

### PR DESCRIPTION
**Pull request by kszucs**

### CODE REVIEW

**Comment by kszucs** [comment]
@ursabot crossbow test docker-python-3.6-nopandas docker-python-3.7-nopandas

**Comment by kszucs** [comment]
@ursabot crossbow test docker-python-3.6-nopandas docker-python-3.7-nopandas

**Comment by kszucs** [comment]
@ursabot crossbow test docker-python-3.6-nopandas docker-python-2.7-nopandas

**Comment by wesm** [comment]
failing due to hadolint

```
Docker Format............................................................Failed
hookid: hadolint
r/Dockerfile:30 DL3027 Do not use apt as it is meant to be a end-user tool, use apt-get or apt-cache instead
c_glib/Dockerfile:33 DL3028 Pin versions in gem install. Instead of `gem install <gem>` use `gem install <gem>:<version>`
```

Aside: hadolint is not part of the lint docker-compose setup https://issues.apache.org/jira/browse/ARROW-5677

**Comment by kszucs** [comment]
@wesm just pushed a PR https://github.com/apache/arrow/pull/4650

**Review by wesm — APPROVED** [review]
+1

**Pull request closed without merging**
