### PR TITLE
ARROW-15526: [Python] Support for Dataset.join

### PR DESCRIPTION
**Pull request by amol-**

### CODE REVIEW

**Comment by alippai** [comment]
Does the join performance depend on which table is left or right? I assume we don't have statistics or optimizer at this point which is different from databases and might confuse the end users. (But I'm not sure about Pandas behavior here either)

**Comment by westonpace** [comment]
> Does the join performance depend on which table is left or right?

Yes.

> I assume we don't have statistics or optimizer at this point which is different from databases and might confuse the end users.

Correct.  We do not have these things and they can lead to easy creation of inefficient plans.

Figuring out query optimization is a big question and I don't know anyone tackling it at the moment.  Calcite looks good but it's a JVM technology so it would be a challenge to integrate.  For now, my working assumption in the C++ has been to assume we are given an optimized plan and execute it as literally as possible.  One semi-related discussion is ARROW-16172 (trying to figure out if the C++ should implicitly cast or reject a plan)

**Comment by alippai** [comment]
I think this is the good approach. Maybe adding a line to the python docs can help managing the expectations.

**Comment by amol-** [comment]
> I think this is the good approach. Maybe adding a line to the python docs can help managing the expectations.

I will definitely mention that as part of https://issues.apache.org/jira/browse/ARROW-16074 :+1:

**Comment by AlenkaF** [comment]
LGTM! 👍

**Review by AlenkaF — APPROVED** [review]

**Pull request closed without merging**
