### PR TITLE
ARROW-16387: [C++] Add -Wshorten-64-to-32 to list of CHECKIN warnings tested by clang

### PR DESCRIPTION
**Pull request by westonpace**

### CODE REVIEW

**Review by pitrou — APPROVED** [review]
+1, I agree this is a welcome improvement. By the way, does gcc have a similar flag?

**Review by lidavidm — APPROVED** [review]
It seems GCC doesn't support this flag. Looking around there's only the more general [-Wconversion](https://gcc.gnu.org/wiki/NewWconversion).

**Comment by pitrou** [comment]
`-Wconversion` is too broad in my experience.

**Comment by pitrou** [comment]
@github-actions crossbow submit -g cpp

**Pull request closed without merging**
