### PR TITLE
ARROW-10653: [Rust] Update toolchain nightly

### PR DESCRIPTION
**Pull request by vertexclique**
I have deployed new intrinsics to rust lang core, so I want to bring these in iterations.

### CODE REVIEW

**Review by nevi-me — APPROVED** [review]
Happy with change

**Review by alamb — APPROVED** [review]

**Comment by alamb** [comment]
This is cool -- though note I think there is a  broader effort afoot to remove the use of rust nightly in Arrow (e.g. https://github.com/apache/arrow/pull/8698)

So I suspect that any use of stuff in nightly rust will likely have to be feature gated to make this work. Just something to keep in mind if you want to introduce more use of such intrinsics into the arrow crates

**Comment by alamb** [comment]
For the record: https://github.com/rust-lang/rust/pull/79131 perhaps is perhaps the change to rustlang that @vertexclique  refers to

**Comment by alamb** [comment]
FYI @andygrove  and @jorgecarleitao

**Comment by jorgecarleitao** [comment]
Thanks a lot. LGTM. And as a side note: super cool @vertexclique that you are contributing to rust core! 😍

**Pull request closed without merging**
