### PR TITLE
ARROW-4315: [Website] Add Go and Rust to list of supported languages

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by wesm** [comment]
Yes, let's add C# and MATLAB also. There should be 11 languages total

**Comment by agrove-rms** [comment]
Updated to `C, C++, C#, Go, Java, JavaScript, MATLAB, Python, R, Ruby, and Rust`

**Review by wesm — APPROVED** [review]
+1. Would you like to have a go at updating the website?

**Comment by agrove-rms** [comment]
Yes, I'd like to. I'd like to start contributing some content to the website / blog in the future so would make sense to learn how to do this.

**Comment by wesm** [comment]
The instructions are in the README, it is not too difficult, but let me know if you run into issues. You can go ahead and merge this PR

**Pull request closed without merging**
