### PR TITLE
ARROW-10509: [C++] Define operator<<(ostream, ParquetException) for clang+Windows

### PR DESCRIPTION
**Pull request by xhochy**

### CODE REVIEW

**Comment by xhochy** [comment]
@github-actions submit conda-win-vs2017-py37

**Comment by xhochy** [comment]
@github-actions crossbow submit conda-win-vs2017-py37

**Comment by xhochy** [comment]
@github-actions crossbow submit conda-win-*

**Comment by xhochy** [comment]
This has been broken in the latest nightly builds of the `r-arrow` conda packages on Windows.

**Comment by xhochy** [comment]
@github-actions autotune everything

**Comment by xhochy** [comment]
Sorry for the close/open noise but otherwise Github Actions doesn't seem to start here.

**Review by bkietz — APPROVED** [review]
@xhochy LGTM but please add at least a line of description of the problem here/on JIRA before merging.

**Comment by xhochy** [comment]
@github-actions autotune everything

**Review by pitrou — APPROVED** [review]
+1

**Comment by pitrou** [comment]
The test failure is unrelated, will merge.

**Pull request closed without merging**
