### PR TITLE
MINOR: [Python] Make ARROW_DEBUG_MEMORY_POOL test more robust

### PR DESCRIPTION
**Pull request by pitrou**
When writing out of bounds and ARROW_DEBUG_MEMORY_POOL isn't set, the test subprocess may crash depending on the underlying allocator.

### CODE REVIEW

**Comment by pitrou** [comment]
@github-actions crossbow wheel-macos-*-arm64

**Comment by pitrou** [comment]
@github-actions crossbow submit wheel-macos-*-arm64

**Comment by pitrou** [comment]
@github-actions crossbow submit -g python -g wheel

**Comment by pitrou** [comment]
@github-actions crossbow submit wheel-macos-*-arm64

**Comment by pitrou** [comment]
@github-actions crossbow submit wheel-macos-*-arm64 wheel-macos-*-universal

**Comment by pitrou** [comment]
@github-actions crossbow submit wheel-macos-*arm64 wheel-macos-*universal*

**Comment by pitrou** [comment]
@github-actions crossbow submit wheel-macos-*arm64 wheel-macos-universal

**Comment by kszucs** [comment]
@github-actions crossbow submit wheel-macos-big-sur-*

**Comment by pitrou** [comment]
@github-actions crossbow submit wheel-macos-*arm64 wheel-macos-*universal2

**Comment by pitrou** [comment]
@github-actions crossbow submit wheel-macos-big-sur-*

**Comment by pitrou** [comment]
+1, will merge

**Pull request closed without merging**
