### PR TITLE
ARROW-7381: [C++] Unbreak manylinux1 wheels after Iterator refactor

### PR DESCRIPTION
**Pull request by bkietz**

### CODE REVIEW

**Comment by bkietz** [comment]
@ursabot --help

**Comment by bkietz** [comment]
@ursabot crossbow --help

**Comment by bkietz** [comment]
@ursabot crossbow submit --help

**Comment by bkietz** [comment]
@ursabot crossbow submit wheel-manylinux1-cp37m

**Review by kou — APPROVED** [review]
+1

**Pull request closed without merging**
