### PR TITLE
ARROW-2330: [C++] Optimize delta buffer creation with partially finishable array builders

### PR DESCRIPTION
**Pull request by alendit**

### CODE REVIEW

**Comment by xhochy** [comment]
What is the benefit of having ArrayBuilders that partly reset them versus just instantiating a new ArrayBuilder? I get it for the Dictionary case where keep state but for FixedSizeBinary I don't see the need to add such complexity.

**Comment by alendit** [comment]
Hi Uwe,

i was actually wondering the same thing myself. The reason I've implemented partial finishers for `FixedSizeBinaryBuilder` etc is that they are used by the `DictionaryBuilder` internally. I've tried to come up with a use case for the partial finishing for other builders, but, as you said, you can almost always simply instantiate a new one. Do you know why the `RecordBatchBuilder` has a partial `Flush` method? Is it because its instantion is more cumbersome compared to array builders?

That being said, I don't think that it adds that much complexity, compared to the previous implementation. Most of the changes are in the testing code, and builder files themselves have around 30 additional LOC. At the same time, it makes the `DictionaryBuilder` quite straight forward.

Maybe a compromise would be to hide the partial ´Finish´ methods for other classes besides `DictionaryBuilder` and make them friends with it? I'm not a big friend of `friend`, though.

**Comment by alendit** [comment]
Hi Uwe,

did you come to any conclusion as to if this PR is a go? I could either adjust it or we can scrap it all together and then I'll look into getting delta dicts into `Readers` and `Writers`.

Note: the test failure is unrelated to my changes, the cause was mentioned on the mailing list.

**Comment by xhochy** [comment]
Hello Dimitri,

I forgot to reply to you. This got drowned in all the other Arrow activity in the last days. Sorry about that.

> Do you know why the RecordBatchBuilder has a partial Flush method? Is it because its instantion is more cumbersome compared to array builders?

The `RecordBatchBuilder` is different to the other builders as it does not generate a Arrays but should be used for a more streaming-like output. In it, all builders are resetted on Flush. This is also the behaviour I would expect in the dictionary builder.
 
> That being said, I don't think that it adds that much complexity, compared to the previous implementation. Most of the changes are in the testing code, and builder files themselves have around 30 additional LOC. At the same time, it makes the DictionaryBuilder quite straight forward.

The added complexity is the thing that scares me most at the moment. The Builders are built with the intention that they complety own their buffers and can modify them as they like internally. You can ask them for snapshot access to elements to inspect them but we don't provide any guarantees that the memory addresses that were returned from them are still valid once you can a method on the builder again.

As far as I understand the current implementation in some cases we return the current buffer pointer as new `Buffer` object in the BufferBuilder. Once we do expand it though later on, we may free this memory address and thus the `Buffer` object point to unreachable memory.

**Comment by alendit** [comment]
Hi Uwe,

I see what you mean. Now that I've looked more carefully into `BufferSlices`, I see how much danger they can bear. Something like [this](https://gist.github.com/alendit/f759bc12e03d9dd9d72cac90a6334cc5) would cause a read-after-free. 

The problem, as I see it, is, that the SliceBuffer user has no way to ensure its validity. So even if we skip this PR, the problems with slices might happen in the future. I think some lean solution, like adding a `shared_ptr<Buffer> parent` to the slice and referencing its data instead, will increase the memory safety and might benefit this PR, too.

Do you think we should discuss it on the mailing list?

Cheers,
Dimitri.

**Comment by alendit** [comment]
Hi Uwe,

I've decided to close this PR until I have a better understanding of the possible issues with slices.

Cheers!

**Pull request closed without merging**
