### PR TITLE
ARROW-16247: [GLib] Add GArrowGCSFileSystem

### PR DESCRIPTION
**Pull request by kou**

### CODE REVIEW

**Comment by pitrou** [comment]
Hmm... this looks quite empty, are you planning to add support for GcsOptions? Or are people expected to instantiate these filesystems using an URI?

**Comment by kou** [comment]
> this looks quite empty, are you planning to add support for GcsOptions?

I'll add do it eventually but it's usable without this by #12763 (or #12932).

> Or are people expected to instantiate these filesystems using an URI?

Yes. We can load data by `Arrow::Table.load("gcs://bucket/a.arrow")` with this.  https://github.com/apache/arrow/blob/master/ruby/red-arrow-dataset/lib/arrow-dataset/arrow-table-loadable.rb#L38 instantiates `GArrowGCSFileSystem` and it's used to load data.

**Comment by pitrou** [comment]
Ok, so should there be a dedicated test?

**Comment by kou** [comment]
We can't implement now because `gcs://bucket/a.arrow` doesn't work without #12763.

**Comment by pitrou** [comment]
Ah, fair enough :-)

**Review by pitrou — APPROVED** [review]

**Pull request closed without merging**
