### PR TITLE
ARROW-6584: [Python][Wheel] Bundle zlib again with the windows wheels

### PR DESCRIPTION
**Pull request by kszucs**

### CODE REVIEW

**Comment by kszucs** [comment]
@ursabot crossbow submit wheel-win-cp37m

**Comment by pitrou** [comment]
Two questions:
* Do you remember why we removed this in the first place?
* Is it possible to use a virtualenv rather than a conda env when testing the wheel? AppVeyor should have the required [Python versions](https://www.appveyor.com/docs/windows-images-software/#python). This would avoid situations where a missing DLL is found in the conda env...

**Comment by kszucs** [comment]
> Two questions:
> 
> * Do you remember why we removed this in the first place?
To link zlib statically with the wheels, see https://github.com/apache/arrow/pull/4886
In the windows wheels ZLIB was linked dynamically despite `zlib_SOURCE=BUNDLED`.
> * Is it possible to use a virtualenv rather than a conda env when testing the wheel? AppVeyor should have the required [Python versions](https://www.appveyor.com/docs/windows-images-software/#python). This would avoid situations where a missing DLL is found in the conda env...
I guess so, but we should create a JIRA for investigating it.

**Comment by kszucs** [comment]
@ursabot crossbow submit -g wheel

**Comment by kszucs** [comment]
`wheel-osx-cp36m` has failed because of a transient travis deployment error.

**Comment by wesm** [comment]
BTW the fact that `-Dzlib_SOURCE=BUNDLED` does not produce a statically-linked binary on Windows seems buggy to me. https://issues.apache.org/jira/browse/ARROW-6587

**Review by wesm — APPROVED** [review]
+1

**Pull request closed without merging**
