### PR TITLE
ARROW-2285: [C++/Python] Can't convert Numpy string arrays

### PR DESCRIPTION
**Pull request by kszucs**

### CODE REVIEW

**Review by xhochy — COMMENTED** [review]
Can you add a test for unicode strings (i.e. `|U3`, …)? It does not need to pass but I want to be careful to not have some weird behaviour with it once we support `|S3`.

**Comment by kszucs** [comment]
@xhochy it raises due to byte length mismatch.

**Comment by xhochy** [comment]
@kszucs Yes, that is good. Can you fix the Python 2 error? Then this is ready to be merged.

**Review by pitrou — APPROVED** [review]

**Review by BryanCutler — APPROVED** [review]
LGTM

**Review by xhochy — APPROVED** [review]
+1, LGTM

**Pull request closed without merging**
