### PR TITLE
ARROW-10896: [C++][CMake] Rename internal RE2 package name to "re2" from "RE2"

### PR DESCRIPTION
**Pull request by kou**
Because upstream uses "re2". If we don't use different package name
such as "RE2", RE2 package is conflicted with other package that uses
RE2 such as gRPC.

This change also includes resolve_dependency() cleanup. There were
some custom resolve_dependency() like codes for packages that need our
custom "Alt" version such as Boost and gRPC. We can use
resolved_dependency() for these packages with the new HAVE_ALT option.

This change also renamed our Boost dependency name to "Boost" from
"BOOST". It means that users need to use -DBoost_SOURCE not
-DBOOST_SOURCE. To keep backward compatibility, -DBOOST_SOURCE is
still accepted when -DBoost_SOURCE isn't specified.

Users also need to use -Dre2_SOURCE not -DRE2_SOURCE. To keep backward
compatibility, -DRE2_SOURCE is still accepted when -Dre2_SOURCE isn't
specified.

### CODE REVIEW

**Comment by kou** [comment]
@github-actions crossbow submit -g nightly

**Comment by kou** [comment]
@github-actions crossbow submit -g nightly

**Comment by kou** [comment]
@github-actions crossbow submit -g linux

**Comment by kou** [comment]
@github-actions crossbow submit -g linux

**Comment by nealrichardson** [comment]
> This change also renamed our Boost dependency name to "Boost" from
"BOOST". It means that users need to use -DBoost_SOURCE not
-DBOOST_SOURCE. To keep backward compatibility, -DBOOST_SOURCE is
still accepted when -DBoost_SOURCE isn't specified.

> Users also need to use -Dre2_SOURCE not -DRE2_SOURCE. To keep backward
compatibility, -DRE2_SOURCE is still accepted when -Dre2_SOURCE isn't
specified.

I would love to have this kind of case-insensitive handling for all dependencies. This has tripped me up many times and it is difficult to explain to others why everything else is ALL_CAPS but these dependencies are a mix.

**Comment by kou** [comment]
OK. How about using `ARROW_${UPPERCASE_DEPENDENCY_NAME}_SOURCE` CMake variables for them like `ARROW_*_USE_SHARED`?

If it sounds reasonable, we can work on it as a separated task.

**Comment by nealrichardson** [comment]
Why does it need the `ARROW_` namespace prefix?

I'm fine with anything that is intuitive and trivial to document.

**Comment by kou** [comment]
Because of consistency.
If we use `ARROW_${UPPERCASE_DEPENDENCY_NAME}_SOURCE` not `${UPPERCASE_DEPENDENCY_NAME}_SOURCE`,  we can explain that you can customize how to use `${DEPENDENCY}` by `ARROW_${UPPERCASE_DEPENDENCY_NAME}_{SOURCE,USE_SHARED}` CMake variables. It'll more intuitive than using `${UPPERCASE_DEPENDENCY_NAME}_SOURCE` and `ARROW_${UPPERCASE_DEPENDENCY_NAME}_USE_SHARED`.

**Comment by kou** [comment]
Anyway, we can handle it as a separated task. Let's discuss it at ARROW-10911 .

**Comment by kou** [comment]
@github-actions crossbow submit -g nightly

**Comment by kou** [comment]
@github-actions crossbow submit test-ubuntu-18.04-cpp-cmake32

**Comment by kou** [comment]
+1

The `wheel-manylinux*-cp{36,37}*` failures are unrelated. It's caused by #8887 .

The AppVeyor failure is also unrelated. It's caused by fsspec 0.8.4 -> 0.8.5.

**Comment by wesm** [comment]
hi @kou, I noticed that you simplified some things related to the Flight serialization customization -- is that a simplification that's due to a newer version of gRPC or was my workaround just more complicated than it needed to be?

**Comment by kou** [comment]
@wesm Sorry, I should have mentioned to you this change.

> is that a simplification that's due to a newer version of gRPC or was my workaround just more complicated than it needed to be?

Both of them.

You put the customization that uses `grpc::protobuf::Message` at 2019-02. gRPC changed to use `grpc::protobuf::MessageLite` from `grpc::protobuf::Message` since 1.22.0 that was released at 2019-06. I didn't confirm but the customization may not be used since gRPC 1.22.0. I don't know why we get build error with gRPC 1.34.0 but doesn't get with gRPC 1.22.0-1.33.2.

The main propose of this change is using `grpc::protobuf::MessageLite` not `grpc::protobuf::Message`. The simplification isn't needed. We could re-copy `SerializationTraits` from gRPC but I simplified. Because I think that copying will increase maintenance cost when gRPC changes something.

I confirmed that our custom serialization/deserialization codes are called with gRPC 1.34.0 by gdb. I didn't confirm performance because I don't have suitable environment. I also didn't confirm that they are called with gRPC 1.21.4 or older. Sorry.

**Pull request closed without merging**
