### PR TITLE
GH-38297: [C#] Fix build for .NET 4.7.2

### LINKED ISSUE #38297: [C#] Duration checkin broke build for .NET 4.7.2
### Describe the bug, including details regarding any error messages, version, and platform.

The recent change to add Duration support broke the build for .NET 4.7.2.

This would have been discovered earlier happened if #36815 had been resolved.

### Component(s)

C#

### PR DESCRIPTION
**Pull request by CurtHagenlocher**
### What changes are included in this PR?

Fixes #38297 

### Are these changes tested?

Yes
* Closes: #38297

### CODE REVIEW

**Comment by CurtHagenlocher** [comment]
As these are trivial changes aimed at fixing the build, I'm going to check in the changes without additional review and ask for forgiveness if required... .

**Comment by kou** [comment]
@CurtHagenlocher Could you use our merge script instead of the GitHub's merge button?
https://github.com/apache/arrow/tree/main/dev#how-to-merge-a-pull-request

**Comment by CurtHagenlocher** [comment]
Oops, sorry :(. Guess I didn't read nearly enough.

**Comment by kou** [comment]
We may need to create a document for new committer in https://arrow.apache.org/docs/ instead of using `dev/README.md`...

**Pull request merged**
