### PR TITLE
WIP: Investigate verify rc linux failures

### PR DESCRIPTION
**Pull request by raulcd**

### CODE REVIEW

**Comment by raulcd** [comment]
@github-actions crossbow submit verify-rc-source-integration-linux-ubuntu-18.04-amd64

**Comment by lidavidm** [comment]
Did you find out anything here?

**Comment by raulcd** [comment]
No, I didn't. I did run the job twice and it finished successfully in both cases.

**Comment by raulcd** [comment]
Revision: e766828c699c6c74eba3b8c5de99e541017b8b9e

Submitted crossbow builds: [ursacomputing/crossbow @ raul-testing-tracking-crossbow-job-7](https://github.com/ursacomputing/crossbow/branches/all?query=raul-testing-tracking-crossbow-job-7)

|Task|Status|
|----|------|
|example-cpp-minimal-build-static|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:raul-testing-tracking-crossbow-job-7-github-example-cpp-minimal-build-static)|
|example-cpp-minimal-build-static-system-dependency|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:raul-testing-tracking-crossbow-job-7-github-example-cpp-minimal-build-static-system-dependency)|
|example-python-minimal-build-fedora-conda|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:raul-testing-tracking-crossbow-job-7-github-example-python-minimal-build-fedora-conda)|
|example-python-minimal-build-ubuntu-venv|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:raul-testing-tracking-crossbow-job-7-github-example-python-minimal-build-ubuntu-venv)|

**Comment by raulcd** [comment]
Revision: e766828c699c6c74eba3b8c5de99e541017b8b9e

Submitted crossbow builds: [ursacomputing/crossbow @ raul-testing-tracking-crossbow-job-8](https://github.com/ursacomputing/crossbow/branches/all?query=raul-testing-tracking-crossbow-job-8)

|Task|Status|
|----|------|
|example-cpp-minimal-build-static|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:raul-testing-tracking-crossbow-job-8-github-example-cpp-minimal-build-static)|
|example-cpp-minimal-build-static-system-dependency|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:raul-testing-tracking-crossbow-job-8-github-example-cpp-minimal-build-static-system-dependency)|
|example-python-minimal-build-fedora-conda|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:raul-testing-tracking-crossbow-job-8-github-example-python-minimal-build-fedora-conda)|
|example-python-minimal-build-ubuntu-venv|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:raul-testing-tracking-crossbow-job-8-github-example-python-minimal-build-ubuntu-venv)|

**Comment by raulcd** [comment]
Revision: fccbfea51fb62adab4019cea122469db14181aa8

Submitted crossbow builds: [ursacomputing/crossbow @ nightly-tests-2022-07-18-0](https://github.com/ursacomputing/crossbow/branches/all?query=nightly-tests-2022-07-18-0)

|Task|Status|
|----|------|
|example-cpp-minimal-build-static|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:nightly-tests-2022-07-18-0-github-example-cpp-minimal-build-static)|
|example-cpp-minimal-build-static-system-dependency|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:nightly-tests-2022-07-18-0-github-example-cpp-minimal-build-static-system-dependency)|
|example-python-minimal-build-fedora-conda|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:nightly-tests-2022-07-18-0-github-example-python-minimal-build-fedora-conda)|
|example-python-minimal-build-ubuntu-venv|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:nightly-tests-2022-07-18-0-github-example-python-minimal-build-ubuntu-venv)|
|test-build-cpp-fuzz|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:nightly-tests-2022-07-18-0-github-test-build-cpp-fuzz)|
|test-build-vcpkg-win|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:nightly-tests-2022-07-18-0-github-test-build-vcpkg-win)|
|test-conda-cpp|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:nightly-tests-2022-07-18-0-github-test-conda-cpp)|
|test-conda-cpp-valgrind|[Azure](https://dev.azure.com/ursacomputing/crossbow/_build/latest?definitionId=1&branchName=nightly-tests-2022-07-18-0-azure-test-conda-cpp-valgrind)|
|test-conda-python-3.10|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:nightly-tests-2022-07-18-0-github-test-conda-python-3.10)|
|test-conda-python-3.7|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:nightly-tests-2022-07-18-0-github-test-conda-python-3.7)|
|test-conda-python-3.7-hdfs-2.9.2|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:nightly-tests-2022-07-18-0-github-test-conda-python-3.7-hdfs-2.9.2)|
|test-conda-python-3.7-hdfs-3.2.1|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:nightly-tests-2022-07-18-0-github-test-conda-python-3.7-hdfs-3.2.1)|
|test-conda-python-3.7-kartothek-latest|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:nightly-tests-2022-07-18-0-github-test-conda-python-3.7-kartothek-latest)|
|test-conda-python-3.7-kartothek-master|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:nightly-tests-2022-07-18-0-github-test-conda-python-3.7-kartothek-master)|
|test-conda-python-3.7-pandas-0.24|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:nightly-tests-2022-07-18-0-github-test-conda-python-3.7-pandas-0.24)|
|test-conda-python-3.7-pandas-latest|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:nightly-tests-2022-07-18-0-github-test-conda-python-3.7-pandas-latest)|
|test-conda-python-3.7-spark-v3.1.2|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:nightly-tests-2022-07-18-0-github-test-conda-python-3.7-spark-v3.1.2)|
|test-conda-python-3.8|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:nightly-tests-2022-07-18-0-github-test-conda-python-3.8)|
|test-conda-python-3.8-hypothesis|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:nightly-tests-2022-07-18-0-github-test-conda-python-3.8-hypothesis)|
|test-conda-python-3.8-pandas-latest|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:nightly-tests-2022-07-18-0-github-test-conda-python-3.8-pandas-latest)|
|test-conda-python-3.8-pandas-nightly|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:nightly-tests-2022-07-18-0-github-test-conda-python-3.8-pandas-nightly)|
|test-conda-python-3.8-spark-v3.2.0|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:nightly-tests-2022-07-18-0-github-test-conda-python-3.8-spark-v3.2.0)|
|test-conda-python-3.9|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:nightly-tests-2022-07-18-0-github-test-conda-python-3.9)|
|test-conda-python-3.9-dask-latest|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:nightly-tests-2022-07-18-0-github-test-conda-python-3.9-dask-latest)|
|test-conda-python-3.9-dask-master|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:nightly-tests-2022-07-18-0-github-test-conda-python-3.9-dask-master)|
|test-conda-python-3.9-pandas-master|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:nightly-tests-2022-07-18-0-github-test-conda-python-3.9-pandas-master)|
|test-conda-python-3.9-spark-master|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:nightly-tests-2022-07-18-0-github-test-conda-python-3.9-spark-master)|
|test-debian-10-cpp-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:nightly-tests-2022-07-18-0-github-test-debian-10-cpp-amd64)|
|test-debian-10-cpp-i386|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:nightly-tests-2022-07-18-0-github-test-debian-10-cpp-i386)|
|test-debian-11-cpp-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:nightly-tests-2022-07-18-0-github-test-debian-11-cpp-amd64)|
|test-debian-11-cpp-i386|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:nightly-tests-2022-07-18-0-github-test-debian-11-cpp-i386)|
|test-debian-11-go-1.16|[Azure](https://dev.azure.com/ursacomputing/crossbow/_build/latest?definitionId=1&branchName=nightly-tests-2022-07-18-0-azure-test-debian-11-go-1.16)|
|test-debian-11-python-3|[Azure](https://dev.azure.com/ursacomputing/crossbow/_build/latest?definitionId=1&branchName=nightly-tests-2022-07-18-0-azure-test-debian-11-python-3)|
|test-debian-c-glib|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:nightly-tests-2022-07-18-0-github-test-debian-c-glib)|
|test-debian-ruby|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:nightly-tests-2022-07-18-0-github-test-debian-ruby)|
|test-fedora-35-cpp|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:nightly-tests-2022-07-18-0-github-test-fedora-35-cpp)|
|test-fedora-35-python-3|[Azure](https://dev.azure.com/ursacomputing/crossbow/_build/latest?definitionId=1&branchName=nightly-tests-2022-07-18-0-azure-test-fedora-35-python-3)|
|test-fedora-r-clang-sanitizer|[Azure](https://dev.azure.com/ursacomputing/crossbow/_build/latest?definitionId=1&branchName=nightly-tests-2022-07-18-0-azure-test-fedora-r-clang-sanitizer)|
|test-r-arrow-backwards-compatibility|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:nightly-tests-2022-07-18-0-github-test-r-arrow-backwards-compatibility)|
|test-r-depsource-bundled|[Azure](https://dev.azure.com/ursacomputing/crossbow/_build/latest?definitionId=1&branchName=nightly-tests-2022-07-18-0-azure-test-r-depsource-bundled)|
|test-r-depsource-system|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:nightly-tests-2022-07-18-0-github-test-r-depsource-system)|
|test-r-dev-duckdb|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:nightly-tests-2022-07-18-0-github-test-r-dev-duckdb)|
|test-r-devdocs|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:nightly-tests-2022-07-18-0-github-test-r-devdocs)|
|test-r-gcc-11|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:nightly-tests-2022-07-18-0-github-test-r-gcc-11)|
|test-r-gcc-12|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:nightly-tests-2022-07-18-0-github-test-r-gcc-12)|
|test-r-install-local|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:nightly-tests-2022-07-18-0-github-test-r-install-local)|
|test-r-linux-as-cran|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:nightly-tests-2022-07-18-0-github-test-r-linux-as-cran)|
|test-r-linux-rchk|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:nightly-tests-2022-07-18-0-github-test-r-linux-rchk)|
|test-r-linux-valgrind|[Azure](https://dev.azure.com/ursacomputing/crossbow/_build/latest?definitionId=1&branchName=nightly-tests-2022-07-18-0-azure-test-r-linux-valgrind)|
|test-r-minimal-build|[Azure](https://dev.azure.com/ursacomputing/crossbow/_build/latest?definitionId=1&branchName=nightly-tests-2022-07-18-0-azure-test-r-minimal-build)|
|test-r-offline-maximal|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:nightly-tests-2022-07-18-0-github-test-r-offline-maximal)|
|test-r-offline-minimal|[Azure](https://dev.azure.com/ursacomputing/crossbow/_build/latest?definitionId=1&branchName=nightly-tests-2022-07-18-0-azure-test-r-offline-minimal)|
|test-r-rhub-debian-gcc-devel-lto-latest|[Azure](https://dev.azure.com/ursacomputing/crossbow/_build/latest?definitionId=1&branchName=nightly-tests-2022-07-18-0-azure-test-r-rhub-debian-gcc-devel-lto-latest)|
|test-r-rhub-debian-gcc-release-custom-ccache|[Azure](https://dev.azure.com/ursacomputing/crossbow/_build/latest?definitionId=1&branchName=nightly-tests-2022-07-18-0-azure-test-r-rhub-debian-gcc-release-custom-ccache)|
|test-r-rhub-ubuntu-gcc-release-latest|[Azure](https://dev.azure.com/ursacomputing/crossbow/_build/latest?definitionId=1&branchName=nightly-tests-2022-07-18-0-azure-test-r-rhub-ubuntu-gcc-release-latest)|
|test-r-rocker-r-base-latest|[Azure](https://dev.azure.com/ursacomputing/crossbow/_build/latest?definitionId=1&branchName=nightly-tests-2022-07-18-0-azure-test-r-rocker-r-base-latest)|
|test-r-rstudio-r-base-4.1-opensuse153|[Azure](https://dev.azure.com/ursacomputing/crossbow/_build/latest?definitionId=1&branchName=nightly-tests-2022-07-18-0-azure-test-r-rstudio-r-base-4.1-opensuse153)|
|test-r-rstudio-r-base-4.2-centos7-devtoolset-8|[Azure](https://dev.azure.com/ursacomputing/crossbow/_build/latest?definitionId=1&branchName=nightly-tests-2022-07-18-0-azure-test-r-rstudio-r-base-4.2-centos7-devtoolset-8)|
|test-r-rstudio-r-base-4.2-focal|[Azure](https://dev.azure.com/ursacomputing/crossbow/_build/latest?definitionId=1&branchName=nightly-tests-2022-07-18-0-azure-test-r-rstudio-r-base-4.2-focal)|
|test-r-ubuntu-22.04|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:nightly-tests-2022-07-18-0-github-test-r-ubuntu-22.04)|
|test-r-versions|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:nightly-tests-2022-07-18-0-github-test-r-versions)|
|test-skyhook-integration|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:nightly-tests-2022-07-18-0-github-test-skyhook-integration)|
|test-ubuntu-18.04-cpp|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:nightly-tests-2022-07-18-0-github-test-ubuntu-18.04-cpp)|
|test-ubuntu-18.04-cpp-release|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:nightly-tests-2022-07-18-0-github-test-ubuntu-18.04-cpp-release)|
|test-ubuntu-18.04-cpp-static|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:nightly-tests-2022-07-18-0-github-test-ubuntu-18.04-cpp-static)|
|test-ubuntu-18.04-r-sanitizer|[Azure](https://dev.azure.com/ursacomputing/crossbow/_build/latest?definitionId=1&branchName=nightly-tests-2022-07-18-0-azure-test-ubuntu-18.04-r-sanitizer)|
|test-ubuntu-20.04-cpp|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:nightly-tests-2022-07-18-0-github-test-ubuntu-20.04-cpp)|
|test-ubuntu-20.04-cpp-14|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:nightly-tests-2022-07-18-0-github-test-ubuntu-20.04-cpp-14)|
|test-ubuntu-20.04-cpp-17|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:nightly-tests-2022-07-18-0-github-test-ubuntu-20.04-cpp-17)|
|test-ubuntu-20.04-cpp-bundled|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:nightly-tests-2022-07-18-0-github-test-ubuntu-20.04-cpp-bundled)|
|test-ubuntu-20.04-cpp-thread-sanitizer|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:nightly-tests-2022-07-18-0-github-test-ubuntu-20.04-cpp-thread-sanitizer)|
|test-ubuntu-20.04-python-3|[Azure](https://dev.azure.com/ursacomputing/crossbow/_build/latest?definitionId=1&branchName=nightly-tests-2022-07-18-0-azure-test-ubuntu-20.04-python-3)|
|test-ubuntu-22.04-cpp|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:nightly-tests-2022-07-18-0-github-test-ubuntu-22.04-cpp)|
|test-ubuntu-c-glib|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:nightly-tests-2022-07-18-0-github-test-ubuntu-c-glib)|
|test-ubuntu-default-docs|[Azure](https://dev.azure.com/ursacomputing/crossbow/_build/latest?definitionId=1&branchName=nightly-tests-2022-07-18-0-azure-test-ubuntu-default-docs)|
|test-ubuntu-ruby|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:nightly-tests-2022-07-18-0-github-test-ubuntu-ruby)|

**Pull request closed without merging**
