### PR TITLE
GH-43707: [Python] Fix compilation on Cython<3

### PR DESCRIPTION
**Pull request by lidavidm**
### Rationale for this change

Fix compilation on Cython < 3

### What changes are included in this PR?

Add an explicit cast

### Are these changes tested?

N/A

### Are there any user-facing changes?

No
* GitHub Issue: #43707

### CODE REVIEW

**Comment by lidavidm** [comment]
@github-actions crossbow submit test-conda-python-3.10-cython2

**Comment by pitrou** [comment]
@github-actions crossbow submit -g python

**Review by pitrou — APPROVED** [review]
+1, thank you!

**Review by jorisvandenbossche — APPROVED** [review]
Thanks!

**Pull request merged**
