### PR TITLE
ARROW-11784: [Rust][DataFusion] CoalesceBatchesStream doesn't honor Stream interface

### PR DESCRIPTION
**Pull request by edrevo**
Unit tests now cover the bug to avoid regressions.

### CODE REVIEW

**Comment by edrevo** [comment]
cc @andygrove

**Review by andygrove — APPROVED** [review]
Nice catch. LGTM!

**Review by alamb — APPROVED** [review]

**Comment by edrevo** [comment]
I really need an fmt hook in my git... Fmt fixed!

**Comment by edrevo** [comment]
@andygrove, I think the CI failure is unrelated to this change. Can you confirm?

**Comment by alamb** [comment]
@edrevo  the integration test failure looks like https://issues.apache.org/jira/browse/ARROW-11717 to me (not related to your PR)

**Pull request closed without merging**
