### PR TITLE
ARROW-12645: [Python] Fix numpydoc validation

### PR DESCRIPTION
**Pull request by kszucs**
Numpydoc helps identifying issues with our docstrings, for example we can list the undocumented parameters using the following command:

```bash
archery numpydoc -a PR01
```

parts of the output:

```console
pyarrow.parquet.write_table
PR01: Parameters {'use_compliant_nested_type', 'where', 'row_group_size', 'use_byte_stream_split', 'compression_level', '**kwargs'} not documented

pyarrow.parquet.write_metadata
PR01: Parameters {'where', 'metadata_collector'} not documented

pyarrow.parquet.read_table
PR01: Parameters {'source', 'columns'} not documented

pyarrow.parquet.read_pandas
PR01: Parameters {'source', '**kwargs', 'columns'} not documented

pyarrow.parquet.PartitionSet
PR01: Parameters {'keys', 'name'} not documented

pyarrow.parquet.PartitionSet.get_index
PR01: Parameters {'key'} not documented

pyarrow.parquet.ParquetWriter
PR01: Parameters {'writer_engine_version', 'use_compliant_nested_type', 'use_byte_stream_split', 'compression_level'} not documented
```

```console
pyarrow._flight.RecordBatchStream
-> pyarrow._flight.RecordBatchStream(data_source, options=None)
PR01: Parameters {'options', 'data_source'} not documented

pyarrow._flight.Location
-> pyarrow._flight.Location(uri)
PR01: Parameters {'uri'} not documented

pyarrow._flight.for_grpc_unix
-> pyarrow._flight.Location.for_grpc_unix(path)
PR01: Parameters {'path'} not documented

pyarrow._flight.for_grpc_tls
-> pyarrow._flight.Location.for_grpc_tls(host, port)
PR01: Parameters {'host', 'port'} not documented

pyarrow._flight.for_grpc_tcp
-> pyarrow._flight.Location.for_grpc_tcp(host, port)
PR01: Parameters {'host', 'port'} not documented

pyarrow._flight.GeneratorStream
-> pyarrow._flight.GeneratorStream(schema, generator, options=None)
PR01: Parameters {'options', 'schema', 'generator'} not documented

pyarrow._flight.FlightWriteSizeExceededError
-> pyarrow._flight.A write operation exceeded the client-configured limit.
PR01: Parameters {'actual', 'limit', 'message'} not documented
```

### CODE REVIEW

**Comment by kszucs** [comment]
@jorisvandenbossche any ides how could we incorporate the numpydoc validations in our CI? We could incrementally enable more and more checks, though we have many docstring violations.

**Comment by jorisvandenbossche** [comment]
Ensuring that all keywords are documented sounds useful to check for. So indeed, if there is one of the validation chekcs we find useful and is passing, we could at that point add it to CI to keep it passing?

Looking at the actual output above:

> pyarrow.parquet.write_table
PR01: Parameters {'use_compliant_nested_type', 'where', 'row_group_size', 'use_byte_stream_split', 'compression_level', '**kwargs'} not documented

It seems there are some false positives for this check. In this case, all those keywords (except for `**kwargs`) are actually documented, but they are missing a space before the colon (`keyword: type` instead of `keyword : type`). Numpydoc, which is used for the validation, is picky about this. But the doc build itself looks fine, for which we use sphinx.ext.napoleon.

**Comment by kszucs** [comment]
We can do a mass update for `PR10` errors before enabling `PR1` on CI:

```
pyarrow.parquet.write_table
GL02: Closing quotes should be placed in the line after the last text in the docstring (do not close the quotes in the same line as the text, or leave a blank line between the last text and the quotes)
GL03: Double line break found; please use only one blank line to separate sections or paragraphs, and do not leave blank lines at the end of docstrings
PR01: Parameters {'use_byte_stream_split', 'compression_level', 'where', 'use_compliant_nested_type', 'row_group_size', '**kwargs'} not documented
PR02: Unknown parameters {'row_group_size: int', 'use_compliant_nested_type: bool', 'use_byte_stream_split: bool or list', 'compression_level: int or dict', 'where: string or pyarrow.NativeFile', 'default None', 'default False'}
PR07: Parameter "table" has no description
PR10: Parameter "where" requires a space before the colon separating the parameter name and type
PR07: Parameter "where: string or pyarrow.NativeFile" has no description
PR10: Parameter "row_group_size" requires a space before the colon separating the parameter name and type
PR09: Parameter "row_group_size: int" description should finish with "."
PR09: Parameter "coerce_timestamps" description should finish with "."
PR10: Parameter "compression_level" requires a space before the colon separating the parameter name and type
PR04: Parameter "default None" has no type
PR10: Parameter "use_byte_stream_split" requires a space before the colon separating the parameter name and type
PR04: Parameter "default False" has no type
PR10: Parameter "use_compliant_nested_type" requires a space before the colon separating the parameter name and type
```

**Review by kszucs — COMMENTED** [review]
+1

**Pull request closed without merging**
