### PR TITLE
PARQUET-2250:[C++][Parquet] Expose column descriptor through RecordReader

### PR DESCRIPTION
**Pull request by fatemehp**
This change exposes the column descriptor through the RecordReader.

### CODE REVIEW

**Comment by fatemehp** [comment]
@emkornfield could you take a look? Thanks!

**Review by wgtmac — APPROVED** [review]
LGTM

**Comment by fatemehp** [comment]
@wgtmac, @emkornfield would you mind merging this? Thanks!

**Comment by emkornfield** [comment]
LGTM.

**Comment by emkornfield** [comment]
@fatemehp looks like this needs a rebase before merge.

**Comment by fatemehp** [comment]
Rebased, @wgtmac, @emkornfield would you mind merging this? Thanks!

**Review by westonpace — APPROVED** [review]

**Pull request merged**
