### PR TITLE
PARQUET-1532: [C++] Fix build error with MinGW

### PR DESCRIPTION
**Pull request by kou**
Error message:

    In file included from C:/msys64/mingw64/include/thrift/TApplicationException.h:23,
                     from C:/Users/kou/work/arrow/arrow.kou/cpp/src/parquet/thrift.h:35,
                     from C:/Users/kou/work/arrow/arrow.kou/cpp/src/parquet/column_reader.cc:36:
    C:/msys64/mingw64/include/thrift/Thrift.h:32:10: fatal error: netinet/in.h: No such file or directory
     #include <netinet/in.h>
              ^~~~~~~~~~~~~~

### CODE REVIEW

**Review by kszucs — APPROVED** [review]

**Comment by kszucs** [comment]
@kou I'm not allowed to edit PARQUET project on jira, so I cannot change the fix version. Could You please grant me permissions?

**Comment by kou** [comment]
Ah, I don't have permission for PARQUET project.
(I could close this issue because I'm the reporter.)

@wesm @xhochy What should we do for PARQUET issues? @kszucs and I can merge changes to this repository but can't change PARQUET issues. Should we wait @wesm, @xhochy or someone for PARQUET issues?

**Comment by wesm** [comment]
@kou I'll make you a contributor on PARQUET

**Comment by kou** [comment]
Thanks!

**Comment by wesm** [comment]
I added @kszucs as a Contributor so he should be able to edit fix versions now

**Pull request closed without merging**
