### PR TITLE
ARROW-8449: [R] Use CMAKE_UNITY_BUILD everywhere

### PR DESCRIPTION
**Pull request by nealrichardson**
To speed up the builds

### CODE REVIEW

**Comment by nealrichardson** [comment]
@github-actions crossbow submit -g r

**Comment by nealrichardson** [comment]
Shaves a couple of minutes off of the linux builds that download a new enough cmake. No effect on the windows and macOS builds yet because they're still using older cmake (3.15 and 3.12, respectively).

@pitrou look good to you?

**Comment by pitrou** [comment]
Out of curiosity, what are the numbers before/after?

**Review by pitrou — APPROVED** [review]
LGTM

**Comment by nealrichardson** [comment]
There's a decent amount of variability across builds, but here's the latest nightly for one of the linux build matrices: https://github.com/ursa-labs/crossbow/runs/585570587?check_suite_focus=true

And on this PR: https://github.com/ursa-labs/crossbow/runs/586277132?check_suite_focus=true

Debian builds are down from 11+ minutes building to 9+; fedora ones are also down, with the biggest drop on the one that uses `clang` (18:12 down to 14:29).

**Comment by pitrou** [comment]
Thanks!

**Pull request closed without merging**
