### PR TITLE
ARROW-4015: [Plasma] remove unused interfaces for plasma manager

### PR DESCRIPTION
**Pull request by zhijunfu**
https://github.com/apache/arrow/issues/3154

This removes unused plasma interfaces Fetch(), Wait(), Transfer() and Info(), which depend on plasma manager which has already been removed from ray.

### CODE REVIEW

**Review by robertnishihara — APPROVED** [review]

**Comment by robertnishihara** [comment]
In

```
def connect(store_socket_name, manager_socket_name, int release_delay=0, int num_retries=-1):
```

Can we make `manager_socket_name` an optional argument and print a deprecation warning if the argument is provided?

**Comment by zhijunfu** [comment]
Updated. Please kindly take another look.

**Review by robertnishihara — APPROVED** [review]

**Comment by robertnishihara** [comment]
Thanks! Looks good to me pending tests passing.

**Comment by zhijunfu** [comment]
@robertnishihara Looks good to me. Thanks.

**Review by pcmoritz — CHANGES_REQUESTED** [review]
There is still a number of test failures in Travis, I started fixing some of them.

**Review by pcmoritz — APPROVED** [review]

**Comment by pcmoritz** [comment]
@zhijunfu Thanks a lot for fixing this!

**Pull request closed without merging**
