### PR TITLE
ARROW-4491: [Python] Use StringConverter and stringstream instead of std::stoi and std::to_string

### PR DESCRIPTION
**Pull request by guoyuhong**
@pcmoritz Asked me to continue this PR https://github.com/apache/arrow/pull/3570, but I don't have the right to change the his repro.

### CODE REVIEW

**Comment by guoyuhong** [comment]
@pitrou Please, help to take a look.

**Review by pitrou — APPROVED** [review]
LGTM, but the build issue (see AppVeyor) should be resolved.

**Comment by pitrou** [comment]
I tried to push a fix for the build issue.

**Review by pitrou — APPROVED** [review]
+1

**Comment by guoyuhong** [comment]
Thanks!

**Comment by pcmoritz** [comment]
@guoyuhong Thanks this is really great and I think it fixes the issues :)

**Pull request closed without merging**
