### PR TITLE
ARROW-13288: [Python] Missing default values of kernel options in PyArrow

### PR DESCRIPTION
**Pull request by edponce**
This PR ensures that default values for kernel options in PyArrow are consistent with the C++ defaults.

### CODE REVIEW

**Review by amol- — APPROVED** [review]
LGTM, `sys.maxsize` and `std::numeric_limits<int64_t>::max()` should be the same exact value. Even though, it would probably be best to find a way to pass `None` from Python and have the actual maximum value written in only one place (C++). Mostly because `sys.maxsize` might depend on the target system, while in C++ we are explicitly stating 64bit.

**Comment by edponce** [comment]
@amol- The issue I find with `None` is that it doesn't provide any useful info w.r.t. to what value it is representing. Consider the case where a default C++ option is `std::numeric_limits<int64_t>::min()` then mapping `None` to also mean `-sys.maxsize-1` is inconsistent. Maybe another approach is to use `None` in Python for all options with a default value in C++, and let the C++ layer establish the actual default value.

**Comment by edponce** [comment]
Related to this PR and discussion, some default values in CPython are typed with `int64_t` see [`PartitionNthOptions`](https://github.com/apache/arrow/blob/master/python/pyarrow/_compute.pyx#L858). Also, why are not all options in CPython explicitly typed?

**Review by bkietz — APPROVED** [review]
LGTM, thanks

**Pull request closed without merging**
