### PR TITLE
ARROW-2553: [Python] Set MACOSX_DEPLOYMENT_TARGET in wheel build

### PR DESCRIPTION
**Pull request by kszucs**
waiting for kszucs/crossbow@build-193

### CODE REVIEW

**Comment by kszucs** [comment]
@xhochy the wheels are here https://github.com/kszucs/crossbow/releases/tag/build-193

How should We check that it works on an older osx? 
Do We test the wheels in the build (like for example conda does)?

**Comment by xhochy** [comment]
The content of the `pyarrow` folder in the virtualenv is:

```
pyarrow/libarrow.10.dylib
pyarrow/libarrow.dylib
pyarrow/libarrow_boost_filesystem.1.65.1.dylib
pyarrow/libarrow_boost_filesystem.dylib
pyarrow/libarrow_boost_regex.1.65.1.dylib
pyarrow/libarrow_boost_regex.dylib
pyarrow/libarrow_boost_system.1.65.1.dylib
pyarrow/libarrow_boost_system.dylib
pyarrow/libarrow_python.10.dylib
pyarrow/libarrow_python.dylib
pyarrow/libparquet.1.4.1.dylib
pyarrow/libparquet.1.dylib
pyarrow/libparquet.dylib
pyarrow/libplasma.10.dylib
pyarrow/libplasma.dylib
```

The library is in there, so this is an RPATH problem.

**Comment by wesm** [comment]
Probably related to ARROW-2326

**Comment by kszucs** [comment]
@wesm auditwheel fails with a similar error https://travis-ci.org/kszucs/crossbow/builds/403270960#L2767

**Comment by kszucs** [comment]
@xhochy I've ported your rpath fix from arrow-dist, here is a [py36m wheel](https://github.com/kszucs/crossbow/releases/tag/build-203-wheel-osx-cp36m) if you want to try. I intend to setup minimal tests for osx wheels. 

Meanwhile someone could give me a hint how to resolve the linux auditwheel issue linked above :)

**Comment by xhochy** [comment]
The auditwheel issue is down to auditwheel now also scanning non-Python binaries: https://github.com/pypa/auditwheel/commit/221d6b1927f660aa4de967a2ee2d55e8dba22744

Looking into this if we might be able to also just fix them to make `auditwheel` pass. Otherwise I'll raise an issue and pin the version while fixing it.

**Comment by xhochy** [comment]
The issue is `libparquet.so`:

```
[root@cb5afc24289f pyarrow]# ldd libparquet.so
	linux-vdso.so.1 =>  (0x00007ffdccbb2000)
	libarrow.so.10 => not found
	libarrow_boost_regex.so.1.66.0 => not found
	libstdc++.so.6 => /usr/lib64/libstdc++.so.6 (0x00007f534f502000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f534f27f000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f534f071000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f534ed18000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f534fbb1000)
```

**Comment by kszucs** [comment]
@xhochy Created an issue for implementing osx wheel tests https://issues.apache.org/jira/browse/ARROW-2844

IMHO we should create another issue for auditwheel, and merge this one.

**Comment by xhochy** [comment]
@kszucs yes, will do both

**Comment by xhochy** [comment]
@kszucs This has a merge conflict, please rebase.

**Comment by kszucs** [comment]
@xhochy Done. I guess github has closed this one on behalf of me after rebase :)

**Comment by xhochy** [comment]
Should this be closed or is it a github malfunction?

**Comment by kszucs** [comment]
Same patch has been applied on the master, so I'm closing the issue too.

**Pull request closed without merging**
