### PR TITLE
ARROW-3516: [C++] Use unsigned type for difference of pointers in parallel_memcpy

### PR DESCRIPTION
**Pull request by kou**

### CODE REVIEW

**Comment by pitrou** [comment]
Does this fix a particular issue?

**Review by wesm — APPROVED** [review]
+1

**Comment by pitrou** [comment]
What is the policy here? AFAIK we're supposed to use `int64_t` or `uint64_t`.

**Comment by wesm** [comment]
That's definitely true for public APIs. On looking closer at this we should probably be `static_cast<int64_t>` instead of using size_t. I understand the motivation is to avoid a compiler warning on WIN32 platforms

**Comment by kou** [comment]
> Does this fix a particular issue?

Yes.
But I was wrong... Sorry.

I saw that MinGW 32bit build without this change causes type error. But it's wrong. It just aborted:
https://dev.azure.com/msys2/mingw/_build/results?buildId=266&view=logs

```text
2018-10-10T05:06:10.4638380Z In file included from D:/a/1/s/mingw-w64-arrow/src/apache-arrow-0.11.0/cpp/src/arrow/io/memory.cc:29:0:
2018-10-10T05:06:10.4639329Z D:/a/1/s/mingw-w64-arrow/src/apache-arrow-0.11.0/cpp/src/arrow/util/memory.h: In substitution of 'template<class Function, class ... Args, class Result> std::future<Result> arrow::internal::ThreadPool::Submit(Function&&, Args&& ...) [with Function = <missing>; Args = <missing>; Result = <missing>]':
2018-10-10T05:06:10.4639444Z D:/a/1/s/mingw-w64-arrow/src/apache-arrow-0.11.0/cpp/src/arrow/util/memory.h:63:72:   required from here
2018-10-10T05:06:10.4639576Z D:/a/1/s/mingw-w64-arrow/src/apache-arrow-0.11.0/cpp/src/arrow/util/memory.h:63:72: internal compiler error: Segmentation fault
2018-10-10T05:06:10.4639644Z                                        left + i * chunk_size, chunk_size));
2018-10-10T05:06:10.4639723Z                                                                         ^
2018-10-10T05:06:10.4639759Z 
2018-10-10T05:06:10.4639833Z This application has requested the Runtime to terminate it in an unusual way.
2018-10-10T05:06:10.4639892Z Please contact the application's support team for more information.
2018-10-10T05:06:10.4639948Z 
2018-10-10T05:06:10.4640007Z D:/a/1/s/mingw-w64-arrow/src/apache-arrow-0.11.0/cpp/src/arrow/util/memory.h:63:72: internal compiler error: Aborted
2018-10-10T05:06:10.4640046Z 
2018-10-10T05:06:10.4640117Z This application has requested the Runtime to terminate it in an unusual way.
2018-10-10T05:06:10.4640425Z Please contact the application's support team for more information.
2018-10-10T05:06:10.4640484Z g++.exe: internal compiler error: Aborted (program cc1plus)
2018-10-10T05:06:10.4640558Z Please submit a full bug report,
2018-10-10T05:06:10.4640612Z with preprocessed source if appropriate.
2018-10-10T05:06:10.4640669Z See <https://sourceforge.net/projects/msys2> for instructions.
2018-10-10T05:06:10.4640734Z make[2]: *** [src/arrow/CMakeFiles/arrow_objlib.dir/build.make:414: src/arrow/CMakeFiles/arrow_objlib.dir/io/memory.cc.obj] Error 4
2018-10-10T05:06:10.4640818Z make[2]: *** Waiting for unfinished jobs....
2018-10-10T05:06:10.4809040Z [ 69%] [32mBuilding CXX object src/arrow/CMakeFiles/arrow_objlib.dir/io/readahead.cc.obj[0m
2018-10-10T05:06:11.8407056Z make[1]: *** [CMakeFiles/Makefile2:357: src/arrow/CMakeFiles/arrow_objlib.dir/all] Error 2
2018-10-10T05:06:11.8426623Z make: *** [Makefile:141: all] Error 2
```

This behavior isn't changed with this change. Sorry.

We can revert this change.

**Pull request closed without merging**
