### PR TITLE
ARROW-11610: [C++] Download boost from sourceforge instead of bintray

### PR DESCRIPTION
**Pull request by nealrichardson**
This also removes some bintray URLs where we had mirrored dependency versions for redundancy (cf. ARROW-11611); they're not active anymore anyway because we've bumped the dependency versions and didn't update our mirroring. 

For what it's worth, our builds won't touch the updated boost on sourceforge because we still have our trimmed boost bundle in front of it (updating that is ARROW-11612), so we'll have to confirm this by other means.

### CODE REVIEW

**Comment by kiszk** [comment]
The description looks good. However, actual changes may include unrelated commits...

**Comment by nealrichardson** [comment]
@github-actions rebase

**Comment by nealrichardson** [comment]
Thanks @kiszk, looks like that was a side effect of the accidental force-push to master. I've rebased so it should be cleaned up now.

**Comment by kiszk** [comment]
Looks good to me.

**Comment by pitrou** [comment]
Doesn't work:
```
$ ./build-support/trim-boost.sh 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  108k  100  108k    0     0  81607      0  0:00:01  0:00:01 --:--:-- 81607

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

**Comment by pitrou** [comment]
The URL (https://sourceforge.net/projects/boost/files/boost/1.71.0/boost_1_71_0.tar.gz) is a 404. Did you test it before submitting this PR?

**Comment by nealrichardson** [comment]
I did check sourceforge but apparently not with the version of boost we currently are pinned to. For some reason it looks like every other version is present there (https://sourceforge.net/projects/boost/files/boost/) but 1.71.0 is empty (https://sourceforge.net/projects/boost/files/boost/1.71.0/).

I think to move forward then, we can (1) rebuild and publish the trimmed boost bundle with the latest version of boost (alongside the 1.71.0 version that's there now) and then (2) bump the boost version in versions.txt.

**Comment by kiszk** [comment]
Oh, I checked the directory exists, but I did not see files under the directory. Sorry.

**Comment by nealrichardson** [comment]
I tried bumping boost to the latest (1.75.0), and that does successfully download from sourceforge. However, the build fails because of Thrift 0.12's use of deprecated boost endian headers (cf. https://issues.apache.org/jira/browse/THRIFT-4836), which were [removed in boost 1.73.0](https://github.com/boostorg/endian/issues/45). This was apparently [fixed in Thrift 0.13](https://issues.apache.org/jira/browse/THRIFT-4861).

I see three options:

1. [Upgrade to thrift 0.13](https://issues.apache.org/jira/browse/ARROW-8049) to allow newer boost. This was stalled before because thrift 0.13 apparently requires newer cmake than we do. https://issues.apache.org/jira/browse/THRIFT-5137 is the issue we created about that. It looks like an easy fix, which we could then apply as a patch step in our cmake build to allow 0.13.
2. Apply the patch from THRIFT-4861 in our build_thrift cmake macro and keep going with thrift 0.12 while allowing us to upgrade to newer boost.
3. Bump boost only to 1.72, the last version before the deprecated headers were removed, and don't bother with thrift. 

IMO option 1 is best; I think thrift 0.13 also uses even less boost than 0.12, so we could prune our boost bundle further. And I suspect it only requires a very small change. Option 3 is the least effort but just defers the maintenance burden.

**Comment by kou** [comment]
I like 1. I think that we can require CMake 3.10 or later only when an user wants to use bundled Thrift.
We already requires CMake 3.7 or later only when an user wants to use bundled Zstandard.

**Comment by kou** [comment]
FYI: We'll drop support for Ubuntu 16.04 LTS soon (2021-04 is EOL of Ubuntu 16.04 LTS) and Ubuntu 18.04 LTS or later ship CMake 3.10 or later. We can use CMake 3.17.5 from EPEL on CentOS 7.

**Comment by nealrichardson** [comment]
Rebased after upgrading thrift to 0.13 in #9658

**Comment by kou** [comment]
@github-actions crossbow submit -g nightly

**Review by pitrou — APPROVED** [review]
+1

**Pull request closed without merging**
