### PR TITLE
ARROW-1787: [Python] Support reading parquet files into DataFrames in a backward compatible way

### PR DESCRIPTION
**Pull request by cpcloud**

### CODE REVIEW

**Comment by wesm** [comment]
May need to use `BytesIO` in the test case

**Comment by cpcloud** [comment]
This needs at least one additional test for columns with named indexes. I'll crank this out early tomorrow.

**Comment by cpcloud** [comment]
@wesm This is ready for review when you have a chance.

**Review by wesm — APPROVED** [review]
+1, thanks @cpcloud!

**Pull request closed without merging**
