### PR TITLE
ARROW-11833: [C++] Bump vendored fast_float

### PR DESCRIPTION
**Pull request by pitrou**
Upstream fast_float has integrated several fixes of interest.

### CODE REVIEW

**Comment by pitrou** [comment]
@github-actions crossbow submit

**Review by nealrichardson — APPROVED** [review]
I see my Solaris patch in there so 👍 from me

**Comment by pitrou** [comment]
@github-actions crossbow submit -g cpp

**Comment by pitrou** [comment]
Crossbow build results: https://github.com/ursacomputing/crossbow/branches/all?query=build-90
The failures are unrelated.

**Pull request closed without merging**
