### PR TITLE
ARROW-2952: [C++] Dockerized include-what-you-use

### PR DESCRIPTION
**Pull request by wesm**
I'm trying to get this working but installing the LLVM tools takes a long time (I ran into https://issues.apache.org/jira/browse/ARROW-3033).

### CODE REVIEW

**Comment by wesm** [comment]
So apparently I'm terrible at Docker and don't understand what it's doing. @cpcloud do you know why this does not do what I want?

https://github.com/apache/arrow/pull/2416/files#diff-7990132af0e846dde30b2d49112b0598R39

**Comment by cpcloud** [comment]
@wesm not without knowing what the issue is, can you expand a bit?

**Comment by wesm** [comment]
It doesn't seem possible to execute a shell script from an attached Volume in the Dockerfile. Do you know a way to avoid having the Python build env setup duplicated across many Dockerfiles?

**Comment by wesm** [comment]
I guess the intended solution is to use base images. Going to try that

**Comment by wesm** [comment]
OK. This works fine for me. We can always make the docker files more modular later. I'll add a pointer to this in the C++ README

**Review by wesm — COMMENTED** [review]
+1. I think this gives us a reasonable starting point to iterate

**Comment by wesm** [comment]
Oops it looks like I forgot to check in the base image files. Will fix

**Comment by kou** [comment]
@wesm Did you forget to add `dev/docker_common/install_pyarrow_conda_toolchain.sh` too?
https://github.com/apache/arrow/pull/2416/files#diff-33e3219b65441bf60f10876c74e8e08cR49

**Comment by wesm** [comment]
It appears that way, that I broke the documentation generation Dockerfile. @kszucs can you take a look? I'm in the airport on bad wifi

**Comment by kszucs** [comment]
Sure!

**Pull request closed without merging**
