### PR TITLE
GH-37803: [CI][Dev][Python] Release and merge script errors

### LINKED ISSUE #37803: [CI][Dev][Python] Release and merge script errors
### Describe the bug, including details regarding any error messages, version, and platform.

The "[Source Release and Merge Script](https://github.com/apache/arrow/actions/runs/6250225828/job/16968598166#logs)" jobs have been starting to fail with Python-related errors.

See for example logs at https://github.com/apache/arrow/actions/runs/6250225828/job/16968598166#step:7:50

```
  /private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/d20230920-1658-v4ivhq/apache-arrow-14.0.0/python/.eggs/setuptools_scm-8.0.1-py3.8.egg/setuptools_scm/_integration/setuptools.py:31: RuntimeWarning: 
  ERROR: setuptools==56.0.0 is used in combination with setuptools_scm>=8.x
  
  Your build configuration is incomplete and previously worked by accident!
  setuptools_scm requires setuptools>=61
  
  Suggested workaround if applicable:
   - migrating from the deprecated setup_requires mechanism to pep517/518
     and using a pyproject.toml to declare build dependencies
     which are reliably pre-installed before running the build tools
  
    warnings.warn(
  ERROR setuptools_scm._integration.setuptools pyproject.toml does not contain a tool.setuptools_scm section
  Traceback (most recent call last):
    File "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/d20230920-1658-v4ivhq/apache-arrow-14.0.0/python/.eggs/setuptools_scm-8.0.1-py3.8.egg/setuptools_scm/_integration/pyproject_reading.py", line 53, in read_pyproject
      section = defn.get("tool", {})[tool_name]
  KeyError: 'setuptools_scm'
  
  The above exception was the direct cause of the following exception:
  
  Traceback (most recent call last):
    File "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/d20230920-1658-v4ivhq/apache-arrow-14.0.0/python/.eggs/setuptools_scm-8.0.1-py3.8.egg/setuptools_scm/_integration/setuptools.py", line 121, in infer_version
      config = _config.Configuration.from_file(dist_name=dist_name)
    File "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/d20230920-1658-v4ivhq/apache-arrow-14.0.0/python/.eggs/setuptools_scm-8.0.1-py3.8.egg/setuptools_scm/_config.py", line 128, in from_file
      pyproject_data = _read_pyproject(name, _load_toml=_load_toml)
    File "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/d20230920-1658-v4ivhq/apache-arrow-14.0.0/python/.eggs/setuptools_scm-8.0.1-py3.8.egg/setuptools_scm/_integration/pyproject_reading.py", line 55, in read_pyproject
      raise LookupError(f"{name} does not contain a tool.{tool_name} section") from e
  LookupError: pyproject.toml does not contain a tool.setuptools_scm section
  Traceback (most recent call last):
    File "setup.py", line 475, in <module>
      setup(
    File "/Users/runner/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/Users/runner/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/distutils/core.py", line 108, in setup
      _setup_distribution = dist = klass(attrs)
    File "/Users/runner/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/setuptools/dist.py", line 434, in __init__
      _Distribution.__init__(self, {
    File "/Users/runner/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/distutils/dist.py", line 292, in __init__
      self.finalize_options()
    File "/Users/runner/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/setuptools/dist.py", line 743, in finalize_options
      ep(self)
    File "/Users/runner/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/setuptools/dist.py", line 750, in _finalize_setup_keywords
      ep.load()(self, ep.name, value)
    File "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/d20230920-1658-v4ivhq/apache-arrow-14.0.0/python/.eggs/setuptools_scm-8.0.1-py3.8.egg/setuptools_scm/_integration/setuptools.py", line 102, in version_keyword
      _assign_version(dist, config)
    File "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/d20230920-1658-v4ivhq/apache-arrow-14.0.0/python/.eggs/setuptools_scm-8.0.1-py3.8.egg/setuptools_scm/_integration/setuptools.py", line 54, in _assign_version
      maybe_version = _get_version(config, force_write_version_files=True)
    File "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/d20230920-1658-v4ivhq/apache-arrow-14.0.0/python/.eggs/setuptools_scm-8.0.1-py3.8.egg/setuptools_scm/_get_version_impl.py", line 94, in _get_version
      write_version_files(config, version=version_string, scm_version=parsed_version)
    File "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/d20230920-1658-v4ivhq/apache-arrow-14.0.0/python/.eggs/setuptools_scm-8.0.1-py3.8.egg/setuptools_scm/_get_version_impl.py", line 63, in write_version_files
      dump_version(
    File "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/d20230920-1658-v4ivhq/apache-arrow-14.0.0/python/.eggs/setuptools_scm-8.0.1-py3.8.egg/setuptools_scm/_integration/dump_version.py", line 36, in dump_version
      assert not write_to.is_absolute(), f"{write_to=}"
  AssertionError: write_to=PosixPath('/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/d20230920-1658-v4ivhq/apache-arrow-14.0.0/python/pyarrow/_generated_version.py')
```

### Component(s)

Continuous Integration, Developer Tools, Python

### PR DESCRIPTION
**Pull request by AlenkaF**
### What changes are included in this PR?

Pin the version of `setuptools_scm` to `<8.0.0`.
* Closes: #37803

### CODE REVIEW

**Comment by AlenkaF** [comment]
@github-actions crossbow submit test-conda-python-3.10

**Review by raulcd — APPROVED** [review]
@AlenkaF is this still a draft? I am fine with merging this as is to fix the merge script + archery crossbow tasks, etcetera and maybe opening an issue to follow up to either fix it for setuptools_scm > 8.0.0 or change how we manage the version.

**Comment by AlenkaF** [comment]
> @AlenkaF is this still a draft? I am fine with merging this as is to fix the merge script + archery crossbow tasks, etcetera and maybe opening an issue to follow up to either fix it for setuptools_scm > 8.0.0 or change how we manage the version.

There are two files where I didn't pin `setuptools_scm` so I need to run the tests first, to see if they also need to be pinned. Then I will merge 👍

**Comment by AlenkaF** [comment]
@github-actions crossbow submit test-conda-python-3.10

**Comment by raulcd** [comment]
> There are two files where I didn't pin `setuptools_scm` so I need to run the tests first, to see if they also need to be pinned. Then I will merge 👍

Sorry you are correct, we have to pin it on archery too: https://github.com/apache/arrow/blob/main/dev/archery/setup.py#L33

**Comment by AlenkaF** [comment]
@github-actions crossbow submit test-conda-python-3.10

**Comment by raulcd** [comment]
I just validated we do the checkout from `apache/arrow` from `main` for the comment bot. The crossbow task won't work until we merge :(

**Comment by AlenkaF** [comment]
> I just validated we do the checkout from `apache/arrow` from `main` for the comment bot. The crossbow task won't work until we merge :(

Got it. Let's give it a go 👍

**Comment by jorisvandenbossche** [comment]
This _might_ already be fixed in the meantime: https://github.com/pypa/setuptools_scm/issues/919 (the same error message is mentioned on that issue, but didn't check if it actually fixed it)

**Comment by cwegener** [comment]
> opening an issue to follow up to either fix it for setuptools_scm > 8.0.0 or change how we manage the version.

A permanent fix to make pyarrow build on latest setuptools + setuptools_scm would be highly desirable. I had to resort to the exact same version constraint myself in an emergency fix to unblock some automated build system failures.

**Comment by jorisvandenbossche** [comment]
@cwegener I am not sure there is something to fix on our side. As far as I understand, it's a regression in setuptools_scm that will be fixed there (https://github.com/pypa/setuptools_scm/issues/925, https://github.com/pypa/setuptools_scm/pull/935). Ideally we would update old releases to add this upper pin for setuptools_scm in the meantime. But our release process is quite heavy, and hopefully a release of setuptools_scm fixing this issue will be released more quickly.

Now, it seems that nowadays it is recommended to configure `setuptools_scm` throught pyproject.toml instead of `use_scm_version` in `setup()` in setup.py. So that's something that we should update on our side (but that's also something we will only do for a future release, I think)

**Comment by jorisvandenbossche** [comment]
I opened a new issue about the problem of having to upper pin setuptools_scm right now with existing releases, so we have an open issue about this that users can find if they run into this -> https://github.com/apache/arrow/issues/37931 

And also opened an issue to track that we should move our setuptools_scm configuration to pyproject.toml -> https://github.com/apache/arrow/issues/37929

**Comment by cwegener** [comment]
@jorisvandenbossche 

Thanks so much for the detailed explanation!

I was in a rush to fix the breakage and the huge amount of code in setup.py, plus the distractions of there also being a pyproject.toml that doesn't seem to be used yet was causing a lot of confusion for me.

**Pull request merged**
