### PR TITLE
ARROW-13421: [C++][Python] Add CSV convert option to change decimal point

### PR DESCRIPTION
**Pull request by pitrou**

### CODE REVIEW

**Review by lidavidm — APPROVED** [review]
LGTM, thanks.

**Comment by nealrichardson** [comment]
Hard for me to review without a test in R showing it working ;P

Is this something that fast_float should support?

**Comment by pitrou** [comment]
@nealrichardson Perhaps you would like to contribute that test? (and the R bindings for the `decimal_point` option)

**Comment by pitrou** [comment]
> Is this something that fast_float should support?

I don't know... but we need to support it for decimals as well.

**Comment by nealrichardson** [comment]
> @nealrichardson Perhaps you would like to contribute that test? (and the R bindings for the `decimal_point` option)

I'll make a followup JIRA, I don't want to hold this up

**Comment by nealrichardson** [comment]
Possibly scope creep, but does this also work the other way, on csv writing?

**Comment by pitrou** [comment]
It doesn't. I'm not sure we want to support emitting such files, either.

**Review by jorisvandenbossche — APPROVED** [review]
Looks good!

**Comment by lemire** [comment]
The fast_float library now has support for commas as of release 2.0.0 thanks to a code contribution by @pitrou.

It requires using a distinct function: not `fast_float::from_chars` but `fast_float::from_chars_advanced`.

**Pull request closed without merging**
