### PR TITLE
ARROW-10260: [Python] Missing MapType in to_pandas_dtype()

### PR DESCRIPTION
**Pull request by dmarsh19**

### CODE REVIEW

**Comment by BryanCutler** [comment]
Thanks @dmarsh19 !  I think you will want to add the type mapping to the test here https://github.com/apache/arrow/blob/eec7277561b9e5c8aac03e44ac11f492ff1385fd/python/pyarrow/tests/test_schema.py#L49

**Comment by BryanCutler** [comment]
cc @kszucs this should be pretty low risk if you are able to get it in for the release

**Review by kszucs — APPROVED** [review]

**Comment by jorisvandenbossche** [comment]
@dmarsh19 thanks for the PR! I quickly added the test, so we can certainly merge this before 2.0

**Comment by dmarsh19** [comment]
You all work fast! Glad to help!

**Pull request closed without merging**
