### PR TITLE
Verify 0.17.1 release candidate [WIP]

### PR DESCRIPTION
**Pull request by nealrichardson**

### CODE REVIEW

**Comment by nealrichardson** [comment]
@github-actions crossbow submit -g verify-rc

**Comment by nealrichardson** [comment]
Initial run:

* 404 on downloading a debian rc binary: https://github.com/ursa-labs/crossbow/runs/671410685?check_suite_focus=true#step:5:3939
* Rust seems to fail on a linting issue? https://github.com/ursa-labs/crossbow/runs/671411853?check_suite_focus=true
* csharp does something 🎉 but fails later: https://github.com/ursa-labs/crossbow/runs/671412116?check_suite_focus=true#step:5:1111
* Windows source verification fails on something with MSVC: https://github.com/ursa-labs/crossbow/runs/671411312?check_suite_focus=true#step:5:4809
* macOS and linux wheels also fail on 404 downloading the rc binaries: https://github.com/ursa-labs/crossbow/runs/671410356?check_suite_focus=true#step:5:2103

**Comment by kou** [comment]
For 404 on downloading binaries: We need to remove `nuget` from `dev/release/download_rc_binaries.py:

```diff
diff --git a/dev/release/download_rc_binaries.py b/dev/release/download_rc_binaries.py
index 1c3da0e1e..a4c2411e3 100755
--- a/dev/release/download_rc_binaries.py
+++ b/dev/release/download_rc_binaries.py
@@ -131,7 +131,7 @@ def parallel_map_terminate_early(f, iterable, num_parallel):
                 raise e
 
 
-ARROW_PACKAGE_TYPES = ['centos', 'debian', 'nuget', 'python', 'ubuntu']
+ARROW_PACKAGE_TYPES = ['centos', 'debian', 'python', 'ubuntu']
 
 
 def download_rc_binaries(version, rc_number, re_match=None, dest=None,
```

`nuget` will be available since the next release but isn't available in 0.17.1.

For C#: 749b77579c92fdd34728ec57dfd7bf77e6ccf990 isn't included in 0.17.1. So we need to ignore it.

**Comment by kszucs** [comment]
@github-actions crossbow submit verify-rc-source-*

**Comment by kszucs** [comment]
@github-actions crossbow submit verify-rc-source-*

**Comment by nealrichardson** [comment]
@github-actions crossbow submit verify-rc-wheel* verify-rc-binaries*

**Comment by nealrichardson** [comment]
No need to merge this; closing.

**Pull request closed without merging**
