### PR TITLE
GH-35278: [C++][Parquet] Tools: Add debug string for ColumnChunkMetadata

### PR DESCRIPTION
**Pull request by mapleFU**
### Rationale for this change

Add debugString to ColumnChunkMetadata

### What changes are included in this PR?

A debug string directly using thrift internal methods.

### Are these changes tested?

No

### Are there any user-facing changes?

User can use it to debug

* Closes: #35278

### CODE REVIEW

**Comment by mapleFU** [comment]
@kou Can we just use this simple function to debug? You can edit this patch directly

**Comment by kou** [comment]
Hmm. Crashed... Broken memory?

https://github.com/apache/arrow/actions/runs/4771826985/jobs/8484004512?pr=35281#step:10:357

```text
/usr/local/lib/libparquet.1200.0.0.dylib(_ZNK7parquet19ColumnChunkMetaData23ColumnChunkMetaDataImpl13ToDebugStringEv+0x50) [0x110c40ce0]
/usr/local/lib/libparquet.1200.0.0.dylib(_ZNK7parquet19ColumnChunkMetaData13ToDebugStringEv+0x30) [0x110c40c80]
/usr/local/lib/libparquet-glib.1200.dylib(gparquet_column_chunk_metadata_to_string+0x26) [0x10892c676]
```

**Comment by kou** [comment]
Ah, I found a problem. This is a Ruby's GC related problem. The C++ implementation isn't related. Sorry.

**Comment by mapleFU** [comment]
(go for movie now, hopefully it will block you before I'm back)

**Comment by kou** [comment]
Fixed it in #35286.

**Pull request closed without merging**
