### PR TITLE
ARROW-6245: [Java] Provide an interface for numeric vectors

### PR DESCRIPTION
**Pull request by liyafan82**
We want to provide an interface for all vectors with numeric types (small int, float4, float8, etc). This interface will make it convenient for many operations on a vector, like average, sum, variance, etc. With this interface, the client code will be greatly simplified, with many branches/switch removed.

 

The design is similar to BaseIntVector (the interface for all integer vectors). We provide 3 methods for setting & getting numeric values:

         setWithPossibleRounding

         setSafeWithPossibleRounding

         getValueAsDouble

### CODE REVIEW

**Comment by emkornfield** [comment]
Per mailing list discussion I don't think this is a good idea.  it will lead to loss of precision for longs and I think in general not how we should be writing code to consume from vectors.

**Comment by liyafan82** [comment]
> Per mailing list discussion I don't think this is a good idea. it will lead to loss of precision for longs and I think in general not how we should be writing code to consume from vectors.

Good point. Will close it.
BTW (maybe unrelated to this issue), what is your suggestion for calculating the average/stddev of a BigIntVector? Use BigInteger or BigDecimal in Java?

**Comment by emkornfield** [comment]
BigIntVector I would expect in most case you can make use of a long, but need to be careful with bounds checking.

**Comment by liyafan82** [comment]
> BigIntVector I would expect in most case you can make use of a long, but need to be careful with bounds checking.

I see. Thank you.

**Pull request closed without merging**
