### PR TITLE
ARROW-3466: [CI] Pin protobuf version to 3.6.0 [skip appveyor]

### PR DESCRIPTION
**Pull request by pitrou**
Work around a crash with tensorflow and protobuf 3.6.1.

The change that triggered the crash seems to be the following:
https://github.com/protocolbuffers/protobuf/pull/4878

### CODE REVIEW

**Comment by wesm** [comment]
Argh, our friend std::once. Can this be solved by using dynamic linking for Protobuf and bundling the .so?

**Comment by pitrou** [comment]
Hmm, what do you mean? Does Arrow use protobuf?

**Comment by pitrou** [comment]
ORC uses protobuf, though. And we link liborc statically. And it seems we let protobuf symbols leak out of libarrow.so...

**Comment by pitrou** [comment]
https://github.com/apache/arrow/pull/2731 seems to fix the issue here.

**Comment by pitrou** [comment]
Closing in favour of https://github.com/apache/arrow/pull/2731

**Pull request closed without merging**
