### PR TITLE
GH-40568: [Java] Test failure in Dataset regarding TestAllTypes

### PR DESCRIPTION
**Pull request by vibhatha**
### Rationale for this change

A recurring CI failure was observed as recorded in https://github.com/apache/arrow/issues/40568. 

### What changes are included in this PR?

Updating the testing submodule to the changes reflected in https://github.com/apache/arrow-testing/pull/99

### Are these changes tested?

Tested by existing test cases. 

### Are there any user-facing changes?

No
* GitHub Issue: #40568

### CODE REVIEW

**Comment by vibhatha** [comment]
@github-actions crossbow submit *java*

**Comment by kou** [comment]
@davisusanibar Could you take a look at this?

**Comment by vibhatha** [comment]
@github-actions crossbow submit -g java

**Comment by kou** [comment]
@vibhatha You don't need to submit new jobs for re-run. You can just use the "Re-run jobs" button in the GitHub Actions page: https://github.com/ursacomputing/crossbow/actions/runs/8340911888/job/22827112337

**Comment by vibhatha** [comment]
@kou I cannot see a re-run button.

**Comment by kou** [comment]
@raulcd Could you check whether @vibhatha has a right to re-run jobs or not?

**Comment by vibhatha** [comment]
@kou btw seems like CIs are passing.

**Comment by vibhatha** [comment]
@davisusanibar what do you think about this comment: https://github.com/apache/arrow/issues/40568#issuecomment-2006290351
Am I missing something here?

**Comment by raulcd** [comment]
> @raulcd Could you check whether @vibhatha has a right to re-run jobs or not?

He is not a member of the ursacomputing GitHub organization at the moment. He has the collaborator role on the arrow project which allows to assign issues and trigger crossbow jobs via GitHub comments but cannot re-run jobs on crossbow as far as I understand.

**Comment by lidavidm** [comment]
@davisusanibar it's because @indigophox reverted it (by accident?) in 2e2bd8b9f231e1fc13ec4f76aebccae8f7a1ef8f. Sorry, I didn't notice that change at the time. So we can merge this and update the testing submodule properly.

**Review by lidavidm — APPROVED** [review]

**Pull request merged**
