### PR TITLE
ARROW-3506: [Packaging] Nightly tests for docker-compose images

### PR DESCRIPTION
**Pull request by kszucs**
Testing at https://github.com/kszucs/crossbow/branches/all?utf8=%E2%9C%93&query=docker

### CODE REVIEW

**Comment by xhochy** [comment]
Looking good but do you really plan to run them nightly? That will be a lot of load on CI services.

**Comment by kszucs** [comment]
That's the only way to ensure they really work. BTW the only need to run once per day, the CI services have way enough bandwidth for that. Actually I plan to utilize circleci and pipelines as well, so a single crossbow repo could handle fair amount of parallel tasks.

**Comment by xhochy** [comment]
@kszucs Generally this looks good. Feel to merge once the builds pass.

**Comment by kszucs** [comment]
Ok, thanks!

**Comment by xhochy** [comment]
What's the state of this? Are the breakages things we need to fix? Maybe open JIRAs then.

**Comment by kszucs** [comment]
I'll merge this and open jira's as nightly builds are failing.

**Pull request closed without merging**
