### PR TITLE
ARROW-6503: [C++] Add an argument of memory pool object to SparseTensorConverter

### PR DESCRIPTION
**Pull request by mrkn**
In this pull-request, I'd like to add an argument of MemoryPool to SparseTensorConverter, and replace SparseTensorImpl's constructors from Tensor with static factory functions.

### CODE REVIEW

**Comment by mrkn** [comment]
I guess [this failure on Travis CI](https://travis-ci.org/apache/arrow/jobs/601063383) isn't caused by this change.

**Comment by pitrou** [comment]
@mrkn indeed. It's fixed on git master, you can rebase if you want.

**Comment by mrkn** [comment]
@pitrou Thank you for telling me it.  I've rebased on to the master.

**Review by pitrou — APPROVED** [review]
LGTM

**Pull request closed without merging**
