### PR TITLE
ARROW-18067: [C++] Update Boost's SHA256 value

### PR DESCRIPTION
**Pull request by MacChen02**
Update  the thirdparty boost's SHA256 value, the version of boost is  1.75.0.

### CODE REVIEW

**Comment by kou** [comment]
Sorry. The SHA256 isn't for the original Boost 1.75.0's archive. It's for the our trimmed Boost 1.75.0's archive at https://apache.jfrog.io/artifactory/arrow/thirdparty/7.0.0/boost_1_75_0.tar.gz .

**Comment by MacChen02** [comment]
@kou But it fails on my local environment, using a different download link.

**Comment by kou** [comment]
Hmm, could you show your `cmake ...` command line and the output of it?

**Comment by MacChen02** [comment]
@kou my cmake cmd is：
cmake -DARROW_DEPENDENCY_SOURCE=BUNDLED -DARROW_GANDIVA_JAVA=ON -DARROW_GANDIVA=ON -DARROW_PARQUET=ON -DARROW_CSV=ON -DARROW_HDFS=ON -DARROW_BOOST_USE_SHARED=ON -DARROW_JNI=ON -DARROW_DATASET=ON -DARROW_WITH_PROTOBUF=ON -DARROW_WITH_SNAPPY=ON -DARROW_WITH_LZ4=ON -DARROW_FILESYSTEM=ON -DARROW_JSON=ON ..

**Comment by kou** [comment]
Could you also show the output of it?

**Comment by MacChen02** [comment]
@kou em... the jira you closed:
https://issues.apache.org/jira/browse/ARROW-18067

**Comment by kou** [comment]
Reopened.

**Comment by kou** [comment]
Ah, did you mean that you already provided the output of your `cmake` command line in the Jira by screenshot?
Then, please use https://apache.jfrog.io/artifactory/arrow/thirdparty/7.0.0/boost_1_75_0.tar.gz instead of https://sourceforge.net/projects/boost/files/boost/1.75.0/boost_1_75_0.tar.gz .

**Comment by MacChen02** [comment]
@kou My compile operations:
1. # mkdir arrow-apache-arrow-8.0.0/cpp/release-build
2. # cd cpp/release-build
3. # cmake -DARROW_DEPENDENCY_SOURCE=BUNDLED -DARROW_GANDIVA_JAVA=ON -DARROW_GANDIVA=ON -DARROW_PARQUET=ON -DARROW_CSV=ON -DARROW_HDFS=ON -DARROW_BOOST_USE_SHARED=ON -DARROW_JNI=ON -DARROW_DATASET=ON -DARROW_WITH_PROTOBUF=ON -DARROW_WITH_SNAPPY=ON -DARROW_WITH_LZ4=ON -DARROW_FILESYSTEM=ON -DARROW_JSON=ON ..
4. # make 
5. # make install

**Comment by kou** [comment]
Could you show the output of `3.`?

**Comment by kou** [comment]
Ah, sorry. `3.` and `4.`.

**Pull request closed without merging**
