### PR TITLE
[Release] Verify 8.0.0-RC0 [WIP]

### PR DESCRIPTION
**Pull request by kszucs**

### CODE REVIEW

**Comment by kszucs** [comment]
@github-actions crossbow submit --group verify-rc-source --param release=8.0.0 --param rc=0

**Comment by kszucs** [comment]
@github-actions crossbow submit verify-rc-source-*ubuntu*

**Comment by kszucs** [comment]
@github-actions crossbow submit --group verify-rc-source --param release=8.0.0 --param rc=0

**Comment by kszucs** [comment]
@github-actions crossbow submit --group verify-rc-binaries --group verify-rc-wheels --param release=8.0.0 --param rc=0

**Comment by kszucs** [comment]
@github-actions crossbow submit --param release=8.0.0 --param rc=0 verify-rc-binaries-jars-*

**Comment by kszucs** [comment]
@github-actions crossbow submit verify-rc-binaries-apt-linux-amd64

**Comment by kszucs** [comment]
@github-actions crossbow submit --param release=8.0.0 --param rc=0 verify-rc-binaries-apt-linux-amd64

**Comment by kou** [comment]
@kszucs I confirmed it. It's caused by GPG key import error. The following key can't be imported because "Key imported successfully" message isn't shown for the key:

https://github.com/ursacomputing/crossbow/runs/6177081003?check_suite_focus=true#step:7:355

```text
Importing GPG key 0x717D3FB2:
 Userid     : "Neville Dipale <nevime@apache.org>"
 Fingerprint: 3905 F254 F9E5 04B4 0FFF 6CF6 0004 88D7 717D 3FB2
 From       : /etc/pki/rpm-gpg/RPM-GPG-KEY-Apache-Arrow
```

The key uses ed25519:

https://dist.apache.org/repos/dist/release/arrow/KEYS

```text
pub   ed25519 2022-02-19 [SC] [expires: 2024-02-19]
```

It seems that ed25519 isn't supported on AlmaLinux 8.

I'll remove keys that use ed25519 from `apache-arrow-release` RPM that register Yum repository information including GPG keys.

**Comment by kou** [comment]
#13002

**Comment by kszucs** [comment]
Closing in favor of https://github.com/apache/arrow/pull/13013

**Pull request closed without merging**
