### PR TITLE
ARROW-4951: [C++] Turn off cpp benchmarks in cpp docker images

### PR DESCRIPTION
**Pull request by kszucs**

### CODE REVIEW

**Comment by fsaintjacques** [comment]
May I ask why? They act as another compilation test. You can avoid running them by invoking `ctest -L unittest`.

**Comment by kszucs** [comment]
Oops, that was changed recently to [ninja test](https://github.com/apache/arrow/blob/master/ci/docker_build_and_test_cpp.sh#L23). 
Good hint to test the compilation itself, updating it. Thanks!

**Comment by kszucs** [comment]
+1, ci error is unrelated

**Comment by fsaintjacques** [comment]
+1

**Pull request closed without merging**
