### PR TITLE
ARROW-8225: [Rust] Continuation marker check was in wrong location.

### PR DESCRIPTION
**Pull request by maxburke**
In the previous commit I had the continuation marker check in the wrong location.

### CODE REVIEW

**Comment by maxburke** [comment]
Hm; these errors popped up but I'm not sure why they're happening?

```
32 | |
33 | | #[tonic::async_trait]
   | |_____________________^ missing `DoExchangeStream`, `do_exchange` in implementation
   |
   = help: implement the missing item: `type DoExchangeStream = Type;`
   = help: implement the missing item: `fn do_exchange(&'life0 self, _: tonic::request::Request<tonic::codec::decode::Streaming<flight::FlightData>>) -> std::pin::Pin<std::boxed::Box<(dyn core::future::future::Future<Output = std::result::Result<tonic::response::Response<<Self as flight::flight_service_server::FlightService>::DoExchangeStream>, tonic::status::Status>> + std::marker::Send + 'async_trait)>> { unimplemented!() }`
```

Is the trunk broken?

**Comment by nevi-me** [comment]
> Hm; these errors popped up but I'm not sure why they're happening?
> 
> ```
> 32 | |
> 33 | | #[tonic::async_trait]
>    | |_____________________^ missing `DoExchangeStream`, `do_exchange` in implementation
>    |
>    = help: implement the missing item: `type DoExchangeStream = Type;`
>    = help: implement the missing item: `fn do_exchange(&'life0 self, _: tonic::request::Request<tonic::codec::decode::Streaming<flight::FlightData>>) -> std::pin::Pin<std::boxed::Box<(dyn core::future::future::Future<Output = std::result::Result<tonic::response::Response<<Self as flight::flight_service_server::FlightService>::DoExchangeStream>, tonic::status::Status>> + std::marker::Send + 'async_trait)>> { unimplemented!() }`
> ```
> 
> Is the trunk broken?

https://github.com/apache/arrow/pull/6800 will fix the issue

**Comment by nevi-me** [comment]
@maxburke do you perhaps have an example to help me understand the continuation issue? I haven't read the spec in a few weeks/months

**Comment by maxburke** [comment]
@nevi-me https://arrow.apache.org/docs/format/Columnar.html

```
The encapsulated binary message format is as follows:

A 32-bit continuation indicator. The value 0xFFFFFFFF indicates a valid message. This component was introduced in version 0.15.0 in part to address the 8-byte alignment requirement of Flatbuffers

A 32-bit little-endian length prefix indicating the metadata size

The message metadata as using the Message type defined in Message.fbs

Padding bytes to an 8-byte boundary

The message body, whose length must be a multiple of 8 bytes
```

**Comment by paddyhoran** [comment]
@nevi-me I think your original IPC implementation was based on 0.14, right before this change was adopted.

**Review by nevi-me — APPROVED** [review]
Thanks, I've now seen the change from 0.15.0, and understand what this change achieves

**Pull request closed without merging**
