### PR TITLE
ARROW-217: Fix Travis w.r.t conda 4.1.0 changes

### PR DESCRIPTION
**Pull request by xhochy**
Travis is happy, fixes the problems we see with Travis in #85

### CODE REVIEW

**Comment by xhochy** [comment]
For reference:

`conda info -a` some days ago:

```
         channel URLs : https://conda.anaconda.org/apache/osx-64/
                        https://conda.anaconda.org/apache/noarch/
                        https://conda.anaconda.org/conda-forge/osx-64/
                        https://conda.anaconda.org/conda-forge/noarch/
                        https://repo.continuum.io/pkgs/free/osx-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/osx-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
```

now:

```
         channel URLs : https://conda.anaconda.org/apache/osx-64/
                        https://conda.anaconda.org/apache/noarch/
                        https://conda.anaconda.org/conda-forge/osx-64/
                        https://conda.anaconda.org/conda-forge/noarch/
```

i.e. continuum's channels are missing

**Comment by wesm** [comment]
+1, thank you

**Comment by wesm** [comment]
@kalefranz can you or someone on the conda team comment on what may have changed with the channel URLs? thank you =)

**Comment by kalefranz** [comment]
In 4.1.0 we introduced a bug where `defaults` wasn't automatically added to `channels` in `~/.condarc` if the file already existed.

We've fixed it here: https://github.com/conda/conda/pull/2670
4.1.1 will be released with that fix and others in a few hours

In general, as of 4.1.0, channel order now matters.  Before, all channels were thrown together and the package with the highest version comparison won.  Now, if a package exists in a higher priority channel (i.e. the channel comes first in the channel list), then that package wins.

We'll continue to refine and improve on channel/package priority.  This is just a first step.

**Comment by wesm** [comment]
@kalefranz thank you for the quick reply. Per the channel priority, am I correct that the last channel added has the highest priority? (so in our case, apache channel would supercede conda-forge?)

**Comment by kalefranz** [comment]
FYI we're also adding a `auto_update_conda` option that defaults to true, but that can be set to false to disable conda's aggressive self-update.  Definitely useful in some CI situations.  That'll be in both 4.1.1 and 4.0.9 coming out later today.

**Pull request closed without merging**
