### PR TITLE
ARROW-4452: [Python] Serialize sparse torch tensors

### PR DESCRIPTION
**Pull request by pcmoritz**

### CODE REVIEW

**Comment by xhochy** [comment]
Rebased.

**Comment by jorisvandenbossche** [comment]
@pcmoritz @xhochy what's the status of this PR?

**Comment by emkornfield** [comment]
@jorisvandenbossche I think this can probably be merged, unless you have any concerns?

**Comment by jorisvandenbossche** [comment]
I am not familiar with pytorch, so can't really comment on that pytorch specific code, but in general looks good to me.

**Review by wesm — APPROVED** [review]
+1

**Pull request closed without merging**
