### PR TITLE
ARROW-2516: [CI] Filter changes in AppVeyor builds

### PR DESCRIPTION
**Pull request by pitrou**
In AppVeyor PR builds, jobs can be exited early if they test something that the PR doesn't affect.

### CODE REVIEW

**Comment by pitrou** [comment]
Side note: currently, `ci/detect-changes.py` rebuilds everything if the C++ codebase is changed. But do we want to rebuild languages which are reimplementations rather than bindings (e.g. Rust or Java, AFAICT)?

**Comment by pitrou** [comment]
Example build with only Rust changes: https://ci.appveyor.com/project/pitrou/arrow/build/1.0.402

**Review by xhochy — APPROVED** [review]
+1, LGTM

**Comment by xhochy** [comment]
> Side note: currently, ci/detect-changes.py rebuilds everything if the C++ codebase is changed. But do we want to rebuild languages which are reimplementations rather than bindings (e.g. Rust or Java, AFAICT)?

If only C++ is changed, we should only rebuild C++/Python/Glib and not the others.

**Comment by pitrou** [comment]
> If only C++ is changed, we should only rebuild C++/Python/Glib and not the others.

Done.

**Pull request closed without merging**
