### PR TITLE
ARROW-12843: [C++][R] Implement is_inf kernel

### PR DESCRIPTION
**Pull request by lidavidm**

### CODE REVIEW

**Comment by ianmcook** [comment]
Thanks for doing this @lidavidm! You mind if I push a commit to your fork to tweak some of the R stuff?

**Comment by lidavidm** [comment]
Yeah, please go ahead! I admit I'm not familiar with the R side of things and mostly just pattern match on similar code.

**Comment by ianmcook** [comment]
The fact that `is_inf` returns false for `NaN` is inconvenient because its negation returns true.

Both R and NumPy have separate functions to test for finite and invite values, and these all return false for `NaN`:
```r
> is.infinite(NaN)
[1] FALSE
> is.finite(NaN)
[1] FALSE
```
```python
>>> np.isinf(np.nan)
False
>>> np.isfinite(np.nan)
False
```
I wonder if this suggests we should also make an `is_fin` or `is_finite` kernel to avoid this problem of negation.

**Comment by lidavidm** [comment]
Oh, doh. Yes, then having an is_finite kernel would make more sense than just inverting it. I'll update that.

**Comment by ianmcook** [comment]
This also fixes an inconsistency with the `is.na()` method for `Scalar` objects in the R package. Previously that returned a length-1 R logical vector. Now it returns a `Scalar` having the `bool` data type. This was necessary go make `is.finite()` and `is.infinite()` work consistently.

**Review by cyb70289 — APPROVED** [review]
LGTM, +1

**Comment by cyb70289** [comment]
@ianmcook , do you have other comments? Can we merge this PR?

**Comment by ianmcook** [comment]
@cyb70289 No more comments from me, looks good, thanks

**Pull request closed without merging**
