### PR TITLE
ARROW-8323: [C++] Add pragmas wrapping proto_utils.h to disable conversion warnings

### PR DESCRIPTION
**Pull request by bkietz**

### CODE REVIEW

**Comment by bkietz** [comment]
Appveyor failure ( https://ci.appveyor.com/project/ApacheSoftwareFoundation/arrow/builds/31915003/job/1xtypdqr13nnkbtb#L1007 ) is https://issues.apache.org/jira/browse/ARROW-5473

**Comment by kszucs** [comment]
@bkietz could you please add a comment to remove the pin once your fixed is released by grpc?

**Comment by wesm** [comment]
Can we use `#pragma warning(disable:4267)` instead as suggested by @rip-nsk?

**Comment by bkietz** [comment]
@wesm I'll try it, but note that warning is globally disabled via a flag, SetupCxxFlags.cmake:152 (to no effect when combined with `/WX`, evidently)

**Review by kszucs — APPROVED** [review]
LGTM, thanks Ben!

**Comment by bkietz** [comment]
Opened https://jira.apache.org/jira/browse/ARROW-8328 to investigate why the global conversion warning disable is not respected

**Pull request closed without merging**
