### PR TITLE
WIP: [Release] Verify release-18.1.0-rc1

### PR DESCRIPTION
**Pull request by kou**
PR to verify Release Candidate

### CODE REVIEW

**Comment by kou** [comment]
@github-actions crossbow submit  --group verify-rc-source --param release=18.1.0 --param rc=1

**Comment by assignUser** [comment]
Revision: apache-arrow-18.1.0-rc1

Submitted crossbow builds: [ursacomputing/crossbow @ release-18.1.0-rc1-0](https://github.com/ursacomputing/crossbow/branches/all?query=release-18.1.0-rc1-0)

|Task|Status|
|----|------|
|almalinux-8-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11789437734/job/32838200383)|
|almalinux-8-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11789437442/job/32838199409)|
|almalinux-9-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11789437792/job/32838200691)|
|almalinux-9-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11789437842/job/32838200883)|
|amazon-linux-2023-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11789437821/job/32838200747)|
|amazon-linux-2023-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11789438156/job/32838224667)|
|centos-7-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11789437654/job/32838200115)|
|centos-8-stream-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11789437988/job/32838202162)|
|centos-8-stream-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11789437503/job/32838199781)|
|centos-9-stream-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11789437405/job/32838199253)|
|centos-9-stream-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11789437973/job/32838201946)|
|conan-maximum|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11789437296/job/32838198799)|
|conan-minimum|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11789437438/job/32838199493)|
|debian-bookworm-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11789437867/job/32838201375)|
|debian-bookworm-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11789437237/job/32838198508)|
|debian-trixie-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11789437580/job/32838199972)|
|debian-trixie-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11789437289/job/32838198631)|
|java-jars|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11789437500/job/32838202733)|
|matlab|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11789437059/job/32838478206)|
|nuget|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11789438260/job/32838224888)|
|python-sdist|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11789437558/job/32838199911)|
|r-binary-packages|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11789437922/job/32838693002)|
|test-debian-12-docs|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11789437377/job/32838199123)|
|ubuntu-focal-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11789437776/job/32838200415)|
|ubuntu-focal-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11789437965/job/32838201779)|
|ubuntu-jammy-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11789438158/job/32838224675)|
|ubuntu-jammy-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11789437090/job/32838197848)|
|ubuntu-noble-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11789438124/job/32838202937)|
|ubuntu-noble-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11789438139/job/32838203207)|
|wheel-macos-monterey-cp310-cp310-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11789438127/job/32838203003)|
|wheel-macos-monterey-cp310-cp310-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11789438096/job/32838202880)|
|wheel-macos-monterey-cp311-cp311-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11789437234/job/32838198480)|
|wheel-macos-monterey-cp311-cp311-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11789438059/job/32838202513)|
|wheel-macos-monterey-cp312-cp312-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11789437629/job/32838199969)|
|wheel-macos-monterey-cp312-cp312-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11789438066/job/32838202642)|
|wheel-macos-monterey-cp313-cp313-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11789436984/job/32838197406)|
|wheel-macos-monterey-cp313-cp313-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11789437773/job/32838200508)|
|wheel-macos-monterey-cp313-cp313t-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11789437223/job/32838198337)|
|wheel-macos-monterey-cp313-cp313t-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11789438204/job/32838224748)|
|wheel-macos-monterey-cp39-cp39-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11789437303/job/32838198791)|
|wheel-macos-monterey-cp39-cp39-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11789438087/job/32838202719)|
|wheel-manylinux-2-28-cp310-cp310-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11789438252/job/32838224801)|
|wheel-manylinux-2-28-cp310-cp310-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11789437211/job/32838198231)|
|wheel-manylinux-2-28-cp311-cp311-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11789437062/job/32838197613)|
|wheel-manylinux-2-28-cp311-cp311-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11789437095/job/32838197835)|
|wheel-manylinux-2-28-cp312-cp312-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11789437375/job/32838199060)|
|wheel-manylinux-2-28-cp312-cp312-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11789437573/job/32838199888)|
|wheel-manylinux-2-28-cp313-cp313-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11789438015/job/32838202335)|
|wheel-manylinux-2-28-cp313-cp313-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11789437918/job/32838201629)|
|wheel-manylinux-2-28-cp313-cp313t-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11789437055/job/32838197670)|
|wheel-manylinux-2-28-cp313-cp313t-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11789437486/job/32838199570)|
|wheel-manylinux-2-28-cp39-cp39-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11789437700/job/32838200288)|
|wheel-manylinux-2-28-cp39-cp39-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11789438005/job/32838202298)|
|wheel-manylinux-2014-cp310-cp310-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11789438122/job/32838203082)|
|wheel-manylinux-2014-cp310-cp310-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11789436985/job/32838197377)|
|wheel-manylinux-2014-cp311-cp311-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11789437904/job/32838201510)|
|wheel-manylinux-2014-cp311-cp311-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11789438125/job/32838202990)|
|wheel-manylinux-2014-cp312-cp312-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11789437320/job/32838198965)|
|wheel-manylinux-2014-cp312-cp312-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11789437181/job/32838198143)|
|wheel-manylinux-2014-cp313-cp313-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11789437997/job/32838202175)|
|wheel-manylinux-2014-cp313-cp313-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11789437962/job/32838201811)|
|wheel-manylinux-2014-cp313-cp313t-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11789437865/job/32838201522)|
|wheel-manylinux-2014-cp313-cp313t-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11789437705/job/32838200258)|
|wheel-manylinux-2014-cp39-cp39-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11789437855/job/32838201293)|
|wheel-manylinux-2014-cp39-cp39-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11789437276/job/32838198640)|
|wheel-windows-cp310-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11789438302/job/32838224992)|
|wheel-windows-cp311-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11789438100/job/32838202805)|
|wheel-windows-cp312-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11789437201/job/32838198261)|
|wheel-windows-cp313-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11789437833/job/32838200885)|
|wheel-windows-cp39-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11789438239/job/32838224763)|

**Comment by amoeba** [comment]
@github-actions crossbow submit wheel-manylinux-2-28-cp310-cp310-amd64

**Comment by amoeba** [comment]
We need to cherry-pick https://github.com/apache/arrow/pull/44433 and https://github.com/apache/arrow/pull/44482. The packaging jobs may have been submitted with a slight issue so we're going to re-run those next.

**Comment by kou** [comment]
Revision: apache-arrow-18.1.0-rc1

Submitted crossbow builds: [ursacomputing/crossbow @ release-18.1.0-rc1-1](https://github.com/ursacomputing/crossbow/branches/all?query=release-18.1.0-rc1-1)

|Task|Status|
|----|------|
|almalinux-8-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/tree/release-18.1.0-rc1-1-github-almalinux-8-amd64)|
|almalinux-8-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11808355983/job/32896786594)|
|almalinux-9-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11808356236/job/32896788347)|
|almalinux-9-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/tree/release-18.1.0-rc1-1-github-almalinux-9-arm64)|
|amazon-linux-2023-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11808355987/job/32896786615)|
|amazon-linux-2023-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11808355814/job/32896785568)|
|centos-7-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11808355972/job/32896786488)|
|centos-8-stream-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11808355766/job/32896785355)|
|centos-8-stream-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11808356593/job/32896790382)|
|centos-9-stream-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11808356353/job/32896789352)|
|centos-9-stream-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11808356088/job/32896787208)|
|conan-maximum|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11808356435/job/32896789532)|
|conan-minimum|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11808356525/job/32896790173)|
|debian-bookworm-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11808356042/job/32896787065)|
|debian-bookworm-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11808356176/job/32896787881)|
|debian-trixie-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11808356038/job/32896786908)|
|debian-trixie-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/tree/release-18.1.0-rc1-1-github-debian-trixie-arm64)|
|java-jars|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11808356446/job/32896792364)|
|matlab|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11808356358/job/32896791911)|
|nuget|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11808356298/job/32896788961)|
|python-sdist|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11808356554/job/32896790190)|
|r-binary-packages|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11808355820/job/32896800911)|
|test-debian-12-docs|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11808355993/job/32896786628)|
|ubuntu-focal-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11808356508/job/32896790127)|
|ubuntu-focal-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11808356153/job/32896787711)|
|ubuntu-jammy-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11808355882/job/32896786089)|
|ubuntu-jammy-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11808355769/job/32896785198)|
|ubuntu-noble-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11808355946/job/32896786381)|
|ubuntu-noble-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11808355894/job/32896786235)|
|wheel-macos-monterey-cp310-cp310-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11808356621/job/32896790521)|
|wheel-macos-monterey-cp310-cp310-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11808356264/job/32896788901)|
|wheel-macos-monterey-cp311-cp311-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11808355767/job/32896785047)|
|wheel-macos-monterey-cp311-cp311-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11808355808/job/32896785209)|
|wheel-macos-monterey-cp312-cp312-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11808356012/job/32896786701)|
|wheel-macos-monterey-cp312-cp312-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11808356632/job/32896790663)|
|wheel-macos-monterey-cp313-cp313-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11808355799/job/32896785052)|
|wheel-macos-monterey-cp313-cp313-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11808356476/job/32896789810)|
|wheel-macos-monterey-cp313-cp313t-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11808355864/job/32896785863)|
|wheel-macos-monterey-cp313-cp313t-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11808356160/job/32896787712)|
|wheel-macos-monterey-cp39-cp39-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11808356191/job/32896788044)|
|wheel-macos-monterey-cp39-cp39-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11808356623/job/32896790594)|
|wheel-manylinux-2-28-cp310-cp310-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11808355765/job/32896785050)|
|wheel-manylinux-2-28-cp310-cp310-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11808355995/job/32896786738)|
|wheel-manylinux-2-28-cp311-cp311-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11808356241/job/32896788543)|
|wheel-manylinux-2-28-cp311-cp311-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11808355910/job/32896786107)|
|wheel-manylinux-2-28-cp312-cp312-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11808355981/job/32896786568)|
|wheel-manylinux-2-28-cp312-cp312-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11808356184/job/32896787880)|
|wheel-manylinux-2-28-cp313-cp313-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11808355925/job/32896786419)|
|wheel-manylinux-2-28-cp313-cp313-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11808356611/job/32896790457)|
|wheel-manylinux-2-28-cp313-cp313t-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11808355966/job/32896786387)|
|wheel-manylinux-2-28-cp313-cp313t-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11808356174/job/32896787860)|
|wheel-manylinux-2-28-cp39-cp39-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11808355805/job/32896785386)|
|wheel-manylinux-2-28-cp39-cp39-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11808356235/job/32896788417)|
|wheel-manylinux-2014-cp310-cp310-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11808355803/job/32896785065)|
|wheel-manylinux-2014-cp310-cp310-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11808356391/job/32896789274)|
|wheel-manylinux-2014-cp311-cp311-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11808355793/job/32896785295)|
|wheel-manylinux-2014-cp311-cp311-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11808356371/job/32896789460)|
|wheel-manylinux-2014-cp312-cp312-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11808355875/job/32896785878)|
|wheel-manylinux-2014-cp312-cp312-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11808356178/job/32896788025)|
|wheel-manylinux-2014-cp313-cp313-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11808356429/job/32896789498)|
|wheel-manylinux-2014-cp313-cp313-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11808356181/job/32896788035)|
|wheel-manylinux-2014-cp313-cp313t-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11808356066/job/32896787232)|
|wheel-manylinux-2014-cp313-cp313t-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11808356309/job/32896789014)|
|wheel-manylinux-2014-cp39-cp39-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11808356303/job/32896788826)|
|wheel-manylinux-2014-cp39-cp39-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11808356021/job/32896786742)|
|wheel-windows-cp310-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11808355935/job/32896786123)|
|wheel-windows-cp311-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11808356259/job/32896788695)|
|wheel-windows-cp312-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11808356481/job/32896790083)|
|wheel-windows-cp313-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11808356399/job/32896789344)|
|wheel-windows-cp39-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11808356338/job/32896788809)|

**Comment by kou** [comment]
Revision: apache-arrow-18.1.0-rc1

Submitted crossbow builds: [ursacomputing/crossbow @ release-18.1.0-rc1-2](https://github.com/ursacomputing/crossbow/branches/all?query=release-18.1.0-rc1-2)

|Task|Status|
|----|------|
|almalinux-8-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11808498418/job/32897162792)|
|almalinux-8-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/tree/release-18.1.0-rc1-2-github-almalinux-8-arm64)|
|almalinux-9-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/tree/release-18.1.0-rc1-2-github-almalinux-9-amd64)|
|almalinux-9-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/tree/release-18.1.0-rc1-2-github-almalinux-9-arm64)|
|amazon-linux-2023-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/tree/release-18.1.0-rc1-2-github-amazon-linux-2023-amd64)|
|amazon-linux-2023-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11808498646/job/32897164245)|
|centos-7-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11808498946/job/32897166231)|
|centos-8-stream-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11808498698/job/32897164382)|
|centos-8-stream-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/tree/release-18.1.0-rc1-2-github-centos-8-stream-arm64)|
|centos-9-stream-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11808498288/job/32897162037)|
|centos-9-stream-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11808498818/job/32897165266)|
|conan-maximum|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11808498544/job/32897163657)|
|conan-minimum|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11808498615/job/32897163979)|
|debian-bookworm-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11808499180/job/32897167443)|
|debian-bookworm-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11808499167/job/32897167606)|
|debian-trixie-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11808498479/job/32897163099)|
|debian-trixie-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11808498807/job/32897165355)|
|java-jars|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11808498585/job/32897167392)|
|matlab|[GitHub Actions](https://github.com/ursacomputing/crossbow/tree/release-18.1.0-rc1-2-github-matlab)|
|nuget|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11808498931/job/32897166162)|
|python-sdist|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11808498487/job/32897163218)|
|r-binary-packages|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11808498443/job/32897178614)|
|test-debian-12-docs|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11808498950/job/32897166478)|
|ubuntu-focal-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11808498996/job/32897166708)|
|ubuntu-focal-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11808498271/job/32897162061)|
|ubuntu-jammy-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11808498630/job/32897164061)|
|ubuntu-jammy-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11808498712/job/32897164662)|
|ubuntu-noble-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11808499036/job/32897166866)|
|ubuntu-noble-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11808498458/job/32897162914)|
|wheel-macos-monterey-cp310-cp310-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11808498869/job/32897165859)|
|wheel-macos-monterey-cp310-cp310-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11808498939/job/32897166344)|
|wheel-macos-monterey-cp311-cp311-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/tree/release-18.1.0-rc1-2-github-wheel-macos-monterey-cp311-cp311-amd64)|
|wheel-macos-monterey-cp311-cp311-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11808499178/job/32897167384)|
|wheel-macos-monterey-cp312-cp312-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11808498793/job/32897165268)|
|wheel-macos-monterey-cp312-cp312-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11808498876/job/32897165865)|
|wheel-macos-monterey-cp313-cp313-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11808498690/job/32897164386)|
|wheel-macos-monterey-cp313-cp313-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11808498491/job/32897163245)|
|wheel-macos-monterey-cp313-cp313t-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11808498379/job/32897162522)|
|wheel-macos-monterey-cp313-cp313t-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11808498445/job/32897162793)|
|wheel-macos-monterey-cp39-cp39-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11808498696/job/32897164504)|
|wheel-macos-monterey-cp39-cp39-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11808498405/job/32897162542)|
|wheel-manylinux-2-28-cp310-cp310-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11808498515/job/32897163406)|
|wheel-manylinux-2-28-cp310-cp310-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11808498651/job/32897164175)|
|wheel-manylinux-2-28-cp311-cp311-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11808498772/job/32897165000)|
|wheel-manylinux-2-28-cp311-cp311-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11808499022/job/32897166832)|
|wheel-manylinux-2-28-cp312-cp312-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11808498295/job/32897162179)|
|wheel-manylinux-2-28-cp312-cp312-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11808498550/job/32897163605)|
|wheel-manylinux-2-28-cp313-cp313-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11808498703/job/32897164736)|
|wheel-manylinux-2-28-cp313-cp313-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11808498300/job/32897162058)|
|wheel-manylinux-2-28-cp313-cp313t-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11808499101/job/32897167259)|
|wheel-manylinux-2-28-cp313-cp313t-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11808498902/job/32897166119)|
|wheel-manylinux-2-28-cp39-cp39-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11808498947/job/32897166406)|
|wheel-manylinux-2-28-cp39-cp39-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11808498798/job/32897165273)|
|wheel-manylinux-2014-cp310-cp310-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11808499069/job/32897167040)|
|wheel-manylinux-2014-cp310-cp310-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11808498814/job/32897165444)|
|wheel-manylinux-2014-cp311-cp311-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11808498573/job/32897163622)|
|wheel-manylinux-2014-cp311-cp311-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11808498766/job/32897164999)|
|wheel-manylinux-2014-cp312-cp312-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11808498605/job/32897163973)|
|wheel-manylinux-2014-cp312-cp312-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11808498738/job/32897164885)|
|wheel-manylinux-2014-cp313-cp313-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11808498653/job/32897164252)|
|wheel-manylinux-2014-cp313-cp313-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11808498402/job/32897162503)|
|wheel-manylinux-2014-cp313-cp313t-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11808498496/job/32897163271)|
|wheel-manylinux-2014-cp313-cp313t-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11808498296/job/32897162158)|
|wheel-manylinux-2014-cp39-cp39-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11808498729/job/32897164730)|
|wheel-manylinux-2014-cp39-cp39-arm64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11808498991/job/32897166659)|
|wheel-windows-cp310-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11808498378/job/32897162538)|
|wheel-windows-cp311-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11808499059/job/32897166972)|
|wheel-windows-cp312-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11808498474/job/32897162937)|
|wheel-windows-cp313-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11808498317/job/32897162043)|
|wheel-windows-cp39-amd64|[GitHub Actions](https://github.com/ursacomputing/crossbow/actions/runs/11808498689/job/32897164370)|

**Comment by raulcd** [comment]
Closing this as we ended up releasing RC2

**Pull request closed without merging**
