### PR TITLE
ARROW-2412: [Integration] Add nested dictionary test case, skipped for now

### PR DESCRIPTION
**Pull request by TheNeuralBit**
Adds a test case that contains a dictionary-encoded struct and list, both with dictionary-encoded children. As expected Java, C++ and JS all complain about the generated JSON.

### CODE REVIEW

**Comment by emkornfield** [comment]
@TheNeuralBit is this still relevant?

**Comment by TheNeuralBit** [comment]
@emkornfield thanks for asking :) I've let this go way too long
This is supposed to test the use-case described [here](https://lists.apache.org/thread.html/37c0480c4c7a48dd298e8459938444afb901bf01dcebd5f8c5f1dee6@%3Cdev.arrow.apache.org%3E)

This test is designed to fail.. but it's probably worth merging this PR without the `generate` call and create associated JIRAs to fix the places where it fails.

**Comment by TheNeuralBit** [comment]
@trxcllnt could you take a look at this since I added changes to JS to support this use-case?

**Comment by trxcllnt** [comment]
@TheNeuralBit does this mean dictionaries will be able to reference prior dictionaries? yay!

**Comment by TheNeuralBit** [comment]
@trxcllnt yep!

**Comment by wesm** [comment]
I can work on this for C++ but I won't be able to do it until after my work on variable dictionaries (which will also allow implementing Delta dictionaries) for ARROW-3144 is completed, so it could be a week or more

**Comment by TheNeuralBit** [comment]
@wesm understood. Would you want to hold off on merging this until we have it implemented in Java and C++ as well?

**Comment by wesm** [comment]
Yeah, I think we should have 2 implementations that can speak the correct binary with each other

**Comment by trxcllnt** [comment]
@TheNeuralBit btw this change looks good to me, but we should probably add some test cases to validate the reader and writer do the correct thing. We may also encounter some unanswered questions in the process. For example, are there requirements/guarantees that dictionary ids are preserved, or is the implementation free to rewrite the ids of dictionaries as necessary?

@wesm I want to double check, how are you thinking about dictionary deltas, and how it relates to variable dictionaries? The JS has deltas implemented as appending new values to an existing dictionary to create a ChunkedArray. I could see someone wanting to replace or partially update a dictionary, or being confused and assuming that's what the `isDelta` flag does, so I want to ensure JS and C++ are in alignment there.

**Comment by wesm** [comment]
@trxcllnt our arrays are immutable, so to avoid breaking immutability, when a delta is observed, the next RecordBatch produced will have a larger dictionary for the corresponding Field. What I'm working on for ARROW-3144 is making the dictionary part of the ArrayData data structure rather than the Schema/type object. You might contemplate doing something similar in JS if the change goes over well in C++ (I'm pretty sure it's the right thing to do...)

**Comment by trxcllnt** [comment]
@wesm if I recall correctly, the JS implementation did have a special `DictionaryData` subclass of ArrayData, but we eliminated it (and all the other ArrayData subclasses) when we consolidated the functionality into the class we have now, though the `isDelta` flag was an important motivator also.

The Vectors in JS are also immutable, so I really meant we (zero-copy) [concatenate the current dictionary with the delta dictionary](https://github.com/apache/arrow/blob/3eb07b7ed173e2ecf41d689b0780dd103df63a00/js/src/ipc/reader.ts#L360) to create a ChunkedArray.

I'm not sure how familiar you are with the JS, and obviously solve this however you need to in CPP, but in case there's ideas worth cross-pollinating, here's a quick description of how we're doing it in JS:

To ensure all Fields that reference the same dictionary id are always pointing at the same Vector instance, we [store added a `dictionaryVector` pointer to the Dictionary DataType](https://github.com/apache/arrow/blob/3eb07b7ed173e2ecf41d689b0780dd103df63a00/js/src/type.ts#L491). Since this instance is part of the Schema, it's shared across all current and future RecordBatches. We then updated DictionaryArray to [retrieve the `dictionaryVector`](https://github.com/apache/arrow/blob/3eb07b7ed173e2ecf41d689b0780dd103df63a00/js/src/vector/dictionary.ts#L38)  from the shared Dictionary DataType instance, rather than each DictionaryArray having its own pointer to the dictionary.

When the Reader sees new delta DictionaryBatch, it [updates the `dictionaryVector` pointer](https://github.com/apache/arrow/blob/3eb07b7ed173e2ecf41d689b0780dd103df63a00/js/src/ipc/reader.ts#L364) on the Dictionary DataType in the Schema.

This approach ensures that all DictionaryArrays point to the same underlying dictionary instance, even if you created the DictionaryArray before the delta batch was processed. This is safe, since DictionaryArrays that already exist before the delta dictionary is parsed by the reader won't have indices that point beyond the original DictionaryBatch. But if you have a pointer to a DictionaryArray that was created before the delta batch came in, calling `oldDictArray.dictionary` is guaranteed to return you the full, most up-to-date version of that Field's underlying dictionary.

Hope this helps, and let me know if we need to discuss further. I don't want the JS to deviate from the C++ behavior here, and am happy to make changes to align the features if necessary.

**Comment by trxcllnt** [comment]
Ah, I just realized you were responding to my question about how to handle deltas. That's great, and sounds like we're already aligned on this :+1:

**Review by wesm — APPROVED** [review]
+1

**Comment by wesm** [comment]
Can you help create follow up JIRA issues to actually implement this in each language?

**Pull request closed without merging**
