### PR TITLE
ARROW-394: [Integration] Generate tests cases for numeric types, strings, lists, structs

### PR DESCRIPTION
**Pull request by wesm**
Automatically generating testing files from Python.

### CODE REVIEW

**Comment by wesm** [comment]
@julienledem there is some problem on the Java causing record batches to be written in the wrong order to the Arrow file. to reproduce, see the file in this gist: https://gist.github.com/wesm/459d9d53983c7eb29df2bd4fa2cc5219

Now run these commands:

```
java -cp /home/wesm/code/arrow/java/tools/target/arrow-tools-0.1.1-SNAPSHOT-jar-with-dependencies.jar org.apache.arrow.tools.Integration -a sample.arrow -j sample.json -c JSON_TO_ARROW

java -cp /home/wesm/code/arrow/java/tools/target/arrow-tools-0.1.1-SNAPSHOT-jar-with-dependencies.jar org.apache.arrow.tools.Integration -a sample.arrow -j sample-roundtrip.json -c ARROW_TO_JSON
```

The sample-roundtrip.json returned has the record batches written in the opposite order:

https://gist.github.com/wesm/3e3403ae09ac97770fc6e5aa9bce95bc

**Comment by wesm** [comment]
@julienledem I'm running into a difference between our implementations for arrays that have no nulls. In the C++, we are writing buffer metadata with 0 length. In Java, even if there are no nulls, a bitmap with all 1's set is being written out. Since I'm randomly generating data in this PR, occasionally it generates vectors without nulls. I would call this a bug but want to confirm that you agree

**Comment by wesm** [comment]
also cc @jacques-n

**Comment by wesm** [comment]
Rebased after ARROW-395. I'm going to add some more data types to the integration tests, but the empty bitmap issue is a blocker to moving forward

**Comment by wesm** [comment]
I created [ARROW-398](https://issues.apache.org/jira/browse/ARROW-398) for this

**Comment by wesm** [comment]
I'll try to take a crack at one of these today if I can. would be great to get this all closed out this week and plan for the 0.2 release

**Comment by wesm** [comment]
I tried to fix ARROW-400 myself but very quickly ran into issues I don't understand -- I commented in the JIRA.

**Comment by wesm** [comment]
@julienledem unfortunately, the fixes to the above JIRAs have introduced more issues:

```
-- Java producing, C++ consuming
Testing with /home/wesm/code/arrow/integration/data/struct_example.json
Testing with /home/wesm/code/arrow/integration/data/simple.json
Testing with /tmp/tmp3pcm6k6f/dae57b606e734452b29c1179f6557fd7.json
Testing with /tmp/tmp3pcm6k6f/7571e15523864e2bbab476457f2cb733.json
Testing with /tmp/tmp3pcm6k6f/6a1cf54c8019480a8eef1fdfe6432a6e.json
Testing with /tmp/tmp3pcm6k6f/ce4f7bcee205441cb26930b894888e9f.json
Testing with /tmp/tmp3pcm6k6f/0480cd10809245f29cc89e226e4f21f3.json
Testing with /tmp/tmp3pcm6k6f/cc9deadcf69041cbb4e090d345b03990.json
Testing with /tmp/tmp3pcm6k6f/5c6577ab9c0e41ad8a688cad662981c8.json
Testing with /tmp/tmp3pcm6k6f/48e38ce2cbf64eb9bbd2a16a2719ae0f.json
Testing with /tmp/tmp3pcm6k6f/2a2aa1fd9a434f97aa2a1090a3352012.json
Testing with /tmp/tmp3pcm6k6f/455b9448600a4183aad2145ff53a9d0e.json
Testing with /tmp/tmp3pcm6k6f/5ee0455f245541d19d2ee88be9df463d.json
-- C++ producing, Java consuming
Testing with /home/wesm/code/arrow/integration/data/struct_example.json
Command failed: java -cp /home/wesm/code/arrow/java/tools/target/arrow-tools-0.1.1-SNAPSHOT-jar-with-dependencies.jar org.apache.arrow.tools.Integration -a /tmp/tmp7bv1snbc/7762a6d2179a4934bc20a37a60c968db -j /home/wesm/code/arrow/integration/data/struct_example.json -c VALIDATE
With output:
--------------
13:41:19.100 [main] DEBUG i.n.u.i.l.InternalLoggerFactory - Using SLF4J as the default logging framework
13:41:19.108 [main] DEBUG i.n.util.internal.PlatformDependent0 - java.nio.Buffer.address: available
13:41:19.108 [main] DEBUG i.n.util.internal.PlatformDependent0 - sun.misc.Unsafe.theUnsafe: available
13:41:19.109 [main] DEBUG i.n.util.internal.PlatformDependent0 - sun.misc.Unsafe.copyMemory: available
13:41:19.109 [main] DEBUG i.n.util.internal.PlatformDependent0 - direct buffer constructor: available
13:41:19.109 [main] DEBUG i.n.util.internal.PlatformDependent0 - java.nio.Bits.unaligned: available, true
13:41:19.109 [main] DEBUG i.n.util.internal.PlatformDependent0 - java.nio.DirectByteBuffer.<init>(long, int): available
13:41:19.110 [main] DEBUG io.netty.util.internal.Cleaner0 - java.nio.ByteBuffer.cleaner(): available
13:41:19.110 [main] DEBUG i.n.util.internal.PlatformDependent - Java version: 7
13:41:19.110 [main] DEBUG i.n.util.internal.PlatformDependent - -Dio.netty.noUnsafe: false
13:41:19.110 [main] DEBUG i.n.util.internal.PlatformDependent - sun.misc.Unsafe: available
13:41:19.110 [main] DEBUG i.n.util.internal.PlatformDependent - -Dio.netty.noJavassist: false
13:41:19.111 [main] DEBUG i.n.util.internal.PlatformDependent - Javassist: unavailable
13:41:19.111 [main] DEBUG i.n.util.internal.PlatformDependent - You don't have Javassist in your class path or you don't have enough permission to load dynamically generated classes.  Please check the configuration for better performance.
13:41:19.111 [main] DEBUG i.n.util.internal.PlatformDependent - -Dio.netty.tmpdir: /tmp (java.io.tmpdir)
13:41:19.111 [main] DEBUG i.n.util.internal.PlatformDependent - -Dio.netty.bitMode: 64 (sun.arch.data.model)
13:41:19.111 [main] DEBUG i.n.util.internal.PlatformDependent - -Dio.netty.noPreferDirect: false
13:41:19.111 [main] DEBUG i.n.util.internal.PlatformDependent - io.netty.maxDirectMemory: 7481065472 bytes
13:41:19.111 [main] DEBUG i.n.buffer.PooledByteBufAllocator - -Dio.netty.allocator.numHeapArenas: 16
13:41:19.111 [main] DEBUG i.n.buffer.PooledByteBufAllocator - -Dio.netty.allocator.numDirectArenas: 16
13:41:19.111 [main] DEBUG i.n.buffer.PooledByteBufAllocator - -Dio.netty.allocator.pageSize: 8192
13:41:19.111 [main] DEBUG i.n.buffer.PooledByteBufAllocator - -Dio.netty.allocator.maxOrder: 11
13:41:19.111 [main] DEBUG i.n.buffer.PooledByteBufAllocator - -Dio.netty.allocator.chunkSize: 16777216
13:41:19.111 [main] DEBUG i.n.buffer.PooledByteBufAllocator - -Dio.netty.allocator.tinyCacheSize: 512
13:41:19.111 [main] DEBUG i.n.buffer.PooledByteBufAllocator - -Dio.netty.allocator.smallCacheSize: 256
13:41:19.112 [main] DEBUG i.n.buffer.PooledByteBufAllocator - -Dio.netty.allocator.normalCacheSize: 64
13:41:19.112 [main] DEBUG i.n.buffer.PooledByteBufAllocator - -Dio.netty.allocator.maxCachedBufferCapacity: 32768
13:41:19.112 [main] DEBUG i.n.buffer.PooledByteBufAllocator - -Dio.netty.allocator.cacheTrimInterval: 8192
13:41:19.125 [main] DEBUG io.netty.buffer.AbstractByteBuf - -Dio.netty.buffer.bytebuf.checkAccessible: true
13:41:19.127 [main] DEBUG io.netty.util.ResourceLeakDetector - -Dio.netty.leakDetection.level: simple
13:41:19.127 [main] DEBUG io.netty.util.ResourceLeakDetector - -Dio.netty.leakDetection.maxRecords: 4
13:41:19.131 [main] DEBUG i.n.util.ResourceLeakDetectorFactory - Loaded default ResourceLeakDetector: io.netty.util.ResourceLeakDetector@73dfc95e
13:41:19.292 [main] DEBUG o.a.arrow.vector.file.ArrowReader - Footer starts at 1408, length: 408
13:41:19.298 [main] DEBUG org.apache.arrow.tools.Integration - Arrow Input file size: 1826
13:41:19.299 [main] DEBUG org.apache.arrow.tools.Integration - ARROW schema: Schema<struct_nullable: Struct<f1: Int(32, true), f2: Utf8>>
13:41:19.299 [main] DEBUG org.apache.arrow.tools.Integration - JSON Input file size: 4846
13:41:19.299 [main] DEBUG org.apache.arrow.tools.Integration - JSON schema: Schema<struct_nullable: Struct<f1: Int(32, true), f2: Utf8>>
13:41:19.330 [main] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.maxCapacity.default: 32768
13:41:19.330 [main] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.maxSharedCapacityFactor: 2
13:41:19.330 [main] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.linkCapacity: 16
13:41:19.330 [main] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.ratio: 8
13:41:19.332 [main] DEBUG i.n.util.internal.PlatformDependent - org.jctools-core.MpscChunkedArrayQueue: available
13:41:19.343 [main] DEBUG o.a.arrow.vector.file.ArrowReader - RecordBatch at 64, metadata: 256, body: 384
13:41:19.343 [main] DEBUG o.a.arrow.vector.file.ArrowReader - allocated buffer ArrowBuf[9], udle: [9 0..1024]
13:41:19.344 [main] DEBUG o.a.arrow.vector.file.ArrowReader - Buffer in RecordBatch at 0, length: 64
13:41:19.344 [main] DEBUG o.a.arrow.vector.file.ArrowReader - Buffer in RecordBatch at 64, length: 64
13:41:19.344 [main] DEBUG o.a.arrow.vector.file.ArrowReader - Buffer in RecordBatch at 128, length: 64
13:41:19.344 [main] DEBUG o.a.arrow.vector.file.ArrowReader - Buffer in RecordBatch at 192, length: 64
13:41:19.344 [main] DEBUG o.a.arrow.vector.file.ArrowReader - Buffer in RecordBatch at 256, length: 64
13:41:19.344 [main] DEBUG o.a.arrow.vector.file.ArrowReader - Buffer in RecordBatch at 320, length: 64
13:41:19.345 [main] DEBUG o.a.a.vector.schema.ArrowRecordBatch - Buffer in RecordBatch at 0, length: 64
13:41:19.345 [main] DEBUG o.a.a.vector.schema.ArrowRecordBatch - Buffer in RecordBatch at 64, length: 64
13:41:19.345 [main] DEBUG o.a.a.vector.schema.ArrowRecordBatch - Buffer in RecordBatch at 128, length: 64
13:41:19.345 [main] DEBUG o.a.a.vector.schema.ArrowRecordBatch - Buffer in RecordBatch at 192, length: 64
13:41:19.345 [main] DEBUG o.a.a.vector.schema.ArrowRecordBatch - Buffer in RecordBatch at 256, length: 64
13:41:19.345 [main] DEBUG o.a.a.vector.schema.ArrowRecordBatch - Buffer in RecordBatch at 320, length: 64
13:41:19.345 [main] DEBUG o.a.arrow.vector.file.ArrowReader - released buffer ArrowBuf[9], udle: [9 0..1024]
13:41:19.352 [main] DEBUG o.a.arrow.vector.file.ArrowReader - RecordBatch at 704, metadata: 256, body: 448
13:41:19.352 [main] DEBUG o.a.arrow.vector.file.ArrowReader - allocated buffer ArrowBuf[31], udle: [17 0..1024]
13:41:19.352 [main] DEBUG o.a.arrow.vector.file.ArrowReader - Buffer in RecordBatch at 0, length: 64
13:41:19.352 [main] DEBUG o.a.arrow.vector.file.ArrowReader - Buffer in RecordBatch at 64, length: 64
13:41:19.352 [main] DEBUG o.a.arrow.vector.file.ArrowReader - Buffer in RecordBatch at 128, length: 64
13:41:19.353 [main] DEBUG o.a.arrow.vector.file.ArrowReader - Buffer in RecordBatch at 192, length: 64
13:41:19.353 [main] DEBUG o.a.arrow.vector.file.ArrowReader - Buffer in RecordBatch at 256, length: 128
13:41:19.353 [main] DEBUG o.a.arrow.vector.file.ArrowReader - Buffer in RecordBatch at 384, length: 64
13:41:19.353 [main] DEBUG o.a.a.vector.schema.ArrowRecordBatch - Buffer in RecordBatch at 0, length: 64
13:41:19.353 [main] DEBUG o.a.a.vector.schema.ArrowRecordBatch - Buffer in RecordBatch at 64, length: 64
13:41:19.353 [main] DEBUG o.a.a.vector.schema.ArrowRecordBatch - Buffer in RecordBatch at 128, length: 64
13:41:19.353 [main] DEBUG o.a.a.vector.schema.ArrowRecordBatch - Buffer in RecordBatch at 192, length: 64
13:41:19.353 [main] DEBUG o.a.a.vector.schema.ArrowRecordBatch - Buffer in RecordBatch at 256, length: 128
13:41:19.353 [main] DEBUG o.a.a.vector.schema.ArrowRecordBatch - Buffer in RecordBatch at 384, length: 64
13:41:19.353 [main] DEBUG o.a.arrow.vector.file.ArrowReader - released buffer ArrowBuf[31], udle: [17 0..1024]
Incompatible files
Could not load buffers for field f2: Utf8. error message: Buffer too large to resize to 44: 128
13:41:19.356 [main] ERROR org.apache.arrow.tools.Integration - Incompatible files
java.lang.IllegalArgumentException: Could not load buffers for field f2: Utf8. error message: Buffer too large to resize to 44: 128
	at org.apache.arrow.vector.VectorLoader.loadBuffers(VectorLoader.java:84) ~[arrow-tools-0.1.1-SNAPSHOT-jar-with-dependencies.jar:na]
	at org.apache.arrow.vector.VectorLoader.loadBuffers(VectorLoader.java:94) ~[arrow-tools-0.1.1-SNAPSHOT-jar-with-dependencies.jar:na]
	at org.apache.arrow.vector.VectorLoader.load(VectorLoader.java:63) ~[arrow-tools-0.1.1-SNAPSHOT-jar-with-dependencies.jar:na]
	at org.apache.arrow.tools.Integration$Command$3.execute(Integration.java:156) ~[arrow-tools-0.1.1-SNAPSHOT-jar-with-dependencies.jar:na]
	at org.apache.arrow.tools.Integration.run(Integration.java:212) ~[arrow-tools-0.1.1-SNAPSHOT-jar-with-dependencies.jar:na]
	at org.apache.arrow.tools.Integration.main(Integration.java:61) ~[arrow-tools-0.1.1-SNAPSHOT-jar-with-dependencies.jar:na]
Caused by: java.lang.IllegalArgumentException: Buffer too large to resize to 44: 128
	at org.apache.arrow.vector.BaseDataValueVector.truncateBufferBasedOnSize(BaseDataValueVector.java:55) ~[arrow-tools-0.1.1-SNAPSHOT-jar-with-dependencies.jar:na]
	at org.apache.arrow.vector.NullableVarCharVector.loadFieldBuffers(NullableVarCharVector.java:142) ~[arrow-tools-0.1.1-SNAPSHOT-jar-with-dependencies.jar:na]
	at org.apache.arrow.vector.VectorLoader.loadBuffers(VectorLoader.java:82) ~[arrow-tools-0.1.1-SNAPSHOT-jar-with-dependencies.jar:na]
	... 5 common frames omitted

--------------
Traceback (most recent call last):
  File "integration_test.py", line 667, in <module>
    run_all_tests(debug=args.debug)
  File "integration_test.py", line 657, in run_all_tests
    runner.run()
  File "integration_test.py", line 564, in run
    consumer.validate(json_path, arrow_path)
  File "integration_test.py", line 607, in validate
    return self._run(arrow_path, json_path, 'VALIDATE')
  File "integration_test.py", line 604, in _run
    return run_cmd(cmd)
  File "integration_test.py", line 78, in run_cmd
    raise e
  File "integration_test.py", line 70, in run_cmd
    output = subprocess.check_output(cmd, stderr=subprocess.STDOUT)
  File "/home/wesm/anaconda3/lib/python3.5/subprocess.py", line 626, in check_output
    **kwargs).stdout
  File "/home/wesm/anaconda3/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['java', '-cp', '/home/wesm/code/arrow/java/tools/target/arrow-tools-0.1.1-SNAPSHOT-jar-with-dependencies.jar', 'org.apache.arrow.tools.Integration', '-a', '/tmp/tmp7bv1snbc/7762a6d2179a4934bc20a37a60c968db', '-j', '/home/wesm/code/arrow/integration/data/struct_example.json', '-c', 'VALIDATE']' returned non-zero exit status 1
```

I'll create a JIRA with the offending Arrow file

**Comment by wesm** [comment]
Removing the max buffer padding check, the integration test suite passes locally for me:

```
$ python integration_test.py
-- Java producing, C++ consuming
Testing with /home/wesm/code/arrow/integration/data/struct_example.json
Testing with /home/wesm/code/arrow/integration/data/simple.json
Testing with /tmp/tmpqtpj5ole/0ea11fef218c49e4800942847eae40e4.json
Testing with /tmp/tmpqtpj5ole/b83aa62969d54107a15a4a9e04fb16b1.json
Testing with /tmp/tmpqtpj5ole/5868b1813dcb49ada7c9b50b2a9e437a.json
Testing with /tmp/tmpqtpj5ole/10af29c62bd8454b93977d62a2b19d1c.json
Testing with /tmp/tmpqtpj5ole/11ee04e8bdae4d4bafc6aeef199fd94f.json
Testing with /tmp/tmpqtpj5ole/04dbb647812e461aa00d20c013a6fe10.json
Testing with /tmp/tmpqtpj5ole/15fc3fecb37a42da9c313b5fddf33c04.json
Testing with /tmp/tmpqtpj5ole/9e304d6c653245a5bc329d620c060dba.json
Testing with /tmp/tmpqtpj5ole/85ecca29f44b4a0c977e8294b2de4a49.json
Testing with /tmp/tmpqtpj5ole/95d179be346348179e5b0403ab7dd8f7.json
Testing with /tmp/tmpqtpj5ole/3b1a276c292142158b20d34f064d3ec7.json
-- C++ producing, Java consuming
Testing with /home/wesm/code/arrow/integration/data/struct_example.json
Testing with /home/wesm/code/arrow/integration/data/simple.json
Testing with /tmp/tmpqtpj5ole/0ea11fef218c49e4800942847eae40e4.json
Testing with /tmp/tmpqtpj5ole/b83aa62969d54107a15a4a9e04fb16b1.json
Testing with /tmp/tmpqtpj5ole/5868b1813dcb49ada7c9b50b2a9e437a.json
Testing with /tmp/tmpqtpj5ole/10af29c62bd8454b93977d62a2b19d1c.json
Testing with /tmp/tmpqtpj5ole/11ee04e8bdae4d4bafc6aeef199fd94f.json
Testing with /tmp/tmpqtpj5ole/04dbb647812e461aa00d20c013a6fe10.json
Testing with /tmp/tmpqtpj5ole/15fc3fecb37a42da9c313b5fddf33c04.json
Testing with /tmp/tmpqtpj5ole/9e304d6c653245a5bc329d620c060dba.json
Testing with /tmp/tmpqtpj5ole/85ecca29f44b4a0c977e8294b2de4a49.json
Testing with /tmp/tmpqtpj5ole/95d179be346348179e5b0403ab7dd8f7.json
Testing with /tmp/tmpqtpj5ole/3b1a276c292142158b20d34f064d3ec7.json
-- All tests passed!
```

let's see if i can get a green build on Travis CI

**Comment by wesm** [comment]
@xhochy this is all working properly finally. would you mind giving a quick review?

**Comment by wesm** [comment]
Green build on my fork: https://travis-ci.org/wesm/arrow/builds/182761224. I'm going to merge and we can chase up more integration test improvements in subsequent JIRAs.

**Review by xhochy — COMMENTED** [review]
LGTM

**Pull request closed without merging**
