### PR TITLE
ARROW-540: [C++] Build fixes after ARROW-33, PARQUET-866

### PR DESCRIPTION
**Pull request by wesm**

### CODE REVIEW

**Comment by wesm** [comment]
@xhochy Travis repro's the OS X build failure you experienced -- will attempt to fix tomorrow

**Comment by wesm** [comment]
Well,  https://github.com/apache/arrow/pull/325/commits/9070baf552f221cf9a2fea983cb34e962c38dd39 fixes the tests on OS X for me locally. I'm not sure why this bug does not occur on Linux -- I'm not satisfied merging this patch until I understand the discrepancy. Will investigate tomorrow...

**Comment by wesm** [comment]
I realized it's because the PRNG is slightly different because it's a different standard library. I will play with the data generation to make it slightly less corner-case-y.

**Review by xhochy — APPROVED** [review]
+1, will merge to unbreak the build

**Comment by wesm** [comment]
Thanks. The test case that was failing is with a deeply nested list (63 levels deep) — I am not going to bother with tweaking it any further since what's being tested with that test case is something fairly unrelated to slicing (it only needs to not fail)

**Pull request closed without merging**
