### PR TITLE
GH-33920: [C++][CI] Disable Flight SQL in sanitizer job

### LINKED ISSUE #33920: [C++][CI] C++ / AMD64 Ubuntu 22.04 C++ ASAN UBSAN (pull_request) Cancelled after 75m
### Describe the bug, including details regarding any error messages, version, and platform.

**C++ / AMD64 Ubuntu 22.04 C++ ASAN UBSAN** frequently hits the timeout limit of 75 min. Does it make sense to increase the limit in the workflow file?

Examples:
https://github.com/apache/arrow/actions/runs/4035720668/jobs/6937808549
https://github.com/apache/arrow/actions/runs/4034613084/jobs/6935958187

Successful check also takes 1h 5m 4s on the current master:
https://github.com/apache/arrow/actions/runs/4038548251/jobs/6942621768

### Component(s)

Continuous Integration

### PR DESCRIPTION
**Pull request by kou**
### Rationale for this change

We want to reduce CI time.

### What changes are included in this PR?

This disables Flight SQL to use system gRPC and ProtoBuf.
We can reduce build time by avoiding bundled gRPC and ProtoBuf.

### Are these changes tested?

Yes.

### Are there any user-facing changes?

No.
* Closes: #33920

### CODE REVIEW

**Review by westonpace — APPROVED** [review]

**Comment by westonpace** [comment]
I ran this locally and does prevent building protobuf.  We still might also want to turn off GCS (although that can be a separate PR)

**Review by westonpace — CHANGES_REQUESTED** [review]
Actually, I didn't notice, but one of the flight tests is failing.  Maybe flight (and not just flight SQL) require newer protobuf?

**Comment by westonpace** [comment]
I spent quite some time today trying to debug this with no luck.  It is a very consistent failure in this configuration.  I can reproduce with docker.

From what I can tell it is including and linking the correct versions of protobuf and grpc.

gdb isn't terribly useful (grpc's symbols are stripped and so I can't inspect the rpc.context object).

**Comment by js8544** [comment]
I can also reproduce this locally. Here's what I can find out with gdb:

1. The UB happens because `rpc.context.initial_metadata_corked_` is not initialized.
2. The constructor `ClientContext::ClientContext()` is called, but only a few member variables are initialized, `initial_metadata_corked_` is not one of them.
3.  This only happens when UBSAN and ASAN are on. In a regular build `rpc.context` is properly initialized.

**Comment by js8544** [comment]
I found the root cause. GRPC's [`gpr_mu`](https://github.com/grpc/grpc/blob/master/include/grpc/support/sync_posix.h#L28) mutex has different structures depending on whether UBSAN is on. So we have to compile GRPC by ourselves if we want to enable UBSAN.
cc @kou @westonpace

**Comment by kou** [comment]
Good catch!
I've added `-DGRPC_ASAN_SUPPRESSED`.

**Comment by kou** [comment]
+1

Passed in 34min: https://github.com/apache/arrow/actions/runs/4092011740/jobs/7056458825

**Comment by westonpace** [comment]
@js8544 great catch indeed!  Very impressive investigating.  Thanks for looking at it.

**Pull request merged**
