### PR TITLE
ARROW-14022: [Dev] Remove arrow/dev/benchmarking

### PR DESCRIPTION
**Pull request by dianaclarke**
The following directory contains a WIP that hasn't been modified in 3 years [1]:

- arrow/dev/benchmarking

The directory with benchmarking code that is currently in use is here:

- arrow/dev/archery/archery/benchmark

I was asked to answer questions about Arrow benchmarking today, and I naturally traversed into the higher level, WIP, benchmarking directory, but the one in use is nested deeper. Perhaps it's time to remove the WIP directory.

PS. This WIP was the jumping off point for Conbench (https://github.com/conbench/conbench). Much appreciated!

[1] Sadly, the author passed away. Thank you Tanya! RIP ;(

https://www.alumni.caltech.edu/in-memoriam/2019-9-24-tanya-schlusser-bs-99-1

### CODE REVIEW

**Comment by jonkeane** [comment]
I don't see anything wrong with this, though I'll let other folks weigh in who might have used this.

A side note: the lintr warning is totally unrelated, and I have a PR to resolve that separately: https://github.com/apache/arrow/pull/11174

**Comment by dianaclarke** [comment]
> I don't see anything wrong with this, though I'll let other folks weigh in who might have used this.

Nods. I found this work really helpful, so I'm happy it wasn't deleted before I happened to stumble upon it.

Perhaps @pitrou has thoughts on if and where it should live on in the arrow repository. I think he collaborated/reviewed on this work.

**Comment by pitrou** [comment]
I didn't know for Tanya Schlusser :-(

As for the `dev/benchmark` directory, obviously noone has been working on it for years, and we have our own benchmarking solution now. So it would only be useful for historical purposes. If this was already a page in the Sphinx docs it would be easy to move it around and still keep it visible, but as a directory lying around in a random place it doesn't strike me as terribly useful. @nealrichardson @amol- What do you think?

**Comment by dianaclarke** [comment]
An alternative would be to just rename `arrow/dev/benchmarking` to `arrow/dev/research`, so that folks continue to dig until they find the active code in `arrow/dev/archery/archery/benchmark`.

**Comment by amol-** [comment]
> I didn't know for Tanya Schlusser :-(
> 
> As for the `dev/benchmark` directory, obviously noone has been working on it for years, and we have our own benchmarking solution now. So it would only be useful for historical purposes. If this was already a page in the Sphinx docs it would be easy to move it around and still keep it visible, but as a directory lying around in a random place it doesn't strike me as terribly useful. @nealrichardson @amol- What do you think?

Not that I have much context in detail, but in general I think that the repository should reflect how things currently work and any code/docs that doesn't apply to current state of the system is distracting or misleading for people having to understand the codebase. 

Keeping historical knowledge is usually the purpose of the versioning system, so maybe we can delete the directory and add to the current benchmarking code (in a README or similar) a note that is based on the old code with a link to the revision that provides the old code.

**Comment by kszucs** [comment]
> > Keeping historical knowledge is usually the purpose of the versioning system, so maybe we can delete the directory and add to the current benchmarking code (in a README or similar) a note that is based on the old code with a link to the revision that provides the old code.
> 
> That sounds like a good idea to me.

Agree.

**Review by nealrichardson — APPROVED** [review]
I'll add a readme note as a followup

**Pull request closed without merging**
