### PR TITLE
PARQUET-2179: [C++][Parquet] Add a test for skipping repeated fields

### PR DESCRIPTION
**Pull request by fatemehp**
Add a test for `TypedColumnReader::Skip` with repeated values to make it clear that we are skipping values and not records.
Also, add some comments to the existing test for Skip of non-repeated values.

### CODE REVIEW

**Comment by fatemehp** [comment]
@emkornfield can you merge this pull request? You already reviewed it, but the pull request was not against the master. This includes some commits that are already checked in. I am not sure how to remove them. You can try looking at the changes from "Merge pull request #1 from fatemehp/skip_test".

**Comment by emkornfield** [comment]
@fatemehp it looks like this merged commits from the SkipRecords with the additional tests for Skip method that only skips values, could you remove some of the commits?

**Comment by fatemehp** [comment]
This is a test for TypedColumnReader::Skip, and not relevant to the RecordReader. I am trying to keep the changes small and self-contained.

**Comment by fatemehp** [comment]
@emkornfield yes, there are some commits here that are not part of this change. I will remove them.

**Comment by fatemehp** [comment]
Ok, I think I have fixed this. @emkornfield, could you take a look and merge this change if everything looks good? Thanks!

**Review by pitrou — APPROVED** [review]
+1, thank you @fatemehp

**Comment by pitrou** [comment]
Let's wait for CI before merging this.

**Comment by pitrou** [comment]
CI failures are unrelated.

**Pull request merged**
