### PR TITLE
GH-36642: [Python][CI] Configure warnings as errors during pytest

### LINKED ISSUE #32892: [Python] ResourceWarnings raised by s3 related tests
Running the python tests give a lot of the following warnings:

```Java

opt/conda/envs/arrow/lib/python3.9/site-packages/pyarrow/tests/test_fs.py::test_s3fs_limited_permissions_create_bucket
  /opt/conda/envs/arrow/lib/python3.9/site-packages/pyarrow/tests/util.py:439: ResourceWarning: unclosed file <_io.TextIOWrapper name=29 encoding='utf-8'>
    _run_mc_command(mcdir, 'admin', 'policy', 'add',
  Enable tracemalloc to get traceback where the object was allocated.
  See https://docs.pytest.org/en/stable/how-to/capture-warnings.html#resource-warnings for more info.
```

Ideally we should ensure the tests don't give such warnings (it also makes other warning we should notice less visible)

**Reporter**: [Joris Van den Bossche](https://issues.apache.org/jira/browse/ARROW-17651) / @jorisvandenbossche
#### Related issues:
- [[Python] Reduce warnings during tests](https://github.com/apache/arrow/issues/33563) (is a child of)

<sub>**Note**: *This issue was originally created as [ARROW-17651](https://issues.apache.org/jira/browse/ARROW-17651). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

### LINKED ISSUE #36642: [Python][CI] Configure warnings as errors during build/test
### Describe the enhancement requested

Warnings are continuously being introduced into the pyarrow tests. Let's enforce warnings as errors in at least one CI build (probably one that covers latest versions of python/dependencies).

### Component(s)

Python

### PR DESCRIPTION
**Pull request by danepitkin**
### Rationale for this change

Warnings are constantly being introduced into the pyarrow tests. Let's try enforcing them as errors in an effort to keep the codebase healthy.

### What changes are included in this PR?

* Fixed existing warnings
* Set warnings as errors in CI

### Are these changes tested?

Yes, ran pytests locally w/o warnings.

### Are there any user-facing changes?

No
* Closes: #36642
* Closes: #32892

### CODE REVIEW

**Comment by danepitkin** [comment]
I enabled warnings as errors for conda python 3.8 through 3.11 and for conda python pandas integration to see what happens. Realistically, we probably want to limit warnings to just the latest python version (currently 3.11).

**Comment by danepitkin** [comment]
@github-actions crossbow submit test-conda-python*

**Comment by danepitkin** [comment]
For python 3.8 through 3.11 there is only 1 warning (repeated in 5 test cases).

```
____________________ ERROR at setup of test_read_s3fs[True] ____________________
___________________ ERROR at setup of test_read_s3fs[False] ____________________
_______________ ERROR at setup of test_read_directory_s3fs[True] _______________
______________ ERROR at setup of test_read_directory_s3fs[False] _______________
__________ ERROR at setup of test_write_metadata_fs_file_combinations __________

cls = <class '_pytest.runner.CallInfo'>
func = <function call_runtest_hook.<locals>.<lambda> at 0x7fd5884620f0>
when = 'setup'
reraise = (<class '_pytest.outcomes.Exit'>, <class 'KeyboardInterrupt'>)

    @classmethod
    def from_call(
        cls,
        func: "Callable[[], TResult]",
        when: "Literal['collect', 'setup', 'call', 'teardown']",
        reraise: Optional[
            Union[Type[BaseException], Tuple[Type[BaseException], ...]]
        ] = None,
    ) -> "CallInfo[TResult]":
        """Call func, wrapping the result in a CallInfo.
    
        :param func:
            The function to call. Called without arguments.
        :param when:
            The phase in which the function is called.
        :param reraise:
            Exception or exceptions that shall propagate if raised by the
            function, instead of being wrapped in the CallInfo.
        """
        excinfo = None
        start = timing.time()
        precise_start = timing.perf_counter()
        try:
>           result: Optional[TResult] = func()

opt/conda/envs/arrow/lib/python3.9/site-packages/_pytest/runner.py:341: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
opt/conda/envs/arrow/lib/python3.9/site-packages/_pytest/runner.py:262: in <lambda>
    lambda: ihook(item=item, **kwds), when=when, reraise=reraise
opt/conda/envs/arrow/lib/python3.9/site-packages/pluggy/_hooks.py:433: in __call__
    return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
opt/conda/envs/arrow/lib/python3.9/site-packages/pluggy/_manager.py:112: in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
opt/conda/envs/arrow/lib/python3.9/site-packages/_pytest/unraisableexception.py:83: in pytest_runtest_setup
    yield from unraisable_exception_runtest_hook()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

    def unraisable_exception_runtest_hook() -> Generator[None, None, None]:
        with catch_unraisable_exception() as cm:
            yield
            if cm.unraisable:
                if cm.unraisable.err_msg is not None:
                    err_msg = cm.unraisable.err_msg
                else:
                    err_msg = "Exception ignored in"
                msg = f"{err_msg}: {cm.unraisable.object!r}\n\n"
                msg += "".join(
                    traceback.format_exception(
                        cm.unraisable.exc_type,
                        cm.unraisable.exc_value,
                        cm.unraisable.exc_traceback,
                    )
                )
>               warnings.warn(pytest.PytestUnraisableExceptionWarning(msg))
E               pytest.PytestUnraisableExceptionWarning: Exception ignored in: <socket.socket fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6>
E               
E               Traceback (most recent call last):
E                 File "/opt/conda/envs/arrow/lib/python3.9/site-packages/_pytest/fixtures.py", line 902, in call_fixture_func
E                   fixture_result = fixturefunc(**kwargs)
E               ResourceWarning: unclosed <socket.socket fd=189, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 35258), raddr=('127.0.0.1', 56633)>

opt/conda/envs/arrow/lib/python3.9/site-packages/_pytest/unraisableexception.py:78: PytestUnraisableExceptionWarning
```

**Comment by danepitkin** [comment]
@github-actions crossbow submit test-conda-python*

**Comment by danepitkin** [comment]
@github-actions crossbow submit test-conda-python*

**Review by kou — APPROVED** [review]
+1

BTW, are you interested in taking over https://github.com/apache/arrow/pull/36745 from me...?

**Comment by danepitkin** [comment]
Hey @kou, sure I can take a look!

**Comment by kou** [comment]
Thanks!

**Pull request merged**
