### PR TITLE
ARROW-7980: [Python] Fix creation of tz-aware datetime dtype on first pandas import

### PR DESCRIPTION
**Pull request by jorisvandenbossche**

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
This is not that straightforward to test: the test I added failed on master in isolation (and is now fixed with this patch), but it passed anyway when running the full test suite (since by the time that test is ran, another test already caused the pandas import checks to have run).

I could do something with a subprocess to ensure we check this "fresh", but not sure that is worth the trouble (does pytest provide some helper for this?)

**Comment by pitrou** [comment]
I agree this should be tested in isolation. `subprocess.check_call` should be easy enough for this.

**Comment by wesm** [comment]
Done, and added a utility to make it easier to write such tests requiring isolation in the future

**Review by wesm — APPROVED** [review]
+1. Appveyor build https://ci.appveyor.com/project/jorisvandenbossche/arrow/builds/31280962

**Comment by jorisvandenbossche** [comment]
@wesm Thanks for adding the test!

**Pull request closed without merging**
