### PR TITLE
ARROW-7260: [CI] Remove Ubuntu 14.04 test job

### PR DESCRIPTION
**Pull request by kou**
https://circleci.com/gh/ursa-labs/crossbow/5329

    /arrow/cpp/src/arrow/dataset/filter_test.cc:80:194: error: invalid suffix on literal; C++11 requires a space between literal and identifier [-Werror=literal-suffix]
       ASSERT_EQ("a"_.ToString(), "a");
                    ^

We drop support for Ubuntu 14.04 because it reaches EOL.

### CODE REVIEW

**Comment by kou** [comment]
@ursabot crossbow submit test-ubuntu-14.04-cpp test-ubuntu-16.04-cpp test-ubuntu-18.04-cpp

**Comment by kou** [comment]
There are some "regex_error" on Ubuntu 14.04: https://circleci.com/gh/ursa-labs/crossbow/5368
```text
[ RUN      ] TestPartitionScheme.Hive
unknown file: Failure
C++ exception with description "regex_error" thrown in the test body.
[  FAILED  ] TestPartitionScheme.Hive (1 ms)
```

**Comment by pitrou** [comment]
I don't understand: what does ccache have to do in this?

**Comment by kou** [comment]
I don't know details why ccache + g++ doesn't work (I didn't look into this deeply) but it seems that ccache drops `-std=gnu++11`.

**Comment by pitrou** [comment]
Instead of disabling ccache, what happens if we disable the warning? (`-Wno-literal-suffix`)

(also, we could simply drop 14.04 as suggested on the ML)

**Comment by fsaintjacques** [comment]
Very odd that ccache fixes this, I'd also vote to disable the warning.

**Comment by kou** [comment]
The error has gone but there are still another errors:

```text
/arrow/cpp/src/arrow/dataset/filter_test.cc:80:196: error: expected ')' before 'a'
   ASSERT_EQ("a"_.ToString(), "a");
                                                                                                                                                                                                    ^
```

BTW, why do you want to use ccache here? We disable reusing ccache cache over containers for now: https://github.com/apache/arrow/blob/master/ci/scripts/cpp_build.sh#L37

So we can't improve build performance by ccache for now.

**Comment by kou** [comment]
It seems that g++ 4.8 doesn't support `[^...]` regular expression.

It seems that g++ 4.9 or later is required: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=53631

**Comment by kou** [comment]
@ursabot crossbow submit test-ubuntu-14.04-cpp test-ubuntu-16.04-cpp test-ubuntu-18.04-cpp

**Comment by kou** [comment]
@ursabot crossbow submit test-ubuntu-16.04-cpp test-ubuntu-18.04-cpp

**Comment by kou** [comment]
Removed Ubuntu 14.04 CI job because nobody wants to keep this job: https://lists.apache.org/thread.html/855eb103d9a58923730af4740404d6c2ba3fa8b3e4e052f09c433d5e@%3Cdev.arrow.apache.org%3E

**Comment by kou** [comment]
Green. I'll merge this.

**Pull request closed without merging**
