### PR TITLE
ARROW-9004: [C++][Gandiva] Support building with LLVM 10

### PR DESCRIPTION
**Pull request by kou**
LLVM 7 and 8 are still supported.

Clang Tools still use 8 because Clang Tools 10 reports an error for
RaipdJSON in sanitizer build. We should work on this as a separated
task.

e.g.:

https://github.com/kou/arrow/runs/725786805?check_suite_focus=true

    /usr/include/rapidjson/internal/stack.h:117:13: runtime error: applying non-zero offset 16 to null pointer
         #0 0x7f4d336c0e2c in void arrow::rapidjson::internal::Stack<arrow::rapidjson::CrtAllocator>::Reserve<arrow::rapidjson::GenericValue<arrow::rapidjson::UTF8<char>, arrow::rapidjson::MemoryPoolAllocator<arrow::rapidjson::CrtAllocator> > >(unsigned long) /usr/include/rapidjson/internal/stack.h:117:13

Ubuntu 16.04 still use LLVM 8 because LLVM 10 requires C++ 14 but g++
5 on Ubuntu 16.04 is too old to use
cpp/src/arrow/vendored/datetime/date.h.

CentOS 8 packages still use LLVM 8 because there are no packages for
LLVM 10 on CentOS 8.

manylinux1 still use LLVM 8 because g++ 4.8.2 is old to build LLVM 9
or later.

Conda package for Windows still use LLVM 8 because llvmdev 9 or later
use Visual Studio 2017. We need to use Visual Studio 2017 not 2015 to
use llvmdev 9 or later.

### CODE REVIEW

**Comment by kou** [comment]
@github-actions crossbow submit -g nightly

**Comment by pprudhvi** [comment]
Didn't we recently upgrade to llvm 9? Why jump to llvm10 so early?

**Comment by wesm** [comment]
@pprudhvi as it says in the PR description LLVM 7 and 8 are still supported

**Comment by kou** [comment]
@pprudhvi Because I found a trouble with Gandiva + LLVM 9: https://github.com/apache/arrow/pull/7280#issuecomment-635634955

I need help from Gandiva experts or LLVM experts to solve it but nobody doesn't help for now.

I started working on LLVM 10 support to break the problem down. If the problem is reproducible with LLVM 10, it will be a Gandiva problem. If the problem isn't reproducible with LLVM 10, it will be a LLVM 9 problem.

The problem isn't occurred with LLVM 10. It may be a LLVM 9 problem.

If you think that we should support LLVM 9, could you take a look https://github.com/apache/arrow/pull/7280#issuecomment-635634955 ?

**Comment by kou** [comment]
@github-actions crossbow submit -g nightly

**Comment by kou** [comment]
The "Python Cron / AMD64 Conda Python 3.7 Dask latest" failure is unrelated to this change.

Some nightly failures are also unrelated to this change.

I want to merge this in this week if nobody objects it.

**Comment by wesm** [comment]
No objections from me

**Comment by kou** [comment]
No objections.
I'll merge this.

**Pull request closed without merging**
