### PR TITLE
ARROW-12704: [JS] Support and use optional chaining

### PR DESCRIPTION
**Pull request by domoritz**
Optional chaining makes the code more concise and easier to reason about. 

Needs a fork of esm because of https://github.com/standard-things/esm/issues/866.

### CODE REVIEW

**Review by trxcllnt — APPROVED** [review]

**Comment by kou** [comment]
@domoritz Could you also rebase on master and update the pull request description?

**Comment by domoritz** [comment]
I merged master and updated the description.

**Comment by domoritz** [comment]
I also merged this branch into the follow-up at https://github.com/apache/arrow/pull/10281. No idea why this one is failing.

**Comment by kou** [comment]
Thanks. These failures are unrelated.

**Pull request closed without merging**
