### PR TITLE
ARROW-15096: [R] Sanitizer failures with duration type

### PR DESCRIPTION
**Pull request by paleolimbot**
This PR is an attempt to fix the [sanitizer failure](https://dev.azure.com/ursacomputing/crossbow/_build/results?buildId=17171&view=logs&j=0da5d1d9-276d-5173-c4c4-9d4d4ed14fdb&t=d9b15392-e4ce-5e4c-0c8c-b69645229181&l=12824) caused by ARROW-14941 (#11850). @jonkeane could you remind me how to submit a job to the sanitizer checker?

### CODE REVIEW

**Comment by jonkeane** [comment]
@github-actions crossbow submit test-ubuntu-18.04-r-sanitizer test-ubuntu-18.04-r-sanitizer

**Comment by jonkeane** [comment]
@github-actions crossbow submit test-fedora-r-clang-sanitizer

Oops, I duplicated the first instead of adding this one second 🙃

**Comment by pitrou** [comment]
Looking at the logs, it seems there's another issue as well:
```

2021-12-14T15:47:09.4969247Z array_to_vector.cpp:929:13: runtime error: downcast of address 0x607000047fb0 which does not point to an object of type 'TimeType'
2021-12-14T15:47:09.4969957Z 0x607000047fb0: note: object is of type 'arrow::DurationType'
2021-12-14T15:47:09.4970338Z  01 00 00 00  48 19 50 0c 7e 7f 00 00  80 70 1c 00 30 60 00 00  00 00 00 00 00 00 00 00  21 00 00 00
2021-12-14T15:47:09.4970656Z               ^~~~~~~~~~~~~~~~~~~~~~~
2021-12-14T15:47:09.4971078Z               vptr for 'arrow::DurationType'
2021-12-14T15:47:09.4971961Z     #0 0x7f7dfb6e8be3 in arrow::r::Converter_Duration<long, arrow::TimeType>::TimeUnit_multiplier(std::shared_ptr<arrow::Array> const&) const (/usr/local/RDsan/lib/R/site-library/arrow/libs/arrow.so+0x1b974be3)
2021-12-14T15:47:09.4973033Z     #1 0x7f7dfb6d1377 in arrow::r::Converter_Duration<long, arrow::TimeType>::Ingest_some_nulls(SEXPREC*, std::shared_ptr<arrow::Array> const&, long, long, unsigned long) const (/usr/local/RDsan/lib/R/site-library/arrow/libs/arrow.so+0x1b95d377)
2021-12-14T15:47:09.4973956Z     #2 0x7f7dfb6259bc in arrow::r::Converter::ScheduleConvertTasks(arrow::r::RTasks&, std::shared_ptr<arrow::r::Converter>)::{lambda()#1}::operator()() const /arrow/r/src/array_to_vector.cpp:88
```

**Review by pitrou — APPROVED** [review]
Thanks a lot for fixing this @paleolimbot .

**Pull request closed without merging**
