### PR TITLE
GH-35736: [C++] Fix compile key_map_avx2.cc

### LINKED ISSUE #35736: [C++] Fix key_map_avx2.cc comiple.
### key_map_avx2.cc compile error.

when i use cmake -DARROW_SIMD_LEVEL=AVX2, i catch this error.
```
/home/light/arrow/cpp/src/arrow/compute/key_map_avx2.cc: In member function 'int arrow::compute::SwissTable::early_filter_imp_avx2_x32(int, const uint32_t*, uint8_t*, uint8_t*) const':
/home/light/arrow/cpp/src/arrow/compute/key_map_avx2.cc:216:3: error: 'ARROW_DCHECK' was not declared in this scope
  216 |   ARROW_DCHECK(log_blocks_ <= 4);
      |   ^~~~~~~~~~~~
/home/light/arrow/cpp/src/arrow/compute/key_map_avx2.cc: In member function 'int arrow::compute::SwissTable::extract_group_ids_avx2(int, const uint32_t*, const uint8_t*, uint32_t*, int, int, int) const':
/home/light/arrow/cpp/src/arrow/compute/key_map_avx2.cc:377:3: error: 'ARROW_DCHECK' was not declared in this scope
  377 |   ARROW_DCHECK(byte_size == 1 || byte_size == 2 || byte_size == 4);
      |   ^~~~~~~~~~~~
make[2]: *** [src/arrow/CMakeFiles/arrow_objlib.dir/build.make:2071: src/arrow/CMakeFiles/arrow_ob
```

### Component(s)

C++

### PR DESCRIPTION
**Pull request by Light-City**
Add missing include for `ARROW_DCHECK`.

* Closes: #35736

### CODE REVIEW

**Review by pitrou — APPROVED** [review]
+1, thanks @Light-City (but next time, please make PR text more descriptive!)

**Comment by pitrou** [comment]
@kou Have you already seen this GLib compile error (which seems unrelated to this PR):
https://github.com/apache/arrow/actions/runs/5065962799/jobs/9098866403#step:10:190

```

[44/121] Compiling C++ object arrow-glib/libarrow-glib-1300.dll.p/compute.cpp.obj
In file included from ../../c_glib/arrow-glib/compute.cpp:28:
../../c_glib/arrow-glib/error.hpp: In instantiation of 'gboolean garrow::check(GError**, const arrow::Status&, CONTEXT_FUNC&&) [with CONTEXT_FUNC = garrow_array_cast(GArrowArray*, GArrowDataType*, GArrowCastOptions*, GError**)::<lambda()>&; gboolean = int; GError = _GError]':
../../c_glib/arrow-glib/error.hpp:71:17:   required from 'gboolean garrow::check(GError**, const arrow::Result<T>&, CONTEXT_FUNC&&) [with TYPE = std::shared_ptr<arrow::Array>; CONTEXT_FUNC = garrow_array_cast(GArrowArray*, GArrowDataType*, GArrowCastOptions*, GError**)::<lambda()>; gboolean = int; GError = _GError]'
../../c_glib/arrow-glib/compute.cpp:4609:20:   required from here
../../c_glib/arrow-glib/error.hpp:49:19: warning: moving a temporary object prevents copy elision [-Wpessimizing-move]
   49 |       std::string context = std::move(context_func());
      |                   ^~~~~~~
../../c_glib/arrow-glib/error.hpp:49:19: note: remove 'std::move' call
```

**Comment by pitrou** [comment]
I rebased, perhaps this will fix the error.

**Comment by Light-City** [comment]
> lease make PR text more descriptive!)

ok

**Pull request merged**
