### PR TITLE
ARROW-12895: [CI] Use "concurrency" setting on Github Actions to cancel stale jobs

### PR DESCRIPTION
**Pull request by pitrou**
We're currently using a dedicated Github Actions to cancel previous jobs when a new job is queued. It seems this now can be done better using the "concurrency" setting (unfortunately in beta):
https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#concurrency

### CODE REVIEW

**Comment by pitrou** [comment]
Note that the "cancel stale runs" workflow is run from git master, so removing it will only be effective once this PR is merged.

**Comment by pitrou** [comment]
cc @potiuk FYI

**Comment by pitrou** [comment]
Note I've checked this on my fork but PR runs may be slightly different.

**Comment by potiuk** [comment]
Cool!

**Review by potiuk — APPROVED** [review]

**Comment by kou** [comment]
Great!

The configuration cancels pending jobs for the master branch, right?
I think that it's better that we don't cancel jobs for the master branch. (We may be able to use `github.event.number` for it. It'll be a number for pull requests and `null` for the master branch.)

**Comment by kou** [comment]
>  (We may be able to use `github.event.number` for it. It'll be a number for pull requests and `null` for the master branch.)

Ah, this doesn't help. Please ignore this.

**Comment by kszucs** [comment]
> The configuration cancels pending jobs for the master branch, right?

If I understand correctly this change should cancel pull request builds as well, like subsequent pushes to the same PR.

**Comment by potiuk** [comment]
> If I understand correctly this change should cancel pull request builds as well, like subsequent pushes to the same PR.

Yep

**Review by kszucs — APPROVED** [review]
It is definitely an improvement over the previous approach.

According to the GHA documentation the changes look good to me. I assume we can ignore the Julia build errors since those are unrelated.

**Comment by pitrou** [comment]
Uh, it seems this may not be working as expected. Here is a unexpectedly cancelled job:
https://github.com/apache/arrow/actions/runs/914966579

**Comment by pitrou** [comment]
Perhaps that's because the `pull_request_target` event doesn't fill the `github.*` variables similarly as the `pull_request` event.

**Comment by pitrou** [comment]
Fix filed in https://github.com/apache/arrow/pull/10467

**Pull request closed without merging**
