### PR TITLE
ARROW-6459: [C++] Remove "python" from conda_env_cpp.txt

### PR DESCRIPTION
**Pull request by AlenkaF**
This PR tries to remove python from the dependency list for cpp CI builds.

There is also a question of keeping Python as a dependency in the Arrow C++ for linting purposes, see https://github.com/apache/arrow/blob/47314c3999d7b7a7f9167c6ed6793da756c411a1/cpp/CMakeLists.txt#L179-L192

### CODE REVIEW

**Comment by AlenkaF** [comment]
@github-actions crossbow submit *python*

**Comment by AlenkaF** [comment]
Removal of python from the dependency list for cpp CI builds seems to not break anything, the extended builds failures are not new AFAIK. And Travis issue has a [JIRA already](https://issues.apache.org/jira/browse/ARROW-17715).
@raulcd do you think I should run any extra builds?

[ARROW-6459](https://issues.apache.org/jira/browse/ARROW-6459) would be closed with this PR. There is still a question about keeping Python in the Arrow C++ for linter purposes, see [comment on the JIRA issue](https://issues.apache.org/jira/browse/ARROW-6459). Any opinion on that? cc @pitrou @jorisvandenbossche @kszucs

I can open a new issue if we think we should change anything with Python and linter scripts for Arrow C++.

**Comment by pitrou** [comment]
> There is also a question of keeping Python as a dependency in the Arrow C++ for linting purposes, see

This should be separate. Linting is only for developers of Arrow, and shouldn't be involved in packaging builds :-)

**Comment by jorisvandenbossche** [comment]
> This should be separate. Linting is only for developers of Arrow, and shouldn't be involved in packaging builds :-)

Yes, but we for example also include "gtest" in the base cpp env file, which is also only for developers? (although testing is also useful for checking non-development installs of course) 
Should we have a separate `conda_env_cpp_dev.yml` to incude Python? Or if we assume linting is done through archery, then the `conda_env_archery.txt` already includes Python (implicitly), so then we are all good already.

**Comment by jorisvandenbossche** [comment]
At the moment you still need "a" Python available on your system when building Arrow C++, because the cmake files look for Python for the lint targets (and AFAIK this is always done, and you can't turn this off. But maybe we should change this and make this optional?) 
So as long that's the case, it maybe makes sense to keep Python in the conda env? (although for linting it probably doesn't matter whether it's some system python that is used instead)

**Comment by AlenkaF** [comment]
I suggest closing this PR for now (and JIRA issue also?). We could open a separate JIRA for the topic of making Python for linting targets optional and see if there is a need or wish to do so.

**Comment by jorisvandenbossche** [comment]
Sounds good. I will move my comment about non-optionally needing Python for building C++ to the JIRA.

**Pull request closed without merging**
