### PR TITLE
ARROW-977: [java] Add Timezone aware timestamp vectors

### PR DESCRIPTION
**Pull request by julienledem**

### CODE REVIEW

**Comment by julienledem** [comment]
@wesm follow up on https://github.com/apache/arrow/pull/568
cleaning up the templates

**Comment by julienledem** [comment]
@wesm rebased

**Review by wesm — APPROVED** [review]
+1. Can you update the PR title to be `ARROW-977: ... `

**Comment by julienledem** [comment]
@wesm: fixed. Sorry about that

**Comment by wesm** [comment]
Since we now have 8 timestamp classes in Java, if there is any way to simplify in the near future to limit the collateral damage in downstream projects of future API changes, that would be great

**Pull request closed without merging**
