### PR TITLE
ARROW-2744: [C++] Avoid creating list arrays with a null values buffer

### PR DESCRIPTION
**Pull request by pitrou**

### CODE REVIEW

**Review by wesm — COMMENTED** [review]
As a matter of usability, I don't know that we should expect all public API users to create a length-0 buffer when there is no data. I believe that code that interacts with the buffers in an array needs to treat length-0 and null equivalently.

A possibly extreme approach to resolve the issue would be to have a length-0 singleton `kNullBuffer`. But to really sanitize well, we would need to check every buffer going into `ArrayData::Make`, which would have negative performance implications. We could do the null check in the array containers, e.g. right here: https://github.com/apache/arrow/blob/master/cpp/src/arrow/array.h#L350. 

Allowing the result of `values()` to be null means more tests to write to make sure that code doesn't break in that edge case.

Another side of this is that for validity bitmaps, it would be incorrect to return a length-0 buffer in the event that there are no nulls, but right now we permit that buffer to be null. In Java they allocate an array of all set bits, which I don't think we should do. So any way you slice it, some code will have to deal with the null buffer case. 

My gut feeling is that we should allow the null buffers and document the issue well so that users can defend themselves from untrusted data.

**Comment by pitrou** [comment]
@wesm 

> As a matter of usability, I don't know that we should expect all public API users to create a length-0 buffer when there is no data.

I don't think this PR is doing that, except in `Array::Validate`.

> I believe that code that interacts with the buffers in an array needs to treat length-0 and null equivalently.

I agree. The parquet-cpp issue was already fixed in https://github.com/apache/parquet-cpp/pull/474

However, I think it's also safer to ensure that we don't generate such buffers unwillingly. I don't think it was deliberate for `ListBuilder` and `StructBuilder` to create null buffers for arrays with 0 child values.

> So any way you slice it, some code will have to deal with the null buffer case.

Yes, I agree for validity bitmaps code will have to deal with it. For actual values it is a bit unexpected, though (at least the person who wrote the parquet-cpp code clearly didn't expect it :-)).

> My gut feeling is that we should allow the null buffers and document the issue well so that users can defend themselves from untrusted data.

Where would you document it? in ArrayData?

**Comment by wesm** [comment]
On this

> What would you say to adding an option to `ValidateArray` about checking for null buffers? I agree that being able to easily check is valuable, even if it isn't strictly "wrong". 

I'm OK with doing this later. I'll give this another review and merge since I don't think it does anything problematic

**Comment by wesm** [comment]
Shoot I think we need to get ARROW-2822 https://github.com/apache/arrow/pull/2239 in first. Let me see if that's ready to merge

**Comment by pitrou** [comment]
This has conflicts now, I'm gonna rebase.

**Review by wesm — APPROVED** [review]
+1. Thanks @pitrou!

**Pull request closed without merging**
