### PR TITLE
ARROW-3818: [R] Table$from_batches

### PR DESCRIPTION
**Pull request by romainfrancois**
https://issues.apache.org/jira/browse/ARROW-3818?filter=12344983

### CODE REVIEW

**Comment by romainfrancois** [comment]
``` r
library(arrow)
#> 
#> Attaching package: 'arrow'
#> The following object is masked from 'package:utils':
#> 
#>     timestamp
#> The following objects are masked from 'package:base':
#> 
#>     array, table

b <- record_batch(tibble::tibble(int = 1:2, dbl = rnorm(2)))
tab <- table_from_batches(b,b,b)
tab
#> arrow::Table
as_tibble(tab)
#> # A tibble: 6 x 2
#>     int     dbl
#>   <int>   <dbl>
#> 1     1 -0.267 
#> 2     2 -0.0270
#> 3     1 -0.267 
#> 4     2 -0.0270
#> 5     1 -0.267 
#> 6     2 -0.0270

# this supports !!! splicing so
batches <- rep(list(b), 20L)
tab <- table_from_batches(!!!batches)
tab
#> arrow::Table
as_tibble(tab)
#> # A tibble: 40 x 2
#>      int     dbl
#>    <int>   <dbl>
#>  1     1 -0.267 
#>  2     2 -0.0270
#>  3     1 -0.267 
#>  4     2 -0.0270
#>  5     1 -0.267 
#>  6     2 -0.0270
#>  7     1 -0.267 
#>  8     2 -0.0270
#>  9     1 -0.267 
#> 10     2 -0.0270
#> # … with 30 more rows
```

<sup>Created on 2019-02-05 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

**Comment by romainfrancois** [comment]
I'm just not sure about the naming. In python the `py.Table` is exposed but in the R package, the classes are not really meant to be used directly, so defining a static method does not really work, as of now the class is ```arrow:::`arrow::Table` ``` ...

We could expose certain classes a first class citizens of the package if we really want the syntax `Table$from_batches()`

**Comment by romainfrancois** [comment]
Actually #3565 is better because it does not need a separate `table_from_arrays()` function, as the `table()` itself can handle list of record batches

**Comment by xhochy** [comment]
Rebased.

**Pull request closed without merging**
