### PR TITLE
ARROW-14593: [C++] Fix crashes on invalid IPC file (OSS-Fuzz)

### PR DESCRIPTION
**Pull request by pitrou**
Fix the following issues:
- https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=39978
- https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=40653

### CODE REVIEW

**Review by lidavidm — APPROVED** [review]
+1 LGTM.

So this was two separate issues? One being, not fully validating MapArray when read in from IPC, the other presumably being an overflow in validation or manipulation of a ListArray?

**Comment by pitrou** [comment]
> So this was two separate issues? One being, not fully validating MapArray when read in from IPC, the other presumably being an overflow in validation or manipulation of a ListArray?

Yes, it was too fuzz crashes in one PR.

**Comment by kszucs** [comment]
@pitrou @lidavidm shall we include this in the patch release?

**Comment by pitrou** [comment]
Probably not, given the slight behaviour change.

**Pull request closed without merging**
