### PR TITLE
ARROW-14748: [C++][CI] Update flags to give warning for unused results

### PR DESCRIPTION
**Pull request by bkmgit**
Maybe problematic on older GCC compilers https://gcc.gnu.org/bugzilla/show_bug.cgi?id=38172

### CODE REVIEW

**Comment by kou** [comment]
Could you confirm the 2 R jobs failures? It seems they were passed on master: https://github.com/apache/arrow/actions/runs/1483611031

**Comment by bkmgit** [comment]
Latest libraries were published on November 20 https://cran.r-project.org/package=arrow - expect some configuration update is needed. Seems like the failing tests are in https://github.com/apache/arrow/blob/master/r/tests/testthat/test-install-arrow.R possibly due to lagging updates. Will try running tests again.

**Comment by bkmgit** [comment]
@github-actions crossbow submit -g nightly

**Comment by bkmgit** [comment]
R AMD 64 Windows  R Tools 40 runs on Arrow 6.0.0.9 rather than latest version. Failing test is
```
== Failed tests ================================================================
-- Error (test-duckdb.R:71:3): to_duckdb then to_arrow -------------------------
Error: Error: IOError: Query Stream is closed
Backtrace:
    x
 1. +-ds %>% to_duckdb() %>% select(-fct) %>% to_arrow() test-duckdb.R:71:2
 2. \-arrow::to_arrow(.)
 3.   +-arrow:::arrow_dplyr_query(duckdb::duckdb_fetch_record_batch(res)$read_table())
 4.   | +-dplyr::group_vars(.data) %||% character()
 5.   | \-dplyr::group_vars(.data)
 6.   \-duckdb::duckdb_fetch_record_batch(res)$read_table()
 7.     \-arrow:::Table__from_RecordBatchReader(self)

[ FAIL 1 | WARN 2 | SKIP 44 | PASS 6185 ]
Error: Error: Test failures
Execution halted
```

**Comment by bkmgit** [comment]
Created separate issue https://issues.apache.org/jira/browse/ARROW-14786 for RTools test failures

**Comment by pitrou** [comment]
The DuckDB failures on R are unrelated.

**Comment by pitrou** [comment]
@github-actions crossbow submit -g cpp

**Review by pitrou — APPROVED** [review]
+1 on the principle. Let's ensure there is no regression on CI.

**Pull request closed without merging**
