### PR TITLE
ARROW-13921: [Python][Packaging] Pin minimum setuptools version for the macos wheels

### PR DESCRIPTION
**Pull request by kszucs**
There was a bug in setuptools which caused the recent nightly failures: https://github.com/ursacomputing/crossbow/runs/3521607291#step:10:269

### CODE REVIEW

**Comment by kszucs** [comment]
@github-actions crosssbow submit wheel-macos-*

**Comment by kszucs** [comment]
@github-actions crosssbow submit wheel-macos-*

**Comment by kszucs** [comment]
@github-actions crossbow --help

**Comment by kszucs** [comment]
@github-actions crossbow submit wheel-macos-*

**Comment by kszucs** [comment]
@github-actions crossbow submit wheel-macos-*

**Comment by kszucs** [comment]
@github-actions crossbow submit wheel-macos-*

**Comment by kszucs** [comment]
@github-actions crossbow submit wheel-macos-*

**Review by pitrou — APPROVED** [review]

**Pull request closed without merging**
