### PR TITLE
ARROW-1088: [Python] Only test unicode filenames if system supports them

### PR DESCRIPTION
**Pull request by jeffknupp**

### CODE REVIEW

**Review by xhochy — CHANGES_REQUESTED** [review]
-1 for the moment, see the discussion in the JIRA

**Comment by wesm** [comment]
In what environment does this occur?

**Comment by jeffknupp** [comment]
@wesm here is a Dockerfile to create the environment:

```
FROM ubuntu:17.10

MAINTAINER Jeff Knupp <jeff@jeffknupp.com>

RUN apt-get update && apt-get install -yq python3 \
        python3-dev \
        g++-4.9 \
        libboost-dev \
        libboost-filesystem-dev \
        libboost-program-options-dev libboost-regex-dev \
        libboost-system-dev libboost-test-dev \
        libssl-dev libtool bison flex pkg-config git vim cmake \
        zlibc python3-pip

WORKDIR /home
COPY .ssh /home/.ssh/

WORKDIR /home/arrow

RUN git clone https://github.com/apache/parquet-cpp
RUN git clone https://github.com/apache/arrow

ENV ARROW_HOME=/usr/local
RUN pip3 install pandas cython
WORKDIR /home/arrow/arrow/cpp/build
RUN cmake -DARROW_PYTHON=on .. && make -j4 && make install

WORKDIR /home/arrow/parquet-cpp
RUN cmake . && make -j4 && make install

WORKDIR /home/arrow/arrow/python
RUN python3 setup.py build_ext --with-parquet --with-jemalloc
```

**Comment by xhochy** [comment]
I digged a bit through this and the main difference between my ubuntu 16.04 machine and the 17.04 docker image is the filesystemencoding:

Ubuntu 16.04:
```
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.getfilesystemencoding()
'UTF-8'
```

Ubuntu 17.04:
```
Python 3.5.3 (default, Jan 19 2017, 14:11:04) [GCC 6.3.0 20170118] on linuxType "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.getfilesystemencoding()
'ascii'
```

Setting the appropriate environment variables like `LC_ALL` and `LANG` to `en_US.UTF-8` didn't help.

**Comment by wesm** [comment]
I was able to fix this by appending this to the Dockerfile

```
RUN apt-get -yq install locales
RUN locale-gen en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8
```

**Comment by jeffknupp** [comment]
@wesm I think you've just proven that if you change a system that doesn't accept unicode filenames into one that does, the tests work as expected. I wasn't really making that point. Rather, if the underlying system doesn't (at the time of test execution) support unicode filenames, we should skip the unit test that relies on their support.

**Review by wesm — APPROVED** [review]
+1, I think this is OK. Most systems are well-behaved enough that this error won't trigger

**Comment by jeffknupp** [comment]
@wesm thanks. Can you (or someone else) merge when you get a chance?

**Comment by wesm** [comment]
I'm going to merge; since @xhochy had said -1 I didn't want to override that right away. If there are more concerns about how this is handled I will be help with another patch

**Pull request closed without merging**
