### PR TITLE
ARROW-5157: [Website] Add MATLAB to powered by Apache Arrow website

### PR DESCRIPTION
**Pull request by hatemhelal**
@kevingurney, @rdmello, @DaveBergstein, @nickhaddady, and @jeremy-hughes let me know what you think of the wording of this.  Thanks!

### CODE REVIEW

**Comment by kevingurney** [comment]
@hatemhelal - The wording looks good to me!

**Comment by rdmello** [comment]
Hi Hatem, I think "Parquet" and "Feather" should be capitalized here, but apart from that I think it looks good.

**Comment by hatemhelal** [comment]
> Hi Hatem, I think "Parquet" and "Feather" should be capitalized here, but apart from that I think it looks good.

Good catch, fixed now.

**Comment by kou** [comment]
Should we wait for reviews from @DaveBergstein, @nickhaddady and @jeremy-hughes?
Or can we merge this?

**Comment by nickhaddady** [comment]
No flags here,  merge away.

-Nick

________________________________

**Comment by jeremy-hughes** [comment]
Same

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by DaveBergstein** [comment]
Same

**Comment by emkornfield** [comment]
Looks like this is ready to merge.

**Comment by kou** [comment]
Thanks all.
I'll merge this.

**Comment by emkornfield** [comment]
already doing merging ..

**Comment by kou** [comment]
Oh. Sorry!

**Comment by emkornfield** [comment]
@kou no worries.

**Pull request closed without merging**
