### PR TITLE
ARROW-2044: [JS] Typings should be a regular dependency

### PR DESCRIPTION
**Pull request by TheNeuralBit**
Made @types/{flatbuffers,node} regular dependencies so they will be included with release packages

### CODE REVIEW

**Comment by wesm** [comment]
@TheNeuralBit can you rebase?

**Comment by TheNeuralBit** [comment]
@wesm I did the rebase. Do you know what went wrong with the C++ build?

**Comment by wesm** [comment]
I will look. We've been having sporadic failures the last 2 weeks

**Review by wesm — APPROVED** [review]
+1

**Pull request closed without merging**
