### PR TITLE
ARROW-7977: [C++] Rename fs::FileStats to fs::FileInfo

### PR DESCRIPTION
**Pull request by kou**
If we use FileInfo instead of FileStats, we can use singular form
"info" and plural form "infos" as variable names instead of "stats"
and "stats_vector". It will help writing readable code.

### CODE REVIEW

**Comment by kou** [comment]
@pitrou What do you think about this?

**Comment by kszucs** [comment]
It was bothering me as well a little bit.

**Comment by pitrou** [comment]
I actually meant "statistics" not "status". I'll let others speak up.

**Comment by pitrou** [comment]
(note the corresponding method is called `GetTargetStats` plural)

**Comment by pitrou** [comment]
Of course, we can also decide to call it `FileInfo`...

**Comment by kszucs** [comment]
@pitrou `FileInfo` sounds better than `FileStat[s]`, but since it supports directories too then perhaps call it `PathInfo`?

**Comment by pitrou** [comment]
It's really about a File or directory entry, so IMHO `FileInfo` is better.

**Comment by kszucs** [comment]
> It's really about a File or directory entry, so IMHO `FileInfo` is better.

Ok, SGTM.

**Comment by kou** [comment]
> I'll let others speak up.

@bkietz @fsaintjacques @mrkn Do you have any thoughts about this? (I chose you by `git log --format=format:%aN cpp/src/arrow/filesystem/filesystem.h`.)

**Comment by bkietz** [comment]
@kou @pitrou @kszucs IMHO FileInfo is fine, but I prefer FileStat because "stat" pluralizes more naturally: stat->stats vs info->infos

**Comment by wesm** [comment]
I'm also more in favor of `FileInfo`. I hate to bikeshed, but you could also call it `fs::PathInfo` (since it can apply to both files and directories).

**Comment by kou** [comment]
Thanks all.
It seems that `FileInfo` is reasonable for us.

I'll rename `FileStats` to `FileInfo`.

**Comment by kou** [comment]
Done.
CI is green.
I'll merge this.

**Pull request closed without merging**
