### PR TITLE
ARROW-646: Cache miniconda directory in travis

### PR DESCRIPTION
**Pull request by xhochy**

### CODE REVIEW

**Comment by xhochy** [comment]
Green build: https://travis-ci.org/xhochy/arrow/builds/212024981

**Comment by wesm** [comment]
Does this actually cache the install? I'm trying to figure out how Travis's cache system works, because it's not clear how this will skip downloading miniconda after the first cache occurs

**Comment by wesm** [comment]
So when we run the miniconda install, it does not blow away $HOME/miniconda/pkgs (the thing we want to cache, right)

**Comment by xhochy** [comment]
I have to re-check this assumption again as it seems currently that cached and non-cached builds take the same amount of time.

**Comment by wesm** [comment]
Seems like we can use `$CONDA_ENVS_PATH` to store the environments and package cache in a different directory, see

http://conda-test.pydata.org/docs/config.html

**Comment by xhochy** [comment]
Declining again as it seems that for now Travis builds fine and the caching here seems to not work flawless.

**Pull request closed without merging**
