### PR TITLE
ARROW-11146: [CI] Remove test-conda-python-3.8-jpype build

### PR DESCRIPTION
**Pull request by pachadotdev**

### CODE REVIEW

**Comment by jonkeane** [comment]
The changes to tasks.yml looks good, however a few notes: 

* Could you rebase/squash your commits here so that we don't have all of that extraneous history? It should be fine when we squash + merge it, but we want to make sure we're being clean with this and it's not touching other things accidentally / unnecessarily
* Dig more into the failure that you noted. What failed? Does it make sense that these changes are touching that? 
* Could you update the format of the PR to match our style (pick either of the two tickets we have for this to use as the ticket number + mark the other as a duplicate)

**Comment by pachamaltese** [comment]
> The changes to tasks.yml looks good, however a few notes:
> 
>     * Could you rebase/squash your commits here so that we don't have all of that extraneous history? It should be fine when we squash + merge it, but we want to make sure we're being clean with this and it's not touching other things accidentally / unnecessarily
> 
>     * Dig more into the failure that you noted. What failed? Does it make sense that these changes are touching that?
> 
>     * Could you update the format of the PR to match our style (pick either of the two tickets we have for this to use as the ticket number + mark the other as a duplicate)

sure !!

no problem, I'll do that now and push again

**Comment by pachamaltese** [comment]
ready :)

**Comment by jonkeane** [comment]
I'm still seeing a bunch of commits that seem unrelated to this change — how did you go about squashing or rebasing so that you don't have that unrelated history in this branch? 

Additionally: Dig more into the failure that you noted. What failed? Does it make sense that these changes are touching that?

**Comment by pachamaltese** [comment]
hmm... i'm not so sure
here I see 1 file changed https://github.com/apache/arrow/pull/10232/files

**Comment by pachamaltese** [comment]
I did a rebase and then a push and it went well

**Comment by pachamaltese** [comment]
i'll open a new pr... it's better i think

**Comment by pachamaltese** [comment]
moved to https://github.com/apache/arrow/pull/10238

**Pull request closed without merging**
