### PR TITLE
[C++][CSV] ParseLine Refactor

### PR DESCRIPTION
**Pull request by zuyu**
### Rationale for this change

`ParseLine` uses lots of `goto`s, and it is not that hard to refactor it using loops.

### What changes are included in this PR?

`ParseLine` refactored.

### Are these changes tested?

Covered by existing tests.

### Are there any user-facing changes?

No.

### CODE REVIEW

**Comment by zuyu** [comment]
@ursabot please benchmark lang=C++

**Comment by zuyu** [comment]
@ursabot please benchmark lang=C++

**Comment by zuyu** [comment]
@ursabot please benchmark lang=C++

**Comment by pitrou** [comment]
@zuyu Thanks for suggesting this. However, I don't think this is an improvement. The reason the code uses labels and `goto`s is that it's essentially a state machine, and the current style makes the states and state transitions explicit, making it easy to reason about them. 

@felipecrv What do you think?

**Comment by felipecrv** [comment]
I agree with @pitrou.

`goto` was deemed harmful by Dijkstra because it made proving the correctness of a program (specially termination checking) harder than with structured constructs, but in the case of a parser, the high-level languages we use don't give us great tools. As such you will find `goto` in many parsers in the wild even when most of the non-parser code in the same codebase doesn't use gotos.

A parser without goto is more branchy. All the parser state must be represented in data instead of being represented in the instruction pointer (which is what goto mutates). These extra branches might affect performance (if the compiler can't make flatten the structured code as we can).

If a label has multiple gotos pointing to it, the version without goto may need functions. This may lead to code repetition due to inlining and worse instruction cache usage.

**Comment by zuyu** [comment]
Thank you for the comments. This *draft* PR was just to let the CI verify the correctness of the refactor. It does not need to get merge, and it seems no performance regressions. 😊

I do agree that sometimes `goto` is useful, and even necessary. Like @felipecrv said, I do observe some CSV parser uses an enum to represent the parsing states, and thus a huge `switch` statement for the state machine, but seems too complicate.

Finally, I really appreciate the code quality of the CSV parser by @pitrou. It is really easier to follow than the above parser.

**Pull request closed without merging**
