### PR TITLE
GH-43095: [C++] Update bundled vendor/datetime to support for building with libc++ and C++20

### PR DESCRIPTION
**Pull request by ben-freist**
### Rationale for this change

We can't build with libc++ and C++20:

CMake command line:

```bash
cmake -DARROW_ENABLE_THREADING=OFF \
 -DARROW_JEMALLOC=OFF \
-DCMAKE_CXX_STANDARD=20 \
-DCXX_ONLY_FLAGS="-stdlib=libc++" \
-DCMAKE_TOOLCHAIN_FILE=toolchain.cmake  --preset ninja-debug-minimal   ../cpp/
```

Error log:

```
In file included from ~/.conan2/p/b/arrowe39f77e638649/b/src/cpp/src/arrow/vendored/datetime/tz.cpp:90:
~/.conan2/p/b/arrowe39f77e638649/b/src/cpp/src/arrow/vendored/datetime/tz_private.h:295:12: error: use of overloaded operator '<<' is ambiguous (with operand types 'std::ostream' (aka 'basic_ostream<char>') and 'const sys_seconds' (aka 'const time_point<std::chrono::system_clock, std::chrono::duration<long long, std::ratio<1, 1>>>'))
  295 |         os << t.timepoint << "Z ";
      |         ~~ ^  ~~~~~~~~~~~
/usr/lib/llvm-17/bin/../include/c++/v1/__chrono/ostream.h:46:1: note: candidate function [with _CharT = char, _Traits = std::char_traits<char>, _Duration = std::chrono::duration<long long>]
   46 | operator<<(basic_ostream<_CharT, _Traits>& __os, const sys_time<_Duration> __tp) {
      | ^
~/.conan2/p/b/arrowe39f77e638649/b/src/cpp/src/arrow/vendored/datetime/date.h:4214:1: note: candidate function [with CharT = char, Traits = std::char_traits<char>, Duration = std::chrono::duration<long long>]
 4214 | operator<<(std::basic_ostream<CharT, Traits>& os, const sys_time<Duration>& tp)
```

### What changes are included in this PR?

Update the bundled vendor/datetime because the upstream has changes for this case:
https://github.com/HowardHinnant/date/pull/827

### Are there any user-facing changes?

* GitHub Issue: #43095

### CODE REVIEW

**Comment by kou** [comment]
Hmm. Our C++20 CI job doesn't report this error: https://github.com/ursacomputing/crossbow/actions/runs/9736169142/job/26866418106

What is the difference between the job and you? g++ and clang++?

**Comment by ben-freist** [comment]
Thank you for the quick response! I can reproduce the behaviour like this
```
cmake -DARROW_ENABLE_THREADING=OFF \
 -DARROW_JEMALLOC=OFF \
-DCMAKE_CXX_STANDARD=20 \
-DCXX_ONLY_FLAGS="-stdlib=libc++" \
-DCMAKE_TOOLCHAIN_FILE=toolchain.cmake  --preset ninja-debug-minimal   ../cpp/
```
Where `toolchain.cmake` looks like this:
```
set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR X86)

set(CMAKE_C_COMPILER clang-17 CACHE INTERNAL "C compiler")
set(CMAKE_CXX_COMPILER clang++-17 CACHE INTERNAL "C++ compiler")
```
Looks like `libstdc++` doesn't have the stream insertion operators yet.

**Comment by ben-freist** [comment]
And it doesn't look like they are coming to libstdc++ soon, this compiles with gcc trunk, but fails when you select clang and use libc++: https://godbolt.org/z/ehnTdsK1e

**Comment by kou** [comment]
OK.
The upstream of `cpp/src/arrow/vendored/datetime/` is https://github.com/HowardHinnant/date . Could you fix this case in the upstream and then update our vendored version like #35612?

**Comment by ben-freist** [comment]
The library is part of the standard for c++ 20 and some compilers now, so I think the proper fix would be not to use it anymore.
Do you think it's good enough to handle it like this for now?

**Comment by kou** [comment]
> The library is part of the standard for c++ 20 and some compilers now, so I think the proper fix would be not to use it anymore.

How can we do this? Does `using arrow_vendored::date::year_month_day = std::chrono::year_month_day;` or something work?

> Do you think it's good enough to handle it like this for now?

What does "this" refer? Changing our bundled date library directly? If so, it's not acceptable. We don't want to maintain these changes in our side. We should upstream these changes.

**Comment by ben-freist** [comment]
I've bumped the version of `vendored/datetime`. At the moment the arrow specific patches are in a separate commit.

**Comment by kou** [comment]
The upstream already has changes for this, right?

**Comment by ben-freist** [comment]
Yep, I think this is the relevant PR: https://github.com/HowardHinnant/date/pull/827

**Review by kou — APPROVED** [review]
+1

**Comment by ben-freist** [comment]
Hey,
thank you for merging this!
It would be nice if this change could be pushed to a new conan recipe. Do you know when this might happen?

**Comment by kou** [comment]
We'll release 18.0.0 in this month. Then conan will add support for 18.0.0.

**Pull request merged**
