### PR TITLE
GH-43217: [Java] Remove flight-core shaded jars

### PR DESCRIPTION
**Pull request by laurentgo**
### Rationale for this change

Remove extra jars generated by `flight-core` modules:
- they do not seem to be used by the project internally and does not seem to satisfy some external purpose as well
- they are not compatible with JPMS

### Are these changes tested?

CI/CD

### Are there any user-facing changes?

Several extras jars attached to `org.apache.arrow:flight-core` artifact will stop being published to Apache Maven Repository/Maven Central.
* GitHub Issue: #43217

### CODE REVIEW

**Comment by laurentgo** [comment]
@github-actions crossbow submit -g java

**Comment by laurentgo** [comment]
@github-actions crossbow submit java-jars

**Review by lidavidm — APPROVED** [review]

**Comment by lidavidm** [comment]
@danepitkin @jduo any concerns here?

**Comment by jduo** [comment]
No concerns as I don't see a reason to use these externally. May as well just delete the shade tasks instead of comment them out though.

**Comment by laurentgo** [comment]
> No concerns as I don't see a reason to use these externally. May as well just delete the shade tasks instead of comment them out though.

Didn't realize I left them commented out instead of removing, will post an update quickly

**Review by danepitkin — APPROVED** [review]
No concerns from me! Thanks @laurentgo!

**Comment by vibhatha** [comment]
@github-actions crossbow submit java-jars

**Pull request merged**
