### PR TITLE
ARROW-14229:  [C++] WIP Bump versions of bundled dependencies

### PR DESCRIPTION
**Pull request by bkmgit**

### CODE REVIEW

**Comment by jonkeane** [comment]
I triggered our offline-r build and it failed for the reasons stated in the ticket (we need to upload the new source(s)). But once that's done it would be good to re-reun this job since it exercises this dependency resolution in a unique way that has caught other issues in the past.

**Comment by bkmgit** [comment]
@jonkeane Thanks. As indicated in https://issues.apache.org/jira/browse/ARROW-6407 would you also consider having a mirror of  https://github.com/ursa-labs/thirdparty  on [OSDN](https://osdn.net/docs/GitHubsync_frs), [GitLab](https://docs.gitlab.com/ee/api/remote_mirrors.html) or [Gitee](https://gitee.com/) ?

**Comment by kou** [comment]
We can use https://apache.jfrog.io/ui/native/arrow/ such as https://apache.jfrog.io/ui/native/arrow/boost for mirror (or master).

**Comment by pitrou** [comment]
@github-actions crossbow submit -g cpp

**Comment by pitrou** [comment]
> Have updated this, but then one of the crossbow builds with previous sha256sum passed.

I may be mistaken, but I think CMake only uses the sha256sum for caching (?).

**Comment by bkmgit** [comment]
Build failures for Thrift versions 0.14 and 0.15 on Ubuntu 18.04 with libssl-dev ( OpenSSL 1.1.1f  ) are due to use of deprecated commands, for example:
                 from /usr/include/openssl/err.h:13,
                 from /root/arrow/cpp/build/thrift_ep-prefix/src/thrift_ep/lib/cpp/src/thrift/transport/TSSLSocket.cpp:48:
/usr/include/openssl/asn1.h:554:1: note: declared here
  554 | DEPRECATEDIN_1_1_0(unsigned char *ASN1_STRING_data(ASN1_STRING *x))
      | ^~~~~~~~~~~~~~~~~~

**Comment by bkmgit** [comment]
Suggest leaving Thrift at 0.13 until next release when OpenSSL requirement can be bumped to 1.1.1 from 1.0.2

**Comment by bkmgit** [comment]
@github-actions crossbow submit -g cpp

**Comment by bkmgit** [comment]
@github-actions crossbow submit -g cpp

**Comment by bkmgit** [comment]
@github-actions crossbow submit -g cpp

**Comment by bkmgit** [comment]
@github-actions crossbow submit -g cpp

**Comment by bkmgit** [comment]
@github-actions crossbow submit -g test-ubuntu-20.04-cpp-17

**Comment by bkmgit** [comment]
@github-actions crossbow submit -g ubuntu-20.04-cpp-17

**Comment by bkmgit** [comment]
@github-actions crossbow submit test-ubuntu-20.04-cpp-17

**Comment by bkmgit** [comment]
@github-actions crossbow submit -g nightly

**Comment by bkmgit** [comment]
@github-actions crossbow submit test-r-ubuntu-21.04

**Comment by bkmgit** [comment]
@github-actions crossbow submit test-ubuntu-20.04-cpp-17

**Comment by bkmgit** [comment]
@github-actions crossbow submit test-ubuntu-20.04-cpp-17

**Comment by bkmgit** [comment]
@github-actions crossbow submit test-ubuntu-20.04-cpp-17

**Comment by bkmgit** [comment]
Closed in favor of https://github.com/apache/arrow/pull/11494

**Pull request closed without merging**
