### PR TITLE
GH-38346: [C++][Parquet] Use new encrypted files for page index encryption test

### LINKED ISSUE #38346: [C++][Parquet] Use new encrypted files for page index encryption test
### Describe the enhancement requested

Encrypted parquet files have been updated to apache/parquet-testing repo. We can use the new files to verify encrypted page index.

### Component(s)

C++, Parquet

### PR DESCRIPTION
**Pull request by wgtmac**
### Rationale for this change

Encrypted parquet files have been updated to apache/parquet-testing repo. We can use the new files to verify encrypted page index.

### What changes are included in this PR?

Minor refactor read_configurations_test.cc to check page index from all parquet files.

### Are these changes tested?

This is indeed a unit test enhancement.

### Are there any user-facing changes?

NO.
* Closes: #38346

### CODE REVIEW

**Review by pitrou — APPROVED** [review]

**Review by mapleFU — APPROVED** [review]
Nice

I wonder should we have a encrypted files with page index in the future...

**Comment by mapleFU** [comment]
Will merge it if nobody has more comment tonight

**Comment by wgtmac** [comment]
Thank you @pitrou and @mapleFU

**Comment by mapleFU** [comment]
CI faileds are unrelated.

**Pull request merged**
