### PR TITLE
ARROW-8645: [C++] Missing gflags dependency for plasma

### PR DESCRIPTION
**Pull request by kszucs**
The documentation build fails because gflags is not installed and CMake doesn't build the bundled version of it.
Introduced by https://github.com/apache/arrow/commit/dfc14ef24ed54ff757c10a26663a629ce5e8cebf

### CODE REVIEW

**Comment by kszucs** [comment]
@github-actions crossbow submit ubuntu-docs

**Comment by kszucs** [comment]
@github-actions crossbow submit test-ubuntu-18.04-docs

**Comment by kou** [comment]
FYI: I'm working on this at #7067 .

**Comment by kszucs** [comment]
Didn't see that, closing in favor that then.

**Pull request closed without merging**
