### PR TITLE
ARROW-9845: [Rust] [Parquet] serde_json is only used in tests but isn't in dev-dependencies

### PR DESCRIPTION
**Pull request by saethlin**

### CODE REVIEW

**Comment by andygrove** [comment]
Build failure is unrelated to these changes - see https://issues.apache.org/jira/browse/ARROW-9846

**Comment by alamb** [comment]
For what it is worth, I cherry-picked this diff locally and ran the rust tests and everything passed for me. I suggest we merge it @andygrove.

If it would help, I can prepare a PR against the latest master with this change to get a clean CI run

**Comment by andygrove** [comment]
Thanks @alamb that would be great.

**Comment by alamb** [comment]
> Thanks @alamb that would be great.

https://github.com/apache/arrow/pull/8087

**Comment by andygrove** [comment]
Thanks @saethlin this was merged in https://github.com/apache/arrow/pull/8087

**Pull request closed without merging**
