### PR TITLE
ARROW-15027: [C++] Fix OpenTelemetry CMake definitions

### PR DESCRIPTION
**Pull request by lidavidm**

### CODE REVIEW

**Review by pitrou — APPROVED** [review]

**Comment by lidavidm** [comment]
I'll file an issue for Gandiva since it appears on master. It seems to have started with https://github.com/apache/arrow/commit/b31dd5148e0e0b55555c7a9417e83a08949e9d4b even though that looks unrelated; since the failing builds use unity builds it seems something about it shifted how the unity build combines files.

**Comment by pitrou** [comment]
Thanks. I'll file a PR for it.

**Comment by lidavidm** [comment]
I filed ARROW-15028

**Comment by pitrou** [comment]
I filed https://github.com/apache/arrow/pull/11905 -- hopefully it'll pass.

**Comment by pitrou** [comment]
The Gandiva fix was merged, it's in git master now.

**Comment by lidavidm** [comment]
Looks like this passes once rebased, thanks for fixing the issue.

**Pull request closed without merging**
