### PR TITLE
ARROW-2231: [CI] Use clcache on AppVeyor for faster builds

### PR DESCRIPTION
**Pull request by pitrou**
clcache is most efficient with Ninja, so this PR switches most of the builds to it.
Also the builds are upgraded to Python 3.6 from 3.5.
Finally, tests are also run on debug builds.

Example build without cache:
https://ci.appveyor.com/project/pitrou/arrow/build/1.0.113

Example build with the cache fully primed:
https://ci.appveyor.com/project/pitrou/arrow/build/1.0.143

### CODE REVIEW

**Comment by pitrou** [comment]
It would also be possible to integrate clcache in the cmake configuration (but would make it more difficult to disable). Thoughts?

**Review by wesm — APPROVED** [review]
+1. Would it be possible to have a clcache-related option to toggle it on/off in the cmake setup?

**Comment by pitrou** [comment]
> Would it be possible to have a clcache-related option to toggle it on/off in the cmake setup?

Probably. Should it be on or off by default?

**Comment by wesm** [comment]
Let me know if you'd like to do that work here or in a follow up patch, in the latter case I can merge this

**Comment by pitrou** [comment]
No preference from me.

**Review by cpcloud — APPROVED** [review]
Awesome.

**Pull request closed without merging**
