### PR TITLE
ARROW-3157: [C++] Add Buffer::Wrap, MutableBuffer::Wrap convenience methods for wrapping typed memory, std::vector<T>

### PR DESCRIPTION
**Pull request by wesm**

### CODE REVIEW

**Comment by wesm** [comment]
cc @pcmoritz @pitrou @xhochy

**Comment by wesm** [comment]
I wonder also if we should change the inline ctor for `Buffer` to be `const void* data` instead of `const uint8_t* data`

**Comment by pitrou** [comment]
> A counter-argument is that this might cause people to have bugs by forgetting to multiple the length by the sizeof(T) when casting from another pointer type

Yes... So instead perhaps a `Wrap` specialization that accepts `const void*`? (I suppose the current one doesn't, because of the `sizeof` call)

**Review by pitrou — APPROVED** [review]
+1, LGTM.

**Comment by wesm** [comment]
> Yes... So instead perhaps a Wrap specialization that accepts const void*? (I suppose the current one doesn't, because of the sizeof call)

That would probably be the way. I'll defer on adding it until it's deemed useful enough to have

**Pull request closed without merging**
