### PR TITLE
GH-36969: [C++] Update ABSEIL to address compile error on GCC 13

### PR DESCRIPTION
**Pull request by amol-**
### Rationale for this change

When trying to compile Arrow with GCC 13, it fails due to ABSEIL missing a `<cstdint>` include, this PR addresses the issue by updating ABSEIL to version nearest to the one currently in use that includes the fix.

There have been past reports for this issue too: https://github.com/apache/arrow/issues/36969 

### What changes are included in this PR?

Downloaded ABSL version updated from 20211102.0 to 20220623.2

### Are these changes tested?

They are tested by the existing compile infrastructure and testsuite

### Are there any user-facing changes?

No, all behaviours should remain the same
* GitHub Issue: #36969

### CODE REVIEW

**Comment by amol-** [comment]
@github-actions crossbow submit -g cpp

**Comment by amol-** [comment]
Seems that there are ABI changes already between the two versions

```
/usr/local/lib/libarrow_flight.so: undefined reference to `absl::lts_20220623::base_internal::StrError[abi:cxx11](int)'
```

**Comment by amol-** [comment]
@github-actions crossbow submit -g cpp

**Comment by amol-** [comment]
@github-actions crossbow submit r-binary-packages test-fedora-35-cpp

**Comment by amol-** [comment]
@github-actions crossbow submit -g r

**Comment by amol-** [comment]
The `cpp-thread-sanitizer` might be unrelated, the process seems to be killed by the OS:

```
Running arrow-compute-internals-test, redirecting output into /build/cpp/build/test-logs/arrow-compute-internals-test.txt (attempt 1/1)
/arrow/cpp/build-support/run-test.sh: line 88: 14285 Killed                  $TEST_EXECUTABLE "$@" > $LOGFILE.raw 2>&1
Running main() from _deps/googletest-src/googletest/src/gtest_main.cc
```

**Comment by amol-** [comment]
@github-actions crossbow submit r-binary-packages

**Comment by felipecrv** [comment]
@amol- can you rebase to get the contents of #43219? You might have a higher chance of getting the build to pass.

**Comment by amol-** [comment]
> @amol- can you rebase to get the contents of #43219? You might have a higher chance of getting the build to pass.

👍 I'll try next week as soon as I'm back home

**Comment by amol-** [comment]
Closing as the issue has been solved

**Pull request closed without merging**
