### PR TITLE
ARROW-4151: [Rust] Restructure project directories

### PR DESCRIPTION
**Pull request by sunchao**

### CODE REVIEW

**Review by andygrove — APPROVED** [review]
Much cleaner. LGTM (once build issue is resolved).

**Comment by kou** [comment]
Can you also change the `Cargo.toml` path in `dev/release/00-prepare.sh`?
https://github.com/apache/arrow/blob/master/dev/release/00-prepare.sh#L103-L105

**Comment by sunchao** [comment]
> Can you also change the `Cargo.toml` path in `dev/release/00-prepare.sh`?
> https://github.com/apache/arrow/blob/master/dev/release/00-prepare.sh#L103-L105

Done.

**Comment by kou** [comment]
Thanks.
There are CI failures:

* https://travis-ci.org/apache/arrow/jobs/476201205
  * We also need to update l`dev/release/rat_exclude_files.txt` https://github.com/apache/arrow/blob/master/dev/release/rat_exclude_files.txt#L190 that is used for license check.
* https://travis-ci.org/apache/arrow/jobs/476201217

Can you fix them?

**Comment by sunchao** [comment]
Oops. Let me fix these.

**Comment by sunchao** [comment]
@kou can you take another look? I think the cargo coverage report is broken for some reason. I'll file a JIRA for that separately.

**Pull request closed without merging**
