### PR TITLE
ARROW-2053: [C++] fix build instruction is incomplete

### PR DESCRIPTION
**Pull request by shiro615**
I did the following [c_glib](https://github.com/apache/arrow/tree/master/c_glib)  instruction
```
cd c_glib
brew install -y gobject-introspection
./configure PKG_CONFIG_PATH=$(brew --prefix libffi)/lib/pkgconfig:$PKG_CONFIG_PATH
```

I got the following result
```
checking for arrow arrow-compute... no
configure: error: Package requirements (arrow arrow-compute) were not met:
No package 'arrow' found
No package 'arrow-compute' found
Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.
Alternatively, you may set the environment variables ARROW_CFLAGS
and ARROW_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
```
 
I need the following information to succeed 

`sudo make install`

### CODE REVIEW

**Comment by wesm** [comment]
Hm, perhaps we should add a new section about installing that includes instructions for both the system default location and a custom location. Then in c_glib, we can document how to use an Arrow install in a custom location (without depending on the system directories). @kou what do you think?

**Comment by cpcloud** [comment]
I don't think the default documentation should say `sudo` anything. How about a line that says "You may have to prefix `make install` with `sudo` if you get a permissions error when installing"?

**Comment by wesm** [comment]
The concern I had was more that "build" and "install" are separate tasks (and not necessarily one size fits all) -- this PR adds an extra step to the "build" section

**Comment by shiro615** [comment]
Thank you for your comment.
I found the following description in c_glib README.

> Arrow C++ must be installed to build Arrow GLib. Run make install on Arrow C++ build directory.

this PR adds an extra step to the "build” section. I close this PR.

**Comment by kou** [comment]
I think that we need a document to install Arrow C++ from source. http://arrow.apache.org/install/ may be better place.

Now, we only have the following documents:
  * Install Arrow C++ as package
  * Build Arrow C++

**Comment by kou** [comment]
> in c_glib, we can document how to use an Arrow install in a custom location (without depending on the system directories).

I think so too. We need the document.

**Pull request closed without merging**
