### PR TITLE
ARROW-852: Also search for ARROW libs when pkg-config provided the path

### PR DESCRIPTION
**Pull request by xhochy**
Change-Id: Ic7fb227342782dfed5885f8fc5e73418fd31d504

### CODE REVIEW

**Comment by xhochy** [comment]
cc @kou

**Review by wesm — APPROVED** [review]
+1. I will wait for @kou's feedback

**Comment by kou** [comment]
+1.

BTW, linking to `libarrow.so.0.0.0` directly instead of linking to `libarrow.so` feature introduced by https://github.com/apache/parquet-cpp/pull/277 (see also: https://github.com/apache/parquet-cpp/pull/276#issuecomment-289816148 ) is missing. (I'm OK because I don't care about it.)

**Comment by kou** [comment]
Ah, sorry. It's for parquet-cpp not pyarrow.

**Pull request closed without merging**
