### PR TITLE
ARROW-11895: [Rust][DataFusion] Add support for more column statistics

### PR DESCRIPTION
**Pull request by Dandandan**
This PR

* adds max/min/distinct_count column statistics
* implements null count statistics for the parquet reader & table provider

This will allow implementing more advanced statistics based optimizations, such as outlined in this article.

https://databricks.com/blog/2017/08/31/cost-based-optimizer-in-apache-spark-2-2.html

### CODE REVIEW

**Comment by Dandandan** [comment]
FYI @andygrove I plan to use this later for some `ANALYZE / COMPUTE STATISTICS` support (would be useful for in memory data) and/or use parquet statistics to make the join order optimization more advanced.

**Comment by alamb** [comment]
BTW the test workspace check is also failing on master, so it may not be related to this PR. See more details on https://issues.apache.org/jira/browse/ARROW-11896

**Review by andygrove — APPROVED** [review]
LGTM. Thanks @Dandandan

**Comment by alamb** [comment]
FYI I merged https://github.com/apache/arrow/pull/9653 / [ARROW-11896](https://issues.apache.org/jira/browse/ARROW-11896) for the Rust CI checks which may affect this PR. If you see "Rust / AMD64 Debian 10 Rust stable test workspace" failing  with a linker error or no logs, rebasing against master will hopefully fix the problem

**Comment by seddonm1** [comment]
> FYI @andygrove I plan to use this later for some `ANALYZE / COMPUTE STATISTICS` support (would be useful for in memory data) and/or use parquet statistics to make the join order optimization more advanced.

This is really cool @Dandandan . And we don't have to make apply the silly limitation that Spark does where the table has to be registered in a Hive Metastore to allow you to calculate statistics!

**Comment by Dandandan** [comment]
> > FYI @andygrove I plan to use this later for some `ANALYZE / COMPUTE STATISTICS` support (would be useful for in memory data) and/or use parquet statistics to make the join order optimization more advanced.
> 
> This is really cool @Dandandan . And we don't have to make apply the silly limitation that Spark does where the table has to be registered in a Hive Metastore to allow you to calculate statistics!

I am also pretty excited about using this for data science / BI use cases where you could load all data in memory. I think that would be a pretty unique feature.

**Review by alamb — COMMENTED** [review]
Just to be clear, this is the infrastructure to implement more sophisticated statistics, but nothing (yet) takes advantage of them. I think it is a good step in the right direction. Thanks @Dandandan

**Review by alamb — APPROVED** [review]

**Pull request closed without merging**
