### PR TITLE
ARROW-8853: [Rust] [Integration Testing] Enable Flight tests 

### PR DESCRIPTION
**Pull request by carols10cents**
This PR has a few refactorings and then the main commit contains a new Flight integration test client and server 🎉 

The middleware scenario tests are currently skipped because they will fail until `tonic` can be updated to a version containing [a fix having to do with trailers](https://github.com/hyperium/tonic/pull/510); this is tracked in [ARROW-10961](https://issues.apache.org/jira/browse/ARROW-10961).

Some Rust <-> Java integration tests will fail until [this PR is merged](https://github.com/apache/arrow/pull/8963); I'm happy to rebase once that goes in, but I wanted to get code review started on this. Thank you!!

### CODE REVIEW

**Review by alamb — APPROVED** [review]
I reviewed this code commit by commit (thanks @carols10cents  for splitting it up into a easy-to-follow chain).

While I am not an expert in Arrow Flight, I did find the code easy to follow and understand and it made sense to me.  

As predicted, some java tests failed on [this integration test](https://github.com/apache/arrow/pull/9049/checks?check_run_id=1627551513) and I have pinged some people on https://github.com/apache/arrow/pull/8963 and hopefully we can get that merged soon. The error was

```
RuntimeError: Command failed: java -Dio.netty.tryReflectionSetAccessible=true -Darrow.struct.conflict.policy=CONFLICT_APPEND -cp /arrow/java/flight/flight-core/target/flight-core-3.0.0-SNAPSHOT-jar-with-dependencies.jar org.apache.arrow.flight.example.integration.IntegrationTestClient -port 39459 -j /tmp/arrow-integration-xu49kq36/generated_null_trivial.json
With output:
--------------
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Verifying location grpc+tcp://0.0.0.0:39459
Unknown error
java.lang.IllegalArgumentException: A batch can only be consumed if it contains a single ArrowBuf.
```

When I looked at the rest of the logs, I see the rust producer is running and passing. ❤️ ❤️  

```
2020-12-30T20:04:00.8176245Z ##########################################################
2020-12-30T20:04:00.8176859Z IPC: C++ producing, Rust consuming
2020-12-30T20:04:00.8177378Z ##########################################################
```

```
2020-12-30T20:05:45.7634027Z ##########################################################
2020-12-30T20:05:45.7634638Z IPC: Java producing, Rust consuming
2020-12-30T20:05:45.7635156Z ##########################################################
```

And there are others too. 

Really nice work 🎉

**Comment by alamb** [comment]
The full set of Rust CI tests did not run on this PR :(

Can you please rebase this PR against [apache/master](https://github.com/apache/arrow) to pick up the changes in https://github.com/apache/arrow/pull/9056 so that they do? 

I apologize for the inconvenience.

**Comment by carols10cents** [comment]
No problem at all, rebased! Thank you for the review ❤️

**Comment by nevi-me** [comment]
@carols10cents this needs a rebase :)

**Review by nevi-me — APPROVED** [review]
I've gone through the PR, and I don't have any comments. We can merge this after the blocking PR is merged, and the PR's been rebased.

**Comment by alamb** [comment]
@carols10cents  -- https://github.com/apache/arrow/pull/8963 was just merged - so hopefully after a rebase this PR will be ready too

**Comment by carols10cents** [comment]
Rebased, and CI is looking good!

**Comment by alamb** [comment]
🎉

**Pull request closed without merging**
