### PR TITLE
ARROW-5145: [C++] More input validation in release mode

### PR DESCRIPTION
**Pull request by pitrou**
This will make user experience better when passing invalid arguments.

### CODE REVIEW

**Comment by pitrou** [comment]
Travis-CI build at: https://travis-ci.org/pitrou/arrow/builds/551298704

The integration failure seems caused by https://www.traviscistatus.com/incidents/mm020jn4nzcn (Maven connectivity issues).

**Comment by pitrou** [comment]
@emkornfield

**Review by wesm — APPROVED** [review]
+1, overall this looks OK. As far as I can tell the DCHECK changes are mostly just renaming. Do you think we should just remove `DCHECK_*` from the codebase overall?

I'm going to compile the repro from ARROW-5145 as a check to see what happens

**Comment by pitrou** [comment]
No, `DCHECK`s are still used for internal invariants and also where performance is important or the check is expensive.

**Comment by wesm** [comment]
Got it. It's a bit anxiety-inducing to introduce so many unconditional validation checks. I think as long as the checks are cheap relative to the operation in context (e.g. allocating a new `ListArray`) that is fine. Our contract to the user should be that we will do best efforts input validation as long as it is cheap, but if something is shown to be a performance issue it may be changed to a debug-only check

**Comment by pitrou** [comment]
Yes, I was careful in this PR to only enable cheap checks, and not on a critical path (for example I left them as `DCHECK`s in our memory allocation routines).

**Comment by wesm** [comment]
Figured you would be careful =) 

I checked out the repro locally and this is definitely much nicer than crashing

```
$ gcc -std=c++11 ~/Downloads/repro.cpp -O3 -I$HOME/local/include -larrow -L$HOME/local/lib -lstdc++
11:16 ~/code/arrow  (ARROW-5145-release-mode-checks)$ ./a.out 
WARNING: Logging before InitGoogleLogging() is written to STDERR
F0627 11:16:30.481189 20099 type.cc:427]  Check failed: is_integer(index_type->id()) dictionary index type should be signed integer
*** Check failure stack trace: ***
Aborted (core dumped)
```

**Pull request closed without merging**
