### PR TITLE
ARROW-15670: [C++/Python/Packaging] Update conda pinnings and enable GCS on Windows

### PR DESCRIPTION
**Pull request by xhochy**

### CODE REVIEW

**Comment by xhochy** [comment]
@github-actions crossbow submit -g conda

**Comment by xhochy** [comment]
@github-actions crossbow submit conda-linux-gcc-py310-cpu

**Comment by xhochy** [comment]
@github-actions crossbow submit -g conda

**Review by kszucs — APPROVED** [review]
Thanks Uwe!

**Pull request closed without merging**
