### PR TITLE
ARROW-17018: [C++][Python] Timedelta dtype metadata base unit is globally mutated by the Table.to_pandas() method

### PR DESCRIPTION
**Pull request by cpcloud**

### CODE REVIEW

**Comment by kou** [comment]
@github-actions crossbow submit *pandas*

**Review by kou — APPROVED** [review]
+1

**Comment by kou** [comment]
@cpcloud Ah, sorry. I should have confirmed the Travis CI failure before I merge this:

https://app.travis-ci.com/github/apache/arrow/jobs/576129016#L9591

```text
=================================== FAILURES ===================================
_____________________ test_does_not_mutate_timedelta_dtype _____________________
    def test_does_not_mutate_timedelta_dtype():
        expected = np.dtype('<m8')
    
>       assert np.dtype(np.timedelta64) == expected
E       AssertionError: assert dtype('>m8') == dtype('<m8')
E        +  where dtype('>m8') = <class 'numpy.dtype'>(<class 'numpy.timedelta64'>)
E        +    where <class 'numpy.dtype'> = np.dtype
E        +    and   <class 'numpy.timedelta64'> = np.timedelta64
/usr/local/lib/python3.8/dist-packages/pyarrow/tests/test_pandas.py:4481: AssertionError
```

It seems that the test doesn't work on s390x (big-endian environment).

Could you confirm this case?

**Comment by cpcloud** [comment]
@kou Thanks! I'll fix the test right now and submit a PR.

**Comment by cpcloud** [comment]
@kou Fixed in #13560.

**Pull request merged**
