### PR TITLE
ARROW-17571: [Benchmarks] Default build for PyArrow seems to be debug

### PR DESCRIPTION
**Pull request by AlenkaF**
This PR tries to change PyArrow to be built in release and not in debug mode for Benchmarks builds.

### CODE REVIEW

**Comment by AlenkaF** [comment]
@ursabot please benchmark name=file-write lang=Python

**Comment by AlenkaF** [comment]
@ursabot please benchmark name=file-read lang=Python

**Comment by pitrou** [comment]
Ok, so the "CMake for PyArrow C++" step seems to run in DEBUG mode on [master](https://buildkite.com/apache-arrow/arrow-bci-benchmark-on-ec2-t3-xlarge-us-east-2/builds/1395#0182f319-c9c0-427a-a98e-94b6045d698f/33-2551) but in RELEASE mode on [this PR](https://buildkite.com/apache-arrow/arrow-bci-benchmark-on-ursa-i9-9960x/builds/1393#0182f445-ebc2-4f6c-abdd-0c69c2e833fd/36-2615).

This is with the caveat that I had to compare two different benchmarking configurations, since some have failed.

**Comment by AlenkaF** [comment]
If I understand correctly you are confirming this PR makes the correct change in the Benchmark build?

**Comment by pitrou** [comment]
> If I understand correctly you are confirming this PR makes the correct change in the Benchmark build?

Yes :-)

**Comment by AlenkaF** [comment]
Will rebase and run another benchmark, just to be sure. After that I would merge this PR, if there is no objection.

**Comment by AlenkaF** [comment]
The benchmarks look good, there is no objection so I will merge the PR.

**Pull request merged**
