### PR TITLE
ARROW-7869: [Python] Remove boost::system and boost::filesystem from Python wheels

### PR DESCRIPTION
**Pull request by pitrou**
Those dependencies are only required by C++ unit tests.

### CODE REVIEW

**Comment by pitrou** [comment]
@ursabot crossbow submit -g wheel

**Comment by pitrou** [comment]
@ursabot crossbow submit -g wheel

**Comment by pitrou** [comment]
@ursabot crossbow submit -g wheel

**Comment by kou** [comment]
@ursabot crossbow submit -g wheel

**Review by wesm — APPROVED** [review]
+1

**Pull request closed without merging**
