### PR TITLE
ARROW-16104: [Packaging] Add support for Ubuntu 22.04

### PR DESCRIPTION
**Pull request by kou**
This also includes a follow-up change for LLVM 14 support by ARROW-16105/#12782.

### CODE REVIEW

**Comment by kou** [comment]
@github-actions crossbow submit ubuntu-jammy*

**Comment by kou** [comment]
@github-actions crossbow submit ubuntu-jammy*

**Comment by kou** [comment]
@github-actions crossbow submit ubuntu-jammy*

**Comment by kou** [comment]
@github-actions crossbow submit ubuntu-jammy*

**Review by cyb70289 — APPROVED** [review]

**Comment by kou** [comment]
+1

**Pull request closed without merging**
