### PR TITLE
ARROW-8598: [Rust] `simd_compare_op` creates buffer of incorrect length

### PR DESCRIPTION
**Pull request by paddyhoran**

### CODE REVIEW

**Comment by paddyhoran** [comment]
cc yordan-pavlov

**Comment by nevi-me** [comment]
@paddyhoran do we need to worry about this, as it'd get removed by #7037?

**Comment by paddyhoran** [comment]
@nevi-me when I added this fix I hadn't looked at your PR removing packed_simd.  I introduced this bug so wanted to get a fix posted.  

Also, I wasn't sure what your timelines were for #7037.

**Review by nevi-me — APPROVED** [review]
LGTM, I still need to do more work on the PR to remove packed_simd, so that might take some more days. Happy to proceed with this fix.

**Pull request closed without merging**
