### PR TITLE
ARROW-4989: [C++] Find re2 on Ubuntu if asked to

### PR DESCRIPTION
**Pull request by pitrou**
This allows `cmake -DRE2_SOURCE=SYSTEM` to work from a Conda environment.

### CODE REVIEW

**Comment by wesm** [comment]
```
CMake Error at cmake_modules/ThirdpartyToolchain.cmake:850 (get_target_property):
  get_target_property() called with non-existent target "GLOG::glog".
Call Stack (most recent call first):
  CMakeLists.txt:544 (include)
```

**Comment by pitrou** [comment]
Yep, I forgot to process the GLOG_ variables in my original patch (cause I disable glog locally :-)).

**Comment by fsaintjacques** [comment]
I'm not sure if this is working as intended:

```
+ cmake -GNinja -DCMAKE_BUILD_TYPE=DEBUG -DARROW_BUILD_TESTS=ON -DARROW_BUILD_BENCHMARKS=ON -DBUILD_WARNING_LEVEL=CHECKIN -DARROW_USE_ASAN=OFF -DARROW_PYTHON=ON -DARROW_PARQUET=ON -DARROW_GANDIVA=ON -DARROW_PLASMA=ON -DARROW_FLIGHT=OFF -DCMAKE_INSTALL_PREFIX=/home/fsaintjacques/miniconda/envs/pyarrow-dev -DCMAKE_INST
ALL_LIBDIR=lib -DRE2_SOURCE=SYSTEM /home/fsaintjacques/src/db/arrow/cpp 

...

-- Checking for module 're2'
--   Found re2, version 0.0.0
-- Found RE2: /home/fsaintjacques/miniconda/envs/pyarrow-dev/lib/libre2.so
```

**Comment by pitrou** [comment]
I don't know. One problem is that when "CONDA" is given, our CMake build translates it internally to "SYSTEM", and so on the level of individual dependencies, the two are undistinguishable.

**Comment by fsaintjacques** [comment]
In your case, do you have both conda and system installed?

**Comment by pitrou** [comment]
No, only system.

**Comment by fsaintjacques** [comment]
and without this patch, this wouldn't work (just to make sure I test the proper behavior)?

**Comment by pitrou** [comment]
At least not here :-)

**Comment by fsaintjacques** [comment]
I can reproduce, one sub-issue, is that with this patch, if I don't provide `-DRE2_SOURCE=SYSTEM` it doesn't work.

**Comment by pitrou** [comment]
You mean even with the conda-installed `re2`? That's weird, especially as there's nothing `re2`-specific here. So it should fail for all conda-installed dependencies instead...

**Comment by fsaintjacques** [comment]
No, with conda's re2, it always pick it up. But if I have an activate conda shell, but with re2 installed with dpkg (and not within conda), it fails.

**Comment by pitrou** [comment]
Yes, that's normal. Within a conda environment, by default it doesn't look into system installs.

**Comment by fsaintjacques** [comment]
Then it works. +1 from me.

**Review by fsaintjacques — APPROVED** [review]

**Comment by kszucs** [comment]
Builds were failing because of wrong node version, after rebasing it should pass.

**Review by wesm — APPROVED** [review]
+1

**Pull request closed without merging**
