### PR TITLE
ARROW-1528: [GLib] Resolve recursive include dependency

### PR DESCRIPTION
**Pull request by kou**
Before:

  * arrow-glib/field.h depends on arrow-glib/data-type.h
  * arrow-glib/data-type.h depends on arrow-glib/field.h

After:

  * arrow-glib/field.h depends on arrow-glib/basic-data-type.h
  * arrow-glib/basic-data-type.h doesn't depend on arrow-glib/field.h
  * arrow-glib/composite-data-type.h depends on
    arrow-glib/basic-data-type.h and
    arrow-glib/composite-data-type.h

### CODE REVIEW

**Review by wesm — APPROVED** [review]
+1. Looks like there's an error with the doc build. I'm going to look at the macOS failure since the release candidate needs to go out today

**Comment by kou** [comment]
Oh... I'm checking now.
And I'm also workin on failure on macOS at https://github.com/kou/arrow/tree/glib-travis-macos .

**Comment by wesm** [comment]
ah ok, I'll wait for you and enjoy some coffee, then. thanks @kou! =)

**Comment by Humbedooh** [comment]
Ignore me, I'm just checking JIRA replication :)

**Comment by Humbedooh** [comment]
JIRA should work now, please ignore me :)

**Comment by Humbedooh** [comment]
One last test :3

**Comment by Humbedooh** [comment]
bah

**Comment by Humbedooh** [comment]
blu blu blu

**Comment by Humbedooh** [comment]
hmm

**Comment by kou** [comment]
It works again.
Failure on macOS is handled on #1529.

**Pull request closed without merging**
