### PR TITLE
ARROW-14519: [C++] Properly error if joining on unsupported type

### PR DESCRIPTION
**Pull request by lidavidm**
Instead of DCHECK, return a NotImplemented.

### CODE REVIEW

**Comment by lidavidm** [comment]
CC @michalursa. Note that the KeyColumnMetadata computed here is unused, but computing it here serves as a useful up-front check as otherwise we run into a DCHECK later during plan execution instead, so I opted to keep it.

**Comment by lidavidm** [comment]
Moved the validation to HashJoinSchema::ValidateSchemas as suggested on JIRA.

**Comment by lidavidm** [comment]
Also includes a fix for the build issues at HEAD.

**Review by michalursa — APPROVED** [review]
I realized that KeyColumnMetadata was not needed. The reason it exists is that it was meant for future changes to hash join and I forgot to remove it in the original hash join change.

**Pull request closed without merging**
