### PR TITLE
ARROW-6440: [Packaging][deb] Follow plasma-store-server name change

### PR DESCRIPTION
**Pull request by kou**

### CODE REVIEW

**Comment by kou** [comment]
@ursabot crossbow package -g linux

**Comment by kou** [comment]
xenial, bionic and cosmic are failed.
`plasma-store-server` failure is fixed but timeout on bionic and cosmic.
Timeout while downloading deb packages on xenial...

These failures are unrelated to this change.
I'll merge this.

We can't use Travis CI to build deb packages because Travis CI resource is poor for these jobs...

**Comment by kszucs** [comment]
@kou on short term we could port the linux packaging builds to azure pipelines, that might solve the timeout issue.

**Comment by kou** [comment]
Thanks for working on #5296 !

**Pull request closed without merging**
