### PR TITLE
ARROW-5260: [Python] Fix crash when deserializating from components in another process

### PR DESCRIPTION
**Pull request by pitrou**

### CODE REVIEW

**Review by wesm — APPROVED** [review]
+1, good catch

**Comment by pitrou** [comment]
Trying to debug an AppVeyor failure...

**Comment by pitrou** [comment]
@wesm Can you reproduce the issue I'm having on AppVeyor? I really don't understand what is happening:
https://ci.appveyor.com/project/pitrou/arrow/builds/24370752/job/kgelhsewticqkfdt

**Comment by pitrou** [comment]
I think I managed to fix the AppVeyor issue.

**Comment by pitrou** [comment]
AppVeyor build: https://ci.appveyor.com/project/pitrou/arrow/builds/24674109

**Comment by wesm** [comment]
That does not look like it was fun, glad you figured it out

**Pull request closed without merging**
