### PR TITLE
GH-39732: [Python][CI] Fix test failures with latest/nightly pandas

### LINKED ISSUE #39732: [Python][CI] Failures on latest/nightly pandas
### Describe the bug, including details regarding any error messages, version, and platform.

The tests on the CI started failing with the new release of pandas (19 jan 2024, version 2.2.0) with:

```
=================================== FAILURES ===================================
__________________ test_array_protocol_pandas_extension_types __________________

monkeypatch = <_pytest.monkeypatch.MonkeyPatch object at 0x7fbb44648c40>

    def test_array_protocol_pandas_extension_types(monkeypatch):
        # ARROW-7022 - ensure protocol works for Period / Interval extension dtypes
    
        storage = pa.array([1, 2, 3], type=pa.int64())
        expected = pa.ExtensionArray.from_storage(DummyExtensionType(), storage)
    
        monkeypatch.setattr(pd.arrays.PeriodArray, "__arrow_array__",
                            PandasArray__arrow_array__, raising=False)
        monkeypatch.setattr(pd.arrays.IntervalArray, "__arrow_array__",
                            PandasArray__arrow_array__, raising=False)
        for arr in [pd.period_range("2012-01-01", periods=3, freq="D").array,
                    pd.interval_range(1, 4).array]:
            result = pa.array(arr)
            assert result.equals(expected)
            result = pa.array(pd.Series(arr))
            assert result.equals(expected)
            result = pa.array(pd.Index(arr))
            assert result.equals(expected)
            result = pa.table(pd.DataFrame({'a': arr})).column('a').chunk(0)
>           assert result.equals(expected)
E           assert False
E            +  where False = <bound method Array.equals of <pyarrow.lib.Int64Array object at 0x7fbb446b7690>\n[\n  1,\n  2,\n  3\n]>(<pyarrow.lib.ExtensionArray object at 0x7fbb446b7a10>\n[\n  1,\n  2,\n  3\n])
E            +    where <bound method Array.equals of <pyarrow.lib.Int64Array object at 0x7fbb446b7690>\n[\n  1,\n  2,\n  3\n]> = <pyarrow.lib.Int64Array object at 0x7fbb446b7690>\n[\n  1,\n  2,\n  3\n].equals

usr/local/lib64/python3.11/site-packages/pyarrow/tests/test_pandas.py:4161: AssertionError
___________________ test_table_factory_function_args_pandas ____________________

    @pytest.mark.pandas
    def test_table_factory_function_args_pandas():
        import pandas as pd
    
        # from_pandas not accepting names or metadata:
>       with pytest.raises(ValueError):
E       Failed: DID NOT RAISE <class 'ValueError'>
```

See:
https://github.com/ursacomputing/crossbow/actions/runs/7604845464/job/20708281882
https://github.com/ursacomputing/crossbow/actions/runs/7604845540/job/20708282208

### Component(s)

Python

### PR DESCRIPTION
**Pull request by AlenkaF**
This PR rearranges if-else blocks in the `table` function (`table.pxi`) so that pandas dataframe object comes before checking for `__arrow_c_stream__` and `__arrow_c_array__`.
* Closes: #39732

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
Alternatively, we might also want to do a similar check of the `names` and `metadata` keywords in case of objects that implement the protocol. Because also in that case we are currently ignoring those keywords.

**Comment by jorisvandenbossche** [comment]
(this is somewhat similar as the discussion in https://github.com/apache/arrow/issues/39394#issuecomment-1881112769 for `pa.array(..)`, while here it is for `pa.table(..)`)

**Comment by AlenkaF** [comment]
Did I understand correctly? -> https://github.com/apache/arrow/pull/39760/commits/20be42559bb9db8c695e46eafe828cdcffe19a10

**Review by jorisvandenbossche — APPROVED** [review]
Thanks!

**Pull request merged**
