### PR TITLE
ARROW-12379: [C++] Fix ThreadSanitizer failure in SerialExecutor

### PR DESCRIPTION
**Pull request by pitrou**

### CODE REVIEW

**Comment by pitrou** [comment]
cc @westonpace

**Comment by pitrou** [comment]
I've checked locally that this fixes the TSan failures.

**Review by lidavidm — APPROVED** [review]
So the issue was that we might be in the middle of SpawnReal on an external thread while the main thread was destructing the state (e.g. it exited early due to an error or something)?

**Comment by pitrou** [comment]
Yes.

**Comment by pitrou** [comment]
Hm, wait, I shouldn't unlock before notifying in MarkFinished().

**Comment by lidavidm** [comment]
Additionally, since we're handing around Executor* instead of shared_ptr<Executor> or something, there's still the possibility that an I/O thread tries to use a dangling reference, right? The main thread has to make sure to block and wait for all I/O threads it spawns under all conditions.

**Comment by pitrou** [comment]
Well, the idea is that the top-level task waits for all dependent tasks to finish, I think.

**Comment by lidavidm** [comment]
True, it's just a potentially easy pitfall (though it comes with the territory I suppose).

**Comment by pitrou** [comment]
Things may get tricky if cancellation or early exit is involved indeed...

**Comment by lidavidm** [comment]
Seems Crossbow built Arrow master, not this branch. I threw up https://github.com/lidavidm/crossbow/actions/runs/748753207

**Review by lidavidm — APPROVED** [review]

**Comment by lidavidm** [comment]
The crossbow job passes!

**Comment by pitrou** [comment]
Github Actions: https://github.com/pitrou/arrow/actions?query=branch%3AARROW-12379-tsan++
Travis-CI: https://travis-ci.com/github/pitrou/arrow/builds/223062391

**Comment by westonpace** [comment]
Thanks @pitrou .  A few thoughts (nothing worrisome):

Why `deque` instead of `queue`?  I don't mind the change.  I just want to make sure I'm not missing some piece of knowledge.

> Things may get tricky if cancellation or early exit is involved indeed...
Cancellation should still flush the task queue.  Early exit (via bad `Status`) should still flush the task queue.  It is important we do because in both cases the remaining tasks might need to do some cleanup to handle the error.  Exceptions/assertions might not but we're already in crash territory there.

**Comment by pitrou** [comment]
It's only for consistency, since `deque` is used for the threadpool executor.

**Pull request closed without merging**
