### PR TITLE
GH-15274: [Java][FlightRPC] handle null keystore password

### LINKED ISSUE #15274: [Java] [Flight] NullPointerException when trust store password not specified on Linux
### Describe the bug, including details regarding any error messages, version, and platform.

When using the Flight JDBC driver on Linux (JDBC version 10.0.0, Ubuntu 22.04, using DBeaver 22.3.2 as the JDBC GUI) with a secure endpoint, a NullPointerException is thrown.

```
NullPointerException
java.lang.NullPointerException
        at org.apache.arrow.driver.jdbc.client.utils.ClientAuthenticationUtils.getCertificateInputStreamFromSystem(ClientAuthenticationUtils.java:163)
        at org.apache.arrow.driver.jdbc.client.ArrowFlightSqlClientHandler$Builder.build(ArrowFlightSqlClientHandler.java:564)
        at org.apache.arrow.driver.jdbc.ArrowFlightConnection.createNewClientHandler(ArrowFlightConnection.java:109)
        at org.apache.arrow.driver.jdbc.ArrowFlightConnection.createNewConnection(ArrowFlightConnection.java:88)
        at org.apache.arrow.driver.jdbc.ArrowFlightJdbcDriver.connect(ArrowFlightJdbcDriver.java:80)
        at org.apache.arrow.driver.jdbc.ArrowFlightJdbcDriver.connect(ArrowFlightJdbcDriver.java:48)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$0(JDBCDataSource.java:206)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$1(JDBCDataSource.java:225)
        at org.jkiss.dbeaver.utils.SecurityManagerUtils.wrapDriverActions(SecurityManagerUtils.java:96)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:223)
        at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.openConnection(GenericDataSource.java:143)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:103)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:102)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.<init>(JDBCRemoteInstance.java:61)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeRemoteInstance(JDBCDataSource.java:128)
        at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.<init>(GenericDataSource.java:109)
        at org.jkiss.dbeaver.ext.generic.model.meta.GenericMetaModel.createDataSourceImpl(GenericMetaModel.java:91)
        at org.jkiss.dbeaver.ext.generic.GenericDataSourceProvider.openDataSource(GenericDataSourceProvider.java:106)
        at org.jkiss.dbeaver.registry.DataSourceDescriptor.openDataSource(DataSourceDescriptor.java:1159)
        at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:1028)
        at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
        at org.jkiss.dbeaver.runtime.jobs.ConnectionTestJob.run(ConnectionTestJob.java:103)
        at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

It seems to be caused by the driver requiring a trust store password on Linux, even though that shouldn't be required. A workaround that seems to work is specifying the connection URI as `jdbc:arrow-flight://<SERVER.NAME>:32010/?trustStorePassword=changeit`

### Component(s)

FlightRPC, Java

### PR DESCRIPTION
**Pull request by mumblepins**
Fixes #15274 by handling trust store passwords that are null.
* Closes: #15274

### CODE REVIEW

**Review by lidavidm — APPROVED** [review]
Thanks!

**Comment by lidavidm** [comment]
Hmm, actually, is there a way to add a unit test here?

**Comment by mumblepins** [comment]
@lidavidm Added a unit test as best as I'm able

**Comment by lidavidm** [comment]
Thank you!

**Pull request merged**
