### PR TITLE
ARROW-3707: [C++] Fix test regression with zstd 1.3.7

### PR DESCRIPTION
**Pull request by pitrou**
Upstream issue: https://github.com/facebook/zstd/issues/1385

### CODE REVIEW

**Comment by pitrou** [comment]
The Windows compilation failure is in the static CRT build. The only thing that changed is bumping the zstd version.
```
libzstd_static.lib(threading.obj) : error LNK2019: unresolved external symbol __imp__beginthreadex referenced in function ZSTD_pthread_create
```

@MaxRis can you advise here?

**Comment by MaxRis** [comment]
@pitrou probably, there is some zstd patching related issue (like linkage to static crt was not configured properly). Need to check more deeply

**Comment by pitrou** [comment]
I _think_ I unbroke the Windows builds now.
@MaxRis If you are interested in zstd, it seems it's not possible to do a debug build using the cmake files anymore: https://github.com/facebook/zstd/pull/1278

**Comment by kou** [comment]
Now, `Static_Crt_Build` job is green. Can we remove it from `allow_failures`?

**Comment by xhochy** [comment]
This also needs a rebase to remove the RAT failure.

**Pull request closed without merging**
