### PR TITLE
GH-44690: [C++] NumericBuilder::AppendValues append vector prevent from ub

### PR DESCRIPTION
**Pull request by mapleFU**
### Rationale for this change

Add boundary check for `NumericBuilder::AppendValues` for std::vector

Originally, it will :

1. `AppendValues` might has `std::vector` as arguments, `std::vector::data` might be used
2. `std::vector::data` might returns `nullptr` if size == 0: https://en.cppreference.com/w/cpp/container/vector/data
3. https://en.cppreference.com/w/cpp/string/byte/memcpy memcpy says, "If either dest or src is an [invalid or null pointer](https://en.cppreference.com/w/cpp/language/pointer#Pointers), the behavior is undefined, even if count is zero."

### What changes are included in this PR?

Add boundary check for `NumericBuilder::AppendValues` for std::vector

### Are these changes tested?

Covered by existing

### Are there any user-facing changes?

no

* GitHub Issue: #44690

### CODE REVIEW

**Review by pitrou — APPROVED** [review]

**Comment by pitrou** [comment]
Well, we do have the `MakeNonNull` helper which I had forgotten about.

**Comment by mapleFU** [comment]
@felipecrv this would be a better solution, maybe I can move forward!

**Comment by felipecrv** [comment]
> Well, we do have the `MakeNonNull` helper which I had forgotten about.

I think it's a weird way to go about fixing this. It's easier to accept that `memcpy` is a bad abstraction when it can't handle 0-length slices for any value of base pointer.

**Comment by pitrou** [comment]
I agree that `memcpy` is a bad abstraction in that regard. But the main issue here is to remember to call the appropriate helper, regardless of whether it's `MakeNonNull` or a `memcpy` wrapper. :)

**Comment by felipecrv** [comment]
Easy to forbid `memcpy` and suggest alternative with `clang-tidy`

```
bugprone-unsafe-functions.CustomFunctions="
  functionRegex1[, replacement1[, reason1]];
  functionRegex2[, replacement2[, reason2]];
  ...
"
```

https://clang.llvm.org/extra/clang-tidy/checks/bugprone/unsafe-functions.html

**Comment by pitrou** [comment]
Hmm, perhaps that can be discussed on the dev ML?

**Comment by mapleFU** [comment]
Let me draft a mail later tonight

**Pull request merged**
