### PR TITLE
MINOR: [C++][Parquet] Add table->ValidateFull() to LegacyTwoLevelList test

### PR DESCRIPTION
**Pull request by wgtmac**
### Rationale for this change

Add a validate call as suggested by https://github.com/apache/arrow/pull/43995#discussion_r1856174932

### What changes are included in this PR?

Add a table->ValidateFull() to LegacyTwoLevelList test case.

### Are these changes tested?

Yes

### Are there any user-facing changes?

No

### CODE REVIEW

**Comment by wgtmac** [comment]
@pitrou I have added the validate call per your comment.

**Review by pitrou — APPROVED** [review]
Thanks @wgtmac !

**Review by kou — APPROVED** [review]
+1

**Comment by wgtmac** [comment]
Just merged it. Thanks @pitrou @kou!

**Pull request merged**
