### PR TITLE
ARROW-13859: [Java] Add code coverage support

### PR DESCRIPTION
**Pull request by laurentgo**
Add optional code coverage support to the Maven build configuration
using the JaCoCo plugin.

Code coverage reporting is enabled when using the `code-coverage`
profile.

### CODE REVIEW

**Comment by liyafan82** [comment]
@laurentgo Thanks for working on this.
Could you please explain the main benefits of jacoco over sure-fire?

**Comment by laurentgo** [comment]
>  Could you please explain the main benefits of jacoco over sure-fire?
It's actually 2 very different sets of plugins:
- surefire (and failsafe) are in charge of executing unit tests (resp integration tests) written by developers. Those plugins only manage test executions but do not capture test coverage
- jacoco plugin is an agent added to the JVM when surefire (and failsafe) tests are running to capture the coverage, along with several mojos to actual generate reports.

**Comment by liyafan82** [comment]
> * jacoco

@laurentgo Sounds like an attractive tool. Thanks for the explanation.
I am a little curious about the performance impact?

**Comment by laurentgo** [comment]
The `code-coverage` profile is not enabled by default, so there should be no performance impact. When enabled, the impact seems negligeable except for the algorithm module which jumps from 1min to 20min so I may have changed something inadvertently here, or the current code would trigger lots of code coverage capture somehow.
In general the main impact I see is a slight increased of stack consumption as the instrumented code needs some extra space for counting method calls and branches.

**Comment by liyafan82** [comment]
> The `code-coverage` profile is not enabled by default, so there should be no performance impact. When enabled, the impact seems negligeable except for the algorithm module which jumps from 1min to 20min so I may have changed something inadvertently here, or the current code would trigger lots of code coverage capture somehow.
> In general the main impact I see is a slight increased of stack consumption as the instrumented code needs some extra space for counting method calls and branches.

@laurentgo Thanks a lot for the investigation. It sounds reasonable.

**Review by liyafan82 — APPROVED** [review]
LGTM

**Comment by emkornfield** [comment]
+1 Should there be a CI target that publishes code coverage changes?

**Pull request closed without merging**
