### PR TITLE
ARROW-17592: [Python][Packaging] Move Windows wheel build to VS 2019

### PR DESCRIPTION
**Pull request by pitrou**

### CODE REVIEW

**Comment by pitrou** [comment]
@github-actions crossbow submit wheel-windows*

**Comment by pitrou** [comment]
Revision: 4346bd10ffa467ace70977db753ecf7a6c3e46e4

Submitted crossbow builds: [ursacomputing/crossbow @ vs2019-0](https://github.com/ursacomputing/crossbow/branches/all?query=vs2019-0)

|Task|Status|
|----|------|
|wheel-windows-cp310-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:vs2019-0-github-wheel-windows-cp310-amd64)|
|wheel-windows-cp37-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:vs2019-0-github-wheel-windows-cp37-amd64)|
|wheel-windows-cp38-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:vs2019-0-github-wheel-windows-cp38-amd64)|
|wheel-windows-cp39-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:vs2019-0-github-wheel-windows-cp39-amd64)|

**Comment by pitrou** [comment]
Revision: 4346bd10ffa467ace70977db753ecf7a6c3e46e4

Submitted crossbow builds: [ursacomputing/crossbow @ vs2019-0](https://github.com/ursacomputing/crossbow/branches/all?query=vs2019-0)

|Task|Status|
|----|------|
|wheel-windows-cp310-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:vs2019-0-github-wheel-windows-cp310-amd64)|
|wheel-windows-cp37-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:vs2019-0-github-wheel-windows-cp37-amd64)|
|wheel-windows-cp38-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:vs2019-0-github-wheel-windows-cp38-amd64)|
|wheel-windows-cp39-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:vs2019-0-github-wheel-windows-cp39-amd64)|

**Comment by pitrou** [comment]
Hmm, so it seems the Python 3 chocolate install is failing because of an existing Python install:
https://github.com/ursacomputing/crossbow/runs/8133106879?check_suite_focus=true#step:6:2589

even though Python was specifically installed before:
https://github.com/ursacomputing/crossbow/runs/8133106879?check_suite_focus=true#step:6:2388

@kszucs @kou Would you know why that would be?

**Comment by pitrou** [comment]
Revision: a197719aa599aefee3cd45947aa66e28205e3fce

Submitted crossbow builds: [ursacomputing/crossbow @ vs2019-2](https://github.com/ursacomputing/crossbow/branches/all?query=vs2019-2)

|Task|Status|
|----|------|
|wheel-windows-cp310-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:vs2019-2-github-wheel-windows-cp310-amd64)|
|wheel-windows-cp37-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:vs2019-2-github-wheel-windows-cp37-amd64)|
|wheel-windows-cp38-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:vs2019-2-github-wheel-windows-cp38-amd64)|
|wheel-windows-cp39-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:vs2019-2-github-wheel-windows-cp39-amd64)|

**Comment by pitrou** [comment]
Revision: 2740827769acf51946cb20d341250b91b1eefc66

Submitted crossbow builds: [ursacomputing/crossbow @ vs2019-3](https://github.com/ursacomputing/crossbow/branches/all?query=vs2019-3)

|Task|Status|
|----|------|
|wheel-windows-cp310-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:vs2019-3-github-wheel-windows-cp310-amd64)|
|wheel-windows-cp37-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:vs2019-3-github-wheel-windows-cp37-amd64)|
|wheel-windows-cp38-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:vs2019-3-github-wheel-windows-cp38-amd64)|
|wheel-windows-cp39-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions?query=branch:vs2019-3-github-wheel-windows-cp39-amd64)|

**Comment by kou** [comment]
It seems that some Python related products were failed to uninstall:

https://github.com/ursacomputing/crossbow/runs/8133106879?check_suite_focus=true#step:6:2437

```text
Executing (\\298D943B4072\ROOT\CIMV2:Win32_Product.IdentifyingNumber="{1D60E386-848D-45D1-BB0A-7E26A3E32011}",Name="Python 3.10.6 Utility Scripts (64-bit)",Vendor="Python Software Foundation",Version="3.10.6150.0")->Uninstall()


Method execution successful.

Out Parameters:
instance of __PARAMETERS
{
	ReturnValue = 1601; <- Not 0
};
```

I tried to install https://www.python.org/ftp/python/3.10.6/python-3.10.6-amd64.exe on local Windows and found the followings:

* I can see only "Python 3.10.6 (64-bit)" entry in control panel. (I can't see any other Python related entries in control panel.)
* But I can see multiple  Python related entries by `wmic product list status`[1] but there is no "Python 3.10.6 (64-bit)" entry.

[1]
```text
InstallState  Name                                                            Version         
5             Python 3.10.6 Standard Library (64-bit)                         3.10.6150.0     
5             Python 3.10.6 Test Suite (64-bit)                               3.10.6150.0     
5             Python 3.10.6 Executables (64-bit)                              3.10.6150.0     
5             Python 3.10.6 Utility Scripts (64-bit)                          3.10.6150.0     
5             Python 3.10.6 Documentation (64-bit)                            3.10.6150.0     
5             Python 3.10.6 Tcl/Tk Support (64-bit)                           3.10.6150.0     
5             Python 3.10.6 Core Interpreter (64-bit)                         3.10.6150.0     
5             Python 3.10.6 Development Libraries (64-bit)                    3.10.6150.0     
5             Python 3.10.6 pip Bootstrap (64-bit)                            3.10.6150.0     
```

I'm not sure how Python's Windows installer is built but it seems that we need to use the uninstaller provided by "Python 3.10.6 (64-bit)" or run uninstallers of "Python 3.10.6 * (64-bit)" in proper order.

**Comment by pitrou** [comment]
I'm gonna close this as it's entirely out of date.

**Pull request closed without merging**
