### PR TITLE
WIP: [Release] Verify release-14.0.2-rc2

### PR DESCRIPTION
**Pull request by raulcd**
PR to verify Release Candidate

### CODE REVIEW

**Comment by raulcd** [comment]
@github-actions crossbow submit  --group verify-rc-source --param release=14.0.2 --param rc=2

**Comment by raulcd** [comment]
Revision: 0b9c1e06ee5612506f17f14cb7a253cddf8886ce

Submitted crossbow builds: [ursacomputing/crossbow @ release-14.0.2-rc2-0](https://github.com/ursacomputing/crossbow/branches/all?query=release-14.0.2-rc2-0)

|Task|Status|
|----|------|
|almalinux-8-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-14.0.2-rc2-0-github-almalinux-8-amd64)|
|almalinux-8-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/7150766538/job/19474392213)|
|almalinux-9-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-14.0.2-rc2-0-github-almalinux-9-amd64)|
|almalinux-9-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-14.0.2-rc2-0-github-almalinux-9-arm64)|
|amazon-linux-2023-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/7150766721/job/19474393005)|
|amazon-linux-2023-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/7150766733/job/19474392872)|
|centos-7-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/7150766827/job/19474393101)|
|centos-8-stream-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/7150766636/job/19474392640)|
|centos-8-stream-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-14.0.2-rc2-0-github-centos-8-stream-arm64)|
|centos-9-stream-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-14.0.2-rc2-0-github-centos-9-stream-amd64)|
|centos-9-stream-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/7150766881/job/19474393205)|
|conan-maximum|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/7150766734/job/19474392969)|
|conan-minimum|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-14.0.2-rc2-0-github-conan-minimum)|
|debian-bookworm-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/7150766544/job/19474392309)|
|debian-bookworm-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/7150766225/job/19474391294)|
|debian-bullseye-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/7150766955/job/19474393456)|
|debian-bullseye-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/7150766590/job/19474392458)|
|debian-trixie-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/7150766077/job/19474390934)|
|debian-trixie-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/7150766841/job/19474393146)|
|java-jars|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/7150766284/job/19474392972)|
|nuget|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/7150766070/job/19474390901)|
|python-sdist|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/7150766731/job/19474392747)|
|r-binary-packages|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/7150766230/job/19474391317)|
|test-ubuntu-22.04-docs|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/7150766598/job/19474392523)|
|ubuntu-focal-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-14.0.2-rc2-0-github-ubuntu-focal-amd64)|
|ubuntu-focal-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/7150766485/job/19474392121)|
|ubuntu-jammy-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/7150766224/job/19474391330)|
|ubuntu-jammy-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/7150766399/job/19474391760)|
|ubuntu-lunar-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-14.0.2-rc2-0-github-ubuntu-lunar-amd64)|
|ubuntu-lunar-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/7150766183/job/19474391191)|
|wheel-clean|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/7150766165/job/19474391107)|
|wheel-macos-big-sur-cp310-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/7150766402/job/19474391877)|
|wheel-macos-big-sur-cp311-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/7150766182/job/19474391126)|
|wheel-macos-big-sur-cp312-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/7150766462/job/19474391957)|
|wheel-macos-big-sur-cp38-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/7150766146/job/19474391054)|
|wheel-macos-big-sur-cp39-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-14.0.2-rc2-0-github-wheel-macos-big-sur-cp39-arm64)|
|wheel-macos-mojave-cp310-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/7150766441/job/19474391874)|
|wheel-macos-mojave-cp311-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-14.0.2-rc2-0-github-wheel-macos-mojave-cp311-amd64)|
|wheel-macos-mojave-cp312-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-14.0.2-rc2-0-github-wheel-macos-mojave-cp312-amd64)|
|wheel-macos-mojave-cp38-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/7150766537/job/19474392288)|
|wheel-macos-mojave-cp39-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/7150766380/job/19474391709)|
|wheel-manylinux-2-28-cp310-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/7150766211/job/19474391210)|
|wheel-manylinux-2-28-cp310-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-14.0.2-rc2-0-github-wheel-manylinux-2-28-cp310-arm64)|
|wheel-manylinux-2-28-cp311-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/7150766635/job/19474392625)|
|wheel-manylinux-2-28-cp311-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/7150766083/job/19474390929)|
|wheel-manylinux-2-28-cp312-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/7150766714/job/19474392734)|
|wheel-manylinux-2-28-cp312-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/tree/release-14.0.2-rc2-0-github-wheel-manylinux-2-28-cp312-arm64)|
|wheel-manylinux-2-28-cp38-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/7150766785/job/19474393065)|
|wheel-manylinux-2-28-cp38-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/7150766877/job/19474393208)|
|wheel-manylinux-2-28-cp39-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/7150766283/job/19474391529)|
|wheel-manylinux-2-28-cp39-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/7150766596/job/19474392557)|
|wheel-manylinux-2014-cp310-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/7150766577/job/19474392357)|
|wheel-manylinux-2014-cp310-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/7150766904/job/19474393291)|
|wheel-manylinux-2014-cp311-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/7150766468/job/19474391997)|
|wheel-manylinux-2014-cp311-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/7150766883/job/19474393250)|
|wheel-manylinux-2014-cp312-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/7150766184/job/19474391168)|
|wheel-manylinux-2014-cp312-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/7150766703/job/19474392742)|
|wheel-manylinux-2014-cp38-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/7150766704/job/19474392727)|
|wheel-manylinux-2014-cp38-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/7150766278/job/19474391522)|
|wheel-manylinux-2014-cp39-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/7150766176/job/19474391113)|
|wheel-manylinux-2014-cp39-arm64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/7150766410/job/19474391714)|
|wheel-windows-cp310-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/7150766069/job/19474390915)|
|wheel-windows-cp311-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/7150766267/job/19474391524)|
|wheel-windows-cp312-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/7150766241/job/19474391418)|
|wheel-windows-cp38-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/7150766997/job/19474406177)|
|wheel-windows-cp39-amd64|[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/7150766461/job/19474392032)|

**Comment by raulcd** [comment]
I am unsure on why some of the macOS verification tasks are failing. Some of them seem to fail due to missing `.git` directory and others seem to have issues with a certificate for TLS and encryption but those are not failing on main and can't find an issue related. I know there has been several changes on the testing git submodule which might be related. @kou the binaries have been generated (Only one failed that [I am currently re-running](https://github.com/ursacomputing/crossbow/actions/runs/7150766881/job/19476140935)). Should we upload binaries and send the vote or do you think we should investigate those verification failures further?

**Comment by kou** [comment]
I think that we should investigate them because there are many failures. But we can do it with other developers.
How about starting a vote with a note about these failures?
I'll sign and upload binaries.

**Comment by kou** [comment]
Uploaded.

**Comment by raulcd** [comment]
@github-actions crossbow submit  --group verify-rc-binaries --group verify-rc-wheels --param release=14.0.2 --param rc=2

**Comment by raulcd** [comment]
Closing do to creation of RC3

**Pull request closed without merging**
