### PR TITLE
ARROW-14653: [R] head() hangs on CSV datasets > 600MB

### PR DESCRIPTION
**Pull request by thisisnic**
This PR switches to using the asynchronous scanner by default when reading in datasets.  I've tested it locally on a large dataset (2.5Gb of CSV files) and it does resolve the original issue, but due to the size of the files involved I wasn't sure this was something I could easily write tests for.

### CODE REVIEW

**Comment by thisisnic** [comment]
@ursabot please benchmark lang=r

**Review by westonpace — APPROVED** [review]
This will hopefully be superseded by #11991 but it can't hurt to have in the meantime.

**Comment by jonkeane** [comment]
@ursabot please benchmark lang=R

**Comment by jonkeane** [comment]
@ursabot please benchmark

**Pull request closed without merging**
