### PR TITLE
GH-41333: [C++][CMake] Prefer protobuf-config.cmake to FindProtobuf.cmake

### PR DESCRIPTION
**Pull request by kou**
### Rationale for this change

`protobuf::libprotobuf` provided by `FindProtobuf.cmake` (provided by CMake) may not provide needed dependencies such as Abseil.

### What changes are included in this PR?

Try `protobuf-config.cmake` provided by Protobuf before `FindProtobuf.cmake`.
`protobuf::libprotobuf` provided by `protobuf-config.cmake` must have needed dependencies.

### Are these changes tested?

Yes.

### Are there any user-facing changes?

Yes.
* GitHub Issue: #41333

### CODE REVIEW

**Comment by kou** [comment]
@github-actions crossbow submit -g cpp -g python -g r

**Comment by kou** [comment]
@github-actions crossbow submit -g cpp -g python -g r

**Comment by raulcd** [comment]
Thanks @kou I was trying something similar on Conda:
```diff
diff --git a/cpp/cmake_modules/FindProtobufAlt.cmake b/cpp/cmake_modules/FindProtobufAlt.cmake
index 15fe1b4..b516415 100644
--- a/cpp/cmake_modules/FindProtobufAlt.cmake
+++ b/cpp/cmake_modules/FindProtobufAlt.cmake
@@ -28,9 +28,21 @@ endif()
 if(ProtobufAlt_FIND_QUIETLY)
   list(APPEND find_package_args QUIET)
 endif()
-find_package(Protobuf ${find_package_args})
-set(ProtobufAlt_FOUND ${Protobuf_FOUND})
-if(ProtobufAlt_FOUND)
+find_package(protobuf CONFIG ${find_package_args})
+set(ProtobufAlt_FOUND ${protobuf_FOUND})
+if(NOT ProtobufAlt_FOUND)
+  find_package(Protobuf ${find_package_args})
+  set(ProtobufAlt_FOUND ${Protobuf_FOUND})
+endif()
+if(protobuf_FOUND)
+  set(ProtobufAlt_FOUND ${protobuf_FOUND})
+  set(ProtobufAlt_VERSION ${protobuf_VERSION})
+  set(ProtobufAlt_VERSION_MAJOR ${protobuf_VERSION_MAJOR})
+  set(ProtobufAlt_VERSION_MINOR ${protobuf_VERSION_MINOR})
+  set(ProtobufAlt_VERSION_PATCH ${protobuf_VERSION_PATCH})
+  set(ProtobufAlt_VERSION_TWEEK ${protobuf_VERSION_TWEEK})
+elseif(Protobuf_FOUND)
+  set(ProtobufAlt_FOUND ${Protobuf_FOUND})
   set(ProtobufAlt_VERSION ${Protobuf_VERSION})
   set(ProtobufAlt_VERSION_MAJOR ${Protobuf_VERSION_MAJOR})
   set(ProtobufAlt_VERSION_MINOR ${Protobuf_VERSION_MINOR})

```

**Review by raulcd — APPROVED** [review]
Error seems unrelated and I arrived to a really similar patch from the initial pointers.

**Comment by raulcd** [comment]
@github-actions crossbow submit verify-rc-source-cpp-macos-arm64

**Pull request merged**
