### PR TITLE
ARROW-1971: [Python] Add pandas serialization to the default

### PR DESCRIPTION
**Pull request by devin-petersohn**
Moving pandas register into default register.

### CODE REVIEW

**Comment by robertnishihara** [comment]
@wesm Is there any reason to use `_register_pandas_arrow_handlers` over `_register_custom_pandas_handlers`? Why not always use `_register_custom_pandas_handlers`? Is there a difference in generality?

**Comment by wesm** [comment]
I'd be perfectly fine with the faster pandas serialization code path. I guess the one thing separating the `pandas_serialization_context` from the default one would be the handling of NumPy object arrays?

**Comment by robertnishihara** [comment]
Is that related to the choice of `_register_pandas_arrow_handlers` versus `_register_custom_pandas_handlers`? Both of those can be used with both of the custom numpy object array serializers, right?

**Review by wesm — APPROVED** [review]
+1, thanks @devin-petersohn!

**Comment by robertnishihara** [comment]
Yes, thanks @devin-petersohn! This PR looks good to me.

@wesm, is speed the *only* difference between the two implementations? Just curious if there are edge cases.

**Comment by wesm** [comment]
I think the new version will have marginally better support for "weird pandas data". If you run into issues please open issues so we can investigate

**Pull request closed without merging**
