### PR TITLE
ARROW-8141: [C++] speed unpack1_32 using intrinsics API

### PR DESCRIPTION
**Pull request by frankdjx**
BM_PlainDecodingBoolean benchmark shows about 1.3x to 1.7x improvements per the size
against the avx512 complier optimizations.

Signed-off-by: Frank Du <frank.du@intel.com>

### CODE REVIEW

**Comment by jianxind** [comment]
We are running benchmark on the arrow avx512 build, perf show unpack1_32 as the major hotspot for BM_PlainDecodingBoolean indicator.

Implement this func with Intrinsics code show big improvements. See below the results on CLX 8280 cpu which is capable of AVX512.


Indictor | default sse   build | avx512 build | avx512 build +   Intrinsics | Intrinsics   improvements
-- | -- | -- | -- | --
BM_PlainDecodingBoolean/1024(G/s) | 1.55394 | 3.77701 | 5.02805 | 1.331224964
BM_PlainDecodingBoolean/4096(G/s) | 1.83472 | 5.3826 | 8.3443 | 1.550235945
BM_PlainDecodingBoolean/32768(G/s) | 2.00957 | 6.1258 | 10.3793 | 1.694358288
BM_PlainDecodingBoolean/65536(G/s) | 2.02249 | 6.20035 | 10.5778 | 1.706000468

**Comment by pitrou** [comment]
I'll say that I personally would rather not want ourselves to spend time on AVX512 intrinsics while there are so few CPUs around supporting AVX512. IMHO, it would be much more useful for the Arrow userbase to optimize using SSE or AVX/AVX2 intrinsics.

About the PR, it's obvious that the file you're touching was initially generated by a script. Unfortunately the script doesn't seem part of the codebase, so we'll need to recreate it somehow and make any changes in the script itself.

cc @wesm

**Comment by jianxind** [comment]
> I'll say that I personally would rather not want ourselves to spend time on AVX512 intrinsics while there are so few CPUs around supporting AVX512. IMHO, it would be much more useful for the Arrow userbase to optimize using SSE or AVX/AVX2 intrinsics.

For client, yes small ratio of cpus has AVX512. But for server, actually all Intel Xeon Scalable processors family support AVX512 feature, currently most server of cloud service providers are based on Xeon Scalable. Others ISV like tensor-flow, pytorch, numpy are heavily optimized to utilize AVX512 performance. 

I don't know too much about what's the most usage for arrow, but if many of them are cloud based, AVX512 definitely can improve the performance significantly. For this case, AVX2 or SSE lack rich set of SIMD instructions which AVX512 provide, I tried to implement with same ways for SSE, but conclude it can't beat the comelier.

**Comment by wesm** [comment]
I personally have no problem with AVX512 optimizations if Intel wants to contribute and maintain them. If they cause us a maintenance burden in the future and there is no one willing to maintain them, then we can re-evaluate

**Comment by wesm** [comment]
@jianxind one problem that will come up is _testing_ with AVX512. I have an AVX512-capable machine (i9-9960X) that I can use to test locally but we eventually will need to get something hooked up to CI (whether using Buildkite or GitHub Actions self-hosted). If you have a machine that you can contribute to our CI please let us know

**Comment by wesm** [comment]
The scripts used to generate the file originally are contained in

https://github.com/lemire/FrameOfReference

+1 -- merging this. let us open a follow-up JIRA about managing AVX-optimized functions from this file?

**Comment by jianxind** [comment]
> The scripts used to generate the file originally are contained in
> 
> https://github.com/lemire/FrameOfReference
> 
> +1 -- merging this. let us open a follow-up JIRA about managing AVX-optimized functions from this file?

Thanks wesm. I find the script file, https://github.com/lemire/FrameOfReference/blob/master/scripts/turbopacking32.py and will check if there's a way to leverage similar script for AVX-optimized.

Sure for our team(intel) will continue looking the AVX521 build sanity and performance as the amazing adopting curve in the ecosystem. We has some scripts(https://github.com/clearlinux/clr-avx-tools/blob/master/avxjudge.pys) to evaluate the SIMD score for library/package and Arrow has a amazing high sse score thus it appears AVX512 probably boost the performance a lot. 

For the CI, yes we has some AVX capable servers in the lab, I has to check with policy if it can be used for such outside usage, will reach back later. But at least we can easily maintain an auto task locally monitoring the healthy of AVX512 build per a weekly bias.

**Pull request closed without merging**
