### PR TITLE
ARROW-12957: [R] rchk issues on cran

### PR DESCRIPTION
**Pull request by romainfrancois**
This should fix the issues reported by rchk

### CODE REVIEW

**Comment by romainfrancois** [comment]
I haven't been able to run rchk locally, do we have a way to run it on actions ?

**Comment by jonkeane** [comment]
Not yet, but I'll make one (though probably separate from this branch)

**Comment by jonkeane** [comment]
@github-actions crossbow submit test-r-linux-rchk

**Comment by jonkeane** [comment]
@github-actions crossbow submit test-r-linux-rchk

**Review by jonkeane — APPROVED** [review]
LGTM

**Comment by jonkeane** [comment]
The lintr error looks unrelated

**Pull request closed without merging**
