### PR TITLE
ARROW-5683: [R] Add snappy to Rtools Windows builds

### PR DESCRIPTION
**Pull request by nealrichardson**
Following https://github.com/r-windows/rtools-backports/pull/7 and https://github.com/r-windows/rtools-packages/pull/19, R Windows builds can now support Snappy compression. This patch tweaks the necessary files and unskips tests, in addition to some other PKGBUILD script cleanup.

Passing build here: https://ci.appveyor.com/project/nealrichardson/arrow/builds/25507388

### CODE REVIEW

**Comment by wesm** [comment]
Can you append the rtools-backports license to our LICENSE.txt?

**Comment by nealrichardson** [comment]
Done, PTAL

**Review by wesm — APPROVED** [review]
+1

**Comment by wesm** [comment]
thanks @nealrichardson!

**Pull request closed without merging**
