### PR TITLE
GH-36655: [Dev] Fix fury command to upload nightly wheels

### LINKED ISSUE #36655: [Packaging] Nightly wheels are not being uploaded to gemfury
### Describe the bug, including details regarding any error messages, version, and platform.

It does seem that since: https://github.com/apache/arrow/pull/35032 was merged we have not been uploading packages to gemfury:
https://pypi.fury.io/arrow-nightlies/pyarrow
The job doesn't fail but it does seem to fail to upload with the following message:
```
Top level ::CompositeIO is deprecated, require 'multipart/post' and use `Multipart::Post::CompositeReadIO` instead!
Top level ::Parts is deprecated, require 'multipart/post' and use `Multipart::Post::Parts` instead!
Could not find command "arrow/python/repaired_wheels/pyarrow_13.0.0.dev484_cp39_cp39_manylinux_2_28_x86_64.whl".
```
This seems to have been there already on the PR and was missed when the change to use the gemfury client was done.
At one point packages were uploaded during the PR (https://github.com/ursacomputing/crossbow/actions/runs/4701748794/jobs/8338180144):
```
Top level ::Parts is deprecated, require 'multipart/post' and use `Multipart::Post::Parts` instead!
C:/Users/runneradmin/.gem/ruby/2.5.0/gems/faraday-1.0.1/lib/faraday/file_part.rb:53: warning: constant ::UploadIO is deprecated
C:/Users/runneradmin/.gem/ruby/2.5.0/gems/faraday-1.0.1/lib/faraday/file_part.rb:59: warning: constant ::UploadIO is deprecated
C:/Users/runneradmin/.gem/ruby/2.5.0/gems/faraday-1.0.1/lib/faraday/file_part.rb:61: warning: constant ::Parts is deprecated
```

Thanks @jorisvandenbossche for reporting on Zulip!

### Component(s)

Packaging

### PR DESCRIPTION
**Pull request by raulcd**
### Rationale for this change

The fury command was missing the push command.

### What changes are included in this PR?

Fix the fury command

### Are these changes tested?

Will test with CI.

### Are there any user-facing changes?
No
* Closes: #36655

### CODE REVIEW

**Comment by raulcd** [comment]
github-actions crossbow submit *wheel*

**Comment by raulcd** [comment]
@github-actions crossbow submit *wheels*

**Comment by raulcd** [comment]
@github-actions crossbow submit -g wheel

**Review by assignUser — APPROVED** [review]
Thanks!

**Review by jorisvandenbossche — APPROVED** [review]
Thanks!

**Comment by jorisvandenbossche** [comment]
Does this need to be backported? (tagged with 13.0) I suppose the release branch doesn't push wheels to fury?

**Comment by raulcd** [comment]
> Does this need to be backported? (tagged with 13.0) I suppose the release branch doesn't push wheels to fury?

I had the same doubt but I am pretty sure is not necessary as:
* We specifically check: `{%- if arrow.is_default_branch() -%}` for this step.
* Wheels for 12.0.0 and 12.0.1 were generated and uploaded successfully as part of their releases.

**Pull request merged**
