### PR TITLE
ARROW-17853: temporary revert fix for test_write_dataset_max_rows_per_file

### PR DESCRIPTION
**Pull request by jorisvandenbossche**
Revert "ARROW-17614: [CI][Python] test test_write_dataset_max_rows_per_file is producing several nightly build failures (#14199)" (commit acd69f92ee92140f42b64714a348d0735a368931), as this causing new failures in `test_write_dataset_s3_put_only`

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
cc @westonpace unless you directly know what is going on to fix it properly, I would prefer reverting the original fix to at least have functional CI for Python

**Review by pitrou — APPROVED** [review]
+1, this will unblock Python CI, and also avoid the cumulative resource effect of CI jobs taking one hour before timeout.

**Comment by pitrou** [comment]
@jorisvandenbossche Feel free to merge once CI looks green on your fork.

**Comment by jorisvandenbossche** [comment]
The Python builds on my fork have passed, eg https://github.com/jorisvandenbossche/arrow/actions/runs/3135613499/jobs/5091502221

**Comment by westonpace** [comment]
Sorry, I'll get to the bottom of this.

**Comment by westonpace** [comment]
#14257 should fix the deadlock properly.

**Pull request merged**
