### PR TITLE
ARROW-2976: [Python] Fix pyarrow.get_library_dirs

### PR DESCRIPTION
**Pull request by pcmoritz**

### CODE REVIEW

**Comment by pcmoritz** [comment]
@wesm @pitrou Can one of you have a quick look if that seems to be the right way to do this? It's working for me but there is probably lots of corner cases.

**Comment by pitrou** [comment]
> Can one of you have a quick look if that seems to be the right way to do this?

No idea, sorry. I'm a bit surprised the CMake scripts aren't able to do that by themselves?
Apparently LLVM installs some CMake scripts that allow third-party projects to include the necessary definitions: https://llvm.org/docs/CMake.html#embedding-llvm-in-your-project
(not that I find CMake easy to work with ;-))

**Comment by wesm** [comment]
I think this is for 3rd party libraries that aren't using cmake? (NumPy has some functions like this)

I tested this locally where I have the libraries installed somewhere else and it seems to be working:

```
In [1]: import pyarrow
pya
In [2]: pyarrow.get_library_dirs()
Out[2]: ['/home/wesm/code/arrow/python/pyarrow', '/home/wesm/local/lib']
```

**Review by wesm — APPROVED** [review]
+1

**Pull request closed without merging**
