### PR TITLE
GH-37017: [C++] Guard unexpected uses of BMI2 instructions

### LINKED ISSUE #37017: [C++][R][Packaging] r-binary-packages macOS High Sierra failed by BMI2 related error
### Describe the bug, including details regarding any error messages, version, and platform.

The last success nightly build (2023-07-19): https://github.com/ursacomputing/crossbow/actions/runs/5596846018/job/15162699322
The first failed nightly build (2023-07-20): https://github.com/ursacomputing/crossbow/actions/runs/5608731289/job/15196725675#step:13:7156

```text
/Users/voltrondata/tmp/hbtmp/apache-arrow-20230720-60391-l8lhul/cpp/src/arrow/compute/key_map_avx2.cc:132:30: error: always_inline function '_pext_u32' requires target feature 'bmi2', but would be inlined into function 'early_filter_imp_avx2_x8' that is compiled without support for 'bmi2'
    out_match_bitvector[i] = _pext_u32(_mm256_movemask_epi8(vmatch_found),
                             ^
```

I think that #36662 is related.

### Component(s)

C++, Packaging, R

### PR DESCRIPTION
**Pull request by pitrou**
### Rationale for this change

Some functions introduced with Acero only check for AVX2 availability, but they actually invoke BMI2 instructions.
This can have two negative consequences:
* compiling BMI2 intrinsics may fail because BMI2 was not explicitly enabled on the compiler (gh-37017)
* some rare CPUs (Via CPUs perhaps) may support AVX2 but not BMI2; other CPUs by AMD have a very inefficient implementation of some BMI2 instructions

### What changes are included in this PR?

1. Ensure that the suitable compiler flag is passed when compiling code with BMI2 intrinsics
2. Make sure the CPU supports BMI2 adequately before invoking functions featuring BMI2 instructions

### Are these changes tested?

Yes, assuming CI covers enough diversity of target platforms.

### Are there any user-facing changes?

No, but performance might change (positively or negatively) depending on the CPU and platform.

* Closes: #37017

### CODE REVIEW

**Comment by pitrou** [comment]
@github-actions crossbow submit r-binary-packages

**Comment by pitrou** [comment]
@github-actions crossbow submit -g cpp

**Comment by pitrou** [comment]
I assume that the remaining errors on r-binary-packages [above](https://github.com/apache/arrow/pull/37610#issuecomment-1710236956) are not related, but I'd appreciate if someone more competent could double-check? @assignUser or @thisisnic  perhaps?

**Comment by assignUser** [comment]
Oh thanks @pitrou I will check!

**Review by westonpace — COMMENTED** [review]
If I understand correctly we compile the `_avx2.cc` files with both AVX2 and BMI2 enabled.  Doesn't this meant that any function in any `_avx2.cc` file may contain a `bmi2` operation?

In other words, even if we examine a file and determine it has no explicit `pext`, `pdep`, etc. then wouldn't it still be possible for the compiler to insert those instructions itself as an implicit operation?

**Comment by assignUser** [comment]
Yeah the remaining errors look unrelated (brotli linking error and actions/checkout failing on centos7...) +1

**Review by bkietz — APPROVED** [review]
LGTM

I'm somewhat surprised we don't just fold AVX2 + efficient BMI2 into a single SIMD level

**Comment by pitrou** [comment]
> I'm somewhat surprised we don't just fold AVX2 + efficient BMI2 into a single SIMD level

Historically we didn't use BMI2 at all. It then appeared only for a very special operation in Parquet, while AVX2 can be implicitly enabled in lots of other places.

This was manageable, but of course the stealth use of BMI2 in Acero makes the situation more annoying.

**Comment by pitrou** [comment]
> If I understand correctly we compile the `_avx2.cc` files with both AVX2 and BMI2 enabled. Doesn't this meant that any function in any `_avx2.cc` file may contain a `bmi2` operation?

Nit: only two `_avx2.cc` files are concerned, those that use explicit BMI2 intrinsics.

> In other words, even if we examine a file and determine it has no explicit `pext`, `pdep`, etc. then wouldn't it still be possible for the compiler to insert those instructions itself as an implicit operation?

Indeed. But this PR introduces matching runtime guards when calling those functions, so this shouldn't be a problem.

Am I missing another concern here?

**Comment by pitrou** [comment]
(distantly related: https://github.com/apache/arrow/issues/26514 )

**Comment by westonpace** [comment]
> Am I missing another concern here?

Consider the file `level_comparison_avx2.cc`. It doesn't contain any explicit bmi2 instructions.  Currently, we compile it with `-mavx2 -march=haswell` and so it also won't contain any implicit bmi2 instructions (inserted by the compiler).

However, if I understand this PR, it is changing this to compile with `-mbmi2 -mavx2 -march=haswell`.  So, even though there are not any explicit bmi2 instructions, isn't the compiler free to insert bmi2 instructions in an optimization pass?

That being said, I just tested this file, and several others with avx2 in the name, and adding the `-mbmi2` flag did not change the compiled object file at all.  So maybe gcc doesn't do any bmi2-specific optimization or maybe these files just can't take advantage of it.

**Comment by pitrou** [comment]
That's not what this PR does. The BMI2 flag should only be passed for three files: `parquet/level_conversion_bmi2.cc`, `arrow/compute/key_map_avx2.cc` and `arrow/compute/util_avx2.cc`. Are you seeing something else?

**Review by kou — APPROVED** [review]
+1

Can we merge this?
Do we need more discussion on this?

**Comment by pitrou** [comment]
No, it's ok to merge since everyone seems to be ok with the approach.

**Comment by pitrou** [comment]
I posted #37623 as a followup to reenable more code paths.

**Pull request merged**
