### PR TITLE
ARROW-15190: [C++] Upgrade bundled zstd version

### PR DESCRIPTION
**Pull request by pitrou**

### CODE REVIEW

**Comment by pitrou** [comment]
@github-actions crossbow submit -g cpp

**Comment by kou** [comment]
@github-actions crossbow submit -g linux

**Comment by pitrou** [comment]
@kou Is this ok to you?

**Comment by pitrou** [comment]
@github-actions crossbow submit -g cpp -g linux

**Review by kou — APPROVED** [review]
+1

**Pull request closed without merging**
