### PR TITLE
GH-40153: [C++][Python] Fix test_gdb failures on 32-bit

### PR DESCRIPTION
**Pull request by pitrou**
### Rationale for this change

`test_gdb.py` would fail on 32-bit platforms because the gdb extension errors out when a timestamp value is larger than the platform's time_t.

### What changes are included in this PR?

1. Catch `OverflowError` from the Python datetime module when trying to format a timestamp
2. Tweak the expected test results on 32-bit

### Are these changes tested?

Yes.

### Are there any user-facing changes?

No.
* GitHub Issue: #40153

### CODE REVIEW

**Comment by pitrou** [comment]
@github-actions crossbow submit -g python

**Comment by AlenkaF** [comment]
No comment on the code, looks good to me.
The build that is testing 32-bit platforms is `test-debian-11-python-3-i386` right?

**Comment by pitrou** [comment]
> The build that is testing 32-bit platforms is `test-debian-11-python-3-i386` right?

Yes, it is.

**Comment by pitrou** [comment]
@github-actions crossbow submit -g python

**Review by AlenkaF — APPROVED** [review]

**Comment by pitrou** [comment]
Test failures are unrelated.

**Pull request merged**
