### PR TITLE
ARROW-16553: [Java] Initial changes to configure GitHub nightly builds Jar as a repository to use from Maven/Gradle

### PR DESCRIPTION
**Pull request by davisusanibar**
For Java side currently we are offering nightly builds Jar artifacts uploaded to GitHub repository as an assets.

Then, if a user decided to use that in their local projects they need to download that Jar assets from the GitHub nightly packages and i[nstall that manually one by one as Jar needed as mention in the documentation](https://arrow.apache.org/docs/java/install.html#installing-nightly-packages).

Trying to figure out if there are some option to use GitHub nightly builds Jar artifacts as a really repository and only configure the nightly build in my pom.xml for example and maven be able to download dependencies needed automatically.

### CODE REVIEW

**Comment by davisusanibar** [comment]
@github-actions crossbow submit java-jars

**Comment by amol-** [comment]
Should we update https://arrow.apache.org/docs/java/install.html#installing-nightly-packages too ?

**Comment by davisusanibar** [comment]
> Should we update https://arrow.apache.org/docs/java/install.html#installing-nightly-packages too ?

There is more changes on the way. Using [Github release](https://github.com/ursacomputing/crossbow/releases/tag/nightly-2022-03-19-0-github-java-jars) is not possible to use/configure as a maven/gradle repository there is no option to create folder inside a [release](https://docs.github.com/es/repositories/releasing-projects-on-github/managing-releases-in-a-repository)

Working on a change to after GitHub release complete successfully, then add a new commit to [crossbow](https://github.com/davisusanibar/crossbow) on the same branch used for release that are containing folder structure and jar needed.

**Comment by davisusanibar** [comment]
> > Should we update https://arrow.apache.org/docs/java/install.html#installing-nightly-packages too ?
> 
> There is more changes on the way. Using [Github release](https://github.com/ursacomputing/crossbow/releases/tag/nightly-2022-03-19-0-github-java-jars) is not possible to use/configure as a maven/gradle repository there is no option to create folder inside a [release](https://docs.github.com/es/repositories/releasing-projects-on-github/managing-releases-in-a-repository)
> 
> Working on a change to after GitHub release complete successfully, then add a new commit to [crossbow](https://github.com/davisusanibar/crossbow) on the same branch used for release that are containing folder structure and jar needed.

If a directory is sending on the release payload this is replaced `/` by `.` as you could see at https://github.com/davisusanibar/crossbow/releases/tag/v1.0.0

**Comment by davisusanibar** [comment]
Just close this PR. This is a more configurable manner to implement this at https://github.com/apache/arrow/blob/master/.github/workflows/r_nightly.yml

**Pull request closed without merging**
