### PR TITLE
GH-41581: [C++][CMake] correctly use Protobuf_PROTOC_EXECUTABLE

### LINKED ISSUE #41581: [C++][CMake] handle Protobuf_PROTOC_EXECUTABLE correctly in cross-compilation
### Describe the bug, including details regarding any error messages, version, and platform.

In the [preparation](https://github.com/conda-forge/arrow-cpp-feedstock/pull/1255) for releasing arrow v16 in conda-forge (where we need to cross-compile for various targets), @raulcd ended up raising https://github.com/apache/arrow/issues/41333 which got fixed in https://github.com/apache/arrow/pull/41360. However, as I was working on the backports, I noticed that there's a hunk missing here in apache/arrow compared to what got committed in https://github.com/conda-forge/arrow-cpp-feedstock/commit/b80a399d39e04b09980d12ee3817b477b175de11, namely
```diff
diff --git a/cpp/cmake_modules/FindProtobufAlt.cmake b/cpp/cmake_modules/FindProtobufAlt.cmake
index f343b42f2..98a3281ee 100644
--- a/cpp/cmake_modules/FindProtobufAlt.cmake
+++ b/cpp/cmake_modules/FindProtobufAlt.cmake
@@ -31,6 +31,12 @@ endif()
 find_package(protobuf CONFIG ${find_package_args})
 set(ProtobufAlt_FOUND ${protobuf_FOUND})
 if(ProtobufAlt_FOUND)
-  if(Protobuf_PROTOC_EXECUTABLE)
-    set_target_properties(protobuf::protoc PROPERTIES
-    IMPORTED_LOCATION_RELEASE "${Protobuf_PROTOC_EXECUTABLE}"
-  )
-  endif()
   set(ProtobufAlt_VERSION ${protobuf_VERSION})
   set(ProtobufAlt_VERSION_MAJOR ${protobuf_VERSION_MAJOR})
   set(ProtobufAlt_VERSION_MINOR ${protobuf_VERSION_MINOR})
```

### Component(s)

C++, Packaging

### PR DESCRIPTION
**Pull request by h-vetinari**
Fixes #41581
* GitHub Issue: #41581

### CODE REVIEW

**Comment by assignUser** [comment]
@github-actions crossbow submit -g cpp r-binary-packages

**Review by raulcd — APPROVED** [review]
:+1: 
Thanks @h-vetinari

**Comment by h-vetinari** [comment]
Gentle ping here :)

**Comment by assignUser** [comment]
ah sorry I lost track of this, Thanks!

**Pull request merged**
