### PR TITLE
ARROW-15303: [R] linting errors

### PR DESCRIPTION
**Pull request by thisisnic**

### CODE REVIEW

**Review by wjones127 — COMMENTED** [review]
What is present here looks good, but locally I get additional linting errors:

```
> lintr::lint_package()
...........................................................................................................................................
tests/testthat/test-Array.R:357:22: style: Place a space before left parenthesis, except in a function call.
  a <- Array$create(-(1:10))
                     ^
tests/testthat/test-compute-arith.R:110:18: style: Place a space before left parenthesis, except in a function call.
  expect_equal(a^(-1), Array$create(c(1, 1 / 2, 1 / 3, 1 / 4, NA_real_)))
                 ^
tests/testthat/test-compute-arith.R:111:18: style: Place a space before left parenthesis, except in a function call.
  expect_equal(a^(.5), Array$create(c(1, sqrt(2), sqrt(3), sqrt(4), NA_real_)))
                 ^
tests/testthat/test-compute-arith.R:115:18: style: Place a space before left parenthesis, except in a function call.
  expect_equal(b^(-1), Array$create(c(1, 1 / 2, 1 / 3, 1 / 4, NA_real_)))
                 ^
tests/testthat/test-compute-arith.R:116:18: style: Place a space before left parenthesis, except in a function call.
  expect_equal(b^(.5), Array$create(c(1, sqrt(2), sqrt(3), sqrt(4), NA_real_)))
                 ^
tests/testthat/test-compute-arith.R:120:18: style: Place a space before left parenthesis, except in a function call.
  expect_equal(c^(-1), Array$create(c(1, 1 / 2, 1 / 3, 1 / 4, NA_real_)))
                 ^
tests/testthat/test-compute-arith.R:121:18: style: Place a space before left parenthesis, except in a function call.
  expect_equal(c^(.5), Array$create(c(1, sqrt(2), sqrt(3), sqrt(4), NA_real_)))
                 ^
tests/testthat/test-compute-arith.R:125:18: style: Place a space before left parenthesis, except in a function call.
  expect_equal(d^(-1), Array$create(c(1, 1 / 2, 1 / 3, 1 / 4, NA_real_)))
                 ^
tests/testthat/test-compute-arith.R:126:18: style: Place a space before left parenthesis, except in a function call.
  expect_equal(d^(.5), Array$create(c(1, sqrt(2), sqrt(3), sqrt(4), NA_real_)))
```

Do you see those too? Or is there something wrong with my linting settings?

**Comment by thisisnic** [comment]
> What is present here looks good, but locally I get additional linting errors:
> 
> ```
> > lintr::lint_package()
> ...........................................................................................................................................
> tests/testthat/test-Array.R:357:22: style: Place a space before left parenthesis, except in a function call.
>   a <- Array$create(-(1:10))
>                      ^
> tests/testthat/test-compute-arith.R:110:18: style: Place a space before left parenthesis, except in a function call.
>   expect_equal(a^(-1), Array$create(c(1, 1 / 2, 1 / 3, 1 / 4, NA_real_)))
>                  ^
> tests/testthat/test-compute-arith.R:111:18: style: Place a space before left parenthesis, except in a function call.
>   expect_equal(a^(.5), Array$create(c(1, sqrt(2), sqrt(3), sqrt(4), NA_real_)))
>                  ^
> tests/testthat/test-compute-arith.R:115:18: style: Place a space before left parenthesis, except in a function call.
>   expect_equal(b^(-1), Array$create(c(1, 1 / 2, 1 / 3, 1 / 4, NA_real_)))
>                  ^
> tests/testthat/test-compute-arith.R:116:18: style: Place a space before left parenthesis, except in a function call.
>   expect_equal(b^(.5), Array$create(c(1, sqrt(2), sqrt(3), sqrt(4), NA_real_)))
>                  ^
> tests/testthat/test-compute-arith.R:120:18: style: Place a space before left parenthesis, except in a function call.
>   expect_equal(c^(-1), Array$create(c(1, 1 / 2, 1 / 3, 1 / 4, NA_real_)))
>                  ^
> tests/testthat/test-compute-arith.R:121:18: style: Place a space before left parenthesis, except in a function call.
>   expect_equal(c^(.5), Array$create(c(1, sqrt(2), sqrt(3), sqrt(4), NA_real_)))
>                  ^
> tests/testthat/test-compute-arith.R:125:18: style: Place a space before left parenthesis, except in a function call.
>   expect_equal(d^(-1), Array$create(c(1, 1 / 2, 1 / 3, 1 / 4, NA_real_)))
>                  ^
> tests/testthat/test-compute-arith.R:126:18: style: Place a space before left parenthesis, except in a function call.
>   expect_equal(d^(.5), Array$create(c(1, sqrt(2), sqrt(3), sqrt(4), NA_real_)))
> ```
> 
> Do you see those too? Or is there something wrong with my linting settings?

That's strange; I don't get those locally, but unsure why we have different results.

**Review by wjones127 — APPROVED** [review]
Okay after installing Jon's branch as instructed in dev docs I see no more lint errors. So this should be good to go. Thanks for being patient with me 😄

**Comment by westonpace** [comment]
Thank you for cleaning up my mess :1st_place_medal: Sorry I didn't catch this myself.

**Pull request closed without merging**
