### PR TITLE
ARROW-6448: [CI] Add crossbow zulip notifications

### PR DESCRIPTION
**Pull request by fsaintjacques**
Failed nightly docker builds will report to zulip in the channel `#crossbow`.

### CODE REVIEW

**Comment by kszucs** [comment]
@ursabot crossbow test -g nightly

**Comment by kszucs** [comment]
@ursabot crossbow test -g docker

**Comment by wesm** [comment]
Note that Zulip is a third party tool. Do we have a plan for notifying the Arrow community about job failures?

**Comment by wesm** [comment]
I'm sort of -0/-1 on this. I put up #5319 to send summary reports to dev@arrow.apache.org

**Comment by fsaintjacques** [comment]
OK, I'll drop this PR in favor of the email based approach.

**Pull request closed without merging**
