### PR TITLE
ARROW-3360: [GLib] Import Parquet GLib

### PR DESCRIPTION
**Pull request by kou**
It's based on https://github.com/red-data-tools/parquet-glib at
32a2b2099f90c19d28322693dd853dc8643c55ec.

See also: https://github.com/red-data-tools/parquet-glib/commit/32a2b2099f90c19d28322693dd853dc8643c55ec

### CODE REVIEW

**Comment by kou** [comment]
I started discussion at `dev@parquet.apache.org`: https://lists.apache.org/thread.html/72b2bf04d8035d854a44487d956322cbe6c8629488128bc326613fb1@%3Cdev.parquet.apache.org%3E

**Comment by wesm** [comment]
Thanks @kou -- we should go through the IP clearance after having a vote on dev@parquet.a.o. Your ICLA should be sufficient for this (I see there is one other contributor with a 2 line change)?

**Comment by kou** [comment]
> we should go through the IP clearance after having a vote on dev@parquet.a.o.

OK.

> Your ICLA should be sufficient for this (I see there is one other contributor with a 2 line change)?

Yes.

The other contributor has one commit: https://github.com/red-data-tools/parquet-glib/commit/8091c812aedd4c94af98d1e664b8bb424c36b992

But the change isn't included in this pull request because we don't need the change by merging this project to the Arrow repository: https://github.com/apache/arrow/pull/2622/files#diff-88333024fdffef0c691b5aa164aa1a37R110

**Comment by xhochy** [comment]
Great work @kou . I looked through the code and everything looks fine. We should do the formal vote and than we can merge this.

**Comment by kou** [comment]
Thanks for reviewing this.
I'll create a PARQUET JIRA ticket when the vote is passed.

**Comment by kou** [comment]
@wesm Thanks for creating a JIRA ticket.
Is it OK to use ARROW ticket instead of PARQUET ticket for Parquet GLib bindings?

If it's OK, I'll also use ARROW ticket for new features.

**Comment by kou** [comment]
OK. I'll also use ARROW project.

**Review by wesm — APPROVED** [review]
+1. The IP clearance vote has carried

**Pull request closed without merging**
