### PR TITLE
ARROW-16735: [C++] Bump vendored version of rapidjson

### PR DESCRIPTION
**Pull request by raulcd**

### CODE REVIEW

**Comment by raulcd** [comment]
The test-conda-cpp-valgrind failure is also happening on our Nightly builds. I've created a new ticket to track it: https://issues.apache.org/jira/browse/ARROW-17071

**Comment by raulcd** [comment]
@pitrou I've updated rapidjson to the latest changeset

**Comment by pitrou** [comment]
@ursabot please benchmark lang=C++

**Review by pitrou — APPROVED** [review]
+1, thank you @raulcd

**Pull request merged**
