### PR TITLE
MINOR: [C++] Use alphabetical order

### PR DESCRIPTION
**Pull request by bkmgit**

### CODE REVIEW

**Comment by bkmgit** [comment]
@kou Ready for review

**Comment by bkmgit** [comment]
Failing build due to a hash mismatch for Google Test
```
 CMake Error at googletest_ep-stamp/googletest_ep-download-Debug.cmake:37 (message):
    Command failed: 1
  
     'C:/Program Files/CMake/bin/cmake.exe' '-Dmake=' '-Dconfig=Debug' '-P' 'D:/a/arrow/arrow/build/cpp/googletest_ep-prefix/src/googletest_ep-stamp/googletest_ep-download-Debug-impl.cmake'
  
    See also
  
      D:/a/arrow/arrow/build/cpp/googletest_ep-prefix/src/googletest_ep-stamp/googletest_ep-download-*.log
  
  
  -- stdout output is:
  -- Downloading...
     dst='D:/a/arrow/arrow/build/cpp/googletest_ep-prefix/src/release-1.11.0.tar.gz'
     timeout='none'
     inactivity timeout='none'
  -- Using src='https://github.com/google/googletest/archive/release-1.11.0.tar.gz'
  -- [download 0% complete]
  -- Using src='https://chromium.googlesource.com/external/github.com/google/googletest/+archive/release-1.11.0.tar.gz'
  -- verifying file...
         file='D:/a/arrow/arrow/build/cpp/googletest_ep-prefix/src/release-1.11.0.tar.gz'
  -- SHA256 hash of
      D:/a/arrow/arrow/build/cpp/googletest_ep-prefix/src/release-1.11.0.tar.gz
    does not match expected value
      expected: 'b4870bf121ff7795ba20d20bcdd8627b8e088f2d1dab299a031c1034eddc93d5'
        actual: '2782376ec5c1ba9b0fe5e7800a32ed94652ad0fc6cf08ed6dcc837ec8aca5a2c'
  -- Hash mismatch, removing...
  -- Using src='https://github.com/ursa-labs/thirdparty/releases/download/latest/gtest-1.11.0.tar.gz'
  -- [download 0% complete]
  -- Using src='https://chromium.googlesource.com/external/github.com/google/googletest/+archive/release-1.11.0.tar.gz'
  -- verifying file...
         file='D:/a/arrow/arrow/build/cpp/googletest_ep-prefix/src/release-1.11.0.tar.gz'
  -- SHA256 hash of
      D:/a/arrow/arrow/build/cpp/googletest_ep-prefix/src/release-1.11.0.tar.gz
    does not match expected value
      expected: 'b4870bf121ff7795ba20d20bcdd8627b8e088f2d1dab299a031c1034eddc93d5'
  CMake Error at googletest_ep-stamp/googletest_ep-download-Debug.cmake:47 (message):
    Stopping after outputting logs.
  
  
        actual: '306f369c9cabc342083c0d0fa581a2ece2f1b4e4e9b0e61763721ea590f27d1f'
  -- Hash mismatch, removing...
  -- Using src='https://chromium.googlesource.com/external/github.com/google/googletest/+archive/release-1.11.0.tar.gz'
  -- verifying file...
         file='D:/a/arrow/arrow/build/cpp/googletest_ep-prefix/src/release-1.11.0.tar.gz'
  -- SHA256 hash of
      D:/a/arrow/arrow/build/cpp/googletest_ep-prefix/src/release-1.11.0.tar.gz
    does not match expected value
      expected: 'b4870bf121ff7795ba20d20bcdd8627b8e088f2d1dab299a031c1034eddc93d5'
        actual: '306f369c9cabc342083c0d0fa581a2ece2f1b4e4e9b0e61763721ea590f27d1f'
  -- Hash mismatch, removing...
  -- Using src='https://chromium.googlesource.com/external/github.com/google/googletest/+archive/release-1.11.0.tar.gz'
  -- verifying file...
         file='D:/a/arrow/arrow/build/cpp/googletest_ep-prefix/src/release-1.11.0.tar.gz'
  -- SHA256 hash of
      D:/a/arrow/arrow/build/cpp/googletest_ep-prefix/src/release-1.11.0.tar.gz
    does not match expected value
      expected: 'b4870bf121ff7795ba20d20bcdd8627b8e088f2d1dab299a031c1034eddc93d5'
        actual: '306f369c9cabc342083c0d0fa581a2ece2f1b4e4e9b0e61763721ea590f27d1f'
  -- Hash mismatch, removing...
  -- Using src='https://chromium.googlesource.com/external/github.com/google/googletest/+archive/release-1.11.0.tar.gz'
  -- verifying file...
         file='D:/a/arrow/arrow/build/cpp/googletest_ep-prefix/src/release-1.11.0.tar.gz'
  -- SHA256 hash of
      D:/a/arrow/arrow/build/cpp/googletest_ep-prefix/src/release-1.11.0.tar.gz
    does not match expected value
      expected: 'b4870bf121ff7795ba20d20bcdd8627b8e088f2d1dab299a031c1034eddc93d5'
        actual: 'cb9bd3ce22c11df58b6af8037d6f4beddac36f6a132044181a593fb9e1a96ad7'
  -- Hash mismatch, removing...
  
  -- stderr output is:
  CMake Error at googletest_ep-stamp/download-googletest_ep.cmake:170 (message):
    Each download failed!
  
CUSTOMBUILD : error : downloading 'https://github.com/google/googletest/archive/release-1.11.0.tar.gz' failed [D:\a\arrow\arrow\build\cpp\googletest_ep.vcxproj]
            status_code: 22
            status_string: "HTTP response code said error"
            log:
            --- LOG BEGIN ---
            timeout on name lookup is not supported
      Trying 140.82.112.3:443...
  
    Connected to github.com (140.82.112.3) port 443 (#0)
  
    schannel: disabled automatic use of client certificate
  
    schannel: ALPN, offering h2
  
    schannel: ALPN, offering http/1.1
  
    schannel: ALPN, server accepted to use h2
  
    Using HTTP2, server supports multi-use
  
    Connection state changed (HTTP/2 confirmed)
  
    Copying HTTP/2 data in stream buffer to connection buffer after upgrade:
    len=0
  
    Using Stream ID: 1 (easy handle 0x1a11f86bd40)
  
    GET /google/googletest/archive/release-1.11.0.tar.gz HTTP/2
  
    Host: github.com
  
    user-agent: curl/7.77.0
  
    accept: */*
  
    
  
    HTTP/2 502 
  
    server: GitHub.com
  
    date: Wed, 17 Nov 2021 06:56:44 GMT
  
    content-type: text/html
  
    content-length: 55124
  
    etag: "6194531c-d754"
  
    x-frame-options: DENY
  
    x-github-request-id: 0400:45B2:35455E:6720BF:6194A7CA
  
CUSTOMBUILD : The requested URL returned error : 502 [D:\a\arrow\arrow\build\cpp\googletest_ep.vcxproj]
  
    stopped the pause stream!
  
    Connection #0 to host github.com left intact
  
    
  
            --- LOG END ---
CUSTOMBUILD : error : downloading 'https://github.com/ursa-labs/thirdparty/releases/download/latest/gtest-1.11.0.tar.gz' failed [D:\a\arrow\arrow\build\cpp\googletest_ep.vcxproj]
            status_code: 22
            status_string: "HTTP response code said error"
            log:
            --- LOG BEGIN ---
            timeout on name lookup is not supported
      Trying 140.82.112.3:443...
  
    Connected to github.com (140.82.112.3) port 443 (#0)
  
    schannel: disabled automatic use of client certificate
  
    schannel: ALPN, offering h2
  
    schannel: ALPN, offering http/1.1
  
    schannel: ALPN, server accepted to use h2
  
    Using HTTP2, server supports multi-use
  
    Connection state changed (HTTP/2 confirmed)
  
    Copying HTTP/2 data in stream buffer to connection buffer after upgrade:
    len=0
  
    Using Stream ID: 1 (easy handle 0x1a11f8a6ae0)
  
    GET /ursa-labs/thirdparty/releases/download/latest/gtest-1.11.0.tar.gz
    HTTP/2
  
    Host: github.com
  
    user-agent: curl/7.77.0
  
    accept: */*
  
    
  
    HTTP/2 404 
  
    server: GitHub.com
  
    date: Wed, 17 Nov 2021 06:57:14 GMT
  
    content-type: text/plain; charset=utf-8
  
    vary: X-PJAX, X-PJAX-Container, Accept-Encoding, Accept, X-Requested-With
  
    permissions-policy: interest-cohort=()
  
    cache-control: no-cache
  
    strict-transport-security: max-age=31536000; includeSubdomains; preload
  
    x-frame-options: deny
  
    x-content-type-options: nosniff
  
    x-xss-protection: 0
  
    referrer-policy: no-referrer-when-downgrade
  
    expect-ct: max-age=2592000,
    report-uri="https://api.github.com/_private/browser/errors"
  
    content-security-policy: default-src 'none'; base-uri 'self'; connect-src
    'self'; form-action 'self'; img-src 'self' data:; script-src 'self';
    style-src 'unsafe-inline'
  
    content-length: 9
  
    x-github-request-id: 0401:5199:38C3AF:5E5E1B:6194A7CA
  
CUSTOMBUILD : The requested URL returned error : 404 [D:\a\arrow\arrow\build\cpp\googletest_ep.vcxproj]
  
    stopped the pause stream!
  
    Connection #0 to host github.com left intact
  
    
  
            --- LOG END ---
            
      
  
  
  CMake Error at googletest_ep-stamp/googletest_ep-download-Debug-impl.cmake:9 (message):
    Command failed (1):
  
     'C:/Program Files/CMake/bin/cmake.exe' '-P' 'D:/a/arrow/arrow/build/cpp/googletest_ep-prefix/src/googletest_ep-stamp/download-googletest_ep.cmake'
  
  
  
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(241,5): error MSB8066: Custom build for 'D:\a\arrow\arrow\build\cpp\CMakeFiles\dd35e229cbdd4f7c8fd7e870c1527186\googletest_ep-mkdir.rule;D:\a\arrow\arrow\build\cpp\CMakeFiles\dd35e229cbdd4f7c8fd7e870c1527186\googletest_ep-download.rule;D:\a\arrow\arrow\build\cpp\CMakeFiles\dd35e229cbdd4f7c8fd7e870c1527186\googletest_ep-update.rule;D:\a\arrow\arrow\build\cpp\CMakeFiles\dd35e229cbdd4f7c8fd7e870c1527186\googletest_ep-patch.rule;D:\a\arrow\arrow\build\cpp\CMakeFiles\dd35e229cbdd4f7c8fd7e870c1527186\googletest_ep-configure.rule;D:\a\arrow\arrow\build\cpp\CMakeFiles\dd35e229cbdd4f7c8fd7e870c1527186\googletest_ep-build.rule;D:\a\arrow\arrow\build\cpp\CMakeFiles\dd35e229cbdd4f7c8fd7e870c1527186\googletest_ep-install.rule;D:\a\arrow\arrow\build\cpp\CMakeFiles\dd35e229cbdd4f7c8fd7e870c1527186\googletest_ep-copy.rule;D:\a\arrow\arrow\build\cpp\CMakeFiles\ca010e340b0a12219ecb0160620773a3\googletest_ep-complete.rule;D:\a\arrow\arrow\build\cpp\CMakeFiles\9371981e4b5864bc64537e6c79092929\googletest_ep.rule;D:\a\arrow\arrow\cpp\CMakeLists.txt' exited with code 1. 
```

**Comment by bkmgit** [comment]
Failed tests on Debian Latest:
```
══ Failed tests ════════════════════════════════════════════════════════════════
── Failure (test-duckdb.R:145:3): Joining, auto-cleanup enabled ────────────────
all(c(table_one_name, table_two_name) %in% DBI::dbListTables(con)) is not TRUE

`actual`:   FALSE
`expected`: TRUE 
── Failure (test-duckdb.R:158:3): Joining, auto-cleanup disabled ───────────────
table_three_name %in% DBI::dbListTables(con) is not TRUE

`actual`:   FALSE
`expected`: TRUE 
── Failure (test-duckdb.R:162:3): Joining, auto-cleanup disabled ───────────────
table_three_name %in% DBI::dbListTables(con) is not TRUE

`actual`:   FALSE
`expected`: TRUE 
```
and
```
Start test: install_pyarrow
Using Python: /usr/bin/python3.9
Creating virtual environment 'arrow-test' ... The virtual environment was not created successfully because ensurepip is not
available.  On Debian/Ubuntu systems, you need to install the python3-venv
package using the following command.

    apt install python3.9-venv

You may need to use sudo with that command.  After installing the python3-venv
package, recreate your virtual environment.

Failing command: ['/root/.virtualenvs/arrow-test/bin/python3.9', '-Im', 'ensurepip', '--upgrade', '--default-pip']

FAILED
Error : Error creating virtual environment 'arrow-test' [error code 1]
  test-python.R:28:3 [skip]
End test: install_pyarrow
```

**Review by pitrou — APPROVED** [review]
+1, thank you

**Pull request closed without merging**
