### PR TITLE
ARROW-17197: [R] floor_date/ceiling_date lubridate comparison tests failing on macOS

### PR DESCRIPTION
**Pull request by rok**
This resolves [ARROW-17197](https://issues.apache.org/jira/browse/ARROW-17197).

### CODE REVIEW

**Comment by rok** [comment]
@github-actions crossbow submit test-r-install-local

**Comment by rok** [comment]
@github-actions crossbow submit test-r-install-local

**Comment by assignUser** [comment]
@github-actions crossbow submit test-r-install-local

**Comment by rok** [comment]
This esoteric flooring/ceiling timezoned bug seems to happen on MacOS also. @djnavarro am I right to understand this issue is on lubridate side?

**Review by assignUser — APPROVED** [review]
What a weird issue, thanks for investigating! LGTM

**Pull request merged**
