### PR TITLE
ARROW-9631: [Rust] flight should depend on arrow, not the other way around

### PR DESCRIPTION
**Pull request by andygrove**
The core `arrow` crate had a dependency on the `arrow-flight` crate, which doesn't make sense. Arrow should have minimal dependencies and should not depend on protocols or servers. Flight should depend on Arrow instead.

I also changed the name of lib from `flight` to `arrow_flight` to match the Cargo manifest. I did this because I ran into compilation issues but I think this is worth changing anyway since there is already a `flight` crate on crates.io (unrelated to Arrow). I can try and roll back this change though if there are objections.

### CODE REVIEW

**Comment by vertexclique** [comment]
Before merging this, please take a look at mine: https://github.com/apache/arrow/pull/7894
I simplified a bit of what happens when feature gates are enabled.

**Comment by andygrove** [comment]
@vertexclique I would prefer to have this PR only change the dependency between arrow and flight. This is quite a large change in itself. We can create follow-on PRs to make changes to feature gates.

**Comment by nevi-me** [comment]
> @vertexclique I would prefer to have this PR only change the dependency between arrow and flight. This is quite a large change in itself. We can create follow-on PRs to make changes to feature gates.

or rebase the feature-gating PR against this one when it's merged ...

**Review by nevi-me — APPROVED** [review]
Thanks Andy

**Comment by vertexclique** [comment]
@nevi-me @andygrove 
ok so yeah what i can do moving forward is:
1. create a ticket and rebase master on top.
2. Finalize https://github.com/apache/arrow/pull/7873 to make parquet also use raw arrow.

Sounds good?

**Pull request closed without merging**
