### PR TITLE
ARROW-6549: [C++] Switch to jemalloc 5.2.x

### PR DESCRIPTION
**Pull request by pitrou**
Revert "ARROW-6478: [C++] Revert to jemalloc stable-4 until we understand 5.2.x performance issues"

This reverts commit 53c5af065462b679fffb2deeda17dd694b51b002.

In addition, configure jemalloc to fix the performance regression.

### CODE REVIEW

**Comment by wesm** [comment]
Thanks @pitrou for investigating this. I will run a benchmark comparison on my machine (pretty newish i9-9960X) once I address https://issues.apache.org/jira/browse/ARROW-6559 which I just opened.

**Comment by wesm** [comment]
I also just rebased so hopefully we get a passing build now that the CI failure from ARROW-6509 is unblocked

**Comment by wesm** [comment]
Here are the benchmark results on my machine (I needed ARROW-6559 to run them)

https://gist.github.com/wesm/7501f688ee221ea826a56092dc02c471

I didn't see anything significant so I'm merging this

**Comment by wesm** [comment]
It looks like we have a UBSAN failure

```
[ RUN      ] TestArrowReadWrite.UseDeprecatedInt96
/arrow/cpp/src/parquet/types.h:558:27: runtime error: signed integer overflow: 2776655897 * 86400000000000 cannot be represented in type 'long'
    #0 0x7f2af04e0582 in parquet::Int96GetNanoSeconds(parquet::Int96 const&) /arrow/cpp/src/parquet/types.h:558:27
    #1 0x7f2af04dfccb in parquet::arrow::TransferInt96(parquet::internal::RecordReader*, arrow::MemoryPool*, std::shared_ptr<arrow::DataType> const&, arrow::compute::Datum*) /arrow/cpp/src/parquet/arrow/reader_internal.cc:741:19
    #2 0x7f2af04e7e66 in parquet::arrow::TransferColumnData(parquet::internal::RecordReader*, std::shared_ptr<arrow::DataType>, parquet::ColumnDescriptor const*, arrow::MemoryPool*, std::shared_ptr<arrow::ChunkedArray>*) /arrow/cpp/src/parquet/arrow/reader_internal.cc:1179:13
    #3 0x7f2af04664d4 in parquet::arrow::LeafReader::NextBatch(long, std::shared_ptr<arrow::ChunkedArray>*) /arrow/cpp/src/parquet/arrow/reader.cc:443:5
    #4 0x7f2af0493b83 in parquet::arrow::FileReaderImpl::ReadSchemaField(int, std::vector<int, std::allocator<int> > const&, std::vector<int, std::allocator<int> > const&, std::shared_ptr<arrow::Field>*, std::shared_ptr<arrow::ChunkedArray>*) /arrow/cpp/src/parquet/arrow/reader.cc:182:20
    #5 0x7f2af044919a in parquet::arrow::FileReaderImpl::ReadRowGroups(std::vector<int, std::allocator<int> > const&, std::vector<int, std::allocator<int> > const&, std::shared_ptr<arrow::Table>*)::$_0::operator()(int) const /arrow/cpp/src/parquet/arrow/reader.cc:806:12
    #6 0x7f2af04480eb in parquet::arrow::FileReaderImpl::ReadRowGroups(std::vector<int, std::allocator<int> > const&, std::vector<int, std::allocator<int> > const&, std::shared_ptr<arrow::Table>*) /arrow/cpp/src/parquet/arrow/reader.cc:826:7
    #7 0x7f2af04620ca in parquet::arrow::FileReaderImpl::ReadTable(std::vector<int, std::allocator<int> > const&, std::shared_ptr<arrow::Table>*) /arrow/cpp/src/parquet/arrow/reader.cc:151:12
    #8 0x7f2af0461c76 in parquet::arrow::FileReaderImpl::ReadTable(std::shared_ptr<arrow::Table>*) /arrow/cpp/src/parquet/arrow/reader.cc:227:12
    #9 0x81f76c in parquet::arrow::DoSimpleRoundtrip(std::shared_ptr<arrow::Table> const&, bool, long, std::vector<int, std::allocator<int> > const&, std::shared_ptr<arrow::Table>*, std::shared_ptr<parquet::ArrowWriterProperties> const&) /arrow/cpp/src/parquet/arrow/arrow_reader_writer_test.cc:436:5
    #10 0x83a1ea in parquet::arrow::TestArrowReadWrite_UseDeprecatedInt96_Test::TestBody() /arrow/cpp/src/parquet/arrow/arrow_reader_writer_test.cc:1398:3
    #11 0x7f2af1c1c88d in void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /build/cpp/googletest_ep-prefix/src/googletest_ep/googletest/src/gtest.cc:2443:10
    #12 0x7f2af1c058ba in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /build/cpp/googletest_ep-prefix/src/googletest_ep/googletest/src/gtest.cc:2479:14
    #13 0x7f2af1be6cf5 in testing::Test::Run() /build/cpp/googletest_ep-prefix/src/googletest_ep/googletest/src/gtest.cc:2517:5
    #14 0x7f2af1be7a5a in testing::TestInfo::Run() /build/cpp/googletest_ep-prefix/src/googletest_ep/googletest/src/gtest.cc:2693:11
    #15 0x7f2af1be811e in testing::TestCase::Run() /build/cpp/googletest_ep-prefix/src/googletest_ep/googletest/src/gtest.cc:2811:28
    #16 0x7f2af1bf4109 in testing::internal::UnitTestImpl::RunAllTests() /build/cpp/googletest_ep-prefix/src/googletest_ep/googletest/src/gtest.cc:5177:43
    #17 0x7f2af1c2028d in bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /build/cpp/googletest_ep-prefix/src/googletest_ep/googletest/src/gtest.cc:2443:10
    #18 0x7f2af1c07f6a in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /build/cpp/googletest_ep-prefix/src/googletest_ep/googletest/src/gtest.cc:2479:14
    #19 0x7f2af1bf3df5 in testing::UnitTest::Run() /build/cpp/googletest_ep-prefix/src/googletest_ep/googletest/src/gtest.cc:4786:10
    #20 0x7f2af1e4a9e0 in RUN_ALL_TESTS() /build/cpp/googletest_ep-prefix/src/googletest_ep/googletest/include/gtest/gtest.h:2341:46
    #21 0x7f2af1e4a9bf in main /build/cpp/googletest_ep-prefix/src/googletest_ep/googletest/src/gtest_main.cc:36:10
    #22 0x7f2ae73f9b96 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b96)
    #23 0x737679 in _start (/build/cpp/debug/parquet-arrow-test+0x737679)
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /arrow/cpp/src/parquet/types.h:558:27 in
/build/cpp/src/parquet
```

@emkornfield any clue why this would only show up here and not on master (this failure isn't occurring there)?

**Comment by pitrou** [comment]
@wesm This has to do with Parquet reading the data for null values. This data seems uninitialized so depending on the memory allocator may take different values.

IMO this may point to a problem in Parquet: it shouldn't serialize uninitialized data (that data may hold user secrets). Note that Arrow itself is not at fault: null data is zero-initialized in `TimestampBuilder` (unless there's a weird bug there).

**Comment by pitrou** [comment]
By the way, 2776655897 is supposed to be a number of days since Unix epoch. If we add `kJulianToUnixEpochDays` we get the following:
```
>>> hex(2776655897 + 2440588)
'0xa5a5a5a5'
```

This points exactly to uninitialized memory, flagged thanks to jemalloc's "junk" option.

>  opt.junk (const char *) r- [--enable-fill]

>    Junk filling. If set to “alloc”, each byte of uninitialized allocated memory will be initialized to 0xa5. If set to “free”, all deallocated memory will be initialized to 0x5a. If set to “true”, both allocated and deallocated memory will be initialized, and if set to “false”, junk filling be disabled entirely. This is intended for debugging and will impact performance negatively. This option is “false” by default unless --enable-debug is specified during configuration, in which case it is “true” by default.

**Comment by pitrou** [comment]
Ok, the uninitialized memory issue is actually on the decoding side. I will push a fix, I'll let you double-check @wesm

**Comment by pitrou** [comment]
Passing Travis-CI build at https://travis-ci.org/pitrou/arrow/builds/585577226

**Comment by emkornfield** [comment]
I'm not exactly sure, I think somehow we must have been getting lucky (or maybe @pitrou data-poisoining PR made this more obvious, if that has been merged).  I believe this is the bug that https://github.com/apache/arrow/pull/4607 is meant to address as well.

**Review by wesm — APPROVED** [review]
+1

**Pull request closed without merging**
