### PR TITLE
ARROW-6797: [Release] Use a separately cloned arrow-site repository in the website post release script	

### PR DESCRIPTION
**Pull request by kszucs**
Seems like `site` directory was removed, but the script was not updated.

### CODE REVIEW

**Review by kou — APPROVED** [review]
+1
We can merge this once CI is green.

**Comment by wesm** [comment]
I'd like to fix the environment variable issue

**Comment by kszucs** [comment]
@wesm what env issue do you mean?

**Comment by wesm** [comment]
changelog.py was still using the old environment variables without "APACHE_" prefix.

**Comment by wesm** [comment]
https://issues.apache.org/jira/browse/ARROW-6741

**Comment by kszucs** [comment]
@wesm thanks! I have env vars set up with both prefixes locally, so it remained hidden.

**Pull request closed without merging**
