### PR TITLE
ARROW-3924: [Packaging][Plasma] Add support for Plasma deb/rpm packages

### PR DESCRIPTION
**Pull request by kou**

### CODE REVIEW

**Review by wesm — APPROVED** [review]
+1

**Comment by wesm** [comment]
It's your preference to have many small packages vs. a single large package? At least in conda-forge we're bundling everything together to make things simpler to maintain

**Comment by kou** [comment]
I prefer to have many small packages. Because the current style (many small packages style) follows deb/rpm guideline.
I think that we should follow deb/rpm guideline. It's easy to use by users.

**Comment by wesm** [comment]
Sounds good

**Pull request closed without merging**
