### PR TITLE
ARROW-15408: [C++] Enable memory logging with env var

### PR DESCRIPTION
**Pull request by wjones127**

### CODE REVIEW

**Comment by pitrou** [comment]
I am a bit skeptical about this. As you point out, this might only be useful for simple applications, otherwise I expect the traces to be too copious and lack too much context to be really of any help.

It may be more useful to invest time into optionally tracing memory allocations using our OpenTracing infrastructure, what do you think?

**Comment by pitrou** [comment]
cc @lidavidm

**Comment by lidavidm** [comment]
Right, we could attach allocations as an event on the currently active span, and then we'd have context (though, that would lose events if there is no active span). 

`perf` can also trace calls to (je)malloc and get call stacks + record arguments, which may also be useful

**Comment by wjones127** [comment]
> I am a bit skeptical about this. As you point out, this might only be useful for simple applications, otherwise I expect the traces to be too copious and lack too much context to be really of any help.

Yeah it certainty seemed less useful once I saw the test output myself. I assumed that since someone put the effort to implement the logging pool it might be useful, and this change seemed like low-hanging fruit.

> It may be more useful to invest time into optionally tracing memory allocations using our OpenTracing infrastructure, what do you think?

I was planning on documenting next using perf to trace calls to the memory pool, but maybe open tracing would be more worthwhile. I'll look into that.

**Comment by pitrou** [comment]
The nice thing with OpenTracing is that it adds context to trace events, so you can know which workload item the allocations are part of.

**Comment by lidavidm** [comment]
> I was planning on documenting next using perf to trace calls to the memory pool, but maybe open tracing would be more worthwhile. I'll look into that.

FWIW I got this to work, if it helps:

```
$ sudo perf probe -x $CONDA_PREFIX/lib/libarrow.so je_arrow_mallocx '$params' 
$ sudo perf record -g --call-graph dwarf -e probe_libarrow:je_arrow_mallocx (which python) -c 'import pyarrow as pa; import pyarrow.compute as pc; print(pc.add(pa.array([1,2]), pa.array([3,4])))'
[
  4,
  6
]
[ perf record: Woken up 1 times to write data ]
[ perf record: Captured and wrote 0.244 MB perf.data (6 samples) ]
$ sudo perf script
python 22571 [009] 343792.307967: probe_libarrow:je_arrow_mallocx: (7f924779c4b0) size=0x100 flags=6
            7f924779c4b0 je_arrow_mallocx+0x0 (/home/lidavidm/miniconda3/envs/arrow-4.0/lib/libarrow.so.600.1.0)
            7f9246ab304b arrow::BaseMemoryPoolImpl<arrow::(anonymous namespace)::JemallocAllocator>::Allocate+0xfb (/home/
            7f9246ab46f1 arrow::AllocateResizableBuffer+0xe1 (/home/lidavidm/miniconda3/envs/arrow-4.0/lib/libarrow.so.600
            7f92469290dc arrow::BufferBuilder::Resize+0xac (/home/lidavidm/miniconda3/envs/arrow-4.0/lib/libarrow.so.600.1
            7f9246a205c2 arrow::NumericBuilder<arrow::Int64Type>::Resize+0x62 (/home/lidavidm/miniconda3/envs/arrow-4.0/li
            7f924657cfc2 arrow::ArrayBuilder::Reserve+0x82 (/home/lidavidm/miniconda3/envs/arrow-4.0/lib/libarrow_python.s
            (snip)
```

**Comment by wjones127** [comment]
Closing this in favor of:

 * ARROW-3016 / #12307: document how to use perf to analyze allocations
 * ARROW-15512: Add OpenTelemetry logging for memory pool allocations

Thanks for your input @pitrou and @lidavidm 😄

**Pull request closed without merging**
