### PR TITLE
ARROW-8538: [Packaging] Remove boost from homebrew formula

### PR DESCRIPTION
**Pull request by nealrichardson**
One more I didn't remove in ARROW-8222.

### CODE REVIEW

**Comment by nealrichardson** [comment]
@github-actions crossbow submit homebrew-cpp

**Comment by pitrou** [comment]
"The job exceeded the maximum log length, and has been terminated." -- restarting

**Comment by pitrou** [comment]
Wow, that is compiling OpenSSL by hand?

**Comment by nealrichardson** [comment]
¯\_(ツ)_/¯ maybe it's time to port this job to GHA

**Review by wesm — APPROVED** [review]
+1. Is this ok to merge?

**Review by kou — APPROVED** [review]
+1
We'll be able to use built binaries instead of building from source for dependencies by adding `osx_image: xcode11.3`.

**Comment by nealrichardson** [comment]
@kou are you adding `osx_image: xcode11.3` somewhere already or should I make a JIRA?

**Comment by kou** [comment]
Could you make a JIRA?

**Pull request closed without merging**
