### PR TITLE
ARROW-12611: [CI][Python] Add different numpy versions to pandas nightly builds

### PR DESCRIPTION
**Pull request by jorisvandenbossche**

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
@github-actions crossbow submit test-*pandas*

**Comment by jorisvandenbossche** [comment]
@kszucs I needed to pin numpy to an older version for the pandas-0.24 build, but so at once added a numpy version for each of the builds, so we also have one build with an older version of numpy and with nightly version

**Comment by jorisvandenbossche** [comment]
@github-actions crossbow submit test-conda-python-3.6-pandas-0.23

**Comment by pitrou** [comment]
Is there a significant difference between pandas "nightly" and "master"?

**Comment by jorisvandenbossche** [comment]
> Is there a significant difference between pandas "nightly" and "master"?

No (on average only a few commits of difference, since nightly is updated every day). IMO testing both is using more CI resources than needed. I am fine with only a single nightly or master build.
(I seem to recall I argued for having only one of both when it was added by @kszucs, but don't remember exactly)

@kszucs this also adds again a build with numpy nightly, which seems to have been accidentally lost in the refactor in https://github.com/apache/arrow/pull/10130

**Comment by kszucs** [comment]
> @kszucs this also adds again a build with numpy nightly, which seems to have been accidentally lost in the refactor in #10130

Thanks @jorisvandenbossche for fixing that!

**Review by kszucs — APPROVED** [review]

**Pull request closed without merging**
