### PR TITLE
ARROW-14977: [Python] Add a "made-up" feature for the guide tutorial

### PR DESCRIPTION
**Pull request by AlenkaF**
We would like to add a **Tutorial** on how to **add a simple feature to PyArrow** that would be a part of the (New) Contributor's Guide.

For this reason I made up a feature called `tutorial_min_max` that I added to `compute.py` plus a unit test to `test_compute.py.` The steps of making this PR will be added to the guide content separately [ARROW-14602](https://issues.apache.org/jira/browse/ARROW-14602.)

cc @jorisvandenbossche @amol- @dragosmg

### CODE REVIEW

**Comment by kszucs** [comment]
Do we plan to add an example using cython as well?

**Comment by AlenkaF** [comment]
@kszucs I think that would be a good idea. Do you have any in mind?

**Comment by kszucs** [comment]
Tipically there are three kinds of patches go to pyarrow:

1. Plain python change like this example which doesn't require rebuilding pyarrow.
2. Cython change touching `.pxi`, `.pyx`, `.pxd` files which requires rebuilding pyarrow (e.g. fixing something or exposing new libarrow functionality)
3. C++ change along with Cython change where we add new code to libarrow[_python] too where we need to rebuild the C++ libraries as well.

**Comment by AlenkaF** [comment]
Thank you for such a good summary.

I was thinking more specifically. It seems harder, at first glance, to make a simple example for cython - I will think of something, suggestions are welcome!

**Comment by kszucs** [comment]
I think we can locate already merged commits for the three separate cases and translate/simplify those to a material suitable for tutorials. Cc @jorisvandenbossche

**Comment by AlenkaF** [comment]
@kszucs do you think this initial PR could be done first and then we can add two more examples in the second version of the Guide?

**Comment by AlenkaF** [comment]
Closing this PR as the [tutorial](https://github.com/apache/arrow/pull/11913) is merged and this will stay an example PR.

**Pull request closed without merging**
