### PR TITLE
ARROW-14722: [R] Fix altrep vector negation modifying original

### PR DESCRIPTION
**Pull request by wjones127**
Got a test reproducing the issue.

### CODE REVIEW

**Comment by wjones127** [comment]
@romainfrancois Got a test reproducing the bug, but not sure where the `-b_int` is actually dispatching to. You have an idea on that?

**Comment by romainfrancois** [comment]
Thanks @wjones127 I'm on it

**Comment by romainfrancois** [comment]
Should be fixed now. For the record, the relevant R code: https://github.com/r-devel/r-svn/blob/1a9b0f70744608548b8d6e7869c3930e3881edab/src/main/arithmetic.c#L793

```c
static SEXP integer_unary(ARITHOP_TYPE code, SEXP s1, SEXP call)
{
    R_xlen_t i, n;
    SEXP ans;

    switch (code) {
    case PLUSOP:
	return s1;
    case MINUSOP:
	ans = NO_REFERENCES(s1) ? s1 : duplicate(s1);
	int *pa = INTEGER(ans);
	const int *px = INTEGER_RO(s1);
	n = XLENGTH(s1);
	for (i = 0; i < n; i++) {
	    int x = px[i];
	    pa[i] = (x == NA_INTEGER) ?
		NA_INTEGER : ((x == 0.0) ? 0 : -x);
	}
	return ans;
    default:
	errorcall(call, _("invalid unary operator"));
    }
    return s1;			/* never used; to keep -Wall happy */
}
```

**Review by romainfrancois — APPROVED** [review]

**Comment by pitrou** [comment]
Removed "WIP" in title to un-skip CI builds.

**Comment by pitrou** [comment]
Should this be merged? Also cc @jonkeane @thisisnic

**Comment by pitrou** [comment]
@ursabot please benchmark lang=R

**Comment by wjones127** [comment]
This should be ready to be merged.

**Pull request closed without merging**
