### PR TITLE
ARROW-14554: [C++][CI] Fix OSS-Fuzz build failure

### PR DESCRIPTION
**Pull request by pitrou**
ARROW-14393 downgraded the bundled GTest version to a version that doesn't build on the OSS-Fuzz setup
(and there doesn't seem to be an obvious fix or workaround around those build errors).
    
Re-bump the bundled GTest version, and try to fix the issue in the Windows verification script differently.
    
Also, add a Crossbow task for the OSS-Fuzz build check, since the Github Actions cron job failure went unnoticed.

### CODE REVIEW

**Comment by pitrou** [comment]
@github-actions crossbow submit -g cpp

**Comment by pitrou** [comment]
@github-actions crossbow submit test-conda-*

**Comment by pitrou** [comment]
@github-actions crossbow submit test-conda-*

**Comment by pitrou** [comment]
@github-actions crossbow submit -g verify-rc-source

**Comment by pitrou** [comment]
@github-actions crossbow submit *vcpkg*

**Comment by pitrou** [comment]
Hmm, it appears we cannot exercise the release verification script using crossbow (it tries to fetch Arrow 1.0.0)? @kszucs

**Comment by pitrou** [comment]
@github-actions crossbow submit test-conda-*

**Comment by pitrou** [comment]
@github-actions crossbow submit -g fuzz

**Comment by pitrou** [comment]
@github-actions crossbow submit -g fuzz

**Comment by pitrou** [comment]
@github-actions crossbow submit -g fuzz

**Comment by pitrou** [comment]
@github-actions crossbow submit -g fuzz

**Comment by pitrou** [comment]
@github-actions crossbow submit -g fuzz

**Comment by pitrou** [comment]
@github-actions crossbow submit -g fuzz

**Comment by pitrou** [comment]
@github-actions crossbow submit -g fuzz

**Comment by pitrou** [comment]
@github-actions crossbow submit test-conda-*

**Comment by pitrou** [comment]
@github-actions crossbow submit test-conda-*

**Comment by pitrou** [comment]
@github-actions crossbow submit test-conda-cpp-valgrind

**Comment by pitrou** [comment]
@github-actions crossbow submit test-conda-cpp-valgrind

**Comment by pitrou** [comment]
@kszucs Can we merge this? I'd like to unblock the OSS-Fuzz builds.

**Comment by kszucs** [comment]
> Hmm, it appears we cannot exercise the release verification script using crossbow (it tries to fetch Arrow 1.0.0)? @kszucs

We can only build releases with those tasks by providing additional parameters: https://github.com/apache/arrow/pull/11511#issuecomment-948918795

**Comment by kszucs** [comment]
> Re-bump the bundled GTest version, and try to fix the issue in the Windows verification script differently.

Do we have a JIRA for that?

**Review by kszucs — APPROVED** [review]

**Comment by pitrou** [comment]
I don't understand the question. What do you want a JIRA for?

**Comment by kszucs** [comment]
> I don't understand the question. What do you want a JIRA for?

Does this fix the windows verification issue as well?

**Comment by pitrou** [comment]
(see diff in https://github.com/apache/arrow/pull/11583/files#diff-6c1e203cf55c63a1f177b4b0c97dc1aa62ea5eed5bd8e017e70703ddf119e343L90-L92)

**Pull request closed without merging**
