### PR TITLE
ARROW-16779:[Python][Packaging] Enable flight on M1 wheels

### PR DESCRIPTION
**Pull request by wjones127**

### CODE REVIEW

**Comment by wjones127** [comment]
@github-actions crossbow submit wheel--cp37-

**Comment by wjones127** [comment]
@github-actions crossbow submit wheel-*-cp37-*

**Comment by wjones127** [comment]
@github-actions crossbow submit wheel-macos-big-sur-cp38-arm64

**Comment by wjones127** [comment]
@github-actions crossbow submit wheel-macos-big-sur-cp38-arm64

**Comment by kszucs** [comment]
cc @raulcd @assignUser

**Comment by kszucs** [comment]
@wjones127 if I recall correctly the main issue was that grpc wasn't available for M1 at the time when we configured this build. I'm not sure what's the current status, but we may need to bump the vcpkg version too so we build against a more recent grpc (which may support M1). 

Updating vcpkg version can be pretty time consuming, but @assignUser has already done it.

**Comment by assignUser** [comment]
After looking into it for a bit I think it should work? our vcpkg has grpc 1.44 and protobuf is also using the correct target...
I think it might be an issue with dependencies missing on the runner https://github.com/ursacomputing/crossbow/runs/6995638000?check_suite_focus=true#step:10:187

**Comment by wjones127** [comment]
Yeah I tried installing libffi, but that didn't seem to actually be missing. So maybe there's an issue with resolving the library.

Is there a good way to open a debug session?

**Comment by assignUser** [comment]
We have a version that is newer than expected
```sh
% ls /opt/homebrew/opt/libffi/lib
libffi.8.dylib  libffi.a        libffi.dylib    pkgconfig
```

**Pull request closed without merging**
