### PR TITLE
GH-38307: [CI] Remove gemfury_clean.rb

### LINKED ISSUE #38307: [CI] Nightlies wheel-clean job is currently failing
### Describe the bug, including details regarding any error messages, version, and platform.

The nightly [wheel-clean](https://github.com/ursacomputing/crossbow/actions/runs/6531049412/job/17731509409) is currently failing with:
```
 Successfully installed gemfury-0.13.0
Parsing documentation for thor-1.2.2
Installing ri documentation for thor-1.2.2
Parsing documentation for progressbar-1.13.0
Installing ri documentation for progressbar-1.13.0
Parsing documentation for netrc-0.11.0
Installing ri documentation for netrc-0.11.0
Parsing documentation for faraday-net_http-3.0.2
Installing ri documentation for faraday-net_http-3.0.2
Parsing documentation for faraday-2.7.11
Installing ri documentation for faraday-2.7.11
Parsing documentation for gemfury-0.13.0
Installing ri documentation for gemfury-0.13.0
Done installing documentation for thor, progressbar, netrc, faraday-net_http, faraday, gemfury after 2 seconds
6 gems installed
/home/runner/.local/share/gem/ruby/3.0.0/gems/gemfury-0.13.0/lib/gemfury/client.rb:258:in `checked_response_body': Gemfury::NotFound (Gemfury::NotFound)
	from /home/runner/.local/share/gem/ruby/3.0.0/gems/gemfury-0.13.0/lib/gemfury/client.rb:73:in `yank_version'
	from arrow/ci/scripts/gemfury_clean.rb:36:in `block (2 levels) in <main>'
	from arrow/ci/scripts/gemfury_clean.rb:33:in `each'
	from arrow/ci/scripts/gemfury_clean.rb:33:in `block in <main>'
	from arrow/ci/scripts/gemfury_clean.rb:25:in `each'
	from arrow/ci/scripts/gemfury_clean.rb:25:in `<main>'
pyarrow
```

### Component(s)

Continuous Integration

### PR DESCRIPTION
**Pull request by raulcd**
### Rationale for this change

wheel-clean nightly job is currently failing. As seen on ADBC: https://github.com/apache/arrow-adbc/issues/1085 gemfury seems to have stopped supporting removing via API.

### What changes are included in this PR?

Do not remove old wheels on gemfury anymore. If we reach quota related issues we can re-create the package on pyarrow as suggested on the comments: https://github.com/apache/arrow/pull/38308#issuecomment-1769767770

### Are these changes tested?

No, we are deleting the CI job that fails.

### Are there any user-facing changes?

No
* Closes: #38307

### CODE REVIEW

**Comment by raulcd** [comment]
@github-actions crossbow submit wheel-clean

**Comment by raulcd** [comment]
@github-actions crossbow submit wheel-clean

**Comment by raulcd** [comment]
I don't understand why is failing to yank any wheel now:
```
Failed to yank pyarrow 13.0.0.dev497 (created 2023-07-13T10:14:54.440Z with Gemfury::NotFound
Failed to yank pyarrow 13.0.0.dev497 (created 2023-07-13T10:14:55.255Z with Gemfury::NotFound
Failed to yank pyarrow 13.0.0.dev497 (created 2023-07-13T10:22:53.335Z with Gemfury::NotFound
Failed to yank pyarrow 13.0.0.dev497 (created 2023-07-13T10:23:02.456Z with Gemfury::NotFound
Failed to yank pyarrow 13.0.0.dev497 (created 2023-07-13T10:30:59.804Z with Gemfury::NotFound
Failed to yank pyarrow 13.0.0.dev497 (created 2023-07-13T10:32:31.240Z with Gemfury::NotFound
Failed to yank pyarrow 13.0.0.dev497 (created 2023-07-13T10:34:39.163Z with Gemfury::NotFound
Failed to yank pyarrow 13.0.0.dev497 (created 2023-07-13T10:36:48.953Z with Gemfury::NotFound
Failed to yank pyarrow 13.0.0.dev497 (created 2023-07-13T10:37:44.074Z with Gemfury::NotFound
Failed to yank pyarrow 13.0.0.dev497 (created 2023-07-13T10:39:39.833Z with Gemfury::NotFound
Failed to yank pyarrow 13.0.0.dev497 (created 2023-07-13T10:39:51.160Z with Gemfury::NotFound
Failed to yank pyarrow 13.0.0.dev497 (created 2023-07-13T10:45:38.766Z with Gemfury::NotFound
Failed to yank pyarrow 13.0.0.dev497 (created 2023-07-13T10:47:21.756Z with Gemfury::NotFound
Failed to yank pyarrow 13.0.0.dev497 (created 2023-07-13T10:47:25.564Z with Gemfury::NotFound
...
```

**Comment by raulcd** [comment]
@kou any idea why this might be failing for the last days?
The ruby gem dependencies seem to be exactly the same versions for the last successful one:
* Last success: https://github.com/ursacomputing/crossbow/actions/runs/6480009013/job/17594663052
The current PR doesn't solve the issue just adds some logging and deals with the exception but I don't think we should catch it as this is hiding the current problem.

**Comment by raulcd** [comment]
> How about just removing `gemfury_clean.rb`?

I am not sure I understand you, if we remove `gemfury_clean.rb` we can remove the `wheel-clean` task? Or are you suggesting a different approach to clean old wheels?

**Comment by kou** [comment]
Sorry for not clarifying it.
I wanted to suggest that we just remove `wheel-clean` task like ADBC did.
If Gemfury reports any quota related error, we can recreate "pyarrow" package on Gemfury. It will remove all uploaded packages.

Or we may be able to stop using Gemfury because we also upload nightly packages to conda-forge: https://arrow.apache.org/docs/developers/python.html#installing-nightly-packages
But we need to ask the community about this on dev@ to choose this approach.

**Comment by raulcd** [comment]
> Sorry for not clarifying it. I wanted to suggest that we just remove `wheel-clean` task like ADBC did. If Gemfury reports any quota related error, we can recreate "pyarrow" package on Gemfury. It will remove all uploaded packages.

Thanks @kou it makes sense to me to remove it. If we reach quota related issues we can recreate as suggested.

**Review by assignUser — APPROVED** [review]

**Review by kou — APPROVED** [review]
+1

**Pull request merged**
