### PR TITLE
ARROW-27: [C++] Set up C++ code coverage uploads to coveralls.io

### PR DESCRIPTION
**Pull request by wesm**
May take a few rounds of trial and error to get this working properly

### CODE REVIEW

**Comment by wesm** [comment]
@MaxRis I can't get the coverage output to show up on https://coveralls.io/github/wesm/arrow, so something is misconfigured. Can you possibly take a look? I added you as a collaborator on my fork

**Comment by wesm** [comment]
@xhochy I can't figure out why parquet-cpp works and this does not. if you have any ideas let me know

**Comment by MaxRis** [comment]
@wesm will investigate, thanks

**Comment by wesm** [comment]
Actually looks like parquet-cpp is broken now too https://coveralls.io/github/apache/parquet-cpp?branch=master

**Comment by wesm** [comment]
Haven't had a good coverage build in parquet-cpp since June 23: https://coveralls.io/repos/93701/builds?page=12

**Comment by wesm** [comment]
Looks like we need to undo the changes to the coveralls upload in https://github.com/apache/parquet-cpp/pull/357

**Comment by xhochy** [comment]
Seems like there is still something missing: https://coveralls.io/builds/13886247/source?filename=src%2Farrow%2Fvisitor.cc

**Comment by wesm** [comment]
Any more ideas on this? Would be nice to get this working soon to start looking at coverage reports

**Comment by pitrou** [comment]
See PR #2023 for an alternative using codecov.io, another free code coverage hosting service.

**Pull request closed without merging**
