### PR TITLE
GH-40944: [Java] Implement TypeEqualsVisitor for StringView

### LINKED ISSUE #40944: [Java] Implement `TypeEqualsVisitor` for StringView
### Describe the enhancement requested

At the moment in the [StringView implementation](https://github.com/apache/arrow/pull/40340), the `TypeEqualsVisitor` functionality is not included. This must be implemented as a follow up PR. 

### Component(s)

Java

### PR DESCRIPTION
**Pull request by tlm365**
### Rationale for this change
Resolves #40944 .

### Are these changes tested?
Yes.

### Are there any user-facing changes?
No.

* GitHub Issue: #40944

### CODE REVIEW

**Comment by vibhatha** [comment]
@tlm365 thanks for working on this PR. I will take a look today.

**Comment by vibhatha** [comment]
@lidavidm could you please help to run the workflows?

**Review by lidavidm — APPROVED** [review]

**Comment by vibhatha** [comment]
@lidavidm  should we also include a test for `string.length > 12`?

**Comment by lidavidm** [comment]
This is for type equality...

**Review by vibhatha — APPROVED** [review]
LGTM!

**Pull request merged**
