### PR TITLE
ARROW-9882: [C++/Python] Update OSX build to conda-forge-ci-setup=3

### PR DESCRIPTION
**Pull request by xhochy**

### CODE REVIEW

**Comment by xhochy** [comment]
@github-actions crossbow submit conda-osx-clang-py36

**Comment by pitrou** [comment]
Can you explain what difference it makes? :-)

**Comment by xhochy** [comment]
This is the newer version of these scripts. Somehow there was a change in the Azure infrastructure that broke the old version.  There are various changes in there, not sure which actually makes the difference.

**Comment by xhochy** [comment]
@github-actions crossbow submit conda-osx-clang-*

**Pull request closed without merging**
