### PR TITLE
MINOR: [C++] Add mising pragma-once

### PR DESCRIPTION
**Pull request by felipecrv**
### Rationale for this change

The C compilation model.

### What changes are included in this PR?

Adding a `#pragma once` that I forgot to add when I created this header.

### Are these changes tested?

N/A.

### CODE REVIEW

**Review by westonpace — APPROVED** [review]

**Comment by felipecrv** [comment]
CI failures are unrelated. @westonpace @pitrou can it be merged?

**Review by pitrou — APPROVED** [review]
Thanks @felipecrv !

**Comment by raulcd** [comment]
Hi @felipecrv , I see this is tagged as 12.0.1 but doesn't have an associated issue. Our cherry-pick scripts can't pick issues for minor releases automatically if there is no a linked GitHub issue. I can cherry-pick this manually but is this required?

**Comment by pitrou** [comment]
@raulcd I don't think this is required if it doesn't fix any breakage.

**Pull request merged**
