### PR TITLE
ARROW-8644: [Python] Restore ParquetDataset behaviour to always include partition column for dask compatibility

### PR DESCRIPTION
**Pull request by jorisvandenbossche**
Given that the original change (https://issues.apache.org/jira/browse/ARROW-3861 / https://github.com/apache/arrow/pull/7050) breaks dask's reading of partitioned datasets (it doesn't add the partition column to the list of columns to read, but expects it will still be read automatically), it doesn't seem worth it to me to fix this in the "old" ParquetDataset implementation. 

But we can keep the "correct" behaviour in the Datasets API - based implementation going forward.

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
@github-actions crossbow submit test-conda-python-3.7-dask-latest test-conda-python-3.8-dask-master

**Review by bkietz — APPROVED** [review]

**Comment by jorisvandenbossche** [comment]
So the question comes up if we actually should also not revert the behaviour in case of `use_legacy_dataset=False` (the

**Comment by wesm** [comment]
This is a regression? If so can you mark it with 0.17.1 (and 1.0.0)

**Comment by jorisvandenbossche** [comment]
No, the PR that caused the regression was only merged after 0.17

**Comment by wesm** [comment]
> For me, that depends a bit on what we want to do long term with ParquetDataset.

IMHO we should be trying to transition people off of this, so that Parquet format isn't necessarily treated separately from general datasets (which may contain different format files). We can keep discussing this

**Pull request closed without merging**
