### PR TITLE
ARROW-15541: [Python] Bump the minimum Cython version

### PR DESCRIPTION
**Pull request by jorisvandenbossche**

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
Cython 0.29.22 is certainly the minimum required version (const in nested type is only supported since then: https://github.com/cython/cython/pull/3886).

**Review by cyb70289 — APPROVED** [review]

**Comment by pitrou** [comment]
Should we also update `ci/conda_env_python.txt` and the various `python/requirements-*.txt` files?

**Comment by jorisvandenbossche** [comment]
> Should we also update `ci/conda_env_python.txt` and the various `python/requirements-*.txt` files?

I think those files are typically used when creating a new environment? In which case they should normally get some latest version of cython. So I am wondering if it is worth it to have to update this version in many more places (certainly given that afterwards building pyarrow will still give a clear error if the cython version was not sufficient)

**Comment by pitrou** [comment]
> So I am wondering if it is worth it to have to update this version in many more places (certainly given that afterwards building pyarrow will still give a clear error if the cython version was not sufficient)

Perhaps not indeed.

**Pull request closed without merging**
