### PR TITLE
ARROW-2772: [JS] Commit package-lock.json and/or yarn.lock

### PR DESCRIPTION
**Pull request by TheNeuralBit**

### CODE REVIEW

**Comment by wesm** [comment]
Wow, 13000 lines? Why is this so large?

**Comment by TheNeuralBit** [comment]
package-lock.json pins version numbers for all of our transitive dependencies, so it's quite a lot of data. You can read more about it here: https://docs.npmjs.com/files/package-lock.json

We haven't run into any issues related to ambiguous dependency versions, but it's generally considered a best practice to have one. @domoritz was pretty shocked when he saw we didn't include it.

Perhaps an argument could be made that we should trim down our dependencies though.

**Comment by wesm** [comment]
It seems like this should be generated as part of a release, no? I am not familiar with best practices for modern JS codebases so I will defer to you all on this

**Comment by domoritz** [comment]
The practice I've seen is to always have the `package.lock`/`yarn.lock` file in the repo. This way every developer always has exactly the same dependencies. A PR that updates a dependency should also update the lock file. 

This looks good to me. I wanted to ask what the reasons for/against using NPM vs yarn are? I personally use yarn for all my projects as it's faster. JupyterLab also uses Yarn. However, NPM is the more standard tool.

**Comment by wesm** [comment]
I read https://medium.com/coinmonks/everything-you-wanted-to-know-about-package-lock-json-b81911aa8ab8. My view (and maybe I'm misunderstanding something) is that as long as installs from released versions are deterministic (i.e. shipping package-lock in the tarball), we don't need to check in this file in the repo

**Comment by domoritz** [comment]
It's not necessary but I found it useful a couple of times. For example, all developers have exactly the same versions and I rarely hear "works for me" these days. I also had some cases where I wanted to try an older commit but since some downstream dependency changed, the code didn't work. I've never had this issue since we started using lockfiles in the repo itself. @wesm are you worried about the additional overhead of having this large file in the repo?

**Comment by wesm** [comment]
Here package-lock.json gzips to ~100KB, which isn't that big of a deal, but I'm trying to understand what use case is being supported. I believe we should be investing our energy in making frequent releases of this software and supporting those releases, not encouraging people to be running unreleased versions of the software

**Comment by domoritz** [comment]
I completely agree! When talked about running previous versions I was talking about me as a developer of the package. Form a release perspective it might be good to have the lockfile in the repo as well since this way no dependencies accidentally update between testing and release.

The npm docs say "It is highly recommended you commit the generated package lock to source control" (https://docs.npmjs.com/files/package-locks#using-locked-packages) and I've not seen a project that only adds the lockfile to releases.

**Comment by trxcllnt** [comment]
@wesm node package lockfiles improve install times locally and in CI, but are also a security feature. Malicious package-hijacking has become a thing, and the lockfiles ensure we/library consumers can pin the dependencies of our dependencies to strict (or exact) version ranges if required. We already do that for our immediate dependencies, but it's extremely common for node modules to declare their own dependencies as allowing major/minor/patch updates.

**Comment by wesm** [comment]
Makes sense. At the released package level I totally get it, but it wasn't clear how this impacts unreleased software. Thanks

**Comment by lmeyerov** [comment]
FWIW, we found NPM packages, once you have enough upstream, is unstable enough that determinism for dev is a feature.

**Review by wesm — APPROVED** [review]
+1

**Pull request closed without merging**
