### PR TITLE
GH-38997: [Java] Modularize format and vector

### LINKED ISSUE #38997: [Java] Build arrow-format and arrow-vector as JPMS modules
### Describe the enhancement requested

This depends on #38998 and #39134 .

Build the first set of core arrow dependencies as JPMS modules while retaining JDK 8 support.

Note that arrow-vector is effectively unusable without also modularizing arrow-memory-core. Vector allocations call into arrow-memory-core's MemoryUtil class which relies on Unsafe.

### Component(s)

Java

### PR DESCRIPTION
**Pull request by jduo**
### Rationale for this change
This PR depends on #39011 .

Make arrow-vector and arrow-format JPMS modules for improved compatibility with newer JDKs
and tools that require modules.

### What changes are included in this PR?
* add module-info.java files for vector and format.

### Are these changes tested?
Yes, these modules are run as JPMS modules in JDK9+ unit tests.

### Are there any user-facing changes?
Yes, some test classes have moved and users can now run these as JPMS modules.

* Closes: #38997

### CODE REVIEW

**Comment by lidavidm** [comment]
This is on my backlog - I'm hoping to give this a review this week

**Review by lidavidm — APPROVED** [review]

**Comment by jduo** [comment]
Thanks for the review @lidavidm . This shouldn't go in yet until we're ready to bite the bullet on modularizing memory-core + making the command-line change though (or we figure out how to avoid the command-line change). I'm changing this back to draft for the time being.

**Comment by jduo** [comment]
Note that this one didn't require doc changes.

**Comment by lidavidm** [comment]
@davisusanibar can you help take a look at the nullness annotation issues here?

**Comment by jduo** [comment]
> @davisusanibar can you help take a look at the nullness annotation issues here?

I fixed a null annotation issue with CountingAllocationListener in the parent patch (#39011).

**Comment by lidavidm** [comment]
Ah whoops, I thought I was looking at that one.

**Comment by lidavidm** [comment]
I think this just needs to be rebased?

**Comment by jduo** [comment]
> I think this just needs to be rebased?

Yes, this is rebased now @lidavidm

**Review by lidavidm — APPROVED** [review]

**Pull request merged**
