### PR TITLE
ARROW-10893: [Rust] [DataFusion] More clippy lints

### PR DESCRIPTION
**Pull request by nevi-me**
This addresses more clippy lints, especially the ones that `cargo clippy --fix -Z unstable-options --allow-dirty` can address

### CODE REVIEW

**Comment by nevi-me** [comment]
@Dandandan making your work a bit harder by taking out the lints that clippy can mostly fix automatically :)

**Comment by Dandandan** [comment]
Ah... just learned a new thing, that clippy (not only the lints in rustc) can be applied automatically using that command. Cool!

**Review by Dandandan — APPROVED** [review]

**Comment by Dandandan** [comment]
LGTM

**Review by alamb — APPROVED** [review]
Looks like some fine improvements to me!

**Pull request closed without merging**
