### PR TITLE
ARROW-9630: [Go] Export JSON reader and writer

### PR DESCRIPTION
**Pull request by zhulongcheng**
Move the JSON reader and writer out of the internal package.
This allows them to be imported by other projects.

### CODE REVIEW

**Comment by fsaintjacques** [comment]
This is not a JSON reader like the C++'s json reader. This is only meant to support the internal custom format used for integration testing between implementation languages.

To me, this package should stay private.

**Comment by xhochy** [comment]
> This is not a JSON reader like the C++'s json reader. This is only meant to support the internal custom format used for integration testing between implementation languages.
> 
> To me, this package should stay private.

Stronly support what @fsaintjacques said, we should rather get https://github.com/apache/arrow/pull/7110 restart to have an official human-readable serialization of the schema.

**Review by sbinet — COMMENTED** [review]
first of all, many thanks for your contribution.

but -like previous committers- I'd err on keeping that package internal. (at the very least it should retain its `arrjson` name to not clash with the standard library's `encoding/json` package).

sorry.

what's the use case for exporting that package?
as other already mentioned, wouldn't that use case be better served by working on an "official" textual arrow representation?

**Comment by zhulongcheng** [comment]
Thanks.

The use case is to read JSON data source into the arrow record batch. Like python's [JSON reader](http://arrow.apache.org/docs/python/json.html) does.

**Comment by fsaintjacques** [comment]
Then I can confirm that it won't work the way you expect it to. It expects a [single giant](https://github.com/apache/arrow/blob/master/go/arrow/internal/arrjson/reader.go#L39-L45) json object.

**Comment by zhulongcheng** [comment]
Thanks for the help, now I know this is not for JSON data sources.

 Sorry, I am new to Arrow.  :)

**Pull request closed without merging**
