### PR TITLE
ARROW-18031: [C++][Parquet] Undefined behavior in bool RLE decoder

### PR DESCRIPTION
**Pull request by zeroshade**
For `BitReader::GetAligned` we need to specialize the behavior for `bool` so that we don't get undefined behavior on potential bad input. Found by the fuzzer.

### CODE REVIEW

**Comment by pitrou** [comment]
The problem here is: how is a RLE boolean literal supposed to be represented? What do other implementations do? cc @sfc-gh-nthimmegowda

**Comment by zeroshade** [comment]
Given the way it's described in the Parquet spec, it looks like it should be a single bit 0 or 1, padded to a single byte, hence just checking that LSB and setting the bool value to that. Of course if others do it differently, we should conform.

**Comment by pitrou** [comment]
Where did you find that? Judging by https://github.com/apache/parquet-format/blob/master/Encodings.md#run-length-encoding--bit-packing-hybrid-rle--3 , it doesn't seem very obvious to me.

**Comment by pitrou** [comment]
Also, should first open a PR to arrow-testing to add the fuzz regression file.

**Comment by zeroshade** [comment]
The error was in handling of a repeated value, which in the spec (that you linked) shows: 

`repeated-value := value that is repeated, using a fixed-width of round-up-to-next-byte(bit-width)`

Hence take the bit-width value (0 or 1 for bit-width == 1) and then pad it to round-up-to-next-byte(1) == 1 byte.

At least that's my read on it. Since you provided the Fuzz file, do you want to add it or should I open the PR?

**Comment by pitrou** [comment]
You now need to update the testing submodule here :-)

**Comment by sfc-gh-nthimmegowda** [comment]
Thank you @zeroshade for the fix. I agree with your explanation. 

@pitrou 
For reference this is how[ java implementation decodes](https://github.com/apache/parquet-mr/blob/5608695f5777de1eb0899d9075ec9411cfdf31d3/parquet-column/src/main/java/org/apache/parquet/column/values/rle/RunLengthBitPackingHybridDecoder.java#L87). 

At the end the type does not matter because everything is casted to int 64 in [Link](https://github.com/apache/arrow/blob/38b956f4da174c1e72607159c9a98f9dbacf6f75/cpp/src/arrow/util/rle_encoding.h#L667) . This is an unfortunate side effect of reusing functions, but I do not see a better way

I disagree with how we are relying on type to calculate the byte size, but unfortunatel I do not see a better way for this.

**Review by pitrou — APPROVED** [review]
+1, thanks @zeroshade

**Review by kou — APPROVED** [review]
+1

**Pull request merged**
