### PR TITLE
ARROW-6099: [Java] introduce a Logger and LoggerFactory class to remove strict dependency

### PR DESCRIPTION
**Pull request by zad**
This PR introduces a Logger and LoggerFactory class to remove strict dependency from slf4j logger, i.e., if slf4j is not available, the logger will be switched to a JDK14Logger.

### CODE REVIEW

**Comment by emkornfield** [comment]
@zad thank you for contribution.  I don't fully understand why this is needed since slf4j is already intended to abstract logging across a variety of different logging sources.  Creating another level of indirection doesn't seem like a good idea.  I wonder maybe this could be better solved with a documentation update on how to use different loggers withing the SLF4j context?

**Comment by jacques-n** [comment]
I'm -1 on this change. It doesn't make sense to have to maintain a secondary facade. Given your situation, I suggest instead you do this the other way around: if you want to include Arrow, generate a version of Arrow that shades the slf4j dependency. You can write your own facade to the shaded APIs that can be used elsewhere. That way we don't take on new code for a very specialized use case. 

In the Dremio case, we publish a version of the JDBC driver with all dependencies shaded in a private package name.

**Comment by praveenbingo** [comment]
@emkornfield We exclude slf4j when we build our jdbc driver using shading. 

@howryu Can we try and solve this using shading when building the snowflake driver?

**Comment by praveenbingo** [comment]
@howryu Depends on how you want to package it

One way to solve this as Jacques mentioned is you can generate a build of Arrow with slf4j shaded and write a facade around that to manage dependencies.

**Comment by emkornfield** [comment]
Given the PR has been vetoed, and it seems like there are alternatives, I'm going to close it for now.  I think further discussions can happen on either user@ or dev@ mailing lists.  @praveenbingo is the JDBC packaging something that is part of dremio-oss that can be pointed to?

**Pull request closed without merging**
