### PR TITLE
ARROW-14310: [R] Make expect_dplyr_equal() more intuitive

### PR DESCRIPTION
**Pull request by thisisnic**
* Renamed "input" to ".input" in test helpers to make more obvious that it's a "special" variable
* Renamed functions that don't fit the `testthat::expect_*()` pattern to prevent confusion
* Added additional documentation to helper functions

### CODE REVIEW

**Comment by dragosmg** [comment]
A more general comment. Would it make sense to replace `expect_equal()` with `expect_identical()` inside `expect_dplyr_equal()`? I feel Arrow is quite strict about type and we're not enforcing a strict check for equivalence with a dplyr call. 
For example, I was surprised to see the {dplyr} call returning an integer and the equivalent {arrow} call returning a double. That's due to `expect_equal()` being less strict than `expect_identical()` - i.e. it has a built in tolerance when checking values (small floating point differences are ignored). This implies that `1L` and `1` are treated as equal.

**Review by jonkeane — COMMENTED** [review]
More generally, since it looks like a lot of the code already has comments throughout. I really appreciate the name change to `compare_*` that makes it pretty clear that these aren't _exactly_ like `expect_equal()` etc. I'm curious to see if `.input` helps make that argument look special enough for folks to recognize something is up there — I'm not sure that would be my first guess, but it's worth a try!

**Review by nealrichardson — COMMENTED** [review]
Some suggestions. Since I wrote most of these test helpers, I'm not in a good position to judge whether these renamings are more intuitive--I don't have any trouble knowing what they do. So if you all are in agreement, that's fine with me.

**Review by jonkeane — APPROVED** [review]
Official approve approve from the files tab

**Pull request closed without merging**
