### PR TITLE
PARQUET-1374: [C++] Fix segfault on writing a parquet file with zero columns

### PR DESCRIPTION
**Pull request by philjdf**
Please see https://issues.apache.org/jira/browse/PARQUET-1374.

This isn't a fix to the ticket, but it fixes something which appears to be wrong which results in a segfault rather than an exception when writing zero columns.

### CODE REVIEW

**Review by pitrou — COMMENTED** [review]
This is fine with me, though I wonder if you could write a simple test for it?

**Comment by pitrou** [comment]
I'm not sure. If the crash is a case of null metadata, perhaps you can create an empty metadata in case there are no columns? (or reorganize the metadata creation logic to achieve that effect)

**Comment by wesm** [comment]
Ping on this one

**Comment by philjdf** [comment]
I won't have the time to change the code to properly support zero columns. Tomorrow I'll add a unit test to check we get an exception upon writing zero columns, so I can at least make this a complete PR!

**Comment by pitrou** [comment]
It appears this was fixed in 3d435e4f8d5fb7a54a4a9d285e1a42d60186d8dc.

**Pull request closed without merging**
