### PR TITLE
MINOR: [Rust] [Ballista] Ballista now uses relative paths for dependencies

### PR DESCRIPTION
**Pull request by andygrove**
This is preperation for moving to the new repo tomorrow

### CODE REVIEW

**Comment by kszucs** [comment]
@andygrove can I include this patch in a new release candidate?

**Comment by andygrove** [comment]
@kszucs yes

**Comment by andygrove** [comment]
@kszucs Actually, it depends ... if you just patch this PR into the previous RC it might not work. If you are starting fresh with a new RC from master, then yes

**Comment by kszucs** [comment]
I'm going to cut a new RC from the master after merging #10091

**Pull request merged**
