### PR TITLE
ARROW-6804: [CI] [Rust] Migrate Travis job to Github Actions

### PR DESCRIPTION
**Pull request by pitrou**

### CODE REVIEW

**Comment by pitrou** [comment]
@andygrove @wesm

**Comment by pitrou** [comment]
The job apparently ran in 17 minutes: https://github.com/pitrou/arrow/runs/250734443

**Review by andygrove — APPROVED** [review]
💯

**Comment by fsaintjacques** [comment]
Any reason to not merge this into `linux-docker-compose.yml` so we don't copy everything?

**Comment by pitrou** [comment]
I don't know. Should look at how the syntax works :-)

**Comment by fsaintjacques** [comment]
See https://github.com/apache/arrow/pull/5580/files#diff-2cf2df30a58f9caa3c1f232fe087bee0R29-R39 on how to do this (similar to travis matrix).

**Comment by andygrove** [comment]
It looks like the `docker-compose build` step is building the Docker image each time, which is pretty slow. We should consider having a base image we extend that already has the two versions of Rust that we need.

**Comment by pitrou** [comment]
That is something @kszucs may be looking at.

**Comment by pitrou** [comment]
Ok, I merged things. I agree it's much better :-)

**Pull request closed without merging**
