### PR TITLE
ARROW-6312: [C++] Add support for "pkg-config --static arrow"

### PR DESCRIPTION
**Pull request by kou**

### CODE REVIEW

**Comment by pitrou** [comment]
This seems useful. Can we add a documentation chapter about using `pkg-config`? For example in https://arrow.apache.org/docs/cpp/cmake.html, which currently only covers CMake.

**Comment by kou** [comment]
I've added a documentation about using `pkg-config`.

**Comment by kou** [comment]
+1

If we need more work for #10404, we can work on it in #10404.

**Comment by kszucs** [comment]
@kou this seems to broke the manylinux and macos wheel builds.

**Comment by kou** [comment]
Oh, sorry. I'll fix it soon.

**Comment by kou** [comment]
#10668

**Pull request closed without merging**
