### PR TITLE
ARROW-5919: [R] Test R-in-conda as a nightly build

### PR DESCRIPTION
**Pull request by xhochy**

### CODE REVIEW

**Comment by xhochy** [comment]
JIRA is currently unresponsive and thus I was unable to open an issue.

@kszucs I always forget where to put things so that they are run as a nightly. Can you point me to it?

**Comment by kszucs** [comment]
@xhochy dev/tasks/tests.yml

**Comment by kszucs** [comment]
@ursabot crossbow test docker-r-conda

**Comment by kszucs** [comment]
The badge shows `failing` for `in-progress`...

**Comment by xhochy** [comment]
`docker-r-conda` passed successfully :)

**Comment by kszucs** [comment]
RAT is failing and misses a ticket number, will do tomorrow.

**Review by kszucs — APPROVED** [review]
LGTM

**Pull request closed without merging**
