### PR TITLE
ARROW-12075: [Rust][DataFusion] Add CTE + UNION ALL to supported list of SQL features

### PR DESCRIPTION
**Pull request by alamb**
@Dandandan  added the feature in https://github.com/apache/arrow/pull/9776, updating docs to keep pace

### CODE REVIEW

**Comment by Dandandan** [comment]
@alamb I should remember to add it to this list! What about adding UNION too?

**Comment by alamb** [comment]
> What about adding UNION too?
Good call -- will do!

**Review by Dandandan — APPROVED** [review]
👍

**Review by jorgecarleitao — APPROVED** [review]
LGTM!

**Comment by alamb** [comment]
This PR only changes documentation -- the CI failures are unrelated.

**Pull request closed without merging**
