### PR TITLE
GH-41891: [C++] Clean up implicit fallthrough warnings

### PR DESCRIPTION
**Pull request by WillAyd**
### Rationale for this change

Helps clean up warnings, and at least one of these looks like a subtle bug that may confuse developers

### What changes are included in this PR?

Added break statements where case statements were previously falling through

### Are these changes tested?

Builds cleanly

### Are there any user-facing changes?

No

* GitHub Issue: #41891

### CODE REVIEW

**Comment by pitrou** [comment]
I'm curious, why did you close this PR?

**Comment by pitrou** [comment]
It's probably a desirable even though minor cleanup.

**Comment by WillAyd** [comment]
@pitrou do we need to run this through crossbow or is it good as is?

**Comment by pitrou** [comment]
Since we're nearing a release, let's do a Crossbow run :-)

**Comment by pitrou** [comment]
@github-actions crossbow submit -g cpp

**Comment by pitrou** [comment]
@github-actions crossbow submit wheel*cp312*

**Review by pitrou — APPROVED** [review]

**Comment by pitrou** [comment]
@WillAyd Do you want to merge this PR? Please make sure you use the [merge script](https://github.com/apache/arrow/blob/main/dev/merge_arrow_pr.sh), not the GitHub button.

**Comment by WillAyd** [comment]
OK sure no problem. So stepping through that, I just need to run

```sh
./merge_arrow_pr.sh 41892
```

right?

**Comment by pitrou** [comment]
Yes!

**Pull request merged**
