### PR TITLE
ARROW-5319: [C++][CI] Use ccache with MinGW builds on AppVeyor [travis skip]

### PR DESCRIPTION
**Pull request by kou**

### CODE REVIEW

**Comment by kou** [comment]
AppVeyor is green.
I'll merge this.

**Comment by pitrou** [comment]
Can you push a new build to check that the cache works?

**Comment by pitrou** [comment]
Too late.

**Comment by kou** [comment]
I've tests on my AppVeyor build:

* First: https://ci.appveyor.com/project/kou/arrow/builds/24578651 (20-22min)
* Second: https://ci.appveyor.com/project/kou/arrow/builds/24579486 (6-8min)

**Pull request closed without merging**
