### PR TITLE
ARROW-14514: [C++][R] UBSAN error on round kernel

### PR DESCRIPTION
**Pull request by edponce**
Add base class `OptionsWrapper` to primary template of `RoundOptionsWrapper`.

### CODE REVIEW

**Comment by edponce** [comment]
Thanks @lidavidm! I am taking a careful look at the use of `OptionsWrapper` and `RoundOptionsWrapper`.

**Comment by lidavidm** [comment]
FYI, setting a breakpoint in R, you can indeed observe that we have the wrong OptionsWrapper type at some point. I'm also trying to track this down now.

**Comment by lidavidm** [comment]
This is the issue:

```diff
diff --git a/cpp/src/arrow/compute/kernels/scalar_arithmetic.cc b/cpp/src/arrow/compute/kernels/scalar_arithmetic.cc
index be6f35164..3036e2c9b 100644
--- a/cpp/src/arrow/compute/kernels/scalar_arithmetic.cc
+++ b/cpp/src/arrow/compute/kernels/scalar_arithmetic.cc
@@ -1062,10 +1062,19 @@ template <>
 struct RoundOptionsWrapper<RoundToMultipleOptions>
     : public OptionsWrapper<RoundToMultipleOptions> {
   using OptionsType = RoundToMultipleOptions;
+  using State = RoundOptionsWrapper<OptionsType>;
+  using OptionsWrapper::OptionsWrapper;
 
   static Result<std::unique_ptr<KernelState>> Init(KernelContext* ctx,
                                                    const KernelInitArgs& args) {
-    ARROW_ASSIGN_OR_RAISE(auto state, OptionsWrapper<OptionsType>::Init(ctx, args));
+    std::unique_ptr<State> state;
+    if (auto options = static_cast<const OptionsType*>(args.options)) {
+      state = ::arrow::internal::make_unique<State>(*options);
+    } else {
+      return Status::Invalid(
+          "Attempted to initialize KernelState from null FunctionOptions");
+    }
+
     auto options = Get(*state);
     const auto& type = *args.inputs[0].type;
     if (!options.multiple || !options.multiple->is_valid) {
```

**Review by lidavidm — APPROVED** [review]

**Comment by edponce** [comment]
Final update: Made a trivial change for better readability of primary templates in specializations.

**Comment by jonkeane** [comment]
Ok, I've got a CI that bumps into this. I'm still waiting for it to finish a (failing) build over at #11577, but I also created a combo of this branch + that branch and triggered a crossbow build at https://github.com/apache/arrow/pull/11578. If that passes (and #11577 fails) this is good to go

**Comment by lidavidm** [comment]
Thanks for working out the CI stuff! I tried to get a dynmically-linked ASan working but no dice there.

**Comment by jonkeane** [comment]
🎉 the sanitizer passed: https://github.com/apache/arrow/pull/11578#issuecomment-955112753

**Comment by lidavidm** [comment]
Thanks Jon! 

The AppVeyor failure is unrelated, merging this now.

**Pull request closed without merging**
