### PR TITLE
ARROW-2682: [CI] Notify in Slack about broken builds

### PR DESCRIPTION
**Pull request by xhochy**

### CODE REVIEW

**Comment by wesm** [comment]
Does this notify on cancelled builds (which we have a lot of in Travis CI) or only builds that reach completion and fail?

**Comment by xhochy** [comment]
Not 100% sure but this should notify only on builds that are colored red in the UI. No notification for the grey (cancelled) builds. It will also only notify by default on master builds in our case.

**Review by wesm — APPROVED** [review]
+1, this should be helpful, thank you!

**Comment by xhochy** [comment]
Seems like we don't need this, already getting notifications.

image

**Comment by wesm** [comment]
That notification is coming from this PR, so I guess that means the patch is working =) I'll merge it now

**Pull request closed without merging**
