### PR TITLE
ARROW-5173: [Go] handle multiple concatenated record batches

### PR DESCRIPTION
**Pull request by sbinet**

### CODE REVIEW

**Comment by sbinet** [comment]
needs #4159

**Comment by sbinet** [comment]
PTAL @stuartcarnie @alexandreyc @nickpoorman

**Comment by sbinet** [comment]
(the Travis-CI error is unrelated (JDK-9 is acting up?))

**Comment by alexandreyc** [comment]
Looks like this PR is a subset of #4161

**Review by stuartcarnie — APPROVED** [review]
For building complex CLI interfaces, I'd recommend you look at https://github.com/spf13/cobra. You can then have a single binary:

```sh
$ arrow ls ...
```

```sh
$ arrow cat
```

etc

**Pull request closed without merging**
