### PR TITLE
ARROW-9963: [Python] Recognize datetime.timezone.utc as UTC on conversion python->pyarrow

### PR DESCRIPTION
**Pull request by jorisvandenbossche**

### CODE REVIEW

**Comment by kszucs** [comment]
@jorisvandenbossche python 3.5 build is failing.

**Comment by pitrou** [comment]
Indeed, on Python 3.5, we have:
```python
>>> timezone.utc.tzname(None)
'UTC+00:00'
```

**Comment by jorisvandenbossche** [comment]
I updated the expected return value for Python 3.5 to still be the former "+00:00" (instead of adding further special cases to the C++ code to "correct" this for python 3.5)

**Review by pitrou — APPROVED** [review]
+1

**Pull request closed without merging**
