### PR TITLE
ARROW-16747: [CI][Release][Python] Drop support for manylinux 2010

### PR DESCRIPTION
**Pull request by raulcd**
See also the discussion on the mailing list:
https://lists.apache.org/thread/dfsvcsmrmktgnqz9fyc9ym33zldwklyx

### CODE REVIEW

**Comment by raulcd** [comment]
@github-actions crossbow submit *manylinux*

**Comment by raulcd** [comment]
@jorisvandenbossche I think this is ready for review. I can't find more references to manylinux 2010.

**Review by kou — APPROVED** [review]
+1

**Comment by raulcd** [comment]
@kou it seems the JIRA ticket did not get resolved by the merge script once the PR was merged. Could it be because of the JIRA link to the other ticket?

**Comment by kou** [comment]
Sorry. I forgot to press "Enter" on my terminal... I did it now.

**Pull request merged**
