### PR TITLE
ARROW-11427: [C++] On Windows, only use AVX512 when enabled by the OS

### PR DESCRIPTION
**Pull request by pitrou**
AVX512 may be supported by the CPU but not by the Windows kernel (which needs to save and restore 512-bit registers on context switch).

Also, add a `GetRuntimeInfo()` API and the corresponding Python function `pa.runtime_info()` to query the current SIMD level.

### CODE REVIEW

**Comment by pitrou** [comment]
cc @jianxind

**Comment by nealrichardson** [comment]
+1 for GetRuntimeInfo, I wanted that when I was debugging ARROW-11217

**Review by bkietz — APPROVED** [review]
LGTM

**Comment by pitrou** [comment]
The fix has been verified to work.

**Pull request closed without merging**
