### PR TITLE
ARROW-4878: [C++] Append \Library to CONDA_PREFIX when using ARROW_DEPENDENCY_SOURCE=CONDA

### PR DESCRIPTION
**Pull request by wesm**
Not sure how this made it through CI

### CODE REVIEW

**Comment by wesm** [comment]
I got confused. I think the `\Library` _only_ has to be added for Boost. I'll fix the PR once the build runs so I can make sure

**Comment by wesm** [comment]
On my machine the correct prefix to find the pkgconfig and cmake file does have the \Library

```
C:\Users\wesmc\code\arrow\cpp\build (toolchain-option -> origin)
(arrow-dev) λ ls %CONDA_PREFIX%\Library\lib\cmake
benchmark/  c-ares/  clang/  double-conversion/  flatbuffers/  gflags/  glog/  llvm/  Snappy/

C:\Users\wesmc\code\arrow\cpp\build (toolchain-option -> origin)
(arrow-dev) λ ls %CONDA_PREFIX%\Library\lib\pkgconfig
benchmark.pc  libbrotlicommon.pc  libbrotlidec.pc  libbrotlienc.pc  libcares.pc  libxml-2.0.pc  protobuf.pc  protobuf-lite.pc
```

**Comment by xhochy** [comment]
I first had this also in my code but then I realised that some code is already dealing with `\Library` and some not so I only fixed the places that were unable to use `$CONDA_PREFIX` directly. If it works with `\Library` always appended, we should keep this, it will make the `Find*.cmake` files simpler.

**Comment by wesm** [comment]
+1. The build passed so I'll go ahead and merge this and we can do clean up of places where \Library is being added elsewhere

**Pull request closed without merging**
