### PR TITLE
ARROW-9130: [Python] Add deprecation wrapper for pyarrow.compat and guid function for Dask

### PR DESCRIPTION
**Pull request by wesm**
This fixes the import error but the integration tests fail with other errors

https://gist.github.com/wesm/312a26a9fcb2521756410251f6672e99

### CODE REVIEW

**Comment by wesm** [comment]
@kszucs or @jorisvandenbossche could you investigate the failing Dask tests?

**Comment by kszucs** [comment]
Discussed it with Joris and he already knows the resolution.

**Comment by jorisvandenbossche** [comment]
@wesm those failures are "expected", in the sense that the integration tests already have been failing for a few weeks with this error.  
At the time, I opened an issue for this on the dask side (https://github.com/dask/dask/issues/6243), as ideally it would be solved there (although the discussion on the issue did not yet result in a clear conclusion ..).

Now, until there is a clear resolution, we can maybe skip those tests for now to get the rest of the integration tests "green"?

**Comment by wesm** [comment]
Sure, thanks, I wasn't in the loop so I'll leave it to you

**Review by jorisvandenbossche — APPROVED** [review]
The PR itself looks good to me, the remaining failures can be handled (eg skipped for now) separately I think

**Comment by wesm** [comment]
Appveyor build https://ci.appveyor.com/project/wesm/arrow/builds/33551938

**Pull request closed without merging**
