### PR TITLE
ARROW-7669: [CI] Turn optimizations off in AppVeyor MinGW builds

### PR DESCRIPTION
**Pull request by pitrou**

### CODE REVIEW

**Review by wesm — APPROVED** [review]
+1. Not sure why the mingw64 build stalled in Appveyor, I just restarted it

**Comment by wesm** [comment]
Hm the mingw64 failure is reproducible, seems like it is hanging on linking libarrow.dll. Is it possible because of the debug settings that it's running against an OOM causing a hang of some kind (@kou any ideas)? 

```
[ 35%] Linking CXX shared library ../../release/libarrow.dll
cd /C/projects/arrow/cpp/build/src/arrow && C:/msys64/usr/bin/ccache.exe /C/msys64/mingw64/bin/cmake.exe -E remove -f CMakeFiles/arrow_shared.dir/objects.a
cd /C/projects/arrow/cpp/build/src/arrow && C:/msys64/usr/bin/ccache.exe /C/msys64/mingw64/bin/ar.exe cr CMakeFiles/arrow_shared.dir/objects.a @CMakeFiles/arrow_shared.dir/objects1.rsp
cd /C/projects/arrow/cpp/build/src/arrow && C:/msys64/usr/bin/ccache.exe /C/msys64/mingw64/bin/g++.exe   -Wno-noexcept-type -O3 -DNDEBUG -O0 -fdiagnostics-color=always  -Wall -msse4.2  -O0 -Wl,--version-script=C:/projects/arrow/cpp/src/arrow/symbols.map -shared -o ../../release/libarrow.dll -Wl,--out-implib,../../release/libarrow.dll.a -Wl,--major-image-version,100,--minor-image-version,0 -Wl,--whole-archive CMakeFiles/arrow_shared.dir/objects.a -Wl,--no-whole-archive  /C/OpenSSL-Win64/lib/libeay32.lib /C/OpenSSL-Win64/lib/ssleay32.lib /C/msys64/mingw64/lib/libbrotlienc-static.a /C/msys64/mingw64/lib/libbrotlidec-static.a /C/msys64/mingw64/lib/libbrotlicommon-static.a -lWs2_32 /C/OpenSSL-Win64/lib/libeay32.lib /C/OpenSSL-Win64/lib/ssleay32.lib /C/msys64/mingw64/lib/libbrotlienc-static.a /C/msys64/mingw64/lib/libbrotlidec-static.a /C/msys64/mingw64/lib/libbrotlicommon-static.a /C/msys64/mingw64/lib/libbz2.dll.a /C/msys64/mingw64/lib/liblz4.dll.a /C/msys64/mingw64/lib/libsnappy.a /C/msys64/mingw64/lib/libz.dll.a /C/msys64/mingw64/lib/libzstd.dll.a /C/msys64/mingw64/lib/libboost_filesystem-mt.dll.a /C/msys64/mingw64/lib/libboost_system-mt.dll.a /C/OpenSSL-Win64/lib/libeay32.lib -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32 
```

**Comment by kou** [comment]
How about debugging on AppVeyor with Remote Desktop by adding the following:

```diff
diff --git a/appveyor.yml b/appveyor.yml
index df1893304..d20207fe5 100644
--- a/appveyor.yml
+++ b/appveyor.yml
@@ -98,6 +98,9 @@ environment:
   MSVC_DEFAULT_OPTIONS: ON
   APPVEYOR_SAVE_CACHE_ON_ERROR: true
 
+init:
+  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
+
 install:
   - python ci\detect-changes.py > generated_changes.bat
   # Populate ARROW_CI_* variables
```

FYI: https://www.appveyor.com/docs/how-to/rdp-to-build-worker/

**Comment by wesm** [comment]
Seems like disabling optimizations might need to be abandoned for the time being? There are some other changes that appear to be needed though

**Comment by kou** [comment]
I'm working on migrating MinGW build to GitHub Actions from AppVeyor.
I got error message for linking libarrow.dll:

https://github.com/kou/arrow/commit/3f0e89092491867411bbc7f3ccb4d3ba3feaa8fa/checks/498999927/logs

```text
2020-03-10T23:37:16.2953654Z D:/a/arrow/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: CMakeFiles/arrow_shared.dir/objects.a(diff.cc.obj):diff.cc:(.text$_ZNSt14_Function_base13_Base_managerIN5arrow20UnifiedDiffFormatterEE10_M_managerERSt9_Any_dataRKS4_St18_Manager_operation[_ZNSt14_Function_base13_Base_managerIN5arrow20UnifiedDiffFormatterEE10_M_managerERSt9_Any_dataRKS4_St18_Manager_operation]+0x48): undefined reference to `typeinfo for arrow::UnifiedDiffFormatter'
2020-03-10T23:37:16.3059414Z D:/a/arrow/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: CMakeFiles/arrow_shared.dir/objects.a(diff.cc.obj): in function `std::_Function_base::_Base_manager<arrow::MakeFormatterImpl::Visit(arrow::BooleanType const&)::{lambda(arrow::Array const&, long long, std::ostream*)#1}>::_M_manager(std::_Any_data&, std::_Function_base::_Base_manager<arrow::MakeFormatterImpl::Visit(arrow::BooleanType const&)::{lambda(arrow::Array const&, long long, std::ostream*)#1}> const&, std::_Manager_operation)':
2020-03-10T23:37:16.3063293Z D:/a/arrow/msys64/mingw64/include/c++/9.2.0/bits/std_function.h:203: undefined reference to `typeinfo for arrow::MakeFormatterImpl::Visit(arrow::BooleanType const&)::{lambda(arrow::Array const&, long long, std::ostream*)#1}'
2020-03-10T23:37:16.3075597Z D:/a/arrow/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: CMakeFiles/arrow_shared.dir/objects.a(diff.cc.obj): in function `std::_Function_base::_Base_manager<arrow::MakeFormatterImpl::MakeTimeFormatter<arrow::TimestampType, true>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)::{lambda(arrow::Array const&, long long, std::ostream*)#1}>::_M_manager(std::_Any_data&, std::_Function_base::_Base_manager<arrow::MakeFormatterImpl::MakeTimeFormatter<arrow::TimestampType, true>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)::{lambda(arrow::Array const&, long long, std::ostream*)#1}> const&, std::_Manager_operation)':
2020-03-10T23:37:16.3139071Z D:/a/arrow/msys64/mingw64/include/c++/9.2.0/bits/std_function.h:203: undefined reference to `typeinfo for arrow::MakeFormatterImpl::MakeTimeFormatter<arrow::TimestampType, true>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)::{lambda(arrow::Array const&, long long, std::ostream*)#1}'
2020-03-10T23:37:16.3172978Z D:/a/arrow/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: CMakeFiles/arrow_shared.dir/objects.a(diff.cc.obj): in function `std::_Function_base::_Base_manager<arrow::MakeFormatterImpl::Visit(arrow::DayTimeIntervalType const&)::{lambda(arrow::Array const&, long long, std::ostream*)#1}>::_M_manager(std::_Any_data&, std::_Function_base::_Base_manager<arrow::MakeFormatterImpl::Visit(arrow::DayTimeIntervalType const&)::{lambda(arrow::Array const&, long long, std::ostream*)#1}> const&, std::_Manager_operation)':
2020-03-10T23:37:16.3185871Z D:/a/arrow/msys64/mingw64/include/c++/9.2.0/bits/std_function.h:203: undefined reference to `typeinfo for arrow::MakeFormatterImpl::Visit(arrow::DayTimeIntervalType const&)::{lambda(arrow::Array const&, long long, std::ostream*)#1}'
2020-03-10T23:37:16.3192076Z D:/a/arrow/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: CMakeFiles/arrow_shared.dir/objects.a(diff.cc.obj): in function `std::_Function_base::_Base_manager<arrow::MakeFormatterImpl::Visit(arrow::Decimal128Type const&)::{lambda(arrow::Array const&, long long, std::ostream*)#1}>::_M_manager(std::_Any_data&, std::_Function_base::_Base_manager<arrow::MakeFormatterImpl::Visit(arrow::Decimal128Type const&)::{lambda(arrow::Array const&, long long, std::ostream*)#1}> const&, std::_Manager_operation)':
2020-03-10T23:37:16.3217116Z D:/a/arrow/msys64/mingw64/include/c++/9.2.0/bits/std_function.h:203: undefined reference to `typeinfo for arrow::MakeFormatterImpl::Visit(arrow::Decimal128Type const&)::{lambda(arrow::Array const&, long long, std::ostream*)#1}'
2020-03-10T23:37:16.3245269Z D:/a/arrow/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: CMakeFiles/arrow_shared.dir/objects.a(diff.cc.obj): in function `std::_Function_base::_Base_manager<arrow::MakeFormatterImpl::Visit(arrow::StructType const&)::StructImpl>::_M_manager(std::_Any_data&, std::_Any_data const&, std::_Manager_operation)':
2020-03-10T23:37:16.3455566Z D:/a/arrow/msys64/mingw64/include/c++/9.2.0/bits/std_function.h:203: undefined reference to `typeinfo for arrow::MakeFormatterImpl::Visit(arrow::StructType const&)::StructImpl'
...
```

Linking libarrow.dll isn't hanged. It just takes very long time (2h+).

**Comment by wesm** [comment]
Oh okay. We may have to abandon this work potentially

**Comment by wesm** [comment]
Is this any better in GitHub Actions? Otherwise perhaps it should be abandoned

**Comment by kou** [comment]
GitHub Actions doesn't solve this.
I can reproduce this long linking time on my local Windows VM.

Let's abandon.
(We may want to merge code improvements in this pull request as a separated pull request.)

**Pull request closed without merging**
