### PR TITLE
GH-35468: [C++] Fix Acero var/std for multiple batches

### LINKED ISSUE #35468: [C++] Fix Acero var/std for multiple batches
### Describe the bug, including details regarding any error messages, version, and platform.

In Acero, var/std computation resets the kernel state, instead of augmenting it, with each batch processed.

### Component(s)

C++

### PR DESCRIPTION
**Pull request by rtpsw**
See https://github.com/apache/arrow/issues/35468

**This PR contains a "Critical Fix".**

The current result of Acero var/std for multiple batches is incorrect.
* Closes: #35468

### CODE REVIEW

**Comment by rtpsw** [comment]
cc @icexelloss

**Comment by rtpsw** [comment]
The [recent commit](https://github.com/apache/arrow/pull/35469/commits/1ca345fe5c302ad9c478e763ea2e10dc9ae6f211) fixes an unrelated error in [this `AMD64 Conda C++` CI job](https://github.com/apache/arrow/actions/runs/4901473101/jobs/8752774192?pr=35469).

**Comment by rtpsw** [comment]
This is odd. The [former build error](https://github.com/apache/arrow/pull/35469#issuecomment-1537145980) was due to `void benchmark::MemoryManager::Stop(benchmark::MemoryManager::Result&)` not overridden by `void arrow::MemoryPoolMemoryManager::Stop(benchmark::MemoryManager::Result*)` (a pointer argument mismatch to a reference argument), while the [current `AMD64 Windows 2019 C++17` CI job build error](https://github.com/apache/arrow/actions/runs/4901926429/jobs/8753471651?pr=35469) (where a reference argument is used) is due to the opposite. Apparently, the signature of `benchmark::MemoryManager::Stop` is inconsistent across platforms. I'll revert this commit and leave the fix to future work.

**Comment by kou** [comment]
https://github.com/apache/arrow/pull/35459 is for the "C++ / AMD64 Conda C++" build error.

**Comment by kou** [comment]
BTW, could you use our PR template instead of ignoring it?

**Comment by rtpsw** [comment]
> BTW, could you use our PR template instead of ignoring it?

I wasn't aware of it. Sure, could you refer me to it?

**Comment by kou** [comment]
You must see it in pull request description when you open a new pull request.
I think that you delete it when you open this pull request.

FYI: It's a GitHub feature. GitHub inserts https://raw.githubusercontent.com/apache/arrow/main/.github/pull_request_template.md to pull request description when we open a new pull request.

**Review by icexelloss — APPROVED** [review]
LGTM

**Review by westonpace — APPROVED** [review]
Thanks for the fix.  I agree the build errors are unrelated.

**Pull request merged**
