### PR TITLE
ARROW-11140: [Rust] [CI] Experimenting with Buildkite

### PR DESCRIPTION
**Pull request by jorgecarleitao**
I removed all workflows so that they do not get triggered on this PR, as there will be a lot of experimenting and I do not want to trigger those flows.

### CODE REVIEW

**Comment by kszucs** [comment]
I set up a pipeline for Rust. You can see the available pipelines here https://buildkite.com/apache-arrow
The dispatcher is responsible to trigger other pipelines, it uses the following configuration:

```yml
steps:
  # if push then compare to the previous commit
  - label: "Triggering pipelines"
    # if pull request
    plugins:
      - chronotc/monorepo-diff#v1.2.0:
          diff: .buildkite/pull-request-diff.sh ${BUILDKITE_PULL_REQUEST_BASE_BRANCH} ${BUILDKITE_COMMIT}
          watch:
            - path: go/
              config:
                trigger: arrow-go
            - path: rust/
              config:
                trigger: arrow-rust
            - path: cpp
              config:
                trigger: arrow-c-plus-plus
            - path: python/
              config:
                trigger: arrow-python
​```

Since we have no agents running at the moment you won't be able to trigger builds.
I'll try to configure a machine in the upcoming days, but we have network provider issues with our self hosted workers.

**Comment by jorgecarleitao** [comment]
Ok, I think that this is now ready for a spin. It took a bit more than I antecipated, but the core work is ready. This basically deprecates all our rust jobs on github, replacing them by equivalents on buildkite.

**Comment by mqy** [comment]
I can't wait for this! Current CI is slower than little snails!

**Comment by kszucs** [comment]
Note that this has a downside, buildkite won't be available for apache/arrow forks.

**Comment by jorgecarleitao** [comment]
> Note that this has a downside, buildkite won't be available for apache/arrow forks.

Yeap. That is a downside. But we plan to have them running for open PRs, right?

**Comment by kszucs** [comment]
Preferably, of course it comes with a maintenance cost.

**Comment by jorgecarleitao** [comment]
@wesm , is there any update around this? If we do not plan to pursue this, please let me know and we close this PR.

**Comment by alamb** [comment]
@jorgecarleitao 
What is the status of this PR?

As part of trying to clean up the backlog of Rust PRs in this repo, I am going through seemingly stale PRs and pinging the authors to see if there are any plans to continue the work or conversation.

**Comment by alamb** [comment]
@jorgecarleitao  I am closing this PR for the time being to clean up the Rust/Arrow PR backlog.  Please let me know if this is a mistake

**Pull request closed without merging**
