### PR TITLE
ARROW-16048: [Python] Avoid exposing null buffer address to the Python buffer protocol

### PR DESCRIPTION
**Pull request by emkornfield**
A 0-size buffer created in C++ can very well have a null address. However, when exporting that buffer through the Python buffer API, we should ensure we pass a valid pointer.

Also, ensure mutability of a buffer is preserved when pickling and unpickling.

### CODE REVIEW

**Review by jorisvandenbossche — APPROVED** [review]

**Comment by emkornfield** [comment]
@pitrou I'm sorry I'm not at a computer that I can merge PRs, it seems like this is ready though?

**Comment by pitrou** [comment]
Hmm, right, I'm going to rebase first to get a working macOS build.

**Comment by pitrou** [comment]
@github-actions crossbow submit -g python

**Comment by pitrou** [comment]
Successful Appveyor build on my fork: https://ci.appveyor.com/project/pitrou/arrow/builds/43298552

**Pull request closed without merging**
