### PR TITLE
ARROW-13001: [Go][Parquet] fix build failure on s390x

### PR DESCRIPTION
**Pull request by zeroshade**

### CODE REVIEW

**Comment by zeroshade** [comment]
@bkietz @emkornfield For attention

**Comment by cyb70289** [comment]
Also add "xxx_arm64.go"?

**Comment by zeroshade** [comment]
@cyb70289 do we actually already have an arm build?

**Comment by cyb70289** [comment]
> @cyb70289 do we actually already have an arm build?

We have Arm64 CI for C++, but not for golang.
Please ignore this requirement. I will try adding golang Arm64 CI job first.

**Comment by zeroshade** [comment]
@cyb70289 Once there is an arm64 golang job, i'm happy to take a look at trying to help fix any failures in it. 

Though I have no idea where I'd test it. I got lucky with this one and spun up an s390x VM via IBM Community Cloud so I was able to printline debug to track this down.

**Review by bkietz — APPROVED** [review]
Thanks for fixing this!
An arm/go CI job sounds worthwhile, please file a follow up JIRA.

**Comment by cyb70289** [comment]
https://github.com/apache/arrow/pull/10515 adds Arm go CI job.

**Pull request closed without merging**
