### PR TITLE
GH-36449: [C++][CI] Don't use -g1 for Python jobs

### LINKED ISSUE #36449: [C++][CI] test_gdb fails on nightly job test-cuda-python
### Describe the bug, including details regarding any error messages, version, and platform.

[test-cuda-python](https://github.com/ursacomputing/crossbow/actions/runs/5449601863/jobs/9913998035) fails on `test_gdb` for several tests. All errors seem to not be able to match the type, like:

```
     def check_stack_repr(gdb, expr, expected):
        """
        Check printing a stack-located value.
        """
        s = gdb.print_value(expr)
        if isinstance(expected, re.Pattern):
            assert expected.match(s), s
        else:
>           assert s == expected
E           AssertionError: assert '<incomplete type>' == 'arrow::null()'
E             - arrow::null()
E             + <incomplete type>
```

### Component(s)

Continuous Integration, Python

### LINKED ISSUE #36455: [CI][Python] NumPy deprecation warnings in test_cuda.py (test-cuda-python nightly build)
In the [test-cuda-python](https://github.com/ursacomputing/crossbow/actions/runs/5449601863/jobs/9913998035) nightly build, there are a whole set of identical warnings, like:

```
usr/local/lib/python3.8/dist-packages/pyarrow/tests/test_cuda.py::test_copy_from_to_host[1000]
  /usr/local/lib/python3.8/dist-packages/pyarrow/tests/test_cuda.py:359: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 256 to uint8 will fail in the future.
  For the old behavior, usually:
      np.array(value).astype(dtype)`
  will give the desired result (the cast overflows).
    arr[:] = range(size)
```

cc @danepitkin 

(in addition, there are also test failures, but that is due to https://github.com/apache/arrow/issues/36449)

### PR DESCRIPTION
**Pull request by kou**
### Rationale for this change

Python jobs have tests for GDB plugin. We can't use -g1 for GDB plugin because -g1 doesn't provide enough debug information.

### What changes are included in this PR?

Don't use `-g1` for Python jobs.

### Are these changes tested?

Yes.

### Are there any user-facing changes?

No.
* Closes: #36449
* Closes: #36455

### CODE REVIEW

**Comment by pitrou** [comment]
@github-actions crossbow submit -g python

**Comment by kou** [comment]
@github-actions crossbow submit test-cuda-python test-debian-*-python-3 test-ubuntu-*-python-3 test-fedora-*-python-3

**Comment by pitrou** [comment]
Can you integrate this patch to also fix Python warnings?
```diff
diff --git a/python/pyarrow/tests/test_cuda.py b/python/pyarrow/tests/test_cuda.py
index 2ba2f8267..43cd16a3c 100644
--- a/python/pyarrow/tests/test_cuda.py
+++ b/python/pyarrow/tests/test_cuda.py
@@ -349,27 +349,29 @@ def test_HostBuffer(size):
 
 @pytest.mark.parametrize("size", [0, 1, 1000])
 def test_copy_from_to_host(size):
-
     # Create a buffer in host containing range(size)
-    buf = pa.allocate_buffer(size, resizable=True)  # in host
+    dt = np.dtype('uint16')
+    nbytes = size * dt.itemsize
+    buf = pa.allocate_buffer(nbytes, resizable=True)  # in host
     assert isinstance(buf, pa.Buffer)
     assert not isinstance(buf, cuda.CudaBuffer)
-    arr = np.frombuffer(buf, dtype=np.uint8)
+    arr = np.frombuffer(buf, dtype=dt)
     assert arr.size == size
     arr[:] = range(size)
-    arr_ = np.frombuffer(buf, dtype=np.uint8)
+    arr_ = np.frombuffer(buf, dtype=dt)
     np.testing.assert_equal(arr, arr_)
 
-    device_buffer = global_context.new_buffer(size)
+    # Create a device buffer of the same size and copy from host
+    device_buffer = global_context.new_buffer(nbytes)
     assert isinstance(device_buffer, cuda.CudaBuffer)
     assert isinstance(device_buffer, pa.Buffer)
-    assert device_buffer.size == size
+    assert device_buffer.size == nbytes
     assert not device_buffer.is_cpu
+    device_buffer.copy_from_host(buf, position=0, nbytes=nbytes)
 
-    device_buffer.copy_from_host(buf, position=0, nbytes=size)
-
-    buf2 = device_buffer.copy_to_host(position=0, nbytes=size)
-    arr2 = np.frombuffer(buf2, dtype=np.uint8)
+    # Copy back to host and compare contents
+    buf2 = device_buffer.copy_to_host(position=0, nbytes=nbytes)
+    arr2 = np.frombuffer(buf2, dtype=dt)
     np.testing.assert_equal(arr, arr2)
```

**Comment by pitrou** [comment]
@github-actions crossbow submit test-cuda-python

**Review by pitrou — APPROVED** [review]
+1, will merge if CI is green

**Pull request merged**
