### PR TITLE
ARROW-5354: [C++] adding support for simple, allocation-free null arrays

### PR DESCRIPTION
**Pull request by bkietz**
In the case of all elements of an array being null, no buffers whatsoever need to be allocated (similar to NullArray). This is a more extreme case of the optimization which allows the null bitmap buffer to be null if all elements are valid.

This pull also adds a factory for producing lightweight arrays with all null elements.

### CODE REVIEW

**Comment by pitrou** [comment]
One problem with this is that all consumers of arrays now have to test for buffers being non-null. It's easy to forget to do it.

**Comment by bkietz** [comment]
@pitrou yes, so this pull is more of an RFC at this point. I'm not sure this is actually a worthwhile optimization rather than a foot gun. It's worth noting that `Array::IsNull, IsValid` work for any valid array

**Comment by emkornfield** [comment]
I started a thread about this optimization on the ML a little while ago, it's probably worth restarting that thread (or a new one) and getting the Java implementation on board

**Comment by wesm** [comment]
I might be missing something but how does this impact the IPC write path? We allow an all-valid validity bitmap to be omitted but omitting a data buffer (or sending a length-0 one) would seem invalid. Another option of course if to write appropriate 0 bytes for this case

Either way a mailing list discussion is probably merited

**Comment by emkornfield** [comment]
I thought it did impact the write path, but I didn't take a very careful look.  I thought writing our  all null array would output zero length buffers?

**Comment by fsaintjacques** [comment]
I think this is a slippery slope, external consumers (python, other languages) might not deal well with this. I would say close this PR for now.

**Comment by wesm** [comment]
Yeah, I would say that optimizing the all-null case isn't enough of a problem right now to merit the additional complexity. We can revisit sometime in the future

**Comment by wesm** [comment]
Closing this to revisit sometime in the future

**Pull request closed without merging**
