### PR TITLE
ARROW-1240: [JAVA] switch logback to version 1.2.3 to address

### PR DESCRIPTION
**Pull request by mattdarwin**

### CODE REVIEW

**Comment by DremioQA** [comment]
Does shifting to this version cause us to shift to a different SLF4j version? I know there are some incompatibilities between versions.

**Comment by wesm** [comment]
Is that @jacques-n? Seems you are logged in with a different GH account

**Comment by jacques-n** [comment]
Hah! Yeah, it was me. I'm back to being myself now :)

**Comment by mattdarwin** [comment]
Well the regression tests all passed, without any other changes.

But I’ve also proposed upgrading slf4j as a separate PR, since that’s also quite out of date.

**Comment by jacques-n** [comment]
Sorry I wasn't more clear in my question (and slow to respond). We depend heavily on Arrow and also use Logback (the same version as Arrow). I was asking whether the API of logback and slf4j is different between your proposed versions and the current versions. Being a library, we have to be cautious about when we should change cross dependencies. (Definitely think an update makes sense, need to figure out how to proceed.)

**Comment by mattdarwin** [comment]
logback's list of changes report the following non-breaking changes between 1.0.13 and 1.2.3:

- MDC values are no longer inherited by child threads.
- Logback 1.1.4 requires SLF4J version 1.7.16 or later.
- Packaging data (as output in stack traces) is now disabled by default.
- all logback modules require JDK 1.6 instead of previously JDK 1.5

Arrow uses slf4j 1.7.6, and the latest version is 1.7.25. So assuming logbook versions >1.1.4 also require SLF4J 1.7.16 or later, we need to upgrade slf4j.
 I propose to include an slf4j upgrade as part of this change - version 1.7.25 unless anyone suggests otherwise...
[SLF4J release notes ](https://www.slf4j.org/news.html) indicate that changes between 1.7.6 and 1.7.25 appear to be bug fixes only, with no API changes.

**Comment by mattdarwin** [comment]
I had to open a new PR since I deleted the fork for this one.
See #879 , where I have upgrade logback to 1.2.3 and slf4j to 1.7.25

**Pull request closed without merging**
