### PR TITLE
GH-39909: [Java][CI] Update reference to Float16 testing file reference on Testing submodule

### LINKED ISSUE #39909: [Java][CI] Nightly java-jars fails with Arrow Java Dataset test failures
### Describe the bug, including details regarding any error messages, version, and platform.

The java-jars job is failing on main and some Java PRs (https://github.com/ursacomputing/crossbow/actions/runs/7738358594/job/21101948710#step:6:61816) with the following error:
```
Error:  Failures: 
Error:    TestAllTypes.testAllTypesParquet:261->TestDataset.assertParquetFileEquals:124 expected:<...length=2, nullCount=[2], ArrowFieldNode [length=0, nullCount=0], ArrowFieldNode [length=2, nullCount=2], ArrowFieldNode [length=0, nullCount=0], ArrowFieldNode [length=2, nullCount=2], ArrowFieldNode [length=0, nullCount=0], ArrowFieldNode [length=2, nullCount=2], ArrowFieldNode [length=2, nullCount=0]], #buffers=71, buffersLayout=[ArrowBuffer [offset=0, size=1], ArrowBuffer [offset=8, size=1], ArrowBuffer [offset=16, size=1], ArrowBuffer [offset=24, size=2], ArrowBuffer [offset=32, size=1], ArrowBuffer [offset=40, size=4], ArrowBuffer [offset=48, size=1], ArrowBuffer [offset=56, size=8], ArrowBuffer [offset=64, size=1], ArrowBuffer [offset=72, size=16], ArrowBuffer [offset=88, size=1], ArrowBuffer [offset=96, size=2], ArrowBuffer [offset=104, size=1], ArrowBuffer [offset=112, size=4], ArrowBuffer [offset=120, size=1], ArrowBuffer [offset=128, size=8], ArrowBuffer [offset=136, size=1], ArrowBuffer [offset=144, size=16], ArrowBuffer [offset=160, size=1], ArrowBuffer [offset=168, size=8], ArrowBuffer [offset=176, size=1], ArrowBuffer [offset=184, size=16], ArrowBuffer [offset=200, size=1], ArrowBuffer [offset=208, size=12], ArrowBuffer [offset=224, size=1], ArrowBuffer [offset=232, size=1], ArrowBuffer [offset=240, size=12], ArrowBuffer [offset=256, size=1], ArrowBuffer [offset=264, size=1], ArrowBuffer [offset=272, size=12], ArrowBuffer [offset=288, size=1], ArrowBuffer [offset=296, size=1], ArrowBuffer [offset=304, size=12], ArrowBuffer [offset=320, size=1], ArrowBuffer [offset=328, size=1], ArrowBuffer [offset=336, size=2], ArrowBuffer [offset=344, size=1], ArrowBuffer [offset=352, size=8], ArrowBuffer [offset=360, size=1], ArrowBuffer [offset=368, size=8], ArrowBuffer [offset=376, size=1], ArrowBuffer [offset=384, size=16], ArrowBuffer [offset=400, size=1], ArrowBuffer [offset=408, size=16], ArrowBuffer [offset=424, size=1], ArrowBuffer [offset=432, size=16], ArrowBuffer [offset=448, size=1], ArrowBuffer [offset=456, size=16], ArrowBuffer [offset=472, size=1], ArrowBuffer [offset=480, size=16], ArrowBuffer [offset=496, size=1], ArrowBuffer [offset=504, size=16], ArrowBuffer [offset=520, size=1], ArrowBuffer [offset=528, size=32], ArrowBuffer [offset=560, size=1], ArrowBuffer [offset=568, size=32], ArrowBuffer [offset=600, size=1], ArrowBuffer [offset=608, size=12], ArrowBuffer [offset=624, size=0], ArrowBuffer [offset=624, size=0], ArrowBuffer [offset=624, size=1], ArrowBuffer [offset=632, size=12], ArrowBuffer [offset=648, size=0], ArrowBuffer [offset=648, size=0], ArrowBuffer [offset=648, size=1], ArrowBuffer [offset=656, size=12], ArrowBuffer [offset=672, size=0], ArrowBuffer [offset=672, size=0], ArrowBuffer [offset=672, size=1], ArrowBuffer [offset=680, size=1], ArrowBuffer [offset=688], size=8]], closed=f...> but was:<...length=2, nullCount=[1], ArrowFieldNode [length=2, nullCount=2], ArrowFieldNode [length=0, nullCount=0], ArrowFieldNode [length=2, nullCount=2], ArrowFieldNode [length=0, nullCount=0], ArrowFieldNode [length=2, nullCount=2], ArrowFieldNode [length=0, nullCount=0], ArrowFieldNode [length=2, nullCount=2], ArrowFieldNode [length=2, nullCount=0]], #buffers=73, buffersLayout=[ArrowBuffer [offset=0, size=1], ArrowBuffer [offset=8, size=1], ArrowBuffer [offset=16, size=1], ArrowBuffer [offset=24, size=2], ArrowBuffer [offset=32, size=1], ArrowBuffer [offset=40, size=4], ArrowBuffer [offset=48, size=1], ArrowBuffer [offset=56, size=8], ArrowBuffer [offset=64, size=1], ArrowBuffer [offset=72, size=16], ArrowBuffer [offset=88, size=1], ArrowBuffer [offset=96, size=2], ArrowBuffer [offset=104, size=1], ArrowBuffer [offset=112, size=4], ArrowBuffer [offset=120, size=1], ArrowBuffer [offset=128, size=8], ArrowBuffer [offset=136, size=1], ArrowBuffer [offset=144, size=16], ArrowBuffer [offset=160, size=1], ArrowBuffer [offset=168, size=4], ArrowBuffer [offset=176, size=1], ArrowBuffer [offset=184, size=8], ArrowBuffer [offset=192, size=1], ArrowBuffer [offset=200, size=16], ArrowBuffer [offset=216, size=1], ArrowBuffer [offset=224, size=12], ArrowBuffer [offset=240, size=1], ArrowBuffer [offset=248, size=1], ArrowBuffer [offset=256, size=12], ArrowBuffer [offset=272, size=1], ArrowBuffer [offset=280, size=1], ArrowBuffer [offset=288, size=12], ArrowBuffer [offset=304, size=1], ArrowBuffer [offset=312, size=1], ArrowBuffer [offset=320, size=12], ArrowBuffer [offset=336, size=1], ArrowBuffer [offset=344, size=1], ArrowBuffer [offset=352, size=2], ArrowBuffer [offset=360, size=1], ArrowBuffer [offset=368, size=8], ArrowBuffer [offset=376, size=1], ArrowBuffer [offset=384, size=8], ArrowBuffer [offset=392, size=1], ArrowBuffer [offset=400, size=16], ArrowBuffer [offset=416, size=1], ArrowBuffer [offset=424, size=16], ArrowBuffer [offset=440, size=1], ArrowBuffer [offset=448, size=16], ArrowBuffer [offset=464, size=1], ArrowBuffer [offset=472, size=16], ArrowBuffer [offset=488, size=1], ArrowBuffer [offset=496, size=16], ArrowBuffer [offset=512, size=1], ArrowBuffer [offset=520, size=16], ArrowBuffer [offset=536, size=1], ArrowBuffer [offset=544, size=32], ArrowBuffer [offset=576, size=1], ArrowBuffer [offset=584, size=32], ArrowBuffer [offset=616, size=1], ArrowBuffer [offset=624, size=12], ArrowBuffer [offset=640, size=0], ArrowBuffer [offset=640, size=0], ArrowBuffer [offset=640, size=1], ArrowBuffer [offset=648, size=12], ArrowBuffer [offset=664, size=0], ArrowBuffer [offset=664, size=0], ArrowBuffer [offset=664, size=1], ArrowBuffer [offset=672, size=12], ArrowBuffer [offset=688, size=0], ArrowBuffer [offset=688, size=0], ArrowBuffer [offset=688, size=1], ArrowBuffer [offset=696, size=1], ArrowBuffer [offset=704], size=8]], closed=f...>
```

This is failing since yesterday and the only related Java PR merged is: https://github.com/apache/arrow/issues/39680

### Component(s)

Continuous Integration, Java

### PR DESCRIPTION
**Pull request by davisusanibar**
### Rationale for this change

Update reference to Float16 testing file reference on Testing submodule.

### What changes are included in this PR?

Testing submodule. changes.

### Are these changes tested?

Yes

### Are there any user-facing changes?

No
* Closes: #39909

### CODE REVIEW

**Comment by davisusanibar** [comment]
@github-actions crossbow submit java-jars

**Comment by raulcd** [comment]
@github-actions crossbow submit java-jars

**Review by raulcd — APPROVED** [review]
LGTM, @kou do we ran any specific tests when we modify the testing submodule?

**Comment by kou** [comment]
@github-actions crossbow submit -g cpp

**Review by kou — APPROVED** [review]
+1

**Pull request merged**
