### PR TITLE
ARROW-2300: [C++/Python] Integration test for HDFS

### PR DESCRIPTION
**Pull request by kszucs**

### CODE REVIEW

**Comment by kszucs** [comment]
@wesm I could use some hints:

With libhdfs3 it still segfaults when [setting](https://github.com/apache/arrow/blob/master/cpp/src/arrow/io/hdfs.cc#L300) `HdfsPathInfo` string members.

In the [ListDirectory](https://github.com/apache/arrow/blob/master/cpp/src/arrow/io/io-hdfs-test.cc#L279) test case the first [iteration](https://github.com/apache/arrow/blob/master/cpp/src/arrow/io/hdfs.cc#L450) goes well, but afterwards `char*` pointers have bogus addresses. For a single file, the test case passes.

There must be something obvious I can't find. Maybe this [bad_alloc](https://github.com/Pivotal-Data-Attic/attic-c-hdfs-client/blob/36cc257d99919f2b98c998ad300ce660fa90b6a2/src/client/Hdfs.cpp#L1053) handling causes it?

**Comment by wesm** [comment]
Oof, sorry that you've run into this. libhdfs3 2.3.x. on conda-forge introduced an ABI incompatibility, see

https://issues.apache.org/jira/browse/ARROW-1465

In the meantime, you can pin to version 2.2.31 to make the problem go away

**Comment by wesm** [comment]
The discussion of the underlying problem is in https://issues.apache.org/jira/browse/ARROW-1445

**Comment by kszucs** [comment]
Hmm, sooo these are the symptoms of ABI incompatibility. Pinning it, thanks!

**Comment by kszucs** [comment]
Another error happens, but it seems fixable. I'll investigate it tomorrow.

**Comment by kszucs** [comment]
`libhdfs3` works now. Currently I'm adding `libhdfs` too.

**Comment by wesm** [comment]
Thank you @kszucs. I will take this for a spin locally and then merge

**Comment by wesm** [comment]
Checked this out and got this error:

```
~/code/arrow/python/testing  (ARROW-2300)$ ./test_hdfs.sh 
+ docker build -t arrow-hdfs-test -f hdfs/Dockerfile .
Sending build context to Docker daemon  36.86kB
Step 1/6 : FROM cpcloud86/impala:metastore
manifest for cpcloud86/impala:metastore not found
```

**Comment by kszucs** [comment]
Something must went wrong during checkout, because this no longer uses the Impala image.

**Comment by wesm** [comment]
Ok, let me nuke my branch and start over

**Comment by kszucs** [comment]
If I recall correctly a couple of tests are failing, but the setup works correctly.

**Comment by kszucs** [comment]
```
[  FAILED  ] 2 tests, listed below:
[  FAILED  ] TestHadoopFileSystem/0.MultipleClients, where TypeParam = arrow::io::JNIDriver
[  FAILED  ] TestHadoopFileSystem/0.MakeDirectory, where TypeParam = arrow::io::JNIDriver
```

**Comment by kszucs** [comment]
I've fixed the python errors, but the previously pasted`libhdfs` tests fail with `errno: 2`. 
AFAIK `errno` isn't handled precisely in `libhdfs`, I'm using hadoop `2.6.0`

**Comment by kszucs** [comment]
@wesm `errno == 2` [here](https://github.com/apache/arrow/blob/master/cpp/src/arrow/io/hdfs.cc#L438), however the library [exists](https://github.com/apache/arrow/blob/master/cpp/src/arrow/io/io-hdfs-test.cc#L208) - only occurs with `libhdfs`

Should We wrap [hdfsListDirectory](https://github.com/apache/arrow/blob/master/cpp/src/arrow/io/io-hdfs-test.cc#L208) with a closure or store the driver/adapter type in `LibHdfsShim` with the following condition?

```cpp
if (result == nullptr && errno == 2 && this->hdfsExists(fs, path)) {
    // if libhdfs reports errno 2: no such file or directory
    // however the path exists, we set errno to zero
    errno = 0;
}
```

It's a super hacky solution, I don't like it, but can't think of an alternative. Perhaps We should pin a minimal `libhdfs` version - assuming it has been fixed.

**Comment by wesm** [comment]
Let me have a closer look today -- I thought I had run this with Hadoop 2.6 before and didn't hit these issues so

**Comment by wesm** [comment]
@kszucs do you see this?

https://github.com/kszucs/arrow/blob/ARROW-2300/python/testing/hdfs/Dockerfile#L19

The scope of the GitHub issue was to fix `python/testing/test_hdfs.sh`, so we should either fix that or remove it. Can you add instructions how to run the HDFS tests?

**Comment by kszucs** [comment]
Ohh sorry @wesm !

I've ported the hdfs integration tests from `arrow/python/testing` to `arrow/dev/` next to `spark_integration` because it fits more naturally with the `docker-compose` setup. It also has a broader scope because it runs cpp tests too. 
I've planned to port dask integration as well and remove `arrow/python/testing` eventually (the best place would be `arrow/integration` though)

Please use the following command: `arrow/dev/run_docker_compose.sh hdfs_integration`

**Comment by wesm** [comment]
Sweet thanks =)

**Comment by kszucs** [comment]
After We have all of the integration tests under the same roof (dask, spark, hdfs) We can simply just submit them as crossbow tasks (similarly like the build tasks, but defined in a separate `tests.yml`). 
Nightly integration tests would run in the same fashion like the nightly builds.

**Comment by wesm** [comment]
@kszucs I applied your workaround for the errno 2 thing. I fiddled with this a little bit (including setting `errno = 0` before the `hdfsListDirectory` call (which made one of the errors go away, I guess errno was in a bad state from elsewhere) but couldn't get it completely working without the workaround. 

+1. I will merge this once the build completes to make sure I didn't mess up the lint

**Comment by wesm** [comment]
thanks @kszucs!

**Pull request closed without merging**
