### PR TITLE
ARROW-6846: [C++] Fix build failures with GLog enabled

### PR DESCRIPTION
**Pull request by pitrou**

### CODE REVIEW

**Comment by pitrou** [comment]
Willing to merge when green in enable to clear CI failures. @wesm

**Comment by pitrou** [comment]
Looks like some other errors cropped up. I wonder what happened (conda-forge fuckup?).

**Comment by pitrou** [comment]
I don't have time to debug this further.

**Comment by wesm** [comment]
Looking

**Comment by wesm** [comment]
The failure seems to be brought on by https://github.com/conda-forge/ctng-compiler-activation-feedstock/commit/24a695667b5c14dd752f0b4f58078f6500d45b69

**Comment by wesm** [comment]
https://github.com/conda-forge/ctng-compiler-activation-feedstock/pull/3

**Comment by pitrou** [comment]
I've restarted the failed Travis jobs, seems to be getting better.

**Comment by pitrou** [comment]
It seems this PR is not useful anymore.

**Pull request closed without merging**
