### PR TITLE
GH-43204: [CI][Packaging] Apply vcpkg patch to fix Thrift version

### PR DESCRIPTION
**Pull request by raulcd**
### Rationale for this change

Currently our java-jars and some wheels jobs are failing due to downloading a wrong version of Apache Thrift based on the 0.20.0 branch instead of the tag. That branch contains a new commit that makes the sha validation to fail.

### What changes are included in this PR?

Apply the Thrift patch that was applied on vcpkg here: https://github.com/microsoft/vcpkg/pull/39787

### Are these changes tested?
Via archery

### Are there any user-facing changes?
No
* GitHub Issue: #43204

### CODE REVIEW

**Comment by raulcd** [comment]
@github-actions crossbow submit wheels-* java-jars

**Comment by raulcd** [comment]
@github-actions crossbow submit -g wheel java-jars

**Comment by raulcd** [comment]
@github-actions crossbow submit java-jars

**Comment by raulcd** [comment]
@github-actions crossbow submit wheel-manylinux-2014-cp310-arm64

**Comment by raulcd** [comment]
@github-actions crossbow submit -g wheel

**Review by kou — APPROVED** [review]
+1

**Comment by jonkeane** [comment]
I was diagnosing some crossbow failures, and noticed that these started failing again with the same issue. We seem to be downloading from https://github.com/apache/thrift/archive/0.20.0.tar.gz which has the different hash. But I can't figure out _why_ we might be doing that (again?). This patch looks good, and should be specifying the right URL.

The only thing I can think of now is that maybe vcpkg is using a cached version of the download? https://github.com/microsoft/vcpkg/blob/cacf5994341f27e9a14a7b8724b0634b138ecb30/scripts/cmake/vcpkg_from_github.cmake#L93-L94 doesn't have `ALWAYS_REDOWNLOAD` but I can't explain how the old version would have gotten there, so this seems unlikely.

**Pull request merged**
