### PR TITLE
ARROW-7333: [CI][Rust] Remove duplicated nightly job

### PR DESCRIPTION
**Pull request by kou**
We run the same test on each push with GitHub Actions.

### CODE REVIEW

**Comment by kou** [comment]
@andygrove @sunchao @nevi-me Do we want to run test with both nightly-2019-09-25 and nightly-2019-11-14? Is it enough that we run test only with nightly-2019-11-14?

**Comment by paddyhoran** [comment]
I would say just nightly-2019-11-14, hopefully we can get back on stable at some stage.

**Comment by nevi-me** [comment]
Also prefer one nightly

**Review by nevi-me — APPROVED** [review]

**Comment by nevi-me** [comment]
@kou can we piggy-back off this PR to remove the AppVeyor Rust job, or should I create a separate PR?

**Comment by kou** [comment]
Sure. :)
It's trivial. We don't need additional JIRA issue.

Done.

**Review by kszucs — APPROVED** [review]

**Pull request closed without merging**
