### PR TITLE
ARROW-3474: [GLib] Extend gparquet API with get_schema and read_column

### PR DESCRIPTION
**Pull request by rostyboost**
So we can read individual columns without loading the whole parquet file in memory, we need to surface the getSchema and ReadColumn functions of parquet-cpp to the parquet glib API.

Originally submitted [here](https://github.com/red-data-tools/parquet-glib/pull/2) before the inclusion of parquet-glib to Arrow.

cc @kou

### CODE REVIEW

**Review by kou — CHANGES_REQUESTED** [review]
Thanks!
Can you check my comments?

**Review by rostyboost — COMMENTED** [review]
Thanks @kou , I addressed your comments and added a unit test.

**Comment by kou** [comment]
Thanks!
I noticed that `garrow_column_new_array()` has a bug that doesn't refer arguments. I'll push fix for the problem to this branch and merge this pull request. Please wait a while.

**Review by kou — APPROVED** [review]

**Comment by kou** [comment]
CI is passed. I'll merge this.

I noticed that we can't use passed schema with `ReadColumn()`. Because the schema may not have all columns. So I changed to read the target field in `gparquet_arrow_file_reader_read_column()`.

I added one more API to `gparquet_arrow_file_reader_select_schema()` that accepts column indices. We can also add `gparquet_arrow_file_reader_select_table()` that also accepts column indices.

I cleaned up tests. We can add more tests easily.

**Comment by kou** [comment]
I've merged. Thanks @rostyboost!

**Pull request closed without merging**
