### PR TITLE
ARROW-957: [Doc] Add HDFS and Windows documents to doxygen output

### PR DESCRIPTION
**Pull request by xhochy**

### CODE REVIEW

**Review by wesm — APPROVED** [review]
+1

**Comment by wesm** [comment]
Deployed. Some formatting is off http://arrow.apache.org/docs/cpp/md__windows.html, we can work on this

**Comment by xhochy** [comment]
@wesm ah this could be because Markdown support in Doxygen is quite new. Locally I use the latest version from homebrew.

**Comment by tkelman** [comment]
There are a few now-dead links that need updating for this

**Comment by wesm** [comment]
Could you submit a patch?

**Comment by tkelman** [comment]
when not on mobile, sure. the mirroring all gets handled?

**Pull request closed without merging**
