### PR TITLE
ARROW-389: Python: Write Parquet files to pyarrow.io.NativeFile objects

### PR DESCRIPTION
**Pull request by xhochy**

### CODE REVIEW

**Comment by xhochy** [comment]
Depends on https://github.com/apache/parquet-cpp/pull/196

**Comment by wesm** [comment]
Cool! Will test this out after PARQUET-782 is in

**Comment by wesm** [comment]
+1 (merge on green build)

**Comment by wesm** [comment]
hm, I wonder what happened in the linux build?

**Comment by xhochy** [comment]
`./dev/release/run-rat.sh: line 27: java: command not found`

I wonder why somehow `java` is not available anymore in the image...

**Comment by xhochy** [comment]
Seemed to be a Travis problem, repushed to get a new build.

**Comment by xhochy** [comment]
Image seems still broken. Waiting a bit for the fix.

**Comment by wesm** [comment]
Looks like Travis changed their Trusty images yesterday

https://docs.travis-ci.com/user/build-environment-updates/2016-12-01/

> Include at least one JDK and the jdk_switcher tool in all Trusty stacks.

Hm, not sure they succeeded

**Comment by xhochy** [comment]
@wesm switched image back for now to `group: deprecated`. This should unbreak the builds and wants Travis managed to get their image fixed, we can remove that again.

Seems like everything is working https://travis-ci.org/xhochy/arrow/builds/180756667

**Comment by wesm** [comment]
Lovely. Is there an issue tracker for Travis where we can complain about this?

**Comment by wesm** [comment]
https://twitter.com/traviscistatus/status/804724820709691392

**Comment by wesm** [comment]
+1

**Pull request closed without merging**
