### PR TITLE
ARROW-5989: [C++] Accommodate openjdk-8 path search prefix

### PR DESCRIPTION
**Pull request by efiop**

### CODE REVIEW

**Comment by kou** [comment]
Could you open an issue on JIRA? https://issues.apache.org/jira/projects/ARROW/issues/
And could you use `ARROW-${JIRA_ISSUE_ID}: [C++] ${SUMMARY}` format for pull request title?

See also: https://arrow.apache.org/docs/developers/contributing.html#how-to-contribute-patches

**Comment by efiop** [comment]
Thanks for the heads up @kuo ! Created the issue and formatted the PR header. Please take a look. I also see that 2 workers failed in https://travis-ci.org/apache/arrow/builds/560726427utm_source=github_status&utm_medium=notification, but it doesn't seem to be related to my patch. Or is it?

**Comment by emkornfield** [comment]
restarted the failed travis, jobs, I think they are unrelated as well.

**Comment by emkornfield** [comment]
It looks like you have a lint error:
/home/travis/build/apache/arrow/cpp/src/arrow/io/hdfs-internal.cc:166:  Line ends in whitespace.  Consider deleting these extra spaces. 

"make format" or "ninja format" should fix this.

**Comment by efiop** [comment]
@emkornfield Fixed formatting. Thanks for the heads up!

**Comment by efiop** [comment]
This time travis is passing fine, but appveyor failed  ¯\_(ツ)_/¯ The failure seems to be unrelated once again.

**Review by kou — APPROVED** [review]
It's unrelated.
I'll merge this.

**Comment by efiop** [comment]
Thank you @kou ! Sorry for bothering, but when can we expect a new release with this patch? openjdk-8 has been around for quite a while, and without this patch it is quite hard to use pyarrow on ubuntu, especially for unsuspecting users of projects that use pyarrow as a dependency.

**Comment by kou** [comment]
0.14.1 isn't released yet. It's just RC for now.
It'll be released in a few days.

This patch will be included into the next release after 0.14.1. It'll be occurred in a few months.

You will be able to `JAVA_HOME` environment variable until this patch is included into our release.

**Comment by efiop** [comment]
@kou Maybe I could submit a backport for 0.14.1 rc so it is included into official 0.14.1?

**Comment by kou** [comment]
It's late...
See also: https://lists.apache.org/thread.html/e343ca0aac17b00cb8edd8c48c10698cba7e244face81e5b9c065474@%3Cdev.arrow.apache.org%3E

**Comment by efiop** [comment]
@kou Got it. Thanks!

**Pull request closed without merging**
