### PR TITLE
ARROW-7466: [CI][Java] Fix gandiva-jar-osx nightly build failure

### PR DESCRIPTION
**Pull request by kszucs**

### CODE REVIEW

**Comment by kszucs** [comment]
@ursabot crossbow submit gandiva-jar-osx

**Comment by kszucs** [comment]
[AMD64 Conda Crossbow Submit (#88863)](https://ci.ursalabs.org/#builders/98/builds/493) builder has been succeeded.

Revision: 2a2d7c378b8faa96b2a420a12b7745af9c827d6e

Submitted crossbow builds: [ursa-labs/crossbow @ ursabot-476](https://github.com/ursa-labs/crossbow/branches/all?query=ursabot-476)

|Task|Status|
|----|------|
|gandiva-jar-osx|[TravisCI](https://travis-ci.org/ursa-labs/crossbow/branches)|

**Comment by kszucs** [comment]
@ursabot crossbow submit gandiva-jar-osx

**Comment by kszucs** [comment]
[AMD64 Conda Crossbow Submit (#88864)](https://ci.ursalabs.org/#builders/98/builds/494) builder has been succeeded.

Revision: 6929f3d2c703059e7cae357177afffe03d9ea32e

Submitted crossbow builds: [ursa-labs/crossbow @ ursabot-477](https://github.com/ursa-labs/crossbow/branches/all?query=ursabot-477)

|Task|Status|
|----|------|
|gandiva-jar-osx|[TravisCI](https://travis-ci.org/ursa-labs/crossbow/branches)|

**Comment by kszucs** [comment]
@ursabot crossbow submit gandiva-jar-osx

**Comment by kszucs** [comment]
[AMD64 Conda Crossbow Submit (#88865)](https://ci.ursalabs.org/#builders/98/builds/495) builder has been succeeded.

Revision: 7b054ecabf129ea267de675b5ee13f18b8c9c7f3

Submitted crossbow builds: [ursa-labs/crossbow @ ursabot-478](https://github.com/ursa-labs/crossbow/branches/all?query=ursabot-478)

|Task|Status|
|----|------|
|gandiva-jar-osx|[TravisCI](https://travis-ci.org/ursa-labs/crossbow/branches)|

**Comment by kszucs** [comment]
@ursabot crossbow submit gandiva-jar-osx

**Comment by kszucs** [comment]
[AMD64 Conda Crossbow Submit (#88866)](https://ci.ursalabs.org/#builders/98/builds/496) builder has been succeeded.

Revision: 6f1beb68515c01633bf8b72bab0a6e47bfc5b556

Submitted crossbow builds: [ursa-labs/crossbow @ ursabot-479](https://github.com/ursa-labs/crossbow/branches/all?query=ursabot-479)

|Task|Status|
|----|------|
|gandiva-jar-osx|[TravisCI](https://travis-ci.org/ursa-labs/crossbow/branches)|

**Comment by kszucs** [comment]
@ursabot crossbow submit gandiva-jar-osx

**Comment by kszucs** [comment]
[AMD64 Conda Crossbow Submit (#88867)](https://ci.ursalabs.org/#builders/98/builds/497) builder has been succeeded.

Revision: b50865e70cc4fbf162382439afafe65e07d7f3d2

Submitted crossbow builds: [ursa-labs/crossbow @ ursabot-480](https://github.com/ursa-labs/crossbow/branches/all?query=ursabot-480)

|Task|Status|
|----|------|
|gandiva-jar-osx|[TravisCI](https://travis-ci.org/ursa-labs/crossbow/branches)|

**Comment by kszucs** [comment]
@ursabot crossbow submit gandiva-jar-osx

**Comment by kszucs** [comment]
[AMD64 Conda Crossbow Submit (#88868)](https://ci.ursalabs.org/#builders/98/builds/498) builder has been succeeded.

Revision: 2131836b6fe29b3eae2e5c237e0eaae25db97b98

Submitted crossbow builds: [ursa-labs/crossbow @ ursabot-481](https://github.com/ursa-labs/crossbow/branches/all?query=ursabot-481)

|Task|Status|
|----|------|
|gandiva-jar-osx|[TravisCI](https://travis-ci.org/ursa-labs/crossbow/branches)|

**Comment by kszucs** [comment]
@ursabot crossbow submit gandiva-jar-osx

**Comment by kszucs** [comment]
[AMD64 Conda Crossbow Submit (#88869)](https://ci.ursalabs.org/#builders/98/builds/499) builder has been succeeded.

Revision: 421142dba8143b57b3d545a236b3c317eb22bb36

Submitted crossbow builds: [ursa-labs/crossbow @ ursabot-482](https://github.com/ursa-labs/crossbow/branches/all?query=ursabot-482)

|Task|Status|
|----|------|
|gandiva-jar-osx|[TravisCI](https://travis-ci.org/ursa-labs/crossbow/branches)|

**Comment by kszucs** [comment]
@ursabot crossbow submit gandiva-jar-osx

**Comment by kszucs** [comment]
[AMD64 Conda Crossbow Submit (#88870)](https://ci.ursalabs.org/#builders/98/builds/500) builder has been succeeded.

Revision: d956297c74db64a359d6febc3ed98e07d96a47c6

Submitted crossbow builds: [ursa-labs/crossbow @ ursabot-483](https://github.com/ursa-labs/crossbow/branches/all?query=ursabot-483)

|Task|Status|
|----|------|
|gandiva-jar-osx|[TravisCI](https://travis-ci.org/ursa-labs/crossbow/branches)|

**Comment by kszucs** [comment]
@ursabot crossbow submit gandiva-jar-osx

**Comment by kszucs** [comment]
[AMD64 Conda Crossbow Submit (#88991)](https://ci.ursalabs.org/#builders/98/builds/504) builder has been succeeded.

Revision: d50b8c8975f5d7a34f291e62742640ac9e92218c

Submitted crossbow builds: [ursa-labs/crossbow @ ursabot-484](https://github.com/ursa-labs/crossbow/branches/all?query=ursabot-484)

|Task|Status|
|----|------|
|gandiva-jar-osx|[TravisCI](https://travis-ci.org/ursa-labs/crossbow/branches)|

**Comment by fsaintjacques** [comment]
Link **https://github.com/ursa-labs/crossbow/releases/tag/ursabot-484-travis-gandiva-jar-osx**

**Pull request closed without merging**
