### PR TITLE
ARROW-5109: [Go] implement reading binary/string arrays from Arrow file

### PR DESCRIPTION
**Pull request by sbinet**

### CODE REVIEW

**Comment by sbinet** [comment]
PTAL @stuartcarnie @alexandreyc @nickpoorman

**Comment by alexandreyc** [comment]
I still need to fully review ARROW-5108 before doing this one, but I will.

**Comment by sbinet** [comment]
you mean https://github.com/apache/arrow/pull/4114 ?
oops, already collected it... my bad.

**Review by stuartcarnie — APPROVED** [review]
LGTM

**Pull request closed without merging**
