### PR TITLE
ARROW-16861: [Rust][Integration] Enable IP compression for Rust

### PR DESCRIPTION
**Pull request by liukun4515**
close [ARROW-16861](https://issues.apache.org/jira/browse/ARROW-16861)

upstream pr: https://github.com/apache/arrow-rs/pull/2462, re https://github.com/apache/arrow-rs/issues/1907

### CODE REVIEW

**Comment by liukun4515** [comment]
@alamb  PTAL

**Comment by alamb** [comment]
https://github.com/apache/arrow/runs/7854025490?check_suite_focus=true seems to have failed. 

I was thinking it may be related to running before https://github.com/apache/arrow-rs/pull/2462  was merged. To confirm/deny this hypothesis I have retriggered the run

**Comment by alamb** [comment]
https://github.com/apache/arrow/runs/7854025490?check_suite_focus=true seems to have failed. 

I was thinking it may be related to running before https://github.com/apache/arrow-rs/pull/2462  was merged. To confirm/deny this hypothesis I have retriggered the run

**Comment by alamb** [comment]
https://github.com/apache/arrow/runs/7854025490?check_suite_focus=true seems to have failed. 

I was thinking it may be related to running before https://github.com/apache/arrow-rs/pull/2462  was merged. To confirm/deny this hypothesis I have retriggered the run

**Comment by liukun4515** [comment]
Maybe it can be merged. @alamb

**Comment by alamb** [comment]
Indeed the tests are passing. I will merge this (via the merge.py script)

**Review by alamb — APPROVED** [review]

**Comment by alamb** [comment]
🤔  I am having trouble merging in 

```shell
(arrow_dev) alamb@MacBook-Pro-8:~/Software/arrow$ ./dev/merge_arrow_pr.py 13893
ARROW_HOME = /Users/alamb/Software/arrow/dev
PROJECT_NAME = arrow

=== Pull Request #13893 ===
title	ARROW-16861: [Rust][Integration] Enable IP compression for Rust
source	liukun4515/enable_coompression_it
target	master
url	https://api.github.com/repos/apache/arrow/pulls/13893
=== JIRA ARROW-16861 ===
Summary		[Rust] enable integration test for 2.0.0 compression for rust version
Assignee	Andrew Lamb
Components	Rust
Status		In Progress
URL		https://issues.apache.org/jira/browse/ARROW-16861

Proceed with merging pull request #13893? (y/n): y
Author 1: liukun4515 <liukun@apache.org>
Traceback (most recent call last):
  File "/Users/alamb/Software/arrow/./dev/merge_arrow_pr.py", line 600, in <module>
    cli()
  File "/Users/alamb/Software/arrow/./dev/merge_arrow_pr.py", line 580, in cli
    pr.merge()
  File "/Users/alamb/Software/arrow/./dev/merge_arrow_pr.py", line 459, in merge
    self.cmd.fail(f'Failed to merge pull request: {message}')
  File "/Users/alamb/Software/arrow/./dev/merge_arrow_pr.py", line 306, in fail
    raise Exception(msg)
Exception: Failed to merge pull request: Not Found: https://api.github.com/repos/apache/arrow/pulls/13893/merge
```

I will try again later today to see if it is some sort of transient error

**Comment by alamb** [comment]
Well, the merge script is still not working, so I will merge this PR in manually and close the JIRA

**Pull request merged**
