### PR TITLE
ARROW-14684: [CI][C++] Use aws-sdk-cpp package on macOS

### PR DESCRIPTION
**Pull request by kou**

### CODE REVIEW

**Comment by nealrichardson** [comment]
Do we have any tests, or CI log output, that confirm that this change is doing what is expected?

**Comment by kou** [comment]
Here:

https://github.com/apache/arrow/runs/4186481073?check_suite_focus=true#step:5:209

> -- Found AWS SDK libraries: aws-cpp-sdk-config;aws-cpp-sdk-transfer;aws-cpp-sdk-identity-management;aws-cpp-sdk-cognito-identity;aws-cpp-sdk-sts;aws-cpp-sdk-s3;aws-cpp-sdk-core

And CI time becomes shorter:

* master: 42m 27s: https://github.com/apache/arrow/runs/4172070713?check_suite_focus=true
* This branch:  25m 3s: https://github.com/apache/arrow/runs/4186481073?check_suite_focus=true

**Comment by kou** [comment]
@github-actions crossbow homebrew-cpp

**Comment by kou** [comment]
@github-actions crossbow submit homebrew-cpp

**Comment by kou** [comment]
@github-actions crossbow submit homebrew-cpp

**Comment by kou** [comment]
+1

**Pull request closed without merging**
