### PR TITLE
ARROW-3032: [C++] Clean up Numpy-related headers

### PR DESCRIPTION
**Pull request by pitrou**
Remove some unused functions

### CODE REVIEW

**Comment by wesm** [comment]
Hmm. We've got

numpy_to_arrow.h
numpy_convert.h
numpy-internal.h

Let me see if I can simplify this situation

**Comment by pitrou** [comment]
Right. When I looked at them, though, I wasn't convinced how to merge them, as it seems they cater to different topics.

**Comment by wesm** [comment]
Fair enough. OK, let's leave further simplification as Won't Fix

**Review by wesm — APPROVED** [review]
+1. Travis build https://travis-ci.org/pitrou/arrow/builds/560041983

**Pull request closed without merging**
