### PR TITLE
PARQUET-1846: [C++] Remove deprecated IO classes

### PR DESCRIPTION
**Pull request by pitrou**

### CODE REVIEW

**Comment by emkornfield** [comment]
LGTM, not at a computer I can merge, but feel free to.  Thanks for the cleanup.

**Comment by pitrou** [comment]
Not necessarily (though they have less features, e.g. no async IO), but there was no advantage in using them either.

**Comment by muyangren123456** [comment]
Thank you for your answer.
And I have another question, does arrow in the c++ environment support reading or writing ascii-encoded data? If so, through which interface is it implemented?

**Comment by pitrou** [comment]
Arrow IO is binary, it does not care about text encoding.
Also, please direct questions to the mailing-list: https://arrow.apache.org/community/

**Pull request closed without merging**
