### PR TITLE
ARROW-331: [Doc] Add statement about Python 2.7 compatibility

### PR DESCRIPTION
**Pull request by pitrou**

### CODE REVIEW

**Review by wesm — APPROVED** [review]
+1

**Comment by pitrou** [comment]
Hmm, it seems doc changes don't trigger any Travis job. Do we have a JIRA for that already?

**Review by xhochy — APPROVED** [review]
+1, LGTM

**Comment by wesm** [comment]
@pitrou see https://github.com/apache/arrow/blob/master/.travis.yml#L162. If the job isn't run (aside from github webhook flakiness) let's open an issue to investigate

**Comment by pitrou** [comment]
I think I found the issue (see latest changes in PR).

**Comment by wesm** [comment]
Ah, indeed, thank you for fixing that

**Pull request closed without merging**
