### PR TITLE
ARROW-10852 [C++] AssertTablesEqual(verbose=true) segfaults if the le…

### PR DESCRIPTION
**Pull request by westonpace**
…ft array has more rows

* Extracted printing logic to its own method (PrintDiff) so a failure case could be tested without triggering assert.

* If the arrays are unequal then the print method returns a message stating as much and MultipleChunkIterator is unused.

### CODE REVIEW

**Review by bkietz — APPROVED** [review]
This looks good to me.

The proper solution would be to extend `Diff` with support for chunked arrays. Currently a diff between `[1, 2], [4, 5, 6]` and `[1, 2], [3, 4, 5, 6]` will simply report the different lengths rather than showing the diff, which would be fairly meanginful in this case. Additionally, when requiring chunk layouts to be equal the diffs can be very messy since it proceeds chunkwise. This need not be addressed in this PR, but please add a follow up JIRA

**Review by bkietz — CHANGES_REQUESTED** [review]
Oh, looks like you need to run clang-format https://github.com/apache/arrow/pull/8922/checks?check_run_id=1556182201#step:7:1382

**Comment by bkietz** [comment]
mingw failures are due a known bug: https://issues.apache.org/jira/browse/ARROW-10896

**Comment by westonpace** [comment]
https://issues.apache.org/jira/browse/ARROW-10922

> This looks good to me.
> 
> The proper solution would be to extend `Diff` with support for chunked arrays. Currently a diff between `[1, 2], [4, 5, 6]` and `[1, 2], [3, 4, 5, 6]` will simply report the different lengths rather than showing the diff, which would be fairly meanginful in this case. Additionally, when requiring chunk layouts to be equal the diffs can be very messy since it proceeds chunkwise. This need not be addressed in this PR, but please add a follow up JIRA

**Pull request closed without merging**
