### PR TITLE
ARROW-7634: [Python] Run pyarrow.dataset tests on Appveyor + fix failures to parse Windows file paths

### PR DESCRIPTION
**Pull request by jorisvandenbossche**

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
Starting with trying to get the failure on Appveyor, will afterwards look into a fix for the tests.

**Review by pitrou — CHANGES_REQUESTED** [review]
You will have to enable it in C++ too.
And since we are there, can you explicitly enable `ARROW_CSV` as well?

**Comment by jorisvandenbossche** [comment]
> You will have to enable it in C++ too.

I will do that for explicitness, but it is not needed I think (it is already built as a consequence of building with python)

**Comment by jorisvandenbossche** [comment]
@ursabot crossbow submit conda-win-vs2015-py37

**Comment by kszucs** [comment]
[AMD64 Conda Crossbow Submit (#87540)](https://ci.ursalabs.org/#builders/98/builds/451) builder has been succeeded.

Revision: 6d0d88a3e11db5349e83966c84cc360b54e37e79

Submitted crossbow builds: [ursa-labs/crossbow @ ursabot-444](https://github.com/ursa-labs/crossbow/branches/all?query=ursabot-444)

|Task|Status|
|----|------|
|conda-win-vs2015-py37|[Azure](https://dev.azure.com/ursa-labs/crossbow/_build/latest?definitionId=1&branchName=ursabot-444-azure-conda-win-vs2015-py37)|

**Comment by kszucs** [comment]
@jorisvandenbossche one of the tests cases is failing

**Comment by pitrou** [comment]
It strikes me that C++ dataset tests are currently not built on Windows. Can you try to enable them?

**Comment by pitrou** [comment]
(see `cpp/src/arrow/dataset/CMakeLists.txt`)

**Comment by jorisvandenbossche** [comment]
It seems that the dataset tests don't compile on Windows right now

**Comment by nealrichardson** [comment]
After I merge https://github.com/apache/arrow/pull/6257 I'll rebase and see if we get a passing build.

**Comment by nealrichardson** [comment]
@ursabot crossbow submit conda-win-vs2015-py37

**Comment by kszucs** [comment]
[AMD64 Conda Crossbow Submit (#88051)](https://ci.ursalabs.org/#builders/98/builds/460) builder has been succeeded.

Revision: e2360a6c689a1e5072ba7d3c8ba7240d5d6feb17

Submitted crossbow builds: [ursa-labs/crossbow @ ursabot-451](https://github.com/ursa-labs/crossbow/branches/all?query=ursabot-451)

|Task|Status|
|----|------|
|conda-win-vs2015-py37|[Azure](https://dev.azure.com/ursa-labs/crossbow/_build/latest?definitionId=1&branchName=ursabot-451-azure-conda-win-vs2015-py37)|

**Comment by jorisvandenbossche** [comment]
This is still failing on windows (1 test). I don't have the time myself to try to fix it today (and likely not tomorrow as well). Would we be fine with skipping that 1 test for windows for now?

**Comment by kszucs** [comment]
cc @pitrou

**Comment by nealrichardson** [comment]
Failure is https://dev.azure.com/ursa-labs/crossbow/_build/results?buildId=5431&view=logs&j=4c86bc1b-1091-5192-4404-c74dfaad23e7&t=ec99a26b-0264-5e86-36fb-9cfd0ca0f9f3&l=3597 (or https://ci.appveyor.com/project/ApacheSoftwareFoundation/arrow/builds/30316993/job/y4secmccsm6v5wud#L2186, same error)

Which is not exactly a file path thing, it's asserting the schemas are equal. That's odd.

**Comment by nealrichardson** [comment]
Oh I see it now: the hive partitioning ("part" in the path segments) isn't being detected.

**Comment by jorisvandenbossche** [comment]
It's still the same failure as before I rebased (before the patch of @pitrou to FileSystemFromUri), which is somewhat expected. From the discussion I think we thought the issue is coming from passing a base path path with backslashes to GetTargetStats, which is then leading to backslashes being used in the crawled file paths.

**Comment by kszucs** [comment]
@jorisvandenbossche so we have a third issue, namely the partition discovery failed with windows paths?

**Comment by jorisvandenbossche** [comment]
Not sure what you mean with "third", but it's still the same issue as we [discussed](https://ursalabs.zulipchat.com/#narrow/stream/205864-datasets/topic/python-windows/near/186267196) a few days ago (indeed partition discovery is not working with windows path, presumably because the path splitting doesn't work)

**Comment by kszucs** [comment]
I've read about about two issues :) 

> Not sure what you mean with "third", but it's still the same issue as we [discussed](https://ursalabs.zulipchat.com/#narrow/stream/205864-datasets/topic/python-windows/near/186267196) a few days ago (indeed partition discovery is not working with windows path, presumably because the path splitting doesn't work)
I've read about two distinct issues.

I'm going to merge, but I suppose we'll need to have a ticket about the real partition discovery issue.

**Comment by kszucs** [comment]
Created a ticket https://issues.apache.org/jira/browse/ARROW-7680

**Review by kszucs — APPROVED** [review]
Thanks @jorisvandenbossche!

**Pull request closed without merging**
