### PR TITLE
ARROW-7877: [Packaging] Fix crossbow deployment to github artifacts

### PR DESCRIPTION
**Pull request by kszucs**

### CODE REVIEW

**Comment by kszucs** [comment]
@ursabot crossbow submit -g nightly

**Comment by kszucs** [comment]
@ursabot crossbow submit -g nightly

**Comment by kszucs** [comment]
@ursabot crossbow submit -g conda -g wheel -g linux

**Comment by kszucs** [comment]
@ursabot crossbow submit -g conda -g wheel -g linux

**Comment by kszucs** [comment]
@ursabot crossbow submit -g conda -g wheel -g linux

**Comment by kszucs** [comment]
@ursabot crossbow submit -g conda -g wheel -g linux

**Comment by kszucs** [comment]
@ursabot crossbow submit -g conda -g wheel -g linux

**Comment by kszucs** [comment]
@ursabot crossbow submit -g conda -g wheel -g linux

**Comment by kszucs** [comment]
@ursabot crossbow submit -g conda -g wheel -g linux

**Comment by kszucs** [comment]
@ursabot crossbow submit -g conda -g wheel -g linux

**Comment by kszucs** [comment]
@ursabot crossbow submit -g conda -g wheel -g linux

**Review by kszucs — COMMENTED** [review]
+1

The python 3.5 wheel failures are caused by https://issues.apache.org/jira/browse/ARROW-7936

**Comment by wesm** [comment]
This doesn't look like it was fun to work out, but seems like this will mean less flaky builds going forward =)

**Pull request closed without merging**
