### PR TITLE
PARQUET-1471: [C++] TypedStatistics<T>::UpdateSpaced reads out of bounds value when there are more definition levels than spaced values

### PR DESCRIPTION
**Pull request by wesm**
This bug arose in https://github.com/apache/arrow/pull/3074 as a result of random data changing

### CODE REVIEW

**Comment by pitrou** [comment]
A weird error on AppVeyor:
```
c:\projects\arrow\cpp\src\parquet\arrow/test-util.h(25): fatal error C1014: too many include files: depth = 1024
```

Is there a recursive inclusion somewhere?

**Comment by pitrou** [comment]
Perhaps we want to add include guards to `test-util.h`.

**Comment by wesm** [comment]
Apparently so. Will fix.

**Comment by wesm** [comment]
Please feel free to push small fixes directly to my branches, especially as I'm 7 hours behind you :)

**Comment by wesm** [comment]
There must be some other problems that resulted from that missing include guard. Firing up my Windows box...

**Pull request closed without merging**
