### PR TITLE
ARROW-6948: [Rust] [Parquet] Fix boolean array in arrow reader.

### PR DESCRIPTION
**Pull request by liurenjie1024**

### CODE REVIEW

**Comment by liurenjie1024** [comment]
@andygrove @nevi-me @andygrove Please help to review.

**Review by nevi-me — APPROVED** [review]
LGTM

**Comment by nevi-me** [comment]
Hey @liurenjie1024, is this blocking any other work you're doing? If so, I'm happy to merge it now instead of waiting for another reviewer.

**Comment by liurenjie1024** [comment]
@nevi-me  No, but I would like to see it get merged.

**Review by paddyhoran — APPROVED** [review]
LGTM

**Comment by paddyhoran** [comment]
Sorry I can't merge this from the laptop I'm on today.

**Pull request closed without merging**
