### PR TITLE
ARROW-4947: [Flight/C++] Remove redundant schema parameter to Flight client DoGet

### PR DESCRIPTION
**Pull request by ghost**
Not a high priority for review - fine to land for 0.14

### CODE REVIEW

**Comment by pitrou** [comment]
It seems desirable for this to land in 0.13.0 - the sooner we fix the API the better -, but you should first fix the CI failures.

**Comment by wesm** [comment]
Flight isn't building on Windows yet and we won't ship it in the wheels for 0.13 so the API can be highly subject to change right now

**Review by pitrou — APPROVED** [review]
LGTM

**Comment by pitrou** [comment]
Rebased.

**Pull request closed without merging**
