### PR TITLE
PARQUET-1525: [C++] remove dependency on getopt in parquet tools

### PR DESCRIPTION
**Pull request by rip-nsk**

### CODE REVIEW

**Comment by rip-nsk** [comment]
getopt.h is not portable header.
with this fix parquet tools can be built on windows.

**Comment by emkornfield** [comment]
gflags might be a slightly cleaner way of accomplishing this, but given the small size of the option set it might not be worth the effort to incorporate it (and it might have build issues on windows).  If this makes the tools buildable on windows is there a follow-up JIRA to add parquet tools to CI for windows to catch regressions (also, a committer would probably know better, but this might be better tracked as a parquet jira issue instead of arrow jira issue)?

**Review by pitrou — CHANGES_REQUESTED** [review]
This looks fine to me on the principle, but can you file this issue as a JIRA Parquet issue, rather than Arrow? Thank you!

**Comment by rip-nsk** [comment]
Next time I'll use Parquet's JIRA. (I thought they were merged)

**Comment by wesm** [comment]
@rip-nsk the _codebases_ are merged, but Parquet still exists as a distinct Apache project

**Comment by emkornfield** [comment]
@rip-nsk I created https://issues.apache.org/jira/browse/PARQUET-1524 for this.  I don't have the ability to assign it to you though.

**Review by wesm — APPROVED** [review]
+1. Thanks @rip-nsk!

**Pull request closed without merging**
