### PR TITLE
GH-44277: [CI] Use Miniforge instead of Mambaforge

### PR DESCRIPTION
**Pull request by pitrou**
Mambaforge is being deprecated upstream in favor of Miniforge: https://conda-forge.org/news/2024/07/29/sunsetting-mambaforge/

* GitHub Issue: #44277

### CODE REVIEW

**Comment by pitrou** [comment]
@github-actions crossbow submit -g cpp -g python

**Comment by raulcd** [comment]
We haven't been testing the `conda-xxx` jobs in a while as those are not up to date with upstream so those are not expected to work. I think we should take a decision whether we just remove them and let upstream conda deal with possible issues or someone takes de effort to update them.

**Comment by pitrou** [comment]
Agreed, I didn't think they were in such a bad state.

**Comment by pitrou** [comment]
@raulcd Is this PR ok to you?

**Comment by raulcd** [comment]
@githbu-actions crossbow submit verify-rc-source-java-linux-conda-latest-amd64

**Review by raulcd — APPROVED** [review]
I've validated locally some of the jobs forcing to rebuild (not caching intermediate docker) and works as expected. I'll wait for the archery job to finish before merging

**Pull request merged**
