### PR TITLE
ARROW-2335: [Go] move README one directory higher

### PR DESCRIPTION
**Pull request by sbinet**

### CODE REVIEW

**Comment by xhochy** [comment]
I think we had a JIRA about moving all of the go contents one folder higher. Wouldn't that be a more preferable solution?

**Comment by sbinet** [comment]
Yes, that's the jira ticket 2335.
But in that issue, it was my understanding the consensus was just to move the readme one level up.

**Comment by xhochy** [comment]
Ah, nice.

**Review by xhochy — APPROVED** [review]
+1, LGTM

**Comment by xhochy** [comment]
Thanks @sbinet !

**Pull request closed without merging**
