### PR TITLE
PARQUET-1705: [C++] Disable shrink-to-fit on the re-usable decryption buffer

### PR DESCRIPTION
**Pull request by orozery**
See: https://issues.apache.org/jira/browse/PARQUET-1705

### CODE REVIEW

**Comment by pitrou** [comment]
Two questions:
1) can the decryption buffer grow unbounded?
2) do you have benchmark numbers?

**Comment by orozery** [comment]
1. No, it's the size of the compressed page, which is not much more than a page size (default 1MB).
2. I ran it on random data with no compression, and obviously it made no difference (since the buffer size stayed fixed at 1MB exactly). I can invest time in constructing an "adversarial" data that will cause as much re-allocations as possible, but I don't think it's worth the effort.

**Comment by pitrou** [comment]
You're right, it's probably not worth the effort. I just wanted to check.

**Review by pitrou — APPROVED** [review]
+1

**Pull request closed without merging**
