### PR TITLE
[WIP] ARROW-1975: [C++] Generate ABI reports

### PR DESCRIPTION
**Pull request by xhochy**

### CODE REVIEW

**Comment by xhochy** [comment]
@pitrou Any chance you know why this is failing with https://api.travis-ci.org/v3/job/367725101/log.txt?

**Comment by pitrou** [comment]
@xhochy I noticed this too, this commit seems to fix it:
https://github.com/apache/arrow/pull/1891/commits/51d77323ff23ded6d371b893baf9b8dd84469e55

**Comment by pitrou** [comment]
This needs rebasing to fix conflicts.

**Comment by xhochy** [comment]
Rebased but I will close this. We have documentation on how to build ABI reports but won't enforce a stable ABI for the moment. The code is linked in the JIRA ticket, so it's still easy to find.

**Pull request closed without merging**
