### PR TITLE
ARROW-8239: [Java] fix param checks in splitAndTransfer method

### PR DESCRIPTION
**Pull request by pprudhvi**

### CODE REVIEW

**Comment by pprudhvi** [comment]
cc @tianchen92

**Comment by tianchen92** [comment]
@pprudhvi Is the purpose of this change to prevent illegal `length`?

**Comment by pprudhvi** [comment]
startIndex, length cannot be illegal on their own. Earlier checks were failing when startIndex, length, valueCount are all 0

**Review by tianchen92 — APPROVED** [review]

**Review by praveenbingo — APPROVED** [review]
lgtm thanks @pprudhvi

**Pull request closed without merging**
