### PR TITLE
ARROW-8485: [Integration][Java] Implement extension types integration

### PR DESCRIPTION
**Pull request by rymurr**
This enables integration tests for extension types after custom metadata is fixed #7269

### CODE REVIEW

**Comment by rymurr** [comment]
@lidavidm you mentioned previously you weren't totally happy with the existing implementation of extension types in Java. Is that still the case and is it wise to explicitly enable in integration if the data type isn't ready?

**Comment by lidavidm** [comment]
@rymurr I admit I've completely forgotten what my complaint was :joy: Have you or anyone else been using it? I'd only be worried if it seemed like the feature wasn't being used at all.

**Comment by rymurr** [comment]
I am not using it, just trying to clean up some of the outstanding integration tests before the v1.0.0 release. This particular integration test requires no changes to the extension type vector so it does give me confidence in Extension types in that they are compatible w/ C++ IPC. However perhaps there is a way to mark the type as working but not extensively tested?

**Comment by lidavidm** [comment]
I think we can enable it and if we later decide we want to rework the implementation or API, this will give us a baseline to compare with.

**Review by lidavidm — APPROVED** [review]

**Comment by lidavidm** [comment]
I'll leave this up for a bit before merging so others can look, but otherwise this is exciting!

**Pull request closed without merging**
