### PR TITLE
ARROW-10349: [Python] linux aarch64 wheels

### PR DESCRIPTION
**Pull request by AWSjswinney**
add support for building python aarch64 wheels for linux

### CODE REVIEW

**Comment by AWSjswinney** [comment]
This change makes it possible to build aarch64 python wheels, but I haven't figured out how to modify the CI code to use Travis CI the do Arm builds. Travis-CI.com is the only CI currently in use by Apache Arrow that supports Arm64 builds on linux. Guidance on the necessary changes to CI/Travis code would be appreciated.

I assume that something [here](https://github.com/apache/arrow/tree/master/dev/tasks/python-wheels) needs to be modified, but it's not clear to me how Travis-CI is invoked with this yaml file or where I would need to add code to add an additional yaml file, `travis.linux.aarc64.yml`, for example. Guidance or recommendations are appreciated.

**Comment by pitrou** [comment]
You'll need to create a Travis-CI job that runs this docker-compose entry.

**Comment by pitrou** [comment]
@xhochy @kszucs  Can you help with this? Our conventions are getting in the way here (e.g. `ARCH` is `amd64` rather than `x86_64`, we use a specific hash for the upstream manylinux base image...).

**Comment by kszucs** [comment]
I'd suggest to expand the docker-compose configuration on short term until we can figure out a nicer way to map different arch naming conventions.

**Comment by wesm** [comment]
We have some self-hosted aarch64 machines that we could use to run these, too, at some point

**Comment by xhochy** [comment]
Crossbow also support using drone.io for running `aarch64` builds. That could be an alternative to Travis.

**Comment by emkornfield** [comment]
@AWSjswinney it looks like this needs a rebase.  @kszucs do you have time to review, when that is done?

**Comment by kszucs** [comment]
Yes, going to take a look today.

**Comment by kszucs** [comment]
I'm currently pruning old crossbow branches and tags since drone doesn't pick up the aarch64 builds and the github settings page can't be loaded.

**Comment by xhochy** [comment]
A possible way to unblock this would also be just running the `aarch64` container with emulation on Github Actions or Azure Pipelines. This will take 3-5x the time but it will at least run!

**Comment by AWSjswinney** [comment]
I believe this PR now has everything needed to build and publish aarch64 wheels for manylinux2014. Thanks for reviewing it!

**Comment by RafayAK** [comment]
So, PyArrow takes a colossal amount of time when building for `aarch64`, probably because it building from sources each time, and running the build in a CI with emulation of ARM takes even longer. Can I help in any way to fast-track this issue, since it seems like it's been dormant for a while?

for reference when building an Airflow container for `aarch64` (5 hrs in an still at it):
```
Collecting pyarrow<3.0dev,>=1.0.0
  Downloading pyarrow-2.0.0.tar.gz (58.9 MB)
  Installing build dependencies: started
  Installing build dependencies: still running...
  Installing build dependencies: still running...
  Installing build dependencies: still running...
  Installing build dependencies: still running...
  Installing build dependencies: still running...
  Installing build dependencies: still running...
  Installing build dependencies: still running...
  Installing build dependencies: still running...
  Installing build dependencies: still running...
  Installing build dependencies: still running...
  Installing build dependencies: still running...
  Installing build dependencies: still running...
  Installing build dependencies: still running...
  Installing build dependencies: still running...
  Installing build dependencies: still running...
  Installing build dependencies: still running...
  Installing build dependencies: still running...
  Installing build dependencies: still running...
  Installing build dependencies: still running...
  Installing build dependencies: still running...
  Installing build dependencies: still running...
  Installing build dependencies: still running...
  Installing build dependencies: still running...
  Installing build dependencies: still running...
  Installing build dependencies: still running...
  Installing build dependencies: still running...
  Installing build dependencies: still running...
  Installing build dependencies: still running...
```

**Comment by RafayAK** [comment]
Oh, just noticed @AWSjswinney has a pull request!

**Comment by AWSjswinney** [comment]
@RafayAK It isn't exactly quick with this change but this test build I ran completed in about 35 minutes: https://travis-ci.com/github/AWSjswinney/crossbow/builds/211319456

**Comment by aitor94** [comment]
I'm trying to install pyarrow in a m6g instance on AWS and I can't. This PR may help to solve my issue. [https://stackoverflow.com/questions/64928357/how-to-install-pyarrow-in-amazon-linux-2-m6g-instance?noredirect=1#comment116973612_64928357](stack_overflow)

Thanks

**Comment by yoonsikp** [comment]
Would truly appreciate having aarch64 wheel support for apache arrow!

**Comment by kszucs** [comment]
We should favor working on https://github.com/apache/arrow/pull/9285 using vcpkg.

**Comment by kszucs** [comment]
Closing in favor of #9285

**Pull request closed without merging**
