### PR TITLE
ARROW-14985: [CI][Go] Use Go 1.16

### PR DESCRIPTION
**Pull request by kou**
Because Go 1.15 reached EOL.

### CODE REVIEW

**Comment by kou** [comment]
@github-actions crossbow submit test-debian-11-go-1.16

**Review by kszucs — APPROVED** [review]

**Comment by kou** [comment]
@zeroshade Is it OK with you?

**Comment by kou** [comment]
@github-actions crossbow submit test-debian-11-go-1.16

**Comment by kou** [comment]
+1

I'll merge this. If there is a problem, we can work on it as a follow-up task.

**Comment by zeroshade** [comment]
@kou sorry for not responding, I've been on vacation and this must have slipped through my filters. As long as all the tests succeed, I have no qualms here.

**Comment by kou** [comment]
No problem!

**Pull request closed without merging**
