### PR TITLE
docker compose instructions

### PR DESCRIPTION
**Pull request by cav71**
Hi, I've added the docker instructions here.

### CODE REVIEW

**Comment by wesm** [comment]
I just fixed up this branch which had some ugly merges. @cav71 can you set your `git config --global user.name` to your name? Currently it is set as "cav71"

**Comment by wesm** [comment]
This will need to get rebased on https://github.com/apache/arrow/pull/3243. Let's resolve that one first (whether to make README.rst or refer users to the rst files)

**Comment by wesm** [comment]
You can leave this PR open and rebase later

**Comment by cav71** [comment]
No problem, I've fixed my name and I'll keep watching for #3243, once merged I'll resubmit the pull request. thanks

**Comment by cav71** [comment]
I've removed by mistake my branch, it doesn't allow me to reopen it. sorry

**Pull request closed without merging**
