### PR TITLE
PARQUET-1709: [C++] Avoid unnecessary temporary std::shared_ptr copies

### PR DESCRIPTION
**Pull request by gawain-bolton**

### CODE REVIEW

**Comment by wesm** [comment]
Can some of these issues be fixed by appropriate uses of `std::move`? 

If the value passed to some of these functions is an rvalue, then no copy will be made. These changes (AFAICT) will trigger copies even when an rvalue is passed.

**Comment by gawain-bolton** [comment]
> If the value passed to some of these functions is an rvalue, then no copy will be made. These changes (AFAICT) will trigger copies even when an rvalue is passed.

These changes do _not_ trigger copies if an rvalue is passed.  A const ref is passed to the rvalue and this is not an extra copy.   So when the parameter is an rvalue these changes have no effect.

These changes _do_ eliminate the extra copying which occurs when the parameter passed is an lvalue.

**Comment by wesm** [comment]
> These changes do not trigger copies if an rvalue is passed. A const ref is passed to the rvalue and this is not an extra copy. So when the parameter is an rvalue these changes have no effect.

For my own understanding, what occurs when the const-ref is assigned to a member on a newly-created class instance? Is there some copy elision performed by the compiler?

**Comment by emkornfield** [comment]
For constructors/other methods that copy the objects, I have a preference for pass by value and use std::move.  There is a [clang tidy](https://clang.llvm.org/extra/clang-tidy/checks/modernize-pass-by-value.html) rule to check this which we should potentially turn on.  It makes it clear that copy will be taken instead of keeping a reference.

**Comment by pitrou** [comment]
Does it improve performance on real-world workloads or are you doing this out of principle?

**Comment by fsaintjacques** [comment]
Abseil's [tip](https://abseil.io/tips/117) recommend passing by value as suggest by @emkornfield

**Comment by gawain-bolton** [comment]
Thank you all for the feedback.  The updated pull request uses the pass by value technique.
This had resulted in a lot more changes as there are a large number of functions which can benefit from this.

**Review by wesm — APPROVED** [review]
+1. Thanks for doing all this, taking a look at the CI and then merging if possible

**Comment by wesm** [comment]
The one failure seems to be transient

```
[ERROR] Failed to execute goal on project arrow-orc: Could not resolve dependencies for project org.apache.arrow.orc:arrow-orc:jar:1.0.0-SNAPSHOT: Failed to collect dependencies at org.apache.orc:orc-core:jar:1.5.5: Failed to read artifact descriptor for org.apache.orc:orc-core:jar:1.5.5: Could not transfer artifact org.apache.orc:orc-core:pom:1.5.5 from/to central (https://repo.maven.apache.org/maven2): repo.maven.apache.org: Temporary failure in name resolution: Unknown host repo.maven.apache.org: Temporary failure in name resolution -> [Help 1]
```

Merging

**Pull request closed without merging**
