### PR TITLE
ARROW-3626: [Go] implement CSV reader

### PR DESCRIPTION
**Pull request by sbinet**
needs #2871

### CODE REVIEW

**Comment by sbinet** [comment]
PTAL @stuartcarnie

**Review by stuartcarnie — APPROVED** [review]
Looks great. Awesome to see all the boxes being checked ✅

**Comment by sbinet** [comment]
@stuartcarnie thanks :)
@wesm: how do you want to proceed? merge this one (and this should automatically close all the other open PRs) or merge all the other PRs in order and I iteratively rebase PR n+1?

**Comment by wesm** [comment]
I'll merge each patch in succession, just give me a little time (have been afk today)

**Comment by wesm** [comment]
OK, I have rebased and merged every Go patch but this. GitHub is pretty bad at allowing incremental diffs, and since we've at > 4000 lines of Go code added, it would be valuable to have some more detailed code review. We can't be rubber-stamping patches, even if it means slowing down the pace of development =)

I will merge this, but now that I have rebased each of the patches that have gone in today, they can be reviewed in isolation if anyone wishes

**Comment by wesm** [comment]
To propagate a comment from another PR here: can we move the Go TODO list to JIRA and out of the README?

**Comment by sbinet** [comment]
done: https://github.com/apache/arrow/pull/2890

**Pull request closed without merging**
