### PR TITLE
ARROW-865: [Python] Add unit tests validating Parquet date/time type roundtrips

### PR DESCRIPTION
**Pull request by wesm**
Requires PARQUET-915 https://github.com/apache/parquet-cpp/pull/311

### CODE REVIEW

**Comment by wesm** [comment]
I need to test some more cases:

- [ ] time32[s] automatically casts to TIME_MILLIS
- [ ] time64[ns] raises exception

**Comment by wesm** [comment]
OK, this is complete. I can rebase after PARQUET-915 is in

**Comment by xhochy** [comment]
PARQUET-915 is in, please rebase ;)

**Review by xhochy — APPROVED** [review]
+1, LGTM. Merge on green build.

**Comment by wesm** [comment]
Rebased

**Pull request closed without merging**
