### PR TITLE
PARQUET-690: [C++] Reuse Thrift resources when serializing metadata structures

### PR DESCRIPTION
**Pull request by wesm**
This patch should yield fewer memory allocations on the Parquet write path, using the same approach from Apache Impala. Before we were allocating a new buffer for each Thrift object serialization. Since a ColumnChunk generally will contain many data page headers, this is a bit wasteful

### CODE REVIEW

**Comment by wesm** [comment]
NB this does not really impact bottom-line performance

**Comment by xhochy** [comment]
Code looks good but CI reports linting problems.

**Comment by wesm** [comment]
I'm on Windows the next few days so linting is hard. 

https://issues.apache.org/jira/browse/ARROW-4123

cc @bkietz if you have any advice about this

**Comment by wesm** [comment]
+1

**Pull request closed without merging**
