### PR TITLE
[WIP] Benchmark placebo

### PR DESCRIPTION
**Pull request by nealrichardson**

### CODE REVIEW

**Comment by ElenaHenderson** [comment]
@benchmark me

**Comment by ElenaHenderson** [comment]
test. ignore this comment

**Comment by ElenaHenderson** [comment]
@benchmark me

**Comment by ElenaHenderson** [comment]
9272 - 30c8491386125d4315b179ec963552333d0494d4  - 50ba53446ecc43a74d0edb35e8c0b23263d0440a

**Comment by ElenaHenderson** [comment]
9272 - 30c8491386125d4315b179ec963552333d0494d4  - 50ba53446ecc43a74d0edb35e8c0b23263d0440a

**Comment by ElenaHenderson** [comment]
9272 - 30c8491386125d4315b179ec963552333d0494d4 - 50ba53446ecc43a74d0edb35e8c0b23263d0440a

**Comment by ElenaHenderson** [comment]
9272 - 30c8491386125d4315b179ec963552333d0494d4 - 50ba53446ecc43a74d0edb35e8c0b23263d0440a

**Comment by ElenaHenderson** [comment]
please benchmark

**Comment by ElenaHenderson** [comment]
please benchmark

**Comment by ElenaHenderson** [comment]
update

**Comment by ElenaHenderson** [comment]
Update

**Comment by ElenaHenderson** [comment]
please benchmark

**Comment by ElenaHenderson** [comment]
@ursabot please benchmark

**Comment by ElenaHenderson** [comment]
@ursabot please benchmark

**Comment by dianaclarke** [comment]
@ursabot please benchmark

**Comment by dianaclarke** [comment]
@ursabot please benchmark

**Comment by ElenaHenderson** [comment]
@ursabot please benchmark

**Comment by dianaclarke** [comment]
@ursabot please benchmark

**Comment by nealrichardson** [comment]
@github-actions rebase

**Comment by ElenaHenderson** [comment]
test

**Comment by ElenaHenderson** [comment]
@ursabot please benchmark

**Comment by ElenaHenderson** [comment]
@ursabot please benchmark

**Comment by ElenaHenderson** [comment]
@ursabot please benchmark

**Comment by ElenaHenderson** [comment]
@ursabot please benchmark

**Comment by ElenaHenderson** [comment]
Testing.

**Comment by ElenaHenderson** [comment]
@ursabot please benchmark

**Comment by ElenaHenderson** [comment]
@ursabot please benchmark

**Comment by ElenaHenderson** [comment]
@ursabot please benchmark

**Comment by ElenaHenderson** [comment]
@ursabot please benchmark

**Comment by ElenaHenderson** [comment]
@ursabot

**Comment by ElenaHenderson** [comment]
@ursabot hello

**Comment by ElenaHenderson** [comment]
@ursabot please benchmark lang=Java

**Comment by ElenaHenderson** [comment]
@ursabot please benchmark something=something

**Comment by ElenaHenderson** [comment]
@ursabot please benchmark lang=Python lang=C++

**Comment by ElenaHenderson** [comment]
@ursabot please benchmark name=file-write lang=C++

**Comment by ElenaHenderson** [comment]
@ursabot please benchmark lang=Python

**Comment by ElenaHenderson** [comment]
@ursabot please benchmark lang=R

**Comment by ElenaHenderson** [comment]
@ursabot please benchmark   lang=C++

**Comment by ElenaHenderson** [comment]
@ursabot please benchmark name=file-.*

**Comment by ElenaHenderson** [comment]
@ursabot please benchmark    name=file-write  lang=Python

**Comment by ElenaHenderson** [comment]
@ursabot please benchmark command=cpp-micro --suite-filter=arrow-compute-vector-selection-benchmark --benchmark-filter=TakeStringRandomIndicesWithNulls/262144/2 --iterations=3 --show-output=true

**Comment by ElenaHenderson** [comment]
@github-actions rebase

**Comment by ElenaHenderson** [comment]
@ursabot please benchmark command=cpp-micro --suite-filter=arrow-compute-vector-selection-benchmark --benchmark-filter=TakeStringRandomIndicesWithNulls/262144/2 --iterations=3 --show-output=true

**Comment by ElenaHenderson** [comment]
@ursabot please benchmark command=cpp-micro --suite-filter=arrow-compute-vector-selection-benchmark --benchmark-filter=TakeStringRandomIndicesWithNulls/262144/2 --iterations=3 --show-output=true

**Comment by ElenaHenderson** [comment]
@ursabot please benchmark command=cpp-micro --suite-filter=arrow-compute-vector-selection-benchmark

**Comment by ElenaHenderson** [comment]
test

**Comment by ElenaHenderson** [comment]
test

**Comment by ElenaHenderson** [comment]
test

**Comment by ElenaHenderson** [comment]
@ursabot please benchmark

**Comment by ElenaHenderson** [comment]
@ursabot please benchmark

**Comment by ElenaHenderson** [comment]
Benchmark runs are scheduled for baseline = ee24399c52c4fb704cbb2a69d489792505bece53 and contender = efcd862d87912e4efd93da3dc124d3b31d5d3e6b. Results will be available as each benchmark for each run completes.
Conbench compare runs links:
[Scheduled] [ec2-t3-xlarge-us-east-2](https://conbench.ursa.dev/compare/runs/d4533241ba22426b8c452bee193ad291...5ca8d73493104cccae43c82df54a8a48/)
[Scheduled] [ursa-i9-9960x](https://conbench.ursa.dev/compare/runs/e016bd93929a4630a1e50f373cbca5f5...a6a6006fdbdf470fada804827bf8a01c/)
[Scheduled] [ursa-thinkcentre-m75q](https://conbench.ursa.dev/compare/runs/8135016fcddc4665b6b862735e355921...700ebd8fe47646c78a35dfbf89e81c44/)
Supported benchmarks:
ec2-t3-xlarge-us-east-2: cloud = True
ursa-i9-9960x: langs = Python, R, JavaScript
ursa-thinkcentre-m75q: langs = C++, Java

**Comment by ElenaHenderson** [comment]
@ursabot please benchmark

**Comment by ElenaHenderson** [comment]
@ursabot help

**Comment by ElenaHenderson** [comment]
@ursabot help

**Comment by ElenaHenderson** [comment]
@ursabot please benchmark

**Comment by ElenaHenderson** [comment]
@github-actions rebase

**Comment by ElenaHenderson** [comment]
@ursabot please benchmark command=cpp-micro --suite-filter=arrow-compute-vector-selection-benchmark

**Comment by ElenaHenderson** [comment]
@ursabot please benchmark name=file*

**Comment by ElenaHenderson** [comment]
@ursabot please benchmark name=file*

**Comment by ElenaHenderson** [comment]
@ursabot please benchmark lang=R

**Comment by ElenaHenderson** [comment]
@ursabot please benchmark

**Comment by ElenaHenderson** [comment]
@ursabot please benchmark

**Comment by ElenaHenderson** [comment]
[test](https://github.com/apache/arrow/pull/9272)

**Pull request closed without merging**
