### PR TITLE
ARROW-3632: [Packaging] Update deb names in dev/tasks/tasks.yml in release process

### PR DESCRIPTION
**Pull request by kou**

### CODE REVIEW

**Review by xhochy — APPROVED** [review]
+1, LGTM

**Comment by kszucs** [comment]
@kou @xhochy We should rather implement this in crossbow.

**Comment by xhochy** [comment]
@kou @kszucs Can you then make a JIRA for the better solution for this in crossbow?

**Comment by kszucs** [comment]
created https://issues.apache.org/jira/browse/ARROW-3635

**Pull request closed without merging**
