### PR TITLE
[C++][Python] Remove boost_regex dependency

### PR DESCRIPTION
**Pull request by kszucs**

### CODE REVIEW

**Comment by pitrou** [comment]
Is this useful? Boost_regex is only used on gcc 4.8, right?

**Comment by kszucs** [comment]
It can make packaging a bit simpler.

**Comment by wesm** [comment]
How do you want to proceed here, should we abandon this?

**Comment by kszucs** [comment]
After realizing that thrift<0.13 has a header dependency on boost we probably should.

**Comment by kszucs** [comment]
I mean parquet is dependent on boost through thrift.

**Comment by wesm** [comment]
Alright. We could still remove the boost::regex dependency since Thrift does not require that, but I'll close this for now

**Comment by nealrichardson** [comment]
FTR Thrift 0.13 (and current master) still requires this boost header: https://github.com/apache/thrift/blob/master/lib/cpp/src/thrift/transport/TTransportException.h#L23

Can we just vendor it?

**Comment by wesm** [comment]
That's annoying. I have a feeling we may end up vendoring and applying small patches to Thrift eventually (it's "only" 18 KLOC). We could discuss on the mailing list

**Comment by pitrou** [comment]
We could also ping the Thrift community about a possible reimplementation of this. This may not be a very complicated function...

**Pull request closed without merging**
