### PR TITLE
ARROW-5587: [Java] Add more style check rule for Java code

### PR DESCRIPTION
**Pull request by tianchen92**
see [ARROW-5587](https://issues.apache.org/jira/browse/ARROW-5587).

### CODE REVIEW

**Comment by emkornfield** [comment]
@tianchen92 these changes LGTM.  Thank you for the cleanup.  Since this is a style change would you mind sending a quick note the mailing list letting people know about the change (I don't expect any objections) but would like people to be aware of it before merging.

**Review by emkornfield — APPROVED** [review]
As noted please send an e-mail out to the mailing list and I'll merge tomorrow if there are no objections (I don't think there should be).

**Comment by tianchen92** [comment]
Thank you @emkornfield , I will send a mail later.

**Comment by emkornfield** [comment]
@tianchen92 it looks like  you need to fix arrow-gandiva as well.

**Review by emkornfield — CHANGES_REQUESTED** [review]
CI failes on gandiva java code.

**Comment by tianchen92** [comment]
@emkornfield Thanks a lot for your kind reminder, I updated this PR and now build pass, cheers!

**Pull request closed without merging**
