### PR TITLE
ARROW-15657: [C++][Java] Upgrade Apache ORC to 1.7.3

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
This PR aims to upgrade Apache ORC to 1.7.3 which is the 3rd maintenance release at 1.7 line.

- https://orc.apache.org/news/2022/02/09/ORC-1.7.3/
- https://github.com/apache/orc/releases/tag/v1.7.3

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
Hi, @sunchao . Could you review this when you have some time?

**Review by sunchao — APPROVED** [review]
LGTM (pending CI)

**Comment by dongjoon-hyun** [comment]
Thank you so much!

**Comment by dongjoon-hyun** [comment]
Could you review this once more, @sunchao ?

**Comment by dongjoon-hyun** [comment]
Thank you so much, @sunchao !

**Pull request closed without merging**
