### PR TITLE
ARROW-13869: [R] Implement options for non-bound MatchSubstringOptions kernels

### PR DESCRIPTION
**Pull request by thisisnic**

### CODE REVIEW

**Comment by thisisnic** [comment]
@github-actions crossbow submit test-r-build-minimal

**Comment by thisisnic** [comment]
In two minds as to whether there's much point to this PR or not, given it's implementing options classes for kernels which are to have bindings implemented for at some point anyway, and likely before the next release (see linked issues in comments)

**Comment by thisisnic** [comment]
@github-actions crossbow submit test-r-minimal-build

**Comment by nealrichardson** [comment]
@github-actions autotune everything

**Review by nealrichardson — APPROVED** [review]
Looks like there are still some lint messages but hopefully autotune will fix them. Otherwise LGTM

**Comment by thisisnic** [comment]
@github-actions autotune everything

**Comment by thisisnic** [comment]
@github-actions autotune

**Pull request closed without merging**
