### PR TITLE
ARROW-14236: [C++] Add GCS testbench for testing

### PR DESCRIPTION
**Pull request by coryan**

### CODE REVIEW

**Comment by emkornfield** [comment]
Left a few comments.  boost process seems like a new dependency on boost?  I don't know if there are any issue taking it (I guess this is only for tests)?  CC @pitrou @kou

**Review by kou — COMMENTED** [review]
We already use `boost::process` for S3 tests. So it's not a new dependency.

**Review by kou — APPROVED** [review]
> I removed the change to `vcpkg.json`.

Sorry for my poor English skill. It's OK that we add `boost-process` to `vcpkg.json` in this pull request. I just wanted to say that there is no problem that we use `boost::process` for GCS test...

I think that we can merge this with minor Dockerfile related improvements.

**Comment by kou** [comment]
@github-actions crossbow submit -g nightly

**Comment by kou** [comment]
Can we set `ARROW_GCS=ON` like `ARROW_S3=ON` in our CI?

**Comment by pitrou** [comment]
> Can we set ARROW_GCS=ON like ARROW_S3=ON in our CI?

How large is the slowdown? Compiling embedded libraries from scratch adds to CI delays.

**Review by pitrou — COMMENTED** [review]
Thank you very much @coryan . Here are a number of minor comments.

**Comment by kou** [comment]
> Some of them already have these settings

Oh, sorry. I missed them.

**Review by pitrou — APPROVED** [review]
+1 (but would be nice to eliminate the slowness in `GcsFileSystem.FileSystemCompare`)

**Comment by coryan** [comment]
>  I will open a separate bug.

https://issues.apache.org/jira/browse/ARROW-14311

**Comment by pitrou** [comment]
@github-actions crossbow submit -g cpp

**Pull request closed without merging**
