### PR TITLE
ARROW-809: [C++] Do not write excess bytes in IPC writer after slicing arrays

### PR DESCRIPTION
**Pull request by wesm**
cc @itaiin

### CODE REVIEW

**Comment by wesm** [comment]
This is complete

**Comment by itaiin** [comment]
The code lgtm.

About dense unions - since its problematic to slice without scanning to find the last offset of each type, its possible to use a best-effort approach by slicing the children with a maximum value. 
It will still keep redundant values, but in some cases can still save a lot of space.
What do you think?

**Comment by wesm** [comment]
Rebased. @itaiin I'll add a change to make them *no longer* than the parent, which will definitely save space in some cases

**Review by xhochy — APPROVED** [review]
+1, LGTM

**Comment by wesm** [comment]
Added the test, will merge once build runs

**Comment by wesm** [comment]
Green MSVC build: https://ci.appveyor.com/project/wesm/arrow/build/1.0.250

**Pull request closed without merging**
