### PR TITLE
ARROW-9104: [C++] Parquet encryption tests should write files to a temporary directory instead of the testing submodule's directory

### PR DESCRIPTION
**Pull request by revit13**

### CODE REVIEW

**Comment by revit13** [comment]
@pitrou Thanks for your feedback. I changed the code to use TemporaryDir as you suggested. I appreciate it if you could review the new version of the code.  (The CI failures so far looks unrelated to the patch)

**Comment by pitrou** [comment]
@revit13 This is good, thank you!

**Review by pitrou — APPROVED** [review]
+1

**Comment by revit13** [comment]
@pitrou Thanks again for the review. I would like to merge the changes but this pull request seems to be closed. I am not sure how to resolve this.

**Comment by revit13** [comment]
@pitrou  Please ignore my previous comment. It seems that the branch is merged ok. Thanks again.

**Pull request closed without merging**
