### PR TITLE
ARROW-17840: [Java] Disable flaky JaCoCo coverage check

### PR DESCRIPTION
**Pull request by lidavidm**
The check doesn't add much value, and makes things flaky because whether a branch is covered or not can come down to chance based on where exactly an exception occurs.

### CODE REVIEW

**Comment by lidavidm** [comment]
@github-actions crossbow submit java-jars

**Comment by lidavidm** [comment]
@github-actions crossbow submit java-jars

**Comment by lwhite1** [comment]
What's the connection between JaCoCo and the JDK8 and JDK9+ profiles?

**Comment by lidavidm** [comment]
We used to have to pass more options to Surefire to get JaCoCo to work, so we had to duplicate some of the test config (since JDK8/9+ require different Surefire options). Now that we're not using JaCoCo, we also don't need that config, so we can simplify it

**Comment by lwhite1** [comment]
> We used to have to pass more options to Surefire to get JaCoCo to work, so we had to duplicate some of the test config (since JDK8/9+ require different Surefire options). Now that we're not using JaCoCo, we also don't need that config, so we can simplify it

Makes sense.

**Review by lwhite1 — APPROVED** [review]
Looks good.

**Pull request merged**
