### PR TITLE
ARROW-18302: [Python][Packaging] Update minimum vcpkg required version

### PR DESCRIPTION
**Pull request by raulcd**

### CODE REVIEW

**Comment by raulcd** [comment]
@kou I am not entirely sure about the commit afcbbdd9784e0797b567d3572c1da5605b30ab60 to fix the following issue I was able to replicate locally:
```
$ PYTHON=3.10 docker-compose build --no-cache --progress plain python-wheel-manylinux-2014
```
Was failing with the following:
```
#19 418.8 Building upb[codegen,core]:x64-linux...
#19 418.8 -- Downloading https://github.com/protocolbuffers/upb/archive/e4635f223e7d36dfbea3b722a4ca4807a7e882e2.tar.gz -> protocolbuffers-upb-e4635f223e7d36dfbea3b722a4ca4807a7e882e2.tar.gz...
#19 420.0 -- Extracting source /opt/vcpkg/downloads/protocolbuffers-upb-e4635f223e7d36dfbea3b722a4ca4807a7e882e2.tar.gz
#19 420.0 -- Applying patch 0001-make-cmakelists-py.patch
#19 420.0 -- Applying patch 0002-fix-uwp.patch
#19 420.0 -- Using source at /opt/vcpkg/buildtrees/upb/src/07a7e882e2-67ea24d098.clean
#19 420.0 CMake Error at scripts/cmake/vcpkg_find_acquire_program.cmake:619 (message):
#19 420.0   Could not find python3.  Please install it via your package manager:
#19 420.0 
#19 420.0       sudo apt-get install python3
#19 420.0 Call Stack (most recent call first):
#19 420.0   ports/upb/portfile.cmake:14 (vcpkg_find_acquire_program)
#19 420.0   scripts/ports.cmake:147 (include)
#19 420.0 
#19 420.0 
#19 420.0 error: building upb:x64-linux failed with: BUILD_FAILED
#19 420.0 error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
#19 420.0 Then check for known issues at:
#19 420.0     https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+upb
#19 420.0 You can submit a new issue at:
#19 420.0     https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[upb]+Build+error
#19 420.0 Include '[upb] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
#19 420.0     vcpkg-tool version: 2022-10-17-3247920fbdd47d08f36cbd480addd9890d3c2435
#19 420.0     vcpkg-scripts version: 2871ddd91 2022-11-10 (4 days ago)
```
That patch worked locally. Let me know if there's an approach that you feel is better for that case.

**Comment by raulcd** [comment]
@github-actions crossbow submit wheel-macos-*

**Comment by raulcd** [comment]
> @kou I am not entirely sure about the commit [afcbbdd](https://github.com/apache/arrow/commit/afcbbdd9784e0797b567d3572c1da5605b30ab60) to fix the following issue I was able to replicate locally:
> That patch worked locally. Let me know if there's an approach that you feel is better for that case.

The patch failed on Windows so I will have to find a workaround

**Comment by raulcd** [comment]
@github-actions crossbow submit wheel*

**Comment by raulcd** [comment]
The macOS build failure is expected and is fixed on this other PR which is waiting for review: https://github.com/apache/arrow/pull/14614

**Review by kou — APPROVED** [review]
+1

**Pull request merged**
