### PR TITLE
ARROW-5438: [JS] EOS bytes for sequential readers

### PR DESCRIPTION
**Pull request by jgm-ktg**

### CODE REVIEW

**Comment by jgm-ktg** [comment]
Will add test case when I can

**Review by trxcllnt — APPROVED** [review]
:+1: Looks great! :+1: Exactly the spot where I thought this would go!

**Comment by wesm** [comment]
@trxcllnt do you want to see a test case for this? It occurs to me that we could also validate this in the integration tests

**Comment by TheNeuralBit** [comment]
@trxcllnt what do you think about going ahead and merging this and making a jira to follow up with a test?

**Comment by trxcllnt** [comment]
@TheNeuralBit that sounds good to me!

**Comment by TheNeuralBit** [comment]
Thanks @jgm-ktg!

**Pull request closed without merging**
