### PR TITLE
ARROW-12405: [Packaging] Fix apt artifact patterns and artifact uploading from travis

### PR DESCRIPTION
**Pull request by kszucs**
Builds: https://github.com/ursacomputing/crossbow/branches/all?query=build-242

### CODE REVIEW

**Comment by kszucs** [comment]
Updated build for arm64 linux packages: https://github.com/ursacomputing/crossbow/branches/all?query=build-243

**Comment by kszucs** [comment]
Verified that the artifacts are properly uploaded and named now.

**Review by kszucs — COMMENTED** [review]
+1, merging on green

**Comment by kou** [comment]
Thanks!

**Pull request closed without merging**
