### PR TITLE
ARROW-13245: [R] CRAN instructions fail if libcurl4-openssl-dev and libssl-dev are not installed

### PR DESCRIPTION
**Pull request by pachadotdev**

### CODE REVIEW

**Comment by jonkeane** [comment]
Those requirements are actually optional — they are only necessary if you are [trying to build with S3 support ](https://arrow.apache.org/docs/r/articles/install.html#s3-support-1). I'm not sure that putting those in `SystemRequirements` is the right move given that they are only _actually_ required for S3 support.

**Comment by pachadotdev** [comment]
> Those requirements are actually optional — they are only necessary if you are [trying to build with S3 support ](https://arrow.apache.org/docs/r/articles/install.html#s3-support-1). I'm not sure that putting those in `SystemRequirements` is the right move given that they are only _actually_ required for S3 support.

right... let me figure out a way to warn about those requirements in the R script

**Comment by jonkeane** [comment]
We already have at least two warnings:

https://github.com/apache/arrow/blob/master/r/tools/nixlibs.R#L66-L67
https://github.com/apache/arrow/blob/master/r/tools/nixlibs.R#L421-L430

**Comment by nealrichardson** [comment]
And in fact we've already listed them in SystemRequirements: https://github.com/apache/arrow/blob/master/r/DESCRIPTION#L25. Note that SystemRequirements is an unstructured field; there are some utilities out there that parse it and help you install system requirements, but `install.packages()` doesn't do anything with it.

**Pull request closed without merging**
