### PR TITLE
MINOR: [Java] Modify document error description

### PR DESCRIPTION
**Pull request by caicancai**
### Rationale for this change

No need to execute cd java

### CODE REVIEW

**Comment by lidavidm** [comment]
I think it helps to imply which directory you should be in. Maybe we can replace it with an explicit "From the `java/` subdirectory" or similar?

**Comment by caicancai** [comment]
> I think it helps to imply which directory you should be in. Maybe we can replace it with an explicit "From the `java/` subdirectory" or similar?

thanks, how about `cd java/gandiva`

**Comment by caicancai** [comment]
@lidavidm I am working on Calcite integrating Arrow with Calcite. Thank you for your excellent work on Arrow.

**Comment by lidavidm** [comment]
Hi @caicancai sorry for the delay. Glad to hear you are working on the Calcite integration!

> > I think it helps to imply which directory you should be in. Maybe we can replace it with an explicit "From the `java/` subdirectory" or similar?
> 
> thanks, how about `cd java/gandiva`

Shouldn't it be just `java`? Maven should be invoked from the root

**Pull request closed without merging**
