### PR TITLE
ARROW-1413: [C++] Add include-what-you-use configuration

### PR DESCRIPTION
**Pull request by fjetter**
This adds `iwyu` make target to run `include-what-you-use` on all changed files of the current branch. As suggested in the ticket https://issues.apache.org/jira/browse/ARROW-1413 I took the code of `apache-kudu` as a starting point and added a few modifications.

While it works fine locally, I'm struggling to get it to work (i.e. build is failing) on travis. Somehow the check isn't performed without raising an error. I expect that clang doesn't have the iwyu properly installed but I couldn't verify it, yet.

Also, the tool requires a `compile_commands.json` to be present including all the files to be checked which is why I added the `export CMAKE_EXPORT_COMPILE_COMMANDS=1` to the `travis_env_common.sh`
This may be an issue since we are partially compiling multiple times but never the full codebase which is why I included the make/ninja iwyu twice.

### CODE REVIEW

**Comment by wesm** [comment]
I don't think it's necessary to run this on every build in Travis as it will primarily inflate our build times, only that we do a manual cleanup periodically (e.g. a couple times a release cycle)

**Comment by wesm** [comment]
@fjetter can you capitalize the "Arrow" in the PR title? I will take this for a spin when I can and then merge, sometime in the next couple days

**Comment by xhochy** [comment]
I took this for a spin and I'm not really sure this produces the expected results. At least we need to tune the `iwyu` configuration a lot.

**Comment by wesm** [comment]
We definitely should not be applying automated changes. iwyu does require a ton of tuning

**Comment by fjetter** [comment]
@wesm I'd remove the travis stuff again or do you want to keep it? Currently it doesn't do anything.

**Comment by wesm** [comment]
Can you remove it ("ninja iwyu", etc.) from the Travis scripts for now?

**Comment by wesm** [comment]
Forgot I have push permissions on your fork, I can take it from here

**Comment by wesm** [comment]
+1. I will wait for the build to pass

**Comment by fjetter** [comment]
@wesm if you want to invoke it on the whole code base you can simply add `cmake -DCMAKE_CXX_INCLUDE_WHAT_YOU_USE=iwyu <iwyu args>` to the cmake arguments. It takes care for you of the compilation database and prints the output of iwyu to `stdout`

c.f. https://cmake.org/cmake/help/v3.9/prop_tgt/LANG_INCLUDE_WHAT_YOU_USE.html?highlight=include

For including it in the build chain, though, I would've preferred a partial check.

**Pull request closed without merging**
