### PR TITLE
ARROW-14675 [R] Enable merge by union for NEWS.md

### PR DESCRIPTION
**Pull request by dragosmg**

### CODE REVIEW

**Comment by pitrou** [comment]
@jonkeane @thisisnic What do you think about this?

**Comment by thisisnic** [comment]
I think that if there aren't any drawback of doing it this way, this would be a good way of making it simple for developers to add things to `NEWS.md` on each PR and simplify collating these items ahead of a release, for sure.

**Comment by dragosmg** [comment]
@jonkeane suggested I looked into any unintended consequences with our merge script (I would say unlikely to have any conflicts). I've not yet looked into it.

**Comment by jonkeane** [comment]
Thinking about this a bit more, any negative impacts this might have on the merge script should surface when attempting to merge this. So I would be ok with attempting to merge it (consensus here looks like we're all good with it — though let me know if I'm missing something!) and if it fails I'll pass it back to Dragoș with the error log. Sound good?

**Comment by jonkeane** [comment]
This merge worked, and I tried a subsequent merge with #11771 which also worked, so I think we're fine on this!

**Pull request closed without merging**
