### PR TITLE
GH-37067: [C++] Install bundled GoogleTest

### LINKED ISSUE #37067: [C++][CI] Flight tests fail running on some configurations
### Describe the bug, including details regarding any error messages, version, and platform.

For example on Ubuntu 22.04:
https://github.com/ursacomputing/crossbow/actions/runs/5799341398/job/15719127299#step:6:4848

or Debian 11:
https://github.com/ursacomputing/crossbow/actions/runs/5799341448/job/15719127520

Symptoms are the same:
```
 70/107 Test  #71: arrow-flight-internals-test ...............***Failed    0.12 sec
Running arrow-flight-internals-test, redirecting output into /build/cpp/build/test-logs/arrow-flight-internals-test.txt (attempt 1/1)
/build/cpp/debug/arrow-flight-internals-test: error while loading shared libraries: libgmockd.so.1.11.0: cannot open shared object file: No such file or directory
/build/cpp/src/arrow/flight

        Start  72: arrow-flight-test
 71/107 Test  #72: arrow-flight-test .........................***Failed    0.12 sec
Running arrow-flight-test, redirecting output into /build/cpp/build/test-logs/arrow-flight-test.txt (attempt 1/1)
/build/cpp/debug/arrow-flight-test: error while loading shared libraries: libgmockd.so.1.11.0: cannot open shared object file: No such file or directory
/build/cpp/src/arrow/flight
```

### Component(s)

C++, Continuous Integration, FlightRPC

### PR DESCRIPTION
**Pull request by kou**
### Rationale for this change

Because `libarrow*_testing.so` depend it. If we don't install bundled GoogleTest, users can't use `libarrow*_testing.so`.

### What changes are included in this PR?

If we install bundled GoogleTest as-is, it may conflict existing GoogleTest. So this PR renames GoogleTest when we install GoogleTest:

* `lib{gtest,gtest_main,gmock,gmock_main}.so` -> `libarrow_{gtest,gtest_main,gmock,gmock_main}.so`
* `${PREFIX}/include/{gtest,gmock}/` -> `${PREFIX}/include/arrow-gtest/${gtest,gmock}/`

Other CMake packages and `.pc` files aren't installed. `ArrowTesting` CMake package and `arrow-testing.pc` configures bundled GoogleTest instead.

### Are these changes tested?

Yes.

### Are there any user-facing changes?

Yes.
* Closes: #37067

### CODE REVIEW

**Comment by kou** [comment]
@github-actions crossbow submit test-debian-11-* test-ubuntu-22.04-*

**Comment by kou** [comment]
@github-actions crossbow submit test-debian-11-* test-ubuntu-22.04-*

**Comment by kevingurney** [comment]
@sgilmore10 and I did manage to reproduce the test failures locally on macOS.

Here is the log output (note I replaced some personal information from the file paths with "..." ):

```shell
dyld[26962]: Library not loaded: libarrow_gtest.1.11.0.dylib

  Referenced from: <02638200-BA25-3D9D-AF66-D4C71F49AEFC> /System/Volumes/Data/.../arrow/matlab/build/placeholder_test

  Reason: tried: 'libarrow_gtest.1.11.0.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlibarrow_gtest.1.11.0.dylib' (no such file), 'libarrow_gtest.1.11.0.dylib' (no such file), '/usr/local/lib/libarrow_gtest.1.11.0.dylib' (no such file), '/usr/lib/libarrow_gtest.1.11.0.dylib' (no such file, not in dyld cache), '/System/Volumes/Data/.../arrow/matlab/build/libarrow_gtest.1.11.0.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/System/Volumes/Data/.../arrow/matlab/build/libarrow_gtest.1.11.0.dylib' (no such file), '/System/Volumes/Data/.../arrow/matlab/build/libarrow_gtest.1.11.0.dylib' (no such file), '/usr/local/lib/libarrow_gtest.1.11.0.dylib' (no such file), '/usr/lib/libarrow_gtest.1.11.0.dylib' (no such file, not in dyld cache)
```

It appears that the linker is unable to find `libarrow_gtest.1.11.0.dylib`. However, we manually verified that `ibarrow_gtest.1.11.0.dylib` does appear under `${MATLAB_BUILD_DIR}/${ARROW_EP_PREFIX}/lib` (e.g. `.../matlab/build/arrow_ep-prefix/lib/`) as expected.

**Comment by kevingurney** [comment]
It seems like this is some kind of `rpath`-related issue on macOS. There is an [`rpath` warning in the build logs](https://github.com/apache/arrow/actions/runs/6033389163/job/16371275244?pr=37483#step:9:572):

```shell
CMake Warning (dev):
  Policy CMP0042 is not set: MACOSX_RPATH is enabled by default.  Run "cmake
  --help-policy CMP0042" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  MACOSX_RPATH is not specified for the following targets:

   gmock
   gmock_main
   gtest
   gtest_main
```

**Comment by sgilmore10** [comment]
Hi @kou 

@kevingurney and I spent some more time investigating this failure. Here's what we found:

1. If you run the `ldd` command on the `placeholder_test` executable (with these changes), the names of the `gtest` and `gtest_main` libraries are specified as relative paths, while other library names are specified as absolute paths:

```shell
>> ldd placeholder_test
placeholder_test:
	libarrow_gtest.1.11.0.dylib (compatibility version 0.0.0, current version 1.11.0)
	libarrow_gtest_main.1.11.0.dylib (compatibility version 0.0.0, current version 1.11.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 1300.36.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1319.0.0)
```
2. However, if you run `ldd` on the `placeholder_test` executable built prior to these changes, the names for `gtest` and `gtest_main` are specified as absolute paths:

```shell
>> ldd placeholder_test
placeholder_test:
	</path/to/repo>/arrow/matlab/build/arrow_ep-build/googletest_ep-prefix/lib/libgtest.1.11.0.dylib (compatibility version 0.0.0, current version 1.11.0)
	</path/to/repo>/arrow/matlab/build/arrow_ep-build/googletest_ep-prefix/lib/libgtest_main.1.11.0.dylib (compatibility version 0.0.0, current version 1.11.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 1300.36.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1319.0.0)
```

**Note:** I replaced some personal information with `</path/to/repo>`.

3. We were able to run the `placeholder_test` executable successfully if we made the changes below:

   - Specify the `MACOSX_RPATH` property to `TRUE` for both targets `gtest` and `gtest_main` in `arrow/cpp/cmake_modules/ThirdartyToolchain.cmake`.
   - Specify the `BUILD_RPATH` property to `"${CMAKE_CURRENT_BINARY_DIR}/arrow_ep-prefix/lib"` for target `placeholder_test` in `arrow/matlab/CMakeLists.txt`.

With those changes, the executable runs as expected:

```shell
Internal ctest changing into directory: <path/to/repo>/arrow/matlab/build
Test project <path/to/repo>/arrow/matlab/build
    Start 1: PlaceholderTestTarget
1/1 Test #1: PlaceholderTestTarget ............   Passed    0.01 sec

100% tests passed, 0 tests failed out of 1

Total Test time (real) =   0.03 sec
```
  
4.  For reference, here's the output of `ldd placeholder` with these changes applied:

```shell
placeholder_test:
	@rpath/libarrow_gtest.1.11.0.dylib (compatibility version 0.0.0, current version 1.11.0)
	@rpath/libarrow_gtest_main.1.11.0.dylib (compatibility version 0.0.0, current version 1.11.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 1300.36.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1319.0.0)
```

I'm not sure if this solution is the right one, but wanted to share with you what we found.

Best,
Sarah

**Comment by kou** [comment]
@kevingurney @sgilmore10 Thanks for your help! It's very helpful. I'll use the `MACOS_RPATH` in `cpp/` approach.

BTW, it seems that we can remove GoogleTest support from `matlab/` because we can run all unit tests for MATLABE with the MATLAB's testing framework now.

**Comment by kou** [comment]
Ah, do we need to set both of `MACOSX_RPATH` and `BUILD_RPATH`?

**Comment by sgilmore10** [comment]
> Ah, do we need to set both of `MACOSX_RPATH` and `BUILD_RPATH`?

Yes, I had to set both to get it to work.

**Comment by sgilmore10** [comment]
> @kevingurney @sgilmore10 Thanks for your help! It's very helpful. I'll use the `MACOS_RPATH` in `cpp/` approach.
> 
> BTW, it seems that we can remove GoogleTest support from `matlab/` because we can run all unit tests for MATLAB with the MATLAB's testing framework now.

I think we want to keep the GoogleTest support for now because we do plan on adding C++ unit tests.  There are a few error-conditions that cannot be triggered from MATLAB for which we want to add C++ unit tests.

**Comment by kevingurney** [comment]
+1 to what Sarah said. I don't think it would be ideal to completely remove GoogleTest yet

**Comment by kevingurney** [comment]
@kou - sorry! I accidentally hit the "Close with comment" button rather than the "Comment" button. I just reopened the pull request.

**Comment by kou** [comment]
@sgilmore10 @kevingurney I see. I don't remove the GoogleTest support in `matlab/` in this PR. But can we discuss it in #37532?

**Comment by kou** [comment]
I'll merge this in this week if nobody objects this.

**Comment by kou** [comment]
> > Ah, do we need to set both of `MACOSX_RPATH` and `BUILD_RPATH`?
> 
> Yes, I had to set both to get it to work.

Thanks! It worked by adding `BUILD_RPATH` too!

**Comment by kevingurney** [comment]
@kou - very sorry for the delayed response. I was out sick at the end of last week and am just getting caught up now.

These changes look good!

Thanks for bringing up the GoogleTest question and capturing it in https://github.com/apache/arrow/issues/37532. After further consideration, we agree that we worth thinking more about removing GoogleTest. As you suggested, we can discuss this in more detail on https://github.com/apache/arrow/issues/37532.

Thank you!

**Review by kevingurney — APPROVED** [review]

**Comment by kou** [comment]
No problem. I'm not in hurry. :-)

Thanks for your approvement. I merge this.

**Comment by danepitkin** [comment]
@github-actions crossbow submit java-jars

**Pull request merged**
