### PR TITLE
GH-41547: [C++] Thirdparty: Upgrade xsimd to 13.0.0

### PR DESCRIPTION
**Pull request by mapleFU**
### Rationale for this change

Arrow now uses xsimd 9.0.1, currently, some conversion for batch is now support in neon, see: https://github.com/apache/arrow/pull/40335#issuecomment-1983609146 . So we can upgrading it.

The xsimd currently released 13.0.0, see: https://github.com/xtensor-stack/xsimd/issues/1015

For conan, seems community is updating it: https://github.com/conan-io/conan-center-index/pull/23859 . Maybe we can wait for a while

### What changes are included in this PR?

Update xsimd to 13.0.0

### Are these changes tested?

Tested by existing test code

### Are there any user-facing changes?

no

* GitHub Issue: #41547

### CODE REVIEW

**Comment by pitrou** [comment]
@github-actions crossbow submit -g cpp -g wheel

**Comment by mapleFU** [comment]
```
 RUN      ] DatasetEncryptionTest.WriteReadDatasetWithEncryption
/build/cpp/src/arrow/dataset

      Start 69: arrow-dataset-file-parquet-encryption-test
    Test #69: arrow-dataset-file-parquet-encryption-test ...***Failed    0.39 sec
Running arrow-dataset-file-parquet-encryption-test, redirecting output into /build/cpp/build/test-logs/arrow-dataset-file-parquet-encryption-test.txt (attempt 1/1)
/arrow/cpp/build-support/run-test.sh: line 88: 34469 Segmentation fault      (core dumped) $TEST_EXECUTABLE "$@" > $LOGFILE.raw 2>&1
Running main() from /builddir/build/BUILD/googletest-1.13.0/googletest/src/gtest_main.cc
[==========] Running 3 tests from 2 test suites.
[----------] Global test environment set-up.
[----------] 2 tests from DatasetEncryptionTest
[ RUN      ] DatasetEncryptionTest.WriteReadDatasetWithEncryption
/build/cpp/src/arrow/dataset

      Start 69: arrow-dataset-file-parquet-encryption-test
    Test #69: arrow-dataset-file-parquet-encryption-test ...***Failed    0.46 sec
Running arrow-dataset-file-parquet-encryption-test, redirecting output into /build/cpp/build/test-logs/arrow-dataset-file-parquet-encryption-test.txt (attempt 1/1)
/arrow/cpp/build-support/run-test.sh: line 88: 34516 Segmentation fault      (core dumped) $TEST_EXECUTABLE "$@" > $LOGFILE.raw 2>&1
Running main() from /builddir/build/BUILD/googletest-1.13.0/googletest/src/gtest_main.cc
[==========] Running 3 tests from 2 test suites.
[----------] Global test environment set-up.
```

Have we seen this before 🤔?

**Comment by pitrou** [comment]
I don't think so, but it's certainly unrelated.

**Comment by mapleFU** [comment]
BTW, in these few days the conan CI checked in, should we also switch to xsimd 13.0.0 in conan?

**Comment by pitrou** [comment]
> BTW, in these few days the conan CI checked in, should we also switch to xsimd 13.0.0 in conan?

I have no idea. @kou What do you think?

**Comment by kou** [comment]
Does it mean that "should we update https://github.com/apache/arrow/blob/657c4faf21700c0899703a4759bde76235c38199/ci/conan/all/conanfile.py#L227 ?"?

If so, we don't need to do it. It should be the same as the upstream: https://github.com/conan-io/conan-center-index/blob/133dcd62540ae212e68197b49a40947df4ff7c80/recipes/arrow/all/conanfile.py#L205

If it means that "should we update https://github.com/conan-io/conan-center-index/blob/133dcd62540ae212e68197b49a40947df4ff7c80/recipes/arrow/all/conanfile.py#L205 ?", it's better that we update. But a conan user/developer may do it eventually.

**Comment by mapleFU** [comment]
All right, how can we make sure 3rd are ready? I may use some feature introduced after 9.0 later, how should I checks that?

**Comment by kou** [comment]
Sorry. What the "3rd" refers? (You want to check xsimd version in our code?)

**Comment by mapleFU** [comment]
Ah I mean all the third-party libraries about xsimd

**Comment by mapleFU** [comment]
@github-actions crossbow submit -g cpp -g wheel

**Comment by mapleFU** [comment]
@pitrou I've check that the two failed CI is remote storage related, and one is acero-hash-join unittest, could we move forward?

**Review by pitrou — APPROVED** [review]

**Comment by pitrou** [comment]
@mapleFU This is ok to me, feel free to merge.

**Review by kou — APPROVED** [review]
+1

**Pull request merged**
