### PR TITLE
ARROW-14057: [C++] Bump aws-c-common version

### PR DESCRIPTION
**Pull request by jonkeane**

### CODE REVIEW

**Comment by pitrou** [comment]
@github-actions crossbow submit -g cpp

**Review by pitrou — APPROVED** [review]
+1 on the principle. Let's ensure CI builds pass.

**Comment by jonkeane** [comment]
The thread sanitizer failure is https://github.com/ursacomputing/crossbow/runs/3665866336?check_suite_focus=true#step:7:4108:

```
[  FAILED  ] 1 test, listed below:
[  FAILED  ] AsyncReaderTests.InvalidRowsSkipped

 1 FAILED TEST
ThreadSanitizer: reported 1 warnings
ThreadSanitizer or leak check failures in /build/cpp/build/test-logs/arrow-csv-test.txt
/build/cpp/src/arrow/csv
```

It looks like S3 isn't even built for this build https://github.com/ursacomputing/crossbow/runs/3665866336?check_suite_focus=true#step:7:2025, could this be unrelated?

**Comment by westonpace** [comment]
The `AsyncReaderTests.InvalidRowsSkipped` is addressed in https://github.com/apache/arrow/pull/11198 / ARROW-14053

**Pull request closed without merging**
