### PR TITLE
ARROW-753: [Python] Fix linker error for python-test on OS X

### PR DESCRIPTION
**Pull request by wesm**
We don't link to libpython in the pyarrow C extensions, but we need to run the googletest unit tests.

I thought we were building and running this test in Travis CI, but we're not yet. It's not that easy to add that right now, so this triages the builds in the meantime

### CODE REVIEW

**Comment by wesm** [comment]
cc @jeffknupp

**Review by xhochy — APPROVED** [review]
+1, LGTM

For me locally the problem persists as somehow my Python distribution does not come with a libpython.dylib (Have to investigate what the problem is)

**Comment by wesm** [comment]
Ah, interesting. I can look more at this if you like, are you on Homebrew Python (I think @jeffknupp was hitting this problem). I can try to set up a virtualenv / homebrew-based environment to try to reproduce the issue

**Comment by xhochy** [comment]
So, found a first solution:

In the virtualenv one needs to call `python-config --ldflags`:

```
# python-config --ldflags
-L/usr/local/opt/python/Frameworks/Python.framework/Versions/2.7/lib/python2.7/config -lpython2.7 -ldl -framework CoreFoundation

# python-config --prefix
/usr/local/opt/python/Frameworks/Python.framework/Versions/2.7
```

`libpython2.7.dylib` is located in `/usr/local/opt/python/Frameworks/Python.framework/Versions/2.7/lib`, also `/usr/local/opt/python/Frameworks/Python.framework/Versions/2.7/lib/python2.7/config` contains a symlink to the correct `libpython2.7.dylib`.

**Comment by wesm** [comment]
Merging this, since at least this makes builds with Miniconda work properly

**Comment by jeffknupp** [comment]
@xhochy Ah, interesting, I never new about that option

**Pull request closed without merging**
