### PR TITLE
ARROW-4103: [Docs] Move documentation build instructions from source/python/development.rst to docs/README.md

### PR DESCRIPTION
**Pull request by wesm**

### CODE REVIEW

**Review by bkietz — APPROVED** [review]

**Comment by cav71** [comment]
Mmm, what about leveraging the ci docker compose for that? As it is the main problem with docs it needs a complete build of the arrow (+dependencies) to be able to build it.

**Comment by pitrou** [comment]
We may want to keep the README in rst format to make transferring text from/to the Sphinx docs easier.

**Comment by wesm** [comment]
OK -- I will change it. The README here could also just direct to the build instructions. Having no README is definitely not good :)

**Comment by pitrou** [comment]
@cav71, why not, but personally I'd like to keep a non-Docker procedure as well.

**Comment by cav71** [comment]
@pitrou Thanks, I've created a pull request https://github.com/apache/arrow/pull/3248 appending those instructions in the REAMDE so we rhave both. 
@kszucs pointed me that in a separate note and @tanyaschlusser also pointed me to the full build process.

**Comment by wesm** [comment]
I made docs/README.md just direct to the place in the documentation where the build instructions are

**Pull request closed without merging**
