### PR TITLE
ARROW-1467: [JAVA] Fix reset() and allocateNew() in Nullable Value Vectors t…

### PR DESCRIPTION
**Pull request by siddharthteotia**
cc @jacques-n , @icexelloss , @BryanCutler 

Things fixed:

1)

allocateNew() in NullableValueVectors allocates extra memory for the validity vector of fixed-width vectors. Instead of doing bits.allocateNew(valueCount + 1), we should simply do bits.allocateNew(valueCount).

AFAIK, the only case where we need an additional valueCount is for the offsetVector and we already do that. Additional valueCount for the validity vector is not needed.

(2)

reset() method should call reset() on the underlying value vector to re-initialize the state (allocation monitor, reader index etc) and zero out the buffers. Right now we just reset the validity vector.

### CODE REVIEW

**Review by wesm — APPROVED** [review]
+1. Your reasoning makes sense to me

**Comment by BryanCutler** [comment]
I agree on (1), but for (2) calling `reset()` on the value vector changes `allocationSizeInBytes` which should stay the same right since it doesn't change the size of the underlying buffer?  Also I don't see where the reader/writer index is being reset?

**Comment by jacques-n** [comment]
@BryanCutler, on your second point. I don't think we should use reader/writer indexes except when exporting the buffers. Isn't that how it works now?

**Comment by siddharthteotia** [comment]
@BryanCutler,

regarding allocationSizeInBytes:

You are right that reset() doesn't change the size of underlying buffer that has been allocated for the vector. It just zeroes out the buffer. However, allocationSizeInBytes is just used to calculate/store the amount of memory that needs to be allocated. Methods like allocateNew(), realloc(), setInitialCapacity() take allocationSizeInBytes as the base value. 

allocationSizeInBytes is not used to determine the value capacity or byte capacity of the vector. Methods like getValueCapacity(), getByteCapacity() operate directly at the ArrowBuf level

Now the way I look (please correct me if I am wrong) at reset() is that it is used to do a re-init of the state of vector

(1) zero out the buffer 
(2) reset mutator
(3) reset accessor
(4) reset the validity vector (if applicable)
(5) allocation monitor, any other state as necessary

This is why I feel reset() method in Nullable Vectors should call reset() on the underlying value vector. 

As part of this, value of allocationSizeInBytes is also reset. It starts with a default value of 16KB for 4 byte integers, 32KB for 8 byte integers implying a value count of 4096.

Take an IntVector
do setInitialCapacity(8192); -- this would set the allocationSizeInBytes as 32KB bytes (at least)
do some operations
reset()
-------
here we cannot expect allocationSizeInBytes to have same state as set by setInitialCapacity() since the user called reset on the vector so I think it is probably fine if allocationSizeInBytes also gets re-initialized as part of reset(). Does this sound right? 

Regarding reader index, I was referring to line 387 in VarCharVector.java. @jacques-n  suggests that we shouldn't really worry about it in the internal vector code. It is only important when we are exporting buffers. May be we should file a JIRA to take off its redundant usages from the code?

**Comment by siddharthteotia** [comment]
any thoughts on the above rationale?

**Comment by siddharthteotia** [comment]
Another side to this is that we probably don't need to call reset() on the underlying value vector from the reset() on nullable vector.

Since the validity vector is already reset (zeroed out), there shouldn't be any way to get to the data/offsets in underlying vector so it probably doesn't matter if the underlying value vector is still holding data.

I am interested in knowing if this will ever be a problem?

**Comment by BryanCutler** [comment]
Thanks for the explanation @siddharthteotia , I agree with the reset steps you listed (1) - (5) - that all sounds like what should be done to me.  Additionally, after a reset we would not want to buffers to change size or be released right?

My concern with changing `allocationSizeInBytes` is that if you did a `reset()` and then later a `reAlloc()` was called, then the buffer would be reallocated with potentially the same or less bytes.  As for making a call to `setInitialCapacity()`, I thought that should only be done before the first call to `allocateNew()` etc, otherwise it shouldn't have any affect?  I'm not sure if that was the intent though..

As for the readerIndex/writerIndex, I brought that up because I saw that FixedWidthVectors `Accessor.getValueCount()` relies on `data.writerIndex()` so if that didn't change it would give wrong results right?

> Another side to this is that we probably don't need to call reset() on the underlying value vector from the reset() on nullable vector.

I was thinking that too.  `Accessor.get(index)` would still return values, but as long as value count gives the right answer and the validity vector is set correctly, it shouldn't be a problem I think.  Can anyone else confirm?

**Comment by siddharthteotia** [comment]
@BryanCutler 

After reset() the vector should not return any values -- for nullable vectors everything should be NULL since the validity vector is zeroed out as part of reset. This works correctly in today's world for both fixed width and variable width vectors since accessor.get(index) always checks the bit vector first and if the bit is not set, returns NULL -- this is exactly the behavior we want after a vector has been reset (until it is subsequently populated).

I concur with your point regarding changing allocationSizeInBytes and impact on subsequent realloc().

For the above reasons, looks like we both agree that there is no need to invoke values.reset() from reset method of nullable value vectors.

However, I need some confirmation on whether it is fine to leave the underlying vector with valid data and just reset the validity vector in bit vector? I don't think so there is any other entry point into the vector data other than accessor methods and they always do the right thing. So we should be good.

**Comment by wesm** [comment]
Is there a conclusion on this patch?

**Comment by siddharthteotia** [comment]
How about undoing (2) and re-visiting that later on as part of ARROW-1463?  If people agree, I will just push another commit and then this patch can be merged.

(_2)

reset() method should call reset() on the underlying value vector to re-initialize the state (allocation monitor, reader index etc) and zero out the buffers. Right now we just reset the validity vector._

**Comment by siddharthteotia** [comment]
I just pushed a commit to undo (2). I think that part needs more evaluation and discussion so we can address that in a separate patch when we get to it. 

I will open a JIRA and include all the above discussion for reference.

**Comment by BryanCutler** [comment]
LGTM

Although it was this way before your changes here, this is what I was referring to with the writerIndex being used in valueCount https://github.com/apache/arrow/blob/master/java/vector/src/main/codegen/templates/FixedValueVectors.java#L327
You don't think the index needs to be reset also?

**Comment by siddharthteotia** [comment]
The current implementation of reset is such that the call to getValueCount before and after reset will return the same result. This is true for both nullable and non-nullable vectors. 

For non-nullable vectors (fixed or variable width), the value count is tracked by the writer index. In case of variable width vectors, it is tracked by the writer index of offset vector. For nullable vectors (fixed or variable width), value count is tracked by the bit vector. 

In both cases, the source of value count is not updated upon a reset.

I am not entirely sure if we should do that. I will add it as a potential requirement for the JIRA I will open to investigate the mechanics of reset method. Is that okay?

Meanwhile, can this patch be merged?

**Comment by jacques-n** [comment]
Good point @BryanCutler. We should just stop using writer index for value counts.

**Comment by BryanCutler** [comment]
Ok, thanks for clarifying.  Yes, this looks fine then and we can address the other issues in a followup JIRA.

**Comment by wesm** [comment]
+1

**Pull request closed without merging**
