### PR TITLE
GH-38915: [Java] Upgrade Arrow Java project to JPMS Java Platform Module System

### LINKED ISSUE #151: [Java] Build Arrow as JPMS modules
### Describe the enhancement requested

Allow Arrow to be referenced as JPMS modules when run in Java 9 and higher

This issue is broken down into the following sub-issues:
- apache/arrow#38996
- apache/arrow#39134  
- apache/arrow#38998 
- apache/arrow#38997 
- apache/arrow-java#150 
- apache/arrow#39001 

The memory module related issues affect the user's command-line and may be too much of a breaking change for users.

### Component(s)

Java

### PR DESCRIPTION
**Pull request by jduo**
### Rationale for this change
This will allow for static linking, better support for newer JDKs, and integration with tools that require modules.

### What changes are included in this PR?
* Create and integrate a maven plugin to compile module-info.java files without using a newer release target. This allows compiling JARs that have Java 8 bytecode but contain module-info.class files for JPMS support.
* Refactor arrow-memory-netty such that code written in Netty packages go into a new maven module arrow-memory-netty-buffer-patch. The code from this module must be patched using patch-module when launching Java.
* add module-info.java files for vector, memory modules, and format.
* Update several plugins to use module-enabled versions:
  * maven-compiler-plugin is updated to 3.11.0
  * maven-shade-plugin is updated to 3.2.4
  * maven-dependency-plugin is updated to 3.1.2
  * CycloneDX is updated to 2.7.10
* Update grpc-java to 1.59 for module support
* Ignored TestBaseAllocator#testRootAllocator_getEmpty() for now

### Are these changes tested?
Yes, unit tests now run with modules when using JDK9+.

### Are there any user-facing changes?
Yes. The Netty module has been moved around significantly for users that depend on that code. Since modules are now named, the add-opens calls needed to run Arrow is significantly more complicated.

* Closes: apache/arrow-java#151
* GitHub Issue: #151

### CODE REVIEW

**Comment by jduo** [comment]
This is roughly comparable to where #13072 got to, minus the actual module-info.java files.
With the following additions:
- Built on the current state of main
- Updated gRPC to a module-friendly version (1.59).
- Updated plugin dependencies to module-friendly versions.
- Staged to compile the codebase with Java 8, with the exception of module-info files which will use a custom plugin (to be added. this is already implemented at https://github.com/Bit-Quill/maven-module-info-compiler-plugin and needs to get integrated to the Arrow build).

@davisusanibar @lidavidm @danepitkin 

Next up will be adding the maven plugin, then adding the module-info files from #13072, then modularizing other modules such as algorithm, adapters, ...

**Comment by jduo** [comment]
This suggests that we need to install JDK 9+ on some of the build agents:
https://github.com/apache/arrow/actions/runs/6982068919/job/19000467907?pr=38876#step:6:791

**Comment by jduo** [comment]
This failure is happening for somewhat complicated reasons:
https://github.com/apache/arrow/actions/runs/6983421948/job/19004513065?pr=38876#step:6:2511

Before refactoring, the allocator used by this test would be the Netty module's DefaultAllocationManagerFactory since TestBaseAllocator lived in the Netty module. This one correctly returns a non-zero value when given a zero-allocation.

After refactoring, TestBaseAllocator lives in memory-core, and uses the dummy DefaultAllocationManagerFactory in memory-core's tests.  This one however does return zero when given a zero-allocation. This might itself be a bug unrelated to the refactoring. This calls MemoryUtil.UNSAFE.allocateMemory(), which calls sun.misc.Unsafe.allocateMemory(), which is supposed to return a non-zero value.

**Comment by jduo** [comment]
I'm not sure what's happening in this CI failure after the Netty refactoring.
This test was in TestBaseAllocator before, but that test class got moved to memory-core. This test got separated into its own test class, moved back to Netty core (because it has Netty dependencies and wouldn't build in memory-core), and now throws a ConcurrentModificationException.

> Error:  org.apache.arrow.memory.netty.TestNettyAllocator.testMemoryUsage  Time elapsed: 0.317 s  <<< ERROR!
java.util.ConcurrentModificationException
	at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1604)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:632)
	at org.apache.arrow.memory.netty.TestNettyAllocator.testMemoryUsage(TestNettyAllocator.java:56)

**Comment by jduo** [comment]
> I'm not sure what's happening in this CI failure after the Netty refactoring.
> This test was in TestBaseAllocator before, but that test class got moved to memory-core. This test got separated into its own test class, moved back to Netty core (because it has Netty dependencies and wouldn't build in memory-core), and now throws a ConcurrentModificationException.
> 
> > Error:  org.apache.arrow.memory.netty.TestNettyAllocator.testMemoryUsage  Time elapsed: 0.317 s  <<< ERROR!
> java.util.ConcurrentModificationException
> 	at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1604)
> 	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
> 	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
> 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
> 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
> 	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
> 	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
> 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
> 	at java.base/java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:632)
> 	at org.apache.arrow.memory.netty.TestNettyAllocator.testMemoryUsage(TestNettyAllocator.java:56)

This didn't happen in my last test run and all I did was change the module info computer plugin to inherit its version. So this is probably a threading issue. Maybe extracting this test from other TestBaseAllocator tests is causing them to run in parallel when they weren't before.

**Comment by davisusanibar** [comment]
> This failure is happening for somewhat complicated reasons: https://github.com/apache/arrow/actions/runs/6983421948/job/19004513065?pr=38876#step:6:2511
> 
> Before refactoring, the allocator used by this test would be the Netty module's DefaultAllocationManagerFactory since TestBaseAllocator lived in the Netty module. This one correctly returns a non-zero value when given a zero-allocation.
> 
> After refactoring, TestBaseAllocator lives in memory-core, and uses the dummy DefaultAllocationManagerFactory in memory-core's tests. This one however does return zero when given a zero-allocation. This might itself be a bug unrelated to the refactoring. This calls MemoryUtil.UNSAFE.allocateMemory(), which calls sun.misc.Unsafe.allocateMemory(), which is supposed to return a non-zero value.
> 
> I'm going to @ignore this test for now.
> 
> Should these allocation manager factorys return a non-zero address when the user asks for an empty allocation? I would assume so since C-allocators have this property.
> 
> @davisusanibar , did you see anything like this? @lidavidm @danepitkin , any thoughts around this?

Thanks for pushing this feature, James. I am observing changes. Does this problem persist?

**Comment by jduo** [comment]
> > This failure is happening for somewhat complicated reasons: https://github.com/apache/arrow/actions/runs/6983421948/job/19004513065?pr=38876#step:6:2511
> > Before refactoring, the allocator used by this test would be the Netty module's DefaultAllocationManagerFactory since TestBaseAllocator lived in the Netty module. This one correctly returns a non-zero value when given a zero-allocation.
> > After refactoring, TestBaseAllocator lives in memory-core, and uses the dummy DefaultAllocationManagerFactory in memory-core's tests. This one however does return zero when given a zero-allocation. This might itself be a bug unrelated to the refactoring. This calls MemoryUtil.UNSAFE.allocateMemory(), which calls sun.misc.Unsafe.allocateMemory(), which is supposed to return a non-zero value.
> > I'm going to @ignore this test for now.
> > Should these allocation manager factorys return a non-zero address when the user asks for an empty allocation? I would assume so since C-allocators have this property.
> > @davisusanibar , did you see anything like this? @lidavidm @danepitkin , any thoughts around this?
> 
> Thanks for pushing this feature, James. I am observing changes. Does this problem persist?

Yes this still happens. I have marked the test as ignored to get past it.
It's not clear if this is a new bug or if it is exposing a bug from the memory-core test version of DefaultAllocationManagerFactory.

**Comment by jduo** [comment]
I'm looking for some ideas on how to fix up a maven issue. I've rigged the general build configuration in the parent POM to continue to use JDK 8 and exclude module-info.java files. I've also shut off using the module path for dependencies.

In the memory-netty build, I need a profile (that runs on JDK9) that compiles using the module-path for dependencies (using the <useModulePath> flag added to maven-compiler-plugin 3.11.0). It needs to run an extra command to patch code from another JAR into some of the packages that Netty modules export. I'd also like to compile module-info.java for this.

I likely need two executions for the Netty build. One that compiles everything in JDK8 except module-info.java, and one that uses JDK 9, compiles module-info.java and does the patch command. I don't want to compile anything else with JDK9 since I need to generate JDK8 bytecode for everything else (or I can compile everything in JDK9, then recompile everything except module-info.java in 8)

The problem I'm seeing is that setting the flag for setting the <useModulePath> flag in the profile's configuration isn't taking effect. This problem happens when both when it's an execution-level configuration or a plugin-level configuration. It does take effect when set on the parent POM.

**Comment by jduo** [comment]
The test errors in memory-core have this cause:
`Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field long java.nio.Buffer.address accessible: module java.base does not "opens java.nio" to module org.apache.arrow.memory.core`

I've addressed this is in maven by adding --add-opens java.base/java.nio=org.apache.arrow.memory.core, but perhaps I haven't covered a profile that CI is using. If anyone has any ideas on what else might need to be edited that'd be really helpful.

**Comment by jduo** [comment]
This PR has alot of changes. Perhaps we handle other modules (such as Flight, algorithm, dataset) in a separate PR so that this one can close.

**Comment by jduo** [comment]
These changes are requiring alot of patching/add-opens calls to work (see the changes It is very unfriendly for the user. 
https://github.com/apache/arrow/pull/38876/files#diff-d8225ebcfc11b480a6e4f54e183b67c3ead51635a167c106d928c2abf1f9ef66R892

The patch-module call is particularly difficult because we, and the user, do not necessarily know where their JARs are.

**Comment by lidavidm** [comment]
I'm not going to be able to review this for a while.

FWIW, I would be fine deferring other modules for another PR, and I would also be fine saying that arrow-memory-netty is just not supported when using modules because of the patching it does.

**Comment by lidavidm** [comment]
Given how new this is, I would even be OK saying that the only supported memory implementation is the Java 21+ one to begin with and we can see if there is even demand to use memory-unsafe or memory-netty.

Finally, if there's need to reorganize which package files live in, maybe we could split some of that into another PR.

**Review by lidavidm — COMMENTED** [review]
Only looking at the memory changes, they seem reasonable.

Is there a way to get rid of the classes declared in Netty's namespace? Or is what we're trying to do still not possible with just the public APIs?

**Comment by jduo** [comment]
> Only looking at the memory changes, they seem reasonable.
> 
> Is there a way to get rid of the classes declared in Netty's namespace? Or is what we're trying to do still not possible with just the public APIs?

The classes in the Netty namespace need to stay there. They call package-private functions on Netty classes.

**Pull request closed without merging**
