### PR TITLE
ARROW-1295: [Plasma] Fix segfault when writing to stderr in the manylinux build

### PR DESCRIPTION
**Pull request by pcmoritz**
This is a workaround for the segfault that happened on the manylinux1 docker container when using the cerr stream.

### CODE REVIEW

**Comment by wesm** [comment]
The whole idea of the RedHat devtoolset is not needing to do this -- do you know what is the underlying cause of the segfault in the Docker container?

**Comment by pcmoritz** [comment]
Just for reference, here is a full backtrace with debug symbols for plasma and libstdc++:

```
0x00007fffee5e41d9 in std::uncaught_exception () at ../../../../libstdc++-v3/libsupc++/eh_catch.cc:142
142	  __cxa_eh_globals *globals = __cxa_get_globals ();
#0  0x00007fffee5e41d9 in std::uncaught_exception () at ../../../../libstdc++-v3/libsupc++/eh_catch.cc:142
#1  0x00007fffee5b83a5 in ~sentry (__out=..., __s=0x7fffef7a62b8 "Connection to IPC2 socket failed for pathname ")
    at /usr/src/debug/gcc-4.1.2-20080825/obj-x86_64-redhat-linux/x86_64-redhat-linux/libstdc++-v3/include/ostream:386
#2  std::operator<< <std::char_traits<char> > (__out=..., __s=0x7fffef7a62b8 "Connection to IPC2 socket failed for pathname ")
    at /usr/src/debug/gcc-4.1.2-20080825/obj-x86_64-redhat-linux/x86_64-redhat-linux/libstdc++-v3/include/bits/ostream.tcc:761
#3  0x00007fffef741204 in arrow::internal::CerrLog::operator<< <char [47]> (this=0x7fffffff5d80, t=...)
    at /arrow/cpp/src/arrow/util/logging.h:115
#4  0x00007fffef7409b6 in plasma::ConnectIpcSocketRetry (pathname="unknown-store-name", num_retries=1, timeout=100, fd=0xbe8da0)
    at /arrow/cpp/src/plasma/io.cc:171
#5  0x00007fffef72c5d4 in plasma::PlasmaClient::Connect (this=0xbe8da0, store_socket_name="unknown-store-name", manager_socket_name="", 
    release_delay=0, num_retries=1) at /arrow/cpp/src/plasma/client.cc:517
#6  0x00007fffe9f4e3d4 in __pyx_pf_7pyarrow_6plasma_2connect (__pyx_self=0x0, __pyx_v_store_socket_name=0x7fffe77ff9d0, 
    __pyx_v_manager_socket_name=0x7ffff7fb3508, __pyx_v_release_delay=0, __pyx_v_num_retries=1)
    at /arrow/python/build/temp.linux-x86_64-2.7/plasma.cxx:6962
#7  0x00007fffe9f4dc7f in __pyx_pw_7pyarrow_6plasma_3connect (__pyx_self=0x0, __pyx_args=0x7fffcfb3d3c0, __pyx_kwds=0x0)
    at /arrow/python/build/temp.linux-x86_64-2.7/plasma.cxx:6849
#8  0x00000000004b889c in PyEval_EvalFrameEx ()
#9  0x00000000004ba738 in PyEval_EvalCodeEx ()
```

**Comment by pcmoritz** [comment]
I think I found the right solution now, the problems seems to be due to mixing static and dynamic linking (see also https://stackoverflow.com/questions/32959082/g-issues-with-shared-libraries-and-libpthread-so). Are there any negative downsides in linking jemalloc dynamically?

**Comment by wesm** [comment]
Well, the problem with dynamically linking libjemalloc in a manylinux1 wheel is that you must have it installed on your host system to `import pyarrow`, or we could bundle the libjemalloc shared library (which seems like a bit of a can of worms)

**Comment by xhochy** [comment]
It would be fine to bundle the dynamically linked `libjemalloc`, probably we should prefix the malloc functions in it. We only need to take care of correct RPATH and add a hash or so to the library name to make it unique.

**Comment by pcmoritz** [comment]
I tried to fiddle with linking orders etc. but it doesn't help. Shall we go with uwe's suggestion and compile our own jemalloc with external_project if some variable like USE_VENDORED_SHARED_JEMALLOC is set and use that for manylinux?

**Comment by pcmoritz** [comment]
Another observation I made is that this problem is not specific to plasma; if I for example print to std::cerr in the MemoryPool constructor like so:
```
MemoryPool::MemoryPool() {
  ARROW_LOG(ERROR) << "creating memory pool" << " XXX";
}
```
I get the following test failure:

```
../../venv-test-2.7/lib/python2.7/site-packages/pyarrow/tests/test_array.py creating memory pool
Program received signal SIGSEGV, Segmentation fault.
0x00007fffee6351d9 in std::uncaught_exception () at ../../../../libstdc++-v3/libsupc++/eh_catch.cc:142
142	  __cxa_eh_globals *globals = __cxa_get_globals ();
#0  0x00007fffee6351d9 in std::uncaught_exception () at ../../../../libstdc++-v3/libsupc++/eh_catch.cc:142
#1  0x00007fffee6093a5 in ~sentry (__out=..., __s=0x7fffef693cf6 "creating memory pool")
    at /usr/src/debug/gcc-4.1.2-20080825/obj-x86_64-redhat-linux/x86_64-redhat-linux/libstdc++-v3/include/ostream:386
#2  std::operator<< <std::char_traits<char> > (__out=..., __s=0x7fffef693cf6 "creating memory pool")
    at /usr/src/debug/gcc-4.1.2-20080825/obj-x86_64-redhat-linux/x86_64-redhat-linux/libstdc++-v3/include/bits/ostream.tcc:761
#3  0x00007fffef469c08 in arrow::internal::CerrLog::operator<< <char [21]> (this=0x7fffffff5ee0, t=...) at /arrow/cpp/src/arrow/util/logging.h:115
#4  0x00007fffef4e1c6f in arrow::MemoryPool::MemoryPool (this=0x7fffef9d99a0) at /arrow/cpp/src/arrow/memory_pool.cc:82
#5  0x00007fffef4e1d34 in arrow::DefaultMemoryPool::DefaultMemoryPool (this=0x7fffef9d99a0) at /arrow/cpp/src/arrow/memory_pool.cc:89
#6  0x00007fffef4e231e in arrow::default_memory_pool () at /arrow/cpp/src/arrow/memory_pool.cc:158
#7  0x00007fffef060c2b in arrow::py::get_memory_pool () at /arrow/cpp/src/arrow/python/common.cc:43
```

**Comment by wesm** [comment]
Thanks for digging into this, pretty annoying problem. Looks like @jeffknupp is already looking at some jemalloc stuff between ARROW-1282 and ARROW-1298, maybe let's wait for the patch for ARROW-1298 to land and then we can sort out a fix to this? If we can't resolve ARROW-1282 before the 0.6.0 release the conservative approach will probably be to turn it off until we can figure out what's wrong.

**Comment by pcmoritz** [comment]
Ok sounds good! We can also think about deploying https://github.com/apache/arrow/pull/914/commits/8e487b525d3cfbf1a8e3a1a997771382c52286e9 which removes the offending call to uncaught_exception, the relevant code from the CentOS version of libstdc++ is this:
```
      /**
       *  @brief  Possibly flushes the stream.
       *
       *  If @c ios_base::unitbuf is set in @c os.flags(), and
       *  @c std::uncaught_exception() is true, the sentry destructor calls
       *  @c flush() on the output stream.
      */
      ~sentry()
      {
	// XXX MT
	if (_M_os.flags() & ios_base::unitbuf && !uncaught_exception()) // line 386
	  {
	    // Can't call flush directly or else will get into recursive lock.
	    if (_M_os.rdbuf() && _M_os.rdbuf()->pubsync() == -1)
	      _M_os.setstate(ios_base::badbit);
	  }
      }
```

**Comment by wesm** [comment]
@pcmoritz the fix https://github.com/apache/arrow/commit/8e487b525d3cfbf1a8e3a1a997771382c52286e9 seems OK if that passes the build, do you want to give that a try? We'll have to address the jemalloc build / bundling issue later on

**Comment by pcmoritz** [comment]
I think without jemalloc it will already pass the test as is, so let's do that for now and come back to it after the other jemalloc problem has been figured out and we switch back to ARROW_JEMALLOC=ON. Maybe then we can find a real fix for this, and only do the workaround from https://github.com/apache/arrow/pull/914/commits/07db0b006771902c649dcebff3bb11ff0c131f81 if really necessary. What do you think?

**Comment by wesm** [comment]
Sounds OK to me. Let's close this PR, then, and we can revisit when we're looking to add jemalloc back as the default allocator

**Comment by pcmoritz** [comment]
It'd still be good to reactivate the plasma tests, shall I do that in a separate PR?

**Comment by pcmoritz** [comment]
Hm, it wasn't fixed b/c I think there is still a ARROW_JEMALLOC=on here https://github.com/apache/arrow/blob/master/python/manylinux1/Dockerfile-x86_64#L23 which gets activated for the manylinux build

**Comment by wesm** [comment]
follow-up patch here https://github.com/apache/arrow/pull/938

**Comment by pcmoritz** [comment]
Closing for now, replaced by https://github.com/apache/arrow/pull/939. Revisit this later.

**Pull request closed without merging**
