### PR TITLE
ARROW-11022: [Rust] Upgrade to Tokio 1.0

### PR DESCRIPTION
**Pull request by Dandandan**
Upgrades crates to use latest versions of
* tokio (1.0)
* tonic (0.4)
* prost (0.7)

I ran the tests/benchmarks to make sure nothing is broken.

### CODE REVIEW

**Comment by mqy** [comment]
Since rust crate version numbers without leading '^'  sometimes leads to confusions, how about prepend the versions changed in this PR with '^' to make it more clear?

**Review by alamb — APPROVED** [review]
Thanks @Dandandan  -- this is a great one to merge in right after 3.0.0 ships I think. We'll then have a few months to stabilize anything that might pop up before our next big release

**Comment by alamb** [comment]
> Since rust crate version numbers without leading '^' sometimes leads to confusions, how about prepend the versions changed in this PR with '^' to make it more clear?

@mqy  -- I think it is common in rust projects (especially library crates like Arrow) to allow some flexibility in their dependencies and thus not prefix with `^`. 

Cargo claims to implement [semve](https://semver.org/) -- which I think means  in theory crate publishers should take care and ensure that "non major version upgrades" (aka 1.2.1 --> 1.2.2, or 1.2.1 --> 1.3.0) don't contain breaking changes. If you use the `^` prefix we would prevent crates / projects that depend of Arrow from using anything other than the exact version specified. 

As you saw, the parquet-format crate didn't follow the semver versioning convention thus breaking our CI :(

**Comment by mqy** [comment]
@alam I got a bit confused about this, let me paste from https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#caret-requirements

`The string "0.1.12" is a semver version requirement. Since this string does not have any operators in it, it is interpreted the same way as if we had specified "^0.1.12", which is called a caret requirement.`

**Comment by alam** [comment]
> @alam I got a bit confused about this, let me paste from https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#caret-requirements
> 
> `The string "0.1.12" is a semver version requirement. Since this string does not have any operators in it, it is interpreted the same way as if we had specified "^0.1.12", which is called a caret requirement.`

Tagged the wrong person @mqy :)

**Comment by mqy** [comment]
> Tagged the wrong person @mqy :)

Hello @alam and @alamb xD

**Comment by Dandandan** [comment]
I agree for clarity it makes sense to start using `^` everywhere instead of omitting it, as it does the same according to the docs/
Do you agree @alamb ?

**Comment by mqy** [comment]
> I agree for clarity it makes sense to start using `^` everywhere instead of omitting it, as it does the same according to the 

```
^1.2.3  :=  >=1.2.3, <2.0.0
^1.2    :=  >=1.2.0, <2.0.0
```

If we expect the minor version to be upgraded with `cargo update`, it's better not set the patch version at all, so this is the default versioning requirement in arrow/rust: **^x.y**. If a dependency version is set with only major (e.g. "^1") or additional patch version (e.g. "^1.2.3"), that should catch our eyes:  is this the expected one? Perhaps some comments are required for these unusual versions as of the default "^x.y" form.

**Comment by alamb** [comment]
@mqy  and @Dandandan  -- I believe there are special rules in "semver" for version of the form `0.0.x` and `0.x.x` which are (slightly) different than the versions that start with something other than 0. I find this both somewhat confusing and clever

https://github.com/steveklabnik/semver#requirements

I don't consider myself a Rust version expert, so I could be wrong, but I took a quick look at several other widely used library crates and none of them seem to pin versions using the caret `^` in their Cargo.toml files

https://github.com/tokio-rs/async-stream/blob/master/async-stream/Cargo.toml
https://github.com/tokio-rs/tokio/blob/master/tokio/Cargo.toml
https://github.com/rust-lang/cargo/blob/master/Cargo.toml
https://github.com/rust-random/rand/blob/master/Cargo.toml
https://github.com/dtolnay/quote/blob/master/Cargo.toml

My opinion is that we should pin and versions using `^` if we have a specific problem we are trying to solve, but not change the default to use `^` otherwise. But that is just my opinion

**Comment by mqy** [comment]
> I believe there are special rules in "semver" for version of the form `0.0.x` and `0.x.x` which are (slightly) different than the versions that start with something other than 0. I find this both somewhat confusing and clever
r
@almb thanks for the reply.

Firstly, I don't think it is pin version when we just add `^` to an existing version as of the spec: it says plain version without leading `^` is same as that with `^`. But maybe I'm wrong because I did not verify this.
Secondly, perhaps this can answer why rust crate version may be different to semver":

Quoting from https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#caret-requirements again:
```
This compatibility convention is different from SemVer in the way it treats versions before 1.0.0. While SemVer says there 
is no compatibility before 1.0.0, Cargo considers 0.x.y to be compatible with 0.x.z, where y ≥ z and x > 0.
```

Best regards @alamb @Dandandan

**Comment by Dandandan** [comment]
Maybe whatever we decide, I think based on the amount of discussion we should maybe move it to a separate PR?

To me it makes sense to have either everything without `^` or with `^` if they give the same behavior, which seems to be according to the docs. If so, `^` to me is a bit less "surprising" about the behavior, but consistentency with other crates is also something to consider of course.

**Comment by houqp** [comment]
+1 on moving this discussion into a follow up discussion since it's not strictly related to the tokio upgrade. Pining dependencies with `^` is a common practice in other languages like python and JS, but it doesn't seem like the case for Rust. I would prefer us sticking with whatever convention Rust community adopts to avoid edge-cases in the future.

**Comment by alamb** [comment]
Maybe the `^` discussion is a good one for the mailing list

**Comment by maxburke** [comment]
Is there an ETA for when this will land?

**Comment by Dandandan** [comment]
@maxburke I expect very soon as the master branch is open for changes again, and we and users will have some time to stabilize on tokio 1.0

**Comment by alamb** [comment]
@maxburke  I predict sometime in the next 24 hours. We are working through the Rust PR backlog (though it is fairly large). I also believe this one is important as tokio flows upwards through the Rust ecosystem

**Comment by alamb** [comment]
Looks to me like the integration test failure on https://github.com/apache/arrow/pull/9230/checks?check_run_id=1716562930 is due to changes in this PR. Namely it seems like there is a timeout when using a rust server -- I took a quick peek into the Cargo.lock file and I can't find any obvious issue with multiple versions of tokio

```
##########################################################
Flight: Java serving, Rust requesting
##########################################################
==========================================================
Testing file null_trivial
==========================================================
==========================================================
Testing file decimal
==========================================================
-- Skipping test because consumer Rust does not support
==========================================================
Testing file decimal256
==========================================================
-- Skipping test because consumer Rust does not support
==========================================================
Testing file primitive_large_offsets
==========================================================
==========================================================
Testing file interval
==========================================================
-- Skipping test because consumer Rust does not support
==========================================================
Testing file map
==========================================================
-- Skipping test because consumer Rust does not support
==========================================================
Testing file map_non_canonical
==========================================================
-- Skipping test because producer Java does not support
==========================================================
Testing file null
==========================================================
==========================================================
Testing file primitive_no_batches
==========================================================
==========================================================
Testing file nested_large_offsets
==========================================================
-- Skipping test because consumer Rust does not support
==========================================================
Testing file union
==========================================================
-- Skipping test because producer Java does not support
==========================================================
Testing file primitive_zerolength
==========================================================
==========================================================
Testing file primitive
==========================================================
==========================================================
Testing file custom_metadata
==========================================================
==========================================================
Testing file dictionary_unsigned
==========================================================
-- Skipping test because producer Java does not support
==========================================================
Testing file nested_dictionary
==========================================================
-- Skipping test because producer Java does not support
==========================================================
Testing file extension
==========================================================
-- Skipping test because consumer Rust does not support
==========================================================
Testing file recursive_nested
==========================================================
==========================================================
Testing file middleware
==========================================================
-- Skipping test because consumer Rust does not support
==========================================================
Testing file nested
==========================================================
==========================================================
Testing file datetime
==========================================================
==========================================================
Testing file duplicate_fieldnames
==========================================================
==========================================================
Testing file dictionary
==========================================================
==========================================================
Testing file auth:basic_proto
==========================================================
Error: The operation was canceled.
```

**Comment by houqp** [comment]
Is there an easy way to reproduce this integration test failure locally?

**Comment by alamb** [comment]
@houqp  -- I think the instructions to run the tests locally are here: https://github.com/apache/arrow/blob/master/docs/source/format/Integration.rst

@carols10cents  or @nevi-me  may have some pointers as I think they have worked in this area too

**Comment by nevi-me** [comment]
> @houqp -- I think the instructions to run the tests locally are here: https://github.com/apache/arrow/blob/master/docs/source/format/Integration.rst
> 
> @carols10cents or @nevi-me may have some pointers as I think they have worked in this area too

I'm also seeing the timeout locally:

@qphou I've not been able to run integration tests successfully with docker, so I use the local script below:

```bash
# prep work
export ARROW_HOME=~/arrow
export ARROW_VERSION=3.0.0-SNAPSHOT
export ARROW_JAVA_INTEGRATION_JAR=$ARROW_HOME/java/tools/target/arrow-tools-$ARROW_VERSION-jar-with-dependencies.jar
export RUST_BACKTRACE=1

# build CPP testing binary
cd ./cpp
# remove the build directory if needed
# rm build -r
mkdir -p build
cd build
# change or remove the -j24, it speeds up the builds for me locally. 24 is the number of CPU cores I have
cmake -DCMAKE_BUILD_TYPE=Debug -DARROW_BUILD_INTEGRATION=ON -DARROW_FLIGHT=ON -DARROW_BUILD_TESTS=ON -j24 ..
make -j24
cd ../../

# build Java testing binary
cd ./java
# clean if necessary
# mvn clean
# I disabled the java build, but added this for completeness. Java Flight tests fail locally for me
# mvn install -DskipTests
cd ../

# build Rust testing binary
cd ./rust && cargo build
cd ../

# run tests
archery integration --with-cpp=1 --with-rust=1 --with-java=0 --run-flight --debug > integration-testing.log
```

**Comment by nevi-me** [comment]
I've started looking at this today/yday. The Rust flight binaries seem to be passed the same arguments as before, I've stopped where the server starts. I'll continue later tonight.

**Comment by houqp** [comment]
Following the steps shared by nevi, i was able to narrow down the reproducible case to simply running `cargo run --bin flight-test-integration-server -- --port=0` from within `integration-testing` crate folder.

**Comment by houqp** [comment]
I see what's going on, the rust tester implementation expects test server to output binding port: https://github.com/apache/arrow/blob/master/dev/archery/archery/integration/tester_rust.py#L88-L96.

But this particular logging line was removed in this PR, so the the test runner passed the wrong port to the consumer client.

We need to add back that logging and also make a comment there to let future developer know this is just an informational print ;)

**Comment by Dandandan** [comment]
Thanks @houqp that's very subtle...

**Comment by Dandandan** [comment]
Something else also seems going on (related to binding the port), but I don't have time anymore today. Feel free to comment here or open a new PR resolving the issue @nevi-me @houqp .

**Comment by houqp** [comment]
```
    let addr: SocketAddr = format!("0.0.0.0:{}", port).parse()?;
    println!("Server listening on localhost:{}", addr.port());
```

Perhaps `let addr: SocketAddr ` is not actually binding to a port and `addr.port()` is returning `0`?

**Comment by Dandandan** [comment]
Thanks @houqp ! That did the trick. I removed the earlier code because of the slightly changed API, but I removed too much.
Looks like integration test is now succeeding @alamb

**Comment by alamb** [comment]
I think this is looking good -- what do you think @nevi-me  @andygrove and @jorgecarleitao ?

**Review by jorgecarleitao — APPROVED** [review]
LGTM. Great work, @Dandandan !

**Review by andygrove — APPROVED** [review]

**Review by nevi-me — APPROVED** [review]
All good from my side

**Pull request closed without merging**
