### PR TITLE
PARQUET-1899: [C++] Deprecated ReadBatchSpaced

### PR DESCRIPTION
**Pull request by emkornfield**

### CODE REVIEW

**Comment by pitrou** [comment]
The tests fail compiling on some builds because of the deprecation warning. Perhaps we can add a facility to disable deprecation warnings around certain function calls or code snippets?

**Comment by emkornfield** [comment]
> Perhaps we can add a facility to disable deprecation warnings around certain function calls or code snippets?

@pitrou I don't have much knowledge for this.   Do you have something specific in mind?  This is relatively low priority it is just confusing to have this code in the code base.

**Comment by pitrou** [comment]
Here is an example: https://www.fluentcpp.com/2019/08/30/how-to-disable-a-warning-in-cpp/
(need to adapt it for the deprecation warning flags / numbers on gcc / clang / MSVC)

**Comment by emkornfield** [comment]
Thanks will give that a try (likely not for a little bit since working on nested functionality is going to be my main focus).

**Comment by kiszk** [comment]
nit: The title should be `PARQUET-1899: [C++] Deprecated ReadBatchSpaced`.

**Comment by pitrou** [comment]
@emkornfield Do you want to revive this?

**Comment by emkornfield** [comment]
Yes.  I'll try to get to it tonight.  Thanks for the reminder

**Comment by pitrou** [comment]
@emkornfield No urgency, but if you want to refresh this PR ;-)

**Comment by emkornfield** [comment]
sorry taking a look at itnow.

**Comment by emkornfield** [comment]
@pitrou I think this is ready to review again.  I added the new macros to in a new file under testing, because I think when we deprecate items the only place we should still reference the methods internally is in tests, but happy to move them if you think there is someplace more appropriate.

**Review by pitrou — APPROVED** [review]
LGTM, thank you @emkornfield

**Pull request closed without merging**
