### PR TITLE
ARROW-5538: [C++] Restrict minimum OpenSSL version to 1.0.2

### PR DESCRIPTION
**Pull request by majetideepak**

### CODE REVIEW

**Comment by kou** [comment]
How about using CMake's version check feature?

```diff
diff --git a/cpp/cmake_modules/ThirdpartyToolchain.cmake b/cpp/cmake_modules/ThirdpartyToolchain.cmake
index 3d922e14..444e08d9 100644
--- a/cpp/cmake_modules/ThirdpartyToolchain.cmake
+++ b/cpp/cmake_modules/ThirdpartyToolchain.cmake
@@ -749,13 +749,14 @@ set(ARROW_USE_OPENSSL OFF)
 if(PARQUET_REQUIRE_ENCRYPTION AND NOT ARROW_PARQUET)
   set(PARQUET_REQUIRE_ENCRYPTION OFF)
 endif()
+set(ARROW_OPENSSL_REQUIRED_VERSION "1.0.2")
 if(PARQUET_REQUIRE_ENCRYPTION OR ARROW_FLIGHT)
   # This must work
-  find_package(OpenSSL REQUIRED)
+  find_package(OpenSSL ${ARROW_OPENSSL_REQUIRED_VERSION} REQUIRED)
   set(ARROW_USE_OPENSSL ON)
 elseif(ARROW_PARQUET)
   # Enable Parquet encryption if OpenSSL is there, but don't fail if it's not
-  find_package(OpenSSL QUIET)
+  find_package(OpenSSL ${ARROW_OPENSSL_REQUIRED_VERSION} QUIET)
   if(OPENSSL_FOUND)
     set(ARROW_USE_OPENSSL ON)
   endif()
```

**Comment by majetideepak** [comment]
I wasn't comfortable with "Version support is currently provided only on a package-by-package basis" in the official documentation. I don't know the support for OpenSSL in all the environments.
https://cmake.org/cmake/help/v3.15/command/find_package.html

**Comment by kou** [comment]
It's supported since CMake 2.8.5: https://github.com/Kitware/CMake/commit/112f1dd7e36b9ce398e7082b48a3770e18b04f94#diff-fe8d6d3a9cfe5f0d0dcdab3824900232

We require CMake 3.2 or later.

So we can use CMake's version check feature for OpenSSL.

**Comment by majetideepak** [comment]
Here, the package is OpenSSL. The comment "Version support is currently provided only on a package-by-package basis" indicates that version support depends on the OpenSSL package. The [Version Selection](https://cmake.org/cmake/help/v3.15/command/find_package.html#version-selection) section further describes the requirement of a "version file" for this to work.

Nevertheless, I updated the PR with your suggestion. We can always revert if we run into issues on certain environments.

**Review by kou — APPROVED** [review]
+1

**Pull request closed without merging**
