### PR TITLE
ARROW-16278: [CI] Fix git installation failure on brew

### PR DESCRIPTION
**Pull request by kszucs**

### CODE REVIEW

**Comment by raulcd** [comment]
I had a PR fixing the git version that fixes the builds: https://github.com/apache/arrow/pull/12956

**Review by raulcd — APPROVED** [review]
The overwrite looks good to me :+1: 
```
 ==> Downloading https://ghcr.io/v2/homebrew/core/git/manifests/2.36.0
==> Downloading https://ghcr.io/v2/homebrew/core/git/blobs/sha256:5739e703f9ad34dba01e343d76f363143f740bf6e05c945c8f19a073546c6ce5
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:5739e703f9ad34dba01e343d76f363143f740bf6e05c945c8f19a073546c6ce5?se=2022-04-22T15%3A35%3A00Z&sig=pY9vSfJMOAKDKrczafN68QJEvALXYN89j5kslVWrom4%3D&sp=r&spr=https&sr=b&sv=2019-12-12
==> Pouring git--2.36.0.big_sur.bottle.tar.gz
==> Caveats
The Tcl/Tk GUIs (e.g. gitk, git-gui) are now in the `git-gui` formula.
Subversion interoperability (git-svn) is now in the `git-svn` formula.

Bash completion has been installed to:
  /usr/local/etc/bash_completion.d

Emacs Lisp files have been installed to:
  /usr/local/share/emacs/site-lisp/git
==> Summary
🍺  /usr/local/Cellar/git/2.36.0: 1,544 files, 43.6MB
==> Running `brew cleanup git`...
```

**Comment by kszucs** [comment]
@raulcd do we have others builds failing due to the same reason?

**Comment by raulcd** [comment]
I was able to trigger it on three different ones:
```
Python / AMD64 MacOS 10.15 Python 3
C++ / AMD64 MacOS 10.15 C++
C GLib & Ruby / AMD64 MacOS 10.15 GLib & Ruby
```

**Review by kszucs — COMMENTED** [review]
+1, failures are unrelated

**Pull request closed without merging**
