### PR TITLE
GH-41867: [Java] Parallel to build JNI C++ code

### PR DESCRIPTION
**Pull request by jinchengchenghh**
### Rationale for this change
Accelerate the default JNI C++ build process

### What changes are included in this PR?
Add `-j` to cmake build command

### Are these changes tested?
Current tests covered.

### Are there any user-facing changes?
No

* GitHub Issue: #41867

### CODE REVIEW

**Comment by vibhatha** [comment]
should we also add some documentation regarding setting a fixed parallelism for Java users (in case of there are concerns on full resource utilization)?

**Comment by lidavidm** [comment]
@github-actions crossbow submit -g java

**Comment by jinchengchenghh** [comment]
> should we also add some documentation regarding setting a fixed parallelism for Java users (in case of there are concerns on full resource utilization)?

Do we need to add `mvn -Dparallel=x` to support setting a fixed parallelism? Or the user can build by CMAKE directly if they would not like to utilize resource fully?

**Comment by vibhatha** [comment]
> mvn -Dparallel=x

I am not sure if this is a standard maven property? But if we can introduce such a variable to the root and document in `development.rst`, that would be very useful for most of the Java devs just use `mvn install` approach to build the project.

cc @lidavidm

**Comment by jinchengchenghh** [comment]
No, it will be arrow defined property. Current `-j` take effect under command `mvn generate-resource`. Maybe -DCPP_BUILD_PARALLEL is more reasonable.

**Comment by lidavidm** [comment]
Does CMAKE_PARALLEL_LEVEL not already work?

**Comment by lidavidm** [comment]
Sorry that should be [`CMAKE_BUILD_PARALLEL_LEVEL`](https://cmake.org/cmake/help/latest/envvar/CMAKE_BUILD_PARALLEL_LEVEL.html)

**Comment by vibhatha** [comment]
> Sorry that should be [`CMAKE_BUILD_PARALLEL_LEVEL`](https://cmake.org/cmake/help/latest/envvar/CMAKE_BUILD_PARALLEL_LEVEL.html)

I haven't actually checked this. @jinchengchenghh could we verify this?

**Comment by vibhatha** [comment]
@jinchengchenghh need any help here?

**Comment by jinchengchenghh** [comment]
> Sorry that should be [`CMAKE_BUILD_PARALLEL_LEVEL`](https://cmake.org/cmake/help/latest/envvar/CMAKE_BUILD_PARALLEL_LEVEL.html)

It works, but I think the default parallel mode should be parallel build mode.
Java users may not check if cpp code is compiled parallism when they use `mvn generate-resource` to compile cpp code.

**Comment by lidavidm** [comment]
As is though, this forces parallelism which may also be undesirable

**Comment by jinchengchenghh** [comment]
ok, I will close this PR

**Pull request closed without merging**
