### PR TITLE
ARROW-3672 & ARROW-3673: [Go] add support for time32 and time64 array

### PR DESCRIPTION
**Pull request by alexandreyc**
Hello everyone,

My attempt at adding support for time32 and time64 array. Need review because I'm not sure I added all that is needed.

Thanks,

Alexandre

### CODE REVIEW

**Review by sbinet — APPROVED** [review]
LGTM.

could you add a few tests for time32/64 arrays and builders?

**Comment by alexandreyc** [comment]
Yes, will do that.

What do you think about templating all the tests for numeric arrays/builders?

**Review by sbinet — APPROVED** [review]
LGTM

@stuartcarnie waht do you think?

**Comment by alexandreyc** [comment]
Still need tests for arrays. I'm working on it and it should be ready soon.

**Comment by stuartcarnie** [comment]
@sbinet looks good to me, too. Thanks for the contribution, @alexandreyc!

**Comment by alexandreyc** [comment]
Should be good now! Fixed a little typo which caused time64 array tests to fail.

**Comment by wesm** [comment]
I noticed you are using unicode "mu" for microseconds here https://github.com/apache/arrow/commit/df54da211448b5202aa08ed2b245eb78cfd1e50c. Is that really what you want?

**Comment by alexandreyc** [comment]
Yes, it's one character like other fractions and translate well to microseconds. I'm open to renaming this if needed.

**Comment by wesm** [comment]
Some other projects use "us" instead of "μs". I had to Google the "mu" unicode character and copy-and-paste it because I'm on Linux and don't know how to type such characters from an English keyboard layout

**Comment by alexandreyc** [comment]
Switched to "us".

**Pull request closed without merging**
