### PR TITLE
ARROW-11586: [Rust][Datafusion] Remove force unwrap

### PR DESCRIPTION
**Pull request by marcprux**
Fix for https://issues.apache.org/jira/browse/ARROW-11586

### CODE REVIEW

**Review by jorgecarleitao — APPROVED** [review]
I know it is draft, but it looks good to me already :)

**Comment by marcprux** [comment]
I've un-drafted it.

**Review by nevi-me — APPROVED** [review]

**Review by Dandandan — APPROVED** [review]
LGTM 👍 😎

**Comment by alamb** [comment]
Thanks @marcprux

**Pull request closed without merging**
