### PR TITLE
ARROW-631: [GLib] Import

### PR DESCRIPTION
**Pull request by kou**
See also https://issues.apache.org/jira/browse/ARROW-631 and `glib/README.md` in this change.

### CODE REVIEW

**Comment by wesm** [comment]
This looks like it was an incredible amount of work, I'm very impressed, and it looks very useful for languages that have support for GObject introspection. Did you write the C bindings all by hand or are there any tools to assist with generating the wrapper bindings? How would you like to handle cases where they may be API changes that impact the bindings (e.g. we recently changed `int32_t` lengths to `int64_t`)? I agree that maintaining C bindings, especially to the IPC metadata, type objects, and array containers, will be really valuable.

**Comment by kou** [comment]
> Did you write the C bindings all by hand or are there any tools to assist with generating the wrapper bindings?

I write them all by hand. 

> How would you like to handle cases where they may be API changes that impact the bindings (e.g. we recently changed `int32_t` lengths to `int64_t`)?

I prefer to C compiler detects it. The length type change wasn't detected by C compiler but most cases will be able to be detected by C compiler. (The length type change case was detected by me because I read commits.)

**Comment by kou** [comment]
This change includes Travis CI integration. We can detect (C compiler detectable) API changes in C++ implementation automatically.

**Comment by julienledem** [comment]
pretty cool :)

**Comment by wesm** [comment]
@kou that's really great (re: Travis CI integration), thank you. I am going to check out the branch as soon as I can (hopefully today) to make sure I am familiar with the build/test workflow for this (so that I can help with maintenance in case there are small API changes). 

Would it be OK to change the top level folder name to be "c_glib" similar to Apache Thrift (https://github.com/apache/thrift/tree/master/lib) -- this will make it more obvious for users who are looking for C bindings, but are not familiar with glib-based C bindings. 

Hopefully it goes without saying you are more than welcome to contribute the Ruby bindings to this codebase if you like.

**Comment by kou** [comment]
> Would it be OK to change the top level folder name to be "c_glib" similar to Apache Thrift (https://github.com/apache/thrift/tree/master/lib) -- this will make it more obvious for users who are looking for C bindings, but are not familiar with glib-based C bindings.

Sure. Should I rename before you merge this changes? Or after?

> Hopefully it goes without saying you are more than welcome to contribute the Ruby bindings to this codebase if you like.

OK. I'll consider about it after .deb/.rpm package support is resolved.

**Comment by wesm** [comment]
Can you rename it in this patch? Very much appreciated. I'm going to merge this as is once I run through the build/test workflow locally. Travis CI passed but there is a failure from an OS X build slave timing out

**Review by wesm — APPROVED** [review]
+1, thank you so much for this contribution. The GObject introspection functionality in Ruby is really neat. I look forward to seeing how this functionality can help develop more bindings for Arrow in the future

**Comment by kou** [comment]
Thanks!

**Pull request closed without merging**
