### PR TITLE
ARROW-13850: [C++] Fix crashes on invalid Parquet data

### PR DESCRIPTION
**Pull request by pitrou**
Add validation to detect invalid DELTA_BINARY_PACKED data.

This should fix the following issues:
* https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=37431
* https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=37432
* https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=37421

### CODE REVIEW

**Comment by pitrou** [comment]
Note this depends on #11059 for CI to pass.

**Comment by pitrou** [comment]
@shanhuuang Can you take a look?

**Comment by shanhuuang** [comment]
> @shanhuuang Can you take a look?

It looks good to me. :)

**Comment by emkornfield** [comment]
+1

**Pull request closed without merging**
