### PR TITLE
ARROW-10239: [C++] Add missing zlib dependency to aws-sdk-cpp

### PR DESCRIPTION
**Pull request by kou**

### CODE REVIEW

**Comment by kou** [comment]
@nealrichardson How do we test this with https://github.com/ursa-labs/arrow-r-nightly ?

**Comment by kou** [comment]
@github-actions crossbow submit -g linux

**Comment by nealrichardson** [comment]
@kou I made a branch to have it test building from your fork: https://github.com/ursa-labs/arrow-r-nightly/commit/938da99c0c59213b3841df779c1766780a463f30

Running here: https://github.com/ursa-labs/arrow-r-nightly/actions/runs/296671640

**Comment by kou** [comment]
Thanks.
It seems that this change works well.

The failure of centos-7 job is unrelated.
We need to remove `-DARROW_S3=ON` from the job because gcc on CentOS 7 is old to build aws-sdk-cpp.

**Comment by kou** [comment]
+1
I'll merge this.

**Comment by nealrichardson** [comment]
Yeah I saw that, will clean that up. Thanks for taking care of this!

**Pull request closed without merging**
