### PR TITLE
ARROW-3131: [Go] add Go1.11 to the build matrix

### PR DESCRIPTION
**Pull request by sbinet**
needs #2486

### CODE REVIEW

**Comment by xhochy** [comment]
Is there a way to see in the logs that we have tested both versions?

**Comment by sbinet** [comment]
Hum... You're right. It seems I've had some finger problems or I didn't completely understood how to modify '.travis.yml'... there's only 1.10.x being tested as far as I can see...

**Comment by kszucs** [comment]
> Since these builds are both pretty fast can you run them in the same CI entry?

Would it be possible to run both versions in the same CI step? 
We've implemented the rust nightly builds in a similar fashion in https://github.com/apache/arrow/pull/2477.

**Comment by sbinet** [comment]
circling back...

I couldn't figure out how to build for multiple Go toolchains, short of copy-pasting the stanza for each Go compiler:
```
  # Go
  - language: go
    go_import_path: github.com/apache/arrow
    os: linux
    go:
    - 1.10.x
    before_script:
    - if [ $ARROW_CI_GO_AFFECTED != "1" ]; then exit; fi
    script:
    - $TRAVIS_BUILD_DIR/ci/travis_script_go.sh
    after_success:
    - pushd ${TRAVIS_BUILD_DIR}/go/arrow
    - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
  # Go
  - language: go
    go_import_path: github.com/apache/arrow
    os: linux
    go:
    - 1.11.x
    before_script:
    - if [ $ARROW_CI_GO_AFFECTED != "1" ]; then exit; fi
    script:
    - $TRAVIS_BUILD_DIR/ci/travis_script_go.sh
    after_success:
    - pushd ${TRAVIS_BUILD_DIR}/go/arrow
    - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
```

I'll just bump to `1.11.x` and call it a day.

**Comment by wesm** [comment]
Sounds fine to me. We can always add a docker-compose entry for testing 1.10.x on demand

**Comment by sbinet** [comment]
build failure (in `R`) unrelated.

**Review by xhochy — APPROVED** [review]
+1, LGTM

**Pull request closed without merging**
