### PR TITLE
ARROW-10479: [C++] Initial support of low bitness Decimals (16, 32, 64)

### PR DESCRIPTION
**Pull request by dchigarev**

### CODE REVIEW

**Comment by pitrou** [comment]
@dchigarev What is the status of this PR? Do you intend to finish working on it?

**Comment by dchigarev** [comment]
@pitrou generally PR is ready, now I'm fixing CI issues caused by my incorrectly usage of `ARROW_EXPORT` attribute, I hope I'll have an opportunity to mark it as ready for review at the next week

**Comment by pitrou** [comment]
@dchigarev This PR is still in draft. Are you planning to update and/or submit it?
(also, it would need rebasing on current master)

**Comment by baumgold** [comment]
Hi.  Any update here?  Thanks.

**Comment by dchigarev** [comment]
The PR is pretty much outdated and would take a lot of effort to align it with the master I think. So it's better to close the PR.

**Pull request closed without merging**
