### PR TITLE
ARROW-3338: [Python] Crash when schema and columns do not match

### PR DESCRIPTION
**Pull request by kszucs**

### CODE REVIEW

**Review by wesm — APPROVED** [review]
+1, thanks! That was a bit silly, I guess =)

**Comment by wesm** [comment]
If you could hold off on merging until I get PARQUET-1427 in that would be great

**Comment by wesm** [comment]
Any idea what's up with Appveyor? https://issues.apache.org/jira/browse/ARROW-3342

**Comment by kszucs** [comment]
> Well, GitHub's new owner has just started a similar service :)
I'm taking a look.

**Review by wesm — APPROVED** [review]
+1

**Pull request closed without merging**
