### PR TITLE
MINOR: [CI][Python] Disable Arrow Engine (substrait) in the ubuntu-python-sdist-test build

### PR DESCRIPTION
**Pull request by jorisvandenbossche**

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
See https://github.com/apache/arrow/pull/12322#issuecomment-1048519053, and similar as https://github.com/apache/arrow/pull/12356/ but not for substrait instead of opentelemetry

This should be a quick fix for the failing nightly build. But not sure if this is a good long term solution to disable this essential part (although for testing that the sdist works, it might not be essential?)

**Comment by jorisvandenbossche** [comment]
@github-actions crossbow submit python-sdist

**Comment by pitrou** [comment]
It seems the usage of git will disappear in https://github.com/apache/arrow/pull/12457 ?

**Comment by jorisvandenbossche** [comment]
Yes, so if that gets merged, I think we can discard this PR

**Pull request closed without merging**
