### PR TITLE
ARROW-17645: [CI] Get conda-integration building again

### PR DESCRIPTION
**Pull request by lidavidm**

### CODE REVIEW

**Comment by lidavidm** [comment]
@kou or @assignUser, how does this look for a fix? I'm not happy about pinning more things but it seems zlib hasn't made a new release yet

**Comment by kou** [comment]
Can we apply https://github.com/madler/zlib/commit/ec3df00224d4b396e2ac6586ab5d25f673caa4c2 in https://github.com/madler/zlib/commit/ec3df00224d4b396e2ac6586ab5d25f673caa4c2 instead?

**Comment by lidavidm** [comment]
I'll try opening a PR and seeing if there's interest in patching

**Comment by lidavidm** [comment]
https://github.com/conda-forge/zlib-feedstock/pull/66

**Comment by lidavidm** [comment]
Patch was accepted, so once I see the new packages go out I'll test unpinning the dependency

**Comment by lidavidm** [comment]
Hmm, it failed, but I see it didn't install the most updated zlib…trying again

**Comment by lidavidm** [comment]
Looks like a dummy change to bump the cache did the trick - what's the 'right' way to accomplish that?

**Comment by kou** [comment]
I'll remove the cached images listed at https://hub.docker.com/r/apache/arrow-dev/tags (admin page: https://hub.docker.com/repository/docker/apache/arrow-dev/tags ).

**Comment by kou** [comment]
I've removed `amd64-conda` and `amd64-conda-cpp`.

**Comment by lidavidm** [comment]
Thanks! Reverted the last commit, let's see how the build goes now

**Review by kou — APPROVED** [review]
+1

**Pull request merged**
