### PR TITLE
ARROW-5384: [Go] implement FixedSizeList array

### PR DESCRIPTION
**Pull request by sbinet**

### CODE REVIEW

**Comment by sbinet** [comment]
PTAL @stuartcarnie @alexandreyc

**Comment by sbinet** [comment]
ping? (I'd like to merge this in by Friday)

**Comment by wesm** [comment]
@sbinet note that Arrow is Commit-Then-Review so you can merge without an explicit +1

**Review by stuartcarnie — APPROVED** [review]
Lots of new code here, so I specifically looked for unit tests 👍

**Pull request closed without merging**
