### PR TITLE
GH-37381: [Python][CI][Packaging] Enable ORC for Pyarrow on Appveyor and Windows wheels

### LINKED ISSUE #37381: [Python][CI][Packaging] Enable ORC on Windows Appveyor CI and Windows wheels for pyarrow
### Describe the enhancement requested

As found on: https://github.com/apache/arrow/issues/36026#issuecomment-1691625160
It does seem we are not testing pyarrow with ORC enabled on Windows and we are not enabling it on our Windows  wheels.
We should enable it.

### Component(s)

Continuous Integration, Packaging, Python

### PR DESCRIPTION
**Pull request by raulcd**
### Rationale for this change

ORC on Windows wheels and CI should be enabled.

### What changes are included in this PR?

Enabling it on CI + our Windows wheels

### Are these changes tested?

On CI

### Are there any user-facing changes?

Yes, currently Windows wheels do not have ORC enabled. They should in the future.
It is not a breaking change.
* Closes: #37381

### CODE REVIEW

**Comment by raulcd** [comment]
@github-actions crossbow submit wheel-windows*

**Comment by raulcd** [comment]
@github-actions crossbow submit wheel-windows-cp310-amd64

**Comment by raulcd** [comment]
@github-actions crossbow submit wheel-windows-cp310-amd64

**Comment by raulcd** [comment]
@github-actions crossbow submit wheel-windows-cp310-amd64

**Comment by raulcd** [comment]
I am not sure why the wheel job is failing with (https://github.com/ursacomputing/crossbow/actions/runs/5997471725/job/16263918617#step:7:3778):
```
 C:/arrow/cpp/src/arrow/adapters/orc/adapter.cc(492): error C2100: illegal indirection (compiling source file C:\arrow-build\src\arrow\CMakeFiles\arrow_shared.dir\Unity\unity_26_cxx.cxx) [C:\arrow-build\src\arrow\arrow_shared.vcxproj]
 ```
The line that seems to fail is `StripeInformation stripe_info({0, 0, 0, 0});` from the following:
```
    if (!include_indices.empty()) {
      RETURN_NOT_OK(SelectIndices(&opts, include_indices));
    }
    StripeInformation stripe_info({0, 0, 0, 0});
    RETURN_NOT_OK(SelectStripeWithRowNumber(&opts, current_row_, &stripe_info));
    ARROW_ASSIGN_OR_RAISE(auto schema, ReadSchema(opts));
    std::unique_ptr<liborc::RowReader> row_reader;
```
https://github.com/apache/arrow/blob/main/cpp/src/arrow/adapters/orc/adapter.cc#L492

@wgtmac any idea?

**Comment by wgtmac** [comment]
> I am not sure why the wheel job is failing with (https://github.com/ursacomputing/crossbow/actions/runs/5997471725/job/16263918617#step:7:3778):
> 
> ```
>  C:/arrow/cpp/src/arrow/adapters/orc/adapter.cc(492): error C2100: illegal indirection (compiling source file C:\arrow-build\src\arrow\CMakeFiles\arrow_shared.dir\Unity\unity_26_cxx.cxx) [C:\arrow-build\src\arrow\arrow_shared.vcxproj]
> ```
> 
> The line that seems to fail is `StripeInformation stripe_info({0, 0, 0, 0});` from the following:
> 
> ```
>     if (!include_indices.empty()) {
>       RETURN_NOT_OK(SelectIndices(&opts, include_indices));
>     }
>     StripeInformation stripe_info({0, 0, 0, 0});
>     RETURN_NOT_OK(SelectStripeWithRowNumber(&opts, current_row_, &stripe_info));
>     ARROW_ASSIGN_OR_RAISE(auto schema, ReadSchema(opts));
>     std::unique_ptr<liborc::RowReader> row_reader;
> ```
> 
> https://github.com/apache/arrow/blob/main/cpp/src/arrow/adapters/orc/adapter.cc#L492
> 
> @wgtmac any idea?

This may be related. Let me try to add an inline comment.

**Comment by raulcd** [comment]
@github-actions crossbow submit wheel-windows-cp310-amd64

**Review by wgtmac — APPROVED** [review]

**Comment by raulcd** [comment]
@github-actions crossbow submit wheel-windows-cp310-amd64

**Comment by raulcd** [comment]
@github-actions crossbow submit wheel-windows-*

**Review by jorisvandenbossche — APPROVED** [review]
Looks good! (assuming the triggered builds will pass)

**Comment by wgtmac** [comment]
@jorisvandenbossche Do you have any idea on the backtrace: https://github.com/apache/arrow/issues/36026#issuecomment-1697519754 ?

**Comment by raulcd** [comment]
> @jorisvandenbossche Do you have any idea on the backtrace: [#36026 (comment)](https://github.com/apache/arrow/issues/36026#issuecomment-1697519754) ?

I am not sure why but the Appveyor tests are successful and I've double checked the orc tests are being executed: https://ci.appveyor.com/project/ApacheSoftwareFoundation/arrow/builds/47906815#L3544

**Comment by jorisvandenbossche** [comment]
Unfortunately those python stacktraces are mostly useless (it only indicates the the segfault happens when actually scanning the data (with `dataset.to_table()`), and so eg not in the dataset discovery, but that would also have been my guess). 
Ideally we would get an actual backtrace like I could get locally with gdb on linux (or enable catchsegv on CI), but I am not very familiar how to do that on Windows (and in CI).

**Comment by felipecrv** [comment]
Are the versions of protobuf used to build ORC and Arrow the same on Windows?

https://github.com/protocolbuffers/protobuf/issues/435#issuecomment-122145694

**Comment by pitrou** [comment]
@raulcd Do you want to revive this?

**Comment by raulcd** [comment]
Closing this in favor of: https://github.com/apache/arrow/pull/40609

**Pull request closed without merging**
