### PR TITLE
ARROW-1331: [JAVA] Refactor unit tests

### PR DESCRIPTION
**Pull request by siddharthteotia**
[cc @jacques-n , @StevenMPhillips ]

Refactored the java-vector unit tests in TestValueVector.java

(1) Moved all the BitVector related tests to TestBitVector.java
(2) Enhanced and added the tests for different vector types and grouped them into different categories in TestValueVector.java
(3) Moved https://github.com/dremio/dremio-oss/blob/master/sabot/kernel/src/test/java/com/dremio/exec/vector/TestSplitAndTransfer.java to arrow. This currently has splitAndTransfer() test for NullableVarCharVector. 
(4) No tests have been removed -- they have either been enhanced or moved around for grouping.

Recently we added splitAndTransfer tests for BitVector, UnionVector and ListVector in their respective test files.  We should ideally move all the splitAndTransfer() related tests to TestSplitAndTransfer.java and should try to cover other vector types as well. A follow-up will address this (I want to keep the patch size small for easy review).

### CODE REVIEW

**Comment by siddharthteotia** [comment]
Unit tests should not check for 0 values in fixed width vectors at positions where no data has been set. No assumption can be made about the value -- it is garbage.

**Comment by siddharthteotia** [comment]
Does this look good?

**Comment by siddharthteotia** [comment]
Can this be merged?

**Comment by wesm** [comment]
@icexelloss @jacques-n @StevenMPhillips can you take a look?

I would probably wait until after the 0.6.0 release vote is completed to merge more patches

**Comment by icexelloss** [comment]
I scan through the changes the it looks good. But this is particular hard to review line by line.

@siddharthteotia, is there anything in particular you want to be reviewed?

**Comment by jacques-n** [comment]
LGTM +1

**Pull request closed without merging**
