### PR TITLE
ARROW-3371: [Python] Remove check_metadata argument for Field.equals docstring

### PR DESCRIPTION
**Pull request by kszucs**

### CODE REVIEW

**Review by wesm — APPROVED** [review]
+1

**Comment by kszucs** [comment]
Do We want to introduce some sort of docstyle checker?

**Comment by wesm** [comment]
Is there a linting tool that will do that?

**Comment by kszucs** [comment]
[pydocstyle](https://github.com/PyCQA/pydocstyle) is the closest one with a flake8 plugin, but AFAIK it doesn't check e.g. missing documentation for a parameter http://www.pydocstyle.org/en/2.1.1/error_codes.html

**Pull request closed without merging**
