### PR TITLE
ARROW-6564: [Python] Do not require pandas for invoking Array.__array__

### PR DESCRIPTION
**Pull request by jorisvandenbossche**
https://issues.apache.org/jira/browse/ARROW-6564

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
Did it now for Array, if the approach seems OK also need to do it for ChunkedArray.

For all dtypes except dictionary type, `ConvertArrayToPandas` already returns a numpy array, so we can call this directly instead of going through `_to_pandas` (wrapping it in a Series) and unpacking the values again. 
Only for dictionary type, this returns a dict of the indices and dictionary values. I was first thinking of an option to `ConvertArrayToPandas` to convert a DictionaryArray to an dense array, but we can also easily create this dense array afterwards as done now in the PR. 
However, and in light of https://github.com/apache/arrow/pull/5398 (cc @wesm), the clear disadvantage of this simpler approach is that the created numpy array is then not in the arrow memory pool (while for all other dtypes they will be). So the option to `ConvertArrayToPandas` might be better?

**Review by wesm — APPROVED** [review]
+1

**Comment by jorisvandenbossche** [comment]
@wesm thoughts on the "not created in arrow's memory pool" consequence of creating the dense array in python? Or not worth the complexity to try to do this in the C++ conversion code?

**Comment by wesm** [comment]
Oh I missed that comment, sorry. Hmm. Might be worth opening an issue but it's unclear what the best option. Casting to Arrow-dense could end up being wasteful (in the case of strings), and implementing the conversion in C++ would be tedious. I'm inclined to let it go for now

**Pull request closed without merging**
