### PR TITLE
ARROW-1167: [Python] Support chunking string columns in Table.from_pandas

### PR DESCRIPTION
**Pull request by wesm**
This resolves the error with converting the dataset in ARROW-1167, which only takes up 4.5 GB in memory but has a single column with over 2GB in binary data.

The unit test for this is not run in CI because of large memory allocation, but can be run with 

```
py.test pyarrow --large_memory
```

cc @jeffknupp

### CODE REVIEW

**Comment by wesm** [comment]
The diff is large because I split `pandas_convert.cc` into two halves (pandas -> arrow and arrow -> pandas)

**Review by xhochy — APPROVED** [review]
+1, LGTM.

I assume that there were no large changes also in the pandas conversion code that I could miss?

**Comment by wesm** [comment]
Nope

**Comment by jeffknupp** [comment]
Fantastic! Thanks for taking this on @wesm

**Pull request closed without merging**
