### PR TITLE
GH-43394: [Java][Benchmarking] Fix Java benchmarks for Java 17+

### PR DESCRIPTION
**Pull request by danepitkin**
### Rationale for this change

Now that Arrow Java has moved from Java 8 -> Java 11, we need to add `--add-opens` when running Java.

### What changes are included in this PR?

* Add `--add-opens=java.base/java.nio=org.apache.arrow.memory.core,ALL-UNNAMED` to `_JAVA_OPTIONS` in archery.
* Clean up test code only used for Java 8

### Are these changes tested?

To be verified via CI and ursabot.

### Are there any user-facing changes?

No
* GitHub Issue: #43394

### CODE REVIEW

**Comment by danepitkin** [comment]
@ursabot please benchmark lang=Java

**Comment by danepitkin** [comment]
Benchmark run is successful: https://buildkite.com/apache-arrow/arrow-bci-benchmark-on-ec2-m5-4xlarge-us-east-2/builds/5025

**Review by vibhatha — APPROVED** [review]
Thanks @danepitkin, PR LGTM.

**Comment by vibhatha** [comment]
@danepitkin shall we run the crossbows as well?

**Comment by danepitkin** [comment]
@github-actions crossbow submit -g java

**Comment by danepitkin** [comment]
Thanks @vibhatha!

**Pull request merged**
