### PR TITLE
ARROW-6089: [Rust] [DataFusion]  Implement physical plan for "selection" operator

### PR DESCRIPTION
**Pull request by andygrove**
This PR implements the physical execution plan for the selection operator (the WHERE clause in a SQL query).

In order to have working tests, I also had to implement some subset of expressions (column reference, literal value, comparison expressions, and CAST). However, the goal of this PR is not to add complete support for all expressions but to implement the Selection operator. I will create separate JIRA/PRs for adding support for other expressions and data types in the physical query plan.

### CODE REVIEW

**Comment by andygrove** [comment]
@paddyhoran @sunchao @nevi-me This PR is now ready for review. PTAL when you can.

My stretch goal is to implement the aggregate operator as well in time for the 0.15 release if I can finish it this weekend. This would mean that people can start experimenting with parallel queries and then for the next release (1.0?) we can drop the code that directly executes the logical plan and change it to create the physical plan and execute that instead.

**Comment by andygrove** [comment]
@paddyhoran @sunchao @nevi-me This is my final PR that I'm hoping can make it into 0.15. I could break this out into smaller PRs by having separate PRs for the new expression types (literal, cast, binary) if that helps.

**Comment by andygrove** [comment]
It's probably too late to try and get this reviewed for 0.15.0 so I have started breaking this down into smaller PRs that are easier to review.

**Comment by paddyhoran** [comment]
@andygrove we might get it in.  I had started reviewing but am struggling to find time now.  Breaking it into smaller PR's definitely helps.

**Comment by andygrove** [comment]
OK thanks @paddyhoran 

I created the following PRs for the expressions:

https://github.com/apache/arrow/pull/5474
https://github.com/apache/arrow/pull/5477
https://github.com/apache/arrow/pull/5478

These PRs have more extensive tests too than this current PR so it was good to pull them out.

I'll need to rebase of course once those are merged.

**Comment by paddyhoran** [comment]
@andygrove can you rebase now please?

**Comment by andygrove** [comment]
@paddyhoran done!

**Review by paddyhoran — APPROVED** [review]
LGTM pending CI

**Comment by andygrove** [comment]
@paddyhoran Thanks so much for reviewing this late flood of PRs. I really appreciate it!

**Comment by paddyhoran** [comment]
Great job pushing the project forward.  The progress you are making is really exciting!

**Pull request closed without merging**
