### PR TITLE
ARROW-6431: [Python] Test suite fails without pandas installed

### PR DESCRIPTION
**Pull request by kszucs**

### CODE REVIEW

**Comment by kszucs** [comment]
@ursabot test docker-python-2.7-nopandas docker-python-3.6-nopandas

**Comment by kszucs** [comment]
@ursabot --help

**Comment by kszucs** [comment]
@ursabot crossbow test docker-python-2.7-nopandas docker-python-3.6-nopandas

**Comment by kszucs** [comment]
@ursabot crossbow test docker-python-2.7-nopandas docker-python-3.6-nopandas

**Comment by kszucs** [comment]
@ursabot crossbow test docker-python-2.7-nopandas docker-python-3.6-nopandas

**Review by wesm — APPROVED** [review]
+1

**Comment by wesm** [comment]
We should lift some testing utilities out of pandas so we aren't depending on it for trivial things like generating random strings

**Pull request closed without merging**
