### PR TITLE
ARROW-2124: [Python] Add test for empty item in array

### PR DESCRIPTION
**Pull request by xhochy**

### CODE REVIEW

**Comment by xhochy** [comment]
@pitrou your change detection script fails here, can you have a short look what the problem may be?

**Comment by pitrou** [comment]
@xhochy My guess is that you force-pushed in the meantime, for example after rebasing, and therefore the original changeset doesn't exist in the repo anymore? I will try to make this more robust.

**Comment by pitrou** [comment]
See https://github.com/apache/arrow/pull/1590

**Comment by wesm** [comment]
Rebased

**Review by wesm — APPROVED** [review]
+1

**Comment by xhochy** [comment]
@pitrou yes, I'm a frequent rebaser and force-pusher :D

**Comment by wesm** [comment]
Appveyor build running here https://ci.appveyor.com/project/xhochy/arrow/build/1.0.572. I will merge once that advances some more

**Comment by wesm** [comment]
thanks @xhochy!

**Pull request closed without merging**
