### PR TITLE
ARROW-7607: [C++] Example of using Arrow as a dependency of another CMake project

### PR DESCRIPTION
**Pull request by pitrou**

### CODE REVIEW

**Review by wesm — APPROVED** [review]
+1, this is great. I gave it a good read through and it all seems reasonable to me

**Comment by wesm** [comment]
I'll await @kszucs to have a look at the GHA / Docker configuration before merging

**Comment by kou** [comment]
CI doesn't work: https://github.com/apache/arrow/pull/7479/checks?check_run_id=784648188

It seems that we need `matrix.title`.

**Comment by kou** [comment]
> CI doesn't work: https://github.com/apache/arrow/pull/7479/checks?check_run_id=784648188
> 
> It seems that we need `matrix.title`.

Sorry. This is not related to this pull request.

**Comment by wesm** [comment]
I'm gonna go ahead and merge this. Thanks @pitrou !

**Pull request closed without merging**
