### PR TITLE
ARROW-2945: [Packaging] Update argument check

### PR DESCRIPTION
**Pull request by kou**
This is follow up change for #2341.

### CODE REVIEW

**Review by wesm — APPROVED** [review]
+1. I opened https://issues.apache.org/jira/browse/ARROW-2949 about the repo.continuum.io flake

**Comment by cpcloud** [comment]
Do this, #2344 and #2345 need to go into 0.10?

**Comment by cpcloud** [comment]
cc @kou @wesm

**Comment by cpcloud** [comment]
Ah, this one does for sure

**Comment by kszucs** [comment]
I'm testing the changes.

**Comment by kszucs** [comment]
`build-300` https://github.com/kszucs/crossbow/branches

**Comment by cpcloud** [comment]
image

**Comment by kszucs** [comment]
Leonidas would be glad: https://github.com/kszucs/crossbow/branches/all?utf8=%E2%9C%93&query=build-300

**Pull request closed without merging**
