### PR TITLE
ARROW-3898: [Example] parquet-arrow example has compilation errors

### PR DESCRIPTION
**Pull request by wangmiao1981**
When compiling example, reader-writer.cc, it shows following compilation errors:

no member named 'cout' in namespace 'std'

  PARQUET_THROW_NOT_OK(arrow::PrettyPrint(*array, 4, &std::cout));

in multiple places. 

Fix:
Add the #include<iostream>
Test:
make passed

### CODE REVIEW

**Comment by wesm** [comment]
I think we should be compiling these examples in Travis CI. Thoughts?

**Comment by wangmiao1981** [comment]
I can check how to do it in Travis CI. I don't know how to do it now.

**Comment by wesm** [comment]
You will have to invoke -DPARQUET_BUILD_EXAMPLES=ON when invoking CMake. Probably want to make it configurable with an environment variable so it is not hard coded. See .travis.yml and the ci/ directory

**Comment by wangmiao1981** [comment]
Thanks! I will do it in the weekend.

**Comment by wangmiao1981** [comment]
If I understand correctly, travis_before_script_cpp.sh has the following lines:
`if [ $ARROW_TRAVIS_PARQUET == "1" ]; then
  CMAKE_COMMON_FLAGS="$CMAKE_COMMON_FLAGS \
-DARROW_PARQUET=ON \
-DPARQUET_BUILD_EXAMPLES=ON \
-DPARQUET_BUILD_EXECUTABLES=ON"
fi`

I checked Travis CI output that it sets ARROW_TRAVIS_PARQUET to 1 at the beginning.

I am reading the code to understand why this failure is not caught by Travis.

**Comment by wangmiao1981** [comment]
Based on my test, -DPARQUET_BUILD_EXAMPLES=ON will not generate Makefile for example and will not build example.

**Comment by wesm** [comment]
OK, I'll have a look

**Review by wesm — APPROVED** [review]
+1, merge on green build

**Pull request closed without merging**
