### PR TITLE
ARROW-13923: [C++] Faster CSV chunker with long CSV cells

### PR DESCRIPTION
**Pull request by pitrou**

### CODE REVIEW

**Comment by pitrou** [comment]
@cyb70289

**Comment by pitrou** [comment]
Benchmarks here:
```
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Non-regressions: (9)
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
              benchmark        baseline       contender  change %                                                                                                                                                                 counters
ChunkCSVVehiclesExample   1.870 GiB/sec   4.570 GiB/sec   144.442     {'family_index': 4, 'per_family_instance_index': 0, 'run_name': 'ChunkCSVVehiclesExample', 'repetitions': 3, 'repetition_index': 2, 'threads': 1, 'iterations': 115}
  ChunkCSVStocksExample   1.686 GiB/sec   2.904 GiB/sec    72.238       {'family_index': 5, 'per_family_instance_index': 0, 'run_name': 'ChunkCSVStocksExample', 'repetitions': 3, 'repetition_index': 2, 'threads': 1, 'iterations': 557}
 ParseCSVFlightsExample 442.445 MiB/sec 529.812 MiB/sec    19.746      {'family_index': 8, 'per_family_instance_index': 0, 'run_name': 'ParseCSVFlightsExample', 'repetitions': 3, 'repetition_index': 2, 'threads': 1, 'iterations': 324}
ParseCSVVehiclesExample   2.694 GiB/sec   2.887 GiB/sec     7.147     {'family_index': 9, 'per_family_instance_index': 0, 'run_name': 'ParseCSVVehiclesExample', 'repetitions': 3, 'repetition_index': 0, 'threads': 1, 'iterations': 167}
  ParseCSVStocksExample   1.304 GiB/sec   1.396 GiB/sec     7.032      {'family_index': 10, 'per_family_instance_index': 0, 'run_name': 'ParseCSVStocksExample', 'repetitions': 3, 'repetition_index': 1, 'threads': 1, 'iterations': 442}
    ParseCSVQuotedBlock 811.253 MiB/sec 852.518 MiB/sec     5.087        {'family_index': 6, 'per_family_instance_index': 0, 'run_name': 'ParseCSVQuotedBlock', 'repetitions': 3, 'repetition_index': 2, 'threads': 1, 'iterations': 3487}
   ChunkCSVEscapedBlock   2.100 GiB/sec   2.187 GiB/sec     4.126       {'family_index': 1, 'per_family_instance_index': 0, 'run_name': 'ChunkCSVEscapedBlock', 'repetitions': 3, 'repetition_index': 0, 'threads': 1, 'iterations': 9857}
   ParseCSVEscapedBlock 627.081 MiB/sec 651.146 MiB/sec     3.838       {'family_index': 7, 'per_family_instance_index': 0, 'run_name': 'ParseCSVEscapedBlock', 'repetitions': 3, 'repetition_index': 1, 'threads': 1, 'iterations': 2870}
ChunkCSVNoNewlinesBlock       102.23985       98.118192    -4.031 {'family_index': 2, 'per_family_instance_index': 0, 'run_name': 'ChunkCSVNoNewlinesBlock', 'repetitions': 3, 'repetition_index': 1, 'threads': 1, 'iterations': 6830200}

----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Regressions: (2)
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
             benchmark      baseline       contender  change %                                                                                                                                                            counters
   ChunkCSVQuotedBlock 1.337 GiB/sec   1.225 GiB/sec    -8.341   {'family_index': 0, 'per_family_instance_index': 0, 'run_name': 'ChunkCSVQuotedBlock', 'repetitions': 3, 'repetition_index': 0, 'threads': 1, 'iterations': 5884}
ChunkCSVFlightsExample 1.309 GiB/sec 884.236 MiB/sec   -34.043 {'family_index': 3, 'per_family_instance_index': 0, 'run_name': 'ChunkCSVFlightsExample', 'repetitions': 3, 'repetition_index': 1, 'threads': 1, 'iterations': 985}
```

**Comment by cyb70289** [comment]
There's build error on Arm locally.

**Comment by cyb70289** [comment]
@github-actions crossbow submit conda-linux-gcc-py38-arm64

**Comment by pitrou** [comment]
Well, in any case, the benchmark numbers are not very good IMHO.

**Comment by pitrou** [comment]
The unity build failure should be fixed now.

Updated benchmarks (I'm not sure it's with the same compiler, sorry):
```
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Non-regressions: (11)
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
                  benchmark           baseline          contender  change %                                                                                                                                                                  counters
    ChunkCSVVehiclesExample      1.820 GiB/sec      5.060 GiB/sec   178.049      {'family_index': 4, 'per_family_instance_index': 0, 'run_name': 'ChunkCSVVehiclesExample', 'repetitions': 3, 'repetition_index': 0, 'threads': 1, 'iterations': 113}
      ChunkCSVStocksExample      1.614 GiB/sec      3.076 GiB/sec    90.595        {'family_index': 5, 'per_family_instance_index': 0, 'run_name': 'ChunkCSVStocksExample', 'repetitions': 3, 'repetition_index': 0, 'threads': 1, 'iterations': 536}
    ChunkCSVNoNewlinesBlock         103.458571         111.097835     7.384  {'family_index': 2, 'per_family_instance_index': 0, 'run_name': 'ChunkCSVNoNewlinesBlock', 'repetitions': 3, 'repetition_index': 2, 'threads': 1, 'iterations': 6745549}
TimestampConversionStrptime  22.623M items/sec  23.951M items/sec     5.869 {'family_index': 5, 'per_family_instance_index': 0, 'run_name': 'TimestampConversionStrptime', 'repetitions': 3, 'repetition_index': 0, 'threads': 1, 'iterations': 1563}
     ParseCSVFlightsExample    475.063 MiB/sec    502.881 MiB/sec     5.856       {'family_index': 8, 'per_family_instance_index': 0, 'run_name': 'ParseCSVFlightsExample', 'repetitions': 3, 'repetition_index': 2, 'threads': 1, 'iterations': 338}
        ChunkCSVQuotedBlock      1.539 GiB/sec      1.624 GiB/sec     5.510         {'family_index': 0, 'per_family_instance_index': 0, 'run_name': 'ChunkCSVQuotedBlock', 'repetitions': 3, 'repetition_index': 1, 'threads': 1, 'iterations': 6749}
      ParseCSVStocksExample      1.272 GiB/sec      1.297 GiB/sec     1.946       {'family_index': 10, 'per_family_instance_index': 0, 'run_name': 'ParseCSVStocksExample', 'repetitions': 3, 'repetition_index': 0, 'threads': 1, 'iterations': 426}
     ChunkCSVFlightsExample      1.274 GiB/sec      1.295 GiB/sec     1.643       {'family_index': 3, 'per_family_instance_index': 0, 'run_name': 'ChunkCSVFlightsExample', 'repetitions': 3, 'repetition_index': 0, 'threads': 1, 'iterations': 930}
    ParseCSVVehiclesExample      2.679 GiB/sec      2.706 GiB/sec     1.026      {'family_index': 9, 'per_family_instance_index': 0, 'run_name': 'ParseCSVVehiclesExample', 'repetitions': 3, 'repetition_index': 1, 'threads': 1, 'iterations': 167}
        ParseCSVQuotedBlock    831.659 MiB/sec    835.781 MiB/sec     0.496         {'family_index': 6, 'per_family_instance_index': 0, 'run_name': 'ParseCSVQuotedBlock', 'repetitions': 3, 'repetition_index': 0, 'threads': 1, 'iterations': 3533}
       ChunkCSVEscapedBlock      2.067 GiB/sec      2.063 GiB/sec    -0.218        {'family_index': 1, 'per_family_instance_index': 0, 'run_name': 'ChunkCSVEscapedBlock', 'repetitions': 3, 'repetition_index': 1, 'threads': 1, 'iterations': 9689}

--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Regressions: (1)
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
           benchmark           baseline         contender  change %                                                                                                                                                           counters
ParseCSVEscapedBlock    796.577 MiB/sec   636.487 MiB/sec   -20.097 {'family_index': 7, 'per_family_instance_index': 0, 'run_name': 'ParseCSVEscapedBlock', 'repetitions': 3, 'repetition_index': 1, 'threads': 1, 'iterations': 3434}
```

**Comment by pitrou** [comment]
The performance seems unfortunately fragile with this approach. Updated benchmark numbers (again):
```
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Non-regressions: (8)
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
              benchmark        baseline       contender  change %                                                                                                                                                                 counters
ChunkCSVVehiclesExample   1.814 GiB/sec   4.476 GiB/sec   146.729     {'family_index': 4, 'per_family_instance_index': 0, 'run_name': 'ChunkCSVVehiclesExample', 'repetitions': 3, 'repetition_index': 2, 'threads': 1, 'iterations': 112}
  ChunkCSVStocksExample   1.606 GiB/sec   2.531 GiB/sec    57.540       {'family_index': 5, 'per_family_instance_index': 0, 'run_name': 'ChunkCSVStocksExample', 'repetitions': 3, 'repetition_index': 0, 'threads': 1, 'iterations': 528}
ParseCSVVehiclesExample   2.643 GiB/sec   2.831 GiB/sec     7.087     {'family_index': 9, 'per_family_instance_index': 0, 'run_name': 'ParseCSVVehiclesExample', 'repetitions': 3, 'repetition_index': 1, 'threads': 1, 'iterations': 161}
   ParseCSVEscapedBlock 640.080 MiB/sec 658.864 MiB/sec     2.935       {'family_index': 7, 'per_family_instance_index': 0, 'run_name': 'ParseCSVEscapedBlock', 'repetitions': 3, 'repetition_index': 0, 'threads': 1, 'iterations': 3193}
  ParseCSVStocksExample   1.264 GiB/sec   1.290 GiB/sec     2.041      {'family_index': 10, 'per_family_instance_index': 0, 'run_name': 'ParseCSVStocksExample', 'repetitions': 3, 'repetition_index': 1, 'threads': 1, 'iterations': 422}
    ParseCSVQuotedBlock 830.836 MiB/sec 841.314 MiB/sec     1.261        {'family_index': 6, 'per_family_instance_index': 0, 'run_name': 'ParseCSVQuotedBlock', 'repetitions': 3, 'repetition_index': 1, 'threads': 1, 'iterations': 3601}
 ParseCSVFlightsExample 500.956 MiB/sec 488.740 MiB/sec    -2.438      {'family_index': 8, 'per_family_instance_index': 0, 'run_name': 'ParseCSVFlightsExample', 'repetitions': 3, 'repetition_index': 0, 'threads': 1, 'iterations': 361}
ChunkCSVNoNewlinesBlock       103.81689      100.649114    -3.051 {'family_index': 2, 'per_family_instance_index': 0, 'run_name': 'ChunkCSVNoNewlinesBlock', 'repetitions': 3, 'repetition_index': 1, 'threads': 1, 'iterations': 6787473}

----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Regressions: (3)
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
             benchmark      baseline       contender  change %                                                                                                                                                            counters
  ChunkCSVEscapedBlock 2.050 GiB/sec   1.763 GiB/sec   -13.988  {'family_index': 1, 'per_family_instance_index': 0, 'run_name': 'ChunkCSVEscapedBlock', 'repetitions': 3, 'repetition_index': 1, 'threads': 1, 'iterations': 9590}
   ChunkCSVQuotedBlock 1.531 GiB/sec   1.112 GiB/sec   -27.361   {'family_index': 0, 'per_family_instance_index': 0, 'run_name': 'ChunkCSVQuotedBlock', 'repetitions': 3, 'repetition_index': 0, 'threads': 1, 'iterations': 5129}
ChunkCSVFlightsExample 1.258 GiB/sec 921.435 MiB/sec   -28.494 {'family_index': 3, 'per_family_instance_index': 0, 'run_name': 'ChunkCSVFlightsExample', 'repetitions': 3, 'repetition_index': 0, 'threads': 1, 'iterations': 943}
```

**Comment by cyb70289** [comment]
Looks pretty good on Arm.

- neoverse n1, clang-12
```
-----------------------------------------------------------------
Non-regressions: (7)
-----------------------------------------------------------------
              benchmark        baseline       contender  change %
ChunkCSVVehiclesExample 848.964 MiB/sec   1.981 GiB/sec   138.966
  ChunkCSVStocksExample 636.249 MiB/sec   1.225 GiB/sec    97.133
ChunkCSVNoNewlinesBlock      208.615358      220.434134     5.665
   ParseCSVEscapedBlock 413.691 MiB/sec 420.424 MiB/sec     1.628
ParseCSVVehiclesExample   1.580 GiB/sec   1.595 GiB/sec     0.926
  ParseCSVStocksExample 969.519 MiB/sec 974.999 MiB/sec     0.565
   ChunkCSVEscapedBlock 722.624 MiB/sec 707.451 MiB/sec    -2.100

-----------------------------------------------------------------
Regressions: (4)
-----------------------------------------------------------------
             benchmark        baseline       contender  change % 
  counters
ParseCSVFlightsExample 337.860 MiB/sec 321.941 MiB/sec    -4.712 
ChunkCSVFlightsExample 553.033 MiB/sec 516.678 MiB/sec    -6.574 
   ParseCSVQuotedBlock 476.093 MiB/sec 437.121 MiB/sec    -8.186 
   ChunkCSVQuotedBlock 673.057 MiB/sec 599.014 MiB/sec   -11.001 
```

- m1, apple-clang-13
```
-----------------------------------------------------------------
Non-regressions: (10)
-----------------------------------------------------------------
              benchmark        baseline       contender  change %
ChunkCSVVehiclesExample   1.426 GiB/sec   4.745 GiB/sec   232.705
  ChunkCSVStocksExample   1.417 GiB/sec   2.779 GiB/sec    96.087
ChunkCSVNoNewlinesBlock       78.281786       79.915575     2.087
    ParseCSVQuotedBlock 515.396 MiB/sec 519.514 MiB/sec     0.799
 ParseCSVFlightsExample 485.565 MiB/sec 485.774 MiB/sec     0.043
   ParseCSVEscapedBlock 527.793 MiB/sec 528.017 MiB/sec     0.042
  ParseCSVStocksExample   1.422 GiB/sec   1.420 GiB/sec    -0.120
ParseCSVVehiclesExample   2.619 GiB/sec   2.592 GiB/sec    -1.054
   ChunkCSVEscapedBlock   1.614 GiB/sec   1.587 GiB/sec    -1.667
 ChunkCSVFlightsExample   1.200 GiB/sec   1.177 GiB/sec    -1.940

-----------------------------------------------------------------
Regressions: (1)
-----------------------------------------------------------------
          benchmark      baseline     contender  change %        
ChunkCSVQuotedBlock 1.510 GiB/sec 1.403 GiB/sec    -7.139
```

**Review by cyb70289 — APPROVED** [review]
LGTM

**Pull request closed without merging**
