### PR TITLE
[Release] Verify 2.0.0-rc2

### PR DESCRIPTION
**Pull request by kszucs**

### CODE REVIEW

**Comment by kszucs** [comment]
@github-actions crossbow submit -g verify-rc

**Comment by kszucs** [comment]
@github-actions crossbow submit -g verify-rc

**Comment by kszucs** [comment]
@github-actions crossbow submit -g verify-rc

**Comment by kszucs** [comment]
@github-actions crossbow submit verify-rc-binaries-yum

**Comment by nealrichardson** [comment]
JS is failing, and integration tests because of the JS failure: 

```
> NODE_NO_WARNINGS=1 gulp test

[19:25:03] Using gulpfile /tmp/arrow-2.0.0.KglPB/apache-arrow-2.0.0/js/gulpfile.js
[19:25:03] Starting 'test'...
[19:25:03] Starting 'test:ts'...
ts-jest[config] (WARN) There is a mismatch between your NodeJs version v12.18.4 and your TypeScript target esnext. This might lead to some unexpected errors when running tests with `ts-jest`. To fix this, you can check https://github.com/microsoft/TypeScript/wiki/Node-Target-Mapping

  ● should close the underlying NodeJS ReadableStream when reading multiple tables and we break early

    expect(received).toBe(expected) // Object.is equality

    Expected: false
    Received: true

      218 | function validateStreamState(reader: RecordBatchReader, stream: NodeJS.ReadableStream, closed: boolean, readable = !closed) {
      219 |     expect(reader.closed).toBe(closed);
    > 220 |     expect(Boolean(stream.readable)).toBe(readable);
          |                                      ^
      221 |     expect(Boolean((stream as any).destroyed)).toBe(closed);
      222 |     expect(Boolean((stream as any).readableFlowing)).toBe(false);
      223 | }

      at validateStreamState (test/unit/ipc/reader/streams-node-tests.ts:220:38)
      at Object.<anonymous> (test/unit/ipc/reader/streams-node-tests.ts:213:9)
          at runMicrotasks (<anonymous>)

[19:26:13] 'test:ts' errored after 1.17 min
[19:26:13] Error: exited with error code: 1
    at ChildProcess.onexit (/tmp/arrow-2.0.0.KglPB/apache-arrow-2.0.0/js/node_modules/end-of-stream/index.js:40:36)
    at ChildProcess.emit (events.js:315:20)
    at ChildProcess.EventEmitter.emit (domain.js:506:15)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
    at Process.callbackTrampoline (internal/async_hooks.js:120:14)
[19:26:13] 'test' errored after 1.17 min
```

Is this a real error or a setup problem?

**Pull request closed without merging**
