### PR TITLE
ARROW-9277: [C++] Fix docs of reading CSV files

### PR DESCRIPTION
**Pull request by crcrpar**
Hi,

This is my first PR for this awesome project. So if I do not follow the workflow, could you tell me, please?

In this PR, I aim at fixing https://arrow.apache.org/docs/cpp/csv.html?highlight=csv%20c#basic-usage as I found the example not working in my environment (arrow v0.17.1).

### CODE REVIEW

**Comment by pitrou** [comment]
Thank you for spotting this and suggesting a fix! I will make a couple changes to your suggestion.

**Comment by pitrou** [comment]
@crcrpar  Do you think the version I pushed is ok and clear enough?

**Comment by crcrpar** [comment]
@pitrou My pleasure :smiley: 

Yes, I think so as the use of `arrow::Result` in my commits might be confusing.

**Comment by pitrou** [comment]
Thank you for your contribution. Please don't hesitate to report other doc problems.

**Comment by crcrpar** [comment]
I'm so impressed by your quick response! Thanks!

**Pull request closed without merging**
