### PR TITLE
ARROW-4013: [Docs][C++] Add how to build on MSYS2

### PR DESCRIPTION
**Pull request by kou**

### CODE REVIEW

**Comment by kou** [comment]
Don't merge this for now. We need to write more.
This is just for https://github.com/apache/arrow/pull/3464#issuecomment-457970673 .

**Comment by jeroen** [comment]
Why are you not using your `mingw-w64-arrow` package? Isn't it much easier for users to build using the packaged setup and simply run `mingw-w64` ?

**Comment by kou** [comment]
This is a document for build from source. It's for advanced users who need a custom build option or develop Apache Arrow.
We need to write a document for average users as a separated document: https://issues.apache.org/jira/browse/ARROW-4012

**Comment by wesm** [comment]
Yes, it's important that we have clear source build instructions for people who want to contribute patches to the project

**Comment by wesm** [comment]
@kou how far are these instructions from being complete? This can be moved to docs/source/developers/cpp.rst

**Comment by kou** [comment]
I've moved to `docs/source/developers/cpp.rst`. I need to test the instruction.

**Comment by kou** [comment]
Done.
Now, this is ready to review.

**Review by wesm — APPROVED** [review]
+1. Thanks @kou!

**Pull request closed without merging**
