### PR TITLE
ARROW-17715: [CI][C++] reduce the parallelism for cmake

### PR DESCRIPTION
**Pull request by kiszk**
Current setting causes timeout during C++ compilation.

### CODE REVIEW

**Comment by kiszk** [comment]
Why do these two job cause time-out at different points?

https://app.travis-ci.com/github/apache/arrow/jobs/583166216#L2767-L2771

https://app.travis-ci.com/github/apache/arrow/jobs/583241288#L2774-L2779

**Comment by pitrou** [comment]
I have no idea. I'm afraid the s390x workers on Travis-CI are generally unreliable.

**Comment by kou** [comment]
It seems that the s390x workers on Travis CI don't have enough resource to build gRPC and Gandiva stably. How about disabling Flight and Gandiva?

**Comment by kiszk** [comment]
Thanks, let me disable some components one by one.

**Comment by kiszk** [comment]
I just found another (possible) solution [`travis_wait n`](https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received)

**Comment by kiszk** [comment]
`travis_wait` workaround allows us to finish build. On the other hand, CI found on failure.
```
33/75 Test #36: arrow-compute-asof-join-node-test .........***Failed    1.25 sec
Running arrow-compute-asof-join-node-test, redirecting output into /build/cpp/build/test-logs/arrow-compute-asof-join-node-test.txt (attempt 1/1)
/arrow/cpp/build-support/run-test.sh: line 88: 30112 Aborted                 (core dumped) $TEST_EXECUTABLE "$@" > $LOGFILE.raw 2>&1
```

[This assertion|https://github.com/apache/arrow/blob/master/cpp/src/arrow/compute/exec/util.cc#L35] causes the failure. I will address this in another PR.

**Comment by kou** [comment]
ARROW-17696 may be related.

**Comment by kou** [comment]
`travis_wait` may be a workaround but it took "1 hr 16 min 35 sec": https://app.travis-ci.com/github/apache/arrow/jobs/584275937

It seems that we should disable some heavy components to reduce build time...

**Comment by kiszk** [comment]
I see. Now, the latest master always cause the timeout error during the compilation
https://app.travis-ci.com/github/apache/arrow/jobs/585223287
https://app.travis-ci.com/github/apache/arrow/jobs/585228716

```
[56/317] Performing download step (download, verify and extract) for 'grpc_ep'
-- grpc_ep download command succeeded.  See also /build/cpp/grpc_ep-prefix/src/grpc_ep-stamp/grpc_ep-download-*.log
[57/317] No update step for 'grpc_ep'
[58/317] No patch step for 'grpc_ep'
[59/317] Performing configure step for 'grpc_ep'
-- grpc_ep configure command succeeded.  See also /build/cpp/grpc_ep-prefix/src/grpc_ep-stamp/grpc_ep-configure-*.log
[60/317] Performing build step for 'opentelemetry_ep'
-- opentelemetry_ep build command succeeded.  See also /build/cpp/opentelemetry_ep-prefix/src/opentelemetry_ep-stamp/opentelemetry_ep-build-*.log
[61/317] Performing install step for 'opentelemetry_ep'
-- opentelemetry_ep install command succeeded.  See also /build/cpp/opentelemetry_ep-prefix/src/opentelemetry_ep-stamp/opentelemetry_ep-install-*.log
[62/317] Completed 'opentelemetry_ep'
[63/317] Generating arithmetic_ops.bc
[64/317] Generating bitmap.bc
[65/317] Generating decimal_ops.bc
[66/317] Generating decimal_wrapper.bc
[67/317] Generating extended_math_ops.bc
[68/317] Generating hash.bc
[69/317] Generating print.bc
[70/317] Generating string_ops.bc
[71/317] Generating time.bc
[72/317] Generating timestamp_arithmetic.bc
[73/317] Generating basic_decimal.bc
[74/317] Generating ../irhelpers.bc
[75/317] Generating ../precompiled_bitcode.cc

No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.

Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received

The build has been terminated
```

**Comment by kiszk** [comment]
#15266 follows this issue.

**Pull request closed without merging**
