### PR TITLE
GH-33616: [C++] Reorder group_by so that keys/segment keys come before aggregates

### LINKED ISSUE #33616: [C++] Group_By from Substrait Shuffles Column Names
### Describe the bug, including details regarding any error messages, version, and platform.

When using a Substrait plan that includes a group_by at the end, it appears that the resulting table will have correct results, but the columns have their names shuffled. This occurs on nightly Arrow 11.0.0.dev406, and a reproducer is included below. The plan in question is included in blob form in the reproducer, but comes from the following Ibis code: 

```
total_population = countries2['population'].sum().name('total_population')
ex_expr = countries2.group_by('continent').aggregate(
    [total_population, countries2['area_km2'].mean().name('average_area')]
)
```

The particular error is as follows: instead of the continent column storing continents in the output table, it stores total population. The total population column stores average area, and the average area column stores continents. This is interpretable, but likely problematic if this table is meant for ingestion elsewhere. 

Reproducer:

```
import pyarrow as pa
import pyarrow.substrait as substrait
​
tab = pa.Table.from_pydict({
    "iso_alpha2": ["x", "y"],
    "iso_alpha3": ["a", "b"],
    "iso_numeric": [1, 2],
    "fips": ["aa", "bb"],
    "name": ["xx", "yy"],
    "capital": ["Olympia", "Denver"],
    "area_km2": [100.1, 200.1],
    "population": [1000, 2000],
    "continent": ["NA", "NA"]
    })
​
def table_provider(names):
    if len(names) == 1 and names[0] == "countries2":
        return tab
    raise Error(f"Unexpected table name: {names}")
​
query = b'\n\x02\x08\x01\x12\x0b\x1a\t\x08\x01\x10\x01\x1a\x03sum\x12\x0b\x1a\t\x08\x01\x10\x02\x1a\x03avg\x1a\xaa\x02\x12\xa7\x02\n\xf9\x01"\xf6\x01\x12\xad\x01\n\xaa\x01\n\x02\n\x00\x12\x95\x01\n\niso_alpha2\n\niso_alpha3\n\x0biso_numeric\n\x04fips\n\x04name\n\x07capital\n\x08area_km2\n\npopulation\n\tcontinent\x128\n\x04b\x02\x10\x01\n\x04b\x02\x10\x01\n\x04*\x02\x10\x01\n\x04b\x02\x10\x01\n\x04b\x02\x10\x01\n\x04b\x02\x10\x01\n\x04Z\x02\x10\x01\n\x04*\x02\x10\x01\n\x04b\x02\x10\x01\x18\x02:\x0c\n\ncountries2\x1a\x0c\n\n\x12\x08\n\x04\x12\x02\x08\x08"\x00"\x1a\n\x18\x08\x01 \x03*\x04:\x02\x10\x01:\x0c\x1a\n\x12\x08\n\x04\x12\x02\x08\x07"\x00"\x1a\n\x18\x08\x02 \x03*\x04Z\x02\x10\x01:\x0c\x1a\n\x12\x08\n\x04\x12\x02\x08\x06"\x00\x12\tcontinent\x12\x10total_population\x12\x0caverage_area'
​
result = substrait.run_query(query, table_provider=table_provider)
​
print(result.read_all())
​
# pyarrow.Table
# continent: int64
# total_population: double
# average_area: string
# ----
# continent: [[3000]]
# total_population: [[150.1]]
# average_area: [["NA"]]
```

### Component(s)

C++

### PR DESCRIPTION
**Pull request by westonpace**
* Closes: #33616

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
The failures in the doc build are because the docstring examples in `TableGroupBy.aggregate` in table.pxi need to be updated as well (those examples are validated)

**Comment by westonpace** [comment]
@nealrichardson R is currently failing, I think, because it is already reordering columns to get the desired behavior.  Would you have a chance to take a look and back out that code?  If not, I can try and look at it later.

**Comment by nealrichardson** [comment]
Sure, I can take a look

**Comment by kou** [comment]
It seems that we need to update more tests for GLib/Ruby.
Can I push changes for it to this branch directly?

**Comment by kou** [comment]
Done!

**Comment by westonpace** [comment]
CI failures are unrelated (and these tests were passing before the acero refactor was rebased).  I'm going to go ahead and merge this.

**Pull request merged**
