### PR TITLE
ARROW-1214: [Python/C++] Add C++ functionality to more easily handle encapsulated IPC messages, Python bindings

### PR DESCRIPTION
**Pull request by wesm**
This patch does a bunch of things:

* Decouples the RecordBatchStreamReader from the actual message iteration (which is handled by a new `arrow::ipc::MessageReader` interface
* Enables `arrow::ipc::Message` to hold all of the memory for a complete unit of data: metadata plus body
* Renames some IPC methods for better consistency (GetNextRecordBatch -> ReadNextRecordBatch)
* Adds function to serialize a complete encapsulated message to an `arrow::io::OutputStream*
* Add Python bindings for all of the above, introduce `pyarrow.Message`, `pyarrow.MessageReader`. Add `read_message` and `Message.serialize` functions for efficient memory round trips
* Add `pyarrow.read_record_batch` for reading a single record batch given a message and a known schema

Later we will want to add `pyarrow.read_schema`, but it seemed like a bit of work to make it work for dictionaries.

This implements the C++ analogue to ARROW-1047, which was for Java. Not sure why I didn't create a JIRA about this. cc @icexelloss

### CODE REVIEW

**Comment by wesm** [comment]
@jacques-n @julienledem @elahrvivaz @nongli @icexelloss @BryanCutler we may want to do some similar work (making handling `Message` objects a little easier) in Java, possibly in conjunction with creating a prototype REST interface (where the stream messages may come across as as single record batches given a previously negotiated schema). 

The idea is that this allows us to do schema negotiation separate from record batch reads, then you can separately receive a stream of record batches to reconstruct. So in Python you would have:

```python
schema = protocol.get_schema()
while True:
    message = protocol.get_next_message()
    batch = pyarrow.read_record_batch(message, schema)
```

Prior to this, the stream reader would have expected to read framed (length-prefixed metadata, with length-0 for EOS) messages from an InputStream, so this decouples things a bit.

**Comment by wesm** [comment]
cc @leifwalsh

**Review by xhochy — APPROVED** [review]
+1, LGTM

**Comment by wesm** [comment]
Rebased, will await build

**Comment by nongli** [comment]
@wesm The python snippet you included looks like what the stream should support. I'm not sure what I follow was missing?

**Comment by wesm** [comment]
Right, but the issue is that the Java stream reader expects an InputStream-like object:

https://github.com/apache/arrow/blob/master/java/vector/src/main/java/org/apache/arrow/vector/stream/ArrowStreamReader.java#L41

The idea is to decouple the input stream message framing from the conversion of messages into record batches. So the `ArrowStreamReader` would accept a "message iterator" object but otherwise be agnostic to how the data comes into memory. 

This is what did in C++ https://github.com/apache/arrow/blob/master/cpp/src/arrow/ipc/reader.h#L74 (though the doxygen comments are out of date)

**Comment by BryanCutler** [comment]
@wesm , I'd really like to see this type of interface in the Java side too.  I made https://issues.apache.org/jira/browse/ARROW-1232 to track this and I'll look into it as soon as I can, thanks!

**Pull request closed without merging**
