### PR TITLE
ARROW-5608: [C++][parquet] Fix invalid memory access when using parquet::arrow::ColumnReader

### PR DESCRIPTION
**Pull request by hatemhelal**
This fix appears to resolve the ASAN failures detected by this [gist](https://gist.github.com/hatemhelal/892e76a48e5b372f0e28a34403893ddd#file-reader-writer-cc-L130). 

This invalid memory access is only observed when:

* The `batch_size` is smaller than the row group
* There are zero repetition levels.

Included with this patch is a type parameterized unittest (might be overkill) that I've qualified on macOS.

### CODE REVIEW

**Comment by hatemhelal** [comment]
I've tested this out to the best of my ability locally.  @fsaintjacques, let me know if this looks alright to you / passes ASAN on your system.

**Comment by fsaintjacques** [comment]
Tested locally, ASAN detects the bug with the unit test and is fixed properly.

**Review by wesm — APPROVED** [review]
+1

**Comment by wesm** [comment]
The parameterized test might be overkill, but it's OK for now (in general we will need to improve performance of this test suite at some point)

**Pull request closed without merging**
