### PR TITLE
ARROW-10790: [C++] Improve ChunkedArray and Table sort_indices performance

### PR DESCRIPTION
**Pull request by pitrou**
- Fix ChunkedArray merge-sort pass to be O(n * log(num_chunks)), not O(n * num_chunks)
- Optimize chunked indexing
- Optimize chunk merging

This produces speedups of up to 1300% on Table sorting and up to 280% on ChunkedArray sorting.

### CODE REVIEW

**Comment by pitrou** [comment]
TODO: perhaps try to reuse the temporary merge buffer (which is implicitly allocated in `std::inplace_merge`).

**Comment by pitrou** [comment]
Micro-benchmarks:
```
                                                        benchmark            baseline           contender  change %                                                                                                                                                                                                 counters
44    TableSortIndicesInt64Narrow/1048576/100/1/32/min_time:1.000    2.133m items/sec   24.862m items/sec  1065.630                             {'run_name': 'TableSortIndicesInt64Narrow/1048576/100/1/32/min_time:1.000', 'run_type': 'iteration', 'repetitions': 0, 'repetition_index': 0, 'threads': 1, 'iterations': 3}
59      TableSortIndicesInt64Narrow/1048576/0/1/32/min_time:1.000    2.699m items/sec   28.849m items/sec   968.988                               {'run_name': 'TableSortIndicesInt64Narrow/1048576/0/1/32/min_time:1.000', 'run_type': 'iteration', 'repetitions': 0, 'repetition_index': 0, 'threads': 1, 'iterations': 4}
5       TableSortIndicesInt64Wide/1048576/100/1/32/min_time:1.000    1.316m items/sec    4.424m items/sec   236.134                               {'run_name': 'TableSortIndicesInt64Wide/1048576/100/1/32/min_time:1.000', 'run_type': 'iteration', 'repetitions': 0, 'repetition_index': 0, 'threads': 1, 'iterations': 2}
72        TableSortIndicesInt64Wide/1048576/0/1/32/min_time:1.000    1.826m items/sec    5.599m items/sec   206.656                                 {'run_name': 'TableSortIndicesInt64Wide/1048576/0/1/32/min_time:1.000', 'run_type': 'iteration', 'repetitions': 0, 'repetition_index': 0, 'threads': 1, 'iterations': 2}
0   ChunkedArraySortIndicesInt64Narrow/1048576/100/min_time:1.000     120.338 MiB/sec     321.258 MiB/sec   166.963    {'run_name': 'ChunkedArraySortIndicesInt64Narrow/1048576/100/min_time:1.000', 'run_type': 'iteration', 'repetitions': 0, 'repetition_index': 0, 'threads': 1, 'iterations': 169, 'null_percent': 1.0}
78  ChunkedArraySortIndicesInt64Narrow/8388608/100/min_time:1.000     102.519 MiB/sec     244.470 MiB/sec   138.464     {'run_name': 'ChunkedArraySortIndicesInt64Narrow/8388608/100/min_time:1.000', 'run_type': 'iteration', 'repetitions': 0, 'repetition_index': 0, 'threads': 1, 'iterations': 18, 'null_percent': 1.0}
22        ChunkedArraySortIndicesInt64Wide/32768/1/min_time:1.000     439.158 MiB/sec     932.084 MiB/sec   112.243      {'run_name': 'ChunkedArraySortIndicesInt64Wide/32768/1/min_time:1.000', 'run_type': 'iteration', 'repetitions': 0, 'repetition_index': 0, 'threads': 1, 'iterations': 19050, 'null_percent': 100.0}
73      ChunkedArraySortIndicesInt64Narrow/32768/1/min_time:1.000     447.550 MiB/sec     930.928 MiB/sec   108.006    {'run_name': 'ChunkedArraySortIndicesInt64Narrow/32768/1/min_time:1.000', 'run_type': 'iteration', 'repetitions': 0, 'repetition_index': 0, 'threads': 1, 'iterations': 20101, 'null_percent': 100.0}
62      TableSortIndicesInt64Narrow/1048576/0/2/32/min_time:1.000    1.107m items/sec    1.807m items/sec    63.207                               {'run_name': 'TableSortIndicesInt64Narrow/1048576/0/2/32/min_time:1.000', 'run_type': 'iteration', 'repetitions': 0, 'repetition_index': 0, 'threads': 1, 'iterations': 2}
13    TableSortIndicesInt64Narrow/1048576/100/2/32/min_time:1.000    1.071m items/sec    1.733m items/sec    61.860                             {'run_name': 'TableSortIndicesInt64Narrow/1048576/100/2/32/min_time:1.000', 'run_type': 'iteration', 'repetitions': 0, 'repetition_index': 0, 'threads': 1, 'iterations': 2}
3       ChunkedArraySortIndicesInt64Narrow/32768/2/min_time:1.000     102.739 MiB/sec     163.490 MiB/sec    59.131      {'run_name': 'ChunkedArraySortIndicesInt64Narrow/32768/2/min_time:1.000', 'run_type': 'iteration', 'repetitions': 0, 'repetition_index': 0, 'threads': 1, 'iterations': 4584, 'null_percent': 50.0}
34     TableSortIndicesInt64Narrow/1048576/0/16/32/min_time:1.000  783.665k items/sec    1.209m items/sec    54.262                              {'run_name': 'TableSortIndicesInt64Narrow/1048576/0/16/32/min_time:1.000', 'run_type': 'iteration', 'repetitions': 0, 'repetition_index': 0, 'threads': 1, 'iterations': 1}
63     ChunkedArraySortIndicesInt64Narrow/32768/10/min_time:1.000      68.848 MiB/sec     105.515 MiB/sec    53.257     {'run_name': 'ChunkedArraySortIndicesInt64Narrow/32768/10/min_time:1.000', 'run_type': 'iteration', 'repetitions': 0, 'repetition_index': 0, 'threads': 1, 'iterations': 3077, 'null_percent': 10.0}
66    ChunkedArraySortIndicesInt64Narrow/32768/100/min_time:1.000      64.576 MiB/sec      98.275 MiB/sec    52.184     {'run_name': 'ChunkedArraySortIndicesInt64Narrow/32768/100/min_time:1.000', 'run_type': 'iteration', 'repetitions': 0, 'repetition_index': 0, 'threads': 1, 'iterations': 2870, 'null_percent': 1.0}
38      TableSortIndicesInt64Narrow/1048576/0/8/32/min_time:1.000  781.772k items/sec    1.179m items/sec    50.851                               {'run_name': 'TableSortIndicesInt64Narrow/1048576/0/8/32/min_time:1.000', 'run_type': 'iteration', 'repetitions': 0, 'repetition_index': 0, 'threads': 1, 'iterations': 1}
9     TableSortIndicesInt64Narrow/1048576/100/8/32/min_time:1.000  754.758k items/sec    1.130m items/sec    49.722                             {'run_name': 'TableSortIndicesInt64Narrow/1048576/100/8/32/min_time:1.000', 'run_type': 'iteration', 'repetitions': 0, 'repetition_index': 0, 'threads': 1, 'iterations': 1}
20        ChunkedArraySortIndicesInt64Wide/32768/2/min_time:1.000      92.991 MiB/sec     138.236 MiB/sec    48.655        {'run_name': 'ChunkedArraySortIndicesInt64Wide/32768/2/min_time:1.000', 'run_type': 'iteration', 'repetitions': 0, 'repetition_index': 0, 'threads': 1, 'iterations': 4157, 'null_percent': 50.0}
79   TableSortIndicesInt64Narrow/1048576/100/16/32/min_time:1.000  757.200k items/sec    1.126m items/sec    48.648                            {'run_name': 'TableSortIndicesInt64Narrow/1048576/100/16/32/min_time:1.000', 'run_type': 'iteration', 'repetitions': 0, 'repetition_index': 0, 'threads': 1, 'iterations': 1}
36     TableSortIndicesInt64Wide/1048576/100/16/32/min_time:1.000    1.999m items/sec    2.970m items/sec    48.620                              {'run_name': 'TableSortIndicesInt64Wide/1048576/100/16/32/min_time:1.000', 'run_type': 'iteration', 'repetitions': 0, 'repetition_index': 0, 'threads': 1, 'iterations': 3}
10      TableSortIndicesInt64Wide/1048576/100/8/32/min_time:1.000    1.995m items/sec    2.956m items/sec    48.157                               {'run_name': 'TableSortIndicesInt64Wide/1048576/100/8/32/min_time:1.000', 'run_type': 'iteration', 'repetitions': 0, 'repetition_index': 0, 'threads': 1, 'iterations': 3}
2       ChunkedArraySortIndicesInt64Narrow/32768/0/min_time:1.000      88.551 MiB/sec     130.972 MiB/sec    47.905       {'run_name': 'ChunkedArraySortIndicesInt64Narrow/32768/0/min_time:1.000', 'run_type': 'iteration', 'repetitions': 0, 'repetition_index': 0, 'threads': 1, 'iterations': 3955, 'null_percent': 0.0}
65      TableSortIndicesInt64Wide/1048576/100/2/32/min_time:1.000    2.003m items/sec    2.959m items/sec    47.703                               {'run_name': 'TableSortIndicesInt64Wide/1048576/100/2/32/min_time:1.000', 'run_type': 'iteration', 'repetitions': 0, 'repetition_index': 0, 'threads': 1, 'iterations': 3}
71        TableSortIndicesInt64Wide/1048576/0/8/32/min_time:1.000    2.033m items/sec    3.003m items/sec    47.700                                 {'run_name': 'TableSortIndicesInt64Wide/1048576/0/8/32/min_time:1.000', 'run_type': 'iteration', 'repetitions': 0, 'repetition_index': 0, 'threads': 1, 'iterations': 3}
74       TableSortIndicesInt64Wide/1048576/0/16/32/min_time:1.000    2.039m items/sec    3.006m items/sec    47.438                                {'run_name': 'TableSortIndicesInt64Wide/1048576/0/16/32/min_time:1.000', 'run_type': 'iteration', 'repetitions': 0, 'repetition_index': 0, 'threads': 1, 'iterations': 3}
57        TableSortIndicesInt64Wide/1048576/0/2/32/min_time:1.000    2.039m items/sec    3.005m items/sec    47.385                                 {'run_name': 'TableSortIndicesInt64Wide/1048576/0/2/32/min_time:1.000', 'run_type': 'iteration', 'repetitions': 0, 'repetition_index': 0, 'threads': 1, 'iterations': 3}
19  ChunkedArraySortIndicesInt64Narrow/32768/10000/min_time:1.000      88.546 MiB/sec     129.714 MiB/sec    46.494  {'run_name': 'ChunkedArraySortIndicesInt64Narrow/32768/10000/min_time:1.000', 'run_type': 'iteration', 'repetitions': 0, 'repetition_index': 0, 'threads': 1, 'iterations': 3948, 'null_percent': 0.01}
35       ChunkedArraySortIndicesInt64Wide/32768/10/min_time:1.000      56.348 MiB/sec      79.952 MiB/sec    41.889       {'run_name': 'ChunkedArraySortIndicesInt64Wide/32768/10/min_time:1.000', 'run_type': 'iteration', 'repetitions': 0, 'repetition_index': 0, 'threads': 1, 'iterations': 2522, 'null_percent': 10.0}
32      ChunkedArraySortIndicesInt64Wide/32768/100/min_time:1.000      52.131 MiB/sec      72.898 MiB/sec    39.836       {'run_name': 'ChunkedArraySortIndicesInt64Wide/32768/100/min_time:1.000', 'run_type': 'iteration', 'repetitions': 0, 'repetition_index': 0, 'threads': 1, 'iterations': 2301, 'null_percent': 1.0}
40    ChunkedArraySortIndicesInt64Wide/1048576/100/min_time:1.000      43.276 MiB/sec      56.738 MiB/sec    31.108       {'run_name': 'ChunkedArraySortIndicesInt64Wide/1048576/100/min_time:1.000', 'run_type': 'iteration', 'repetitions': 0, 'repetition_index': 0, 'threads': 1, 'iterations': 61, 'null_percent': 1.0}
75    ChunkedArraySortIndicesInt64Wide/32768/10000/min_time:1.000      73.439 MiB/sec      96.212 MiB/sec    31.009    {'run_name': 'ChunkedArraySortIndicesInt64Wide/32768/10000/min_time:1.000', 'run_type': 'iteration', 'repetitions': 0, 'repetition_index': 0, 'threads': 1, 'iterations': 3285, 'null_percent': 0.01}
11        ChunkedArraySortIndicesInt64Wide/32768/0/min_time:1.000      74.006 MiB/sec      96.199 MiB/sec    29.987         {'run_name': 'ChunkedArraySortIndicesInt64Wide/32768/0/min_time:1.000', 'run_type': 'iteration', 'repetitions': 0, 'repetition_index': 0, 'threads': 1, 'iterations': 3313, 'null_percent': 0.0}
14    ChunkedArraySortIndicesInt64Wide/8388608/100/min_time:1.000      37.004 MiB/sec      46.574 MiB/sec    25.863        {'run_name': 'ChunkedArraySortIndicesInt64Wide/8388608/100/min_time:1.000', 'run_type': 'iteration', 'repetitions': 0, 'repetition_index': 0, 'threads': 1, 'iterations': 6, 'null_percent': 1.0}
46     TableSortIndicesInt64Narrow/1048576/100/1/4/min_time:1.000   39.643m items/sec   49.753m items/sec    25.505                             {'run_name': 'TableSortIndicesInt64Narrow/1048576/100/1/4/min_time:1.000', 'run_type': 'iteration', 'repetitions': 0, 'repetition_index': 0, 'threads': 1, 'iterations': 52}
[...]
41         TableSortIndicesInt64Wide/1048576/0/2/1/min_time:1.000    5.833m items/sec    4.302m items/sec   -26.249                                  {'run_name': 'TableSortIndicesInt64Wide/1048576/0/2/1/min_time:1.000', 'run_type': 'iteration', 'repetitions': 0, 'repetition_index': 0, 'threads': 1, 'iterations': 8}
77        TableSortIndicesInt64Wide/1048576/0/16/1/min_time:1.000    5.829m items/sec    4.297m items/sec   -26.281                                 {'run_name': 'TableSortIndicesInt64Wide/1048576/0/16/1/min_time:1.000', 'run_type': 'iteration', 'repetitions': 0, 'repetition_index': 0, 'threads': 1, 'iterations': 8}
70       TableSortIndicesInt64Wide/1048576/100/2/1/min_time:1.000    5.739m items/sec    4.230m items/sec   -26.283                                {'run_name': 'TableSortIndicesInt64Wide/1048576/100/2/1/min_time:1.000', 'run_type': 'iteration', 'repetitions': 0, 'repetition_index': 0, 'threads': 1, 'iterations': 8}
37         TableSortIndicesInt64Wide/1048576/0/8/1/min_time:1.000    5.845m items/sec    4.304m items/sec   -26.353                                  {'run_name': 'TableSortIndicesInt64Wide/1048576/0/8/1/min_time:1.000', 'run_type': 'iteration', 'repetitions': 0, 'repetition_index': 0, 'threads': 1, 'iterations': 8}
18       TableSortIndicesInt64Wide/1048576/100/8/1/min_time:1.000    5.750m items/sec    4.231m items/sec   -26.419                                {'run_name': 'TableSortIndicesInt64Wide/1048576/100/8/1/min_time:1.000', 'run_type': 'iteration', 'repetitions': 0, 'repetition_index': 0, 'threads': 1, 'iterations': 8}
33      TableSortIndicesInt64Wide/1048576/100/16/1/min_time:1.000    5.753m items/sec    4.232m items/sec   -26.440                               {'run_name': 'TableSortIndicesInt64Wide/1048576/100/16/1/min_time:1.000', 'run_type': 'iteration', 'repetitions': 0, 'repetition_index': 0, 'threads': 1, 'iterations': 8}

**Comment by pitrou** [comment]
Micro-benchmarks (without changes that are within +/-20%):
```
                                                        benchmark            baseline           contender  change %                                                                                                                                                                                                 counters
70    TableSortIndicesInt64Narrow/1048576/100/1/32/min_time:1.000    2.103m items/sec   29.517m items/sec  1303.373                             {'run_name': 'TableSortIndicesInt64Narrow/1048576/100/1/32/min_time:1.000', 'run_type': 'iteration', 'repetitions': 0, 'repetition_index': 0, 'threads': 1, 'iterations': 3}
42      TableSortIndicesInt64Narrow/1048576/0/1/32/min_time:1.000    2.632m items/sec   32.005m items/sec  1115.857                               {'run_name': 'TableSortIndicesInt64Narrow/1048576/0/1/32/min_time:1.000', 'run_type': 'iteration', 'repetitions': 0, 'repetition_index': 0, 'threads': 1, 'iterations': 3}
4       TableSortIndicesInt64Wide/1048576/100/1/32/min_time:1.000    1.310m items/sec    5.699m items/sec   334.947                               {'run_name': 'TableSortIndicesInt64Wide/1048576/100/1/32/min_time:1.000', 'run_type': 'iteration', 'repetitions': 0, 'repetition_index': 0, 'threads': 1, 'iterations': 2}
45  ChunkedArraySortIndicesInt64Narrow/1048576/100/min_time:1.000     120.277 MiB/sec     457.146 MiB/sec   280.079    {'run_name': 'ChunkedArraySortIndicesInt64Narrow/1048576/100/min_time:1.000', 'run_type': 'iteration', 'repetitions': 0, 'repetition_index': 0, 'threads': 1, 'iterations': 169, 'null_percent': 1.0}
74        TableSortIndicesInt64Wide/1048576/0/1/32/min_time:1.000    1.818m items/sec    5.713m items/sec   214.210                                 {'run_name': 'TableSortIndicesInt64Wide/1048576/0/1/32/min_time:1.000', 'run_type': 'iteration', 'repetitions': 0, 'repetition_index': 0, 'threads': 1, 'iterations': 2}
43  ChunkedArraySortIndicesInt64Narrow/8388608/100/min_time:1.000     100.449 MiB/sec     296.414 MiB/sec   195.090     {'run_name': 'ChunkedArraySortIndicesInt64Narrow/8388608/100/min_time:1.000', 'run_type': 'iteration', 'repetitions': 0, 'repetition_index': 0, 'threads': 1, 'iterations': 18, 'null_percent': 1.0}
36        ChunkedArraySortIndicesInt64Wide/32768/1/min_time:1.000     436.969 MiB/sec     937.543 MiB/sec   114.556      {'run_name': 'ChunkedArraySortIndicesInt64Wide/32768/1/min_time:1.000', 'run_type': 'iteration', 'repetitions': 0, 'repetition_index': 0, 'threads': 1, 'iterations': 19706, 'null_percent': 100.0}
67      ChunkedArraySortIndicesInt64Narrow/32768/2/min_time:1.000     103.001 MiB/sec     220.776 MiB/sec   114.344      {'run_name': 'ChunkedArraySortIndicesInt64Narrow/32768/2/min_time:1.000', 'run_type': 'iteration', 'repetitions': 0, 'repetition_index': 0, 'threads': 1, 'iterations': 4599, 'null_percent': 50.0}
33      ChunkedArraySortIndicesInt64Narrow/32768/1/min_time:1.000     440.082 MiB/sec     936.393 MiB/sec   112.777    {'run_name': 'ChunkedArraySortIndicesInt64Narrow/32768/1/min_time:1.000', 'run_type': 'iteration', 'repetitions': 0, 'repetition_index': 0, 'threads': 1, 'iterations': 19740, 'null_percent': 100.0}
20     ChunkedArraySortIndicesInt64Narrow/32768/10/min_time:1.000      68.612 MiB/sec     141.755 MiB/sec   106.604     {'run_name': 'ChunkedArraySortIndicesInt64Narrow/32768/10/min_time:1.000', 'run_type': 'iteration', 'repetitions': 0, 'repetition_index': 0, 'threads': 1, 'iterations': 3079, 'null_percent': 10.0}
26    ChunkedArraySortIndicesInt64Narrow/32768/100/min_time:1.000      64.937 MiB/sec     132.435 MiB/sec   103.942     {'run_name': 'ChunkedArraySortIndicesInt64Narrow/32768/100/min_time:1.000', 'run_type': 'iteration', 'repetitions': 0, 'repetition_index': 0, 'threads': 1, 'iterations': 2904, 'null_percent': 1.0}
52        ChunkedArraySortIndicesInt64Wide/32768/2/min_time:1.000      92.572 MiB/sec     186.731 MiB/sec   101.715        {'run_name': 'ChunkedArraySortIndicesInt64Wide/32768/2/min_time:1.000', 'run_type': 'iteration', 'repetitions': 0, 'repetition_index': 0, 'threads': 1, 'iterations': 4144, 'null_percent': 50.0}
27       ChunkedArraySortIndicesInt64Wide/32768/10/min_time:1.000      56.622 MiB/sec     108.760 MiB/sec    92.080       {'run_name': 'ChunkedArraySortIndicesInt64Wide/32768/10/min_time:1.000', 'run_type': 'iteration', 'repetitions': 0, 'repetition_index': 0, 'threads': 1, 'iterations': 2538, 'null_percent': 10.0}
60      ChunkedArraySortIndicesInt64Wide/32768/100/min_time:1.000      51.971 MiB/sec      99.685 MiB/sec    91.809       {'run_name': 'ChunkedArraySortIndicesInt64Wide/32768/100/min_time:1.000', 'run_type': 'iteration', 'repetitions': 0, 'repetition_index': 0, 'threads': 1, 'iterations': 2313, 'null_percent': 1.0}
0     ChunkedArraySortIndicesInt64Wide/1048576/100/min_time:1.000      43.418 MiB/sec      71.135 MiB/sec    63.836       {'run_name': 'ChunkedArraySortIndicesInt64Wide/1048576/100/min_time:1.000', 'run_type': 'iteration', 'repetitions': 0, 'repetition_index': 0, 'threads': 1, 'iterations': 61, 'null_percent': 1.0}
72      TableSortIndicesInt64Narrow/1048576/0/2/32/min_time:1.000    1.034m items/sec    1.681m items/sec    62.568                               {'run_name': 'TableSortIndicesInt64Narrow/1048576/0/2/32/min_time:1.000', 'run_type': 'iteration', 'repetitions': 0, 'repetition_index': 0, 'threads': 1, 'iterations': 1}
11      ChunkedArraySortIndicesInt64Narrow/32768/0/min_time:1.000      88.918 MiB/sec     138.677 MiB/sec    55.960       {'run_name': 'ChunkedArraySortIndicesInt64Narrow/32768/0/min_time:1.000', 'run_type': 'iteration', 'repetitions': 0, 'repetition_index': 0, 'threads': 1, 'iterations': 3976, 'null_percent': 0.0}
30    TableSortIndicesInt64Narrow/1048576/100/2/32/min_time:1.000    1.045m items/sec    1.618m items/sec    54.872                             {'run_name': 'TableSortIndicesInt64Narrow/1048576/100/2/32/min_time:1.000', 'run_type': 'iteration', 'repetitions': 0, 'repetition_index': 0, 'threads': 1, 'iterations': 1}
23  ChunkedArraySortIndicesInt64Narrow/32768/10000/min_time:1.000      88.881 MiB/sec     136.954 MiB/sec    54.086  {'run_name': 'ChunkedArraySortIndicesInt64Narrow/32768/10000/min_time:1.000', 'run_type': 'iteration', 'repetitions': 0, 'repetition_index': 0, 'threads': 1, 'iterations': 3952, 'null_percent': 0.01}
41    ChunkedArraySortIndicesInt64Wide/8388608/100/min_time:1.000      36.545 MiB/sec      54.546 MiB/sec    49.259        {'run_name': 'ChunkedArraySortIndicesInt64Wide/8388608/100/min_time:1.000', 'run_type': 'iteration', 'repetitions': 0, 'repetition_index': 0, 'threads': 1, 'iterations': 6, 'null_percent': 1.0}
49      TableSortIndicesInt64Narrow/1048576/0/8/32/min_time:1.000  756.824k items/sec    1.110m items/sec    46.676                               {'run_name': 'TableSortIndicesInt64Narrow/1048576/0/8/32/min_time:1.000', 'run_type': 'iteration', 'repetitions': 0, 'repetition_index': 0, 'threads': 1, 'iterations': 1}
40     TableSortIndicesInt64Narrow/1048576/0/16/32/min_time:1.000  769.325k items/sec    1.111m items/sec    44.463                              {'run_name': 'TableSortIndicesInt64Narrow/1048576/0/16/32/min_time:1.000', 'run_type': 'iteration', 'repetitions': 0, 'repetition_index': 0, 'threads': 1, 'iterations': 1}
22     TableSortIndicesInt64Narrow/1048576/100/1/4/min_time:1.000   41.401m items/sec   59.226m items/sec    43.055                             {'run_name': 'TableSortIndicesInt64Narrow/1048576/100/1/4/min_time:1.000', 'run_type': 'iteration', 'repetitions': 0, 'repetition_index': 0, 'threads': 1, 'iterations': 55}
64        TableSortIndicesInt64Wide/1048576/0/2/32/min_time:1.000    2.037m items/sec    2.896m items/sec    42.210                                 {'run_name': 'TableSortIndicesInt64Wide/1048576/0/2/32/min_time:1.000', 'run_type': 'iteration', 'repetitions': 0, 'repetition_index': 0, 'threads': 1, 'iterations': 3}
28   TableSortIndicesInt64Narrow/1048576/100/16/32/min_time:1.000  734.690k items/sec    1.037m items/sec    41.134                            {'run_name': 'TableSortIndicesInt64Narrow/1048576/100/16/32/min_time:1.000', 'run_type': 'iteration', 'repetitions': 0, 'repetition_index': 0, 'threads': 1, 'iterations': 1}
57    TableSortIndicesInt64Narrow/1048576/100/8/32/min_time:1.000  740.323k items/sec    1.040m items/sec    40.479                             {'run_name': 'TableSortIndicesInt64Narrow/1048576/100/8/32/min_time:1.000', 'run_type': 'iteration', 'repetitions': 0, 'repetition_index': 0, 'threads': 1, 'iterations': 1}
69      TableSortIndicesInt64Wide/1048576/100/2/32/min_time:1.000    2.052m items/sec    2.860m items/sec    39.332                               {'run_name': 'TableSortIndicesInt64Wide/1048576/100/2/32/min_time:1.000', 'run_type': 'iteration', 'repetitions': 0, 'repetition_index': 0, 'threads': 1, 'iterations': 3}
56     TableSortIndicesInt64Wide/1048576/100/16/32/min_time:1.000    2.069m items/sec    2.874m items/sec    38.875                              {'run_name': 'TableSortIndicesInt64Wide/1048576/100/16/32/min_time:1.000', 'run_type': 'iteration', 'repetitions': 0, 'repetition_index': 0, 'threads': 1, 'iterations': 3}
71      TableSortIndicesInt64Wide/1048576/100/8/32/min_time:1.000    2.067m items/sec    2.867m items/sec    38.699                               {'run_name': 'TableSortIndicesInt64Wide/1048576/100/8/32/min_time:1.000', 'run_type': 'iteration', 'repetitions': 0, 'repetition_index': 0, 'threads': 1, 'iterations': 3}
63        ChunkedArraySortIndicesInt64Wide/32768/0/min_time:1.000      73.852 MiB/sec     102.317 MiB/sec    38.544         {'run_name': 'ChunkedArraySortIndicesInt64Wide/32768/0/min_time:1.000', 'run_type': 'iteration', 'repetitions': 0, 'repetition_index': 0, 'threads': 1, 'iterations': 3287, 'null_percent': 0.0}
16    ChunkedArraySortIndicesInt64Wide/32768/10000/min_time:1.000      73.234 MiB/sec     100.801 MiB/sec    37.642    {'run_name': 'ChunkedArraySortIndicesInt64Wide/32768/10000/min_time:1.000', 'run_type': 'iteration', 'repetitions': 0, 'repetition_index': 0, 'threads': 1, 'iterations': 3273, 'null_percent': 0.01}
15        TableSortIndicesInt64Wide/1048576/0/8/32/min_time:1.000    2.115m items/sec    2.906m items/sec    37.416                                 {'run_name': 'TableSortIndicesInt64Wide/1048576/0/8/32/min_time:1.000', 'run_type': 'iteration', 'repetitions': 0, 'repetition_index': 0, 'threads': 1, 'iterations': 3}
46       TableSortIndicesInt64Wide/1048576/0/16/32/min_time:1.000    2.124m items/sec    2.882m items/sec    35.644                                {'run_name': 'TableSortIndicesInt64Wide/1048576/0/16/32/min_time:1.000', 'run_type': 'iteration', 'repetitions': 0, 'repetition_index': 0, 'threads': 1, 'iterations': 3}
[ ... ]
76      TableSortIndicesInt64Wide/1048576/100/16/1/min_time:1.000    5.701m items/sec    4.260m items/sec   -25.267                               {'run_name': 'TableSortIndicesInt64Wide/1048576/100/16/1/min_time:1.000', 'run_type': 'iteration', 'repetitions': 0, 'repetition_index': 0, 'threads': 1, 'iterations': 8}
21        TableSortIndicesInt64Wide/1048576/0/16/1/min_time:1.000    6.023m items/sec    4.350m items/sec   -27.777                                 {'run_name': 'TableSortIndicesInt64Wide/1048576/0/16/1/min_time:1.000', 'run_type': 'iteration', 'repetitions': 0, 'repetition_index': 0, 'threads': 1, 'iterations': 8}
50       TableSortIndicesInt64Wide/1048576/100/8/1/min_time:1.000    6.003m items/sec    4.277m items/sec   -28.752                                {'run_name': 'TableSortIndicesInt64Wide/1048576/100/8/1/min_time:1.000', 'run_type': 'iteration', 'repetitions': 0, 'repetition_index': 0, 'threads': 1, 'iterations': 8}
51         TableSortIndicesInt64Wide/1048576/0/8/1/min_time:1.000    6.120m items/sec    4.359m items/sec   -28.776                                  {'run_name': 'TableSortIndicesInt64Wide/1048576/0/8/1/min_time:1.000', 'run_type': 'iteration', 'repetitions': 0, 'repetition_index': 0, 'threads': 1, 'iterations': 8}
39         TableSortIndicesInt64Wide/1048576/0/2/1/min_time:1.000    6.122m items/sec    4.358m items/sec   -28.818                                  {'run_name': 'TableSortIndicesInt64Wide/1048576/0/2/1/min_time:1.000', 'run_type': 'iteration', 'repetitions': 0, 'repetition_index': 0, 'threads': 1, 'iterations': 8}
6        TableSortIndicesInt64Wide/1048576/100/2/1/min_time:1.000    6.027m items/sec    4.285m items/sec   -28.901                                {'run_name': 'TableSortIndicesInt64Wide/1048576/100/2/1/min_time:1.000', 'run_type': 'iteration', 'repetitions': 0, 'repetition_index': 0, 'threads': 1, 'iterations': 8}
```

**Review by kou — APPROVED** [review]
+1

Great! I didn't notice that `ResolveChunk()` is too slow.

**Pull request closed without merging**
