### PR TITLE
ARROW-3582: [CI] fix incantation for C++/Java detection tool

### PR DESCRIPTION
**Pull request by sbinet**

### CODE REVIEW

**Comment by sbinet** [comment]
build failure (in R) unrelated:

```
$ Rscript -e 'deps <- devtools::dev_package_deps(dependencies = NA);devtools::install_deps(dependencies = TRUE);if (!all(deps$package %in% installed.packages())) { message("missing: ", paste(setdiff(deps$package, installed.packages()), collapse=", ")); q(status = 1, save = "no")}'
Error: HTTP error 403.
  API rate limit exceeded for 35.192.187.174. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
  Rate limit remaining: 0
  Rate limit reset at: 2018-10-21 12:08:21 UTC
Execution halted
```

**Comment by pitrou** [comment]
Aha, lovely bash.

**Review by xhochy — COMMENTED** [review]
+1, LGTM

**Comment by pravindra** [comment]
thanks for fixing this !

**Pull request closed without merging**
