### PR TITLE
ARROW-10049: [C++/Python] Sync conda recipe with conda-forge

### PR DESCRIPTION
**Pull request by xhochy**

### CODE REVIEW

**Comment by xhochy** [comment]
@github-actions crossbow submit -g conda

**Comment by xhochy** [comment]
@github-actions crossbow submit 

conda-linux-gcc-py36-cpu
--

**Comment by xhochy** [comment]
@github-actions crossbow submit conda-linux-gcc-py36-cpu

**Comment by xhochy** [comment]
@github-actions crossbow submit -g conda

**Review by kszucs — APPROVED** [review]
Thanks Uwe!

**Pull request closed without merging**
