### PR TITLE
ARROW-7601: [Doc][C++] Update fuzzing doc

### PR DESCRIPTION
**Pull request by pitrou**
Also split up the monolithic "C++ development" document in several distinct sub-documents.

### CODE REVIEW

**Comment by nealrichardson** [comment]
Does this file reorganization break old links (e.g. https://github.com/apache/arrow/blame/master/r/README.md#L198)? If so, can we at least search our own codebase for URLs and update them accordingly?

**Comment by pitrou** [comment]
Ah, right... the annoyance of course is that the docs will be updated on the website only when the release is done.

**Comment by pitrou** [comment]
Hmm, of course the R builds are broken now. What was I thinking :-D

**Comment by nealrichardson** [comment]
Check test-install-arrow.R, looks like there's another find/replace needed

**Review by wesm — COMMENTED** [review]
Looks OK to me once the CI is fixed

**Pull request closed without merging**
