### PR TITLE
ARROW-17269: [Java] implemented TransferPair methods in MapVector to get correct valuevector as mapvector instead of listvector

### PR DESCRIPTION
**Pull request by Ankit01Gehlot**
…rect valuevector as mapvector instead of listvector

### CODE REVIEW

**Comment by pprudhvi** [comment]
@projjal could you please review this change?

**Review by lwhite1 — APPROVED** [review]
Looks good to me.

**Comment by pprudhvi** [comment]
@pitrou could you please approve running the 4 workflows awaiting approval?

**Comment by pitrou** [comment]
@pprudhvi Someone else already did apparently :-)

**Comment by pitrou** [comment]
The Python lint errors are unrelated.

**Comment by pprudhvi** [comment]
@pitrou All checks passed except the unrelated python lint errors, can we merge this PR?

**Comment by pprudhvi** [comment]
Thank you @pitrou

**Pull request merged**
