### PR TITLE
MINOR: [Java] Bump org.apache.derby:derby from 10.14.2.0 to 10.15.2.0 in /java

### PR DESCRIPTION
**Pull request by danepitkin**
### Rationale for this change

Bump to latest version that supports Java 11. See Apache Derby support matrix here https://db.apache.org/derby/derby_downloads.html

### What changes are included in this PR?

* Bump derby to 10.15.2.0

### Are these changes tested?

CI

### Are there any user-facing changes?

No

### CODE REVIEW

**Comment by danepitkin** [comment]
@github-actions crossbow submit -g java

**Comment by danepitkin** [comment]
@github-actions crossbow submit -g java

**Comment by vibhatha** [comment]
Seems like we may need to file an issue for this C++ compile error.

**Comment by danepitkin** [comment]
Merging, since the failure is unrelated.

**Pull request merged**
