### PR TITLE
ARROW-8157: [C++][Gandiva] Support building with LLVM 9

### PR DESCRIPTION
**Pull request by kou**
LLVM 7 and 8 are still supported.

### CODE REVIEW

**Comment by kou** [comment]
@github-actions crossbow submit -g nightly

**Comment by kou** [comment]
@github-actions crossbow submit -g nightly

**Comment by kou** [comment]
@github-actions crossbow submit -g nightly

**Comment by kiszk** [comment]
According to [this discussion](https://github.com/apache/arrow/pull/7295#issuecomment-635351048), could you please update the LLVM part of LICENSE.txt?

cc @wesm

**Comment by kou** [comment]
> According to [this discussion](https://github.com/apache/arrow/pull/7295#issuecomment-635351048), could you please update the LLVM part of LICENSE.txt?

Thanks for notifying this. I've updated.

The new `LICENSE.txt` mentions bundled software:

https://github.com/apache/arrow/pull/7280/commits/4a8464512c9b60a7f1aea6e699184438f51969c0#diff-61e0bdf7e1b43c5c93d9488b22e04170R1298-R1308

```text
==============================================================================
Software from third parties included in the LLVM Project:
==============================================================================
The LLVM Project contains third party software which is under different license
terms. All such code will be identified clearly using at least one of two
mechanisms:
1) It will be in a separate directory tree with its own `LICENSE.txt` or
   `LICENSE` file at the top containing the specific license and restrictions
   which apply to that software, or
2) It will contain specific license and restriction terms at the top of every
   file.
```

I've checked bundled software in LLVM 9. There are 2 software:

* llvm/test/YAMLParser/LICENSE.txt
* llvm/utils/unittest/googlemock/LICENSE.txt

Both of them are for testing. So I didn't put additional license information to our `LICENSE.txt`.

**Comment by kou** [comment]
Umm, the `gandiva-decimal-test` test is sometimes  stuck on CI:

* e.g.: AMD Debian 10 C++: https://github.com/apache/arrow/pull/7280/checks?check_run_id=718284495
* e.g.: AMD Fedora 31 C++: https://github.com/apache/arrow/pull/7280/checks?check_run_id=718284516

But I couldn't reproduce this on my local environment...

Could  @praveenbingo, @pravindra or someone help me?

**Comment by emkornfield** [comment]
I think this PR has a mis-assigned JIRA number

**Comment by kou** [comment]
Oh, sorry. I've fixed Jira ID.

**Review by wesm — APPROVED** [review]
+1

**Pull request closed without merging**
