### PR TITLE
ARROW-6763: [Python] Additional testing requirements on Travis (s3fs)

### PR DESCRIPTION
**Pull request by jorisvandenbossche**
https://issues.apache.org/jira/browse/ARROW-6763

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
I don't know if this is the best solution, but I wanted a way to add some additional packages to the test environment on travis, without adding them to the main python environment file that is also used for setting up a development environment.

**Comment by kszucs** [comment]
@jorisvandenbossche we already list the test-only dependencies in conda_env_python.yml, so I think It is better to ass s3fs to conda_env_python.yml which is used only for setting up development environments.

**Comment by jorisvandenbossche** [comment]
The test-only dependencies in `conda_env_python.yml` right now are mostly the required deps to just get the tests running, which certainly needs to be installed in a dev environment. 
But the question is if we want to install all optional test deps also in the default dev environment for contributors. Eg, I think we should also add `fastparquet` to this file, but that's maybe not something that should be added to the base dev environment? If it would be just for `s3fs`, I agree, we can just add that to python environment.

**Comment by kszucs** [comment]
cc @pitrou

**Comment by pitrou** [comment]
We already have Pandas and cloudpickle in `conda_env_python.yml`. Why not add s3fs there? It's a lightweight dependency.

(fastparquet OTOH depends on Numba, which is much larger AFAIR)

**Comment by jorisvandenbossche** [comment]
And if I add fastparquet to the `conda_env_python_test.yml` file, does it then make more sense to have it separate? (or do we not want to test this on travis?) 
Or would you still prefer to have s3fs in the main python env even in that case?

**Comment by pitrou** [comment]
Please first try locally to see if fastparquet adds a large download.

**Comment by jorisvandenbossche** [comment]
I *think* it needs numba (3 Mb) which needs llvmlite (15 Mb) (can't check exactly because I already have those, and conda does not download them again)

**Comment by kszucs** [comment]
```
The following NEW packages will be INSTALLED:

  fastparquet        conda-forge/osx-64::fastparquet-0.3.2-py37heacc8b8_0
  llvmlite           conda-forge/osx-64::llvmlite-0.29.0-py37h3fea490_1
  numba              conda-forge/osx-64::numba-0.45.1-py37h86efe34_0
  thrift             conda-forge/osx-64::thrift-0.11.0-py37h0a44026_1001
```

**Comment by fsaintjacques** [comment]
Ping.

**Comment by pitrou** [comment]
If we want to keep `conda_env_python_test.yml`, then other (optional or not) test dependencies such as `pandas`, `cloudpickle` or `hypothesis` should be move there too.

**Comment by jorisvandenbossche** [comment]
`hypothesis` is a required dependency for running the tests at the moment. `pandas` could be moved, but this is an optional run dependency, not only optional test dependency, and I would argue that out contributing docs should by default construct an environment that contains `pandas` (which is not necessarily the case for all optional test dependencies such as fastparquet)

**Comment by pitrou** [comment]
What is the purpose of `conda_env_python_test.yml` exactly?

**Comment by jorisvandenbossche** [comment]
What I said above: I wanted a way to add some additional packages to the test environment on travis, without adding them to the main python environment file that is also used for setting up a development environment.

I now added s3fs because that was the case I ran into when I opened the PR, but actually also wanted to add `fastparquet`

This is assuming that 1) we actually are OK with adding those to the test env on travis, and 2) that we rather not add them to the main python env file for creating a development environment. 

If the second assumption is not correct, I am happy to remove this file and move it into the main `conda_env_python.yml`. 
And if the first assumption is not correct, then we should discuss where we *do* want to test them (one of the ursabot builds?)

**Comment by pitrou** [comment]
Well, right now it's completely ad hoc and there is no clear definition of what this file does (except "Joris likes it"). So I'd say remove it.

**Comment by jorisvandenbossche** [comment]
With "remove it", you mean "move it the `conda_env_python.yml` ? 
In that case, we are OK with adding fastparquet (thus numba) in there?

**Comment by pitrou** [comment]
Well, the logical thing to do would be to put _all_ test requirements in `conda_env_python_test.yml`. Including "hypothesis". I agree fastparquet shouldn't be installed by default on developers' machines, but why would cloudpickle?

**Comment by jorisvandenbossche** [comment]
> Well, the logical thing to do would be to put all test requirements in conda_env_python_test.yml. 

I think that the main `conda_env_python.yml` should contain the minimum set of test requirements that allows you to run `pytest` (for a development environment). Which right now needs hypothesis, although I think we can refactor our usage of hypothesis to make it optional (although not sure this is worth the effort). 
But indeed in that definition, cloudpickle can certainly be moved to a test file.

**Comment by nealrichardson** [comment]
Is this still active? If so, it needs rebase after the docker-compose changes.

**Comment by jorisvandenbossche** [comment]
The situation has changed a bit in the meantime. `pandas` was removed from `conda_env_python.yml` as discussed above (so from the base python ci build).

But the question is still: where to put (and test) additional python tests (eg for s3fs, fastparquet, ..). Currently tests relying on those are never run by any CI we have. 

One option could be to have a `conda_env_python_extra.yml` with those additional optional dependencies, and then eg install those in the pandas docker image?

**Comment by kszucs** [comment]
@jorisvandenbossche it needs an update. How about adding this dependency to the task integration test and run the tests there?

**Comment by pitrou** [comment]
Is this still useful now that we ditched Travis-CI?

**Comment by jorisvandenbossche** [comment]
> Is this still useful now that we ditched Travis-CI?

Yes (in an updated form of course), see https://github.com/apache/arrow/pull/5562#issuecomment-553782658

> How about adding this dependency to the task integration test and run the tests there?

@kszucs what do you mean exactly with the task integration tests?

**Comment by kszucs** [comment]
@jorisvandenbossche we have separate docker builds for downstream dependencies like dask.
See the scripts prefixed with (integration_](https://github.com/apache/arrow/tree/master/ci/scripts) and the [services](https://github.com/apache/arrow/blob/master/docker-compose.yml#L504) in the compose file. Perhaps we could add it to the dask [build](https://github.com/apache/arrow/blob/master/ci/docker/conda-python-dask.dockerfile) or to a new build.

**Comment by kszucs** [comment]
The travis scripts doesn't exist anymore so we need to run it somewhere else.

**Comment by pitrou** [comment]
We're not using Travis-CI anymore, so closing.

**Pull request closed without merging**
