### PR TITLE
ARROW-15901: [C++] Support custom output field names in Substrait

### PR DESCRIPTION
**Pull request by rtpsw**
See https://issues.apache.org/jira/browse/ARROW-15901 . Tests will be added after agreement on the approach is reached.

### CODE REVIEW

**Comment by rtpsw** [comment]
Not sure what to do about the unsuccessful checks; they don't seem to be related to the change. What is the next step?

**Comment by westonpace** [comment]
Sorry for not noticing this originally.  Feel free to ping someone in the future after a few days.

As for the PR, I think this is part of the solution but I think we also want to handle the case where the last node in the declaration is not a project node.  And we will want to have a plan in place for round-trip.  A simple solution would be to just add a project node onto the end (if one is not there already) but that would mean our plan wouldn't round-trip cleanly.

Another approach could be to add a vector of names to `ConsumingSinkNodeOptions`.  The sink node could then take the output schema from its input, swap out the names, and pass that on to the consumer.  This should round-trip nicely.

Thoughts?

**Comment by rtpsw** [comment]
> As for the PR, I think this is part of the solution but I think we also want to handle the case where the last node in the declaration is not a project node. And we will want to have a plan in place for round-trip. A simple solution would be to just add a project node onto the end (if one is not there already) but that would mean our plan wouldn't round-trip cleanly.

Agreed, this would not round-trip cleanly. While this could be fixed by creating a special projection-node, which could be removed when going back the round-trip, that seems even less elegant.

> Another approach could be to add a vector of names to `ConsumingSinkNodeOptions`. The sink node could then take the output schema from its input, swap out the names, and pass that on to the consumer. This should round-trip nicely.

Yes, sounds like this should work and round-trip nicely. I'll look into implementing it. One thing to keep in mind here is that in the future we may want to use other sink nodes (e.g., "write" rather than "consuming_sink") in Substrait, so I think it makes sense to factor out the names into a reusable options class (to be included as a member in `ConsumingsinkNodeOptions`) and the schema-renaming operation for it into a reusable function.

**Comment by rtpsw** [comment]
> Another approach could be to add a vector of names to `ConsumingSinkNodeOptions`. The sink node could then take the output schema from its input, swap out the names, and pass that on to the consumer. This should round-trip nicely.

@westonpace, I looked into it a bit and it appears to run into an issue - the schema is not available to `ConsumingSinkNode`. Instead, `ConsumingSinkNode` passes a (schema-less) `ExecBatch` to a `SinkNodeConsumer`; it is `SinkNodeConsumer` which is expected to already have been initialized with a schema, like in `TableSinkNodeConsumer`, and use it to obtain a `RecordBatch`. Perhaps a reasonable solution would be to extend `ConsumerFactory` to accept a `names` parameter? Despite this being a backwards-incompatible change, presumably the Arrow-Substrait code is still in flex so this would be OK.

**Comment by westonpace** [comment]
The Arrow-Substrait code is definitely in flex.  Nothing has been released externally via any binidings so I wouldn't worry about any backwards incompatible changes.

That being said, I think `SinkNodeConsumer` has an `Init` method which receives a schema.  This is called by `ConsumingSinkNode` in `ConsumingSinkNode::StartProducing`.  At that point (`StartProducing`) the `ConsumingSinkNode` should have access to the schema (it's the output schema of the node's single input).

Instead of passing that schema directly it should modify the schema with the names that it gets from its options.  So the act of assigning names to an existing schema would happen in `ConsumingSinkNode::StartProducing`.

**Comment by rtpsw** [comment]
You're right, I needed to rebase to pick up this `Init` function. I'll commit shortly.

**Review by westonpace — COMMENTED** [review]
This is just a dummy comment to move this into the "reviewed" state.  Please click re-request review when you're ready for me to take another look.

**Comment by rtpsw** [comment]
> This is just a dummy comment to move this into the "reviewed" state. Please click re-request review when you're ready for me to take another look.

Hmm, I don't see such a button. You can review. For some reason, the code in my last couple of commits builds OK in my environment but failed in the checks, so I committed a fix that hopefully would resolve this.

**Comment by westonpace** [comment]
I don't think the rebase went through correctly (right now GH is showing ~1200 files changed) so I can't review at the moment.  The re-request review button should be way up in the top-right corner.

image

**Comment by rtpsw** [comment]
To keep things clean, I'm replacing this PR with https://github.com/apache/arrow/pull/13069 .

**Pull request closed without merging**
