### PR TITLE
ARROW-3996: [C++] Add missing packages on Linux

### PR DESCRIPTION
**Pull request by kabukawa**
[C++] Build requirement libraries add to README.md.

* autoconf
* Jemalloc
* boost-regex

### CODE REVIEW

**Comment by kou** [comment]
Can you open a JIRA issue for this?
https://issues.apache.org/jira/projects/ARROW/

**Comment by kabukawa** [comment]
open issue ARROW-3996.

**Comment by kou** [comment]
Thanks.

Does we need to install `libjemalloc-dev`? We always use vendored jemalloc in master.

I think that `autotools-dev` isn't a suitable package for installing Autoconf. It's a package for building .deb packages. Can we use `autoconf` instead of `autotools-dev`?

**Comment by kou** [comment]
Do we need to add `g++` add `libboost-regex-dev` too?

**Comment by kabukawa** [comment]
Ubuntu 18.04 LTS, jemalloc is not installed. Install libjemalloc-dev log below

```
kabukawa@kabukawa-HP:~/arrow/cpp$ sudo apt install libjemalloc-dev
[sudo] password for kabukawa:
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  libjemalloc1
The following NEW packages will be installed:
  libjemalloc-dev libjemalloc1
0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
Need to get 239 kB of archives.
After this operation, 1265 kB of additional disk space will be used.
Do you want to continue? [Y/n]
```

> Can we use autoconf instead of autotools-dev?

Yes. autotools is include autoconf, but must not need.

> add g++ 

Sorry, /usr/bin/c++ used.

```
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
```

This is contained build-essential package.

> libboost-regex-dev too?

I Retry build after remove this, please wait.

After checking by myself, issue a pull request again.
Please disapprove this request once.

**Comment by kou** [comment]
You don't need to recreate pull request.
You can push more commits to this branch.

**Comment by kou** [comment]
> Ubuntu 18.04 LTS, jemalloc is not installed. Install libjemalloc-dev log below

Ah, sorry. "vendored jemalloc" means that "jemalloc in Apache Arrow not in Ubuntu system".
If you can build Apache Arrow at master without `libjemalloc-dev`, we don't need to install `libjemalloc-dev`.

**Comment by kou** [comment]
> This is contained build-essential package.

Do we need to add `build-essential` package to the `apt-get install` list?

**Comment by pitrou** [comment]
Why is autotools needed?

**Comment by kou** [comment]
Autotools is needed to build vendored jemalloc.
If we vendor `autoconf`-ed jemalloc, users don't need to install Autotools.

**Comment by wesm** [comment]
Indeed, please remove `libjemalloc-dev` as we do not support system jemalloc at all. It is not required to use jemalloc if not desired (pass `-DARROW_JEMALLOC=OFF`)

**Comment by kabukawa** [comment]
I confirmed it again in the initialized environment.
I think that compilers are sure to have you use "build-essential" package.

In conclusion, what was necessary additionally is

* boost_regex
* autoconf

There are only two of them.

boost_regex gets an error like the following when executing cmake command and stops.

```
- Found pthread: /usr/lib/x86 _ 64 - linux - gnu / libpthread.so
CMake Error at /usr/share/cmake-3.10/Modules/FindBoost.cmake: 1947 (message):
Unable to find the requested Boost libraries.
Boost version: 1.65.1
Boost include path: / usr / include
Could not find the following Boost libraries:

           boost_regex

Some (but not all) of the required Boost libraries were found. You may
need to install these additional Boost libraries.
BOOST_LIBRARYDIR to the directory containing Boost libraries or BOOST_ROOT
to the location of Boost.
```

**Comment by kabukawa** [comment]
If libjemalloc-dev is not mandatory, autoconf is not mandatory, is it?

In other words,

* boost_regex

only. Correct it with this content and push it again.

**Review by kou — APPROVED** [review]
+1
I've added `autoconf`.

**Comment by kou** [comment]
Merged.
Thanks for your contribution!

**Pull request closed without merging**
