### PR TITLE
ARROW-13148: [Dev][Archery] Fix crossbow job submission

### PR DESCRIPTION
**Pull request by pitrou**

### CODE REVIEW

**Comment by pitrou** [comment]
@github-actions crossbow submit test-fedora-33-cpp

**Comment by pitrou** [comment]
Comment above failed because it used the Crossbow version from git master. Please disregard :-)

**Comment by pitrou** [comment]
Dummy crossbow submission from the CLI: https://github.com/ursacomputing/crossbow/branches/all?query=build-366

**Comment by kszucs** [comment]
The comment bot is triggered on the master branch, so we need to merge it to a fork's master in order to test it.

**Comment by pitrou** [comment]
A fork with the comment bot enabled?

**Comment by pitrou** [comment]
Ah, I understand what you mean now.

**Comment by pitrou** [comment]
Doesn't work either: https://github.com/apache/arrow/runs/2893717316?check_suite_focus=true
```
fatal: Refusing to fetch into current branch refs/heads/master of non-bare repository
```

**Comment by pitrou** [comment]
In any case, I tested locally with the Crossbow CLI and it worked fine. Are we ok with this?

**Comment by kszucs** [comment]
> In any case, I tested locally with the Crossbow CLI and it worked fine. Are we ok with this?

Yes, that tests the version generation too.

**Review by kszucs — APPROVED** [review]

**Pull request closed without merging**
