### PR TITLE
ARROW-4930: [C++] Fix discovery of platform dependent library directories

### PR DESCRIPTION
**Pull request by suvayu**
This PR is the first attempt at library detection to succeed in cases where libraries are in platform dependent directories: $prefix/lib, $prefix/lib64, etc.  This means now a PyArrow build to succeeds without -DCMAKE_INSTALL_LIBDIR=lib.

@kou This is my attempt.  I'm a bit out of my depth here, so please feel free to revise my changes.  I took your comments as a guide and used `LIB_PATH_SUFFIXES` for `FindParquet.cmake` also.  And since the library ABI version check is reliant on `PARQUET_HOME`, I simply added an `if` at the top, where I set `ARROW_HOME` to `PARQUET_HOME` in case `PARQUET_HOME` is not set, but `ARROW_HOME` is.

### CODE REVIEW

**Review by bkietz — APPROVED** [review]
lgtm

**Comment by kou** [comment]
I'll test this in a week.
Please wait for a while. Sorry.

**Comment by suvayu** [comment]
> I'll test this in a week.
> Please wait for a while. Sorry.

No worries, there's no hurry :)

**Comment by wesm** [comment]
@kou does this potentially impact packaging? Is it OK if I merge this?

**Comment by kou** [comment]
It doesn't impact packaging.
I can't test this yet but I think that we need more work. e.g. We shouldn't use `find_library()` with `PATH_SUFFIXES ${LIB_PATH_SUFFIXES}` in pkg-config path. Because `pkg-config` returns library directory with suffix. We may also need to remove https://github.com/apache/arrow/blob/master/python/setup.py#L257-L262 .

Do you want to hurry? Then It's OK to be merged. I'll follow up later.

(I'm very busy recently...)

**Comment by suvayu** [comment]
@kou no worries, this was only addressing a small part of the bigger need for reorganisation.  I'll follow the other PR

**Comment by kou** [comment]
This change works well but this is just a workaround.
I created real fix as https://github.com/apache/arrow/pull/5767 . So I close this. Sorry.

**Pull request closed without merging**
