### PR TITLE
ARROW-10095: [Rust] Update rust-parquet-arrow-writer branch's encode_arrow_schema with ipc changes

### PR DESCRIPTION
**Pull request by carols10cents**
Note that this PR is deliberately filed against the rust-parquet-arrow-writer branch, not master!!

Hi! 👋 I'm looking to help out with the rust-parquet-arrow-writer branch, and I just pulled it down and it wasn't compiling because in 75f804efbfe367175fef5a2238d9cd2d30ed3afe, `schema_to_bytes` was changed to take `IpcWriteOptions` and to return `EncodedData`. This updates `encode_arrow_schema` to use those changes, which should get this branch compiling and passing tests again.

I'm kind of guessing which JIRA ticket this should be associated with; honestly I think this commit can just be squashed with https://github.com/apache/arrow/commit/8f0ed91469f2e569472edaa3b69ffde051088555 next time this branch gets rebased.

Please let me know if I should change anything, I'm happy to!

### CODE REVIEW

**Comment by nevi-me** [comment]
Hi Carol 👋🏾

Thanks, I would definitely appreciate your help and expertise with the writer. I forgot to open a JIRA for the IPC changes, as I saw them after I had rebased. I've opened https://issues.apache.org/jira/browse/ARROW-10095 as a subtask of that, and I'll rename this PR to 10095, and merge this when CI completes.

In terms of where we are on the writer, I was last working on https://issues.apache.org/jira/browse/ARROW-9728 for calculating the correct spacing when writing deeply nested arrays. I have something working, but it's a lot of mental effort to keep track of what I was doing. I'll however be able to complete those changes in the coming 2 weeks 🤞🏾

AFAIA, there isn't anyone else working on the other open subtasks of ARROW-8421, so please feel free to have a look at any of those.

**Review by nevi-me — APPROVED** [review]

**Comment by nevi-me** [comment]
Merged, I'll rebase on the branch shortly

**Comment by carols10cents** [comment]
Thanks so much! I'm going to take a look at writing dictionary types :)

**Comment by nevi-me** [comment]
I just noticed that there's more breaking changes on the branch :(. I'll address them shortly

**Pull request closed without merging**
