### PR TITLE
ARROW-1409: [Format] Remove page id from Buffer metadata, increment metadata version number

### PR DESCRIPTION
**Pull request by wesm**
This is a breaking metadata change per discussion on the mailing list. I expect this kind of truly breaking changes to be exceedingly rare going forward, and when we make a 1.0.0 release we should document expectations around metadata / memory format stability. 

This could be made backwards compatible with some effort (we would have to add `RecordBatchV3` and `BufferV3` types).

### CODE REVIEW

**Review by xhochy — APPROVED** [review]
+1, LGTM

**Comment by wesm** [comment]
@trxcllnt @TheNeuralBit this patch change the Arrow binary format in a non-backwards compatible way. This is the peril of having binary files in the repo, and the sooner we can eradicate these from our development workflow, the better

**Review by trxcllnt — APPROVED** [review]

**Comment by wesm** [comment]
How should we address the JS test failures?

**Comment by trxcllnt** [comment]
@wesm I think we should disable the JS tests in CI for now, then re-enable when the tests use the JSON->Arrow writer

**Comment by wesm** [comment]
OK, no problem

**Comment by BryanCutler** [comment]
+1

**Comment by wesm** [comment]
@jacques-n @siddharthteotia could you let me know if this change is OK? What impact will the 0.7.1 -> 0.8.0 upgrade with breaking metadata change have on Dremio?

**Comment by jacques-n** [comment]
As far as I know, we don't persist this data (ephemeral only) so I think we'll be fine. @StevenMPhillips, you see any problems we'll hit with this change?

**Comment by wesm** [comment]
@StevenMPhillips could you comment? I will merge this sometime today if I don't hear back, hopefully it will be OK

**Comment by StevenMPhillips** [comment]
Yes, it should be fine to merge this. Jacques is correct that we don't persist this data.
+1

**Comment by wesm** [comment]
sweet, thanks!

**Comment by wesm** [comment]
@BryanCutler @icexelloss @holdenk just a heads up that this patch means that Spark will need to upgrade to Arrow 0.8.0 as soon as pyarrow 0.8.0 lands

**Comment by holdenk** [comment]
Since we don’t persist it though is that really necessary? I think it’s still a good idea to upgrade, but our Jenkins infra still has some difficulty with changing Python library versions so it might take a little bit.

**Comment by wesm** [comment]
As long as the JAR version and the Python version are the same, it's okay, but if users have pyarrow 0.8.0 and connect to a Spark cluster running an older JAR there will be problems. I don't expect this to become a regular occurrence -- I don't anticipate the need to break the metadata format again anytime soon

**Pull request closed without merging**
