### PR TITLE
ARROW-16185: [C++] Fix uninitialized output data in strptime kernel

### PR DESCRIPTION
**Pull request by pitrou**

### CODE REVIEW

**Comment by pitrou** [comment]
@github-actions crossbow submit test-conda-cpp-valgrind

**Review by lidavidm — APPROVED** [review]

**Comment by jonkeane** [comment]
@github-actions crossbow submit test-r-linux-valgrind  test-ubuntu-18.04-r-sanitizer test-fedora-r-clang-sanitizer

**Comment by pitrou** [comment]
On my computer, the Python benchmark posted on ARROW-11989 goes from this:
```
Time to access example at i=0%	: 5.3μs
Time to access example at i=10%	: 4.0μs
Time to access example at i=20%	: 5.5μs
Time to access example at i=30%	: 7.1μs
Time to access example at i=40%	: 8.6μs
Time to access example at i=50%	: 10.0μs
Time to access example at i=60%	: 12.8μs
Time to access example at i=70%	: 13.6μs
Time to access example at i=80%	: 15.2μs
Time to access example at i=90%	: 16.8μs
```

to this:
```
Time to access example at i=0%	: 4.3μs
Time to access example at i=10%	: 1.8μs
Time to access example at i=20%	: 1.7μs
Time to access example at i=30%	: 1.6μs
Time to access example at i=40%	: 1.6μs
Time to access example at i=50%	: 1.4μs
Time to access example at i=60%	: 1.6μs
Time to access example at i=70%	: 1.7μs
Time to access example at i=80%	: 1.9μs
Time to access example at i=90%	: 1.9μs
```

**Review by cyb70289 — APPROVED** [review]
`arrow-compute-tpch-node-test .............***Timeout 300.00 sec`
is another issue, not related to this PR

**Pull request closed without merging**
