### PR TITLE
ARROW-3324: [Python] Destroy temporary metadata builder classes more eagerly when building files to reduce memory usage

### PR DESCRIPTION
**Pull request by tanyaschlusser**
Destroy RowGroupMetadataBuilder after each row group is completed

### CODE REVIEW

**Comment by tanyaschlusser** [comment]
I could not think of a unit test to add; something that could access and assert the total count for one of the `shared_ptr` values maybe in the `cpp/src/parquet/file-serialize-test.cc`?

Also, (noted in the [Jira comment](https://issues.apache.org/jira/browse/ARROW-3324?focusedCommentId=16728819&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-16728819)) this does not address the leaking other users reported on read, which I could not duplicate.

**Comment by wesm** [comment]
Thanks @tanyaschlusser for looking into this. I haven't been able to dig into this memory use issue yet, were you able to replicate some kind of memory leak? I will try to take a closer look also today

**Comment by wesm** [comment]
Thanks @tanyaschlusser -- having the repro / investigation is very helpful. I'll take a closer look and let you know what I find out.

**Comment by wesm** [comment]
Taking a closer look at this -- the file writer class does indeed accumulate metadata in-memory, so can have memory use problems if you are writing very big files with many row groups, because there's no way to flush the metadata to disk because it's in a temporary Thrift C++ object.

It seems we can definitely improve memory use by destroying the metadata builders once we're done with them, which is partly what you've done here. Let me have a hack at that and I'll push my changes here

**Comment by wesm** [comment]
I couldn't replicate the memory leak in the script attached to ARROW-3324. I checked on both 0.11.1 and master. See `test_leak3` function in `scripts/test_leak.py`:

```
$ python scripts/test_leak.py 
450: 11.97265625
Memory increased by 13.26171875 megabytes after 500 iterations
```

Here I wrote 500 row groups, where each row group has 50 columns. In this case this means about 27K in buffered metadata per row group. `sizeof(format::ColumnChunk)` is 376 bytes, so the memory increase should be _at least_

```
>>> (376 * 50 * 500) / (1 << 20)
8.96453857421875
```

**Comment by majetideepak** [comment]
So far, this looks good to me.
I think we can further reduce the memory use by removing the redundant copy of `format::RowGroup` inside `FileMetaDataBuilder::Finish()`. I will submit a patch tomorrow.

On a side note, Parquet files with many RowGroups (and many columns) are very bad for the read performance. The thrift metadata can grow to the order of hundreds of MBs. I also observed that the thrift deserialization time increases exponentially after a point as metadata size grows. I am yet to investigate the cause of this behavior. A better approach is to create multiple parquet files with a decent number of RowGroups per file and decent RowGroup (compressed) sizes.

**Comment by wesm** [comment]
OK, I'll go ahead and merge this.

My understanding it is fairly well known that Parquet performs badly when the file metadata is very large

**Pull request closed without merging**
