### PR TITLE
ARROW-676: move from MinorType to FieldType in ValueVectors to carry all the relevant type bits

### PR DESCRIPTION
**Pull request by julienledem**
I'm adding all the Type information to the vector with FieldType.
This avoids losing information and carrying around extra type metadata that can not go in the MinorType enum (for example: decimals' precision and dictionary encoding)

### CODE REVIEW

**Review by wesm — APPROVED** [review]
This seems reasonable to me, better encapsulating the type metadata. Needs to be rebased

**Comment by wesm** [comment]
@julienledem per discussion in #452 I think if we rebase and merge this, it will help with adding new data types. @elahrvivaz do you have any comments on the implementation?

**Comment by julienledem** [comment]
rebased

**Comment by wesm** [comment]
OK, let's merge this after the build runs, in case it causes any conflict with #475?

**Comment by wesm** [comment]
+1

**Pull request closed without merging**
