### PR TITLE
ARROW-14291: [CI][C++] Add cpp/examples/ files to lint targets

### PR DESCRIPTION
**Pull request by bkmgit**

### CODE REVIEW

**Review by kou — APPROVED** [review]
+1

**Comment by pitrou** [comment]
`archery lint` is now linting unrelated source files in build directories inside `cpp`.

**Comment by bkmgit** [comment]
Ok. Can update it. Is there a particular run to examine? Can specify the directories to lint more precisely.

**Comment by pitrou** [comment]
@bkmgit I'm working on a fix already.

**Comment by bkmgit** [comment]
@pitrou Ok. [Lint exclusions file](https://github.com/apache/arrow/blob/master/cpp/build-support/lint_exclusions.txt) was updated, but the build directory can have any name. The examples were not being linted, and it would be good to include these in addition to the source code - this is what motivated the change.

**Pull request closed without merging**
