### PR TITLE
ARROW-17080: [Java] Add a top-level CMakeLists.txt for JNI

### PR DESCRIPTION
**Pull request by kou**

### CODE REVIEW

**Comment by kou** [comment]
@github-actions crossbow submit java-jars

**Comment by kou** [comment]
@github-actions crossbow submit java-jars

**Comment by kou** [comment]
@github-actions crossbow submit java-jars

**Comment by kou** [comment]
@github-actions crossbow submit java-jars

**Comment by kou** [comment]
@github-actions crossbow submit java-jars

**Comment by kou** [comment]
@github-actions crossbow submit java-jars

**Comment by kou** [comment]
@github-actions crossbow submit java-jars

**Comment by kou** [comment]
@lwhite1 @davisusanibar This is ready to review/merge.

**Review by lwhite1 — APPROVED** [review]
Looks good to me. Thank you!

**Comment by davisusanibar** [comment]
@kou  Will be needed to update [Java documentation](https://arrow.apache.org/docs/developers/java/building.html#building-jni-libraries-on-macos) for these changes ?

**Review by lidavidm — APPROVED** [review]
Agreed with @davisusanibar's question, looks like this section needs a small update: https://arrow.apache.org/docs/dev/developers/java/building.html#building-jni-libraries-on-macos

**Comment by kou** [comment]
OK. Updated.

Note that the documentation will be updated again by ARROW-17081.

**Review by lidavidm — APPROVED** [review]

**Pull request merged**
