### PR TITLE
ARROW-2226, ARROW-2233: [JS] Dictionary bugfixes

### PR DESCRIPTION
**Pull request by trxcllnt**
Resolves https://issues.apache.org/jira/browse/ARROW-2226

### CODE REVIEW

**Comment by TheNeuralBit** [comment]
How does this bug present itself? I thought maybe `DictionaryVector.slice` wouldn't work, but I just wrote some unit tests for that on master and it seems ok

**Comment by wesm** [comment]
Would definitely be good to have a unit test for this

**Comment by trxcllnt** [comment]
@wesm @TheNeuralBit yeah, I wanted to get a fix in first. I encountered this trying to read values from a DictionaryVector whose indices have a `nullCount > 0`. I think this was just a typo/bad merge when I merged my branch with Brian's a few weeks ago. I would imagine the Dictionary integration tests could cover this case?

**Comment by trxcllnt** [comment]
@wesm I might've asked this before, but is it possible (via the spec) for the `indices` itself to be a DictionaryVector? We don't guard against doing it on-the-fly, but if we want to support it, we should probably go through the public `indicies.nullCount` instead of using the private `_nullCount` here.

**Comment by wesm** [comment]
The indices are supposed to be a signed integer type

**Comment by TheNeuralBit** [comment]
I already started adding some basic unit tests for DictionaryVector, so I'll look at adding a test that covers the indices `nullCount > 0` case and maybe PR them into your branch @trxcllnt

**Comment by TheNeuralBit** [comment]
Put up a PR with some tests: https://github.com/trxcllnt/arrow/pull/5
I _think_ I may have found another bug? Slicing a `DictionaryVector` with `nullCount > 0` is throwing an error

**Comment by wesm** [comment]
@TheNeuralBit you should be able to push directly to this branch, too, if that's easier

**Comment by TheNeuralBit** [comment]
Oh nice, I'll do that in the future, thanks @wesm

**Comment by trxcllnt** [comment]
@TheNeuralBit lgtm thanks! 👍

**Pull request closed without merging**
