### PR TITLE
ARROW-9206: [C++][Flight] Add latency benchmark

### PR DESCRIPTION
**Pull request by cyb70289**
Calculate latency by accumulating processing time of all threads then
divides total batches transferred. It only works for synchronous RPC.

This patch also adds throughput(IOPS) metric.

### CODE REVIEW

**Comment by cyb70289** [comment]
CI failure reproduces [[Python][C++] Non-deterministic segfault in "AMD64 MacOS 10.15 Python 3.7" build](https://issues.apache.org/jira/browse/ARROW-8999)

**Comment by pitrou** [comment]
You can't compute latency like that if the test is multithreaded.

**Comment by cyb70289** [comment]
> You can't compute latency like that if the test is multithreaded.

Assume two threads, one finishes `n1` IO in `t1` time, another finishes `n2` IO in `t2` time. So the average latency should be `(t1/n1 + t2/n2) / 2`, not `(t1+t2) / (n1+n2)`?

**Comment by pitrou** [comment]
IMHO it should be `(t1+t2) / (n1+n2)`. Is it what the code is doing?

**Comment by cyb70289** [comment]
> IMHO it should be `(t1+t2) / (n1+n2)`. Is it what the code is doing?

Yes, this is what the code is doing.

**Comment by pitrou** [comment]
Ok, then I was mistaken. Sorry :-)

**Review by pitrou — APPROVED** [review]
+1 from me. @lidavidm Any opinion?

**Review by lidavidm — APPROVED** [review]
+1 from me but I think it'd be good to eventually have a latency-focused benchmark that measures individual batches so we can also get a min/max/distribution.

**Pull request closed without merging**
