### PR TITLE
ARROW-12991: [CI] Migrate Travis-CI ARM job to "arm64-graviton2" arch

### PR DESCRIPTION
**Pull request by pitrou**

### CODE REVIEW

**Comment by pitrou** [comment]
@kou

**Comment by pitrou** [comment]
@jorisvandenbossche Do you know what the right way to solve the `No module named 'setuptools'` error is?

**Comment by kszucs** [comment]
@pitrou If I recall correctly I managed to resolve that once with the manylinux wheels. I suggest you to use the exact same travis config as we have in the [manylinux task](https://github.com/apache/arrow/blob/master/dev/tasks/python-wheels/travis.linux.arm64.yml#L20-L31).

**Comment by kou** [comment]
I forgot that we need to `group: edge` for `arm64-graviton2`.

https://docs.travis-ci.com/user/multi-cpu-architectures/#example-multi-architecture-build-matrix

> Note that group: edge is required for arm64-graviton2 architectures.

**Comment by kou** [comment]
`virt` is also required.

https://docs.travis-ci.com/user/multi-cpu-architectures/#testing-on-multiple-cpu-architectures

> The arm64-graviton2 architecture builds can be run on both LXD and regular ‘full VM’ environments. You need to explicitely set the target environment by using virt key. A virt: vm routes build jobs to a full virtual machine setup while virt: lxd routes build jobs to an LXD container setup.

**Review by kou — APPROVED** [review]
+1

**Pull request closed without merging**
