### PR TITLE
GH-38702 [C++]: Implement AzureFileSystem::DeleteRootDirContents

### LINKED ISSUE #38702: [C++][FS][Azure] Implement `DeleteRootDirContents()`
### Describe the enhancement requested

It's not implemented yet.

This is a child of GH-18014.

### Component(s)

C++

### PR DESCRIPTION
**Pull request by felipecrv**
### Rationale for this change

This copies the behavior implemented by S3FileSystem.

### What changes are included in this PR?

An implementation of `DeleteRootDirContent` that prevents deletion of all blob containers.

### Are these changes tested?

N/A.
* Closes: #38702

### CODE REVIEW

**Comment by felipecrv** [comment]
@kou @Tom-Newton

**Review by kou — APPROVED** [review]
+1

We will implement this when we add `allow_container_deletion` #38999, right?
(Or we may add one more option only for this something like `allow_all_containers_deletion`?)

**Review by Tom-Newton — APPROVED** [review]

**Comment by Tom-Newton** [comment]
Personally I think it's reasonable to never implement this.

**Comment by felipecrv** [comment]
> +1
> 
> We will implement this when we add `allow_container_deletion` #38999, right? (Or we may add one more option only for this something like `allow_all_containers_deletion`?)

s3fs doesn't infer that it's OK to delete all the buckets from these options and doesn't have an option allowing deleting everything. I think anyone that wants to delete all containers will either do it manually or via the official SDK if the want to do it programmatically.

**Pull request merged**
