### PR TITLE
ARROW-887: add default value to units for backward compatibility

### PR DESCRIPTION
**Pull request by julienledem**

### CODE REVIEW

**Comment by jacques-n** [comment]
Looks good to me. @julienledem, were there any other types/unit we introduced recently that also need this change?

**Comment by julienledem** [comment]
@jacques-n I did a diff since 0.2 and added a default for Time.bitWidth as well.
AFAICT those are the only fields that have been added.

**Comment by jacques-n** [comment]
Cool.

Thanks for turning this around so quickly.
+1

**Review by wesm — APPROVED** [review]
+1

**Pull request closed without merging**
