### PR TITLE
ARROW-3301: [Website] Update Jekyll and Bootstrap 4

### PR DESCRIPTION
**Pull request by xhochy**
Screenshot:

127 0 0 1_4000_ ipad pro

### CODE REVIEW

**Comment by xhochy** [comment]
I noticed that we had no text that runs alongside the columnar vs row-wise image. Any suggestions what to put there?

**Review by wesm — APPROVED** [review]
LGTM. I can write some text for the "advantages" part if you like

**Comment by wesm** [comment]
I'll write some placeholder text here in the next hours and merge this, then update the website

**Comment by xhochy** [comment]
@wesm Awesome, thanks!

**Comment by wesm** [comment]
Merged this and just pushed a website update

**Pull request closed without merging**
