### PR TITLE
ARROW-17292: [C++] Segmentation fault on arrow-compute-hash-join-node-test on macos nightlies

### PR DESCRIPTION
**Pull request by vibhatha**
**DO NOT REVIEW OR MERGE**

created merely to test crossbows

### CODE REVIEW

**Comment by vibhatha** [comment]
@github-actions crossbow submit verify-rc-source-cpp-macos-conda-amd64

**Comment by vibhatha** [comment]
@github-actions crossbow submit verify-rc-source-cpp-macos-conda-amd64

**Comment by vibhatha** [comment]
@github-actions crossbow submit verify-rc-source-cpp-macos-conda-amd64

**Comment by vibhatha** [comment]
@github-actions crossbow submit verify-rc-source-integration-macos-conda-amd64

**Comment by vibhatha** [comment]
@github-actions crossbow submit verify-rc-source-python-macos-amd64

**Comment by vibhatha** [comment]
@github-actions crossbow submit verify-rc-source-cpp-macos-conda-amd64

**Comment by vibhatha** [comment]
@github-actions crossbow submit verify-rc-source-python-macos-amd64

**Comment by vibhatha** [comment]
@github-actions crossbow submit verify-rc-source-cpp-macos-conda-amd64

**Comment by vibhatha** [comment]
@github-actions crossbow submit verify-rc-source-integration-macos-conda-amd64

**Comment by vibhatha** [comment]
@github-actions crossbow submit verify-rc-source-python-macos-amd64

**Comment by vibhatha** [comment]
@github-actions crossbow submit verify-rc-source-cpp-macos-conda-amd64

**Comment by vibhatha** [comment]
@github-actions crossbow submit verify-rc-source-integration-macos-conda-amd64

**Comment by vibhatha** [comment]
@github-actions crossbow submit verify-rc-source-python-macos-amd64

**Comment by vibhatha** [comment]
@github-actions crossbow submit verify-rc-source-integration-macos-conda-amd64

**Comment by vibhatha** [comment]
@github-actions crossbow submit verify-rc-source-integration-macos-conda-amd64

**Comment by vibhatha** [comment]
@github-actions crossbow submit verify-rc-source-integration-macos-conda-amd64

**Comment by vibhatha** [comment]
@github-actions crossbow submit verify-rc-source-integration-macos-conda-amd64

**Comment by vibhatha** [comment]
@github-actions crossbow submit verify-rc-source-cpp-macos-conda-amd64

**Comment by vibhatha** [comment]
@github-actions crossbow submit verify-rc-source-cpp-macos-conda-amd64

**Comment by vibhatha** [comment]
@github-actions crossbow submit verify-rc-source-cpp-macos-conda-amd64

**Comment by vibhatha** [comment]
@github-actions crossbow submit verify-rc-source-integration-macos-conda-amd64

**Comment by vibhatha** [comment]
@github-actions crossbow submit verify-rc-source-integration-macos-conda-amd64

**Comment by vibhatha** [comment]
@github-actions crossbow submit verify-rc-source-integration-macos-conda-amd64

**Comment by vibhatha** [comment]
@github-actions crossbow submit verify-rc-source-python-macos-amd64

**Comment by vibhatha** [comment]
@github-actions crossbow submit verify-rc-source-python-macos-amd64

**Comment by vibhatha** [comment]
@github-actions crossbow submit verify-rc-source-python-macos-amd64

**Comment by vibhatha** [comment]
@github-actions crossbow submit verify-rc-source-cpp-macos-conda-amd64

**Comment by vibhatha** [comment]
@github-actions crossbow submit verify-rc-source-cpp-macos-conda-amd64

**Comment by vibhatha** [comment]
@github-actions crossbow submit verify-rc-source-integration-macos-conda-amd64

**Comment by vibhatha** [comment]
@github-actions crossbow submit verify-rc-source-integration-macos-conda-amd64

**Comment by vibhatha** [comment]
@github-actions crossbow submit verify-rc-source-integration-macos-conda-amd64

**Comment by vibhatha** [comment]
@github-actions crossbow submit verify-rc-source-python-macos-amd64

**Comment by vibhatha** [comment]
@github-actions crossbow submit verify-rc-source-python-macos-amd64

**Comment by vibhatha** [comment]
@github-actions crossbow submit verify-rc-source-python-macos-amd64

**Comment by vibhatha** [comment]
@github-actions crossbow submit verify-rc-source-cpp-macos-conda-amd64

**Comment by vibhatha** [comment]
@github-actions crossbow submit verify-rc-source-cpp-macos-conda-amd64

**Comment by vibhatha** [comment]
@github-actions crossbow submit verify-rc-source-integration-macos-conda-amd64

**Comment by vibhatha** [comment]
@github-actions crossbow submit verify-rc-source-integration-macos-conda-amd64

**Comment by vibhatha** [comment]
@github-actions crossbow submit verify-rc-source-integration-macos-conda-amd64

**Comment by vibhatha** [comment]
@github-actions crossbow submit verify-rc-source-python-macos-amd64

**Comment by vibhatha** [comment]
@github-actions crossbow submit verify-rc-source-python-macos-amd64

**Comment by vibhatha** [comment]
@github-actions crossbow submit verify-rc-source-python-macos-amd64

**Comment by vibhatha** [comment]
@github-actions crossbow submit verify-rc-source-cpp-macos-conda-amd64

**Comment by vibhatha** [comment]
@github-actions crossbow submit verify-rc-source-cpp-macos-conda-amd64

**Comment by vibhatha** [comment]
@github-actions crossbow submit verify-rc-source-cpp-macos-conda-amd64

**Comment by vibhatha** [comment]
@github-actions crossbow submit verify-rc-source-cpp-macos-conda-amd64

**Comment by vibhatha** [comment]
@github-actions crossbow submit verify-rc-source-integration-macos-conda-amd64

**Comment by vibhatha** [comment]
@github-actions crossbow submit verify-rc-source-python-macos-amd64

**Comment by westonpace** [comment]
Should we close this?

**Comment by vibhatha** [comment]
@westonpace We didn't finalize this ticket, right?

**Comment by westonpace** [comment]
Are we still seeing the issue?  I was hopeful that https://issues.apache.org/jira/browse/ARROW-18018 was the root cause for the macos nightlies failures.  I imagine we've have enough runs since then to see if this has happened again.

**Comment by vibhatha** [comment]
> https://issues.apache.org/jira/browse/ARROW-18018

Yes probably, you're correct here. Let's close this one.

**Pull request closed without merging**
