### PR TITLE
ARROW-7178: [C++] Vendor forward compatible std::optional

### PR DESCRIPTION
**Pull request by gawain-bolton**
Add a version of std::optional vendored from
https://github.com/martinmoene/optional-lite using git tag v3.2.0

### CODE REVIEW

**Review by bkietz — CHANGES_REQUESTED** [review]
Please amend LICENSE.txt

**Comment by pitrou** [comment]
+1 from me.

**Review by bkietz — APPROVED** [review]
merging

**Comment by bkietz** [comment]
@gawain-bolton please assign yourself on JIRA, I wasn't able to do so for some reason

**Pull request closed without merging**
