### PR TITLE
GH-34242: [C++][Parquet] Optimize comment and move for shared_ptr in parquet schema

### LINKED ISSUE #34242: [C++][Parquet] Remove unnecessary shared_ptr copy
### Describe the enhancement requested

C++ Parquet use lots of unnecessary `shared_ptr` copy. `shared_ptr` copy will increment atomic counter, and be bad for optimize. This issue just want to improve it.

### Component(s)

C++, Parquet

### PR DESCRIPTION
**Pull request by mapleFU**
### Rationale for this change

This patch fix some comments, and remove some copying for shared_ptr, using reference or `std::move` instead.

### What changes are included in this PR?

Some comment and shared_ptr usage fix

### Are these changes tested?

No

### Are there any user-facing changes?

No

* Closes: #34242

### CODE REVIEW

**Comment by mapleFU** [comment]
@emkornfield @wjones127 This patch is small and trivial, PTAL

**Review by emkornfield — APPROVED** [review]

**Comment by mapleFU** [comment]
Retrigger because CI failed

**Comment by mapleFU** [comment]
@emkornfield @wjones127 CI failed because timeout...Should I trigger rerun or waiting you to trigger?

**Review by wgtmac — APPROVED** [review]

**Review by wjones127 — APPROVED** [review]
Looks good. Thanks @mapleFU

**Pull request merged**
