### PR TITLE
ARROW-3202: [C++] Fix compilation on Alpine Linux by using ARROW_WITH_BACKTRACE define

### PR DESCRIPTION
**Pull request by bskaggs**
Should fix #2818.

### CODE REVIEW

**Comment by wesm** [comment]
We should probably set up an Alpine Dockerfile so we can easily check that the build works, any volunteers?

**Comment by wesm** [comment]
Please also open a JIRA issue for this work

**Comment by wesm** [comment]
Best to reuse https://issues.apache.org/jira/browse/ARROW-3202. There is a Dockerfile / repro there that could be used also

**Comment by kszucs** [comment]
@wesm testable via https://github.com/apache/arrow/pull/3059

**Comment by wesm** [comment]
Thanks @kszucs! I'm going to merge this and then we can address any follow ups in #3059

**Review by wesm — APPROVED** [review]
+1

**Pull request closed without merging**
