### PR TITLE
ARROW-3591: [R] Support for collecting decimal types

### PR DESCRIPTION
**Pull request by javierluraschi**
Fix for https://issues.apache.org/jira/browse/ARROW-3591, implemented following Python string to decimal conversion: https://github.com/apache/arrow/blob/master/cpp/src/arrow/python/arrow_to_pandas.cc#L723.

Note: We could consider a more efficient conversion from decimal to R's integer or numeric types depending on the precision/scale from Arrows decimal; however, my guess is that this has been explored before for other languages and there is no straightforward `memcpy()` version of cross language decimal type conversions since the internal representation has been implemented as language specific.

Bonus: Added accessors in the `schema` wrapper for `num_fields()` and `field()` which can help diagnose schema issues.

### CODE REVIEW

**Review by romainfrancois — COMMENTED** [review]
Wondering if there is a way to keep the information, rather than converting to a double vector. 

Maybe inspired by the `rational` example in `vctrs`. https://vctrs.r-lib.org/articles/s3-vector.html#rational

**Comment by romainfrancois** [comment]
🤔 this is kind of confusing from https://github.com/apache/arrow/blob/42cf69abfc1368c9884f4581811e2e7900c98fcd/cpp/src/arrow/util/decimal.h#L35

```
/// Represents a signed 128-bit integer in two's complement.
/// Calculations wrap around and overflow is ignored.
///
/// For a discussion of the algorithms, look at Knuth's volume 2,
/// Semi-numerical Algorithms section 4.3.1.
///
/// Adapted from the Apache ORC C++ implementation
class ARROW_EXPORT Decimal128 {
```

but looking at the tests this is indeed a decimal

https://github.com/apache/arrow/blob/e0f70bbf9bc8eb909373abaaf0b4c9f50bc0a2d6/cpp/src/arrow/util/decimal-test.cc#L307

```cpp
INSTANTIATE_TEST_CASE_P(Decimal128PrintingTest, Decimal128PrintingTest,
                        ::testing::Values(std::make_tuple(123, 1, "12.3"),
                                          std::make_tuple(123, 5, "0.00123"),
                                          std::make_tuple(123, 10, "1.23E-8"),
                                          std::make_tuple(123, -1, "1.23E+3"),
                                          std::make_tuple(-123, -1, "-1.23E+3"),
                                          std::make_tuple(123, -3, "1.23E+5"),
                                          std::make_tuple(-123, -3, "-1.23E+5"),
                                          std::make_tuple(12345, -3, "1.2345E+7")));
```

@hadley would this be a good example of a `vctrs` record implemented as a list of two integer vectors, or perhaps a better approach would be a list of one complex vector (which uses 128 bits, just like Decimal128) so that we could minimize copies. 

Can I assume that if we do the "right" thing and implement this as a record, then the complex vector would only be an implementation detail that would be not so easy for the user to get to ?

**Comment by romainfrancois** [comment]
Generally speaking, would things like this and int64 be safer if implemented as a `vctrs` record ?

**Comment by hadley** [comment]
Yes, definitely.

**Comment by romainfrancois** [comment]
Great. @javierluraschi i’ll play around with a record based implementation for decimal128

**Comment by hadley** [comment]
For int64, we have to copy what the DBI package do in order to be consistent.

**Comment by romainfrancois** [comment]
My understanding is that by default we should return an `integer64`, and then places that want to convert it to a `double` or `integer` vector can always use the converters, those are explicit. Can you confirm @krlmlr ?

@javierluraschi that does not mean that the user has to explicitly use the `as.*` methods but package code can. 

We might have to consider changing the `Array$as_vector()` method in favor of something more flexible if we want to avoid the `Array` -> `bit64::integer64` -> `numeric` roundtrip.

**Comment by romainfrancois** [comment]
I would rather like something closer to the arrow layout initially (lossless) and the possibility to convert to doubles then.

**Comment by javierluraschi** [comment]
That's fine but can we merge this one and then replace with something better?

**Comment by romainfrancois** [comment]
That’s fine by me, as long as you realise this will likely change.

**Comment by javierluraschi** [comment]
Yes, that's totally fine with me.

**Comment by krlmlr** [comment]
@romainfrancois: The native DBI backends return an `integer64`, but the specification is kept vague on purpose so that the actual implementation can change later. Also, `dbConnect()` has a `bigint` argument that controls if conversion to `numeric` or `integer` happens immediately.

**Comment by javierluraschi** [comment]
@wesm merge please? Looks like Romain and I are both 👍 to get this merged.

**Comment by kou** [comment]
I've merged!
Thanks!

**Pull request closed without merging**
