### PR TITLE
MINOR: [C++] Remove unnecessary ; failing the linter

### PR DESCRIPTION
**Pull request by felipecrv**
This caused another PR of mine to fail the linter check because I touched this file.

### CODE REVIEW

**Comment by felipecrv** [comment]
@benibus an easy review :)

**Comment by kou** [comment]
Could you check CI failures?

**Comment by kou** [comment]
Could you use the pull request template content next time?

**Comment by felipecrv** [comment]
@kou I'm closing this now that I realized this is probably a linter bug since the `;` in this line is needed.

**Pull request closed without merging**
