### PR TITLE
GH-37488: [C++] Disable unity build for Azure SDK for C++

### LINKED ISSUE #37488: [C++] Azure SDK for C++ build is failed with unity build
### Describe the bug, including details regarding any error messages, version, and platform.

test-ubuntu-22.04-docs

https://github.com/ursacomputing/crossbow/actions/runs/6033190366/job/16369520061#step:7:6744

```text
FAILED: _deps/azure_sdk-build/sdk/core/azure-core/CMakeFiles/azure-core.dir/Unity/unity_2_cxx.cxx.o 
/usr/bin/ccache /usr/lib/ccache/c++ -DARROW_HAVE_RUNTIME_AVX2 -DARROW_HAVE_RUNTIME_AVX512 -DARROW_HAVE_RUNTIME_BMI2 -DARROW_HAVE_RUNTIME_SSE4_2 -DARROW_HAVE_SSE4_2 -DARROW_NO_DEPRECATED_API -DARROW_WITH_RE2 -DARROW_WITH_TIMING_TESTS -DARROW_WITH_UTF8PROC -DAZ_RTTI -DBUILD_CURL_HTTP_TRANSPORT_ADAPTER -I/build/cpp/_deps/azure_sdk-src/sdk/core/azure-core/inc -fdiagnostics-color=always -g -Werror -O0 -ggdb -g1 -Wno-error -fPIC -fno-operator-names -Wold-style-cast -Wall -Wextra -pedantic -std=c++14 -MD -MT _deps/azure_sdk-build/sdk/core/azure-core/CMakeFiles/azure-core.dir/Unity/unity_2_cxx.cxx.o -MF _deps/azure_sdk-build/sdk/core/azure-core/CMakeFiles/azure-core.dir/Unity/unity_2_cxx.cxx.o.d -o _deps/azure_sdk-build/sdk/core/azure-core/CMakeFiles/azure-core.dir/Unity/unity_2_cxx.cxx.o -c /build/cpp/_deps/azure_sdk-build/sdk/core/azure-core/CMakeFiles/azure-core.dir/Unity/unity_2_cxx.cxx
In file included from /build/cpp/_deps/azure_sdk-build/sdk/core/azure-core/CMakeFiles/azure-core.dir/Unity/unity_2_cxx.cxx:17:
/build/cpp/_deps/azure_sdk-src/sdk/core/azure-core/src/http/url.cpp: In function 'bool {anonymous}::ShouldEncode(char)':
/build/cpp/_deps/azure_sdk-src/sdk/core/azure-core/src/http/url.cpp:136:11: error: reference to '_internal' is ambiguous
  136 |   return !_internal::StringExtensions::IsAlphaNumeric(c)
      |           ^~~~~~~~~
In file included from /build/cpp/_deps/azure_sdk-src/sdk/core/azure-core/inc/azure/core/case_insensitive_containers.hpp:11,
                 from /build/cpp/_deps/azure_sdk-src/sdk/core/azure-core/inc/azure/core/http/policies/policy.hpp:11,
                 from /build/cpp/_deps/azure_sdk-src/sdk/core/azure-core/src/http/policy.cpp:4,
                 from /build/cpp/_deps/azure_sdk-build/sdk/core/azure-core/CMakeFiles/azure-core.dir/Unity/unity_2_cxx.cxx:3:
/build/cpp/_deps/azure_sdk-src/sdk/core/azure-core/inc/azure/core/internal/strings.hpp:15:46: note: candidates are: 'namespace Azure::Core::_internal { }'
   15 | namespace Azure { namespace Core { namespace _internal {
      |                                              ^~~~~~~~~
In file included from /build/cpp/_deps/azure_sdk-src/sdk/core/azure-core/inc/azure/core/http/raw_response.hpp:13,
                 from /build/cpp/_deps/azure_sdk-src/sdk/core/azure-core/inc/azure/core/exception.hpp:12,
                 from /build/cpp/_deps/azure_sdk-src/sdk/core/azure-core/inc/azure/core/http/http.hpp:13,
                 from /build/cpp/_deps/azure_sdk-src/sdk/core/azure-core/inc/azure/core/http/policies/policy.hpp:15,
                 from /build/cpp/_deps/azure_sdk-src/sdk/core/azure-core/src/http/policy.cpp:4,
                 from /build/cpp/_deps/azure_sdk-build/sdk/core/azure-core/CMakeFiles/azure-core.dir/Unity/unity_2_cxx.cxx:3:
/build/cpp/_deps/azure_sdk-src/sdk/core/azure-core/inc/azure/core/io/body_stream.hpp:163:13: note:                 'namespace Azure::Core::IO::_internal { }'
  163 |   namespace _internal {
      |             ^~~~~~~~~
In file included from /build/cpp/_deps/azure_sdk-src/sdk/core/azure-core/inc/azure/core/http/policies/policy.hpp:15,
                 from /build/cpp/_deps/azure_sdk-src/sdk/core/azure-core/src/http/policy.cpp:4,
                 from /build/cpp/_deps/azure_sdk-build/sdk/core/azure-core/CMakeFiles/azure-core.dir/Unity/unity_2_cxx.cxx:3:
/build/cpp/_deps/azure_sdk-src/sdk/core/azure-core/inc/azure/core/http/http.hpp:166:34: note:                 'namespace Azure::Core::Http::Policies::_internal { }'
  166 |   namespace Policies { namespace _internal {
      |                                  ^~~~~~~~~
/build/cpp/_deps/azure_sdk-src/sdk/core/azure-core/inc/azure/core/http/http.hpp:382:13: note:                 'namespace Azure::Core::Http::_internal { }'
  382 |   namespace _internal {
      |             ^~~~~~~~~
```

### Component(s)

C++

### PR DESCRIPTION
**Pull request by kou**
### Rationale for this change

It seems that Azure SDK for C++ doesn't support unity build.

### What changes are included in this PR?

Force to disable unity build.

### Are these changes tested?

Yes.

### Are there any user-facing changes?

No.
* Closes: #37488

### CODE REVIEW

**Comment by kou** [comment]
@github-actions crossbow submit test-ubuntu-22.04-docs

**Comment by pitrou** [comment]
> It seems that Azure SDK for C++ doesn't support unity build.

Did you report the issue upstream?

**Comment by kou** [comment]
No. I didn't think that Azure SDK for C++ should support unity build.

Anyway, I reported this: https://github.com/Azure/azure-sdk-for-cpp/issues/4921

**Comment by kou** [comment]
+1

The following error is unrelated. I'll fix it separately.

https://github.com/ursacomputing/crossbow/actions/runs/6034388088/job/16372666129#step:7:8241

```text
FAILED: arrow-cuda-glib/libarrow-cuda-glib.so.1400.0.0.p/cuda.cpp.o 
sccache c++ -Iarrow-cuda-glib/libarrow-cuda-glib.so.1400.0.0.p -Iarrow-cuda-glib -I../../arrow/c_glib/arrow-cuda-glib -I. -I../../arrow/c_glib -Iarrow-glib -I/usr/local/include -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=c++17 -O0 -g -Wmissing-declarations -DARROW_NO_DEPRECATED_API -fPIC -MD -MQ arrow-cuda-glib/libarrow-cuda-glib.so.1400.0.0.p/cuda.cpp.o -MF arrow-cuda-glib/libarrow-cuda-glib.so.1400.0.0.p/cuda.cpp.o.d -o arrow-cuda-glib/libarrow-cuda-glib.so.1400.0.0.p/cuda.cpp.o -c ../../arrow/c_glib/arrow-cuda-glib/cuda.cpp
In file included from /usr/local/include/arrow/gpu/cuda_api.h:21,
                 from ../../arrow/c_glib/arrow-cuda-glib/cuda.hpp:22,
                 from ../../arrow/c_glib/arrow-cuda-glib/cuda.cpp:29:
/usr/local/include/arrow/gpu/cuda_context.h:155:26: error: 'CUstream' does not name a type; did you mean 'Stream'?
  155 |     [[nodiscard]] inline CUstream value() const noexcept {
      |                          ^~~~~~~~
      |                          Stream
/usr/local/include/arrow/gpu/cuda_context.h:161:14: error: expected type-specifier before 'CUstream'
  161 |     operator CUstream() const noexcept { return value(); }
      |              ^~~~~~~~
/usr/local/include/arrow/gpu/cuda_context.h:170:55: error: 'CUstream' has not been declared
  170 |     explicit Stream(std::shared_ptr<CudaContext> ctx, CUstream* st,
      |                                                       ^~~~~~~~
/usr/local/include/arrow/gpu/cuda_context.h:200:19: error: 'CUevent' does not name a type
  200 |     [[nodiscard]] CUevent value() const {
      |                   ^~~~~~~
/usr/local/include/arrow/gpu/cuda_context.h:206:14: error: expected type-specifier before 'CUevent'
  206 |     operator CUevent() const noexcept { return value(); }
      |              ^~~~~~~
/usr/local/include/arrow/gpu/cuda_context.h:220:58: error: 'CUevent' has not been declared
  220 |     explicit SyncEvent(std::shared_ptr<CudaContext> ctx, CUevent* ev,
      |                                                          ^~~~~~~
```

**Pull request merged**
