### PR TITLE
ARROW-14920: [C++] Use alphabetical ordering

### PR DESCRIPTION
**Pull request by bkmgit**

### CODE REVIEW

**Comment by bkmgit** [comment]
Appveyor failure seems unrelated S3FS directory deletion error.

**Comment by lidavidm** [comment]
Thanks for doing this - would you mind creating a [JIRA](https://issues.apache.org/jira/) for this, though? I believe a refactoring like this goes beyond what we consider a minor change, even if it doesn't affect functionality.

**Comment by kou** [comment]
FYI: Our "minor" definition is described at https://github.com/apache/arrow/blob/master/CONTRIBUTING.md#Minor-Fixes

> * Grammar, usage and spelling fixes that affect no more than 2 files
> * Documentation updates affecting no more than 2 files and not more than 500 words.

The URL is linked in the auto comment https://github.com/apache/arrow/pull/11785#issuecomment-981114425 .

**Comment by bkmgit** [comment]
Thanks. Created ticket https://issues.apache.org/jira/browse/ARROW-14920

**Review by pitrou — APPROVED** [review]
LGTM, will merge

**Comment by bkmgit** [comment]
Thanks

**Pull request closed without merging**
