### PR TITLE
ARROW-96: Add C++ API documentation

### PR DESCRIPTION
**Pull request by xhochy**
This adds a basic `Doxyfile` that can be used to generate the HTML API documentation as well as a small, initial "Getting Started".

The documentation is not yet deployed anywhere. We can either also use `readthedocs.org` for this (via the `breathe` package) or wait for the restructuring of the website as discussed on the ML and then add this to the "update website" scripts. I'd personally prefer the latter.

### CODE REVIEW

**Comment by xhochy** [comment]
@wesm Two things we need to review/decide here:

- [ ] Where should we upload the docs?
- [ ] Should doxygen only include the API docs or also include the usage documentation about HDFS/S3/... ? I'm in favour of that (then I would move `apidoc` into `doc` to make this clear). The only negative point I found w.r.t. this is that Doxygen's [markdown support](https://www.stack.nl/~dimitri/doxygen/manual/markdown.html) is a little different than that of Github. But in the end, you can use it to directly link to the automatically generated API docs.

**Comment by wesm** [comment]
@jacques-n @julienledem what do we need to do to be able to upload these docs to http://arrow.apache.org/doc and add a link to the homepage?

**Comment by julienledem** [comment]
@xhochy the site is deployed automatically based on https://github.com/apache/arrow-site which committers should have access too.
We don't have much of a process for this yet.
For the release I just committed the link:
https://github.com/apache/arrow-site/commit/9ea653e851b0ac3a534965fd0b06168bd88e8a38

**Review by wesm — APPROVED** [review]
+1 -- merging this. @xhochy let's pursue the documentation builds / website updates separately

**Pull request closed without merging**
