### PR TITLE
ARROW-4263: [Rust] Donate DataFusion

### PR DESCRIPTION
**Pull request by andygrove**
This PR is to donate the DataFusion source code (assuming that the vote passes!)

### CODE REVIEW

**Comment by wesm** [comment]
You can squash the branch this way

```
git checkout -b ARROW-4263-squash
git fetch apache
git reset --hard apache/master
git merge --squash
git commit -m "commit message here"
git checkout ARROW-4263
git reset --hard ARROW-4263-squash
git push -f
```

If you make a mistake you can recover using the reflog. see also https://ohshitgit.com/

**Comment by wesm** [comment]
(Generally once you have merge commits in a branch, rebasing is off the table)

**Comment by wesm** [comment]
Can you move the test data files to arrow-testing?

```
3.35s$ $TRAVIS_BUILD_DIR/ci/travis_release_audit.sh
NOT APPROVED: rust/datafusion/test/data/aggregate_test_1.csv (apache-arrow/rust/datafusion/test/data/aggregate_test_1.csv): false
NOT APPROVED: rust/datafusion/test/data/aggregate_test_2.csv (apache-arrow/rust/datafusion/test/data/aggregate_test_2.csv): false
NOT APPROVED: rust/datafusion/test/data/all_types.csv (apache-arrow/rust/datafusion/test/data/all_types.csv): false
NOT APPROVED: rust/datafusion/test/data/all_types_flat.csv (apache-arrow/rust/datafusion/test/data/all_types_flat.csv): false
NOT APPROVED: rust/datafusion/test/data/null_test.csv (apache-arrow/rust/datafusion/test/data/null_test.csv): false
NOT APPROVED: rust/datafusion/test/data/numerics.csv (apache-arrow/rust/datafusion/test/data/numerics.csv): false
NOT APPROVED: rust/datafusion/test/data/people.csv (apache-arrow/rust/datafusion/test/data/people.csv): false
NOT APPROVED: rust/datafusion/test/data/uk_cities.csv (apache-arrow/rust/datafusion/test/data/uk_cities.csv): false
8 unapproved licences. Check rat report: rat.txt
```

**Comment by andygrove** [comment]
@wesm I have created a PR against arrow-testing:

https://github.com/apache/arrow-testing/pull/1

**Comment by kou** [comment]
Could you re-add a change for https://github.com/apache/arrow/blob/master/dev/release/00-prepare.sh#L101-L105 ?

**Comment by andygrove** [comment]
Once https://github.com/apache/arrow/pull/3547 and https://github.com/apache/arrow-testing/pull/1 are merged, I can delete the test data file from this PR and update the tests to use the version from arrow-testing

**Comment by wesm** [comment]
The IP clearance vote is passed

**Comment by wesm** [comment]
I just merged https://github.com/apache/arrow-testing/pull/1. Let me know when this is ready to merge =)

**Comment by andygrove** [comment]
@wesm Tests pass for me locally so hopefully we're good to go once Travis has run ...

**Comment by andygrove** [comment]
Travis is happy

**Comment by andygrove** [comment]
Appveyor is happy too. Let's do this!

**Comment by wesm** [comment]
:+1:

**Comment by paddyhoran** [comment]
Excited to see this merged, thanks @andygrove

**Pull request closed without merging**
