### PR TITLE
ARROW-5842: [Java] Revise the semantic of lastSet in ListVector

### PR DESCRIPTION
**Pull request by liyafan82**
The lastSet member in ListVector seems misleading. According to the name, it should refers to the last index that is actually set. However, from the context of the code, it actually means the next index that will be set.

We fix this problem, and make it consistent with the lastSet in BaseVariableWidthVector.

### CODE REVIEW

**Comment by pravindra** [comment]
lgtm.

can you please hold on the merge for a day ? I'd like to test the change with dremio.

**Comment by liyafan82** [comment]
> lgtm.
> 
> @liyafan82 can you please hold on the merge for a day ? I'd like to test the change with dremio.

@pravindra , thanks a lot for your review. 
Just take your time. I can hold it until you think it is OK. 
Maybe you can add a "require change" in this PR.

**Comment by pravindra** [comment]
@liyafan82 I tested your change with dremio, and it works fine. thanks !

**Comment by liyafan82** [comment]
> @liyafan82 I tested your change with dremio, and it works fine. thanks !

@pravindra ， thanks a lot for your confirmation.

**Review by pravindra — APPROVED** [review]

**Pull request closed without merging**
