### PR TITLE
ARROW-17193: [C++] Add support for finding system Abseil

### PR DESCRIPTION
**Pull request by kou**

### CODE REVIEW

**Comment by kou** [comment]
@github-actions crossbow submit -g nightly-tests -g nightly-packaging -g nightly-release

**Comment by kou** [comment]
@github-actions crossbow submit -g linux

**Comment by kou** [comment]
@github-actions crossbow submit debian-* ubuntu-jammy-*

**Comment by kou** [comment]
@github-actions crossbow submit ubuntu-jammy-*

**Comment by kszucs** [comment]
@github-actions crossbow submit -g nightly-tests -g nightly-packaging -g nightly-release

**Comment by kou** [comment]
@github-actions crossbow submit *ubuntu-22.04* *fedora-35* test-r-gcc* r-binary-packages homebrew*

**Comment by kou** [comment]
@github-actions crossbow submit -g nightly-tests -g nightly-packaging -g nightly-release

**Comment by kou** [comment]
This is ready.

**Review by rok — APPROVED** [review]
Looks good and works on my M1!

**Comment by kou** [comment]
+1

**Pull request merged**
