### PR TITLE
ARROW-13424: [C++] Remove needless workaround for conda and benchmark

### PR DESCRIPTION
**Pull request by kou**
https://github.com/google/benchmark/issues/1046 has been resolved.

### CODE REVIEW

**Comment by kou** [comment]
@pitrou Could you try this? I don't have conda environment.

**Review by pitrou — APPROVED** [review]
Tried this and it fixed the issue. Thank you @kou !

**Comment by pitrou** [comment]
@github-actions crossbow submit -g cpp

**Comment by pitrou** [comment]
@github-actions crossbow submit -g conda

**Pull request closed without merging**
