### PR TITLE
ARROW-5679: [Python][CI] Remove Python 3.5 support

### PR DESCRIPTION
**Pull request by pitrou**

### CODE REVIEW

**Comment by pitrou** [comment]
@github-actions crossbow submit -g python

**Comment by jorisvandenbossche** [comment]
Looking at that comment with the list of triggered builds, we should add builds with Python 3.9 to our CI. But that's another issue :)

**Comment by xhochy** [comment]
> Looking at that comment with the list of triggered builds, we should add builds with Python 3.9 to our CI. But that's another issue :)

We should probably merge most of https://github.com/apache/arrow/pull/8386

**Comment by pitrou** [comment]
@emkornfield opined on this on the ML.

**Review by xhochy — APPROVED** [review]
@pitrou You mean `review` instead `rewrite`? Looks good to me.

**Comment by pitrou** [comment]
Yes, sorry :-)

**Pull request closed without merging**
