### PR TITLE
ARROW-12649: [Python/Packaging] Move conda-aarch64 to Azure with cross-compilation

### PR DESCRIPTION
**Pull request by xhochy**

### CODE REVIEW

**Comment by xhochy** [comment]
@github-actions crossbow submit conda-*-arm64

**Comment by xhochy** [comment]
@github-actions crossbow submit conda-*-arm64

**Comment by xhochy** [comment]
@github-actions crossbow submit conda-*-arm64

**Comment by xhochy** [comment]
@github-actions crossbow submit conda-*-arm64

**Comment by kszucs** [comment]
@github-actions crossbow submit conda-*-arm64

**Review by kszucs — APPROVED** [review]
Thanks Uwe! Merging on green!

**Pull request closed without merging**
