### PR TITLE
GH-35053: [Java] Fix MemoryUtil to support Java 21

### LINKED ISSUE #35053: MemoryUtil.directBuffer throws UnsupportedOperationException on Java 21
### Describe the bug, including details regarding any error messages, version, and platform.

On an early access build of Java 21, I'm seeing some failures in Apache Arrow tests. The same tests work on Java 17, 18, 19 and 20.

Test failures all look like this:
```
java.lang.UnsupportedOperationException: sun.misc.Unsafe or java.nio.DirectByteBuffer.<init>(long, int) not available
       org.apache.arrow.memory.util.MemoryUtil.directBuffer(MemoryUtil.java:167)
       org.apache.arrow.memory.ArrowBuf.getDirectBuffer(ArrowBuf.java:228)
       org.apache.arrow.memory.ArrowBuf.nioBuffer(ArrowBuf.java:223)
       org.apache.arrow.vector.ipc.ReadChannel.readFully(ReadChannel.java:87)
       org.apache.arrow.vector.ipc.message.MessageSerializer.readMessageBody(MessageSerializer.java:727)
       org.apache.arrow.vector.ipc.message.MessageChannelReader.readNext(MessageChannelReader.java:67)
       org.apache.arrow.vector.ipc.ArrowStreamReader.loadNextBatch(ArrowStreamReader.java:145)
```

From a brief investigation, it looks like the private `(long, int)` constructor has been replaced with a `(long, long)` constructor in Java 21. (See https://github.com/openjdk/jdk/blob/42fa000a7d042e425913aab2842f8166a0c2172a/src/java.base/share/classes/java/nio/Direct-X-Buffer.java.template#L180-L188 and https://github.com/openjdk/jdk/commit/a56598f5a534cc9223367e7faa8433ea38661db9)

### Component(s)

Java

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
### Rationale for this change

Java 21 switched `DirectByteBuffer(long,int)` constructor to `DirectByteBuffer(long,long)` via https://github.com/openjdk/jdk/commit/a56598f5a534cc9223367e7faa8433ea38661db9
 
### What changes are included in this PR?
In order to avoid `NoSuchMethodException` error in Java 21 environment, this PR aims to choose one of constructors based on the Java version like https://github.com/netty/netty/pull/13366 .
 
### Are these changes tested?

```
$ java -version
openjdk version "21-ea" 2023-09-19
OpenJDK Runtime Environment (build 21-ea+28-2377)
OpenJDK 64-Bit Server VM (build 21-ea+28-2377, mixed mode, sharing)

$ cd java

$ mvn clean package --am --pl memory/memory-core
...
[INFO] Apache Arrow Java Root POM ......................... SUCCESS [  5.693 s]
[INFO] Arrow Memory ....................................... SUCCESS [  1.703 s]
[INFO] Arrow Memory - Core ................................ SUCCESS [  7.050 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  14.630 s
[INFO] Finished at: 2023-06-28T20:43:29-07:00
[INFO] ------------------------------------------------------------------------
```

### Are there any user-facing changes?

* Closes: #35053

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
The `Java JNI` pipeline's `flight-core` failure looks irrelevant.
```
Error:  Failed to execute goal org.xolstice.maven.plugins:protobuf-maven-plugin:0.6.1:compile-custom (src)
on project flight-core: protoc did not exit cleanly. Review output for more information. -> [Help 1]
```

**Review by lidavidm — APPROVED** [review]
Thanks!

It looks like Java 21 isn't planned to release until September. @davisusanibar do we have an issue to track adding this to CI?

**Comment by dongjoon-hyun** [comment]
Thank you, @lidavidm . It will be GA on 19th September. Currently, GitHub Action jobs can use `21-ea` to track it.

DATE | DESCRIPTION
-- | --
2023/06/08 | Rampdown Phase One (fork from main line)
2023/07/20 | Rampdown Phase Two
2023/08/10 | Initial Release Candidate
2023/08/24 | Final Release Candidate
2023/09/19 | General Availability

**Comment by calebAtIspot** [comment]
To clarify does the latest spark (3.5.5) support Java 21? https://issues.apache.org/jira/browse/SPARK-43831 has a fix version of 4.0.0 but this PR has been merged a long time ago so I'm a bit confused.

**Pull request merged**
