### PR TITLE
ARROW-824: Date and Time Vectors should reflect timezone-less semantics

### PR DESCRIPTION
**Pull request by julienledem**
The current java vector support the timezone less version of time related types but in an incomplete way.
This change fixes it and clarifies what the vectors implementation do.
We'll need separate vectors or adapt those to deal will timezone aware time types.

### CODE REVIEW

**Comment by wesm** [comment]
I suppose failing the integration tests is good? 

```
With output:
--------------
<SNIP>
22:26:05.180 [main] DEBUG o.a.arrow.vector.file.ReadChannel - Reading buffer with size: 10
22:26:05.184 [main] DEBUG o.a.a.vector.file.ArrowFileReader - Footer starts at 5992, length: 1064
22:26:05.184 [main] DEBUG o.a.arrow.vector.file.ReadChannel - Reading buffer with size: 1064
Incompatible files
only timezone-less timestamps are supported for now: Timestamp(MILLISECOND, America/New_York)
22:26:05.281 [main] ERROR org.apache.arrow.tools.Integration - Incompatible files
java.lang.IllegalArgumentException: only timezone-less timestamps are supported for now: Timestamp(MILLISECOND, America/New_York)
	at org.apache.arrow.vector.types.Types$1.visit(Types.java:584) ~[arrow-tools-0.2.1-SNAPSHOT-jar-with-dependencies.jar:na]
	at org.apache.arrow.vector.types.Types$1.visit(Types.java:489) ~[arrow-tools-0.2.1-SNAPSHOT-jar-with-dependencies.jar:na]
	at org.apache.arrow.vector.types.pojo.ArrowType$Timestamp.accept(ArrowType.java:929) ~[arrow-tools-0.2.1-SNAPSHOT-jar-with-dependencies.jar:na]
	at org.apache.arrow.vector.types.Types.getMinorTypeForArrowType(Types.java:489) ~[arrow-tools-0.2.1-SNAPSHOT-jar-with-dependencies.jar:na]
	at org.apache.arrow.vector.types.pojo.FieldType.createNewSingleVector(FieldType.java:56) ~[arrow-tools-0.2.1-SNAPSHOT-jar-with-dependencies.jar:na]
	at org.apache.arrow.vector.types.pojo.Field.createVector(Field.java:89) ~[arrow-tools-0.2.1-SNAPSHOT-jar-with-dependencies.jar:na]
	at org.apache.arrow.vector.file.ArrowReader.initialize(ArrowReader.java:160) ~[arrow-tools-0.2.1-SNAPSHOT-jar-with-dependencies.jar:na]
	at org.apache.arrow.vector.file.ArrowReader.ensureInitialized(ArrowReader.java:143) ~[arrow-tools-0.2.1-SNAPSHOT-jar-with-dependencies.jar:na]
	at org.apache.arrow.vector.file.ArrowReader.getVectorSchemaRoot(ArrowReader.java:68) ~[arrow-tools-0.2.1-SNAPSHOT-jar-with-dependencies.jar:na]
	at org.apache.arrow.tools.Integration$Command$3.execute(Integration.java:171) ~[arrow-tools-0.2.1-SNAPSHOT-jar-with-dependencies.jar:na]
	at org.apache.arrow.tools.Integration.run(Integration.java:101) ~[arrow-tools-0.2.1-SNAPSHOT-jar-with-dependencies.jar:na]
	at org.apache.arrow.tools.Integration.main(Integration.java:62) ~[arrow-tools-0.2.1-SNAPSHOT-jar-with-dependencies.jar:na]
```

**Comment by wesm** [comment]
@julienledem could you take a look at the integration test failure?

**Comment by julienledem** [comment]
@wesm Yes, failing the test is good. FYI: I removed this JIRA from the 0.3 release. I'll update the integration test.

**Comment by wesm** [comment]
Cool

**Comment by jacques-n** [comment]
Did you evaluate using the java8 apis instead of the joda ones? There is this backport for java 7: http://www.threeten.org/threetenbp/.

**Comment by julienledem** [comment]
@jacques-n Since those classes use a different package name, it does not look like there's a benefit to have them as an intermediate step. I'd rather move to the actual java 8 classes once arrow is on java 8. Moving to LocalDateTime is already a pretty big change without adding this on top.

**Comment by jacques-n** [comment]
Got it, makes sense, thanks for the explanation @julienledem.

**Comment by julienledem** [comment]
This is good to go IMO

**Comment by wesm** [comment]
Removing the time zone feels like a regression. How difficult is it to preserve the time zone as metadata only?

**Comment by julienledem** [comment]
@wesm The current vector implementation of the TimestampVector is TimezoneLess (except it was buggy because it used DateTime instead of LocalDateTime).
 It worked in the integration tests because we never went through the Accessor.getObject/Reader/Writer java apis essentially just looking at the numeric timestamp value and ignoring the timezone.
To have a correct implementation we need a separate TZTimestampVector or a major refactor to decouple this logic from the vector.

**Comment by wesm** [comment]
Got it. I am ok with this, then. Let's open a JIRA to make a plan and implement something that works in time for 0.4 (end of this month)?

**Comment by julienledem** [comment]
@wesm OK: I have started the new vectors and some template cleanup here: https://github.com/apache/arrow/pull/644/commits/3e3ac8482cde2944b0a85d09fee7a69abe631c57

**Review by wesm — APPROVED** [review]
+1

**Pull request closed without merging**
