### PR TITLE
ARROW-11864: [R] Document arrow.int64_downcast option

### PR DESCRIPTION
**Pull request by msummersgill**
Per discussion on https://issues.apache.org/jira/browse/ARROW-9083

### CODE REVIEW

**Comment by nealrichardson** [comment]
@msummersgill did you want to add mention of this option in any other parts of the docs?

**Comment by msummersgill** [comment]
Yes, I'm planning on adding a similar note to the R package reference manual in the "Details" section "data-type" section, I'll update the PR by tomorrow with final proposed changes.

**Comment by msummersgill** [comment]
@nealrichardson Proposed changes are complete now, with the following addition to the `data-types` section of the reference manual. It didn't feel like a perfect fit in that section, but I couldn't really find a better place, if you think it would make more sense moved somewhere else I'd be happy for feedback!

>uint32 (32 bit unsigned integer), uint64 (64 bit unsigned integer), and int64 (64-bit signed integer) types may contain values that exceed the range of R's integer type (32-bit signed integer). When these arrow objects are translated to R objects, uint32 and uint64 are converted to double ("numeric") and int64 is converted to bit64::integer64. For int64 types, this conversion can be disabled (so that int64 always yields a bit64::integer64 object) by setting options(arrow.int64_downcast = FALSE).

**Comment by nealrichardson** [comment]
> It didn't feel like a perfect fit in that section

I was worried about that too, but I think it reads ok as you wrote it, thanks!

**Review by nealrichardson — APPROVED** [review]
LGTM, thanks!

**Pull request closed without merging**
