### PR TITLE
ARROW-3761: [R] Bindings for CompressedInputStream, CompressedOutputStream

### PR DESCRIPTION
**Pull request by romainfrancois**

### CODE REVIEW

**Comment by wesm** [comment]
Are you working on this somewhere else?

**Comment by romainfrancois** [comment]
I'm not.

**Comment by wesm** [comment]
Looks like you may need to `git reset --hard` to https://github.com/apache/arrow/commit/8ccc977a9b861dcaeeea56543477eefdc3d96b37 and then rebase. It should be in your reflog

**Comment by wesm** [comment]
There are no tests here. What would you like to do?

**Comment by romainfrancois** [comment]
I’m still unsure how to test this. I’ll look around in pyarrow next time i look at this branch

**Comment by wesm** [comment]
Got it. I think we just generate random bytes and write them to a compressed file, then read them back in and compare

**Comment by romainfrancois** [comment]
Makes sense. IIRC I tried to serialize a record batch but that did not work out well.

**Comment by romainfrancois** [comment]
Thanks. I’ll use that in testing.

**Comment by romainfrancois** [comment]
This will likely need to be rebased once #3043 is merged

**Review by wesm — APPROVED** [review]
+1

**Pull request closed without merging**
