### PR TITLE
Arrow-582: [Java] Added JSON read/write support for Date, Time and TImestamp types

### PR DESCRIPTION
**Pull request by BryanCutler**
Modified `JsonFileReader` and `JsonFileWriter` to support Date and Time types.  Date is written out as a Java Long and Time is written as a Java Integer.

Added new unit test to verify read/write of JSON for Date, Time and Timestamp with milliseconds types.

### CODE REVIEW

**Comment by wesm** [comment]
Can you add tests for nanoseconds with integer values exceeding 2^32?

**Comment by BryanCutler** [comment]
sure

**Comment by BryanCutler** [comment]
@wesm , do you mean a `TIME` type exceeding 2^32 nanoseconds or a `TIMESTAMPNANO` type?

**Comment by julienledem** [comment]
@wesm @BryanCutler: I think the current TimeVector in java is milliseconds only

**Comment by wesm** [comment]
@BryanCutler @julienledem do you want to coordinate to pick up the JSON support so we can get integration tests going? I will try to complete the C++ side sometime in the next week

**Comment by julienledem** [comment]
depends on: https://github.com/apache/arrow/pull/407

**Comment by BryanCutler** [comment]
It will be great to get this going!  I should have some time in the next day or so to finish this up.  @julienledem , does this also depend on ARROW-663 for additional vector value accessors?  I think it should work now for 32-bit ints so maybe just get it working for TIME in milliseconds?

**Comment by wesm** [comment]
I just opened ARROW-729. This is effectively blocked until ARROW-663 and 729 are done

**Comment by BryanCutler** [comment]
@wesm would you still want the JSON read/write test from here?  It doesn't look like the other PR had any

**Comment by wesm** [comment]
I think it's in there -- the integration tests pass

**Comment by BryanCutler** [comment]
Not the integration tests, just on the Java side that test the Java JSON reader/writer are working java/vector/src/test/java/org/apache/arrow/vector/file/json/TestJSONFile.java

**Comment by wesm** [comment]
Ah sorry, I misread. Can you submit a rebased patch with the unit tests, that would be great. Much obliged

**Comment by BryanCutler** [comment]
sure, just made #495

**Pull request closed without merging**
