### PR TITLE
ARROW-7764: [C++] Don't keep a null bitmap in ArrayData if null_count == 0

### PR DESCRIPTION
**Pull request by pitrou**
This spotted a couple bugs in kernels where null bitmaps were always iterated even if null.

### CODE REVIEW

**Comment by pitrou** [comment]
@wesm I'm not entirely sure the Parquet fixes are using the right approach, advice welcome.

**Comment by pitrou** [comment]
Also cc @fsaintjacques for review.

**Review by bkietz — APPROVED** [review]
LGTM

**Comment by fsaintjacques** [comment]
I'm wary of this one, while saving space, I think it'll uncover path where we implicitly require a bitmap non-null pointer, e.g. Gandiva.

**Comment by pitrou** [comment]
Well, the tests pass ;-)

**Review by wesm — APPROVED** [review]
+1. I hear @fsaintjacques's concerns -- however on the flip side this serves to force the issue of the superfluous bitmap in the `null_count == 0` case:

* If it is not there (which is not required in this library), then any function that expects it to be is incorrect
* Any null bitmap that is processed when null_count == 0 may be doing unnecessary computational work

It seems like the other approach to take would be the one that Java uses, namely to create a validity bitmap of all 1's for data with no nulls. 

The changes in parquet/encoding.cc are indeed a nuisance -- I briefly looked at what a generic function that accepts lambdas would look like, and it isn't too great either. 

Does someone know where the code is on the Java IPC read hot path that handles the unallocated validity bitmap? (note that the columnar format states "Arrays having a 0 null count may choose to not allocate the validity bitmap. Implementations may choose to always allocate one anyway as a matter of convenience, but this should be noted when memory is being shared.")

**Comment by wesm** [comment]
I'll leave this open for a bit before merging since there wasn't clear consensus...

**Comment by pitrou** [comment]
@wesm Well, from what I've gathered, it looks a bit messy:
* in `column_reader.cc`, there's `ColumnReaderImplBase::ReadValuesSpaced` vs. `ColumnReaderImplBase::ReadValues`
* but in the same file, there's also `TypedRecordReader::ReadValuesSpaced` vs. `TypedRecordReader::ReadValuesDense`: why? (note subtly different naming :-))

You'll see that `ReadValuesSpaced` is only called if the Parquet file may have spaced values. But perhaps in some cases the file declares an optional field that in reality is always present, in which case `null_count` ends up 0.

It seems that in `encoding.{h,cc}`, perhaps we could forego the `Decode`/`DecodeSpaced` distinction as well as `DecodeArrow`/`DecodeArrowNonNull`, and instead have the implementation switch to different paths depending on `null_count`. But that's a significant architectural change, and I don't know enough about Parquet to make a decision.

**Comment by wesm** [comment]
I see. I think the rationale for the Decode/DecodeSpaced distinction is that consumers of the decoded data may or may not want the spaced / Arrow-like memory layout in the decoded data, even when there are nulls. Since the spaced decoding takes extra computational work (the non-null values have to "moved into place") we don't force this semantic on public API users

**Comment by pitrou** [comment]
What could be done though is merge `DecodeArrow` and `DecodeArrowNonNull` together, since `DecodeArrow` already has to take a different path based on `null_count`.

**Comment by wesm** [comment]
@pitrou that sounds acceptable to me

**Comment by pitrou** [comment]
@emkornfield Would you object to this?

**Comment by pitrou** [comment]
Note that this PR actually makes some decoding a bit faster:
* before:
```
BM_ArrowBinaryPlain/DecodeArrow_Dense/65536            822259 ns       822116 ns         3381 bytes_per_second=457.569M/s
BM_ArrowBinaryPlain/DecodeArrowNonNull_Dense/65536     778227 ns       778096 ns         4015 bytes_per_second=483.455M/s
BM_ArrowBinaryPlain/DecodeArrow_Dict/65536            3609862 ns      3609246 ns          771 bytes_per_second=104.225M/s
BM_ArrowBinaryPlain/DecodeArrowNonNull_Dict/65536     3500624 ns      3500022 ns          808 bytes_per_second=107.478M/s
BM_ArrowBinaryDict/DecodeArrow_Dense/65536            2702473 ns      2702013 ns         1035 bytes_per_second=139.22M/s
BM_ArrowBinaryDict/DecodeArrowNonNull_Dense/65536     2689046 ns      2688489 ns         1034 bytes_per_second=139.921M/s
BM_ArrowBinaryDict/DecodeArrow_Dict/65536             4219876 ns      4219148 ns          670 bytes_per_second=89.159M/s
BM_ArrowBinaryDict/DecodeArrowNonNull_Dict/65536      4143485 ns      4142749 ns          677 bytes_per_second=90.8032M/s
```
* after:
```
BM_ArrowBinaryPlain/DecodeArrow_Dense/65536            690074 ns       689951 ns         4069 bytes_per_second=545.22M/s
BM_ArrowBinaryPlain/DecodeArrowNonNull_Dense/65536     692913 ns       692758 ns         4046 bytes_per_second=543.01M/s
BM_ArrowBinaryPlain/DecodeArrow_Dict/65536            3275331 ns      3274655 ns          864 bytes_per_second=114.875M/s
BM_ArrowBinaryPlain/DecodeArrowNonNull_Dict/65536     3263202 ns      3262458 ns          852 bytes_per_second=115.304M/s
BM_ArrowBinaryDict/DecodeArrow_Dense/65536            2476155 ns      2475691 ns         1128 bytes_per_second=151.947M/s
BM_ArrowBinaryDict/DecodeArrowNonNull_Dense/65536     2612045 ns      2611368 ns         1068 bytes_per_second=144.053M/s
BM_ArrowBinaryDict/DecodeArrow_Dict/65536             3986622 ns      3985459 ns          705 bytes_per_second=94.3868M/s
BM_ArrowBinaryDict/DecodeArrowNonNull_Dict/65536      3973003 ns      3971878 ns          705 bytes_per_second=94.7096M/s
```

**Comment by pitrou** [comment]
AppVeyor failure is due to a conda-forge package regression... :-/

**Comment by emkornfield** [comment]
Sorry I missed the initial ping.  I can take a look tonight.  If the question was about parquet read path I have no opinion yet

**Comment by emkornfield** [comment]
won't have time to look at this tonight, please don't block on me.

**Comment by pitrou** [comment]
Will merge, thanks everyone.

**Pull request closed without merging**
