### PR TITLE
ARROW-897: [GLib] Extract CI configuration for GLib

### PR DESCRIPTION
**Pull request by kou**

### CODE REVIEW

**Comment by wesm** [comment]
`$TRAVIS_BUILD_DIR/ci/travis_before_script_cpp.sh` is doing a lot of things that are unnecessary for the GLib build, like building the C++ unit tests and installing conda. Maybe extract a portion of that file and only build the libraries?

**Comment by kou** [comment]
How about this? https://github.com/apache/arrow/pull/713/commits/682f0bd100cdef3affb888dbd7c65c656ab3a2f1

**Comment by wesm** [comment]
Looks good to me. Thanks!

**Comment by kou** [comment]
Thanks for confirming this.
I'll add a CI configuration on macOS after this pull request is merged.

**Pull request closed without merging**
