### PR TITLE
ARROW-7158: [C++] Use compiler information provided by CMake

### PR DESCRIPTION
**Pull request by kou**
The current our approach doesn't work on non English locale
environment.

### CODE REVIEW

**Comment by kou** [comment]
@ursabot crossbow submit -g conda -g wheel -g linux

**Comment by nealrichardson** [comment]
Do we have any test/job that would exercise this? Is it worth adding one?

**Comment by kou** [comment]
> Do we have any test/job that would exercise this?

I think that most cases are covered by existing CI jobs. But some cases such as `-DARROW_USE_TSAN` aren't covered.

> Is it worth adding one?

It may be better but I don't think that we should add some CI jobs for testing this change. I think that we should add some CI jobs for target functions such as sanitizers. If we don't need some existing features, we should drop code for these features instead of adding new some CI jobs.

**Comment by kou** [comment]
@ursabot crossbow submit -g nightly

**Review by bkietz — APPROVED** [review]

**Pull request closed without merging**
