### PR TITLE
ARROW-2712: [C#] Initial C# .NET library

### PR DESCRIPTION
**Pull request by chutchinson**
PR to merge in the WIP C# implementation as directed by Wes McKinney.

### CODE REVIEW

**Comment by wesm** [comment]
The IP clearance vote has passed. We can merge this once the release audit issues are resolved:

```
NOT APPROVED: csharp/.gitattributes (apache-arrow/csharp/.gitattributes): false
NOT APPROVED: csharp/README.md (apache-arrow/csharp/README.md): false
NOT APPROVED: csharp/build/Common.props (apache-arrow/csharp/build/Common.props): false
NOT APPROVED: csharp/src/Apache.Arrow/Apache.Arrow.csproj (apache-arrow/csharp/src/Apache.Arrow/Apache.Arrow.csproj): false
NOT APPROVED: csharp/src/Apache.Arrow/Flatbuf/Block.cs (apache-arrow/csharp/src/Apache.Arrow/Flatbuf/Block.cs): false
NOT APPROVED: csharp/src/Apache.Arrow/Flatbuf/Buffer.cs (apache-arrow/csharp/src/Apache.Arrow/Flatbuf/Buffer.cs): false
NOT APPROVED: csharp/src/Apache.Arrow/Flatbuf/DictionaryBatch.cs (apache-arrow/csharp/src/Apache.Arrow/Flatbuf/DictionaryBatch.cs): false
NOT APPROVED: csharp/src/Apache.Arrow/Flatbuf/DictionaryEncoding.cs (apache-arrow/csharp/src/Apache.Arrow/Flatbuf/DictionaryEncoding.cs): false
NOT APPROVED: csharp/src/Apache.Arrow/Flatbuf/Enums/DateUnit.cs (apache-arrow/csharp/src/Apache.Arrow/Flatbuf/Enums/DateUnit.cs): false
NOT APPROVED: csharp/src/Apache.Arrow/Flatbuf/Enums/Endianness.cs (apache-arrow/csharp/src/Apache.Arrow/Flatbuf/Enums/Endianness.cs): false
NOT APPROVED: csharp/src/Apache.Arrow/Flatbuf/Enums/IntervalUnit.cs (apache-arrow/csharp/src/Apache.Arrow/Flatbuf/Enums/IntervalUnit.cs): false
NOT APPROVED: csharp/src/Apache.Arrow/Flatbuf/Enums/MessageHeader.cs (apache-arrow/csharp/src/Apache.Arrow/Flatbuf/Enums/MessageHeader.cs): false
NOT APPROVED: csharp/src/Apache.Arrow/Flatbuf/Enums/MetadataVersion.cs (apache-arrow/csharp/src/Apache.Arrow/Flatbuf/Enums/MetadataVersion.cs): false
NOT APPROVED: csharp/src/Apache.Arrow/Flatbuf/Enums/Precision.cs (apache-arrow/csharp/src/Apache.Arrow/Flatbuf/Enums/Precision.cs): false
NOT APPROVED: csharp/src/Apache.Arrow/Flatbuf/Enums/TimeUnit.cs (apache-arrow/csharp/src/Apache.Arrow/Flatbuf/Enums/TimeUnit.cs): false
NOT APPROVED: csharp/src/Apache.Arrow/Flatbuf/Enums/Type.cs (apache-arrow/csharp/src/Apache.Arrow/Flatbuf/Enums/Type.cs): false
NOT APPROVED: csharp/src/Apache.Arrow/Flatbuf/Enums/UnionMode.cs (apache-arrow/csharp/src/Apache.Arrow/Flatbuf/Enums/UnionMode.cs): false
NOT APPROVED: csharp/src/Apache.Arrow/Flatbuf/Field.cs (apache-arrow/csharp/src/Apache.Arrow/Flatbuf/Field.cs): false
NOT APPROVED: csharp/src/Apache.Arrow/Flatbuf/FieldNode.cs (apache-arrow/csharp/src/Apache.Arrow/Flatbuf/FieldNode.cs): false
NOT APPROVED: csharp/src/Apache.Arrow/Flatbuf/FixedSizeBinary.cs (apache-arrow/csharp/src/Apache.Arrow/Flatbuf/FixedSizeBinary.cs): false
NOT APPROVED: csharp/src/Apache.Arrow/Flatbuf/FixedSizeList.cs (apache-arrow/csharp/src/Apache.Arrow/Flatbuf/FixedSizeList.cs): false
NOT APPROVED: csharp/src/Apache.Arrow/Flatbuf/Footer.cs (apache-arrow/csharp/src/Apache.Arrow/Flatbuf/Footer.cs): false
NOT APPROVED: csharp/src/Apache.Arrow/Flatbuf/KeyValue.cs (apache-arrow/csharp/src/Apache.Arrow/Flatbuf/KeyValue.cs): false
NOT APPROVED: csharp/src/Apache.Arrow/Flatbuf/Map.cs (apache-arrow/csharp/src/Apache.Arrow/Flatbuf/Map.cs): false
NOT APPROVED: csharp/src/Apache.Arrow/Flatbuf/Message.cs (apache-arrow/csharp/src/Apache.Arrow/Flatbuf/Message.cs): false
NOT APPROVED: csharp/src/Apache.Arrow/Flatbuf/RecordBatch.cs (apache-arrow/csharp/src/Apache.Arrow/Flatbuf/RecordBatch.cs): false
NOT APPROVED: csharp/src/Apache.Arrow/Flatbuf/Schema.cs (apache-arrow/csharp/src/Apache.Arrow/Flatbuf/Schema.cs): false
NOT APPROVED: csharp/src/Apache.Arrow/Flatbuf/Tensor.cs (apache-arrow/csharp/src/Apache.Arrow/Flatbuf/Tensor.cs): false
NOT APPROVED: csharp/src/Apache.Arrow/Flatbuf/TensorDim.cs (apache-arrow/csharp/src/Apache.Arrow/Flatbuf/TensorDim.cs): false
NOT APPROVED: csharp/src/Apache.Arrow/Flatbuf/Types/Binary.cs (apache-arrow/csharp/src/Apache.Arrow/Flatbuf/Types/Binary.cs): false
NOT APPROVED: csharp/src/Apache.Arrow/Flatbuf/Types/Bool.cs (apache-arrow/csharp/src/Apache.Arrow/Flatbuf/Types/Bool.cs): false
NOT APPROVED: csharp/src/Apache.Arrow/Flatbuf/Types/Date.cs (apache-arrow/csharp/src/Apache.Arrow/Flatbuf/Types/Date.cs): false
NOT APPROVED: csharp/src/Apache.Arrow/Flatbuf/Types/Decimal.cs (apache-arrow/csharp/src/Apache.Arrow/Flatbuf/Types/Decimal.cs): false
NOT APPROVED: csharp/src/Apache.Arrow/Flatbuf/Types/FloatingPoint.cs (apache-arrow/csharp/src/Apache.Arrow/Flatbuf/Types/FloatingPoint.cs): false
NOT APPROVED: csharp/src/Apache.Arrow/Flatbuf/Types/Int.cs (apache-arrow/csharp/src/Apache.Arrow/Flatbuf/Types/Int.cs): false
NOT APPROVED: csharp/src/Apache.Arrow/Flatbuf/Types/Interval.cs (apache-arrow/csharp/src/Apache.Arrow/Flatbuf/Types/Interval.cs): false
NOT APPROVED: csharp/src/Apache.Arrow/Flatbuf/Types/List.cs (apache-arrow/csharp/src/Apache.Arrow/Flatbuf/Types/List.cs): false
NOT APPROVED: csharp/src/Apache.Arrow/Flatbuf/Types/Null.cs (apache-arrow/csharp/src/Apache.Arrow/Flatbuf/Types/Null.cs): false
NOT APPROVED: csharp/src/Apache.Arrow/Flatbuf/Types/Struct_.cs (apache-arrow/csharp/src/Apache.Arrow/Flatbuf/Types/Struct_.cs): false
NOT APPROVED: csharp/src/Apache.Arrow/Flatbuf/Types/Time.cs (apache-arrow/csharp/src/Apache.Arrow/Flatbuf/Types/Time.cs): false
NOT APPROVED: csharp/src/Apache.Arrow/Flatbuf/Types/Timestamp.cs (apache-arrow/csharp/src/Apache.Arrow/Flatbuf/Types/Timestamp.cs): false
NOT APPROVED: csharp/src/Apache.Arrow/Flatbuf/Types/Union.cs (apache-arrow/csharp/src/Apache.Arrow/Flatbuf/Types/Union.cs): false
NOT APPROVED: csharp/src/Apache.Arrow/Flatbuf/Types/Utf8.cs (apache-arrow/csharp/src/Apache.Arrow/Flatbuf/Types/Utf8.cs): false
NOT APPROVED: csharp/src/Apache.Arrow/Properties/Resources.Designer.cs (apache-arrow/csharp/src/Apache.Arrow/Properties/Resources.Designer.cs): false
NOT APPROVED: csharp/src/Apache.Arrow/Properties/Resources.resx (apache-arrow/csharp/src/Apache.Arrow/Properties/Resources.resx): false
NOT APPROVED: csharp/test/Apache.Arrow.Tests/Apache.Arrow.Tests.csproj (apache-arrow/csharp/test/Apache.Arrow.Tests/Apache.Arrow.Tests.csproj): false
NOT APPROVED: csharp/test/Apache.Arrow.Tests/app.config (apache-arrow/csharp/test/Apache.Arrow.Tests/app.config): false
47 unapproved licences. Check rat report: rat.txt
```

Some of these files can be added to `dev/release/rat_exclude_files.txt`. Do you definitely want to check in the generated Flatbuffers files? If so, then these should be excluded

**Comment by chutchinson** [comment]
Just a heads up, the MSBuild project files (*.csproj) have some NuGet package information referencing the Apache Foundation (copyright, company name, etc). We can remove or replace that if necessary. Not sure what's going on with Common.props and gitattributes. 

Ideally the Flatbuffer models would be generated on build, but that's not currently part of build pipeline. We can work on getting that done but it's going to take a week or so. Does it make sense to check in the code as-is with the generated flatbuffers, or wait until the pipeline is modified to use the Flatbuffer tooling on build?

If you agree on moving forward I will add all of the files to the exclusion list and resubmit the PR.

**Comment by wesm** [comment]
Sounds good. You can go ahead and push additional commits to this PR branch. No need to open a new PR.

**Comment by wesm** [comment]
I see that this PR is made out of your master branch. In the future you will want to create a feature branch to use for PRs

**Comment by wesm** [comment]
I added the RAT excludes. I'll merge this once we get the green light

**Comment by wesm** [comment]
@chutchinson could you create an account on https://issues.apache.org/jira so I can assign ARROW-2712 to you? Thanks

**Pull request closed without merging**
