### PR TITLE
MINOR: [R] cleanup some notes in our checks

### PR DESCRIPTION
**Pull request by jonkeane**
This cleans up a handful of NOTEs I noticed on as-cran. Though when I run `make check` locally I'm getting the following:

```
NOTE
Found the following hidden files and directories:
  tools/.env
These were most likely included in error. See section ‘Package
structure’ in the ‘Writing R Extensions’ manual.
```

I'm not sure if we need to add that to `.Rbuildignore` or not copy it, or do something else with it so that CRAN doesn't complain about it.

### CODE REVIEW

**Comment by jonkeane** [comment]
@github-actions crossbow submit test-r-linux-as-cran

**Review by nealrichardson — APPROVED** [review]

**Comment by jonkeane** [comment]
@github-actions crossbow submit test-r-linux-as-cran

**Comment by jonkeane** [comment]
@github-actions crossbow submit test-r-linux-as-cran

**Comment by jonkeane** [comment]
@github-actions crossbow submit test-r-linux-as-cran

It looks like the CI is having transient issues installing cmake, I'm trying to install cmake before this runs to avoid this and confirm that everything is ok. I don't intend to keep the cmake installation steps in r_docker_configure.sh, but want to confirm this works.

**Pull request closed without merging**
