### PR TITLE
ARROW-5664: [Crossbow] Execute nightly crossbow tests on CircleCI instead of Travis

### PR DESCRIPTION
**Pull request by kszucs**
The spark integration test has hit the 50mins maximum build time on travis, whereas Circle can run jobs up to 5 hours. Now it's possible to run crossbow tasks on circleci.

### CODE REVIEW

**Comment by kou** [comment]
I want to use GitLab Runner instead of CircleCI.
Because we can add custom GitLab Runners for us. For example, we can add GPU enabled GitLab Runner to test CUDA enabled Apache Arrow build. We can also increase timeout more than 5h for our GitLab Runners.

We can use https://gitlab.com/ to run GitLab Runners: https://about.gitlab.com/solutions/github/
This feature isn't included in the Free tier on GitLab.com (it's available with the Free tier for campaing for now (*1)) but GitLab.com provides Gold tier features to open source projects (*2). So we can use this feature by choosing "CI/CD for external repo" in "New project page" https://gitlab.com/projects/new .

(*1)
> So, for the next year we are making the GitLab CI/CD for GitHub feature a part of our GitLab.com Free tier.

(*2)
> As part of our commitment to open source, we offer all public projects our highest tier features (Gold) for free.

**Comment by kszucs** [comment]
@kou didn't know about that, thanks for sharing it! Crossbow is kinda a meta-ci, so I'd keep circleCI as well, I'm just about to add support for azure pipelines (for conda-forge packages), and gitlab will follow right after that. 
Note we already have cuda enabled tests in ursabot https://github.com/ursa-labs/ursabot/blob/master/ursabot/builders.py#L445 it just requires some configuration on the dgx machines.

**Comment by kszucs** [comment]
Created an issue for it https://issues.apache.org/jira/browse/ARROW-5673

**Review by kszucs — COMMENTED** [review]
+1

**Pull request closed without merging**
