### PR TITLE
GH-34921: [C++][Python][Java] Require CMake 3.16 or later

### LINKED ISSUE #34921: [C++] Require CMake 3.16 or later
### Describe the enhancement requested

We need to support Ubuntu 20.04 (CMake 3.16) or later, CentOS 7 (CMake 3.17) or later, and Debian GNU/Linux buster (CMake 3.13 but backports repository has CMake 3.18) or later.

So we can require CMake 3.16 or later.

### Component(s)

C++

### PR DESCRIPTION
**Pull request by kou**
### Rationale for this change

We need to support Ubuntu 20.04 (CMake 3.16) or later, CentOS 7 (CMake 3.17) or later, and Debian GNU/Linux bullseye (CMake 3.18) or later.

So we can require CMake 3.16 or later.

### What changes are included in this PR?

Require CMake 3.16 or later.

### Are these changes tested?

Yes.

### Are there any user-facing changes?

Yes.
* Closes: #34921

### CODE REVIEW

**Comment by kou** [comment]
I'll rebase on main after #35923 is merged.

**Comment by assignUser** [comment]
:tada: very nice!

**Comment by pitrou** [comment]
The CI failure on Windows looks related:
https://github.com/apache/arrow/actions/runs/5183549768/jobs/9354274524#step:11:1307

It seems that bundled dependencies are built with the wrong flags? (release instead of debug perhaps)
```
orc.lib(TypeImpl.cc.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in unity_26_cxx.cxx.obj
orc.lib(TypeImpl.cc.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MDd_DynamicDebug' in unity_26_cxx.cxx.obj
```

**Comment by kou** [comment]
Thanks.
CMP0091 was related.

**Comment by kou** [comment]
FYI: I noticed that Amazon Linux 2 uses CMake 3.13. Amazon Linux 2's EOL was 2023-06-30 but extended to 2025-06-03:  https://aws.amazon.com/amazon-linux-2/faqs/?nc1=h_ls
If we add support for Amazon Linux 2023 in Apache Arrow 13.0.0, can we drop support for Amazon Linux 2 in Apache Arrow 13.0.0?
Or should we support CMake 3.13 or later for now?

**Comment by kou** [comment]
@github-actions crossbow submit -g linux

**Comment by assignUser** [comment]
@kou I am unable to find 3.13 on ama linux 2 (with epel and extras installed and active)
```
bash-4.2# cmake --version
cmake version 2.8.12.2
```
In any case I think it is fine to only support the 2023 version as that is the version recommended by aws.
Also 3.13 is missing FetchContent_MakeAvailable and other things which would make moving from ep to fc kind of futile.

**Comment by kou** [comment]
You can find CMake 3 by `yum install -y cmake3` and `cmak3 --version`.

**Comment by assignUser** [comment]
Ah I see thanks! Still +1 on supporting 2023 over 2

**Comment by kou** [comment]
@github-actions crossbow submit -g nightly-tests -g nightly-packaging -g nightly-release

**Comment by kou** [comment]
No objection on the mailing thread: https://lists.apache.org/thread/1gfpg0pxhk10n10lo0snx68t3pxfs2sl

I'll merge this once we confirm that this doesn't break our CI.

**Pull request merged**
