### PR TITLE
ARROW-1264: [Python] Raise exception in Python instead of aborting if cannot connect to Plasma store

### PR DESCRIPTION
**Pull request by wesm**
cc @pcmoritz @robertnishihara

### CODE REVIEW

**Comment by wesm** [comment]
Not sure why the manylinux1 build failed, giving it a kick

**Comment by pcmoritz** [comment]
Hm, failed again :(

I'm happy to see if I can figure out what's going on here.

**Comment by wesm** [comment]
Sure, that would be helpful! There's so little changed here (outside code formatting) that I'm not sure what could be wrong

**Comment by wesm** [comment]
I'm taking a look also...

**Comment by pcmoritz** [comment]
https://travis-ci.org/pcmoritz/arrow/jobs/258919543

**Comment by wesm** [comment]
Here's the backtrace:

```
#0  0x00007fffeea5f1d9 in std::uncaught_exception() () from /usr/lib64/libstdc++.so.6
#1  0x00007fffef350fd2 in std::basic_ostream<char, std::char_traits<char> >& std::__ostream_insert<char, std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, char const*, long) ()
   from /venv-test-2.7/lib/python2.7/site-packages/pyarrow/libarrow_python.so.0
#2  0x00007fffeecbe397 in plasma::ConnectIpcSocketRetry(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, long, int*) () from /venv-test-2.7/lib/python2.7/site-packages/pyarrow/libplasma.so.0
#3  0x00007fffeecb798a in plasma::PlasmaClient::Connect(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, int) ()
   from /venv-test-2.7/lib/python2.7/site-packages/pyarrow/libplasma.so.0
#4  0x00007fffe80f136f in __pyx_pw_7pyarrow_6plasma_3connect(_object*, _object*, _object*) ()
   from /venv-test-2.7/lib/python2.7/site-packages/pyarrow/plasma.so
```

digging into this

**Comment by wesm** [comment]
It seems there is some kind of permissions error when libplasma tries to write to stderr inside the Docker container. Trying to figure out how to fix it

**Comment by pcmoritz** [comment]
Could it have anything to do with https://docs.pytest.org/en/latest/capture.html?

**Comment by wesm** [comment]
I don't think so. I'm disabling the Plasma unit tests in the Docker build, we should add a follow up JIRA to investigate

**Comment by pcmoritz** [comment]
SGTM: https://issues.apache.org/jira/browse/ARROW-1295

**Comment by pcmoritz** [comment]
+1 LGTM

**Pull request closed without merging**
