### PR TITLE
ARROW-11209: [Rust] DF - Better error message on unsupported GROUP BY

### PR DESCRIPTION
**Pull request by ovr**
I am getting error without details which type is not supported inside GROUP BY:

External error: Arrow error: External error: Internal error: Unsupported GROUP BY data type.

I added the column's DataType to the error message to make the investigation easier.

### CODE REVIEW

**Comment by andygrove** [comment]
Hi @ovr could you write a more description PR description? The PR description becomes the commit message when the PR is merged so we want it to explain exactly what the change is/was. Thanks!

**Review by andygrove — APPROVED** [review]

**Comment by ovr** [comment]
Thanks, @andygrove, for the notice. I've updated the description, and I will use a more useful description in my PRs.

**Comment by alamb** [comment]
BTW @ovr  I am not sure what type you were grouping on, but I had started working on support for String dictionary support for grouping but have gotten distracted.

**Comment by ovr** [comment]
@alamb I think this problem caused with our fork and Float support, I've prepared a PR with support for Float32/Float64 https://github.com/apache/arrow/pull/9175

But anyway, it's better to get an error message with details which type is not supported, instead of trying to understand it from SQL and DB.

**Pull request closed without merging**
