### PR TITLE
GH-39982: [Java] Add RunEndEncodedVector 

### PR DESCRIPTION
**Pull request by danepitkin**
# WIP 

### Rationale for this change

Add REE vectors to the Java implementation as per the Arrow spec.

### What changes are included in this PR?

WIP

### Are these changes tested?

WIP

### Are there any user-facing changes?

Yes, additional features are added.
* GitHub Issue: #39982

### CODE REVIEW

**Comment by felipecrv** [comment]
@danepitkin  Ping me when you need a review.

**Comment by ViggoC** [comment]
Hi, @danepitkin I am really looking forward to this feature. Is this PR ready to be reviewed?

**Comment by danepitkin** [comment]
Hi @ViggoC , no this has been paused on my end for quite some time. I might be able to work on it for the Arrow v18 release.  Feel free to take it over if needed earlier!

**Comment by ViggoC** [comment]
@danepitkin I can do that, but I have no idea how to add a new vector. Would you point me to some reading material, or just left some TODO comment to show me which part need to be implemented.

**Comment by felipecrv** [comment]
> @danepitkin I can do that, but I have no idea how to add a new vector. Would you point me to some reading material, or just left some TODO comment to show me which part need to be implemented.

Take a look at @vibhatha PRs and find the PRs where he is adding support for `StringView` to the Java implementation.

**Comment by ViggoC** [comment]
@felipecrv thanks for your info.

**Comment by danepitkin** [comment]
Potentially superceded by https://github.com/apache/arrow/pull/43888

**Pull request closed without merging**
