### PR TITLE
ARROW-15200: [C++][Gandiva] Enable RTTI when building LLVM dependency using vcpkg

### PR DESCRIPTION
**Pull request by anthonylouisbsb**
When generating Gandiva's jar file it is possible that an error of UnsatisfiedLinkError may occur based on an LLVM's symbol being used, more specific the llvm::ObjectCache.

To fix that problem, it is necessary to compile the LLVM dependency with RTTI enabled when generating the jars in the nightly build.

### CODE REVIEW

**Comment by anthonylouisbsb** [comment]
@github-actions crossbow submit java-jars

**Comment by anthonylouisbsb** [comment]
@github-actions crossbow submit java-jars

**Comment by anthonylouisbsb** [comment]
The nightly build is being broken when it is executing the set up of the last job, I need to check if it is related to the changes I made.

**Comment by anthonylouisbsb** [comment]
@kou @kszucs the java-jars nightly build is broken when is executing the checkout in the last step I will check and fix it.

**Comment by anthonylouisbsb** [comment]
> @kou @kszucs the java-jars nightly build is broken when is executing the checkout in the last step I will check and fix it.

Apparently the problem is in the checkout actions https://github.com/actions/checkout/issues/672#issuecomment-1010606946

**Comment by anthonylouisbsb** [comment]
@github-actions crossbow submit java-jars

**Review by kou — APPROVED** [review]
+1

**Pull request closed without merging**
