### PR TITLE
ARROW-11163: [C++] Fix reading of compressed IPC/Feather files written with Arrow 0.17

### PR DESCRIPTION
**Pull request by jorisvandenbossche**
(obviously still needs test, but already putting the fix I was testing locally in a draft PR)

### CODE REVIEW

**Comment by pitrou** [comment]
+1. Perhaps the test file should be added to https://github.com/apache/arrow-testing (not sure).

**Comment by jorisvandenbossche** [comment]
If it's a tiny file (can be less than 1 kB), can we then add it to the arrow repo itself? (historically, we have some files included in `pyarrow/tests/data`) Or do we try to avoid that entirely nowadays? 
Can certainly look into adding a file to https://github.com/apache/arrow-testing as well

**Comment by pitrou** [comment]
@wesm  What do you think?

**Comment by nealrichardson** [comment]
Would you mind adding a bullet to https://github.com/apache/arrow/blob/master/r/NEWS.md#bug-fixes since this was also reported in R (ARROW-10850)?

**Comment by nealrichardson** [comment]
IMHO it's simpler to add a tiny file here than always having to worry with a git submodule. You could also defer it: @jonkeane is currently working on some backwards/forwards compat testing for parquet and feather files (#9118), so he could handle it there.

**Comment by jorisvandenbossche** [comment]
Added a tiny test, and added an R news bullet point. This should be ready then.

**Review by pitrou — APPROVED** [review]
+1, thank you @jorisvandenbossche

**Pull request closed without merging**
