### PR TITLE
ARROW-8415: [C++][Packaging] Fix gandiva linux job

### PR DESCRIPTION
**Pull request by pprudhvi**
- use ubuntu xenial instead of trusty
- use crossbow to deploy

### CODE REVIEW

**Comment by pprudhvi** [comment]
@ursabot crossbow submit -g gandiva

**Comment by pprudhvi** [comment]
@ursabot crossbow submit -g gandiva

**Comment by pprudhvi** [comment]
@ursabot crossbow submit -g gandiva

**Comment by pprudhvi** [comment]
@ursabot crossbow submit -g gandiva

**Comment by pprudhvi** [comment]
@ursabot crossbow submit -g gandiva

**Comment by pprudhvi** [comment]
@ursabot crossbow submit -g gandiva

**Comment by pprudhvi** [comment]
@ursabot crossbow submit -g gandiva

**Comment by pprudhvi** [comment]
@ursabot crossbow submit -g gandiva

**Review by kszucs — APPROVED** [review]
Thanks @pprudhvi!

**Pull request closed without merging**
