### PR TITLE
[EXP][C++] Bloom filter / SIMD filter for CSV parser

### PR DESCRIPTION
**Pull request by pitrou**
Not for merging. This is just an experiment I did some time ago to speed up CSV parsing when CSV values are not small (long strings, for example).

### CODE REVIEW

**Comment by pitrou** [comment]
@cyb70289

**Comment by pitrou** [comment]
Benchmark numbers with the 4-byte bloom filter:
```
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Non-regressions: (2)
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
              benchmark        baseline     contender  change %                                                                                                         counters
ParseCSVVehiclesExample 684.761 MiB/sec 1.570 GiB/sec   134.758 {'run_name': 'ParseCSVVehiclesExample', 'repetitions': 0, 'repetition_index': 2, 'threads': 1, 'iterations': 14}
  ParseCSVStocksExample 969.460 MiB/sec 1.365 GiB/sec    44.187  {'run_name': 'ParseCSVStocksExample', 'repetitions': 0, 'repetition_index': 0, 'threads': 1, 'iterations': 108}

---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Regressions: (3)
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
             benchmark        baseline       contender  change %                                                                                                         counters
ParseCSVFlightsExample 647.011 MiB/sec 558.314 MiB/sec   -13.709 {'run_name': 'ParseCSVFlightsExample', 'repetitions': 0, 'repetition_index': 1, 'threads': 1, 'iterations': 157}
  ParseCSVEscapedBlock 804.706 MiB/sec 635.738 MiB/sec   -20.998  {'run_name': 'ParseCSVEscapedBlock', 'repetitions': 0, 'repetition_index': 0, 'threads': 1, 'iterations': 1183}
   ParseCSVQuotedBlock 848.702 MiB/sec 622.788 MiB/sec   -26.619   {'run_name': 'ParseCSVQuotedBlock', 'repetitions': 0, 'repetition_index': 0, 'threads': 1, 'iterations': 1199}
```

**Comment by pitrou** [comment]
Benchmark numbers with the 8-byte SSE 4.2 filter:
```
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Non-regressions: (2)
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
              benchmark        baseline     contender  change %                                                                                                         counters
ParseCSVVehiclesExample 655.957 MiB/sec 2.976 GiB/sec   364.633 {'run_name': 'ParseCSVVehiclesExample', 'repetitions': 0, 'repetition_index': 1, 'threads': 1, 'iterations': 13}
  ParseCSVStocksExample 926.799 MiB/sec 1.687 GiB/sec    86.353  {'run_name': 'ParseCSVStocksExample', 'repetitions': 0, 'repetition_index': 0, 'threads': 1, 'iterations': 104}

---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Regressions: (3)
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
             benchmark        baseline       contender  change %                                                                                                         counters
ParseCSVFlightsExample 629.230 MiB/sec 492.473 MiB/sec   -21.734 {'run_name': 'ParseCSVFlightsExample', 'repetitions': 0, 'repetition_index': 2, 'threads': 1, 'iterations': 151}
   ParseCSVQuotedBlock 810.219 MiB/sec 577.851 MiB/sec   -28.680   {'run_name': 'ParseCSVQuotedBlock', 'repetitions': 0, 'repetition_index': 0, 'threads': 1, 'iterations': 1047}
  ParseCSVEscapedBlock 831.597 MiB/sec 550.618 MiB/sec   -33.788  {'run_name': 'ParseCSVEscapedBlock', 'repetitions': 0, 'repetition_index': 0, 'threads': 1, 'iterations': 1303}
```

**Comment by pitrou** [comment]
Takeaway: both filter types are quite beneficial with long CSV values, but incur a slowdown if all CSV columns have short values. One approach would be to only enable those filters when the _row length / num columns_ ratio is above a given constant, e.g. 10.

**Comment by pitrou** [comment]
@ursabot please benchmark

**Comment by pitrou** [comment]
Updated numbers (locally) with the added heuristic:
* 4-byte bloom filter:
```
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Non-regressions: (2)
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
              benchmark        baseline     contender  change %                                                                                                         counters
ParseCSVVehiclesExample 676.694 MiB/sec 1.463 GiB/sec   121.368 {'run_name': 'ParseCSVVehiclesExample', 'repetitions': 0, 'repetition_index': 0, 'threads': 1, 'iterations': 13}
  ParseCSVStocksExample 949.070 MiB/sec 1.217 GiB/sec    31.354  {'run_name': 'ParseCSVStocksExample', 'repetitions': 0, 'repetition_index': 0, 'threads': 1, 'iterations': 103}

---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Regressions: (3)
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
             benchmark        baseline       contender  change %                                                                                                         counters
   ParseCSVQuotedBlock 787.366 MiB/sec 682.948 MiB/sec   -13.262   {'run_name': 'ParseCSVQuotedBlock', 'repetitions': 0, 'repetition_index': 1, 'threads': 1, 'iterations': 1072}
  ParseCSVEscapedBlock 806.420 MiB/sec 639.499 MiB/sec   -20.699  {'run_name': 'ParseCSVEscapedBlock', 'repetitions': 0, 'repetition_index': 0, 'threads': 1, 'iterations': 1234}
ParseCSVFlightsExample 639.818 MiB/sec 468.004 MiB/sec   -26.854 {'run_name': 'ParseCSVFlightsExample', 'repetitions': 0, 'repetition_index': 2, 'threads': 1, 'iterations': 156}
```
* 8-byte SSE4.2 filter:
```
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Non-regressions: (2)
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
              benchmark        baseline     contender  change %                                                                                                         counters
ParseCSVVehiclesExample 655.679 MiB/sec 2.795 GiB/sec   336.446 {'run_name': 'ParseCSVVehiclesExample', 'repetitions': 0, 'repetition_index': 2, 'threads': 1, 'iterations': 10}
  ParseCSVStocksExample 925.001 MiB/sec 1.627 GiB/sec    80.154  {'run_name': 'ParseCSVStocksExample', 'repetitions': 0, 'repetition_index': 0, 'threads': 1, 'iterations': 103}

---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Regressions: (3)
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
             benchmark        baseline       contender  change %                                                                                                         counters
ParseCSVFlightsExample 625.680 MiB/sec 562.829 MiB/sec   -10.045 {'run_name': 'ParseCSVFlightsExample', 'repetitions': 0, 'repetition_index': 1, 'threads': 1, 'iterations': 150}
   ParseCSVQuotedBlock 824.559 MiB/sec 708.487 MiB/sec   -14.077   {'run_name': 'ParseCSVQuotedBlock', 'repetitions': 0, 'repetition_index': 2, 'threads': 1, 'iterations': 1156}
  ParseCSVEscapedBlock 763.441 MiB/sec 626.461 MiB/sec   -17.942  {'run_name': 'ParseCSVEscapedBlock', 'repetitions': 0, 'repetition_index': 0, 'threads': 1, 'iterations': 1176}
```

**Comment by cyb70289** [comment]
> @cyb70289 Out of curiosity, would you like to benchmark this on ARM?

There's no Neon equivalent of `_mm_cmpistrc` AFAIK.
I tried simulating it with multiple `compare` and `or` operations. IIRC, it's a bit better than bloom filter, but not satisfying (regression for short fields).

**Comment by pitrou** [comment]
What about the bloom filter? Can you post numbers?

**Comment by cyb70289** [comment]
> What about the bloom filter? Can you post numbers?

- Neoverse N1
```
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Non-regressions: (4)
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
              benchmark        baseline       contender  change %                                                                                                              counters
  ParseCSVStocksExample 673.604 MiB/sec 828.022 MiB/sec    22.924       {'run_name': 'ParseCSVStocksExample', 'repetitions': 0, 'repetition_index': 0, 'threads': 1, 'iterations': 225}
ParseCSVVehiclesExample 813.776 MiB/sec 900.741 MiB/sec    10.687      {'run_name': 'ParseCSVVehiclesExample', 'repetitions': 0, 'repetition_index': 0, 'threads': 1, 'iterations': 50}
 ParseCSVFlightsExample 352.727 MiB/sec 358.065 MiB/sec     1.513      {'run_name': 'ParseCSVFlightsExample', 'repetitions': 0, 'repetition_index': 0, 'threads': 1, 'iterations': 254}
    ParseCSVQuotedBlock 499.112 MiB/sec 495.496 MiB/sec    -0.725        {'run_name': 'ParseCSVQuotedBlock', 'repetitions': 0, 'repetition_index': 0, 'threads': 1, 'iterations': 2153}

------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Regressions: (1)
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
           benchmark        baseline       contender  change %                                                                                                        counters
ParseCSVEscapedBlock 487.788 MiB/sec 435.671 MiB/sec   -10.684 {'run_name': 'ParseCSVEscapedBlock', 'repetitions': 0, 'repetition_index': 0, 'threads': 1, 'iterations': 2246}
```

- Apple M1
```
Current
ParseCSVQuotedBlock         348864 ns       348704 ns         2008 bytes_per_second=464.935M/s
ParseCSVEscapedBlock        324485 ns       324302 ns         2158 bytes_per_second=470.512M/s
ParseCSVFlightsExample     2332653 ns      2331827 ns          301 bytes_per_second=416.65M/s
ParseCSVVehiclesExample   28060035 ns     28046800 ns           25 bytes_per_second=408.886M/s
ParseCSVStocksExample      5108847 ns      5106313 ns          134 bytes_per_second=410.962M/s

Bloom filter
ParseCSVQuotedBlock         344054 ns       343942 ns         2016 bytes_per_second=471.371M/s
ParseCSVEscapedBlock        324147 ns       324009 ns         2159 bytes_per_second=470.937M/s
ParseCSVFlightsExample     2328186 ns      2327037 ns          295 bytes_per_second=417.508M/s
ParseCSVVehiclesExample   14166857 ns     14161059 ns           51 bytes_per_second=809.822M/s
ParseCSVStocksExample      2402691 ns      2401820 ns          295 bytes_per_second=873.714M/s
```

**Comment by pitrou** [comment]
Thank you. The numbers on M1 are more impressive than I expected.

> There's no Neon equivalent of _mm_cmpistrc AFAIK.

I see there's a `svmatch` family on SVE, but I suppose SVE is out of scope for now?

**Comment by cyb70289** [comment]
SVE/SVE2 is still out of scope (but I think it's almost there). The only gap is lack of hardware. Few Arm CPU supports SVE nowadays.
Some simd libraries already supports SVE (e.g., google highway). Haven't discussed it with xsimd community.

**Comment by pitrou** [comment]
Closing in favour of #11828

**Pull request closed without merging**
