### PR TITLE
 DO NOT MERGE: Testing the MacOS wheel failures

### PR DESCRIPTION
**Pull request by jorisvandenbossche**
Test for https://github.com/apache/arrow/issues/39562

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
@github-actions crossbow submit *wheel-macos*

**Comment by jorisvandenbossche** [comment]
So it's clearly not related to the logging fs wrapper around the filesystem ..

**Comment by jorisvandenbossche** [comment]
@github-actions crossbow submit *wheel-macos*

**Comment by jorisvandenbossche** [comment]
@github-actions crossbow submit *wheel-macos*

**Comment by jorisvandenbossche** [comment]
@github-actions crossbow submit *wheel-macos*

**Comment by jorisvandenbossche** [comment]
@github-actions crossbow submit *wheel-macos*

**Comment by jorisvandenbossche** [comment]
So I could nail down the failure to the following:

https://github.com/apache/arrow/blob/ac50918a63f13088a5ea9e6c27a9fadbbb19d53f/cpp/src/arrow/dataset/file_parquet.cc#L814-L823

In the above snippet, sometimes `manifest_->descr->num_columns()` returns -1, and so then we do a vector resize with -1 which triggers the `std::length_error` crash. 

But I have no idea why that would sometimes return -1, and only on MacOS when running the test from an installed wheel (not any of the other Mac builds where we build Arrow directly)

**Comment by pitrou** [comment]
Fixed in #39632. We can close now.

**Pull request closed without merging**
