### PR TITLE
ARROW-4122: [C++] Initialize class members based on codebase static analysis

### PR DESCRIPTION
**Pull request by micafan**

### CODE REVIEW

**Comment by wesm** [comment]
Is there a compiler setting to detect these automatically?

**Comment by bkietz** [comment]
Clang doesn't catch it with `-Wall`:

```
struct err {
  err() : i(9) {}
  int i, j;
};

int main() {
  err e;
  return e.j;
}
```

**Comment by wesm** [comment]
> Elsewhere we have default member initializers, is that preferred to specifying them in a constructor?

I think this is ok for POD structs at least

**Comment by bkietz** [comment]
`-Weffc++` doesn't catch the example above either. Clang documentation indicates it's (currently) just an alias for non virtual destructor warning

**Comment by micafan** [comment]
> @micafan can you rebase and run clang-format? Thanks

ok

**Comment by micafan** [comment]
> Is there a compiler setting to detect these automatically?

Yes,

**Comment by micafan** [comment]
> Is there a compiler setting to detect these automatically?
Yes, named coverity. Commercial, need to pay. More details:
https://scan.coverity.com

**Comment by pitrou** [comment]
Those warnings are benign as we initialize the members later one (which is why I chose not to fix them in a previous PR).

**Review by wesm — APPROVED** [review]
+1

**Pull request closed without merging**
