### PR TITLE
MINOR: [C++][Parquet] fix dict_length for ReadDictionary when not having dict

### PR DESCRIPTION
**Pull request by mapleFU**
### Rationale for this change

`dictionary_length = 0` is used when page doesn't have dictionary, however, this should be a nop.

### What changes are included in this PR?

Change `dictionary_length = 0` to `*dictionary_length = 0`.

### Are these changes tested?

No?

### Are there any user-facing changes?

no

### CODE REVIEW

**Comment by mapleFU** [comment]
cc @pitrou @jp0317 @wgtmac

**Review by wgtmac — APPROVED** [review]
Nice catch!

**Comment by pitrou** [comment]
It would have been nice to add a test for this.

**Comment by mapleFU** [comment]
Sigh, seems even the author doesn't reply that, I think that doesn't have user, and maybe before Read, the value would be 0 :-(

**Comment by jp0317** [comment]
sorry for the late reply, thanks for catching this!

**Pull request merged**
