### PR TITLE
ARROW-5372: [GLib] Add support for null/boolean values CSV read option

### PR DESCRIPTION
**Pull request by shiro615**

### CODE REVIEW

**Review by kou — CHANGES_REQUESTED** [review]
Thanks!
Could you use `std::vector` in `arrow::csv::ConverterOptions` like the following:

```diff
diff --git a/c_glib/arrow-glib/reader.cpp b/c_glib/arrow-glib/reader.cpp
index 82d8df93..1f3d7847 100644
--- a/c_glib/arrow-glib/reader.cpp
+++ b/c_glib/arrow-glib/reader.cpp
@@ -904,7 +904,6 @@ typedef struct GArrowCSVReadOptionsPrivate_ {
   arrow::csv::ReadOptions read_options;
   arrow::csv::ParseOptions parse_options;
   arrow::csv::ConvertOptions convert_options;
-  GArray *null_values;
   GArray *true_values;
   GArray *false_values;
 } GArrowCSVReadOptionsPrivate;
@@ -939,10 +938,6 @@ garrow_csv_read_options_finalize(GObject *object)
 {
   auto priv = GARROW_CSV_READ_OPTIONS_GET_PRIVATE(object);
 
-  if (priv->null_values) {
-    g_array_free(priv->null_values, TRUE);
-  }
-
   if (priv->true_values) {
     g_array_free(priv->true_values, TRUE);
   }
@@ -1388,7 +1383,8 @@ garrow_csv_read_options_get_column_types(GArrowCSVReadOptions *options)
 /**
  * garrow_csv_read_options_set_null_values:
  * @options: A #GArrowCSVReadOptions.
- * @null_values: (array length=n_null_values): The null values to be read.
+ * @null_values: (array length=n_null_values):
+ *   The values to be processed as null.
  * @n_null_values: The number of the specified null values.
  *
  * Since: 0.14.0
@@ -1396,50 +1392,41 @@ garrow_csv_read_options_get_column_types(GArrowCSVReadOptions *options)
 void
 garrow_csv_read_options_set_null_values(GArrowCSVReadOptions *options,
                                         const gchar **null_values,
-                                        guint n_null_values)
+                                        gsize n_null_values)
 {
   auto priv = GARROW_CSV_READ_OPTIONS_GET_PRIVATE(options);
-  if (priv->null_values) {
-    g_array_free(priv->null_values, TRUE);
-  }
-  if (n_null_values == 0) {
-    priv->null_values = NULL;
-  } else {
-    priv->null_values = g_array_sized_new(FALSE,
-                                          FALSE,
-                                          sizeof(gchar *),
-                                          n_null_values);
-    g_array_append_vals(priv->null_values, null_values, n_null_values);
-
-    std::vector<std::string> cpp_null_values(n_null_values);
-    for (guint i = 0; i < n_null_values; ++i) {
-      cpp_null_values.push_back(null_values[i]);
-    }
-    priv->convert_options.null_values = cpp_null_values;
+  priv->convert_options.null_values.resize(n_null_values);
+  for (gsize i = 0; i < n_null_values; ++i) {
+    priv->convert_options.null_values[i] = null_values[i];
   }
 }
 
 /**
  * garrow_csv_read_options_get_null_values:
  * @options: A #GArrowCSVReadOptions.
- * @n_null_values: The number of the specified null values.
  *
- * Return: (nullable) (array length=n_null_values):
- *   The null values to be read.
+ * Return: (nullable) (array zero-terminated=1) (element-type utf8) (transfer full):
+ *   The values to be processed as null. It's a %NULL-terminated string array.
+ *   If the number of values is zero, this returns %NULL.
+ *   It must be freed with g_strfreev() when no longer needed.
  *
  * Since: 0.14.0
  */
-const gchar *
-garrow_csv_read_options_get_null_values(GArrowCSVReadOptions *options,
-                                        guint *n_null_values)
+gchar **
+garrow_csv_read_options_get_null_values(GArrowCSVReadOptions *options)
 {
   auto priv = GARROW_CSV_READ_OPTIONS_GET_PRIVATE(options);
-  if (priv->null_values) {
-    *n_null_values = priv->null_values->len;
-    return reinterpret_cast<gchar *>(priv->null_values->data);
-  } else {
-    *n_null_values = 0;
+  const auto &arrow_null_values = priv->convert_options.null_values;
+  if (arrow_null_values.empty()) {
     return NULL;
+  } else {
+    auto n = arrow_null_values.size();
+    gchar **null_values = g_new(gchar *, n + 1);
+    for (size_t i = 0; i < n; ++i) {
+      null_values[i] = g_strdup(arrow_null_values[i].c_str());
+    }
+    null_values[n] = NULL;
+    return null_values;
   }
 }
 
diff --git a/c_glib/arrow-glib/reader.h b/c_glib/arrow-glib/reader.h
index 70840cfa..a80775ac 100644
--- a/c_glib/arrow-glib/reader.h
+++ b/c_glib/arrow-glib/reader.h
@@ -268,11 +268,10 @@ GARROW_AVAILABLE_IN_0_14
 void
 garrow_csv_read_options_set_null_values(GArrowCSVReadOptions *options,
                                         const gchar **null_values,
-                                        guint n_null_values);
+                                        gsize n_null_values);
 GARROW_AVAILABLE_IN_0_14
-const gchar *
-garrow_csv_read_options_get_null_values(GArrowCSVReadOptions *options,
-                                        guint *n_null_values);
+gchar **
+garrow_csv_read_options_get_null_values(GArrowCSVReadOptions *options);
 GARROW_AVAILABLE_IN_0_14
 void
 garrow_csv_read_options_set_true_values(GArrowCSVReadOptions *options,
diff --git a/c_glib/test/test-csv-reader.rb b/c_glib/test/test-csv-reader.rb
index 89216321..4fb768f7 100644
--- a/c_glib/test/test-csv-reader.rb
+++ b/c_glib/test/test-csv-reader.rb
@@ -93,7 +93,10 @@ count,valid
 
       def test_null_values
         options = Arrow::CSVReadOptions.new
-        options.null_values = ["2", "5"]
+        null_values = ["2", "5"]
+        options.null_values = null_values
+        assert_equal(["2", "5"], options.null_values)
+
         table = Arrow::CSVReader.new(open_input(<<-CSV), options)
 message,count
 "Start",2
```

**Comment by kou** [comment]
How about adding a function that adds an element such as `garrow_csv_read_options_add_null_value()`?

**Comment by shiro615** [comment]
Thanks for your comment. I think I've addressed it.

> How about adding a function that adds an element such as garrow_csv_read_options_add_null_value()?

Sounds good. I've added `garrow_csv_read_options_add_{null,true,false}_value`.

**Comment by wesm** [comment]
Related: we should have a discussion about what should be the default null values in case we want to make changes to the current defaults

**Comment by kou** [comment]
@wesm OK. Thanks for the note. We'll do when we need to change the default values.
Arrow GLib uses the same default values as Arrow C++ in this implementation. (It'll not be changed.)

**Review by kou — APPROVED** [review]
+1
I've pushed a commit to clean some tests. We can merge this when CI is green.

**Pull request closed without merging**
