### PR TITLE
WIP: GH-20496: [CI] Migrate Travis jobs to dev/tasks

### LINKED ISSUE #20496: [CI] Migrate jobs on Travis CI to dev/tasks/
https://cwiki.apache.org/confluence/display/INFRA/Travis+Migrations

> On November 2nd, 2020, Travis-CI announced the end of unlimited support for open source projects.
> 
> Infra is therefore moving our CI offerings away from Travis-CI in order to keep our builds pipeline  cost-effective
> 
> Deadline: December 31st 2022
> 
> Infrastructure is moving ASF projects away from using Travis-CI at the end of 2022.

We need to migrate jobs in `.travis.yml` to `dev/tasks/`. `dev/tasks/` are triggered by Crossbow. And Crossbow used in apache/arrow ( https://github.com/ursacomputing/crossbow/ ) can still use Travis CI ( https://app.travis-ci.com/github/ursacomputing/crossbow ) because the Travis CI account is sponsored by Voltron Data not ASF.

**Reporter**: [Kouhei Sutou](https://issues.apache.org/jira/browse/ARROW-18316) / @kou
#### PRs and other links:
- [GitHub Pull Request #14751](https://github.com/apache/arrow/pull/14751)

<sub>**Note**: *This issue was originally created as [ARROW-18316](https://issues.apache.org/jira/browse/ARROW-18316). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

### PR DESCRIPTION
**Pull request by raulcd**
### Rationale for this change

ASF guidelines to move out of Travis.

### What changes are included in this PR?

TBD

### Are these changes tested?

Yes on crossbow

### Are there any user-facing changes?
No
* Closes: #20496

### CODE REVIEW

**Comment by raulcd** [comment]
@github-actions crossbow submit test-ubuntu-20.04-python-s390x

**Comment by raulcd** [comment]
The s390x output seems stuck. I've opened the following issue on travis to see if I can understand what is happening: https://travis-ci.community/t/output-disconnected-on-s390x-getting-no-output-build-failures/13811

**Comment by raulcd** [comment]
@BryanCutler @kiszk do you know if there is something we could do with the IBM s390x?
I am trying the approach of using the ones sponsored by IBM through travis (https://docs.travis-ci.com/user/billing-overview/#partner-queue-solution) but doesn't seem to be working as per above issue.

**Comment by raulcd** [comment]
@github-actions crossbow submit test-ubuntu-20.04-python-s390x

**Comment by kiszk** [comment]
Thank you for pinging me about this topic. I am thinking about going away from Travis for s390x.
If Jenkins at https://ibmz-ci.osuosl.org/ works well, I will try to discuss it.

**Comment by raulcd** [comment]
There was some slight push back on the mailing list for Jenkins, cc @pitrou @kou 
BTW the Apache Arrow travis CI jobs for s390x haven't run for the last three months:
https://app.travis-ci.com/github/apache/arrow/branches

**Comment by pitrou** [comment]
> There was some slight push back on the mailing list for Jenkins, cc @pitrou @kou , See: https://lists.apache.org/thread/bnyfkhz658jpv6xjqdq9jvgjfw16g43l

Yes, it would really be better if all CI relies on either Crossbow tasks or regular PR-based CI builds (using services such as Github Actions, AppVeyor...).

**Comment by kou** [comment]
I agree with pitrou.

If we need to use https://ibmz-ci.osuosl.org/  , we can improve Crossbow to support https://ibmz-ci.osuosl.org/ .

**Comment by raulcd** [comment]
@github-actions crossbow submit test-ubuntu-20.04-python-s390x

**Pull request closed without merging**
