### PR TITLE
ARROW-9781: [C++] Fix valgrind uninitialized value warnings

### PR DESCRIPTION
**Pull request by kszucs**

### CODE REVIEW

**Comment by kszucs** [comment]
@github-actions crossbow submit test-conda-cpp-valgrind

**Comment by kiszk** [comment]
sounds good to me

**Review by kou — COMMENTED** [review]
+1 for changes but core was dumped: https://github.com/ursa-labs/crossbow/runs/997997189?check_suite_focus=true#step:6:3738

Is it unrelated?

**Comment by jianxind** [comment]
The failed compute case is running with SimdLevel::AVX512(4), probably Valgrind doesn't support AVX512?

```
==5971== Your program just tried to execute an instruction that Valgrind
==5971== did not recognise.  There are two possible reasons for this.
==5971== 1. Your program has a bug and erroneously jumped to a non-code
==5971==    location.  If you are running Memcheck and you just saw a
==5971==    warning about a bad jump, it's probably your program's fault.
==5971== 2. The instruction is legitimate but Valgrind doesn't handle it,
==5971==    i.e. it's Valgrind's fault.  If you think this is the case or
==5971==    you are not sure, please let us know and we'll try to fix it.
==5971== Either way, Valgrind will now raise a SIGILL signal which will
==5971== probably kill your program.
```

**Comment by kou** [comment]
Thanks.

We can work on the issue as a separated task. (We will disable the test with valgrind or disable AVX512 for valgrind build.)

I'll merge this.

**Comment by kszucs** [comment]
I've [bumbed](https://github.com/conda-forge/valgrind-feedstock/pull/11) the valgrind version in the conda forge feedstock, perhaps that will help.

**Pull request closed without merging**
