### PR TITLE
ARROW-3985: [C++] Let ccache preserve comments

### PR DESCRIPTION
**Pull request by pitrou**
Some comments may be meaningful to the compiler, such as when a warnings needs to be prevented.

### CODE REVIEW

**Comment by pitrou** [comment]
Note I wasn't able to reproduce the original issue here. @fsaintjacques

**Comment by fsaintjacques** [comment]
gcc-8 with `WARN_LEVEL=EVERYTHING` will produce this.

**Comment by pitrou** [comment]
Can you check the PR fixes it for you?

**Review by fsaintjacques — APPROVED** [review]
It does fix the fall through warning for gcc-8 with and without ccache.

**Comment by kszucs** [comment]
Thanks @pitrou for the PR and @fsaintjacques for the review!

**Pull request closed without merging**
