### PR TITLE
ARROW-8269: [Python] Add pandas mark to test_parquet_row_group_fragments to fix nopandas build

### PR DESCRIPTION
**Pull request by wesm**

### CODE REVIEW

**Comment by wesm** [comment]
@kszucs how do I get the conda-nopandas workflow to run on this PR?

**Comment by kszucs** [comment]
@github-actions crossbow submit test-conda-python-3.6

**Comment by kszucs** [comment]
`conda-python-pandas` is the build with pandas installed and `conda-python` is the nopandas counterpart (parent image).

**Review by kszucs — APPROVED** [review]

**Comment by wesm** [comment]
@kszucs that was counterintuitive to me given the amount of pandas-related functionality and tests in the project. Other people might also be confused / misled. I would be more comfortable with having the "nopandas" tests be a special case and the default Python image to have pandas

**Pull request closed without merging**
