### PR TITLE
ARROW-8979: [C++] Refine bitmap unaligned word access

### PR DESCRIPTION
**Pull request by cyb70289**
This patch adds word based bitmap reader/writer class to hold common
code in unaligned bitmap operations(copy, compare, logical).

It processes in words, then bytes, and finally in bits. Bitmap copying
improves about 5% ~ 10% performance. Slight drop(2% ~ 5%) for bitmap
comparing. No obvious difference for logical operations.

### CODE REVIEW

**Comment by cyb70289** [comment]
@ursabot benchmark --suite-filter=arrow-bit-util-benchmark

**Comment by cyb70289** [comment]
Not sure of "C GLib & Ruby" ci failure, is it related to this patch?
https://github.com/apache/arrow/pull/7340/checks?check_run_id=733807350#step:8:2240

**Comment by cyb70289** [comment]
Benchmark result is better than my machine. Pick some items from above table (one minor glitch of the benchmark output is the items are not sorted by name like local benchmark)
```
  ======================================  ===============  ===============  ========
  benchmark                               baseline         contender        change
  ======================================  ===============  ===============  ========
  CopyBitmapWithOffset/8192               4.177 GiB/sec    5.041 GiB/sec    20.692%
  CopyBitmapWithOffsetBoth/8192           2.309 GiB/sec    2.441 GiB/sec    5.729%
  BitmapEqualsWithOffset/8192             3.521 GiB/sec    3.842 GiB/sec    9.108%
  BenchmarkBitmapAnd/32768/1              3.195 GiB/sec    3.223 GiB/sec    0.879%
  BenchmarkBitmapAnd/131072/1             3.270 GiB/sec    3.285 GiB/sec    0.452%
  BenchmarkBitmapAnd/32768/2              3.196 GiB/sec    3.225 GiB/sec    0.898%
  BenchmarkBitmapAnd/131072/2             3.266 GiB/sec    3.285 GiB/sec    0.573%
  ======================================  ===============  ===============  ========
```

**Comment by kou** [comment]
> Not sure of "C GLib & Ruby" ci failure, is it related to this patch?
> https://github.com/apache/arrow/pull/7340/checks?check_run_id=733807350#step:8:2240

It's not related to this patch. Please ignore it in this pull request.
I'll fix this as a separated pull request.

**Comment by wesm** [comment]
Perhaps https://github.com/apache/arrow/pull/7352 can be merged first and then this patch can be rebased. Sorry about the extra work

**Comment by cyb70289** [comment]
> Perhaps #7352 can be merged first and then this patch can be rebased. Sorry about the extra work. I can help with rebasing also if it helps.

No problem. I will do rebasing when #7352 merged.

**Comment by cyb70289** [comment]
rebased

**Review by wesm — APPROVED** [review]
+1, this definitely makes things cleaner / more readable. Thanks @cyb70289!

**Pull request closed without merging**
