### PR TITLE
ARROW-3676: [Go] implement Decimal128 array

### PR DESCRIPTION
**Pull request by sbinet**

### CODE REVIEW

**Comment by sbinet** [comment]
PTAL @stuartcarnie @alexandreyc

**Comment by sbinet** [comment]
FYI, the `decimal128` package is a very minimal one to be able to hold `128-bits` data.
not much of the logic is implemented.

**Comment by sbinet** [comment]
travis error (linting build) seems unrelated.

**Review by stuartcarnie — APPROVED** [review]
Great addition 👍

**Pull request closed without merging**
