### PR TITLE
ARROW-4881: [C++] remove references to ARROW_BUILD_TOOLCHAIN

### PR DESCRIPTION
**Pull request by bkietz**
`ARROW_BUILD_TOOLCHAIN` has been superceded since the cmake refactor, but a few scripts still set and use it.

### CODE REVIEW

**Comment by bkietz** [comment]
Should [this](https://github.com/apache/arrow/pull/3993/files#diff-51e1e4615087d22b2911b51a248e82a3L49) be `python=%PYTHON%` like [that](https://github.com/apache/arrow/pull/3993/files#diff-51e1e4615087d22b2911b51a248e82a3R44)

**Comment by pitrou** [comment]
> Should this be python=%PYTHON% like that

Since Python is already installed by `conda create`, you can probably delete the `python=3.6` from the `conda install` invocation.

**Comment by bkietz** [comment]
@kszucs Travis failed because brew couldn't find llvm@7 https://travis-ci.org/apache/arrow/jobs/509210161#L4002 could you restart this please

**Comment by kszucs** [comment]
That happened with multiple PRs, brew has even hit github's abuse detection system - I'd fail again.
Probably cause by the recent llvm upgrade https://github.com/Homebrew/homebrew-core/blob/master/Formula/llvm.rb

**Review by kszucs — APPROVED** [review]
LGTM

**Comment by kszucs** [comment]
Created issue for the travis error: https://issues.apache.org/jira/browse/ARROW-4986

**Pull request closed without merging**
