### PR TITLE
GH-38591: [Parquet][C++] Remove redundant open calls in `ParquetFileFormat::GetReaderAsync` 

### LINKED ISSUE #38591: [Parquet][Python] Potential regression in Parquet parallel reading
### Describe the enhancement requested

UPDATE: this is looking more like a bug on closer look. What happens:

When calling `to_table()` on a FileSystemDataset in Python using pyarrow.fs.S3FileSystem,
- Using https://github.com/apache/arrow/commit/02de3c1789460304e958936b78d60f824921c250, one HEAD request and two GET requests are made for each file. Also the requests are made concurrently.
- With current `main`, there are two HEAD requests and three GET requests for each file. Also, the first HEAD request is made from the main thread so the downloads are started sequentially. I would expect to see only one HEAD request, not sure if the three GET are expected due to some change.

Here's an example using https://github.com/apache/arrow/commit/02de3c1789460304e958936b78d60f824921c250, reading a FileSystemDataset using `fragment_readahead = 100` and io concurrency set to 100; Y-axis represents files and X-axis is time in seconds, and each point is the relative start time of a request (HEAD or GET):
Screenshot 2023-11-05 at 18 43 54

With the current `main` https://github.com/apache/arrow/commit/fc8c6b7dc8287c672b62c62f3a2bd724b3835063 it seems that the first request for each file is made from the same thread (blue), and notably there are five requests per each file.

Screenshot 2023-11-05 at 18 43 44

See comment below for reproducible example.

I'm running on Max OS 14.1.

### Component(s)

Parquet

### PR DESCRIPTION
**Pull request by eeroel**
### Rationale for this change
There were duplicate method calls causing extra I/O operations, apparently unintentional from https://github.com/apache/arrow/commit/0793432ad0ef5cb598b7b1e61071cd4991bd1b8b.

### What changes are included in this PR?
Remove the extra method calls.

### Are there any user-facing changes?

* Closes: #38591

### CODE REVIEW

**Review by mapleFU — APPROVED** [review]

**Comment by mapleFU** [comment]
Will merge in one day if don't have any further comments

**Comment by mapleFU** [comment]
Also cc @raulcd would this better in 14.0.1?

**Comment by raulcd** [comment]
> Also cc @raulcd would this better in 14.0.1?

14.0.1 is frozen and ready to be shipped

**Comment by jorisvandenbossche** [comment]
I labeled the issue as backport-candidate, though, in case we do another bug fix release

**Comment by mapleFU** [comment]
@jorisvandenbossche Maybe this should also related to https://github.com/apache/arrow/pull/38466 and https://github.com/apache/arrow/pull/38437 ? I'll drive them to be merged this week

**Pull request merged**
