### PR TITLE
ARROW-12188: [Docs] Switch to pydata-sphinx-theme for the main sphinx docs

### PR DESCRIPTION
**Pull request by jorisvandenbossche**

### CODE REVIEW

**Review by wjones127 — COMMENTED** [review]
I poked around a bit and the new theme works quite well.

I think I prefer how the sidebar in [the option 3 from the JIRA](https://jorisvandenbossche.github.io/arrow-docs-preview/html-option-3-single-sidebar/python/compute.html) worked over what's implemented here in two respects:

 1. It collapsed the nav options by default, making it quick to scan through the top-level sections.
 2. You could expand a section in the navbar without triggering a page navigation.

**Comment by jorisvandenbossche** [comment]
> I think I prefer how the sidebar in the option 3 from the JIRA worked over what's implemented here in two respects:

@wjones127 thanks for testing! 
Maybe one thing I should have noted: this PR requires the master version of the theme, and then the 2 items (the captions + ability to expand sections without triggering a page navigation) should work as they worked in the option 3 preview of JIRA.

**Comment by jorisvandenbossche** [comment]
@github-actions crossbow submit test-ubuntu-18.04-docs

**Comment by jorisvandenbossche** [comment]
@github-actions crossbow submit test-ubuntu-18.04-docs

**Comment by jorisvandenbossche** [comment]
@github-actions crossbow submit test-ubuntu-20.04-docs

**Comment by jorisvandenbossche** [comment]
@github-actions crossbow submit test-ubuntu-20.10-docs

**Comment by jorisvandenbossche** [comment]
As in https://github.com/apache/arrow/pull/9933#issuecomment-819500381, the doc build is failing for Java (even before building the sphinx docs), so is not actually useful to check at the moment.

**Review by lidavidm — APPROVED** [review]

**Pull request closed without merging**
