### PR TITLE
ARROW-18190: [CI][Packaging] Fix macOS mojave wheels test step to actually test wheels

### PR DESCRIPTION
**Pull request by raulcd**

### CODE REVIEW

**Comment by raulcd** [comment]
@github-actions crossbow submit wheel-macos-mojave-*

**Comment by raulcd** [comment]
@github-actions crossbow submit wheel-macos-mojave-*

**Comment by raulcd** [comment]
@pitrou I updated here how we test our macOS mojave wheels to use the same approach as the rest of the wheels. As seen on the crossbow jobs tests are executed now.

**Review by pitrou — APPROVED** [review]
Much better, thanks @raulcd :-)

**Pull request merged**
