### PR TITLE
ARROW-2829: [GLib] Add GArrowORCFileReader

### PR DESCRIPTION
**Pull request by kou**
c_glib/test/fixture/TestOrcFile.test1.orc is copied from
https://github.com/apache/orc/blob/master/examples/TestOrcFile.test1.orc .
Its license is Apache License 2.0.

### CODE REVIEW

**Comment by kou** [comment]
This isn't a required change for 0.10.0. This is a nice-to-have change.

**Review by xhochy — APPROVED** [review]
+1, the copied files is ok as it comes from another Apache project.

@kou can you take care of the failing ruby build?

**Comment by kou** [comment]
Oops. I've fixed the test failure.
And I revised API. I removed field indexes arguments from readers and added accessor for field indexes. We can add API to specify target fields by names like PyArrow did in the future without breaking API.

**Comment by kou** [comment]
@shiro615 Can you review this?

**Comment by shiro615** [comment]
@kou Thanks!
This PR looks good to me.

**Comment by kou** [comment]
@shiro615 Thanks! I've added one more change after your review. Sorry. It renames `read_schema` to `read_type` because other read family, `read_stripes` and `read_stripe`, use ORC term not Arrow term. So `read_schema` should use ORC term.

I'll merge this.

**Pull request closed without merging**
