### PR TITLE
ARROW-13674: [CI] PR checks should check for JIRA components

### PR DESCRIPTION
**Pull request by amol-**

### CODE REVIEW

**Comment by amol-** [comment]
@pitrou I think this does what you were describing in the Jira, what do you think?

**Comment by pitrou** [comment]
@amol- I think it does... but can you try to consolidate the Javascript helpers as suggested in the JIRA description?
(also, add comments/docstrings to those helpers so that they are easier to reuse)

**Comment by amol-** [comment]
> @amol- I think it does... but can you try to consolidate the Javascript helpers as suggested in the JIRA description?
> (also, add comments/docstrings to those helpers so that they are easier to reuse)

Refactored utility functions into their own module and document them 👍

**Comment by pitrou** [comment]
This looks good to me, I hope it will give satisfaction.

**Pull request closed without merging**
