### PR TITLE
WIP: Type checking with mypy

### PR DESCRIPTION
**Pull request by xhochy**
First iteration to have type hints. I have found some problems using them, I'll adress those in separate PRs but I will leave the type hints itself here as an FYI and will rebase continuously until we have dropped Py2 so that we can use inline hints.

To make real use of `mypy`, we would need stubs for the Cython based modules, this depends on someone implementing a `pyi` generator for Cython, see also https://github.com/cython/cython/issues/3150.

### CODE REVIEW

**Comment by wesm** [comment]
Seems like rehabilitating this and adding mypy to our CI would be useful soon

**Comment by xhochy** [comment]
My main issue holding this back is that I remember that we don't wanted to break 2.7 hard in the source code. Adding type hints and check to `pyarrow` would be much simpler when we could use 3.6+ syntax.

I'm still from time to time fixing bits that popped up during this work as separate PRs.

**Comment by nealrichardson** [comment]
We did remove 2.7 support already, so maybe that's not a concern anymore?

**Comment by xhochy** [comment]
Split this up and made a first round in https://github.com/apache/arrow/pull/6676

**Comment by wesm** [comment]
Closing this since the work is being divided into separate PRs

**Pull request closed without merging**
