### PR TITLE
ARROW-7743: [Rust] Support reading timestamp micros

### PR DESCRIPTION
**Pull request by onursatici**
https://issues.apache.org/jira/browse/ARROW-7743

### CODE REVIEW

**Comment by onursatici** [comment]
I have kept the name of the `get_timestamp` method in `RowAccessor` and `ListAccessor` traits, I can change them to `get_timestamp_millis` if thats preferred

**Comment by nevi-me** [comment]
Hi Our, I'll review this during the week.

**Review by sunchao — APPROVED** [review]
Overall LGTM. I'm inclined to have a new `get_timestamp_millis` method and deprecate the old `get_timestamp` one. Let me know how do you think.

**Review by sadikovi — APPROVED** [review]
LGTM. Agree with comments, however, changing `get_timestamp` to `get_timestamp_millis` might break the public API if people use this functionality.

**Review by nevi-me — APPROVED** [review]
LGTM2

> LGTM. Agree with comments, however, changing `get_timestamp` to `get_timestamp_millis` might break the public API if people use this functionality.

The next release is likely `1.0.0`, and while it's to signify stability in the format, we could benefit from making the breaking change as users won't be immediately affected from a semver perspective. What do you think @sadikovi?

**Comment by sadikovi** [comment]
Oh, I didn’t know that, thanks for pointing it out. Yes, let’s change it!

**Comment by onursatici** [comment]
Thanks for the reviews, will rename!

**Comment by sunchao** [comment]
Merged. Thanks @onursatici !

**Pull request closed without merging**
