### PR TITLE
ARROW-7922: [CI][Crossbow] Nightly macOS wheel builds fail (brew bundle edition)

### PR DESCRIPTION
**Pull request by nealrichardson**

### CODE REVIEW

**Comment by nealrichardson** [comment]
@ursabot crossbow submit wheel-osx-cp35m wheel-osx-cp36m wheel-osx-cp37m wheel-osx-cp38

**Comment by nealrichardson** [comment]
@ursabot crossbow submit wheel-osx-cp35m wheel-osx-cp36m wheel-osx-cp37m wheel-osx-cp38

**Comment by nealrichardson** [comment]
@ursabot crossbow submit wheel-osx-cp35m wheel-osx-cp36m wheel-osx-cp37m wheel-osx-cp38

**Review by kszucs — APPROVED** [review]
LGTM, thanks @nealrichardson!

**Pull request closed without merging**
