### PR TITLE
ARROW-8997: [Archery] Improve benchmark comparison formatting

### PR DESCRIPTION
**Pull request by fsaintjacques**
This adds human readable values to the compare values.

### CODE REVIEW

**Comment by fsaintjacques** [comment]
@ursabot benchmark diff --suite-filter=arrow-bit-util-benchmark --benchmark-filter=CopyBitmapWithOffset origin/master

**Comment by fsaintjacques** [comment]
@ursabot benchmark --suite-filter=arrow-bit-util-benchmark --benchmark-filter=CopyBitmapWithOffset origin/master

**Comment by fsaintjacques** [comment]
@ursabot benchmark --suite-filter=arrow-bit-util-benchmark --benchmark-filter=CopyBitmapWithOffset origin/master

**Comment by kszucs** [comment]
@ursabot benchmark --suite-filter=arrow-bit-util-benchmark --benchmark-filter=CopyBitmapWithOffset origin/master

**Comment by kszucs** [comment]
@ursabot build

**Comment by kszucs** [comment]
@ursabot benchmark --suite-filter=arrow-bit-util-benchmark --benchmark-filter=CopyBitmapWithOffset origin/master

**Pull request closed without merging**
