### PR TITLE
GH-40814: [C++] Thirdparty: bump zstd to 1.5.6

### PR DESCRIPTION
**Pull request by mapleFU**
### Rationale for this change

Zstd releases 1.5.6 here: https://github.com/facebook/zstd/releases/tag/v1.5.6

### What changes are included in this PR?

Change default zstd to 1.5.6

### Are these changes tested?

Already has test

### Are there any user-facing changes?

no

* GitHub Issue: #40814

### CODE REVIEW

**Comment by mapleFU** [comment]
Will trigger other tests and benchmarks after ci passed

**Comment by mapleFU** [comment]
@github-actions crossbow submit -g cpp -g wheel

**Comment by mapleFU** [comment]
cc @pitrou @kou

**Comment by felipecrv** [comment]
LGTM. I trust the CI tests to confirm there is no issue.

**Review by kou — APPROVED** [review]
+1

**Pull request merged**
