### PR TITLE
ARROW-8656: [Python] Switch to VS2017 in the windows wheel builds

### PR DESCRIPTION
**Pull request by kszucs**

### CODE REVIEW

**Comment by kszucs** [comment]
@github-actions crossbow submit wheel-win-*

**Comment by kszucs** [comment]
@github-actions crossbow submit wheel-win-cp38

**Comment by kszucs** [comment]
@github-actions crossbow submit wheel-win-cp38

**Comment by kszucs** [comment]
@github-actions crossbow submit wheel-win-cp38

**Comment by kszucs** [comment]
@github-actions crossbow submit wheel-win-cp38

**Comment by kszucs** [comment]
@github-actions crossbow submit wheel-win-cp38

**Comment by kszucs** [comment]
@github-actions crossbow submit wheel-win-*

**Comment by kszucs** [comment]
@github-actions crossbow submit wheel-win-*

**Review by xhochy — APPROVED** [review]
Note that this will also have a user impact that they need the VS2017 runtime locally. We should document that somewhere.

**Comment by fsaintjacques** [comment]
@xhochy to run the wheels, or build them?

**Comment by xhochy** [comment]
> @xhochy to run the wheels, or build them?

To run.

**Comment by wesm** [comment]
Is this change necessary? I understand why we are using VS2017 in the conda package but why in the wheels?

**Comment by xhochy** [comment]
We would need to switch away from using the compiled conda packages as the basis for the wheels. I'm not sure if there is a different source that could provide except Arrow building them on their own.

With my Arrow hat on, this is really annoying as either build times will increase significantly or we would have to use make a pre-filled Windows Docker image that already includes all our static libraries.

With my conda-forge hat on, I would actually love to see this happen as this would mean that we could get rid of the static libraries which we actually don't want to build and distribute. As a package manager who can explicitly deal with native dependencies, dynamic linkage makes the package maintenance a whole lot easier.

**Comment by xhochy** [comment]
Actually, I think the most practical approach would be to use the conda-forge recipes, patch them to use `vs2015` and upload them to a separate channel. This gives us the build machinery to not rebuild them in every CI run and also keeps us from maintaining a complete set of build scripts, we just need to copy them over from time to time.

**Comment by wesm** [comment]
We could also use `BUNDLED` builds for the dependencies of interest (might also be nice to turn on ARROW_MIMALLOC while we are at it). We'd need to turn off Gandiva, though

**Comment by kszucs** [comment]
I'm not sure what's the verdict here, but this issue becomes pressing because of a possible upcoming patch release. 

The python 3.5 script uses bundled dependencies except for boost python and zlib (no gandiva, no flight). I can try to switch back to vs2015 if you would prefer that.

**Comment by wesm** [comment]
Yeah, IMHO let's change to bundled dependencies and stick with VS2015 until we understand the implications of moving to the newer runtime.

**Comment by kszucs** [comment]
Closing in favor of https://github.com/apache/arrow/pull/7129

**Pull request closed without merging**
