### PR TITLE
ARROW-3785: [C++] Enable using double-conversion from $ARROW_BUILD_TOOLCHAIN

### PR DESCRIPTION
**Pull request by wesm**
I couldn't get the INTERFACE library strategy working locally so I extract the relevant properties from the CMake target

### CODE REVIEW

**Comment by xhochy** [comment]
The failure in Travis seems unrelated and the Windows failure is due to the fact that we're probably using the system CMake and not the conda provided one.

**Comment by wesm** [comment]
Looks like I will need to modify CMAKE_PREFIX_PATH on Windows. Will look

**Comment by wesm** [comment]
I don't know why it's not taking the `PATHS` argument to `find_package`. Anyone with ideas?

**Comment by wesm** [comment]
I'm unable to repro on Windows locally, so it may be a CMake version thing. I can try installing the same version of CMake used in Appveyor to see if I can repro. If anyone else can take a look it would be appreciated

**Comment by wesm** [comment]
Oh well this is the problem:

```
PackagesNotFoundError: The following packages are not available from current channels:
  - double-conversion
```

**Comment by wesm** [comment]
@kszucs does "python" need to be in ci/conda_env_cpp.yml? It makes this file harder to use in environments where you may be using/testing multiple versions of Python

**Comment by wesm** [comment]
Extremely strange Windows failure

```
/MANIFESTFILE:src\arrow\CMakeFiles\arrow_shared.dir/intermediate.manifest src\arrow\CMakeFiles\arrow_shared.dir/manifest.res" failed (exit code 1000) with the following output:
  Version 14.00.24241.7
  ExceptionCode            = C0000005
  ExceptionFlags           = 00000000
  ExceptionAddress         = 00007FF7CE2AAE57 (00007FF7CE270000) "C:\PROGRA~2\MI0E91~1.0\VC\bin\amd64\link.exe"
  NumberParameters         = 00000002
  ExceptionInformation[ 0] = 0000000000000000
  ExceptionInformation[ 1] = 00000002004DE640
CONTEXT:
  Rax    = 0000000000000011  R8     = 0000000000000000
  Rbx    = 000000D5E02F0130  R9     = 00007FF7CE36EA30
  Rcx    = 00007FF7CE36EA30  R10    = 0000000000000000
  Rdx    = 0000000000000011  R11    = 000000D5DFB0F3C0
  Rsp    = 000000D5DFB0DF00  R12    = 0000000000000000
  Rbp    = 000000D5DFB0E000  E13    = 0000000000000000
  Rsi    = 0000000000000000  R14    = 0000000000000100
  Rdi    = 00000002004DE640  R15    = 0000000000000001
  Rip    = 00007FF7CE2AAE57  EFlags = 0000000000010202
  SegCs  = 0000000000000033  SegDs  = 000000000000002B
  SegSs  = 000000000000002B  SegEs  = 000000000000002B
  SegFs  = 0000000000000053  SegGs  = 000000000000002B
  Dr0    = 0000000000000000  Dr3    = 0000000000000000
  Dr1    = 0000000000000000  Dr6    = 0000000000000000
  Dr2    = 0000000000000000  Dr7    = 0000000000000000
LINK : fatal error LNK1000: unknown error at 000000D5EB5AB4E0; consult documentation for technical support options
[143/223] Building CXX object src\arrow\ipc\CMakeFiles\file-to-stream.dir\file-to-stream.cc.obj
```

https://ci.appveyor.com/project/wesm/arrow/builds/20467505/job/rttalt9gmy7tl6eu

Seems like it must be transient. I'll wait for the build under ApacheSoftwareFoundation to run to see

**Comment by wesm** [comment]
Trying conda-forge again on Windows. defaults does not have all the packages we need, and trying to mix them is a recipe for pain

**Comment by wesm** [comment]
+1. Build failure (Plasma JNI looks unrelated)

**Pull request closed without merging**
