### PR TITLE
ARROW-15388: [C++] Avoid including absl from flatbuffers

### PR DESCRIPTION
**Pull request by pitrou**
There may be an incomplete/broken copy of the Abseil library lying around
(for example because of a race condition while installing it as a bundled library).

Since absl is only used by Flatbuffers to provide a string_view facility,
use our own vendored string_view instead.

### CODE REVIEW

**Comment by pitrou** [comment]
@coryan Not sure whether you have an opinion on this?

**Comment by coryan** [comment]
> It's a bit convoluted and awkward, as Abseil is only an optional indirect dependency of the GCSFS implementation. Furthermore, since Flatbuffers is vendored, I don't think it has an existence in the dependency graph at all currently (it's basically always there).

I see.

Consider that (by default) `absl::string_view` is just an alias for `std::string_view` when compiling with C++ >= 17, and it is a template class when compiling with C++ <= 14 (something I do not happen to like but it is a thing: abseil/abseil-cpp#696).  I am not sure if Flatbuffers depends on that (my guess would be no), hopefully not.  If it did, you may run intro trouble as it tries to use `std::string_view` in C++17 but the Arrow version of `string_view` does not magically convert to `std::string_view`.

You may want to just disable the automatic detection of Abseil's string view.  Just my $0.02, I think your change should work as-is too.

**Comment by pitrou** [comment]
Flatbuffers' use of string_view is merely to enable two APIs (that we don't currently use AFAICT, so we may indeed as well disable it). It doesn't store any `std::string_view` under the hood, so that should be fine.

**Comment by lidavidm** [comment]
If it just enables APIs we don't use, I would lean towards avoiding the mess in the first place and just removing the detection as well. But as-is things are OK here too.

**Review by lidavidm — APPROVED** [review]

**Comment by kszucs** [comment]
@pitrou shall we include this in 7.0 (in the case I need to cut another RC)?

**Review by bkietz — APPROVED** [review]

**Comment by pitrou** [comment]
@kszucs There's no real need to.

**Comment by pitrou** [comment]
Crossbow C++ builds: https://github.com/ursacomputing/crossbow/branches/all?page=1&query=build-592

**Pull request closed without merging**
