### PR TITLE
ARROW-15495: [C++][FlightRPC] Require Protobuf/gRPC SOURCEs to match

### PR DESCRIPTION
**Pull request by lidavidm**
Prevent us from mixing system/bundled gRPC and Protobuf, since gRPC itself links to Protobuf and having two copies of Protobuf linked will lead to runtime errors or crashes.

### CODE REVIEW

**Comment by lidavidm** [comment]
For many of the Crossbow builds, this should have the effect of bundling both Protobuf and gRPC, since the system Protobuf is too old to support Flight/Flight SQL.

**Comment by lidavidm** [comment]
CC @kszucs @kou, I originally had it raise an error, but this is less disruptive. I checked that the tests indeed fail on Ubuntu 21.04 when you mix the two.

**Comment by kszucs** [comment]
> I originally had it raise an error, but this is less disruptive. 
My first thought was to raise too, but this looks like a better way to handle it. 

> I checked that the tests indeed fail on Ubuntu 21.04 when you mix the two, and that they pass when both are bundled. I couldn't test when both dependencies came from the system, since Protobuf is too old. 
Did you manage to reproduce it with `UBUNTU=21.04 archery docker run ubuntu-cpp`?

**Comment by lidavidm** [comment]
> Did you manage to reproduce it with `UBUNTU=21.04 archery docker run ubuntu-cpp`?

I will give that a try

**Comment by lidavidm** [comment]
Sorry for the delay. It indeed fails with 

> env UBUNTU=21.04 PYTHONPATH=./dev/archery:(pwd) python -m archery.cli docker run -e "ARROW_FLIGHT=ON" -e "ARROW_FLIGHT_SQL=ON" -e "Protobuf_SOURCE=BUNDLED" ubuntu-cpp

I had to update a dockerfile:

```
diff --git a/ci/docker/ubuntu-21.04-cpp.dockerfile b/ci/docker/ubuntu-21.04-cpp.dockerfile
index 58639cb1c..595776a8a 100644
--- a/ci/docker/ubuntu-21.04-cpp.dockerfile
+++ b/ci/docker/ubuntu-21.04-cpp.dockerfile
@@ -85,6 +85,7 @@ RUN apt-get update -y -q && \
         libprotoc-dev \
         libre2-dev \
         libsnappy-dev \
+       libsqlite3-dev \
         libssl-dev \
         libthrift-dev \
         libutf8proc-dev \
```

**Comment by kszucs** [comment]
Thanks David! I'm going to add that and also register it as a nightly job.

**Comment by kszucs** [comment]
@github-actions crossbow submit test-ubuntu-21.04-cpp

**Comment by kszucs** [comment]
@github-actions crossbow submit test-ubuntu-21.04-cpp

**Comment by kszucs** [comment]
@github-actions crossbow submit *21.04*

**Review by kou — APPROVED** [review]
+1

Ubuntu 21.04 reaches EOL in this month. We should switch this to Ubuntu 21.10 soon.

**Pull request closed without merging**
