### PR TITLE
ARROW-12121: [Rust] [Parquet] Arrow writer benchmarks

### PR DESCRIPTION
**Pull request by nevi-me**
Adds benchmarks for writing Arrow data to an in-memory Parquet sink. Leverages ARROW-12120 to create random data. Please see the JIRA for more details.

The nested benchmark is not enabled as I've triggered an edge-case in the nested writer, so I'll investigate that separately.

### CODE REVIEW

**Comment by nevi-me** [comment]
I also need the benchmarks so I can use them as guidance when clearing the TODOs that are still in the writer code.

I'm getting the below, feels very slow to me, but I don't yet know how fast the C++ writer is (@emkornfield do you have an idea?):

```
write_batch primitive/1024 values                                                                             
                        time:   [1.0473 ms 1.0505 ms 1.0539 ms]
                        thrpt:  [95.109 MiB/s 95.415 MiB/s 95.708 MiB/s]

write_batch primitive/4096 values                                                                             
                        time:   [4.3952 ms 4.4335 ms 4.4851 ms]
                        thrpt:  [87.996 MiB/s 89.020 MiB/s 89.795 MiB/s]
```

I might not be calculating the throughput values correctly, but I'll check that separately (it'd be useful to know the size of a recordbatch).

CC @houqp

**Review by jorgecarleitao — APPROVED** [review]
LGTM!

**Review by sunchao — APPROVED** [review]
LGTM

**Review by alamb — APPROVED** [review]
I tested this out locally and worked for me 👍 

```
(arrow_dev) alamb@ip-10-0-0-124:~/Software/arrow2/rust/parquet$ cargo bench --bench arrow_writer
```

I got even worse numbers than @nevi-me  (on a macbook pro):

```
Warning: Unable to complete 100 samples in 5.0s. You may wish to increase target time to 9.6s, enable flat sampling, or reduce sample count to 50.
write_batch primitive/1024 values                                                                             
                        time:   [1.9491 ms 1.9828 ms 2.0198 ms]
                        thrpt:  [49.626 MiB/s 50.552 MiB/s 51.426 MiB/s]
write_batch primitive/4096 values                                                                            
                        time:   [6.5758 ms 6.6413 ms 6.7119 ms]
                        thrpt:  [58.802 MiB/s 59.426 MiB/s 60.018 MiB/s]
Found 3 outliers among 100 measurements (3.00%)
  1 (1.00%) high mild
  2 (2.00%) high severe
```

**Pull request closed without merging**
