### PR TITLE
GH-41314: [CI][Python] Add a job on ARM64 macOS

### PR DESCRIPTION
**Pull request by llama90**
### Rationale for this change

We need the GitHub-hosted ARM64 macOS to do more specific testing for the Python test.

### What changes are included in this PR?

Add a job on ARM64 macOS (version: 14) for python

### Are these changes tested?

Yes.

### Are there any user-facing changes?

No.

* GitHub Issue: #41314

### CODE REVIEW

**Comment by llama90** [comment]
The PR is WIP. The WIP is removed because the workflow was not working due to `if: ${{ !contains(github.event.pull_request.title, 'WIP') }}` condition in the workflow.

**Comment by kou** [comment]
https://github.com/apache/arrow/actions/runs/8766189015/job/24058044138?pr=41313#step:5:2198

```text
[567/568] Install the project...
-- Install configuration: "DEBUG"
CMake Error at cmake_install.cmake:41 (file):
  file cannot create directory: /usr/local/lib/cmake/Arrow.  Maybe need
  administrative privileges.
```

How about using other directory for `ARROW_HOME`? Something like:

```diff
diff --git a/.github/workflows/python.yml b/.github/workflows/python.yml
index 2db9b17e89..f06d7d2a65 100644
--- a/.github/workflows/python.yml
+++ b/.github/workflows/python.yml
@@ -133,7 +133,7 @@ jobs:
     if: ${{ !contains(github.event.pull_request.title, 'WIP') }}
     timeout-minutes: 60
     env:
-      ARROW_HOME: /usr/local
+      ARROW_HOME: "${GITHUB_WORKSPACE}/local"
       ARROW_AZURE: ON
       ARROW_DATASET: ON
       ARROW_FLIGHT: ON
```

```diff
diff --git a/.github/workflows/python.yml b/.github/workflows/python.yml
index 2db9b17e89..c441ace812 100644
--- a/.github/workflows/python.yml
+++ b/.github/workflows/python.yml
@@ -133,7 +133,7 @@ jobs:
     if: ${{ !contains(github.event.pull_request.title, 'WIP') }}
     timeout-minutes: 60
     env:
-      ARROW_HOME: /usr/local
+      ARROW_HOME: /tmp/local
       ARROW_AZURE: ON
       ARROW_DATASET: ON
       ARROW_FLIGHT: ON
```

Could you open a new issue for this? GH-41312 should be used for a PR that fixes the crash.

**Comment by llama90** [comment]
@kou You're right about making a new issue for the new workflow. But I'm worried that until we fix this issue, any PR that tries to add new workflow code might run into problems.

Another option is to skip this test in the new workflow PR and fix the problem in the code first. After fixing it, we can add the test back in.

Anyway, I will upload a new issue and PR for the workflow in that environment.

**Comment by llama90** [comment]
Hello, @kou 

As you suggested:

- I've created an issue for the workflow.
- I've changed the title of this PR to match the issue.
- For the failing workflow, I've changed the path to `tmp`.

However, another error has occurred. I have another commitment, but I will look into it as soon as possible.

Thank you.

**Comment by kou** [comment]
https://github.com/apache/arrow/actions/runs/8768627040/job/24063174654?pr=41313#step:5:2754

```text
  CMake Error at CMakeLists.txt:271 (find_package):
    By not providing "FindArrow.cmake" in CMAKE_MODULE_PATH this project has
    asked CMake to find a package configuration file provided by "Arrow", but
    CMake did not find one.

    Could not find a package configuration file provided by "Arrow" with any of
    the following names:

      ArrowConfig.cmake
      arrow-config.cmake

    Add the installation prefix of "Arrow" to CMAKE_PREFIX_PATH or set
    "Arrow_DIR" to a directory containing one of the above files.  If "Arrow"
    provides a separate development package or SDK, be sure it has been
    installed.
```

It seems that Apache Arrow C++'s CMake package can't be found from PyArrow.

How about this?

```diff
diff --git a/ci/scripts/python_build.sh b/ci/scripts/python_build.sh
index 7a24c1172f..99153cdf75 100755
--- a/ci/scripts/python_build.sh
+++ b/ci/scripts/python_build.sh
@@ -74,6 +74,8 @@ export PYARROW_WITH_SUBSTRAIT=${ARROW_SUBSTRAIT:-OFF}
 
 export PYARROW_PARALLEL=${n_jobs}
 
+: ${CMAKE_PREFIX_PATH:=${ARROW_HOME}}
+export CMAKE_PREFIX_PATH
 export LD_LIBRARY_PATH=${ARROW_HOME}/lib:${LD_LIBRARY_PATH}
 
 pushd ${source_dir}
```

BTW, it seems that ccache isn't used for PyArrow jobs on macOS. Could you open a new issue to use ccache for them?

**Comment by llama90** [comment]
Hello, @kou 

As you mentioned, I have created an issue for enabling ccache. Does this align with what you mentioned? Thank you. 

- https://github.com/apache/arrow/issues/41316

**Comment by llama90** [comment]
hello @kou.

Separately from the issue([41312](https://github.com/apache/arrow/issues/41312)), I cleaned this PR.

The issue seems to be that in CI, tests that fail during local builds are treated as PASSED. Regardless of resolving the issue, it seems right that this workflow (ARM64, macOS) should be added.

When you have time, please review!

Thank you always.

**Comment by kou** [comment]
Yes. Thanks.

**Comment by kou** [comment]
@github-actions crossbow submit -g python

**Review by kou — APPROVED** [review]
+1

**Pull request merged**
