### PR TITLE
[WIP][Release] Verify 1.0.0 release candidate RC0

### PR DESCRIPTION
**Pull request by kszucs**

### CODE REVIEW

**Comment by kszucs** [comment]
@github-actions crossbow submit verify-rc-source-*

**Comment by wesm** [comment]
I'm able to reproduce the failure locally, trying to get into it with gdb to see what's going on

**Comment by kszucs** [comment]
Closing in favor of #7787

**Comment by nealrichardson** [comment]
FWIW you don't need a new PR, you can just edit the scripts again on the same branch to say rc1 instead of rc0.

**Pull request closed without merging**
