### PR TITLE
ARROW-16474: [C++][Packaging] Require Python 3.7 or later

### PR DESCRIPTION
**Pull request by kou**

### CODE REVIEW

**Comment by kou** [comment]
@github-actions crossbow submit -g linux

**Comment by kou** [comment]
@github-actions crossbow submit debian-* ubuntu-*

**Comment by kou** [comment]
@github-actions crossbow submit -g linux

**Comment by kou** [comment]
+1

**Comment by vibhatha** [comment]
@kou Thanks a lot for working on this.

**Pull request closed without merging**
