### PR TITLE
ARROW-5722: [Rust] Implement Debug for List/Struct/BinaryArray

### PR DESCRIPTION
**Pull request by ghost**
- Add a helper to elide the middle of long arrays (same behavior as Python)
- Adds `Debug` trait bound on `Array`

If we don't want those changes, we can simply take only the first commit here, which adds basic `Debug` implementations for the three mentioned array types. 

Travis build: https://travis-ci.com/lihalite/arrow/builds/126247128

Example output:
```
$ cargo run --example builders
    Finished dev [unoptimized + debuginfo] target(s) in 0.07s
     Running `target/debug/examples/builders`
PrimitiveArray<Int32>
[
  55,
  null,
  39,
  89,
  12,
  null,
  25,
  26,
  27,
  28,
  ...11 elements...,
  40,
  41,
  42,
  43,
  44,
  45,
  46,
  47,
  48,
  49,
]
PrimitiveArray<Date64(Millisecond)>
[
  2019-02-23,
  null,
  2019-02-23,
]
PrimitiveArray<Time64(Nanosecond)>
[
  00:00:00,
  00:00:00.000000001,
  00:00:00.000000002,
  00:00:00.000000003,
  00:00:00.000000004,
  00:00:00.000000005,
  00:00:00.000000006,
  00:00:00.000000007,
  00:00:00.000000008,
  00:00:00.000000009,
  ...80 elements...,
  00:00:00.000000090,
  00:00:00.000000091,
  00:00:00.000000092,
  00:00:00.000000093,
  00:00:00.000000094,
  00:00:00.000000095,
  00:00:00.000000096,
  00:00:00.000000097,
  00:00:00.000000098,
  00:00:00.000000099,
]
$ cargo run --example list_array
    Finished dev [unoptimized + debuginfo] target(s) in 0.06s
     Running `target/debug/examples/list_array`
ListArray
[
  PrimitiveArray<Int32>
[
  0,
  1,
  2,
],
  PrimitiveArray<Int32>
[
  3,
  4,
  5,
],
  PrimitiveArray<Int32>
[
  6,
  7,
],
]
StructArray
[
-- child 0: "b" (Boolean)
PrimitiveArray<Boolean>
[
  false,
  false,
  true,
  true,
]
-- child 1: "c" (Int32)
PrimitiveArray<Int32>
[
  42,
  28,
  19,
  31,
]
]
```

### CODE REVIEW

**Review by nevi-me — APPROVED** [review]
Thanks @lihalite. I'd favour collapsing all 4 examples into 1 function/main.

I'm also happy with `Debug` trait on Array

**Comment by nevi-me** [comment]
@lihalite  may you please rebase recent changes on master so the CI can build again. We've pinned to a specific nightly to reduce built-time issues on recent nightlies.

**Comment by lihalite** [comment]
I've rebased, but let me collapse the examples as well.

**Review by paddyhoran — APPROVED** [review]
LGTM, thanks @lihalite

**Pull request closed without merging**
