### PR TITLE
ARROW-79: [Python] Add benchmarks

### PR DESCRIPTION
**Pull request by xhochy**
Run them using `asv run --python=same` or `asv dev`.

### CODE REVIEW

**Comment by wesm** [comment]
What is your opinion on putting the benchmarks in `pyarrow/benchmarks` versus at the top level `$ROOT/python/benchmarks`. This is what we do with pandas, but I don't have a strong opinion: https://github.com/pydata/pandas/tree/master/asv_bench

**Comment by xhochy** [comment]
Actually I'm used to have benchmarks and unit tests at the top level. I only put them into `pyarrow/benchmark` as the unit tests where also located there. Should I move them?

**Comment by wesm** [comment]
Sure, that would be great. The main reason I've embedded the test suite in packages is to be able to have a `PACKAGE.test()` for users to verify their installation (for example `numpy.test` or `pandas.test`), but it's not a hard and fast rule. For benchmarks this is less important

**Comment by wesm** [comment]
+1, thank you

**Pull request closed without merging**
