### PR TITLE
ARROW-9449: [R] Strip arrow.so

### PR DESCRIPTION
**Pull request by nealrichardson**
cf. http://dirk.eddelbuettel.com/blog/2017/08/14/#009_compact_shared_libraries

cc @romainfrancois

### CODE REVIEW

**Comment by nealrichardson** [comment]
@github-actions crossbow submit *autobrew*

**Comment by nealrichardson** [comment]
This is an order of magnitude improvement. On the AMD64 Ubuntu 18.04 R 4.0 builds, which use an Arrow C++ shared library, arrow.so (so just the R bindings) is down from 24.3mb to 3.3mb. On the 4.0 centos7 build, which bundles static libs, it's down from 144.5mb (about 3x larger in the last couple of days) to 17.4mb.

**Comment by nealrichardson** [comment]
Apparently the macOS version of `strip` takes different args: https://travis-ci.org/github/ursa-labs/crossbow/builds/707793921#L1112

So we'll have to switch based on uname and/or make sure that this doesn't fail the build. Will pick up on this tomorrow.

**Comment by wesm** [comment]
> On the 4.0 centos7 build, which bundles static libs, it's down from 144.5mb (about 3x larger in the last couple of days) to 17.4mb.

Whoa, that's kind of crazy. Which static libraries have debug symbols in them? I'm concerned that perhaps we might have a BUNDLED build that is being built in DEBUG mode instead of RELEASE which would also have negative performance implications

**Comment by nealrichardson** [comment]
Cmake reports that it is a release build. You can see that in the logs. Maybe the change to the new bundled dependency library is no longer passing that to the external projects? 

Either way, there's value in stripping even just the R bindings themselves.

**Comment by wesm** [comment]
I only meant the thirdparty dependencies -- some projects have debug symbols by default even in release builds so it could just be that. At some point it might be worth going through and seeing which are the largest thirdparty static libraries

**Comment by nealrichardson** [comment]
Something caused a major (3x) increase in the size of the libs from one day to the next. Could have been the bundled dependency patch or could have been one of several others, it was a busy day. I could bisect if we care to find out, but for the moment this seemed to be a good enough fix.

**Comment by wesm** [comment]
As near as I can tell this is the patch that caused the size increase

https://github.com/apache/arrow/commit/ba1f6315aa4b4a85435e890bed948b537708d858

So I guess it's related to the CXX toolchain?

That's 2 commits after the dependency bundle match, which has 42MB of libs https://github.com/apache/arrow/runs/859650227

**Comment by xhochy** [comment]
Can you try passing `-g0` in `C(XX)FLAGS` instead / in addition of stripping? That's what we do in the Python wheels (through `multibuild`) so that the debug symbols themselves not even get build at all.

**Comment by pitrou** [comment]
On macOS it seems you may want `strip -Sx`, according to the [man page](https://www.unix.com/man-page/osx/1/strip/).

**Comment by nealrichardson** [comment]
On one of the linux images I've been testing locally, as well as on my mac, the R makevars added in that commit are setting `CXXFLAGS="-g -O2"`. Given that, it probably makes sense not to pass those flags to the libarrow build. But I still think we should strip because I can't control the fact that R is including that when it compiles the R bindings--that is, I could edit the makevars on my own system, but the package installation can't override whatever makevars R has on other people's systems.

**Comment by nealrichardson** [comment]
@github-actions crossbow submit -g r

**Comment by nealrichardson** [comment]
The two crossbow failures (other than conda-r, which we're ignoring) appear to be flakes, but I'll re-run them to be extra sure. 

Re-review appreciated on the latest change.

**Comment by nealrichardson** [comment]
@github-actions crossbow submit test-r-rstudio-r-base-3.6-opensuse42 test-r-rocker-r-base-latest

**Review by wesm — APPROVED** [review]
+1, looks OK here

**Pull request closed without merging**
