### PR TITLE
ARROW-2799: [Python] Add safe option to Table.from_pandas to avoid unsafe casts

### PR DESCRIPTION
**Pull request by kszucs**
Depends on both #2497 and #2503

### CODE REVIEW

**Comment by kszucs** [comment]
There is a spurious but pertinacious conda error:

```
CondaHTTPError: HTTP 500 INTERNAL SERVER ERROR for url <https://conda.anaconda.org/conda-forge/linux-64/repodata.json>
Elapsed: 00:00.413982
CF-RAY: 4541d1fc0b3e54f8-ORD
A remote server error occurred when trying to retrieve this URL.
A 500-type error (e.g. 500, 501, 502, 503, etc.) indicates the server failed to
fulfill a valid request.  The problem may be spurious, and will resolve itself if you
try your request again.  If the problem persists, consider notifying the maintainer
of the remote server.
```

**Comment by wesm** [comment]
This happens quite often. Is there a way to configure conda to retry some number of times, or wait and retry?

**Comment by xhochy** [comment]
The 500 errors were a general outage of conda which was resolved. `conda` in the newest version should do some retries.

**Comment by xhochy** [comment]
@kszucs The dependencies were merged. Can you rebase?

**Review by xhochy — APPROVED** [review]
+1, LGTM

**Comment by wesm** [comment]
The parquet-cpp merge has caused our merge script to do something pretty wacky. I'm going to try to figure it out

**Comment by wesm** [comment]
Rebased

**Pull request closed without merging**
