### PR TITLE
optimization debian package manager tweaks

### PR DESCRIPTION
**Pull request by rajpratik71**
By default, Ubuntu or Debian based "apt" or "apt-get" system installs recommended but not suggested packages .

By passing "--no-install-recommends" option, the user lets apt-get know not to consider recommended packages as a dependency to install.

This results in smaller downloads and installation of packages .

Refer to blog at [Ubuntu Blog](https://ubuntu.com/blog/we-reduced-our-docker-images-by-60-with-no-install-recommends) .

Signed-off-by: Pratik Raj <rajpratik71@gmail.com>

### CODE REVIEW

**Comment by wesm** [comment]
Do you want to rebase and open a JIRA issue?

**Comment by pitrou** [comment]
Also cc @kou and @kszucs

**Comment by kou** [comment]
I tried this in #6620 and found that we need to install some extra packages explicitly.
So we can't complete this task by just adding `--no-install-recommends` like this pull request.
We need to work carefully for this task.

If we want to complete this task, I recommend that we close this pull request and split this task to small sub tasks.

**Comment by wesm** [comment]
This has grown stale. Per @kou's comment this should be split into smaller tasks and submitted as other PRs

**Pull request closed without merging**
