### PR TITLE
GH-38528: [Python][Compute] Describe strptime format semantics

### LINKED ISSUE #38528: [Python][Compute] Make pyarrow.compute.strptime %Y handling consistent with time.strptime
### Describe the enhancement requested

The `pyarrow.compute.strptime` handles the `%Y` format part (i.e. 4-digit year) differently from the built-in `time.strptime`:
When the year part of the input has only two digits, `time.strptime` fails to parse it, while `pyarrow.compute.strptime` parses it with no error yielding a result with a year in the 1st century.

For example

```python
>>> import pyarrow as pa
>>> import pyarrow.compute as pc
>>> import time
>>> input = "01-01-23"
>>> format = "%m-%d-%Y"
>>> time.strptime(input, format)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/no23reason/.pyenv/versions/3.11.4/lib/python3.11/_strptime.py", line 562, in _strptime_time
    tt = _strptime(data_string, format)[0]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/no23reason/.pyenv/versions/3.11.4/lib/python3.11/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '01-01-23' does not match format '%m-%d-%Y'
>>> pc.strptime(pa.array([input]), format=format, unit="s")
<pyarrow.lib.TimestampArray object at 0x152e40c40>
[
  0023-01-01 00:00:00
]
```
I believe the `pyarrow.compute.strptime` should also fail in this case as it most likely means that the format is wrong.

### Component(s)

Python

### PR DESCRIPTION
**Pull request by no23reason**
### Rationale for this change

To prevent possible confusion with the compute strptime function, we now explicitly mention that the C/C++ semantics are followed.

### What changes are included in this PR?

The documentation of the `format` parameter of the `strptime` function is expanded.

### Are these changes tested?

N/A documentation change only.

### Are there any user-facing changes?

Just the documentation.
* Closes: #38528

### CODE REVIEW

**Comment by no23reason** [comment]
@github-actions crossbow submit preview-docs

**Comment by rok** [comment]
@github-actions crossbow submit preview-docs

**Comment by rok** [comment]
@github-actions crossbow submit preview-docs

**Comment by rok** [comment]
Once docs are built they will be viewable at http://crossbow.voltrondata.com/pr_docs/38665

**Comment by rok** [comment]
I got this building locally with some effort - I used `ninja-debug-python` cmake preset and have the following exports:
```
export PYARROW_WITH_PARQUET=1
export PYARROW_WITH_DATASET=1
export PYARROW_WITH_SUBSTRAIT=1
export PYARROW_WITH_ACERO=1
export PYARROW_WITH_COMPUTE=1
```

Result:
Screenshot from 2023-11-13 02-30-10

**Comment by rok** [comment]
> Revision: [4dfa21a](https://github.com/apache/arrow/commit/4dfa21ace422805ffa1ed4950ba26dcac09a8398)
> 
> Submitted crossbow builds: [ursacomputing/crossbow @ actions-09574f30f3](https://github.com/ursacomputing/crossbow/branches/all?query=actions-09574f30f3)
> 
> Task	Status
> preview-docs	[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/6826798420/job/18567489023)



> Revision: [4dfa21a](https://github.com/apache/arrow/commit/4dfa21ace422805ffa1ed4950ba26dcac09a8398)
> 
> Submitted crossbow builds: [ursacomputing/crossbow @ actions-e79d534cc7](https://github.com/ursacomputing/crossbow/branches/all?query=actions-e79d534cc7)
> 
> Task	Status
> preview-docs	[Github Actions](https://github.com/ursacomputing/crossbow/actions/runs/6825342194/job/18562980166)

@assignUser it seems that AWS CLI binary is not found, is this known or shall I open an issue?
```
/home/runner/work/_temp/760ee02b-fed6-4047-ace0-49260f3fa628.sh: line 1: aws: command not found
```

**Comment by assignUser** [comment]
Hm this is happening outside of the docker container so perhaps the runner image changes and removed it? It's news to me

**Comment by no23reason** [comment]
@rok thank you for the preview and the suggestion! I applied it, I think it is now ready for final review :)

**Review by rok — APPROVED** [review]

**Comment by rok** [comment]
Thanks for doing this @no23reason !

**Comment by no23reason** [comment]
Thank you for your very patient support @rok!

**Pull request merged**
